### PR TITLE
Toggled autosteering

### PR DESCRIPTION
**Pull request by dplepage**
This is an alternative to #314 that makes autosteering behave more like landing, etc. - instead of holding down the autosteer button, you press it once and you will continue autosteering until you manually turn (or activate a different autopilot feature like jumping or landing).

Note that this and #314 now make the Preferences pane look weird - I originally just made the controls slightly taller to fit in the autosteering option, but now the scan button is filling that space and I'm not sure how best to add this to the Preferences without re-rendering the image.

@endless-sky Have you considered using a GUI toolkit like [libRocket](http://librocket.com/) or [CEGUI](http://cegui.org.uk/) so that it would be easier to extend some of the gui elements?

### CODE REVIEW

**Comment by endless-sky** [comment]
The UI elements have a lot of subtle frills that would make it hard for them to be resizable, but I've certainly thought about changing the GUI code so that less of it has to be hard-coded.

The bigger issue, though, is that I already get a lot of complaints that there are too many controls to learn, so I'm a bit hesitant about adding yet another one.

**Comment by dplepage** [comment]
Are experienced players having trouble with the large number of commands, or is it mainly that new players just find the preferences panel intimidatingly large?

One solution would be to make some of these actions available from dialogs instead of requiring keybindings. For example, you'd target a ship and hit a single "inspect" key that pauses the game and pops up a dialog with details about that ship and buttons for "scan", "hail", "board", "have escorts attack this target", etc. Advanced players could still assign keys for those actions so that they wouldn't have to call up that dialog all the time, but new players would have fewer keys to remember. It'd also help that "inspect" would be the obvious thing to do when e.g. you know you need to scan a ship but can't remember how. And this would pave the way for adding more complicated ship interactions without needing to assign key bindings every time.

Also, maybe the `PreferencesPanel` should hide controls that aren't relevant to the current ship. For example, a new player wouldn't have cloaking, afterburners, or fighters, so all of those bindings would be hidden unless they hit some "show advanced controls" button. The options would become visible by default once your ship had appropriate outfits, but by the time you actually have fighters or a cloaking device you're presumably already comfortable with basic steering and firing.

**Comment by dplepage** [comment]
Another advantage of an "inspect" panel would be that it would finally be possible to board disabled neutral ships without shooting them to turn them hostile first - your hotkey would still be shorthand for "board to raid if the target is hostile and board to assist otherwise", but the inspect panel could actually give you both types of boarding as separate options.

**Comment by frameworld** [comment]
If you hide controls, you hide assigned keys and need a free-keys-listing.

I prefer if you could assign keyboard-sections to "press while use", "set context" and "pre-cursor-key, cancel with backspace".

Some commands would require 2 keys, but the number of actions you have to put into random free spots is smaller.
It would be easier to remember a key if it starts with the same letter or be a context and one of 4 belonging to actions of any context instead of having a random position and shape on your keyboard.

**Pull request closed without merging**
