### PR TITLE
feat(enhancement): Dynamic Camera

### PR DESCRIPTION
**Pull request by Koranir**
## Feature Details
Adds a full dynamic camera system to the game. The camera has additional behaviours such as zooming in when landing, zipping off in a hyperjump, zooming out out a jump drive, locking on to targets.

## UI Screenshots

https://user-images.githubusercontent.com/101683475/220801673-79d06ae7-3117-44c7-99db-3b6f3f2af032.mp4

https://user-images.githubusercontent.com/101683475/220835989-71980e1f-6f50-4180-a3c8-9aa6f29f66bc.mp4

## Testing Done
Zipped around a few systems, works as expected :)

## Performance Impact
VERY Minimal.

### CODE REVIEW

**Comment by Saugia** [comment]
I'm going to say this now before we get too far with this - the type of game Endless Sky is based around entirely is having a central camera locked to the ship. Endless Sky is not an RTS, nor are we interested in turning it into or adding elements of those and other such game elements. I'll wait for feedback for others, but that's my stance on this.

**Comment by RisingLeaf** [comment]
Some things:
1. I already have a similar PR, have you looked at it? #7347
2. The art in the game is created to be looked at from a certain zoom, we do not really want to zoom in further.
3. Although I do not fully agree with Saugia, I think we should not have too much camera noise as it does not really fit the game concept
4. Instead of having an all in one PR, try to make minimum viable product PR

**Comment by MasterOfGrey** [comment]
If we did this I would prefer the acceleration offset to be in reverse actually.
If I’m going fast in one direction I want to see *more* space in front of me, not less.

**Comment by Saugia** [comment]
The thing with your PR leaf is it doesn't move the actual location of the camera, it does it retroactively with the dynamic elements of the player's ship. That I'm more willing to debate for. Having an unlocked camera I'm against.

**Comment by Koranir** [comment]
> I'm going to say this now before we get too far with this - the type of game Endless Sky is based around entirely is having a central camera locked to the ship. Endless Sky is not an RTS, nor are we interested in turning it into or adding elements of those and other such game elements. I'll wait for feedback for others, but that's my stance on this.
> 
> Having a locked camera is not a bad thing. It's a design choice. Just because we don't have "insert element another game or other types of games has" doesn't mean we need it, even if it's an option. Endless Sky from the very start is a 2d space game focused around the central player, not the ability to pan through things that aren't the player's ship. A lot of dynamic movement in Endless Sky should remain to special movements such as landing, jumping, etc., and it's a bit undesirable to put dynamic movement in the interface itself, especially with camera movement.

I'm not really detatching the camera from the ship, it is still intrinsically linked, just that I made it feel less static. And I think the locked camera _is_ a bad thing, there is so much lost by having the camera stuck in one place all the time.

> If we did this I would prefer the acceleration offset to be in reverse actually.
>If I’m going fast in one direction I want to see more space in front of me, not less.

Added an option for that, just like RisingLeaf's.

> Thoughts:
> 
> 1. The dynamic movement based on velocity does look good. It lends a strong sense of movement and acceleration into an otherwise static environment. However, it's too extreme right now. Looking at it, it would give me difficulty picking out specific targets when flying around, and I'd get motion sick using it for over an hour or two.
> 2. The camera movement on landing looks good; the zoom-in to the planetary UI is very clean and professional looking and lends a bit of movement to an otherwise completely static scene with zero player input. If nothing else, I would like to see this get in.
> 3. The dynamic movement on jump also looks pretty good and shares the same advantages as landing. However, we should keep the player's flagship as a constant reference point that stays onscreen. Other than that, though, it's good.
> 
> To conclude, I love the camera movement on landing, and I like the camera movement on jumping. However, I prefer the camera acceleration offset that leaf has in his PR for general movement.

Thanks, I increased the camera tracking, and the effect can be toggled off.


> Some things:
> 
> 1. I already have a similar PR, have you looked at it? [Feature/Enhancement: Optional acceleration camera offset #7347](https://github.com/endless-sky/endless-sky/pull/7347)
> 2. The art in the game is created to be looked at from a certain zoom, we do not really want to zoom in further.
> 3. Although I do not fully agree with Saugia, I think we should not have too much camera noise as it does not really fit the game concept
> 4. Instead of having an all in one PR, try to make minimum viable product PR

With regards to zoom, I disagree. We can already zoom in, and at normal levels of zoom it goes to at max only double the zoom in.

**Comment by RisingLeaf** [comment]
> With regards to zoom, I disagree. We can already zoom in, and at normal levels of zoom it goes to at max only double the zoom in.

Yea, but max zoom is chosen so that it shows the ships in the inteded size

**Comment by Koranir** [comment]
> > With regards to zoom, I disagree. We can already zoom in, and at normal levels of zoom it goes to at max only double the zoom in.
> 
> Yea, but max zoom is chosen so that it shows the ships in the inteded size

The ships never actually change size, though.

**Comment by Koranir** [comment]
Okay, I got rid of the camera going off center in normal gameplay.
Not my favourite solution, but whatever, can be added later.

**Comment by Zireael07** [comment]
I must say I <3 the landing and jumping behavior <3

**Comment by Koranir** [comment]
Closing, will split into different PRs (for now, #8450)

**Pull request closed without merging**
