### PR TITLE
Vanguard fix

### LINKED ISSUE #1791: Vanguard hardpoints are off
vanguardfail

### PR DESCRIPTION
**Pull request by jafdy**
#1791

### CODE REVIEW

**Comment by Bladewood** [comment]
Center guns still have some problems.
vanguardfail2
Other than that, you did it!

**Comment by jafdy** [comment]
Chears @Bladewood.

**Comment by DingusShingleton** [comment]
Even still looks off to me. I tinkered with it, and this is looking spot on.

```
	gun 0 -132
	gun -22 -122
	gun 22 -122
	gun -21 -45
	gun 21 -45
	gun -31 -45
	gun 31 -45
```

**Comment by jafdy** [comment]
Some people, never happy.

**Comment by DingusShingleton** [comment]
Hey if we're gonna get it, might as well get it right :P

**Pull request merged**
