### PR TITLE
Library of Alexandria side-story and jobs

### PR DESCRIPTION
**Pull request by W1zrad**
This a reopened and edited version of #4770 by @NomadicVolcano (who has since left the community). See below for the original description:

>## Summary
>This pull request adds a side-story where the player gains a formal relationship with the Library of Alexandria. The player gains permanent access to the library and new library jobs. It is intended for first-time players to reach about the time they finish paying their mortgage. They get a one-time, guided tour of about 1/3 of Human space, led by a senile adventurer. There are tutor-like aspects such as how to jump with a fleet, how to dodge enemies in combat, how to talk to a planet, and how to board a ship to repair it.
>This story and ones to follow, address issue #4907 by providing a place for the player to go for quests that teach and hint. This first story ensures you have Pirate, Free World, and Syndicate systems on your map. You're introduced to side-players like the Quarg, Tarazed Shipyards, possible Alphas, and the Militias. Along the way, you learn skills you'll need soon. You get to see the pirate threats you'll run into, while heavily armed escorts make sure your Shuttle survives. The books you gather tell a story of an ancient explorer in the same situation as yourself. The explorer's actions tell the player that there's a lot more to Endless Sky than trading and transport missions, and provide hints about what is to come.
>
>## Save File
>The best way to test this is to start a new game and try the library mission when it becomes available. It happens after Remembrance Day when you have at least 300k net worth, and it appears in the Job Board within 7 jumps of Earth. It is the "Alexandria Library Card" job.
>For the impatient, here is a save file:
>[Super.Sparrow.revised.mission.top.of.job.board.txt](https://github.com/endless-sky/endless-sky/files/6430958/Super.Sparrow.revised.mission.top.of.job.board.txt)
>You have a well-outfitted Sparrow that has already explored all Human, Hai, and Remnant space. You would get the full effect of the side-story if you start a new game with whichever ship you prefer.

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I uploaded the necessary image, blend, and texture assets here: N/A
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: (In progress)
 - [ ] Fix usage of `fail` to prevent breakage.
 - [ ] Significant changes.
 - [ ] Amazinite's edits.
  
 I've done my usual spelling, grammar, and style edits. There are some things that I think need to be considered:
 1. The original author has stated this was only the beginning of a much larger story involving the Alexandria library. This PR is technically an incomplete story (though it functions well enough by itself to make it to PR form). I'm hesitant to make significant changes because that may close the door on this project's original intent, and because...
 2. Based on the discussion on the original PR, the author was fairly adamant about preserving their vision and writing for this story. Even the small edits to style, spelling, and grammar I've made here may have been refused by the author.

Essentially, I'm concerned that significantly changing the content here could prohibit the original author from finishing their story should they eventually choose to return. Either I stick to NomadicVolcano's work as closely as possible (which would be more or less in this state and probably have a lower chance of being merged), or I decide that because the author abandoned it, it's free reign to take creative liberties. I'd like to understand exactly how much would have to change if I chose the latter option before I make a final decision, so if you want to provide it, I'd appreciate some feedback on which way you think the PR should lean. ~~I plan to take this out of draft form once I've heard others' thoughts on this and decided for myself.~~
Update: Both because of a consensus that I should take creative liberty with the content and discussion with Amazinite, I plan to make some significant changes to these missions. The finished product will be different enough that I don't think this should be considered "ready for review" until those changes have been made; as such, I'll keep this in draft form for the time being.

### CODE REVIEW

**Comment by Amazinite** [comment]
> Either I stick to NomadicVolcano's work as closely as possible (which would be more or less in this state and probably have a lower chance of being merged), or I decide that because the author abandoned it, it's free reign to take creative liberties. I'd like to understand exactly how much would have to change if I chose the latter option before I make a final decision, so if you want to provide it, I'd appreciate some feedback on which way you think the PR should lean.

I would say that the work is open to any changes. People contacted Nomadic about picking up the pieces that he left behind, and as far as I can tell he didn't display any issue with people working on what he had left behind. And seeing as how we're closing in on a year since the closing of the original PR, I'm not too keen on holding back our changes in the hopes of Nomadic returning to finish what he started, not even bringing into question whether the direction he was going in was something I would have approved in the first place.

From what I recall, the mission structure of this PR was rather sloppy, unnecessarily using `fail` and repeatedly running into #1938 when the mission structure could easily be reshaped to not require the use of `fail`, or at least not so often, and therefore not break as a result of #1938. So to that end, simple grammar and style changes in the conversations won't be enough to have this PR in a mergeable state.

**Comment by Zitchas** [comment]
NomadicVolcano was pretty adamant about disavowing any further participation, even going so far as to "burn" their email and other lines of communication. So I wouldn't be too concerned about making changes.

**Comment by Amazinite** [comment]
I think akin to #5111, I might have to do my own total restructuring of these missions, making my own changes along the way. I'd then PR my changes to your branch for approval, for as far as I'm concerned, this is your project now, Wizrad.

Given that I want to involve myself in editing this though, this will absolutely be sitting around for a while. There are already a number of v0.9.15 marked content PRs that have been opened before this (although thankfully many of them are more on the minor side), not to mention I already have my own plans for content I want to work on for v0.9.15. I'll tentatively mark this PR for v0.9.15 as well, but I can't guarantee that I'll get to it in that time.

**Comment by MasterOfGrey** [comment]
Right off the bat the mission structure doesn't make an abundance of sense to me and I'm unsure how it's meant to work. So yeah, I think we can safely say it might need some re-working.

Having said that, the added jobs actually seem really cool, so I would certainly appreciate the kinks getting worked out of this to the point of making it playable.

**Comment by W1zrad** [comment]
It looks like the consensus so far is that the content should be open for adjustments since the author's made a pretty clean break. I'll look into the usage of `fail` and try to fix that up first.

> Given that I want to involve myself in editing this though, this will absolutely be sitting around for a while. There are already a number of v0.9.15 marked content PRs that have been opened before this (although thankfully many of them are more on the minor side), not to mention I already have my own plans for content I want to work on for v0.9.15. I'll tentatively mark this PR for v0.9.15 as well, but I can't guarantee that I'll get to it in that time.

@Amazinite this sounds good to me. I'm in no rush and you've obviously got some stuff of your own going on, so I'll just upkeep this and address reviews/suggestions till you're set to swing around to it.

**Comment by W1zrad** [comment]
I'm planning to make some significant changes to this content after discussing with others. For the time being, I think it's appropriate to close this to get rid of clutter, especially considering I'm not currently working on it. Expect this to be reopened in (hopefully) a couple months when it's closer to a finished state.

**Comment by Zitchas** [comment]
I will look forward to seeing how it is after the revisions. It definitely has been interesting so far.

**Comment by W1zrad** [comment]
Quick update: Going to keep this closed. I've got a rough draft done, but I'm struggling to make this feel like something interesting rather than just more "stuff", especially in a place as content-saturated and fleshed out as the Deep. Someday I might swing around to this again, but for the time being I'll be moving onto some other stuff. Thanks for following along!

**Comment by Zitchas** [comment]
Worth noting that a lots of people consider the deep rather empty and un-populated, and in need of stuff for people to do while they stumble across the main stuff leding to the Bactrian missions.

**Pull request closed without merging**
