### PR TITLE
added Skeins to Dreadnought deployment

### PR DESCRIPTION
**Pull request by LocalGod79**
addressing #1711

### CODE REVIEW

**Comment by endless-sky** [comment]
It seems weird to me that a Free Worlds fleet (which is essentially a militia patrol) would have Boxwings in place of combat-capable ships.

**Comment by LocalGod79** [comment]
Governments need to move cargo too, right?

when i implemented the Boxwings into the FW Large fleets, I reasoned that the Free Worlds would have cargo to move from time to time, and the Skeins were flexible enough to provide some efficient/secure cargo movement (also demonstrating this flexibility).

that said, a pair of Skeins fully loaded with Finches is a force to be reckoned with, and balancing was also a consideration.

**Comment by endless-sky** [comment]
My concern is that when they attack pirates, the Skeins will automatically drop the Boxwings along with the fighters, which would be really odd behavior since the Boxwings are helpless.

**Comment by DingusShingleton** [comment]
That was the major drawback I discovered when I made my fighter-using captain. There's no way to launch fighters selectively, so if you actually want to use fighters offensively, boxwings become kind of useless. Not sure the best way to fix it, or if it's really even important enough to need a fix.

**Comment by Amazinite** [comment]
@DingusShingleton #868

**Comment by DingusShingleton** [comment]
For the time being, perhaps the simplest solution would be to just set bowxings to never deploy at all? I think the benefit gained (that is, actually being able to use them) would outweigh any situation where a player might want to deploy them for whatever reason. Unless there's some reason that I'm just not seeing...

**Comment by Amazinite** [comment]
Something that @LocalGod79 originally suggested was to use them as meat shields; convert their cargo to outfit space and pack them with shield generators and you've got yourself a little shield.

**Comment by LocalGod79** [comment]
actually, i had intended it as a compromise solution to folks asking for the ability to "wall up fighter bays for more cargo/outfit space", which was always a non-starter.

one suggested combat role for the Boxwing was as a meat shield, but that strategy is prohibitively expensive (though may still find a role yet, as the game grows).

that said, if i had an Aerie with a pair of Boxwings in it doing cargo missions, i would want to "temporarily dump my cargo" to turn my flagship into a nimble warship when the opportunity to capture an interceptor appeared...thinking on it as a fleet tactic, this could be very effective...

**Pull request merged**
