### PR TITLE
Republic standby fleet has been launched in Sol

### PR DESCRIPTION
**Pull request by wkoot**
The Republic is in panic. Makes sense to have a standby fleet in Sol?

### CODE REVIEW

**Comment by endless-sky** [comment]
This seems to have changes from your other pull request included with it. Also, it might make sense to just have a bunch of "Large Republic" fleets in the NPC rather than spelling out what ships are in the fleets - they're just for show, so the exact ships don't matter.

**Comment by wkoot** [comment]
Crap I thought it was diffed from the endless-sky master branch. I'll try to graft it from the earlier commit

**Comment by endless-sky** [comment]
Doesn't this change make that mission unwinnable unless you kill all the Republic NPCs, because you marked them as an NPC that you must "evade," and they are occupying Sol?

**Comment by endless-sky** [comment]
I've added a defense fleet in commit 748eaf1 as you suggested, but without the "evade" trait.

**Comment by wkoot** [comment]
cool, tnx

**Pull request closed without merging**
