### PR TITLE
Make Hai not hostile to the Unfettered by default

### PR DESCRIPTION
**Pull request by temtemy**
In this PR, the regular Hai will only be hostile to the Unfettered when the latter attacks them. The Hai should only attack for self-defense. If the Hai attack the Unfettered before the latter do, then it is contradicting their claim that they are a peaceful race. And I don't think that the regular Hai would like to kill each other.

### CODE REVIEW

**Comment by endless-sky** [comment]
It doesn't actually work that way - if either government is hostile toward the other, they'll fight if they encounter each other. The choice of what attitude each government has toward the other just affects how much your reputation changes for disabling or killing a government's allies or enemies. (And in this case, the negative attitude makes it so that if you disable an unfettered ship, you'll be able to land on Hai-home without bribing them.)

**Comment by temtemy** [comment]
Oh, didn't knew about that (maybe it would be possible to code that?). But I don't think the regular Hai will like you for killing their brothers in the north though. It is also still possible to increase your reputation without killing some Unfettered, like repairing Hai ships in Wah Ki and finishing the "Wanderers: Hai Diplomat" mission.

**Comment by KiLEdEnNis** [comment]
if a government would always be attacked by another one, naturally they're not gonna keep waiting to take the first hit
and the Hai don't "like" that you kill the Unfettered, but they don't really "mind" either as they know the Unfettered are the ones who get themselves killed

but in short, this PR isn't really necessary, the intended effects are already met

**Comment by temtemy** [comment]
I don't see any chance for this PR to be merged, so closing.

**Pull request closed without merging**
