### PR TITLE
Miscellaneous grammar in data/human/

### PR DESCRIPTION
**Pull request by NRK4**
## Summary

- Made the verb tenses consistent in one spot in the boarding missions file
- Changed an "on to" into an "onto" in the deep missions file
- Changed an "in to" into an "into"
- "lead" -> "led" to match tense
- "so called" -> "so-called"
- "mean time" -> "meantime"
- Removed a duplicate "that"
- Moved a misplaced comma
- "get recorded voice message" -> "get a recorded voice message"
- "You are brought to large research complex" -> "You are brought to a large research complex"

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
I’m pretty sure the “onto” should stay “on to” because it’s a figurative phrase where you don’t actually put things “on” to the object in question.

I’d also raise a question mark over “so-called”. That’s not usually hyphenated in my experience.

Everything else looks good.

**Comment by Zireael07** [comment]
Seconding that I haven't seen "so called" hyphenated (English major, however, non-native)

**Comment by ravenshining** [comment]
I usually see it hyphenated

**Comment by Zireael07** [comment]
Might be a US vs UK thing? Does ES even specify which variant is used?

**Comment by ravenshining** [comment]
No, digging into it a bit, "so called" and "so-called" are different phrases.  Here, it is appropriate to hyphenate as they form a compound adjective.  You would omit the hyphen in a different context where they do not combine into an adjective, e.g. "Quantum keystones, so called because of their ability to wedge open a quantum structure..."

**Review by Zitchas — APPROVED** [review]
These look like good corrections. Thanks for the fix!

**Comment by Zitchas** [comment]
Pulling from Mirriam and Webster's examples:

> Definition of so-called
> 
> 1 : commonly named, ex: the so-called pocket veto
> 2 : falsely or improperly so named, ex: deceived by a so-called friend

**Review by roadrunner56 — APPROVED** [review]

**Review by TheMarksman-ES — APPROVED** [review]
Aside from the points raised by Grey, the rest of the errors were left in-game for some time. Good work.

**Pull request merged**
