### PR TITLE
Issue 798

### PR DESCRIPTION
**Pull request by jmhorjus**
* Boarding missions behave the same when using keyboard or mouse to trigger dialog nodes.
* Add mission keyword for "defer + leave location" currently called "depart". 
* Allow "on defer" mission callback, triggered by "defer" or "depart".
* Make sure "flee" triggers "on decline" callback correctly. 
* Includes changes allowing planets to define a government if they want.

### CODE REVIEW

**Comment by jmhorjus** [comment]
Sorry some automatic whitespace cleanup also got into one file - I can undo those if desired.  I realize that "depart" may be a bit controversial. Any comments would be welcome.

**Comment by endless-sky** [comment]
This seems to be merged with your pull request for planets specifying their own governments, and the whitespace changes are also a bit distracting. Those extra changes make it a bit hard to read through and see what is specifically necessary for the "depart" code.

**Comment by jmhorjus** [comment]
Ok, cleaned up the branch, put back all the tabs, and merged up with the current master.  
The depart functionality is primarily handled with the simple "Conversation::LeaveImmediately" function, besides just adding it to the enumerations.

**Comment by endless-sky** [comment]
Sorry for the delay in merging this - got caught up with other stuff. But this looks good, and it seems you fixed some other bugs in the process. Thanks!

**Pull request merged**
