### PR TITLE
Updated Firebird description

### PR DESCRIPTION
**Pull request by warp-core**
Changed 'nearly half a millenium ago' to 'over half a millenium ago' to better reflect the game history.

### CODE REVIEW

**Comment by Admiral-Danforth** [comment]
Using "around" would be better. It represents more of a general sense instead of a date set in stone.

**Comment by Amazinite** [comment]
Well your character moves through time, so "over half a millenium ago" will always be true, while "around" will not.

**Comment by Pointedstick** [comment]
"Many decades ago" could also convey a sense of age and always be valid.

**Comment by KiLEdEnNis** [comment]
@Amazinite what if in-game you play so much that 1000 years passed? would be over half a millenium but also over one and a half millenium

**Comment by Amazinite** [comment]
So? Over half still remains true, no matter how many other statements are true as well. 
And I like the "many decades ago" idea, but maybe change it to "centuries."

**Comment by Bladewood** [comment]
"Centuries ago"?

**Comment by KiLEdEnNis** [comment]
well, technically speaking, if you edit your save file to like the year 1200 nothing would make sense, so it's fine either way

**Comment by warp-core** [comment]
I'm torn between 'many centuries ago' and 'over half a millenium ago'.
I'm just going to let MZ decide.

**Comment by KiLEdEnNis** [comment]
@warp-core or vote; each upvote is "many centuries ago", each downvote is "over half a millenium ago"
I'll start then :P

**Comment by Amazinite** [comment]
> well, technically speaking,

that doesn't apply because it's messing with the game. If you were to design a game for everything to always be true no matter how much players change it, then those players must have very little options of what to change.

**Comment by KiLEdEnNis** [comment]
@Amazinite I'm aware of that lol, if you mess with the game you can't complain about errors that appear

**Comment by Pointedstick** [comment]
"Centuries ago" seems best to me.

**Comment by Bladewood** [comment]
Now that I think about it, "over half a millennium ago" sounds pretty weird. "More than half a millennium ago" sounds a bit better.

**Pull request merged**
