### PR TITLE
feat(content): Add Split-Quarg governments to Heliarch Relations

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR adds each Quarg government that was split in https://github.com/endless-sky/endless-sky/pull/8561/files#diff-52ab6c2e7dd87148c178b0cb37499256a21fa460b750065a596d6cce76b0e3ac to the Heliarch's relationships, so that they are properly fired upon should they ever find themselves in Coalition space (see the Wanderer missions that give the player Quarg escorts).

## Save File
N/A

### CODE REVIEW

**Review by Arachi-Lover — APPROVED** [review]

**Review by lumbar527 — APPROVED** [review]
Makes sense, but should the Quarg governments be hostile as well?

**Comment by Saugia** [comment]
This PR fixes the missing hostilities from the Heliarch's side. The Quarg have have never themselves been hostile to the Heliarchs, and that can be brought up elsewhere with Arachi as I'd imagine the Coalition Campaign may adjust the Quarg - Heliarch relations.

**Comment by lumbar527** [comment]
OK, I was just used to, in general, both governments having reputation towards each other.

**Comment by Quantumshark** [comment]
Gameplay-wise, as long as one side has a negative attitudes towards the other they'll both attack each other on sight. The only reason why you'd need to add it from both sides is if you were using attitudes greater than .05 or less than -.05, which cause player reputation to change when killing the other government. Since we don't want players to be able to farm heliarch reputation by killing Quarg ships, or vice versa, it doesn't matter if only one side has the attitude.

**Review by W1zrad — APPROVED** [review]

**Pull request merged**
