### PR TITLE
Gkramme patch 1

### PR DESCRIPTION
**Pull request by Gkramme**
Still cannot update my master...

### CODE REVIEW

**Comment by Gkramme** [comment]
How do you update your master?

**Comment by Wrzlprnft** [comment]
1. https://help.github.com/articles/configuring-a-remote-for-a-fork/
2. https://help.github.com/articles/syncing-a-fork/
3. and `git push origin master`

**Comment by Gkramme** [comment]
Thanks. I don't think I can do this on my iPad tho.

**Comment by Wrzlprnft** [comment]
you could delete your fork, and re-fork it. That's the only thing i found out in the web-interface. But you may loose changes and get conflicts with local residues of the old repo.

**Pull request closed without merging**
