### PR TITLE
Docs(manual): Add a reference to the player's manual in the credits.

### PR DESCRIPTION
**Pull request by hmglasgow**
**Feature:** This PR implements the feature request detailed and discussed in issue #7583

## Feature Details
Although PR #7958 is adding Loading Hints to the start up, it would also be useful to point players towards the wiki manual.

## Testing Done
Starting the game displays the updated credits including the link to the player's manual.

### Automated Tests Added
N/A

## Performance Impact
N/A

### CODE REVIEW

**Review by Zitchas — APPROVED** [review]
Yeah, that looks good to me too; although it may be more useful to direct people to the much shorter web address, and suggest that they look at the link on the side:

endless-sky.github.io

**Comment by hmglasgow** [comment]
That make better sense, as there's more there than just the manual. I'll update the change.

**Review by Zitchas — APPROVED** [review]
That looks good. And also much easier to remember/type.

**Comment by quyykk** [comment]
The website is already mentioned in the paragraph below though.

**Comment by Zitchas** [comment]
It agree that it is not the cleanest to have that duplication, but it *is* the clearest in terms of communication. The players that most need to read the manual are the newest ones who probably aren't invested enough to care at all about:

> To report bugs, give feedback,
> or contribute to story writing,
> artwork, or programming, visit:

Having this entry specifically telling them that there's a manual and other resources at this site is clear and to the point, and unencumbered by all this other stuff that a new player probably isn't interested in yet, and thus more likely for them to remember specifically that there's a manual there.

As such, while the duplication isn't great, it is probably better for uptake than, for instance, merely expanding that little blurb to include references to a manual.

**Pull request merged**
