### PR TITLE
Organizing game data into subfolders (#2125)

### PR DESCRIPTION
**Pull request by Amazinite**
This PR organizes game data into 10 subfolders:
Coalition
Drak (which includes indigenous)
General (stuff that isn't related to a single species like landing messages or the map)
Hai
Human
Korath
Pug
Quarg
Remnant
Wanderer

I removed the jump drive, scram drive, and hyperdrive from outfits.txt and gave them their own file in general. I also removed the Pug and Quarg names, fleets, and hails from the mostly-human files and put them into their respective folders.

Addresses #2125

**To consider:** Remove prefixes from file names? i.e. Every file in the Korath subfolder doesn't need to be prefixed with "korath" when the folder itself labels them all such anyways. I've made this a seperate commit so that it can be reverted if desired.

### CODE REVIEW

**Comment by Elyssaen** [comment]
I've gone to make a comment on this a few times, and honestly I just keep changing my mind about whether this would make it easier for me or harder.

So, there's only one way I can be sure: trying it out. I'll stick your changes in the copy I play for a bit, and will let you know how the experience is.

Removing prefixes like "korath" is probably worth doing, as typing `data\korath\korath missions.txt` in the command line is going to get tiresome quickly.

**Comment by tehhowch** [comment]
If you're tab-completing from korath, it'll jump up as far as it can.. e.g. if every file in korath/ is "korath ____" you'll tab to `korath/korath\ ` and just have to type the rest of the specific file, just as though none of the files started with "korath "  :+1: 
If you're not tab-completing when typing directories... why. why do such a thing to yourself. Tab is a big key, it's pretty easy to press.

**Comment by Amazinite** [comment]
I guess this is going to have conflicts whenever a data file is changed.

**Comment by Amazinite** [comment]
¯\_(ツ)_/¯

**Comment by Elyssaen** [comment]
At the moment I'm finding it a little frustrating that map and governments aren't in the data folder. I think it's worth talking about whether `data/general` is needed vs. keeping those files in the `data` root.

I'm changing my mind about prefixes as I keep looking at files in Notepad++ that are all called weapons.txt.

Also, I know it doesn't precisely fit the structure you've set out, but on my copy I've just gone and made a `free worlds` folder and chucked the campaign missions in there. I've found that the most helpful change. Those, and Deep / Paradise Worlds / Syndicate jobs, are the ones that most bother me personally.

How's it been working out for you in play, @Amazinite?

**Comment by endless-sky** [comment]
I'm not convinced that this is useful. At least for my own workflow, it's more convenient to have a flat file structure so I can just grep data/* when I'm looking for something.

**Comment by Amazinite** [comment]
Having everything in subfolders certainly feels a lot better to me, especially for anything human or general related since those aren't clumped together in the current system like they would be in subfolders.
I wouldn't be against axing the general folder and leaving all that stuff in `data/` while everything else is organized, because in the end the general stuff still get clumped together nicely.
I don't know exactly how it is that you're browsing files that makes this a more difficult/less usable system, but for most of us who have something like a shortcut to the data folder on out desktop this is a much better organization structure (hence why there was so much support on #2050 and #2125 from content creators).
If this system doesn't work, then I'd at least like to revisit the idea from #2050 and prefix human related files as such, because then the only files that aren't clumped together by purpose are the general ones, and they'd end up being easier to pick out anyways just because of the fact that they'd be the only unprefixed files.

@Elyssaen For those job folders, what do you think about just putting them into the existing job file and using comments to label where general or regional jobs are?

**Comment by KiLEdEnNis** [comment]
bigger real games also have organized folders, and since Endless Sky is getting more and more data files, it gets very cluttered and hard to navigate through
the "general" files might as well stay in the direct data folder, but each species should be put in a folder of their own (including humans)
you can still easily find something you're looking for in windows explorer or whatever in the data folder as it'll search those folders

I really think this should happen

**Comment by jafdy** [comment]
I would rather see them being grouped by using a word in front than put into subfolders. I like to have all the files side by side so I don't need to have multiple widows open or have to back down every time I want to change species.

**Comment by Elyssaen** [comment]
Prefixing some files with `human ` seems an inoffensive enough fallback. I can't be the only person to periodically forget about the engines and power files, and since I've trained my brain to ignore the "f" part of the list (the seven Free Worlds files) engines has become a bit invisible.

The tricky problem here is that while @Amazinite's/@MessyMix's sort method has the best logical meaning, _sometimes_ it doesn't reflect what you're doing. Maybe MZ or other contributors are just looking across Coalition files for a bit. In that case, great. But if you're looking across _ships_, this scheme seems to make it a little harder.

It's why I've reverted it on my copy for now. Felt like it was taking more time, not saving time. 

But I left my tweak of `data/free worlds/*`, because I find campaign files genuinely are things I either want to look at together, or have out of the way. On combining the jobs file, not sure: I'm away from my computer right now and it's really just a question of file length.

**Comment by Amazinite** [comment]
[Here](https://github.com/Amazinite/endless-sky/tree/organizationTake2/data) is a branch showing what the prefix organization would look like. 

@Elyssaen The regional jobs, when added to the jobs file, only take up like 1/5th of the space in the file, so it isn't a very big increase in size.

**Comment by Pointedstick** [comment]
Definitely more useful for me. You can grep almost as easily by just using the -r flag:

`grep -r data/*`

**Comment by Lineth** [comment]
I've not as much of a horse in this race, but the subfolder idea does sound better than the current system.

**Comment by Amazinite** [comment]
Given that the conflicts of this PR are just going to grow with every change to the data folder (and I have no idea how to fix them), I'm just going to leave the actual changes to @endless-sky.

**Comment by MessyMix** [comment]
I don't see how navigating folders would be any harder than navigating files; the only thing is, instead of typing a space, it would be a slash, i.e. `data/korath weapons.txt` vs. `data/korath/weapons.txt`. I'm totally for subfolder organization, because I don't see how typing a slash instead of a space could make _that_ much of a difference.

**Comment by Amazinite** [comment]
Closing this PR; the issue related to this is still open and this PR isn't getting merged.

**Pull request closed without merging**
