### PR TITLE
fix(typo): Fix copyright

### PR DESCRIPTION
**Pull request by tibetiroka**
This PR fixes a double space in the standard copyright header, which has been copy-pasted into just about every single file. As discussed with Derpy, this change shouldn't cause any legal issues with the license.

I also have a [PR open in the endless-sky.github.io](https://github.com/endless-sky/endless-sky.github.io/pull/30) repository that fixes the same issue in the example copyright in the C++ Style Guide, which may have been the root of this issue.

### CODE REVIEW

**Comment by Zitchas** [comment]
What are the odds that this was just copy-pasted from an official legalese template from the GPL source or something? Does that make a difference as to whether or not we leave it or remove it?

**Comment by quyykk** [comment]
It might also be worth investing the use of SPDX identifiers instead of that block of text.

**Comment by tibetiroka** [comment]
> What are the odds that this was just copy-pasted from an official legalese template from the GPL source or something? Does that make a difference as to whether or not we leave it or remove it?

Derpy found a version without the double space [here](https://gist.github.com/ilg-ul/aa6de96c993719667f07). Also, as far as I know, these headers are not defined by the license. There are many different versions on the internet, some of them with double spaces.

According to the [guide on gnu.org](https://www.gnu.org/licenses/gpl-3.0.html#howto), the exact text of the license doesn't really matter, as long as it contains a copyright line and a pointer to the full license. In their example, there indeed seem to be two spaces. At this point, though, we should worry about the missing `If not, see <https://www.gnu.org/licenses/>.` sentence, that might actually be required here.

Maybe we should just copy-paste that template or something, can't really go wrong with that one.

**Comment by tibetiroka** [comment]
All done, now the copyright headers match the GPL guide.

**Comment by Amazinite** [comment]
I'm just gonna take it on faith that all 453 files look good cause there's no way I'm manually checking all those. 4 additions * 453 files = 1,812 additions, and 1 deletion per file is 453 deletions, so the numbers check out with what GitHub tells me.

**Pull request merged**
