### PR TITLE
Quarg Wardragon Classification Fix

### PR DESCRIPTION
**Pull request by McloughlinGuy**
Fixes the error in which the quarg wardragon is classified as a heavy warship

-----------------------
**Bugfix:** This PR addresses issue #5830

## Fix Details
I swapped out the word heavy for light in the classification.

## Testing Done
I modified the sales file so that the basic ships category included the wardragon. I then chekced to see if my fix worked, and it did work.
## Save File
[Blue Susatonia.txt](https://github.com/endless-sky/endless-sky/files/6361230/Blue.Susatonia.txt)

-----------------------
**Feature:** This PR implements the feature request detailed and discussed in issue #{{insert number}}

## Feature Details
It changes the classification.

## UI Screenshots
N/A (won’t load)

## Usage Examples
Currently N/A

## Testing Done
I added the Quarg Wardragon to the sales file under basic ships, so I could see if the change worked. It did.

## Performance Impact
N/A

### CODE REVIEW

**Comment by McloughlinGuy** [comment]
note: I forgot to put a title

**Comment by MCOfficer** [comment]
You can edit titles
image

**Comment by McloughlinGuy** [comment]
Thanks

**Comment by ravenshining** [comment]
-`quarg ships.txt` needs to live in the `data/quarg/` folder, you have it in the root folder which results in this PR making two copies of the file.
-  I didn't see any discussion on #5830 as to where to put it.  The Wardragon seems too heavy and too full of turrets to class as a light warship to me, personally I'd go for a compromise solution and change both title *and* description to class it as a medium warship.
- If the Wardragon is downcategorised, the Skylark should be, too, as they are nearly identical ships

**Comment by Arachi-Lover** [comment]
The thumbs down is in reaction to the second point only.
The Quarg are going to be rebalanced at some point, and as I see it the changes made in # 3665 bring down the Wardragon to pretty much about where it should be as a T3 LW, and since then the various buffs to the Heliarchs should make it so a Punisher beats a Wardragon, which I believe should be the case, given it's only half a tier below it, so it should be more than a "match."
Continuing with that, I think Punishers should still pose some trouble to Quarg MWs imo, but should not be capable of beating them alone, and should be completely outmatched by a Quarg HW.
As for turrets, the Met Par Tek 53 has a total of six turret mounts and three gun ports, so even though it is an automated ship, there's precedent for LWs with many turrets, and I'd say it's reasonable to assume it could still function with four turrets, were it not automated (as in losing all gun ports and two turret mounts to compensate for the crew's living quarters, more than half the hardpoints and whatever mechanisms would be in place to allow guns and turrets to be equipped in them).

**Comment by McloughlinGuy** [comment]
The skylark should be changed to a medium warship, as it is roughly the same as the arfecta in size and strength. I did a test once, and found that the arfecta and skylark have equal strength.

**Comment by McloughlinGuy** [comment]
On second thought, changing classifications is something for another issue.

**Comment by McloughlinGuy** [comment]
> 
> 
>     * `quarg ships.txt` needs to live in the `data/quarg/` folder, you have it in the root folder which results in this PR making two copies of the file.
I don't know how to fix that.

**Comment by Amazinite** [comment]
Aside from the fact that this PR is improperly formatted, I'd really rather not hassle with the categorization of Quarg ships. They've admittedly been just placeholders for many years now and we plan to eventually completely overhaul them. Until then though, there's really no use in fiddling with their stats in any way.

**Pull request closed without merging**
