### PR TITLE
Brighten some gov colors to improve map readabilty

### PR DESCRIPTION
**Pull request by TomGoodIdea**
## Summary
Increased color brightness of Gegno, Scin, Vi, Kor Mereti and Kor Sestor governments to make them more distinguishable on the map.
## Screenshots
Current colors:
current
Updated colors:
brightened
## Additional notes
Brightness change is x1.33, but waiting for feedback.

### CODE REVIEW

**Comment by Saugia** [comment]
While I could probably deal with the Gegno and Scin colors, the Vi ones are becoming too pink to me. Their original darker shade is kind of desired, and I don't see a problem with it especially if you compare it to the dark blue human colors, they're almost the same brightness.

**Comment by TomGoodIdea** [comment]
Revert Vi:
vi

**Comment by Saugia** [comment]
Yeah that's fine. As much as I'd love for those to be brown, brown would be too dark, and brightening it up wouldn't make it brown anymore, just tan like the regular Gegno.

**Review by Saugia — APPROVED** [review]
Looks good. I was gonna say something about the Korath ones being a tad bit too pinker now, but if placed back to red, it might be too close to pirate systems.

**Pull request merged**
