### PR TITLE
"pragmatic" personality to work around bug in retreat logic

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Feature:** Adds a *pragmatic* ship personality that works around a major bug in the ship retreat logic.

*Edit: My previous reasoning was backwards, but the consequence is still the same.*

## Feature Details

Here's the bug: when a non-escort ship is severely damaged and wants to retreat, it won't retreat if it has disabled its current target. That means:

1. Several ships are shooting at me, but I've disabled my hostile target.
2. I don't flee because my hostile target is disabled.
3. Now that my target is disabled, I pillage it or select a new target.
4. Other ships are still shooting at me, so I die.

You know all those pirates and Korath who are willing to give their lives just to finish a fight? This bug is the reason.

~~Long-term, the fix is to remove the section of code responsible for this. However, that would require retuning *the entire game*. Instead, I'm adding a personality as a workaround, which will let us remove the bug piece-by-piece.~~

*Edit: The consensus seems to be that, if I am right about this bug, then it should be fixed instead of worked around. However, there is no consensus yet on whether I'm right. I'd like to reach a consensus on the bug vs. no question before opening another PR.*

## UI Screenshots
N/A

## Usage Examples
Korath ships will escape from fights when being swarmed by pirates and Syndicate, instead of volunteering themselves as shooting practice and a source of high-tech outfits.

## Testing Done
Turned on "pragmatic" for Korath Raid, Korath Mining, and Korath Large Raid fleets, and was amazed by the difference.

### Automated Tests Added
N/A

## Performance Impact
negligible

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
If people prefer I fix the bug, I can open a PR for that. Just keep in mind that we'll have to re-balance all of Endless Sky after fixing this bug.

**Comment by Hurleveur** [comment]
I'd prefer to fix the bug for sure honestly
Cowards still run away because they clear the target though?

**Comment by EjoThims** [comment]
I frankly don't see how not suiciding after already deciding to flee will require retuning much of anything at all, much less everything in the entire game.

Even if that is the case though, directly fixing that would (as long as the interaction there is indeed unintended) will still be preferable to just creating a single case of working around it.

**Comment by quyykk** [comment]
The comment now reads:

> Run away if your hostile target is not disabled and you are badly damaged, unless the ship is pragmatic enough to realize disabling one more ship isn't worth dying for.

which contradicts itself, but maybe it's just me.

The code change is incorrect for pragmatic ships with the `fleeing` personality, those will simply always flee no matter what. Also you say this:

> it won't retreat until it has disabled its current target (if the target is hostile)

where exactly does that happen? If the current target is hostile and not disabled, it tries to flee. That's what the current code does, and it seems correct to me?

**Comment by warp-core** [comment]
I have to agree with quyykk, both the existing comment and code that you are changing suggest to me a ship will actually *only* flee if its current hostile target is *not* disabled, not that it will wait until that target is disabled.
Also, I have frequently seen Korath ships jump out of the system when I am the only ship hostile to them there (and I am not disabled), so it's not possible for them to have disabled "one last ship" before leaving, and yet they still left.

**Comment by UnorderedSigh** [comment]
> only flee if its current hostile target is not disabled, not that it will wait until that target is disabled

I agree with that, but I am still right about the consequence because what happens is this:

1. Several ships are shooting at me, but I've disabled my hostile target.
2. I don't flee because my hostile target is disabled.
3. Now that my target is disabled, I pillage it.
4. Other ships are still shooting at me, so I die.

Sure, if only one ship was shooting at you, the logic would work. It doesn't work when you are being swarmed, and that is how Korath die.

**Comment by UnorderedSigh** [comment]
> code change is incorrect for pragmatic ships with the fleeing personality those will simply always flee no matter what

I thought that is what they were supposed to do. What, exactly, is the fleeing personality intended to do?

**Comment by UnorderedSigh** [comment]
> Cowards still run away because they clear the target though? idk it just seemed to me that ships often do run away, not sure

Yes, but not always. That's the part I haven't worked out yet. There are details of the target selection algorithm I don't understand yet.

**Comment by UnorderedSigh** [comment]
The consensus seems to be that, if I am right about this bug, then it should be fixed instead of worked around. However, there is no consensus yet that I'm right. I'd like to reach a consensus on the bug vs. no question before opening another PR.

**Comment by UnorderedSigh** [comment]
Could other people please evaluate this and conclude what it does?

```
                if(!it->IsYours() && shouldFlee && target && target->GetGovernment()->IsEnemy(gov) && !target->IsDisabled()
                        && (!it->GetParent() || !it->GetParent()->GetGovernment()->IsEnemy(gov)))
                                                Flee()
                else
                                                DoNotFlee()
```

Keeping in mind short-circuit logical operators, and de Morgan’s Theorem, and the rule of double negation, is this what it does?

```python
if(it is your ship)
  DoNotFlee()
else if(it does not want to flee)
  DoNotFlee()
else if(it has no target)
  DoNotFlee()
else if(the target is not an enemy)
  DoNotFlee()
else if(the target is not disabled)
  DoNotFlee()
else if(the ship has a parent that is its enemy)
  DoNotFlee()
else
  Flee()
```

If so, I *think* this means @quyykk is correct.

I am 100% certain someone needs to learn about "else if" chains and methods.

**Comment by quyykk** [comment]
> else if(the target is not disabled)

this should be "else if(the target is disabled)`, because you're negating `!target->IsDisabled()`

**Comment by quyykk** [comment]
> Other ships are still shooting at me, so I die.

This should happen for a single frame only, no? I would assume that it takes just one frame for the AI to pick a new target. But I might be wrong.

**Comment by UnorderedSigh** [comment]
> This should happen for a single frame only, no? I would assume that it takes just one frame for the AI to pick a new target (and so for the ship to flee). But I might be wrong.

The other ships will keep shooting at you regardless of what you do. The only exception is if you got into the Flee() block *and* the shooter is merciful.

**Comment by UnorderedSigh** [comment]
> I would assume that it takes just one frame for the AI to pick a new target (and so for the ship to flee).

If the target is a friend or disabled, it will stay.

**Comment by quyykk** [comment]
> If the target is a friend or disabled, it will stay.

I'm pretty sure every ship prioritizes hostile targets over friendlies. So if there is a hostile ship in the system and it needs a new target, it'll target it 100% of the time.

**Comment by UnorderedSigh** [comment]
I *think* this is the correct logic:

```python
if(it is your ship)
  DoNotFlee()
else if(it does not want to flee)
  DoNotFlee()
else if(the ship has a parent that is its enemy)
  DoNotFlee()
else
  Flee()
```

The part about an enemy parent ensures that npc hunting the player will not flee when they found her.

**Comment by quyykk** [comment]
Ships with `fleeing` will then always flee.

> What, exactly, is the fleeing personality intended to do?

it shouldn't flee if there is no hostile in the system. If there is one then yes it flees.

**Comment by UnorderedSigh** [comment]
> I'm pretty sure every ship prioritizes hostile targets over friendlies. So if there is a hostile ship in the system and it needs a new target, it'll target the hostile 100% of the time.

What if the hostile is disabled? Or, what if it keeps its current disabled target and pillages it? Or, what if it waits a few frames before deciding to change targets?

This is where I'm not completely certain. The behavior is inconsistent, so I need to read the targetting logic more.

However, I do believe that reducing to my suggested logic else if chain is correct.

**Comment by UnorderedSigh** [comment]
> it shouldn't flee if there is no hostile in the system. If there is one then yes it flees.

I'll have to add more to the logic for that to work. I will ponder this before submitting a PR.

**Comment by UnorderedSigh** [comment]
Apart from the trouble with the *fleeing* personality, do I have any errors in my suggested "else if" chain?

**Comment by quyykk** [comment]
> What if the hostile is disabled?

Disabled ships get deprioritized as well.

> Or, what if it keeps its current disabled target and pillages it?

I believe they those ships still prioritize not disabled targets. If not, and a hostile ship comes into range they will switch again.

> Or, what if it waits a few frames before deciding to change targets?

That's fine? It waits a maximum of half a second before changing targets. Maybe that's where the issue comes from?

> Apart from the trouble with the fleeing personality, do I have any errors in my suggested "else if" chain?

Similar to the fleeing problem: If a ship has low health and successfully flees a system, and the system it flees to doesn't have any hostiles your logic will make it continue to flee (because of its low health).

**Comment by warp-core** [comment]
> > only flee if its current hostile target is not disabled, not that it will wait until that target is disabled
> 
> I agree with that, but I am still right about the consequence because what happens is this:
> 
> 1. Several ships are shooting at me, but I've disabled my hostile target.
> 2. I don't flee because my hostile target is disabled.
> 3. Now that my target is disabled, I pillage it, or pick a new target.
> 4. Other ships are still shooting at me, so I die.
> 
> Sure, if only one ship was shooting at you, the logic would work, because that ship was now disabled. It doesn't work when you are being swarmed, and that is how Korath die.
> 
> _Edit: To put it another way, if the ship wants to flee, but decides not to because of an unfinished objective, it will never flee until that objective is achieved. Disabled target vs. non-disabled target are both problematic objectives, unless code elsewhere clears that objective._

That's not really what was originally described.

Regardless, I think the solution to your problem would be to also check for hostile ships targeting this one instead of just that this ship is targeting a hostile ship that isn't disabled.

**Comment by UnorderedSigh** [comment]
> That's not really what was originally described.

I changed the description after two people pointed out that it was wrong.

> Regardless, I think the solution to your problem would be to also check for hostile ships targeting this one instead of just that this ship is targeting a hostile ship that isn't disabled.

Does the game keep track of that? Or will I need to loop over all ships to see who is targeting it?

**Comment by UnorderedSigh** [comment]
Another possibility is for the ship to keep track of the approximate damage per second it has been taking over the last X frames. I could do that pretty trivially, and it would be very cheap.

```python
AI::Step()
{
    ...
    foreach ship:
        dpsRecently = dpsFrame * 0.01 + dpsRecently * 0.99;
        dpsFrame = 0;
}
...
if(i want to flee && dpsFrame > someFactor * (hull + shields) && other conditions)
    Flee()
```

Then, whenever a ship takes damage, it increments dpsFrame.

**Comment by UnorderedSigh** [comment]
> Regardless, I think the solution to your problem would be to also check for hostile ships targeting this one instead of just that this ship is targeting a hostile ship that isn't disabled.

Doesn't the health check already do a good job of this?

It'll take into account other reasons for damage loss beyond targetting. I can improve it by looking at DPS, but I really think health is enough of a check on its own for a first pass at a new PR.

**Comment by UnorderedSigh** [comment]
I am closing this PR, and I'll make a new one soon-ish to fix the bug instead of working around it. I still need to iron out some details, as you may have noticed, but my mind is 93% of the way to a solution.

**Pull request closed without merging**
