### PR TITLE
feat(mechanics): New Damage Type: Engine Scrambling

### PR DESCRIPTION
**Pull request by OcelotWalrus**
## Summary
This PR is about adding a new damage type: the `Engine Scrambling Damage`. It has similar work to any damage. The particularity to this one is that it will 'randomly' disable the ship thusters (forward and reverse thrust) as well as the ships turn for a split second while having the effect. It kind of have the same effect when you don't have enough crews and your ship moves erratically.

## Usage Examples
It could be a cool and a useful new damage type for plugin creators. For example, for creating a missile that heavily damage the target in engine scrambling damage and make it almost unable to move.

## Testing Done
I tested the code and it works well. Maybe some code optimization/organization will need to be done and balancing for this new damage type.
[Watch the video](https://github.com/endless-sky/endless-sky/assets/87318892/a39e3b9a-35fe-426d-be8f-8844a309651b
)

## Performance Impact
No performance impact

### CODE REVIEW

**Comment by Zitchas** [comment]
Sounds like a good concept, and definitely has potential for allowing more differentiated types of weapons. 

I'll just note that it currently fails one of the checks:
```
FAILED: source/CMakeFiles/EndlessSkyLib.dir/Weapon.cpp.obj 
  sccache C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP -DUNICODE -D_UNICODE -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include\SDL2 -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include\AL /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MD -flto=thin /W3 /permissive- /sdl /GR- /analyze- -Wno-nonportable-include-path /Gy /Oi -WX /showIncludes /Fosource\CMakeFiles\EndlessSkyLib.dir\Weapon.cpp.obj /Fdsource\CMakeFiles\EndlessSkyLib.dir\ -c -- D:\a\endless-sky\endless-sky\source\Weapon.cpp
  D:\a\endless-sky\endless-sky\source\Weapon.cpp(302,5): error: array index 23 is past the end of the array (which contains 23 elements) [-Werror,-Warray-bounds]
                                  damage[RELATIVE_ENERGY_DAMAGE] = value;
                                  ^      ~~~~~~~~~~~~~~~~~~~~~~
  D:\a\endless-sky\endless-sky\source/Weapon.h(325,2): note: array 'damage' declared here
          mutable double damage[DAMAGE_TYPES] = {};
          ^
  1 error generated.
  ```

**Comment by OcelotWalrus** [comment]
Thanks! I'll try to fix that right now.

**Comment by OcelotWalrus** [comment]
> Sounds like a good concept, and definitely has potential for allowing more differentiated types of weapons.
> 
> I'll just note that it currently fails one of the checks:
> 
> ```
> FAILED: source/CMakeFiles/EndlessSkyLib.dir/Weapon.cpp.obj 
>   sccache C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP -DUNICODE -D_UNICODE -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include\SDL2 -imsvcD:\a\endless-sky\endless-sky\build\ci\vcpkg_installed\x64-windows-release\include\AL /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MD -flto=thin /W3 /permissive- /sdl /GR- /analyze- -Wno-nonportable-include-path /Gy /Oi -WX /showIncludes /Fosource\CMakeFiles\EndlessSkyLib.dir\Weapon.cpp.obj /Fdsource\CMakeFiles\EndlessSkyLib.dir\ -c -- D:\a\endless-sky\endless-sky\source\Weapon.cpp
>   D:\a\endless-sky\endless-sky\source\Weapon.cpp(302,5): error: array index 23 is past the end of the array (which contains 23 elements) [-Werror,-Warray-bounds]
>                                   damage[RELATIVE_ENERGY_DAMAGE] = value;
>                                   ^      ~~~~~~~~~~~~~~~~~~~~~~
>   D:\a\endless-sky\endless-sky\source/Weapon.h(325,2): note: array 'damage' declared here
>           mutable double damage[DAMAGE_TYPES] = {};
>           ^
>   1 error generated.
> ```

It's weird because I don't get these errors when i build to game on my computer. And on the Ubuntu checks, the errors that happens on Windows and Mac don't happen on Ubuntu.

**Comment by Saugia** [comment]
I feel like this has a bit of overlap with engine slowing. You could argue that it's the difference between ion damage and scrambling, however, in those two examples, one is scrambling weapons while other damages energy itself. Slowing vs engine disruption seems to be more of an overlap in that, and not enough of a distinction to include as a separate damage type, imo.

Also, keep in mind we do not add content to the game solely for the purpose of plug-in creators. We take a look at concepts and how they would help improve vanilla, and what it brings to the table. While variety is typically good to have, so is the moderation of variety and avoiding having *too* many different mechanics, or, in this case, mechanics that overlap with pre-existing ones.

**Comment by OcelotWalrus** [comment]
I know slowing damage does the same effect as the engine scrambling but there is a noticeable difference: slowing damage make you ship slower but still manoeuvrable, while the engine scrambling damage slows down your ship but it also make it move erratically and make it hard to maneuver it.

I totally understand if you think it's not enough worth it and different to add it to the game.

**Comment by Saugia** [comment]
I will say it is something worth debating, but not something to consider simply due to variety, and not something to add strictly for plug-in content.

**Comment by OcelotWalrus** [comment]
I'll work on searching ideas to make the Engine Scrambling damage more different from the slowing damage and make it worth it to add to the game.

**Comment by Saugia** [comment]
I'd wait for more opinions from other creators and devs first - it's still something that can work with what we have. I'm not saying to make it vastly more complex, different, or more involved than it currently is in order to have it considered, I'm more saying that a second engine-damage type in general is something worth discussing.

**Comment by Zireael07** [comment]
Maybe having your engines scrambled could also affect heat?

**Comment by Hecter94** [comment]
I'm concerned that while this effectively creates the same effect as slowing damage, it does so in a way that's a lot more annoying to have used against you when compared to regular slowing.

Trying to maneuver when under the effects of slowing damage is the same as normal, just slower and more ponderous, which can be worked around. 
Trying to maneuver while under the effects of engine scrambling means it will often take a lot of work to move the way you want to, as it's entirely random when it does and does not work.

Another question you should ask is: "What does this add to the game? What can this accomplish that slowing does not?"
If you can identify a scenario the existing slowing damage doesn't cover, you can find a niche where Engine Scrambling might fit.

I would also say to avoid anything that takes effect "randomly," as that usually contributes to a poor "game feel." 

If you can fill a niche that slowing damage can't fill and do it without randomness, I think I would feel much better about this PR.

**Comment by OcelotWalrus** [comment]
> Maybe having your engines scrambled could also affect heat?

It could be a side-effect of the Engine Scrambling.

**Comment by OcelotWalrus** [comment]
> Trying to maneuver when under the effects of slowing damage is the same as normal, just slower and more ponderous, which can be worked around.
Trying to maneuver while under the effects of engine scrambling means it will often take a lot of work to move the way you want to, as it's entirely random when it does and does not work.

That's what I'm trying to explain.

> I would also say to avoid anything that takes effect "randomly," as that usually contributes to a poor "game feel."
>
>If you can fill a niche that slowing damage can't fill and do it without randomness, I think I would feel much better about this PR.

I'll work on that. I think what I should try to make is still make the Engine Scrambling random but not as enough than the current effect. What I mean by that is, if I'd make the effect randomly slow the ship at a random thrust/turn (not too much) but do not make the engines 'turn off'.

And maybe adding additional heat could be a good thing.

**Comment by Hurleveur** [comment]
Maybe prevent hyperspacing with this

**Comment by Hecter94** [comment]
> Maybe prevent hyperspacing with this

I like this more than any of the other suggestions I've seen thus far. 
The only change I'd suggest is that rather than simply "prevent hyperspacing," it should impose an artificial departure distance on any ship hit by it, scaling up based on how much of the damage has been applied.

However, I wouldn't call it "engine scrambling" if you went this route since jumping doesn't require or use engines for anything more than getting lined up to jump.

**Comment by RisingLeaf** [comment]
> Maybe prevent hyperspacing with this

I agree that a damage type like that would be useful, especially for pirate like groups. But to be honest it doesn't really fit into the damage type proposed here.

**Comment by OcelotWalrus** [comment]
> The only change I'd suggest is that rather than simply "prevent hyperspacing," it should impose an artificial departure distance on any ship hit by it, scaling up based on how much of the damage has been applied.

I think imposing an artificial departure is not really realistic, even if it could be useful. 
What I propose is the damage will still 'scramble' the target engines but it will also prevent the target to use hyperdrive/jump drive if the target has too many 'engine scrambling' damage stacked on him.

I also think that 'engine scrambling' is not a good name for that and it need to be changed to something else.

**Comment by RisingLeaf** [comment]
> > The only change I'd suggest is that rather than simply "prevent hyperspacing," it should impose an artificial departure distance on any ship hit by it, scaling up based on how much of the damage has been applied.
> 
> 
> 
> I think imposing an artificial departure is not really realistic, even if it could be useful. 
> 
> What I propose is the damage will still 'scramble' the target engines but it will also prevent the target to use hyperdrive/jump drive if the target has too many 'engine scrambling' damage stacked on him.
> 
> 
> 
> I also think that 'engine scrambling' is not a good name for that and it need to be changed to something else.

That sounds too strong. You get locked down _and_ you can't jump away? That just sounds terrible. If anything they should be separate things.

**Comment by Hecter94** [comment]
Not "realistic," how? Too difficult to implement? If so, try asking around on our [Community Discord](https://discord.gg/ZeuASSx) and someone will be happy to help.
If your concern is that it's "unrealistic" in the sense of not agreeing with reality, that isn't a concern for Endless Sky. We aren't trying to be realistic. 

I disagree that it should prevent hyperspacing *and* damage mobility. They should be separate attributes so Content Creators can choose to add one or the other or both as needed, and I'm still unconvinced that "Engine Scrambling" as you've proposed is actually a good addition from a playability and game feel standpoint.

**Comment by OcelotWalrus** [comment]
I agree, it should be 2 separated thing.

**Comment by OcelotWalrus** [comment]
Si about the Engine Scrambling? Should I do something about it or is it good like that?

**Comment by RisingLeaf** [comment]
Btw to fix the build error, change DAMAGE_TYPES in Weapon.h to 24

**Comment by OcelotWalrus** [comment]
> Btw to fix the build error, change DAMAGE_TYPES in Weapon.h to 24

Ooh, I see, that's why there was that error...

**Comment by OcelotWalrus** [comment]
And what about a `confusion damage`? It will make the target weapons loose accuracy.

**Comment by Saugia** [comment]
Speaking for the Dev team: We want damage types without too much overlap from one another, and this isn't distinct enough from slowing to make sense to have. I also don't think overloading the attribute with other small additions, like confusion damage, or heat damage, is a good way to make it different enough from slow damage. Essentially, the concept of an "Engine Scramble" damage type is already in the game as a lack of crew issue. We wouldn't want to have damage types with multiple damages as that can get frustrating or hard to balance. Ultimately, we don't feel like we need more damage times than there currently are in the game.

Something I say often is: Variety is good to have, but it's good to have in moderation as well. We shouldn't be trying to fill every gap that exists, especially ones that overlap current content. If we were to do this, then eventually it wouldn't be variety, it would be having a ton of different concepts, things, etc., with only the slightest differences from one another.

**Pull request closed without merging**
