### PR TITLE
fix(map): darken map sprite to make text readable again (take 4 or so)

### PR DESCRIPTION
**Pull request by RisingLeaf**
**Bugfix:** This PR addresses issue: 42

## Fix Details
look here:

before:

reduced the brightness of the map sprite, I also reduced contrast by just a tad to keep the outer areas at the approximately same brightness

## Save File
bruh just open the map

### CODE REVIEW

**Review by Saugia — COMMENTED** [review]
Although the original's colors are more dynamic, this has much better readability especially towards the center of the galaxy, which was the whole concern with it, and does a better job at it than the previously shown name outlines, which were at odds with one another and other graphics on the map such as system circles, hyperlanes, etc..

Most of the gameplay is focused around the systems, and the galaxy backdrop is that - a backdrop, so having readability at the sacrifice of some of the colors is an acceptable change.

I still think perhaps the small center of the galaxy could be dimmed a bit more as I'm losing the "Sa" part in Sagittarius A* when zoomed in (though zoomed out looks fine).

**Comment by Saugia** [comment]
Looking at it again, the concern was mainly the middle, so if there's desire to kind of bring back the colors around the outer edges like with the EW, etc., that could happen. Some sort of gradient contrast from the center of the galaxy to the outer.

**Comment by Saugia** [comment]
After taking another look, the only real concern is the center, so we don't necessarily need to lose color everywhere. Could you try just changing the brightness/contrast around the center region of the galaxy? Make sure to feather the edges too it's not cut out like a circle.

**Comment by Saugia** [comment]
Sorry, I should have been more clear. I meant change the middle brightness (as you did in the commit), but from the map as it is now, not from your map in this PR.

**Comment by RisingLeaf** [comment]
Another try (sorry for late, kinda forgot)

**Review by Saugia — APPROVED** [review]
Core systems are a lot nicer to read now, especially SagA* and Kor Ak Mari. It looks a little dusty now, but honestly it fits.

**Pull request merged**
