### PR TITLE
Fix news entry in Hai space

### PR DESCRIPTION
**Pull request by ziproot**
**Bugfix:** This PR addresses an issue reported on [Steam](https://steamcommunity.com/app/404410/discussions/0/5513030395229755377/)

## Fix Details
Merchants would talk about staying away from the "north of Syndicate space" where "ships disappeared" (i.e. the wormhole to Hai space) ... in Hai space. With this PR, that no longer happens.

## Testing Done
Checked to make sure it would really only stop appearing in Hai space

## Save File
This save file can be used to verify the bugfix. The bug will occur when using latest Continuous, and will not occur when using this branch's build.
[Test Pilot~Hai Space.txt](https://github.com/endless-sky/endless-sky/files/13401819/Test.Pilot.Hai.Space.txt)

### CODE REVIEW

**Review by mOctave — APPROVED** [review]
Looks good to me! That phrase also appears in `merchant in human space` so it was probably added to `merchant anywhere` by accident.

**Comment by Amazinite** [comment]
#4361

**Comment by ziproot** [comment]
Then should I remove the line in "merchant in human space?"

**Comment by Amazinite** [comment]
It doesn't look like any of the other "merchants anywhere" news is duplicated, so I'd say go ahead.

**Pull request merged**
