### PR TITLE
Increased Kestrel base cost

### PR DESCRIPTION
**Pull request by Nescio0**
Currently the Kestrel's base cost (10.3m) is actually lower than the Falcon's (10.9m), although it's stronger than the Bactrian (17.6m). This patch increases the Kestel's base cost to 14.7m, somewhere in between.

EDIT: d2e19f154a37c267562192847a720fd4a36e3c1b improved the Kestrel, justifying a price increase.

### CODE REVIEW

**Comment by SirStigII** [comment]
It could be possible that the player is getting a discount for testing the ship, but even then this price increase seems reasonable.

**Comment by ghoulavenger** [comment]
The Kestrel is a stronger warship than the Bactrian, but you're paying for the cargo space and crew members on the Bactrian, neither of which the Kestrel really has so I don't see it as a fair comparison. But I see no fault in making sure the base price of the Kestrel is above the Falcon, considering the Kestrel is the next tier up. And it's not like you're going to capture them anyway which is I feel where the base price is most important.

**Comment by Amazinite** [comment]
>I see no fault in making sure the base price of the Kestrel is above the Falcon, considering the Kestrel is the next tier up. And it's not like you're going to capture them anyway which is I feel where the base price is most important.

In that case, the sale price and not the hull price is what we want to look at.

Ship | Sale Price
-----|-----
Vanguard | 13.730 M
Falcon | 15.854 M
Leviathan | 17.147 M
Dreadnought | 18.283 M
Current Kestrel | 18.523 M
Cruiser | 19.490 M
Proposed Kestrel | 22.123 M
Carrier | 23.618 M
Bactrian | 25.844 M

**Comment by tehhowch** [comment]
Plenty of folks don't bother using a Kestrel due to having better options at the time of unlock (it's hard to get the required combat rating without having a good combat ship, or a large escort fleet). Raising the price of the Kestrel isn't going to help this situation.

(The change is logical, but perhaps not sensible.)

**Comment by mdsmestad** [comment]
Has anybody considered that the Kestrel needs a buff & a price increase?

**Comment by ghoulavenger** [comment]
@mdsmestad why would the Kestrel need a buff? It's the best warship in human space. If it doesn't get used, it might be because by the time most people get it they're already moving on to Wanderer tech. Which to me means a lower point of entry might be better than any buff.

**Comment by KiLEdEnNis** [comment]
> why would the Kestrel need a buff? It's the best warship in human space.

not really, top 5 though
but for what one has to do to unlock the Kestrel, and the mission suggests it's based on an alien design one saw in his dream, it'd be logical if it was stronger than other human ships; mostly so the player can actually use it by the time they get to it and it's not that strange lore-wise

**Comment by ghoulavenger** [comment]
@KiLEdEnNis I don't see which human ship would be better. The Bactrians more of a boarder than a pure warship (especially after the mass expansion nerf). The Leviathan and Falcon are basically its predecessors. The Syndicate ships are all significantly worse. Which leaves the Dreadnaught, the Cruiser and Carrier maybe? Offhand I can't say those three aren't better with 100% certainty, but I would wager the Dreadnaught isn't, and the other two can't be bought. 

For the ease of access though you could go for the Shield Beetle and that one is on par if not better than the Kestrel, and the Kestrel is a real nag to unlock in comparison. Heck if you knew what you were doing, you could probably get Remnant stuff unlocked before the Kestrel.

**Comment by Bladewood** [comment]
It's about on par with a carrier in terms of customizability, but barely on the level of a dreadnought in terms of health and speed.

**Comment by Nescio0** [comment]
To make the discussion easier, let's compare the values. The Kestrel is one step above the Falcon, the Osprey is one step below. I've also included the Bactrian and the Dreadnought, its closest human competitors (Carriers and Cruisers are not for sale):

```
         Osprey, Falcon, Kestrel, Dreadnought, Bactrian
cost   :  4.4m , 10.9m , 10.3m       , 11.9m , 17.6m
shields:  7200 , 12800 , 17400/20100 , 18100 , 17500
hull   :  1600 ,  3700 ,  6200/7500  ,  7300 ,  8600
crew   :     9 ,    52 ,    72       ,    84 ,    70
bunks  :    24 ,    75 ,   128       ,   147 ,   245
mass   :   270 ,   510 ,   740       ,   630 ,   940
drag   :   6.1 ,   6.7 ,  12.5       ,  10.1 ,  16.1
heat dn:   .8  ,   .7  ,   .45       ,   .65 ,   .4 
fuel   :   600 ,   600 ,   500       ,   600 ,   700
cargo  :    40 ,    90 ,   120       ,   100 ,   530
outfit :   450 ,   540 ,   810       ,   790 ,   740
weapon :   180 ,   240 ,   380/400   ,   360 ,   300
engine :   130 ,   150 ,   210/230   ,   190 ,   180
gun    :     4 ,     4 ,     6       ,     4 ,     4
turret :     2 ,     4 ,     4       ,     5 ,     6
```
Statistically the Falcon is clearly closer to the Osprey than it is to the Kestrel, yet the Falcon's base cost is 2.5× as high as the Osprey's, while the Kestrel's is rather surprisingly 5% *cheaper*.
* the Osprey is already amongst the most expensive medium warships, making it more expensive is not really an option
* the Falcon's base cost is similar to the Leviathan's, making it cheaper would also force us to make Behemoths and other heavy ships cheaper, which seems an unnecessarily bad idea
* the Kestrel is much better than its smaller Tarazed cousins, therefore it's perfectly logical it ought to be more expensive; the proposed raise is rather conservative if you see what you get

> It's about on par with a carrier in terms of customizability, but barely on the level of a dreadnought in terms of health and speed.

The Carrier is not for sale. The More Shields Kestrel (the one I ended up with) has more health than the Dreadnought; also, all Kestrels can equip A5 steering and thrusters simultaneously, making it actually faster than the Dreadnought as well, despite the higher drag.

> Plenty of folks don't bother using a Kestrel due to having better options at the time of unlock

True, myself included; the Bactrian and Mule are the only human ships I consider worth buying (both of which I think are too cheap, but that's a different discussion). And the Shieldbeetle is clearly the best choice for a warship in about all respects (besides, the Unfettered are kind enough to send in a free supply at Wah Ki).

> Has anybody considered that the Kestrel needs a buff & a price increase?

A slight buff to make it more attractive wouldn't hurt, especially since it's surprisingly inefficient for the supposedly most modern human warship. A few suggestions:
* lower minimum crew from 72/128 to 64/128
* improve heat coefficient from .45 to .6 (still worse than Dreadnought)
* lower drag or swap it with Dreadnought (10.1 instead of 12.5)
* increase weapon capacity from 380 to 390 (to allow 4 plasma turrets + 6 plasma cannons)
  * More Weapon Kestrel's weapon capacity from 400 to 420 (to allow 4 plasma turrets + 6 particle cannons)
* significantlly increase Kestrel's base cost (e.g. to 14.7m or even more)

**Comment by Nescio0** [comment]
> Heck if you knew what you were doing, you could probably get Remnant stuff unlocked before the Kestrel.

Actually I didn't know what I was doing, yet somehow I unlocked the Kestrel and Remnant stuff *before* I discovered the Free Worlds campaign; I suppose I'm an exception (I also had a jump drive but kept it in cargo because I didn't understand its purpose).

**Comment by KiLEdEnNis** [comment]
to unlock Remnant tech ya do have to disable a World-Ship that pussies out when it gets low & later hunt 3 Raiders before ya get their license, and for the Kestrel ya need 8k combat rating, so that was more a matter of ya took really long until ya found the story

**Comment by endless-sky** [comment]
I'm not convinced that a price change is needed, at least not without also buffing the Kestrel in some way. Because you get it through a special mission, even if the price is a bit low it's not unreasonable.

**Comment by Nescio0** [comment]
Improved Kestrel's stats to justify a price increase (see above for details). It's still not as good as a shield beetle, but at least the Kestrel is now a better choice on its own and in comparison with other human ships.

**Comment by KiLEdEnNis** [comment]
I'm for a Kestrel buff so it's an actual choice by the time you get it until you get, say, a Tempest

**Comment by Nescio0** [comment]
The reduced drag is necessary to make the Kestrel (a streamlined design) at least faster than the Dreadnought (a bulky container). Osprey has heat dissipation of .8, Falcon .7, so .6 would be a logical next step for the Kestrel (and it's still not as good as the Dreadnought's). A lower mass would also reduce its heat capacity. As for the minimum crew, the proposed value is still higher than the Derecho's or Shield Beetle's. 
The Kestrel is supposed to be a very modern state-of-the-art ship, so I'd expect it to be highly efficient (which is why I think a lower minimum crew and better heat dissipation and drag make sense).

More outfit capacity is unnecessary, since the Kestrel already has one of the highest outfits/weapons/engines capacities:
* Hurricane: 960/428/140
* Carrier: 820/370/210
* Kestrel: 810/380/210
* Shield Beetle: 798/333/150
* Derecho: 796/342/164
* Dreadnought: 790/360/190
* Cruiser: 760/320/170
* Bactrian: 740/300/180

A little bit more health could work, although I'm not sure it's necessary, since it's already very close to the Bactrian's and Carrier's.

**Comment by KiLEdEnNis** [comment]
that reminded me; the Kestrel does have a ridiculous amount of engine capacity, bringing the drag down at all makes it a big-ass war Flivver

**Comment by SirStigII** [comment]
I'll have to play test it, as it had a really slow top speed previously, so much so I know it bugged be when I first used it.

**Comment by Nescio0** [comment]
> that reminded me; the Kestrel does have a ridiculous amount of engine capacity, bringing the drag down at all makes it a big-ass war Flivver

> I'll have to play test it as it had a really slow top speed previously, so much so I know it bugged me when I first used it.

With these changes the Kestrel could become the fastest heavy warship, yes. Although it can not compete with the Shield Beetle, Albatross, or Wanderer ships in terms of health, the Kestrel's firepower is second only to the Hurricane. Taking everything together, the Kestrel would become suitably different from its alternatives.

**Comment by Nescio0** [comment]
Related but independently, the Dreadnought is a bit cheap and fast as well. If drag were increased from 10.1 to 11.1 and base cost from 11.9m to 13.5m, it would compare with the Cruiser:
screenshot from 2018-01-02 19-42-30

**Comment by Amazinite** [comment]
I'm not sure how I feel about the Dreadnought price increase, especially at an increase of 1.6 million. The drag increase I can understand (offsets the Dreadnought's 20+ engine space over the Cruiser), but the Dreadnought already has a hull cost than the Cruiser while only costing less because southern tech is cheaper. And given issues like #1848 exist and #3330 that tries to address that, I don't think a price increase would be helpful gameplay wise for someone already struggling to keep up during the FW campaign if they aren't the kind of person to get themself a Shield Beetle or even Kar Ik Vot before starting.

**Comment by Nescio0** [comment]
Well, I think the Dreadnought is clearly better than the Cruiser, yet currently it's cheaper, hence the price increase of about 10%, which shouldn't be a serious problem. (However, my own experience is rather limited, since I already purchased ten Bactrians and captured ten Shield Beetles before I discovered the Free Worlds campaign.) I can revert it if you think it would really break things.

Anyway, this proposal is actually about the Kestrel; the Dreadnought tweaks I did on the fly while comparing the Kestrel with its human alternatives.

**Comment by MessyMix** [comment]
The norm is to create a separate PR for separate issues, so MZ can merge the features as he likes. Don't put the Kestrel edits with the Dreadnought ones. And, if in that case the Dreadnought change seems too insubstantial for its own PR, then don't open it. Or create an issue first.

**Comment by Nescio0** [comment]
> The norm is to create a separate PR for separate issues, so MZ can merge the features as he likes. Don't put the Kestrel edits with the Dreadnought ones. And, if in that case the Dreadnought change seems too insubstantial for its own PR, then don't open it. Or create an issue first.

It's included because they're related; if the Kestrel becomes more expensive, it would make sense to increase the price of the statistically similar Dreadnought, the other human heavy warship which has to be unlocked, as well, albeit to a lesser degree. If the proposed Kestrel tweaks are rejected, then a separate Dreadnought proposal would be unnecessary too.

**Comment by Nescio0** [comment]
Closing because it's unlikely to be implemented in its current form.

**Comment by Nescio0** [comment]
Because the Kestrel's been improved with d2e19f154a37c267562192847a720fd4a36e3c1b, I think it's appropiate to reopen the discussion on its base cost.

**Comment by Pointedstick** [comment]
Now that the Kestrel has been buffed, I think this makes sense, in some form. But I have no particular opinions regarding the exact numbers chosen. I'll leave that to others to sort out.

**Comment by Amazinite** [comment]
In my eyes, I don’t see why we’d make the Kestrel less attractive by increasing the cost after we just tried to make it more attractive.

**Comment by Pointedstick** [comment]
By the time the player gets here, money is likely not to be much of an issue anyway, so it's all kind of a moot point I suppose. Still, there's likewise probably no reason not to: better ship -> higher price. Makes sense to me.

**Comment by Amazinite** [comment]
Like I mentioned, I don't think it makes sense to make the Kestrel less attractive be increasing the cost by so much when we just tried to make it more attractive by buffing it. Consider the rather low cost a discount for helping to test and name the ship.

How about just +1 to 2 mil instead of +4.4 mil?

**Comment by Nescio0** [comment]
The Kestrel was already too cheap compared before #3976 was implented; now the Kestrel has been improved, there's even more reason for a price increase. For comparison:
```
               base cost, shields, hull; cargo, outfit, weapon, engine
Bactrian:         17.6 m, 17500, 8600; 530, 740, 300, 180
Carrier:          15.2 m, 21400, 8300; 100, 820, 370, 210
proposed Kestrel: 14.7 m, 19400, 7200; 120, 810, 390, 210
Dreadnought:      11.9 m, 18100, 7300; 100, 790, 360, 190
Cruiser:          11.2 m, 19600, 6400;  60, 760, 320, 170
Falcon:           10.9 m, 12800, 3700;  90, 540, 240, 150
current Kestrel:  10.3 m, 19400, 7200; 120, 810, 390, 210
Leviathan:         9.8 m, 14400, 5000;  80, 620, 240, 120
Vanguard:          7.2 m,  9800, 6000;  50, 560, 220, 120
Protector:         5.5 m,  9500, 6500;  50, 570, 220, 100
```
(base Kestrel values are listed; in practice you have one of the statistically superior variants).

**Pull request merged**
