### PR TITLE
Commendations on pilot info screen

### PR DESCRIPTION
**Pull request by guillochon**
I have created a list of  "commendations" that appears on the pilot info screen. At the moment, I have a single example commendation I've added for completing the main free worlds storyline, but I added a bunch of images of medals (which are from a freely available source, http://www.fatcow.com/free-icons) which others can use for other commendations they think of.

I wanted the commendations to not overwhelm the info screen, but still stand out, so they are colorful but small. Here is what the pilot info screen looks like after winning a commendation for completing the main storyline:

image

This can be viewed as a sort of in-game achievement system (as I suggested here: https://github.com/endless-sky/endless-sky/issues/301), but the idea is that commendations are actually awarded to your pilot during the storyline; they are physical objects that you acquire.

### CODE REVIEW

**Comment by endless-sky** [comment]
It doesn't make much sense for the name and icon of every commendation to be hard-coded. Either the name of the icon should be identical to the name of the commendation, or there needs to be a data element mapping names to sprites.

But, aside from that, I'm also somewhat opposed to "achievement" systems, because they generally represent an attempt to artificially add replay value to a game.

On the other hand, I've been thinking of adding a "pilot's logbook" or something to that effect (see #237). The logbook could include entries you make by hand and also automatic entries when you complete certain missions. That might be a reasonable place to put something like this.

**Comment by guillochon** [comment]
The idea was really not to make this an "achievement" system per-se, but just to give some additional flare when milestones in the story are achieved. For instance at the end of the free worlds storyline it actually tells you that you will receive a commendation, but then there's no visual indication that you've been awarded anything!

I changed the name to be equal to the commendation name, that at least removes the hard-coded aspect. I kept the other medal icons in the folder for others to use, if they so desire.

**Comment by egilburg** [comment]
Perhaps expand "salary" to be a factional rank which comes with bonuses of which salary is just one.

Example:

Faction: Free World
Rank: Commodore
Salary: 6000

Rank could be used for other bonuses than salary, for example Dreadnoughts only sold to faction members of a certain rank.

**Comment by omagasohe** [comment]
I don't see this system being an achievement system. Those are dumb, seriously who really cares if you've killed 40 of anything. I do like rank systems. They allow for interesting story arcs.  

But it needs to be a plug-in compatible system, that can be used for conditions in missions, outfitters and ship buying. Salary would be nice, fleets get expensive. awarding them needs to allow for a higher rank to already have be awarded. This would allow for a few mission paths. I'm not a fan of linear story lines.

**Comment by frameworld** [comment]
I don't like the idea of achievements either.

In school you don't get a nice test-result every few seconds either. All these artificial achievements are creating an illusion of you doing something of value when you do not.

When you progress through the story-line, at least you learn something (namely you listen to the mission's author's wisdom)

**Comment by guillochon** [comment]
What's the consensus on this one? Again, these are not "achievements," just nice little icons to show the player's progress in the world.

**Comment by Wrzlprnft** [comment]
We all agree we do not want an "classic" achievment system like "kill x pirate ships" etc. 
But @guillochon suggested "milestones" which give you maybe more of a reward feeling for completing the story, and are bound to it.
The dev supposed to fusion the commendations with the "logbook"-topic.
And here appeared, which is in my opinion not connected to the topic of the pull request, only to the broader variaty of achievements, the expansion of the rank system.
Did i get that right?
This poll is only about this certain pull request and it's content, to get back to the point. it just felt like we could talk about this issue for ages, but that doesn't help this pull request

http://poll.lab.io/K_a3I5O-sW3kP1RYS7zOUw

**Comment by Thunderforge** [comment]
I like the idea of commendations if they represent in-story awards, such as the commendation described at the end of the Free Worlds campaign. I can also imagine other awards appearing there, such as the scifi equivalents to a Medal of Honor or knighthood.

**Comment by jmhorjus** [comment]
+1 to this idea, so long as it is fully mod compatible. I believe they should be called "titles" or "ranks" rather than "commendations".  Unless something like this is implemented, my mod to give myself the title of "Cunjo Hunter" will never see the light of day, which would be 100% intolerable! :)

In the future when there are a few minor factions with side stories it would be quite nice to see a few indications:
Free Worlds Lieutenant (300cr salary)
Tarazad Corporation Clearance Level 2 
Bounty Hunter's Guild Initiate
etc.

**Comment by davidwhitman** [comment]
Eight months later...

I had the idea myself a couple of days ago of adding a "trophy case" in the game, which would conceivably be in your ship but of course just displayed in the gui. I was thinking of using larger sprites in a grid format on a new tab of the Info screen. 

Trophies would not be achievements ("killed 1000 pirates!" "flown 2mil parsecs!"), but rather things you pick up or win from various missions. For example, a fang from a dragon on Skymoot, or maybe a trophy from some cross-galaxy racing mission, or an interesting rock from the far reaches of space, or a piece of cake from a world overrun by an AI obsessed with testing. 

They would serve as mementos of things you've done and kind of give a greater impression that you're flying around in a real ship that you can put souvenirs in. 

This isn't exactly the same as is suggested in this PR, but I think the two ideas could easily be combined if there is interest in both. 

> my mod to give myself the title of "Cunjo Hunter" will never see the light of day, which would be 100% intolerable! :)

If you liked the Cunjo hunting mission, then you should totally check out [my mod](https://github.com/davidwhitman/endless-sky-dangerous-games) :P 
And I'm working on the second mission, an underwater flight where you guide a crew of men in subs around various hazards in order to view "Quoijuu" (Koi + Kaiju :P) during mating season.

**Comment by endless-sky** [comment]
Another suggestion was to have some sort of "captain's log" that would contain a record of significant missions you've completed, written as a sort of logbook, e.g. "7 Mar 3014: Met some Quarg aliens. 30 Apr 3015: discovered some weird alien technology on a Deep planet. 15 Jan 3017: Got a job offer from the Free Worlds. 31 Jan 3017: Tried to rescue Katya from Clink, but couldn't find find her anywhere." The logbook would also allow the player to add their own lines, and might also include adding personal notes on specific star systems like "Lots of pirates here. Avoid."

**Comment by davidwhitman** [comment]
At the risk of sounding overambitious, I think there's room for both.

As a pilot, I would definitely have space on my ship for trophies/mementos. You should see the trophy rooms I've made in Terraria. IRL if I go to a new place, sometimes I'll bring back cool-looking rocks or some local art or something. If I were a galaxy-trotter, you can bet that I'd have a place full of things that I've gathered. 

A captain's log could serve the same purpose, but lines of text are an awfully dry way of doing it compared to nice little sprites. On the other hand, it would cover quite a few use cases and being able to tag systems and such with custom messages would be neat (although I've not once wished I had this feature in this game because the ingame map is quite detailed).

**Comment by Wrzlprnft** [comment]
Anyone knows that small trophy room in star trek online?

**Comment by endless-sky** [comment]
Closing this because the logbook serves a very similar function.

**Pull request closed without merging**
