### PR TITLE
See Muspel from Norn, see Norn from Muspel

### PR DESCRIPTION
**Pull request by DrBlight**
I changed the planet images for the sister worlds, Norn and Muspel, to make them visible in one another's atmospheres. I also added a few buildings in the distance on Norn's image. 

The high DPI version can be found here: https://github.com/endless-sky/endless-sky-high-dpi/pull/61

### CODE REVIEW

**Comment by jafdy** [comment]
Note that `beach4` is also used for Vara Pug.

**Comment by Pointedstick** [comment]
> Note that `beach4` is also used for Vara Pug.

Hmm, I don't see it: https://github.com/endless-sky/endless-sky/blob/master/data/map.txt#L27074

**Comment by tehhowch** [comment]
To prevent such possible "oops" changes, specialized landscapes could likely be labeled as the relevant planet.

**Comment by DrBlight** [comment]
I agree about the image names. I always check first to see if the image is used elsewhere in the game, but that really isn't a long-term solution. 

It's true that the planets are big and now we can always see them, and yes, that's a bit of artistic license on my part. It's just visually better when they have that classic sci-fi book cover look, as opposed to being obvious locations on Earth. And surely both Norn and Muspel are bigger than our moon?

**Comment by Amazinite** [comment]
Hold up, the beach4 image has the same problem that the last PR did. 
https://github.com/endless-sky/endless-sky/pull/3852#issuecomment-406618864

**Comment by DrBlight** [comment]
Ah yes, the assets: [norn-muspel krita files.zip](https://github.com/endless-sky/endless-sky/files/2664644/norn-muspel.krita.files.zip)
I did forget to update the copyright file this time. I'll have to do that in another pull request.

**Comment by Amazinite** [comment]
Assets should preferably be in .xcf so that they can be used by Gimp.

**Comment by DrBlight** [comment]
OK:  
[norn-muspel gimp files.zip](https://github.com/endless-sky/endless-sky/files/2670355/norn-muspel.gimp.files.zip)

**Pull request merged**
