### PR TITLE
Project: Smarter Korath Raids

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Feature:** Korath ships raiding human space are often overwhelmed and killed. The main purpose their human space raids serve is to be easy farming targets for players. Similar problems are discussed here: #7539

This PR is intended as a testing ground and discussion forum for multiple PRs that will fix the problem. Any changes to Korath raids will need to be tested along with other changes to those raids, otherwise the result will conflict and be generally useless. In other words, this is a collaborative project, or an issue with a branch, rather than a true pull request.

As the ideas mature, I'll submit PRs for individual pieces. (Or you can submit them instead!)

## Feature Details

These are the changes I plan. I'll check them off as they're implemented.

- [ ] Korath don't wait until they're outgunned before entering a system.
     - #8082
     - #8123 (not merged into this PR, because 8082 is superior)
- [ ] Korath will stay in a system even if their prey is more than 2000 pixels away.
    -  #8117
    - #8125
- [ ] Korath ships can retreat when they need to
    - #8127
- [ ] Korath ships will prioritize assisting other Korath ships.
- [ ] Korath rapid response fleets and maydays.
- [ ] Some pirates won't attack the Korath.
- [ ] Re-balance the Korath raids.

I'll apply these changes to other Korath-haunted and Korath-inhabited systems when relevant.

## Problems, Investigations, and Solutions

These are the results of my investigations, and the fixes I've found. The :heavy_check_mark:  green check marks mean I have a solution to the problem (even if it hasn't been merged yet).

### Korath don't wait until they're outgunned before entering a system. :heavy_check_mark: 

Presently, the Engine ensures a fleet will not enter if the resulting credit value of that side would be more than twice that of the enemies. This is to prevent one side from sending waves of reinforcements when they have plenty already. In the case of the Korath, this means their extremely valuable ships are overpowered by fleets of cheeper, but quite effective, pirate vessels.

This is implemented in #8082 and that PR is merged into this one. Look at changes in `map systems.txt` to see how I tuned the fleets.

### Korath will stay in a system even if their prey is more than 2000 pixels away :heavy_check_mark: 

This was actually two problems, which I can solve through new personalities:

1. A Korath vessel will have nothing to do, so it'll jump out of the system without waiting for a target. This is solved by the new *lingering* personality, which causes them to wait a while before leaving, even if there's nothing to do. (#8125)
2. Korath were unwilling to travel more than 2000 pixels to attack someone. The new *hunting* personality overrides this. (#8117)

### Korath ships can retreat when they need to :heavy_check_mark: 

There were a few problems that prevented this:

1. A bug in the retreat logic. If a ship wants to flee, it'll wait until its current target is disabled, because that is always worth dying for. This is fixed by the new *pragmatic* personality in #8127
2. Korath ships rarely get below 50% health unless they're about to die. This is because their shield repair is always enough, until they're overwhelmed by multiple ships. Giving them *coward* helps with this, and also reduces the massive build-up of ships that come from other changes.
3. The Syndicate and core pirates have particle and proton weapons that can easily paralyze ships; a dozen or so of these guns will keep Korath from jumping. This is unavoidable.

### Korath ships will prioritize assisting other Korath ships

Presently, in Endless Sky, helping a disabled vessel is an afterthought. Ships will do it if they have nothing better to do. Instead, the Korath should be willing to cross the system to help another vessel that's in trouble.

### Korath rapid response fleets and maydays

If a Korath ship is in trouble, it sends a mayday, which causes a rapid response fleet of larger, faster, vessels, to jump in and rescue it. This is actually very easy to implement on top of #8082, but there isn't much of a point until Korath ships can prioritize assisting other Korath ships.

### Some pirates won't attack the Korath

This is (tentatively?) planned for later Korath stories anyway. The closer you are to New Tortuga in uninhabited or pirate systems, the more pirates you'll see that are unwilling to attack Korath. The consequence of this is that it'll be harder to farm Korath without fighting them.

## UI Screenshots
N/A

## Usage Examples

1. Farming the Korath in human space will be a challenge.
4. Korath won't cause lore problems by giving away their goods to the humans in bulk through blatant stupidity.
5. We won't wonder how a race got to be Tier 2.5 with an almost total lack of understanding of tactics.

## Testing Done
Fly around in Korath-raided human systems.

### Automated Tests Added
N/A

## Performance Impact
N/A

### CODE REVIEW

**Comment by Hurleveur** [comment]
Have you considered adding coward to the ships so they jump out earlier when losing a fight? That wouldnt quite be the distress call but still smth.
Also if you want to respond to the player's fleet in raiding https://github.com/endless-sky/endless-sky/pull/8092 this should help. That said all of this seems very rough as a draft and like it should belong in an issue, so we can do each of these changes as independent PRs to get them going faster?
This seems like it'll require some new features which should not be implemented in the same PR where they're used as a general good practise rule.

An issue would also allow for discussion over how to best do all of this.

**Comment by UnorderedSigh** [comment]
> Also if you want to respond to the player's fleet in raiding https://github.com/endless-sky/endless-sky/pull/8092 this should help

Korath don't use the raid functionality. It wouldn't be useful since they don't attack systems with frequent merchant traffic. Also, they're usually strong enough so the player alone isn't much of a threat.

> Have you considered adding coward to the ships so they jump out earlier when losing a fight?

Yes, but I was informed third hand that @ravenshining didn't like the idea. As third-hand information, that may be false.

> so we can do each of these changes as independent PRs

I don't know if you read the PR description, but these are in independent PRs. This draft PR combines them into one so they can be tested together.

> An issue would also allow for discussion over how to best do all of this.

No, an issue wouldn't give us a place to test the various approaches together as a single product. Just like a campaign, you need a draft PR for testing. Otherwise, we're just hypothesizing without seeing if our hypotheses are nonsense.

**Comment by UnorderedSigh** [comment]
This needs to be in a draft PR, not an issue, so the individual PRs that improve Korath raiding can be tested together. Otherwise, our theorizing about what might help could be nonsense. Just like a campaign, you need a single branch that will let you test everything together.

**Comment by UnorderedSigh** [comment]
This PR is intended as a testing ground and discussion forum for multiple PRs that will fix this problem. I don't anticipate this PR will ever be merged on its own, but that depends on how reviewers and commenters feel. Any changes to Korath raids will need to be tested along with other changes to those raids, otherwise the result will conflict and be generally useless.

In other words, consider this PR to be a "collaborative project" rather than a "pull request"

**Comment by UnorderedSigh** [comment]
> An issue would also allow for discussion over how to best do all of this.

Also, point of note: pull requests are issues. That's why the pull requests search page is just the issue search page with `is:pr`, and it's why the pull requests and issues increment together.

So, yes, I opened an issue for this. You're reading it.

**Comment by quyykk** [comment]
> That's why the pull requests search page is just the issue search page with is:pr,

And the issues page is just the PR search page with `is:issue`? PRs aren't issues, even if they both use the same number sequence.

**Comment by UnorderedSigh** [comment]
> And the issues page is just the PR search page with is:issue? PRs aren't issues, even if they both use the same number sequence. but whatever

Is there another way to have an issue with a branch that tracks its progress? I've always used draft PRs for that.

**Comment by UnorderedSigh** [comment]
> Have you considered adding coward to the ships so they jump out earlier when losing a fight?

The retreat logic is broken. What the Korath need is the [pragmatic](https://github.com/endless-sky/endless-sky/pull/8127) personality, which is the workaround for the bug in the retreat logic.

**Comment by warp-core** [comment]
> > Have you considered adding coward to the ships so they jump out earlier when losing a fight?
> 
> The retreat logic is broken. What the Korath need is the [pragmatic](https://github.com/endless-sky/endless-sky/pull/8127) personality, which is the workaround for the bug in the retreat logic.

If the retreat logic is indeed "broken," I suggest perhaps it should be fixed, rather than trying to tack on a workaround.

**Comment by UnorderedSigh** [comment]
> If the retreat logic is indeed "broken," I suggest perhaps it should be fixed, rather than trying to tack on a workaround.

That would require retuning the entire game.

**Comment by UnorderedSigh** [comment]
> If the retreat logic is indeed "broken,"

My changes are here. Coudl you please let me know if my interpretation is right? #8127 

It isn't 100% reliable since the ships will sometimes decide they don't have a valid jump target when they really do, or they'll decide to flee and then... not flee. Of course, that isn't always their fault: the pirate and syndicate have proton and particle weapons which are excellent at paralyzing ships.

**Comment by UnorderedSigh** [comment]
> they'll decide to flee and then... not flee

This particular problem was a conflict between lingering and fleeing.

**Comment by UnorderedSigh** [comment]
I've found that pragmatic+coward eliminates problems that come from "ignore enemy strength"+hunting+lingering. On its own, pragmatic is not enough since:

1. A ship will get overwhelmed with particle and proton weapons, preventing it from fleeing in time. Cowards will flee before that becomes a problem.
2. The hunting, lingering, and "ignore enemy strength" lead to a huge build-up of Korath ships that just dominate the system. Once there's about three, the Korath are unstoppable. If they retreat earlier (coward) they maintain a better balance and lose fewer ships.

**Comment by ravenshining** [comment]
All these ideas are good.  I've got a half-finished branch that touches on the last point (Some pirates and Korath get along), which I've been meaning to PR for like a month now.  Maybe I'll PR it to this one, but don't hold your breath.

> Yes, but I was informed third hand that @ravenshining didn't like the idea. As third-hand information, that may be false.

When it comes to me I think even second hand information is highly questionable :-)

I think I've expressed cautious, ambivalent support about `coward`.  It has pros and cons, and I don't fully understand the mechanics, which I believe are not fully documented.   But if it works as it is advertised here, great!

**Comment by UnorderedSigh** [comment]
>  Maybe I'll PR it to this one, but don't hold your breath

No, any PRs related to this project should go to master first. They can be merged into this branch for balance testing, but master is the target. (All the PRs I list in the description are to master.)

**Comment by Zitchas** [comment]
I like the sounds of these. The additional precision in personalities also sounds good, and the way they allow us to portray the Korath as smarter, more responsive, and and less prone to just getting farmed by low-grade pirates and syndicate. 

The only part I'm really dubious about is the Korath actively working with pirates. Some degree of "they're bigger, better, badder pirates than us, so we stay out of their way and treat them as if they were a big pirate gang" attitude on the pirate's part makes a lot of sense, though. Given the disparity of capabilities, the most there really should be in terms of cooperation is something along the lines of "The pirates dump loads of cargo (tribute?) somewhere for the Korath, and the Korath don't attack them. So the Korath get commodities, and the pirates get to not-die."

The relationship between Korath and Humans is a central thread to the Remnant campaign, and having any kind of pirates and Korath working together sort of thing going on basically renders a couple chapters of planned story obsolete. No point in story talking about it if we can just go "convince" some pirates to reveal everything.

**Comment by UnorderedSigh** [comment]
> Korath actively working with pirates

No, the Korath will have no direct contact with pirates. That would be a catastrophically toxic relationship that would last only a few days. There is another human group that acts as go-between, but they would not share the Exiles' secrets until the Exiles trust you, since their bond runs deeper than business. The Korath tolerate certain pirate groups because their human go-betweens need those pirates to run cargo or transport individuals. Any other pirate groups are viable targets.

**Comment by Zitchas** [comment]
That sounds better, but still dubious as to the nature of this human group working with the Korath. Not as bad as having a major pirate organization working with them, but still problematic.

**Comment by UnorderedSigh** [comment]
> That sounds better, but still dubious as to the nature of this human group working with the Korath. Not as bad as having a major pirate organization working with them, but still problematic.

It is not, and to find out why, you must discuss it with ravenshining and I on Discord. It would be advantageous if we could set up a three-way chat.

**Comment by UnorderedSigh** [comment]
> You are in the Swizzle 6 discord, I assume? We can probably coordinate a three-way chat there.

Yes.

**Comment by Amazinite** [comment]
As with #8669, PRs that are not themselves intended to be merged should not be opened.

**Comment by UnorderedSigh** [comment]
Sorry, I meant to close this draft PR since the work has moved elsewhere. Thanks for closing it for me.

**Pull request closed without merging**
