### PR TITLE
Anti Ijs Cloning

### LINKED ISSUE #1083: "FW Reconciliation Break" and "FW Conservatory 1" can both be active at the same time
And if you complete one of the missions, the other one stays active.
Ijs Springborn confirmed master of cloning.

### PR DESCRIPTION
**Pull request by LocalGod79**
fixes #1083

### CODE REVIEW

**Comment by endless-sky** [comment]
That would make the main story line mission (FW Reconciliation 1) fail to be offered, with no explanation for why it is blocked. I think there needs to be a better solution - like, if you get too far along in the Free Worlds plot without dropping Ijs off, a new mission should spawn where Ijs says, "You know what, Captain, I think I'll just catch a ride with someone else," and that new mission then declines itself and tells the conservatory mission to fail.

**Comment by LocalGod79** [comment]
it's about 70% of the way through the fw middle arc - plenty of time for the player to have transported him (considering they've also been in the neighbourhood of the destination for several other missions - diplomacy/war with Bloodsea)

seemed like a good spot for him to book passage from.

**Comment by endless-sky** [comment]
I'm not sure if he should pay you, given how much you've inconvenienced him. :)

For formatting, please only use single spaces between sentences - double spaces mess up the text justification. And, don't indent the first paragraph of text. (I'm trying to match the standards of modern professional typesetting as much as possible.)

Also, note that it might be preferable to make Ijs's mission fail this way, instead:
```
mission "ijs catches another ride"
	on offer
		...
		conversation
			`...`
				decline
		fail "FW Conservatory 1"
```
That would have the slight advantage that the logic for failing that mission is all localized in one place.

**Comment by LocalGod79** [comment]
it wasn't the whole amount - about 30%.  i figured that the player should get *something* for getting him from Bourne to Bloodsea, even if they didn't get him all the way to Winter.  in the end, Ijs didn't give a deadline, so the inconvenience couldn't have been *that* great...i've cut it down to 10k - what's that between friends, right?

sorry about the typesetting - old habits die hard...

**Comment by endless-sky** [comment]
I just merged this in manually, to keep the commit history a bit cleaner and avoid pulling those changes to the side plots file along with it: ce88f7c.

**Pull request closed without merging**
