### PR TITLE
feat(content): Balance - Quicksilver price decrease & cargo buff

### LINKED ISSUE #8048: Balance: Make Quicksilver cheaper
### Problem Description

When choosing my Light Warship I noticed that Quicksilver is just horrible in everyway compared to other ship of same price range especially as combat ship. Here's some of the stats between Quicksilver, Headhunter, and Clipper

<table>
<tr>
	<td>Stats
	<td>Quicksilver
	<td>Clipper
	<td>Headhunter
<tr>
	<td>Shields/Hull
	<td>3000/800
	<td>2700/800
	<td>3800/700
<tr>
	<td>Hardpoints
	<td>2 Guns
	<td>4 Guns
	<td>4 Guns, 1 Turret
<tr>
	<td>Outfit/Wep/Engine Space
	<td>240/60/70
	<td>260/60/80
	<td>250/60/80
<tr>
	<td>Cargo Space
	<td>10
	<td>70
	<td>50
<tr>
	<td>Crew Req/Bunk
	<td>3/6
	<td>3/9
	<td>2/4
<tr>
	<td>Fuel
	<td>400
	<td>500
	<td>400
<tr>
	<td>Price(Hull/Outfitted)
	<td>1.090M/2.012M
	<td>0.900M/1.270M
	<td>1.850M/2.660M
</table>

Headhunter is quite a lot better than Quicksilver in everyway(+800 shields, turret, more space) for just 660K credits more but even worse *Clipper* is just better for cost of 300 shields which you could probably make back with outfit expansion and bigger shield generators. In fact, I can outfit a Clipper to use 2 Particles like Quicksilver but also use biggest shield generator by installing 3 outfit expansion(no cooling needed), Radiothermal instead of Fuel Cell, and still have 40 spaces to spare (also while using a bigger battery than Quicksilver) and it sits at 2.135M outfitted, merely 125K above stock Quicksilver. Oh wait the turn is slightly less, anyway I can swap Greyhound for Impala steering and now it turns 28 units faster than stock Quicksilver, actually still faster than Quicksilver with A250+A255 atomics as well (by 8 units). So with that Clipper cost 2.178M total outfitted, a bit more than Quicksilver for everything + versatility of being able to just go back to merchanting whenever you want. The only thing Clipper is worse at is top speed and acceleration but nobody care about that when star systems are so tiny you can fly across it in like 10 seconds anyway.

Anyway as you can see Quicksilver is just worse than even a cheaper freighter *at combat* (and I may have accidentally proved instead that Clipper is just OP.)

### Related Issue Links

Talked about abit on Discord
https://discord.com/channels/251118043411775489/266345072554016768/1059575308493258852

### Desired Solution

Outfitted, Quicksilver probably should sell a bit cheaper, maybe 1.6M~1.8M or something so it might be more of a choice for cheap and combat effective ship.

### Alternative Approaches

Not sure how but maybe Clipper could be nerfed instead.

### Additional Context

-

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR fixes #8048 

## Fix Summary:
This reduces the hull price to 836k, which gives 220 credits per point of health, which is just slightly cheaper than the Hawk's 223 credits per point of health, inspired by the quicksilver description. This brings its shipyard purchase price from 2.018M down to 1.758M. Note that this is just cheaper *per point of health*. The quicksilver hull is still more expensive than a Hawk hull.

+5 cargo space means it is still inferior to every other human light warship or light freighter, but at least it won't be a downgrade from a sparrow now...

## Comments

This does not solve the problem that the Quicksilver is, overall, an inferior ship. There's really not a lot of reason to switch to it from a Hawk, and likewise if the player can afford any other light warship, there's not much reason to use the Quicksilver either. That being said, it's description flat out states that the main reason it's still around is that it's durability-to-cost ratio is really good, and the shipyard has a long term contract manufacturing these for syndicate security. That's as much as stating that this is an obsolete ship that is only still being manufactured at all because of corporate manoeuvring has guaranteed them sales for the foreseeable future. 

As such, I see no problem with this ship being outclassed by ships both above and below it. But even so, it should have a use, and being the cheapest available light warship *is* a valid use. It is, understandably, not a use that players will want to fly in for very long, but if they absolutely want to get out of their interceptor into something with a bit more durability and without sacrificing mobility or waiting to store up another million necessary for the headhunter... Then this ship has a use for them. 

That being said, this price point puts the Quicksilver in a unique spot, supported by its description: It's still vastly more expensive than interceptors, being double the price of most of them and about 70% more expensive than the Hawk, but it is also vastly cheaper than other light warships, with the rainmaker at 2.2M and the headhunter at 2.6M. 

Based on the description and utilization in-game, I feel that the Quicksilver is best kept as a bargain-basement light warship, as opposed to being a potential top-tier interceptor. I acknowledge that it does blur the line between the two.

## Balance

The intent of this fix is to help the Quicksilver better fit its main use in the galaxy at present without significantly altering the balance of ship utility. This fix isn't going to help the ship perform any better by any metric, and even the +50% cargo capacity boost is only enough to ensure that it isn't being outperformed by the Sparrow and Fury (both interceptors that have 15 cargo). It's not enough to even match the Hawk, let alone any of the light warships (which start at 20 and go up from there, quicksilver excluded). I don't expect a bump up to 15 cargo to material affect the balance of the ship, but it does ensure that the quicksilver retains at least sparrow levels of utility in terms of mission running or mining.

## Testing Done
compared to other ships and looked at it in game.

## Save File
n/a any pilot with >2M can test this in any shipyard that sells quicksilvers.

### CODE REVIEW

**Review by EjoThims — APPROVED** [review]

**Review by Hurleveur — APPROVED** [review]
I don't have much of a say in balance but I can say that I never used this ship, so its good that it gets a buff.

**Comment by Anarchist2** [comment]
I'd also swap out the radiothermal generator for a fuel cell instead. The Quicksilver has enough battery capacity to use one, and it reduces the sale price from 1.8 mil to about 1.5 mil.

**Comment by warp-core** [comment]
It doesn't really need the cooling ducts anymore.

**Review by warp-core — APPROVED** [review]
I just want to add that I do think the ability to carry two particle cannons is a significant upgrade over a Hawk.

**Pull request merged**
