### PR TITLE
New Syndicate heavy warship: the Vanguard

### PR DESCRIPTION
**Pull request by Pointedstick**
I didn't think there were enough heavy warships or enough variety in their offerings, so I created a new one: the Vanguard. It's basically a Protector with lots of guns instead of lots of turrets. You can use it as a close-range capital ship killer with Particle Cannons, Proton Guns, or Plasma Cannons, or turn it into a long-range bombardier. I rather like the 7 torpedo launcher configuration, myself.

### CODE REVIEW

**Comment by guillochon** [comment]
Very nice, I like the look!

**Comment by Wrzlprnft** [comment]
Good idea, nice look, maybe make the front grey "wings" next to the cockpit a little bit smaller

**Comment by endless-sky** [comment]
Can you add copyright information to the "copyright" file, too? (I'd recommend using the CC-BY-SA 4.0 license that most of the other art assets are under.)

**Comment by Pointedstick** [comment]
Done!

**Comment by thenerdfreak** [comment]
I like that idea, goes along with the Syndicate's ships being brutally effective. Looks almost too good to be a Syndicate ship though ;P

**Comment by Tufton** [comment]
So just for clarity's sake, is this the best way to try and add stuff to
the release version of the game?  Like where is the line between plugin/mod
and release?  Say someone makes a plugin with three new ships and a new
weapon that are balanced within the existing game.  What do they do?  Do
they make a pull request here and hope Michael merges it?  Do they post it
on the google group?  At what point does a user-created plugin become
something added to the game on Steam?

So far it seems like most of the stuff on github, besides this, have been
base functionality programming stuff and less content.  Meanwhile, the
google groups have a decent amount of ideas and new mods and ships and
art.  I love the fact that this game is community driven, but the
"community" seems very spread out among several different mediums (steam,
google, github, etc.).

Personally, I would just like a little guidance, because I would love to
contribute new content to the game, but there isn't really a process for
that (other than this apparently?)  Maybe we need some sort of formal
submission process if someone has a plugin that they think should be added
to the game?

**Comment by endless-sky** [comment]
If a new ship or outfit:

* is apparently well balanced (not overpowered),
* belongs in the main game universe (e.g. not Star Wars), and
* has graphics that won't look out of place,

then I'm willing to add it directly through a pull request. (Honestly, though, a plugin would be easier to test.)

I do look at ships and weapons that get posted on the Google forum, but most of those do not yet seem particularly well balanced.

**Comment by Tufton** [comment]
Oh great so you are looking at the forums.  Since you have tested most of
them out, I hope you wouldn't mind posting some comments or ideas to help
us balance our in progress outfits?  It's mostly 1-2 people commenting so
it's hard to get a real feel for a ship or outfit's balance, especially
when the creator tends to have a colored view of their creation.  Thanks!

**Comment by endless-sky** [comment]
@Tufton, I can try to be better at replying to new content when it appears on the forum, but bear in mind that this is just a part-time hobby for me, and the time I have available might better be spent working on bug fixes or code improvements instead.

**Comment by Tufton** [comment]
Of course I understand.  My biggest concern is that it is just going to be
hard to have a game driven by community content when we can't be sure what
is and isn't acceptable and all additions have to go through one person
with an admittedly limited amount of time.

Right now it kind of seems like you are the final decision-maker, so
everything currently has to go through you to be considered "balanced",
thematically appropriate, and graphically appropriate.  Obviously, this
puts a big burden on you, which ideally won't be the case.  Perhaps if we
had a series of stricter or clearer guidelines someone could draw up with
specific requirements it would raise the quality of submitted plugins and
reduce the time you or anyone else had to spend sifting through apparently
low quality user submissions.

Currently it appears that the best way to "balance" is to just make your
ship worse than the Bactrian or your outfit worse than particle
cannons/electron turrets/plasma turrets and call it balanced (when in
reality its just weaker and/or useless).  I think that limits the potential
for exploring new and unique ships and outfits that don't necessarily fall
on a straight power line somewhere between the Bactrian and Shuttle.  To
quote the League of Legends balance team, I think we need to be looking at
"strategic diversity" and encouraging players and modders (pluginners?) to
explore new methods of combat/trading/pirating/whatever by giving them a
diverse variety of ship and weapon types that are suited to different
styles of combat (or work in tandem with one another in unique ways).

The base game ship power progression all feels very straightforward (too
much so in my opinion), where you just consistently upgrade to the ship
with the most potential outfit space (through mass expansion or otherwise)
and mounts to match (First Ship --> Interceptor/trade fleet --> Mule/Aerie
--> Bactrian/Kestrel). Currently I feel like the only real strategic
choices are missiles (easily countered with anti-missile or just being in a
system with asteroids, plus ammo limits), fighters (too weak/too much
micromanagement without the UI to support it), or big guns and big shields
up close (bactrian/kestrel w/ plasma/electron/particle/quarg).

Sure there ARE other choices, but they all feel weaker.  I have trouble
seeing why I would use any other setup.  Sure maybe a gigantic horde of
Aerie's (second most powerful light warship behind Mule IMO) filled with
fighters may be pound for pound stronger, but A) managing and replacing
100+ fighters is an obnoxious amount of micromanagement (naming every one,
customizing, deploy, undeploy, replacing lost fighters, RIP CPU) and B) I
can just load up 3+ Bactrians/Kestrels with Hai shields and take on pretty
much anything in the game short of the Quarg until I pick up Quarg
outfits.  It's not like the AI is going to bring 200 fighters to overwhelm
me, they will generally just sit and face trade with me until the stronger
ship (me) inevitably wins with little strategic investment or pre-planning.

Anyways, any input you or anyone else have on these things would be much
appreciated.  I think all of us making plugins out there would love to be
able to efficiently add content to the base game, but it currently feels
like spinning our wheels in the mud, so to speak. Thanks for reading my
wall of text!

**Comment by Pointedstick** [comment]
Michael has been very open to reasonable, evidence-based balance changes, and I particularly agree that the Mule is the best light warship hands-down. If you submit an issue and make your case, he'll listen. I recently got the Bactrian, Falcon, and Protector changed this way.

The deeper issue here that having a lot of outfit and cargo space is an inherent and nearly overpowering advantage. The limitations on weapon and engine space are intended to differentiate ships and reduce this advantage but I think we can all see that it's not working quite the way it's supposed to. Perhaps the problem is that ships with a lot of cargo and outfit space like the Mule and Bactrian simply have too much weapon and engine space.

**Comment by Wrzlprnft** [comment]
there appears the problem of the different sites again. good ideas might get lost in the flood of ideas in steam e.g

it's hard to balance, too. i personally think it is also important WHEN in the story it becomes available.

the overall problem of choosing between cargo, weapon, and engine space doesn't apply our two little problem-kids(ships). But that's their strength
If we constrain them via energy
(the ships are huge compared to others of their class... or at least they are meant to be,
so maybe you should loose lots of energy while transferring it through the ship, another attribute maybe(this just came up while writing, ill think over this idea more carefully and maybe making an issue))
or on another way, it might get too complicated

**Comment by endless-sky** [comment]
My long term plan for people adding new ships, etc. is to have a plugin
registry web page that collects all new content people have created, in a
single place. Initially you would have to download and install plugins
manually, but eventually the game itself will be able to pull the list of
plugins from the web page and let you choose which ones you want to
install. Eventually there could even be a voting process for getting some
of those plugins "canonized" in the game data itself.

**Comment by Tufton** [comment]
Sounds like a good plan for sure, but it seemed like the original goal was
more about community contribution to the creation of the base game, not
just modding (at least in this early stage).

It seems like there are grand plans for this giant galaxy-wide universe
with numerous storylines, alien species, ships, weapons, etc etc, but we
have no reliable method to contribute content to the base game besides
submitting stuff through pull requests, which generally speaking would
become obtrusive if that became the go-to for submitting proposed content.

Moving away from ships and weapons for a second for the sake of diversity,
what happens if someone writes a big beautiful storyline?  Where do they
upload it?  The forums? Github?  Would it be incorporated into the game or
would it just be "Bob's Quarg Storyline" that I could get off the steam
workshop (or equivalent)?  Is the only way for that to happen for Michael
personally to comb through Bob's story for balance, appropriate content,
thematic uniformity?  Would Bob submit a gigantic pull request?

Absent some more elegant solution, maybe Michael  should just put out
"Content Requests" specifying what it is they need ("heavy freighter with
more engine space and a cloaking field [whatever]" or "korath storyline
exploring their history").  That way we don't have people unknowingly
duplicating efforts, we don't have people wasting time balancing things
that won't be in the game, and we wouldn't have to bug Michael every time
we thought we had a good idea.  At least for content.  The programming and
base code seem to be well served on GitHub.

For now it appears that the answer is "put it somewhere and maybe something
will happen".  Considering the relatively inactive forums, it makes me
worry that the community will lose motivavtion/interest with the game and
with generating new content, which leaves us with a great base game that
fizzles out and goes nowhere unless a small handful of people keep putting
in significant amounts of effort.  I don't want that to happen because this
game has been needed since EV Nova was released a million years ago.

**Pull request merged**
