### PR TITLE
Outfitter Hotkey/GUI Rework

### PR DESCRIPTION
**Pull request by FurretGoWalcc**
**Feature:**
This PR is my attempt to solve issue #8735 as discussed somewhat at https://github.com/endless-sky/endless-sky/discussions/8761#discussion-5199793. As a quick summary, this PR had two mains goals

- Change backend of the outfit trading system in OutfitterPanel & ShopPanel (which led to altering ShipyardPanel slightly) to allow more specific control of outfit sources and destination (e.g. allowing for storage->install, even when there is cargo of the same item).
-  Introduce a GUI system using this new backend as an example solution.

On the whole, I feel that these commits do a solid job of meeting these two goals. The GUI system is not perfect, but it's a decent stopgap for when someone comes along with a better idea.

## UI Screenshots
*Before:*
before
*After:*
after

## Feature Details
- Replaced the Outfitter Key with the 4 options of swapping the source of the outfits. These four buttons are mapped to q,w,e,r, with the top being 'q' and bottom being 'r'.
- Related to the above, I stretched the outfitter key sprite horizontally by 20 more pixels, and pasted the detailing on the top and rightside so it did not mess up the aspect ratio. I think it looks okay, but someone who is more skilled in this may want to properly extend the sprite instead.
- Resized and Added a button in the bottom right corner. There are now 3 buttons, with 4 options representation the 3 destinations that can be selected (Install = 'i', Store='u', Sell='s', Cargo='c'. The sell button will initially be invisible (as the default source is the store, selling wouldn't make much sense), but as you change the source, the sell button will shift around to fill the space of the new source.
- Most of the backend involving trading has been unwinded out of CanBuy and CanSell into several new functions CanUnique, CanSource and CanDestination, which switch() based on characters. This means that it's now easier to alter pieces of the logic which relate specifically to uninstalling, buying, selling...

## Testing Done
- I have only lightly tested this. I would appreciate it if the code herders could do some fairly tough testing on this, specifically when using modifier keys and installing/uninstalling from multiple ships. Testing of edge cases like crew counts, ammunition + moving launchers around, and licenses would also be appreciated.

## Performance Impact
Honestly, not sure. Most of the actual logic I added to the backend is very similar if not directly copy-pasted piecemeal from CanBuy, CanSell, Buy, and Sell. If a player is uninstalling/installing to many ships using modifiers, the repeated calls to CanTransactionHandle may start to have a real performance impact. 

To create the moving sell button, I also had to a few lines of logic to the button hovering, and drawbutton functions. I don't anticipate that being the cause of performance issues, but I'll have it noted.

## Additional Notes
These are some things I noticed while poking through these files but did not feel changing them as part of this PR was appropiate. 
- The bool forceCreate related to storage seems badly named, as it is seems to be less of forceCreate and more of the only way to createStorage if it does not already exist.
- I wasn't quite sure what to do with ShouldHighlight, which is a function which highlights ships. Initially, it was highlighted whenever someone was hovering over the "buy" or "sell" keys and a ship could add or remove the selected outfit, but with the addition of the third key I am unsure what should justify a highlight.

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
Do you need any help with fixing code style errors?

**Comment by bene-dictator** [comment]
> Sure. I'm stepping away from this

I'm taking this to mean that the PR has been orphaned for the time being, though it would be a nice addition if someone could take the time to complete it.

**Comment by xobes** [comment]
I would like to contribute to seeing this or something like it finished.

I would like to suggest that the filters for what is displayed, however, do not include verbs.  They are filters of what to show.  The actions of what to do with those things is myriad and handled elsewhere.

I'm picking this up.  Wish me luck.

**Comment by TomGoodIdea** [comment]
Removing the "orhpaned" label as #10743 is in development.

**Pull request closed without merging**
