### PR TITLE
Make the Coalition solars use Solar Heat

### PR DESCRIPTION
**Pull request by Arachi-Lover**
----------------------
**Content (Stats)**

## Summary
Just changes the Coalition's solar panels' `heat generation` to `solar heat`, which was pointed in the Discord to be more appropriate since it'd scale with the solar collection, rather than being a constant heat.

### CODE REVIEW

**Review by Zitchas — APPROVED** [review]
Looks like an appropriate change.

**Review by EjoThims — APPROVED** [review]
Makes perfect sense to me

**Comment by Zitchas** [comment]
I'll just note here that this will make the heat produced more variable: As high as 3 per outfit near the center of the system, and as low as 0.3 on the outskirts; with potentially greater variation possible due to different stars. I assume this is intended, since that's literally the definition of what `solar heat` does; but just noting it here so no one is surprised when these panels sometimes generate 2x the heat that they used to make.

Since this is the first addition of anything with solar heat to the vanilla game, I'll just include the current documentation description for future reference:

> "solar heat": the amount of heat that this outfit produces when your ship is 1250 pixels from the system center. As with solar collection, heat increases up to two times this value the closer you are to the system center and decreases down to 1/5 of this value the farther away you are. This value will also vary based on the [solar power](https://github.com/endless-sky/endless-sky/wiki/MapData#solar) of the star(s) in the current system. (v. 0.9.12)

**Comment by Arachi-Lover** [comment]
I made the change to my files and hopped ingame before PRing. Highest heat level of (civilian) Coalition ships that were jumping in was about 3%, so even if they went right on top of the sun it wouldn't be an issue I figured.

The Heliarch Fighters might be impacted more noticeably, but I don't expect this'd render them useless in combat situations. If we find out it does, will adjust them.

**Pull request merged**
