### PR TITLE
fix(content): Make Nanachi pre-HR requirements not encourage mega fleets

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR addresses a balance issue with the Nanachi accessibility.

## Problem
The Nanachi missions are designed, I gather, with the primary aim of being post Hai Reveal content. This is fine. They have an alternate criteria that allows them to be accessed prior to Hai Reveal, namely acheiving 2B Networth along with a combat rating of 1200. Now, the combat rating of 1200 is "seasoned fighter", which seems like an appropriate skill level for the mission. 

The Networth, though... Well, just taking a look at things. Right now, the biggest, most expensive ship I can buy is the Shield Beetle, and that's a bit under 34M. To achieve this networth, I'd need a fleet of almost *sixty* of them. (to be exact, 59 Shield Beetles and one additional >12M ship). 

Just to be clear, Networth includes bank balance. So it *could*, I think, be satisfied by someone flying a shuttle who happens to have 2B credits in the bank who happens to have actually put that blaster to exceptionally good use. Possible, but I don't even want to think about how much time it'd take to earn 2B with nothing but a single shuttle.

The general principle we balance around is the expectation of a player flying solo. When we talk about balancing around the player flying fleets, it's generally assumed to be 1-6 escorts, maybe as many as 10, tops. While yes, people can and do sometimes build up massive snowball trading fleets with hundreds of ships, this comes up again and again as a problem to be solved. 

Here in the Nanachi missions, though, we have a situation where we have set up the trigger conditions such that - if someone wants to do these missions prior to Hai Reveal (and, by extension, without doing the FW campaign), then the only option they have is to build up exactly the sort of fleet that we keep labeling as OP and being a problem. We should *not* be giving people additional reasons to build up fleets the likes of which we don't really want to see and keep talking about putting in places measures to discourage.

## Fix Details
edit: originally this simply dropped the requirement from 2B down to 200M. It has since been revised further.

Currently, this reworks the offer conditions so that it requires the player to have a combat rating of 1200 and a networth of 20M, and to have met the Hai, as a baseline.

On top of that, the player needs to have one of two conditions: Either the Hai have *not* been revealed to the human public; or the Hai-human relations have been successfully resolved. This blocks the Nanachi missions from taking place *during* Hai Reveal, but allow it to be equally accessible before and after.

## Clarification

I'm posting this as a bug/balance report and solution in one; so I'd appreciate hearing from those responsible for Nanachi and the Hai missions as to why they chose such a massively high number. If there's other options that serve their purposes better, I'm open to them.

## Alternate
1. Given that I don't think we should ever encourage trade snowballing with targets like this; if this is meant to be a "Really should only happen post HR but we wanted to give a chance at it happening prior to it", then I think we should just drop the NW requirements and replace it with something like a `random < 2`.
2. As another alternative, one could shift the focus to *experience* rather than wealth, and put a time check there. How many years experience would be appropriate? 5, 10? Presumably this alternate is there to give people a chance to see it who haven't done (or perhaps who failed) the main story missions, so a time check would fit that really well.

For example, my current playthrough, I recently discovered and explored Hai space, and I'm in June 3019. That's what, about six years of in-game experience? That's *probably* enough to provide Nanachi with a bit of guidance... (especially if I had the 1200 combat rating, which I don't. Probably another couple years before I achieve that)

I'll be happy to modify this PR to either of those two alternates if people (particularly those focused on the Hai) prefer them.

### CODE REVIEW

**Comment by warp-core** [comment]
Reading your summary, it looks like you're saying net worth is the sum of the value of a player's ships (including outfits)?

**Comment by Zitchas** [comment]
Well, if I'm not mistaken it also includes total credits, too. But yeah, interpreting it mainly in terms of tangible assets. Not sure if depreciation impacts it or not, though.

**Comment by Hecter94** [comment]
This seems appropriate. I checked the original PR and didn't see any reason why the net worth requirement is as high as it is, though I'd like Arachi to take a look and perhaps provide some clarification if there is a specific reason.

Even 200m seems a bit high? There's only one fight in that mission chain that I can see, and it's against:

```
		ship "Marauder Firebird (Hai)" "Nut King Call"
		ship "Marauder Splinter (Hai)" "The Nutcracker"
		ship "Marauder Quicksilver (Hai)" "Hazelnut's Bane"
		ship "Marauder Bounder (Hai)" "Rodent Hunter"
```

For comparison, that fleet is worth ~40m credits. Assuming the player only has about half their net worth invested into combat-capable ships, an equivalent net worth would be ~80m. It could possibly be bumped up to 100m to ensure a little bit of wiggle room for players that are heavily inefficient in their spending or have a lot of parked ships elsewhere. 

Though a more open-ended question, what purpose is that check serving? Is it for balance purposes? Story purposes? Do we need the player to be sufficiently rich to mentor Nanachi? Are we trying to block players that may not be ready to start the mission? If so, `armament deterrence` might be a better condition to check.

**Comment by warp-core** [comment]
> I'm posting this as a bug/balance report and solution in one; so I'd appreciate hearing from those responsible for Nanachi and the Hai missions as to why they chose such a massively high number. If there's other options that serve their purposes better, I'm open to them.

The previous requirement was only 20 million, Hai Reveal changed it to the current conditions.

As for "net worth", see the player conditions page of the wiki.

**Comment by Zitchas** [comment]
Quoted from said page:
> "net worth" is your net worth, the sum of the worth of all your ships and outfits plus your current account balance minus any outstanding mortgages, fines, salaries, or maintenance.

That seems pretty much in line with what I understood it to be. Nice to have a definition, though. Thanks!

Anyway, increasing it from 20M to 2B seems rather... drastic... shift. I'm curious as to their thought process behind picking that value.

**Comment by Hurleveur** [comment]
The cultural convos should be there too? Granted those don't require you to do anything though.

**Comment by Arachi-Lover** [comment]
The Nanachi missions were made before Hai Revealed was even in concept form, so they weren't designed to be done afterwards, but even if they had been 2B is just too much. As is 200M. I assume it was some odd mistake to add in the 2 extra 0s, but I'm in favor of just having the networth requirement be the original 20M.

**Comment by Hurleveur** [comment]
Why would it matter if this happened before HR actually? Shouldnt it be changed to just not happen in the middle of it?

**Comment by Zitchas** [comment]
I'm slowly working my way towards actually playing through HR, so I'm a little ignorant of the story there. If Nanachi missions are fine before *and* after, is there any particular problem with them happening during? I've got the impression that HR is more like a small campaign, and, well, I do *lots* of missions during the FW campaign, I don't see a problem with that, either.

**Comment by MasterOfGrey** [comment]
> I'm slowly working my way towards actually playing through HR, so I'm a little ignorant of the story there. If Nanachi missions are fine before _and_ after, is there any particular problem with them happening during?

Parts of the Nanachi mission chain would be impossible/illegal during certain parts of the HR campaign, so it should only be before *or* after for safety.

**Comment by Zitchas** [comment]
Based on #7889 , reworked the restrictions to more properly reflect that it can be accessed before or after Hai Reveal, but shouldn't take place *during* it. 

Changes: 
- both sides have required net worth, and it has been reduced back to the original 20M that it was prior to Hai Reveal changing it.
- both sides have the required combat rating.
- both sides require Hai first contact.
- the `or` part is that the player needs to either **have** the hai-human resolution announced event, or **not** have the "hai secret leaks" event. This effectively locks this mission from happening during Hai Reveal.

It now looks like this:
```
	to offer
		random < 15
		"net worth" > 20000000
		"combat rating" > 1200
		has "First Contact: Hai: offered"
		or
			has "event: hai-human resolution announced"
			not "event: hai secret leaks"```

**Comment by warp-core** [comment]
The order of the final two conditions could perhaps be reversed to reflect that secret leaks comes first and should block this mission until the later event occurs, unblocking it.

**Comment by Zitchas** [comment]
As a general note, I'm continuing to work on this PR in the face of 7889 because that one has fixes for a whole range of stuff, including some things (like the situation blocking the Wanderer story) that seem quite a bit more complex and/or the subject of discussion. As such, I don't know what it's timeline looks like. Potentially long, as stuff continues to be discussed. In contrast, this PR just fixes a single thing, and it looks like we've got all the feedback so far rolled into it, so it shouldn't cause any problems or interfere with other stories; and as such is ready to go.

**Comment by warp-core** [comment]
Since this is being addressed now anyway, without a reason for increasing the net worth requirement, the changes made in this PR seem better than the other one to me (that one requires 200M both before and after HR. It may have been ok to make it higher before HR if, for whatever reason, you wanted it to be more difficult to start this chain before HR, but no such reason has been given (as far as I know) so restoring the original value, a point person might reach if they have, or at least can afford, a human heavy warship seems reasonable given the missions themselves.)

**Review by Hurleveur — APPROVED** [review]
I'm all for restoring that 20M and just making it not trigger mid campaign, that seems to make the most sense and reactivates one mission in the pre-HR hai space which could use it tbh

**Review by warp-core — APPROVED** [review]

**Pull request merged**
