### PR TITLE
Update to libpng 16.16 aka 1.6.18. It is newer and seems to work fine…

### PR DESCRIPTION
**Pull request by dreness**
…. Supported by Brew (brew install libpng).

Is there a reason not to update to 1.6.18? If you'd like to take this, I can also update the docs.

### CODE REVIEW

**Comment by guillochon** [comment]
I verify that 1.6.18 also works fine for me.

**Comment by guillochon** [comment]
Just another appeal to merge this in, I always prefer to have the code match the latest brew stack rather than having to install custom libraries into /usr/local.

**Comment by endless-sky** [comment]
I'm treating the 0.8 series or releases as a "stable" series, trying to focus on bug fixes and minor changes in order to reduce the risk that I'll introduce some new system incompatibility that will break things for those 100,000 Steam users. Because of how relative linker paths work on the Mac, it's unfortunately very easy to think a new library is working but to have the app fail to run when installed on other computers.

Once it appears that all the bugs in the 0.8 series are out, it'll be time to switch to "experimental" releases that introduce bigger changes. At that point I'll need to add some new libraries anyways (e.g. for mp3 decoding, full Unicode text rendering, etc.) so that's probably the point where I'll make any upgrades to the other libraries.

**Comment by omagasohe** [comment]
@endless-sky 100,000 steam users, that's pretty epic for a hobby. Thank you for being kind and trying to keep things stable. I've seen too many projects that fall apart because the bugs get unmanageable.

**Comment by dreness** [comment]
+1 for not disturbing all those steam users :)

**Comment by frameworld** [comment]
I prefer a game that works with older libraries if your Linux-distro doesn't ship with the latest ones.
(( Or the linux-version of something in general. ))

New dependencies should be optional if possible. The easiest way to get everyone happy would be modules that can handle multiple versions of something.

**Pull request closed without merging**
