### PR TITLE
New minable type

### PR DESCRIPTION
**Pull request by Amazinite**
From #1973. I'm PRing now because I've finished all the debris sprites. Hopefully I can get feedback on just this while damaged outfits are being worked on

I'm currently missing the Boxwing because for some reason, it crashes my Blender to try and open. 

Help received from @Wrzlprnft in getting some of the rotated sprites, and he made the really banged up look of the Hawk. 

To Do:
- [ ] Finish the Boxwing
- [ ] Create damaged outfits for debris to drop
- [ ] Put the minables into systems
- [x] Balance the hull of these minables (currently the hull is equal to that of the ship, but that is really low compared to normal minables). **Ship debris now has 5 times the hull of the ship it comes from**
- [ ] #1450 so that picking up damaged outfits displays the proper mass of the cargo picked up

### CODE REVIEW

**Comment by Amazinite** [comment]
#1450 needs to be done if we're using damaged outfits.

Speaking of which, what should the naming scheme be for damaged outfits?

"LP036a (Damaged)"
Or
"Damaged LP036a"

Or does anyone else have another suggestion other than just putting "damaged" in all of the names. (A list of all the outfits we are going to make damaged versions for is in #1973.)

**Comment by DingusShingleton** [comment]
The only thing you can do with this stuff is sell it, yeah? What if they all just had the same name? damaged outfit, or salvaged outfit, regardless of what it is. You can see the sprite, what it's based on, if you know what that sprite is, but having them all named the same signals to the player that yeah, these are just for selling to get some extra cash.

Just a thought.

**Comment by Amazinite** [comment]
I like the idea, b the problem is that outfit variants don't exist. :/

**Comment by Amazinite** [comment]
#1998

**Comment by egilburg** [comment]
Is it not possible to just provide a single direction for mineables, and have the game auto-rotate them, the same way ships currently work? CC @endless-sky

**Comment by Amazinite** [comment]
Why? That's boring.
Plus, I'm pretty sure that asteroids already rotate like ships but the extra tumbling is cool.

**Comment by EndrosG** [comment]
I have a few questions and some sort of suggestions in the end.

When I had a first look at the minable definitions, and did not really read this PR clearly, I thought: This guy wants to create flotsam of type "hull debris" when the ship explodes.
What came to my mind was: add a ship tag "final debris" "<hull debris outfit of that ship>" and place it (in terms of readability) just below the "final explosion" tag.
That would have been easy to code by extending the following code section:
https://github.com/endless-sky/endless-sky/blob/master/source/Ship.cpp#L811

Then, I was concerned that the 5x hull of the new minables can result in a larger payload than the original hull.

But then I stuggled amongst some "errors".
First, those minable definitions - i.e. the "asteroids" - but not their payload. I.e. when you destroy them, they give nothing.
Second, since those define the "asteroids", the 5x hull is "wrong" imho. If I just destroyed a ship with 400 mass, why TF does the debris have a hull of 2.000 to be destroyed / cracked before it will drop any payload?
Third, the linked ship code already uses .07 of the actual ship mass for some smoke effects.
>				const Effect *effect = GameData::Effects().Get("smoke");
>				int debrisCount = attributes.Get("mass") * .07;

It seems wrong to convert the entire ship into a minable then if some stuff already smoked away. Note: the smoke depends on the "mass" not on the "hull".

So, I thought again about what your original intention might be and how it might look like in terms of a full definition.

```
ship "Arrow"
	sprite "ship/arrow"
	"final explode" "final explosion small"
	"minable debris" "arrow debris"

minable "arrow debris"
	sprite "asteroid/debris/arrow/spin"
	hull 320 ---- comment: i.e. 80% of the original hull, I suggest even lower values since the hull has already been destroyed once. So may be just 25% - 50%.

	payload "Aluminum" 20 ---- comment: arrow = transport = civilian spacecraft, thus aluminium, otherwise titanium

	payload "damaged Hyperdrive" 1 ---- comment: maximum of 1 item dropped, with 25% chance
	payload "damaged A250 Atomic Thruster" 1 --- again, 25% chance
	payload "damaged A255 Atomic Steering" 1 --- again, 25% chance
	payload "damaged Dwarf Core" 1 --- again, 25% chance
	payload "damaged Supercapacitor" 1 --- again, 25% chance
	payload "damaged Sidewinder Missile Launcher" 2 --- the vanilla ship contains has two of these

	explode "smoke" 20
	explode "bolide" 20
	explode "final explosion small"
```
now... this might work well with vanilla ships as they are used by fleets and most NPCs.

*What happens if an escort explodes?*
An escort might have a Jump Drive installed, but the debris definition contains a damaged Hyperdrive.

*Position, Movement and Lifetime*
- The current minable class only has orbital placement. Can be changed, though. Place that thing just ontop of the exploding ship.
- The current minable class only has orbital movement, i.e. your debris have some excentric orbit around the star / stellar object.
- Do you want some max lifetime for the debris? Or shall it stay there for ....... (until you leave the system / land on a planet)?

*Thoughts*
- Wouldnt you maybe want a rather some sort of movement straight away from the ship (accelerated by the hit force of the final explosion)?
- Your approach does not use "chunks of ...", i.e. you have one main debris, so there is no need to generate e.g. 6 minables moving away from the center of explosion into 6 different directions.
- Would you maybe want a dynamic mineable? [1] Having it's hull depend on the mass of the parent ship or on the `MinimumHull()` for disabling a ship? (derelict starts with half of the MinimumHull()) and [2] having payload depend on the currently installed outfits, and finally [3] may be adding some aluminium or titanium relative to the empty ship mass.
- have classes of damaged outfits:
1. "damaged thruster element [1 ton]" (do not apply to exotic thrusters, just to all sorts of compatible systems)
2. "damaged battery component [1 ton]" (do not apply to some bio gel packs)
3. "fuel cell debris [1 ton]" (for all fuel cells)
4. "shield generator debris [1 ton]"
etc.
- Append "debris" tags to the respective outfits
>outfit "D14-RN Shield Generator"
>	category "Systems"
>	"mass" 15
>	debris
>		"shield generator debris [1 ton]" 15
>outfit "D23-QP Shield Generator"
>	category "Systems"
>	"mass" 22
>	debris
>		"shield generator debris [1 ton]" 22

This is, if you invest more into coding, you can invest less into endless definition files.
As long as minables are not targetable, you dont even need a full "minable" definition, only the sprite. I.e. you could - when ships explode - query for a "minable debris sprite" attribute and add all attributes dynamically (sprite: as defined in the ship, hull: suggested above, payload: suggested above, explode: it's up to you).

And I would really stay with the 25% chances which are currently defined (a) for flotsam drops upon explosion of ships [code linked above] and (b) for payload drops of minables [code: https://github.com/endless-sky/endless-sky/blob/master/source/Minable.cpp#L135

**Comment by EndrosG** [comment]
Interesting thought after the previous comment and it's 27 edits:
`"minable"` in combination with `removable -1` (I currently prefer removable over unremovable because we have installable and not uninstallable...) could even be used in the outfitter. If you really try to remove an unremovable outfit and if it has a minable definition (but only then!), then remove it and add the minables. If the minables are installable, which I still prefer, install them, otherwise into cargo. If an outfit is `removable -1` and has no `minable`, then really dont allow to remove it in any way. --- You can remove that cloaking device from that Arfecta ship, but you will only get some [payload "Neodymium" 5].

**Comment by EndrosG** [comment]
Dang, there is something in #1973 which I didnt read. #1973 says
>appears in remote systems, yields appropriate materials...

So the original proposal was not having them spawn upon ship explosion but having them spawn "naturally" or upon events.
Regarding events, e.g. defeating the Sestor fleet in Alnair (?), some Syndicate fleet or something in the FW campaign, I would assume a fixed / limited number of such minables - as the fleet you defeated was limited in numbers. Minables (asteroids) currently reset/respawn with each landing / system entering.

If somebody wants a ship remnant full of broken / damaged outfits, which the player can extract from, I would probably suggest defining a mission, like the current "drag guarding" missions (or like "FWC Pug 3D: Reinforcements" from the FW checkmate file), but with a proper defined derelict ship which has the damaged outifts in cargo space and not equipped. i.e. ship with attribute selfdestruct 1 (will always selfdestruct if you try to board it because it is already breaking apart), minimal hull left, dropable outfits in cargo = 25% chance for them to get dropped = consistent to what I wrote in the previous comments. And "permanent" in terms of savegame status but "unique" in terms of not respawning.
Obiously/sadly, ships do not have an (excentric) orbit around a stellar object and thus would not move like an asteroid. And they are targetable. Something like "remnant/debris of R.N.S. Kenya" would make a nice name then?
Ships can have animated sprites too, e.g. the shuttle.
Ships (if not fully derelict) could eventually even achieve some other behaviour: Eradic movement is part of the game code. Having a Bactrian with 1 crew (70 required), staying personality, ... could allow for some potentially interesting movement patterns. Boarding failes with selfdestruct (computer malfunction, systems too damaged to recognize this as friendly assisting attempt or whatever).

**Comment by Amazinite** [comment]
Given that this PR has been left to collect dust, I'm going to close it, but I'll open a new PR when this is actually done.

**Comment by TheGiraffe3** [comment]
@Amazinite what is the status on this? It was closed because MZ wasn’t paying attention, but more people have write access now.

**Comment by Saugia** [comment]
If a PR is closed or merged, that means a given decision is made. Amazinite here has said he has plans to open it up again someday. We generally avoid discussion once they have been closed.

**Pull request closed without merging**
