### PR TITLE
Slow turrets

### PR DESCRIPTION
**Pull request by ItsNickBarry**
Turrets must now turn to face their targets, and will begin firing when within 10 degrees of their target.  Turn rate is determined by a "rotation speed" attribute on the turret outfit.

Rotation speed is measured in degrees per frame.  This is kind of arbitrary, but makes the set of reasonable values rather convenient (about 1 through 5), and saves a few thousand multiplications per second.  Arc-seconds per second-second was a close second.

I've set rotation speed to 3 (180 degrees / second) for all turrets, as a placeholder.

### CODE REVIEW

**Comment by Alkallid** [comment]
Since some turrets, like human lasers and pulse seem to be meant for tracking quickly, do you think that _this_ would be the redeeming value of the Electrons? All alien lasers (besides maybe Quarg) would have a much slower turn speed, and human stuff is weak enough to help justify fighters! Anti-missile instant turn, and mass-ier guns slower, save the Pulse.

**Comment by toilethinges** [comment]
Yeeeeesssssss!

**Comment by egilburg** [comment]
when they begin firing after being within 10 degrees, are they aiming at their current angle or actually aiming at the ship?

laser turrets, for example, would always miss unless aimed exactly at the target, and thus should fire when directly pointing at the target rather than within 10 degrees

**Comment by lehgogh** [comment]
@egilburg Plus, it would look weird to have a laser miss the ship, but still stop slightly behind the ship.

**Comment by ItsNickBarry** [comment]
@Alkallid Certainly all turrets shouldn't have the same rotation speed of 3, but I think setting different values and rebalancing is a separate issue.

@toilethinges Indeed.

@egilburg Part of the reason for the arbitrary value of 10 degrees is that turrets have crew requirements, and are presumably fired by humans.  Also, the target ship takes up more than 0 degrees, so it makes sense to fire even when not aiming directly at its center.

@lehgogh That's a good point, but the same should be true for fixed lasers and other weapons.

**Comment by LocalGod79** [comment]
expressed as desired in #906 by @endless-sky

**Comment by LocalGod79** [comment]
if the angle is not specified, is the turret unable to turn?

**Comment by jmhorjus** [comment]
Firing within 10 degrees should be fine even for lasers.  Depending on the range and the shape of the target your aim can be off by quite a bit from the center of the target and still connect with it. 

However I need to try this for myself.  

I really hope this will make being agile more worthwhile in combat, if it allows you to avoid some portion of turret fire.

**Comment by ItsNickBarry** [comment]
@LocalGod79 Yes, turrets without a rotation speed cannot turn.  I'm not sure what the policy is for default values.

@jmhorjus Agile ships do take less fire, though I don't think skillful piloting is much of a factor.

**Comment by ItsNickBarry** [comment]
`rotation speed` is now a property of `weapon` rather than of `outfit`.  `Weapon::RotationSpeed()` returns `3` if no value is given in the data files.

@endless-sky Should I keep working on this?

**Comment by toilethinges** [comment]
Weapon slowing effect? I think I've seen that requested a few times.

**Comment by LocalGod79** [comment]
indeed - as a measure to make fighters and other small ships "more balanced" - until the Southern Carriers came along and showed everyone what a mass of tiny ships can do...

**Comment by onnikyla** [comment]
The rotation speed doesnt relly make sense in my mind. Its the thirtyfirst century. surely in 1000 years they have found a effective way (good magnets for example) to turn a turret quickly.

**Comment by jafdy** [comment]
It's a balance thing.

**Comment by LocalGod79** [comment]
rather an "unbalance" thing.

with the introduction of missile tracking, and wider fighter/carrier availability, i believe that further penalizing large ships might be uncalled for.

**Comment by LocalGod79** [comment]
also, with https://github.com/endless-sky/endless-sky/commit/6e5aebcb90d11e36af0b3860b5ec33955f5107f8 , one can simply add confusion to larger ships/turrets, and accomplish essentially the same thing...

**Comment by LocalGod79** [comment]
lastly, while this may seem a minor change, it seems to be missing the fw storyline rebalance - unless it's been tested "from the perspective of a new player", already...

**Comment by jmhorjus** [comment]
I still really like this idea still.  Infinite turn speed on turrets weighing tens of tons only makes sense as a concession to simplify the game; it has no "realism" benefit.  

As far as balance, asking if this is "good" or "bad" for balance because it might make some particular perceived problem "better" or "worse" is totally the wrong question.  The right question is not "will this make balance *more interesting*?", "will it allow for balance to be expressed in new wqays?".  A new mechanic like this is not just a "fix" for balance; it's potentially a whole new dimension of balance.  It's a new *tool* in the balance box, which of course can be used well, used poorly, or (probably at first) hardly used at all.  

But in my mind a new tool, especially one so intuitively rooted in the physical reality of the things the game is supposed to be depicting, is never ever a bad thing.

**Comment by jmhorjus** [comment]
@endless-sky  It saddens me how many great ideas for this game, even when they are good ideas with a fully functional pull request behind them, still get left by the wayside indefinitely and for no stated reason. This pull requests is sitting here accumulating merge conflicts while its creator appears to have long since lost interest in the game. The PR's creator is a coder who (a) was competent enough to create this change, (b) liked ES enough to be motivated to actually envision, design, implement, and test a game-mechanics upgrade like this by himself, and (c) was clearly willing to keep working on it until it met your standards.  Yet three months after he asked you directly **"Should I keep working on this?"** there is no answer. Why? 
I mean if your really don't like an idea you can just say so...I think it would be better than being ignored. :( Personally I think this PR is a great idea and said so like 10 weeks ago ((1) it adds to realism, (2) it's a brand new tool for both balancing and differentiating different gear, (3) turrets could be given a fast default turn speed so as to not interfere with existing balance concerns at all). Is there any chance of this idea being resurrected?

**Comment by KiLEdEnNis** [comment]
@jmhorjus MZ said he doesn't want turn rate for turrets, idk what reason exactly, something about that slow ships would suffer even more

**Comment by endless-sky** [comment]
In the case of this commit, it's a rather major change to the game mechanics, and once a change like that has been made and game content and plugins start to rely on a certain feature existing, it's a lot harder to change. So when something like this is added, I want to make sure that the way it is implemented makes sense and isn't going to need further changes somewhere down the road.

Minable asteroids are a good example of that: there were pull requests for a variety of very kludgy ways of implementing them, but rather than merging any of those I waited and weighed different options and recommendations until it seemed to me that there was a clear solution that handled *all* the technical issues at the same time, rather than just some of them.

**Comment by KiLEdEnNis** [comment]
I thought that what I said was a reason too, personally I don't mind them that much because I always try to get a turn rate above 70, around 90-100

**Comment by jmhorjus** [comment]
@endless-sky If you did glance over @ItsNickBarry 's ~40 lines of code and found it to be "very kludgy" it'd have been nice to let him know that three months ago when he asked is all. He was actively engaged with the project at the time, and very likely would have been willing to improve his code or refactor it if asked. 

Thanks for responding to me right away this time though. I'm sure your own re-implementation of turret rotation will be truly superior when you finally get time to do it. You're an awesome engineer, and of course your own code always fits perfectly in your own code-base. But you're still just one guy...it's a lost opportunity when other willing hands sit idle or drift away like this.

**Comment by Pointedstick** [comment]
This feature has now been implemented in an official manner (along with awesome turret sprites). Can we close the PR?

**Pull request closed without merging**
