### PR TITLE
Applying Damage to Plundered Outfits

### PR DESCRIPTION
**Pull request by brazencavalier**
This is my first contribution to the project, I don't think I'm duplicating anyone else's issue/pull request but I apologies if I am or am in any other way breaching the contribution guidelines.

**RATIONALE**

The value of plundered outfits is quite high, making a militaristic approach to money-making (especially later game) far more valuable than trading. Not only does it limit available play styles, but it doesn't recall to modern or classical piracy, in which plundering civilian goods is far more common and worthwhile (especially during the age of sail) than plundering weapons and military vessels. It's one of the reasons I especially like the death dues mechanic because it harkens to the shares system employed by many historical pirates.

This attempts to address the issue also raised in #227, but in a different way. It would also conflict (but could be made compatible with) #852. I intentionally didn't mess with the equality in purchase/sale price of purchased outfits because I like the ability to test out different outfit combinations and progressively upgrade without incurring financial penalty.

**LORE**

When you plunder a ship for outfits, you're not carefully removing them with specialist training and tools as would be done at an outfitter. You and your crew, possibly in a combat situation, are hastily removing them with whatever cutting equipment you have available. Hence the plundered outfits will be in a far worse condition than those newly purchased and will require some cost to repair to an installable state, and may otherwise only be good to be sold as scrap. Ammunition, like goods, is easily removable and transportable and hence not at risk of being damaged.

**MECHANICS**

The concept of damaged outfits is added to outfits carried in the cargo hold. Damage is a binary state, and the cargo hold will keep a track of the number of total & damaged outfits.The only way to acquire damaged outfits is through plundering other ships. All plundered outfits will be damaged, except for ammunition to maintain consistency with the ability to use freshly plundered ammunition straight away.

Damaged outfits take up the same space in your cargo hold, cannot be installed at an outfitter and are only sold for 10% of the standard price. They can be repaired (which replaces the buy/install option) at an outfitter, which requires 90% of the standard price to install them on a ship.

A ship with X total outfits of which Y are damaged will display this in their ship info view and outfitter panel as:

X (Y dam.)

Damageable outfits (i.e. all except ammunition) display their "cost if damaged" and "cost to repair" in the outfitter information screen.

**ISSUES/IMPROVEMENTS**

- Damage/repair costs are not displayed in the outfitter map view.
- The "X (Y dam.)" display style may be confusing, but using the full "X (Y damaged)" overflows in some displays.
- The display style may be ugly/inconsistent.
- The damaged/undamaged cost ratio (10%) is hard baked into the code and universal for all damageable outfits.
- Damageable/undamageable outfits are hard baked into the code based on membership of the "Ammunition" category.
- An outfit cannot be repaired unless it can be immediately installed.
- Damaged outfits are always sold before undamaged ones, and undamaged outfits are always installed before damaged ones. I don't see a problem with denying player choice here, but I may have missed something.
- When selling a damaged outfit to an outfitter, it is immediately repaired and can only be repurchased at full price.

**FURTHER WORK**

- I'd like to scale the damaged cost based on the outfit cost to mass ratio (CMR), such that most plundered outfits are similar in value to plundered goods. Damaged early human tech outfits would have a lower CMR than goods, late alien tech would be higher, but represent an even smaller fraction of its total value. e.g. The Korath Tek'nel Reactor has a current CMR of 100,000, when damaged it is 10,000, still over 6x times more valuable than the most expensive luxury goods.
- A flat cost reduction (perhaps 50%) on outfits (damaged and undamaged) sold using the "Sell All" function on planets that lack an outfitter, representing the decreased demand for outfits where they cannot be installed.
- Calculating the cost of items in a cargo hold is performed separately across a number of class files, but always uses similar methodology. Refactoring a lot of this code into the CargoHold class would improve maintainability for modifications such as this.
- The same methodology could be applied to boarded ships (combat damage/sabotage by defenders), damaging their outfits/hulls and requiring one-off paid repairs to bring them back to full functionality.

**UNRELATED FIXES**

The OutfitterPanel::CanBuy method incorrectly returned true for outfits in the player's cargo hold that exceeded the ship outfit space limits, the method has been fixed (although also modified to account for repairing damaged outfits).

### CODE REVIEW

**Comment by jmhorjus** [comment]
The primary purpose of this is to directly apply a 10x nerf to the price of plundered outfits.  Capturing outfits is one of the best ways to make money, so I'm not opposed to a nerf, but balance-wise 10x seems a bit harsh.  Main issue it this will leave capturing interceptors (whole ship captured, outfits not damaged) as the undisputed champion of money making.  
However I haven't tried your branch yet! It looks like we have similar motivations, so I'm going to get your branch and play through the first stages of a new game with it.  Would you mind doing the same with my Used Parts branch, and we can compare notes? 

In addition to the reduction of used ship/outfits values, I really wanted to continue economic balance by drastically **increasing** the base-price of the high end commodities - such that if a cargo ship is flying around stuffed to the gills with gold bars, the gold is actually worth nearly as much as the ship carrying it, and 20 tons of Rolex watches and Gucci handbags are worth more than 20 tons of standard-issue hyperdrive. I've refrained from adding a commodity price re-balance to that branch itself, but the code in that branch allows commodities to be re-balanced by editing commodities.txt, which previously wasn't possible without editing each individual planet.

**Comment by jmhorjus** [comment]
Oh, also your editor is cleaning up tabs for you (deleting what it sees as "trailing white space") without asking, and it super-clutters the file diff views and makes it hard to read your pull request. :( 
Turn that off! (I had code blocks and sublime both do that to me by default at first)

**Comment by brazencavalier** [comment]
> The primary purpose of this is to directly apply a 10x nerf to the value of plundering outfits, right? Plundering outfits is one of the best ways to make money, so I'm not opposed to a nerf, but balance-wise 10x seems a bit harsh. The main issue is that this will leave capturing interceptors and other small ships (whole ship captured, outfits not damaged, 1-6Million per ship and you can capture 3-6 or more per day easily) as the undisputed champion of all money making.

I definitely agree that it would be imbalanced in favour of boarding. I'd like to extend the damage system to boarded ships (both outfits and the ship hulls themselves) to balance it all out. I wouldn't mind playing around with the death dues system either to make boarding large ships more worthwhile.

> However I haven't tried your branch yet! It looks like we have similar motivations, so I'm going to get your branch and play through the first stages of a new game with it before commenting further. Would you mind doing the same with my Used Parts branch, and we can compare notes?

Absolutely will! I mainly tested my own with an advanced fleet that I had been using to farm Korath reactors, I admit I'm not sure about early game balance as much (I'm not that great a combat pilot...).

> In addition to the reduction of used ship/outfits values, I really wanted to continue economic balance by drastically increasing the base-price of the high end commodities - such that if a cargo ship is flying around stuffed to the gills with gold bars, the gold is actually worth nearly as much as the ship carrying it, and 20 tons of Rolex watches and Gucci handbags are worth more than 20 tons of standard-issue hyperdrive. I've refrained from adding a commodity price re-balance to the Used Parts branch itself, but the code in that branch allows commodities to be re-balanced by editing commodities.txt, which previously wasn't possible without editing each individual planet.

I saw your refactoring of commodity prices into commodities.txt earlier and thought it was a great idea, and would love to see it used to increase the price of valuable commodities on par with good looted outfits. I also wondered if new commodities could be added, but keep the same number of commodities/system (for UI cleanliness) such that later systems/alien species might use entirely different commodities that could have much higher base values.

> Oh, also your editor is cleaning up tabs for you (deleting what it sees as "trailing white space") without asking, and it super-clutters the file diff views and makes it hard to read your pull request. :(
> Turn that off! (I had code blocks and sublime both do that to me by default at first)

Yeah I'm really sorry. :( I noticed that but wasn't sure how to reverse all the deletions, I've turned it off now so hopefully won't happen again.

**Comment by jmhorjus** [comment]
The only way I was able to undo all the tab changes once they were made was to either undo them manually or to make a copy of your version of the file, revert the file entirely, and then re-paste in the 2-3 actual code changes. :(

**Comment by brazencavalier** [comment]
After playing around with your #852 @jmhorjus, given that it's a far more complete and polished reworking of outfits than mine, I don't think there's any point on me continuing with my fork as I've implemented it because all in all I'd prefer to implement any changes to plundered outfits using the framework you've already built. The plunder value is much improved on the basis that most outfits are already at 50% wear, although I still find them to be a little high (at least until some more valuable trade goods are available) - then again, playing my own fork I found starting as a combat pilot completely impossible. I'd be interested in taking your fork and implementing extra damage to plundered outfits (perhaps proportional to hull damage) and adding the repair concept to outfits with <50% condition (just a cost you pay at the outfitter before they can be installed). Thoughts?

**Comment by jmhorjus** [comment]
Yeah, I think it makes sense for "New"-->"Used"-->"Very Used"-->"Damaged" to be points on the same continuum. What I currently call "age" could be renamed/re-understood as "wear". 

Currently there's no limit on "age" and at a certain point the age just stops effecting price. First step is to have the "wear" itself stop accumulating at a certain level - the part is now "well worn" and not noticeably getting worse.  Then outfits with *more* wear than that "well worn" level could be considered "damaged" and need to be repaired before they could be installed.

Then you could have a plundered outfit take a little extra "wear" when being plundered. (Balance wise, I'd like to not knock more than another half off of even the heaviest and most valuable outfits though - so that if you capture two of something you can always at least sell one for 25% and use the money to repair the other one from 25% to 50%.)

I don't like the idea of determining damage level by the hull damage on the disabled ship, since that is super hard to control (unless you never use any non-laser weapon) and can go up or down if a ship is assisted and then disabled again. Perhaps use a small random factor plus the item's weight?  The heavier something is the harder it's likely to be to extract it in one piece after all.

**Comment by wargwargwarg** [comment]
Yes, looting disabled light cruisers is very unbalanced (in about 1 hour I gathered about 15Milion, after having traded a loooong time). But this works only with a cavernous Mule (that is an unballanced super jack-of-all-trades.

So, here's another take: say you disabled a ship with 10 systems installed and 5 crew onboard. It is drifting, with 40% hull. The 5 crew defend the critical systems, like powerplant and thrusters, to repair them and get out of there.

That would mean 6 out of 10 systems are damaged in some way, on a random basis and the other 2 are defended. 

On boarding, the list details what is damaged (perhaps degree), what is intact and ready for looting, what is defended and let's you choose.

More, all this looting is being done on the run, with hostiles onboard and hostile ships in the area. There should be a time counter ("you have 1 hour minutes to grab what you can", the more mass the device, the more time it takes to bring it to your hold.)

I myself like the condition "wear" idea  from use and forcefully removing the components. My variant may be easier to implement

**Pull request closed without merging**
