### PR TITLE
added ammo storages to ships and did the lay-outs a lot

### PR DESCRIPTION
**Pull request by KiLEdEnNis**
it took like 8 hours or so and it says 7299 additions and 7046 deletions (which is a bit weird to me and is gonna be HELL to read through for you people) so let me explain everything I did:

- added ammo storages to some ships that had missiles and room left (only the stock Protector lost 2 of the 3 small radar jammers for 2 torpedo storages), also added the ammo for them
- made a lot of lay-out fixes and improvements
- ordened all variants in variants.txt alphabetically & even ordened the variants per ship), and put all Hai outfitted human ship variants to the bottom seperately
- had to manually add the hardpoint fix commit but that's 100% fine now

it'll take a while to check everything but if I made a mistake it's just a typo

I made sure I made no mistakes, and if I made any they're typo fixes

### CODE REVIEW

**Comment by LocalGod79** [comment]
we discussed this a bit on discord, just want to record it here:

doesn't this just make players who play a plunder/capture style even richer, while doing nothing for the other playstyles?

extra storage containers, extra unfired ammo...

**Comment by KiLEdEnNis** [comment]
with depreciation the profit changes barely go up like 30k on ships that sell for hundreds of thousands, if not millions of credits, + most of the storages are on the larger ships and warships

if we refrain from updating ships merely for more profit: why not remove radar jammers, big batteries etc.?

it's barely game changing in money grinding through plundering/capping, and in my opinion the tiny bit more profit it gives is fine anyway early game as there it's dangerous to do so, and late game you can capture ships and sell them for millions, you won't notice an extra 20k anyway

**Comment by Amazinite** [comment]
You might want to redo this so that it doesn't say that every single line was changed.

**Comment by KiLEdEnNis** [comment]
@Amazinite if only I knew how
I forked the repo & uploaded the files, but should I copy-paste the content instead?

**Comment by jafdy** [comment]
Yes. By re-uploading the files you deleted the old ones and created new ones under the same name.
I would recommend GitHub desktop for this kind of work.

**Comment by KiLEdEnNis** [comment]
for desktop GitHub I'd have to make a 2nd repo & I'm already glad I made my 1st 1 work
but I copy-pasted the text files' content over to a new form and made #2271 now, so closing this
ty for the help

**Pull request closed without merging**
