### PR TITLE
Is this a joke? Maybe...

### PR DESCRIPTION
**Pull request by RisingLeaf**
**Feature:** This PR implements the feature request detailed and discussed in the underworld

## Feature Details
Some halloween hails

## Testing Done
Done

### CODE REVIEW

**Comment by Hurleveur** [comment]
I quite like the idea of unique hails depending on the period but they should add up to existing ones and be more fleshed out.
Or just have a person that goes spooky and does these I guess

**Comment by Anarchist2** [comment]
Relevant: #6516, this [comment](https://github.com/endless-sky/endless-sky/pull/6516#pullrequestreview-866992565) in particular.

**Comment by RisingLeaf** [comment]
This will be closed today because it **is** a gag

**Comment by Saugia** [comment]
Closed this PR as it's already been discussed as not something we'd add to the game and to keep overall PR count down.

**Comment by a-random-lemurian** [comment]
we should have this as a plugin

**Pull request closed without merging**
