### PR TITLE
Fare'n Lai

### PR DESCRIPTION
**Pull request by Lineth**
Fixes [2059](https://github.com/endless-sky/endless-sky/issues/2059).

### CODE REVIEW

**Comment by Lineth** [comment]
Also, any way to prevent the annoying remote-tracking appearing as commits ahead thing? Sorry for that.

**Comment by zwparchman** [comment]
Look into rebasing. The short explanation is that it lets you rewrite history in git including merging multiple commits into one.

**Comment by Lineth** [comment]
Seems interesting, but I can't make heads or tails of the instructions. Deeply frustrating.

**Comment by Nechochwen-D** [comment]
Try taking a look at the tutorials found here. https://www.atlassian.com/git

**Comment by Lineth** [comment]
Closing this for now as Git's own help page did not help me at all.

**Comment by BorkBorkGoesTheCode** [comment]
@Lineth Want some help?

**Comment by Lineth** [comment]
@BorkBorkGoesTheCode Yeah. I have an experimental branch for fiddling with rebasing, but it seems goofed.

**Comment by BorkBorkGoesTheCode** [comment]
What operating system are you developing with?

**Comment by Lineth** [comment]
Win10. Using Github Desktop primarily.

**Comment by BorkBorkGoesTheCode** [comment]
You'll need to open git shell and perform a rebase from there.

Have you opened it?

**Comment by Lineth** [comment]
Yeah. I id to a rebase on the now deleted branch, but it was goofed up. Was using [this](https://help.github.com/articles/using-git-rebase-on-the-command-line/) as a reference. Followed it largely to the letter, merged 275 commits ( I presume these are the sum of the 26 merge commits) into one. With the merge-faffery branch I set up to experiment, there's some kind of merge conflict with the maps file.

**Comment by mootootwo** [comment]
Sorry, this pull will not fix the issue.  Far'en Lai has the `uninhabited` flag already, and is fine.

The problem described in https://github.com/endless-sky/endless-sky/issues/2059 is actually with planets missing the `secuirty 0` flag such as Kessel Sepret and Gresku Fodar.  The behavior seems inconsistent, however, and I am not sure what causes it to trigger sometimes but not others.

**Comment by Bladewood** [comment]
Inconsistent behavior is good in this case, because we don't want to get caught every single time we land with nerve gas, no?

http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository#7244456

**Pull request closed without merging**
