### PR TITLE
Move ShipAICache to the main source directory

### PR DESCRIPTION
**Pull request by TomGoodIdea**
## Details
Removed `source/ship/` directory since it contains only a single source file (for ShipAICache class) with its header; moved those files to `source/`.

### CODE REVIEW

**Comment by RisingLeaf** [comment]
The creation of that folder was for all ship related files, the reason why they have not been moved yet was to not create conflicts with some pull requests as far as I remember.

So instead of removing the directory, the other ship files should be moved there too.

**Comment by Hurleveur** [comment]
Yeah we should have more folder division of code not less

**Comment by TomGoodIdea** [comment]
Won't we end up in a situation that we have multiple subfolders just like this one with only one class because nothing else could be grouped with it?

**Comment by Zireael07** [comment]
@TomGoodIdea see @RisingLeaf 's comment

**Comment by TomGoodIdea** [comment]
Alright, I'll close this if you prefer grouping other files, but I'm afraid having subfolders can make navigation actually harder, especially for items that it's not obvious to which subdir they belong.

**Pull request closed without merging**
