### PR TITLE
Removed unarmed Flivver from Defensive Deep fleet

### LINKED ISSUE #2430: Deep Planets refusing to surrender due to fleeing defensive ship
i tried to dominate Munnin Station ("The Gate to the Deep") several times, but they simply refuse to surrender. There are no Defense Ships left in the system, i even destroyed the disabled ones, but no matter what i try, the station just tells me that they are "not ready to surrender yet".
i tried to dominate Huggin Sation in the meantime, and it worked like a charm.

attached is a video showing 2 attempts and the successful Huggin Station domination. i had to speed it up a lot, but that messed up the sound, so you better mute it.
https://www.dropbox.com/s/b59cjpzljudq2xv/MunninStation2.mp4

### PR DESCRIPTION
**Pull request by MCOfficer**
this should fix #2430

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
even if it doesn't fix it (although I think it does), why would an unarmed Flivver be part of the Deep anyway?

**Comment by MCOfficer** [comment]
i just did some test, and so far it's working like a charm. also i checked my video, you can actually see the flivver fleeing, right before the end.
i'm sure that we found the cause :+1:

**Comment by Tadrix** [comment]
> even if it doesn't fix it (although I think it does), why would an unarmed Flivver be part of the Deep anyway?

A scout for the fleet?
I suspect it being unarmed was the problem.

**Comment by KiLEdEnNis** [comment]
it does fix this, but unarmed defense fleet ships shouldn't leave, maybe that needs some coding fix
and what would the Deep need a scout for?

but feels good that my suspicion I've had for like 5 months was right though, never had any tribute problem w/ Syndicate etc. but entire Deep gave me this bug 3x in 1 save

**Comment by MCOfficer** [comment]
i tried that, with... interesting results. apparently only some of the flivvers flee from the system the rest scouting the system (they fly from one habitated planet/station to the next).
https://www.dropbox.com/s/k412hno94vbx67c/2017-04-20%2015-57-20.mp4?dl=0

**Comment by KiLEdEnNis** [comment]
all we may need then is having unarmed ships not flee, or let military fleets only have armed ships

**Comment by Tadrix** [comment]
There are various reasons for the military fleets to have unarmed auxiliary ships (transports, tankers, scouts, ships with weapons removed by plunderers). I'd suggest making defense fleets staying, it sounds logical and it would be one less thing to keep in mind.

**Comment by KiLEdEnNis** [comment]
transporting would be done by civilians or at least something armed, tankers don't really exist in the game, scouts have no use at all, plundered ships are usually killed etc.
I don't really see the point
but defense fleets are from fleets.txt, making them staying makes all those fleets always stay, and making special defense_fleets.txt is gonna take a lot of probably unnecessary work

**Comment by endless-sky** [comment]
The "Deep" fleets are used primarily to define what ships occupy the Deep, and unarmed, racing Flivvers are intended to be one of them. Really there should be separate fleet definitions for defenders, because having Star Queens included in the defense fleet doesn't make any sense either.

**Comment by KiLEdEnNis** [comment]
making a new .txt for them and updating map.txt would do then, at least for the Deep, since some ships aren't warships at all

**Comment by Tadrix** [comment]
Anyway, as a cautionary measure, any ship that fled the system should be considered defeated for domination purposes. They abandoned their planet; they aren't defending it.

**Comment by KiLEdEnNis** [comment]
it should have some check like "isInSystem && no=destroyed" (just for explanation purposes, didn't learn any coding, that's next year)

**Comment by KiLEdEnNis** [comment]
I still think there should still be a fix where if a defense ship isn't in a system it doesn't count anymore either
just to fully fix this and prevent future tribute bugs (since this works around a problem that's not fixed itself)

**Comment by endless-sky** [comment]
What I was suggesting was to remove *all* non-military ships from the Deep defense fleets, not just the racing Flivver. (Basically, both Flivver variants in the small fleet, and everything involving a Star Queen in the large one.)

**Comment by KiLEdEnNis** [comment]
making a new "defense fleets.txt" allows special defense fleets and could give more variety in tributes
the only issue then is if it's worth making an entire new text file w/ new fleets, changing all defense fleets etc. for the small tribute side-feature

**Comment by MCOfficer** [comment]
literally all military ships, or only those flown by military organisations? i agree for navy, deep and maybe FW militia, but to me it makes sense for pirates or militia to come up with whatever they have.

**Comment by KiLEdEnNis** [comment]
whatever they have would be warships (and for pirate ships; warships w/ cargo)

**Pull request closed without merging**
