### PR TITLE
Hai assist mission

### PR DESCRIPTION
**Pull request by toilethinges**
Merchants occasionally pay you for helping them - why not the extremely friendly, peaceful, Hai?

I made it so it pays more, and has more of a chance, for two reasons:
a) The only place they get disabled is on the border between theirs and the Unfettered's borders, making it extremely dangerous, with a high chance of death.
b) They are the Hai, who are more friendly, more generous, etc.

The missions pay much more than the original (30k as opposed to 10) and are more common (< 27 as opposed to < 10.)

Similiar issues: #333 and #1002.

### CODE REVIEW

**Comment by toilethinges** [comment]
#333

**Comment by ItsNickBarry** [comment]
>5 is less likely than >10.

**Comment by toilethinges** [comment]
@ItsNickBarry - how does that work, anyway? Does it select a random number between 1-100?

**Comment by ItsNickBarry** [comment]
It will select some number and then compare it to the one you use in the mission.  I'm not sure what the maximum is, but 100 is a good guess.

**Comment by Amazinite** [comment]
From the wiki.

> "random" is a random number between 0 and 99. This can be used to make a mission only sometimes appear when all other conditions are met.

**Comment by toilethinges** [comment]
I'm a bit unsure on the numbers, but does this seem good for the most part?

**Comment by jafdy** [comment]
Only the Quarg version has a destination and 10M seems a bit high.

**Comment by toilethinges** [comment]
@jafdy, I agree on the price, I'll make it 1m or 500k, but they all have destinations. They're just all after the comment.

**Comment by toilethinges** [comment]
e0c38d5

**Pull request merged**
