### PR TITLE
more planet sprites

### PR DESCRIPTION
**Pull request by comnom**
The galaxy has been expanding, but the number of planet sprites has not; so I figured I'd try my hand at some.

I didn't want to do too many, as I'm not sure how many we'd be looking for, if any, but if these make the cut I can do another batch or two. Also this makes it easy to weed out any subpar ones.

This PR is just the sprites/copyright, because while its simple enough to randomly distribute them in map.txt, care has to be taken to make sure the orbits dont overlap if the size difference is too great, and also because I wasn't sure if some could be used to make certain areas of space a bit more unique to aid the exploration aspect of the game.

So if we need more, lemme know, if not, then lemme know ;)

Oh, 2x here in case you don't want to squint to review them:
[scl2x.zip](https://github.com/endless-sky/endless-sky/files/1061045/scl2x.zip)
.xcf zip is 36mb, so I'll upload that in chunks upon request.(some of the NASA sources were very large)

Edit 6/15:
Demo plugin included as per @tehhowch 's suggestion. Test System is linked to Rutilicus and contains all sprites:
[planet-sprite-demo.zip](https://github.com/endless-sky/endless-sky/files/1079353/planet-sprite-demo.zip)

### CODE REVIEW

**Comment by jafdy** [comment]
I have concerns that there is not enough light, for me both lava0 and rock2 appear to be black circles with no color at all.
Normally copyright is done with -suffix so that the images will be clumped with their counterparts, similarly the numbers carry on as if the suffix wasn't there. Have a look at the way the landscape images have been done.

**Comment by tehhowch** [comment]
I agree, they seem a bit darker than the existing images (at least in the previews shown here on GitHub). Maybe lighten by 10-25%?

**Comment by comnom** [comment]
Renamed them all in https://github.com/endless-sky/endless-sky/pull/2606/commits/36aa391d002994983b4b9e969ff2908bad4852ac

As for the brightness, naturally everything appears brighter on a proper black background. Which is what they'll be drawn on.
lava0

**Comment by jafdy** [comment]
You still have a * on the end of your copyright.
And that still looks really dim to me (although I do see color now).

**Comment by comnom** [comment]
The wildcard at the end is to handle the extension (both at2x and the actual extension).

I still don't really get the brightness thing, brown and red are dark colors, so naturally they appear darker than light colors. But those two could easily be removed if there's an issue, as just increasing the brightness would wash out the brown, and turn the red to a more pinkish color (unless I oversaturate it, which is just as bad).

**Comment by nylki** [comment]
@comnom I think the issue @jafdy has with the darkness is that too much area of the planets is covered in shadows.

**Comment by comnom** [comment]
@nylki No, the shadows are correct. See: https://github.com/endless-sky/endless-sky/wiki/PlanetSprites

The issue is that the since shadows get added in a multiply layer (two actually), it makes the whole thing overall a bit darker than the norm since we started with dark colors. At the top we pretty much get 100% black, with the planet's color no longer coming through at all.

I personally didn't think it looked out of place, hence the confusion, but like I said I'm willing to remove them if necessary.

I did experiment with switching to overlay on the darker ones, but it kinda messes up the gradient from very light shadow to dark shadow, so I don't like it that way either:

lava8-fwg
rock22-fwg


Easier to just pull them out if they don't work, and make new ones.

**Comment by tehhowch** [comment]
tested out these sprites in the preview-pack, and they look great.
newplanets

**Comment by endless-sky** [comment]
For adding more planet sprites, the real question would be how to work them into all the existing star systems. Adding new sprites but only having them appear in new star systems created after 0.9.7 wouldn't make a lot of sense.

In my opinion the best strategy would be to first collect a complete set of "alternative" sprites paired with the existing ones - e.g. "lava0" and "lava0b" would both be 100x100 lava planets, etc. Then it would be easy to write a one-time script that would replace half the planets in the map with the "b" version of that sprite, instantly doubling the sprite diversity thoughout the map.

**Comment by comnom** [comment]
@endless-sky Fair enough. I'll close this PR and open another once I've amassed enough to do a whole set.

Sprites of planets from our solar system will be a fair challenge, but just adding an unrelated variant wouldn't make much sense naming wise. I'll see what I can come up with.

**Comment by endless-sky** [comment]
I'd suggest creating a separate repository (or at least a separate branch) to allow multiple people to contribute more planet sprites, instead of having to do them all yourself. The repo's web page could include something like the attached HTML file to track progress and view the variants side by side:

[planets.html.zip](https://github.com/endless-sky/endless-sky/files/1081156/planets.html.zip)

For variants of the solar system sprites, they would just have to be something that looks visually similar. When randomly replacing sprites with variants we'd just need to make sure none of the sprites in Sol got replaced.

**Pull request closed without merging**
