### PR TITLE
Dec16corrections

### PR DESCRIPTION
**Pull request by Zitchas**
A variety of fixes and corrections, mainly word changes, grammar, and adjustments to match stated purpose.

### CODE REVIEW

**Comment by Amazinite** [comment]
You might need a better work flow.

**Comment by Zitchas** [comment]
lol. It really wasn't much, it just got PR'd here instead of to my fork. I really wish that GitHub wouldn't default PR's to the original upstream. I never PR to that, always to my fork. Also wish I could just delete erroneous PRs.

**Comment by MCOfficer** [comment]
next time this happens, leak some personal data so github stuff has a reason to delete it ^^

**Comment by Zitchas** [comment]
Sorry.

**Comment by Zitchas** [comment]
As far as that goes, I'd like to move to a better work flow, but until I get the Remnant Content PR done, this stuff *is* my master. Once it is out of the way, I'll be moving to working on branches like I'm supposed to, and hopefully that (amongst other things) will help my work flow go a bit better.

**Comment by Zitchas** [comment]
Isn't that the proper way of doing doing it? Do nothing directly to master, always work in a branch that gets merged into master?

**Pull request closed without merging**
