### PR TITLE
Remnant - Penguin Flare Points

### PR DESCRIPTION
**Pull request by Zitchas**
**Content**

## Summary
This PR adds 
- a reverse engine flare for the Penguin's built-in reverse engine.
- Flare point for the reverse engine
- Two flare points for the left turn flare
- Two flare points for the right turn flare

## Save File
This save file can be used to play through the new mission content:
[RemTest.txt](https://github.com/endless-sky/endless-sky/files/4567884/RemTest.txt)
This pilot has a Penguin that was purchased after these flares were implemented, and thus in the 0.9.13 branch it will show the requisite flares.
It can also be viewed at: [https://youtu.be/fB3gOdsYBzY](https://youtu.be/fB3gOdsYBzY)

  
This uses code added to 0.9.13 in https://github.com/endless-sky/endless-sky/pull/4539

### CODE REVIEW

**Comment by tehhowch** [comment]
If you base off a non-default branch, make sure you open your PR to the correct non-default branch.

**Comment by Zitchas** [comment]
Sorry about that. I'll do so in the future.

And I fixed that one extra commit that was from something that was committed to the Master but not to 0.9.13

**Comment by tehhowch** [comment]
recreate your PR without the extra merges (force push over it) and i'll reopen.
Do not revert commits that came from merges.

**Comment by Zitchas** [comment]
OK. Willco.

**Pull request closed without merging**
