### PR TITLE
Hai Reveal: Revised Smuggler Story Arc

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Content (Artwork / Missions / Jobs)**

Simplifies the Hai Reveal smuggler story arc, changes the wormhole to blue, and fixes plot holes. Wraps the Free Worlds War, Pug War, and Hai Reveal into one beautiful whole, and adds a little bit of nightmare fuel to the lore.

## Summary

The Hai Reveal smuggler story arc is critical to Hai Reveal, as it humanizes the kidnapping victims rather than leaving them as a mere plot device mentioned in passing. There were lore objections and numerous plot holes formed as a result of the means chosen to implement the smuggler mission sequence. I've fixed all of them, and taken advantage of Base Principles to wraps the Free Worlds War, Pug War, and Hai Reveal into one beautiful whole (see branch name). The key to all of this is that Devil-Run is hidden so that even the advanced races can't reach there without the code. To accomplish that, I added a little bit of nightmare fuel to the lore.

Changes:

1. The wormhole is blue and Giti only tells you where Elenchus is (B03-B05)
2. You must find Devil-Run, which involves hunting smugglers and solving a riddle (B05-B08)
3. When you reach Devil-Run (and later, Al Hurr) you find a strange anomaly that has been cloaking the star system. It turns out there is a Pug ship in the middle of the anomaly (B09-B13)
4. There are more types of smuggler ships.
5. The smuggler hunt starts at Ada, near the systems with smugglers, rather than waaaaay at the other end of the galaxy.

<details> <summary>Detailed changelog of all missions</summary>

### New Story as the Player Sees It

B03 - Sayari gives you info about smugglers, and you decide to check in with Giti.
B04 - Giti has translated part of the inscription, which tells about Devil-Hide and Elenchus. She doesn't know where Devil-Run is, but says it has to do with this riddle: "Where does the soul sleep?" While she works on the riddle, you should go to Ada and visit Goraz who works for Lovelace Labs as a communications researcher.
B05 - persistent mission that reminds you the goal is to find a route to Elenchus
B06 - Goraz tells you about smuggler ships and where to find them.
B07 - Board a smuggler ship and find out that, "It's 0.184 steradians." Captain Last recognizes this as a typical hyperspace aperture size because, "Any interstellar pilot knows that a proper aperture size is critical to reaching the next star system in one piece," and decides to go to Giti.
B08 - Find the location of Devil-Run and get arrested.
B09 - Syndicate sends you and Giti to scan Devil-Run and Devil-Hide. There's a bizarre anomaly at Devil-Run hiding the entire solar system, and preventing anyone from jumping in through ordinary means.

Missions after that are unchanged, except:

B13 - Now has an explanation of Devil-Run's discovery and the anomaly in that system. Elenchus denizens think there's a tree-shaped ship in the middle of the anomaly. The initial colonists long ago on Freedom found Devil-Run, Devil-Hide, Elenchus, and Al Hurr using a smaller ship of a similar design discovered in a cavern near their settlement. The ship was accompanied by three jump drives and maps to several invisible star systems.
C04 - The Al Hurr system has an anomaly identical to the one at Devil-Run. (No wormhole, though.)

</details>

<details> <summary>What really happened (nominal timeline and lore)</summary>

### The Story an Experienced Player can Deduce

Shortly after (or before) anarchists founded a colony on Freedom, the Pug left a ship, some jump drives, and a cartouche with star system locations, including a few "hidden" star systems. Since then, they've been manipulating one of the colony's founding groups: the Base Principles. That is the organization that founded Elenchus, deliberately started the Free Worlds war, and ultimately led to the Hai Reveal. They were an unwitting puppet of the Pug for over a century.

That means everything that has happened so far has been an elaborate manipulation of the Pug. They started the Free Worlds war, which eliminated the unfairness in human politics, reduced piracy in the south, rooted out two Alpha groups, and made contact between the humans and the Betas. The Pug "war" was, of course, a Pug plot, with many positive consequences. The Pug arranged the reveal of the Hai, which woke up the Hai, brought them closer to unification than they've been in centuries, led to a Hai-human treaty, and eventually a safe corridor of traffic from Hai space to the Syndicate. They even made a "backup copy" of the humans, Hai, and Korath, at a science colony in deep space.

All they need to do was hide some tech and a map with anarchists, manipulate an anarchist group, and hide some star systems.

I promised you nightmare fuel, though.

</details>

<details><summary>Why didn't anyone find Devil-Run? -- the nightmare fuel I promised</summary>

### Why Didn't Anyone Find Devil-Run?

If you thought the Remnant had better cloaking technology than the Pug, prepare to be amazed.

Nobody could reach Devil-Run; not the humans, Hai, Quarg, Coalition, and probably even the Archons. Why?

The Pug hid it.

Devil-Run is invisible to all technologies known to the humans and Hai, but even if you knew where the system was, you couldn't get there. The "anomaly" hiding the system scatters jump attempts, so instead of ending up in Devil-Run, you'll be in deep space. To get to Devil-Run, you need to jump to a precise location slightly outside the system, and the "anomaly" will pull you in.

You remember that Pug galaxy with nowhere to jump to?
Oh, and you know how they left behind the system they were using to spy on the humans?
Yes, and that habit they have of hiding "backup copies" of species... but we don't know exactly where?

Scary, isn't it? But that's not the nightmare fuel I promised.

The "anomaly" has a Pug ship in the middle, which has been hiding the star system for over a century, and they only pulls ships into the system when they want to. It is almost a kilometer long, outputting as much power as a star, and pumping the system full of jump drive particles. This is the sort of ship the Pug use when they need to make intergalactic wormholes in a hurry, hide entire star systems, make shock and awe attacks, teleport ringworlds, or just... when they've decided not to give you a fair fight.

Those ships could be anywhere. Now *that* is nightmare fuel.

</details>

<details><summary>Artwork: Pug star system cloak.</summary>

If someone wants to make better art for this, then please feel free to do so.

The blue-purple-red lines/blobs are a cloaking field. This is not intended to be haze; rather, it is the main event in the star system.

That strange swirl near the wormhole is the "anomaly" surrounding a ship that is cloaking the star system. It is far larger than the ship: the ship is about a kilometer long, but the anomaly is definitely larger than 250,000 kilometers.

cloaked-star-system

</details>

## Save Files
These save files are just before each mission or set of missions.

1. Before B02. Visit spaceport, follow mission to Stormhold: [Friction Diction~3026-01-14 TRY18 before B03.txt](https://github.com/endless-sky/endless-sky/files/10473213/Friction.Diction.3026-01-14.TRY18.before.B03.txt)
6. Before B04. [Friction Diction~3026-01-18 TRY19 before B04.txt](https://github.com/endless-sky/endless-sky/files/10473250/Friction.Diction.3026-01-18.TRY19.before.B04.txt)
7. Smuggler hunt, at the best system for it. You just need to board one smuggler, but you'll get additional dialog for later smugglers. [Friction Diction~3026-02-01 TRY19 before B07 at almach.txt](https://github.com/endless-sky/endless-sky/files/10473251/Friction.Diction.3026-02-01.TRY19.before.B07.at.almach.txt)
8. Before B08 (reporting to Giti and get arrested). [Friction Diction~3026-02-07 TRY19 before B08.txt](https://github.com/endless-sky/endless-sky/files/10473254/Friction.Diction.3026-02-07.TRY19.before.B08.txt)
9. Before B09 (mission to scan Devil-Run and Devil-Hide). [Friction Diction~3026-02-09 TRY19 before B09.txt](https://github.com/endless-sky/endless-sky/files/10473255/Friction.Diction.3026-02-09.TRY19.before.B09.txt)
10. Before B10 (reporting to Teeneep) [Friction Diction~3026-03-06 TRY19 before B10.txt](https://github.com/endless-sky/endless-sky/files/10473256/Friction.Diction.3026-03-06.TRY19.before.B10.txt)
11. Before B11 (pick up fighters at Foundary) [Friction Diction~3026-03-08 TRY19 before B11.txt](https://github.com/endless-sky/endless-sky/files/10473267/Friction.Diction.3026-03-08.TRY19.before.B11.txt)
12. Before B12 (Devil-Hide battle) [Friction Diction~3026-03-20 TRY19 loaded fighters at B12.txt](https://github.com/endless-sky/endless-sky/files/10473271/Friction.Diction.3026-03-20.TRY19.loaded.fighters.at.B12.txt)
13. Before B13 (Elenchus conversation) [Friction Diction~3026-03-30 TRY19 before B13.txt](https://github.com/endless-sky/endless-sky/files/10473270/Friction.Diction.3026-03-30.TRY19.before.B13.txt)
14. Before C04 (finding Terry) [Friction Diction~3026-05-03 TRY19 before C04.txt](https://github.com/endless-sky/endless-sky/files/10473273/Friction.Diction.3026-05-03.TRY19.before.C04.txt)
15. During C04 just before jumping to Al Hurr. [Friction Diction~3026-05-08 TRY19 C04 before aspiration.txt](https://github.com/endless-sky/endless-sky/files/10473276/Friction.Diction.3026-05-08.TRY19.C04.before.aspiration.txt)

## Artwork Checklist

FIXME: Do these things.

 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

### CODE REVIEW

**Comment by RisingLeaf** [comment]
> Simplifies the Hai Reveal smuggler story arc, changes the wormhole to blue, and fixes plot holes. Wraps the Free Worlds War, Pug War, and Hai Reveal into one beautiful whole, and adds a little bit of nightmare fuel to the lore.

Love this description.

But I want to note that the haze looks pretty strong, I am not an art guy though so dont trust my impression.

**Comment by UnorderedSigh** [comment]
@MasterOfGrey wanted me to ping @Amazinite when I PR'd this. It would also be great if @bene-dictator could review it.

**Comment by UnorderedSigh** [comment]
> But I want to note that the haze looks pretty strong, I am not an art guy though so dont trust my impression.

It is not haze; it is a Pug cloaking field, and it is intended to be pretty strong.

If someone wants to make a better one, please do so.

**Comment by RisingLeaf** [comment]
> > But I want to note that the haze looks pretty strong, I am not an art guy though so dont trust my impression.
> 
> It is not haze; it is a Pug cloaking field, and it is intended to be pretty strong.
> 
> If someone wants to make a better one, please do so.

I was referring to it as a haze because that is what it is in the data files. If you got some good lore reasons for it I am totally fine.

I want to ask with what software you made this though?

**Comment by UnorderedSigh** [comment]
> I want to ask with what software you made this though?

Gimp 2.10. I am going to PR the assets soon.

**Comment by UnorderedSigh** [comment]
> I was referring to it as a haze because that is what it is in the data files.

I can't really help that; `haze` is what the code wants. The image file is `pug-cloak+.jpg` which should make the intent clear.

**Comment by UnorderedSigh** [comment]
> something this large scale when they could just as easily make a backup elsewhere

The backup copy is no longer needed, and the cloaked system was necessary to make a hide-out for the anarchists the Pug were manipulating. This "backup copy" isn't just a backup: it is a three-race science colony with a century of advancements they can now share with the humans and Hai. It also contains Korath that could one day be used as interpreters. Also, this isn't a major use of resources for the Pug. They've only dedicated one ship to the task.

Lastly, these are the Pug, and it is unlikely you've seen all the purposes for which the ship is there, cloaking a star system.

**Comment by UnorderedSigh** [comment]
> I also don't really like that this removes even more agency from humanity.

Centuries of manipulation by the Pug is part of the Endless Sky lore. I'm sure humanity didn't like it either. The Quarg certainly didn't, but look at what happened to them.

If you don't want a "Pug master race" to be the Endless Sky lore, then you need to rewrite the game and its lore document.

**Comment by Saugia** [comment]
Have to agree, I'm very turned off by any sort of Pug involvement in HR.

**Comment by Arachi-Lover** [comment]
The document you reference isn't canon, it is simply a doc.

**Comment by UnorderedSigh** [comment]
Also, point of note: the pug merely tweaked the direction of humanity. They did not dictate how it would be reached, or exactly where it would go. They're not the "do this or we'll smack you" sort of manipulators, they ensure we have free will.

It is unlikely the Pug intended us to nuke ourselves, or for the Syndicate to conspire with Alphas, but they had contingency plans (their Tier 1 ships) in case something went horribly wrong.

**Comment by UnorderedSigh** [comment]
Am I right in saying that the primary objection to this is the Pug involvement?

I'm sure, with creativity, I can invent an alternative.

**Comment by UnorderedSigh** [comment]
My use of the Pug was the plot device for hiding Devil-Run. It is not needed beyond that. If the use of the Pug is so problematic, I can replace them with another plot device.

**Comment by UnorderedSigh** [comment]
I'm closing the PR, with plans to remove the Pug from the story (which is actually not that much work).

However, I would appreciate comments on other aspects of the PR.

**Comment by Saugia** [comment]
Give it a minute.

**Comment by Amazinite** [comment]
Not going to lead you on with putting significant time into review this. I'd must rather see this smugglers arc of HR removed entirely, with much of the other HR5 content heavily reworked. Hai Reveal should be focus on the relationship between the Hai and humanity, and as a secondary characteristic, focus on the relationship between the Unfettered and the Hai more broadly. Since the beginning, I've thought that this whole HR5 section with the wormhole and the systems beyond it has been rather outlandish and "out of scope" with what HR should be focused on, particularly with how it veers off into talk about hyperspace tracking and history lessons on the Syndicate and kidnapped Korath somehow being involved as well.

**Comment by MasterOfGrey** [comment]
If you would like to leave off things until you open your own PR, then that is fine.

While I've been rather busy the last couple weeks I know Sigh had put a lot of thought into closing (and not opening/re-opening new) plot holes and resolving other issues raised by various people though, so depending on what you end up submitting, you should probably expect the content here to be used as a reference for tracking that issues are resolved without introducing more problems.

**Pull request closed without merging**
