### PR TITLE
feat(refactor): moving ShopPanel ship selection into its own class

### PR DESCRIPTION
**Pull request by flowers9**
**Feature:**

## Feature Details
ShopPanel is a large class, and this cleans up the header and code a bit.  In particular, the ship grouping code had some duplication I was able to remove.  ShopPanel already has two in-class classes, so this was moved into a completely separate class.

One slight change was that if you're toggling a ship group selection (shift-#), it will no longer check ships that cannot be shown when checking to see if all ships in the group are present (so it'll deselect the whole group if all the displayable ships are present, even if there are non-displayable ships in the group).

Another slight change was that when shift-clicking on a ship with no current selection, only the clicked ship is selected.  Previously, all ships from the end of the list to the clicked ship would be selected.

Edit: shift-clicking on a selected ship selects all ships (this now matches what happened when you shift-clicked on the first ship when it was already selected).  However, if all ships are already selected, they will be deselected, leaving only the ship you clicked on as selected.

And the code in Shipyard::SellShip checked for ship system and disabled status rather than planet when finding a new ship to select after selling the current one, so was moved over to match the rest of the selection code.

## Testing Done
Tried many ways to select and deselect ships in the side pane.

### CODE REVIEW

**Comment by flowers9** [comment]
I would appreciate any advice on how to pull out a useful error message from that.  I have no idea what went wrong.

**Comment by warp-core** [comment]
Looks like there was a segfault while running one of the ship selling integration tests. I suggest running the integration test locally in a debugger to try and reproduce the issue; the debugger should make it fairly straightforward to determine where and how the segfault is occuring.

**Comment by flowers9** [comment]
Thanks!  I just started figuring out how to do that.  I probably cleaned something up that I shouldn't have. ;)

**Comment by flowers9** [comment]
I think I figured out why shift-click was selecting everything from the end - if only the first ship was selected (the default when entering the shop), if you shift-clicked on it all ships would be selected.  So, I added a more generalized version of this (see Edit: in main description).

**Comment by quyykk** [comment]
I'll go ahead and close this in favor of #9074, which includes this PR anyways, to avoid having to fix so many merge conflicts.

**Pull request closed without merging**
