### PR TITLE
fix(content): Use both `on capture` and `on kill` in bounty jobs

### PR DESCRIPTION
**Pull request by Anarchist2**
~these jobs will be the death of me~

This PR adds `on capture` to all of the bounty missions with `on kill`, meaning that the mission will function properly whether the targeted is destroyed or captured.

### CODE REVIEW

**Comment by Hurleveur** [comment]
Thats weird I always thought capture counted as kill

**Comment by warp-core** [comment]
> Thats weird I always thought capture counted as kill ~also dont give money on cap thats perfect balancing~
> 
> Edit: wouldnt the proper way to address this in the long run simply be adding a way to write `on capture kill` And that logic can extend to `on accept decline` for instance

NPC actions should probably be changed to handle capturing a ship as if it were destroyed the same way NPC objectives handle it.

**Comment by warp-core** [comment]
It looks like there's an issue in NPC::Do where the original ShipEvent object is passed to NPC::DoActions, but this object does not account for things like capturing also counting as destroying the ship, this change is applied to a local variable that is then added to a class member collection of ship events. Since that local variable isn't being passed to DoActions, it only sees a cpature event, not a destroy event.

**Comment by Amazinite** [comment]
I think it'd make sense to instead change the behavior of `on kill` to actually match the `kill` objective (i.e. the ship is destroyed or captured), and provide a separate `on destroy` action that behaves like the current `on kill` action does (i.e. the ship is destroyed, ignoring captures).

**Pull request closed without merging**
