### PR TITLE
Update Xcode project to compile unit tests

### PR DESCRIPTION
**Pull request by DeBlister**
**Bugfix:** This PR addresses the issue that unit tests are not readily buildable on macOS.

## Fix Details
The tests folder has been added to the Xcode project to provide access/scope to the new build target.  It was done as a group rather than just a directory to avoid cluttering up the top-level of the Project navigator when adding the test files to the Compile Sources of the new build target.  main.cpp was similarly removed from the Compile Sources to provide a single entry point.

## Testing Done
I can build and run the game with the original build target and I can build and run the unit tests with the new build target.

## Checklist
- [x] Update the include paths in the test files to properly reflect the file structure
- [x] Update the Xcode project so that the unit tests can be built as a new build target
- [x] Update build targets so that there's a single library target to which the two targets that compile the game and tests point
- [ ] Update the xcode-checker to work with these changes
- [x] Update the CI workflows to make use of this change and run the unit tests on macOS
- [x] Verify that the CD workflow still manages macOS properly

### CODE REVIEW

**Comment by DeBlister** [comment]
The macOS build check is failing because of all the implicit conversions that have become exposed when building into a framework first.  I'm not sure if it would be more appropriate to address these Xcode warnings/ci errors
A) in the integration test itself
B) by correcting them so they are no longer an issue

I don't know how I would solve this in the integration test but it should be easily resolved by a bunch of `static_cast<>`'s (102 to be exact).

**Comment by DeBlister** [comment]
@tehhowch how would you like me to address the [comment above](https://github.com/endless-sky/endless-sky/pull/6843#issuecomment-1138023746) regarding implicit conversions.  

What I see when I build for debug:
EngineDebugWarnings
What I see when I try to build for release:
EngineReleaseError

**Comment by DeBlister** [comment]
I think I fixed the warnings/errors on the engine target.  For some reason `xcodebuild` can't compile the project properly (same thing for me on the command line as in the checks).  Xcode itself can, though, which is perplexing.

**Comment by DeBlister** [comment]
It fixed `xcodebuild` failing on my machine, at least...

**Comment by DeBlister** [comment]
Yeah, I broke it by accident what should have been an unrelated change.

**Comment by DeBlister** [comment]
BTW, I'm working on updating the CI workflow in [#5](https://github.com/DeBlister/endless-sky/pull/5).  The CD workflow may be fine but I'll look at that after I finish with CI.

**Comment by DeBlister** [comment]
@tehhowch Any chance we could refactor so that source directories hold files for a single target only?  In the Xcode project checker, accounting for `main.cpp` being mixed in with the engine files in `source` is going to be a little ugly and not easily extensible for the future.

**Comment by DeBlister** [comment]
I'm working on the Xcode checker in [#6](https://github.com/DeBlister/endless-sky/pull/6).

**Comment by quyykk** [comment]
The XCode project is now on the way out, replaced with an XCode project generated by CMake which supports building the unit tests as well. So we can close this now, sorry

**Pull request closed without merging**
