### PR TITLE
feat(UI): Implement settings pagination

### PR DESCRIPTION
**Pull request by Terin**
This PR implements settings pagination from #7452. Currently, the settings panel is 100% full on both sides. PRs #7324 and #8429, along with multiple upcoming ones from @Koranir have additional settings that push it past the single page. Rather than having each implement a second page in their own way, we should have the pages split upstream first.

image

### CODE REVIEW

**Review by Koranir — APPROVED** [review]
Looks Good!

**Comment by Koranir** [comment]
Actually, it might be nice to switch out the AI and performance tabs.

**Comment by Zitchas** [comment]
Good idea. That being said, I think that "AI" should probably be renamed "Gameplay", and "Rehire lost crew" moved to that panel. The reasons is that the AI things and that one option from "Other" are the only things that materially affect actual gameplay - not just how things look or performance, but actually change how the game plays.

**Comment by Terin** [comment]
Those changes sound good to me. So right now we're at this, does anyone have strong feelings against those?
image

**Review by RisingLeaf — APPROVED** [review]

**Comment by RisingLeaf** [comment]
requesting warp because warp did the mechanic for multiple pages

**Review by warp-core — APPROVED** [review]

**Pull request merged**
