### PR TITLE
Rebalanced Star Queen

### PR DESCRIPTION
**Pull request by Disiuze**
This PR was made with permission from @kikotheexile and @Sinsling.
I take no credit whatsoever, as they have done all the work and it seems that they do not know how to make Pull Requests.

Quoting @Sinsling's issue:
> First time posting here, let me know if I miss anything important on this post;
> 
> When looking at the Star Queen's price tag, I couldn't figure out why it had such low profit potential. The current vanilla queen requires a profit of 143 credits per day/ton just to pay crew wages, meaning you need to make 246 when moving one sector after taking off. The types of missions that are suppose to make this ship profitable -ferry missions, presumably- can be done with a fleet of 2 mules providing more free passanger space when their turrets are removed with a fraction of the crew cost and 8 times the cargo space.
> 
> Perhaps I am missing something, but after discussing it with Kiko the Exile on steam, we played with some numbers to provide a more competitive ship for the 7m+ base price without (hopefully) making its' capture play too good.

> For a quick summary of the changes;
> -Lowered the min crew and max passengers
> -Increased shields, lowered hull
> -Removed the starting missile launchers
> -Added extra engine space to fit third tier atomic engines
> -Added scram drive, ram scoop, and increased fuel
> -Lowered max outfit space to account for on-board "luxuries"; also reduces crew bunk spam
> 
> Over-all, the ship feels much more like a luxury liner, and doesn't have such a harsh cargo:crew cost. It can also be fitted into a good capture ship for the cost, making for some more interesting uses of the star queen.

### CODE REVIEW

**Comment by kikotheexile** [comment]
We're steam noobs, we do nooby stuff on steam. Thank you for submitting this for us.

**Comment by Sinsling** [comment]
+1 Disiuze getting credit for helping us get it here.

**Comment by MarcelineVQ** [comment]
There's something about the star queen, I can't help using it at some point on every other pilot
Something endearing about driving a luxury liner to do unluxurious things

**Comment by Disiuze** [comment]
It's still, quite a capable warship, with some retrofitting.

**Comment by LocalGod79** [comment]
i believe the Star Queen's niche to be "to be the worst ship in the game", to illustrate to potential content developers what attributes a large, bad ship could be like.

still, i appreciate effort that has been made: did anybody want to create a new sprite?  perhaps use Kerry's as a "modern version"?  did he post @2x?

**Comment by Wrzlprnft** [comment]
I think when someone sends a mail to kerry, we can get our hands onto the 2x sprite and the blender model. He seemingly was busy with reallife and then lost track/motivation. With a little bump he might even publish the rest of his work.

**Comment by mdsmestad** [comment]
I did like that star queen he posted, but I don't think his art style was very congruent. It was beautiful, just not congruent. I could always take a crack at the sprite.

**Comment by endless-sky** [comment]
The extra cost is what you pay for things like wood paneling in the living quarters, bathrooms with marble countertops and real running water instead of sonic showers. In other words, it's intentionally supposed to be an overpriced "luxury ship" that's only useful as a tempting target for pirates.

**Comment by Wrzlprnft** [comment]
How about we implement some sort of luxury attribute missions can check on?

**Comment by Amazinite** [comment]
You could create missions with a `to offer` of `has "ships: Transport"` making them only offer if you have a dedicated transport ships. Maybe also make a Heavy Transport or Luxury Transport category and put the Star Queen in it in order to have higher level transport ship missions.

**Comment by johndh** [comment]
Why not leave the Star Queen as it is and add a Modified Star Queen that's stripped down for use as a combat transport?

**Comment by KiLEdEnNis** [comment]
it is a luxury ship, the general idea is luxury everywhere for rich people, so maybe making Star Queen specific missions that transports a few rich people that pay a lot more than regular plebs

**Comment by Wrzlprnft** [comment]
I'd go with derpys idea for the original starqueen. But i wont oppose a combat modified decoy version

**Comment by kikotheexile** [comment]
Actually that makes a hell of a lot of since imho, combining the ideas. Have decoy or refitted versions of the starqueen, and then implementing a check for luxury ships, thus making it that specific missions only drop with luxury ships, and also generate more pirates for luxury transports much the same way as they are generated for freighters. 

Something that makes it logic out in the game so people have an excuse to purchase one. Perhaps even a mission thread involving the Paradise Planets?

Idk, if no one else beats me to it i might work on it.

**Comment by KiLEdEnNis** [comment]
I'd say special well-paying transport missions, but a modified version could be a thing, but why would "pirates" bother modifying a ship like that? modified clippers make more sense since they are like the best ship early-game until you can afford a better ship

**Comment by BorkBorkGoesTheCode** [comment]
> I'd say special well-paying transport missions, but a modified version could be a thing, but why would "pirates" bother modifying a ship like that? modified clippers make more sense since they are like the best ship early-game until you can afford a better ship

I think it's supposed to be a pirate bait/trap.

**Comment by Alkallid** [comment]
They were like, "Ooh, high-class hostages! Let's take 'em! Shit, we killed them. Ooh, but purty expensive ship!"

**Comment by BorkBorkGoesTheCode** [comment]
> The extra cost is what you pay for things like wood paneling in the living quarters, bathrooms with marble countertops and real running water instead of sonic showers. In other words, it's intentionally supposed to be an overpriced "luxury ship" that's only useful as a tempting target for pirates.

> Why not leave the Star Queen as it is and add a Modified Star Queen that's stripped down for use as a combat transport?

> I think it's supposed to be a pirate bait/trap.

> They were like, "Ooh, high-class hostages! Let's take 'em! Shit, we killed them. Ooh, but purty expensive ship!"

You could add a new Star Queen with all the luxury stripped out and replaced with a barracks filled with a regiment of marines and hidden weapons bays undetectable by scanners. Pirate bait.

**Comment by Disiuze** [comment]
Closing this and removing branch.

**Pull request closed without merging**
