### PR TITLE
Ships tagged spareDisabled will cease firing if a disabled ship drift…

### PR DESCRIPTION
**Pull request by jamespglaze**
…s between them and their target.

When the disabled ship is no longer obstructing the tagged ship's line
of sight to it's target, they will resume firing.

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
projectiles that change course when their target was disabled can help too

**Comment by pcordes** [comment]
Does this make the ship look for a target it can shoot at safely?  It would be bad for a ship to sit there not firing because it picked a target but then decides not to shoot after all.

**Comment by Amazinite** [comment]
Currently if a ship targets an enemy and there is a disabled ship between it and its target, it will shoot at the disabled ship to try and hit its target, destroying the disabled ship. 
This is suppose to stop that from happening, making a ship with the disable tag not fire at its target if there is a disabled ship it could hit in the way.

**Comment by pcordes** [comment]
@Amazinite, yes I can see that, but I think this stops a ship from firing its turrets at all, even if there's another ship they could hit without damaging any disabled ships.

e.g. consider the case where `currentTarget` is on the other side of a disabled ship, but there's also a fighter buzzing around.  Don't we want to fire turrets at the fighter, instead of sitting there not firing?

Inside the loop over Hardpoints, there's a loop over enemy ships to find one to shoot at:  `for(const shared_ptr<const Ship> &target : enemies)`.  The condition is `if(mask.Collide(-p, v, target->Facing()) < 1.)`.

There are a couple other places in the function where `command.SetFire(index);` is called, too.  I'm not sure I've fully understood it.

**Comment by Amazinite** [comment]
> @Amazinite, yes I can see that, but I think this stops a ship from firing its turrets at all, even if there's another ship they could hit without damaging any disabled ships.

That may be the case as I can't exactly read the code, I'm just stating the intended use.

**Comment by Bladewood** [comment]
It conserves battery power.

**Comment by jamespglaze** [comment]
@KiLEdEnNis Good idea, I'll see if I can do it.
@pcordes Indent is fine in my code, seems to be a github issue.  Ships currently don't look for a new target, I'll see what I can do potentally.  if I understand correctly command.SetFire(index) sets a command to fire the weapon at hardpoint(index).

**Comment by jamespglaze** [comment]
So I feel dumb but apparently I wrote this commit against an old version of the code, I am gonna have to fix it to work with the current release  :/

**Comment by jamespglaze** [comment]
Alright, so getting homing weapons to find a new target after their target is disabled is going to be a bit more challenging, I also don't know how lore friendly that would be.  Making ships look for a new target if theirs is obstructed should be doable, I just need to sift through the code some more to fully understand the targeting mechanic.

**Comment by jamespglaze** [comment]
@Peaksh You would have to compile from the source code, which is rather difficult if you don't know what your doing, and I'm not really the best person to ask about that.

**Comment by jamespglaze** [comment]
Fixed the indent issue.

**Pull request closed without merging**
