### PR TITLE
Pirate Troubles mission line in Hai space

### PR DESCRIPTION
**Pull request by Amazinite**
**Content (Artwork / Missions / Jobs)**

## Summary
Ref: #4646 #4649 
Adds a new string of missions in Hai space to gain up to 80 reputation toward being able to access Hai-home permanently, as well as getting paid up to 3 million credits.

* A Hai system near the wormhole is attacked by a sizable pirate.
* The Hai inform you that this attack and other recent attacks from pirates is the cause of a pirate gang known as Scar's Legion, and they ask you to track them down. This mission gives clearance to Hai-home and sticks around in the player's active missions for a while, giving them ample opportunity to buy a Shield Beetle without having the necessary reputation.
* The player is then let loose. Landing on various pirate worlds close to the wormhole, as well as landing on Farpoint, gives you information about Scar's Legion.
* After you've gathered enough information about the gang, the player narrows down the gang's hideout to 4 systems. The player must locate Scar's Hideout, an asteroid base in Danoa, and land.
* From here, the player interacts with the leader of the gang. The gang leader says that if the Hai give them a tribute of weapons and technology, they'll leave the Hai alone. If the player refuses, then they must fight the leader before returning to Hai-home. If the player accepts, they must return to Hai-home and then escort three freighters to Scar's Hideout and back.

This is intended to replace #4646, since its narrative doesn't work well after the merging of #4649.

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: The asteroid base is just a render of the first frame of the large rocky asteroid.
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/101

### CODE REVIEW

**Comment by Amazinite** [comment]
Anyone?
download

**Comment by LordInsane** [comment]
Should solving the Scar's Legion issue by defeating Scar be a full 40 reputation difference with the Hai (nearly half of all reputation possible with the Hai)? The Hai elders find it unfortunate it came to that (whether you mention Scar's tribute demand or say they weren't willing to negotiate), but they do express appreciation to you, with one even expressing a preference for that outcome over tribute, so perhaps an on decline adding 10 or 20? From a gameplay perspective, while you skip the escort mission, you also had a more difficult and time-consuming previous mission.

**Comment by Amazinite** [comment]
I've fixed it so that both endings get +80 rep in total. I also moved most of the payment so that both endings get a large amount, with the "peaceful" ending only getting an extra 500k.

**Comment by jostephd** [comment]
Given that the purpose of the mission string is to let the player earn reputation in order to be able to access Hai-home, should the `clearance` attribute be added to `Pirate Troubles [3]`?

**Comment by Amazinite** [comment]
@jostephd Clearance is given by Pirate Troubles [1] and held until Pirate Troubles [3] is done.

**Comment by jostephd** [comment]
@Amazinite Thanks! I did ask on Discord first but no one knew, so I asked here.

**Pull request merged**
