### PR TITLE
Add Ambient Occlusion to several ship models

### PR DESCRIPTION
**Pull request by JanErikAhrens**
## Summary
Ambient occlusion is an effect that helps create depth in 3D images, and is one way to mitigate the "flat" look a lot ship thumbnails give without post processing. Most ships artificially add ambient occlusion in post, but I found that making this effect procedural not only can save time, but it also helps bring out details that a human would miss during the post step. This can already be seen in game with the Auxiliary and Combat Drone, to - in my opinion - their great benefit. In the end, I want to add the effect on all ship models that I have redone in the past:

- [x] Carrier
- [x] Corvette
- [x] Cruiser
- [x] Frigate
- [x] Gunboat
- [x] Lance
- [x] Rainmaker
- [x] Raven
- [x] Splinter

## Save File
This save file can be used to view all affected ships:
[Aaron Zuhl~All remodels.txt](https://github.com/endless-sky/endless-sky/files/8349711/Aaron.Zuhl.All.remodels.txt)

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/22
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/230

### CODE REVIEW

**Comment by Zireael07** [comment]
> I found that making this effect procedural not only saves time

Is there a readme somewhere for how assets are created (I seem to remember requirements such as a certain perspective), it'd be worth it to add info on how to do it for future contributors.

**Comment by JanErikAhrens** [comment]
Well there is this: https://github.com/endless-sky/endless-sky/wiki/CreatingShips
I probably could create a little guide fairly easily, but that can hardly just go in the wiki. Not entirely sure where I could post it though.

**Comment by Zireael07** [comment]
Why can't such a guide just go into the wiki (as a separate subpage if it's big)?

**Comment by JanErikAhrens** [comment]
I mean it possibly could in the end, but I don't have access to it, and I'm not sure it would make sense if only a small subset of ships even use AO.

**Comment by EjoThims** [comment]
Seeing them side by side here in the PR makes the difference (and purpose for it) a lot more evident than the previews in Discord! Really enhances the distinction between the different materials, too.

If the goal is to check off the whole list in this single PR, I'd think it's probably best to convert it to a draft until you knock them out.

**Review by EjoThims — APPROVED** [review]
Very subtle differences, but I think it's a definite improvement overall.

**Pull request merged**
