### PR TITLE
Buff the Scout

### PR DESCRIPTION
**Pull request by Anarchist2**
The Scout is a wanting ship: while it is 300k credits cheaper than the Bounder, and has 15 more cargo space, it has far less health, less bunks, less fuel and higher upkeep, often leading to players skipping over the Scout in lieu of the Bounder. Many of these weaknesses go against the descriptions of both ships, which describe the Scout as an older vessel made for a more dangerous era, while the Bounder is a vessel optimised for courier duties. This PR adjusts the stats of the Scout to make it better fulfil this role.

Changes:

- ~**Make the Scout slightly larger.** Right now, the Scout is only 90 pixels high. While the Heavy Shuttle, a vessel roughly 2/3 the mass of the Scout, is 10 pixels smaller vertically and horizontally, it takes up more area in total due to its shape. This PR makes the Scout slightly larger to more accurately reflect its mass. ~
- **Increase shields from `1200` to `2000`.** This brings the Scout from the durability of a Sparrow/Flivver to the durability of a Fury. It still has less total HP than a dedicated combat vessel like the Hawk, or the more expensive Bounder, but it will be able to take much more punishment than before.
- **Reduced required crew from `2` to `1`.** You could try to explain the extra crew member as being some sort of holdover from its previous role, but being saddled with crew wages makes the ship especially unappealing compared to the Bounder. Losing a required crew also gives the ship an effective extra bunk.
- ~**Increase fuel capacity from `800` to `1000`.** While both the Bounder and the Scout are said to be designed for long-range ferrying, their respective descriptions imply that the Scout would have more fuel capacity, not the Bounder. I also considered reducing the Bounder to 800 fuel capacity, but decided against it.~
- ~**Increase weapon capacity from `40` to `50`.** It doesn't make sense for the vessel designed for a more hostile era of space travel to have lower weapon capacity than the ship that wasn't.~

HDPI is at https://github.com/endless-sky/endless-sky-high-dpi/pull/307

### CODE REVIEW

**Review by ravenshining — APPROVED** [review]
I've always had a soft spot for the scout.  Nice to see it get a modest buff towards relevance.

**Comment by Zitchas** [comment]
I fully support reducing the Bounder to 800 fuel. Having any more than 8 jump range is really excessive in human space, at least for a stock ship. I doubt there's enough courier business to make having 10 jumps in a standard ship a viable thing. The few people who need that can use fuel pods. (In general, I find fuel amounts in human ships to be excessive. It's not like they routinely have to cross big expanses of empty space or anything, and there's really zero exploration going on.)

I'd also leave the size of the ship alone. Being small and hard to it is more valuable than the extra shields, honestly. (I'd much rather shrink the shuttle than grow the scout.) As it is, though, I'd just chalk up the density difference to the shuttle being very lightweight and empty for its size.

**Comment by EjoThims** [comment]
I agree with it not really needing the size or weapon space bumps, but rest seems perfectly in line to me.

**Comment by warp-core** [comment]
I don't think it needs the weapon capacity increase. It'd give it as much as the Hawk and more than every other (non-marauder) human interceptor, while also becoming as durable as a Fury, while also having way more passenger and cargo space than any interceptor, and a turret mount, and more outfit and engine space. I don't think it should be better than every interceptor at combat as well as being able to carry more passengers and cargo.
I don't really mind the fuel capacity increase, but if it is only being done to bring it above the Bounder, perhaps the Bounder's should be decreased instead?
I think I would prefer the sprite be left the size it is, but I don't really have strong feelings on this either way.
Shield and required crew changes are good.

**Comment by Anarchist2** [comment]
The Scout isn't just oddly sized when compared to the Heavy Shuttle. Take this diagram of interceptors, small transports and light freighters, sorted from left to right in ascending loaded mass:
gaming
The Scout is the third heaviest ship of the bunch, but it looks a similar size to ships all the way on the left (compare the duplicate Scout closer to the left with the ships around it, then compare the true Scout with the ships around it),

**Comment by ravenshining** [comment]
...How about 46 for weapon space?  You could fit a pair of heavy lasers and an AM turret with that, while still being less space than the Bounder or Hawk enjoy.  Doesn't seem right to have a ship made for hostile times and territory to have such a tight hardpoint:weaponspace ratio.

I suppose I agree with Zitchas about fuel and size though.   I'd rather the Bounder be shrunk than the Scout grown, as well as a number of the smaller ships to a lesser degree.

**Comment by Zitchas** [comment]
I'm still not a fan of making it bigger, but the extent of the rest of the changes look good. To be honest, the crew change alone would make me sure a bit more likely to use this, the shields just reinforce that.

**Comment by Anarchist2** [comment]
I've reverted the size changes to the Scout.

**Review by Zitchas — APPROVED** [review]
Looks good to me.

**Review by EjoThims — APPROVED** [review]

**Pull request merged**
