### PR TITLE
Injured, player-owned escorts regroup with the player's flagship

### PR DESCRIPTION
**Pull request by tehhowch**
Refs #3008, #3004 
 - endless-sky#3008 fixed an issue with a loss of target combat
 - However if injured, the ships should not be lured away by enemy ships until they have repaired somewhat.

This makes the player's escorts behave with a bit more self-preservation instinct rather than - even while critically injured - chasing off into the distance after a hostile ship.

### CODE REVIEW

**Comment by SirStigII** [comment]
Could this be made to work for allied ships as well?

**Comment by tehhowch** [comment]
Allied ships are generally governed by the personality tags a content creator gave them, so I don't know that it is correct to override their chosen behavior.

It's certainly possible to do - the simplest way would be dropping the it->IsYours() check from the changes being added here. Note that this would work both ways - enemy ships will retreat to their parent to be a bit more protected during recovery, which will cause more disabled ships to be destroyed by crossfire (one of the most common 'complaints').

**Comment by flaviojs** [comment]
Using `health < 1.` as a guard for the behavior is not good.

For small ships it might work fine (min hull 50%), but for big ships it definitely doesn't work well.
I let an escort Mule be disabled to see how it behaved. When it's shields are full it chases an enemy, but as soon as it gets a few hits it tries to run back to my side.
This would be acceptable for small fast/maneuverable ships that have little shield, but for big ships it is definitely bad. Another aggravating factor is that big ships have a lower minimum hull, and therefore trigger this behavior with more shield than small ships. A more consistent check would be `hull <= 50% && shield <= 50%` (assuming 0% shields when only hull is available).

From what I've seen during my play time with big fleets and small fleets, a good rule of thumb to avoid losses is to protect vulnerable ships (heavy hull damage) at least until their shields hit 50%. For some big ships, protecting until their shields reach the minimum hull is enough. Note that in really I'm just making a rough visual match of when they stop being priority targets, so a "smarter" way to guard the behavior would be to see if they are priority targets in comparison to other ships.

**Comment by tehhowch** [comment]
I wanted to keep the health check the same as that which triggers alternate behavior in NPCs, in light of a possible rework to the health formulation. Given that such a rework will involve updating the values and target values anyway, I can tune for better behavior now.

**Comment by tehhowch** [comment]
Swapped to use @flaviojs 's suggestion of `shields < .5 && hull <= .5`
Will need changing if we ever implement something that addresses #3092

**Comment by endless-sky** [comment]
Wouldn't that make it so that small ships (i.e. ships that are disabled at 50% hull) never retreat?

**Comment by tehhowch** [comment]
They would retreat while below 50% shields after being repaired, due to the `<=` compare for the hull.

**Comment by endless-sky** [comment]
As with all AI behavior gated on shields or hull, this might run into the issue where a ship right on the threshold gets stuck oscillating between the two behaviors.

Also, I wonder if this could use the new Ship::Health() measure I added for fighter repairing, maybe somewhere in the 25-35% range. That measure is based on damage until disabled, so it avoid the issue where ships disabled at 50% think they've got more time left than they actually do.

And, note that this *would* make it so a ship that is disabled at 50% hull would never retreat (because its hull will never be below 50% if it's not disabled, and it only retreats if both shields and hull are below 50%). The likelihood of hull being *exactly* 50% without crossing below it is astronomically small, so in practice the `<=` is no different from a `<`.

**Comment by tehhowch** [comment]
I saw the addition of that function in the big fighter commit and plan to address health based behavior with this pull this week.

**Comment by tehhowch** [comment]
I originally included #3538 in this pull, but figured that should be a separate issue.
To avoid needing to rework the `appeasementThreshold` interactions, I've opted to keep it based on the ship's absolute health. Same for the cloak hysteresis.

**Comment by LocalGod79** [comment]
i think more important to this would be to have damaged fighters and drones dock until repaired fully when the system is "safe" - the same conditions that will cause escorts to revive other escorts should trigger the "dock until repaired or hostiles are present" behaviour.  perhaps another issue/pr, but since preservation has been mentioned...

**Comment by tehhowch** [comment]
@LocalGod79 when this pull was written, fighters did not dock with the carrier at all unless the deploy order was rescinded. I can certainly include that situation in the AI autobehavior - the only time it would be "inconvenient" would be if the fighters were assisting the parent ship in mining asteroids. Probably that will be a different PR, though.

**Pull request merged**
