### PR TITLE
Fuel Damage attribute

### PR DESCRIPTION
**Pull request by Nechochwen-D**
I have added another damage type that drains hyper space fuel which could be used as either a method of preventing ships from leaving systems or used to cripple Flame Thrower ships.

### CODE REVIEW

**Comment by toilethinges** [comment]
Yay. Congratulations on #1492.

**Comment by Amazinite** [comment]
Works nicely. :ok_hand:

**Comment by Nechochwen-D** [comment]
You can also set a negative value to give fuel.

**Comment by Amazinite** [comment]
Yup, I tried that out as well; always got to mess with new stats be shoving them into the negative.

**Comment by Nechochwen-D** [comment]
If you look at the damage profile it completely bypasses the shields at the moment.

**Comment by endless-sky** [comment]
If the fuel damage is negative (i.e. a recharging beam) there are two issues:

* It cannot recharge a ship that has 0 fuel remaining.
* It can charge a ship beyond its maximum fuel level.

Also, like most special weapons it should probably be more effective when shields are down.

**Comment by Nechochwen-D** [comment]
Sorry if my code is still a bit kludgey. I am still learning and have quite a way to go.

**Comment by Nechochwen-D** [comment]
Closing this due do outdated code. Will open a new pull once I have balanced a few more things.

**Pull request closed without merging**
