### PR TITLE
Making Deep Archaeology 1 minor

### PR DESCRIPTION
**Pull request by Amazinite**
It was kind of annoying having another mission pop up while I'm getting ready to raid an Alpha base in Host.

### CODE REVIEW

**Comment by Bladewood** [comment]
> Alpha base on Hope

**Comment by Amazinite** [comment]
>>Alpha base on Hope

I keep mixing up Hope and Host. xD

**Comment by KiLEdEnNis** [comment]
it IS a good hiding place under all the ice...

**Comment by gunqqer** [comment]
You could hide a whole base under all that ice...

**Comment by Bladewood** [comment]
Hiding a base under the ice would not be a bad plan, if the Republic had not already rigged thousands of sensors in the ice.

**Comment by gunqqer** [comment]
But weren't all the sensors blown up in the beginning of the war?

**Comment by jafdy** [comment]
No, only when the free worlds moved into new tibet.

**Pull request merged**
