### PR TITLE
Stationary turret for missile hardpoint

### PR DESCRIPTION
**Pull request by RPBCACUEAIIBH**
With excelent tracking missiles it produces a nice curve shooting effect that was broken for me by the default turn rate. So I fixed it. :)
Add "turret notrurn" 1 to outfit attributes to make the turret stationary. (It overrides the specified or default turnrate!)

### CODE REVIEW

**Comment by tehhowch** [comment]
If it isn't a turret then it shouldn't use a turret mount IMO.

**Comment by Amazinite** [comment]
`Add "turret notrurn" 1 to outfit attributes to make the turret stationary. (It overrides the specified or default turnrate!)`

Why not just set the turn rate to 0 then instead of adding another attribute which pretty much just means `"turn rate" 0`?

**Comment by Tadrix** [comment]
Just use gun ports for non-turrets.

**Comment by RPBCACUEAIIBH** [comment]
> If it isn't a turret then it shouldn't use a turret mount IMO.

Well it's easier to just turn off the motor of an existing turret then to invent a new hardpoint or something...


> `Add "turret notrurn" 1 to outfit attributes to make the turret stationary. (It overrides the specified or default turnrate!)`
> 
> Why not just set the turn rate to 0 then instead of adding another attribute which pretty much just means `"turn rate" 0`?


Because that's what I did initially, but someone added a default turn rate that specifies a turn rate of 4 if the turn rate is 0, and also gives an error... so "turn rate" 0 is not working anymore!

> Just use gun ports for non-turrets.

Gun ports fire forwards, you don't get the same visual effect, and not every ship has gun ports...

**Comment by Tadrix** [comment]
`and not every ship has gun ports`
That's for a reason. The reason being that no ship should be able to do everything. The concept of an immobile turret is a wasteful one, and it's an attempt to circumvent the existing game balance.

Besides, the longer trajectory you're creating in this way is wasteful (presenting more opportunities for the missile to be shot down for no other apparent reason than the designer stupidity, and throwing the ship off-balance if we had the realistic inertia physics; there's a reason why IRL most aircraft launch their missiles forward). See also: [Artistic curving trajectories for no apparent reason](https://tvtropes.org/pmwiki/pmwiki.php/Main/Roboteching).

If you insist on having a weird firing angle, don't you think AI should be accounting for it? Which is the reason I believe that the point that you brought up is a specific case of *broadside firing mechanics* which were discussed, but never implemented. You could bring it up, if you wish, but first look up already existing issues on that topic.

**Comment by jafdy** [comment]
I think you need to find a workaround to your problem, the AI currently isn't able to use fixed weapons off angle. Perhaps use a very small turn rate so the turret doesn't turn perceivably.

**Comment by RPBCACUEAIIBH** [comment]
> That's for a reason. The reason being that no ship should be able to do everything. The concept of an immobile turret is a wasteful one, and it's an attempt to circumvent the existing game balance.

Look... I did not ask you to waste your time adding a feature for me, I simply did it. I did not add an actual turret that could possibly throw the game out of balance, I simply added the possibility to make the turret stationary. There's no need for complicating the AI it's a game not a real life simulator. A game where visuals count! (or at least they should...)

**Comment by RPBCACUEAIIBH** [comment]
> I think you need to find a workaround to your problem, the AI currently isn't able to use fixed weapons off angle. Perhaps use a very small turn rate so the turret doesn't turn perceivably.

The AI doesn't need to use fixed weapons, excelent tracking will do... :)

**Comment by jafdy** [comment]
If you add the ability to have an off angle turret then someone will try to put a fixed weapon on it. When they ask why it isn't working do you expect us to say "because some guy wanted this function for a mod he was doing". Adding a new feature to the game just for some mod should be a last resort when all workarounds have failed, and I have offered a workaround, using a number as large as 0.000004 will result it a turret that would take over an hour to make a full turn.

**Comment by RPBCACUEAIIBH** [comment]
> If you add the ability to have an off angle turret then someone will try to put a fixed weapon on it. When they ask why it isn't working do you expect us to say "because some guy wanted this function for a mod he was doing". Adding a new feature to the game just for some mod should be a last resort when all workarounds have failed, and I have offered a workaround, using a number as large as 0.000004 will result it a turret that would take over an hour to make a full turn.

Ok, will thest that, if it works, fine. I'll close this... What's the smallest value btw?

**Comment by MCOfficer** [comment]
> Ok, will thest that, if it works, fine. I'll close this... What's the smallest value btw?

It's defined as a `double`, so on most systems, the closest positive non-zero value should be 2^-1074.

That's 
`4,9406564584124654417656879286822e-324`
 or (it's hard to find calculators which don't break with these numbers, naturally)
 ```
1/202402253307310618352495346718917307049556649764142118356901358027430339567995346891960383701437124495187077864316811911389808737385793476867013399940738509921517424276566361364466907742093216341239767678472745068562007483424692698618103355649159556340810056512358769552333414615230502532186327508646006263307707741093494784
```

OR (brace yourself):

```
0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359923797965646954457177309266567103559397963987747960107818781263007131903114045278458171678489821036887186360569987307230500063874091535649843873124733972731696151400317153853980741262385655911710266585566867681870395603106249319452715914924553293054565444011274801297099995419319894090804165633245247571478690147267801593552386115501348035264934720193790268107107491703332226844753335720832431936092382893458368060106011506169809753078342277318329247904982524730776375927247874656084778203734469699533647017972677717585125660551199131504891101451037862738167250955837389733598993664809941164205702637090279242767544565229087538682506419718265533447265625
```
(that's 323 zeroes after the comma)

Sorry for the digression. Credit goes to @0kku for explaining to me how `e` works.

**Comment by jostephd** [comment]
Ref #3900

**Comment by RPBCACUEAIIBH** [comment]
Right... Thanks! :D I think 0.00000001 is slow enough for me not to notice any change in the past few hours, and does't give an error... so I think this is solved!

**Pull request closed without merging**
