### PR TITLE
fix(content): Make Wool Smuggling 1 on `complete dialog` make sense with Wool Smuggling 2 `blocked` dialog

### PR DESCRIPTION
**Pull request by lumbar527**
**Bugfix:** This PR addresses issue #9220

## Fix Details
Changes the dialog of both Wool Smuggling 1 `on complete` and Wool Smuggling 2 `blocked` to make more sense together.

## Testing Done
N/A

## Save File
N/A, only dialog changes.

### CODE REVIEW

**Comment by warp-core** [comment]
I think it might be better to remove the `on complete` from the first mission and put that text in an `on offer` for the second mission.

**Comment by Amazinite** [comment]
Yeah, not a fan of the split dialogs. But as noted in #9220, if we move the text to the on offer of the next mission then it needs to be a `conversation`, as we can't create `dialogs` that automatically accept.

**Comment by lumbar527** [comment]
So should I make it a conversation in `on offer`, or keep the split dialogs?

**Comment by lumbar527** [comment]
Wait—will it automatically accept if there is no `on offer` text? If so, then I could add an `on accept` dialog?

**Comment by lumbar527** [comment]
`on accept` doesn't work. Reverting commit.

**Comment by Amazinite** [comment]
This way of resolving the issue doesn't feel very clean to me. It has the same feel to it as disjointed conversations (an on complete conversation that leads into a `landing` on offer conversation with no actual gap in time/consciousness between the two). Since this is such a minor issue, though, I feel like I'd rather wait until #6632 is resolved.

**Pull request closed without merging**
