### PR TITLE
feat(artwork): New Bounder sprites

### PR DESCRIPTION
**Pull request by Anarchist2**
## Summary
This PR adds a new sprite for the Bounder and its derivatives.
image

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/issues/136
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/issues/362

### CODE REVIEW

**Review by Zitchas — CHANGES_REQUESTED** [review]
I like the new bounder image, but all the marauder images don't actually look better, just different.

Also, I find it completely impossible to tell the difference between engine and shield variant. As far as that goes, I find it next to impossible to differentiate *any* of the marauders. In the image above, if I magnify it up to 300% and spend a minute or two looking for details that I know should be there I can kind of just barely make out two little pixels that aren't on the other marauders that probably indicate two guns on the front where there used to be one, but I'm *never* going to be able to do that kind of meticulous examination of sprites in game. 

Guns. The original marauders had them either top mounted, or a little more prominent on either side; the new bounders have them mounted underneath and tucked in tight. The new guns are also darker. This combination of less gun being visible, and the bit that is visible being very dark renders them almost invisible in-flight. No one has time in a fight to look for one or two pixels that are different on this sprite versus some other sprite. Marauders are supposed to be threatening. Before, that was evident in that a fairly visible difference between bounder and marauder variant was the very prominent addition of a big gun in front of the cockpit. Now, though, that's been virtually erased and we're left with the only at-a-glance difference being the string of grey boxes. Not terribly intimidating, to be honest.

Beyond that, though, the marauder variants are post-construction modifications. They add all sorts of stuff that the original bounder just plain didn't and doesn't have room for. There's no space to discretely fit an extra gun inside the hull, that's why it's built onto the exterior of the nose. Even more so for the weapons variant, the double guns shouldn't be discretely tucked under the nose, but prominent and easily visible external mounts. Perhaps even something ostentatious like EVN's pirate valkyrie:
pirate valkyrie


The little bit of red on the turret emplacement in the stand-alone sprite looks like a nice differentiator... But it's completely obscured in-game, so it's effectively non-existant. Maybe if it was moved farther out so that it would be around the emplacement instead of on it? Just far enough that it is visible with most turrets used on these ships.

Admittedly, the original marauder bounder sprites aren't much better, but at least I can tell at a glance that they have extra gun(s) and can pick out the weapons version in-flight a little better.

All this being said, up close these new marauder bounders definitely look much better and rather nice. They should look great in scenes, or in animations, or other situations where the ship is taking up a sizeable portion of the screen. But at gameplay scales they're just different, as non of the improved detail translates to improved gameplay visibility, nor to improved capability of differentiating the variants in combat.

Summary:
- I can't tell the difference between shields and engine variants.
- All the guns are less visible in-flight than they were before. Original marauders had them top mounted, which makes them an identifying feature. Guns should be prominent.
- Red ring on weapon variant turret emplacements hidden by turrets
- Most of the new detail is basically invisible at in-game scales, but probably be nice improvements for scenes.

**Comment by Anarchist2** [comment]
I've updated the MBounder sprites.

**Comment by Zitchas** [comment]
Is the screenshot in the first post updated to show it?

**Comment by Anarchist2** [comment]
Not yet.

**Review by Saugia — CHANGES_REQUESTED** [review]
As with the Scout, this is looking better now that you've done a go-through with it. 

Original:

While the extra detail may not be easily visible in flight, it most certainly is in thumbnail views and is consistent with other models you've done that share the same type of detail.

I like that you've rounded out edges more -  most notably with the tail fins. This helps give the vessel a bit of a sleeker appearance and it seems a bit more, merchant-esq? Civilian? Either way looks nice on a Bounder. Angling the canards also suits this style more. Additionally, making parts thicker helps with visuals (tail fins, rear line structures).

Visible turret mounts, hurray! I think some ships in ES do work well without them, but in this particular case it works better with.

Variants:

Looks like you addressed the gun bit, which I agree with. The only thing I'm slightly missing from the originals is the darker hues of parts on them (the ring/arrayed structures) - however, the way you do have them now does fit with what I mentioned above about the curvilinear-ness, and matches the newer turret design better (why did the old ones look like guns?).

I do agree that the engine variant still needs a tiny bit to accentuate the engines. On the original, the engines were made a bit more wide and pulled out father in the back. You've done so on the newer one and added cone-shapes to the end, and while I like the design, they start to get lost due to them tapering off. I'd suggest taking the flat part of where the cones meet the engine, and pull each one out a bit further - right now that flat line is at the same spot as where the tails end, so there's a bit of a tangent there. Having them further out and past the fins will help.

Since the shield variant is essentially the engine variant/base marauder without emphasized engines, it looks fine. 

Same goes for the weapons variant from what I said above - perhaps darker parts around the guns, otherwise essentially the shield variant.

Lastly -  the second "canards" are curious -  are these supposed to be some type of interference plates? I do like their look because it's different and a bit scrappy, and comes off marauder-esque. Just wondering.

b

**Review by Zitchas — APPROVED** [review]
Thanks! looks much better, and now I can actually identify the different ships without spending a few minutes playing "hunt the pixel." Still not sure I can tell the difference between engines and shields variants if the engines aren't firing (only the flares are giving it away for me currently), but that's something, anyway.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
