### PR TITLE
Display projectile velocity in outfitter panel

### PR DESCRIPTION
**Pull request by Nescio0**
Display projectile velocity in outfitter panel (#3771).

### CODE REVIEW

**Comment by tehhowch** [comment]
UI pull -> include screenshots of relevant things.

**Comment by Nescio0** [comment]
Before:
screenshot from 2018-07-09 15-08-14
After:
screenshot from 2018-07-09 15-09-13
(particle cannon)

**Comment by Nescio0** [comment]
Range = velocity * lifetime, therefore it makes sense to display it on the same line. 
Velocity is per frame, i.e. 60 times as high? I'll correct it.

**Comment by Nescio0** [comment]
Here you go:
screenshot from 2018-07-09 15-52-29

**Comment by Nescio0** [comment]
Here you go:
screenshot from 2018-07-09 15-58-50

**Comment by KiLEdEnNis** [comment]
1800 velocity & 750 range means it'd travel 1800 pixels per frame, 1 frame being minimum, and dividing it by the 750 range a particle would only exist 5/12th of a frame

not sure what you're trying and honestly I didn't read it all but you messed up velocity

**Comment by tehhowch** [comment]
> 800 velocity & 750 range means it'd travel 1800 pixels per frame, 1 frame being minimum, and dividing it by the 750 range a particle would only exist 5/12th of a frame

@KiLEdEnNis velocity units as used by the game are indeed distance per frame, (`30` for the Particle Cannon), but velocity units used by humans are generally distance per second. Note that velocity **displayed** for ships is given in distance/second, not distance/frame: so this representation (`30 * 60` -> `1800`) is consistent with existing displayed data:
https://github.com/endless-sky/endless-sky/blob/e574ba53f0b2d2ec4afac4f3685affd97eb60843/source/ShipInfoDisplay.cpp#L197-L198

**Comment by KiLEdEnNis** [comment]
my mistake then, but isn't this gonna confuse a lot of people?

**Comment by gunqqer** [comment]
Probably not unless they are aware of how ES does velocity, but then they *should* be able to figure it out. Or we could add a tooltip explaining how it's in dist/sec rather than dist/frame

**Comment by jafdy** [comment]
People don't know that the "physics" simulation happens at 60fps so they won't automatically assume that the number refers to the distance travelled per frame.

**Comment by Nescio0** [comment]
Added a tooltip, just in case anyone might be confused.

**Comment by Amazinite** [comment]
Closing as this steps into the realm of providing too much information. Any efforts to show more stats like this should probably go into creating an advanced stats page. Ref: #4215.

**Pull request closed without merging**
