### PR TITLE
Manta description change

### PR DESCRIPTION
**Pull request by The-Legendary-M**
Manta description. "fleeing with it is impossible" -> "fleeing against it is impossible"

----------------------
**Content (Artwork / Missions / Jobs)**

## Summary
The previous description doesn't make too much sense. The Manta having a lot of long-ranged firepower has no direct implications to its mobility. The description probably means that fleeing from the Manta is difficult because it can still fire against a ship far away.

### CODE REVIEW

**Comment by Quantumshark** [comment]
Fleeing _from a battle_ with it. As in, you are in battle against the Manta and are hence unable to escape.

**Comment by The-Legendary-M** [comment]
Yes, precisely.

Fleeing from a battle against a Manta. Not fleeing from some opponent with a Manta. Hence the word swap.

**Comment by Quantumshark** [comment]
"Fleeing from a battle from it" doesn't work as a sentence. It'd be "fleeing from a battle against it" if that was what you wanted.

**Comment by The-Legendary-M** [comment]
Ah yes

**Comment by The-Legendary-M** [comment]
There we go. Fleeing against. Far less ambiguous from the original Fleeing with.

**Comment by The-Legendary-M** [comment]
Three alternatives to the proposed edit:
"Fleeing from it is impossible"
"Fleeing from it is virtually impossible"
 "Fleeing from a battle against it is virtually impossible"

**Review by mOctave — CHANGES_REQUESTED** [review]
I don't think this is any better than the current phrasing; some other word word probably work better.

The original `with` is confusing, since it implies two scenarios:
1. You're fighting it, and you want to escape.
2. You're escorting it, and every time you try to escape a battle, it dies.

Naturally, we want to imply only the first. Although `against` does this, it also suggests that it is the _only_ ship you're fighting. On your side, you may well have several fast, capable warships, but the way this is worded makes it sound like you still face inescapable doom.

**Comment by The-Legendary-M** [comment]
The changed wording removes any ambiguity, which I think is a positive change. The original wording does imply that escaping a Manta's long-ranged weapons are nigh-impossible (in a weaker ship, obviously), so I changed the wording so that it's clearer.

If you think that the meaning of the sentence itself is wrong objectively, would deleting the entire sentence work better? I see the description as more in line with a salesperson introducing the ship more than a cold factual assessment.

**Comment by mOctave** [comment]
> The changed wording removes any ambiguity, which I think is a positive change. The original wording does imply that escaping a Manta's long-ranged weapons are nigh-impossible (in a weaker ship, obviously), so I changed the wording so that it's clearer.

Yes, this is definitely much better than the original. I still feel like it could be improved, though maybe that's just me.

> If you think that the meaning of the sentence itself is wrong objectively, would deleting the entire sentence work better? 

No, I think the sentence conveys the right meaning and makes sense, it just has those extra connotations. I'd prefer your second alternative ("Fleeing from it is virtually impossible") here, since that doesn't suggest hyperdrive use as strongly and doesn't accidentally imply that it doesn't have any ships on its side.

If we wanted more detail, then maybe something like "escaping its fire is virtually impossible" would also work.

**Comment by TheMarksman-ES** [comment]
The description of the last sentence implies that if there's a battle with the manta around, it'd be impossible to run from it. Then again, it's a source of confusion, so an alternative would be "fleeing from it in battle is virtually impossible."

**Comment by warp-core** [comment]
It seems that the issue here is the confusion of "fleeing from a battle with it" with "fleeing with it from a battle."
Given that the alternate interpretation doesn't actually make sense, especially when considering everything that's come before it in the description, I'm not sure any change is warranted here.

**Comment by Saugia** [comment]
> Fleeing from a battle with it. As in, you are in battle against the Manta and are hence unable to escape.

Have to agree with Doom's comment. Including the context of the ship description, which is talking about the Manta, as a construction from the Syndicate, the phrase" ....fleeing from a battle with it" is not really ambiguous - it's not talking about you owning it as a captain, it's talking about it being a Syndicate product. So this seems unnecessary.

**Pull request closed without merging**
