### PR TITLE
MarauderSelfDestruct

### PR DESCRIPTION
**Pull request by LocalGod79**
after farming these from Winter in Yed Prior, i quickly got to 1B
credits before completing my collection (which still isn’t done)…

with the current stat, ~56% to engage in capture combat…

i’m not averse to nerfing the stat to .15 with your input, @endless-sky

### CODE REVIEW

**Comment by LocalGod79** [comment]
okay, so i tinkered with them a little bit, so that the player won't get too frustrated while trying to build a collection...

**Comment by endless-sky** [comment]
Seems reasonable. Bounty missions are unbalanced no matter what, because no one interferes with your capture and plunder.

Do you want to keep tweaking this or merge it as-is?

**Comment by LocalGod79** [comment]
i think it's pretty solid - if the steam community freaks out, i can always make a pull to nerf the s.d. stat a little...

**Comment by LocalGod79** [comment]
@Wrzlprnft - fyi (since it's Marauder related)

**Comment by Wrzlprnft** [comment]
I've seen it, and it's a good idea.

**Pull request merged**
