### PR TITLE
feature: recent price changes show up on screen

### PR DESCRIPTION
**Pull request by Hurleveur**
-----------------------
**Feature:** This PR implements a feature I've always found lacking

## UI Screenshots
Long title short, here is what you see whenever a change is made to your money, after said change has been applied (this is only a graphic change)
price change 1
price change 2
price change 3

## Feature Details
When a deal just happened (for instance you sold a lot of cargo, or just made a lot of missions) I always found myself wondering, how much did I just win? I look at the credits but frankly it doesn't help much, the transaction has already happened or in the best of cases I get a rough idea of it.
No more! Long title short, look at the images, they are distanced by 1 approximately, meaning it first shows up a bit bright then progressively disappears.
All the deals you make stack into it, refreshing it and adding to it (but after the 2 seconds are passed, it resets to 0, also it does not show itself when there is no change, like selling and buying back the same goods right afterwards).

## Usage Examples
Seeing how much you bought/sold for. It only shows the net gain, so the information on takeoff of how much money you made by trading still is relevant.

## Testing Done
Bought and sold outfits and goods.

## Performance Impact
N/A

### CODE REVIEW

**Comment by Ferociousfeind** [comment]
Seems a bit hacky, especially to put it there, right on the border of the ui element. Anywhere better for it to be placed?

**Comment by Hurleveur** [comment]
> Seems a bit hacky, especially to put it there, right on the border of the ui element. Anywhere better for it to be placed?

I'm completely open to suggestions, I just placed it there because that is where your money is.

**Comment by Amazinite** [comment]
We already have a message that pops up when you depart after having sold off commodities that tells you how much money you made. It can be easy to miss perhaps (#4794) but it's there. If we wanted something to show the player how much they made in total after a day, it'd make more sense to me to expand upon the existing message to also take into account missions. Either that, or, since we keep track of the player's net worth over the course of the last 100 days, perhaps have some way to review your account history in the player info panel.

**Comment by Hurleveur** [comment]
> We already have a message that pops up when you depart after having sold off commodities that tells you how much money you made. It can be easy to miss perhaps (#4794) but it's there. If we wanted something to show the player how much they made in total after a day, it'd make more sense to me to expand upon the existing message to also take into account missions. Either that, or, since we keep track of the player's net worth over the course of the last 100 days, perhaps have some way to review your account history in the player info panel. That might be getting into the realm of an "advanced player info page" type of thing, though.

That is exactly why I do this, the thing you get when you launch is too late (can't buy the outfits back!), and it does not show how much you gained from missions. Also it's easy to miss.
I am mostly doing this so that if you sell big outfits you did not remember having, or special smuggling commodities, you would notice instantly, and also that way you know how much missions you just ended/ what you just sold in the outfitter/shipyard... brought you.

**Pull request closed without merging**
