### PR TITLE
Changed some pictures with NC licenses, updated copyright

### PR DESCRIPTION
**Pull request by roadrunner56**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR addresses issue #6659, replacing NC licensed landscape images with commercial ones. This standardizes the copyright for our assets. Doesn't do anything practical other than maybe let us make deb packages in the future. Thanks to @MCOfficer for finding these images.

## Save File
lol I added 4 images

## Artwork Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/221

### CODE REVIEW

**Review by Amazinite — CHANGES_REQUESTED** [review]
station8 is an almost identical copy of space2.
space2

**Comment by Zitchas** [comment]
Question: Is this Thomas Hawk (who is credited with the pictures being replaced) a member of the community? Or were these simply available images that were licensed such that we could use them that someone found and added?

If these are pictures that were made by someone in our community, then I think we should keep them in. I value our community much more than absolute-freedom crusaders from outside. If they are just convenient pictures we found off the internet, then no harm in replacing them.

That being said, I like the new images. They're good additions in their own right, even without replacing anything.

**Comment by Terin** [comment]
> Question: Is this Thomas Hawk (who is credited with the pictures being replaced) a member of the community? Or were these simply available images that were licensed such that we could use them that someone found and added?

They're 10-11 year old images found on a flickr library. Almost certainly were just found on the internet.

**Comment by roadrunner56** [comment]
Yup, @Terin is right, just found them online. I'll get to finding a better image for station8.

**Comment by Zitchas** [comment]
Alright. If we're not just deleting a member of the community's contributions, then I'm fine with this replacement.

**Review by MCOfficer — APPROVED** [review]

**Pull request merged**
