### PR TITLE
fix: Remove instances of images having odd dimensions to avoid induced blurriness

### PR DESCRIPTION
**Pull request by Anarchist2**
**Bugfix** 

## Fix Details
This PR addresses issue #5456 and removes all instances of ships, thumbnails and outfit images having odd dimensions, thereby making them show up blurry in-game. Hardpoints and effects were chosen to not be modified in this PR, as they are small enough/only show up for brief enough that there wouldn't be a noticeable difference in quality.

HDPI version at https://github.com/endless-sky/endless-sky-high-dpi/pull/188

### CODE REVIEW

**Review by Pointedstick — APPROVED** [review]
Thanks!

**Comment by tehhowch** [comment]
Here's the full list of non-even WxH images in the base game:
```
Warning: image "_menu/haze-none" will be blurry since width and/or height are not even (1x1).
Warning: image "effect/fusionflare" will be blurry since width and/or height are not even (167x500).
Warning: image "effect/jump drive red" will be blurry since width and/or height are not even (55x55).
Warning: image "effect/ionball ring" will be blurry since width and/or height are not even (150x45).
Warning: image "effect/ka'het flare/medium" will be blurry since width and/or height are not even (15x150).
Warning: image "effect/korath flare/medium" will be blurry since width and/or height are not even (33x160).
Warning: image "effect/korath flare/small" will be blurry since width and/or height are not even (25x120).
Warning: image "effect/korath flare/tiny" will be blurry since width and/or height are not even (17x80).
Warning: image "effect/sheragiam" will be blurry since width and/or height are not even (13x900).
Warning: image "effect/sunbeam impact" will be blurry since width and/or height are not even (25x25).
Warning: image "hardpoint/inhibitor turret" will be blurry since width and/or height are not even (23x30).
Warning: image "hardpoint/proton turret" will be blurry since width and/or height are not even (20x43).
Warning: image "hardpoint/nuke" will be blurry since width and/or height are not even (10x75).
Warning: image "hardpoint/pwavehp" will be blurry since width and/or height are not even (18x47).
Warning: image "hardpoint/quarg skylance" will be blurry since width and/or height are not even (18x45).
Warning: image "label/graveyard" will be blurry since width and/or height are not even (411x313).
Warning: image "planet/sheragi_postverta" will be blurry since width and/or height are not even (100x75).
Warning: image "projectile/2x laser" will be blurry since width and/or height are not even (11x600).
Warning: image "projectile/2x heavy laser" will be blurry since width and/or height are not even (17x800).
Warning: image "projectile/bullet" will be blurry since width and/or height are not even (4x15).
Warning: image "projectile/thunderhead" will be blurry since width and/or height are not even (15x90).
Warning: image "projectile/tinyflare" will be blurry since width and/or height are not even (11x30).
Warning: image "star/a-dwarf" will be blurry since width and/or height are not even (25x25).
Warning: image "star/b-dwarf" will be blurry since width and/or height are not even (27x27).
Warning: image "star/black-hole" will be blurry since width and/or height are not even (2020x1515).
Warning: image "star/black-hole-core" will be blurry since width and/or height are not even (255x255).
Warning: image "star/f-dwarf" will be blurry since width and/or height are not even (25x25).
Warning: image "star/k-dwarf" will be blurry since width and/or height are not even (23x23).
Warning: image "star/k0" will be blurry since width and/or height are not even (85x85).
Warning: image "star/k5" will be blurry since width and/or height are not even (85x85).
Warning: image "star/k8" will be blurry since width and/or height are not even (85x85).
Warning: image "star/m-dwarf" will be blurry since width and/or height are not even (13x13).
Warning: image "star/m0" will be blurry since width and/or height are not even (77x77).
Warning: image "star/m8" will be blurry since width and/or height are not even (55x55).
Warning: image "star/neutron-core" will be blurry since width and/or height are not even (255x255).
```
We could limit the diagnostic to ships, thumbnails, and outfits if that makes more sense.

**Comment by quyykk** [comment]
There's one instance of a ship with odd dimensions remaining:

```
Warning: image "ship/caster" will be blurry since width and/or height are not even (259x400).
```

**Comment by Amazinite** [comment]
That's not a vanilla ship.

**Comment by quyykk** [comment]
Oh, my bad. I didn't realize. Should've double checked...

**Pull request merged**
