### PR TITLE
Fix jobs requiring outfits being acceptable with the outfits in cargo, not installed

### PR DESCRIPTION
**Pull request by warp-core**
**Bugfix:** This PR addresses issue #8516

## Fix Details
The `outfit: <outfit>` condition only requires that the player has the outfit locally. When landed, this means installed on any landed ship, in cargo, or in storage.
Counting outfits in cargo or storage is inappropriate for these jobs.

This PR adds a new autocondition: `outfit (active installed): <outfit>` which only counts local ships which are active (not disabled or parked), and uses that condition for these jobs.

~This PR instead uses the `outfit (flagship installed): <outfit>` conditions which require the outfit be installed on the flagship.~

~The `outfit (installed): <outfit>` condition could also be used, but this would count parked ships, but the player could also just switch flagship or park the flagship after accepting the job so maybe that's not important.~
~We could also add a new condition: `outfit (local unparked installed): <outfit>` which would only count outfits installed in local, unparked ships, but the player could park any of those after accepting the job anyway; requiring the outfit be installed on the flagship when accepting is much simpler and easier to understand.~

## Testing Done
None

## Save File
This save file can be used to verify the bugfix. The bug will occur when using {{insert commit hash / version}}, and will not occur when using this branch's build.
{{attach a save file that can be used to verify your bugfix. It MUST have no plugin requirements}}

### CODE REVIEW

**Comment by Hecter94** [comment]
I think I prefer `outfit (installed): <outfit>` for cases where you have a ship with a lot of bunks and a brig that isn't your flagship. 

Are you sure it counts parked ships? From the wiki it just says:
`If the player is landed, "local" is any outfit installed on any landed ships (i.e. disabled ships in-system don't count), in the player's pooled cargo, or in storage on the planet the player is landed on.` 
usually, it explicitly mentions parked ships if they are included. 

If it does include parked, but only ships parked locally, I think I'd still prefer that over requiring the brig be installed on your flagship.

**Comment by Hurleveur** [comment]
I agree we should use flagship installed for now, it is the most simple way of doing it
this aims to fix a bug not to change existing behavior

**Comment by Amazinite** [comment]
@Hecter94 Parked ships fall under "any landed ships... on the planet the player is landed on." So yes, `"outfit (installed): "` does include parked ships.

When it comes to the player experience, I think we'd be better to allow that, though. Sure, we shouldn't allow brigs in cargo to count, but we do currently allow brigs on your escorts to count, and making this change would remove that ability.

But as stated, we could also simply add another condition which matches what we want it to. These conditions are not difficult to create, so we shouldn't be shy to create a new one if our current ones aren't sufficient. I'd use the term `"outfit (local active installed): "` instead of "unparked," as it isn't just unparked ships, but also disabled ships that we want to avoid. Or perhaps just `"outfit (active installed): "`, as "local" is currently assumed in a lot of the condition names.

**Comment by Hurleveur** [comment]
Wouldnt it be better to reverse the logic, and to add parked installed? I would not expect installed to count parked ships, and it could cause unwanted behaviors

**Comment by Hecter94** [comment]
I agree with Hurl here. I wouldn't intuitively expect "local" to count parked ships; having a switch we can add to the condition to count parked makes more sense to me.

**Comment by Amazinite** [comment]
If `"outfit (installed): "` were to no longer count parked ships, then so to should `"outfit: "`, replacing that behavior with `"outfit (parked): "`.

**Pull request merged**
