### PR TITLE
Move plasma engines from Syndicate to Basic and Common outfitters

### PR DESCRIPTION
**Pull request by Nescio0**
Removed the Chipmunk and Greyhound plasma thruster and steering from the Syndicate outfitters, because those already sell their own X Ion engines. For comparison, Deep Sky and Delta V do not sell any engines other than their own either, nor does any alien outfitter. Besides, it's very unlike the Syndicate to support their competitors by selling their products when they have their own equivalents.

EDIT: new proposal: make availability of plasma and ion engines similar
* replace X2 ion engines with Chipmunk plasma engines and kept X1 in the Basic outfitter
* replace X3 ion engines with Chipmunk plasma engines and kept X1 and X2 in the Common outfitter
* add Impala to Delta V Basics outfitter
* remove Chipmunk from Kraz and Syndicate outfitters (because those systems typically have Basic and Common outfitters as well)

### CODE REVIEW

**Comment by jafdy** [comment]
Interesting thought. It would add to the feeling of having separate manufacturing areas but it would reduce the availability of plasma engines.

Do you have any gameplay arguments? (Something most of your PRs seem to lack.)

**Comment by Amazinite** [comment]
>Removed the Chipmunk and Greyhound plasma thruster and steering from the Syndicate outfitters, because **those already sell their own X Ion engines.** For comparison, **Deep Sky and Delta V do not sell any engines other than their own either**

Actually:
Sale of X1 and X2 series ion engines
screenshot_1
Sale of X3 series ion engines
screenshot_2
Sale of X4 and X5 series ion engines.
screenshot_3
As you can see, it's only the largest two sets of ion engines that are sold exclusively on Syndicate worlds.

For comparison:
Chipmunk series engines
screenshot_1
Greyhound series engines
screenshot_2
Impala, Orca, and Tyrant series engines
screenshot_3

So the two smallest plasma engine sets are sold almost as widely as the THREE smallest ion engine sets, with the three largest plasma sets only being sold in the south, as opposed to the two largest ion engine sets only being sold on Syndicate worlds.

So this
>Deep Sky and Delta V do not sell any engines other than their own either

Is incorrect, and by the logic of this PR,
>those already sell their own... engines 

ion engines should be removed from multiple different outfitters as well if plasma engines are being removed from Syndicate worlds.

Deep Sky Atomic engines are the ONLY engines in human space that are sold exclusively in the region they are built by, as they are top of the line engines that poorer outfitters like in the south simply can't afford to purchase for sale and the outfitters of the Syndicate and Paradise Worlds actually have historical competition with the Deep and likely wouldn't sell Deep engines for that reason.

And if it's a matter of the Syndicate being unlikely
>to support their competitors by selling their products when they have their own equivalents.

why is it that perhaps the most widely known Syndicate ship, the Star Barge, comes default with plasma engines?
screenshot_1

**Comment by Nescio0** [comment]
> Do you have any gameplay arguments?

What kind of are you exactly looking for? 
* It's consistent with other outfitters in the game
* It better fits lore
* The affected outfitters still sell Ion equivalents
* Ion and Plasma engines are quite comparable, much closer to each other than to any other engine type. Plasma engines are somewhat more powerful, larger, and more expensive. The energy efficiency is about the same, Ion engines have a better heat efficiency, plasma engines a slightly better mass efficiency.
* For the Greyhound, it means an availability reduction from 18 to 13 systems, the Chipmunk is available at somewhat more places; for comparison, Impala, Orca, Tyrant are only available at four systems (unchanged). 
Keep in mind both C and G are still sold at New China in Merak, which is only two steps from Earth and five steps from Hephaestus in Markab (the core of The Core), as well as at Tarazed and several systems in The South, The Rim, and The Dirt Belt, which together span quite a broad area. For comparison, the A250 is available at eleven systems, but all those are concentrated in the Deep, which forms just a tiny part of the map.

So yes, this change means these two plasma engines are no longer available in The Core. However, this is no great loss, since you can get ion engines there, and Plasma engines are still readily available.

**Comment by jafdy** [comment]
How will this improve the gameplay experience? 
If you can't give a good answer to that question on any public facing change then it is not something that if likely (or should) be merged. "Because it makes sense" is not a valid argument.

**Comment by Amazinite** [comment]
>"Because it makes sense" is not a valid argument.

Especially when it doesn't actually make sense, or an alternative/the current situation makes more sense.

**Comment by Nescio0** [comment]
> How will this improve the gameplay experience?

Because it encourages players to travel around the galaxy, which is a core element of this game.

Amazinite, I didn't see your long post when I was writing mine. Short answer: Ion engines are widely available because they're part of "Basic Outfits" and "Common Outfits", and this proposal doesn't change that. They are not included in "Deep Sky", "Delta V", or "Kraz". Check the `data/sales.txt` file.

If you think Chipmunk and Greyhound ought to be as widely available as the lower X Ion engines, they ought to be included in the CO sales list (but not under Syndicate, as is currently the case).

**Comment by Amazinite** [comment]
>If you think Chipmunk and Greyhound ought to be as widely available as the lower X Ion engines, they ought to be included in the CO sales list (but not under Syndicate, as is currently the case).

I never said they should be as widely available, only that this change is unnecessary.

And this
> it's very unlike the Syndicate to support their competitors

It's questionable If Delta V is even a major competitor of Syndicate ion engines given that like I said, the Star Barge comes default with plasma engines, which is practically an endorsement of plasma engines from the Syndicate, in which case it makes sense that Syndicate worlds would also sell the plasma engines that their own ships use.

**Comment by Nescio0** [comment]
> It's questionable If Delta V is even a major competitor of Syndicate ion engines given that like I said, the Star Barge comes default with plasma engines, which is practically an endorsement of plasma engines from the Syndicate, in which case it makes sense that Syndicate worlds would also sell the plasma engines that their own ships use.

The Bactrian comes by default equipped with a X5200, which doesn't mean that engine is sold at the same planet. I for one do not think outfitters have to sell all the outfits any ship at that planet happens to be equipped with.
But in case you're interested in default engines:
* Chipmunk: Finch, Sparrow, Star Barge (which is part of the "Basic Ships" available outside Syndicate space)
* Greyhound: Argosy, Clipper, Hauler I, II, III, Hawk, Headhunter, Modified Argosy, Nest, Quicksilver, Roost, Skein (none of which is a Syndicate ship)

**Comment by Bladewood** [comment]
The difference between your argument and his is that the Star Barge is by far one of the most common ships in human space, while there are probably only a dozen Bactrians left.

**Comment by Amazinite** [comment]
> I for one do not think outfitters have to sell all the outfits any ship at that planet happens to be equipped with.

Which again, isn't what I said. What I'm stating is 
1) The Star Barge comes equipped by default with plasma engines
2) The Star Barge is a Syndicate ships
3) The Shuttle makes Betelgeuse Shipyards the majority of their profit, so it is reasonable to assume that the same is true for the Star Barge and Syndicated Shipyards.
4) Given the above 3 facts, Delta V is making a lot of money because of the Star Barge being equipped with plasma engines

therefore, it's reasonable to assume that the reason Chipmunk and Greyhound engines are sold in Syndicate outfitters is because Delta V and the Syndicate have some form of agreement with one another, as otherwise the Star Barge should have ion engines and not plasma engines so that Delta V doesn't make a cut of money off of the Syndicate's sale of Star Barges.

**Comment by KiLEdEnNis** [comment]
I do get removing the "Southern" engines from the Syndicate outfitters, but why would a company that makes outfits not try to sell them in other parts of human space? (like, add the "Basics" outfitters of 1 area in a few places in another)
so I think either this change should get paired with adding some outfitters (at least the basics) to regions of space they're not from, or simply leaving it be

**Comment by Nescio0** [comment]
The Star Barge is the only Syndicate ship equipped with a plasma engine, but it's also the only Syndicate ship sold (produced?) outside of Syndicate space. And their next popular ship, the Freighter, is by default equipped with a Heavy Anti-Missile Turret, which is only sold at three planets, each of which is outside Syndicate area.
My point is that when we are comparing outfitters, we should look at outfitters, not primarily at shipyards and default ships.

Let's have a look at it from the `data/sales.txt` perspective:
```
outfitter "Deep Sky Advanced"
	"Ramscoop"
	"LP144a Battery Pack"
	"Beam Laser"
	"Laser Turret"
	"Heavy Laser"
	"Torpedo"
	"D23-QP Shield Generator"
	"D41-HY Shield Generator"
	"LP288a Battery Pack"
	"LP576a Battery Pack"
	"nGVF-CC Fuel Cell"
	"nGVF-DD Fuel Cell"
	"NT-200 Nucleovoltaic"
	"Torpedo Launcher"
	"Torpedo Storage Rack"
	"Heavy Laser Turret"
	"D67-TM Shield Generator"
	"D94-YV Shield Generator"
	"Security Station"
	"A120 Atomic Thruster"
	"A125 Atomic Steering"
	"A250 Atomic Thruster"
	"A255 Atomic Steering"
	"A370 Atomic Thruster"
	"A375 Atomic Steering"
	"A520 Atomic Thruster"
	"A525 Atomic Steering"
	"A860 Atomic Thruster"
	"A865 Atomic Steering"
	"AR120 Reverse Thruster"
	"Dwarf Core"

outfitter "Delta V Advanced"
	"Chipmunk Plasma Thruster"
	"Chipmunk Plasma Steering"
	"Greyhound Plasma Thruster"
	"Greyhound Plasma Steering"
	"Heavy Rocket"
	"Meteor Missile"
	"Javelin"
	"Javelin Pod"
	"Javelin Storage Crate"
	"Impala Plasma Thruster"
	"Impala Plasma Steering"
	"Orca Plasma Thruster"
	"Orca Plasma Steering"
	"Tyrant Plasma Thruster"
	"Tyrant Plasma Steering"
	"Breeder Reactor"
	"Heavy Rocket Launcher"
	"Heavy Rocket Rack"
	"Meteor Missile Launcher"
	"Meteor Missile Box"
	"Modified Blaster"
	"Modified Blaster Turret"
	"Scram Drive"
	"Small Radar Jammer"
	"Large Radar Jammer"

outfitter "Syndicate Advanced"
	"RT-I Radiothermal"
	"LP144a Battery Pack"
	"Meteor Missile"
	"Meteor Missile Launcher"
	"Meteor Missile Box"
	"X3700 Ion Thruster"
	"X3200 Ion Steering"
	"Chipmunk Plasma Thruster"
	"Chipmunk Plasma Steering"
	"Javelin"
	"Blaster Turret"
	"D23-QP Shield Generator"
	"Laser Rifle"
	"Water Coolant System"
	"Proton Gun"
	"Fission Reactor"
	"Javelin Pod"
	"Javelin Storage Crate"
	"X4700 Ion Thruster"
	"X4200 Ion Steering"
	"X5700 Ion Thruster"
	"X5200 Ion Steering"
	"Greyhound Plasma Thruster"
	"Greyhound Plasma Steering"
	"Quad Blaster Turret"
	"Torpedo Launcher"
	"Torpedo Storage Rack"
	"Torpedo"
	"D41-HY Shield Generator"
	"D67-TM Shield Generator"
	"Security Station"
	"Scram Drive"

outfitter "Kraz Advanced"
	"Chipmunk Plasma Thruster"
	"Chipmunk Plasma Steering"
	"S3 Thermionic"
	"Liquid Nitrogen Cooler"
	"LP144a Battery Pack"
	"D23-QP Shield Generator"
	"nGVF-CC Fuel Cell"
	"Energy Blaster"
	"Blaster Turret"
	"Torpedo"
	"Beam Laser"
	"Cargo Scanner"
	"Liquid Helium Cooler"
	"LP288a Battery Pack"
	"LP576a Battery Pack"
	"D41-HY Shield Generator"
	"nGVF-DD Fuel Cell"
	"nGVF-EE Fuel Cell"
	"Laser Turret"
	"Heavy Laser"
	"Plasma Cannon"
	"Torpedo Launcher"
	"Torpedo Storage Rack"
	"Outfit Scanner"
	"Laser Rifle"
	"Small Radar Jammer"
	"Large Radar Jammer"
	"Tactical Scanner"
```

As you can see, Syndicate is the only outfitter which sells engines from two different sets.

**Comment by Pointedstick** [comment]
This giant argument is unhelpful. I agree with the core goal of the PR: to differentiate the regions of space; you'd buy Ion engines in Syndicate space, and Plasma engines in the Galactic South, to match the fact that Atomic engines are only sold in the Deep. If there's some more tweaking to go along with it, that's fine, but let's not kill this PR with semantic arguments.

**Comment by KiLEdEnNis** [comment]
if the Syndicate & Southern (& more?) outfitters sold their stuff in some "foreign" regions of human space, this PR change would be fine, as different engines are still available in various areas

**Comment by Nescio0** [comment]
> if the Syndicate & Southern (& more?) outfitters sold their stuff in some "foreign" regions of human space, this PR change would be fine, as different engines are still available in various areas

This occassionally happens:
```
planet "New China"
	outfitter "Common Outfits"
	outfitter "Ammo South"
	outfitter "Delta V Basics"
	outfitter "Kraz Basics"
planet Geyser
	outfitter "Basic Outfits"
	outfitter "Ammo North"
	outfitter "Syndicate Basics"
	outfitter "Lovelace Basics"
```
(On the map it's one step from Earth to Geyser and a second to New China).

**Comment by Amazinite** [comment]
>My point is that when we are comparing outfitters, we should look at outfitters,

There's a difference between how the outfitters/shipyards show on the back end and how they are actually presented in game. In game, a player isn't going to land on Hephaestus and know "oh, this planet has the basic ships, Megaparsec basic, Syndicate basics, and Syndicate advanced shipyards," what a player is simply going to see is a Syndicate world selling some Southbound ships because Megaparsec basics contains the Hauler. To a player, it's all one outfitter or shipyard, not multiple separate outfitters or shipyards.

>As you can see, Syndicate is the only outfitter which sells engines from two different sets.

And again:
>it's reasonable to assume that the reason Chipmunk and Greyhound engines are sold in Syndicate outfitters is because Delta V and the Syndicate have some form of agreement

given the stated info.

<hr/>

>I agree with the core goal of the PR: to differentiate the regions of space

If this is the goal, then not only do outfitters (and shipyards) need changed, but the shipyards and outfitters that planets offer need changed.

1) The smallest ion engines are sold nearly everywhere
2) The Hauler I is sold in multiple places up and down the galaxy despite being a Southbound Shipyards ship, and the Hauler II is also sold on some Syndicate worlds.
3) The Falcon is somehow sold all the way up north on Shroud when it's built down in the far south by Tarazed
4) The Deep Heavy Laser and (normal) Laser Turret is sold in the south. I'm letting the wide-spread sale of the Beam Laser (and every normal blaster weapon, for that matter) slide given its age.
5) Heavy Rockets are only sold on 4 southern worlds (one being a pirate world), but their ammo is sold all across the South, Rim, and Dirt Belt regions, as well as all but one pirate world.
6) Large Radar Jammers are somehow only sold in the south when the missile they're effective against, the Sidewinder, is sold all the way up in the north.

Those are the different things I found to be interestingly off in terms of what different regions of space sell. Such changes would also warrant checking the outfits that different default ships have and changing them to be more congruent with their seller, e.g. the mentioned fact that Star Barges come default with engines that aren't of the Syndicate.

**Comment by endless-sky** [comment]
Any time the player has to fly to different regions of space just to pick up the outfits they need for a ship, that adds a certain annoyance factor. In general, the outfitters are designed so that the only time you absolutely *need* to go to a particular region is when you're looking for a high-end outfit.

It's comparable to how modern retail works - most people can do their grocery shopping all at one store, but if you need something really specific you may have to hunt around for it. Low-level, cheap engines would be enough of a commodity that a lot of outfitters would sell them.

**Comment by Nescio0** [comment]
To use your grocery metaphor, bread is one of the most common food staples in our world. However, bread in Spain is not the same as bread in France. And in Germany alone, there are hundreds of different types of bread, each region has its own, and does not necessarily sell the breads of neighbouring regions.

Likewise, this patch does not reduce the number of outfitters which sell low-level, cheap engines; it only removes a few specific engines from Syndicate outfitters who already offer equivalents.

Furthermore:
* Regional differences are already the case for many different outfits
* If plasma engines count as common outfits, why are they not included in the "Basic Outfits" or "Common Outfits" sales lists, as are ion engines currently?
* If plasma engines do not count as common outfits, then why is it problematic if the number of systems which sell Greyhound engines is reduced by 5 from 18 to 13?
* For comparison, let's have a look at third level engines (unaffected by this proposal):
  * A370 and A375 atomic engines are sold in eleven systems
  * X3700 and X3200 ion engines are sold in dozens of systems
  * Impala plasma engines are sold in only four systems
  * Ships equipped by default with impala engines are sold in dozens of systems

**Comment by KiLEdEnNis** [comment]
> And in Germany alone, there are hundreds of different types of bread, each region has its own, and does not necessarily sell the breads of neighbouring regions.

compare that back to the engines: each region would have slightly different versions of plasma engines; some exhaust may be 10cm longer, another would use another material, but it's still a plasma engine

if ya want to compare the different engines w/ bread, make 1 regular bread, and 1 actual baguettes, because what you're doing now is a sloppy comparison
adding that the comparison doesn't make that much sense, and there's not really a good reason to even argue against MZ's argument as his gave a perfect idea of why different outfits shouldn't be strictly limited

**Comment by Nescio0** [comment]
What do you think of the following alternative proposal?
* Basic and Common: Chipmunk and X1
* Delta V Basic: Chipmunk, Greyhound, Impala
* Delta V Advanced: Chipmunk, Greyhound, Impala, Orca, Tyrant (unchanged)
* Syndicate Basic: X1, X2, X3
* Syndicate Advanced: X1, X2, X3, X4, X5

Instead of the current situation:
* Basic and Common: X1, X2 (no plasma engines)
* Delta V Basic: Chipmunk, Greyhound (no Impala)
* Delta V Advanced: Chipmunk, Greyhound, Impala, Orca, Tyrant (unchanged)
* Kraz: Chipmunk
* Syndicate Basic: Chipmunk, X1, X2, X3
* Syndicate Advanced: Chipmunk, Greyhound, X1, X2, X3, X4, X5

This effectively increases the availability of plasma engines and reduces the availability of some ion engines, to make both comparable.
* fourth and fifth level ion and plasma engines would be available at four systems each (unchanged)
* second and third level ion and plasma engines would be available at c. 15 systems each (instead of X3 at dozens and Impala only at four)
* first level ion and plasma engines would be available throughout human space (instead of X1, X2, but not any plasma engines)

Basic availability of basic engines, regional specialization for higher level engines.

**Comment by KiLEdEnNis** [comment]
how about just add Plasma Engines to the common outfitters w/o removing the Ion Engines for no reason at all? all you do is basically messing up gameplay for no reason, while if ya just add the smallest Plasma Engines to common outfitters ya actually improve gameplay for new players

**Comment by Nescio0** [comment]
Changed it to:
* Basic: Chipmunk, X1
* Common: Chipmunk, X1, X2
* Syndicate B: X1, X2, X3
* Syndicate A: X1, X2, X3, X4, X5

**Comment by Amazinite** [comment]
I still consider the changes rather unnecessary; the Syndicate produce ion engines, and given the vast power that the Syndicate hold, it makes sense that ion engines can be found at practically any outfitter. Plasma engines are produced by Delta V, and while not as big a producer as the Syndicate, their engines are still easy to afford and therefore expected to be found in multiple outfitters relatively close to Solace. The fact that Atomic engines are only sold in the Deep and smaller engines on only a couple of Paradise Worlds relates to MZ saying that
>outfitters are designed so that the only time you absolutely need to go to a particular region is when you're looking for a high-end outfit.

In the end, I really don't see the purpose of these changes. I just feel that the locations that engines are sold at are fine as-is.

**Comment by KiLEdEnNis** [comment]
making the smallest 2 Plasma AND Ion engines available in common outfits seem a worthy change, don't change this all as it's unnecessary

**Pull request closed without merging**
