### PR TITLE
Implementing burst function into weapons.

### PR DESCRIPTION
**Pull request by unknown1419**
I just started this game a couple of weeks ago. One of the few things I find lacking in the game is that there is no weapon that can fire in burst(ie. continuous fire for a period of time before being unable to fire until it finishes it's reloading. I tried to mess with data file editing to no avail and hence tried my hands on the coding and these are the editing I have came up with.

I do not have any much experience in C++ coding and hence doing this requires me to read up on various c++ tutorials and recoding multiple times in order to finally able to implement it. I also wish to take this opportunity to apologize for any deviation in the required coding style due to my inexperience.

I have added an attribute ("burst") that can be used to convert any weapon to Burst mode. It will make beam weapons with extreme damage but long reload time be able to fire in burst(instead of a moment of fire/fire for only a frame) possible.

Any feedback for improvement is greatly appreciated and I apologize for any trouble caused as it's my first time doing a pull request.

### CODE REVIEW

**Comment by endless-sky** [comment]
You should read through the [style guide](http://endless-sky.github.io/styleguide/styleguide.xml) if you're proposing changes to the code. In particular, your pull request contains a lot of spurious changes that are purely formatting changes, and you also appear to be using spaces instead of tabs.

Also, in the past when people have requested "burst" support the idea has been to have it be possible to have a shorter reload time in between projectiles within the burst, rather than requiring that the burst fires every single frame for some number of frames. (For example, the weapon fires five projectiles with three frames in between each, then pauses for 30 frames.) So this is a partial implementation of burst weapons, but it would be better to have a more general-purpose implementation.

**Comment by unknown1419** [comment]
Thanks for the suggestion, I will take this in mind for improving the implementation.

**Comment by endless-sky** [comment]
As of commit 46cc7f5, I added an alternative implementation of burst firing. My goal was to:
* allow you to stop firing mid-burst
* reduce the full reload time if you only fired half a burst
* allow "reload" times in between projectiles within a burst
* have burst weapons fall back gracefully 0.8.11 (firing in streaming mode at the same average rate of fire, rather than firing at a much lower rate)

**Comment by unknown1419** [comment]
The alternative implementation is more code efficient and makes more sense than mine. But I'm glad that it is finally going to be implemented in future versions of the game. But the alternative implementation after testing I realise that it is not complete and hence I have suggested some changes/ addition to the coding for your consideration.

**Pull request closed without merging**
