### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by shitwolfymakes**
## Summary
Fixes a typo in gegno intro missions

### CODE REVIEW

**Review by Saugia — APPROVED** [review]

**Comment by shitwolfymakes** [comment]
Still playing through the missions, so don't merge just yet

**Comment by Saugia** [comment]
OOf.

**Comment by shitwolfymakes** [comment]
lmao, no worries

**Comment by Saugia** [comment]
Right as I did it. Whoops.

**Pull request merged**
