### PR TITLE
Relocate population; related jobs and missions

### PR DESCRIPTION
**Pull request by Amazinite**
These are updated versions of the jobs and missions from #1034.
**Relocating the Population**
The main premise of these missions is that the Parliament of the Republic sees the danger in having so many people on a single planet. With overpopulated worlds like Earth, New China, and Chiron having billions upon billions of inhabitants, a single nuclear attack or the cutting off of the food supplies from the south could lead to massive numbers of casualties on planets like these.
**The Jobs**
One month after the bombings on Geminus and Martini, Parliament announces to the public that they are in need of assistance. They require merchants to assist the Navy in relocating people from overpopulated worlds to less populated, usually farming or industrial worlds. These jobs are intended to be better than transport colonizer jobs, requiring on average more passenger space and paying more cash per person per jump.
**The Space Elevator**
Even with the help of a few merchants being able to transport anywhere from 40 to 150 people at a time, the efforts are slow. There is no way that just having transport ships dock at the already likely overcrowded spaceports will do much good. As such, the Republic attempts to build a space elevator on Earth. This space elevator leads to a large spaceport in the sky reserved only for those who are helping to transport people off the planet. After completing a mission where you assist in escorting materials for the space tower to Earth, you are given a temporary (30 day) Navy license and are credited in the spaceport description 45 days later for helping to build the new space elevator, which can be seen lighting up on the Earth sprite itself when in space. If you did not assist in building the elevator, then the sprite with the elevator appears after you have chosen sides and the spaceport description of Earth gives an explanation as to why the elevator was built.

### CODE REVIEW

**Comment by Amazinite** [comment]
@LocalGod79 Would the acquiring of a 30 day Navy license conflict with your ideas for the Republic storyline? I added a `not "event: joined the navy"` line in the event that removes the license as to not interfere with any license that the player gains from joining the Navy.

**Comment by LocalGod79** [comment]
i think the larger problem is "why is this Admiral handing out passes to buy Navy hardware?"

if there were even one civilian Gunboat or Rainmaker present in the game, i could buy into it, but it seems like the Navy is one of those kids that doesn't share their toys...

**Comment by Amazinite** [comment]
True. If anything, it makes sense that it could be used for a side mission that points the player in the direction of the Navy instead of having the player get a Navy license right then and there, even if only for a month. Is there anything you suggest for the end for the Admiral to say to point the player toward a certain direction, or should I just leave it at "we could use people like you." I'm reluctant to actually have it point the player somewhere specific since there probably won't be anything for the player to actually go to yet.

**Comment by LocalGod79** [comment]
i actually kind of think that this could be added to the republic intro missions, with perhaps a tweak or two...

**Comment by Amazinite** [comment]
If that is the case, should we hold off on the merge for now?

**Comment by Amazinite** [comment]
Gonna be honest, I've never done the checkmate route. How would this impact that route, as I recall some people asking to possibly cut off the Earth's food supply to impact the moral of the Republic. This is the Republic's precaution to that, so I wonder how much this would actually help.

**Comment by wambat1** [comment]
there is already a precedent in the current content for emergency movement of populations. it was a very lightly populated planet, and took quite a long time for the entire navy to accomplish. i think a pretty drastic technological advance would be called for if the Republic was trying to keep up with birth rates on the overpopulated worlds. probably, the program would be framed as increasing the security of the Republic as a whole, but not as a program to reduce overpopulation, or the risk to the overpopulated worlds themselves.

**Comment by Amazinite** [comment]
Given that the bombings would have just occurred and would be fresh in most people's minds, I feel that that would be a better motivator for most people. And given how the Parliament has been described as catering to the Paradise world's and the Synidcate Corporation, I don't think that people would be as fond to "Make the Republic stronger!" "Save your fellow man!" just feels like it would bring in more help. 

And as for the evacuation of Hope, I don't recall any talk of how long it took (granted it's been a while since I've done the campaign), but that's all the better reason to build the space elevator and recruit merchants to assist in transporting people, especially with most of the Navy worrying about the Free Worlds.

**Comment by Gkramme** [comment]
Well done. The elevator looks very bulky though. Maybe you could slim it down a little?

**Comment by Amazinite** [comment]
Bulky how? Vertically or horizontally?

**Comment by wambat1** [comment]
i am having trouble imagining a space elevator competing favorably with anti-gravity take-off. its not like you have other options beside the "40 to 150 people at a time" transports to get people from one planet to the next in any case. i don't see how it would make more sense to build a giant, vulnerable, space elevator; at a time when the Republic is trying to reduce vulnerability; rather than spending the same resources expanding existing, or building new space ports. maybe the space elevator would be a better idea for an alien race.

**Comment by Gkramme** [comment]
@Amazinite Horizontally

**Comment by Amazinite** [comment]
I addressed the whole repulsor engine argument within the conversations. You can ask why they don't just use a ton of transport ships, and he explains how the current spaceport is to small and to use it would not only be slow, but would also slow down trade on the planet since most of the landing pads would be taken up by transport ships loading people on.

**Comment by wambat1** [comment]
i am afraid i addressed your rebuttal specifically in my critique. the proposition, as presented, does not make sense on several points. if the author is fine with that, so be it; plenty of good literature does not make sense when looked at soberly. 

    On Monday, June 6, 2016 8:02 AM, Amazinite <notifications@github.com> wrote:
 

 I addressed the whole repulsor engine argument within the conversations. You can ask why they don't just use a ton of transport ships, and he explains how the current spaceport is to small and to use it would not only be slow, but would also slow down trade on the planet since most of the landing pads would be taken up by transport ships loading people on. —

**Comment by toilethinges** [comment]
R.N.S., not RNS. :)

**Comment by onnikyla** [comment]
the relocation mission would make no sense. the republic wouldnt just start moving people away from earth. the people would find their own transport off planet if they felt afraid. the time it would take to transport just a million would be rediculous so I see no logic  in the whole idea.

**Comment by Amazinite** [comment]
The point is to avoid mass casualties, so it makes sense for the Republic to at least do something about it. With merchants constantly coming in and out to transport people, it isn't extreme to think a million people could be getting transported a day. It may not be much compared to the total population of the planet, but that's millions saved if there is a bombing.

And if this does get added and it becomes canon that the Republic are attempting to reduce the population on these dangerously highly populated planets then it would also make sense that they would put rules and regulations in to assist in reducing the birth rate so that the population does eventually drop.

**Comment by Amazinite** [comment]
Given that @localgod79 is considering using this for the Republic Mavy storyline, I'll be closing this for now and touching it up a bit.

**Pull request closed without merging**
