### PR TITLE
Windows 64-bit installer

### PR DESCRIPTION
**Pull request by jonnyhsu**
NSIS based installer for Win64 releases.

To build the installer:

- Install [nsis](http://nsis.sourceforge.net/)
- Ensure the paths for GCC and the dev64 folder in `installer/EndlessSky-Win64.nsi` are correct
- Build the project per usual. The install script will look for `EndlessSky.exe` in the `bin/Release` directory
- Build the installer, either through the NSIS interface or by right clicking on the install script and selecting "Compile NSIS Script"

### CODE REVIEW

**Comment by jafdy** [comment]
You have 3 commits, 9 files and 53 lines that I don't think you meant to change.

**Comment by jonnyhsu** [comment]
>You have 3 commits, 9 files and 53 lines that I don't think you meant to change.
Yes, thanks. I squashed my commits and accidentally included a few extra. Fixed.

**Comment by KiLEdEnNis** [comment]
it'll take some weeks for the owner to come back and maybe merge it in case you'll wonder

**Comment by jonnyhsu** [comment]
Thanks for letting me know. In the mean time, if someone with some spare time can test it, that would be awesome.

**Comment by comnom** [comment]
@jonnyhsu Built fine, installed/uninstalled fine for me on Win 7. Great work. Is it possible to add an option to remove the config directory as well? (%Appdata%\endless-sky) I personally like an uninstaller that murders every bit of a program ;)

**Comment by jonnyhsu** [comment]
> Is it possible to add an option to remove the config directory as well?

Yes, good idea. I'll add that when I get a chance.

**Comment by tehhowch** [comment]
@jonnyhsu any further progress?

I have a makefile that can be used by MinGW to build Endless Sky without the user needing to open or configure code blocks (but necessarily requiring an os find routine to select the proper MinGW directory and dev64 library folder location). See my pull #2786 

A tool which does a guided install of the necessary files and programs for building Endless Sky on Windows (e.g. correct versions of MinGW, dev64 resources, and correct path configuration for Code::Blocks)  would be pretty helpful for new contributors.

**Comment by jonnyhsu** [comment]
I got hung up on this, I have some time this week to work on it.

**Comment by jonnyhsu** [comment]
I've added an option to the uninstaller that allows deletion of user data. This option is off by default, and when enabled, deletes the user's entire `AppData\Roaming\endless-sky` folder. If you wish to test this feature of the uninstaller, please backup your data first!

Note that the uninstaller will only delete the data for the current logged-in user. If there are other users on the machine that have game data, their data will not be deleted. This is what Microsoft recommends in this blog post: [What do I do with per-user data when I uninstall?](https://blogs.msdn.microsoft.com/oldnewthing/20070917-00/?p=25103).

Thoughts?

**Comment by tehhowch** [comment]
Just noticed this has an associated milestoned issue: https://github.com/endless-sky/endless-sky/issues/1363

**Comment by jonnyhsu** [comment]
Old, and likely outdated. I'm retracting this.

**Pull request closed without merging**
