### PR TITLE
New wrapped text element for interfaces.

### PR DESCRIPTION
**Pull request by quyykk**
## Feature Details

Implements a new kind of text element: The wrapped text element. It's basically a wrapper around `WrappedText`. No visual difference compared to master.

The spaceport and planet panel can now be fully defined using interfaces!

## Usage Examples

```
"wrapped text" <name>
	size <font size>
	alignment <alignment>
	color <color>
        truncate <truncate>
```

## Testing Done

Made sure that there are no differences between this PR and master. Including with news portraits.

## Performance Impact

For simplicity I do not cache the text, so every frame the word wrap of the `WrappedText` gets recalculated. Hope that's ok :)

### CODE REVIEW

**Comment by quyykk** [comment]
@tehhowch status on this?

**Comment by tehhowch** [comment]
I was hoping to do @oo13 's pango PR first, given how often we have conflicted it, how tirelessly they had kept it updated, and that this was guaranteed to conflict it even more.

(Their PR is waiting for me to spin up a repo in which we can reproducibly build platform-specific dependency packages needed for both macOS and Windows at our target 10-15 y.o. hardware level.)

I was definitely happy to see you open this PR and want to see it merge eventually, but that's why I have been hands-off it.

**Review by warp-core — APPROVED** [review]
I don't see anything wrong with this.
I'm going to assign tehhowch to this for whenever he's got the other stuff done.

**Comment by quyykk** [comment]
I'll close this for now.

**Comment by TomGoodIdea** [comment]
Any chance for reopening soon? I need interface buttons with WrappedText for https://github.com/endless-sky/endless-sky/pull/9997#discussion_r1581605773

**Pull request closed without merging**
