### PR TITLE
Bombar(d)ment Turret spelling mistake

### PR DESCRIPTION
**Pull request by Elyssaen**
Bombarment -> Bombardment

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
doesn't the PR have to be named Bombarment Turret spelling mistake then?

**Comment by Alkallid** [comment]
The intended name and real word is bombardment, so it's referring to what is most likely MZ's name for the turret.

**Comment by Elyssaen** [comment]
Let's keep everyone happy. Title changed.

**Comment by KiLEdEnNis** [comment]
:3

**Pull request merged**
