### PR TITLE
Flamethrower Turret

### PR DESCRIPTION
**Pull request by DearVarun**
I figured a Flamethrower turret would be quite good against small fighters.

### CODE REVIEW

**Comment by toilethinges** [comment]
This needs to be tested with the Free Worlds campaign and added to new variants, and existing fleets.

**Comment by lehgogh** [comment]
Remember that even if this does not get submitted, you can still make it into a plugin.

Also, may I suggest a rewording of the description?

A Flamethrower Turrets is a pair of flamethrowers mounted on a turret, designed to hit nearby fighters. While its fuel usage is significant, most fighters are unable to handle the heat.

**Comment by DearVarun** [comment]
I was think I'd get the weapon approved and then do the variants and Campaign afterwards.

**Comment by LocalGod79** [comment]
that's generally not the way software development works.

features get added when (mostly) complete.  that means;
•integrated into the existing universe
•tested for bugs
•tested for balance
•blender model prepared
•outfitter sprite prepared
•@2x outfitter sprite prepared
•tested for difficulty

generally, that last one is the stumbling block - nobody wants to put their outfit on ships that will be used in the Free Worlds campaign, and then play through it over and over, adjusting their outfit to make sure that the story didn't suddenly get very easy or difficult when facing the Pug.

it seems like you have a lot of work to do.

**Comment by DearVarun** [comment]
Do you know where ship variants are in the game files?

Because I cannot seem to find them.

**Comment by LocalGod79** [comment]
within the game's source, 

data/variants.txt

**Comment by mdsmestad** [comment]
@DearVarun Was there a regular pluggin for this?

**Pull request closed without merging**
