### PR TITLE
New Nuke effects

### PR DESCRIPTION
**Pull request by Karirawri**
**Content (Artwork)**

## Summary
These are some new nuke explosion effects. The original was blurry, with sprites that cut off suddenly at the borders. These are much bigger due to the "spokes" of light, but the bright explosion itself is just slightly bigger than the original, brighter, more detailed, and more colorful.

## PR Checklist
 - [ x ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ x ] I uploaded the necessary image, blend, and texture assets here: https://www.dropbox.com/sh/v3vkm8kz8see7ca/AADfdzAMVc7crAYU42FxaOkGa?dl=0
 - [ x ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/199

### CODE REVIEW

**Comment by Karirawri** [comment]
note: i have no idea why all of my previous commits from the sheragi missions are showing up there. please advise if i did something wrong, i'm a bit of a noob at this.

**Comment by MCOfficer** [comment]
> note: i have no idea why all of my previous commits from the sheragi missions are showing up there. please advise if i did something wrong, i'm a bit of a noob at this.

Because you PR'd them from the same branch. They got squash-merged back then, so your branch's history now differs from ES's master (one commit containing all changes on ES, several commits containing the same changes on yours). Nevertheless, the changes those commits contain are the same, hence why your branch doesn't differ in content in anything but your new commits.

For future reference, you want to create a new branch from ES's master* then work on that and PR it. That way you're not limited to one PR at a time, and you can start from a clean slate for every PR.

**Comment by McloughlinGuy** [comment]
> note: i have no idea why all of my previous commits from the sheragi missions are showing up there. please advise if i did something wrong, i'm a bit of a noob at this.

Happened to me once.

**Comment by tibetiroka** [comment]
This may be a dumb question, but shouldn't the images have transparent background?

**Comment by Amazinite** [comment]
Doesn’t need one. It uses additive blending (the + in the file name) so it’ll appear with no background in game.

**Pull request merged**
