### PR TITLE
Rebalance human primary weapons: buff blasters and cannons, nerf lasers

### PR DESCRIPTION
**Pull request by Amazinite**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR is intended as a companion to #6671 and an alternative to #5796.

As of right now, among human primary weapons, lasers are the top dog in practically every scenario. Lasers are relatively small, meaning it's easy to saturate a ship's hardpoints with them. Lasers have very low firing requirements, meaning you don't need to dedicate as much of your outfit space to cooling or energy. And lasers have very high damage for their size, making them great choices in combat. And on top of all that, the instant impact nature of lasers makes them perfect for boarding playstyles where you want to leave your target alive and means that they'll never miss.

The two alternatives to lasers are blasters and cannons.

Blasters as they are right now are essentially a non-choice for the player. They are inferior to lasers in almost all ways. Blasters have lower DPS/ton than lasers. While blasters are smaller even than lasers, lasers already don't have a difficult time saturating a ships hardpoints, meaning that saturating your hardpoints with blasters is just a loss in DPS. Blasters also have CONSIDERABLY firing requirements, with extremely high firing energy and heat: as a comparison, the Modified Blaster requires more energy and heat per second to fire than an Electron Beam does.

Cannons are in a much better spot than blasters are. Cannons are larger than lasers, but they make up for this in their slightly increased DPS (although they do have lower DPS per ton), or in the case of Plasma Cannons they have a special damage type. But the main downside of them is that even though their DPS is comparable, they require much more energy and heat to fire. Cannons also lack the instant impact that lasers have, meaning that even if a cannon has better DPS on paper, it's often still beneficial to choose a laser as a laser won't miss and is, again, perfect for disabling ships.

The goal of this PR is to make all weapons at least somewhat viable instead of having a single clear winner among human primaries. That is, we should not be treating blasters as weapons that are intentionally bad and meant to be replaced ASAP; blasters should have a proper place in the weapon sandbox for the player to make use of.

This PR makes the following changes:
* -40% firing energy and heat for all human blasters.
  * Even a decrease this large still leave blasters less energy and heat efficient than lasers, but the gap is now much, much narrower, making blasters less of a pain to use.
  * This change goes much further than #5796, which I feel doesn't go far enough in making blasters a viable weapon.
* +10% shield and hull damage for all human blasters.
  * This slight bump in DPS means that blasters now have ever so slightly more DPS/ton than lasers instead of having slightly less. The tradeoff then is that blasters aren't instant impact and require more firing energy and heat.
  * This change is in contrast to #5796, which makes blaster damage more balanced while keeping the total DPS the same or even decreasing it in the case of the Energy Blaster.
  * Remember that the number of hardpoints a ship has is still a major limiting factor: even if blasters have higher DPS per ton than lasers, if you can fit the same number of blasters as lasers then the lasers will be the way to go since they have a higher raw DPS.
* +33% firing energy and heat for all human lasers.
  * While a considerably increase relative to what it was, the firing energy and heat were so low on lasers to begin with that this simply brings lasers more in line with other human primary weapons.
  * This change is in contrast to #5796's 50% increase to firing energy alone.
* No change to shield or hull damage for human lasers
  * Given that lasers are the most popular choice for dealing damage, I wanted to leave laser DPS as a baseline and give other human weapons a DPS bump rather than drop the DPS of lasers.
  * This change is in contrast to #5796's flipping of the damage values to make lasers more shield damage heavy than hull damage heavy while also reducing their overall DPS by about 25%. I don't want to change the role that lasers fulfill in being high hull damage weapons, at least not right now.
* +20% shield and hull damage for the Particle Cannon and Proton Gun.
  * The Plasma Cannon has been left out since it already benefits greatly from its heat damage.
  * With leaving laser damage where it is and increasing their firing energy and heat, this brought them closer to where the cannons are at. Instead of lowering the firing energy and heat of cannons to make them more competitive, I've instead given them a damage buff so that now if damage output is the concern, cannons are the way to go, as opposed to before where the Electron Beam, Particle Cannon, and Proton Gun were all pretty close in damage output.

And something to remember: If these changes go too far in one area or another, we can always reel them back in slightly at a later date. But I'd say this is at least a good stepping stone toward a healthier sandbox.

## Save File
N/A

## Artwork Checklist
N/A

### CODE REVIEW

**Comment by Zitchas** [comment]
Overall, I think these are a good set of changes. The exception is the damage buff to blasters. I don't feel that it is helpful to the game to try to make them more relevant as a general purpose gun like this. 

I think it would be better to recast the blaster as primarily a fighter weapon, that happens to be useful as a cheap weapon for people (like merchants) who don't actually want to fight, they just want the smallest possible thing that lets them claim they are armed without taking up space better used for things that actually make them money, like cargo and bunks.

Benefits:
1. Blasters have an actual unique role
2. Blasters can be smaller (smallest guns is a useful perk in and of itself)
3. Fighters can have their outfit space reduced without impacting their ability to fill all their gun ports. (this also makes it harder to put warship caliber weapons on fighters, which makes fighters and warships more different)
4. When combined with the reduced energy & heat requirements, fighters can be reduced even smaller as they'll need less of each.
5. Blasters are basically the "starter gun" whose main reward is to give players the sense of achievement in being the first thing they replace. I know some people don't value this, but many of us also *like* having starting equipment that is just flat out there to get us through the start until we can replace them.

Negatives:
A. Blasters are less competitive with regular weapons for use on warships. 

In the lore, blasters are the oldest of all human weapons, and are the primary weapons used by humanity back when the Pug decided to interfere in the Alpha war by giving humans better weapons so that humanity actually had a shot at winning. This, alone, makes me thing that, as a baseline, lasers should be absolutely better than blasters in every combat relevant metric. And, well, all the rest of the weapons humanity has developed since then. If they weren't clearly superior, why would we waste time making them? In terms of space warfare, blasters are the hand-canon muskets. Interesting relics, cheap to make, but not fit for serious use on actual warships in anything but a few rare specialized circumstances; the main one being use on fighters where their tiny size fits perfectly.

**Comment by Amazinite** [comment]
> Negatives: Blasters are less competitive with regular weapons for use on warships.

And that's the one negative I won't accept. I think that blasters should be competitive with other weapons. If blasters are billed as weapons for fighters, then why in the world would we have blaster turrets that fighters can't use? What your suggested changes would do is wipe away what blasters currently are and turn them into something else, which you might as well just create an entirely new weapon for.

>  This, alone, makes me thing that, as a baseline, lasers should be absolutely better than blasters in every combat relevant metric.

That may have been true 560 years ago, but it's stated in FWR that "[The Pug] also gave us beam weapon technology; five centuries later, we've only just reached the point where we understand that technology well enough to improve on it." So in 560 years lasers have hardly improved if at all while there's been nothing stopping blasters or other weapons from improving.

> If they weren't clearly superior, why would we waste time making them?

Why must something be clearly superior for it to be made? Would that logic not then state that since laser are superior, why bother making other weapons?

**Comment by Zitchas** [comment]
Blaster as singular guns shouldn't be useful on warships. The places where they *are* useful is things like blaster turrets, or, more likely, quad blaster turrets. Things that take that tiny size of blasters to enable a single turret mount to carry larger multiples than other weapons can fit. This means that this small, fighter-caliber weapon can be great for situations (like anti-fighter roles) where a captain cares more about filling the sky with bolts than they do about precision. Is such a weapon good for warship-on-warship combat? No. Does it have a clear combat role to fill? Yes. 

We should be looking to have weapons fill different combat roles, not figure out how to get every weapon to somehow be acceptable in the same role.

**Comment by Amazinite** [comment]
> Blaster as singular guns shouldn't be useful on warships. The places where they are useful is things like blaster turrets, or, more likely, quad blaster turrets.

Then this is already the case. The suggested 10% damage buff is not going to suddenly have people choosing energy or modified blasters instead of heavy lasers for the guns on their warships. Blasters are 5 tons while modified blasters are 6. Heavy lasers are 15 tons. Outside maybe some light warships, I don't see blasters being useful as forward facing guns on anything bigger than an interceptor.

**Comment by Zitchas** [comment]
Except shrinking the blaster makes them smaller, and thus will make fighters & drones lighter. As I recall from Revamp, even reducing fighter hulls to 0 had insufficient impact to get fighters up to a good manouverability because the vast majority of their mass was in their outfits, not the hull. So trimming some mass out of everything is basically a requirement, which ties back to the fact that we need stuff that is actually made for fighters. So long as we keep trying to have fighters just be "really small warships," they're just going to be "warships that die really really fast" and not actually their own thing. Blasters getting smaller is an essential part of this.

**Comment by EjoThims** [comment]
What about splitting the difference? Make normal blasters smaller but not give them the damage buff, while giving mod blasters the damage buff (maybe even a bit, 15% or 20% instead) and their current size, specifically in order to further differentiate between the two.

I also think blaster and cannon ranges are still far too short compared to lasers, but that's an issue across the board, not just in human weapons.

**Comment by Amazinite** [comment]
> Except shrinking the blaster makes them smaller, and thus will make fighters & drones lighter. As I recall from Revamp, even reducing fighter hulls to 0 had insufficient impact to get fighters up to a good manouverability because the vast majority of their mass was in their outfits, not the hull.

Energy Blasters are already 5 tons. Shrinking them even further will have a negligible effect on the total mass of fighters. We'd need to slightly shrink every outfit that a fighter has in order to get any noticeable change in maneuverability.

> So trimming some mass out of everything is basically a requirement, which ties back to the fact that we need stuff that is actually made for fighters.

It's not a requirement, it's a possible course of action. What I had said is that *if* we want to make fighters more maneuverable *and* we want to do that by lowering fighter mass *then* we'd run up against the fact that we can't shrink fighters much more. But that "by lowering fighter mass" part is not the only course of action. The other course of action was to increase the thrust and steering of all engines and then up the mass on larger ships to compensate while leave smaller ships relatively unchanged. But that's only a necessity insomuch as we think that fighters need even more of a maneuverability boost, which looking at #5779 I don't think is so much the case.

**Comment by Zitchas** [comment]
I'm ambivalent about blaster ranges, as they should only be found on fighters (who can close distance easily) or on turrets on larger ships, where they are basically just there as AAA, and their primary target will come to them quickly enough. 

Humanity really does need some artillery though. And by artillery, I mean EVN's railguns. Stuff that you can pile on a carrier and have it bombard things from across the system without having to be even on the same side of the star as its target. Granted, it's not going to *hit* anything at those distances unless the fighters do their job and pin down the target, but that's the point of teamwork.

**Pull request merged**
