### PR TITLE
Artwork(star): A-Eater

### PR DESCRIPTION
**Pull request by RisingLeaf**
NOTICE: Sorry Saugia 😄 

----------------------
**Content (Artwork / Missions / Jobs)**

## Summary
I created this one some time ago to spice up Incipias space, but I would like to have it reviewed separately, to keep the Incipias PR less dense.
Screenshot 2023-02-13 at 7 02 08 PM

One blue a type star eating another, here is the configuration I use for this one:
```
	object
		sprite star/a-eater
		period 10
	object
		sprite star/a-dwarf
		period 10
		distance 55
```

Not an uncommon phenomenon in space so yea, why not? If we can add more spice, we should, at least that is what I think. 

Some technical notes on the design:
As you can see the cloud of gas is much bigger than the star it is coming from, 2 reasons for this:
1. The gas has a lesser density than the star.
2. The star was bigger and shrunk because it getting eaten.

## Artwork Checklist
As with the other 2 I will upload assets and that stuff when I know that it is finished.
 - [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [ ] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}

### CODE REVIEW

**Comment by Quantumshark** [comment]
Shouldn't it be a-eaten, rather than a-eater? As I understand it, what happens in these circumstances is that the small, but extremely dense dwarf star strips material from its larger companion as the companion star ages and expands beyond its roche lobe.

**Comment by RisingLeaf** [comment]
> Shouldn't it be a-eaten, rather than a-eater? As I understand it, what happens in these circumstances is that the small, but extremely dense dwarf star strips material from its larger companion as the companion star ages and expands beyond its roche lobe, so the larger star is the one that is being 'eaten'.
> 
> 

I got to say that my knowledge of this special phenomenon is not going really far. I don't think the name is really important but if you think I should change it I will do so.

**Review by GefullteTaubenbrust2 — CHANGES_REQUESTED** [review]
Only complaint is the star dust cloud stuff bits look a bit blurry, there star looks great though.

**Comment by TheGiraffe3** [comment]
Remove `orphaned` because it was included in the Incipias PR eventually?

**Pull request closed without merging**
