### PR TITLE
Added discord rpc (dont judge how sloppy it is, i've never used c++ before this)

### PR DESCRIPTION
**Pull request by eepyfemboi**
**Feature**

## Summary
Added Discord RPC to show the current system the player is in

## Screenshots
image

## Performance Impact
The discord activity is updated every frame, although I doubt it will be an issue.

### CODE REVIEW

**Comment by Koranir** [comment]
As far as I'm aware, Discord's game SDK isn't GPL-3.0 compatible which means that we can't accept this contribution without violating the game's license.

**Comment by RisingLeaf** [comment]
That is true:
https://support-dev.discord.com/hc/en-us/articles/8562894815383-Discord-Developer-Terms-of-Service

**Comment by eepyfemboi** [comment]
i guess i'll try to re-do it using https://github.com/discord/discord-rpc instead

**Comment by TheGiraffe3** [comment]
By the way, credits are usually updated when the changelog is, so you don't have to do that in this PR.

**Comment by eepyfemboi** [comment]
oh, i didnt know

**Comment by RisingLeaf** [comment]
copying a library over is not really something we would want to do, so unless this can be installed via either vcpkg or some other cmake magic like fetchcontent this is still not fitting

**Comment by eepyfemboi** [comment]
I have no clue how to do that
This is the first time i've ever done anything with c++, so i wouldn't know how to set that up, and in my opinion, if it works, it works, and at this point i've googled more than enough errors to give me a headache, so i don't see any reason to change it further, since its the same code being distributed either way

**Comment by Koranir** [comment]
Other than the package management thing, if we're entertaining the idea of integrations I'd rather have a central `Integrations` singleton that dispatches events to a list of integrations (through a virtual interface). This would make it so that we have an avenue for other integrations in the future, not just Discord.

**Comment by eepyfemboi** [comment]
i can try but at this point i think it'd be better if someone who actually knows what they're doing did it

**Comment by tibetiroka** [comment]
Yeah, a feature like this would need a lot of accompanying work. We wouldn't like to pull 17k lines of unreviewed (and unmaintainable by us) code into the project, and there is no guarantee that this deprecated version of the discord code will keep functioning for long.

In its current form, this PR is not going to get merged. The idea is nice, but I'm not sure if there is a good way of achieving this directly in the game's source code, unfortunately. I'm closing this PR until someone comes up with a fundamentally different way of adding these integrations.

**Pull request closed without merging**
