### PR TITLE
Change the colours of shield, hull and disabled hull in the UI to improve contrast

### PR DESCRIPTION
**Pull request by Quantumshark**
**Feature:** Better contrast in the UI, particularly with regards to colourblind support

## Feature Details
Changes the colours of the shield, hull and disabled hull in the UI
Hull is changed from the current orange to a greyish colour, which makes more sense as an indicator of hull armour
Disabled hull is changed to a dark red, giving much better contrast which makes it far more visible, especially to people with red-green colourblindness
Shields are made more saturated, to create better contrast with the grey colour of hull.

## UI Screenshots
image

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
I litteraly never noticed there was a disabled treshold before today.
Very good change!

**Review by Zitchas — APPROVED** [review]
This is a good change, as it makes it easier for everyone to see, or should, as best I can tell. (If it doesn't, then please let us know.

For reference, here's a site that tries to give a sense of how different people perceive color:

https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40

**Review by EjoThims — APPROVED** [review]

**Comment by quyykk** [comment]
I find the gray a bit hard to see, but maybe it's just me

**Comment by Naf5000** [comment]
I also think the hull is a bit hard to see. Maybe if it were a bit brighter, or even just white? The shield and disabled hull colors look great, though. Fantastic idea.

**Comment by vitalchip** [comment]
It's not a change I'll make so no skin in the game as such but the grey is less visible to me also.

The other issue is that the flagship now has different colours than the escorts and targets. That's not the biggest of problems but consistency is a good thing in Ui design. Hull would now be grey for the flagship but for the escort display grey is energy.

Google UK harmonised colours if you want an example of a colour changing shit show.


three-phase-colour-coding-bs-7671-label-set jpg

**Comment by Zitchas** [comment]
I think in terms of the hull change I'd be more inclined to make it a pixel thicker (and perhaps make the black hull segment lines a pixel thicker too). Maybe pull the whole ring in by a pixel too (so it's ever so slightly more separated from the shield ring)

**Comment by Zireael07** [comment]
I agree that both flagship and escorts should use the same colors.
Maybe the hull could be made white?

**Comment by Quantumshark** [comment]
The same colours are used for escorts and targets, because all three of the displays (flagship, target and escort) pull the colours from interfaces.txt.

image
image
image

**Comment by Naf5000** [comment]
I never noticed that escorts lacked a disabled hull indicator, but now that I think about it there have been several times where it would've actually been useful information during large battles. I'd also suggest giving escort hull similar graduations to flagship hull. Tie those UI elements together better and make it easier to distinguish escort hull and energy at a glance.

**Comment by Amazinite** [comment]
I feel like the increased saturation on the shield and disabled hull colors is enough. Do we really also need to make the hull color gray, meaning it's fighting against energy's color?

This screenshot is with the disabled hull and shield changes here while keeping the current hull color.
image

If we were to change the color of hull to something else, I'd imagine green might make more sense without clashing with energy's gray. This is with hull being `.18 .72 .18 .75`. The disabled hull opacity or color could perhaps use some work.
image
image

**Comment by Zitchas** [comment]
Honestly, I have a hard time differentiating between which bars are what on the escort section. They all blend together, there's really no identifier as to which bar is what, and combat is sufficiently fast that it is pretty rare that I can respond to anything I'm being told from there anyway. Energy and fuel levels are pretty much only useful for diagnosing problems out of combat. I'd just as soon remove energy and replace it with a way to click on a ship and get a "escort select" bubble or something that gives tactical scanner type info, except in detail, and without having to be within tactical scan range. (or even have a tactical scanner at all). And very importantly: Is **not** targeting the ship for weapons or attack order purposes.

**Comment by Zireael07** [comment]
Green hull does look nice and pops out from the background <3

**Review by Arachi-Lover — APPROVED** [review]

**Review by Saugia — CHANGES_REQUESTED** [review]
Agree with Derpy on the example using green looking better for something like this. The original looks too plain, and in comparison the disable orange color is a bit too vibrant compared to the rest.

**Comment by Quantumshark** [comment]
Red and green is not an ideal colour scheme, as red-green colour blindness (by far the most common type) makes it hard to distinguish the two - this is why I went for red and _grey_, because those are visually distinct for people with red-green colour blindness.
If we opt for Amazinite's suggestion of implementing support for different colour palettes, I see no reason why we couldn't make red and green the default, but keep red and grey as the colourblindness-friendly alternative palette.
Alternatively, having the two parts at contrasting brightnesses, rather than just contrasting hues, would guarantee visual distinction regardless of colour vision.

**Comment by Quantumshark** [comment]
image
```
color "hull" .18 .72 .48 .75
color "disabled hull" .5 0 0 .5
```
How about this?

**Comment by Koranir** [comment]
> image image
> 
> ```
> color "hull" .18 .72 .48 .75
> color "disabled hull" .25 0 0 .5
> ```
> 
> How about this?

Is the image using the changed colours? Because I can't tell the difference between the shields and disabled hull.

**Comment by Zitchas** [comment]
According to the website on coloring for colorblindness, Magenta is a pretty good substitute for red. Perhaps try that for the disabled segment? Not sure what the color code would be for it in ES terms, but the site lists: HEX #D41159, or R 212  G 17  B 89 .

https://davidmathlogic.com/colorblind/#%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7

That being said, it does have three professionally developed color schemes created by experts specifically for wide-ranging color accessibility across multiple types of colorblindness. Instead of trying to re-invent the wheel, it might be worth using one of them. These color palettes are not designed by the site, but rather by various independent research teams. The site merely presents them and a comparison mechanism to allow people to approximate what someone with various conditions would see.

The big thing, though, that keeps coming up in all the reference materials for accessibility in colorblindness contexts is: Don't rely exclusively on color to convey information. Use textures, patterns, symbols, or other differentiations.

To use a real-world dial as inspiration: (An airspeed indicator from an aircraft):

asi-colored-markings

Note the red bar on the left side, labeled VNE. (Stands for Velocity Never Exceed. It's the speed at which significant structural failure is likely to occur). Having a magenta  bar similar to this one placed at the disabled threshold would go a long ways towards making this transition point obvious and very distinctive, regardless of the colors involved.

**Comment by Zireael07** [comment]
@Zitchas the escort bars could get a one letter label to add some distinguishing element that does NOT rely on color, but I fail to see how that could be done for the flagship display

Re: the colors, when I researched colorblindness for my project, two common alternatives to red-green color scheme were magenta-green and red-cyan.

**Comment by Quantumshark** [comment]
> Note the red bar on the left side, labeled VNE. (Stands for Velocity Never Exceed. It's the speed at which significant structural failure is likely to occur). Having a magenta bar similar to this one placed at the disabled threshold would go a long ways towards making this transition point obvious and very distinctive, regardless of the colors involved.

Yes, having a little magenta mark sticking out of the hull circle at the disabled threshold would be a perfect solution!
Adding additional elements like that to the UI is beyond what I can do, but if someone else wanted to code that I think it would be an excellent addition, and would solve the problem that this PR was created to fix.

Independently of that, it seems that there has been broad support for the change to shield colour in this PR, which is largely separate from the hull/disabled hull clarification. If the new shield colour in this PR is something that people want to see in-game, I could reduce the scope of this PR to just changing the shield colour, and leave the addition of a mark to someone more experienced with UI code.

**Comment by Hurleveur** [comment]
With the way interface.txt works its possible we can add it without needing code changes, I think

**Comment by Saugia** [comment]
Any progress on this PR, or any sort of consensus as to what the most recent plausible color schematic should be.

**Comment by Quantumshark** [comment]
Closing as the desired solution isn't currently possible.

**Comment by Zireael07** [comment]
@Quantumshark: you said > It seems that there has been broad support for the change to shield colour in this PR, which is largely separate from the hull/disabled hull clarification. 

Please please?

**Comment by Quantumshark** [comment]
> @Quantumshark: you said
> 
> > It seems that there has been broad support for the change to shield colour in this PR, which is largely separate from the hull/disabled hull clarification.
> 
> Please please?

I'll open a separate PR (#9012) for that, rather than opening this one.

**Pull request closed without merging**
