### PR TITLE
add newline to the end of coalition.txt

### PR DESCRIPTION
**Pull request by 7even**
This adds a newline to the end of `data/coalition.txt` so that the parser of [my reference site for ES](https://github.com/7even/endless-ships) doesn't break; also it seems like a good practice anyway and is checked both by git and various programming language linters.

### CODE REVIEW

**Comment by tehhowch** [comment]
Your parser should not be dependent on the presence--or lack thereof--of a final newline.

**Comment by Pointedstick** [comment]
A harmless change, but @tehhowch is right: this is not and should not be mandatory, so you should fix your parser.

**Comment by 7even** [comment]
Sorry, I know that a proper parser should not fail because of a lack of newline but newlines are an important part of the data files grammar, and making a special rule for the last line of the file would really complicate things up; unfortunately I don't have the time to implement and maintain that.

**Comment by Amazinite** [comment]
No harm.

**Comment by 7even** [comment]
Thanks.

**Pull request merged**
