### PR TITLE
Submunition Velocity Inheritance – Fix

### PR DESCRIPTION
**Pull request by DeBlister**
**Bugfix:** This PR addresses issue #6695

## Fix Details
Previously, submunitions would fire from their primary munitions as if from a standstill.  The main culprits were Ka'Het Annihilator Turrets, Proton Turrets, and Drak Antimatter Cannons.  The code that seems to follow my pseudocode most closely worked for the introduced issues for Proton Turrets (it's the only weapon that has primary munitions with non-zero velocities), so I commented it out and it seems to work for all weapons now.  Missiles seem not to follow ship velocity but I'm fairly certain this is due to drag: I eliminated the drag on Finisher Pods and they then performed as expected.

## Testing Done

- Ka'Het Annihilator Turret – functions as expected
- Proton Turret – functions as expected, though with the code that is commented out the projectiles would not move beyond the turret.  I don't understand how things are working now as my pseudocode says I should have needed the code I commented out, but I can't find anything I broke.
- Drak Antimatter Cannon – functions as expected, though the visual trail does look rather off, if still correct when you think it through.
- Finisher Pod – initially appears to exhibit faulty behavior, but that is only due to the drag.  When that it removed, it functions as expected.
- Inhibitor Cannon – functions as expected
- Ka'Het Ravager Turret – functions as expected
- Particle Waveform Turret – functions as expected
- Railgun – functions as expected
- Javelin Rack – functions as expected

## Save File
Any save will work.  I might later attach a save with weapons in storage on a single planet for testing, but IIRC there's a plugin that does that too though I've never tried it.

### CODE REVIEW

**Comment by DeBlister** [comment]
This does not fix the issue, currently.  What it does is add submunition velocity to parent velocity, which can lead to incorrect behavior.

That being said, I think I figured out why the Proton Turret acted funny when using the code that is currently commented near the change (which was just removing the parent projectile's self-velocity).  Proton Fragments have no set velocity of their own and cause weapon->Velocity() to return 0.  So, the parent munition is correctly halted or rather brought back into sync with the parent ship's velocity at firing, but the submunition does not do anything other than rotate itself with its inaccuracy.  The same behavior can be observed with the Drak Antimatter Cannon and Drak Antimatter Fragments.  The Ka'Het Annihilator Turret works because Annihilator Projectiles; that the primary munition has no velocity and only velocity override (used for AI targeting I believe?) is irrelevant.

In order to fully resolve this, then, we either need to standardize the format of the data files for weapons with submunitions or put in a workaround in the submunition launcher that takes uses primary munition velocity at the new heading if submunition velocity returns 0.  For example:

`if(weapon->Velocity() == 0)`
`{`
`Point firingVelocity = this->angle.Unit() * (parent.GetWeapon()->Velocity() + Random::Real() * weapon->RandomVelocity());`
`}`
`else {`
`Point firingVelocity = this->angle.Unit() * (weapon->Velocity() + Random::Real() * weapon->RandomVelocity());`
`}`
`velocity += this->angle.Unit() * (firingVelocity);`

**Comment by DeBlister** [comment]
This is a functioning fix now.  The second commit above doesn't change any functionality, it just standardizes the submunitions in the data files and maybe saves a small amount of computation time.  If we want to leave the submunitions to inherit their parent velocity instead of hard coding it in the data files that will work too, *so long as there are never sub-submunitions*.  I haven't yet checked if you can point back to the parent of a parent munition, but the workaround that I used briefly doesn't allow for it.

**Comment by Amazinite** [comment]
Not a fan of the approach of ignoring the parent velocity and adding the submunition velocity to the parent velocity in the data. Not only does this not account for any changes in velocity from acceleration/drag or changes caused by the velocity of the firing ship, it also would essentially break any plugin weapons that use submunitions.

**Comment by DeBlister** [comment]
I think you're right.  I realized today that this wouldn't work for explosions or weapons with very high inaccuracy.  I'm trying to purge the old commit history currently and then I'm going to try to augment the parent velocity with the new submunition heading rather than maintain the "grandparent" velocity only.

**Comment by DeBlister** [comment]
Well that worked, if only partially.  At least now if you look at my branch it's only 3 commits ahead of master (the 3 commits I actually did for this PR).

I'm going to work on changes to address explosions, high inaccuracy submunitions, and the issues presented if the primary munitions have changed velocity since being fired.

**Comment by DeBlister** [comment]
At this point...I'm just going to delete my fork and start over.

**Pull request closed without merging**
