### PR TITLE
Add cloaking heat attribute

### PR DESCRIPTION
**Pull request by Hadron1776**
This PR adds a `cloaking heat` attribute for further customization of outfits, (specifically, cloaking devices).

Requested by @TheUnfetteredOne

### CODE REVIEW

**Comment by TheUnfetteredOne** [comment]
Thx bby

**Comment by Hadron1776** [comment]
Yeah, totally forgot about that :P

**Comment by tehhowch** [comment]
Question: should cloaking heat be added to idle heat display or not? I don't know if the energy it uses is, but I imagine including both could be warranted

**Comment by Bladewood** [comment]
`cloaking energy` isn't.

Nor is something like `afterburner energy` and `afterburner heat`.

**Comment by Hadron1776** [comment]
@tehhowch It doesn't look like the cloaking energy is added to the idle energy display.

**Comment by tehhowch** [comment]
Maybe we need/want an "Activated outfit" line? For a different PR though.

**Pull request merged**
