### PR TITLE
fix(tests-output): Don't show condition errors during unit testing

### PR DESCRIPTION
**Pull request by quyykk**
This PR suppresses the condition errors shown when executing the unit tests:

```
Error: not adding provider for "ships: A:", because it is within range of prefixed derived provider "ships: ".
Error: not adding provider for "ships: A:", because it is within range of prefixed derived provider "ships: ".
Error: replacing condition-entry for "ships: ", because it is within range of prefixed derived provider "shi".
Error: replacing condition-entry for "ships: A", because it is within range of prefixed derived provider "ships: ".
Error: replacing condition-entry for "ships: A", because it is within range of prefixed derived provider "ships: ".
Error: not adding provider for "ships: Large: ", because it is within range of prefixed derived provider "ships: ".
===============================================================================
All tests passed (75923 assertions in 58 test cases)

```

### CODE REVIEW

**Comment by tehhowch** [comment]
I'm unfamiliar with the context surrounding these particular tests, but:
 - if these are _errors_, that would imply something should be fixed.
 - if they are _expected_ to occur, then they should be asserted upon, not just suppressed.

**Comment by quyykk** [comment]
> if they are expected to occur, then they should be asserted upon, not just suppressed.

They are in fact asserted upon :) Or rather, the behavior that shouldn't happen is verified not to happen, and there is also a warning emitted if it does happen (which is the one we're suppressing)

**Comment by tehhowch** [comment]
> > if they are expected to occur, then they should be asserted upon, not just suppressed.
> 
> They are in fact asserted upon :) Or rather, the behavior that shouldn't happen is verified not to happen, and there is also a warning emitted if it does happen (which is the one we're suppressing)

A rephrasing of my comment would be, "Make assertions on the contents of the captured output rather than just capturing the output."
Conceivably, one would want to make sure that these errors are omitted when the scenario occurs, so that the responsible party can avoid doing whatever triggered the scenario.

Related: are these scenarios user-achievable? If not, and these are scenarios only a developer making changes to the code would achieve, a std::terminate would seem more appropriate than an error message they may not notice.

**Comment by petervdmeer** [comment]
> Related: are these scenarios user-achievable? If not, and these are scenarios only a developer making changes to the code would achieve, a std::terminate would seem more appropriate than an error message they may not notice.

Those scenarios tested for can only be achieved by a developer making changes, so using `std::terminate()` sounds appropriate.
Using Exceptions (which usually result in std::terminate()) might even be better, because then we can also [check within Catch2 that the exception is thrown](https://github.com/catchorg/Catch2/blob/devel/docs/assertions.md#exceptions).

**Comment by quyykk** [comment]
> Those scenarios tested for can only be achieved by a developer making changes

Can they also not happen for old save files that contain the old conditions?

**Review by petervdmeer — APPROVED** [review]

**Pull request merged**
