### PR TITLE
feat(artwork): Make the Systems Core (Tiny) fit in with the rest of the System Cores

### PR DESCRIPTION
**Pull request by Anarchist2**
## Summary
This PR brings the graphics of the Systems Core (Tiny) in line with the rest of the Systems Cores, by adjusting the lighting and materials, as well as changing the layout of the model so that the wires reach up to behind the text, and the floating panels are the same size as they are on the Systems Core (Small).

## Screenshots
Before:
women kissing

After:
men kissing

## Artwork Checklist
 - [x] I decline to claim copyright of any assets produced or modified.
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/190
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/433

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
I think the stem on the top may be extended slightly too far at the moment; the others go about that distance, but the diminutive size of the Tiny Core changes the dynamic.
And should the feet be changed as well to be in a pentagonal shape as opposed to the haphazard way they're currently arranged?
You can see the "legs" of the Tiny SysCore; when compared to the other ones which are all dark there's a distinctive difference.

**Comment by Koranir** [comment]
I feel like if we want the tiny core to be more in-line with the rest, the inner bit should be a regular octahedron instead of whatever is going on in there now, as the rest of the core's cores are made up of triangular bits.

**Comment by Anarchist2** [comment]
Updated.
image

**Review by Koranir — APPROVED** [review]

**Review by TheGiraffe3 — APPROVED** [review]
It still looks like the pole on the top goes too far to me, but given that all the other Systems Cores overlap, that's probably fine.

**Pull request merged**
