### PR TITLE
feat(balance): Reduce v0.9.15 afterburner buff by about 50%

### PR DESCRIPTION
**Pull request by Amazinite**
**Content (Artwork / Missions / Jobs)**

## Summary
Alright, we've had our fun, but it's time to pull afterburners down a bit.

For many years, afterburners were basically useless. They took up too much space to be worth downgrading your engines to fit them, as they didn't feel like they provided a substantial enough boost in thrust for the amount of fuel they consumed. As such, afterburners rarely saw use prior to v0.9.15.

In #6686, which was merged for v0.9.15, I made substantial changes to all these three pain points: size, thrust, and fuel usage. Afterburners were made about 33% smaller, given about 50% more thrust, and took 75% or 80% less fuel. I definitely knew at the time that these numbers were probably overboard, but wanted to see how things played out, and I'd say they've played out pretty absurdly.

This PR seeks to rein afterburners in after that buff. I looked to the stats of thrust/ton and thrust/fuel on the Volcano, Ionic, and Bellows afterburners before and after the buffs from #6686 and cut the increase roughly in half. This means that these afterburners will be at the midpoint in power between what they were before and what they are now. If these are two strong then we can cut the buff in half again, or if they're too weak we can cut this nerf in half from here, basically binary searching the balancing point. In order to not make space usage an issue again, I've opted to only change the thrust and fuel usage values, leaving the afterburners at their 33% reduced size compared to before.

Afterburner | Stat | Before buff | Current | Nerf
---|---|---|---|---
Volcano | thrust/ton | 6,000 | 13,500 | 9,756
\- | thrust/fuel | 3,000 | 22,500 | 13,008
Ionic | thrust/ton | 4,350 | 9,787.5 | 7,065
\- | thrust/fuel | 17,400 | 104,400 | 62,800
Bellows | thrust/ton | 50,072.7 | 78,685.7 | 64,285.7
\- | thrust/fuel | 4,590 | 18,360 | 11,538.5

Along with these three afterburners having been buffed in v0.9.15, we've also gained new afterburners, a whole Korath set as well as a new human afterburner larger than the now-named Volcano: the Caldera. The Caldera has been nerfed proportionally to how the Volcano was nerfed. This means about 28% less thrust and 25% more fuel usage. The Korath set has been given a flat 20% thrust decrease and 20% increase in fuel usage; the Korath afterburner set may need to be looked at on its own in the future, as I didn't want to overnerf these new afterburners, so I've given them a lesser nerf than what the other afterburners are receiving here.

Notably, the buffs to fuel usage were much greater than the buffs to thrust, so while this is a blanket 50% buff reduction to both, it may be that fuel usage or thrust need looked at independently of the other stat in the future.

### CODE REVIEW

**Comment by Zitchas** [comment]
Seems reasonable, at least in concept. 

Although instead of nerfing the afterburners directly it might be worth considering how they work and interact with the physics. For instance, what about setting it up so that a ship starts slowing down to its normal max speed immediately when afterburners are released? That'd make the high fuel cost of some of these more meaningful, since afterburners would have to be used continuously to maintain a above-max-speed cruise.

If I'm not mistaken (which I might be), we don't slow down to max until we start accelerating normally or change direction, right?

**Comment by Hurleveur** [comment]
I think that we should not just bring power down but also bring fuel cost up, its way too low currently.

**Comment by Saugia** [comment]
I haven't looked terribly deep in the stats yet, but if not already, we should probably make it so two volcanics =/= caldera or better.

**Comment by Amazinite** [comment]
> For instance, what about setting it up so that a ship starts slowing down to its normal max speed immediately when afterburners are released?

I could see that working. I'd justify allowing us to have afterburners provide more thrust without causing issues.

> If I'm not mistaken (which I might be), we don't slow down to max until we start accelerating normally or change direction, right?

The way drag works specifically is that if your "acceleration" Point is non-zero, drag is applied. This Point can be non-zero if you're using thrusters or afterburners, weapons with firing force, or are hit by a projectile with hit force.

I imagine the reasoning behind this was MZ wanted to add drag to cap ship speeds, but felt that drag being applied at all times caused ships to feel less responsive or more clunky or some other issue with game-feel. Imagine a scenario where you're traveling in one direction, let up on the thrust to think for a moment about what you want to do next or to change directions more quickly (as if you held thrust the entire time while you were trying to change directions, that could make it take longer than just facing the direction you want to go before thrusting), but that entire time you're slowing down. If this is happening in the middle of being chased, then that entire time you'll have your enemies gaining on you, which means the most effective tactic becomes "just hold W," which doesn't sound the best.

I do think it's a little absurd that letting up on your thrust lets you cruise forever, though. How do these ideas sounds? We might not use all of them at once, but just throwing out stuff that comes to mind.
* If above achievable speed from normal thrusters, drag is doubled, regardless of whether you're thrusting or not. (Could still use normal drag when afterburners are active as to not effectively cut in half the thrust that afterburners apply.) Once you've slowed to your normal max speed, drag begins applying normally. This means you wouldn't just not be able to keep a high cruising speed after using an afterburner, but that you'd tank down to your normal speed, meaning afterburners are only really useful while, well, in use.
* Drag only doesn't kick in while not thrusting for 3 seconds (180 frames) (1 second with fast forward on). After the 3 seconds are up, if you're not thrusting, you'll begin slowing to a stop. This leaves open a window of time to think or change your facing angle before moving again, while also removing the ability to cruise forever. This change would especially make reverse thrusters more important for combat, as right now you're able to thrust away from a target, turn to face them while still cruising away, and use your guns to pound on them while they try catching up to you. If slowed to a stop while trying to do that, though, then you'd *need* reverse thrusters to try and do that.

**Comment by Amazinite** [comment]
> I think that we should not just bring power down but also bring fuel cost up, its way too low currently.
> Like bring it down 25% instead of 50 and bring fuel up by 25% too

This is a 50% reduction in the buff to both thrust and fuel, not just thrust. The actual change in "50% buff reduction" does come out to about 20-30% less thrust and 20-30% more fuel.

**Comment by Zitchas** [comment]
I'm fine with regular thrust letting us cruise forever: It's space, after all.

I'd run with the lore that the afterburners have some kind of "safety override" that lets the ship bypass normal manoeuvring speed restrictions, but once the afterburner lets off, it starts decelerating back down to normal speed. Having a 3 second gap there before the deceleration starts would fit.

**Comment by Hurleveur** [comment]
Changes look good, bye afterburner only I guess

**Review by Hurleveur — APPROVED** [review]
the slightly higher fuel cost makes a lot of sense and lower thrust too, I was piloting a world ship faster than a sparrow not so long ago...
good changes, I think, although I'm no balance expert ofc

**Comment by Saugia** [comment]
I haven't tested this - is the one `olofez variant still able to run afterburner-only?

**Comment by Zitchas** [comment]
I would expect so. It'll be slower than it used to be, but nothing about this makes it imossible to fly.

Now, whether or not it is effective as a fighting solution... That I don't know. Again, I expect that yes, but not as good as before.

**Review by Zitchas — APPROVED** [review]
My preference would be to be a little lighter on the non-core-human afterburners; but either way, this looks reasonable.

edit: lighter, as in less-nerf.

**Comment by warp-core** [comment]
> Now, whether or not it is effective as a fighting solution... That I don't know. Again, I expect that yes, but not as good as before

It doesn't have any ship to ship weapons, so it should probably just avoid getting close to anything that might want to fight it.

**Pull request merged**
