### PR TITLE
feat(content): Remove Gegno Quarg `custom penalties for`

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR removes the custom penalty introduced in https://github.com/endless-sky/endless-sky/pull/8016 so that the Gegno Quarg properly react to you firing on the Gegno's civilians. The custom penalty was added to avoid an all-out Quarg war, but now that the Quarg are split in governments, this can be done simply with the Gegno Quarg's relations. Now the Quarg will care if you shoot at a civilian in front of their eyes.

## Save File
N/A

## Testing Done
Yes

### CODE REVIEW

**Comment by mOctave** [comment]
Looks good, although lore-wise, does it make sense for the Quarg to treat the Gegno as if they are their own kind when it comes to this? I don't know enough about the Gegno to say for sure, but it seems to me like something like .5 would be more reasonable: a signficant penalty, but not as bad as shooting up Quarg ships.

**Comment by Saugia** [comment]
Yes. As I've discussed and Arachi agrees, the Quarg with the Gegno are on a "do not fire on civilians or else" policy. It's a young species in a galaxy with several species the Quarg and Drak failed to protect. Regardless of if the number is too big or not, the Gegno Quarg should get upset if you fire on even the smallest civilian vessel. They wouldn't care as much about themselves because they're a Tier 3 race that can handle you, whilst the Gegno are not.

**Review by mOctave — APPROVED** [review]
Alright, then. In that case, this looks good.

**Comment by Saugia** [comment]
I've brought the Quarg (Gegno)'s relation with the Gegno down from 1 to 0.1. It doesn't necessarily change how the interactions behave, since the gov still has `foreign penalties for`, but it makes sense the Quarg aren't at a 1:1 relation with the Gegno (while the only other ones they're 1:1 with is other Quarg). Gameplay-wise, the (Gegno) Quarg still properly become hostile if you fire upon a civilian, even if you meet them after you jump away from the system you did it in.

**Review by quyykk — APPROVED** [review]
makes sense

**Pull request merged**
