### PR TITLE
Change blending for the Coalition Flare effects

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
This PR changes the Coalition Flare effects back to using half-additive blending. This fixes an annoying issue where the launcher does not delete the old files, thus breaking the effect altogether. In game, the difference should be fairly subtle.

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/53
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/267

### CODE REVIEW

**Comment by quyykk** [comment]
Wouldn't this mean that we're breaking the launcher continuous builds again?

**Comment by Amazinite** [comment]
I don't really think we should be making content changes to the base game to cope with issues with the launcher.

**Comment by Hecter94** [comment]
The effects with half-additive blending definitely look better. 
It's not a significant difference, but it is a visual improvement. The flares look much sharper and more distinct, rather than smeared out and slightly faded. 

Definitely an improvement even ignoring the benefit to the launcher.

**Comment by GefullteTaubenbrust2** [comment]
> The effects with half-additive blending definitely look better. It's not a significant difference, but it is a visual improvement. The flares look much sharper and more distinct, rather than smeared out and slightly faded.
> 
> Definitely an improvement even ignoring the benefit to the launcher.

To be entirely fair, the image I posted, I believe anyways, was from an early commit before it got merged, but it still looks noticeably better in my eyes.

**Comment by Arachi-Lover** [comment]
Yeah I can't tell the difference between these (couldn't tell the difference between the original and Geffulte's first redo of them either), so not much I can say on this I'm afraid.
I'm fine with changing, like I said I can't tell the difference so it definetly doesn't impact anything negatively on my end. I don't know about blend technicalities or details, but if this one is more advantageous then sure.

**Review by roadrunner56 — APPROVED** [review]

**Review by beccabunny — APPROVED** [review]

**Comment by Amazinite** [comment]
Since the work's already done, might as well take it, but going forward, as I mentioned, we shouldn't be making changes for the sake of the launcher.

**Pull request merged**
