### PR TITLE
Navy Tear Gas Outfit

### PR DESCRIPTION
**Pull request by tmbutterworth**
I added a new Navy Tear Gas Outfit that requires a Navy Outfit License. It will show up in the game at the same time as the electron weapons.

### CODE REVIEW

**Comment by Amazinite** [comment]
1) Is this not effectively a duplicate of #3923? (i.e. a new H2H weapon released by the Navy during the war.)
2) Why would tear gas appear in game so late? (tear gas isn't exactly something that takes centuries to develop like the electron weapons and is likely something already in existence in game.)
3) Why would tear gas be sold at Deep outfitters, but be locked behind a Navy license? (Electron weapons are sold at Deep outfitters because the Deep developed them, and they are not explicitly Navy technology.)
4) Why would tear gas be locked behind a Navy license and be sold at the same time as the electron weapons, which are not behind a Navy license? (Releasing the sale of tear gas at the same time as the electron weapons would suggest some link between the two, yet the way of obtaining them differs because of this license)

**Comment by tmbutterworth** [comment]
> No patch mission for people who are already past that point in the story line.
> The outfit sprite is a swizzled Nerve Gas sprite.
> 
> How does this outfit improve the game? What new choices does it give the player?
> 
> Also opened a second PR when new commits to the old PR would have sufficed.

I was having problems adding the files to the first PR so I closed it and forked master instead.

**Comment by tmbutterworth** [comment]
>     1. Is this not effectively a duplicate of #3923? (i.e. a new H2H weapon released by the Navy during the war.)

That is a new rifle. Tear gas and a rifle is different.
>     2. Why would tear gas appear in game so late? (Tear gas isn't exactly something that takes centuries to develop like the electron weapons and is likely something already in existence in game.)

With the exception of the pirates they were at peace until the war. I license locked it and added it to the navy because I wasn't sure if it would be considered unbalancing.

>     3. Why would tear gas be sold at Deep outfitters, but be locked behind a Navy license? (Electron weapons are sold at Deep outfitters because the Deep developed them, and they are not explicitly Navy technology.)

I just thought that was a good place to put it. I can move them if you have a better idea.

>     4. Why would tear gas be locked behind a Navy license and be sold at the same time as the electron weapons, which are not behind a Navy license? (Releasing the sale of tear gas at the same time as the electron weapons would suggest some link between the two, yet the way of obtaining them differs because of this license.)
Nerve gas is illegal, so I figured tear gas would be restricted to navy only.

>     1. Do you have a unique outfit image?

I adjusted the Hue saturation on the Nerve gas in GIMP to make the green red and the box reddish pink. I figured since they are both gas the canisters can look the same.

**Comment by tmbutterworth** [comment]
> > The outfit sprite is a swizzled Nerve Gas sprite.
I adjusted the hue saturation on the nerve gas in Gimp to make the green red and the boxes reddish pink.

> > How does this outfit improve the game? What new choices does it give the player?
The navy has license locked ships, but no specific hand to hand outfits. I was thinking tear gas and body armor would be good. Like the ships it is their to show Navy capabilities.

**Comment by tmbutterworth** [comment]
> No patch mission for people who are already past that point in the story line.

Like the Navy license locked ships, the license locked outfits would be just to show Navy capabilities.

I could change it to simply add the outfit to outfitters and not have them appear with the electron weapons.

**Comment by jafdy** [comment]
A patch mission would cause the changes to events visible in your PR appear for saves that have already had that event, it is more or less a requirement for any PR that changes an existing event, especially one that was in the game for the last stable release.

**Comment by Amazinite** [comment]
>That is a new rifle. Tear gas and a rifle is different.

Yes, they are different in reality, but in functionality they are not. As I said, both this proposal and #3923 add war-time H2H weapons to the Navy. How would these actually differ in game and why should both exist, or why should tear gas exist over the electron rifle?

>With the exception of the pirates they were at peace until the war.

That doesn't answer the question as to why they would only appear so late. If such weaponry existed, should the Navy not always have them on hand? The FW-Navy war also doesn't deal much with H2H combat, so the Navy only fielding such weapons during the war doesn't make much sense.

>I adjusted the Hue saturation on the Nerve gas in GIMP to make the green red and the box reddish pink. I figured since they are both gas the canisters can look the same.

A swizzled version of an existing image is not a unique image.

**Comment by tmbutterworth** [comment]
> A swizzled version of an existing image is not a unique image.

If the art work is no good for inclusion then the rest is irrelevant so I will go ahead and close it.

**Comment by DingusShingleton** [comment]
Nerve gas and tear gas are EXTREMELY different. In real life in 2018, police forces and others all over the world use tear gas for various purposes. Using nerve gas, on the other hand, is a war crime. Nicholas cage didn't infiltrate alcatraz and risk his life to prevent ed harris from bombarding san fransisco with tear gas lol.

Now having said that, while I have some issues with this concept, I do like the idea of harder-to-get hand to hand outfits. For tear gas, I agree that it should not be introduced during the war, it should be there from the get go since, again, we literally have tear gas now in 2018. However this brings my to my next point which is that...

...In the description it calls tear gas a non-lethal weapon, but uh... when you use it, they will all die (assuming you win). Given the fact that the game doesn't support non-lethal weapons, I suggest using a different weapon that is in fact lethal. Like an armed exosuit outfit that takes up outfit space, requires crew, and rips face. Now THAT would be a navy locked outfit, and it would be super cool and desirable. But also off topic. I think there are many more types of weapon that could be used with these stats that would be lethal.

Then again, now that I'm thinking this out, I suppose it is possible to have 100 guys with unlimited frag grenades just nolan ryaning a deluge of nades down the halls of the enemy ship. So maybe the disbelief is already suspended, in which case tear gas is fine. I'll have to think on that

**Comment by tmbutterworth** [comment]
> I think there are many more types of weapon that could be used with these stats that would be lethal.

I'm working on a bunch of hand-to-hand outfits at the moment that I am combining into one plugin. Here is what I have so far:
Armory - copied from "Shields UP Plug-in" Takes up mass and increases the armory rating.
Assault Rifle - copied from "Shields UP Plug-in" Higher attack and defend and higher cost than the laser rifle.
Blaster Rifle - lower attack and defend and less cost than laser rifle sold by Syndicate.
Body Armor - copied from "Shields UP Plug-in" 2 attack and 2 defend
Sidearm - Basic blaster pistol, I made this cheap 1000 it only has a small amount of attack and defend. These are referenced in the game but are not currently present. The outfit description for laser rifle "A laser rifle is a step up from the sidearms that crew members typically carry"
Stun Grenades - these cost less than fragmentation grenades and have a weaker attack and defend.
Tactical Armor - full suite of body armor with helmet. better quality than body armor 4 4

Of course tear gas higher cost than stun grenades hight attack and defend. I'm thinking about adding a Gas mask as well.

I currently do not have any of these license locked including the tear gas. I was afraid of unbalancing but cost will take care of it. I'm putting the final touches on the plug-in. I should have it ready to upload tonight or tomorrow. Probably tomorrow.

**Comment by tmbutterworth** [comment]
I just pushed the plug-in repository to GitHub: tmbutterworth / hand-to-hand-outfits
https://github.com/tmbutterworth/hand-to-hand-outfits

Please take a look at it and let me know what you think and if you have any ideas for additional outfits.

**Comment by KiLEdEnNis** [comment]
(or join the Discord and discuss plugin stuff there since GitHub's not for that
invite link extension: ZeuASSx)

**Comment by tmbutterworth** [comment]
> (or join the Discord and discuss plugin stuff there since GitHub's not for that
> invite link extension: ZeuASSx)

Thanks for the invite I'll look at setting that up when I get a chance.

**Pull request closed without merging**
