### PR TITLE
tactical scanner image

### PR DESCRIPTION
**Pull request by Kryes-Omega**
made for the recent and currently image-less tactical scanner

### CODE REVIEW

**Comment by jafdy** [comment]
@2x images?

**Comment by endless-sky** [comment]
Is that using the standard lighting angle? I feel like more of it should be in shadow.

**Comment by Kryes-Omega** [comment]
Nope, I changed it while I was working and forgot. Fixed, and looks much better now.

**Comment by endless-sky** [comment]
Can you post or email me the raw source files (blender and GIMP) for this?

**Comment by Kryes-Omega** [comment]
Blender and gimp files:
[tactical scanner.zip](https://github.com/endless-sky/endless-sky/files/1493758/tactical.scanner.zip)

**Comment by Pointedstick** [comment]
Awesome, looks like it came off the Millennium Falcon.

**Comment by Kryes-Omega** [comment]
actually about 60% of it is a modified radar dish from a model Corellian freighter I was working on, so you're not far off.

**Pull request merged**
