### PR TITLE
Elementary C++ error can cause a crash in NPC MissionAction Conversations

### LINKED ISSUE #8870: Crash when accomplishing this mission definition.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The game crashes when accomplishing the following mission definition (see steps).
EDIT: It crashes when using the AppImage version, but does not crash in all configurations (or it's chaotic). It does crash in `linux-gles-release` / `linux-gles-debug` configurations.

Note that if `on enter "Rutilicus"`, or the last conversation line, are not present, the crash does not happen. The `on enter` does not need to be empty for the crash to happen.

The crash message is as follow (after clearing the mission definition a bit, longer versions will simply result in a segfault):
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```
**EDIT:** Sometime it's this message, sometime it's a segfault.

### Steps to Reproduce

1. Use the `AppImage` or build endless-sky with a `linux-gles-*` configuration.
2. Install this mission:
```endless-sky
mission "CRASH TEST"
	landing
	source "New Boston"
	on offer
		conversation
			"Depart and board the derelict Freighter."
				launch
	on enter "Rutilicus"
	npc save
		government "Team Red"
		ship "Freighter"
		personality staying derelict nemesis
		system "Rutilicus"
		on board
			conversation
				`	If the line 'on enter "Rutilicus"' is not present in the mission, it does not crash.`
				`	Pick the first option cause a crash.`
				choice
					`	(Crash.)`
				`	If this line is not present, no crash happen. Also, if the line 'on enter "Rutilicus"' is not present, it does not crash.`
```
3. Either use an existing pilot, or start a new one and land on New Boston.
4. The mission will cause you to take off, asking you to board the ship. Do that.
5. Click the first option from the conversation: The game crashes.
**EDIT: It's chaotic, sometime it crashes, sometimes not.** Several attempts doing the exact same thing sometimes cause the crash, sometimes not, and with different error messages.

### Expected Behavior

The game should not crash.

### Screenshots

Not applicable.

### Link to save file

Works with new pilots too.

### Operating System

Ubuntu

### Game Source

Github Releases (AppImage)

### Game Version

v0.10.1-alpha (e3aa335)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Bugfix:** This fixes a memory corruption error that crash *any build* on *any platform*. Fixes #8870 

## Fix Details
When an NPC MissionAction has a Conversation, the Conversation is destructed before the ConversationPanel can use it. This happened because of an elementary C++ coding mistake:

```C++
class ConversationPanel: public Panel {
...
    const Conversation &conversation;
};
```

You should never, ever, ever, *ever*, use reference members. Either use a regular member, or a managed pointer. The only acceptable time - and maybe not even then - is if you know 100% for certain that the object has a longer lifetime than the reference. (Such as PlayerInfo.) That is *not* the case with a Conversation.

This is the sequence of events:

1. Mission is instantiated, creating a new NPC with a MissionAction that contains the Conversation.
2. The action is triggered. It sends a `const Conversation &` of its conversation to a new ConversationPanel
3. NPC deletes the MissionAction, which deletes the Conversation.
4. The ConversationPanel uses the now-deleted Conversation object.

This is why you should *never* have reference members.

There aren't many ConversationPanels active at once, and Conversations aren't very large. We can manage giving ConversationPanel its own copy of the Conversation.

## Testing Done
Run this mission in Endless Sky in Valgrind:

[crash.txt](https://github.com/endless-sky/endless-sky/files/11710338/crash.txt)

## Save File
Any pilot on New Boston will work. Start a new game, or use any save.

### CODE REVIEW

**Comment by Pshy0** [comment]
I tried with those changes, and it does not crash anymore.

**Comment by Amazinite** [comment]
>The only acceptable time is if you know 100% for certain that the object has a longer lifetime than the reference.

Checking the blame, this is a 10 year old line from the very first commit to the repository.
image
This was 100% the case up until #7326 was merged a few months ago. I'd prefer if we instead changed the manner by which NPC makes actions single-use, as the erasure of the mission action was intended as a temporary measure until NPC actions are given more functionality.
https://github.com/endless-sky/endless-sky/blob/226df696e262349ef03743d804707463b9a5e426/source/NPC.cpp#L781-L783

Given that there are things that we'd want actions triggered by NPCs to do which would not make sense for MissionAction (e.g. having actions trigger a personality change for the NPC), we should create a new class called NPCAction that contains a MissionAction (similarly to how MissionAction contains a GameAction). For the time being, the sole functionality of NPCAction should be to hold a MissionAction and record whether it's been used or not as to not have it be used twice. An NPCAction that has been used up should then not be saved in NPC::Save, as opposed to the current behavior of deleting the MissionAction immediately after use. Not saving the NPCAction prevents it from retriggering after a save is reloaded without needing extra keywords, just to keep things simple for now. New functionality specific to NPCAction can come later.

**Comment by UnorderedSigh** [comment]
Regardless of how NPC actions are managed, maintaining a `const Conversation &` is *awful* software design. It's extremely error-prone, as this bug has just demonstrated. It needs to be changed to a `Conversation`.

**Comment by UnorderedSigh** [comment]
Actually, your suggestion to solve this by adding another class that manages Conversations, will only make the problem worse. I fear I may have misguided you by suggesting there is a situation where `const &` members are a good idea.

Anywhere the code creates a Conversation object, that is another opportunity for a `const Conversation &` to become invalid later on. There is *no way at all* to automatically check whether `const &` are handled correctly in the code. Managed pointers, or member objects, don't have that problem. Adding more classes that pass Conversations around just increases the chances that we'll make mistakes. It has to be a member object or managed pointer.

I'm going to ping @quyykk and @tehhowch hoping one of them will back me on this very basic aspect of C++ software architecture.

**Comment by UnorderedSigh** [comment]
User: *The game keeps crashing.*
Developer: *It's because of this error-prone C++ language feature whose continued use will strain reviewer resources. We can fix it with a two-line change.*
Project Lead: *Let's spend a few weeks implementing new capabilities instead!*

**Comment by quyykk** [comment]
superseded by #8881

**Comment by UnorderedSigh** [comment]
> superseded by https://github.com/endless-sky/endless-sky/pull/8881

No, that PR does not solve the problem. It prevents the crash, but the underlying reason for the crash is still present: an unsafe reference. Unless the unsafe `const X &` members are removed, this will just keep happening again.

**Pull request closed without merging**
