### PR TITLE
Better differentiate various human medium warships and knock the Mule down a peg

### PR DESCRIPTION
**Pull request by Amazinite**
## Summary
The Mule has been a topic of discussion for some time, as well as the balance between the various human medium warships. (Ref: #4579,  #1598/https://github.com/endless-sky/endless-sky/commit/ece73dc9cab663bf02f15d048b7252469cc65672, #1626, #1627, #3411, #2076) This PR seeks to knock the Mule down a bit, but in lowering the effectiveness of the Mule, I felt that I was making it too similar to some of the other human medium warships, so I made some slight tweaks to other medium warships as well. These tweaks also help to differentiate the various roles that the medium warships are suppose to fulfill. 

These are the roles that I see each medium warship filling:
* **Cheap but Effective**: Splinter, Manta
* **Dedicated Carrier**: Nest, Roost, Skein
* **Combat Carrier**: Aerie
* **Jack of All Trades**: Mule
* **Tank**: Bastion
* **General Combat**: Firebird
* **Speedy Combat**: Osprey
* **Speed Demon**: Corvette
* **Best in Combat**: Frigate

For the most part, these ships fit their roles well. But, the Mule was notably a master of all trades more than a jack of all trades. As such, it has received the bulk of the changes.
<details><summary>Mule changes</summary>

The Mule has...
* the most weapon space among all medium warships (210 vs 180 Bastion and Osprey next closest).
* the most cargo among all medium warships by more than double the next closest (270 vs 120 Skein).
* a greater cargo space than all light freighters (270 vs 150 Freighter) and more cargo than the Hauler II, a heavy freighter (270 vs 260).
* the second highest outfit space (450 tied with Osprey vs 470 Bastion in first place).
* the highest spare bunk space (37 tied with Frigate vs 24 Corvette next closest).
* the second lowest crew requirement (6 tied with Roost vs 5 Nest at the lowest).
* the second highest HP when ignoring licensed ships (9,800 vs 10,900 Bastion in first).
* the only real downside is its lower speed.

With all this in mind, I wanted to make changes to make the Mule less of a master of all trades, but I wanted to be less drastic than #2076.
* Left the engine space and drag as is as the speed isn't something of note.
* Decreased the weapon space from 210 to ~~180~~ 170 so that the Mule still has a high weapon space, but not the most by a substantial amount. 
   * The single fighter bay can partially be seen as +20 weapon space, so the previous 210 weapon space plus the single fighter made the Mule a no brainer in terms of combat for medium warships.
* Decreased the cargo space from 270 to ~~200~~ 170, meaning that the Mule's cargo is now at a midpoint between light and heavy freighters instead of being within the range of heavy freighter cargo space.
* Decreased the cost by 500k since the previous cost increase was done in part due to the similar cargo space to the Hauler II.
* Decreased the outfit space from 450 to 440 to differentiate it from the Osprey. Nothing an outfits expansion can't fix.
* Increased the required crew count from an astonishingly low 6 to ~~22~~ (edit) ~~17~~ 14.
* Added a sentence to the end of the description noting that the required crew is a downside for the ship, and that it's only a jack of all trades and not a master of all.

</details>

Moving on to the Bastion, I had the feeling that it was just a worse version of the Osprey. Same weapon space, similar outfit and engine space, similar gun and turret numbers, but about 24% more health at the cost of about half the speed. The only real positives of the Bastion over the Osprey are being cheaper and having more cargo. As such, I decided to make some changes to push the Bastion a little more into its tank role.

<details><summary>Bastion changes</summary>

* Increased the shields from 6700 to 7500.
* Increased the hull from 4200 to 4700.
  * These changes push the Bastion further into its tank role by giving it a significantly higher health pool than the next closest ship (1700 point difference compared to the previous 400 point difference with the Frigate), and it now has about 39% more health than the Osprey instead of about 24%.
* Increased the weapon space from 180 to 190 to differentiate its weapon space from the Osprey and Mule, as well as push it a little further into a tank role with space for the biggest guns among medium warships.
* Increased the cost slightly to compensate for the increased combat effectiveness.
* Made no changes to the engine space and drag since it's already a very slow ship.
* (edit) ~~Reduced the required crew from a comparatively high 17 to 14, only 4 more than the Osprey's 10.~~ Left the Bastion's crew requirement as is, as the Bastion is now the closest thing to a heavy warship without being one.
</details>

The Osprey is an interesting ship that fits its role well, but I decided to make some slight changes to it still.

<details><summary>Osprey changes</summary>

* Reduced the cost slightly to make it a more appealing choice. The sale cost of the Osprey is still the greatest among the medium warships by quite a bit, but it's just ever slightly less expensive.
* Reduced the drag slightly given that despite the description as an agile ship, I got the sense that the drag was a little high.

</details>

Beyond these three ships, I think that everything else in the medium warship category is largely fine, save for perhaps the Splinter. 
* The Nest, Roost, and Skein are fine as is, given they excel at their dedicated carrier role.
* The Firebird and Corvette already received some changes in #3411, and I think that they're great as is.
* The Manta with its 6 gun ports works amazingly as a missile platform now, so it needs no changes.
* The Aerie works amazingly as a combat carrier; a ship designed to carry a small number of fighters but also get involved in the combat on its own. As a side note, the fact that we're missing this archetype of ship at higher tiers is a little saddening. (Although the Pond Strider and [Ibis](https://github.com/endless-sky/endless-sky/pull/4546/files) look to fill this role.)
* The Frigate already fits well within the Navy fleets, and fits its combat role well; it has the second highest HP among medium warships paired with a balanced speed and weapon space.

## PR Checklist: questions that need answered
 - [x] Make changes to the Splinter? VERDICT: It's fine as-is.
The Splinter is personally my least used medium warship, and I don't hear good things from others either. The Splinter is still an interesting ship, though, being the cheapest and second fastest medium warship. It's essentially a downgraded version of the Corvette, which may mean that it's fine as is.
 - [x] Lower Bastion required crew? VERDICT: No. The Bastion is now the closest MW to a HW, so it should have the highest crew requirement.
I think that the crew requirement on the Bastion was rather unjustifiable before, which is partially why I looked to increase the effectiveness of the Bastion slightly. The Bastion now fills the same role for medium warships that the Modified Argosy does for light warships; that is, it get very close to the edge of the next category up, but isn't quite there. But, is the required crew still too high, or do these changes make the required crew fine now?
 - [x] Lower Mule required crew from the increased value? VERDICT: Lowered from 22 to 14.
An increase from 6 (which was admittedly way too low before) to 22 might be a bit much. Should the required crew be brought down a bit from here? For reference, the Vanguard has the lowest crew requirement among the heavy warships at 23.

## Additional Notes

Further justification for each change can be found in the description of each of the commits where the change was made.

Despite my mention of #2076, I have no intention to make any changes to the Bactrian. I feel that #2184 and #3120 were all that was necessary for balancing the Bactrian.

Given that @Pointedstick mentioned that #1598 wasn't actually addressed when it was closed, and since he's opened many of the issues that I mentioned about the differentiation between the medium warships, I'd like to see what he thinks about the changes here.

Given that @Zitchas has opened a PR in the past with regards to the categorization of the Mule, I'd like to see what he thinks about the Mule's place now.

Changes have been made in the past to various interceptors and light warships, and the heavy warships have always been pretty distinct from one another, so I don't see a need to do any similar balance passes on the other categories of human combat ships. The only change I can think about needing done is swapping the crew requirements of the Quicksilver and Headhunter.

### CODE REVIEW

**Comment by Nescio0** [comment]
Personally I'm still in favour of removing one gun port from the Mule (from two to one), as suggested earlier (https://github.com/endless-sky/endless-sky/pull/4369#issuecomment-504736381). And maybe lower the Mule's and Bastion's shields but increase their hull, to reflect the fact they're freighters-turned-warships.

**Comment by Amazinite** [comment]
>Personally I'm still in favour of removing one gun port from the Mule

I don't really see that as necessary.

>And maybe lower the Mule's and Bastion's shields but increase their hull, to reflect the fact they're freighters-turned-warships.

The Mule's shield/hull ratio already about matches the Behemoth, and the Bastion's matches the Argosy.

**Comment by Naminson** [comment]
I'm not an expert on ship balancing, so I'm not able to give amazing feedback, but I did do one 200k bounty in each of them. This is just for single ship combat, which is completely different than fleet combat. Also important to mention I didn't use missiles on any of these ships, since I don't really like using them.

Bastion: Tested on a laser Protector. I know there was a concern that the bastion would overpowered now, so I think everyone will be happy to know that Jimothy absolutely wiped the floor with my bastion as long as I didn't kite him. This just makes it more competitive with the Mule, and more viable in FWC, which is a plus to me.


Mule: Tested on a Laser Bastion. I did end up having to decide whether to prioritize weapons or shields. It's worth mentioning it had an acceleration of about 225, and a top speed of 500, which was near my osprey's speed. I don't know if the osprey is slow or the mule is fast. Otherwise, there are better options for every style of combat, although it makes money much faster than any other medium.


Osprey: Tested on a stock manta and laser protector (I think). It's as good as I remember. For the most part, in a single ship fight maximum speed only matters if it's higher than the other ship's, so it's not a massive change in this context.

**Comment by Pointedstick** [comment]
In general I approve but don't feel like the changes to the mule are bold enough to accomplish the goal of making it not a no-brainer. :) In my mind the main problem is its high potential armament and total hull+shield values. With this PR, it's still possible to stuff a Mule with three Proton Turrets, a HAMT, and four Meteor Missile launchers. Plus a carried fighter has room for more missile launchers. That's some pretty deadly firepower in a ship that still has 200 tons of cargo space. I think it's still too much of a no-brainer.

My preference would be to additionally see one or more of the following:
- Remove the fighter bay
- Reduce the shields a bit
- Reduce the number of gunports or turret mounts by 1
- Reduce the cargo space to 100 tons or less

BTW I'm somewhat partial to the Splinter myself because it's cheap enough to acquire pretty quickly but has 3 turret mounts and a large-ish cargo area. IMO these two factors are some of the most important ones for the player's overall effectiveness in the early to mid game which is why the Mule is so good; it's got large amounts of both but doesn't cost all that much money.

**Comment by Amazinite** [comment]
>and four Meteor Missile launchers
>...
>Reduce the number of gunports or turret mounts by 1

How'd you fit in more launchers than gun ports?

>Remove the fighter bay

Given the small number of human ships capable of carrying fighters in the first place, I'm not too keen on removing the fighter bay.

>Reduce the shields a bit

The Mule's HP isn't exactly all that high to begin with. The Bastion, Skein, and Frigate all have more HP, and the Mule's HP is only about 6% greater than the Firebird's.

>Reduce the cargo space to 100 tons or less

Right now the cargo space is the only outstanding factor about the Mule among the medium warships, as there are other warships with more weapon space (after this change, that is), more fighters, more health, more speed, and more outfit space. I don't see such a drastic change, making it 3rd in cargo space among MWs, as being beneficial, especially because at that point you're basically making the Bastion the next Mule.

**Comment by Pointedstick** [comment]
> How'd you fit in more launchers than gun ports?

Oops, my bad, please disregard my ramblings!

> The Mule's HP isn't exactly all that high to begin with. The Bastion, Skein, and Frigate all have more HP, and the Mule's HP is only about 6% greater than the Firebird's.

The Frigate isn't available to the player during normal course of play so I don't think we should directly compare the two. The Skein is an unappealing ship due to its extremely poor speed and micromanagement-intensive play requirements.

> Right now the cargo space is the only outstanding factor about the Mule among the medium warships

There's one more thing: it's the only human medium warship that has four turret mounts and isn't slow as sin. Maybe I'm just a sucker for turrets, but this is a huge deal to me when I choose ships.

**Comment by Amazinite** [comment]
>Maybe I'm just a sucker for turrets, but this is a huge deal to me when I choose ships.

Funny, since your changes to missile launchers has made me love ships with more guns. :)

**Comment by Pointedstick** [comment]
Hah! What I'm enjoying nowadays is one of the following for a capital ship:
- A primary armament of large powerful missile launchers with a defensive armament of 1-2 anti-missile turrets, and the balance being something fast-turning for anti-fighter action (i.e. modern missile cruiser in space)
- All heavy turrets (i.e. WW2 battleship in space)

What's great about a Mule is that it lets you do either of these things, which makes it consistently punch above its classification as a medium warship IMO.

**Comment by Amazinite** [comment]
In #2076 I sought to take the Mule's cargo down to 150. While I now think that was a little low, I do think that something between 150 and 200 is reasonable, since that's still above any MW by a fair amount and above any light freighter. How does 170 sound?

As for the other changes, I don't see them as all that necessary or helpful.

**Comment by Pointedstick** [comment]
All right. How about also reducing the weapon space by another 10 tons then?

**Comment by Amazinite** [comment]
Feels a bit harsh going from 210 to 170, but I think it's reasonable.

**Comment by Amazinite** [comment]
With the further reduction in mass and cargo, I think the required crew of 17 is now a tad high. How about 14, and lower the Bastion to 12 so that they don't tie? Or maybe the Bastion and Mule should swap places from where they are now. (i.e. the Bastion would then remained unchanged from the master, and the Mule's required crew would be going from 6 to 14).

**Comment by Amazinite** [comment]
Made the swap. The Bastion is the closest medium warship to being a heavy warship after these changes, so it makes sense for it to have a high required crew. The Mule now has the second highest required crew with these changes, instead of having the second *least* required crew.

**Pull request merged**
