### PR TITLE
FW continuity fix

### PR DESCRIPTION
**Pull request by jafdy**
Continuation of #966.
Hopefully I wont brake this one.

### CODE REVIEW

**Comment by jafdy** [comment]
FW senate 1B now works.
Having trouble testing the andersons part of the pull.

**Comment by endless-sky** [comment]
The "goto" needs to be indented one more level.

Also, there's no "Jump drive" condition, so that won't work. (And, you'd need a space between the >= and the 0 anyway.)

**Comment by LocalGod79** [comment]
@jafdy use the jump drive missions in the reconciliation plot as your guide to outfit based mission restrictions.

**Comment by jafdy** [comment]
@LocalGod79 I was hoping to avoid that clunky method.
@endless-sky Sorted the "goto" the branch isn't working still. Also could you make Outfits a condition?

**Comment by LocalGod79** [comment]
so have we all...

probably including M.Z. at the time he wrote the mission referenced.  i imagine that it's more difficult than one might immediately assume.

**Comment by endless-sky** [comment]
If you take the player's hyperdrive out and put it back in, they'll get messages informing them of that, and be really confused.

In this particular case, i really don't think it's worth it just to cover the unusual case where the player has a jump drive. It'd be easier to just change the text to something like, "You consider trying to explain to her that Bourne is seven jumps away..."

Also, I'm not sure if it should be "a couple... which," or "a couple... whom." That sentence confused me the first time I read it. Maybe something simpler like, "... a man and woman are with him. He introduces them as ..."

**Comment by jafdy** [comment]
Tested the jump and hyper drive versions of senate 1B. follow on missions are working fine.

**Comment by jafdy** [comment]
Is the outfit removal/addition messages a change to application code since 0.8.11?

**Comment by jafdy** [comment]
image
It looks like the branch is if true and if false options are both being directed to the first option. If I edit the save file to `branch 2` instead of `branch 1 1` it works as intended.

**Comment by jafdy** [comment]
Its ready to merge now.
@endless-sky I can remove the FW senate part if you want but I would rather have a `has "Jump Drive"` condition or something like that so that it can be done.

**Comment by jafdy** [comment]
I have reverted the FW senate 1B changes. @endless-sky could you merge or close this.

**Pull request merged**
