### PR TITLE
Travel changes

### PR DESCRIPTION
**Pull request by Isaacssv552**
I've added fully functional variable drive fuel consumption. Has been tested and functions properly with both solo and fleet jumps.

I plan to work on adding some sort of multi-jump functionality ala the multi organ from EVN. I also intend to double check the route plotter to make sure it uses modded fuel values properly when optimizing for fuel usage. Currently a hyperdrive takes precedence over jump drive even if the jump drive has a lower fuel consumption.

EDIT: Both of these are done.

### CODE REVIEW

**Comment by Isaacssv552** [comment]
For some reason the indentation that shows up in github is different than the indentation that shows up in XCode.

**Comment by endless-sky** [comment]
It looks like you're indenting with [spaces instead of tabs](http://endless-sky.github.io/styleguide/styleguide.xml#Formatting).

**Comment by Isaacssv552** [comment]
The issue should be solved, I had indentation set to "prefer spaces".

**Comment by endless-sky** [comment]
This would make it so that if you had two hyperdrives of the same sort (say, two scram drives to allow you to jump at even higher speeds) the fuel cost would double.

Also, have a look at the rest of the [style guide](http://endless-sky.github.io/styleguide/styleguide.xml) and try to match your formatting to the existing code (in particular, spaces before and after the ternary operator and brackets on their own line).

**Comment by Isaacssv552** [comment]
I believe the issues should be resolved.

**Comment by Elyssaen** [comment]
I notice the comment on DistanceMap::Cost still refers to jumps as always costing 2. I haven't checked your code yet, but do you know if Cost functions correctly, and if so should the comment be updated too?

**Comment by Isaacssv552** [comment]
I've changed the calculation so it will use the actual value, but I can't test it because I'm getting a bunch of errors when compiling the latest release.

**Comment by Elyssaen** [comment]
It's not a "clean the project to delete the old object files" sort of issue, is it?

**Comment by Isaacssv552** [comment]
I don't think so, I have the same issue on my "clean slate" master branch.

**Comment by Isaacssv552** [comment]
I've made it add 1 for the less expensive of hyper/jump and 2 for the more expensive because the original calculation used either 1 or 2 regardless of whether the scram drive might be changing the relative cost of a hyperdrive jump. Adding the exact fuel value would be more precision than originally used.

**Comment by endless-sky** [comment]
Closing because I've added an alternative implementation of this (ebb46d8).

**Comment by Elyssaen** [comment]
@Isaacssv552, please-please-please repost (maybe as an issue first) the multi-jump stuff, though!

**Comment by Isaacssv552** [comment]
@Elyssaen, testing it now.

**Pull request closed without merging**
