### PR TITLE
Introduce "Rainmaker (Javelin)" variant

### PR DESCRIPTION
**Pull request by Nescio0**
The Rainmaker's purpose, to my understanding, is to overwhelm the opponent's anti-missile systems with a barrage of missiles. The weapon most suitable for this is obviously the Javelin, which has a far lower reload time than any other missile weapon. Javelins also tend to inflict slightly more damage than Meteors or Sidewinders, have no homing and thus no annoying missile boat behaviour, and are less likely to be intercepted because of its relatively short range.
Besides, the missile pods on the Rainmaker's wings visually resemble javelin pods.

### CODE REVIEW

**Comment by tehhowch** [comment]
Note that the Mk I rainmaker's Energy Blasters mean that it also has no missile boat behavior.

I don't think wholly eliminating the use of Sidewinders from Rainmakers is appropriate.

**Comment by Pointedstick** [comment]
This change would alter their battle role substantially, transforming them into short-range brawlers rather than essentially space artillery.

**Comment by Amazinite** [comment]
I think a Javelin variant is fair to add, but to remove long range tracking missiles from all Rainmakers could very much change how battles against the Navy go. Javelins might be better at "overwhelm the opponent's anti-missile systems" on paper, but how good are they really when that means getting up close and personal with much larger ships, likely leading to the death of the Rainmaker and therefore the large ship no longer being distracted/overwhelmed by missiles.

**Comment by Amazinite** [comment]
Why does the Javelin variant have atomic engines but is seen in Navy fleets at the same time as the Mark I variant, which uses ion engines?

**Comment by Amazinite** [comment]
Why remove the radar jammer? And this thing has 50 tons of extra outfit space (without the radar jammer), so perhaps up the batteries and shields a bit so that this variant can survive better up close.
\+ Radar jammer
LP036a -> LP072a
D14-RN -> D41-HY

**Comment by Nescio0** [comment]
Replaced the engines with ions, replaced the D14 with a D41, and added a large radar jammer. 
Why the batteries? Javelin Pods hardly require energy.

**Comment by Pointedstick** [comment]
I don't think this is actively bad anymore, but I don't really see the point. As has been pointed out, the Navy already has a short-ranged brawler: the Gunboat. In a lot of ways it's better suited to that with its better shields. The Rainmaker seems to be designed in every way to be a flying howitzer, and I think it should stay that way.

Better luck next time. :)

**Pull request closed without merging**
