### PR TITLE
Add a "no hyperdrive" flight check.

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by tehhowch** [comment]
That's not quite true though - a ship can use a wormhole just fine without a Hyperdrive or jump drive (barring some caveats (currently))
Related https://github.com/endless-sky/endless-sky/issues/2936, https://github.com/endless-sky/endless-sky/issues/2937

Any plugin which doesn't rely on hyperspace for its civilization would trigger this warning display for every ship with no conceivable way to disable the warning except by giving ships hyperdrives.

**Comment by jafdy** [comment]
Isn't there a warning if you try to play a route without a drive that can handle it? (An interstellar route without wormholes in this case)

**Comment by jostephd** [comment]
The in-flight warning doesn't help when I remove the hyperdrive from an escort, park it, and unpark it the next day when the flagship at another system.

Wormholes could be supported by rephrasing the warning or disabling it when the system has a wormhole.

No idea how to support plugins that don't use hyperspace.

**Comment by mootootwo** [comment]
There are valid reasons to strip a hyperdrive out of a ship.  For example, to maximize space available when you have a job in the current system, or something to loot in the current system.  Or when stripping a hull for parking.

**Comment by jostephd** [comment]
I agree and that's why it's only a warning that doesn't block takeoff.

**Pull request merged**
