### PR TITLE
feat(content) Alternative Galaxy Sprite Overhaul

### PR DESCRIPTION
**Pull request by ravenshining**
----------------------
**Content (Artwork )**

## Summary

This is a rework of the galaxy sprite, similar to Azure's in #7175 , that I made much earlier.  I even got as far as making a branch, but never PR'd it due to a perceived lack of support for the concept from the community at the time.

The distorted galaxy currently in game is replaced with an image composed of:
 - M83, for the general appearance of a spiral galaxy
 - M96, a galaxy that happens to have a bizzare red arm for the ember wastes
 - some *other* galaxy whose designation I've forgotten at this point because I did this over a year ago
 - imagery generated by Celestia, for proper Milky Way structure,
 - the current galaxy, for stars and other features presently relevant to the game, especially coalition space
 - numerous edits by hand to remove obnoxious foreground stars, fade the border, and clean up in various spots such as clearly defining the borders around coalition space as negotiated with Arachi.

The sprite is oriented such that Sol is in its proper location, without having to change the location of as many systems as possible. Empty space is left around the core to make room for the Xapleaux and other core expansion in #6439 .  A handful of systems have been nudged eastward, and three of @MasterOfGrey 's Xapleaux systems -- all uninhabited -- have been added to provide a jump/hyper path to Sagittarius A*, which has been moved to the new centre of the galaxy.  Finally, the inaccessible systems of the Ember Wastes are moved south out of the clear area around the core.

## Save File
This save file can be used to explore the new sprite:
[explored.txt](https://github.com/endless-sky/endless-sky/files/9484818/explored.txt)

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] ~~I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets~~ Asset too big for me to add to the repo, here's a gdrive link instead: https://drive.google.com/file/d/1it7EG_tyX-R52XztWsn4BnlDQr5D0RB0/view?usp=sharing
(250MB 7zip, will update with final rendition of sprite if this PR is merged)

## Screenshots
Screenshot_20220905_014658
Screenshot_20220905_014629

### CODE REVIEW

**Comment by mOctave** [comment]
The new galaxy image looks really nice, but I'm slightly concerned by the fact that the shape of the galaxy has changed enough that systems from plugins that have been placed in specific places based on the features of the old galaxy may no longer be in the right place.

**Comment by AbsolutelyLudicrous** [comment]
It looks very different than the old, very blue, very dark except around the core, where it now looks very bright. The gaps between the arms are larger, which puts some systems well in the void between them; the Cognizance systems are now significantly closer to the core than the rest of the Waste.

I understand the hyperlink between Kor Ak'mari and Sag. A* being necessary to access it now, but I don't think it makes sense from a lore perspective; either an advanced civilization saw fit to give the Korath Exiles a path to Sag. A*, or it's a result of extensive jump drive traffic around the black hole. Similarly, we know that hyperlinks can be disrupted by gravitational waves - I imagine a black hole would certainly affect hyperspace travel.

Personally, I'm partial to #7175

**Comment by ravenshining** [comment]
> systems from plugins that have been placed in specific places based on the features of the old galaxy may no longer be in the right place.

The old galaxy sprite is a layer in this composite, more of it could be incorporated to be used for other content.  However, maintaining plugin compatibility is not a particular goal.

I have considered making the original galaxy sprite into a layerable transparent sprite that plugins could cut down and add overlay on top of this image, if that is more of a concern than finding new features.

> It looks very different than the old, very blue, very dark except around the core, where it now looks very bright. The gaps between the arms are larger, which puts some systems well in the void between them;

I can easily adjust things like the colour balance as the community desires.  The gaps between the arms are modelled after the gaps between arms in the real Milky Way.

> the Cognizance systems are now significantly closer to the core than the rest of the Waste.
> I understand the hyperlink between Kor Ak'mari and Sag. A* being necessary to access it now, but I don't think it makes sense from a lore perspective; either an advanced civilization saw fit to give the Korath Exiles a path to Sag. A*, or it's a result of extensive jump drive traffic around the black hole. Similarly, we know that hyperlinks can be disrupted by gravitational waves - I imagine a black hole would certainly affect hyperspace travel.
> 
> Personally, I'm partial to #7175

Unlike #7175, this sprite makes room for @MasterOfGrey 's Xapleaux faction in #6439 without having to radically reshape Korath and other core regions of space.  Once those systems are added - the uninhabited skeleton of which could be added in this PR if people like - there would be no need for the long hyperlink.

**Comment by MasterOfGrey** [comment]
I should note that I do believe the systems in and around the core *should* be reshaped as a game-design decision. Those areas are quite evidently the least developed parts of the game, and I think strictly adhering to or trying to preserve the existing elements as-is is something of a mistake.

Having said that - if the balance of argument comes down on the side of not reshaping things I have no particular issue with an approach like this.

**Comment by ravenshining** [comment]
I don't myself *particularly* want to preserve the absolute shape of thing, but I avoided it here just on a "least amount of changes to get this PR's job done" principle.  I agree with your desire to populate and condense the area, but I think the way it's handled in #6439 goes too far, completely rearranging the paths through and importance of systems in Korath space, giving the visual of crowded space at the cost of gameplay.

**Comment by quyykk** [comment]
Neat! Although there's still the issue that the system names are barely visible near the center:

image

**Comment by ravenshining** [comment]
I tried toning down the structure and reducing highlights and saturation to make this...  and whether or not y'all think it's better than the above, I'm glad I did because as it turns out after 15 months of the XCF sitting on my hard disk it turns out I never saved the final edge blackening layer :-P

But also yeah, I know you wanted the XCF, Quikk, but as you can see above it's 250 MB 7zipped!  Had to have the working image be 16 bits per channel for smooth fades.

Screenshot_20220904_200342
Screenshot_20220904_200454

**Comment by ravenshining** [comment]
I've copied in three of @MasterOfGrey 's uninhabited systems from #6439 to provide a more sensible hyper/jump path from Kor Ak'Mari to Sagittarius A*.  It's tempting to add the rest, but I wouldn't want to steal Grey's thunder :-)  And, without a viable map editor, positioning that many systems is a heck of a task.

Top post updated with fresh screenshots.

**Comment by MasterOfGrey** [comment]
> And, without a viable map editor, positioning that many systems is a heck of a task.

It is indeed a mighty headache.

**Comment by AbsolutelyLudicrous** [comment]
It looks better now, but still imho more blue than milky - at least, from the zoomed out view; the zoomed in view is less noticeable. Maybe up the red channel a bit? Could also just be the white stars mixing more with the black space between the arms - the old galaxy had a *lot* less define arms.

Out of the scope of this PR, but it would be great if we could shuffle around just about every system to have them fit better into the arms. It would also be great if, as mentioned above, we had a better map editor, but alas.

More lore stuff: Sheratan is now a lot further away from Sag. A*; Previously it was almost touching the globular core, now it has an arm and a half between it and the core. I would argue it should be bumped in a bit to accommodate the black hole observatory there.

**Comment by ravenshining** [comment]
> It looks better now, but still imho more blue than milky - at least, from the zoomed out view; the zoomed in view is less noticeable. Maybe up the red channel a bit?

Well, if I up the red channel or desaturate, that makes hyperlinks and the Ember Wastes less visible, which isn't ideal for gameplay.

Besides, when I look up at the Milky Way at night, it looks blueish to me.

> Could also just be the white stars mixing more with the black space between the arms - the old galaxy had a _lot_ less define arms.

Yes, correcting the number and distribution of arms is a major goal of this sprite, and perhaps the most significant issue I have with Azure's galaxy sprite.

>  it would be great if we could shuffle around just about every system to have them fit better into the arms.

Why should they do that?  They already fit the stars imported from the old galaxy sprite, rearranging systems to fit arms instead would require abandoning that feature.

> Sheratan is now a lot further away from Sag. A*; Previously it was almost touching the globular core, now it has an arm and a half between it and the core. I would argue it should be bumped in a bit to accommodate the black hole observatory there

It's still the closest human system to it.  With Grey's additional systems added to Syndicate space, it could be pushed slightly closer, though.

**Comment by leklachu** [comment]
> >  it would be great if we could shuffle around just about every system to have them fit better into the arms.

> Why should they do that? They already fit the stars imported from the old galaxy sprite, rearranging systems to fit arms instead would require abandoning that feature.

I think because the new image is brighter, the new structure sometimes drowns out the old structure. Most noticeably the Deep, which now looks like it an Mebusta sit on either side of what should be an arm.

Overall, I think some aspects of this new background+map are really cool, some feel a step down, and some I've got personal opinions on either way that probably don't really matter.

Having pondered this for a bit, I like that Sag A* is further away, if that region of space is kept reasonably clear of other civilization. I like the feel that the black hole is something you have to journey far, through much nothingness, to get to. (Especially on that Remnant mission to go and see it.) More subjectively I also like the lack of a bright spot in its place (compared to #7175) because in that version, zooming in, the bright spot is ever so slightly offset from the system marker!

I'm not an immediate fan of the bead-structure of the arms. But biggest I feel is that the structure in used-space doesn't fit the map as well as it used to.

So as things stand, I prefer #7175, and I think this alternative should only be merged if there's an agreement on the rework of the map itself, not just the galaxy sprite.

**Comment by Zireael07** [comment]
> I like that Sag A* is further away, if that region of space is kept reasonably clear of other civilization.

I like the far away bit too, but note that IRL the region of space is unimaginably dense, lots of stars in the core, I could imagine some civilization setting up shop there.

**Comment by leklachu** [comment]
>  IRL the region of space is unimaginably dense, lots of stars in the core

Fair enough then. I'm definitely a fan of structuring things based on IRL as much as possible. Maybe that's a solution to the extra planned civilization between Korath and Core (IIRC?) if the map/hole isn't shifted: run a bunch of systems very close to each other, if being able to jump across many systems in one jump doesn't matter.

I wonder if there's any IRL effect on expected distribution of possibly-habitable planets. Not that the Korath need them anyway with their worldships.

**Comment by RisingLeaf** [comment]
I need to ask this:
We obviously have two map sprite PR's. One needs to go. I dont say this one. But it should probably be discussed.

**Comment by ravenshining** [comment]
Ah.  Well, I was waiting to hear back from Azure about possibly working together, and got working on other things in the meantime.  But, that was over a month ago, and I've just recently heard through the grapevine that unfortunately, that may not be happening for some reason.

So, I guess I'm on my own.  I'd like to publish my Korath lore doc before updating this PR with more systems and using some different imagery, but I'm almost done with that.

**Comment by Amazinite** [comment]
Closing in favor of #7175.

**Pull request closed without merging**
