### PR TITLE
Add remodel of the Flivver

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds fully remodelled sprites for the Flivver.

flivver

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/68
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/282

### CODE REVIEW

**Review by roadrunner56 — APPROVED** [review]
I like this remodel. The cockpit and layout of the ship actually makes sense now.

**Comment by Zitchas** [comment]
Overall looks nice, I think. My one quibble is that now a bunch of the color has been hidden away, making it less colorful, greyer, and less to change when swizzled. Having a bit more color visible somewhere, anywhere, would be much appreciated.

I do like the more streamlined design, though. It looks more like a racer now.

**Comment by ravenshining** [comment]
Worst thing is that it's all narrow now.  We need more wide ships.
Seems to have gone from a cool variable wing geometry to a boring old fixed wing
Also it seems to be lacking in contrast and, as Zitchas pointed out, colour

**Comment by Hurleveur** [comment]
I don't think this particular ship should be too wide, as its pretty much just a racer, and now it actually looks like one which I kinda like.

**Comment by Zitchas** [comment]
Ravenshining's got a good point, though. Everything seems to go long and narrow. I, too, generally interpreted its wing configuration as a variable wing geometry - aka meaning it could be wide for landing and acrobatics, while pointy for racing. I still interpret this ship being that way, except in the racing configuration now.

**Comment by warp-core** [comment]
Would there be interest in the option to have the wings move between the old and new positions based on speed (instead of just moving backwards and forwards all the time, which is all the game can currently do if the sprites are provided)?
Aerodynamically, it'd be totally meaningless since it'd be in space, but it'd probably look really cool.

**Comment by GefullteTaubenbrust2** [comment]
> Would there be interest in the option to have the wings move between the old and new positions based on speed (instead of just moving backwards and forwards all the time, which is all the game can currently do if the sprites are provided)?
> Aerodynamically, it'd be totally meaningless since it'd be in space, but it'd probably look really cool.

That would indeed be immensely cool. Someone proposed having different variants instead over on the discord, although thinking about it a bit I‘m not sure how much sense that would make. In either case, I could certainly do that on the graphics side.

**Review by beccabunny — APPROVED** [review]
Love the new sprite, the only thing that could improve it at this point would be @warp-core 's idea (but imo that's best left for later as it's code changes)

**Comment by Zitchas** [comment]
Have you tried making those two darker grey panels on either side colored? Those look like good candidates to bring some more color into things.

**Comment by ravenshining** [comment]
> Would there be interest in the option to have the wings move between the old and new positions based on speed (instead of just moving backwards and forwards all the time, which is all the game can currently do if the sprites are provided)? Aerodynamically, it'd be totally meaningless since it'd be in space, but it'd probably look really cool.

That would be very cool, yes.  Such an animation could be useful for things like Void Sprites, too

More realistic for the Flivver would be to have a launching animation - have it start out folded like this remodel while it's exiting the atmosphere, and expand to the old model for spaceflight.

**Comment by Hurleveur** [comment]
Currently the only animation we can do is one that happens all the time, unfortunately.

**Comment by Saugia** [comment]
My comments from Discord:

*For me, I personally don't like the slanted wing look. I much more prefer the straighter wings and the oddness of them being separate from the body (but of course preferably with some sort of attachment) and I also like the higher angled tail fins, although I do think making them shorter than the wings was a good idea. I also prefer the odd nub for a cockpit than something more fighter-jet like. I don't know, to me it seems making all 4 wings slanted + the new cockpit turned it into looking like another interceptor based on a fighter jet design rather than an odd but iconic looking personal ship.*

*The new design is trying to "modernize" it by making it more slanted winged and more V-shaped, which I don't feel fits a personal iconic speedy ship, I feel the new design is militarizing it too much, and that the old design reminds me of interesting and unique plane shapes that we try to make outside of military fighters
It doesn't have to be exactly the old one, I'm just not a huge fan of the stealth plane-esq cockpit for this ship in particular
I liked the rounder bulkier/small appendage look of it.*

**Comment by Hurleveur** [comment]
Previously there wasnt a real cockpit, it was just a gun and the part linking the two sides of the ship (though I guess someone could fit in there, but there wasnt any glass)

**Comment by ravenshining** [comment]
The cockpit in the original looks pretty darn obvious to me, glass and all

**Review by Saugia — APPROVED** [review]
Looking at the changes based on discord feedback, I much like where the design has gone now. It is a lot more faithful to the original, looks less "swept-jet-ified" and now retains more of that iconic look, all while being an overall visual improvement. Nice.

**Review by Hurleveur — APPROVED** [review]
Definitely an improvement that this ship finally gets a proper cockpit, and some additional depth.
Nice job!

**Review by ravenshining — APPROVED** [review]
*Much* better.  Glad we got that iconic "luxury yacht" look rather than the "stealth fighter."  I do stand by my suggestion that if we ever do get launching animations though, that first revision would be great for landing and takeoff.

I might still like the old one more, sure, but that's only because I don't like the direction human things have gone in general.  Where you've taken this now is better for the game as a whole, to fit in with that human aesthetic so those who like it may be appeased and those of us who are aliens can have our fun :-)

**Pull request merged**
