### PR TITLE
feat(UI): Movable Shift Panel

### PR DESCRIPTION
**Pull request by Zitchas**
**Feature:**
Every time something is added or moved in the key bindings panel, we generally need to either contort definitions to keep the shift-altered values aligned, or we need to redraw the key panel image, which is problematic as parts of it we don't have original files for. This adds a lot of overhead work to adjusting the keybindings.

## Feature Details
This splits the Key Panel into "Key Panel" and "Shift Panel" and adds the appropriate reference to interfaces.txt. As such, whenever the key bindings are changed or adjusted, one merely has to adjust the location of the shift panel up or down appropriately.

## UI Screenshots
There should be no visible change to the user.

## Usage Examples
N/A

## Testing Done
Played the game, checked the key binding menu, tried altering values in interfaces.txt and noted that the shift panel moves accordingly.

### Automated Tests Added
N/A}

## Performance Impact
"N/A"

### CODE REVIEW

**Comment by warp-core** [comment]
High DPI and assets?

**Comment by Zitchas** [comment]
Quite literally just the old sprite split in two, and extra shading added to the key panel so that regardless of how the shift panel is moved, it will always be shaded.

**Comment by warp-core** [comment]
> Quite literally just the old sprite split in two, and extra shading added to the key panel so that regardless of how the shift panel is moved, it will always be shaded.

Still need high DPI, and assets if you've changed the sprites (not having up to date assets to work from has been a significant problem for other people relatively recently.)

This is how it looks without updating the high DPI plugin:

image

Your shift panel also looks rather fuzzy:

existing | this PR
-- | --
image | image

And note that this is not comparing your standard DPI sprite to the existing high DPI one; the high DPI plugin was not loaded in either of those cases.
This is what the high DPI currently looks like:

image

**Comment by Zitchas** [comment]
Yes, what passes for "assets" for these is woefully lacking and a real pain to deal with. I heartfelt want to banish every and all .xcf file into the abyss. Post processing is terrible for repeatability. As in not being able to.

**Comment by Zitchas** [comment]
GIMP is great for lots of things. I use GIMP regularly. But creating easily modifiable interface elements is *not* something it is good at unless someone spends the time to set it up for that properly. And no-one has here.

Either way, I'll have replacement images eventually. And usable assets.

**Comment by Amazinite** [comment]
Closing in favor of #9360/#9406, which move all shift modifier information into the tooltips and uses the shift panel to instead display extra info about binding controls (and doesn't need to move based on where the different controls are).

**Comment by Zitchas** [comment]
Sounds good to me. I'll revive this if those fail to happen, but in the meantime, sounds good.

**Pull request closed without merging**
