### PR TITLE
Move the "Deep Space" systems from Hai Reveal away from the Coalition

### PR DESCRIPTION
**Pull request by Quantumshark**
## Summary
Moves the "Deep Space" systems (and Devil-Hide) from their location near Coalition space to a new location north of the wanderers, as requested by Arachi on the discord.
Capture

New location
image

### CODE REVIEW

**Review by Arachi-Lover — APPROVED** [review]

**Comment by warp-core** [comment]
There is at least one person who wants to put stuff to the north of the Wanderers.

Why can't these systems just go 3 or 5 or 10 thousand pixels away?

**Comment by Saugia** [comment]
If you're talking about Zoura, plans have changed to move them to the south east of the galaxy. We really shouldn't be putting things past the Wanderers.

**Comment by Saugia** [comment]
As per my post on discord:

image

If we take a look at the galaxy's overall image, This is something with what we get. The current alienish areas (oranges) and future possibilities (blues) are the more late game and alienated content. The old HR spot at least had some sort of visual flow with the galaxy, but didn't make sense that it was by the coalition. It basically cut through it, and by doing so, basically puts the coalition as a whole a bit less dynamic within the game flow as now you have something even beyond the alien coalition, before even meeting them. 

Moving it past the Wanderers does the same thing. In game, a new player comes across the Wanderers as these far off quiet aliens in their distant northern territory. If we are to put HR systems cutting through beyond that, in which these systems have massive plot action etc., it will severely downplay the quietness and, so to speak, "beyond-ness" that the Wanderers represent as an initial encounter. (Note, I am not talking about anything with the Wanderers moving.) This essentially breaks the linear progression of the stories, showing that the dense action and plot relevance in those HR systems is much beyond and earlier than that of the Wanderers. 

It would be better to place them off the sides as I've demonstrated in the green, as then they don't really cut through any factions like the Wanderers. Yes, it still cuts through humans, but this is later in the human story, Yes, it's through the Hai, but that's fitting since they're related. They shouldn't be stressing the beyond north of the Wanderers because that will put more visual and conceptual focus on that, and downplay the wanderers' place in the galaxy. It would also possibly lead players to believe there are other such cases beyond other alien races, which also further takes away from them being alienated as it will suggest something even more alienated is beyond them. 

With that said, I also think the system density could be lowered a bit for HR systems. Either a few less systems, or the systems not being that far apart from one another (I'm mostly talking about the tail end). I understand the idea that that much farther from the center of the galaxy typically means longer hyperspace lanes, but it seems too much at the moment.

**Comment by UnorderedSigh** [comment]
The west green area is a good spot, but there's three major problems.

1. It's way too small. The Whispering Void is supposed to be in intergalactic space, not *just* far out, and the stars are very sparse that far (Devil Hide doesn't even have a star; it has a rogue planet). 
2. Also on the matter of too small, it should feel like a long journey, not a short hop, so it must be long and sparse. You shouldn't be able to get through it in 2-3 Jump Drive jumps. It should be 6, minimum.
3. Devil-Hide is way too far out; it should be even closer to the galaxy than it is now. This is clear from the Devil-Eye image.

The map below has three advantages:

1. The inhabited system isn't too far out, so this isn't a "race beyond the Wanderers"
2. It's quite long, so you won't get through in a few jump drive jumps.
3. There's room for you to add more stars (if you wish).
4. The Devil-Hide is close enough to the galaxy to appear to be almost a part of it, while still being visibly outside of it (more or less). 

green-blob

**Comment by UnorderedSigh** [comment]
If you're bothered by the purple line's location, there's nothing wrong with moving Devil-Run. To fit the story, it has to be unreachable by hyperdrive, must be near Syndicate space or near Freedom, and one jump from a pirate world. We'll need to change the smuggler arrival rates if you move it, but that's not a big deal.

**Comment by Saugia** [comment]
In general I don't want it to be crossing the Wanderer space as shown in this PR, or anywhere super far out/past an alien race. I do like the idea of putting the wormhole system closer to the Northern Pirates though, but as for placement of "deep space", the example you gave won't work because Derpy/MZ don't want anything near or touching The Deep space.

**Comment by UnorderedSigh** [comment]
How about somewhere to the south-east of the Remnant? The presence of a red wormhole would fit better with the region.

**Comment by Saugia** [comment]
I feel that'd be at least more appropriate for a "deep space" sort of content area, EW makes sense especially for the proto stars and the alien life. However you'd have to ask @Zitchas 's opinion, and I believe @Azure3141 has a future faction planned somewhere between the Coalition and Remnant space.

**Comment by UnorderedSigh** [comment]
> You'd also have to consider if using an EW wormhole, you'd need to introduce keystones as a plot element

It requires a keystone. There's already a rather long sequence of missions to learn about the keystones.

> I believe @Azure3141 has a future faction planned somewhere between the Coalition and Remnant space

If you avoid putting things anywhere there are future factions or plugins, then we won't ever have new content. The reason NV put the systems out that far is that every part of the galaxy has been claimed for possible future content.  I say we put it where it makes sense, and let hypothetical future content move to areas that aren't used, once that content moves from "hypothetical" to "planned for the next stable release."

**Comment by UnorderedSigh** [comment]
> I believe @Azure3141 has a future faction planned somewhere between the Coalition and Remnant space

There's already a faction between Remnant and Coalition space.  Do you mean south-east of Remnant space?  That is where I was suggesting.

**Comment by Saugia** [comment]
@UnorderedSigh This is the most up to date content map for the future. If you are talking about beyond Remnant to the southeast, you'd have to talk to @Karirawri who's Mata is located there.

content map

**Comment by UnorderedSigh** [comment]
From that map, I see why the area north-west of The Deep, Wanderers and Freedom, makes the most sense.

Either your current position (far far away) or the one I propose, should fit okay with the story as it is now, apart from the view of the sky from Devil-Eye. (Though, as someone pointed out, I put my Devil-Hide too close to The Deep.)

Of course, if @Azure3141 is rewriting the story, then there's no telling where it should be.

**Review by UnorderedSigh — APPROVED** [review]
This makes the critical change of moving away from Coalition space, and there's nothing wrong with this placement that isn't already wrong with the existing locations.

I'd like to point out a problem this change does not fix, in case @Quantumshark wants to fix it:

If you look at the night sky image from the rogue planet Devil-Eye, it appears to be closer to the Milky Way. Maybe I'm wrong; look at the image and judge it yourselves.

This isn't a big problem though, and it may be my imagination.

**Review by Hecter94 — APPROVED** [review]
The current location is completely unsuitable. The new location is more suitable. 
Let's not let some minor concerns about what the new location is block a good change.

**Comment by UnorderedSigh** [comment]
I'd like to second what @Arachi-Lover said, that this needs to be moved as soon as possible before its location gets incorporated into other stories or lore. Having it be "far far away in intergalactic space" is easier to manage than having it "just north of the Coalition." We don't need to rewrite parts of the Hai Reveal to justify this change either; it can go in as it is.

**Comment by Quantumshark** [comment]
It is apparently planned that no systems will be reachable by jump drive from the Deep, in which case outside jump drive distance north of the Deep would probably be the perfect place for this.

**Comment by UnorderedSigh** [comment]
> It is apparently planned that no systems will be reachable by jump drive from the Deep, in which case outside jump drive distance north of the Deep would probably be the perfect place for this.

Context for those who are unaware: the Whispering Void has to be unreachable by jump drive, and you need a keystone.

**Comment by Quantumshark** [comment]
image
what do people think about moving them here instead?

**Comment by UnorderedSigh** [comment]
I see no problem with it, but you should check with Amazinite on whether that fits the "nothing near the deep" parameters. (If you haven't already.)

**Comment by Quantumshark** [comment]
It is outside jump drive range from the deep, so it fits the "nothing near the deep" in that sense

**Comment by UnorderedSigh** [comment]
That spot also gives it more of a "close to home" feel than putting it near the Wanderers or Coalition

**Review by MasterOfGrey — APPROVED** [review]
> image what do people think about moving them here instead?

Assuming this is the current state from that last commit; this is definitely my first preference by far.
I will probably re-shape the systems a bit later, but this suits me just fine for now.

**Comment by Amazinite** [comment]
Cursed location.

**Pull request merged**
