### PR TITLE
fix(typo): Mass production

### PR DESCRIPTION
**Pull request by tibetiroka**
**Bugfix:** This PR fixes mass-produced typos.

## Fix Details
[Correct form](https://www.merriam-webster.com/dictionary/mass-produce):
`mass production`
`mass-produce`
`mass-producing`
`mass-produces`

## Testing Done
N/A

## Save File
N/A

Also, does anyone know if the correct form is `weapon fire` or `weapons fire`? Another potential typo fix I wanted to get into this PR, but I can't find anything online.

### CODE REVIEW

**Comment by lumbar527** [comment]
Are the instances of `weapon fire` and `weapons fire` used as synonyms to gunfire?

**Comment by tibetiroka** [comment]
The ones I was looking at, yes.

**Comment by lumbar527** [comment]
Just my opinion, I think they should just be replaced with gunfire.

**Comment by tibetiroka** [comment]
That might be a bit too drastic. Chances are, half of those are correct as-is.

**Comment by lumbar527** [comment]
I guess, it just sounds a little awkward to me.

**Comment by Amazinite** [comment]
Granted there could be extra context around the usages of these two words in combination that's being lost by this graph, but it looks like "weapons fire" is more common than "weapon fire".
image

**Comment by tibetiroka** [comment]
I'm not sure about the FW one.

**Pull request merged**
