### PR TITLE
Small change in the intro conversation

### PR DESCRIPTION
**Pull request by Amazinite**
Just noticed this. Then it started to irk me.

### CODE REVIEW

**Comment by endless-sky** [comment]
From Wikipedia:

> The International Bureau of Weights and Measures states that "when there are only four digits before or after the decimal marker, it is customary not to use a space to isolate a single digit". Likewise, some manuals of style state that thousands separators should not be used in normal text for numbers from 1000 to 9999 inclusive where no decimal fractional part is shown (in other words, for four-digit whole numbers), whereas others use thousands separators, and others use both.

**Comment by Amazinite** [comment]
Alright.

**Comment by Amazinite** [comment]
Then why the comma here?
screenshot_1
And when you're paid a credit amount with 4 digits it includes the comma.
screenshot_3

**Comment by jafdy** [comment]
Simplicity in coding? Also;
>...and others use both.

**Comment by Amazinite** [comment]
>...and others use both.

That may be the case, but I think it would be fair to at least stay consistent, otherwise I'm probably never going to be able to look at the intro conversation the same way again.

**Comment by MessyMix** [comment]
I agree—we should go for some consistency, as long as it's not too much code work.

**Pull request merged**
