### PR TITLE
Player can now deselect current target by clicking, can now easily click on asteroids for mining.

### PR DESCRIPTION
**Pull request by ChamEV**
* Player can click empty space to deselect current selection and target.
* Can only have a ship xor an asteroid targeted at once.  Clicking one un-targets the other.

### CODE REVIEW

**Comment by ChamEV** [comment]
> All of your PRs contain styling and whitespace inconsistencies with the current code. There is a code style guide to draw from on the github.io website, along with an EditorConfig file if you use an editor/ide that supports it.

I think I've fixed all the space/tab issues, was there anything else style wise that is off?

**Comment by ChamEV** [comment]
I suspect this was the original behavior and it got lost along the way.

**Comment by Amazinite** [comment]
@ChamEV Anyone home?

**Comment by Amazinite** [comment]
@ChamEV Do you have the time to address tehhowch's review?

**Comment by Wyrdean** [comment]
@ChamEV I would like to make this functional as it's a rather nice idea and prepare it for use in the game, any objections?

**Comment by Amazinite** [comment]
Handled by #5661.

**Pull request closed without merging**
