### PR TITLE
Replacing Solace's landing picture & another better one for Earth

### PR DESCRIPTION
**Pull request by bene-dictator**
**Content (Artwork)**

## Summary
(I know I'm doing this again. Please stay with me on this one.)

After a little bit I realised that Earth's new landing picture; while it's better than the old one at making Earth look populated and dangerous; is too monocolour and soulless. This new picture should be better as it has much more colour, but still makes Earth look overpopulated and moody. I've also added a new picture for Solace, because it's a 2 billion population planet that looks just like a Dirt Belt planet. 

city19@2x
This is the current Earth picture. Compare it with:
city20@2x
This is a picture of Manila from Unsplash. 

valley6@2x
This is the current Solace picture. Compare it with:
city23@2x
This is a picture of Santiago from Unsplash. 

Ingame:
Screenshot_20221204_075815

Screenshot_20221204_075704

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: [#324](https://github.com/endless-sky/endless-sky-high-dpi/pull/324)

### CODE REVIEW

**Comment by a-random-lemurian** [comment]
Manila will be the city that people see when landing on Earth the moment this PR is merged.

The additional color is pretty much appreciated.

**Filipino pride intensifies**

**Review by a-random-lemurian — APPROVED** [review]

**Comment by bene-dictator** [comment]
Hahaha, I chose Guangzhou before because that where my family's from, but Manila fits a lot better for Earth.

**Review by mOctave — COMMENTED** [review]
Looks good, although, what was city20 used for before now?

**Comment by bene-dictator** [comment]
It wasn't being used. I wanted to use another photo for Solace in my other PR. Maybe I will need to redo this bit?

**Review by mOctave — APPROVED** [review]
Everything looks good, since city20 is unused.

**Comment by bene-dictator** [comment]
I've made another version of Solace's landing image that has a little bit more city in it, which bugged me before because it was not cleanly in half like other pictures (the picture of Manila especially). It should also help get the idea across of Solace being very populated. Tell me if it's better, and I'll change it. 

New:
city23@2x

Previous:
city23@2xold

**Comment by Saugia** [comment]
We for sure here? No changing the landscape for a third time after this? :P

**Comment by bene-dictator** [comment]
No, I'm happy. I was afraid someone was going to say this!

**Review by Saugia — APPROVED** [review]

**Comment by a-random-lemurian** [comment]
It's finally merged! I can feel the filipino pride in my blood vessels everytime someone lands on Earth and sees Manila in all its glory.

**Pull request merged**
