### PR TITLE
fix(bug): Surviving escorts after FWC Pug 1 attack the Pug in subsequent missions

### PR DESCRIPTION
**Pull request by ziproot**
**Bug fix**

This PR addresses the bug described in issue #8832 

## Summary
When your job is to attack the Pug and steal a jump drive, your escorts just sit there and do nothing. This continues when you re-enter pug space later until you try to retake Oblivion. This PR creates a new government for the escorts. It is attacked by the Pug at first and then the Pug become peaceful. However, when you depart to steal a jump drive, the escorts help you.

## Screenshots
image

## Testing Done
Made sure the escorts attacked during the escape mission and onward, and during the pug attack at first, but not in between.

## Save File
This save file can be used to test these changes: 
[Test Pilot~Escape!.txt](https://github.com/endless-sky/endless-sky/files/14030975/Test.Pilot.Escape.txt)

### CODE REVIEW

**Comment by ziproot** [comment]
The ships aren't your escorts (you can't give them commands). If you get something that changes your swizzle those ships will have changed swizzles as well. If you have negative reputation with the Free Worlds the ships won't attack you, which is inconsistent with other escorts in the game.

**Comment by alexrovw** [comment]
> The ships aren't your escorts (you can't give them commands). If you get something that changes your swizzle those ships will have changed swizzles as well. If you have negative reputation with the Free Worlds the ships won't attack you, which is inconsistent with other escorts in the game.

1. Many non-controllable escorts already use the `Escort` government, such as the prisoner transport Blackbirds in `"FW Southern Prisoners - Release"`.
2. Being able to swizzle in the middle of FW would be a bug. You may not change from FW colors while under their employment.
3. If you have negative reputation with the Free Worlds, you should fail the corresponding mission `mission "FWC Checkmate Escorts"`. I would make that change instead.

**Comment by ziproot** [comment]
> Many non-controllable escorts already use the Escort government, such as the prisoner transport Blackbirds in "FW Southern Prisoners - Release".
I didn't know that. I will switch to the Escort government.

**Comment by Amazinite** [comment]
> If you get something that changes your swizzle those ships will have changed swizzles as well.

We don't write missions from the assumption that the player may have a plugin or may have edited their save file in a way that could break things.

**Comment by ziproot** [comment]
> We don't write missions from the assumption that the player may have a plugin or may have edited their save file in a way that could break things. Write missions from the assumption that everything is working as intended.
That makes sense

**Comment by Amazinite** [comment]
This might not actually be desirable behavior from the fleet that is with you, which is limited in size until you can relink the Pug occupied systems to the rest of the galaxy. https://github.com/endless-sky/endless-sky/issues/8832#issuecomment-1913704714

**Comment by ziproot** [comment]
I didn't realize FW Pug 3A was a non-attack mission

**Pull request closed without merging**
