### PR TITLE
Improved blasters

### PR DESCRIPTION
**Pull request by Nescio0**
Yet another counterproposal to make blasters somewhat more attractive. This one does not involve any changes to default or variant ship builds. As suggested in #3393:

> Increasing the Blaster range (maybe by increasing speed rather than lifetime) and decreasing its heat production.

This proposal does that:
* blaster velocity increased from 7 to 8.5, which means a range increase from 420 to 510
  * modified blaster from 7.5 to 9.0, thus range from 450 to 540
* blaster and modified blaster firing heat reduced by 3/7 (to make it twice the firing energy)
* blaster and modified blaster firing energy remains unchanged (i.e. highly inefficient)
* blaster shield + hull damage per second changed from 45+30 to 50+25
  * modified blaster from 60+40 to 70+35

With these changes blasters remain highly inefficient, but might become occasionally useful.

*not implemented* but to be considered, because of modified blaster's 40% higher damage:
  * modified blaster gun size from 6 to 7 (blaster has 5)
  * modified blaster turret size from 18 to 20 (blaster has 15, quad blaster 25); 
  * the "Modified Argosy (Blaster)" seems to be the only ship equipped with modified blasters (maybe replace the ordinary quad blaster turrets with modified blaster turrets to save space and heat?)

Effectively this patch results into:

Blasters:
* poor energy and heat efficiencies
* good credit and mass efficiencies
* mediocre range
* higher shield than hull damage

Lasers:
* great energy and heat efficiencies
* decent credit and mass efficiencies
* low range (especially with #3406)
* higher hull than shield damage
* continuous fire

So yes, lasers remain attractive, but blasters get their own niche.

### CODE REVIEW

**Comment by tehhowch** [comment]
As an aside, "mb" is an absolutely terrible commit name. https://github.com/endless-sky/endless-sky/commit/845c304698d4442da64c81cebe21991c48742380

If I were to see that title and description in a git log I would have zero clue what that commit does or tries to do.

**Comment by Nescio0** [comment]
> As an aside, "mb" is an absolutely terrible commit name.

You're right, I should have written "modified blasters" at the very least. Whenever I use command line git I typically use more precise commit messages. With web forms (such as github's) I have the bad habbit to use abbreviations or placeholders to fill in required fields quickly, which I do not always expand properly afterwards; a poor excuse, I know.

**Comment by Amazinite** [comment]
Mostly a welcomed change. I'm just unsure about increasing the modified blaster's combined DPS (even though it is only a 5% buff). If we aren't afraid of damage values with decimals in them, then I'd suggest changing the modified blaster's shield damage to 13.3 and the hull damage to 6.7 in order to get its shield/hull as close to 2 as possible without using repeating decimals and have it retain its current combined DPS.

**Comment by Nescio0** [comment]
https://github.com/endless-sky/endless-sky/commit/beb7f03836f37e173134e9e9f510494393924bb7 does implements something similar, so this proposal probably won't be implemented.

**Pull request closed without merging**
