### PR TITLE
Add reworked sprites for the Plasma Core outfits

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds reworked sprites for the Plasma Core outfits. The 3D model were entirely redone.

comparison

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/60
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/273

### CODE REVIEW

**Review by beccabunny — APPROVED** [review]
Fantastic stuff

**Review by Hurleveur — APPROVED** [review]
Finally they look like actual advanced alien tech, and not weird trash collectors!
Amazing work especially on the lightning, I love the fact they are radiating with heat.

edit: looking more closely I liked the metallic look on them, now it's more subtle, maybe a bit too much so? still a massive improvement anyway.
RP wise these are super old so it makes sense they wouldn't be shiny.

**Comment by Hurleveur** [comment]
That looks even better, with the additional contrast you've added too! Nice work

**Review by Saugia — APPROVED** [review]
These look amazing! As Hurl said, they look much more alienated now and fit the hot working tech theme of the korath much better now. They no longer look like a hunk of metal that powers a ship, but something more dangerous that you want to be careful with heating, a a reactor should be. The highlights make the cake.

**Review by ravenshining — APPROVED** [review]
Great work!

And thank you so much for bearing with me and all my feedback during the process.

**Comment by GefullteTaubenbrust2** [comment]
> Great work!
> 
> And thank you so much for bearing with me and all my feedback during the process.

Wouldn't be half as good if you hadn't given it so you're most welcome!

**Pull request merged**
