### PR TITLE
Again with the hails.txt (Sorted Edition)

### PR DESCRIPTION
**Pull request by greatkek**
I'll be updating this one from this point on, as this is now preferable due to being searchable. But, new pull request as this is a fairly large change.

### CODE REVIEW

**Comment by greatkek** [comment]
I also have all the various factions in their own .txt if anyone wants it.

**Comment by tehhowch** [comment]
The old one was also searchable. In general a huge diff in which it is not clear what is being done is difficult to review, and hard to approve.

What is not searchable about the current format that it needs to be rearranged?

**Comment by greatkek** [comment]
It's sorted, and easier to search. Download the file and you'll see. control f #navyhostile will go straight to all the navy hostile responses, rather than them being spread throughout as they were previously. I recommend you download the file and look yourself. It's easier to use.

**Comment by Amazinite** [comment]
>control f #navyhostile will go straight to all the navy hostile responses, rather than them being spread throughout as they were previously.

What do you mean by that? Currently you can ctrl+f "hostile navy" and all three phrase sets are already located next to each other. They aren't spread out.

**Comment by greatkek** [comment]
It but them all together rather than having to scroll from the top to the bottom to see all the hostile navy. #navyhostile has all hostile navy responces. idk why this is so hard to understand. It's just sorted for future releases to be easier to look at and navigate as you just control f #navyhostile for every single hostile navy reply, rather than finding them all split up all over the file. Use it or don't, it's a good change though just to make it easier in the future. I'm not gonna try and sell it to you though, if you want it to not be sorted that's up to you guys. They are simply categorized now, unlike before.

**Comment by Wrzlprnft** [comment]
While this pull is certainly something to discuss, your perception of what was and what you did is very... self-assured.

The System before was: First all friendly hails, then all hostile hails. but within that, they were already grouped by phrase name/government.
What you did: Now they are primarily grouped by phrase name/government, and within that by friendly then hostile.
Given that they are not bound to the government names, but surely wether they are friendly or not, this seems a change that can be useful, especially with the future in mind, but changes a working system. This definitly isn't as straight forward as you thought, but that could be solved in a discussion here.
BUT:

- You mixed a content pull request with a organisational pull request. which is the same as bundling 29 bad skins with the one good one that people want. please don't do that.
- You kept your flood of commits. While there is nothing wrong with that in ongoing pulls, as long as it doesn't get too messy, it is favored to keep the commit amount low. This time you missed that chance.
- You totally not describe what you actually did, and confuse people, further you seemingly misunderstood the existing system. Since you seemed to be interessted and joined the discord, a quick question along the lines of "are the hails currently organized in any way?" would probably have set up a healthy discussion and a way cleaner constructive pull. 
- You reversed the tags you put in there with the actual phrase names. Why do that?
- You succesfully ripped apart the Band phrase structure, contrary to your initial intention.

And please, for the love of god, keep those kind of comments out there.

Summary: this pull isn't convincing by itself, and throwing it at "us guys" instead of making a "we should consider this" is not the proper way on here

**Comment by tehhowch** [comment]
The current organization is largely alphabetical, with some thematic organizational elements (i.e. songs right after bands):
 - band
 - song
 - friendly hails
  - 15 civilian
  - 4 navy
  - 5 militia
  - 6 syndicate
  - 3 free worlds
  - 1 pug
  - 12 pirate
  - 1 disabled
 - hostile hails
  - 1 disabled
  - 1 civilian
  - 3 navy
 - 1 friendly deep
 - hostile hails again
  - 1 deep
  - 3 pirate
  - 2 bounty
  - 1 Quarg
  - 4 bounty hunter
  - 1 pug
  - 2 syndicate
  - 3 militia
  - 2 free worlds
  - 1 test dummy
  - 1 disabled test dummy
 - wormhole hails

The only set I find to be out of order is that the friendly and hostile deep phrases are together, instead of friendly deep with all the other friendly hails.

**Comment by greatkek** [comment]
fair enough, but I still stand by my stance saying the current is preferable. I ask you look at it :)

**Comment by tehhowch** [comment]
I wrote the current hail file layout above. Surely you can do the same for your proposed change to the file?

**Comment by Wrzlprnft** [comment]
i looked at it. i say:debatable, or let MZ decide. 
good catch that the deep ones are out of order.
but definitly do not merge this pull as is :)

**Comment by Pointedstick** [comment]
In general, proposing huge changes (not just additions) when you're just starting out as a new contributor isn't starting off on the right foot. Big changes require either significant justifications or credibility. As others have pointed out, there's nothing wrong with any of the ordering as-is except for the friendly Deep hails. A change to correct that is probably merge-able. Something this large and unnecessary isn't likely to be.

**Comment by greatkek** [comment]
tehhowch, I didn't ask you to make that, and never said I would could them all just to compare a list with yours. If you want to see the layout that I proposed, it's right there. Our numbers will be the same, it's just a matter of preference. Since no one liked the idea but me, case closed.

**Comment by tehhowch** [comment]
Submitting organizational changes for review is fine, but don't omit a clear and concise summary. MZ and MZ alone has commit access, and he has to go through every line of every PR before he merges them, to make sure they meet his standards. If you provide the overview for the change you can greatly speed this process along, rather than just saying "see the change for yourself."

Your opening post in this PR should have included the summary list I made, and the summary list you still haven't made. Doing so would have immediately identified what you are doing with the pull, and what you mean when you say "sorted." Instead, you claimed the current hails.txt is not searchable, and your large update to it should be approved solely because your version is searchable.
This dismissal of the existing format created defensive (perhaps hostile :wink: ) environment, especially when Ctrl+F searches the existing version just fine, and even indicates that every equivalent hail is already grouped together.

In this repo's Contributing file, you'll note that it is recommended to open an issue in which you propose a change and discuss the reasoning for it prior to actually performing the work. If you had done so (presumably presenting the current file layout as in my post above, and then the updated layout that you feel is an improvement), you would have gotten much better feedback.

I recommend you use this PR solely to reorder the clearly out-of-place `friendly deep` hails amidst the other `friendly...` hails, and then open the issue I mention above.

(I would likely move the `friendly deep` hails after `friendly navy`.)

**Pull request closed without merging**
