### PR TITLE
Marauder ship outfits and sprite credits

### PR DESCRIPTION
**Pull request by LocalGod79**
more ships added by max k

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
oh... i have loked at how the name is given, not if all ships are there...
insert random curse here.

**Comment by LocalGod79** [comment]
np - just making sure everything that should be there, is.

i noticed that there was only one mention for each 'mship' hull, with the asterisk to replace the (e)ngine,(s)tandard, and (w)eapon variants distinction - but the mfury (as mmk's ship) does not have all of those hulls, so it does not require the *.

**Comment by toilethinges** [comment]
Do the Marauder missions require finishing the campaign? If they don't, you shouldn't use Electron Beams, as they're unlocked late in the storyline.

**Comment by endless-sky** [comment]
The asterisk is so that the same copyright file can be used for the normal sprites and the @2x sprites. That way, I don't have to maintain two completely separate versions of the file; I can just copy it into the high dpi plugin when I release a new version of it.

**Comment by LocalGod79** [comment]
asterisk returned to mfury.

@toilethinges the electron beams are only available on two of the rare variants in the top tier of the jobs, which require a combat rating that would normally be acquired late in the fw campaign.

that said, it is possible for a player to do some serious grinding to get their combat rating high enough early enough, and then further grinding to draw the right ships (engines variants of the Leviathan or Falcon) on an already rare mission set.

it's possible, and if they put in that much effort (possibly more than just doing the FW story), i feel like they may actually deserve the four 'prototype' e-lasers.

if the boss says so, i'll find an alternate outfit.  otherwise: "happy easter!"

**Comment by toilethinges** [comment]
@LocalGod79 Makes sense, and happy Easter to you too!

**Comment by endless-sky** [comment]
I've got mixed feelings about the electron beams, but I think it's reasonable to leave them in, given that most players will play through the story before seeing these ships. (And, for those who don't, the new technology is sort of a cool bonus.)

**Pull request merged**
