### PR TITLE
Add station5.jpg

### PR DESCRIPTION
**Pull request by MCOfficer**
a rendered corridor inside a space station; use it at will.

### CODE REVIEW

**Comment by MCOfficer** [comment]
i also have this space station ready, but i'm not sure about the scaling and the colors. feel free to request any kind of coloring. personally, the yellow does not satisfy me yet.
https://dl.dropboxusercontent.com/1/view/kvxl318us4lakpa/Apps/Shutter/final.png

**Comment by KiLEdEnNis** [comment]
looks a bit artificial tbh

**Comment by Wrzlprnft** [comment]
i recommend taking the model of a existing space station and look at the camera angle and light sources and see if yours are the same.otherwise, looks cool

**Comment by Pointedstick** [comment]
Lower the light level and re-position the lights to create more shadows; that should both enhance the look as well as disguise the CG aspects.

**Comment by endless-sky** [comment]
Do you have a 2x version and source files (3D model, plus any post-processing you did)?

**Comment by MCOfficer** [comment]
i only did minor color and lighting changes starting from this template: 
http://www.blendswap.com/blends/view/74788
if you don't use blender, i could also export the station as .obj or any other file, lighting is (as mentioned) suboptimal anyways, so i would let you do the rest ;)

**Comment by KiLEdEnNis** [comment]
Blender is the 3D program MZ (and I think all plugin creators) use

**Comment by MessyMix** [comment]
I love the look. @Pointedstick has good advice, but otherwise, I support it! :D

**Comment by MCOfficer** [comment]
@MessyMix for some reason, these links expire from time to time. here's a new one. https://www.dropbox.com/s/ym5lt0bb32jelrj/final.png?dl=0
i would upload it on a public image host, but i don't know how i should credit the OP there.

**Comment by MessyMix** [comment]
@MCOfficer good idea—solid design—but needs polishing on this one. Your interior design is stunning, though, and it is nearly game-ready imo.

**Comment by Pointedstick** [comment]
You also can attach images straight to posts here. Just drag and drop!

**Comment by MCOfficer** [comment]
i will probably not work on this in the near future. feel free to adapt or maybe even finish this, i'll gladly send you the blend files if requested.

**Pull request closed without merging**
