### PR TITLE
Tooltip changes

### PR DESCRIPTION
**Pull request by TheGiraffe3**
# Bug fix

This PR addresses the bug/feature described in issue 
No issue

## Summary
The tooltip had said that ships cloaked as red when fancy was enabled. In 0.10.7, this was changed to black. I changed the tooltip to reflect that.

## Screenshots

Before
Before

After
After

## Usage examples
_No Response_

## Testing Done
Checked to see if the tooltip updated properly.

## Save File
N/A
This was a settings change.

## Artwork Checklist
N/A

## Wiki Update
N/A

## Performance Impact
N/A

### CODE REVIEW

**Comment by Anarchist2** [comment]
This is definitely red.
image
We could technically be more specific by saying the ship becomes grayscale, but the tooltip is already wordy as it is.

**Comment by TheGiraffe3** [comment]
Sorry. But the ship itself does not turn red, it turns grey.

**Comment by TheGiraffe3** [comment]
You're right. I was thinking of flagship, but the tooltip does say escort.

Screenshot 2024-06-06 at 3 22 06 PM

However, it is a transparent black, and the current tooltip is not completely clear on that.

**Comment by TheGiraffe3** [comment]
@Anarchist2 could you look at this again?

**Comment by Amazinite** [comment]
The current tooltip is not incorrect. The ship does become transparent and does receive a red outline. I see no need to specify that when the ship becomes transparent, it also gets grayscaled/blackened.

**Comment by TheGiraffe3** [comment]
Okay. Just seems a bit unclear to me.

**Pull request closed without merging**
