### PR TITLE
feat(content): Navy Surveillance Fleet Rework

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

**The PR is currently in-progress, as there's a decent amount of fleet changes and event changes that I have to look through, account for, and discuss.**

## Summary

Currently, the player can encounter Gunboats with scanning equipment in any Navy fleet with a Gunboat present, making it difficult for gameplay such as smuggling when the Navy essentially dogpiles the player whenever a fleet shows up. This PR makes various changes to the fleet and where it is defined.

- The cargo and outfit scanners from the default Gunboat have been removed, and adds a specific variant using them has been added to the "Navy Surveillance" fleet.

That said, as pointed out by @bene-dictator, this fleet does not show up until the Free Worlds is created.

- The Navy Surveillance fleet has been added at start of the game to systems it would generally appear in, and only uses the Gunboat. 
- Once the Free Worlds is created, these fleets are then given the variant spawn with a Cruiser and Surveillance Drones.

The only thing that has changed so far from the current game is that these fleets now exist at the start of the game as Gunboats, in place of every Gunboat being a surveillance ship that scans you or others, and then exist normally later on with the Cruiser/drone spawns.

@Quantumshark has brought up that perhaps the Navy Surveillance Fleets should no longer be showing up randomly in Free Worlds systems following the first major of battle (Defend Sabik), as that can be interpreted as wasting resources, especially drones/smaller ships that can be easily destroyed. This is the true act of fighting, rather than doing so during the capture of Kornephoros; Quantum states:

`The capture of Kornephoros happens nonviolently - the navy show up, say the planet is theirs, and the FW let them do it. It's only when the Navy tries the same with Sabik that the FW responds and fighting begins. `

It makes sense that the Navy use supplies like these on the borders, but not sent deep within FW space itself once actual fights are happening. That said, this PR additionally removes Navy Surveillance fleets from any FW systems following the battle of Sabik, but not from any other systems at this time. Navy Surveillance fleet presence changes are as follows:

- The Navy Surveillance fleets introduced in Initial Deployment Events 1-3 are now present in those systems at the start of the game (in Gunboats until the FW is formed).
- I've elected to keep Initial Deployment 4 untouched, as the Surveillance fleets are introduced in systems nearby FW space, to indicate a move of Surveillance following the formation of FW.
- The Surveillance fleets in the capture of Kornephoros are also untouched. This is prior to the battle of Sabik, and the system is in control of the Navy at the time. After it's liberated, the fleet disappears normally.

Events yet to be explored that use Navy Surveillance fleets:

Normal in Alnasl
FW Southern Expansion
FW Occupying North
FW Armistice 
Navy Out of Rastaban
FWC Southern LIberation

It's also important to know that Gunboats don't all have scanners now, meaning not every system in human space has a surveillance possibility because only select systems currently use the fleet. Maybe we consider adding the surveillance fleet to systems of importance (Sol, etc.), or make another small and uncommon Surveillance fleet simply for background spawns for human space in general. It might be odd if only borders were surveilled, and as a Pirate player, you're suddenly free of scans deep in human space.

Keeping this as a draft for now until every event is addressed.

### CODE REVIEW

**Comment by Saugia** [comment]
So, actually thinking about it more, this method may not be the best way to go about this.

This is a map of systems that gain Navy Surveillance fleets through the four "initial deployment events" that happen passively before hostilities:

deployment activity

And this is a map of Navy Surveillance fleets added throughout various events in the campaign, all done post battle of Sabik save for the Navy's capture of Kornephoros:

various events

Of course, this means any events that remove fleets do so with the same systems )(from either image). That said, removing surveillance Gunboats from general fleets and relying on the events that introduce them is obviously limiting as this is only systems based around the Dirt Belt and the rest of human space (even the north pirates not in this screenshot as they are cropped out) is free of any scanning.

Perhaps we do add a Small Navy Surveillance Fleet (or whatever name) and strategically place it across the map, keeping in mind possible Pirate gameplay (both traps and loopholes), etc.. The presence of Surveillance fleets can still be removed from post-hostilities FW systems, but I think instead of changing these fleets to be present at the start, it might simply be better to add a new separate fleet and leave these ones alone since they still imply Navy movements in the south. It also would mean keeping the Cruiser variant in the current fleet to begin with instead of adding it later on.

Looking for thoughts before continuing work on the PR.

**Comment by TheGiraffe3** [comment]
A Navy Surveillance fleet separate from down South would help quite a bit, in my opinion.
One things I have wondered though is why the Navy stop scanning FW systems after becoming at peace. There is, after all, no ships of the FW that are at all capable of scanning.

**Comment by TheGiraffe3** [comment]
Related: #9894.

**Comment by Saugia** [comment]
Closing this until I have more time to work on it as it will require a decent amount of reworking.

**Pull request closed without merging**
