### PR TITLE
Grammar fix - Remnant 1 intro

### PR DESCRIPTION
**Pull request by opusforlife2**
**Content (Artwork / Missions / Jobs)**

Grammar fix: depreciatingly > deprecatingly

### CODE REVIEW

**Comment by Hecter94** [comment]
Remember to fill out the template before marking this as ready for review :wink:

**Review by Zitchas — APPROVED** [review]
I think this word has come up before, but in reviewing search results for depreciatingly vs deprecatingly it seems to overall favor this replacement.

Both work, with the intended sense, but deprecating (especially in the sense of self-deprecating) fits better.

**Comment by Hecter94** [comment]
> @Hecter94 I'm not sure what else needs to be added to the template.

For the template, I would suggest filling out the following sections:

```
**Content (Artwork / Missions / Jobs)**

## Summary
{{summarize your content! Include links to related issues, in-game screenshots, etc.}}

## Save File
This save file can be used to play through the new mission content:
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}

## UI Screenshots
{{attach before + after screenshots of any changes to UI, or replace this line with "N/A"}}

## Testing Done
{{describe how you tested the new feature}}
```

I would not suggest using the bugfix template, as this is a content change. 
You want to give a summary of the change, what you changed, and why, and your reasoning for why the change is a good one.
A save file that will allow others to verify the change, a screenshot showing the change and the testing you did to confirm that the change worked in-game as expected.

**Review by roadrunner56 — APPROVED** [review]
If Zitchas is okay with this change then I am too.

**Pull request merged**
