### PR TITLE
Create interfaces.txt

### PR DESCRIPTION
**Pull request by ziproot**
**Bugfix:** This PR addresses issue #9188 

## Fix Details
This forces an overwrite of the old interfaces.txt file so only the new one in the _ui folder is used.

## Testing Done
Tested to make sure this didn't overwrite the file in the _ui folder. Planets still look fine.

## Save File
Create a new pilot.

### CODE REVIEW

**Comment by ziproot** [comment]
Marking as ready for review so the game will build and I can test it.

**Comment by ziproot** [comment]
... apparently I need to assign a copyright header to an empty file
This shouldn't cause it to not build so I will wait to fix that until then.

**Comment by ziproot** [comment]
fine

**Comment by ziproot** [comment]
I spoke too soon. This works.

**Comment by TomGoodIdea** [comment]
This PR may fix this particular interfaces file case, but the root problem remains; there are other files affected (see #8044) and possibly there will be more. We need a proper solution to make sure no outdated files are left after an upgrade.

**Comment by ziproot** [comment]
Yes. The issue fixed is on a milestone due today.

**Comment by Amazinite** [comment]
A majority of the reports for this issue have been from people who used the ES launcher to update to continuous, which doesn't delete old, no longer existent files. The reproduction method that Tom mentioned in #9188 similarly didn't delete old files, therefore causing an incorrect interfaces file to be used.

There's only one report of this occurring on Steam, but Steam actually does delete old files when updating, and if it didn't then we would have received far more reports of this being an issue when 0.10.1 and 0.10.2 were released.

**Comment by ziproot** [comment]
In that case, close the linked issue as not planned.

**Pull request closed without merging**
