### PR TITLE
feat(artwork): Remnant Swan

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork)**

## Summary
Similar to https://github.com/endless-sky/endless-sky/pull/6895, this is a PR to add sprites for a future ship, the Remnant Swan, that has been in the works for a little while now. It is also an animated ship similar to the Peregrine.

Representations below are now updated according to feedback.

swan-game-final

swan-shipyard-final

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/77
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/299

### CODE REVIEW

**Comment by GefullteTaubenbrust2** [comment]
I have mixed feelings about this model, my biggest issue being that it breaks from a lot of design decisions that are otherwise fairly consistent among the other ships. I get that not every ship has to be virtually the same, but here it is significant enough to stand out considerably. 

The most obvious case of this is in the wings, which are much more "chaotic" in structure than on any of the other ships; the contours are significantly more difficult to see, the support beam things bulge out a lot as well being much more complex in shape and the gill section underneath is largely in its shadow. Again, trying something different with it is fine, but it feels too much.

As for the main body, it bulges out a lot although I think its purpose may justify that to an extent. Something I noticed is that the center gun at the front casts a very dark shadow which kind of breaks up the shape of the nose. Maybe it could be moved under the ship instead.

Anyways, other than that it looks pretty solid to me - the colors and shading all look great and for the most the shape blends in quite nicely.

**Review by GefullteTaubenbrust2 — CHANGES_REQUESTED** [review]
I have mixed feelings about this model, my biggest issue being that it breaks with a lot of design decisions that are otherwise fairly consistent among the other ships. I get that not every ship has to be virtually the same, but here it is significant enough to stand out considerably.

The most obvious case of this is in the wings, which are much more "chaotic" in structure than on any of the other ships; the contours are significantly more difficult to see, the support beam things bulge out a lot as well being much more complex in shape and the gill section underneath is largely in its shadow. Again, trying something different with it is fine, but it feels too much.

As for the main body, it bulges out a lot although I think its purpose may justify that to an extent. Something I noticed is that the center gun at the front casts a very dark shadow which kind of breaks up the shape of the nose. Maybe it could be moved under the ship instead.

Anyways, other than that it looks pretty solid to me - the colors and shading all look great and for the most the shape blends in quite nicely.

**Comment by Saugia** [comment]
>The most obvious case of this is in the wings, which are much more "chaotic" in structure than on any of the other ships; the contours are significantly more difficult to see, the support beam things bulge out a lot as well being much more complex in shape and the gill section underneath is largely in its shadow. Again, trying something different with it is fine, but it feels too much.

The wings are intentionally more involved than previous remnant designs. Based off of a Swan's elegancy, there are a lot more tendrils coming off of them that curl outwards, and the wings themselves are supposed to be one of the main design points of it (swans have great wingspans). They also curl downward a bit too as seen in the thumb. 

>As for the main body, it bulges out a lot although I think its purpose may justify that to an extent. Something I noticed is that the center gun at the front casts a very dark shadow which kind of breaks up the shape of the nose. Maybe it could be moved under the ship instead.

The bulges are entirely intentional as this ship is designed to carry a lot of liquid/fuel, and were requested by Z. As for the gun, the intention on this was to also break other remnant patters of them always being underneath the ship and show a sort of "tri" pattern around the nose- having the gun underneath makes the 3 guns look too much like a fork in front. 

I will point out that this ship has been extensively modeled and redone several times under the guidance of not just Z himself but the community in both artwork and ember waste chat. There are reasons the design is further from other Remnant ships, and why some parts are more intricate.

**Comment by GefullteTaubenbrust2** [comment]
> The wings are intentionally more involved than previous remnant designs. Based off of a Swan's elegancy, there are a lot more tendrils coming off of them that curl outwards, and the wings themselves are supposed to be one of the main design points of it (swans have great wingspans). They also curl downward a bit too as seen in the thumb.

I get that, but I still think they look odd, mainly because of the huge shadows that are cast on the gills.

> The bulges are entirely intentional as this ship is designed to carry a lot of liquid/fuel, and were requested by Z. As for the gun, the intention on this was to also break other remnant patters of them always being underneath the ship and show a sort of "tri" pattern around the nose- having the gun underneath makes the 3 guns look too much like a fork in front.

It still looks quite odd in my opinion. The gun is hardly visible either way because it lines up perfectly with the seam in the middle, so all that really shows from it is a dark spot on the left.

> I will point out that this ship has been extensively modeled and redone several times under the guidance of not just Z himself but the community in both artwork and ember waste chat. There are reasons the design is further from other Remnant ships, and why some parts are more intricate.

I don‘t doubt for a second the effort that went into making it, and kudos to you for it. Thing is, the wings don‘t look nearly as odd in the screenshots you posted as they do here. I will elaborate on this later when I get the chance to post images to make my point.

**Comment by beccabunny** [comment]
I partially agree with Gefu's points here, in particular the shadows. I don't have any problem with the wings' structure personally, but what looks off to is the shadows it has on it; if they were tilted less and if the vent-like things in the middle of them were closer to the top it would look much better to me, specifically to reduce the shadow casted here
image

**Comment by Hurleveur** [comment]
Idk if its just me but seeing the wings forward and the overhaul look of the ship (imposing) makes me think of a predator. Or at least a very tank-y ship.

I personally love the look of this ship, the only thing that slightly bugs me is that, if I understood correctly, this is a new, sentient ship, which I had the impression had a different post processing, and an overhaul "cleaner" look, like we can see for the Peregrine.
Anyway great work! Makes me want to buy it as soon as it comes out...

**Comment by Zitchas** [comment]
I will post some additional detail after the weekend when I have more time. The short of it is that the swan is a fleet tanker. It's primary purpose is to collect and transport massive amounts of fuel to support long-range major fleet activities. Also can handle things like transporting supertanker scale shipments of liquids. As such, significantly larger gills and bulgy wings filled with fuel, liquids, and gases storage systems, are all part of the design.

In terms of armaments, I anticipate it carrying a few things: PDT for obvious reasons, rear facing Taciimachs to discourage pursuers, perhaps an inhibitor turret located near the back to slow down pursuers, with the various support weaponry at the front. By support weaponry, I mean a repair turret, fuel transfer gun, etc. We can already make such weapons, just the AI doesn't know how to use them.

In terms of timeline, these are one of Taely's projects that are currently in progress, although she would describe it as more of a mental exercise: She knows fleets have historically needed tankers, so she is designing one; but she would be the first to acknowledge that there really isn't any demand for it. At best, this might be useful in the future of the Remnant needed to leave the EW or support a project that had massive fuel requirements. As of the end of Chapter 2, this ship is nearing the end of its design process, scale models have been tested, and it is entering the final refinements stage.

It will most likely be introduced in chapter four, and used extensively in the following chapter. (Going from memory here, as I don't have immediate access to my notes)

This ship may be a carrier in the form of a handful of drones to make use of the refueling AI in PR (insert number here), but it is not intended to be an offensive carrier. (Probably in the 2-4 range)

**Comment by GefullteTaubenbrust2** [comment]
So for the wings my main issue is with the top down view. For one, the supporting structure bulges "out of the screen":

swan6

 This creates a disconnect withthe gills section, which isn't helped by the massive shadow it casts on the left side. It also makes the wings appear much thicker than they really are, which looks odd given how thin they are from front to back.

The other major issue is that the very strong contrast on the front of those supporting sections is absent on the back side:

swan7

If you step back from your screen, they become hardly visible as a result. This is a problem, because it looks as though the wing is split up into just two sections. This issue was much less prominent with the image from the discord, which shows the structures much better (I assume mostly because the lighting is very different):

swan4

The thumbnail will also not get away scot free though. My issue here is that the wing seems to poke out at the camera pretty irritatingly due to its apparent shape:

sawn3

I imagine that this could be fixed with a few supports to move the wings' center of mass closer to the ship (this would be more logical from an engineering point of view, too) or shrinking them a bit.

**Comment by Zitchas** [comment]
My initial image for what I was imagining was a picture of a swan about to land in the midst of a wing stroke, where the wings make a decided curve, so they *are* closer to the camera than the body, while the wingtips are level with it even a little below the bottom of the body.

I really dislike how pancake flat our ships are, so having that curve is both intentional and desirable. I do realize it is harder to make arches like that look good when flattened into a 2d sprite than just starting out with pancakes, though.

**Comment by Saugia** [comment]
@GefullteTaubenbrust2 @beccabunny 

I think a majority of the shadow issues can be resolved by increasing the lighting a little on the left side and raising the vents themselves a bit. The wing structure I wish to keep the same, curved downwards like this.

image

And for the thumbnail bit Gefu, it looks as such because that's how the wings are designed, they *are* trapezoidal and increased in width a bit more to the end. And regarding the thickness of them popping out, that's just how remnant designs are- if I make it any thinner, it will be too thin. Again I would imagine manipulation of the lighting versus the model itself will be beneficial here, especially considering I have everything rigged up to an animation already.

image

I'm not sure what you mean by the back structures, though. If you're talking about the size of the front edge being a bit smaller to the rear edge, I can see that being different, but from a design standpoint the rear tendrils that aren't part of the wing are supposed to make up the difference visually. 

image

I have to dispute an engineering standpoint though because, and I know it sounds silly, this is a game and this is an alien species we can't compare to real life engineering. 

@Hurleveur As for your comment, I can try to do more post similar to the Peregrine but the peregrine's post stacks a lot of things on top of each other which initially provided to be even *less* cleaner than the current post I'm using (very basic albatross work). 

In the end of all this, a lot of this comes down to the model already being rigged for animation and rendering thereof. If lighting is the major issue, I would prefer to manipulate that (which is also done on other ES ships despite their design) than have to dig back into the mesh again. And with that said, I probably won't come back to this model for a little while because rendering the animation + post is a huge pain and takes time.

**Comment by Zireael07** [comment]
@GefullteTaubenbrust2 is the support struct the green/red thing? It "bulges" out for me too...

**Comment by Saugia** [comment]
Those *aren't* support structures, they're individual tendrils, not connected to the wing, but curve above it a bit so there's depth to the design.

**Comment by GefullteTaubenbrust2** [comment]
Possibly it is a lighting issue idk. I stand by my point about the thumbnail though. It looks like is actually properly 3D and not just an orthographic projection, which just looks strange. I'm a bit too tired to keep arguing about it, so I guess for now we can just see how much lighting helps and go from there.

**Comment by Saugia** [comment]
Old Render:

swan old
swan new

New Render:

swant old
swant new

The lighting does help a bit, especially on the top view. Gun is now under. Changed the post to be more like the Peregrine. Unfortunately, the thumb is still just a result of the angle and reflection. The wing itself is uniform in thickness, it's just that particular glare is more pronounced there due to the curve. I don't think that's reason enough to have to redo the wing mesh though.

**Comment by beccabunny** [comment]
I like it! Can you replace the screenshots in the OP with the new ones for comparison?

**Comment by GefullteTaubenbrust2** [comment]
It is better, that is for sure. I'd need to see it in game, but it's definitely going in the right direction.

**Comment by Saugia** [comment]
@GefullteTaubenbrust2 @beccabunny 

I think while the *lighting* is better, I can/should still bump post overlay layers up/down a bit so it is closer to the darkness of other remnant ships. Though, the Ibis is an example of a brighter one, and sort of the Heron too, maybe it's fine?

swan-new-shipyard

swan-top-new

**Comment by GefullteTaubenbrust2** [comment]
> I think while the _lighting_ is better, I can/should still bump post overlay layers up/down a bit so it is closer to the darkness of other remnant ships. Though, the Ibis is an example of a brighter one, and sort of the Heron too, maybe it's fine?

Yeah it is probably a tad bright, but it looks much better. I can also look past the point with the thumbnail to be honest, I guess it gives it a bit of personality if you will.

**Review by GefullteTaubenbrust2 — APPROVED** [review]
Looks great, I think we're good to merge.

**Review by beccabunny — APPROVED** [review]

**Comment by Zitchas** [comment]
Sorry I can't comment much on the images: I don't have a decent screen to look at them, but from what I can make out it looks good.

So long as it visually fits into the Remnant shipyard: fairly dark, some iridescence, etc... Didn't need to be an exact match, probably healthier to not be an exact match. Remnant are iterating on their ship manufacturing on a regular basis.

**Comment by kestrel1110** [comment]
just gotta say, this is beautiful- reminds me of the romulan warbirds from star trek (specifically the scimitar from nemesis)
i like the curved wings though

**Review by Zitchas — APPROVED** [review]
I think it looks good. I do think it might be a bit on the bright side, but I'm not sure. Anyway, I'm happy with how it looks.

**Pull request merged**
