### PR TITLE
Additional Quarg Outfit Descriptions

### PR DESCRIPTION
**Pull request by Swiftrender**
This is a simple addition that adds some much-needed descriptions to the Quarg outfits that didn't previously have one.

fyi the 5762 person is me just from my team's pc

### CODE REVIEW

**Review by Swiftrender — COMMENTED** [review]
Fixed a copy-paste typo. Updated the graviton thrusters description

**Comment by tehhowch** [comment]
Note that companies often have IP stipulations associated with the use of their property. Please verify with your team that the account has the appropriate permissions for contributing GPL v3 licensed content. If not, you will need to make the commits from an account that is legally able to make that contribution.

**Comment by Amazinite** [comment]
I'd honestly rather just not. We all know the Quarg need updated. Might as well give them snazzy descriptions at the same time as we update them, and leave the descriptions blank now to basically show that it's temporary content.

**Comment by Amazinite** [comment]
Added my own placeholder descriptions in 455209c.

**Pull request closed without merging**
