### PR TITLE
Move human related data into human sub-folder

### PR DESCRIPTION
**Pull request by Darcman99**
Relocate two data files into human sub-folder because all the data in the files are relevant to human content only. There are no non-human starts in the game yet and the current intro missions don't even scratch aliens, so it would be assumed that they belong to the human sub-folder.

One could easily argue that the start/intro of the game isn't strictly human and could be alien if that direction was taken as alternate starts to the game, however as of right now it remains only relevant to humans.

Obviously this is related to #4895 where sub-folders were created in the first place.

### CODE REVIEW

**Comment by Amazinite** [comment]
I went back and forth on whether to put these files in the human folder. I think there's a good argument for putting the intro mission in the human folder, as they do relate entirely to human space (human characters, human sources and destinations, etc.), but I think the start file should stay outside of the subfolders. 

Whereas the intro missions file may expand in the future but always contain intro missions pertaining to humans, the start file may expand in the future to include starts that aren't for humans. (Ref: #1519) The start file is also not really "human" outside of the fact that the only start right now is for humans. It feels like a more general file to me akin to governments (and given #1519, that's exactly what it'd become, as mentioned).

**Comment by Darcman99** [comment]
Then could `start.txt` not simply be moved back to the general area in the same eventual commit that adds alternative starts? It seems pointless to prepare for a feature that we don't even have an estimate for when it might be created. (this is purely from what I know, as far as I know there's no estimate yet)

**Comment by MCOfficer** [comment]
Judging by topics: both files are about the player, not about humans.

**Comment by Amazinite** [comment]
> Then could `start.txt` not simply be moved back to the general area in the same eventual commit that adds alternative starts?

In the same vain, if it’s going to be moved back, why move it in the first place?

**Comment by Darcman99** [comment]
Going off MCOs comment, I understood that the text files were ordered by what they contained. If they are ordered by their topics and what they are meant for then I agree on how it was.

**Pull request closed without merging**
