### PR TITLE
refactor: Replace *_s functions if they're not needed

### PR DESCRIPTION
**Pull request by TomGoodIdea**
**Refactor**

## Summary
Replaced some _s functions with their normal versions. The _s means that the function will perform some nullchecks, which in these cases aren't needed as the arguments point to addresses of variables defined earlier.

Also refactored some win32 `#ifdef`s to avoid returning a pair with one unused element.

## Testing Done
none.

## Performance Impact
No negative impact.

### CODE REVIEW

**Review by tibetiroka — CHANGES_REQUESTED** [review]
`_fopen`, `_wfopen` and `freopen` are deprecated. You switched back to using them and silenced the warning about it.

Do we really care about the performance cost an extra null check that we would use deprecated functions on purpose?

**Comment by TomGoodIdea** [comment]
In this case, "deprecated" means only that Microsoft doesn't like these functions. From the [official docs](https://learn.microsoft.com/en-us/cpp/c-runtime-library/security-features-in-the-crt):
> In this context, "deprecated" means that use of the function isn't recommended. It doesn't mean the function will be removed from the CRT.

**Comment by tibetiroka** [comment]
What's the benefit of going with the non-`_s` versions, though?

**Comment by TomGoodIdea** [comment]
> What's the benefit of going with the non-_s versions, though?

1) Technically, slightly better performance, although in these places it's probably not noticeable.
2) Less code differences between Windows and UNIX.

If we really needed these nullchecks, we'd use *_s functions everywhere, not only for Windows.

**Comment by tibetiroka** [comment]
Maybe we should switch to the C++-style `ifstream` implementations instead of using the old C functions. That would be uniform, and it should work with std::filesystem for path handling, so no need for null checking there either.

**Comment by TomGoodIdea** [comment]
what about localtime?

**Comment by tibetiroka** [comment]
We got some time/date functions in C++20 which (from what I've been told) should be able to fully replace the old C API. I don't have the exact setup to show you, though.

**Comment by TomGoodIdea** [comment]
ok, I'll close this PR then

**Pull request closed without merging**
