### PR TITLE
New Hai Reactor Images

### PR DESCRIPTION
**Pull request by Brick63**
Replaces the current Reactor Sprites because they are just human recolors. Giving the Hai a unique style for outfits will help make them more unique in my opinion

Pebble:
hai pebble core@2x

Geode:
hai geode@2x

Boulder:
hai boulder@2x

[Hai Reactor assets.zip](https://github.com/endless-sky/endless-sky/files/4010345/Hai.Reactor.assets.zip)

### CODE REVIEW

**Comment by beccabunny** [comment]
As I already mentioned, I prefer the current ones and I don't think they need replacing

**Comment by Brick63** [comment]
the current ones are just recolored human outfits, why would a species that has such a different ship design have outfits that look so similar to human outfits.

**Comment by Pointedstick** [comment]
> the current ones are just recolored human outfits, why would a species that has such a different ship design have outfits that look so similar to human outfits.

Agreed. A lot of the Hai outfits suffer from being obvious tweaks and recolors of the human versions, which is rather immersion-breaking.

However, I gotta say it but... these new reactors look like nipples to me. Maybe make them a bit less nipple-like. :)

**Comment by Amazinite** [comment]
Idk man, I feel like it really fits the phallic aesthetic of many ships. #1814 :)

**Comment by Zireael07** [comment]
Maybe change the top of the reactors to resemble the top of the acorn (the one with the differently textured cap), rather than the bottom?

**Comment by Amazinite** [comment]
>the current ones are just recolored human outfits, why would a species that has such a different ship design have outfits that look so similar to human outfits.

I do think that the Hai should have unique looking outfits instead of outfits derivative from human ones, but this ain't it chief.
I actually really like the new Pebble Core you have here, but the other two aren't doing it for me. And I've said it at least a few times before while you were working on these, but I think you're overdoing it on the green. I really like the minimal green aesthetic of the current Hai reactors, but you're taking the green and making it more (too) prominent.

**Comment by Pointedstick** [comment]
Agreed, I like the new pebble, but the others are kinda meh to be honest.

**Comment by Brick63** [comment]
mhm, ill work more on the geode and boulder then

**Comment by Muffindrake** [comment]
Since people are complaining about phallic ships, adding nipples isn't going to help with that matter. (Yes, I don't like them at all. Yes, I will jump down your throat if you replace the current Hai equipment with something worse)

**Comment by Zitchas** [comment]
I like the overall design, but the top part just doesn't fit. Referencing the actual acorns, I'd like to echo  Zireael07's comment about maybe making it look like the top of the acorn instead of the bottom? (perhaps more accurately, the base of the acorn instead of the tip. Acorns don't really have an up/down)

From a more graphical perspective, the base of the acorn has more texture and shape to it that I think might be more interesting to look at than simply a smooth dome and point.

Acorns

**Comment by petervdmeer** [comment]
The green parts on the base of the new Pebble and Geode look a bit painted instead of the "glowing green" that the current Hai reactors seem to have. The base for the new Boulder looks very promising.

For the rest I agree with Zitchas, the current Hai reactors look like upgraded human reactors (similar to how Atomic engines and Hai engines relate), so replacing them by something unique makes sense.

**Comment by Zitchas** [comment]
Given that I think the current Hai reactors do actually look good, I'd like to suggest that once Brick has perfected his new Hai reactors, the old hai images be reserved for a "Human developers updating human stuff after learning from the Hai" plot-line. Because that's really what the current Hai reactors look like.

**Comment by Pointedstick** [comment]
Ah yes, much nicer!

**Comment by MCOfficer** [comment]
The Geode and Pebble are really starting to come together. Compared to their materials, the boulder is looking very synthetic, though.

**Comment by Zitchas** [comment]
Everytime I see the new geode I keep thinking that it and the boulder should switch images, since the geode looks like a giant boulder. Looks good, though.

**Comment by Brick63** [comment]
New boulder design 
hai fusion gimped

**Comment by Amazinite** [comment]
I get the sense that the Boulder is now a little to busy on the detail. 
And I'd say that I also feel like the visual progression between the Pebble and Geode is great, but the Boulder doesn't exactly seem like a progression from the Geode, but it wasn't exactly the case beforehand that there was a visual progression, so this is at least an improvement.

**Comment by Brick63** [comment]
hai boulder@2x
New boulder design based on continued feedback

**Comment by Pointedstick** [comment]
Yeah, I'd remove a few pipes. Hai stuff in general doesn't have a very cobbled-together aesthetic.

**Comment by Amazinite** [comment]
I'd like to see how it looks with the pipes and wires gone altogether.

**Comment by Zitchas** [comment]
I think I'd like to see how it looks with fewer pipes and wires too. That being said, this is a massive improvement over what's in the game, and I'd be happy if it got merged as it stands right now.

**Comment by Brick63** [comment]
hai boulder less pipes

a version with less pipes

**Comment by Zitchas** [comment]
Less pipes is good.

**Comment by Amazinite** [comment]
Much cleaner looking. I'd go with that one.

**Comment by Brick63** [comment]
updated the image to less pipes version, so should be good to go

**Comment by Amazinite** [comment]
@beccabunny @toilethinges @Darcman99 Thoughts on this now?

**Comment by Darcman99** [comment]
I preferred the Boulder with more pipes honestly, but either one is good.
The Geode is pretty nice in shape, however the green glow seems just 'painted' on top of the metal, the originals had depth with the glow and I think that's part of why they were so nice.
The Pebble seems bland in both shape and again, the glow. Without depth to the glow it seems almost cartoonish. This is most evident with the Pebble, the Geode and Boulder have other defining features which sort of hides the issue somewhat, especially under shadowy areas.

All in all, they're getting there, but I think the glow definitely needs to be addressed, take examples from the existing Hai reactors with how they embed the glowing sections within the reactors themselves.

**Comment by Zitchas** [comment]
That's a good point. The original Hai stuff all the green strips looked liked they were inside the reactor shell and were simply revealed by slots / engraving. The new reactor images looks like the green stuff is either surface level material or bulging out from it.

**Comment by Brick63** [comment]
i am working on the green, its going well so far and i will update the PR later today hopefully

**Comment by Amazinite** [comment]
Any final thoughts from anyone?

**Comment by Brick63** [comment]
i am working more on this, i was just waiting on a new laptop to do higher quality projects

**Comment by Brick63** [comment]
hai pebble core@2x
updated the pebble

**Comment by Amazinite** [comment]
@beccabunny @Darcman99 @toilethinges Approving of the images now?

**Comment by beccabunny** [comment]
They're fine

**Pull request merged**
