### PR TITLE
bug fix: three dialogs had `accept` in their text

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Bugfix:** Three `dialog`s had `accept` in them, so I've changed two to conversations, and removed the accept from a third.

## Fix Details
There were three places with text like this:

```ruby
mission whatever
    on something
        dialog
            `Blah blah blah?`
            `    Blah blah blah.`
            `    Blah!`
                accept
```

The `accept` is ignored. In #8504, this will generate a warning that causes the github checks to abort.

Fixes:

1. The two Skadenga dialogs are conversations, matching the fix in [#8483](https://github.com/endless-sky/endless-sky/pull/8483).
2. In the Remnant mission dialog, the `accept` is removed. If [#8505](https://github.com/endless-sky/endless-sky/pull/8505) is merged, then the `accept` can be replaced with a `to decline`

## Testing/Saves

Two of these changes came from #8483, so any testing done there will apply here.

One change removes a spurious "accept" from a mission dialog. That "accept" has no effect, so there's no way that removing it will break anything.

### CODE REVIEW

**Comment by Terin** [comment]
I'm addressing the Skadenga ones in #8483.

**Comment by Zitchas** [comment]
I used a dialog instead of a conversation at that point in the Remnant story because the text is so short that it looks pretty bad, in my opinion, as a conversation. A whole massive grey sidebar for a single sentence at the top.

That being said, the ability to say "no" to a dialog that really shouldn't definitely isn't ideal either, but I figured it was the lesser of the two evils.

**Comment by UnorderedSigh** [comment]
Unless I'm misreading the code, the `accept` does nothing.

**Comment by UnorderedSigh** [comment]
For the remnant one, I kept it as a dialog and removed the "accept"

**Comment by UnorderedSigh** [comment]
My changes do not conflict with #8483, and I do need these three specific fixes for a PR I'm about to open that allows `to display` in dialogs. As a consequence of adding that feature, it complains if there is a spurious `accept` (which causes github checks to fail).

**Comment by Terin** [comment]
_Might_ be worth commenting it out, for when we have #6632 implemented? Although a link between that issue and here might be enough of a reminder.

**Comment by UnorderedSigh** [comment]
> Might be worth commenting out the Remnant accept, for when we have https://github.com/endless-sky/endless-sky/issues/6632 implemented? Although a link between that issue and here might be enough of a reminder.

Working on that now.

**Comment by UnorderedSigh** [comment]
> Might be worth commenting out the Remnant accept, for when we have https://github.com/endless-sky/endless-sky/issues/6632 implemented? Although a link between that issue and here might be enough of a reminder.

I implemented it in #8505, but with a different syntax

```ruby
    dialog
       ...
       to decline
             condition == 123
```

**Pull request merged**
