### PR TITLE
Correct intro mission typo

### PR DESCRIPTION
**Pull request by BartMoyaers**
This pull request fixes a small error in the text of one of the intro missions.

### CODE REVIEW

**Comment by tehhowch** [comment]
Not an error - this is a person's speech and does not need to be grammatically perfect.

You can read about the "this here" speech pattern in a number of references - here's just one: https://www.grammarphobia.com/blog/2012/06/this-here.html

**Comment by MCOfficer** [comment]
> Not an error - this is a person's speech and does not need to be grammatically perfect.
> 
> You can read about the "this here" speech pattern in a number of references - here's just one: [grammarphobia.com/blog/2012/06/this-here.html](https://www.grammarphobia.com/blog/2012/06/this-here.html)

TIL; it really does sound goofy as a non-native speaker.

**Comment by Zireael07** [comment]
Does ES have such a thing as translator comments somewhere? Might be worth putting that bit down. English major here, but non-native, and I didn't get the pattern either.

**Comment by Amazinite** [comment]
>TIL; it really does sound goofy as a non-native speaker.

Well you non-native speakers sound goofy to me sometimes. 😛

**Comment by jafdy** [comment]
The original sounds like a more natural way of saying it, the replacement sounds a bit forced to me. As always with this I recommend saying it out loud.

**Comment by petervdmeer** [comment]
What about just removing the word `here` completely?

**Comment by tehhowch** [comment]
It's character speech. James is old, a bit rustic, and worried he won't be accepted by the locals because he worked for his money. Speaking imperfectly fits.

**Pull request closed without merging**
