### PR TITLE
mini change: fixed(?/improved) some grammar

### PR DESCRIPTION
**Pull request by KiLEdEnNis**
I've been told that the current form is fine, but my change is "more correct"

the change:
prying the lids off them --> prying the lids off of them
EDIT, it became:
prying their lids off

### CODE REVIEW

**Comment by Pointedstick** [comment]
"prying their lids off" would  be equally correct and sound better than the proposed change, thereby bypassing a potential argument entirely.

**Comment by KiLEdEnNis** [comment]
you're right, thanks

**Comment by Bladewood** [comment]
I personally think the original and the original proposal sound better.

**Comment by endless-sky** [comment]
My general policy is, if it's not actually a grammar error and is just a matter of opinion, it's not worth tweaking it. There are probably just as many people who would want it switched back to the original.

**Pull request closed without merging**
