### PR TITLE
Integration test adjustments

### PR DESCRIPTION
**Pull request by warp-core**
**Refactor**

## Refactor Details
Now that it is possible for `test-data` to be more than just save games, I think it makes sense to ensure that the test-data names indicate clearly what they contain (currently, "save" or "mission").

Also, move some missions used by integration tests into test-data objects and inject those as appropriate.

## Testing Done
It'll test itself.

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
better this way, and since the tests run this is good to merge I think

**Comment by Hurleveur** [comment]
we could also rename the names of the missions inside the tests but that could be for another PR

**Comment by warp-core** [comment]
> we could also rename the names of the missions inside the tests but that could be for another PR

The ones inside the save files for the illegal atrocity test?

**Comment by Hurleveur** [comment]
Everything that starts with "%TEST%: " can have it removed

**Comment by warp-core** [comment]
If a mission exists that's going to conflict with one used by a test, it's still going to conflict if the test mission is injected, so yeah, if you want to adjust the names of the missions themselves, or the conditions, that can be done separately.

**Comment by Hurleveur** [comment]
Yeah its not like its causing any problems to use %TEST%:

**Pull request merged**
