### PR TITLE
Minimize precision errors of outfit additions.

### PR DESCRIPTION
**Pull request by flaviojs**
Selling 50000 Fragmentation Grenades, 50000 Laser Rifle and 50000 Nerve Gas accumulates so many precision errors the you are left with 1 unsellable Nerve Gas.
You can get around the issue by loading the game again.

Precision errors are avoided by truncating to `EPS` precision whenever possible.
Note that it is still possible to get precision errors if `count` is big enough to propagate the `mul` precision error to `.5 * EPS`.

Fixes: #3639 (bulk selling processes 1 outfit at a time, so count is not an issue)

Test file provided by @KiLEdEnNis: [sell_issue.txt](https://github.com/endless-sky/endless-sky/files/1722054/sell_issue.txt)

### CODE REVIEW

**Comment by Hacklin** [comment]
While you're at it.
What about Outfit::CanAdd() ?
Shouldn't it at least be `<= -EPS` ?  Or use `PreciseAddMul()` ?


```
         // Allow for rounding errors:
-        if(value + at.second * count < -EPS)
+        if(value + at.second * count <= -EPS)
             count = value / -at.second + EPS;
```

**Comment by flaviojs** [comment]
I rather not touch it unless the precision of big counts is handled. (for that I would need to fully understand the error propagation in the multiplication)

It is fine as is because it can't produce lasting effects.
Unitary counts have no problems. Big counts might produce an "off by x" result but you can just buy/sell what was left out after the bulk operation ends.

**Comment by flaviojs** [comment]
@endless-sky 
After thinking about this, I'm pretty sure there are precision issues all over the place.
The usual double has enough precision to fully hold 15 decimal digits.
With a target `const double EPS = 0.0000000001;` (in Outfit.cpp) you effectively start losing the less significant data around `100000.0000000000` (100K).
With `out.precision(8);` in (DataWriter.cpp) there is also precision loss.

I want to know if you are open to using `mpf_class` (from `gmpxx.h`) in DataNode and Dictionary (maybe more). Is it a "definitely no" or "you can give it a try"?
It introduces dependencies to `gmpxx` and `gmp`, will probably bleed out to lots of other code and will probably impact CPU performance negatively (not sure by how much).

**Comment by Hacklin** [comment]
How accurate does ES have to be?
Would it be enough to disable Subnormal/Denormal floats?
And round towards 0 instead of towards -Infinity?

I've never used Multiple Precision or BigNum Arithmetic.

**Comment by tehhowch** [comment]
As far as incorporating GMP, it seems they report instabilities on a variety of platforms. 

https://gmplib.org/#STATUS

I don't know that it would be wise to include this library without knowing more about the issues encountered, and the user cross-section that would be affected by it.

**Comment by Zitchas** [comment]
We have another case of this come up again, reported by matthew.najmon on the Discord.

**Comment by petervdmeer** [comment]
This PR appears to reduce/minimize the precision errors, while PR #5498 appears to completely remove the precision errors in the calculations where the precision matters. If I can choose between a PR that reduces the problem and another PR that completely removes the problem, then I prefer the PR that completely removes the problem. (So #5498 is preferred by me over this PR if that PR works as advertised.)

**Comment by petervdmeer** [comment]
Closing this PR (which minimizes the problem) in favor of another PR which removes the problem completely.

**Comment by Zireael07** [comment]
You might want to mention which PR is that, as 5498 was closed too (and that one is mentioned above as fixing the problem completely... so I'm confused)

**Pull request closed without merging**
