### PR TITLE
dialog random [Ref Issue #1856]

### PR DESCRIPTION
**Pull request by kozbot**
Add random qualifier to dialog.  Used uniform distribution. 
Reference Issue #1856 
Example:

```
on accept
	dialog random "anything here is ignored when it sees random and will cause a PrintTrace"
		"This dialog will randomly be used."
		"This is another random dialog."
		"Huzzah for random variety!"
```

### CODE REVIEW

**Comment by jafdy** [comment]
For variable dialog use

```
on accept
	dialog 
		random "anything here is ignored when it sees random and will cause a PrintTrace"
			"This dialog will randomly be used." 1
			"This is another random dialog." 2
			"Huzzah for random variety!" 3
```

The indent is more like the normal way conversations are written.
The numbers next to the chance show the relative likelyhood ("Huzzah for random variety!" is used 3/6 times or 50%).

**Comment by jafdy** [comment]
I was thinking in terms of random paragraphs within a diolog.

**Comment by Pointedstick** [comment]
Honestly that looks too complicated and confusing to me--not very user-friendly for mission creators. It's hard for me to parse what's going on in your example.

**Comment by Pointedstick** [comment]
What is "inline" for? I don't understand that part.

**Comment by Pointedstick** [comment]
Ah, I get it now. Do we really need this inline functionality at all? It seems like it adds a lot of complication for very little gain (IMHO) since you can just copy-and-paste the paragraph and make whatever changes you need:
```
dialog
	random
		"Oh no! The ship is on fire!"
		"Oh no! The engines are on fire!"
		"Oh no! The main computer core is on fire!"
		"Oh no! My pet gorilla is on fire!"
		"Oh no! The cargo of Limburger cheese on fire!"
		"Oh no! The delegates to the 453th Intergalactic Firefighters Union Convention are on fire!"
````

Not the most elegant approach of course, but it avoids adding a very complicated syntactic directive that's likely to be really confusing to a lot of people.

**Comment by Pointedstick** [comment]
Excellent! Thank you so much for your hard work on this and understanding.

**Pull request closed without merging**
