### PR TITLE
Corrected osprey sprite

### PR DESCRIPTION
**Pull request by beccabunny**
The osprey sprite isn't symmetrical, but the mosprey is. Using tehhowtch's mosprey blender model as a base to make them fit, this PR should correct it. The change is very minor, so i am not sure if a copiright modification is required
[osprey.zip](https://github.com/endless-sky/endless-sky/files/3050656/osprey.zip)

### CODE REVIEW

**Comment by beccabunny** [comment]
Alright, i updated the image and the files following @tehhowch 's suggestion

**Comment by Amazinite** [comment]
It's larger even than the 2x image...
Could just grab the 2x image and downsize it to replace this one. If the file size is still larger somehow then clearly conservation of matter is a lie.

**Comment by comnom** [comment]
>I'm still not sure why this image is 400% larger than the original.

The image is alright. The file size just looks like no compression was used. Both blender and gimp have their own compression settings (blender stores file settings, but gimp stores user settings), so it's understandable it would vary.

**Comment by MCOfficer** [comment]
I call png compression. When saving this file with maximum compression, i get 34KB.

**Comment by Pointedstick** [comment]
Yeah maybe you could run it through `pngcrush` or something.

**Comment by beccabunny** [comment]
Done, now it is smaller than the game one

**Pull request merged**
