### PR TITLE
Outfit factory: Outfits that Produce Other Outfits

### PR DESCRIPTION
**Pull request by Ferociousfeind**
**Preface:** Reposting the PR, this time on a branch I actually have write access to. So I will be able to actually work on it. Here is the original PR text (which still will be updated as changes to syntax etc occur) for posterity and for meeting the requirements to PR:

**Feature:** This PR implements a feature taking advantage of the dynamic nature of the cargo and outfit variables, by allowing outfits to modify the contents of either (or both) while in-flight.

## Feature Details
Outfits, once installed, can remove outfits from outfit or cargo space and (simultaneously) add outfits to outfit or cargo space as defined by certain syntax. This is anticipated to be used for two primary purposes- mining-related refineries which take outfits mined from asteroids and converts them into higher-quality outfits over time, and combat-related mini-factories which consume raw materials and produce ammunition for use in combat, without stopping at a planet to restock. There are other possible uses as well.

Planned before this is merged is the inclusion of the typical stats- shields, hull, energy, fuel, and heat, along with their DoT variants and relative values and such. Perhaps all those 20 attributes could be united under one functionality, in a different PR? Weapons and engines access them, and this would aim to add factories accessing them too. A lot of things access these five stats in these four different ways [regular, relative, DoT, and relative DoT, all together].

One of the parameters of the factory outfits is "speed", which is currently a misnomer. It describes the frames between each attempt at producing the outputs, and is more analogous to "reload" than "max speed". )Low "speed" equals high rate of production.) Speaking of speed, too, I am not 100% set on the way it works. Ideally, the timer set by "speed" (or, say, just reuse the "reload" term) only ticks down on a frame where all the inputs are present (because then it can actually begin the work of producing the outputs), and _then_ if there is no space for the output, it hangs on 1 (or 0?) on the timer, until it has both all the inputs and also the space to place all the outputs.

As well there is a small bug or oversight, where remaining space is not properly accounting for the consumption of the inputs in the process of production of the outputs. This means if an outfit consumes 10 tons of stuff to produce 3 tons of stuff, you need at least 13 tons of space to be able to use it- 10 to store the inputs, and 3 to store the outputs, even though the 3 tons of stuff could go in 3 of the 10 tons of space vacated by the process of producing the outputs.

Also there are (EDIT:) NO merge conflicts that I need to iron out before it can be merged. EDIT: simply manually copying the changes over cleared the merge conflicts. Most likely it was whitespace changes tripping up github.

## UI Screenshots
As of now, the outfit screen does not properly account for the "production" attribute, and doesn't display its abilities. This is likely to prevent the PR from being merged for a while, until the data can be displayed.

## Usage Examples
As of posting this PR, and likely to be updated as changes come, the added functionality works like this:
EDIT: the syntax has been changed.
```
outfit <outfit name>
    production
        (input | output) (cargo | outfit)
            <outfit name> [<number>]
        speed <frames>
        "shields" <amount>
        "hull" <amount>
        "energy consumption" <amount>
        "fuel consumption" <amount>
        "heat production" <amount>
```

"input" is what the outfit consumes, "output" is what the outfit produces. "cargo" means it pulls from/puts into the cargo bay, "outfit" means the same for the outfit space of the ship. "speed" is, unintuitively, the number of frames between each attempted production. 
EDIT: each of the added values are the amount consumed on producing the output, except for heat, which is produced, not consumed. (Make it a negative value to consume heat.)

## Testing Done
Created a "piercer factory" which consumes iron and silicon, the mined outfits, and produces piercers into your outfit space. With a piercer launcher installed, this factory installed, and the weapons to mine asteroids and collect the requisite iron and silicon. Additionally, created a "philosopher's stone" outfit (though perhaps an "alchemical stone" or "midas's touch" would've been more fitting?) which consumes lead in your cargo bay and produces gold into your cargo bay (to turn lead into gold!), which revealed a fatal (well, niche) flaw in the current implementation. Future developments are discussed above.

More testing should be done to confirm that the feature works as intended as it is worked upon.

## Performance Impact
I do not think this will be intensive, but it does have the _ability_ to significantly slow down the game. For example, if you have a million outfits with this ability installed, you will be counting down a million counters each frame, and likely checking your ship's outfit makeup a million times every frame, it'll get laggy. But I do not think that is a likely vanilla scenario.

**Reminder:** This is a repost which I can actually work on. With this, I'll close #7426

### CODE REVIEW

**Comment by RisingLeaf** [comment]
Just one thing as a side note, you might want to put production class and helper functions in a new file.

**Comment by ravenshining** [comment]
Oh, this is exciting!  We've been talking a *lot* about this sort of functionality over in the Korath channels on S6 for use in some outfits that we've been working on for the Korath, particularly for the Ikatila'ej in #7264 .

We were thinking of it happening on a per *day* basis rather than per *frame*, but hey frame is awesome, too, we'll take it!

**Comment by Ferociousfeind** [comment]
There is the good possibility that `speed`, or whatever is best to replace that key word with, could accept `"daily"` as an argument, to turn it into a once-a-day event, rather than a once-per-X-frames thing. Just depends on how much of a headache porting the code to occur on day changes too

**Comment by Amazinite** [comment]
Closing, as there has been no movement on this draft PR since it was opened five months ago.

**Pull request closed without merging**
