### PR TITLE
feat(content): remove Korath prefix from ship/outfit names, provide some native names

### PR DESCRIPTION
**Pull request by ravenshining**
----------------------
**Content (Semantics)**

## Summary

All outfits that begin with "Korath" have been renamed to something slightly more descriptive
All Korath ships have been given native Korath-sounding names

-----------------------
**Feature:** This PR implements a feature request detailed and discussed in PR #6955 

@Amazinite noted on #6955 that the name "Raider Mark XLII" is extremely clumsy.  Although I am the one who proposed it, I wholeheartedly agree, and proposed instead moving to a naming scheme for ships that uses native Korath.  This was found agreeable, and it was further proposed on-stream that outfit names be looked at as well.

Tables of names:

Old name -> New name
 - Korath Raider -> Palavreb
 - Korath Raider Mark XLII -> Tubfalem
 - Korath Dredger -> Ranolenred
 - Korath Chaser -> Olohfec
 - Korath World-Ship -- As-Is, names will be given with differentiation in KEE Stage II
 - Korath Repeater Rifle -> Thermal Repeater Rifle
 - Korath Grab-Strike -> Grab-Strike Turret
 - Korath Banisher -> Banisher Grav-Turret
 - Korath Warder -> Warder Anti-Missile
 - Korath Detainer -> As-Is, desc. calls attention to this instead
 - Korath Fire-Lance -> Fire-Lance
 - Korath Repeater -> Thermal Repeater
 - Korath Repeater Turret -> Thermal Repeater Turret
 - Korath Piercer -> Piercer Missile
 - Korath Piercer Rack -> Piercer Missile Rack
 - Korath Piercer Launcher -> Piercer Missile Launcher
 - Korath Mine -> Cluster Mine
 - Korath Mine Rack -> Cluster Mine Rack
 - Korath Minelayer -> Cluster Mine Layer
 - Korath Disruptor -> Shield Disruptor Turret
 - Korath Slicer -> Husk-Slice
 - Korath Slicer Turret -> Husk-Slice Turret

Names for Exile ships upcoming in future PRs:
 - Probe -> Ivonref
 - Miner -> Nrahfarem
 - Shuttle -> Lakra-Kobfev
 - Seedship -> Rakihihfes
 - Trawler -> Katofet
 - Ravager -> Onnrannrer
 - Freighter -> Nralah
 - Conqueror -> Tomtarec
 - Tanker -> Itnrak
 - Traveller -> Racakamic
 - Herder -> Aca'fec
 - Habitat -> Rala'omet
 - Refuge -> Rai'naronrer
 - Refabricator -> Ik'atilhajel
 - Haven -> Anlo'pathe
 
Names for Efreti ships upcoming in future PRs:
 - World-Ship -> Nacasairot
 - Contorted Core -> Ikrikopespeb
 - Safe Blessing -> Haspebrafa
 - Miner -> Lrabfarec

## Methodology

To quickly generate the names for Korath ships -- all 23 of them, from the four included here to upcoming content -- and other Korath text, I made a little cipher that I could automate.

UPDATE:  After digesting @Anarchist2 's feedback below, I conducted a more thorough review of Korath text, and of languages that may be similar enough to merit use in a cipher.

On the text - this time, I divided the corpus by faction, as you can see in the third sheet in the Korath google spreadsheet:
https://docs.google.com/spreadsheets/d/1AAI_z0ctIzZug4BbCBG_mHBZVNe2AGqB5U1HITUBzSs/edit?usp=sharing

I've gone into greater depth on Discord as to what is meant by and potential lore behind the Kaliptari and Korsmanath regions, suffice to say for now that Kaliptari, Sestor, and Mereti are all considered common to both dialects, while Korsmanath is exclusive to Exile.  The current fragments from the phrase constructor are considered exclusive to Efreti, since they are a later work and there used to be an alternative version that was only ever used by the Exiles.  From that, I came up with the following character breakdown:

Screenshot_20220723_183616

As for language to use in the cipher, I progressively narrowed the field by choosing:
 - languages that have the relevant data easily available and can be auto-translated
 - of those, which use Latin, Cyrillic, or Greek script, so I can understand what I'm reading while I do this
 - which use enough characters, once accents are purged, to represent all the characters used in Korath
 - which - as Korath does - have a vowel as the most common letter, and a consonant as the second most common
 - which have the closest ratio of vowels to consonants to Korath (about 40% of Korath characters are vowels)
 - of those, those which use the fewest diphthongs, keeping an even distribution as @Anarchist2 pointed out
 - finally, running a sample text through the steps to see what just looked and sounded best
Ultimately, I settled on Indonesian.

Therefore, the revised cipher is:

1. Translate the text into Indonesian
2. Reverse the order of letters in words
3. Employ a character substitution for Exile or Efreti as detailed below
4. If the result looks really bad, repeat from 1 with a related word.
6. Clean up the name with additional letters for Efreti or apostrophes for Exile

```
Indonesian	Exile	Efreti
A		A	A
E		E	E
I		I	I
O		U	U
U		O	O
B		H	B
C		D	V
D		S	T
F		J	Y
G		N	L
H		P	H
J		V	W
K		T	S
L		M	N
M		F	F
N		R	R
P		B	C
Q		Z	Also T
R		L	P
S		'	M
T		K	K
V		Q	Also R
W		C	G
X		Y	Also S
Y		G	D
Z		W	Also K
```

## Notes
Rather that provide more detailed names for outfits, they could be given fully- or partially- Korath names, as the ships do, but I thought this would be excessive.  I may still do this, however, for outfit names that still use the size descriptors "tiny," "small," "medium," "large," & "huge."

There are a number of outfits whose names are clumsily presented and could be cleaned up with a simple rearrangement -- `Thrusters (Planetary-Class)` would be better as `Planetary-Class Thrusters`, but I didn't think that small a change would be worth having to add them to `depreciated outfits.txt`.

For fully Korath names, randomly mashing out Korath-sounding words may be quick and perhaps desirable for the odd word here and there, but when dealing with large amounts of text, I thought it would be easier to use a cipher.

## This PR's relationship to the Korath Exiles Expansion
I had planned to PR another branch -- the non-abridged [korath-renames](https://github.com/ravenshining/endless-sky/tree/korath-renames) branch -- *after* Stage I was merged.  Alternatively, if these names are approved, I could merge that branch into #6891 before it is merged -- see [pull request 15](https://github.com/ravenshining/endless-sky/pull/15) on my fork.

The latter option of merging this into #6891 rather than here directly would involve the least headache for *me*, but, now that Stage I has been tagged for 0.9.15, I thought I'd leave the options open.  More importantly, I'd like public comment on these renames not to get buried by or distract from all the new content discussion in, or delay, #6891

### CODE REVIEW

**Review by Anarchist2 — COMMENTED** [review]
In my opinion, only one of the native Korath names feels Korath-y, especially when compared to the existing samples of Korath language. One standout feature of the language is that, almost always, words can be broken down into simple groups consisting of a vowel sound surrounded by one or two consonant sounds. Take, for example, the Kor Efreti first contact sentence:
> "Humani efreti, naskoor amasavarkta."

This can be broken down into its base sounds like such:
> "Hu-ma-ni e-fre-ti, nas-koor am-as-av-ark-ta."

On the other hand, this was my attempt at breaking down the Dredger's new name:
> "Kaoakst"
"Ka-o-akst"

This is a rather messy way for a word to be broken up by Korath language rules. The only way the vowels can be broken up is if you pronounce the singular "o" as "oh", giving it a consonant sound (splitting it as "Kao" can also work, but requires using an "ao" vowel sound, which I don't think ever pops up in the Korath language).

> "Vertsipmo"
"Vert-sip-mo"

This is definitely the most Korath-like of the four names, and I'm not whether it needs any changes. 

> "Kakafrolj"
"Ka-ka-frolj"

Repeated sounds are already not present in any existing examples of Korath language, but the biggest problem lies in the final sound of the word. Beyond "frolj" having one too many consonant sounds, the sound "j" doesn't appear anywhere in the Korath language. Not in ship names, not in system names and not in the limited samples of Korath speech that exist.

> "Rekaniz"
"Re-kan-iz"

Similar to above, the "z" sound doesn't appear anywhere in Korath text.

**Comment by Zireael07** [comment]
@Anarchist2: "ao" is, precisely speaking, a diphtong not a vowel sound, but I applaud the rest of your linguistic analysis for a fictional language <3 <3

**Comment by ravenshining** [comment]
> Edit: Okay, I'm not sure how I managed to miss the explanation in the main post, but I did. Regardless, the above statement about the structure of words as vowel-consonant groups still stands, and I'm also not sure where you found examples of z and j in Korath text? I couldn't find anything when I searched.

Thank you for that thoughtful analysis!   I can't respond in full at the moment, but I can quickly address this point - I did not include only Korath text in the game at *present*, but, in order to obtain a decent sample size, Korath content that was in the game when I first got in to ES in the 0.8.x days.  There's outfit names with j, and a number of small sentences.  Nevertheless those are certainly the amongst the least likely letters to be used, as you can see from the substitution chart.

**Comment by MasterOfGrey** [comment]
> I did not include only Korath text in the game at _present_, but, in order to obtain a decent sample size, Korath content that was in the game when I first got into ES in the 0.8.x days, some of which I intend to resurrect in a modified form for the Exiles campaign in development. There's at least one outfit name with a j - one of the thrusters I think - and a number of small sentences to draw from.

One thing of note: MZ reputedly changed his mind on how Korath worked part way through, which is why some of the automata systems have sibilant sounds when earlier ones didn't.

From the google doc he dropped us a while back: `Korath language is somewhat similar to German, with lots of hard consonantal sounds and long, compound words. Because they are reptiles, their speech contains a lot of sibilant sounds.`

If sounds are _only_ present in very old stuff that was removed, that's possibly a good argument for excluding them.

**Comment by ravenshining** [comment]
On the other hand, it makes sense for there to be two different sounding versions of Korath, even in fact two different languages.  In the Wanderers storyline, it's mentioned that your translator, who speaks the language of the Efreti, has some difficulty understanding the Exiles, that they have a strange dialect with unfamiliar sounds and gestures.

Now, IRL I speak Hawaiian, and if pressed, because I've studied how polynesian languages have evolved and drifted apart, I can listen to something in Maori or Rapa Nui, and get the gist of the message, or sit down and translate it, despite not actually speaking those languages.

I imagine Korath could be similar - we have an Efreti and an Exile language, both very similar and coming from the same roots, but after several generations of isolation, as well as being under different influences and having different proportions of those same roots, have drifted apart.  A professional translator - or linguistics geek - might be able to understand both given only one, but not necessarily your average speaker.

That wouldn't excuse my method above being inadequate for converting words specifically into *Efreti* Korath, for when it comes time to handle that.  At the present I only need 3-7 words, only one of which I've written down - Cesmip'tlad, for the Efreti descendant of the World-Ship.

Perhaps, then, I should take a closer look at the Korath corpus, and see if I can tease out the earlier works from the later ones - using the earlier works as the example for Exile, and the later ones for Efreti.

**Comment by ravenshining** [comment]
After some exhaustive research, I've re-done the method I used to come up with Korath-sounding words.  Top post updated to detail this.

Some fun notes:
- Dredger had to go through twice with a different word, it came out "toilet" the first time
- A *lot* of ships wound up with names ending in -eb, so I changed a lot to have their ending letter match the original first
- I used the log entry describing the Korath faction(s) as my sample text when testing ciphers.  Here's how it came out in the final version:

__Efreti:__
Hkarus hanata nikcer, reina natecib lrad adrhadanig ricfah adrhoronem rovrah: akus-akus rovrah rat horonem keranc samorit henu aca lrad adrsacfak rasacoref lrarec aratoam lrad fawes. Acarebeb imsay hkarus rahakreb. Ehk "rus ikerye" nallrik it kacfek ralrotrinrec irat tnruglrir lraot rat ralrobohreb iafat ralret lraot. Hkarus adrrian, cotih ialabem lraru ralraob it kaset ikri imsanal, hanek obredref airot aimoraf sokro irovref rarasaf rat raaitemrec. Rat hiben fanat it lraor hkarus, aot rasomac rameb erurt lrarec mikafuku, lrad naresit ialabem rus ikeref rat rus rukmem, ivrosrek fanat ralraowrec acrak rihsa. Aseref lraredref caikem lrowrolrec es hadanig lraor aseref, somafrek lraot.

__Exile:__
Pkalut pamasa mikbel, reima masebih nrag agrpagamic libfap agrpolome' lodrap: akut-akut lodrap ras polome' keramb ta'olis pemu aba nrag agrtabfak ratabolef nraleb alasoa' nrag favet. Abaleheh i'taj pkalut rapakleh. Epk "lut ikelje" mannrik is kabfek ranrosrimleb ilas smlucnril nlaoz ras ranrohopleh iafas ranres nlaoz. Pkalut agrriam, bosip ianahe' nralu ranraoh is kates ikri i'taman, pamek ohlegref airos ai'oraf tokro ilodref rarataf ras raaise'leb. Ras pihem famas is nraol pkalut, aos rato'ab la'eh eruls nraleb 'ikafuku, nrag maretis ianahe' lut ikelef ras lut luk'e', idrotlek famas ranraovleb abrak lipta. Atelef nralegref baike' nrovronreb et pagamic nraol atelef, to'aflek nlaoz.

**Comment by ravenshining** [comment]
Over on Discord, I've gotten a complaint that "Shield Disruptor Turret" sounds too generic.  Unfortunately no alternatives were suggested, so in the meantime, if anyone would like to suggest one before I come up with something, please do.

**Comment by ravenshining** [comment]
> There are a number of outfits whose names are clumsily presented and could be cleaned up with a simple rearrangement -- Thrusters (Planetary-Class) would be better as Planetary-Class Thrusters, but I didn't think that small a change would be worth having to add them to `depreciated outfits.txt`.

@Amazinite , you brought up this bit on the stream this morning.  At the time, I thought you were pointing it out for the benefit of the viewers, to remind them of what's necessary... but re-watching the stream tonight, I realised you may have misinterpreted this statement and were addressing me?

So to be clear, what I'm saying here is that I don't think it would be worth *making that name change*, **because** they'd have to be added to `depreciated outfits.txt`; I was **not** saying that it that the change *should* be made and that, in the case that they are changed, it would not being worth adding them to `depreciated outfits.txt`.

**Comment by ravenshining** [comment]
Closing as the merge of #6891 rendered this PR unsalvagable.  A new branch has been PR'd with similar changes and more, #7101

**Pull request closed without merging**
