### PR TITLE
Fix for non-repeating coalition jobs

### PR DESCRIPTION
**Pull request by mootootwo**
Fix for https://github.com/endless-sky/endless-sky/issues/2062

Sorry, I am a complete git noob.  Feel free to delete this and fix it properly.

### CODE REVIEW

**Comment by Bladewood** [comment]
You and I are in the same boat with pull requests.

You've done it right for now, but once Michael pushes a commit (that is, one that does not involve accepting one of our pull requests), the whole thing will come crashing down.

**Comment by SonEasterZombie** [comment]
but blade, you got everyone to approve that last one you did.

**Comment by Bladewood** [comment]
They're just approving what the pull entails, I'd assume.
I myself am pretty much a newbie when it comes to creating pull requests.
I don't know what to do if it goes wrong.
And I'd let everyone down.
[Cue sad music.](https://www.youtube.com/watch?v=F7zCFpQa4gQ)

**Comment by KiLEdEnNis** [comment]
@Bladewood I hardly know how to make a PR myself
go to a file, edit, make PR, & hope you see no other mistakes

**Comment by SonEasterZombie** [comment]
@Bladewood I probably would have made the request myself if I wasn't afraid of failure.
Literally my only experience with github is Endless Sky so yeah
but I don't think you could screw up 'switch 4 guns to 6 and 6 turrets to 4'

**Comment by KiLEdEnNis** [comment]
@SonEasterZombie you should know Bladewood better ( ͡° ͜ʖ ͡°)
jk

**Comment by Bladewood** [comment]
@SonEasterZombie It's not making changes to the game that are difficult. Those are trivial.
It's making the pull requests themselves and maintaining them.
I am nearly useless with GitHub.

**Pull request merged**
