### PR TITLE
Bulk Freighter / Container Transport / Class C: Divergent stats & Variants

### PR DESCRIPTION
**Pull request by ravenshining**
**Content / Balance (ship data)**

## Summary

This PR implements divergent stats for the Bulk Freighter, Container Transport, and Class-C Freighter drafted in #5892  and omitted from #5949 , also diverges their variant loadouts, adds a Long-Haul BF and Short-Haul CT variant, and makes further fleet adjustments.

The Bulk Freighter is significantly larger by volume than the Container Transport, and at the same time has much less surface area.  So, overall, the BF gets more cargo space, two more jumps worth of fuel (to suit its role in servicing more remote locations), and has less drag than the CT, but the BF suffers from severely reduced heat dissipation.  Yet more extra space in the BF is used to provide berths for crane operators - so the BF has a higher crew requirement and bunk count, but fewer free bunks.

This doesn't make much difference to the stock loadouts -- so the CT gets a price discount due to its lower cargo space and more modular design -- but it becomes a large factor in optimising variants and the Class-C derivative.

Long-Haul BFs, equipped with ramscoops and with Scout or ramscoop-equipped Berzerker escorts, can be occasionally seen throughout a larger area of the galaxy.  Short-Haul CTs, meanwhile, optimised for making profit in safe shipping lanes, are found more in the Core and servicing Paradise Planets.

Screenshot_20210514_200807

## Save File

I was using this save file to test and balance the variant loadouts, it has a number of them present at the end of the ship list... more or less.  I'll have to upload a better one later.
[star test.txt](https://github.com/endless-sky/endless-sky/files/6482465/star.test.txt)

## PR Checklist

This PR contains no new art assets.

## UI Screenshots

- Basic overview (default loadouts are unchanged):

mapcompare

- **Bulk Freighter (Blaster)**

Because the BF has lower heat dissipation than the CT, the 5-Quad-Blasters variant would overheat, so it drops two of them for anti-missile turrets.  At the same time, it doesn't need as much engine power, so it saves some heat by stepping down to plasma engines.  The CT version is mostly unchanged.
bf-blaster

- **Container Transport (Hai)**

Because of the CT's increased heat dissipation, it can safely mount a larger power plant to power an extra pulse cannon.  Because it's slower, it needs a better set of engines.  The BF version is mostly unchanged.
ct-hai

- **Bulk Freighter (Proton)** and **Container Transport (Proton)**

This variant seemed to be weirdly not filled out despite having an outfit expansion, so I made use of the extra space to add an anti-missile turret to both, a water coolant system to the BF, and an upgrade to Sidewinders to the CT.
bf-proton
ct-proton

- New **Bulk Freighter (Long Haul)**

bf-lh

- New **Container Transport (Short Haul)**

ct-sh

- **Class-C Freighter**

I kinda just went all-out on this one, since it hasn't been put to use yet.  Note that the original definition for the Class-C predates the Proton Turret; I thought a Proton Turret + Quad Blasters felt more "Syndicate" than lasers while offering the same DPS.  As for the atomics, the S-970, etc.... well, if it's meant to ambush pirates, I think it needs more threat than just the drones.

There's a lore question to be answered here - Is the Class C a converted Bulk Freighter, or is it a warship designed to fit into a Bulk Freighter's outer hull?  The former might suit the unedited stats and a storyline where this ship is a failure, the latter, these stats and a storyline where it succeeds.

cc

Expanded description for the Class-C "Freighter"
cc-sy

## Usage Examples

Ramscoop-equipped BF & escorts:
```
	variant 1
		"Bulk Freighter (Long Haul)"
		"Berserker (Strike)" 4
```

CT for safer areas:
```
	variant 1
		"Container Transport (Short Haul)"
```

## Testing Done
Flying the various variants around Shaula and getting killed in them...  or seeing how long I could *avoid* getting killed in the Class-C.

## Performance Impact
N/A

### CODE REVIEW

**Comment by ravenshining** [comment]
So far, the only feedback I've gotten is that the higher crew requirement on the Bulk Freighter seems too high. I would like to point out that:

- 13 is the same number of crew required for the Deep River
- There are 12 cranes to operate, anything less than 12 crew does not make much sense if the requirement is because of the cranes.

For now I'll lower it to 12.

**Review by EjoThims — APPROVED** [review]
Near as I can see, all this should be waiting on at this point is getting updated to master, yes?

IMO this should definitely be merged first before big overhauls to mass, that way we have the differentiated baseline to work from.

**Comment by Amazinite** [comment]
> Near as I can see, all this should be waiting on at this point is getting updated to master, yes?

You don't need to update to master unless there's a merge conflict, which this PR doesn't have. ~~No, I have no idea why some people obsessively update their PRs to master.~~

**Comment by Zitchas** [comment]
I think the lore fits best if it is a bulk freighter that has been converted to being a carrier. More interesting that way too. I would imagine it sight to have a bunch of interference plating too.

**Comment by ravenshining** [comment]
> I think the lore fits best if it is a bulk freighter that has been converted to being a carrier. More interesting that way too. I would imagine it sight to have a bunch of interference plating too.

Of course, I disagree - I find it more interesting for it to be a Q-ship from the keel-out - or I wouldn't have taken the time to make these stats :-P

More importantly, however, is that I think this would be a more *fun* ship to have around, should the player seize one somehow.  ~~also in the year since opening this PR I've had two computers fail and don't want to go back in and deal with this again if the PR is fine as-is unless you want to wait even longer~~

Ultimately, however, what matters is how Derpy is writing his story, and what fits best in with that.

**Comment by Amazinite** [comment]
I think the increase to required crew on the Bulk Freighter might be a bit much, but it's not like we can't tweak things in the future. As Ejo mentioned, I plan to tackle a ship mass rework relatively soon, and I also want to make some more targeted changes to various underperforming ships, Bulk Freighter included (as the Behemoth seems to be the much, much more popular pick among human heavy warships), so I'll just merge this as our new baseline.

**Comment by ravenshining** [comment]
> As Ejo mentioned, I plan to tackle a ship mass rework relatively soon, and I also want to make some more targeted changes to various underperforming ships

On that note, would it be helpful for us to boot some of the new Korath ships into PRs before then?  I realise I haven't gotten much done on that front, but, having roped Ejo and some others into it recently, plus as of _today_ I've become a lot less busy with certain IRL priorities that had me constantly flying everywhere, maybe we could do some cramming if there's a deadline.

**Comment by Amazinite** [comment]
> On that note, would it be helpful for us to boot some of the new Korath ships into PRs before then?

Not really. If the PR is posted and then the changes are made then the PR will just need to be updated to adjust to the new changes. If the PR is posted and merged before the changes are made then it's more work for me and will take longer to get the mass changes in. (I've postponed finishing my own PR #6438 just so that any such mass changes don't take longer for the main game and I can just tackle that PR on its own.) Might as well just hold off on anything then react accordingly to the changes once they're finalized.

> maybe we could do some cramming if there's a deadline.

There's no deadline for anything at the moment. Although we are definitely getting near the tail end of pushing stuff into v0.9.15 here. Not sure if you're aware, but tehhowch and MCO have developer perms for the game on Steam now, so we're looking to update Steam to v0.9.14 in the near future, and a v0.9.15 release should follow shortly after that. But until v0.9.14 is up on Steam, no deadline to worry about for v0.9.15.

**Comment by ravenshining** [comment]
> Might as well just hold off on anything then react accordingly to the changes once they're finalized before getting to the PR phase.

Got it.  That'll give me some time to get my new Blender machine up and running and make sure everything looks as it should or better.

> Not sure if you're aware, but tehhowch and MCO have developer perms for the game on Steam now, so we're looking to update Steam to v0.9.14 in the near future, and a v0.9.15 release should follow shortly after that. But until v0.9.14 is up on Steam, no deadline to worry about for v0.9.15.

Cool.  Glad to hear there ought to be less waiting games going forward.

**Pull request merged**
