### PR TITLE
typo: Incipias typo fixes

### PR DESCRIPTION
**Pull request by Tangle10**
**Typo fix**

The Incipias thrusters should be called thrusters since they're thrusters and not engines, but they're called engines instead. I was volunteered to make this PR when I noticed the issue. However I am fatigued. So blame any mistakes or oddities on that.

## Summary
All your engines are belong to thrust.

### CODE REVIEW

**Comment by Saugia** [comment]
This will have to be done for High DPI as well.

**Comment by Tangle10** [comment]
> This will have to be done for High DPI as well.

oh shit right

**Comment by Saugia** [comment]
(And copyright files in both base and high dpi.)

**Comment by ziproot** [comment]
Save file for testing: [Test Pilot~Incipias Thruster.txt](https://github.com/user-attachments/files/16325515/Test.Pilot.Incipias.Thruster.txt)

**Comment by Tangle10** [comment]
> (And copyright files in both base and high dpi.)

OH

**Comment by Tangle10** [comment]
> (And copyright files in both base and high dpi.)

No, actually; the outfit images are in as "images/outfit/mh?*"

**Pull request merged**
