### PR TITLE
Drag is applied to ships above max speed

### PR DESCRIPTION
**Pull request by Elyssaen**
**The Problem:** Firing/hit force allows a ship to go faster and faster, well beyond the max speed, as drag never applies. The easiest way to demonstrate this going silly is with a Drak Distancer, with blurring star field and distancer flares drawing off the ship:

image

**Proposed Fix:** A ship travelling faster than it can reach with thrusters (and afterburners) will always lose speed to drag, not just when accelerating. Afterburners _aren't_ affected: you can still surpass your max speed with afterburners and then drift at that new value. Above that, you'll decay down to it.

Had to do a bit of a restructure to Ship::Move, but not too much. An `applyDrag` boolean is used, with commentary explaining why it's true and false under different conditions. All the behaviour in `if(acceleration)` is the same – I just had to rework it so the actual drag could be applied only once, at the end.

To talk about:

1. Is line 1123 okay? I didn't want to compare two doubles for equality (`== -1.`), so `< 0.` felt the safest way to check the vectors were in different directions.
2. There might be a _small_ change to how much this helps the Distancer work. Bumping the firing force from 60 to about 100 seems to keep things equivalent.
3. Anyone up for a code review and playtest?

### CODE REVIEW

**Comment by Amazinite** [comment]
How does this effect things like particle cannons and grab strikes in combat?

**Comment by Elyssaen** [comment]
It doesn't. Say a ship has a normal max speed of 400, and with some afterburners it has it could reach 500. As long as it has a speed below 500, gameplay is absolutely identical.

The only situation where it'd be able to exceed a speed of 500 is with firing force, particularly spamming it. In that case, it'd lose speed to drag until it hit 500.

There are only two situations where this matters:
1. If the player ever spams a weapon with firing force... particularly, say you wanted to let the player obtain something similar to the Distancer, or made a tractor beam that used negative firing force to pull _you_ in.
2. In practice, the Archon's Distancer does seem to temporarily, and intentionally, push it above its speed limit. This drags it a little, hence why I think a Distancer bump from 60 to 100 might round things out.

**Comment by endless-sky** [comment]
This would make it so that if you're applying an afterburner at 89 degrees relative to your current velocity, and then you rotate so you're facing 91 degrees away, suddenly drag kicks in full-strength. That will look rather clunky compared to the current behavior of smoothly phasing in and out.

Also, the current behavior exists for a good reason, to avoid situations where ships can "trap" you just by hitting you with lots of small projectiles that have hit force and therefore cause drag to kick in.

**Comment by Elyssaen** [comment]
> This would make it so that if you're applying an afterburner at 89 degrees relative to your current velocity, and then you rotate so you're facing 91 degrees away, suddenly drag kicks in full-strength. That will look rather clunky compared to the current behavior of smoothly phasing in and out.

Good point, I dropped to erroneous 1D thinking when I was a bit confused by the comment, so thought the line was just choosing between 0 and 1. I can fix that tonight to make it behave the same way as before.

> Also, the current behavior exists for a good reason, to avoid situations where ships can "trap" you just by hitting you with lots of small projectiles that have hit force and therefore cause drag to kick in.

I'm having difficulty thinking of a scenario where that might happen: do you have a test case? To me, it seems like the worst they can do is make you lose ~1% of your speed in one single frame, which'd be shaved off anyway if you were thrusting. If you can give me a test case, I'll see if I can replicate the trapping problem. If I can, perhaps there's a third option that preserves all the existing behaviour but doesn't allow zipping about at a speed of 1,000,000+?

**Comment by Quantumshark** [comment]
How about only apply drag when accelerating due to firing force, but not due to hit force? That should fix the lack of a max speed when using distancers etc without  allowing ships to trap you with hit force.

**Comment by Elyssaen** [comment]
@Quantumshark, sorry to take a while to get back to you. I've had a think about your suggestion, and while I like the directness of it there are a few reasons I don't think it's a good fix overall:

1. Splitting how firing force and hit force work could be hard to understand in the long term, given how both right now call ApplyForce in a nice clear way.
2. Both of them can apply multiple times per frame. You wouldn't want to actually apply _drag_ multiple times a frame, so you'd need to carry over a flag to Ship::Move. How you'd then write it in Ship::Move... I can't think of a nice elegant way.
3. If there _was_ a trapping problem, it'd create odd situations where you'd only get trapped when you fired some of your own guns with recoil, and then a player would _really_ be confused.

Moreover, I've run every test case I can think of, and I can't reproduce this trapping problem. MZ, could you describe the scenario to me? It's got to be a scenario where you want to escape but you're not thrusting, because otherwise drag would apply anyway. And if drag does drop your drift speed, it will get harder for hit force to push you above the limit to keep drag on. Don't know if I'm missing a scenario, but everything I look at plays nicely.

Lastly, I've made a second commit which restores the original dot product functionality. I don't quite get what this is physically doing in all but the -1 case, but it's back to how it was.

**Comment by endless-sky** [comment]
The most obvious examples are:

1. Hyperspace jumping, when your path takes you through hostile fire, and

2. Trying to flee with afterburner while an enemy is hitting you with a particle cannon.

The main point is, the current drag behavior took a *lot* of tweaking to get it into an acceptable state (see #353 for an example of the issues that needed to be addressed) so I don't want to change it further without thinking through the consequences carefully.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/b20b7ff3522d97e145e19f8be9a2347995568542

**Pull request closed without merging**
