### PR TITLE
Rename MacOS application to "Endless Sky"

### PR DESCRIPTION
**Pull request by nobodywasishere**
See #561

### CODE REVIEW

**Comment by nobodywasishere** [comment]
Yeah sorry I'm a little new to this whole git thing, and had trouble pushing the changes I made in xcode to git. My apologies. I will relook at it again tomorrow On Jan 27, 2019 23:44, Nate Graham <notifications@github.com> wrote:@Pointedstick requested changes on this pull request.

Erm, I think you accidentally touched more files that you meant to...
A final git diff before committing helps to ensure you're only modifying the files you intended to.

**Comment by nobodywasishere** [comment]
Redone with newer branch.

**Comment by tehhowch** [comment]
Rather than PR a new branch, just force-push this one as needed

**Comment by nobodywasishere** [comment]
...that seems to be the right way to do that. I apologize. I did manage to get it working the correct way, though. (And I did already deleted the old branch, my apologies).

**Pull request closed without merging**
