### PR TITLE
Wasp +2 weapon capacity

### PR DESCRIPTION
**Pull request by Nescio0**
This puts the Wasp, a "medium strength interceptor", nicely in between the Sparrow's 20 and the Fury's 40; at 30 the Wasp could equip e.g. one particle cannon or three meteors.

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
> This puts the Wasp, a "medium strength interceptor", nicely in between the Sparrow's 20 and the Fury's 40

and in another pull you nerfed weapon space to differentiate ships

giving +2 space isn't that bad but your reason for it is bad

**Comment by Pointedstick** [comment]
28 tons seems perfect to me--it's enough space to fit one Proton gun, which is made by the same company. Why would that company include enough space to mount a competitor's weapon? ;-)

**Comment by Nescio0** [comment]
Why? To sell more Wasps, of course, because 30 weapon capacity offers more flexibility.
Besides, the Syndicate outfitters also produce and sell meteor missile launchers; the Wasp has three gun ports; 3*10=30.

**Comment by KiLEdEnNis** [comment]
> Why? To sell more Wasps, of course, because 30 weapon capacity offers more flexibility.

then why not 32? to offer more options for ship captains
then why not 34? etc. etc.

there's no reason to buff this ship just so "It'S mOrE iN-lInE"

**Comment by Brick63** [comment]
But then they sell less gun

**Pull request closed without merging**
