### PR TITLE
Updated the Finisher Pod description to improve readability

### PR DESCRIPTION
**Pull request by warp-core**
This is to improve readability as the current way seems awkward to read.

### CODE REVIEW

**Comment by tehhowch** [comment]
Maybe also strip the first `for`?

"...of their other weapons merely exist to hold a ship in place ~~for~~ long enough for a barrage of Finishers to destroy it."

`
Finisher Torpedoes are one of the Heliarchs' most dreaded weapons. In fact, in one way or another, most of their other weapons merely exist to hold a ship in place long enough for a barrage of Finishers to destroy it.
`

**Comment by Bladewood** [comment]
I've said this before, but I believe another problem is in the use of the phrase `one of` with a plural `Finisher Torpedoes`, rather than using Torpedo singular or using `some of` instead.

I have a feeling this will be written off as "personal style", or something along those ends...

**Comment by endless-sky** [comment]
I think this is just a matter of personal preference, not a definite improvement or a grammatical error fix.

**Comment by MessyMix** [comment]
Good snipe, @Bladewood. :P

**Pull request closed without merging**
