### PR TITLE
Hai Security: varying planet security and Hai surveillance fleets

### PR DESCRIPTION
**Pull request by NomadicVolcano**
This is a revision to the PR #4649 which improved Hai security due to, in part, to their dislike of nerve gas. It does not make sense that all Hai planets would have equal security; slipping nerve gas into Cloudfire should be more difficult than a nearly uninhabited planet like Heartvalley. Also, the Hai seem wise enough (or cowardly enough) to scan for dangerous neurotoxins *before* they reach the planet surface.

Changes:

1. Hai planet security is about 0.1-0.3 on most planets, but a bit higher on Hai-home and planets with Humans. Cloudfire, a military base, has a security of 0.9

2. Waypoint and all Hai systems except Wah Ki have surveillance fleets.  You'll see one or two lightning bugs, or a squadron of unconstrained grasshoppers.

*Note:* This commit adds no surveillance ships in Wah Ki. The fights there are non-stop, so any surveillance ships would fight instead of scan.

### CODE REVIEW

**Comment by NomadicVolcano** [comment]
The way I've coded this, you're scanned maybe once every three or four journeys through Hai space.  That is because only the surveillance fleets scan you and they're relatively infrequent. I'm not sure how high security should be turned up in Hai space.

In `data/map.txt`, The "Hai Surveillance (Slow)" fleets are the Lightning Bugs and the "Hai Surveillance (Unconstrained)" fleets are the grasshopper squadrons.  The grasshoppers are more likely to succeed in their scans since they come in groups of 5 to 7, and they are hard to evade. I made them less frequent.

**Comment by NomadicVolcano** [comment]
Another odd thing I've seen is that the Lightning Bugs will leave a system immediately in a few seconds, sometimes before they even finish their scans. The Grasshoppers will stay forever.

**Comment by NomadicVolcano** [comment]
If you leave the game running in one system for a few hours, you'll have a dozens and dozens of stationary Grasshoppers scanning you while spouting hippie love phrases.

**Comment by Amazinite** [comment]
Ref: #4723

**Comment by beccabunny** [comment]
Might be worth adding the outfit and cargo scanner to the hai outfitters

**Comment by NomadicVolcano** [comment]
> Might be worth adding the outfit and cargo scanner to the hai outfitters

Thank you for catching that. I just added it to the intermediate and advanced Hai outfitters.

**Comment by NomadicVolcano** [comment]
> It seems unnecessary to me to have two separate surveillance fleets. I'd suggest just combining both into one, or completely removing one or the other. (Perhaps only Grasshoppers do surveillance.)
> I'd say that 5 or 7 Grasshoppers is a bit much, but given that that's an uncommon fleet size (the most you'll see otherwise is 3), it'd make it obvious that Hai with scanners just showed up, so I think it's fine as a way to signal to the player that they're likely about to be scanned.

The Lightning Bugs are ineffective at scanning, but serve to warn the player that the Hai do scan. This is especially important for experienced players who do not expect the Hai to scan them. The Grasshoppers are the ones that will actually scan you; the bite that comes after the bark. 

Often the Grasshoppers won't try to scan anyone; they'll just sit around. Seven seems to be enough so at least two attempt to scan you. This is likely due to issue #4723 and is a necessary workaround. An alternative is for two or three to appear at a time, but appear far more often.

**Comment by NomadicVolcano** [comment]
I have merged the fleets into one, reduced fleet sizes, made them more frequent, and added Shield Beetles. The beetles have seven each of outfit and cargo scanners, so they're quite skilled at scanning you. They also have a brig to put you in, should you misbehave.

**Comment by NomadicVolcano** [comment]
I've also removed the "Small Hai" fleets from Waypoint, because there is no reason for Hai to fly there and back unless they're policing. Instead, there is a non-stop flow of surveillance ships.

**Comment by NomadicVolcano** [comment]
> > It seems unnecessary to me to have two separate surveillance fleets. I'd suggest just combining both into one, or completely removing one or the other. (Perhaps only Grasshoppers do surveillance.)
> > I'd say that 5 or 7 Grasshoppers is a bit much, but given that that's an uncommon fleet size (the most you'll see otherwise is 3), it'd make it obvious that Hai with scanners just showed up, so I think it's fine as a way to signal to the player that they're likely about to be scanned.
> 
> The Lightning Bugs are ineffective at scanning, but serve to warn the player that the Hai do scan. This is especially important for experienced players who do not expect the Hai to scan them. The Grasshoppers are the ones that will actually scan you; the bite that comes after the bark.
> 
> Often the Grasshoppers won't try to scan anyone; they'll just sit around. Seven seems to be enough so at least two attempt to scan you. This is likely due to issue #4723 and is a necessary workaround. An alternative is for two or three to appear at a time, but appear far more often. That would negate the effectiveness of the Lightning Bugs as a warming that the Hai will scan.
> 
> An interesting alternative to the Lightning Bugs would be a Shield Beetle with a brig and extra Pulse Rifles.

I suppose a changelog entry is enough to warn experienced players.

**Pull request merged**
