### PR TITLE
feat(content): Elaborate Far'en Lai description, showing Drak-Exile relationship

### PR DESCRIPTION
**Pull request by ravenshining**
----------------------
**Content (Lore)**

## Summary

This rewrites the description of Far'en Lai, going from a more straightforward tale to a more poetic, and yet more complete one, giving a look into the continuing relationship between the Archons and the Korath, what they have done and must do.

In the old description, the terms of exile seemed ambiguous and the Korath response confused, which reflects badly upon the Drak.  This text aims to shine some light on Drak wisdom, that working through their confusion to understanding is part of the journey the Korath must undertake.

Quoth @UnorderedSigh :

> Presently, the Far'en Lai planet description leaves the player with blissful ignorance about the fate of the Korath. They can fill in the situation with their imagination. Some players prefer blissful ignorance of a placeholder faction. That will end once we have a campaign.
> 
> The first contact mission alone is enough to render the current planet description irrelevant (#8752).  Once the campaign PR is in, the Korath will tell you, in great detail, their situation. Adding the terms of exile gives the player context to understand the problem.
> 
> Drak are an enlightened race, not a race of bullies, and this koan reflects that. Take some time to think about it and you'll understand what the Drak are trying to teach the Korath and why the Korath know they can't terraform Far'en Lai yet. It's in the message, plainly there for all to see, if they care to take time to understand the koan.
> 
> Some players find symbolism and deeper meaning to be confusing and upsetting. This is a rare spot where it is necessary. Archons are millions of years old and have achieved enlightenment. They see themselves in the Korath: young Drak that can learn from their mistakes before it is too late. This koan is the Archons passing their enlightenment on to the Korath.
> 
> Of course, once there's a campaign, you'll learn this from the Korath directly, in their own words.

## UI Screenshots

Screenshot (488)

### CODE REVIEW

**Comment by Koranir** [comment]
I don't see how this change is necessary.

The previous description was succinct and evocative, and gives a sense that _this is it_ for the exiles, and they veer away from touching the planet due to what they know they have done before, and may do once more. The description is clean and to-the-point, leaving much unspoken, and that empty space speaks volumes to how pure and untainted they have kept the planet in spite of it being the final hope for their race. It shows they yet have some self-awareness to what they are. 

You say that the previous description made the Drak's intentions ambiguous, but they are perfectly clear: Learn to coexist with the environment, and you have hope for the future. The new description is far too verbose, and the words seem out of character for the Drak, with the Drak usually being quite curt and imperical with their communication.

The phrase seek kinship comes up twice, which is almost the most ambiguous thing a Drak could have said in this situation. It seems like the Drak are just berating the Exiles for their past transgressions and not leaving a path forward with how they just tell the Korath to 'return to their contemplation', something far out of character for the Drak.

It puts the blame for the Exiles staying exiled on the Drak instead of the Exiles themselves, and paints the Exiles as a wronged faction, unsure of what to do to get their homelands back, while the previous description paints the Exiles as having the means to fix Far'en Lai, but refusing to do so as they are aware of how destructive they can be in a form of self-penance.

When I first stumbled onto Far'en Lai in-game, I felt like I had just walked into the most private quarters of the Korath. It made me feel empathy and gave me insight into the Exile mindset, and I must have sat there for a while just imagining what being an Exile felt like, the desolation in knowing that your race _did this to themselves, and can't bear to do anything about it_. I don't feel the same emotions while reading this description. The Korath before seemed aware of their own destructive capabilities, but with this change just seem like they were wronged by the Drak.

**Comment by ravenshining** [comment]
I don't know how you get that from this at all, but it would be good to discuss it in more detail on Discord, since you're a member on S6.  We spent quite a bit of time hashing this out there about a month ago.

**Comment by UnorderedSigh** [comment]
> I don't see how this change is necessary.

You would be right in the game as it is now. The Korath are merely a placeholder faction. Keeping their story a mystery was a necessity because of the many plot holes to fill in having a story at all.

The largest plot hole of all is why the Drak left the Exiles with such tremendous confusion about the terms of exile. Leaving the Korath baffled is victimizing them, not saving them.

Now we know the Drak left the Exiles with a koan. The ambiguity is to teach them. Leaving the planet untouched is the choice the Korath made. And perhaps most importantly of all, the Drak would never kill the Korath for making a mistake.

**Comment by UnorderedSigh** [comment]
> It puts the blame for the Exiles staying exiled on the Drak instead of the Exiles themselves

The previous one implied that was the case as well.

>  and paints the Exiles as a wronged faction, unsure of what to do to get their homelands back

> while the previous description paints the Exiles as having the means to fix Far'en Lai

Wrong. The previous one provided no information about the level of terraforming knowledge the Exiles have. It left many people under the illusion that the Wanderers could "fix the Exiles" by spending a few weeks terraforming their planet.

> but refusing to do so as they are aware of how destructive they can be in a form of self-penance.

Irrelevant and redundant. The campaign will explain this in detail immediately.

> When I first stumbled onto Far'en Lai in-game, I felt like I had just walked into the most private quarters of the Korath. It made me feel empathy and gave me insight into the Exile mindset, and I must have sat there for a while just imagining what being an Exile felt like, the desolation in knowing that your race did this to themselves, and can't bear to do anything about it. I don't feel the same emotions while reading this description. The Korath before seemed aware of their own destructive capabilities, but with this change just seem like they were wronged by the Drak.

Again, irrelevant and redundant. As soon as you land on Far'en Lai, you'll meet the Korath and converse with them. Soon after, you'll get a lot of detail. None of this will be a mystery.

**Comment by Arachi-Lover** [comment]
> I don't know how you get that from this at all, but it would be good to discuss it in more detail on Discord, since you're a member on S6. We spent quite a bit of time hashing this out there about a month ago.

It is far easier for discussion points to be drowned by comments in Discord servers, and as this has been PRd the PR itself is the exact place discussion should happen.
It is also irrelevant for the PR stage how much discussion about the content happened on other mediums; the PR should stand on its own.

> The Korath are merely a placeholder faction.

That's completely false.

> Keeping their story a mystery was a necessity because of the many plot holes to fill in having a story at all.
> The largest plot hole of all is why the Drak left the Exiles with such tremendous confusion about the terms of exile. Leaving the Korath baffled is victimizing them, not saving them.

That's not a plot hole. And even if we were to count it as one, *this version* is the most ambiguous one. As Koranir said the previous description was to the point, "this world thrives you're restored, it perishes and you're done" you can't get clearer than that. The presented changes are incredibly convoluted and are what would really cause tremendous confusion, as per points already brought up by Koranir.

> Now we know the Drak left the Exiles with a koan. The ambiguity is to teach them. Leaving the planet untouched is the choice the Korath made.

So it's not a plot hole only when *you* intend for it to be ambiguous?

**Comment by UnorderedSigh** [comment]
> > The Korath are merely a placeholder faction.
> 
> That's completely false.

Yes, I meant the Exiles are merely a placeholder faction. They're no more than the Quarg: people talk about them and we see their ships doing things. Land on their planets and you see information about them.

We don't know anything about them, aside from ambiguities and conflicting information.

> > Keeping their story a mystery was a necessity because of the many plot holes to fill in having a story at all.
> > The largest plot hole of all is why the Drak left the Exiles with such tremendous confusion about the terms of exile. Leaving the Korath baffled is victimizing them, not saving them.
> 
> That's not a plot hole. And even if we were to count it as one, _this version_ is the most ambiguous one. As Koranir said the previous description was to the point, "this world thrives you're restored, it perishes and you're done" you can't get clearer than that. The presented changes are incredibly convoluted and are what would really cause tremendous confusion, as per points already brought up by Koranir.

Except that isn't the case. The Drak genocide threat is something the Exiles imagined.
 
> > Now we know the Drak left the Exiles with a koan. The ambiguity is to teach them. Leaving the planet untouched is the choice the Korath made.
> 
> So it's not a plot hole only when _you_ intend for it to be ambiguous?

There is no ambiguity. It appears ambiguous until one understands the koan. That's the point of a koan.

**Comment by UnorderedSigh** [comment]
> >   I don't know how you get that from this at all, but it would be good to discuss it in more detail on Discord, since you're a member on S6. We spent quite a bit of time hashing this out there about a month ago.
> It is far easier for discussion points to be drowned by comments in Discord servers, and as this has been PRd the PR itself is the exact place discussion should happen.

Oh really? Then delete all those dev-only and member-only channels on ESC and let the community take part in decisions about this community game. If you're not going to do that, then you need to get used to people doing the same. At least we let anyone into korath-public.

**Comment by ravenshining** [comment]
> It is far easier for discussion points to be drowned by comments in Discord servers, and as this has been PRd the PR itself is the exact place discussion should happen. It is also irrelevant for the PR stage how much discussion about the content happened on other mediums; the PR should stand on its own.

These sorts of arguements are entirely inappropriate for GitHub.  The simple practical matter is, if someone wants to get in touch with me, the easiest way to do it is to do so on Discord.  We can argue all we want there.

**Comment by UnorderedSigh** [comment]
In retrospect, I think this makes little sense outside the context of the Korath campaign.

It should probably be considered a companion PR to #8752

**Comment by Arachi-Lover** [comment]
> They're no more than the Quarg: people talk about them and we see their ships doing things. Land on their planets and you see information about them.

That's absurd. The Quarg have 2 ships and less than 10 outfits, and are tangentially talked with in several campaigns. The Exiles have nearly the latter half of the Wanderers middle portion to them. They have over a dozen ships and many outfits providing lore description. They have outside interactions with the Remnant in their missions combating them.

To compare the Korath and the Quarg in terms of being placeholder is flat out dishonest.

> We don't know anything about them, aside from ambiguities and conflicting information.

The proposed change here is not helping make them any less ambiguous.

> Except that isn't the case. The Drak genocide threat is something the Exiles imagined.

Based on lore of yours that's not in the game yet so it's not a valid defense source?

> There is no ambiguity. It appears ambiguous until one understands the koan. That's the point of a koan.

If something is only not ambiguous until you ask the author of the message the original meaning to know for sure then it is ambiguous to the point where you need to ask the author of the message the original meaning.
Meaning it is ambiguous.

> Oh really? Then delete all those dev-only and member-only channels on ESC and let the community take part in decisions about this community game. If you're not going to do that, then you need to get used to people using Discord. At least we let anyone into korath-public.

Literally all content discussed anywhere from ESC to DMs to S6 needs to pass through the PR stage during which anyone can criticize PRs as much as they wish and their comments will be acknowledged, addressed or further discussed.
We all go through the same exact process. Nobody demands one to be part of one server or the other to see the discussed points; points discussed in the Discord server are reiterated, more often than not even more elaborated upon, when the content gets to the PR stage.

> These sorts of arguements are entirely inappropriate for GitHub. The simple practical matter is, if someone wants to get in touch with me, the easiest way to do it is to do so on Discord. We can argue all we want there.

No, GitHub is the platform we utilize for PRing, discussing and adjusting changes before any get in the game. It is precisely the place where we want to discuss things openly and fully. For practicality purposes I'll agree Discord is easier to discuss with more people and less of a hassle in the UI to locate messages, however everyone has to go through the PR process and the PR is where everything *has* to be explained in as much detail as possible because, as noted, not everyone is in every ES discord server.
Furthermore, this is not the case of "we wish to argue", it is the case that when PRs are opened it is expected of the author to engage in discussions within the PR and answer questions within the PR. Defering people to go to some Discord server and look there for explanations is counterproductive as it'll keep demanding people move from GitHub to Discord, and it separates the discussion instead of keeping all relevant points contained within the PR, which is how it should be.

**Comment by UnorderedSigh** [comment]
I'll open a new PR for this soon as a companion PR to #8752.

I hope people will refrain from bile and personal attacks in the next PR.

**Comment by MCOfficer** [comment]
> I hope people will refrain from bile and personal attacks in the next PR.

Nobody will deny that this got heated, but having read through it twice looking for personal attacks, all I can see is lack of politeness on both sides. (Which isn't necessarily a bad thing, but it can serve to escalate existing tensions).

That aside, opening a PR is akin to asking for feedback, and regardless of how the feedback is phrased, discarding it as "bile" after the fact is not helpful to anyone, least of which yourself.

**Comment by Hurleveur** [comment]
would be cool if discovering the terms of the exile changed the planet description I think, would make the world a bit more reactive to what you do

**Comment by UnorderedSigh** [comment]
> would be cool if discovering the terms of the exile changed the planet description I think, would make the world a bit more reactive to what you do

Yes, Arachi suggested that twice over the past few years.

**Comment by UnorderedSigh** [comment]
What would the original description be, when you've only just met the Korath in First Contact: Korath Exiles?

**Comment by UnorderedSigh** [comment]
> @MCOfficer
> 
> > Nobody will deny that this got heated, but having read through it twice looking for personal attacks, all I can see is lack of politeness on both sides. (Which isn't necessarily a bad thing, but it can serve to escalate existing tensions).
> 
> The Raven has been subjected to a pattern of messages that are what you call "heated." When every message ever sent your way is "heated" it becomes a pattern of abuse. Frankly, I am a target too, but I'm willing to heat back and rewrite my PRs five times.

Clarification: She has been subjected to this on a regular basis for a long time.

**Comment by Koranir** [comment]
> > @MCOfficer
> > > Nobody will deny that this got heated, but having read through it twice looking for personal attacks, all I can see is lack of politeness on both sides. (Which isn't necessarily a bad thing, but it can serve to escalate existing tensions).
> > 
> > 
> > The Raven has been subjected to a pattern of messages that are what you call "heated." When every message ever sent your way is "heated" it becomes a pattern of abuse. Frankly, I am a target too, but I'm willing to heat back and rewrite my PRs five times.
> 
> Clarification: She has been subjected to this on a regular basis for a long time.

If you're doing controversial things on a  regular basis, you shouldn't be surprised when people disagree with you. _Especially_ if you're basing these changes on things that you claim "will" be implemented in an uncertain future.

**Comment by UnorderedSigh** [comment]
> > The Raven has been subjected to a pattern of messages that are what you call "heated." When every message ever sent your way is "heated" it becomes a pattern of abuse. Frankly, I am a target too, but I'm willing to heat back and rewrite my PRs five times.
> If you're doing controversial things on a regular basis, you shouldn't be surprised when people disagree with you. 

Ah, I see the subtext here. If you're doing controversial things on a regular basis then you should expect to be a subject of abuse. We have the right to abuse you if we disagree with the content or your views.

**Comment by UnorderedSigh** [comment]
> Especially if you're basing these changes on things that you claim "will" be implemented in an uncertain future.

After Arachi's massive PR was merged, I have more faith in the dev's abilities to get large content in. The Korath campaign will be merged... eventually... though how long it takes is  not up to me.

**Comment by Hecter94** [comment]
This is getting pretty off-topic for the PR in question. Especially considering it's now been closed. 
Let's keep the discussion on the PR relevant to the PR itself. Better yet, since the PR has been closed, open an issue for further discussion/feedback on the suggested change.

**Comment by UnorderedSigh** [comment]
Agreed. I will delete my one disagreeable comment and leave it at that.

**Pull request closed without merging**
