### PR TITLE
New Tarazed ship sprites

### PR DESCRIPTION
**Pull request by Anarchist2**
**Content (Artwork)**
image
## Summary
This PR, in the same vein as the other redetail PRs by Becca, the models used for the ships that Tarazed produces were detailed, namely the Sparrow, Hawk, Finch, Blackbird, Osprey and Falcon (+ marauder/modified variants where applicable).

Blackbird:
blackbird

Hawk:
hawk

Osprey:
osprey3

Shipyard on Wayfarer:
image

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: 
https://drive.google.com/file/d/16ZYdJENk204AieWww8SDmMw4CBcSFrFf/view?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky/pull/https://github.com/endless-sky/endless-sky-high-dpi/pull/144

### CODE REVIEW

**Comment by beccabunny** [comment]
That's very good! The only ship sprite that I think could use some more work is the Osprey, as the details in it are a little too weird, but the rest looks absolutely fantastic.

**Comment by Zitchas** [comment]
At first glance, they look good, with the exception of the Osprey which looks like it should be renamed the hedgehog. It looks just a bit too spiky. I've long thought that the Osprey needed a redo, primarily to get it a little more firmly anchored together. Adding more spikiness I think just makes it look a bit more fuzzy.

**Comment by Arachi-Lover** [comment]
yeah the Osprey seems a bit overkill to me

**Comment by Amazinite** [comment]
The Osprey looks like it has dazzle camo.

**Comment by Anarchist2** [comment]
Dialed back the changes on the Osprey. Left is original, middle is PR (old), right is new.
osprey2
Also added in the rear flares for the Osprey.

**Comment by Zitchas** [comment]
Ok, the new and improved Osprey looks much better now. It is still a bit busy, but much improve.

**Comment by beccabunny** [comment]
Since the Kestrel is Tarazed as well, this might be a good place to improve it as well. I believe @Zitchas could have a fair amount of pictures of what the ES kestrel is based on and the Kestrels of the EVs

**Comment by Zitchas** [comment]
Sadly, I don't really. There's a fair number of Kestrel pictures on the internet, but the original EV had very little external graphics, so people are basically extrapolating from a tiny sprite.

Current Kestrel for reference.
kestrel@2x
kestrel@2x

Escape Velocity Kestrel (Shipyard image):
EV Kestrel (shipyard)

Escape Velocity Nova Kestrel (Source claims it as shipyard image, I'm dubious. I think this is probably a plug-in's upgrade of the shipyard image)
EVN Kestrel (shipyard-black)

**Review by Amazinite — CHANGES_REQUESTED** [review]
You've consumed some commits on the master and deleted Becca.
I'm not a fan of the gray parts you put inside of a lot of the colored fins. These ships are already predominately gray, and you're just removing more color from that. The Sparrow and Finch are great examples of this. There's hardly any color now because you've removed most of what was there. The Falcon thumbnail is another good example of losing a lot of color. The Hawk is lacking as well.

**Review by Amazinite — APPROVED** [review]
Looking much better. So, who's next? 

I'm fine with leaving the Kestrel for now.

**Comment by finite-galaxy** [comment]
@Amazinite, @Anarchist2, @Zitchas, I tried my hand at the Kestrel in March and posted the files at #4959. (My Blender skills are very basic; moreover, it's unclear how to do proper post-processing (in GIMP?), hence the issue.)
In June I made some further edits; amongst other things, I gave the top wing exactly the same size as the other two, because I like symmetry. Frontal view:
kestrel
You can find the files at https://github.com/finite-galaxy/art-source/tree/master/ships
What you decide to do with it is up to you.

**Pull request merged**
