### PR TITLE
Make Starting Loan Optional

### PR DESCRIPTION
**Pull request by Hecter94**
**Content (Missions)**

## Summary
I highly encourage you to read through issue #8427, as that goes through most of my reasoning for why I feel this is a good change in much more detail. 

To summarize, the current forced loan at the start of the game comes with a lot of drawbacks, namely:

1. Lack of player agency.
2. No obvious benefit.
3. Disincentives experimentation.
4. Interferes with, rather than complements, the core gameplay loop.

With this change, I aim to:

1. Make the loan an obvious player choice.
2. Give an obvious benefit to taking the loan.
3. Allow skipping the loan entirely

For more details about any of those points, or information about other alternatives I considered, see #8427 

## Save File
This change makes edits to both the start and the intro missions, so creating a new save is necessary to test them. 

### Why Draft?
I'm opening this as a draft for three reasons: 
1) This is a potentially controversial change, so it should have some time open before being considered for merging.
2) While technically feature complete and mechanically functional. There is no way to give the player a debt, only a fine. While this works mechanically, it would need to be changed to debt before this could be merged.
3) The conversations need a lot more polish.

### ToDo:
1) Allow action nodes to give the player a mortgage like a start can. (Probably in a different PR, and then update this one once that is done)
2) Polish up the writing once the idea of making the starting loan optional is accepted on a conceptual level.
3) Double-check the rest of the game for any references to the starting loan I missed.

### Points for consideration.
Is this loan too high? Too low? 
Are the ships offered too powerful?
Should you have to trade in your current ship? If so, how do we handle players that have already customized/sold their starting ship?
How does this play into the Syndicate/Republic/Pirate campaign?
Should you still be able to access this mission without going through the tutorial? Should it become unavailable once you've done the tutorial?

### CODE REVIEW

**Comment by ziproot** [comment]
Fines have a much higher interest rate than the original loan.

**Comment by Hecter94** [comment]
> Fines have a much higher interest rate than the original loan.

Correct. However, adding a mortgage in an action node is impossible and would need to be changed once possible to do so, as mentioned in the PR description.

**Comment by ziproot** [comment]
Sorry, I need to do a better job reading the PR descriptions.

**Comment by Anarchist2** [comment]
I'm having trouble writing my ideas out, so here's a condensed form of my thoughts:
1. Requiring a loan to start as a starship captain is an important part of the ludonarrative regarding the economic inequality present in the galaxy, and removing it causes lore problems as to why the inequality exists when a textile worker can buy into the starship business relatively easily (the player character has always been treated as being fairly young).
2. Delaying the loan doesn't necessarily mean that players will better understand it. Very few players will be checking credits/jump, and those that are aren't the ones that are going to get got by loans.

**Comment by Zitchas** [comment]
Anarchist2 has some good points about the economic narrative.

Personally, I'd be inclined to go a slightly different route: Have people start out directly into a shuttle without debt. If they want to go their own way, well, that's their choice. If they go through the James stuff and whatnot, they end up getting the opportunity to get that starting loan and the option to get the three starter ships, with heavy shuttle in place of the shuttle. 

Also, as an aside, I find it really problematic that when people start the game, new players are basically randomly picking a ship. And depending on their random selection, we minimize teaching them about the other aspects of the game. I think we could really do better at teaching people the other aspects, especially teaching shuttle/starbarge pilots about combat.

**Comment by Hecter94** [comment]
> 1. Requiring a loan to start as a starship captain is an important part of the ludonarrative regarding the economic inequality present in the galaxy, and removing it causes lore problems as to why the inequality exists when a textile worker can buy into the starship business relatively easily (the player character has always been treated as being fairly young).

I can understand this, but there are tangible gameplay benefits to doing it this way, and it makes sense to prioritize gameplay benefits over lore concerns. Especially gameplay benefits targeting the very early game.
Let's keep the idea of the loan as an optional choice but also tweak some of the existing wording to make it less of a lore problem. Perhaps we need a specific mention of FirLast's experience being unusual? Or some reference to an unusual event that allowed FirLast to reach this outcome? 

> 2. Delaying the loan doesn't necessarily mean that players will better understand it. Very few players will be checking credits/jump, and those that are aren't the ones that are going to get got by loans.

Sure, but at the very least, they're going to see what they got paid for their first couple of jobs and will have seen how much their starter ship cost to purchase, and will, at the very least, have some idea of what they are getting themselves into. 

It's also optional; if players don't like the idea of going into debt, they don't have to. If someone wants to explore, they can, we're not forcing them into a core gameplay loop that they aren't going to enjoy, and that has many benefits on its own. 

For reference, I remember finding the starting loan extremely stressful the first time I played ES. I didn't find it hard to pay off, and it didn't kill my game or anything; I could pay it off eventually, but starting the game in debt was stressful. It put me on a timer, and I was more worried about not failing than actually playing and learning the game. 
When I eventually paid it off, I thought, "phew, now I can play the game."

**Comment by Hecter94** [comment]
> Personally, I'd be inclined to go a slightly different route: Have people start out directly into a shuttle without debt. If they want to go their own way, well, that's their choice. If they go through the James stuff and whatnot, they end up getting the opportunity to get that starting loan and the option to get the three starter ships, with heavy shuttle in place of the shuttle.

I'd also be 100% okay with going this route if that is what we want to go with. 
I mainly wanted to avoid changing the early game more than necessary, so I decided to pick your starting ship and then get an optional upgrade since that required the least tweaking of existing content. 

> Also, as an aside, I find it really problematic that when people start the game, new players are basically randomly picking a ship. And depending on their random selection, we minimize teaching them about the other aspects of the game. I think we could do better at teaching people the other aspects, especially teaching shuttle/starbarge pilots about combat.

It's somewhat random; players will often have *some* experience with this type of space exploration and trading game and will have some idea as to what they would prefer doing and can pick their starting ship based on that. 
Though this is another reason why I quite like the idea of the "pick your starting ship and then get an optional upgrade" approach, as it means players can pick what they think they'd want to do, get a short intro mission chain showcasing what the actual playstyle of their pick will be, and then get the option of _changing_ their pick a little later if they want to. 

For example, a player might pick the sparrow as their starting ship, decide that they aren't fond of it after doing the tutorial, and then have the option of upgrading to, say, a clipper to try out a different playstyle without being stuck with their sparrow and a debt. It keeps the idea of allowing players to make a meaningful decision very early on while allowing them to back out of that decision a little later if they don't like what they picked.

**Comment by Anarchist2** [comment]
The reason I bring up point two is that I feel that there isn't enough time to differentiate having an optional loan after the tutorial from having different starts, which is generally much more lore-friendly.

(I suppose that a part of my reasoning is influenced by the fact that I've been workshopping some alternate starts recently.)

**Comment by Hecter94** [comment]
> The reason I bring up point two is that I feel that there isn't enough time to differentiate having an optional loan after the tutorial from having different starts, which is generally much more lore-friendly.

The starting tutorial may take little time, but it does provide an absolute *wealth* of information. 

Consider from the perspective of a brand-new player. You can start with a 480,000 credit loan, but how much is that loan? How much is 480,000 credits? 
You won't know if you're a completely brand-new player. Can you buy an upgrade for 600,000 credits or 10,000,000 credits? Will you spend 50,000 credits to buy your first ship or 480,000? Will it take one job to pay off this loan? Or 100?

We, as longer-term players, have a more general understanding of the difference between 480,000 credits and 800,000, we have a fairly solid idea of the buying power of x number of credits, but a brand-new player won't.

So with that in mind, what can you learn from the tutorial? Even if it's short?

1. You will have learned the costs of the three starter ships and may have learned the costs of more ships if you've viewed other shipyards out of curiosity.
2. You will have likely seen the costs of some outfits if you followed the tutorial's advice and visited the outfitter to buy a map.
3. You will have seen what you got paid for your first few jobs and will have an idea of what kind of income you can be expected to be earning 
4. You'll have jumped around a bit and will know how ships handle, know what movement/jumping is like, and know how frequent/deadly combat is
5. If you follow the tutorial advice and check the trading center, you'll know the costs of various commodities and the profit per ton you can earn. 
And, a lot more stuff that we, as experienced players, take for granted that might be completely unknown information to a brand-new player. 

For reference, after just doing the tutorial, not exploring any more than necessary, and not buying any maps, 

<details><summary>my map looks like this:</summary>

image
</details>

<details>
<summary>With what I've uncovered so far, I've at least had the opportunity to see the prices of the following ships:</summary>

Heavy Shuttle
Shuttle
Freighter
Star Barge
Berserker
Sparrow
Wasp
Gunboat
Rainmaker
Firebird
Dropship
Lance
Combat Drone
Surveillance Drone
</details>

<details><summary>and the following outfits:</summary>

Beam Laser
Heavy Laser
Anti-Missile Turret
Blaster Turret
Javelin Mini Pod
Javelin Pod
Meteor Missile Launcher
Meteor Missile Pod
Sidewinder Missile Launcher
Sidewinder Missile Pod
Heavy Rocket
Javelin
Javelin Storage Crate
Meteor Missile
Meteor Missile Box
Sidewinder Missile
Sidewinder Missile Rack
Torpedo
Asteroid Scanner
Brig
Bunk Room
Cargo Expansion
Cargo Scanner
Cooling Ducts
D14-RN Shield Generator
D23-QP Shield Generator
D41-HY Shield Generator
Fuel Pod
Hyperdrive
Liquid Nitrogen Cooler
Luxury Accommodations
Outfit Scanner
Outfits Expansion
Small Bunk Room
Small Radar Jammer
Tactical Scanner
Water Coolant System
KP-6 Photovoltaic System
KP-6 Photovoltaic Panel
LP036a Battery Pack
LP072a Battery Pack
LP144a Battery Pack
RT-I Radiothermal
S3 Thermionic
Supercapacitor
nGVF-AA Fuel Cell
nGVF-BB Fuel Cell
nGVF-CC Fuel Cell
Caldera Afterburner
Capybara Reverse Thruster
Chipmunk Plasma Steering
Chipmunk Plasma Thruster
Greyhound Plasma Steering
Greyhound Plasma Thruster
Volcano Afterburner
X1100 Ion Reverse Thruster
X1200 Ion Steering
X1700 Ion Thruster
X2200 Ion Steering
X2700 Ion Thruster
X3200 Ion Steering
X3700 Ion Thruster
Laser Rifle
Local Map
</details>

Of course, your average player will have yet to see and memorize the prices of all those things. Still, they will likely have seen at least a couple of them purely out of curiosity and thus have *some* baseline information they can use to make an informed decision. That is all information that a player cannot access when picking a start.
So while the starting tutorial may not be long in the grand scheme of things, I firmly believe that it gives access to a *lot* of useful information that a brand-new player can use to make a better-informed decision that an alternate start wouldn't be able to provide.

**Comment by Terin** [comment]
Definitely seconding the narrative impact of the loans. That really was a big hook for me getting into the universe of the game, where just to get off the ground, you needed to work up to have collateral for only a _loan._ While the player isn't subject to taxes and the like after paying off the loan. it was really effective in materially grounding me in the universe, where getting access to flight came with some big hooks and caveats.

If the player just gets a spaceship from working in a mill... that's much, _much_ less effective to me. Changing it so that the player's got access to that many funds, and the loan is just an optional bonus makes the world feel much simpler the navigate. And even on top of narrative hooks, having the loan did encourage me to look for those long-distance jobs that paid 50-100k credits. I'd be able to explore a lot of the galaxy, and take a good chunk off that at the same time.

I definitely understand seeing players drop a game and wanting to prevent that. But a game doesn't have to be for every person, and I think just killing it outright is a big, big loss. I'd much rather have different starts that have various degrees of loans (Derpy's Paradise Worlds start where you got a no-interest loan as a birthday present was a nice example). Or, have a (somewhat visible) gamerule to disable it outright. But unless there's a lot of support for this, I don't think it's worth it.

**Comment by EjoThims** [comment]
I hadn't considered that side of life implications in the loan itself, and definitely see now keeping it in some capacity in the base start as important to helping establish that.

We could still reduce its amount to have a gentler starting experience though, shift the narrative to player scrimping and saving their whole life until now to squirrel away 150k (a big chunk of money to have outright today) and -still- needing 250k in loans in top of that, for example?

I am also now more liking the idea of reintroducing Republic space licensing costs, which may help make up the difference in that lore feel even if the total daily payment at start is still less than current loan interest.

**Comment by Terin** [comment]
If you buy a shuttle, you have 142k credits to start with, or 56 days before you run out if you do nothing. If a new player feels like they're burning through money too quick, going back and doing something like a Deep or Paradise Worlds start for more would do it.

Re-adding licenses could be fun, but also seem like either a big can of worms to open up, or just not very effective. I know with EV Nova, I didn't have to touch licenses until I had plenty of money stored up, ready to pick up an actual combat ship. Either it'd be that, or very aggressive licensing on every incremental step up in ship size/outfit size, which is a whole other PR/topic to handle.

**Comment by EjoThims** [comment]
Ah, for licensing I meant the angle of piling on daily payments for them based on licensed usage. So (as more napkin examples) starting pilot license has low (or no) daily payment base, but a steeper scale for daily payments accrued for additional ships, versus a commercial license that discounts (or exempts) cargo ships. So we can still create that early need to monetize ship usage to start, but we could also have it scale up over time instead of quite as punishing to start as current loan payments. This could also help to marginally address (at least early on) deathballing, as well as dovetail into the FW issue over it, without needing to directly gate every individual ship/item behind different purchased licenses.

**Comment by Hecter94** [comment]
Bear in mind that there are tangible gameplay benefits to handling the starting loan in this manner outlined in #8553, which I highly encourage you to read. 

As such, while I recognize the concerns with how it impacts the lore, that should not be prioritized over improving the gameplay experience, especially the very early gameplay experience for newer players. 
We should focus on how to *resolve* that lore concern while still retaining the gameplay benefits of the optional loan. 

Additionally, consider that the three starting ships you're able to buy barely classify as spaceships:
The sparrow is outright stated to be a fighter and only classed as an interceptor because it has a hyperdrive.
The shuttle is the cheapest way to get a hyperspace-capable ship. 
The star barge is just a cargo container with an engine and a cockpit.

Trying to use any of these as the first step in your starship captain career is effectively suicide for anyone that doesn't have the powers of saving and loading the way FirLast does. 
Any regular person in the world of ES who wants something they could use to get started as a captain without being a flying deathtrap will be ~3x the cost, well out of reach of what FirLast saves up to purchase.

**Comment by Zireael07** [comment]
@Hecter94 You linked to this very PR?

**Comment by Hecter94** [comment]
> @Hecter94 You linked to this very PR?

my bad, fixed.

**Comment by Hecter94** [comment]
If anything, the idea that someone from a less fortunate economic background quite literally needs to put themselves at *significant risk of death* or go deep into debt just to be able to work their way up to where individuals from a more privileged economic background can *start* is still very much showcasing that economic inequality.

Anyone can do what FirLast does, as long as they're willing to work themselves half to death in a low-paying job for most of their life and then effectively "win the lottery" and not die within their first week of owning a shuttle.
Anyone who prefers not to die must be from a better economic background or take out a million credit loan to start.

**Comment by ziproot** [comment]
Aren't scrappers cheaper?

**Comment by bene-dictator** [comment]
Yeah, I don't agree with how it's written, but I definitely get the idea.

I would have had James help you from the start, telling you to go to the Bank to get credits first and then going over the features of each ship in the Shipyard, but I'm not sure that's possible.

**Comment by Amazinite** [comment]
Closing this on the grounds that it's bad implementation. If you want a loan/no loan option, then either we need to be able to have missions/choices provide loans so that we aren't using fines to make this work, or just use an alternative start.

**Pull request closed without merging**
