### PR TITLE
Feat(content): Ember Waste Ramscoop Changes

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
This is a compromise PR implementing changes to the fuel balance in the Ember Waste enabled by #8046 , which, when merged, will remove my objection to universal ramscoop being re-enabled, and thus #7740 can move forward.

Changes:
- This implements
```
	ramscoop
		universal 0
		addend -0.02
		multiplier 1.5
```
universal 0 disables the universal ramscoop.
addend -0.02 reduces the amount of fuel generated by ramscoops by 0.02 fuel per frame; representing the significant irregularities present in the Ember Waste that prevent weak ramscoops from being very useful. This includes the high density of material found in space. (It's still a vacuum, it is merely much denser than space outside the EW. 
multiplier 1.5 represents the higher density of fuel-suitable resources to be collected.

With this difficulty in collecting fuel, the existing `ramscoop 0.5` outfit and ships of the Remnant are actually useless, as in they do not generate any fuel whatsoever. Given that this outfit and these ships were designed and built to operate in the Ember Waste, they have been adjusted upwards to maintain the same production rate as before. I worked this out to be +0.75, which has been applied equally across all Remnant ships and outfit.

For progression purposes I'll note that while this makes the Emergency Ramscoop clearly better than the regular ramscoop that humanity has; it is still inferior to the Catalytic ramscoop in both absolute ramscoop value and ramscoop per space.

## Impact
The primary impact is that the Ember Waste is now a little bit more dangerous for outsiders to venture into. Fuel *must* be considered, either in capacity or regeneration; and it is likely that both will require a larger commitment than before. 

For progression purposes I'll note that while this makes the Emergency Ramscoop clearly better than the regular ramscoop that humanity has; it is still inferior to the Catalytic ramscoop in both absolute ramscoop value and ramscoop per space. This means that instead of the Remnant's ramscoop being more of a sidegrade or something to fill up an unused 4 space, it actually is an upgrade.

I find the Ramscoop progression problematic from two angles:
a) gameplay progression: Starting with access to regular ramscoops, then most people will get the catalytic ramscoop, and then either discover the Remnant or the Wanderers and *then* the Remnant. Being the third or 4th step in the chain, it means that this is either a big step down in ramscoop capabilities or a *massive* step down in capabilities.
b)The catalytic ramscoop specifically states that human ramscoop technology has remained unchanged for centuries because there is nowhere to explore, no big uninhabited gaps, and thus no need for it. No one is ever more than 4 jumps from a port, even in the most distant reaches of the pirate infested far North. (If one discounts the seldom-visited Ultima Thule, no point is more than 3 jumps from a port). The Remnant, on the other hand, have depended heavily on ramscoops from the very start. From sustaining their ships as they wanderered looking for someplace to go, to the present day with their exploration and "ready to run" mindset. Not a day goes by for the past half a millenia without a team of Remnant trying to figure out how to get better efficiency out of their ramscoops. In contrast, the Wanderers at least have a history (and an already established vault of old tech they can pull from) to explain their awesome ramscoops. They've basically spent millennia tending to the terraforming and fixing of planets. It makes sense that they'd be able to pull out great ramscoops. Doesn't really make sense that they'd be in production prior to when they think they'll need to evacuate, but definitely makes sense that they can get them out into production fairly quickly.

Given that ramscoops are *not* a combat-critical component, I don't foresee any balance problems from this change. It is likely to make early forays into the Ember Waste a little more challenging as it makes combat-optimized builds a little less viable; but overall the player should be able to overcome it with the tools they have, without even needing any of the story-locked outfits.

## Save File
This save file can be used to play through the new mission content:
No new missions or art are added.

## Artwork Checklist
 - ~~[x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
 - ~~[x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by Quantumshark** [comment]
I'm not sure your maths with the ship ramscoop changes is correct.
The addend -.02 is applied once, not once per source of ramscoop, so while it does make a single emergency ramscoop alone almost useless (or entirely useless, depending on the amount of solar wind), it doesn't make _adding_ an emergency ramscoop to a ship that already has some ramscoop useless (in fact, the small constant negative factor makes adding the same amount of ramscoop marginally more useful proportionally).

Based on your ramscoop calculator (and referencing stars.txt), the only situation I can find where 0.5 ramscoop would yield 0 fuel when directly atop a star (i.e. the `scale` from the distance calculation is 2) is in a system with only a single y-type brown dwarf - anything else, and 0.5 ramscoop when atop a star still yields at least some fuel.
Looking through the map systems file, one system fits this description: Perfica
Every other star (and thus, every other possible system) has at least .4 solar wind, and will still yield at least some fuel from any ramscoop value above .309 - so even a single emergency ramscoop will yield some fuel.
To make it impossible to be stranded with only a single emergency ramscoop, even in Perfica, you'd only need to up it from .5 to .6 (i'd suggest .8, to make it a round .2/ton)

So, the Penguin, Puffin, Petrel and Tern can run out of fuel and be unable to ramscoop in Perfica, but not in any other system and not if they have a ramscoop installed. Adding .5 to those three ships would be enough to make ramscooping there possible (actually, the required ramscoop value to get some fuel from directly atop the star is .549, so even adding .05 would be enough technically). Of course, the Petrel and Tern are carried ships, so running out of fuel isn't necessarily a problem for them anyways.
So it's only the Penguin and Puffin that would need a buff to make sure they're always able to ramscoop.

For the ships which already have lots of ramscoop, the 1.5 multiplier will exceed the effect of the flat -.02, so this change will be a net increase in their ramscooping abilities within the Ember Waste without increasing their ramscoop stat.
Using your ramscoop calculator again, it looks like the point at which the 1.5 multiplier adds more than .02 fuel/frame happens at 4.938 ramscoop in Perfica, and 2.778 in a system with .4 solar wind. At .5 solar wind, the intersection is at 1.778 ramscoop, and at .6 solar wind it's 1.235. So, any ship with 2 or more ramscoop is almost always going to be better off in the Ember Waste than out.

**Comment by Zitchas** [comment]
My math is based on using a general value of 1, given that the Ember Waste has a wide variety of stars. 

> Adding .5 to those three ships would be enough to make ramscooping there possible.

The point isn't to have *any* possible ramscooping. Definitely, a much smaller value would suffice if the goal isn't to just get it to a positive value. That's not the point. The point is to keep it at the same ramscooping potential as prior to the change for the weakest level of Remnant ships, and then adjust the whole set up equally. Yes, this does mean the ones at the top get a bit more fuel since they can benefit from the multiplier. There's no mistake in my math there, it's functioning as intended.

**Comment by Hurleveur** [comment]
The EW should be dangerous for newer players.
The EW is space that got disturbed a lot. It's easy to say the energy courants arent stable enough for the base ship ramscoop to work.
Also this does make ramscoops better with the 1.5 multiplier, its just that the first one doesnt work quite as well (maybe we should just remove the addent of -0.02?)

And just to remind a fact: this is an alternative to disabling universal ramscoop everywhere. Zitchas did not come up with that idea, I did and implemented it as a compromise.

Btw I'm no balance expert or anything but I'd honestly prefer the buff to be on the emergency ramscoop (just up it to 1 ramscoop?) rather than on the ships.

**Comment by Hurleveur** [comment]
Expanding upon that idea, since the universal ramscoop was removed in the wastes, I think the emergency ramscoop should definitely get a buff accounting for that, at the very least.
Furthermore, I believe that whatever we settle on in the end, a player coming with a human ship (say an Osprey ^^) and equipping an emergency ramscoop should have emergency fuel in any EW system. Not at an acceptable rate, that would be if they have a remnant ship, but at a rate at least.

**Comment by Zitchas** [comment]
From the very beginning, I've made a point of describing the Ember Wastes as somewhere that the rules of physics as humanity understands them in the 31st centuries keeps coming up wrong. Planets that spin faster than they should, vacuum that spontaneously *emits* energy (those ion storms aren't solar flares or weather systems moving through, that's actually energy coming out of nowhere, very specifically), space itself being massively less of a vacuum than the rest of the galaxy, (significantly more dense than the densest nebula)... This is just one more piece of the puzzle. 

Yes, the Ember Waste *is*, for all intents and purposes, a splinter of the galaxy, a small sub region where a lot of "universal" stuff turns out to be not-so-universal. This is by design, and has been from the very beginning. 

As to the exact lore of what's going on, I'll just quote Amazinite from the Preceding PR:
> Thinking of potential in-universe explanations for why the universal ramscoop might not work while outfit ramscoops still do, imagine the solar wind as a [liquid](https://tvtropes.org/pmwiki/pmwiki.php/Main/SpaceIsAnOcean) and ramscoops as filters, with larger ramscoops being larger/more effective filters. The universal ramscoop would then be analogous to a small filter, one which could be easily clogged if the liquid it were filtering were polluted in some way, while a larger filter would be able to remain unclogged, but perhaps still experience a reduction in efficiency. I feel this concept of polluted solar wind also lends itself well to the Ember Waste.

The stuff filling the Ember Wastes is absolutely *not* just a large amout of hydrogen or other fuel-appropriate elements. It's a fairly diverse range of components, so Amazinite's suggestion of having things clog up the ramscoop's mechanisms makes perfect sense to me. Ideally, those effects would be conditional so that systems designed for them would ignore the blocking effect instead of it just being overpowered, but that wasn't even an idea when the original was made and it would be unfair.

> I don't think it makes a lot of sense for universal ramscoop to behave differently in the EW from a gameplay perspective either, as it's not like navigating the EW is particularly fuel-intensive given the huge amount of wormholes that greatly cheapen travel. This wouldn't really add anything to the way people play the game (really, where are the people spending 2+ hours in the EW collecting fuel with universal ramscoop?), which again is why it feels to me like you just want the EW to operate under your preferred rules, even if they have almost no effect. For this to actually make sense as a quirk of the EW, it would need to actively change the way ramscoops work in general, not just the backend, non-canon version that is there purely for QoL.

From a lore perspective, universal ramscoop has too many implications to simply just ignore it. Either it is *not* default on (just available as something that can be activated by those who want it), or it is part of the world, and people can just choose to turn it off if they really want to. Something that requires a gamerule to turn off means it is about as cononical as any other in-game mechanic that requires a plug-in or data editing to change. That means that universal ramscoop *is* part of the lore, explicitly so. That does reinforce some early design choices and locks out other things. For instance, it explains why the Archons were so careful about ensuring *all* hyperlink routes were cut between areas, even taking care to ensure that there was no backroute 60 jump long not-really-a-route-but-something-someone-could-use-to-get-between-areas. If universal ramscoop is a thing, then that 60 day long ramscooop is no more an obstacle than, say, the Atlantic was to people traveling from Europe to North America in the 1600-1700s. A challenge? Yes, but one that is  perfectly understanable, surmountable, and can even be trivialized with some proper preparation. The fact that some players find waiting a couple minutes to regenerate fuel to be unbearably long has zero relevance to limiting how far the general spacefaring population would be willing to wait in pursuit of exploration, curiosity, and perhaps new riches. Universal ramscoop closes that plothole, and provides justification for that already existing design choice. Honestly, I'd have preferred we reverse it and go the other direction, as I am very much a fan of early-game true exploration (not just this "exploring a new city" exploration). But we're not. Amazinite made their choice, as did other vocal people. So that door is closed, and the lore will be that accordingly. This isn't a situation where "it's just a mechanic we can ignore and pretend isn't part of the lore." It is, or it isn't. We have chosen "is", so that's the way it is.

> Expanding upon that idea, since the universal ramscoop was removed in the wastes, I think the emergency ramscoop should definitely get a buff accounting for that, at the very least. And for the -0.02 if we do add that.
> Furthermore, I believe that whatever we settle on in the end, a player coming with a human ship (say, an Osprey ^^) and equipping an emergency ramscoop should have emergency fuel in any EW system.
> Not at an acceptable rate, that would be if they have a remnant ship, but at a rate at least.

Yes, that's the intent. I chose -0.02 because, for a generic power 1 system, that level of ramscoop blocking leaves the standard ramscoop functional, just noticeably slower. If they have just a single one, in said generic system, it should be about half the usual rate. 

That being said, I will go through all the Ember Waste systems and find out what the actual minimum solar wind is, and verify that the generic ramscoop will always generate at least a small amount. (greater than what universal would have)

**Comment by Hurleveur** [comment]
Ok, but why buff both the outfit and the ships?

**Comment by Zitchas** [comment]
Because the last half a millenia of Remnant development (as well as most of the alien tech they found) is specifically adapted to life in the Ember Waste. So the outfit and the ships get bumped up slightly to keep them at the same point as they were previously.

There's also the practical side that the Emergency ramscoop (at the generic 1 solar wind) is actually in the negative. I know, it can't actually lose fuel. But it is entirely useless. Remnant ships are notorious for being tight on space, so stacking isn't an option. And beyond that, they'd never bother to produce something that is useless.

**Comment by Zitchas** [comment]
Alright, I just did some analysis of the Ember Waste, giving the following data:

**Info:** | **Result**
-- | --
**Total Systems:** | **44**
**Total stars:** | **53**
**Stars with Wind <1:** | **26**
**Minimum** | **0.30**
**Maximum** | **10.00**
**Average** | **1.39**
**Median** | **1.00**

Looking into it a bit more, the average is swung upwards significantly by Caeculus (4), Patir (8), and Antevorta (10). Omitting these three drops the average of the Ember Waste down to 1.03. The bottom end doesn't really have the same extremes, as it goes .3, .4, .5, .51, .55, .6... But just to be balanced, if we omit the lowest three (Perfica, Paeli, and Feraticus) such that we are omitting the extreme 3 on either end of the set, then our average becomes 1.07. 

Given that the median is 1, and the two variations without the most extreme 3 systems' averages are 1.03 and 1.07; I think my use of 1 as a baseline is reasonable for the overall values. I'll take a look at the Terminus entry system, Nenia, and the other systems along the route between those and the Remnant to ensure that there isn't any stretches where the standard ramscoop (singular. I'm not expecting or requiring anyone to have more than 1 just to avoid getting stuck in the Ember Waste) would get stuck.

I'll edit my findings into this spot once I have them.

As an aside, I'll note the presence of a `neutron-core` and a `carbon-core` which are both listed as stars in `map systems` but have no corresponding listing in `stars`.

<details>

<summary>Table of Ember Waste Systems and Stars</summary>

**System** | **Star(s)** | **1st Star Wind** | **2nd Star Wind**
-- | -- | -- | --
Levana | A-giant and k5 | 1.7 | 0.82
Fereti | a5 | 0.55 |  
Esix | b5 | 0.51 |  
Feraticus | browndwarf-l-rouge | 0.5 |  
Paeli | Browndwarf-t-rouge | 0.4 |  
Perfica | browndwarf-y-rouge | 0.3 |  
Antevorta | carbon and carbon-core | 10 | ?
Convector | f-giant | 1.8 |  
Arculus | f5 | 0.6 |  
Nenia | f5-old and g5-old | 0.9 | 1.1
Ossipago | f5-old and m5 | 0.9 | 1.05
Edusa | g-giant | 1.9 |  
Aki'il | g0 | 0.64 |  
Lire | g0 | 0.64 |  
Nona | g0 | 0.64 |  
Polerius | g0 | 0.64 |  
Egeria | g0 and k5-old | 0.64 | 1.5
Peragenor | g0-old | 1 |  
Queri | g3 | 0.66 |  
Giribea | g5-old and g8 | 1.1 | 0.72
Stercutus | g5-old and m0 | 1.1 | 0.9
Parca | g5-old and m8 | 1.1 | 1.1
Gerenus | k-giant | 2 |  
Cinxia | k0 | 0.75 |  
Delia | k0 | 0.75 |  
Dixere | k0-old | 1.3 |  
Fearis | k0-old | 1.3 |  
Relifer | k0-old | 1.3 |  
Ritilas | k0-old | 1.3 |  
Pantica | k3 | 0.78 |  
Cardea | k5-old | 1.5 |  
Coluber | k5-old | 1.5 |  
Diespiter | k5-old | 1.5 |  
Segesta | k5-old | 1.5 |  
Farinus | k5-old and m0 | 1.5 | 0.9
Lucina | m0 | 0.9 |  
Vaticanus | m0 | 0.9 |  
Insitor | m0 and m3 | 0.9 | 0.95
Aescolanus | m3 | 0.95 |  
Postverta | m8 | 1.1 |  
Statina | m8 | 1.1 |  
Patir | nova and neutron-core | 8 | ?
Prosa | o-giant | 1.5 |  
Caeculus | wr | 4 |  
  | **Minimum** | **0.30**
  | **Maximum** | **10.00**
  | **Average** | **1.39**
  | **Median** | **1.00**
  | **Total stars:** | **53**
  | **Stars < Wind 1:** | **26**

</details>

**Review by EjoThims — APPROVED** [review]
I do think this is an appropriate thematic change, and I'm okay with that list of risks and slowdowns, especially since either place there's any chance of basic preparation still stranding you has ample amounts of either help or enemies that are going to prevent soft locking by either killing you or eventually giving you fuel from boarding.

**Review by Hurleveur — APPROVED** [review]
I dont have much to say in terms of content, but I like this making fuel in the waste weirder, and I think it makes sense to adapt most ships to compensate for it
I'm not sure on touching the biggest ships (because they do get x1.5) but if anything it shows the remnant care about their biggest ship too
I think that the best way to know if it is right is to get it in game so it can be tested, though

**Review by MasterOfGrey — APPROVED** [review]
Purely from a thematic pov, reading through the discussion and things, this gives good vibes.

**Comment by Saugia** [comment]
We'll go ahead with this and see where it takes us. Anything merged is still susceptible to change. From what I've read, this seems like an appropriate thematical change for the Wastes, and there is solid points to back it up. There's nothing stopping us if we wish to change it in the future anyway.

**Pull request merged**
