### PR TITLE
feat(enhancement): Scripting support via shared libraries

### PR DESCRIPTION
**Pull request by tibetiroka**
**Feature**

This PR addresses the bug/feature described in issue #1841

## Summary
Adds basic scripting support via shared libraries. Since it's running native code, the performance hit should be minimal compared to using a scripting language like Lua or Python.

It also avoids having to maintain third-party bindings, since our header files are already fit for compiling shared libraries.

It takes 59 lines of code to support shared libraries; the rest is for the trigger system demo.

## Usage examples
Plugins could use this system to replace or enhance any standard function that triggers get added to. Plugins could even provide bindings for Lua or other languages, if they wish, without burdening the development of the game.

## Testing Done
Basic testing was done to ensure that the loading of shared libraries works. I haven't really tested the latest version of the trigger system yet.

You can compile shared libraries by linking against the headers from EndlessSkyLib. (For instance, you could include endless-sky as a submodule, delete all cpp files, then use the EndlessSkyLib target in cmake.) This cmake config works for a similar setup:
<details>
```
cmake_minimum_required(VERSION 3.29)
project(scripting_demo)

# Configure C++ options
set(CMAKE_CXX_STANDARD 20 CACHE STRING "" FORCE)
set(CMAKE_BUILD_RPATH_USE_ORIGIN ON)


# Create script target (Plugin.cpp is the only source file in this plugin)
add_library(scripting_demo SHARED Plugin.cpp)

# Pull in the ES library
target_include_directories(scripting_demo PUBLIC endless-sky)

# Configure build options
target_compile_options(scripting_demo PUBLIC "-fPIC")
```
</details>

## Wiki Update
Not until I know it's getting anywhere.

## Performance Impact
Triggers would have a performance impact, but it should be minimal without plugins.

### CODE REVIEW

**Comment by Koranir** [comment]
Lua and other scripting languages are environment-agnostic and simple to use, which is good for the content creators who would be willing to use these scripts to improve their work.

Making plugins use compiled shared libraries introduces a significant barrier to entry for the average plugin developer, making them have to mess around with raw C/++ or language FFI. In addition, these shared libraries would have to be compiled for each platform they want to be used on, and the base game will have to use `extern "C"` or another stable abi to stop plugins from breaking every time a class' layout is changed.

Overall, I don't think this is a great way to implement custom user code for the game. Endless Sky is _not_ a very heavy game, and scripting languages are more than fast enough for simple purposes.

**Comment by tibetiroka** [comment]
> Lua and other scripting languages are environment-agnostic and simple to use, which is good for the content creators who would be willing to use these scripts to improve their work.
> Making plugins use compiled shared libraries introduces a significant barrier to entry for the average plugin developer, making them have to mess around with raw C/++ or language FFI.

If someone wants to use a scripting language, they can add a dependency on a plugin that provides support for that. I looked at how lua bindings work, and I can tell you right now that they are never going to be part of the base game in that form - it's ugly as hell and difficult to maintain.

> In addition, these shared libraries would have to be compiled for each platform they want to be used on

Can be automated. The game itself is also compiled for every platform.

> and the base game will have to use extern "C" or another stable abi to stop plugins from breaking every time a class' layout is changed.

Nope. If we want a stable api, we also have to have deprecation and legacy support for code internals, which is likely to cause some serious spaghetti down the road. And how often do class layouts change, anyway?

If the class layout changes, the plugin author just has to recompile the plugin. No code changes necessary. I wouldn't expect even this to be a common case. But let's say that we use `extern "C"`.  It will not:
 - work for class members
 - work for overloaded functions (including templates I believe)
which makes it rather useless. The plugins' init functions have to use it, but that's about the only place where it's useful.

**Comment by RisingLeaf** [comment]
For me this is a do it right or leave it type of situation,
what you are adding is not scripting support, if I have to automate a process that compiles my lib for different platforms, it is just easier for me to fork the game and deploy an executable for the fork.

If you do not want to add lua support, fine (although I think we are missing out), but do not add an alibi solution to point to when someone asks for scripting support. This solution only appeals to people who already know how to code c++ and I do not see why they should use this solution. And I doubt a lot of plugin creators know their in and outs of c++.

Apart from that this PR again adds more dependencies to the deal (boost), which I do not think help to maintain a small dependency graph at all.

To make it short I do not see any benefit from adding shared libraries and I would want to avoid this solution.

**Comment by tibetiroka** [comment]
Do you know what "Lua support" actually looks like? I generated bindings based on our _public_ data members and functions, and it looks something like this:

[generated.txt](https://github.com/user-attachments/files/16232416/generated.txt)

Now imagine if all of our private members were protected/public and we could bind to those ones as well. It would require waaaay more code. (Also, this doesn't even support templated types at all. That complicates things a LOT.)

There is no way something like this would ever get added to vanilla. It's not maintainable.

It can be added to a plugin without problems, though, since it's automatically generated and the maintenance doesn't have to be handled immediately. If a function isn't supported, it's not going to cause problems, it won't fail builds on unrelated PRs randomly - it's flexible enough. It would still take effort to maintain, but that wouldn't mess with development in general.

**Comment by RisingLeaf** [comment]
Obviously we would not auto generate these bindings, I imagine we would select items that lua should be able to control.
Anyways I am not arguing about whether to implement lua on this PR, all I am saying is that I do not think this is a solution befitting the problem that was presented by the plugin authors who requested scripting support.

**Comment by petervdmeer** [comment]
Added the `unlikely` label; loading `.so` or `.dll` files directly from the plugins directory suddenly allows plugin creators to run arbitrary code on our players PCs. That is quite undesirable from a security point of view. (And we also shouldn't want to support that.)

**Pull request closed without merging**
