### PR TITLE
Small tweaks to the particle cannon projectile and effect

### PR DESCRIPTION
**Pull request by AzureNyoki**
The projectile now looks less flat, and the impact effect now has a smooth fade out, and isn't left hanging in space.

### CODE REVIEW

**Comment by tehhowch** [comment]
In the future note that you don't want to merge your feature branch into your master branch.. just set up the PR from your feature branch. Otherwise every PR you make is going to include possibly rejected, possibly duplicated commits, and likely unrelated changes.

**Comment by AzureNyoki** [comment]
Noted, thank you. I'm still learning the ins and outs of this.

**Comment by endless-sky** [comment]
The trouble with bright sprites moving very quickly is that rather than looking like a continuously moving object, they can look to your eye like a dashed line due to persistence of vision. For example, here is what several particle cannon frames look like when overlaid, using the original sprite (left) and yours (right):

particle

To my eyes, at least, the effect is really obvious with your new sprite.

As for the impact effect, I think the real issue is just that the lifetime is too long given the frame rate (it reaches the final frame of the animation after 15 frames, then stays around for another 20). But that could be fixed just be reducing the lifetime from 35 frames down to 20 or so.

**Comment by KiLEdEnNis** [comment]
wouldn't that mean it'd get either a shorter range or more velocity to compensate?

**Comment by Bladewood** [comment]
It's just a visual artifact, nothing more.

**Comment by KiLEdEnNis** [comment]
well if the lifetime would go down the range would automatically go down, unless I misunderstood something

**Comment by SirStigII** [comment]
They are talking about the impact frame life I believe, not the projectile.

**Comment by KiLEdEnNis** [comment]
ah you're right ("As for the impact effect"), my bad

**Pull request closed without merging**
