### PR TITLE
feat(content): New Argosy & Modified Argosy Variants

### PR DESCRIPTION
**Pull request by bene-dictator**
**Content (Ship Variants)**

## Summary
This PR adds five new Argosy variants and three new Modified Argosy variants, making use of Plasma Cannons, Modified Blasters and Twin Blaster variants. It also adds them to `fleets.txt`.

It doesn't make use of the Plasma Repeater, which will come in another PR. This PR is one of the PRs I am submitting to take chunks out of #7837. 

## Save File
Go south and fight some pirates.

## To-do
- [ ] mmm testing

### CODE REVIEW

**Comment by Hurleveur** [comment]
This increases the proportion of this ship we see, maybe we could tweak the variant to make it not be the case? (Increase the rest)
Or maybe its not really an issue

**Comment by bene-dictator** [comment]
That would be a good idea, especially because I'd think the Modified Argosy (Particle Cannon) should be particularly rare.

**Comment by bene-dictator** [comment]
Man, going down south with these Particle and Plasma Cannon equipped Mod Argosies can be really dangerous now : )

**Comment by bene-dictator** [comment]
I'm considering removing the Modified Argosy (Particle Cannon) variant from common spawns because it's too far south for Particle Cannons. In addition I'd think that the people with the connections to get Particle Cannons would have the connections to put them on better ships like Bastions and Firebirds.

Otherwise, I could change the Particle Cannons to Proton Guns, which already are around in the Southern Rim with the Proton Furies.

**Comment by bene-dictator** [comment]
> This increases the proportion of this ship we see, maybe we could tweak the variants to make it not be the case? (Increase the rest) Or maybe its not really an issue

I am also still thinking about adding other new ship variants too. The issue won't be as big if that continues to happen.

**Comment by Amazinite** [comment]
Given the pain of adding new ship variants to existing fleets, I'd honestly rather we not add a bunch of new ship variants until #4704 is resurrected and finalized (which I want to take a look at during v0.10.3). Sure, the work has already been done in this case to add the variants to the fleets, but it only makes fleet definitions more cluttered and difficult to visually parse than they already are. And as noted by Hurl, any such changes mean we need to be very careful about how we're changing the proportion of certain ships in fleet spawns (an issue which would similarly be helped by #4704 in that we could create lists of every variant of a ship that we could add to, while keeping the use of that list unchanged in the fleet definitions so as to not actually change the appearance rate of ships).

**Pull request closed without merging**
