### PR TITLE
Add the Scrapper to Bounty/Escort Jobs

### PR DESCRIPTION
**Pull request by Anarchist2**
This PR allows the Scrapper to show up in the smallest escort and bounty jobs. It also rebalances the weights on the smallest bounty job to reduce the amount that the Wasp shows up.

### CODE REVIEW

**Comment by LorenzoBolla** [comment]
I always found Wasps were too common in those small bounties. Great change!

**Review by Zitchas — APPROVED** [review]
I think this is a good addition, and makes the missions a little more varied. Also means that there will be an opponent that even under-prepared pilots pushing their luck might be able to defeat. Sometimes.

**Comment by TomGoodIdea** [comment]
I think it would still make sense if the Scrappers were flying in groups of two or even three.

**Comment by 1010todd** [comment]
It would actually make more sense if they fly in a group of two or three at least for bounty jobs, typical lone Scrapper probably isn't threatening enough for a bounty.

**Comment by Zitchas** [comment]
As a counterpoint: A criminal can be too pathetic to waste sending Navy resources after. Not all bounties have to be extra strong. The Navy (or local law enforcement) might be too busy dealing with *serious* problems, and thus request that some concerned citizen deal with this particular threat.

**Comment by Luuiscool4567** [comment]
Least genocidal bounty hunter

**Comment by LorenzoBolla** [comment]
Could easily have groups of scrappers appear as another option. A Wasp, a Scrapper, 2 Scrappers.

**Review by Saugia — APPROVED** [review]
I think this is a good change as-is. I'm not sure about having groups of Scrappers, to me it makes more sense to have them here and there, especially for early game. It also allows more variety and interesting interactions in the early game, rather than "hey another 3 scrappers", etc..

**Pull request merged**
