### PR TITLE
Suppress package usage information

### PR DESCRIPTION
**Pull request by quyykk**
This PR suppress the long package usage information that is printed when configuring:

```
The package glew is compatible with built-in CMake targets:

    find_package(GLEW REQUIRED)
    target_link_libraries(main PRIVATE GLEW::GLEW)

The package libjpeg-turbo is compatible with built-in CMake targets:

    find_package(JPEG REQUIRED)
    target_link_libraries(main PRIVATE ${JPEG_LIBRARIES})
    target_include_directories(main PRIVATE ${JPEG_INCLUDE_DIR})

The package libpng is compatible with built-in CMake targets:

    find_package(PNG REQUIRED)
    target_link_libraries(main PRIVATE PNG::PNG)

libuuid provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-libuuid CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::UUID::uuid)

The package openal-soft provides CMake targets:

    find_package(OpenAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenAL::OpenAL)

sdl2 provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main
        PRIVATE
        $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>
        $<IF:$<TARGET_EXISTS:SDL2::SDL2>,SDL2::SDL2,SDL2::SDL2-static>
    )
```

### CODE REVIEW

**Review by RisingLeaf — APPROVED** [review]
did you tested it?

**Comment by quyykk** [comment]
of course

**Comment by warp-core** [comment]
Is something goes wrong, will this prevent it from printing error information?

**Comment by quyykk** [comment]
No, this is only suppresses the usage lines that describe how to use the libraries, which is only useful when adding a new library. But in that case you could just look up the usage, It doesn't seem worth it to print all those lines every time.

**Review by warp-core — APPROVED** [review]

**Pull request merged**
