### PR TITLE
Allow subphrases within phrases

### PR DESCRIPTION
**Pull request by sfiera**
The motivation here is an INN-like system. There are already some appropriate phrases, like sports team names or Syndicate advertisements, that would be nice to thread through both systems.

### CODE REVIEW

**Comment by jmhorjus** [comment]
Looks like a smart addition.  

Do we need to guard against infinite loops?
Like if I made a phrase A that contained phrase B that contained phrase A...would my computer explode when it tried to resolve this?

**Comment by sfiera** [comment]
Hmm. Yes, it's possible to create an infinite loop (well, infinite recursion; we'd blow the stack and crash, not hang). I don't think you'd anything that complicated, just:

    phrase crash
        phrase crash

It would be fairly easy to limit the recursion depth (probably to something moderate and hard-coded; say 16).

**Comment by egilburg** [comment]
alpha...epsilon could likewise expand to greek alphabet subphrases.

**Comment by lehgogh** [comment]
Also, for debugging reasons, should there be a command line warning message for using recursive phrases?

`WARN: map.txt line <something> - Recursive phrases detected.`
`ERROR: map.txt line <something> - Recursion limit reached; failed to complete phrase.`

Something like that, just to help modders debug their plugins?

**Comment by sfiera** [comment]
I tried to detect recursion; this supersedes the previous commit (which should be squashed and removed before merging). Maybe this works; maybe it doesn't. Is there a recommended way to test?

**Comment by sfiera** [comment]
I didn't add a subphrase for Alpha...Epsilon because it would only be used in one place. Republic and Deep fighters both use greek letters, but Republic fighters also use colors, so it wouldn't be as simple to replace with a subphrase (maybe Republic should use only colors anyway).

**Comment by endless-sky** [comment]
Thanks! Sorry for the very long delay in merging this - I got kind of buried under the sheer number of issues to handle...

**Pull request merged**
