### PR TITLE
Condensing "Food" into more useful categories

### PR DESCRIPTION
**Pull request by Thunderforge**
The former list of "food" categories is a little unusual in how specific it is. It's honestly a little silly to get a mission to transport 80 tons of frozen pizzas or 130 tons of brownie mix. Therefore, I have removed many of the sillier items and instead used broader categories. There are a couple of reasons for this:

 - It removes the silliness of transporting enormous quantities of oddly specific and niche items
 - It is more realistic in that a shipment would include several items (e.g. a truck carrying food in the real world would likely have more than one type of item to a store that requests several items from a supplier).
 - It gets us away from Earth-based food items and leaves room for the player to imagine other types of things that are discovered on other planets. For instance:
     - "Seafood" would encompass catfish and [treel](http://babylon5.wikia.com/wiki/Treel)
     - "Lifestock" would encompass cattle and [nerfs](http://starwars.wikia.com/wiki/Nerf)
     - "Alcoholic beverages" would encompass whiskey and [Romulan ale](http://memory-alpha.wikia.com/wiki/Romulan_ale)

I believe that there are still plenty of categories to give sufficient variety in missions. If this pull request is well-received and implemented, I am happy to create pull-requests like this one for each of the other categories (shipping 90 tons of bedpans? Really?).

### CODE REVIEW

**Comment by Pointedstick** [comment]
I really like the minor silliness in the commodities list. You could make the same complaint about a lot of the other oddly-specific things in other categories: "resorcinol glue" instead of "construction adhesive," for example, or "cough drops" instead of "medicine.". I think these things add character to the game.

**Comment by Thunderforge** [comment]
As I put in the pull request description, I would like to create similar pull requests for the other commodities, such as the medicine category, should this get approved. I am of the opinion that the silly list clashes with the tone of the game, certainly the one described in the mission-writing guidelines.

**Comment by ItsNickBarry** [comment]
It can be assumed that the commodities on the list are produced by economies of scale, and that each planet produces whichever commodity is [comparatively advantageous][ca].  The player isn't delivering food to the grocery store, but to the planetary distribution center, which may serve billions of people.

I don't like every item in the list, but the focus on present-day foods does make some sense.  Not only would early colonists have brought species from Earth for the purpose of terraforming, but they also would have brought their culture, including a taste for avocados.  With that said, what are avocados anyway?  After 1000 years of incremental genetic modifications, they might be the futuristic fruit you're looking for, while still retaining their original name.  Whatever happens, "avocados" will always have more flavor than "foodstuffs."
[ca]: https://en.wikipedia.org/wiki/Comparative_advantage

**Comment by endless-sky** [comment]
> shipping 90 tons of bedpans? Really?

I'm sure that has a reasonable in-game explanation - say, an epidemic of that dreaded and disgusting virus, the Aldebaraanian Stomach Flu.

**Comment by frameworld** [comment]
Latest Wanderer-missions have a planet with adult and sick Wanderers on one planet. Sort of a retirement for those who can't fly anymore.

I guess 90 tons is not much for a whole planet, if Wanderer even build bedpans, or anything that special off-planet

**Comment by guillochon** [comment]
I think it's perfectly reasonable to have a shipment of 130 tons of brownie mix. Sales of brownie mix from General Mills alone totaled $142 million ([source](http://www.statista.com/statistics/488406/dollar-sales-of-the-leading-us-brownie-mix-companies/)), and at $0.10/oz, that amounts to 45,000 tons of brownie mix. Perfectly reasonable to expect a single shipment could be hundreds of tons.

**Pull request closed without merging**
