### PR TITLE
remove alpha as drone names

### PR DESCRIPTION
**Pull request by MCOfficer**
it might be nitpicking, but i feel like alpha may no be considered a suitable name in a galaxy that is still in constant memory of the alphas.
it's like the number 13. only few believe in it's evil power, most laugh about it, but still there is no row 13 in airplanes (iirc).
just a tiny detail, but it's the details that make the athmosphere.

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
alpha is a letter in the Greek alphabet, I don't see why they should not use it
and check all story files to see if there are no fighters that spawn w/ a set name
and remove sectors like Alpha Centauri
get my point? the Alphas aren't called Voldemorts because their names can just be spoken and their name happens to be a word that's used

**Comment by jafdy** [comment]
I think this is the difference between Alpha and α. The first one is the name of a group of sociopaths and the other is a Greek letter often used to imply "first".
I don't think many people will be at all concerned that the Republic use it in their fighter squadrons. 
Personally I would be more worried if the Reps *didn't* use it out of fear.

**Comment by gunqqer** [comment]
I feel like this would be an interesting lore point. After the Alpha wars the greek alphabet falls out of use due to the fact the first letter makes everyone think of the war.

**Comment by MCOfficer** [comment]
> I think this is the difference between Alpha and α. The first one is the name of a group of sociopaths and the other is a Greek letter often used to imply "first".

 looking at the meaning of alpha, there is no real difference between the letter and the group of sociopaths. they were called like that because they see themselves as superior to the human race.

> and remove sectors like Alpha Centauri

it's a set name for a sector that was known long before the alpha wars.

> alpha is a letter in the Greek alphabet, I don't see why they should not use it

it's like the swastika. in most parts of the worlds it is (still) seen as kinda harmless, even though "a groupd of sociopaths" (hehe) used it for terror and dictatorship. in russia, it is mostly known under it's original meaning. however, it is forbidden to use it in germany. you get my point? i think you are unerestimating the human need to judge upon stuff represantative of a certain happening. the bigger and more horrible an event is, the more "heavy" the sign that stood for that event gets banned (also think about hard judgement for rapists as a warning example). and if the alpha wars had such a great impact on the galaxy as the storyline suggests, i doubt that humans would think of something else than this particular war when hearing the word "alpha".

**Comment by jafdy** [comment]
>on many worlds the Alphas are treated as nothing more than a bogeyman story to frighten children . . . on some worlds kids even run around wearing green face paint on Remembrance Day, trying to frighten people

That would be equivalent to people dressing up as nazis on our remembrance day if that's what you want to compare. Also;
>2450: The first "Alpha War"

This is over 500 years in the past. So it would be more like comparing it too something like the war of the roses. 

If I have offended someone I apologise.

**Comment by Bladewood** [comment]
https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

**Comment by Tadrix** [comment]
@Bladewood (quote from wiki article):
> "Delta" is replaced by "Data", "Dixie" or "David" at airports that have a majority of Delta Air Lines flights, such as Hartsfield-Jackson Atlanta International Airport, in order to avoid confusion because "Delta" is also Delta's callsign.

@gunqqer 
> greek alphabet falls out of use

And then the word "alphabet" falls out of use also. Because of "alpha" in it, hehe. Silly humans.

Various SF works tried to create altered phonetic alphabet as well, for example using epsilon for E.
[Here's another example.](http://web.archive.org/web/20161116153749/http://en.battlestarwiki.org/wiki/Colonial_wireless_alphabet)

There's no need to cling to NATO standard, seeing as it is only one of many used during 20th century, and that it's more than likely that another standards will be introduced during 21st or 22nd centuries.

On this issue I'd rather mostly agree with jafdy — nobody cared until recently. However, during both Alpha wars phonetic letter Alfa would likely be swapped for something else for similar practical reasons civil aviators swap Delta for something else — to avoid confusing letter with one of belligerent parties.

**Comment by KiLEdEnNis** [comment]
> it's a set name for a sector that was known long before the alpha wars.

and Alpha was also a set Greek letter long before the alpha wars, they probably used it as planet fighter names, ships, whatever too
and a swastika is a logo made by a sociopath, he didn't use an existing letter (although maybe he pasted 4 L's)

so no, I really don't get your point and this issue seems unneeded imo
I agree w/ jafdy

**Comment by Tadrix** [comment]
@KiLEdEnNis Offtopic, but [check your history facts](https://en.wikipedia.org/wiki/Swastika#Prehistory). You just proved MCOfficer's point by ignoring last 11000 or so years of human history while remembering 11 years of one moron's reign.

**Comment by KiLEdEnNis** [comment]
he stole the cross, not the entire flag
and either way I don't see how a ripped-off windmill design used by a tyrant can be compared to a word that's used to describe a group
using the word Nazi isn't illegal either, and about no one is scared of the word Nazi

**Comment by MessyMix** [comment]
@KiLEdEnNis, you say some true things.

Having said that, if I were a Navy Admiral, I would not name a carrier-based fighter group "Nazi squadron", I would name it "Gamma Squadron". lol.

There's a difference between saying the word, and naming my ships after the word.

**Comment by jafdy** [comment]
But Alpha is already a Greek letter. nazi is not, it was the name of a political party. And again I would like to point out the **500 year** gap between the start of the game and the alpha wars.
While during the war itself they may not have used Alpha for the sake of communication the 500 years is more than enough time for it to come back into use.

**Comment by KiLEdEnNis** [comment]
I never heard a fighter squadron named after "Nazi"
"Nazi Führer, we lost Nazi 6"
"copy that Nazi 2"
Alpha IS a squadron name

**Comment by MCOfficer** [comment]
> I never heard a fighter squadron named after "Nazi"

yes, we cannot compare this alpha problem with anything we know, because we simply never had athe case where letter gets misused by some idiots, causing a horrific war (letters U, S and A don't count :P ).
but that does also mean that we can't tell for sure what happened after the alpha wars to the letter alpha. i personally like the idea that it was "kinda-banned". it's just one of these small, easter-egg-ish details that add to a good game.

**Comment by Wrzlprnft** [comment]
i personally think 500 are enough. especially once jokes are no longer socially frowned upon, as well as soon as someone has the idea that not using it shows fear. in a time of peace, this might outreign the military convenience to not use it.

**Comment by Tadrix** [comment]
True, but the thing is that by then alfa would be long ago replaced by something else, and unfortunately people tend to leave alone established things and practices everyone's used to, including cases when change would be just change back to original system (all modern history consists of this). Hell, even changes for the better might be rejected.

**Comment by Wrzlprnft** [comment]
giving that the normal people hardly use alpha except when for some sort of fancy counting, as well as the alpha war was a bit smaller than one would expect and the fear came from the potential of the alphas, i would assume the military would not use it during the conflict, but afterwards, since it being the established system, it would sneak back.

**Comment by Tadrix** [comment]
Not to start an argument, but point me to at least one instance where old designations were restored after becoming deprecated. I can provide an opposite example:
Consider how during Cold War West didn't know Soviet (proper) names of their military tech, so they invented reporting names for those. Thus, [Mi-8](https://en.wikipedia.org/wiki/Mil_Mi-8) became _Hip_, [Mi-24](https://en.wikipedia.org/wiki/Mil_Mi-24) became _Hind_, [An-2](https://en.wikipedia.org/wiki/Antonov_An-2) became _Colt_, and so on. Nowadays, nearly 30 years have passed since Cold War ended. NATO still uses those same reporting names, disregarding proper naming.
I don't see the reason why, if the military indeed changed _alpha_ to something else during the war, it would sneak back. Immediately after the Alpha war, memories were still fresh and people wouldn't do this; some centuries later there's even less incentive to change something, because they would need galaxy-wide computer updates, change procedure manuals (also for civilians, since spaceports service both military and civilian ships), rewrite documentation, standardize everything, and so on. Only way alpha could make a comeback — if all phonetic alphabet would be changed at some point. For one letter there's too much hassle to bother. And, using NATO phonetic alphabet, Endless Sky implies it hasn't changed for at least millennium.

If you would in charge of communications authorities at some point, say, in 29th or 30th century, would you really bother to change a latter? Or you would rather devote time and resources to something more productive? "Sneaking back" is nonsense; people are inert, there has to be a real need to change anything.

**Comment by jafdy** [comment]
That would imply that there is a "standard" way to name fighter squadrons. As long as it is recognizable name a fighters call-sign could be anything. 
If nothing else the word will stay in use because of things like the bible ("I am the Alpha and the Omega." Revelation 1:8) or because mathematicians would continue to use it because of the need for new letters to stand for things.

**Comment by MCOfficer** [comment]
ok, this got a lot further than i ever expected. you both have a point one cannot deny, and i am not so sure if alpha would get kicked out forever or not. truth is, all we can do is judge from our understandment of the ES universe. and since this universe belongs to MZ, he's probably the only one who can tell the truth :smile: not to mention that he will have to decide anyways. i personally will leave it up to him, as i fell like it's all said and done. and i'm kinda scared this will turn into a fight :P

**Comment by Tadrix** [comment]
@jafdy I agree with your last comment. My point was only about phonetic alphabets and other such things which have standing standards.

**Pull request closed without merging**
