### PR TITLE
typo fix in a There Might Be Riots transport mission

### PR DESCRIPTION
**Pull request by KiLEdEnNis**
starting asking > started asking

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
also a little later when you drop them off in Hai space "I rented a shuttlecraft under an assumed name and went tooling around the galaxy"
should tooling be touring?

**Comment by DingusShingleton** [comment]
Definition 13:
to drive (a vehicle):
He tooled the car along the treacherous path.

**Comment by KiLEdEnNis** [comment]
ah thanks, google translator isn't the best dictionary :P

**Comment by KiLEdEnNis** [comment]
and is it me or does that timer ship thing not work? the dialog won't pop up after several minutes and I'm not planning to alt tab for 3 days like that TMBR guy did

**Pull request merged**
