### PR TITLE
Assigns a default value to the new ship name field based on civilian ship names.

### PR DESCRIPTION
**Pull request by guillochon**
Addresses https://github.com/endless-sky/endless-sky/issues/328.

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
Good idea, i like it.

**Comment by Pointedstick** [comment]
Very nice!

**Comment by guillochon** [comment]
I think it'd be great to make this a bit smarter; for instance if you buy a ship in a pirate system your ship gets a pirate name. But I wasn't quite sure the best way to go about that, should ship names depend on system alone? Or ship type?

But for now I do think that giving ships default civilian names is better than nothing.

**Comment by Wrzlprnft** [comment]
I would say ship type.

**Comment by johndh** [comment]
Another possible consideration would be the player's faction.  If you're a flying for the Free Worlds, it would make sense for your ships to take names from their list, or at least get "F.S." before the name.

**Comment by Tufton** [comment]
Or we could just do [Character Name]'s [Ship Name] for default.

**Comment by endless-sky** [comment]
There seems to be something odd in the diff, because it says this would add changes to Dialog.h, but those changes are already in the latest code. Maybe your branch has to be rebased to the latest master version?

**Comment by guillochon** [comment]
Not sure what you mean, Dialog.h did change, I added a new function to it to pass a default value into the dialog.

**Comment by endless-sky** [comment]
Ah. Well, it's the same change as in commit f46b11b, so you should be able to just use the function from that commit.

**Comment by endless-sky** [comment]
Oops, never mind, I see it's passing a string initial value rather than an int.

**Comment by endless-sky** [comment]
In this form, this change would mean the player must delete the default ship name before typing in their own choice of a name, which is made more difficult by the limited editing capability for text entry fields. I wonder if it would make more sense to instead only generate a name if no name is given.

**Comment by guillochon** [comment]
The inability to select text really does limit the options here, I would have liked to have it start with the text pre-selected, but as you said that's currently not possible.

**Comment by Pointedstick** [comment]
Maybe add a button that replaces the content of the text field with a new randomly generated ship name. With this, you wouldn't have to pre-populate the text field with any text, working around its limited capability. Additionally, if you were having trouble thinking of something yourself but didn't like the random name it came up with the first time, you could have it make a new one.

**Comment by Wrzlprnft** [comment]
Random-Buttons are always a good idea :)

**Comment by guillochon** [comment]
The random button would be a nice way too, but unfortunately the dialogs don't seem to support extra buttons at the moment, without making fairly large changes to the Dialog class.

**Comment by Thunderforge** [comment]
Pity that a random button is not possible; I think that would be the right way to solve this problem from a user interface perspective. I think it would be worth investigating what changes need to be made to the Dialog class to allow for it.

As for the name categories, I think that it should be based on ship class. For instance:

> **Light Freighter:** Terrapin, Scarab
> **Heavy Frieghter:** Behemoth, Leviathan
> **Fighter:** Wasp, Viper

Including factions as a category makes sense too (e.g. adding F.S.).

**Comment by luiges90** [comment]
For minimal change, I think we can consider giving the ship the random name if the player leaves the name blank and hit OK...

**Comment by ph2000bis** [comment]
I agree with @luiges90

**Comment by endless-sky** [comment]
There's a couple of problems with this, including that the "civilian" names include a bunch of individual people's names, that will generally not match the player. For now I've just changed it to give unnamed ships the name "`<first>'s <model name>`", e.g. "Michael's Kestrel."

**Comment by guillochon** [comment]
Closing this because @endless-sky has a better solution, for now. Would still like to see text be selectable in the game so that dialogs can have default values.

**Pull request closed without merging**
