### PR TITLE
Added Energy and Heat Summary to Ship Info Panel

### PR DESCRIPTION
**Pull request by Karelzarath**
Added a summation of energy expenditure and heat generation to the ship panel, including battery depletion time and overheating amount. This should help players better understand their chosen loadout and whether they need to adjust their power generation or cooling outfits.

### CODE REVIEW

**Comment by Pointedstick** [comment]
Your text editor appears to have stripped out indented whitespace. Can you revert those changes and turn off that feature for the future?

**Comment by Karelzarath** [comment]
There's some default setting in Code::Blocks that's doing that. Until I can hunt it down, I've manually excluded those changes.

**Comment by Pointedstick** [comment]
Thanks! I still see a few, though.

**Comment by Karelzarath** [comment]
Ha! I found the setting. This is my first time using Code::Blocks as an IDE. I guess I got a little used to how Visual Studio handles things. At least it's fixed now.

**Comment by Pointedstick** [comment]
There ya go!

**Pull request closed without merging**
