### PR TITLE
grammar: any but -> all but

### PR DESCRIPTION
**Pull request by malard**
Just started playing, noticed this odd choice of language

### CODE REVIEW

**Comment by DingusShingleton** [comment]
Well it's not incorrect. Think about it, it can move any ship, except for the largest. Any but the largest. Either works though.

**Comment by jmhorjus** [comment]
"All but" does sound significantly more natural to me.

**Comment by malard** [comment]
any but, is not natural speech, I cannot find via Google anywhere where this is a normal way to describe what is being described here. "all but" or "anything but" are very common

**Comment by endless-sky** [comment]
According to Google Ngrams, "any but" and "all but" were equally common a mere 200 years ago. So 1000 years in the future, it's quite possible that "any but" will be back in vogue.

**Comment by malard** [comment]
quite possible, however as we are creating a neural link to our virtual selves 1000 years into the future, I find it odd that this term is in use.

**Comment by endless-sky** [comment]
Anyway, if something is not grammatically incorrect, and is not *so* archaic that the vast majority of people will fail to understand it, I don't feel like it needs to be changed. (And even then I'd make exceptions for poetic reasons if the archaic turn of phrase sounds better...)

**Pull request closed without merging**
