### PR TITLE
Add new Marauder missions

### PR DESCRIPTION
**Pull request by ZBok**
This PR adds ~30 repeating jobs/spaceport combat focused missions in human space, and more difficult "Marauder Hunted" fleets (invisible mission) that scale as combat rating becomes higher.

These missions primarily utilise existing Marauder/pirate fleets, and two new fleets "Marauder fleet XX" and "Elite Marauders".

This PR is part of a four part plan, where subsequent PR's will, amongst other things, attempt to add further variety to the above mentioned fleets (and therefore the missions that use them) as the player progresses through the game.

edit: For ease of review, here's a brief breakdown of the content:

- Five job board missions which are basically scaled up versions of the "hunt down the <npc>" jobs already in game.
- Six spaceport missions, based on the "Pirate Attack" and "Pirate Occupation" missions. There are four variants of each, North/South/Deep/Core. There are then five low-chance variations of the most difficult of these, differing only in that they have interesting NPC assistance, each of these is only found in one of the aforementioned regions.
- "Marauder Hunted" mission extensions. Adding three new scaled up variations and setting combat rating ranges on each.
- Elite Marauder Hunted mission. As above, but instead of large fleets consisting of many ship sizes (like the "Marauder fleet X" and "Marauder fleet XX") this is a smaller, homogeneous, heavy warship only fleet with expensive custom outfit combinations. This last category is a recent addition and has not gone through as much balancing or testing yet, tho I do think it's super fun and adds nice variety.

### CODE REVIEW

**Comment by ZBok** [comment]
Becca picked up that there are two spaceport missions, both very low chance (<2%) and with CR<11 requirement, where the job dialogue has the character spotting friendly merchant Leviathans or Bactrians taking off to join battle toting "what looks to be alien weaponry" (Hai weapons). Is this bad?

I feel that if a player has reached CR 11 and is unaware of aliens at all, that this would actually be a nice vague nudge to go exploring without giving any detail, but if not I can add FW completion or Hai First Contact requirement to these two.

**Comment by ZBok** [comment]
This PR was intended to be the first in a series of three dependent PR's but I've messed up somewhat in my planning so I'll close for now and come back to it another time.

**Comment by ZBok** [comment]
Reopened.

**Comment by Pointedstick** [comment]
Super cool, I can't wait to review this when I have a few hours to devote to it.

**Comment by ZBok** [comment]
> Super cool, I can't wait to review this when I have a few hours to devote to it.

Enjoy man, I added some notes in the OP for the benefit of review.

**Comment by LocalGod79** [comment]
the marauder fleets count in roman numerals - "Marauder Fleet X" is the 10th difficulty level - had you planned 11-19?

**Comment by Amazinite** [comment]
@ZBok Are you going to be available to make changes, because if not then I'm not even going to review this if the review comments are just going to sit there (as the comments on #4293 weren't addressed).

**Comment by Amazinite** [comment]
If anyone wants to take the content from this PR and reopen it and maintain it on their own then go ahead, but seeing as how @ZBok is seemingly MIA, I'm going to go ahead and close this. If ZBok shows back up and shows interest in this PR still then I can reopen this as well.

Review wise, the one thing that sticks out with this PR is that all choices are for some reason in parentheses and quotation marks. If a choice is something that the player says (dialog choice), then it goes in quotation marks. If a choice is something that the player does (action choice), then it goes in parentheses. You don't do both at once.

Content wise, I'd say cut the larger Marauder hunted missions. These massive Marauder fleets that come after you just for having a high combat rating would essentially force the player into having a big fleet, when it isn't impossible to get the combat rating required for these missions without such a fleet. I personally only ever use a small fleet, which wouldn't be able to combat these bounty hunter fleets. It looks to me as if they're a punishment for the player simply having an older pilot. The existing Marauder hunted mission can be annoying enough as is. For example, 15 fleets of enemies at the high end? Really?

As for the increasingly large normal bounty missions though, that's all fine by me. Give players the option to create massive battles if they want. The important point being that it's optional, whereas the Marauder hunted missions wouldn't be, hence my apprehension to those.

The spaceport missions could be an issue though. Adding so many with no cut-off point for lower difficulty missions means that you're significantly increasing the odds of getting any defense mission on any visit of the spaceport, which could drown out other spaceport missions with actual story to them instead of just being pure combat. Do we really need so many variants of what are basically the same thing over and over again? "Attack" looks to be the source planet, "Blockade" is a distant planet, but then "Blockade Attempt" seems to just be a repeat of "Attack" and "Fleet Clear" is just "Blockade" in multiple systems, then all those have a second, higher difficulty version, with some of those also having nearly identical variants. I imagine that instead of duplicating every mission for a lower and higher difficulty, you could instead use an event that figures out if the player's combat rating has reach a certain point, then use an event to just double the fleet sizes. I imagine the amount of lines needed would be lower. The only issue would be payment, but at the levels seen here, is the player really going to care about 10 mil vs 20 mil coming from a mission when boarding the ships involved will likely be far more rewarding?

That's just my general thoughts from glancing at this without going line by line. Anyone interested in resurrecting this should keep these in mind.

**Comment by ZBok** [comment]
> @ZBok Are you going to be available to make changes, because if not then I'm not even going to review this if the review comments are just going to sit there (as the comments on #4293 weren't addressed).

Sure.

If I make any changes, will they just "sit there" as you put it? Or do you think it might be looked at within 6mths?

**Comment by Zitchas** [comment]
Within six months? Highly likely.

**Comment by ZBok** [comment]
> If anyone wants to take the content from this PR and reopen it and maintain it on their own then go ahead, but seeing as how @ZBok is seemingly MIA, I'm going to go ahead and close this. If ZBok shows back up and shows interest in this PR still then I can reopen this as well.
> 
> Review wise, the one thing that sticks out with this PR is that a lot of choices are for some reason in parentheses and quotation marks. If a choice is something that the player says (dialog choice), then it goes in quotation marks. If a choice is something that the player does (action choice), then it goes in parentheses. You don't do both at once.
> 
> Content wise, I'd say cut the larger Marauder hunted missions. These massive Marauder fleets that come after you just for having a high combat rating would essentially force the player into having a big fleet, when it isn't impossible to get the combat rating required for these missions without such a fleet. I personally only ever use a small fleet, which wouldn't be able to combat these bounty hunter fleets. It looks to me as if they're a punishment for the player simply having an older pilot. For example, 15 fleets of enemies at the high end? Really? The existing Marauder hunted mission can be annoying enough as is.
> 
> As for the increasingly large normal bounty missions though, that's all fine by me. Give players the option to create massive battles if they want. The important point being that it's optional, whereas the Marauder hunted missions wouldn't be, hence my apprehension to those.
> 
> The spaceport missions could be an issue though. Adding so many with no cut-off point for lower difficulty missions means that you're significantly increasing the odds of getting any defense mission on any visit of the spaceport, which could drown out other spaceport missions with actual story to them instead of just being pure combat. Do we really need so many variants of what are basically the same thing over and over again? "Attack" looks to be the source planet, "Blockade" is a distant planet, but then "Blockade Attempt" seems to just be a repeat of "Attack" and "Fleet Clear" is just "Blockade" in multiple systems, then all those have a second, higher difficulty version, with some of those also having nearly identical variants. I imagine that instead of duplicating every mission for a lower and higher difficulty, you could instead use an event that figures out if the player's combat rating has reach a certain point, then use an event to just double the fleet sizes. I imagine the amount of lines needed would be lower. The only issue would be payment, but at the levels seen here, is the player really going to care about 10 mil vs 20 mil coming from a mission when boarding the ships involved will likely be far more rewarding?
> 
> That's just my general thoughts from glancing at this without going line by line. Anyone interested in resurrecting this should keep these in mind.

I agree with the the points on combat spaceport missions potentially swamping any possible storyline missions, the % chance needs to be substantially dropped across the board.

I also agree about the Marauder Hunted missions, I didn't realise players with small fleets could get high combat ratings in a realistic amount of time. Would it be best just to delete these since vanilla ES now has reworked these missions entirely? What does everybody else think?

However the point you make about the player not really caring about the mission payout when boarding/capturing the ships is way more profitable, is correct, but this is how it is with the vanilla missions also. A 500k Marauder mission can easily net the player 10mil via boarding/capturing (20x the payout) as it stands in vanilla, so these missions generally keep that theme, I feel like the payouts are fairly good as is.

**Pull request closed without merging**
