### PR TITLE
Add tiny and small photovoltaic generators

### PR DESCRIPTION
**Pull request by ItsNickBarry**
Ship info panels will now display the "solar collection" attribute.

### CODE REVIEW

**Comment by ItsNickBarry** [comment]
Maybe this isn't appropriate, since it will currently always be 0?

**Comment by endless-sky** [comment]
This would cause the info display for some ships (such as a Carrier) to extend beyond the bottom of the player info panel. So, I'd need to extend the height of that panel to compensate.

If solar collection becomes a widely used feature, that might be worth doing, but a better approach for now might just be to add the solar collection value to the idle energy generation value (that is, have the idle value show how much energy you would be getting at a "typical" distance of 1250 pixels from the sun (Earth orbits at around 1000 pixels, for comparison).

**Comment by ItsNickBarry** [comment]
Solar collection is now included in the energy generation calculation.  I've also added an outfit which makes use of solar collection.  Maybe it looks familiar?  The model comes from interference plating.  If you like the look of it, I will email you the .blend and .xcf files.

Derived from [this image](https://commons.wikimedia.org/wiki/Solar_panel#/media/File:Mafate_Marla_solar_panel_dsc00633.jpg).

**Comment by LocalGod79** [comment]
the photo cell seems like it would be a widely available outfit, since a single shipment could contain literally hundreds of them.

also, it seems more like something the Syndicate would produce...

**Comment by DingusShingleton** [comment]
Honestly, not necessarily. If it's based on really old outdated technology it could be a niche item that you can only find on backwater worlds where people need to use any outfit they can get their hands on. With that in mind you can make it as common or uncommon as you want, really.

**Comment by LocalGod79** [comment]
sorry - the 'changed files' made it seem like it was available only in some southern areas...

it's a basic outfit: comment withdrawn.

**Comment by ItsNickBarry** [comment]
These are meant to be antiques from the early days of human space exploration.  They are ubiquitous throughout space due to their durability and ease of repair, but are no longer in production.  Larger outfitters don't bother with them.

**Comment by ItsNickBarry** [comment]
I had been considering another idea to fill the role of "tiny" size photovoltaic, but that no longer seems to make sense.  This outfit now fills the "tiny" role.

**Comment by endless-sky** [comment]
I'm looking forward to seeing how far I can get in a shuttle with nothing for power but a supercapacitor and a single solar panel...

**Comment by ItsNickBarry** [comment]
Sounds like a Steam achievement.  That'll teach those hardcore-mode completionists.

But really, anything more is just extravagant.

**Pull request merged**
