### PR TITLE
Add a high-tech image for Lagrange

### LINKED ISSUE #3103: New space station image
Don't have time to put together a PR right now, but I came across a CC image that seems like it would be perfect for a space station in Endless Sky: https://en.wikipedia.org/wiki/National_Ignition_Facility#/media/File:Preamplifier_at_the_National_Ignition_Facility.jpg

image

### PR DESCRIPTION
**Pull request by Pointedstick**
screenshot_20180814_091400

Closes #3103

HiDPI assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/52

### CODE REVIEW

**Comment by Amazinite** [comment]
```
planet Lagrange
	attributes tourism
```

"And here on our left you can see our fusion generator!."

**Comment by jafdy** [comment]
It's a quarg space station in the same system as a quarg ring world. Sounds like an interesting place to me.

**Comment by Bladewood** [comment]
I mean, as long as you explicitly tell the local Quarg that you have questions for them, it should work out fine.

**Comment by Amazinite** [comment]
As I pointed out in https://github.com/endless-sky/endless-sky/pull/3906, 30 stations share landscape images between 10 images, so any new station images are great in my eyes, [even if the copyright file does get a little unwieldy](https://github.com/endless-sky/endless-sky/issues/3103#issuecomment-335009486)

**Pull request merged**
