### PR TITLE
Fixing default start edge case

### PR DESCRIPTION
**Pull request by flowers9**
**Bugfix:**

## Bug Details
At the very start, if the player either doesn't buy a ship or immediately sells it, and then repays his loan (either in full or sufficiently that they can't afford a ship anymore), it's game over, as the bank will not offer a loan.  Which is weird, because the bank *did* just offer a loan under the same conditions.

## Fix Details
Added history to the default start such that they can get that 480k bank loan back if they accidentally repay it all the first day (as opposed to having to restart on the first day).  They can still hose themselves by selling the ship and repaying too much on a later day, but they could also have gotten killed by a pirate by that point.  Once you leave the cradle, life is harsh.

The history is crafted such that they can only get a 480k loan on the first day, and that any mortage offerings past that will be the same as if they hadn't messed around with the loan at all.  (But if they partially repay the loan on the first day, loan offerings (if any) will be as if they had not (for the first 100 days), and thus a smidgin larger.)

## Testing Done
Checked effects on history and bank mortage offerings with a new pilot.  It's not quite perfect - if they repay the loan, then take out multiple loans in smaller amounts (e.g., four 100k loans), they can get slightly more than 480k (around 480379).  This appears to be a result of rounding effects from currentPayments being an int64_t rather than a double (expect another PR soon ;).

### CODE REVIEW

**Comment by Hurleveur** [comment]
Maybe another way to address this issue would be to allow the player to take more risk with their loans? ~~let me bankrupt myself~~

Otherwise cant we just make the same thing happen in fewer lines, even if it means you can get the debt back later again?
I dont think its an issue to allow more debt flexibility, especially in the early game.

**Comment by flowers9** [comment]
I tried to find a different approach that used fewer lines, but it's actually kind of tricky, as the Account::Prequalify() code only has access to account information, not the whole player record.  So, you can't find out what the starting conditions are, for example.  I felt this was the least impactful approach, despite the large number of extra lines (which simply add a history to the starting account information).

I didn't want to go with a code approach to generating the history either, as that might not fit properly with non-default starts (although I am relying on the value of Account::HISTORY, which could change).

It would be a significant change to allow the player to take on more debt than usual, allowing them to ramp up their income quite quickly.

I could also reduce the history to two lines, but that would allow the player to get larger loans early in the game (once they start generating income) until the first entry rolls off the history.  On the plus side, it would allow them to recover (to a fair bit) after the first day, if they repaid too much.

**Comment by Hurleveur** [comment]
Getting larger loans sort of is an issue yeah
You are sure this doesnt already allow more loan after you bought your ship?

**Comment by flowers9** [comment]
Yes, because loan offerings are based on net worth - buying something has no effect on net worth.  Well, that and I tried it out. ;)

**Comment by RisingLeaf** [comment]
Instead of having to add this to every start we make, wouldn't a solution in code be preferable?

I think something like this: when you start a new pilot and the history is too short just add these numbers to the history automatically.

**Comment by Hurleveur** [comment]
That code doesnt feel clean either, and now that I think about it this would make all savefiles 100 lines longer like the solution you suggest, so definitely we need to find another way, or just ignore the softlock issue all together.

**Comment by Hurleveur** [comment]
Another maybe more interesting way to go about this is to have a special trigger when this happens, because you could get in this issue at many points in the game.
Maybe a captain offers to sell their own ship, or smth else, I'm not saying it has to be one thing but just giving an idea.

**Comment by RisingLeaf** [comment]
> That code doesnt feel clean either, and now that I think about it this would make all savefiles 100 lines longer like the solution you suggest, so definitely we need to find another way, or just ignore the softlock issue all together.

not really? the maximum size for account history is 100 so it would just make the savefile 100 lines longer in the beginning but 100 transactions are quickly done in the game so I do not think it would really matter.

I do agree though that it would not be the best solution but still better than polluting the game data with a hundred lines per start, especially if we want to add alternate starts

**Comment by flowers9** [comment]
It doesn't noticeably affect savefiles - early game savefiles are short anyway (compared to mid/late game), so this makes early game more like mid game in size (and barely at that, with only 100 lines).  The account history grows at one line per day up to 101 lines in any case.

While this might seem like an ugly fix (and it is, in ways), putting in the default start means that you can have different starts that behave quite differently, like ones that start you with a ship you really can't replace (not available for sale, say), with warnings in the text that selling it would be a really bad idea.  Alternatively, you could make the default start getting the loan text imply that someone was putting pressure on the loan officer, and he won't give you the loan again if you ask for it.  But, without warnings of that sort, it's weird that you can't get the loan back, and this offers the least change I could come up with to the starting game that allows for that.

A change with slightly more loan permissive early game (i.e., first 100 days or so) would be to add only the first two lines of the history.  Same effect on day one, and the total loan amount would slightly dip as your network went negative, but you generally wouldn't run into a softlock unless you really messed up the early start.  But once your networth went positive (in the first 100 days) you could start getting loans past the starting $480k, rather than having to hit ~$250k positive.  I think this makes the loan offerings feel more natural (there isn't that sharp cutoff on day 2), but it's certainly more permissive.

**Comment by Hurleveur** [comment]
I agree not all starts (thinking about plugins especially) should have this, I just dont know if this is the best way even if it is the most flexible for the player
Ig I just like the idea of a "hidden" mission that triggers when you are broke but yeah thats more alongside content and could be done later.

**Comment by Amazinite** [comment]
There's nothing stopping the player from simply starting a new pilot after falling into this situation. And honestly, I find this situation rather hilarious to leave in, as it's something that others have noticed and had a laugh about as well. So I'd rather keep this in, and perhaps make it something of an easter egg by having a message appear if this happens. Perhaps in resolving #2737, we have a normal message that appears when you pay off your loan at a later date, but a special message that appears if you pay off your loan at the very start of the game.

**Pull request closed without merging**
