### PR TITLE
Reorder settings

### PR DESCRIPTION
**Pull request by warp-core**
**Refactor:**

# Details

As more settings have been added, the ordering and grouping of some seems to lack any sort of sense.
Each of hte categories also now has a lot of items, some of which could fit better in a more focused category.

New categories:
"HUD" for items relating to information provided to the player while in flight.
- Overlays (ship, missile, asteroid, planet).
- Mini-map
- Radar
- Alert indicator
- Messages

"Map" for settings relating to the map panel. Moved here from "Other." Located below "Gameplay," in the first column of the second page.

"Always underline shortcuts" has been moved to "Other." It doesn't seem to fit in very well with the zoom, screen mode, and vsync settings, nor any of the other categories.

The "Performance" category has been moved from the second column of the first page to the first column, below what's left in "Display." "HUD" is now in the second column.

Re-ordered some of the items in "Gameplay:"
- Turret tracking immediately below automatic firing; I think this is closely related to the two settings now above it, being about the way your flagship's weapons behave, so it makes far more sense for it to be here than at the bottom of this category.
- Asteroid targeting between turret tracking and boarding target priority, since it is very similar to boarding priority, except for asteroid targeting.
- Extra fleet status messages moved to "HUD."
- Fighter repair moved between escort ammo expenditure and fighter cargo transfer, since these three all relate to the behaviour of non-flagship player ships, and fighter repair is more combat relevant than fighter cargo transfer, so I think it makes sense for it to be closer to escort ammo usage than the other.

# Screenshots:
(Ignore the text colour, that change is not in this PR.)

Note: control ship with mouse is now at the top of its category.

Before | After
-- | --
image | image
image | image

### CODE REVIEW

**Review by quyykk — APPROVED** [review]

**Review by Saugia — COMMENTED** [review]
Pertaining to the Gameplay:

I feel the order of importance is a bit off. Automatic Aiming, Firing, Turret and Asteroid Targeting make sense. 

I feel Escorts expending ammo is more important than boarding because not every player will be boarding-focused, but ammo usage is important all-around.

After that, Rehiring Crew should come right after Boarding as the two are directly tied with one another.

After that, then do the fighter stuff, as the above options are all more important than fighters since not everyone uses them. The order of the two is fine though (first repair, second cargo), since fighters are for fighting more than cargo.

Control ship with mouse is an odd one. It should definitely be either the first or last thing since it's a huge gameplay option, and shouldn't be stuffed between the other things. I lean towards the bottom of the list. Could also be in the Other section maybe (it's not so much gameplay as it is controls), but I'm not big on that.

So, the order would be:

Automatic aiming
Automatic firing
Turret tracking
Target asteroid
Escorts expend ammo
Boarding target priority
Rehire extra crew
Repair fighters
Fighters transfer cargo

Control ship with mouse

The other sections seem fine.

**Comment by warp-core** [comment]
> Pertaining to the Gameplay:
> 
> I feel the order of importance is a bit off. Automatic Aiming, Firing, Turret and Asteroid Targeting make sense.
> 
> I feel Escorts expending ammo is more important than boarding because not every player will be boarding-focused, but ammo usage is important all-around.

Escort ammo usage is not at all important if I either don't have escorts or don't give them weapons affected by this setting.

I've put asteroid target priority and boarding target priority together because they do essentially the same thing, one just related to asteroids and the other to boarding targets. And both relate to the behaviour of your ship, not escorts.

> After that, Rehiring Crew should come right after Boarding as the two are directly tied with one another.

While rehiring extra crew might be related to boarding, it's not really related to boarding target priority: one happens when you land the other relates to something that happens in flight. Indeed, it is the only one of these settings that does not affect in flight behaviour.

> After that, then do the fighter stuff, as the above options are all more important than fighters since not everyone uses them. The order of the two is fine though (first repair, second cargo), since fighters are for fighting more than cargo.
> 
> Control ship with mouse is an odd one. It should definitely be either the first or last thing since it's a huge gameplay option, and shouldn't be stuffed between the other things. I lean towards the bottom of the list. Could also be in the Other section maybe (it's not so much gameplay as it is controls), but I'm not big on that.
> 
> So, the order would be:
> 
> Automatic aiming Automatic firing Turret tracking Target asteroid Escorts expend ammo Boarding target priority Rehire extra crew Repair fighters Fighters transfer cargo
> 
> Control ship with mouse
> 
> The other sections seem fine.

Overall, this isn't about trying to order the different settings by "importance," because different settings carry a different level of importance to different people. For example, you've mentioned placing asteroid targeting priority fourth in the list, while this is where I have it as well, it's not there because of importance, and in terms of my usual gameplay, if I were ordering these by importance, asteroid targeting priority would be near the bottom. The first three items relate to your flagship's behaviour in combat. While neither asteroid nor boarding target priority are related to combat behaviour, they are both related to your flagship's behaviour. Control ship with mouse is there because I didn't think it particularly fit better anywhere else. The next three settings are all about escort behaviour, with the latter two only relating to fighters. Of those two, combat behaviour comes first because the preceding option is also about combat behaviour. Finally, the only option not related to in-flight behaviour.

If I'm moving either of the two target priority options, I'd be inclined to move them to the bottom (or perhaps just above rehire extra crew) since neither really relates to combat.

I will move control ship with mouse to the top, since it affects how you control your flagship, which most closely relates to automatic aiming (it also overrides automatic aiming which we should probably convey in some way at some point.)

**Comment by Saugia** [comment]
>Escort ammo usage is not at all important if I either don't have escorts or don't give them weapons affected by this setting.

Fair enough.

>I've put asteroid target priority and boarding target priority together because they do essentially the same thing, one just related to asteroids and the other to boarding targets. And both relate to the behaviour of your ship, not escorts.

>While rehiring extra crew might be related to boarding, it's not really related to boarding target priority: one happens when you land the other relates to something that happens in flight. Indeed, it is the only one of these settings that does not affect in flight behaviour.

If the purpose of the order for the two is what they do being similar, perhaps the text should be similar - "Asteroid target priority" with Boarding target priority, or vice versa. 

>I will move control ship with mouse to the top, since it affects how you control your flagship, which most closely relates to automatic aiming (it also overrides automatic aiming which we should probably convey in some way at some point.)

Yeah, it's definitely an important setting, so that works.

**Comment by warp-core** [comment]
> If the purpose of the order for the two is what they do being similar, perhaps the text should be similar - "Asteroid target priority" with Boarding target priority, or vice versa.

Yes, but not here.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
