### PR TITLE
Feat(content): Remnant Scanning Adjustments

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
With the recent changes to scanning, the Remnant's fondness (and fearful exuberance) for scanning any and everything in their systems has become more obvious, more annoying, and in some cases, even problematic. This PR generally increases their scanning capabilities such that they complete faster and aren't quite as affected by the range dropoff, and thus will spend less time annoying the player with incessant scanning.

**Methodology: Ships**
I took the weakest ship in terms of scanning potential (the tern), and bumped it up to be equivalent of a standard human outfit scanner and tactical scanner. This equates to +15 outfit scanning, +3 outfit scanning efficiency, and +12 tactical scan.

I picked these as the baseline values because, with the current changes to scanning, a single human scanner of each type is basically the bare minimum to be able to even contemplate scanning something, and typically if one is targeting anything even remotely uncooperative this minimum is quite non-user-friendly. As evidenced by a request to revert it entirely.

Likewise, as far as that goes, many players largely consider human scanners to be more or less useless at the best of times; something to be carried only when forced to by a mission. Given that one of the meta reasond behind having these capabilities in Remnant ships is to give players the option to try using them in a situation where having them isn't optional. It is hoped that if they have them, they'll try using them. This goal is sabotaged by having these built-in capabilities be weaker than the already lackluster outfits they have experienced in human space.

As a general method, I buffed all Remnant ships by this amount. Note that, given how the scanning formula works, this means that the tern got the biggest buff, the rest got comparatively less.

This methodology was not applied consistently. There were a few cases where the original values didn't really fit the relative newness of the ship,  but overall the majority were close to the +15/+3/+12 amounts.

**Methodology: Outfits**
The Research lab had it's asteroid scan buffed as, unlike its  human counterpart, this outfit incurs an ongoing daily cost in the form of +1 required crew. Between the scientific focus of the Remnant, the additional crew, and the additional cost, I felt that this was reasonable.

The Tactical Scanner: As Hector pointed out in the PR on the Value Scanner, the tactical scanner has a higher range-per-space than the salvage scanner. While this metric isn't typically what we use to compare scanner values on the content creation side of things, it is a very significant metric from the player side. At the end of the day, the player doesn't care how much power their scanner has, just how far out it can see and how much space it takes up.

**Lore**
From a lore perspective, the Remnant got their start in terms of scanning capabilities with the specialized research equipment they brought with them. The original Remnant were humanity's best and brightest astrophysists, spacecraft engineers, astronomers, and the independent captains and crews that funded, supported, and took part in their research. So not only did the Remnant *start* with a headstart on humanity, humanity probably also suffered something of a setback in losing those specialists. (Recalling that this was a time of desperation and war where humanity was *losing*. Astronomy and astrophysics was *not* something that was getting much resources, if any). So on-par with humanity makes sense as a baseline from that perspective.

Their new home in the Ember Waste is a realm where the rules of physics (as we and the humans of the 25th century know them) are broken daily. One has to but look around and find examples of what could be considered laws of physics that seem to be ignored. Whether it is energy pouring out of empty space, or planets orbiting in ways that don't match their or their stars physical characteristics, anomalies abound. As such, both incentive to develop better instruments is readily apparent, and the need to do so, since their survival depends on them understanding their environment.

Then there is the alien vaults. Alien technology considerably more advanced than humanity's, still in working condition. With advanced scanning and targeting systems part of the guidance systems of the defense turrets, the Remnant were quick to learn and integrate these systems, and continue to refine them.

Beyond this, their primary use of actively targeted scanning is hostile alien ships, most predominantly the Korath. Given that the Korath have a preponderance for very large ships with long-range and heavy hitting weaponry, close-range slow scanning isn't an option.

**Results:**
While this PR doesn't solve the petrel/tern/smew scanning behavior in and of itself, it does make the situation a lot more tolerable by enabling other Remnant ships in the area a decent shot at engaging in scanning the player and thus resolving the need for currently-present ships to do any more scanning.

It also makes it possible for players to try out and possibly even find uses for scanning in a somewhat more friendly package than what is available elsewhere.

## Save File
This save file can be used to play through the new mission content:
Any pilot that can access Remnant space can see the results of this.

## Artwork Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by Hecter94** [comment]
I don't think we should be buffing scanners to compensate for the recent change to the scanning formula while there are still multiple PRs open that seek to further adjust the scanning formula and scanning in general, which would presumably require even further tweaking once they have been merged.

I think any tweaks to scanner stats should wait until the scanning formula is no longer in flux, and if further tweaks are needed at that time, they should be applied globally to all scanners so we can ensure they're applied consistently, rather than piecemeal faction by faction. 

At the moment, scanners are all in-line with each other in terms of their data values, adjusting those values in the interim is just going to make it more difficult to actually build a good scanning formula for all of them to use.

**Comment by Zitchas** [comment]
> Also, given that the changes to outfit/cargo scan don't affect tactical scan, why are Remnant tactical scan values being buffed?

Because this is an overall adjustment to scanning in the Ember Waste environment. While this is precipitated by the changes to scanning, it is not solely because of it. 

> To keep them balanced against each other, they should be rebalanced together, preferably after we're done tweaking the scanning formula

This is actually done in complete cognizance of the other scanners in the game, and I consider it to be rectifying the existing imbalances create with the last scanner that was added to the game. Any "game wide" adjustments done after scanners have settled down should take place after this has been implemented.

Most importantly, though, scanners must fit within their environment. Remnant scanners aren't being used to scan arrows or star queens for business secrets, they're scanning Palavrets and Rano'erek *in combat*. The only way that we'd be getting anywhere close to an "apples to apples" comparisons for scanner power between these in their respective use cases is if the scanner "floor" for the Remnant scanner is bumped up from the current 200 mass to something closer to 1500 mass. If we could set the floor in the outfit statistics, that'd work just as well. And then equip all those VIP transports with korath grade weaponry and make them automatically hostile to the player from the start of the mission. 

----

At the root of it, I'd just like to re-emphasize that the bulk of these changes is bringing Remnant ships up to par with what is generally consider one of the most worthless outfits in human space. They have reduced outfit space because they have this scanning, and they have better scanning tech than humanity, so this should be reflected in their statistics. Given that the space lost has been more than 1 space (quite a bit more for the larger ships), the amount of scanning they have should be likewise be more.

Likewise, I'll just re-iterate that scanners are a *non-combat* outfit, one that is generally viewed as being utterly worthless for any combat ship to have, and they are also the only way a player can gain information about another ship. Even knowing exactly what they have is of dubious value given our lack of in-flight options for changing our ship, but it is made considerably worse by the fact that at most of these values, scanning can only take place inside the effective range of most ships in the game, and especially Korath weaponry. That means that, using vanilla values, the only way for player to gain even this marginal and unlikely to have any impact on combat information is to relegate their combat activities to second place while focusing on completing a scan, during which they will almost certainly take far more damage than they could hope to compensate for via any information gained. 

-----

This isn't changing anything in any other area of the game, this is purely trying to make information gathering a regular part of gameplay within the Ember Waste environment. If people want to maintain human space as an information-lite area, that's the choice of those who are focusing on the human area, such as Amazinite. I've pretty much given up on trying to get more information into the hands of players in that domain. The Remnant, however, are an information-centric society and storyline, and I would prefer to enable the player to get some of said info themselves instead of being restricted to what is fed to them. And doing that requires that they have means to reliably get information without compromising combat capabilities. The Korath are tough, and they recently got tougher. It's hard enough to 1v1 Korath ships in a purely Remnant ship as it is, without sacrificing a whole ton of space for stacking outfits. Stacking, which I point out, is intentionally build to be discouraged and result in ever smaller gains.

**Comment by Hecter94** [comment]
> This is actually done in complete cognizance of the other scanners in the game, and I consider it to be rectifying the existing imbalances create with the last scanner that was added to the game. 

If the last scanner added created imbalances, we should look at and adjust that outfit as needed, not adjust existing outfits to compensate.

> Most importantly, though, scanners must fit within their environment. Remnant scanners aren't being used to scan arrows or star queens for business secrets, they're scanning Palavrets and Rano'erek _in combat_. 

> Likewise, I'll just re-iterate that scanners are a _non-combat_ outfit, one that is generally viewed as being utterly worthless for any combat ship to have

If scanners are a non-combat outfit which are utterly worthless for combat ships to have, why are they scanning Palvrets and Rano'ereks in combat?
Should they even have scanners at all if they're worthless for combat ships to have?

> At the root of it, I'd just like to re-emphasize that the bulk of these changes is bringing Remnant ships up to par with what is generally consider one of the most worthless outfits in human space.

Remnant ships are already sufficiently better than humanity's ships, the additional built-in scanning is a bonus on top of that.

> This isn't changing anything in any other area of the game, this is purely trying to make information gathering a regular part of gameplay within the Ember Waste environment. 

The Ember Waste environment is still contained within the Endless Sky environment and should maintain consistency with other environments within that environment. Changes to anything within the Ember Waste is always going to change other areas of the game by proxy. 

Regardless, the last I have to say on this matter is, we should not be making any big changes to scanner values until after the scan formula is finalized.

**Comment by Zitchas** [comment]
> If scanners are a non-combat outfit which are utterly worthless for combat ships to have, why are they scanning Palvrets and Rano'ereks in combat?
Should they even have scanners at all if they're worthless for combat ships to have?

Because, as I mentioned, I'm actually trying to make them relevant to and a useful part of the decision making process for players while in combat. I'm trying to expand scanners to something other than just an inconvenient outfit-space-tax imposed by the occasional mission into something that is actually tactically useful to at least some players. The Remnant already do this, it's just a matter of adjusting capabilities so that the player can achieve the same thing that the NPCs do in lore.

**Comment by UnorderedSigh** [comment]
I suggest you test this against the revised scanning formulae in #8288. Scanners are still completely broken. (Try the Free Worlds scanning missions with just one outfit scanner.) Certainly, bumping up both the scanners' stats and the formulae will have a compound effect, and it may not achieve the result you want.

Plus, it would be great to get another datapoint in #8288, testing with more than just Hai and Navy ships.

**Comment by Zitchas** [comment]
Sure, I'll test that. 

I'll also note that in https://github.com/endless-sky/endless-sky/pull/7876 FerociousFiend stated:
> If @Zitchas intends to tune up the Remnant built-in scanning values, that'd be awesome, because there are a lot of them, and I think I did a poor job because I didn't properly consider what the values meant. As I said, a single outfit scanner is 2 tons and that's not enough (in my opinion) to get an OK scanning time. So, when I transcribed the remnant stuffs, I don't think I've sufficiently increased the scanning efficiency for these ships to be OK standalone scanners.

And I agreed there (and approved that PR) on the basis that I would be doing this PR to finish adjusting the scanner values to properly update the values.

**Review by warp-core — COMMENTED** [review]
> With the recent changes to scanning, the Remnant's fondness (and fearful exuberance) for scanning any and everything in their systems has become more obvious, more annoying, and in some cases, even problematic. This PR generally increases their scanning capabilities such that they complete faster and aren't quite as affected by the range dropoff, and thus will spend less time annoying the player with incessant scanning.

Note that the truly problematic part (some ships being entirely unable to complete scans at all, regardless of time or proximity) is not as a result of Fero's recent changes. You can see in #7229 that that issue has been present much longer, before 0.9.15 was released, even.

Additionally, the changes to scanning only affect outfit and cargo scan, not tactical or asteroid scan. Any changes to values relating to the latter two are going to need to be explained separately, since seem to be yet another straight buff.

> I took the weakest ship in terms of scanning potential (the tern), and bumped it up to be equivalent of a standard human outfit scanner and tactical scanner. This equates to +15 outfit scanning, +3 outfit scanning efficiency, and +12 tactical scan.
> 
> I picked these as the baseline values because, with the current changes to scanning, a single human scanner of each type is basically the bare minimum to be able to even contemplate scanning something, and typically if one is targeting anything even remotely uncooperative this minimum is quite non-user-friendly. As evidenced by a request to revert it entirely.

This has no bearing on tactical scan.

As for outfit scan, if the current values of the Outfit Scanner are now considered the "bare minimum to be able to even contemplate scanning something," and you feel the Tern should be at the "bare minimum," then this also calls for the Outfit Scanner to be buffed in order to mmaintain the relative performance, since it was clearly not prviously the "bare minimum," since the Tern had only ~63% the range.

> Likewise, as far as that goes, many players largely consider human scanners to be more or less useless at the best of times; something to be carried only when forced to by a mission. Given that one of the meta reasond behind having these capabilities in Remnant ships is to give players the option to try using them in a situation where having them isn't optional. It is hoped that if they have them, they'll try using them. This goal is sabotaged by having these built-in capabilities be weaker than the already lackluster outfits they have experienced in human space.

Is this supposed to apply to the Tern or...?

> As a general method, I buffed all Remnant ships by this amount. Note that, given how the scanning formula works, this means that the tern got the biggest buff, the rest got comparatively less.

> This methodology was not applied consistently. There were a few cases where the original values didn't really fit the relative newness of the ship, but overall the majority were close to the +15/+3/+12 amounts.

Can you give a breakdown of what parts of each buff are to make up for existing inconsistencies and what are in response to recent scan changes? It looks like you've mostly doubled outfit scan power, the Petrel, Starling, and Tern are the only places where you add 15 power, so that doesn't appear to have been the "general" approach.

> The Research lab had it's asteroid scan buffed as, unlike its human counterpart, this outfit incurs an ongoing daily cost in the form of +1 required crew. Between the scientific focus of the Remnant, the additional crew, and the additional cost, I felt that this was reasonable.

It costs more to have the Research Laboratory than the Asteroid Scanner, so the Research Laboratory should be better? Did you know that it is already better? Able to highlight minable asteroids in an area around the ship over twice as large as the Asteroid Scanner, and it has significant cargo scanning capabilities built in to boot.

> The Tactical Scanner: As Hector pointed out in the PR on the Value Scanner, the tactical scanner has a higher range-per-space than the salvage scanner. While this metric isn't typically what we use to compare scanner values on the content creation side of things, it is a very significant metric from the player side. At the end of the day, the player doesn't care how much power their scanner has, just how far out it can see and how much space it takes up.

I'd like to refer you to this series of comments: https://github.com/endless-sky/endless-sky/pull/4211#discussion_r262132490.



> From a lore perspective, the Remnant got their start in terms of scanning capabilities with the specialized research equipment they brought with them. The original Remnant were humanity's best and brightest astrophysists, spacecraft engineers, astronomers, and the independent captains and crews that funded, supported, and took part in their research. So not only did the Remnant start with a headstart on humanity, humanity probably also suffered something of a setback in losing those specialists. (Recalling that this was a time of desperation and war where humanity was losing. Astronomy and astrophysics was not something that was getting much resources, if any). So on-par with humanity makes sense as a baseline from that perspective.

So, your argument for why they should have better tech than the rest of humanity at this time is that *you decided* that not only was it particularly smart people that formed the original Remnant, but it was *most or all* of the particularly smart people?

> Their new home in the Ember Waste is a realm where the rules of physics (as we and the humans of the 25th century know them) are broken daily. One has to but look around and find examples of what could be considered laws of physics that seem to be ignored. Whether it is energy pouring out of empty space, or planets orbiting in ways that don't match their or their stars physical characteristics, anomalies abound. As such, both incentive to develop better instruments is readily apparent, and the need to do so, since their survival depends on them understanding their environment.

This reasoning would perhaps be more readily acceptable if it came with some reduction in other capabilities, but the only obvious place where Remnant technology is inferior to the rest of humanity's (who, it should be noted, have far more resources and people, and have not needed to do things like colonise the only worlds they have, certainly humanity has colonised new worlds since the Alpha Wars, but they already had worlds, many of the currently inhabited human worlds have rather low populations, suggesting that much of the colonisation humanity has done has been an excess, not a necessity) is energy generation, and that is because the Remnant have pursued radiothermal energy generation instead of nuclear fusion or fission, and even then, their radiothermals are superior to those which humanity has developed, and when affected by significant ionisation, they are far superior to all human reactors

It should also be noted that the scanning capabilities of Remnant ships are already far superior to humanity's: no human ship gets any amount of scanning *for free*.

> Then there is the alien vaults. Alien technology considerably more advanced than humanity's, still in working condition. With advanced scanning and targeting systems part of the guidance systems of the defense turrets, the Remnant were quick to learn and integrate these systems, and continue to refine them.

Certainly, that's what the Point Defense Turrets are derived from, but what's the source for those turrets having advanced scanning systems? Why would such systems even be applicable to starships given that those vaults were deep underground? Maybe if you wanted to talk about conducting geological surveys or something.
But, it seems to me like the thought process has been: "I want to buff Remnant scanners. How to justify it? Well, there's those alien vaults, they probably had very advanced scanners."
It's even said that the point defense systems are considered to be much more useful than anything else that the Remnant found there; if such advanced scanners were present, surely that would at least be of comparative usefulness?

> Beyond this, their primary use of actively targeted scanning is hostile alien ships, most predominantly the Korath. Given that the Korath have a preponderance for very large ships with long-range and heavy hitting weaponry, close-range slow scanning isn't an option.

I'm not necessarily saying that they shouldn't have high performance scanning, but it should perhaps come at a greater cost. Just because they face these enemies doesn't mean they should be able to overcome the difficulties for free. There's that one Archon that has previously attacked them and disrupted their Void Sprite harvesting or whatever they were doing, but using this as an argument to justify some enormous buff to their capabilities to allow them to defeat the Archon would be ridiculous.



> They have reduced outfit space because they have this scanning

Are you sure?
It seems to me that the reduced outfit space compared to otherwise similar vessels (the Shield Beetle and Korath raider for the Albatross, for example) is because of the large amounts of health regeneration they have, health regeneration that is highly energy and heat efficient.
Note, however, this is not the only reason. The Albatross also has less mass than those ships and more health (these factors also contribute to the reduced weapon capacity while still being considered comparable).

> This isn't changing anything in any other area of the game, this is purely trying to make information gathering a regular part of gameplay within the Ember Waste environment.

Unless I'm mistaken, the Ember Waste is still a part of this game, not a separate game or a plugin, so I don't see why this would justify your changes.

> > If @Zitchas intends to tune up the Remnant built-in scanning values, that'd be awesome, because there are a lot of them, and I think I did a poor job because I didn't properly consider what the values meant. As I said, a single outfit scanner is 2 tons and that's not enough (in my opinion) to get an OK scanning time. So, when I transcribed the remnant stuffs, I don't think I've sufficiently increased the scanning efficiency for these ships to be OK standalone scanners.
> 
> And I agreed there (and approved that PR) on the basis that I would be doing this PR to finish adjusting the scanner values to properly update the values. As such, I'd consider this PR to be part of that one, not a stand alone thing.

You can consider x to be y but it doesn't make it true.
The tactical and asteroid scan changes have *nothing* to do with that PR and I believe the outfit scan changes have gone beyond what was merited by that PR alone, at least, Remnant outfit scan capabilities have been adjusted by a greater amount than others' were. The increases to outfit scan power allone do this.

**Comment by Zitchas** [comment]
Relevant opinion post from a player: https://github.com/endless-sky/endless-sky/discussions/8493 copied here for ease of consideration:

> Outfit scanning was recently overhauled apparently, and with it scanning is overall much slower. There are a couple missions that make you scan hostile ships, and I'm concerned that they might need to be rebalanced.
> 
> There's a Remnant mission to scan a Tubfalet in Kor Zena'i. Since the outfit scan change, this mission seems a lot harder to actually complete. Scanning it takes far too long considering both its firepower and the fact that it is equipped with two banisher turrets. Disabling it is also very difficult, since it's in hostile Korath space and you're likely to be swarmed if you stay long enough to disable and then scan a large warship. I eventually scanned it by taking a single Dreadnought equipped with twenty-three outfit scanners.
> 
> There's also (if I remember correctly) a Free Worlds mission to scan a Republic gunboat equipped with electron beams, and that one is probably also problematic for similar reasons.

Needing 23 outfit scanners for a random player seems just a tad excessive....

**Comment by Zitchas** [comment]
Someone needed to get their scanners up to a scan power of 575 in order to complete a Remnant scanning mission. You're making a fuss about (taking the most extreme purchaseable ship case) of a ship being bumped up to scan power 36, and the Remnant outfit scanning outfit being bumped up to 25.

Presumably that's at least in part because they needed the range to be able to scan the target without *dying*.

The Ember Wastes and Korath Exile territory aren't human space. Unless we're planning on nerfing all Korath ships and outfits down to being equivalent of regular human civilian ships & equipment, then the player needs to be able to be able to get scanning that is *better* than regular human stuff, because expecting regular players to just stuff this many outfit scanners on a ship is ridiculous. 

We can't balance the Remnant scanning equipment on the basis of what is suitable for scanning non-hostile and vastly smaller ships in human space. It's not the same mini-game, not the same challenge, not even the same environment. Not only is the target hostile, they're generally in systems with no possibility of a friendly planet and usually significant hostile spawns.

**Comment by warp-core** [comment]
> Someone needed to get their scanners up to a scan power of 575 in order to complete a Remnant scanning mission. You're making a fuss about (taking the most extreme purchaseable ship case) of a ship being bumped up to scan power 36, and the Remnant outfit scanning outfit being bumped up to 25.
> 
> Presumably that's at least in part because they needed the range to be able to scan the target without _dying_.
> 
> The Ember Wastes and Korath Exile territory aren't human space. Unless we're planning on nerfing all Korath ships and outfits down to being equivalent of regular human civilian ships & equipment, then the player needs to be able to be able to get scanning that is _better_ than regular human stuff, because expecting regular players to just stuff this many outfit scanners on a ship is ridiculous.
> 
> We can't balance the Remnant scanning equipment on the basis of what is suitable for scanning non-hostile and vastly smaller ships in human space. It's not the same mini-game, not the same challenge, not even the same environment. Not only is the target hostile, they're generally in systems with no possibility of a friendly planet and usually significant hostile spawns.

Because no one in human space might want to scan a hostile ship?

Are you proposing that the equivalent of 23 outfit scanners should be a reasonable amount to have built into Remnant ships?
I think such a disparity would be so great as to have no place in the same game, even if it is a different part of it.

Also, of note is that 23 outfit scanners is actually only 46 tonnes of outfit space. While significant, this doesn't actually seem like an unreasonable amount of space to devout to scanners to conduct a mission into enemy territory to scan a new ship.

And, was the goal of the scanning changes not to make scanning ships less trivial?

**Review by UnorderedSigh — APPROVED** [review]
For the Remnant, salvaging is a core tenant of their civilization. It makes sense that they'd have scanners that are superior to most, if not all, races whose outfits Captain Last can obtain.

Even if the scanner formulae were adjusted to de-nerf scanners, these outfit stat changes still seem appropriate to me.

**Comment by UnorderedSigh** [comment]
@Zitchas - since the Remnant scanners are important to the scanning missions, I suggest you let their cheaper scanner be available earlier. I see these approaches:

1. Don't require a license for the Salvage Scanner
2. Have a special "scanning license"
3. Gift the player a few Salvage Scanners just before the void sprite scanning mission. They're already getting an entire ship and 6 million credits. A few scanners is small in comparison.

**Comment by Zitchas** [comment]
> Because no one in human space might want to scan a hostile ship?
> 
> Are you proposing that the equivalent of 23 outfit scanners should be a reasonable amount to have built into Remnant ships?
> I think such a disparity would be so great as to have no place in the same game, even if it is a different part of it.
> 
> Also, of note is that 23 outfit scanners is actually only 46 tonnes of outfit space. While significant, this doesn't actually seem like an unreasonable amount of space to devout to scanners to conduct a mission into enemy territory to scan a new ship.
> 
> And, was the goal of the scanning changes not to make scanning ships less trivial?

a) We currently have no missions requiring it in human space.

b) No, I'm not and you can read the stats to see that. I'm basically proposing that the Remnant's built-in scanners range from equal-to the outfit scanner, up to at the top end, 144%. The original idea was that they were highly effective but short range, but the recent change has made *everything* feel even shorter range than before. Either the range needs to be brought up, or they need sufficient increase in efficiency that doing drive-by scans on Palavrets is actually feasible. I can swap to that if you'd like. Might be more interesting, even. 

c) Agreed, somewhat. I don't think 46 is reasonable for Remnant ships, although 20-30 definitely would be.

d) Yes, the goal was to make it more challenging. I believe the thought was that a single scanner should be doable but either difficult or painful, whereas something around 6 would be enough to accomplish anything quite well, and a "scanning optimized" ship would probably have maybe 10ish? That was the sort of ranges I had the impression of, anyway.

Again, you will note that nowhere am I saying that Remnant scanner outfit scanners should be made orders of magnitude more powerful, just up to or slightly passed parity in terms of range. The Salvage Scanner, for instance, is made to be the exact same range (just a bit more efficiency) than the human scanner. At triple the size, it's still going to be a poor choice for getting range, but at least on a 1 to 1 comparison it's not going to be inferior range.

**Comment by warp-core** [comment]
> a) We currently have no missions requiring it in human space.

That doesn't mean no one would want to do it.

> b) No, I'm not and you can read the stats to see that. I'm basically proposing that the Remnant's built-in scanners range from equal-to the outfit scanner, up to at the top end, 144%. The original idea was that they were highly effective but short range, but the recent change has made everything feel even shorter range than before. Either the range needs to be brought up, or they need sufficient increase in efficiency that doing drive-by scans on Palavrets is actually feasible. I can swap to that if you'd like. Might be more interesting, even.

I actually said a number of things about the changes in this PR in a previous comment that has not received any replies yet.
And, those changes do not really specialise these scanners into high speed at low range. I don't think you've mentioned that this is what you are trying to achieve until this comment. They increase the range and also increase the speed. It is still possible to achieve high speed at low range for the purpose of "drive-by" scanning in the same way it was before, low power, high speed (just "efficiency" instead of "speed" now).

> c) Agreed, somewhat. I don't think 46 is reasonable for Remnant ships, although 20-30 definitely would be.

As was discussed in the comments I linked to in my previous comment, the Salvage Scanner seems to have been created as a more general scanner, granting a user better scanning capabilities from the used space in multiple areas than multiple of the discrete human outfits would. You haven't conveyed very well that you would like instead for the Remnant to offer superior outfit scanning density, and I don't think the Salvage Scanner should be hijacked for this goal. Perhaps instead the Remnant should have a larger device that is primarily an outfit scanner that can offer the greater density, while requiring a larger investment.

> d) Yes, the goal was to make it more challenging. I believe the thought was that a single scanner should be doable but either difficult or painful, whereas something around 6 would be enough to accomplish anything quite well, and a "scanning optimized" ship would probably have maybe 10ish? That was the sort of ranges I had the impression of, anyway.

This would seem to be a general issue, not specific to the Remnant, and perhaps something that should be solved by adjusting hte scanning mechanics themselves rather than the outfits.

**Comment by UnorderedSigh** [comment]
> Yes, the goal was to make it more challenging. I believe the thought was that a single scanner should be doable but either difficult or painful, whereas something around 6 would be enough to accomplish anything quite well, and a "scanning optimized" ship would probably have maybe 10ish? That was the sort of ranges I had the impression of, anyway.

We'll have to update the dialog in a lot of places where it says "install an outfit scanner," as if that makes the mission doable. It'll have to say, "Install between five and twenty outfit scanners, depending on the speed of your ship. If you can't fit them, go in unarmed and hope you don't have to fight, or get a better ship."

**Comment by Zitchas** [comment]
> That doesn't mean no one would want to do it.

True, but no mission requires it, whereas here one *does*.

> I actually said a number of things about the changes in this PR in a previous comment that has not received any replies yet.
And, those changes do not really specialise these scanners into high speed at low range. I don't think you've mentioned that this is what you are trying to achieve until this comment. They increase the range and also increase the speed. It is still possible to achieve high speed at low range for the purpose of "drive-by" scanning in the same way it was before, low power, high speed (just "efficiency" instead of "speed" now).

Ironically, it *wasn't* what I've been trying to do, I just note that in the previous PR you linked to, one of my comments was specifically to that regard. I'd forgotten that too, actually. This comment was more offering that if it'd be acceptable to you, I'd be OK with reverting the changes to outfit scanner power here and significantly boosting the speed. I don't know by how much, I'd have to go do some testing. But I suspect it would be fairly significant.

> As was discussed in the comments I linked to in my previous comment, the Salvage Scanner seems to have been created as a more general scanner, granting a user better scanning capabilities from the used space in multiple areas than multiple of the discrete human outfits would. You haven't conveyed very well that you would like instead for the Remnant to offer superior outfit scanning density, and I don't think the Salvage Scanner should be hijacked for this goal. Perhaps instead the Remnant should have a larger device that is primarily an outfit scanner that can offer the greater density, while requiring a larger investment.

I'm actually not really happy with how the purpose of the Salvage Scanner and Research Laboratory match their statistics. Tactical scan doesn't really fit the Salvage Scanner, and Cargo scan doesn't fit the Research Laboratory. 

That aside, I'll point out that boosting it up to scan power 25 still leaves it significantly inferior to the outfit scanner in terms of outfit scanning density. Even with this boost, one could fit 3 outfit scanners (and get outfit power 75) in the space of a single Salvage Scanner (which would only give outfit scan 25). Nowhere am I suggesting that the outfit scan should be boosted here to a higher density than the regular human outfit scanner. Just enough so that on a 1 outfit to 1 outfit comparison, they have the same range.

> This would seem to be a general issue, not specific to the Remnant, and perhaps something that should be solved by adjusting hte scanning mechanics themselves rather than the outfits.

To be honest, I'm reasonably happy with how scanning works in human space. The gausian drop-off that UnorderedSigh has proposed or doing something to prevent losing scan outside of range would be more than enough to solve the remaining problems. Perhaps other small tweaks. The point that I'm making is that from my perspective these two areas are actually different mini-games. Kind of like, say, comparing a FW vs Navy battle is a different sort of challenge than the first invasion of Pug space. The former you can bring extra ships if you want, or just hang out long enough and the FW will eventually win just by attrition of random spawns. But the pug battle... bringing extra ships is quite hard, and there's *never* any additional supportive spawns that will help you win if you can't manage it. On the surface they look like the same sort of game, but in practice they're quite different.

---

Anyway, thank you for being persistent. I feel like we're making progress here.

**Comment by ziproot** [comment]
The person you linked to had an issue with outfit scanners, not Remnant scanners. I don't see how this PR would fix that, and I also don't see how UnorderedSigh's PR **won't** fix that. You said yourself that outfit scanners are fine in that PR.

**Comment by Zitchas** [comment]
The person you linked to had an issue with outfit scanners, not Remnant scanners. I don't see how this PR would fix that, and I also don't see how UnorderedSigh's PR won't fix that. You said yourself that outfit scanners are fine in that PR.

The Remnant missions are intended to be completed solely using locally available outfits. If they need 23 outfit scanners (which are temporarily available on Remnant worlds because there wasn't an alternative, but aren't intended to be there), then it certainly won't be possible using Remnant outfits that have a shorter range.

**Comment by UnorderedSigh** [comment]
> The person you linked to had an issue with outfit scanners, not Remnant scanners. I don't see how this PR would fix that, and I also don't see how UnorderedSigh's PR **won't** fix that. You said yourself that outfit scanners are fine in that PR.

Repeating what I said before: For the Remnant, salvaging is a core tenant of their civilization. It makes sense that they'd have scanners that are superior to most, if not all, races whose outfits Captain Last can obtain.

... So, boosting their scanner capabilities makes sense anyway.

**Comment by ziproot** [comment]
I kind of get what you mean now. You are saying that if outfit scanners, which are better, are an issue, than Remnant scanners are also an issue which should be fixed. In that case, we should wait until the other PR is merged, then see if this is still an issue at which point this PR can continue.

**Comment by Zitchas** [comment]
The problem with that is that there's no indication that it'll be accepted; and a variety of people expressing opinions outside of discord that it shouldn't be. So right now it looks like what we've got, is what we have to work with.

**Comment by UnorderedSigh** [comment]
> The problem with that is that there's no indication that it'll be accepted; and a variety of people expressing opinions outside of discord that it shouldn't be. So right now it looks like what we've got, is what we have to work with.

I fear that PR may be rejected due to the word "gaussian" in the name, instead of letting me strip out the unwanted parts. We're choosing between taking all of the features I've implemented... or the broken situation we have now.

**Comment by ziproot** [comment]
I saw no indication of that. Where are those opinions saying the PR shouldn't be accepted?

**Comment by quyykk** [comment]
> I fear that PR may be rejected due to the word "gaussian" in the name

You're too cynical. Anyways, now that the #8288 has been merged this PR probably needs to be updated?

**Comment by Amazinite** [comment]
Closing because the state of the scanning mechanic itself is still up in the air (#9201), so it doesn't make much sense to leave PRs sit that mess with scanner stats or loadouts.

**Pull request closed without merging**
