### PR TITLE
Code(feat): Providing Players the option to get live numerical data on their flagship

### PR DESCRIPTION
**Pull request by Zitchas**
**Feature:**

## Feature Details
This adds five HUD elements that inform the player about their current speed, their potential max acceleration, potential max turning, current ramscoop, and current solar gain. It also adds a second ghost ship outline that indicates the ship's actual direction of travel. if the player has the rotating flagship turned off, this feature will be hidden.

This gives players an opportunity to actually learn from experience how proximity to a star affects their fuel and energy production, as well as helping them to identify which stars might provide better results. Importantly, it allows them to do so without spending time just hanging out staring at their fuel gauge trying to decide if fuel is going up faster or slower here than in the last system.

This also adds a preference to hide or reveal them.

Notes
- The current ramscoop and current solar gain will only display if the player has a ramscoop or solar panels respectively. If they do not have the capability to ramscoop, the ramscoop value won't show up. If they don't have any solar panels, they won't see a solar number either.
- The acceleration and turning values take slowing into account. So while they will be static most of the time, they will decrease appropriately when the player is hit by slowing effects.

All the icons and values are positioned individually using interfaces.txt, and thus can be moved by the player if they so desire.

Please note that this PR utilizes artwork and code established in #8172 , and thus it is built upon it.

## UI Screenshots

A shuttle idling near a sun with a single solar panel:
work in progress (showing ramscoop missing)

Here's a shuttle in flight with both a ramscoop and solar panels:
Shuttle with both solar and ramscoop

Here is a shuttle in flight with both ramscoop and solar panels, and both ghost & and arrow velocity indicators selected. There is a preference that allows the player to choose off, ghost, arrow, or both.

Shuttle with both solar and ramscoop and both velocity indicators

# Usage Examples
N/A

## Testing Done
Played the game, and a variety of ships. Tried approaching various stars, and noted how different stars gave different amounts of ramscoop and solar.

### Automated Tests Added
N/A

## Performance Impact
none-anticipated.

### CODE REVIEW

**Comment by Koranir** [comment]
I'd rather have the direction indicator be just a pointer (the triangle-looking thing) instead of a ghost ship.
this
(but the pointer being behind the rings)

**Comment by mOctave** [comment]
> I'd rather have the direction indicator be just a pointer (the triangle-looking thing) instead of a ghost ship.

I was going to say just that. Maybe a pointer on the outside ring? It would sort of make sense what with the compass points, and be a _lot_ less confusing than the ghost ship.

**Comment by Zitchas** [comment]
I personally rather like the ghost ship, but having an arrow is a popular request, so I'll see what I can do to accommodate that. I appreciate the feedback. :)

**Comment by 1010todd** [comment]
Yeah a ghost ship would be a little confusing. I prefer the pointer. 

Overall I do like the concept of this one especially the ramscoop and solar energy, this will make those values more tangible and could encourage more player to experiment with it now that they have a concrete number to look at instead of playing guess with how fast the bar raises or going full spreadsheet on the non-linear math behind it.

Personally I'm not sure what I'd use the potential max turning for but for completeness it could stay there I guess. 

As for the icons, I think it could be better. The max turn icon could be just a single arrow instead of 4 to be clearer, not sure what would be good for ramscoop but maybe just an outline of the ramscoop sprite might work? Same for the solar, maybe just the outline of solar panel outfit itself as icon with some beam of light coming from some angle. For speed maybe there could be more connection between the two and the max speed is just the speed icon with vertical line at the pointy end. Also lines in general probably should be thicker.

(I noticed you mention that the artwork is from another PR but I didn't see the preview of it in the summary over there and Github preview doesn't quite work in this case.)

**Comment by Zitchas** [comment]
Thanks.

There are two main points to having the turning and acceleration data points:
1) To be able to see what those numbers are when using them. This enables a bit more direct connection rather than having to swap out to a different window. It's also fairly typical that people don't remember what their speed is, and especially in conjunction with the Strategic scan PR, I hope players will be able to see the performance numbers of their target and compare that to their own, which makes them more concrete and "real".
2) To be able to see what effect slowing is actually having on one's ship. Right now, slowing is just this nebulous frustrating thing that shows up sometimes and makes your ship more sluggish. It's not clear how much of an effect it is having, or how long it lasts, or how it is changing. These indicators take any slowing present into account, and thus let the player learn about it, experiment with it, and try out ways of using it.

Overall, adding in these sources of information is intended to open up more styles of gameplay. Right now, things are very much a casual Serenity-esque flying experience. I can just imagine going "Pilot! how fast are we going?" and getting a casual "We're going fairly fast, captain!" back. This is great for the casual arcade feel style gameplay. Some people, however, prefer a more technical feel to it. Something like one might experience on Star Trek or The Expanse, where when one asks "How fast can we accelerate?" We expect to get a response that's more along the lines of "We can change velocity at a rate of 225, Captain!"

I appreciate the feedback on the icons. The reason I didn't go with an outline of one of the outfits was because there's a variety of different outfits of different shapes, and I didn't feel that a general outline was sufficiently detailed or unique to be recognizable. 

Tactical Augmentations_v2

I updated the "all info" screenshot in the other PR, but have attached it here too for your convenience. The artwork from that PR that is used here is the current speed, acceleration, and turning speed.

**Comment by Zitchas** [comment]
I got the preference working, so now one can choose whether to have the ghost, arrow, both, or nothing.

**Comment by Zitchas** [comment]
Closed and replaced by #8636 due to contamination from other code.

**Pull request closed without merging**
