### PR TITLE
Fix #2482: Ships with only Jump Drives performing Hyperdrive actions

### LINKED ISSUE #2482: Jumps along hyperspace links trigger hyperdrive accelerations
If systems are connected directly by links, and your jump-drive-only fleet is traveling along said link, your ships will use the hyperdrive animations (with jump drive alignments).
In other words, your ships accelerate in any number of directions and arrive in the next system with significant velocity.
Expected jump behavior occurs when not following a hyperspace link.

### PR DESCRIPTION
**Pull request by tehhowch**
Closes #2482 .

(PS I really wanted to trim the trailing whitespace)

### CODE REVIEW

**Comment by Elyssaen** [comment]
Tested it myself to be thorough, and worked appropriately for the Jump Drive, Hyperdrive, and my own Shunt Drive (combined Jump + Scram).

**Comment by endless-sky** [comment]
Sorry, I checked in a commit to fix this before seeing that there was a PR for it.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/3698235b0e37644527541801acbdbcf1e71681cc rekt

**Comment by tehhowch** [comment]
Win some, lose some :1st_place_medal:

**Pull request closed without merging**
