### PR TITLE
feat: Add 2 Drone Bays to the Aerie

### PR DESCRIPTION
**Pull request by Saugia**
## Summary
The lack of accessible drone bays in human space often becomes a nuisance to those who capture drones earlier on. Despite not being extremely useful, many players still partake in capturing them, but currently have to wait until later in the game to either attempt capturing Automata drone carriers (requiring later game builds/JD access), Remnant Ibis (requires decent Remnant story progression), or the Hai Pond Strider (requires Wanderer campaign progression). 

Either this, or the player attempts to capture a Navy Cruiser/Carrier, which despite the Navy becoming hostile at one point in the FW campaign, doesn't seem to be a very solid reason to go out of the way and capture one just for this purpose.

The upcoming Sunder, a small mining ship that will carry two drones, will be a well-needed alleviation to this matter, but that doesn't mean it should be the only human ship able to carry Drones other than Cruisers. If on one end an upcoming small civilian vessel can carry two drones, and the other sits the Navy's large Cruiser/Carrier carrying four, there seems to be a nice spot in the middle for another ship, and the Aerie couldn't be a better fit.

## Implementation
Aeries have been constantly underrated in the game as their signature purpose is to be a small carrier. While an Aerie carrying two missile-oriented fighters can be fairly strong early in the game, they are still decently fightable as fighters are easily dispatched with any sort of decently sized weaponry. There have been talks as to buffing bay capacity for carrier ships, and the Aerie has been highlighted several times.

Adding two Drone bays to the Aerie further excels its particular role of a "pocket" carrier without going as far as to make it a carrier as strong as, well, the Carrier. Since it's such an underrated ship and very underused as many other ships do what it can except better, or don't even need to carry ships to be better, the Aerie deserves some love. Not only this, but this will now provide more incentive to obtain one as it will be another ship that can carry Drones in human space- a much needed utility as described above.

## Placeholding
A point was brought up as to why should a civilian ship be given drone bays if civilians won't be able to use them. I've currently given all Aerie fleets Combat Drones to fill them, and in the future when the Mining Drone is added, they can replace those on civilian fleets. The Deep would be keeping the combat drones (I don't see why the Deep couldn't have them). As for pirates, I'm not sure. They could easily plausibly capture therefore have combat drones, or just have mining drones. Maybe even mining drones refitted with a different weapon (Gatling gun? Javelin Pod?). 

This way, I'm avoiding having any bays empty (though I don't personally see a huge problem with that, but I understand gameplay/lore concerns). Perhaps this might be a time to revisit how obtainable combat drones should be? Either way, I'm fine if it makes more sense to leave the bays empty, or fill them with combat drones in the meantime. I don't think this is a major enough reason to cancel this entire concept.

All instances of an Aerie have been updated, and descriptions edited to match.

## Save File
N/A (I'm sure people can imagine an Aerie with two drones)

### CODE REVIEW

**Comment by tibetiroka** [comment]
The Skein seems to have better stats overall, but is a lot slower for the same price. Seems a bit more balanced now, although I'm still not sure if they are equal.

**Comment by tibetiroka** [comment]
I was actually worried that there wasn't a reason to use the Aerie before this PR, not the other way around. I quite like the idea.

**Comment by TheMarksman-ES** [comment]
> Despite not being extremely useful, many players still partake in capturing them

_Coughing in capturing as many drones as possible in that one TMBR mission._

**Comment by Saugia** [comment]
I agree that the combat drones on merchant/civilian fleets doesn't make sense, which is why I was advocating for them just remaining empty. Though then that kind of defeats the purpose of adding the drone bays by leaving them empty. The goal was to add another ship in human space capable of carrying drones while the bump to the Aerie being nice part alongside it. 

In the community poll back on ships, the Aerie was one of the ships a lot of people felt deserve a buff, and Derpy has also agreed with this a few times on stream. Statistically they are one of the least-bought ships for reasons stated above (and I meant in game as in, amongst all other ships- perhaps I should be more clear and say amongst human ships). The Sunder being introduced eventually (and someday possibly another small mining carrier) will definitely alleviate the drone bay issue. 

As for having extra bays, perhaps this was too immature of an addition. Again Derpy has mentioned on stream and others in discord about increasing overall bay capacity of all carrier vessels, so only doing it to the Aerie for the moment under the assumption all will do it someday is probably too premature. 

#sadaeriegang

**Comment by tibetiroka** [comment]
> Scanning, exploration, science, and patrol drones will likely exist in the ES universe as tools to perform potentially dangerous tasks that you don't want to risk human life for.

They totally do. There are already missions where Deep scientists send drones to investigate anomalies and wormholes; but there are currently _no ships manufactured by Lionheart that can carry drones._ In fact, human drone carriers are _exclusive to the Navy_ (with the only exception being the Class C Freighter).

It would make perfect sense for the Deep to have some sort of ship to transport their drones. That's all I'm saying here.

**Comment by Saugia** [comment]
@Anarchist2 how do you feel about Hecters response?

**Comment by Saugia** [comment]
>Would the addition of a combat drone that is purchasable by civilians make this PR possible?

Adding a *civilian* combat drone would definitely resolve the issue with restricted combat drones, but that brings up a new question- is there a reason why combat drones are restricted from civilians in the first place? Are they thought of as too much utility for a civilian to be able to use, and are more militarized? 

If we do make the civilian drone, then I'd have to propose it be a piece of junk with an energy blaster in it, a sort of "extra means of defensing against pirates, but not a fleet asset". Slower, only able to hold an energy blaster or smaller, less armor, etc.. Adding a civilian drone also adds another playstyle for the upcoming Sunder as a makeshift combat drone carrier, which seems like a good lead-in playstyle for players who want to lean towards carrier ships. 

As food for thought, if the Sunder is going to have 2 drone bays, then having the Aerie have two on top of the two fighter bays I feel also applies to the Aerie's role as a dedicated light carrier, otherwise a smaller mining ship is carrying the same amount of shipboard fighters.

>It would make perfect sense for the Deep to have some sort of ship to transport their drones. That's all I'm saying here.

I feel this is an important point as well- this would make the Aerie another asset to the deep in terms of their research and solidify it's lore a bit better than just "light carrier because light carrier". I think the most interesting thing to develop from this would be the Aerie ~~finally~~ getting some differences in fleets: 

1. Civilian Aeries carrying civilian combat drones
2. Civilian ones refit for mining carrying mining drones (which therefore makes an Aerie a newly desired ship as a step up from a Sunder)
3. Deep Aeries carrying the current combat drones as defensive weapons
4. Deep Aeries carrying surveillance drones as research focused (good use for editing/future Deep mission/incorporating the Aerie more)
5. Pirate Aeries carrying either civilian or regular combat drones

Not to mention giving the variants slightly different weapon loadouts. Currently the Aerie only has the base variant. 

Thoughts @Anarchist2 ?

**Comment by Saugia** [comment]
Closing this per discussions on discord. The concept is being held for the future and will still likely be used.

**Pull request closed without merging**
