### PR TITLE
Action choices to First person

### PR DESCRIPTION
**Pull request by Anarchist2**
As requested by Derpy.

### CODE REVIEW

**Comment by Pointedstick** [comment]
Isn't this inconsistent with other parentheses actions in conversations?

**Comment by Ferociousfeind** [comment]
I would rather change all parentheses options to be second person, so that it is an author giving you choices, rather than an author invading your mind

**Comment by Pointedstick** [comment]
Then that should be done in the PR as well, so it's at least theoretically merge-able, and then we can have a discussion about whether we want to make that change. Right now this PR is not merge-able because it would create a stylistic inconsistency if we merged it.

**Comment by Amazinite** [comment]
> Isn't this inconsistent with other parentheses actions in conversations?

These were inconsistent when they were added.

Here's a collection of action choices from some of the oldest missions in the game that are written in first person.

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/human/free%20worlds%20intro.txt#L437-L440

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/human/free%20worlds%20intro.txt#L484-L487

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/human/free%20worlds%20intro.txt#L757-L761

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/human/free%20worlds%20intro.txt#L1249-L1250

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/human/free%20worlds%20intro.txt#L1872-L1873

And even into the Wanderer campaign, first person was continued to be used

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/wanderer/wanderers%20start.txt#L934-L935

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/wanderer/wanderers%20start.txt#L1052-L1057

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/wanderer/wanderers%20start.txt#L1381-L1384

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/wanderer/wanderers%20middle.txt#L874-L876

https://github.com/endless-sky/endless-sky/blob/4d621c1d7416bb621f3bcbc1a5d0b65bef60f525/data/wanderer/wanderers%20middle.txt#L3084-L3086

Action choices were first person from the beginning and have continued to be first person. It is the action choices that are second person that are inconsistent at the moment.

**Comment by Pointedstick** [comment]
Ok!

**Comment by Amazinite** [comment]
While we're here, here's some other second person action choices I've spotted:
* coalition\coalition missions.txt
  * `	(Ask them to tell you about the data they have collected.)`
  * `	(Stay in your ship.)`
* hai]hai culture conversations.txt
  * `	(Play games on your ship.)`
  * `	(Keep your thoughts to yourself.)`
* human\culture conversations.txt
  * `	(Get out while you can.)`
  * `	(Hope she doesn't notice you.)`
  * `	(Finish your meal and leave.)`
  * `	(Finish up at your own pace.)`
  * `	(Settle your bill as quickly as possible and leave.)`
* human\deep missions.txt (ref: #6630)
  * `	(You shake your head. You have better things to do than bus old men around.)`
  * `	(You nod. Skaldgar and his hard-earned money are more than welcome aboard your ship.)`
  * `	(Answer for yourself.)`
  * `	(Let Helm answer for you.)`
  * `	(You offer to help Thorleif.)`
  * `	(You head to bed for some well deserved sleep.)`
  * `	(After all you've been through, you don't see any way to refuse the request.)`
  * `	(Sigh and shake your head.)`
  * `	(Rise from your seat.)`
  * `	"You only live once." (Key your signature.)`
  * `	(Unbuckle your seatbelt and get yourself up.)`
  * `	(Cannibalize the Ice-Crawler and contact your ship.)`
  * `	(Give up trying to contact your ship and fix the Ice-Crawler.)`
  * `	(Pump your fist.)`
  * `	(Try and find your way to the spaceport.)`
  * `	(Continue to meander because you are sick of Hjlod telling you what to do.)`
  * `	(Try and shake your leg free.)`
  * `	(Try and pull your leg free.)`
  * `	(Return to your ship.)`
  * `	(Power down your ship and open the hatch.)`
* human\human missions.txt
  * `	(Ready your ship for the battle with the Esca.)`
  * `	(Draw your sidearm and shoot the man.)` (appears twice)
  * `	(Run towards your ship and leave immediately.)`
  * `	(Put away your sidearm and pretend nothing happened.)`
* kahet\kahet missions.txt
  * `	(Try shooting at the hover engines of the Ka'sei with your sidearm.)`
* remnant\remnant 2 cognizance.txt
  * `	(Ask if you can help with their work.)`
  * `	(Gesture that you are not thirsty.)`
  * `	(Ask the Remnant next to you what just happened.)`
* sheragi\archaeology missions.txt
  * `	(Return to your ship and wait until the Emerald Sword is operational.)`
* wadnerers\wanderer start.txt
  * `	(Keep insisting that they listen to you.)`

**Comment by Amazinite** [comment]
Second person and first person action choices are actually neck and neck in usage right now. Here's my counts:
* Action choices containing "I" or "my" (including "I'm" and "myself"): 39
* Action choices containing "you" (including "your" and "yourself"): 39

As I made note of though, all the oldest stuff uses "I" and "my", whereas a vast majority of the "you" action choices are as new as having been merged after v0.9.14.

**Comment by W1zrad** [comment]
Interesting! I personally prefer using second-person (I may be behind a few of those 'you' uses since 0.9.14), but I'm cool with whatever as long as we're consistent.

**Comment by W1zrad** [comment]
Do we want to convert this PR to "fix all instances," or go ahead and merge this now and worry about the rest later?

**Comment by MasterOfGrey** [comment]
Now that I've heard the reasoning on stream, I support first-person action choices.

**Comment by DeBlister** [comment]
I prefer second person.  Before watching Derpy’s stream and seeing his reasoning, my thinking on it was that this isn’t a DnD game where you announce your actions to the rest of your group, with the DM possibly improvising if you devise a novel action.  The conditions presented to the player should be reasonably exhaustive, but they are nothing if not deterministic.  We should present the actions as correctly as possible.

Coincidentally, Derpy’s thinking seems to be similar but opposite mine, in that we should try to improve immersion by portraying it such that the game and player can improvise together.  I never had issues with immersion, though with the usages split and possibly weighted towards first person when I first played you may wish to take my personal experience in that area with a grain of salt.

*Please note that I haven’t played DnD before so my analogy is a bit on the outside-looking-in side, but I think my point stands with ES specifically* not *presenting spontaneous situations.*

**Comment by Ferociousfeind** [comment]
I don't want first person because no matter how you write it, it is always going to be your words and not the player's. Get out of the player's head!!

First person would, personally, rip me right out of it...

Of course, first person "being spoken" works fine, that is how spoken English works. But this is THE use case for second person in literature.

**Comment by W1zrad** [comment]
Another thought abt this that popped into my head after watching the stream vod - switching between 1st and 2nd person and back for each choice between narration does feel a little... "jarring" to me? Sems to clash with narration in a way that feels inconsistent. I agree with the reasoning of 1st person reinforcing it's the player's choice rather than the narration's, but that detail might get lost behind 1st person feeling too inconsistent with the majority of other text being 2nd person.

**Review by roadrunner56 — APPROVED** [review]

**Pull request merged**
