### PR TITLE
Add other artist names to the credits

### PR DESCRIPTION
**Pull request by Brick63**
they have added art so seems to be appropriate

### CODE REVIEW

**Comment by MCOfficer** [comment]
[Did they?](https://github.com/endless-sky/endless-sky/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Abeccabunny+)

**Comment by Zitchas** [comment]
And there is more coming, too. They've done a bunch of Remnant stuff for me that hasn't been PR'd yet, but will be as soon as the missions are ready. (Not to mention, they did the Penguin and Void Rifle, which are both in current PR's)

**Comment by Amazinite** [comment]
>We have dozens of one-time contributors who are not part of the credits.

This is only for art though, not any odd contribution. Excluding landscape images, Darcy, Comnom, and Omega are the only other people who have contributed art who are not in the art credits.

**Comment by comnom** [comment]
>This is only for art though, not any odd contribution.

In light of https://github.com/endless-sky/endless-sky/issues/2280 being milestoned, I don't see a reason not to just go ahead and fully update it with all the art people, tehhowch on programming, and a new section for significant story additions (ie, writing). It's all relevant to this, and then it gets checked off and done.

After that collaborators can require that large PR's update credits.txt from here on out to avoid a backlog.

**Comment by Amazinite** [comment]
While we're here, add Darcy, Comnom, and Omega to the credits and I'd say this is good to go. No point in only adding one person to the credits when there are three more that should be added as well.

**Comment by Brick63** [comment]
should be good now

**Pull request merged**
