### PR TITLE
Move trade panel

### LINKED ISSUE #627: Star map information panel overlap
when the screen resolution isn't big enough, some of those panel would overlap like:
screenshot

if it even smaller (eg, playing in window mode), part of it (mainly the commodity prices) end up being partly off-screen.

____
it's unplayable at the [minimum supported screen resoution](https://github.com/endless-sky/endless-sky/blob/f77acb85ced1daf620fba2a5785dbe3f4c546d62/source/main.cpp#L112) (lol)
screenshot_2016-01-09_01-46-24

### PR DESCRIPTION
**Pull request by asl97**
Fix #627 & #2230

~~After a whole bunch of copying and pasting lines of pixel by pixel to get the alpha require, I finally made a decent texture.~~

@endless-sky linked the [source images](https://drive.google.com/drive/folders/0B9aK8dG39P29fmtmVjJtZ2Iwa2NJWlRRUDhIZDdTSVRxR1RTSFplRDZUa0lPWE0xYlVaSVE) and those i can edit with ease

screenshot:
screenshot

### CODE REVIEW

**Comment by asl97** [comment]
ugh, alpha is still mess up, didn't see it in the graphic editor...

**Comment by asl97** [comment]
@endless-sky Fixed to the best that i could and rebased.

editing alpha is hard.

**Comment by asl97** [comment]
@endless-sky comments?  is it no good?  i know the top left corner of `images/ui/map key.png` isn't round but it's hard to edit it by hand to made it round.

**Comment by endless-sky** [comment]
The trouble is, this is an issue that only affects the <1% of systems with three ports, and only for the <20% of users with such a small screen. So in my mind, it's only worth making a change like this to the UI if it's also an improvement the other 99.8% of the time - especially because to make a change like this official would also require editing the original [vector graphics](https://drive.google.com/drive/folders/0B9aK8dG39P29fmtmVjJtZ2Iwa2NJWlRRUDhIZDdTSVRxR1RTSFplRDZUa0lPWE0xYlVaSVE) and @2x images to match.

**Comment by asl97** [comment]
@endless-sky imo, having the trade price shown at the same spot is a improvement (even though it's a small one).
____
why was those files not included in the repo?
it would have been much easier for me to edit through them than the pngs.

also, the current `map trade.png` in the repo and on the `map trade.xcf` on the google drive
as in the one in the repo doesn't have those square boxes on the bottom left

**Comment by asl97** [comment]
it was way easier to edit, the only problem is resizing it, some lines stay at two pixel wide.
it's not really noticeable in-game though.

the two original xcf files that has been edited is available here: https://www.dropbox.com/sh/ii89mo0xdhic1vg/AADr_Nju__nGrPrTaLm1nIOMa?dl=0

**Comment by asl97** [comment]
Finally notice the map trade is in the map ui and decided to redo it again after seeing another issue about this.

New screenshot:
screenshot

I merged the map trade svg and map key svg together in [map key.zip](https://github.com/endless-sky/endless-sky/files/1223428/map.key.zip)

Should probably clean up the map ui.svg but that is outside the scope of this pull request I think.

An png render of the svg since github doesn't allow uploading svg:
map key svg

**Comment by endless-sky** [comment]
Addressed this (finally) by moving the orbits widget to the top right and the key directly below it, in 746bc21. That addresses both this issue and the rather awkward-looking placement of the orbits widget:

map details

**Pull request closed without merging**
