### PR TITLE
[content] add Particle Cannon Turret

### PR DESCRIPTION
**Pull request by Taejang**
## Summary
Added Particle Cannon Turret and made it possible to purchase. No thumbnail included!

**Feature:** This PR implements the feature request detailed and discussed in [issue #6382](https://github.com/endless-sky/endless-sky/issues/6382)

## Feature Details
Turret added to human/outfits.txt and human/sales.txt using particle cannon as a guide on stats and purchase location.

Existing particle cannon thumbnail used as placeholder until a proper one is created.

### CODE REVIEW

**Comment by Red-57** [comment]
Most likely no-one is going to up and make an outfit sprite for you. The way this community works is that either you make the content yourself or you have to convince someone else to do it for you. We do not have a professional set of developers.

Another thing that may need to be considered is whether we really need a particle cannon turret, it is not good to make content just for the sake of making content. I would say that maybe discuss this farther with other people in the community before making a PR for it.

if you would like to join our discord server, here is the link https://discord.gg/ZeuASSx This is often where most of the content creators and the general community talk and discuss content creating.

**Comment by Galaucus** [comment]
Make sure you edit Syndicate hails so that any mentions of particle cannon turrets are appropriately altered

**Comment by Galaucus** [comment]
I'd also say... I'd rather we not have too many heavy beam turrets when it comes to long range heavy on heavy warfare. They aren't fun when you're in an interceptor and trying to dodge speed of light shots with good tracking on a 2D plane.

**Comment by Taejang** [comment]
> Most likely no-one is going to up and make an outfit sprite for you. The way this community works is that either you make the content yourself or you have to convince someone else to do it for you. We do not have a professional set of developers.
> 
> Another thing that may need to be considered is whether we really need a particle cannon turret, it is not good to make content just for the sake of making content. I would say that maybe discuss this farther with other people in the community before making a PR for it.
> 
> if you would like to join our discord server, here is the link https://discord.gg/ZeuASSx This is often where most of the content creators and the general community talk and discuss content creating.

While I did make a content request to discuss this first, I didn't know about the discord. Thanks for the link, and I'll pursue it further there. I'm leaving this PR up for now to help facilitate discussion (with actual stats and for easy testing, should someone besides me wish to), but may close it depending on discord feedback.

Perhaps I'll have to actually make myself figure out basic graphical editing then. For this particular thing, it should be possible to splice together a particle cannon with a turret mount for the outfit thumbnail. The ship-mounted sprite will likely be harder- or maybe easier, I honestly don't know. Won't hurt me to try it though. Whether I can make them look good is another story, of course.

> Make sure you edit Syndicate hails so that any mentions of particle cannon turrets are appropriately altered

I had no idea the Syndicate hails mentioned these; I'll have to look into that. Thanks!

> I'd also say... I'd rather we not have too many heavy beam turrets when it comes to long range heavy on heavy warfare. They aren't fun when you're in an interceptor and trying to dodge speed of light shots with good tracking on a 2D plane.

Right now the turret is only sold in one location and not on any NPC ship loadouts, so that part of the balancing is a non-issue until someone (likely me) creates a few ship variants that use them. Thanks for this reminder, I'll have to bring it up on the discord when I go to put together ship loadouts.

**Comment by EjoThims** [comment]
Pretty sure this is already in the works as part of the Republic campaign anyway, so (if that's the case) a separate stand alone is definitely not going to get through.

**Comment by Taejang** [comment]
> Pretty sure this is already in the works as part of the Republic campaign anyway, so (if that's the case) a separate stand alone is definitely not going to get through.

Yep, found out about this on the discord.

**Pull request closed without merging**
