### PR TITLE
Update commodities.txt

### PR DESCRIPTION
**Pull request by anonybosch**

### CODE REVIEW

**Comment by Pointedstick** [comment]
There are a couple of typos among the additions:
shitaki -> shittake
extention -> extension
oxigen -> oxygen
telescpoes -> telescopes
colomators -> collimators

Tungsten is really more of a heavy metal (I already added it there in my changes). And some are maybe a bit esoteric and difficult for the average person to imagine what they might be, like xylene, dacron, assorted shimstock, and monel.

Other than that, I like the additions!

**Comment by Wrzlprnft** [comment]
Do you know how to edit pull requests? @anonybosch

**Comment by Pointedstick** [comment]
You just make another commit to the branch that you're requesting be pulled.

**Comment by Wrzlprnft** [comment]
yeah, but anonybosch isn't familiar with github, so i wanted to offer some help if needed

**Comment by guillochon** [comment]
Since @anonybosch seems to be having some trouble, I've gone ahead and manually merged his commodities here: https://github.com/endless-sky/endless-sky/pull/410

**Comment by endless-sky** [comment]
Your updates were added in #410.

**Pull request closed without merging**
