### PR TITLE
Better commodity price comparison on map, compare any two systems.

### PR DESCRIPTION
**Pull request by ChamEV**
This PR allows the player to better see the price changes between two systems by showing both the change in price, and the actual price.  The change in price is colored to better demonstrate the potential profit.  Greater price differences are brighter, up to 500.  The player can also control click on systems to choose a comparison system, by default this is the player's current system.  If the comparison system is chosen, a light blue path is drawn between the selected system and the comparison system and a yellow ring is drawn around the comparison system.

Demonstration: https://streamable.com/rzkxk

commodityfinal1

Notes:
- If control click select is never used, the map behaves exactly as normal.
- The trade path will never draw over the travel plan, even if it does a lot of hi-jinx with shift clicking destinations and doubling back over itself.
- Nearly all modifications and additions are in MapPanelDetail.
- Overloads MapPanel select function.
- The commodity panel gets wider if necessary to handle the extra text, as does the click area to select the commodity.
- Adds Color::Blend(Color,ratio) to blend two colors.  (ratio% of one, leaves (1-ratio)% of the other).
- Creates one additional instance of distanceMap on selecting a system, this path finding class has the potential for exponential computational growth, however at the current # of systems, and this usage case, once per click, there is unlikely to be an issue here.  Select already creates one instance on it's own as well.

Needed:
images/ui/map trade extended.png (currently using a placeholder sprite)  Probably needs to be about 2 pixels wider than the current placeholder.
Feedback on colors, behavior.

### CODE REVIEW

**Comment by petervdmeer** [comment]
This PR seems aimed at the "trading power-user" type of players and I think it's very nice that this feature is invisible for regular players. As "power-user trader" I would however expect to get some more information when looking up a trade-route, like for example:
* How much cargo (and profit) would I get when I use all empty cargo-space for this product on this route?
* What are the crew salaries that I pay when moving over this route with my active ships?
* How much interest would I pay if I would have to borrow the money for buying goods? (Or: how much interest do I pay while travelling this route?)
* What is the value-loss I have in ship deprecation when moving over the route? (To check if it makes sense to buy more transport ships and sell them at the destination.)
* Calculate not just 1 route, but a loop.
* How stable is the route? (Demand for a product decreases when a lot of the product is delivered.)
* How safe are the systems I travel through? (Pirate systems, uninhabited systems, ...)
* Both the source price, the target price and the price-delta.

The colors look nice, but some numbers seem to be a bit hard to read (like the dark red).

I would also expect the travel path to be invisible when the blue "comparison path" is active. Showing both at the same time is likely going to confuse users of this feature. (And the travel path hiding the "comparison path" is also not too desired, since the user is actively looking into the comparison path when using this feature.)

**Comment by ChamEV** [comment]
I wonder how much hand holding we should be doing for the user.

>     * How much cargo (and profit) would I get when I use all empty cargo-space for this product on this route?
>     * What are the crew salaries that I pay when moving over this route with my active ships?
>     * How much interest would I pay if I would have to borrow the money for buying goods? (Or: how much interest do I pay while travelling this route?)

These seem reasonable, and should be easy to implement, total cost per loop and total profit per loop.

>     * What is the value-loss I have in ship deprecation when moving over the route? (To check if it makes sense to buy more transport ships and sell them at the destination.)
A bit harder, and changes each loop due to being non linear.
>     * How stable is the route? (Demand for a product decreases when a lot of the product is delivered.)

I haven't looked too closely at the relationship between the players trade capacity and price stability, or how to predict the long term effects of mass trades.

>     * How safe are the systems I travel through? (Pirate systems, uninhabited systems, ...)
I think this is out of scope at this time, tehhowch's system danger level system, and the general piracy threat shown in player info can be used by the player.

>     * Both the source price, the target price and the price-delta.

This may be a bit unwieldy.  The price difference is what players are looking for when they regular click select.  when they control-click select, I'm unsure how to make it obvious which one is which if both prices are included.

> The colors look nice, but some numbers seem to be a bit hard to read (like the dark red).

Is this opinion from the video or screenshot?  The video host lowered the video quality more than I'd have liked.  As for the colors what would you suggest?  Currently it blends the regular dim color with red/green based on the magnitude of the difference.  So it should never be harder to read than the dim color already is.  I did not use the less dim color when the commodity was selected as  it made the colors looked washed out.  Any suggestions on how to improve this are welcome.

>     * Calculate not just 1 route, but a loop.
> I would also expect the travel path to be invisible when the blue "comparison path" is active. Showing both at the same time is likely going to confuse users of this feature. (And the travel path hiding the "comparison path" is also not too desired, since the user is actively looking into the comparison path when using this feature.)

This may be an alternative way to go.  Control click your 2, 3 or 4+ systems, game calculates all the profit and costs for the player over that route.  If it's a closed route (starts where it ends), then we calculate both ways, showing the best direction with arrows.  Otherwise an open route just assumes going back and forth between end points.

I'm hesitant to hide the player's current path outright, maybe dimming it would be better.  Maybe making the trade route use narrower lines so if it draws over the travel route both are visible.

**Comment by ChamEV** [comment]
Made some updates, will need to clean it up, and clear out unused code and save some of it for later, particularly the non-drawing over the travel route.

* Can now deselect trade comparison by control clicking on the compare system, you can also do this by control clicking on your current system or any uninhabited system, or simply closing and opening the map/switching map views.
* Dims the travel route while comparison route is active.
* Draws over links of travel route while comparison mode is active.

I've been thinking about providing the extra info about trade route profitability and I think it's too much at this time.  It's certainly nice to have, but it can be added as a separate feature later.  Specifically I would like an easier way to access the player's income and expenses.  I think the best way to do this is modifying Account::Step() and caching the totals each day so other areas of the game can just ask for total expenses, total income instead of having to go through each tribute, salary, loan, etc. themselves.  But this feature probably needs it's own pull request and review.

I did implement total profit for the route however and it looks like this:
tradesummary1
tradesummary2
The next 2 lines would simply be expenses, and totals.  The text would be right aligned in each column, and there would be a background UI sprite.  The color of the green may change based on how profitable the route is, with anything above 80 cr/ton/day getting max green.

For now players are pretty much just looking for the biggest trade route they can find, which means finding the biggest deltas between worlds.  So they'll be looking for the brightest red's and greens.

There's two issues I have currently however, the first link of the travel route looks overly white when dimmed.

The second is a little complicated.  When the player first opens up the port map, the player's system is selected, and the travel route is shown to some other system, which is not selected.  Any time the player changes travel routes, he selects a new system, which is not the player's current system.  Makes sense.  Now when they open the map with a travel route to some system, and the player's system is selected and control click a third system, the trade route is drawn from the player's system to the trade system as seen here.

tradesummary3

As soon as they select another system, it updates both the travel route and trade route resulting in the normal looking version in the 2nd screenshot above.  Player is in Epsilon Leonis, travel route is to Pollux, which they are comparing with Tania Australis.

I could just leave it, it's an idiosyncrasy that may bother no one but me.  Or I could change the selected system to the end of the travel route, but that would also be unexpected behavior for some people.

Here's a video of the current implementation, ignore the colors in the video, this website seems to do a bad job at re-encoding: https://streamable.com/fv0vk 

At the end you'll see this issue, or maybe not an issue at all.

Finally, is Blend the right function name for the color function I added?  Is there a better or more standard name for what it does?

**Comment by ChamEV** [comment]
Added 2 commits, first contains the WIP for displaying the trade route value/profit for preservation's sake.  The latest cuts that part out, removes all dead code, cleans up comments and is ready for review.

Still needs a new background sprite for the wide commodity comparison.

**Comment by Pointedstick** [comment]
For the "power-user trader" I can imagine a special "Trade hub network connector" outfit or something that would unlock that additional information on the map. That would save the UI from getting too cluttered up with all that extra information for people who don't buy the special outfit

**Comment by Bladewood** [comment]
The biggest issue I have here beyond anything else is the choice of colors. That bright RGB tone is very "tacky."

Aside from that, have you seen https://github.com/endless-sky/endless-sky/pull/3963 and https://github.com/endless-sky/endless-sky/issues/3964#issuecomment-435725884? Those pertain to the Trading screen, but I think they're still relevant here.

**Comment by ChamEV** [comment]
>For the "power-user trader" I can imagine a special "Trade hub network connector" outfit or something that would unlock that additional information on the map.  That would save the UI from getting too cluttered up with all that extra information for people who don't buy the special outfit

If they have this outfit, the UI still has to not be cluttered.

If ships can already access the trade prices from anywhere via the hyperspace communications network, then getting price comparisons is just software installed on the ship.  It would be weird if that took a ton of space.  Do you then just buy a 0 ton outfit that's just software?  Do they no longer have free and open source software in this future?  Ideally the player would not need to re-buy it every time they switch ships, so it's like a license, but it's not a license.

> The biggest issue I have here beyond anything else is the choice of colors. That bright RGB tone is very "tacky."

It is currently .75 on the green/red scale.  I could lower that.  Is there any other color scheme worth trying?  Do you like the continuous color change?  Low variance is basically just grey.

> Aside from that, have you seen #3963 and #3964 (comment)? Those pertain to the Trading screen, but I think they're still relevant here.

Neither really reached a consensus about coloring or icons.  The icons suggested a much greater rate of change for commodities on any single planet.

**Comment by Tadrix** [comment]
Didn't MZ state at some point that he designed the game colours to be friendly to people with red/green colour blindness? Indicators that operate on that scale would ruin that objective.

**Comment by ChamEV** [comment]
I ran an example image through http://www.color-blindness.com/coblis-color-blindness-simulator/ 

The results are the red/green look like gold for the most common color blindness, but critically for every type the text is readable from the background.  The + and - are the primary way to distinguish between increased and decreased prices.

image

**Comment by petervdmeer** [comment]
Sorry to see this PR being delayed; most of my review-comments seem to have been handled in 2019 and @chamEV already identified some remaining issues that still need to be handled; I just never want to see the travel-plan and the comparison drawn at the same time.

The PR is currently not in a merge-able state however, so I'm going to mark it as "Waiting on OP". Please resolve the merge-conflict and the remaining issues to get this merged.

**Comment by Amazinite** [comment]
Closing all PRs which have been marked "orphaned."

**Pull request closed without merging**
