### PR TITLE
WIP: Update Heliarch fleets

### PR DESCRIPTION
**Pull request by unjown**
## Summary
Update Heliarch fleets

## Save File
This save file can be used to play through the new mission content:
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
 - [ ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}
  
  
-----------------------

## Testing Done
WIP

## Feature Details
I have separated heliarch fleets onto small and large,

I thought this would be necessary since all other fleets have large and small

TO DO
[ ] Apply changes to map.txt
[ ] Build and test

### CODE REVIEW

**Comment by Arachi-Lover** [comment]
The Heliarchs have no need for large fleets as their ships are simply on regular patrols, as there is no area that needs more or less security than another, as there is no conflict in Coalition space at the moment.
For the campaigns there will be different fleets, but there is no need to implement those now, especially as I don't even know how large the fleets used in the campaigns will need to be, as that will vary with testing for balance in battles.

**Comment by Amazinite** [comment]
Note that the Quarg similarly only had a single fleet size until larger fleets became necessary with the addition of the Korath automaton territories.

**Comment by unjown** [comment]
i see.. but i will keep this PR open in case 😁

**Comment by Amazinite** [comment]
>i see.. but i will keep this PR open in case 😁

That's now how it works, unfortunately.

**Pull request closed without merging**
