### PR TITLE
Outfit Expansion

### PR DESCRIPTION
**Pull request by AJMansfield**
You can already trade outfit space for crew space via a Bunk Room, but you should also be able to make that trade in reverse: reduce crew capacity and gain extra outfit space. It also makes sense physically - it should be possible to strip out bunks and tables and just put that reactor in the mess hall.

In a lot of cases, some ships have just far more crew space than is needed. When I have upwards of  800 free bunks across my entire fleet, I should be able to do at least something with that, and presently there aren't jobs that involve transporting hundreds of people at a time, and there aren't hundreds of smaller jobs available at one time either.

I have been playing with this outfit for a while, and it appears to be suitably balanced. It does modify the game balance by making it possible to fit more outfits into things, but overall it makes the game more fun.

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm a little bit worried about how this would affect balance. Right now the Bactrian is already overpowered because you can convert all its cargo into outfit space. If it were also possible to convert bunks, ships like the Bactrian (and the World-Ship, which has huge numbers of bunks) would become even more overpowered compared to purpose-built "warships" with limited cargo.

**Comment by AJMansfield** [comment]
The only thing you could really do with the space to make the ship OP is add lots and lots of shields though, since the engine and weapon limits already prevent you from going too fast or getting too much DPS. But by the time you get there, it is actually more efficient to use a larger number of smaller ships, since you can get much more DPS that way. In fact, the only reason I don't just use a fleet of 800 sparrows is because I need a large capital ship in order to board large enemy capital ships, and because of the lag.

**Comment by lehgogh** [comment]
> presently there aren't jobs that involve transporting hundreds of people at a time

I'll get to work on a PR that adds large transport missions.

**Comment by endless-sky** [comment]
Sorry, I just don't think that letting bunks be swapped for outfit space is ever going to be a "balanced" option - it's way too powerful.

**Pull request closed without merging**
