### PR TITLE
Artwork: New Hai Railgun, Railslug, and Railslug Rack sprite

### PR DESCRIPTION
**Pull request by 1010todd**
**Content (Artwork)**

## Summary
New outfit sprite for Hai Railgun, Railslug, and Railslug Rack because I don't like how the railslug looks currently. The triangular shape of the current railslug is maintained but instead it becomes a (overcomplicated) sabot ammo like real railgun ammo. The railgun itself also received a remodel into multi-barrel rotary railgun instead of odd 3-rail thing. The railgun design was primarily based off  more round-ish shapes of their reactor and ships. Railslug rack was also remodeled to to take the new railslug as well as directly fitting with the new railgun sprite, in addition it also got part of loading mechanism exposed to add a bit more to the sprite.

New Sprites:
railgun setv2

In Game :
railoutfitternew

<details>
<summary>Additional Images</summary>
Railgun 4x image

railgun new4 4x

Railgun left view

railgun@4x left

Railslug sabot 4x

railgun sabot2@4x

Railslug rack 4x

railslug rack@4x

Railgun + (old)slug rack

railgun w storage hai

Shot fitting.

railgun shot fitting

</details>

## Save File
This save file can be used to play through the new mission content:
Any save within Hai space.

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{[PR link](https://github.com/endless-sky/endless-sky-assets/pull/101)}}
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{[PR link](https://github.com/endless-sky/endless-sky-high-dpi/pull/323)}}

### CODE REVIEW

**Review by beccabunny — APPROVED** [review]
Damn, this looks fantastic

**Comment by Saugia** [comment]
~Can we see them in game please~

**Comment by bene-dictator** [comment]
These are super slick!

**Comment by Pointedstick** [comment]
This is hot as hell.

**Review by McloughlinGuy — APPROVED** [review]
Absolutely amazing

**Comment by Saugia** [comment]
While I watched you make this in discord, I was somewhat concerned your style of extreme/small detail would be a bit too much for the game (Hai aesthetics aside). Seeing it in game now, it actually looks really good! 

The only thing that I have a quick thought on is the rack doesn't really show the slugs. It looks like some sort of containment contraption either way, but it's hard to tell those little points in the middle are the slugs. I almost want less framework surrounding them so I can see them better, while keeping just enough framework for the sliding mechanism to still be plausible.

If you think you can do something with that, go ahead, but otherwise, this looks pretty good either way.

**Comment by 1010todd** [comment]
Updated railslug storage. Asset and 2x PRs also should be updated now as well.

**Review by Saugia — APPROVED** [review]
Much better. Looks great!

**Pull request merged**
