### PR TITLE
fix(typo): Various Typos in 0.10.1

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR fixes a few typos found in 0.10.1. I will leave it as a draft for a bit for if any more are found later on. 

Note: Some were found later on.

Thanks to Midnight on discord for finding some, and Tibe for others.

### CODE REVIEW

**Comment by tibetiroka** [comment]
Two more typos:

data/human/news.txt:1390:
```
"This is the life! I'm only in class like 3, so my days are totally open! I know it'll end in a few years, but I'm going to enjoy it while I can. After you graduate, it's just work work work until you're dead."
```
should be something like
```
"This is the life! I'm only in like 3 classes, so my days are totally open! I know it'll end in a few years, but I'm going to enjoy it while I can. After you graduate, it's just work work work until you're dead."
```
(See #8898)

data/human/deep missions:4120: 
```
`	There's an old-style book there, bound up in a ice-blue cover, titled: "The Skadenga Saga: Against All Odds, by Hjlod Hrimnirsdottir."`
```
should be 
```
`	There's an old-style book there, bound up in an ice-blue cover, titled: "The Skadenga Saga: Against All Odds, by Hjlod Hrimnirsdottir."`
```
(a ice-blue -> an ice-blue)

**Comment by tibetiroka** [comment]
Damn it, two more:

data/bunrodea/bunrodea outfits.txt:76:
```
description "The Nanite Enhancer is a component that can be installed into a Bunrodean nanite fabricator in order to modify its effectiveness. Enhancers increase the strength of the hull repair of an fabricator, but at the cost of reduced energy efficiency."
```
an fabricator -> a fabricator

data/hai/hai reveal 1 intro.txt:66:
```
`	A functionary leads you to what appears to be a situation room, filled with monitors, holoprojectors, and other equipment. Everyone takes their seats at an semicircle-shaped table, and the functionary motions you to the middle seat. A massive holoprojector in front of the table turns on.`
```
an semicircle -> a semicircle

Should be the last of these a->an issues.

**Comment by tibetiroka** [comment]
I'll try to add this check to the content style checker as a warning.

**Comment by tibetiroka** [comment]
~~Aaaaaaaaaaaaaaa~~

There seems to be an extra empty line at the end of data/human/deep missions.txt.

**Comment by warp-core** [comment]
Merged the fixes from tibe and removed a couple of extra empty lines in GameData.cpp.

**Review by tibetiroka — APPROVED** [review]

**Pull request merged**
