### PR TITLE
Add unique effects for the Burning und Corrosion status effects

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds unique effects for the Burning and Corrosion status effects, a "smoke" effect for Burning and a "disintegration" effect for Corrosion.

Burning effect:
burning

Corrosion effect:
corrosion

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/65
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/278

### CODE REVIEW

**Comment by warp-core** [comment]
Milestoned for 0.9.15 because this should be added in a release no later than #6891 (KEE stage 1) and that is milestoned for 0.9.15.

**Review by Saugia — APPROVED** [review]
I don't have a whole lot to discuss for a review since I was part of the process on discord. Everything looks like it was well addressed (for all sides). 

The smoke looks very nice for the heat effect and blends together very well, creating a "fog" effect and trails off of a ship nicely. Having the hints of red-browns in there also adds to the effect, much more than the bright oranges it used to be and is nice and subtle. The only comment I would have is that it does get a big messy if a ship isn't moving because it consumes the whole ship, but in an arcade game as a visual indicator that is fine (and it's not like it stays that way anyway). 

The corrosion also came out nicely- it really does look like sheets of metal slowly peeling off of a ship, and the very subtle green to it helps distinguish it from other effects (most notably disruption, which looks similar in that sparkly whites design), and is much better than the initial idea of notably green chunks. 

+1

**Review by beccabunny — APPROVED** [review]
LGTM👍

**Comment by kestrel1110** [comment]
...this is beautiful

**Review by roadrunner56 — APPROVED** [review]
Looks good to me!

**Pull request merged**
