### PR TITLE
Higher Resolution Stations

### PR DESCRIPTION
**Pull request by Anarchist2**
## Summary
This PR implements #4779, and makes stations be double-resolution but half-scale, just like ship sprites. Not sure whether it would be worthwhile making high-DPI versions of the new stations sprites.
Compare and contrast:
image
image
image
image

## Artwork Checklist
 - [x] ~I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky/pull/6964
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/271

### CODE REVIEW

**Comment by ravenshining** [comment]
> Not sure whether it would be worthwhile making high-DPI versions of the new stations sprites.

Revamping the Korath station sprites is actually a thing already in progress, so that's just what we'll do :-)

**Comment by Amazinite** [comment]
I do think that we should still have 2x versions of these sprites. Looks like that'll require a fair amount of time to do, though, as from looking through some of the .xcf files for the stations, not all of the stations were rendered and postprocessed at 4x.

**Comment by MasterOfGrey** [comment]
> I do think that we should still have 2x versions of these sprites.

Would this be a different PR though?

**Review by beccabunny — APPROVED** [review]
I've wanted this for a long time, looks good!

**Pull request merged**
