### PR TITLE
Hide unknown outfits

### PR DESCRIPTION
**Pull request by daggs1**
this feature was split from PR #7906

the goal of this feature is to hide unknown outfits marking them as unknown until the player has entered an outfitter.
screenshots from PR https://github.com/endless-sky/endless-sky/pull/7906:
https://user-images.githubusercontent.com/90052312/209447696-699c123c-65fb-45f1-81db-7ebd54156306.jpg
https://user-images.githubusercontent.com/90052312/209447697-cc0ad4e0-ea6b-4700-921b-5a57ca78b11a.jpg
https://user-images.githubusercontent.com/90052312/209575577-17b8b91b-e53a-45af-8e5d-be0dbb685b52.jpg

when the feature is enabled, the logic is as follows:
an outfit will be marked as unknown until:
1. the player enters an outfitter when the outfit is in it's cargo
2. the outfit was given to the player as a present or as a reward from a mission
3. the outfit is part of a captured ship
4. the outfit is part of a bought ship
5. the outfit is an asteroid which was targeted using an asteroid scanner

when encountered an unknown outfit in either boarding, outfit scan, cargo scan or when invoking the ship's info panel:
1. the outfit name will be "Unknown Outfit" or "Unknown Outfits" for more than one.
2. it's value is not shown

unknown outfits cannot be sold via the trading panel as it's value is not known.

this feature depends on a preference key which is set to off by default.
like the other pr split from #7906, the code is written as such so switching between the mode of the feature only affects the UI.

tests were done as in the original PR in addition to asteroid and cargo scans

performance impact should be minimal and based on the std::set's insert and count complexity time.

### CODE REVIEW

**Comment by DarcyManoel** [comment]
It may be better to display just "Unknown" on the boarding menu, all other cases feel right with the full "Unknown Outfit".

**Comment by daggs1** [comment]
> It may be better to display just "Unknown" on the boarding menu, all other cases feel right with the full "Unknown Outfit".

your suggestion is because commodities are listed in the boarding list?

**Comment by LorenzoBolla** [comment]
I think it's because it just looks better with just "unknown" in the boarding panel! At least IMO.

**Comment by daggs1** [comment]
> I think it's because it just looks better with just "unknown" in the boarding panel! At least IMO.

imho it is confusing, boarding can get you commodities or outfits, as commodities are not masked out as they are not outfits, placing "unknown" rather than "unknown outfit" leads one to the assumption that there is another thing beside outfit that can be plundered from that ship when there isn't one.
I'd prefer leaving it with "unknown outfit"

**Comment by LorenzoBolla** [comment]
Is stuff like yottrite and void sprite parts ever unknown with this code? They count as outfits, technically, on the menus, but are actual commodities instead. Boarding can then get you outfits, commodities, and commodities which are classed as outfits, but should definitely not be called "unknown outfit". 

If only actual outfits can be unknown, while I'm still sure if having them not explicitly called that could cause enough confusion to justify an "uglier" text choice, it is a very reasonable thing to worry about. 

Either way, absolutely great work, i find improvements to the "learning through playing" side of things to be very positive. I love this change!

**Comment by daggs1** [comment]
> Is stuff like yottrite and void sprite parts ever unknown with this code? They count as outfits, technically, on the menus, but are actual commodities instead. Boarding can then get you outfits, commodities, and commodities which are classed as outfits, but should definitely not be called "unknown outfit".

Yottrite, Iron, Silicon, all are considered outfits and are covered by the code, mineral outfits have special case handling, see bullet num 5 in the list above.

as for void sprite parts, I didn't encountered such so I don't know how to address them.
unless I encounter them of given a savefile with the ability to access them, I cannot change much here.

> 
> If only actual outfits can be unknown, while I'm still sure if having them not explicitly called that could cause enough confusion to justify an "uglier" text choice, it is a very reasonable thing to worry about.
> 
it is possible change the print of the name if the category is mineral, but code-wise, there isn't any difference between boarding scenario and other scenarios and I don't think adding such change is correct, so as I see it, either, keep it as is or change minerals naming to all relevant code bits

> Either way, absolutely great work, i find improvements to the "learning through playing" side of things to be very positive. I love this change!

thank you for your kind words

**Comment by DarcyManoel** [comment]
If the options for representation of unknown outfits are too conflicted, we could default to `???`.

**Comment by LorenzoBolla** [comment]
> Yottrite, Iron, Silicon, all are considered outfits and are covered by the code, mineral outfits have special case handling, see bullet num 5 in the list above.

Alright, so the issue here would be that a ship may break down an asteroid of a material you had never targeted (if, for example, you never had an asteroid scanner on board in that game, or never mined asteroids with one, anyway), and then the minerals would show up as an `unknown outfit` in their hold! For Void Sprite Parts, they are found in the holds of Korath ships during the Remnant campaign, and it'd be weird to have them called outfits, too. 

If you could rename just the mineral class "outfits" to `unknown materials` as a blanket category, that would be nice. Or use `???`, like Darcy said. Just to avoid that small confusion!

**Comment by daggs1** [comment]
every mineable is saved under the Mineral class.
such items won't show up under the scanned outfits dialog, only in cargo scan and in the ship info screen.
this means that all mineable outfits can be label as "Unknown Mineral". this change is rather simple to preform
agreed?
as for void outfits, I see only one (Pincer), problem is, I cannot distinguish between it and other outfits.
I'd recommend leaving it for now until there will be more outfits

**Comment by daggs1** [comment]
here:
image

**Comment by Amazinite** [comment]
Marking unlikely as per the comment on one of the other PRs: https://github.com/endless-sky/endless-sky/pull/8531#issuecomment-1475379970

**Pull request closed without merging**
