### PR TITLE
Add spatial container for asteroids

### PR DESCRIPTION
**Pull request by flaviojs**
Reference: #3146

This is a space-time tradeoff using http://spatial.sourceforge.net/.

Why did I use this particular library?

* header only library simplifies dependencies
* don't have to configure anything
* don't need to create or modify existing classes, standard ones are sufficient

I'm not sure how this kind of dependency should be handled, so I took the easy way out and just dumped the root files and the source (headers) into ```source/spatial/``` =~

----

Possible improvements that I didn't try:

1. If mask collisions are heavy, doing line-box overlap tests to decide when to do them should improve performance. This is not worth trying unless mask collisions are confirmed to have a significant performance impact. I would probably try the method described in the answer to https://math.stackexchange.com/questions/91362/fast-2d-line-triangle-intersection-test
2. When the movement crosses both vertical and horizontal wrap edges, there is 1 or 2 of the split boxes that can be discarded. This looks like a small performance impact, so probably not worth the trouble.

### CODE REVIEW

**Comment by Amazinite** [comment]
Wow, that's a lot; I'll test this out when I get the chance.

**Comment by jafdy** [comment]
This is a roughly 10% increase in the number of lines in the entire project (both C++ and .txt). OK, it is very well commented but even so I do wander if it is a bit obtuse.

**Comment by tehhowch** [comment]
I'm not sure if you can submodule a repo hosted not on git, but I imagine that would be the preferred way to rope in an external dependency.

Going solely off your comments in da55965, the use of this library sounds a fair bit like the CollisionSet class, in which only those objects within a grid cell (containing the projectile) are checked for collisions rather than all objects

**Comment by flaviojs** [comment]
CollisionSet is a spatial container too, but uses non-overlapping fixed-size cells instead of content-based regions. Looks like a matrix instead of a tree.
I don't see non-Body functions being used so Ship can probably be changed to Body.
Not sure what would need to change so that it works as an infinitely-repeating region.

It's definitely a possibility, I'll try adapting it. :)

**Comment by tehhowch** [comment]
It was just recently made Ship-only :)
Definitely keep this pull open (maybe see if it can be done via git submodule for easily performing version updates first) for input on external dependencies in the future

**Comment by endless-sky** [comment]
It doesn't make any sense to me to add a completely different set of functions for spatial lookup when CollisionSet already exists (and probably has very similar performance).

**Comment by flaviojs** [comment]
This PR was superseeded.

**Pull request closed without merging**
