### PR TITLE
feat(ci): Exclude individual words from the spellcheck CI

### PR DESCRIPTION
**Pull request by tibetiroka**
**Feature:** This PR adds the ability to exclude words from the spellcheck CI. This is done in a separate file, and the old, line-based exclusions remain supported.

## Feature Details
From the [docs](https://github.com/codespell-project/codespell#ignoring-words):
> When ignoring false positives, note that spelling errors are case-insensitive but words to ignore are case-sensitive. For example, the dictionary entry wrod will also match the typo Wrod, but to ignore it you must pass wrod.

See also: [ignore_words_file](https://github.com/codespell-project/actions-codespell#parameter-ignore_words_file)

## UI Screenshots
N/A

## Usage Examples
Alien words can now be ignored once, instead of having to put the whole line into the ignore file every time they appear.

## Testing Done
Added a typo and tested it with/without the exclusion. Works as expected.

### Automated Tests Added
N/A

## Performance Impact
N/A

### CODE REVIEW

**Comment by warp-core** [comment]
Add the new file to the codespell section of .github/path-filters.yml.
https://github.com/endless-sky/endless-sky/blob/2d254f624c035d8f9a6500806a95893f13dced0a/.github/path-filters.yml#L17-L18

**Comment by tibetiroka** [comment]
Yeah, I was doing that rn, just couldn't find where. Thanks!

**Comment by tibetiroka** [comment]
Should be good to go now.

**Comment by Hurleveur** [comment]
This would change CC life forever

**Pull request merged**
