### PR TITLE
[Bugfix] Make Successors: Researchers Out 1 and Large Researchers Out 1 Account for Distance

### PR DESCRIPTION
**Pull request by tekker2234**
makes the researchers out missions do distance calculations so the scientists start paying you to transport them.

### **Bug fix**

This PR addresses the bug/feature described in issue #10550

## Summary
Successors: Researchers Out 1 and Large Researchers Out 1 give low or negative payments due to not taking into account the wormhole or jump drive required to get to the stopover. This makes them take jump drives and wormholes into account so they stop ripping you off.

### Before
Screenshot 2024-10-04 133041
Screenshot 2024-10-04 004034

### After
Screenshot 2024-10-04 223209
Screenshot 2024-10-04 223148

## Usage examples
N/A

## Testing Done
set random < 100 (for convenience)
added the lines
saw the payout (as seen in screenshots)

## Save File
N/A

## Artwork Checklist
N/A

## Wiki Update
N/A(?)

## Performance Impact
N/A

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]

**Review by reticent-rem — APPROVED** [review]
Good catch and good problem solving to get to the fix!

**Review by Daeridanii1 — COMMENTED** [review]
Good fix, thank you! 
This does leave me a little bit concerned about the size of the payout for the `Successors: Large Researchers Out 1` mission in particular, if it's offering potentially over a million credits per run. It's a lot for a job board mission! That being said, I'm not particularly knowledgeable about the balancing of credits rewards, so I'd be happy to defer to someone with a more experienced opinion in this area.

**Comment by TheGiraffe3** [comment]
I think it's probably fine. Seeing as how there are Wanderer missions which give almost that much for the same amount of people, and this requires both an installed Jump Drive _and_ Quantum Keystone, the large payout is alright.

**Comment by tekker2234** [comment]
> Good fix, thank you! This does leave me a little bit concerned about the size of the payout for the `Successors: Large Researchers Out 1` mission in particular, if it's offering potentially over a million credits per run. It's a lot for a job board mission! That being said, I'm not particularly knowledgeable about the balancing of credits rewards, so I'd be happy to defer to someone with a more experienced opinion in this area.

I agree with TheGiraffe3 on the need for more special equipment justifies the higher payout. A good point of comparison for this might be the high class tourist group jobs in human space, which use higher modifiers (250 for regular, 170 for large) but have a lower but consistent base payout between the two (25000).

**Comment by Saugia** [comment]
Prices are on the high end, but comparing it to some other missions like Remnant bounties and Coalition missions, they seem somewhat plausible, so we'll keep an eye on them for now.

**Pull request merged**
