### PR TITLE
Add several ships to pirate fleets

### PR DESCRIPTION
**Pull request by ZBok**
This PR adds the Osprey/Mule/Aerie/Vanguard/Protector to pirate fleets.

### CODE REVIEW

**Comment by ZBok** [comment]
This was part of a four part PR plan but said plan is on hold for now and this PR isn't really doing much by itself.

**Comment by ZBok** [comment]
Reopened.

**Comment by Amazinite** [comment]
I put this off originally because I think that any change to the pirate fleet warrants a good look at if we should just combine it with a resolution of https://github.com/endless-sky/endless-sky/issues/4158. It's notable that this PR swings the average fleet strength of large pirate fleets toward heavier ships. In order to not bog this PR down though, I think I'll just merge this after v0.9.10 is out then handle the balancing on my own. 

A question on the addition itself though; why add Mules to every region?

**Comment by Amazinite** [comment]
Anyone home?

**Pull request merged**
