### PR TITLE
Militia Hails

### PR DESCRIPTION
**Pull request by Amazinite**
Striking another bullet off the list. 👍

### CODE REVIEW

**Comment by OmegaLokkes** [comment]
If the militia are just volunteered/recruited merchant(ish) captains, I feel like the hails would be a bit less formal, and more like normal merchant hails.

**Comment by Amazinite** [comment]
Given that the militia seem to often fly a few ships that merchants don't normally have, I'd think that there is at least some structure and formality to the militia. There's also the fact that the Free Worlds rose up out of the militia, so I would think there would be at least some sort of formality in becoming a militia. If anything, it may be more of a mixed bag of people who are formal and take the job seriously and those who do not, which I feel that I already somewhat did with these hails (one friendly hail about militia complaining that the Navy never show up and a hostile hail where the militia tell all the surrounding merchants to "Activate your hyperdrives!").

**Comment by endless-sky** [comment]
Thanks!

**Comment by Pointedstick** [comment]
Those are excellent!

**Comment by Amazinite** [comment]
No, thank you. :3

**Pull request merged**
