### PR TITLE
Landmarked locations in missions!

### PR DESCRIPTION
**Pull request by warp-core**
**Feature:** This PR implements the feature request detailed and discussed in issue #1934

## Feature Details
This implementation is based on the design proposed by @Elyssaen in the linked issue.

Within a mission, a set of named location filters, `landmark`s, may be defined.
On instantiation, a planet and system will be selected from each of these and stored alongside hte corresponding name for use by the various places that can use planets or systems throughout hte rest of instantiation.
This includes:

- Mission stopovers.
- Mission waypoints.
- Mission destination.
- NPC systems.
- NPC planets.

The mission `source` may not refer to a landmark: this would have no use anyway.
A stopover and waypoint cannot really be the source planet or system anyway, and the destination will automatically be set to hte source if no destination definition is provided. Similarly, the NPC will use the source system if no system definition is provided.

This will almost certainly conflict with #8029, and even if it does not *actually* conflict, it probably will be conflicting in terms of logic, and so it is inadvisable to merge both without an opportunity to resolve conflicts and ensure proper functionality following the merging of one, assuming both are to be merged.

## Usage Examples
```
mission "whatever"
    landmark "location 1"
        <some location filter>
    landmark "location 2"
        <some other location filter>
    destination landmark "location 2"
    waypoint landmark "location 1"
    npc disable save
        system landmark "location 1"
        ...
    npc
        system landmark "location 1"
```

## Testing Done
It builds and runs! I have not tested further.

### Automated Tests Added
Can probably make an integration test. I'll do that once I've actually tested this.

## Performance Impact
N/A, I hope.

### CODE REVIEW

**Comment by warp-core** [comment]
Drafting because I haven't tested this yet and, on consideration, there are a few things that definitely do need to be tested because I can't even guess how they would work.

**Comment by Amazinite** [comment]
> This will almost certainly conflict with #8029, and even if it does not actually conflict, it probably will be conflicting in terms of logic, and so it is inadvisable to merge both without an opportunity to resolve conflicts and ensure proper functionality following the merging of one, assuming both are to be merged.

Would
```
"not source"
```
just be synonymous with
```
landmark "source"
	...
source landmark "source"
destination
	not landmark "source"
```
?
If yes, I'd say close #8029, since the functionality can be achieved within landmarks. No need to double dip on the same feature if we don't need to.

**Comment by warp-core** [comment]
Not with the current implementation, and I don't really want to pass landmarks into LocationFilters.
The `Mission` doesn't parse the children of the `source`, `destination`, `stopover`, or `waypoint` nodes and `NPC`s don't parse the children of their `system` or `planet` nodes. So, the whole landmark maps would need to be passed to `LocationFilter.PickPlanet()`, which seems excessive, or `LocationFilter` would need to know what mission it is in, and be able to check the landmarks for itself.

I suppose we could alternatively add a separate `CalibrateLandmarks` (or similar) method to `LocationFilter` which `Mission::Instantiate()` would call before it asks the filters for specific planet or systems.

In this case, `source` would likely be a reserved landmark name that always corresponds to the source planet/system, rather than being a user-defined landmark (the source location is known before instantiation, the landmark filters are not evaluated until instantiation.)

**Comment by Amazinite** [comment]
I would like landmarks to be able to be used wherever location filters can be used within a mission (baring landmarks themselves, we don't want an infinite loop). If the source is a hardcoded landmark, then that's just as good as making source able to take a landmark. The main issue we want to fix is the reuse of the same output of the same location filter across multiple location filters, so that's basically just the bare minimum that I'm looking for out of this.

**Comment by warp-core** [comment]
Closing in favour of #8055.

**Pull request closed without merging**
