### PR TITLE
Quyykk fix

### PR DESCRIPTION
**Pull request by RisingLeaf**
quyykk, merge it

### CODE REVIEW

**Comment by warp-core** [comment]
The template exists for a reason.

**Comment by RisingLeaf** [comment]
> The template exists for a reason.

... Yes

**Comment by RisingLeaf** [comment]
sorry

**Comment by RisingLeaf** [comment]
> The template exists for a reason.

fixed

**Comment by warp-core** [comment]
It's not really a bug with the game itself, the closest other option is probably cd/ci/testing, but it's definitely not a mechanic.

**Comment by quyykk** [comment]
we need a buildsystem label?

**Comment by warp-core** [comment]
> we need a buildsystem label?

Apparently.

**Pull request merged**
