### PR TITLE
Creating asteroids that can be mined

### PR DESCRIPTION
**Pull request by Amazinite**
This idea has been on my mind for a while, but recent talk about it has gotten me to actually get around to seeing if I can create it. So here it is.

This pull would add in the ability to mine certain asteroids, not all of them. It includes 4 mining lasers that are built specifically for mining the fragile asteroids and revealing the minerals inside, as well as 3 different jobs that relate to asteroids.

It is not completely done yet, as it still needs images for the 4 mining lasers, and maybe a little bit of balancing out.

To do:
- [ ] Mining laser images and effects

- [x] Uncapturable attribute

### CODE REVIEW

**Comment by toilethinges** [comment]
It would make more sense if the missions came from research planets instead of Syndicate, unless they are for Unknown Material. The fleets don't have governments defined. Titanium is really, although the hardest metal for it's density, not all that great, and is mainly used in alloys with aluminum and in naval infrastructure, due to it's corrosion resistance.

**Comment by Amazinite** [comment]
The fleets don't really need governments as I've set the governments where the fleets spawn. As for making jobs offer outside of Syndicate, that does make sense, but I wonder how common it would really be to have mining operations outside of Syndicate space when the Syndicte probably have a monopoly on the market. I think that the unknown materials mission would actually be the one that would be offered everywhere, as any government would probably want to know what is going on with these strange asteroids?

But I do agree that they could be offered elsewhere as well. I'll change the to offers on the missions tomorrow when I'm on my computer, as editing on a mobile device is really touchy sometimes.

**Comment by Amazinite** [comment]
Ey, that worked.

**Comment by Wrzlprnft** [comment]
Something like this:
old mining laser
for the old mining laser?

**Comment by jafdy** [comment]
With the metallic element images it may be worthwhile putting their chemical name in the corner just to leave no doubt about what it is.
Copper: Cu
Silver: Ag
Iron: Fe
Gold: Au
Titanium: Ti
Uranium: U
Another element you might use is Tungsten (W). It is used in filament lamps.

**Comment by Amazinite** [comment]
@Wrzlprnft that looks great. I'll get the sound effects if you could do the projectile effects. 

@Jafdy I was considering doing something like that. The images I have right now are just some quick things I found, so I might remake them in the future with the abbreviations.

**Comment by Wrzlprnft** [comment]
okidoki. ill post again if i have detailed and postprocessed all 4 images, as well as the projectiles. might need quite a while, though

**Comment by Amazinite** [comment]
@Wrzlprnft Given that MZ is going to try and make a more developed form of mining asteroids for later (check the #992 issue for his response) I'm going to close this and move development to Steam as a plug in until actual asteroid mining is added.

**Pull request closed without merging**
