### PR TITLE
feat(content): Gegno space fleet & minable adjustments

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

## Summary
After working on Corroboration, I've begun to plot out Gegno story and have a basic idea of where things will be going in the near-future. While doing so, I've thought about a few things regarding the area's minables and fleets (and some needed to be properly balanced).

### Minables

A few minable systems were either notably unbalanced or had some freedom to be increased some more. Since the area used to be Rulei space in the distant past, it also makes sense that there is some sort of affect on the minables (outside of some relics that [redacted]) based on population-dense locations or other [redacted].

I've tweaked minables across the map - generally, there are more minables, but the more profitable ones have either been shifted around or cut where there's too many (for example, Fscher). I used human space as a reference, which had a lot more minables than I thought in comparison. In general though, I wanted to match the value in minables, or at least increase it from where it was, since mining is supposed to be important in Gegno space.

Because it's a bit difficult to read the changes in the files, here are before and after images. Red text is the changed areas (NOT deleted - changed). Red dots are mining fleets.

Before:
gegno space mining original

After:
gegno space mining updated

<details>
  <summary>Human space in comparison</summary>

lower human space

</details>

### Fleets

Most fleet changes are based around conquest areas on the map. Because I plan on Gegno fleets to be more fluid and active throughout the duration of the campaign, I've tweaked them based on the initial events (a PR to come) and more importantly tuned down the amount of Scin/Vi fleets being deeper in the others' territory, along with a few changes to some spawn rates.

Before:
gegno space fleets original

After:
gegno space fleets UPDATED

If there are any specific questions or suggestions on any of the changes, feel free to ask. It's worth noting I still plan on doing special larger asteroids for Gegno space, but primarily for systems like Vesvii, which should be the most profitable system based on the rings there.

## Save File
This save file can be used to test these changes: N/A

### CODE REVIEW

**Comment by Saugia** [comment]
> I've been in Gegno space recently and thought the minable rate was slightly high, so I think this would be a good change to make.

In some systems like Fscher they were pretty high, but in many distant ones there were more than needed to be. That said, some have gained even more minables, but the areas where this happens are different. So, there technically are more minables in the area overall, just in locations that make more sense (to me).

(See the human map example - several systems have upwards of 50 - 80 minables, but nothing in Gegno space had that.)

**Review by OcelotWalrus — APPROVED** [review]
Nice balance.

**Comment by Quantumshark** [comment]
Mineable changes look good.

Shouldn't there be Scin fleets in Yerser? That seems like it must be where they go through on the way to Vesvii.
Also, why aren't there Vi and Scin `warfleet` fleets on the way from their settled systems to and from Vesvii?

**Comment by Saugia** [comment]
Mineable changes look good.

>Shouldn't there be Scin fleets in Yerser? That seems like it must be where they go through on the way to Vesvii.

I was trying to avoid fleets in Yerser because of plans south from there that would require the Gegno not frequenting the area's entrance, and I was going to rely off of the fleets that occasionally would follow you in there anyway from the nearby systems with high spawn rates. I could still put fleets there and it'd still make sense I suppose, but only if it's really necessary.

>Also, why aren't there Vi and Scin warfleet fleets on the way from their settled systems to and from Vesvii?

Are fleets like this in FW? I forget. The Navy occupation of FW planets; are there increased FW fleets in nearby systems? I only put them in Vesvii since that's the big war system, and again was relying on representation beyond it being the ones that fly to and from it when the player passes through, but I could add some.

**Comment by Quantumshark** [comment]
> Are fleets like this in FW?

FW isn't really analogous as the FW and Republic have a direct border, rather than being small islands in a sea of empty space like the Vi and Scin. Also, there isn't a distinction made between home fleets and war fleets, so fighting fleets are sort of mixed up with home patrols - `large republic` fleets etc are present both deep in republic space, on the way to the FW, and right on the FW border.
The Mereti/Sestor conflict is geographically more similar, and you can indeed see Mereti fleets travelling through the empty systems of Eshkoshtar and Salipastart on their way to the fighting in Mesuket.

**Comment by Saugia** [comment]
Added warfleets to systems, added a small fleet to Yerser. Here's a visual.
gegno space fleets w warfleets

**Review by Quantumshark — APPROVED** [review]

**Pull request merged**
