### PR TITLE
Fix(content): Remove outfit scanning capabilities from Grey's person ship

### PR DESCRIPTION
**Pull request by mOctave**
**Bug fix (sort of)**

This PR addresses the issue described in discussion #9974, specifically @MasterOfGrey's comment at https://github.com/endless-sky/endless-sky/discussions/9974#discussioncomment-9065672

## Summary
Removed outfit scanning power and efficiency from the Modified Ladybug, to prevent it from doing outfit scans. Kept other scanning attributes.

## Testing Done
None

## Save File
N/A

### CODE REVIEW

**Comment by Hecter94** [comment]
See https://github.com/endless-sky/endless-sky/issues/6747#issuecomment-1103889300

**Review by MasterOfGrey — APPROVED** [review]

**Review by OcelotWalrus — APPROVED** [review]

**Comment by mOctave** [comment]
> See [#6747 (comment)](https://github.com/endless-sky/endless-sky/issues/6747#issuecomment-1103889300)

And yet, the majority of author ships are drastically different from their stock counterparts (if such ships even exist). It's not like the Modified Ladybug has the same stats as the normal one. If Grey doesn't want outfit scanning, is there any reason why it has to be kept?

**Comment by MasterOfGrey** [comment]
The comment Hecter is referring to is actually speaking about the government for Person ships.
As in, there should be no artificial restrictions on what the category of all person ships can do.

It's not pertaining to any specific person ship, and does not negate the case made for this.

**Comment by Saugia** [comment]
I think it's fine we remove these abilities of Grey wants to. If the concern is author ships being able to do so in general, then Hecter's comment makes sense. Pester was intended to scan and do things another ship could, so no problems there. If Grey doesn't think this ship should do the same, we can change it.

**Comment by ziproot** [comment]
The concern was not the scanning. The concern was the fining. I don’t see this as the right solution, especially as MasterOfGrey pointed out that they really wanted to have it scan you and not fine you.

**Comment by MasterOfGrey** [comment]
> The concern was not the scanning. The concern was the fining. I don’t see this as the right solution, especially as MasterOfGrey pointed out that they really wanted to have it scan you and not fine you.

Technically, I said *if* it was to scan you, I'd have it message you instead of fine you.

That is a vastly more complicated change though, for little more than a humorous moment. This change is fine.

**Comment by Hecter94** [comment]
> It's not pertaining to any specific person ship, and does not negate the case made for this.

Yes, if it's just changing the loadout of a single person ship and not placing an artificial restriction on person ships as a whole, this is fine.

**Pull request merged**
