### PR TITLE
Add Mining jobs

### PR DESCRIPTION
**Pull request by tehhowch**
Closes #2449 
Refs #2101 

Given the latest mission/job toolset in https://github.com/endless-sky/endless-sky/commit/11a30e0efc309d67f18d5e7212c81eac89fce8cd, I've updated @EndrosG 's PR to use the automatic shipyard attributes.
I've expanded upon her work and also clarified the file diffs, to simply the pre-merge review needed. To prevent the player from starting a bunch of high-quantity or rush jobs without knowing where to find some of the needed outfits, the player has to complete smaller jobs for a given minable first (which will place a marker for those minables in the player's map file when viewing the map->Outfitter and selecting the minable).

Summary:
 - Mining jobs for
    - Human
    - Hai
    - Coalition
    - Wanderer
 - Shipyard-based Delivery missions

While working on this, I came across a deprecated function declaration, and also determined that any missions that completed based on the ability to gift outfits do not display this dependence visually. Those two issues are rectified in #3075

### CODE REVIEW

**Comment by tehhowch** [comment]
Given the multi-author nature of this PR, I feel it should be merged 'normally' and not via squash-merge, as that would inappropriately label me as the original author of some of EndroG's work.

**Comment by endless-sky** [comment]
I'm a bit worried that adding so many more "large bulk" and "large rush" delivery missions will make them swamp the job list. (And, limiting them to planets with shipyards will concentrate the destinations on a few planets, making those missions even more lucrative compared to others.)

Also, all the formatting changes make this hard to review. I know the existing code isn't totally consistent about this, but I often try to use quotation marks for free-form text to distinguish it from keywords, even if the free-form text is one word (e.g. "Republic"). That's why the government names in the jobs are in quotes.

**Comment by tehhowch** [comment]
I can revert that token quotation change and decimate the `random` condition on the new non-mining jobs. I think @EndrosG was looking to make use of the new keywords she added.

I agree with the bit about the oops-too-lucrative nature of specialized missions which is why I had reduced the mining job rates, and limited their concurrency somewhat.

**Comment by tehhowch** [comment]
"Replace All" was a bit greedy, but normalizes the Escort & Bounty jobs to quote single-word government names in their location filters, along with the rest of the generic jobs.

**Comment by Pointedstick** [comment]
IMHO more flavor jobs is always a huge gain. If there are too many jobs in the list, we should merge this and then just adjust the frequencies down for all the jobs.

**Comment by tehhowch** [comment]
This will also be the first set of missions that use complex/"arbitrary" conditions, so it can't merge until #3128 or an equivalent merges (lest we flood users' consoles with "Unrecognized condition expression" 😁 ).

**Comment by endless-sky** [comment]
I'm still not too enthusiastic about this. First, because mining is enough of a niche activity that it doesn't seem like there need to be special missions for it. And second, because players who do mine will likely prefer to just fill up their holds with the most valuable materials they can mine rather than having to be limited to searching out a particular material.

**Comment by tehhowch** [comment]
I'll add the mining missions into a plugin i develop around mining, drawing other changes for it from #2752

**Pull request closed without merging**
