### PR TITLE
Scrappy Punisher outfit typo

### PR DESCRIPTION
**Pull request by Bladewood**
https://github.com/endless-sky/endless-sky/issues/2043

### CODE REVIEW

**Comment by Bladewood** [comment]
I feel proud.

**Comment by KiLEdEnNis** [comment]
more approves

**Comment by Amazinite** [comment]
Tfw no disapprove

**Comment by DingusShingleton** [comment]
Congrats on getting your [Contributor] tag @Bladewood! Feels good man ;)

**Pull request merged**
