### PR TITLE
xcodeproj fixes

### PR DESCRIPTION
**Pull request by mashers**
Some filenames had been changed in the source folder which had not been updated in the xcodeproj, causing linker errors when building the Mac OS X version. This pull request resolves this issue.

### CODE REVIEW

**Comment by Bladewood** [comment]
touchscreen

what

**Comment by mashers** [comment]
@Bladewood 
I'm adding on-screen controls and will subsequently be attempting to port to OpenGL ES so Endless Sky can run on mobile devices with touch controls.

**Comment by KiLEdEnNis** [comment]
mobile Endless Sky does sound nice...

**Comment by Wrzlprnft** [comment]
i recommend looking at the relevant google group threads for those who haven't

**Comment by Bladewood** [comment]
My point was that this was titled "xcodeproj fixes", not "touchscreen implementation".

**Comment by mashers** [comment]
The pull request was for changes to the xcodeproj. The touch screen controls are subsequent commits.

**Comment by tehhowch** [comment]
standard procedure for pull requests is to make a branch dedicated to the content you want to add, and only push the necessary commits to that branch.

so you should have 3 branches... `master`, `xcodeprj_fixes`, and `add_touch_support`

**Comment by mashers** [comment]
@tehhowch I didn't know that. I'm not very experienced with GitHub. I may as well close this pull request then as the subsequent commits aren't ready to be merged yet.

**Comment by tehhowch** [comment]
I'm relatively new to it as well. I've not had to do it, but there is a way to move some select commits into the branch of your choosing and out of your `master`. Then you should be able to easily rebase/fast-forward your local master with the master branch on this repo (instead of needing to fix conflicts from your personal tweaks every time you want to keep up-to-date with MZ's own additions).

This may be a good start: https://stackoverflow.com/questions/2369426/how-to-move-certain-commits-to-another-branch-in-git

**Comment by Bladewood** [comment]
https://groups.google.com/forum/#!category-topic/endless-sky/general-discussion/EJ-hjHUmQ4c

**Pull request closed without merging**
