### PR TITLE
[Enhancement] Give Unstable Wormholes Red Links

### PR DESCRIPTION
**Pull request by Azure3141**
**Content**

## Summary
Ember Waste wormholes are now red-purple

## Save File
If you don't have a save file where you can visit the Ember Waste, I am sorry for you.

### CODE REVIEW

**Review by GefullteTaubenbrust2 — APPROVED** [review]
Not much to complain about here, I like.

**Review by RisingLeaf — COMMENTED** [review]
I like it, it makes the one stable wormhole more special

**Comment by Amazinite** [comment]
Could the color be a bit brighter, or perhaps a bit closer in color to the wormholes themselves? This color doesn't really look red to me, more like a dark purple-ish color, which is a somewhat difficult to spot at a glance on some parts of the map.

**Comment by EjoThims** [comment]
Yea, this is solidly magenta to me. Something more in line with the wormholes are EW haze, more in that "danger red" type band would probably be better.

**Comment by Amazinite** [comment]
That still seems a bit too dark to me. Try to match the brightness of the existing color.
image

**Comment by EjoThims** [comment]
I think the zoomed out looks great, brightness wise, just still  too much to the pink side.

Can we get shots of the most recent color brightened both in close and zoomed? Unless in the direct comparison there's some noticeable issue that stands, I think that'd probably be good to go.

**Review by Zitchas — APPROVED** [review]
Based on trying this out in-game, a few thoughts.

- I like having the unstable wormholes be a different color.

- The current color seems a bit pink to me, but I'm not really sure how to get a redish-purple color that looks good on such a thin line. (I've tried a bunch of different colors, and it's hard to get something to look good.)

- All in all, I think the proposed color here looks OK, and it is definitely good to have the color be different from the standard purple.

**Review by EjoThims — APPROVED** [review]
Really do think the subtle difference here leans a lot more into indicating them as dangerous than the previous, which is what I wanted from the redder color. :)

**Comment by Zitchas** [comment]
That looks good to me too.

**Comment by warp-core** [comment]
Should the Barren wormholes have an even more different colour?

**Comment by warp-core** [comment]
> By that do you mean the ones that show up with Postverta?

Yes

**Comment by Zitchas** [comment]
Sorry. Yes, those ones should just match the rest of the Ember Waste for now.

**Pull request merged**
