### PR TITLE
Minor text adjustment for landing on Hephaestus

### PR DESCRIPTION
**Pull request by wkoot**
Minor text adjustment for landing on Hephaestus, during mission "FW Pug 4"

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm not sure if these changes are needed. Also, "working hard to address" was already correct; "working hard on to address" is not.

**Comment by Thunderforge** [comment]
I'm on the fence with this commit. Although it's a slight improvement in terms of sentence structure, I feel like there was nothing particularly wrong with the original phrasing. Of course, it would need to have the "working hard on to address" fixed if it were to be committed.

**Comment by wkoot** [comment]
Missed that one! I actually didn't know where to go with the wording and put something temporary there. Should correct that

**Comment by egilburg** [comment]
"private hangars for Syndicated Systems" is grammatically incorrect, "Syndicated Systems private hangars" is the correct way to express this. 

I agree the other changes are more of a question of taste rather than fixes.

**Comment by endless-sky** [comment]
It's actually not grammatically incorrect as it is: you could have a "private booth for Microsoft" at a trade show, say, or a "secret backdoor for Apple." In this case "Syndicated Systems" is an entity that can have its own private hangar if it wants. :)

**Pull request closed without merging**
