### PR TITLE
Added the very first mission of the Syndicate Storyline

### PR DESCRIPTION
**Pull request by Disiuze**

### CODE REVIEW

**Comment by Disiuze** [comment]
uh oh, something went wrong. Ignore this.

**Comment by Alkallid** [comment]
Oh wait someone's already working on this?

**Comment by Disiuze** [comment]
@Alkallid Me and Matthew are working on it....
In the meantime, YOU NEVER SAW ANYTHING

**Comment by Alkallid** [comment]
*Copies into personal doc and repo*
fite me

**Comment by Gkramme** [comment]
Vlad and I

**Pull request closed without merging**
