### PR TITLE
Update grammar in free worlds intro.txt

### PR DESCRIPTION
**Pull request by unjown**
NOTICE: Delete the sections that do not apply to your PR, and fill out the section that does.
(You can open a PR to add or improve a section, if you find them lacking!) 

----------------------
**Content (Artwork / Missions / Jobs)**
FW Recon 2 mission

  
  

## Fix Details
{{the mission requires you to scan all the selected ships not any.}}

## Performance Impact
{{describe any performance impact (positive or negative). "N/A" if no performance-critical code is changed. }}

N/A

### CODE REVIEW

**Review by MCOfficer — COMMENTED** [review]
So... Why the change? How is this better?

**Comment by tehhowch** [comment]
It's already qualified:

"Scan any ships _that look like 'X'_"

"Any," "all," and "the" are each substitutable without changing the meaning of the sentence, at least to native speakers.

A more formal statement would likely be "Scan all the ..." but this also indicates that the will be more than one, when you are doing reconnaissance and thus _shouldn't be hinted how many there are_.

**Comment by unjown** [comment]
> It's already qualified:
> 
> "Scan any ships _that look like 'X'_"
> 
> "Any," "all," and "the" are each substitutable without changing the meaning of the sentence, at least to native speakers.
> 
> A more formal statement would likely be "Scan all the ..." but this also indicates that the will be more than one, when you are doing reconnaissance and thus _shouldn't be hinted how many there are_.

when you say any.. means literally any amount. mine is more proper

**Comment by Anarchist2** [comment]
You'd be right if the text said "Scan any ship", but the use of "Scan any ship**s**" carries the implication that you will have to scan all the ships that fit that description, as indicated by the plural.

**Comment by unjown** [comment]
scan any ships can also mean any value less or more than the intended... scan the ships is with a certain value but unknown

**Comment by Amazinite** [comment]
Closing as this is not a fix or improvement.

**Pull request closed without merging**
