### PR TITLE
draw icon background separate from icons

### PR DESCRIPTION
**Pull request by comnom**
refs: https://github.com/endless-sky/endless-sky/issues/3428

I took the simplest code change possible and went with icon + halo with a separate "icon background" sprite.

Ran into a couple snags with the gat icon and rail slug icon, which had an ugly border that was hidden by the background.

Also took the liberty of standardizing the alignment and making sure all icons fit within their "bounding box" (the background), as the typhoon 1x was aligned this way, but wasn't in the 2x, and the tracker had it's own 45 degree-ish alignment going on, so I hope that's ok.

Summary:
* Draw the background separate from the icon in Engine.cpp
* New icon set with transparent backgrounds
* Reworked gat and rail icons to get rid of the border
* Aligned several icons that were outliers
* Scaled several icons that broke their bounding box

So more than I wanted to do really, but the icons now have a standard orientation (within a pixel) and size (rough margin of 1-2px from the bounding box).

I moved the gat and rail into the xcf with the others which is here:
[icon.zip](https://github.com/endless-sky/endless-sky/files/3041189/icon.zip)

### CODE REVIEW

**Comment by tehhowch** [comment]
@comnom what's your stance on updating the copyright files for the reworked icons?

**Review by tehhowch — DISMISSED** [review]

**Comment by comnom** [comment]
>what's your stance on updating the copyright files for the reworked icons?

Not necessary. All I did was re-render from existing models with a slight color touch-up to get a clean image to use.

I'd like to hold off on this being merged as is, as I was hoping to get some feedback from @endless-sky . Specifically, the goal of the PR is easier modding, and that's actually better served by icons without the "halo" we discussed in the [issue](https://github.com/endless-sky/endless-sky/issues/3428).

I didn't make that change because it alters the design (rather than splitting the existing design into two parts), and I wasn't comfortable doing so without feedback. Then I kinda totally forgot about it, so I never requested feedback ;) .

**Comment by Pointedstick** [comment]
Is there a High DPI PR that goes with this?

**Comment by comnom** [comment]
>Is there a High DPI PR that goes with this?

Not yet. I was still just adding the 2x to the main post for the dev to handle when I initially did this. When I'm satisfied, I'll be sure to put one up.

I'm still arguing with myself about doing a set without the halo/drop shadow, as the current implementation only allows changing the color without doing an icon set, but you have to do a whole set to change the shape (ex: https://github.com/comnom/es-huds/blob/master/pug-hud/images/icon/finisher%402x.png).

I've been meaning to look through the assets to see if there's a good case for writing a "drop shadow" shader (nice for highlighting buttons and such without needing a separate asset, as well as plain artsy stuff like we have here), but I just haven't gotten around to it.

**Comment by comnom** [comment]
>I've been meaning to look through the assets to see if there's a good case for writing a "drop shadow" shader...

There isn't. Only three sprites are used solely for selection highlighting. I don't want to change the design either, so I'm satisfied.

High dpi: https://github.com/endless-sky/endless-sky-high-dpi/pull/74

**Comment by petervdmeer** [comment]
Both Amazinite and Tehhowch already approved this PR, but it is no longer ready for merging due to a merge-conflict in the code and due to 3 weapons being added in the meantime (dragonflame, mhd and shard) for which the icons would likely also need to be changed to a transparent background (both in this PR as well as in the high-DPI PR). Adding "Waiting on OP" label.

**Comment by petervdmeer** [comment]
Both Amazinite and Tehhowch already approved this PR, but it is no longer ready for merging due to a merge-conflict in the code and due to 3 weapons being added in the meantime (dragonflame, mhd and shard) for which the icons would likely also need to be changed to a transparent background (both in this PR as well as in the high-DPI PR). Adding "Waiting on OP" label.

**Comment by Amazinite** [comment]
Closing all PRs which have been marked "orphaned."

**Pull request closed without merging**
