### PR TITLE
Clear Outfit description before loading

### PR DESCRIPTION
**Pull request by vitalchip**
NOTICE: Delete the sections that do not apply to your PR, and fill out the section that does.
(You can open a PR to add or improve a section, if you find them lacking!) 

This PR addresses an issue raised by Becca on Discord, when a plugin creator makes an outfit to replace one in the regular game, both outfit descriptions appear in the Outfitter.

Single line code change to clear the description string before loading.
  
  
-----------------------

## Testing Done
Created multiple outfits with same name, each with multi paragraph descriptions. Only the last loaded outfit description displays now as opposed to all descriptions appended.

-----------------------

## Performance Impact
No performance issues

### CODE REVIEW

**Comment by vitalchip** [comment]
Made a mess of it. First PR..

**Comment by vitalchip** [comment]
Re-opening, made some further checks, looks OK. Some extra commits in my Master for some reason but no actual change to base code..

**Comment by Amazinite** [comment]
This only addresses part of #1764. It's more than just descriptions that get added together when a plugin outfit attempts to override an existing outfit.

This is also basically a duplicate of #4489, which does allow the explicit overriding of existing outfits (which includes the clearing of the description).

**Comment by vitalchip** [comment]
Should we just close this one and let one of the prior PRs run it's course for a more complete solution?

**Comment by Amazinite** [comment]
Yeah.

**Pull request closed without merging**
