### PR TITLE
refactor(data): Organizing un-sorted files in the data folder

### PR DESCRIPTION
**Pull request by Zitchas**
**Feature:** This organizes the uncategorized files in the data folder to provide a bit more context and information to new developers, as well as make things tidier and easier to navigate for veterans such as myself.

## Feature Details
Moved into the `_ui` folder:
- categories, 
- conversations, 
- help, 
- interfaces, 
- ratings, and 
- tooltips 
These all pertain to text presented by the game within the interface and game-controlled elements such as tooltips or warnings. This provides additional clarity by providing context to the file names. For example "conversations" while technically being conversations, are actually not conversations but rather the text for warning dialogs about problems with the player's ships. _ui/conversations.txt hints to the developer that this contains text that is used in an interface capacity and are not, for instance, generic conversations used in missions.

Moved into the `_general` folder:
- dialog phrases, 
- effects, 
- governments, 
- persons, and 
- start 
These are in the general folder, as they are actual in-game content that is of a general or support nature. They aren't particularly belonging to a single faction/region, but are all content that the player is going to see in-game.

Moved into the `human` folder:
- intro missions 
This is a human mission chain, quite simply. Starts in other areas are going to need new intro missions, if they choose to have them at all, and given that this mission set is all about introducing the player to their chosen ship, basic game concepts, and an intro to human space; it's basically entirely unsuitable for use anywhere else.

## Related PR:
#5041 
This PR is fully compataible with #5041 as it does not touch any of the files used in that PR, and ideally both would be merged. However, in the even that putting the map files in their own folder is vetoed, this PR achieves the same end from the other direction by isolating all the files that should be in a map folder on the root level of data, and moving all the rest of the files into their own subfolders. This is a less satisfactory, but acceptable.

# Thanks:
Thanks to warp-core for having suggested these groupings in the #5041 comments. I haven't followed their precise suggestions in their entirety, but I feel I should credit them with the idea.
> If we are to move the files not currently in a subfolder into subfolders, why not also move some of the others? Tooltips, ratings, interfaces, and help could all go into a UI folder (arguably also where landing messages should go). Dialog phrases and conversations could go to a "generic text" folder (another place landing messages would fit, and I can see some potential reasons why commodities would also fit).

They have also provided a prime example of the confusion the current lack of folder structure has generated: In this case, the fact that despite its name, the conversations file actually has no generic conversations within it. That's exactly what I thought it had too, but it doesn't. If this trips up an experienced developer who is *very* familiar with Endless Sky's data, how can we expect a newcomer to *not* be confused?

### CODE REVIEW

**Comment by Zireael07** [comment]
Agreed that conversations.txt not being conversations is *Still* confusing.

**Comment by Zitchas** [comment]
> I'm not sure that moving the file to a folder named `_ui` is actually going to resolve this. It probably just makes it worse. "Why is the file called 'conversations.txt' in the '_ui' folder?" I would suggest instead renaming it to "flight check conversations.txt" or similar.

Sure, I could rename it. That being said, I find it odd that you find that worse. Doesn't "ui/conversations" suggest larger blocks of text used by the ui?

> 
> I note you didn't mention the fact that I suggested the landing messages file would fit well into either of the other folders I theorised, which demonstrates that splitting the files up like this, at best, a subjective improvement.

Amazinite specifically suggested landing messages as something that could go along with the map stuff. It's specifically about the map. Note that I gave you credit for the idea and very specifically stated I didn't follow all your suggestions. 

> 
> Your "general" folder... The title suggests to me that the thought process behind it was: "Now, there's all these other files, and I can't figure out what links them, but I want to put them in a folder anyway, so I'll call it 'general'." You seem to have put them together for hte sake of having folders, not because it actually improves anything. Indeed, your explanation just seems to give a definition of `general` and assert that it applies to all of these files.

That is, in fact, a useful way of gathering files together. `Not ui + not map + not faction = general`. This PR has two points:
a) to organize the rest of the files, and 
b) to isolate the map files
Grouping all the files that do not belong in the other three folder types is a perfectly valid way of organizing them and making them easier to find.

> 
> I'm curious as to why you've put the `start` file in here when it seems like your reasoning for moving the `intro missions` file would seem to directly contradict it. The `start` file currently only contains one start, _the_ start, the start that is intended to lead directly into the intro missions, and from which they are designed to lead on.

I assume (I know, dangerous) that the start file is, at some point, going to contain more starts. If content creators decide to put each start in their own faction folder instead of in the general "start" file, then yes, this should be moved into the `human` folder. The intent seems to be for it to be a general file, not a specific one, but this is subject to change.

> 
> The dialog phrases are largely quite generic, every single one even begins with `generic` (though, someone might argue that they really only apply to humans, at least in some cases,) but governments are most certainly not generic. They are grouped together, I expect, because the most important part of a government definition is its relationship with other governments and the player.

Like the starts, the intent seems to be for these to be general. If we want to split it up and put each factions in their own faction folder, then sure, that'd be appropriate. Until then, however, it's a general purpose thing.

> 
> The effects, much like the dialog phrases, are in many cases quite generic, used by content associated with many of the in game factions (though, the Pug and Remnant specific ones should perhaps be moved to those folders).
> 
> I'm going to stop here for now, Overall, I think you're just doing this for the sake of it, without much actual thought put into how things should be arranged or if there is actually any benefit to rearranging things. I believe the word is "churn."

Believe it or not, I don't change things just for the sake of changing things. I've long been annoyed at the mess in the data folder (hence the other PR that I started this with being 5041). We either clean it up, or it gets worse. We're at a point where it is about to get worse, so I'm trying to change this change-over point to one where things actually *improve.*

**Comment by 1010todd** [comment]
I have a feel we might not want to categorize just everything, I recall first time I looked into data folder and immediately see simple .txt files everywhere gives me a feeling of ease, like "oh I just pile everything in here and not worry about folder structure." (same with source folder as well) then I could start looking into things modding it right away. Opening data folder and seeing just more folder might be slightly more intimidating to beginners. Yes in our case it's only one folder away but it's about feeling and once you opened a folder and see more folder your mind may already entered another mode and after that it's more "Thank god it ends here.". This might be just me because before ES I've tried looking into data of other games before and seeing rows and stacks or folders can be a little scary while ES just shoving easy-to-edit plain text in my face immediately is actually encouraging. 

So over all I feel like we could leave a few random things outside the categories just so it feels better. If I were to give some example maybe everything in `_general` could be left outside.

Anyway this is just some random pure emotional viewpoint from a random creator recalling stuffs from over half decades ago.

**Comment by Zireael07** [comment]
> Not ui + not map + not faction = general

In that case, imho they should just stay in the root data folder

> Doesn't "ui/conversations" suggest larger blocks of text used by the ui?

No, it suggests some conversations used in the UI or something, and my first thought is why these aren't where other conversations (hails/missions) are?

**Comment by Zitchas** [comment]
That's a good point. If #5041 is merged, I'd be quite happy to pull the "general" stuff out of the folder so there's a bunch of general stuff at the root level. That being said, right now this PR is presented as also being an alternative to 5041. In which case just this PR would be merged, and thus the root would have all the map-related files sitting there.

**Comment by Zireael07** [comment]
I don't think these are alternatives, I think this and 5041 complement each other

**Comment by Zitchas** [comment]
Thank you, they were intended to. But they are also alternatives, so kind of dual-purpose. Would be better to merge together, but either one separately would work too.

**Comment by quyykk** [comment]
I'm not sure I like the `_` prefix for the folders. Why did you choose to include it?

**Comment by Zitchas** [comment]
Just to try it out.
- See if it broke any checks
- See how it looked in practice
- See what anyone else thought of it.

I'm ambivalent towards it. All things being equal, I'd just as soon leave it off. But some people seem to feel that the non-faction folders should be separated from the faction ones somehow, and an underscore does effectively differentiate them.

It is far from being the only way of doing so, though. Other options include:
- appending something on the front of faction names (ex. "f_factionnamehere" or "faction_factionnamehere")
- adding another layer of folders (ex. group all the factions folders into a faction folder.

**Review by Amazinite — CHANGES_REQUESTED** [review]
+1 on moving intro missions to the human folder. I think we should have a single start file for all starts, but the intros for each start should be in a file for the associated faction.
+1 on the UI folder. Also fine with the underscore in the name.
+1 on the deprecated folder. Should we perhaps add an underscore to the name as well?
-1 on the general folder. I don't think the rationale behind what's in the folder checks out.
-1 on renaming conversations to warning messages. I'd rename to "flight checks.txt" instead so that it's more clear from the file name what it contains, as I don't imagine us ever adding new things that would constitute a generic warning message that isn't a flight check.
-1 on moving categories into the UI folder. Categories are a content thing, not strictly a UI thing like help or interfaces or tooltips or flight checks are. I could also see landing messages being put into the UI folder.

There are 22 files in the data folder which aren't in subfolders. With the above suggestions, that number would be reduced to 13.

**Comment by Zitchas** [comment]
- [ ] underscore for deprecated
- [ ] removing general
- [ ] renaming warnings to flight checks
- [ ] unmove categories into the UI folder.
- [ ] landing messages to the UI folder.

**Pull request merged**
