### PR TITLE
Content: Modified Leviathan and Falcon

### PR DESCRIPTION
**Pull request by LocalGod79**
six ships in all, mild tweak.  “purchase” is in death benefits, and balance point is
availability - only through high combat rating bounty hunting/hunted
jobs/mission.  better variants spawn less frequently.

### CODE REVIEW

**Comment by LocalGod79** [comment]
high-dpi images are also available below.

@endless-sky .blend have been forwarded to your gmail.

[https://drive.google.com/folderview?id=0B92_vuqiHabWRXRSdldNdDhwQzA&usp=sharing](url)

**Comment by LocalGod79** [comment]
#505

**Comment by jmhorjus** [comment]
Very nice! Going to pull this myself and play with it on - will report any issues.

**Comment by endless-sky** [comment]
It's likely that future story lines will let you land on all the Wanderer missions, so rather than using one of their worlds as the destination and counting on the player never being able to land there, you should do this:

```
    to complete
        never
    npc kill
        ...
```

Also, like the other missions, that one should probably also be limited to human source planets.

The required combat ratings might be a bit too high; someone who has played through the main plot will probably be in the 4000 to 8000 range, so 60,000 will only be achieved by people who spend a ton of time grinding after they've already played through everything the current plot offers.

Other than that, though, I really like the idea of the new variants! I'm just worried that putting the combat rating so high means that most people will never see them.

**Comment by LocalGod79** [comment]
thanks for the feedback!

will make some adjustments and re-pull soon.

**Comment by LocalGod79** [comment]
i left the hunted npc save as is, so that the player is not carrying active completed missions (npc kill) until they happen to land at Earth - it was only intended to very occasionally spawn the fleets to provide added availability of the upper tier variants if the player had gotten to a 'worthy' combat rating, and wanted to capture them.

**Comment by LocalGod79** [comment]
i think we're all eager to get to work on more ships for this lineup.

@endless-sky did you have any favourites for future modified models?

i was thinking a light medium-warship armed star queen like british q-ships from wwII (though the sprite detail on this one needs to be *really* subtle, if anything at all) might be a little fun...all of a sudden, several bulkheads retract, revealing that the 'Yacht Royale' is not a pleasure cruise, and actually carries several Plasma Turrets...looks like you picked the wrong (or right!) Star Queen to attack, today...

smaller modified warships would be available through jobs at combat ratings between the current "Bounty Hunting (Big)"@500 and the adjusted 3000-8000 for the Falcons and Leviathans.

**Comment by Wrzlprnft** [comment]
If anyone wants to help further development of the variants, [this google forum thread](https://groups.google.com/forum/#!category-topic/endless-sky/tpsrXEaCvA8) is the origin of them.

**Pull request merged**
