### PR TITLE
Lots of haze

### PR DESCRIPTION
**Pull request by TheUnfetteredOne**
Looking at a black and blue background with a bunch of white dots all over the place gets boring.
Looking at that awesome red background in Remnant space is cool. 
I thought it would be cool to make haze for other areas of space, so I did it. :3

Here are some previews.
Wanderer space:
wanderer haze
Unfettered space:
unfettered haze
Coalition space:
coalition haze
Korath space (both around the core and in their home territory):
korath haze
Hai space:
hai haze

### CODE REVIEW

**Comment by Elyssaen** [comment]
This does look _really_ cool, and I appreciate your aesthetic point, but the realism side really bothers me. To me haze should be a property of a region of space – whatever relation it has to real-life nebulae, that shouldn't change. But what you've got here is haze as a property of a culture. 

What's the explanation for it? Why isn't Wanderer space Hai-haze, and what happens when the Unfettered recapture some of it? Does Korath space turn Wanderer-haze when they go through the Eye?

**Comment by TheUnfetteredOne** [comment]
> Why isn't Wanderer space Hai-haze, and what happens when the Unfettered recapture some of it? Does Korath space turn Wanderer-haze when they go through the Eye?

Because Wanderer space is a different cluster of systems, and the haze doesn't change if the government does.

**Comment by Elyssaen** [comment]
That might makes sense, but it then raises the question of why the hazes happen to coincide with current borders. Isn't it an enormous coincidence that this property-of-space effect coincides with legal borders in the year 3015-ish?

It also has the effect of taking away the uniqueness of the Ember Waste. Right now the Ember Waste is _striking_. If every region of space had this effect, first visiting the Ember Waste would lose a lot of the impact it just had on me this evening.

**Comment by TheUnfetteredOne** [comment]
>Isn't it an enormous coincidence that this property-of-space effect coincides with legal borders in the year 3015-ish?

If it were a "legal borders" thing then different regions of human space would have different haze. 
I could just as easily say that isn't it a coincidence that there are borders at all? Oh wait, Drak. :3

>It also has the effect of taking away the uniqueness of the Ember Waste.

And other regions of space shouldn't be unique? To this point, I would be willing to take the special haze out of Hai systems since those are the easiest to reach, but I think it makes sense to have the haze in the other regions.

**Comment by Elyssaen** [comment]
> If it were a "legal borders" thing then different regions of human space would have different haze.
> I could just as easily say that isn't it a coincidence that there are borders at all? Oh wait, Drak.

I don't think I understand where you're coming from here. Your PR would set up a galaxy where species just so happen to live in colour-coded regions of space, without stepping one system out of them, but only if you look in the year 3015, as some of them did indeed step out of them before and will after. That it doesn't apply to humans doesn't change how _odd_ that is, does it?

> And other regions of space shouldn't be unique? To this point, I would be willing to take the special haze out of Hai systems since those are the easiest to reach, but I think it makes sense to have the haze in the other regions.

They shouldn't _necessarily_ be unique, but even if they should, a palette swap of the Ember Waste isn't really unique.

Also, the Ember Waste has an unusually large number of dead stars, I think? With that, the haze, and the red wormholes, I think we're looking at a _very_ interesting region, and one that's supposed to look it.

**Comment by TheUnfetteredOne** [comment]
You really seem like you're overthinking this. :/

**Comment by Bladewood** [comment]
just to note, Wanderer space was originally Hai space (or at least that's what the Unfettered claim). So it should share the Hai haze, which is what I believe @Elyssaen was trying to say.

**Comment by endless-sky** [comment]
Because this is an exploration game, one of my core principles is that the cooler a thing is, the harder you should have to look for it. That's why the special star types, etc. are so rare.

Think of it this way. Which of these options is better?

1. By the time they've explored 25% of the galaxy, a player has seen nearly everything the engine is capable of. Nothing after that really surprises them.

2. As the player keeps exploring new parts of the galaxy, they keep discovering new things that are unique to that region.

As others have said, I think that having different haze backgrounds all over the place would detract from the enjoyment of entering the Ember Waste and saying, "Whoa, I didn't even know that was possible."

**Comment by TheUnfetteredOne** [comment]
Alright

**Pull request closed without merging**
