### PR TITLE
add indicator for spaceport missions

### PR DESCRIPTION
**Pull request by MarcelineVQ**
Added an indicator to hint to the player when checking the spaceport will trigger a mission.
It's very easy to land on a planet and not check the spaceport. It's especially easy to not even know you need to check the spaceport. When you miss the opportunity to do this for a randomly given mission you have to wait until it hits the right random number again.
This seemed like a useful addition to alleviate some possible player frustration, I personally ran into the issue trying to start the freeworlds intros and get the story rolling because they rely on randomness and checking the spaceport panel.

alert

### CODE REVIEW

**Comment by nylki** [comment]
I like this idea. As a side note: It might be useful to think of additional game mechanics that can only be performed in the SpacePort (besides starting mission/storyline), in order to get the player actually clicking the spaceport.

**Comment by endless-sky** [comment]
Given how many of the spaceport missions are presented as something that happens to the player by surprise ("As you're wandering through the spaceport, you run into...") I feel like giving you a forewarning that you're going to have an unexpected encounter in the spaceport is a little odd.

**Comment by Pointedstick** [comment]
What's needed instead of this is more of a reason to go into the spaceport bar other than the chance to get a mission. EV had news, gambling, and escort hiring.

**Comment by nylki** [comment]
@Pointedstick I liked those little gambling videos in EVN. :)

A very far-fetched idea, which is probably not feasible to implement (because it requires a remote database), would be if you could actually chat in a planets space port with other Endless Sky players, or see posts/notes they left behind. That would give it a meaningful incentive to visit regularily to see new messages.

Or it could be host to some trade-tips. As the tradesystem is dynamic now, some trade routes may become more lucrative in the future (which could be calculated or atleast  guessed in the game engine) and then be posted as news messages.

**Comment by mdsmestad** [comment]
@Pointedstick Thats true, space port could have more features to give incentive.

**Comment by toilethinges** [comment]
I click on spaceport everywhere I go, just to read the description. :)

**Comment by KiLEdEnNis** [comment]
never saw this issue, but I love it o:

**Comment by KevinKorzekwa** [comment]
Really sad this is closed, it would reduce so much frustration as I play through missions.

**Comment by Pointedstick** [comment]
@KiLEdEnNis: #1552

**Comment by KiLEdEnNis** [comment]
@Pointedstick yeah I know by now lol

**Pull request closed without merging**
