### PR TITLE
[Content]Battery Buff

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
Basically, batteries are too weak, and in virtually every circumstance if one has a fixed amount of space to devote to power, it is better to spend that space on a generator than on a battery. Batteries don't even have the capacity to last appreciable lengths of time, either.

So, this is a buff to batteries, with the goal of making them more useful, and lead to the addition of more ships (including stock ships used by NPCs and random fleets) that actually run on pure-battery builds.

Changes:
- Energy capacities have been increased to 4x their current energy density.
- All human, hai, and coalition batteries have their cost halved.
- System cores, which are batteries + other significant abilities had their energy capacity doubled, but are otherwise unchanged.
- In order to "solve" the problem of supercapacitors being the only "stackably useful" size 1 outfits, the KP-6 solar panel has also been dropped to size 1. So people now have both something they can put in a small space, something that's useful for small ships, *and* have choice, so there's isn't a "always take this thing" situation.
- Supercapacitors and Chasms have been buffed slightly, the former so they are approaching (but not reaching) LP036a densities, and the latter so they are between the LP036a and LP072a densities instead of just below the LP036a.

Notes:
- Things that happen to have energy capacity but aren't primarily batteries (Wanderer reactors, various weapons, etc.) are NOT changed.
- The Sheragi batteries are kind of like really weak system cores. As they aren't purchaseable I just treated them like pure batteries, but will need to check how powerful that makes their regen stats. Might need to treat them like system cores instead of like batteries, but we'll see how they feel.

Effectively, this means batteries are 4x more energy dense than they used to be. Which is a far cry from some of the alternatives proposed, but I think it is a good place to start.

## Alternatives
On the discord we've had several discussions about batteries recently, fueled in part by the efforts to make the code support [battery-only fighters](https://github.com/endless-sky/endless-sky/pull/6726). I would like to acknowledge here that these changes are definitely on the conservative side of the proposed suggestions. Some of these proposals included:
- Giving all batteries 10x energy capacity.
- Larger reductions in size
- Significant nerfs to generators (I've heard talk of everything from 10% to 90% reduction in generator output either alone or in combination with increases to heat production)

While there is definitely merit in considering some of these more extreme measures; I prefer to buff the thing that is weak rather than nerf everything else. I also felt that more extreme measures might have other unintended ripple effects, such as rendering ion virtually worthless. 

## Problem
The one big problem is Ion damage. Bigger batteries means ion becomes weaker. It's already not very significant, and ships that make heavy use of batteries become that much less affected by ion. 
- Note, with Derpy's Ion buff, this becomes a moot point. Ions have their own thing, and aren't just pathetic wannabe heat damage.

## Save File
This save file can be used to play through the new mission content:
Any pilot file can be used to test this. Batteries are among the least-restricted things in the game.

## Artwork Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by Amazinite** [comment]
Not a fan of cutting the sizes in half. Smaller batteries aren't exactly that difficult to install as is, and so we don't need to make them any easier to install. The supercapacitor in particular should not be a 1 ton outfit. Size is only really a concern for the absurdly large batteries, so as in #6686 where I reduced the size of the more absurdly large engines in human space, I'd rather just reduce the size of the absurdly large batteries as opposed to blanket buffing all batteries.

I'm also not so sure about blanket buffing all battery outfits aside from those weapons which had slight battery capabilities. Right now once it comes to T2 tech, dedicated batteries can basically be outright ignored in favor of Wanderer generators and System Cores which have decent amounts of energy capacity capabilities baked in. In all energy capacities are buffed to the same degree, the relative positions between those T2 outfits and dedicated batteries won't change. So I think a larger buff to dedicated batteries relative to integrated ones is in order.

How do the values on the second page of my [energy capacity spreadsheet](https://docs.google.com/spreadsheets/d/1Xwzho6CNc8gA0UmUja3MBiaxSN5KdanmNAr01NPKggU/edit?usp=sharing) look? 1.5x energy capacity for integrated batteries, 3x for dedicated batteries, and a change to the size ramping on human and Hai batteries to be plus some outfit space over the previous size for the larger sizes as opposed to two times the outfit space of the previous size.

**Comment by Zitchas** [comment]
> Not a fan of cutting the sizes in half. Smaller batteries aren't exactly that difficult to install as is, and so we don't need to make them any easier to install. The supercapacitor in particular should not be a 1 ton outfit.

Why not? It's a capacitor. It does barely anything, and is basically just an weapon clip-on so that ships that otherwise don't have energy capacity can fire some weapons. I know MZ expressed some dislike of having *anything* be 1 ton; but we've already got keystones; and there's talk of having a whole bunch of various 1 size outfits. Just like there's nothing special about filling up *all* the space on a ship, there's nothing special about explicitly preventing people from doing so either. 

If I recall correctly, the bulk of MZ's argument was that having 1 space left over is pretty common, and he didn't want there to be an outfit that everyone installed because "well, it's the only 1 ton outfit and I've got 1 space left, might as well throw it in to fill things out." The solution to this isn't ban 1 ton outfits, its ensure that there's enough options out there people have *choice,* so there's no single goto option. 

> Right now once it comes to T2 tech, dedicated batteries can basically be outright ignored in favor of Wanderer generators and System Cores which have decent amounts of energy capacity capabilities baked in. In all energy capacities are buffed to the same degree, the relative positions between those T2 outfits and dedicated batteries won't change. So I think a larger buff to dedicated batteries relative to integrated ones is in order.

This is why they're *not* all buffed to the same degree.
1. Only Batteries got the 4x energy density.
2. System cores only got 2x energy capacity (no size reduction)
3. Wanderer Generators didn't get touched at all.

So this PR makes batteries more competitive vs Wanderer generators. I'm personally probably still going to pick a wanderer generator over a battery most of the time; but this reduction at least makes it something that I'd have to think about. Are you arguing that batteries need a bigger buff than the effective 4x they are getting here?

> How do the values on the second page of my [energy capacity spreadsheet](https://docs.google.com/spreadsheets/d/1Xwzho6CNc8gA0UmUja3MBiaxSN5KdanmNAr01NPKggU/edit?usp=sharing) look? Highlighted values are those that have changed: 1.5x energy capacity for integrated batteries, 3x for dedicated batteries, and a change to the size ramping on human and Hai batteries to be plus some outfit space over the previous size for the larger sizes as opposed to two times the outfit space of the previous size.

a. I'd say leave the wanderer reactors alone. They're already the goto reactors, they don't need any buffing.
b. It's... different. Not sure what I think of the alternate values, overall.

One of the big reasons I dropped the size of batteries is because of what they're competing against. We're not comparing how good this battery is with that battery, we're comparing this battery versus that generator. In other words, this high capacity but ultimately limited thing (when the battery runs out, that's it. No more power, ever) versus something with infinite power, forever. 

For example, comparing one of the smaller battery packs (the LP036a) versus the nGVF-BB Fuel Cell. 

(these are current vanilla values)
LP036a : 1000 energy at 10 tons
LP072a: 2200 energy at 20 tons
nGVF-AA : 72 energy per second at 30 tons.

Using my stock shuttle as a case in point: Stock, it uses 102 energy per second to move, and 12 for shields. So, that means my stock shuttle can literally recharge shields while doing a constant full thrust, for ever, infinitely. 

If I have an LP036a + LP072a (30 tons worth of human battery), that gives 3200 energy. My stock shuttle will completely exhaust that in 28 seconds. 

Is there *anyone* that is going to opt for the 30 tons of battery instead of the 30 tons of fuel cell?

Now, with the values in this PR, the fuel cell doesn't change, but 30 tons of battery is a LP144a+LP072a, which gives 14400 energy; which the stock shuttle will take 123 seconds to burn through. 

So, generator for infinite flight vs pair of batteries for 123 seconds of flight? That's actually long enough to start considering. Maybe I could ditch the smaller battery and install a KP-6 solar panel. I could even install a pair of small radar jammers alongside it! Suddenly there's actually options, and we can start discussing doing something with the shuttle. There's still risks involved, and doing much is going to run into dead  batteries and having to wait for solar to recharge it now and then, but this could actually add some solid possibilities of having *fun* outfitting small ships instead of the main purpose of small ships being "get out of it into something bigger."

**Comment by Terin** [comment]
I'm for battery buffs in general, but when it comes to looking into battery numbers for balance/ship builds, _please_ stop doing this:

> Stock, it uses 102 energy per second to move [...] My stock shuttle will completely exhaust that in 28 seconds.

It takes 102 energy to thrust _and_ turn, please do not just add up the numbers and present that as the simple fact, when solely thrusting takes less energy, solely turning (which will be the majority of movement done preparing to jump) takes even less, and jumping uses _no_ energy.

**Comment by Zitchas** [comment]
Sorry, but that is the closest we have to hard, repeatable, measurable, numbers. We do have to recognize it is what it is, though. Thrusting and spinning at the same time continuously. It is basically the worst case scenario of how fast a shuttle could burn through its energy. Actual usage is so variable and individual or is pretty close to impossible to give an endurance otherwise.

**Comment by DeBlister** [comment]
> Sorry, but that is the closest we have to hard, repeatable, measurable, numbers. We do have to recognize it is what it is, though. Thrusting and spinning at the same time continuously. It is basically the worst case scenario of how fast a shuttle could burn through its energy. Actual usage is so variable and individual it is pretty close to impossible to give an endurance otherwise.

Could do something like X% thrust cost + Y% turning cost.  You aren't going to turn the whole time, but you may thrust the whole time (at least in terms of relative probability) so X could be 100 and Y could be something like 65.

**Comment by Zitchas** [comment]
> > Sorry, but that is the closest we have to hard, repeatable, measurable, numbers. We do have to recognize it is what it is, though. Thrusting and spinning at the same time continuously. It is basically the worst case scenario of how fast a shuttle could burn through its energy. Actual usage is so variable and individual it is pretty close to impossible to give an endurance otherwise.
> 
> Could do something like X% thrust cost + Y% turning cost. You aren't going to turn the whole time, but you may thrust the whole time (at least in terms of relative probability) so X could be 100 and Y could be something like 65.

Yes, we could, but that's basically just running stuff through a formula. Although, in retrospect, constant turning and thrusting is pretty accurate for, say, dodging. Or trying to catch dropped minerals.

I'll leave it as is, but yes, we should all treat it like the metric it is: It is *A* way of measuring endurance that is consistent, and that's it. Although it is useful for being the extreme value. The shuttle *will* last at least 28 seconds, so that's one end of the possible endurance scale. The other end is, sadly, infinite, as we can easily let off the thrust key and just coast whenever and for however long we wish.

**Comment by Anarchist2** [comment]
re: 1 ton outfits: The only 1 ton outfit currently in the game, the Quantum Keystone, provides a non-stackable effect. This means that, unless you're installing multiple useless keystones at once, you're still not going to be filling a ship's full outfit space.

As for other prospective 1 ton outfits, we can wait until those get added in before evaluating dropping the supercapacitor to 1 ton.

**Comment by Zitchas** [comment]
I'm still not sure why having a 1 ton outfit is actually a problem, but yes, I can revert that if people consider it a big problem. Actually, I consider it quite realistic. If you are going on an interstellar voyage, are you not going to make every effort to take along every possible resource? Especially something basic like power, that you can *always* use more of?

Anyway, as for the batteries themselves. Thoughts? Impressions? Testing out using them?

**Comment by Arachi-Lover** [comment]
I'm not much for this in general, but if they are to be buffed I'd rather it be just the doubled capacity. Halving sizes is just too much I feel, and would open up a lot of space in most ships and variants, would be annoying to fill that in so as to not leave obvious gaps that are just not used for no reason.

**Comment by Zitchas** [comment]
I will remove the half space buff from the Coalition batteries if you wish, but I very much feel that the half-size is a very necessary part of the buff.

**Comment by Arachi-Lover** [comment]
> I will remove the half space buff from the Coalition batteries if you wish, but I very much feel that the half-size is a very necessary part of the buff.

That'd just nerf them in relation to everything else.
Someone mentioned in the Discord that only the absolutely huge batteries would really need a cut in size, so why not just have those reduced if you really want some size reduction? IE any battery over 50 outfit space gets a reduction of some form.

**Comment by Zitchas** [comment]
Well, if they aren't getting half the size, then they get bumped up to 4x the energy, so they'll remain on the same relative power to everything else.

**Comment by DeBlister** [comment]
If you're going to shrink the small solar panel you need to address the energy generation, if for no other reason than the fact that there's a larger one that's now worse than the smaller one.

**Comment by Zitchas** [comment]
Thank you for spotting that. I should have noticed that. 

Anyway, in case anyone was concerned about the size 1 outfits, we actually have *ten* size 1 outfits now:
Supercapacitor, Solar panels, cargo scanner, quantum keystone, quantum key stone, reasoning node, control transceiver, tree skeleton key stone, hexagonal crystal, and Crystalline Formation.

Only five of those are purchasable, but all can be acquired in-game.

On more important topics, I halved the cost of the Human, Hai, and Coalition batteries in order to lead players into the intended behavior: That they look at batteries first, and then upgrade to generators when they need long-term power supplies. This also provides more options at the low end, which supports greater opportunities for low-level economic play; as well as supporting smaller ship gameplay. It also furthers the options for creating smaller drones and fighters than we have been able to do until now. Not by much, but at the <200 range, getting rid of even 5 tons can be significant.

**Comment by Zitchas** [comment]
In my experience, there are three factors that influence my decision as to what I use as an energy source, once I have identified options that will satisfy my energy requirements:

1. Cost. This becomes less and less relevant as the game progresses, but is especially important in the early game.
2. Size. Smaller size means I can carry more other stuff. Need I say more?

As such, this PR in its current state address these three elements:

First, it increases the energy capacity of all batteries so that they are actually capable of satisfying energy demands beyond that of the most minimalist and high-risk merchants.

Secondly, it reduces their size so that they have a favorable contrast with generators.

Thirdly, it reduces their cost so they are actually good options for cost-saving pilots (not to mention reducing the stock price slightly for some ships).

I feel that the reduced space across the whole set is actually probably the most important part here because that is what actually makes batteries competitive against reactors. This is what gives people the choice of opting for batteries that, wile depriving them of infinite power, does let them install other stuff using that space. 

--------------------
(reposted from earlier, with some edits for accuracy and clarity):

nGVF-BB : 114 energy per second at 30 tons.

Using my stock shuttle as a case in point: Stock, it uses 102 energy per second to move, and 12 for shields. So, that means my shuttle with a nGVF-BB can literally recharge shields while doing a constant full thrust, full turn, for ever, infinitely.

If I have an LP036a + LP072a (30 tons worth of human battery), that gives 3200 energy. In a worst-case scenario where I'm taking shield damage while I thrust and spin trying to dodge a pursuer, my stock shuttle will completely exhaust that in about 28 seconds.

Is there anyone that is going to opt for the 30 tons of battery instead of the 30 tons of fuel cell? And then look at the cost: That's 47,000 in reactors vs 42,000 in batteries. So batteries are cheaper, but only for the measily cost of a single 2 passenger transport mission the player can opt for the infinite power option instead. 

Now, with the values in this PR, the fuel cell doesn't change, but 30 tons of battery is a LP144a+LP072a, which gives 14400 energy; which the stock shuttle will take 123 seconds to burn through. And since the cost is only 21,000, that's actually a 26,000 saving compared to the reactor. That's actually a meaningful amount for that stage of the game.

So, generator for infinite flight vs pair of batteries for 123 seconds of flight? That's actually long enough to start considering. Maybe I could ditch the smaller battery and install a KP-6 solar panel. I could even install a pair of small radar jammers alongside it! Suddenly there's actually options, and we can start discussing doing something with the shuttle. There's still risks involved, and doing much is going to run into dead batteries and having to wait for solar to recharge it now and then, but this could actually add some solid possibilities of having fun outfitting small ships instead of the main purpose of small ships being "get out of it into something bigger."


At the end of the day, this enhances opportunities, makes battery-focused builds much more viable across multiple regions of space, makes them attractive to the player. All in all, my tests show this making flying small ships more fun, particularly on a more mercantile pilot.

**Comment by Zitchas** [comment]
With this PR, pilots actually have choices, for instance, in an otherwise stock shuttle, one has three primary choices for power:

a) the reactor which provides infinite power for 30 space and 47k.
b) the same set of batteries, which provides about 60 seconds of max-throttle for 15 space and 21k.
c) one step up the battery ladder, which provides about 130 seconds of max-throttle power in exchange for 30 space and 48k.

That's actually a not bad set of choices, although option C isn't a particularly good one.

That being said, these are extremes. What I really hope to encourage is that more player consider doing something like, say, putting the size 10 battery in there (so, 40 seconds of max burn flight), and then add a solar panel or two as backups. Or for larger ships, they aim for whatever battery is suitable provides them with their minimum required power (Somewhere in the 20-40 seconds of full-throttle-everything is what is comfortable for me) with a small generator that might only be able to provide 25% of the engine energy requirements alone. This would be more than enough to keep merchants safe, even get them through a few small fights with a random pirates, and never actually run out of power (although their performance would drop significantly when a fight stretches out too long.)

This is why the insistence on the outfit space side. Because so long as many ships can get infinite running time with a reactor of the same space as the battery, why chose a battery?

Yes, this basically amounts to adding a battery of half the size of the faction's current smallest, move the stats over a step, and remove the biggest one. This works within what we have. If we'd rather just add a new tiniest battery that's half the size of the current smallest battery in each tech grouping, I'm good with that too. (Human, Hai, and Remnant primarily. Ka'het and Coalition would be good too, but not required.)

**Comment by Amazinite** [comment]
> This is why the insistence on the outfit space side.

I don't see why you're stuck on the outfit space changes when the important factor is actually energy density. If instead of halving all sizes and doubling all energy capacity we left the sizes alone and quadrupled all energy capacities, you'd have almost the exact same choices. And actually, if we (about) half the costs (or more) while leaving the sizes alone, it'd become even cheaper, since half cost + half size = same price per ton while half cost + no size change = cheaper per ton. Using the same Shuttle comparison:

1) nGVF-BB for infinite flight time at 30 tons and 47k credits.
2) LP072a + LP036a for 112 seconds of flight time at 30 tons and say 21k credits (almost double the flight time for the same cost as with your changes).
3) LP072a for 77 seconds of flight time at 20 tons and say 14k credits.
4) LP036a for 35 seconds of flight at 10 tons and say 7k credits.
5) LP144a for 168 seconds of flight at 40 tons and say 32k credits (more space used but cheaper).
6) LP036a + 3x supercapacitors (with a 5x energy capacity buff instead of 4x) for 55 seconds of flight time at 16 tons and say 37k credits (less space used but more expensive, since price-per-ton forms a J curve).

I say "say Xk credits" because my numbers I'm fiddling with aren't exactly halving costs.
image

**Comment by Zitchas** [comment]
I'm sorry, but price per ton is virtually meaningless. Actual size of the outfit, however, is very important *all* the time; and that goes hand-in-hand with energy density. 

Also, part of this is aimed at giving people more options in the early part of the game when flying small human ships is actually relevant. During this part of the game the *player* may not even know the Hai exist, let alone the pilot. We can't balance human outfits on the expectation that if they really need a size 5 battery, they can just nip over to the Hai to get one. Once they *do* discover the Hai, sure, the Hai battery should be a clear (but not massive) improvement for them; but we don't need to restrict human batteries to avoiding the sizes used by Hai. It doesn't hurt anything to have a battery that is the same size in the two areas, and thus permits a "if you use this battery, you can straight up replace it with this one" upgrade.

That being said, if we're good with increasing the energy density of the supercapacitor to just shy of the LP036a, then that resolves the majority of my concerns here.

Alright, so changes that have been done here:
- unhalving the battery halving for human, hai, and Coalition batteries.
- increasing their energy capacity to stick with the 4x energy capacity.
- Supercapacitor buffed to 375/ton energy density (LP036a is at 400/ton)
- Hai Chasm buffed slightly to 420/ton so it is actually better than the LP036a, but still lower than the LP072a.

**Comment by Zitchas** [comment]
How does this look now? The almost-to-battery levels supercapacitor has mitigated my strong wish for a size 5 *human* battery, I think.

**Comment by samrocketman** [comment]
I have been play testing this pull request about **15-20 hours** in game.

I've had a chance to use it both on ships and on fighters (I am play testing this in [a build combining all of my development changes combined with Zitchas' battery buff](https://github.com/samrocketman/endless-sky/actions/runs/2279001023)).

Overall, I think the battery changes are kind of nice from a playability perspective.  It doesn't feel overpowered like I thought it would initially (before actually playing).  Since I find mining to be very important here's a benefit I get with Ztichas' **outfit space sizes** that would not be otherwise possible:

* Because the 10-ton battery is now 5-ton I am about to equip 2 cargo expansions instead of 1 cargo expansion on the Dagger.  I made my Daggers battery powered for mining.
* The battery doesn't feel "infinite" even at the sizes and capacity in this pull request.  If you heavily rely on battery they still will drain rather quickly if you heavily depend on more battery than energy generation.
* In extended combat battery helps but can still be easily drained (even without ion damage or ion storms).  I don't consider this a problem.  I am just highlighting that playing this practically still feels similar to the old batteries.

Currently, I'm still only in human space.  I have not reached Hai space yet so I have only tried Human batteries.  In vanilla, the Hai batteries do not have an advantage over human batteries they're just sized differently with comparable capacities. I'll post another update when I get through the game with more experience with Zitchas' changes.

# Summary

Overall, I think this is an improvement in game play while play testing.  I will write up another report when I have more experience (maybe after 40 or 50 hours of play testing this further).

**Comment by samrocketman** [comment]
Small update:  I updated my game to the latest battery buff PR.  My fighters could no longer equip the 10-ton battery (formerly 5-ton).  However, I was able to get a similarly satisfying battery fighter build by using 8 1-ton supercapacitors.  A trade off of smaller capacity however the build still works so is a satisfying result I think.

**Comment by samrocketman** [comment]
# Hour 9 playtest update

My current save game is 9 hours into playing the game.  My net worth is 55m credits and I've actively participated in ship capturing and other lucrative opportunities following the story as if a new player would naturally discover.

I'm part-way through the Free Worlds campaign now (I've not picked sides, yet).  Have not yet "discovered" the Hai.  So far the battery sizes feel appropriate in human space.  I've been building and customizing ships a lot and nothing feels out of place.  Nothing feels over powered.  It just feels like good game play so far.

I look forward to when I "discover" the Hai because in vanilla their batteries are not much better than Human batteries.

**Comment by Zitchas** [comment]
I'm dubious about increasing the capacity on the Wanderer reactors, since they're already the best reactors in the game.

Regarding the Remnant crystal capacitors, I've got graphics that can be used for a larger Remnant battery, and the current graphics look best for a smaller one. So I'd leave those at the half-size I had them at, and I'll introduce the larger battery in a near-future PR. I'm ambivalent about the change to the cost. I don't think it's necessary, but I don't think it's not, so I'm good either way with that.

Other than those two things, looks good.

**Comment by Amazinite** [comment]
As mentioned in the commit description, the Wanderers already get hit pretty hard by ion damage, so I think it's appropriate to give them increased energy capacity to compensate for the buff to ion damage.

As for the Crystal Capacitor, if you want a smaller and larger version then those can both be dealt with in a separate PR instead of doing half the work here and half the work in a separate PR.

**Pull request merged**
