### PR TITLE
Create player conditions for mortgages, fines, back pay, and credit score

### PR DESCRIPTION
**Pull request by tehhowch**
Creates a few new automatic conditions to allow missions based on the player's financial acumen.
Refs #2737 

I'll let more seasoned writers draft the message / conversation @Pointedstick was looking for :+1:

### CODE REVIEW

**Comment by endless-sky** [comment]
This would get incremented every time the player "refinances" their mortgage (i.e. takes out a new mortgage at a lower rate and uses it to pay off the original mortgage). For #2737, it'd be much better for the variable to instead store the current total number of mortgages, so you know when the player is actually completely debt-free.

**Comment by Amazinite** [comment]
While on the topic of player conditions for mortgages, perhaps a `"credit score"` condition would go well along with the mentioned `"mortgages"` condition.

**Comment by tehhowch** [comment]
I had gone with this approach to avoid needing to add a variable to the PlayerInfo class (and am sad to say I never considered refinancing my ES loans, so I hadn't considered that behavior).

Credit score autocondition shouldn't be too hard to add either.

**Comment by tehhowch** [comment]
Updated to be more robust about the exposed autoconditions

**Comment by endless-sky** [comment]
To me it would make a lot more sense to only have auto-conditions for total debt, credit score, and salaries owed. In general I try to avoid adding too many auto-conditions, because once they're added and plugin creators could theoretically have made use of them, they're impossible to remove even if the base game code never used them.

**Comment by tehhowch** [comment]
How about a compromise to drop the TypeCount, and keep the separate tallies of fines vs mortgages? After all, one comes from being shady, and the other from being an aspiring entrepreneur - quite different situations (though sometimes not :wink: )

I'll push that change shortly

**Comment by Pointedstick** [comment]
If you wrote a mission with a condition `unpaid mortgages == 0`, wouldn't it trigger every time the player paid off a new mortgage--not just the first time?

**Comment by tehhowch** [comment]
Only if it is given repeat

**Comment by Pointedstick** [comment]
Oh of course, that makes sense.

**Pull request merged**
