### PR TITLE
feat(balance): Buff Star Barge Weapon Capacity by 2

### PR DESCRIPTION
**Pull request by Hecter94**
**Content (Balance)**

## Summary
This PR increases the weapon capacity on the Star Barge by 2, bringing it from 20 weapon capacity to 22 weapon capacity. 
Currently, with 20 weapon capacity and lacking a gun port, the only human weapons a star barge can equip are the blaster turret and modified blaster turret. Expanding that to 22 also gives the Star Barge the option of equipping a Laser Turret. 

The justification for this change is threefold:
1) Adding a second weapon type, other than the two blaster weapons, allows for more early-game experimentation. A new player or a player newly trying the Star Barge gets slightly more variety in their weapon choice.
2) For players interested in mining, the Laser turret is a significantly better option than either blaster turret, with 156 hull DPS rather than the 88 hull DPS on the modified blaster turret.
3) Allowing a laser turret gives the star barge slightly more ability to be modified into something capable of combat. A player that's interested in trying out combat can install a laser turret for a very slightly stronger ship

I think this change, while small, does give just a tiny bit more variety to what the Star Barge can do, letting a newer player that's picked a Star Barge transition over to combat or mining a little bit easier if they want to try out either of those options and gives it the potential to be a nice very early game mining ship alongside the sparrow or shuttle.

## Additional Details

This change also allows the Star Barge to fit three other turrets it wasn't able to before: the Ravager Turret, Chameleon Anti-Missile, and Inhibitor Turret. 
Ravager and Inhibitor seem unlikely to have any value installing on a Star Barge; Chameleon could be a weird but viable option if someone really wants to make a very small and cheap anti-missile ship. 
It also technically allows for equipping an AR120 Reverse Thruster, whereas previously, it was limited to a Capybara reverse thruster. 
Hopefully, neither of these caveats is considered a major balance concern. 

Comparison between the three starting ships with this change:
image

An example early mining build that's now possible with the Star Barge
image

Overall, it is my hope that the slight bit of additional variety that this change allows and the small benefit to the new player experience is worth whatever balance concerns may arise from the additional two weapon capacity.

### CODE REVIEW

**Comment by Saugia** [comment]
Being a mining-focused ship is the intention of the Sparrow, not the Star Barge. If we allow a Star Barge to be able to carry a Laser Turret, I feel that it will be often chosen over the Sparrow for mining - a beam laser turret does the damage of two beam lasers, and the ship's feature is its cargo size, so it would compete with the Sparrow. I don't think this should be the case.

You could say giving it a beam laser turret is another option for offense, but the concern is you're adding another capability to the Star Barge outside of heavy cargo transport, giving it the chance to be a slightly more jack of trades ship when the Shuttle already fulfils this purpose.

**Comment by EjoThims** [comment]
As minor as this seems in the scheme of things, this really does make the Star Barge blatantly the superior starting all rounder as well as cargo carrier, and that cargo capacity plus turret aiming together quite possibly make it better than the Sparrow as a miner, when even on par wouldn't really be appropriate.

I think it's fine to have one of the starting options just not have an offensive role.

**Comment by hexagonrecursion** [comment]
> @Saugia 
> Being a mining-focused ship is the intention of the Sparrow

This is not how a new player would read the description of  Sparrow (see below; emphasis mine).

> Classified as an **interceptor** rather than a fighter because it has its own hyperdrive instead of needing to be carried inside a larger ship, the Tarazed Sparrow is the smallest and cheapest **combat ship** available. Because of its **limited cargo** and passenger space, the primary way for a Sparrow pilot to pay the bills is to **upgrade the weapons** and **hunt pirates... or become one**. In either case, it is a **perilous way to earn a living**. [...]

**Comment by Ferociousfeind** [comment]
> Being a mining-focused ship is an intention of the Sparrow, not the Star Barge. If we allow a Star Barge to be able to carry a Laser Turret, I feel that it will be often chosen over the Sparrow for mining - a beam laser turret does the damage of two beam lasers, and the ship's feature is its cargo size, so it would compete with the Sparrow. I don't think this should be the case.
> 
> You could say giving it a beam laser turret is another option for offense, but the concern is you're adding another capability to the Star Barge outside of heavy cargo transport, giving it the chance to be a slightly more jack of trades ship when the Shuttle already fulfils this purpose.
> 
> The starter ships should be as separate as possible from each other to be more important in choosing them from one another, and I feel this overlaps more than it should. The Star Barge is already the most popular starter, so I don't think it should be getting a buff like this.

to be honest, I don't think the sparrow really makes for a good mining ship, and the fact that the star barge can compete with it if its weapon capacity is buffed 10% is indicative of who really makes a proper mining ship.

Just admit it, the sparrow is worthless! The shuttle caps better than it, and the star barge mines better than it!

**Comment by Ferociousfeind** [comment]
(and mostly, "Being a mining-focused ship is an intention of the Sparrow, not the Star Barge" is an unhealthy approach to balance, the ships are customizable)

**Comment by Saugia** [comment]
>Just admit it, the sparrow is worthless! The shuttle caps better than it, and the star barge mines better than it!

Then there's no reason to be buffing the Star Barge.

>(and mostly, "Being a mining-focused ship is an intention of the Sparrow, not the Star Barge" is an unhealthy approach to balance, the ships are customizable)

Saying the Sparrow is bad, but then saying the Star Barge is fine with getting a "simple" 2 weapon space, is the unhealthy approach to balance. The answer isn't to buff the Sparrow following a buff to the Star Barge. 

Two weapon space, in this context, as a human starter ship, and the possibility of adding something like a Laser turret which is 2 beam lasers, something the Star Barge normally doesn't have, is a lot more than just "a simple 2 weapon space". You have to look at this within the very start and early part of the game, not from a later perspective saying that the number 2 is simple and small.

Regardless of if the Sparrow is currently subpar, I don't think buffing the Star Barge should be getting a buff.

**Comment by Hecter94** [comment]
I think there are, perhaps, two different approaches to the idea of balancing at play here. 

If you look at this change as a veteran player looking to min-max their ship and get as much benefit as they possibly can out of it by making use of every possible advantage, then yes, this is probably giving the Star Barge a bit more than it should have in terms of absolute balance. I can certainly respect and understand that viewpoint; I don't think that is wrong.

However, considering that these are starting ships and will be a player's first experience with ES, it would be prudent to consider the case from more of a brand-new player perspective, especially as they are the ones that will likely be making the most use of these starting ships, as veteran players will likely be upgrading fairly early. 

In that context, I feel it would benefit the new player experience and ES as a whole to suffer the hit of making the Star Barge slightly unbalanced to present a better new player experience. Allow them more variety in what weapons they can use, what loadout they can go with, and what playstyles they can try without feeling locked into whatever playstyle comes with their pick of a starting ship with limited ability to customize into trying something different.

This is more of a general design philosophy. Still, I feel that while the starting ships certainly should lean into different playstyles and have different strengths and weaknesses and very different stock load-outs, I also think allowing a new player to customize their starting ship into a different role to allow them the freedom of trying out a different playstyle without much difficulty would go a long way to improving our new player experience. I see this change as a step in that direction. 

Regardless, there's not much room for compromise here simply due to the small size of this change. So, while I ask that you consider my alternate viewpoint, I will leave the final decision to merge or close up to the Dev team.

**Comment by Amazinite** [comment]
> (and mostly, "Being a mining-focused ship is an intention of the Sparrow, not the Star Barge" is an unhealthy approach to balance, the ships are customizable)

Ships are customizable, but ships also have limits to their customizability. Would it be unhealthy to say that the Bulk Freighter is not a combat-focused ship? No, because the Bulk Freighter is intended to be a, as the name suggests, freighter. Sure, it's possible to press it into other roles, but you're better off choosing a different ship that's actually intended at base for that role.

In the same manner, the Sparrow is intended at-base to be a combat ship, which effectively also makes it a mining ship. (There are distinctions to be made between combat and mining focus, but the basic similarity between the two is that they both require some level of firepower.) The Star Barge is intended to be a cargo-focused ship, and we shouldn't allow it to be pressed into being as good as if not better a mining ship than the Sparrow.

> the fact that the star barge can compete with it if its weapon capacity is buffed 10% is indicative of who really makes a proper mining ship.
>
> Just admit it, the sparrow is worthless! The shuttle caps better than it, and the star barge mines better than it!

Read: "If we make the Star Barge better at mining, it'll be better than the Sparrow at mining, which shows that it is better than the Sparrow at mining." What?

> it was expected but extremely funny to see strong opposition to +2 weapon capacity. Not even +2 outfit space which would allow you to fit more stuff in it, just +2 weapon capacity, allowing you to fit larger weapons in exchange for smaller other outfits, being pushed back against because it means the star barge might outclass the other two starters.

You talk about 10% and +2 as if they're tiny changes to make. Sure, they're tiny in a magnitude sense, but they're actually very impactful in a performance improvement sense, as the base stats of these three ships are already so low. A slight change for any of these ships in any direction toward any of the other ships does make them much more powerful relative to the others.

**Comment by Amazinite** [comment]
> In that context, I feel it would benefit the new player experience and ES as a whole to suffer the hit of making the Star Barge slightly unbalanced to present a better new player experience. Allow them more variety in what weapons they can use, what loadout they can go with, and what playstyles they can try without feeling locked into whatever playstyle comes with their pick of a starting ship with limited ability to customize into trying something different.

Except you can already try out other playstyles in the Star Barge, you simply won't be as effective with them as if you had chosen the other ships that are more suited for those playstyles. You could mine with a blaster turret. You could convert some of your cargo space to outfit space to get enough bunks to match or even exceed the base Shuttle. It's actually already a lot more difficult for the Sparrow and Shuttle to break out of their molds than it is for the Star Barge; the Star Barge is already the Mule/Bactrian of the starter ships, and we don't need to give it any more benefits.

**Pull request closed without merging**
