### PR TITLE
Feat: Realtime hailing

### PR DESCRIPTION
**Pull request by petervdmeer**
**Feature:** This PR implements a first step towards the feature discussed in issue #871

## Feature Details
This is the first step towards allowing the game-engine to continue running when certain panels are active. The panels get an IsModal function which will ensure that the game-engine is not paused when the function returns true.

The first panel that I'm testing this with is the HailPanel. With this PR the game-engine keeps running while the HailPanel is open. (And the planetary defence force launches while the panel still is open if you demand tribute. Note to self: don't ask tribute when being too close to the hailed planet.)

If this works well, then one of the next steps would be to update the BoardingPanel to run in real-time as well (which is the feature requested in #871).

The IsModal functionname was inspired by Tehhowchs remark in #2978.

## UI Screenshots
N/A

## Usage Examples
N/A

## Testing Done
I need to review the HailPanel code a bit more and some more testing is required before this can be merged.

The main reviewing/testing that still is required is to check if the panel uses cached/static game-data, for example what happens if a ship gets hailed that then flies away, or if the player dies while the panel is open? Is the code in the HailPanel able to handle such situations?

The HailPanel is now also active while the event-loop is active. I also need to check if this gives undesirable interactions between those pieces of code.

## Performance Impact
No performance impact expected.

### CODE REVIEW

**Comment by Amazinite** [comment]
Would it be possible to have the game not just continue running, but instead slow down when you have a modal panel open? I don't see that as being necessary right now, but I can imagine it being something we might want in the future. E.g. when you board a ship, the game outside of the panel still runs, but only at a third the speed. This means that if you're boarding a ship, you have extra time to react should you start getting fired upon.

**Comment by tehhowch** [comment]
I'm of the opinion that the game should not continue running in the background when the UI is up. Rather, the boarding panel would close / minimize when you engage in some action that should take time, and would reopen automatically when said time has elapsed. While the action is underway, you would either be unable to do anything (attacking / defending), or (if plundering) any such action would result in disengaging and canceling the action (after a disengagement time, rather than immediately). In both cases, you would be unable to use offensive weapons (limitation of the engine at this point, since your projectiles may hit the boarded ship) or crewed defensive weapons (since your crew is presumably busy at the moment).

**Comment by petervdmeer** [comment]
@Amazinite Sure that is possible. The discussion/alignment on the preferred slowdown/timing will likely take more time than the implementation, so doing that in a separate PR sounds very appropriate.

**Comment by petervdmeer** [comment]
@tehhowch
For plundering I was thinking of the following:
- give the player the option to show and to hide the panels during the plundering (for example by pressing B again).
- allow the player to queue the plunder actions by selecting the outfits and pressing take, after which those actions are executed in the order the player selected them.
- execute fuel transfers (from the hostile ship to the player) in the background while the ships are boarded/connected and in parallel to other actions.
- execute ammo transfers (from the hostile ship to the player) also the background while the ships are boarded/connected and in parallel to other actions.
- automatically stop the plundering when the player flies away, presses weapons or performs any other ship-control-action with the panel minimized.
  - on such disengage; have a chance (depending on how far the plundering process for the current item is) that the current item being plundered flies away as flotsam.
  - we could also go for a fast disengage (just flying away) that has a risk of some crew loss (due to crew still being outside plundering stuff) and a slower disengage that takes longer but doesn't trigger crew loss.

For capturing I was thinking of the following:
- as soon as the player presses capture, then the UI closes.
- the "primary fire" button is then used to indicate that the player wants his/her crew to attack.
- the "secondary fire" button can then be used to have the crew attack with consumable H2H outfits (#2392)
- when both the target and the player don't attack for 3 seconds, then both crews retreat to their own ships and capture ends.
- any ship-movement button forces a dis-engage, possibly causing some crew to be lost because they are in the airlocks inbetween ships.
  - the loss would be bigger if the player just attacked (defending crew retreat to the players ship)
  - we could extend this later with counters that count how many crew from the player are on the hostile ship and vice-versa
    - capture could then still succeed after disengage (due to player crews still fighting)
    - and in a similar sense, the player could still die due to hostile crew still fighting after disengage.
- adding a soft-disengage option (pressing B?) that takes longer, but that does not cause crew to be lost in space.

I like the idea that time also continues while the panels are up, but those proposals could also work if the panels do pause the game.

Having said that; if we really want every panel (like the hail-panel in this PR) to always pause the game, then we should close this PR, since this PR only adds the code to continue the game while UI panels are up.

**Comment by tehhowch** [comment]
My objection to running the game in the background is that the player is presented with text to read and then penalized for being unable to read it instantly. For a text-based story engine, I believe this goes against the desired user experience.

**Comment by petervdmeer** [comment]
I agree with pausing the game for story engine panels that pop-up unexpectedly with relevant/unique mission-texts. The player however has full control on when the hail- and boarding-panels pop-up, so I consider them closer to the "real-time spaceship control engine" than to the "story engine".
But I'm okay with having the game paused during the hail- and boarding-panels and move all time-consuming capture and plunder actions to after closing of the boarding-panel, so I'll focus my efforts on that when I continue with this.

**Comment by tehhowch** [comment]
It should be noted that the player currently is the only one that can initiate the boarding or hail panel, but this is not going to always be true. NPCs will eventually hail the player (be it to bribe or to e.g. offer a special mission), and it's possible we could come up with a way for the player to respond to being boarded (though such a "defensive" boarding panel would likely be a different class than the current one).

**Pull request closed without merging**
