### PR TITLE
Reduce Quantum Keystone/Key Stone mass and eliminate outfit space cost

### PR DESCRIPTION
**Pull request by dragonmaus**
Doesn't really fit into any of the proscribed categories; this is more of a "quality-of-life/immersion" tweak.

Not much to it, just removes the outfit space metric from keystones, and reduces their mass to 0.1 tonnes each.

I also scanned through the missions and removed one instance of pre-allocated cargo space that no longer makes sense, but it's entirely possible that I missed something; edits welcome.

### CODE REVIEW

**Comment by Zitchas** [comment]
I'm not sure how I feel about this. On the one hand, we do in fact that a mission where a Remnant hands the player a keystone they were carrying around. (albeit a very rare mission that most players never see.) On the other, it means it is ultra-convenient to just put a keystone on *everything*. As a 1 space outfit it's already pretty easy, but now it requires no thought at all. While I'm a fan of giving people easy choices, making them totally costless is something I am dubious about. Especially for something that is actually installed on a ship.

I think I would prefer that it still took up some space, even if it is just 0.1. Granted, until we have other <1 outfits, that .1 might as well be 1 as far as outfitting is concerned (it would, however, make transporting them from the Hai much, much easier).

**Comment by Amazinite** [comment]
I'm fine with reducing the mass, as that will notably make it easier to pack 60 into your cargo for the purposes of that one Remnant mission, but I'm not too keen on the reduction in outfit space, for reasons that Zitchas has mentioned.

**Comment by dragonmaus** [comment]
Well, I was hoping to foment somewhat more active discussion, but it's easy enough to see which way the wind's blowing here. 😅

I'll revert the outfit space removal in a moment, but keep the mass change.

**Comment by dragonmaus** [comment]
Welp, guess I'll have to reopen. Screwed something up by being hasty and accidentally zeroed out the branch.

**Pull request closed without merging**
