### PR TITLE
Removing jet fuel from plastics

### PR DESCRIPTION
**Pull request by Amazinite**
https://groups.google.com/forum/#!category-topic/endless-sky/_QH0kFGIQPg

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
isn't jet fuel made from the same thing as plastic?
but should be... industrial?

**Comment by MessyMix** [comment]
@KiLEdEnNis it should be industrial?

but for what use? Jet fuel can't melt steel beams!
REEEEEEEEEEEE

~topic: why should "jet fuel" be under "industrial"?

**Comment by Amazinite** [comment]
@KiLEdEnNis oils are used to produce plastics. Everything oil based looks like its under plastics.

**Comment by KiLEdEnNis** [comment]
because people use industry to make fuel?

**Comment by Bladewood** [comment]
people use industry to make everything?

**Comment by KiLEdEnNis** [comment]
then put everything under Industry
black meme

**Comment by Pointedstick** [comment]
Honestly I have to kind of agree with @KiLEdEnNis on that. The distinction between goods in `Industrial` and `Equipment` has always seemed a bit nebulous to me.

That said, yeah, let's get Jet Fuel out of `Plastics`.

**Comment by whismerhill** [comment]
In this case shouldn't you remove much more such as asphalt too ?

**Comment by Amazinite** [comment]
Why?

**Comment by Pointedstick** [comment]
B,ecause it's not a plastic, I imagine. The category is "Plastics," not "Petroleum-Derived Products".

**Comment by whismerhill** [comment]
exactly what pointedstick said
I'm just asking, maybe I missed something, my mind is kind of elsewhere these days.

**Comment by KiLEdEnNis** [comment]
everything that's actually plastic can stay in plastic, the other stuff made from oil etc. should be industrial or something

**Comment by whismerhill** [comment]
@KiLEdEnNis 
well, it seems like plastic would be near empty then. I'm not an expert and english is not my native language but it seems to me a lot of those are oil byproducts....

**Comment by KiLEdEnNis** [comment]
I mean anything that's made from plastic can stay
& we could add more plastic stuff then

**Comment by KiLEdEnNis** [comment]
I can't think of a good-sounding alternative either: "Oil-based products", "Plastic-like products"
and adding a new commodity isn't gonna happen

**Comment by MessyMix** [comment]
>plastic-like products

aka plastics

**Pull request closed without merging**
