### PR TITLE
Wandering typo fixes

### PR DESCRIPTION
**Pull request by Bladewood**
A bunch of typo fixes for the Wanderer start and middle files.

One thing perplexes me:
Kor Efret or Kor Efreti?

### CODE REVIEW

**Comment by Amazinite** [comment]
You and Jafdy with your branches. tsk, tsk.

**Comment by Bladewood** [comment]
I don't know how to use GitHub, leave me alone.

**Comment by MessyMix** [comment]
Yeah, can we please get rid of Remote Tracking?

You're just like me. I keep having those branches. To fix it, I just clone repo every time. xD :P

or learn to use Git.

**Comment by Amazinite** [comment]
I just branch from the main on the desktop app.

**Comment by Nechochwen-D** [comment]
`git fetch endless-sky
git rebase endless-sky/master
git push upstream -f`

**Comment by endless-sky** [comment]
Efret vs. Efreti is meant to be singular vs. plural, in the same way that you'd say that a ship is German (singular) but it's piloted by Germans (plural). There was originally the same distinction between Sestor and Sestri, but people got confused by that.

I like to give the alien words plural forms that are not the same as English (i.e. not just adding an s) to represent the fact that it's a different language.

**Comment by Lineth** [comment]
@Nechochwen-D What does that do precisely? Another git newb here.

**Comment by MessyMix** [comment]
@thomasballinger http://stackoverflow.com/questions/6406762/why-am-i-merging-remote-tracking-branch-origin-develop-into-develop

**Comment by Nechochwen-D** [comment]
@MessyMix That is likely a better method than mine but I have not run into any serious issues yet with it.

**Comment by Bladewood** [comment]
yay~!

**Comment by EndrosG** [comment]
I am completely new to github, so I am really not yet firm with how to use it properly etc. Sorry in advance.
But while playing the missions defined in `wanderer middle.txt` I found a few text errors.
And since I at least found this thread I think I better post them here than opening a new issue, correct? I dont know how to check with the pulls and commits etc. (just created that account 1 hour ago via browser, no other interface), so I simply put all the information just into this comment and leave it to one of you to check if those are still up2date or if they have been fixed already.

**needed change / fixing proposal:**
`On <planet>` in the `on offer` conversation should be replace by `On <origin>` since it obviously relates to Kort Kehai (source planet) and not Spera Anatrusk (destination planet).

```
mission "Wanderers: Mind 2"
	landing
	name "Return to <planet>"
	description `Return to <planet> with a Wanderer named Meto Pa'aret and an "artificial mind" that he constructed.`
	autosave
	source "Kort Kehai"
	destination "Spera Anatrusk"
	to offer
		has "Wanderers: Mind 1: done"
	cargo "artificial mind" 2
	passengers 1
	blocked "To take this mission, you will need a bunk and two tons of cargo space free."
	on offer
		conversation
			`On <planet> you are met by a Wanderer named Meto Pa'aret. He explains that he is in charge of the artificial intelligence lab, and he wants to travel with you along with the "Mind" that is being entrusted to your care. "We have already [altered, reconfigured] one of the climate [simulation, prediction] Minds for this new purpose," he says. "It now contains [stores, databases, libraries] of historical and cultural information, things we hope will help the alien [consciousness, intelligence] to [understand, sympathize with] us and realize our intentions are [peaceful, forthright]."`
			choice
				`	"Are you sure that's wise, giving the Kor Mereti access to so much information about the Wanderers?"`
				`	"How likely do you think this is to work?"`
					goto work

			`	"It is certainly not wise," he says, "but it is [right? fitting?]."`
				goto end

			label work
			`	He says, "There is insufficient [data, information] to even [attempt, hazard] a guess. But nevertheless it is the most [appealing, pleasing] [course of action?]."`

			label end
			`	The "artificial Mind" turns out to be a computer not much larger than a typical cargo crate. Pa'aret walks beside it with one wing draped around it like an overprotective parent while Wanderer workers load it onto your ship. Clearly this particular piece of technology is very valuable to the Wanderers.`
				accept
```

----------

**needed change / fixing proposal:**
`The Wanderers back on <planet>` in the `on offer` conversation should be replace by `The Wanderers back on <origin>`, same mistake as above, but different names.

```
mission "Wanderers: Mind 7"
	landing
	name "Investigate <planet>"
	description "Visit <destination>, and figure out what the Kor Mereti are doing there, now that they are apparently no longer hostile."
	autosave
	source "Spera Anatrusk"
	destination "Korbatri Eska"
	to offer
		has "Wanderers: Mind 6: done"
	on offer
		event "wanderers: kor mereti transformation"
		conversation
			`The Wanderers back on <planet> are in a frenzy to know the outcome of the battle. Pa'aret tells you, "Less than a second after the Mind [made contact, merged] with the Mereti, it severed the [backdoor, failsafe] connection. So we have no [information, visibility] on what the Mind is doing or whether the Mereti [received, welcomed] it."`
			choice
				`	"Most of the drones started fighting on our side. That seems like a good sign."`
				`	"They've sealed up access to the Mind. There is no way we can get it back now."`
					goto mind

			`	"Indeed," says Pa'aret. "But whatever [transformation, change] the Mind [wreaks, catalyzes] may not be complete. It is too soon to trust that we have [succeeded, chosen correctly]."`
				goto next

			label mind
			`	"That is [gratifying, encouraging]," says Pa'aret. "Surely if they viewed it as an [intruder, enemy] they would have destroyed the Mind rather than building a [nest, fortress] to protect it."`

			label next
			`	A few minutes later Tele'ek arrives with some scout ships from the Wanderer fleet. "The drones have sealed up every [entrance, ingress] to that station," he says, "and they are [swarming, gathering] around it [protectively, jealously]. There is no way we can return there to [discover, assess] what is happening inside. And there is also some [activity, development] on the planet's surface."`
			choice
				`	"What sort of activity?"`
				`	"I'd like to go and investigate."`
					goto end

			`	"They seem to be [scavenging, hunting] for resources to build something," says Pa'aret. "It is [strange, surprising]; the Mereti drones until now were ignoring the planets in their [systems, territory]. Would you be [willing, bold] to land your ship on the surface and investigate?" You agree to do so.`

			label end
			`	The Wanderers wish you the best of luck, and you prepare to return to the <system> system. Hopefully the Mereti drones will not become hostile once more while you are landed on the planet's surface, exposed and relatively defenseless.`
				accept
```

----------

**needed change / fixing proposal:**
`When you last left <planet>` in the `on offer` conversation should be replace by `When you last left <origin>`, same mistake as above, but different names.

```
mission "Wanderers: Mentors 3"
	landing
	name "Return to <planet>"
	description "Return to <planet> to see what the Wanderer leaders have planned next."
	autosave
	source "Korbatri Eska"
	destination "Spera Anatrusk"
	to offer
		has "Wanderers: Mentors 2: done"
	on offer
		conversation
			`When you last left <planet>, there were less than a dozen buildings in the greenhouse facility. It has now grown to the size of a major spaceport, including some towers that are dozens of stories high. Some plants now grow on open-air terraces; others are in domed enclosures tall enough to house fully-grown trees. The larger domes also have birds flying about inside them, and some larger land animals as well. Everything is built of gleaming steel and glass and filled with lush vegetation; from high above the facility looks like a scattered handful of diamonds and emeralds.`
			`	The freighter you were escorting was full of professors and researchers, who are clearly not used to any sort of military discipline or to living in a dangerous region of space: the moment the freighter lands they fly off toward the greenhouse without bothering to wait for instructions from their supposed manager. Several of them are already engaged in conversation with the drones, while others are exploring the different rooms of the facility, examining plants and probing soil with their talons.`
			`	The team's manager, already looking a bit overwhelmed, flies over to talk with you. "What are we [expected, requested] to do next?" he asks.`
			choice
				`	"Help the drones to learn to take care of the planets in this region."`
				`	"Make sure the drones remain convinced that the Wanderers are on their side."`
					goto side
				`	"Maybe see if the drones will share their technology with us? They have impressive weapons."`
					goto weapons

			`	He says, "We will try to do that. But this, storing [plants, living things] in boxes made of metal, is not the Wanderer way. We seek to return worlds to their [natural, pristine] state, not to build our own [monuments, structures] on them."`
				goto end

			label side
			`	"Very well," he says, "we will do that. Please return to <planet> and see what our [leaders, elders] think should be done next."`
				goto end

			label weapons
			`	He doesn't seem enthusiastic about that suggestion. "Human," he says, "you have very different [priorities, goals] than we do. I am more [excited, intrigued] by the possibility of using these drones for [renewal, creation] than by their capacity for destruction."`

			label end
			`	You return to your ship. It will be interesting to see what else has changed the next time you return to this world.`
				accept
	on complete
		event "wanderers: hurricane mass production"
		event "wanderers: desi seledrak" 24
		conversation
			`The mood among the Wanderer leaders is much lighter now that the danger from the Mereti drones appears to have been eliminated. In fact, they're now so intrigued by the emergent Mereti consciousness that they don't seem to be thinking about the more distant threat of the drones in Kor Sestor space. Instead, they want to focus on their true calling: terraforming planets.`
			`	Sobari Tele'ek tells you, "We should take time to enjoy this [peace, respite]. We need not [face, deal with] the other drones immediately. We will be working to start a second [settlement, base] nearby. Visit us there when the base is [formed, established] and we will decide our next [actions, steps]. In the meantime, our latest ship of [war, defense] is now being produced on our [major, central] worlds, and you may buy one."`
```

----------

**optional change:**
use common text replacement in name, i.e. change it to `name "Deliver device to <planet>"`

```
mission "Wanderers: Sestor: Bomb Zenith 1"
	landing
	name "Deliver device to Zenith"
	description "Admiral Danforth asked you to drop this device (presumably a bomb) above the Alpha base on <destination>."
	source "Farpoint"
	destination "Zenith"
	clearance
	infiltrating
```

----------

**optional change:**
use common text replacement in name, i.e. change it to `name "Deliver device to <planet>"`

```
mission "Wanderers: Sestor: Bomb Zenith 2"
	landing
	name "Return to <planet>"
	description "You have destroyed the Alpha base on Zenith. Return to Farpoint and find out if your intervention allowed Danforth to gain the upper hand against the Kor Sestor fleet."
	source "Zenith"
	destination "Farpoint"
	to offer
		has "Wanderers: Sestor: Bomb Zenith 1: done"
```

----------

**needed change / fixing proposal:**
**Zenith is not available as variable because source is Farpoint (but the base was on Zenith)**, hard code it like currently done in the previous mission (Bomb Zenith 2).

```
mission "Wanderers: Sestor: Kill Southern Remnant"
	landing
	name "Destroy Kor Sestor drones"
	description "When you destroyed the Alpha base, the Kor Sestor drones began acting independently. They are now attacking human space. Help the Navy destroy the drones, then return to <planet>."
	autosave
	source "Farpoint"
	to offer
		has "Wanderers: Sestor: Bomb Zenith 2: done"
	to complete
		has "Wanderers: Sestor: Scattered Remnant: done"
	waypoint "Alnitak"
	waypoint "Betelgeuse"
	waypoint "Canopus"
	waypoint "Capella"
	waypoint "Castor"
	waypoint "Kursa"
	waypoint "Mebsuta"
	waypoint "Miaplacidus"
	waypoint "Rigel"
	waypoint "Saiph"
	waypoint "Wazn"
	on offer
		conversation
			`The base on <planet> appears to have survived the attack, despite the Kor Sestor drones that were overhead. You meet with Danforth and tell him that you destroyed the Alpha base using the weapon he gave you.`
			`	He says, "When you destroyed the base, the Sestor drones suddenly stopped acting as a unified fleet. A few stayed here, but most of them have spread throughout this sector of space, and we are receiving reports that they are attacking Navy and civilian ships indiscriminately. My own fleet is too damaged to do anything to stop them, but other Navy bases are sending in reinforcements. Can you join them to help eliminate the drones?"`
			choice
				`	"Of course, I would be glad to."`
					goto end
				`	"Of course. But first, what the hell was that bomb you had me drop on <planet>? It cracked the whole planet open."`

			`	Danforth sighs. "Unfortunately," he says, "I am not permitted to tell you what that weapon was or how we acquired it. And already news agencies throughout the Republic are questioning our use of such a terrible weapon. I wish we had been able to defeat the Kor Sestor fleet without resorting to such extreme measures, but we had no choice."`

			label end
			`	Danforth gives you a map of the systems where there have been reports of Kor Sestor drones attacking civilian ships. "These, plus any that were left alive in the Alnilam system, are all the automata that we have been able to track," he says. "Report back here once you have succeeded in completely destroying them. We can't risk letting some local warlord capture them. The Navy will hopefully send some ships to help you."`
				accept
```

----------

To be honest I found the latter ones just when writing this summary and looking for the relevant missions in the file. Luckily I didnt have to bomb Zenith but could destroy all sestor ships earlier.

**Comment by KiLEdEnNis** [comment]
ya can just make a new issue for typo's
as for stating them, just say what mission & where, pasting several missions and saying what to fix causes people to scroll for 5 seconds until we reach the bottom of your comment

**Pull request merged**
