### PR TITLE
Center Pointedstick's Vanguard

### PR DESCRIPTION
**Pull request by czartrak**
I finally get this PR out

This PR fixes the offset on Pointedstick's Vanguard
Credit to @KiLEdEnNis for fixing the sprite.

Corrected sprites can be found here: https://drive.google.com/drive/u/1/folders/1elQ0B_T8t7ZUymu_MrPjJeK40hoPQa1S

### CODE REVIEW

**Comment by MCOfficer** [comment]
ref #3858 #3851

**Comment by czartrak** [comment]
Third time's the charm

**Comment by Pointedstick** [comment]
So much love for my beautiful Vanguard :smile:

**Comment by KiLEdEnNis** [comment]
since Amazinite didn't want to break more PRs (:P),  he told me to say this here as well:
move turret hardpoint from 0 40 to 0 42

**Comment by Amazinite** [comment]
I double checked the pixel measurements and hardpoint coordinates and this looks all good now.

**Pull request merged**
