### PR TITLE
Make Power of the People never disabled

### PR DESCRIPTION
**Pull request by toilethinges**
2f5b760

(Edit: I was just playing last night and I successfully disabled and captured it, so it currently is not "never disabled." tehhowch gives explanation below)

### CODE REVIEW

**Comment by Amazinite** [comment]
?

https://github.com/endless-sky/endless-sky/blob/master/data/persons.txt#L455

**Comment by Brick63** [comment]
it already is toilet

**Comment by toilethinges** [comment]
I was just playing last night and I successfully disabled and captured it, so it currently is not "never disabled."

**Comment by Brick63** [comment]
okay you should probably include that in the description as i had no context.

**Pull request merged**
