### PR TITLE
Cold planets

### PR DESCRIPTION
**Pull request by dorbarker**
## Summary
Adds `frozen` as a planet attribute, analogous to the `volcanic` or `forest` attributes. This PR only adds `frozen` to planets where cold and ice cover is the **dominant** feature in the description, _i.e._ it is added to Winter, but not Earth, Trinket, or Albatross.

The `frozen` attribute could open up the ability to write jobs specifically for cold climates, _e.g._ looking for volunteers to bring heaters and blankets as suggested in #8819.

Search terms I used to identify candidate planets:
- frozen
- cold
- ice
- icy
- glaci*
- snow (yielded nothing not covered by the preceding terms)
- frigid (yielded nothing not covered by the preceding terms)

### CODE REVIEW

**Review by Quantumshark — APPROVED** [review]

**Comment by lumbar527** [comment]
I found some planets you missed, do you want me to tell you them or make a PR to your branch?

**Comment by bene-dictator** [comment]
> I found some planets you missed, do you want me to tell you them or make a PR to your branch?

Yeah, list them please. I know it wouldn't be possible to add suggestions but better you comment them here and let us discuss whether they're suitable.

**Comment by lumbar527** [comment]
I actually think Snowfeather would make sense as frozen, for you could have a sudden huge storm and need supplies or something. I guess if it melts after a few days that would make it less problematic, though.

Updated List (thanks @Quantumshark): New Greenland, Snowfeather [debatable - probably not], Vail?, Viminal.

**Comment by dorbarker** [comment]
For a future PR, I think some of the discussion here about which planets qualify for `frozen` could warrant a `cold` /`cool`/`brisk` attribute in addition to the `frozen` one introduced here.

I added `frozen` to capture planets that were dominated by ice sheets, but `cold` (or equivalent) might be worth while for planets like Earth, that are cold in places or times, but isn't necessarily their predominating feature.

**Comment by Hurleveur** [comment]
Most planets would be cold in some places, right?

**Comment by Amazinite** [comment]
>Most planets would be cold in some places, right?

Per the PR description, this is meant to identify planets which are predominately cold/frozen. Earth has volcanos, but we don't call it a volcanic planet as far as planet attributes go.

**Pull request merged**
