### PR TITLE
Syndicated Shipyards Revamp

### PR DESCRIPTION
**Pull request by Anarchist2**
image

## Summary
A revamp of the graphics used on Syndicated Shipyard ships, including the Wasp, the Barbs, the Protector, the Vanguard, the Freighters (Bulk, Freighter, Star Barge) and the Arrow.

Old on left, new on right:
wasp
arrow
protector

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/file/d/1qlX3bpvjbZlINGK7ctHFd6e9iPCjf3-2/view?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/152

### CODE REVIEW

**Comment by Arachi-Lover** [comment]
that "mouth" on the new wasp looks really weird to me

**Comment by MasterOfGrey** [comment]
I'll second Arachi, the mouth could do with not being a thing.

**Comment by ravenshining** [comment]
I like the mouth, but I'm really not a fan of the indented fins.

**Review by Amazinite — CHANGES_REQUESTED** [review]
Some of these, like the Barb and the Marauder Arrows, run into the same issue I had with the Tarazed detailing. That is, you're removing a lot of the color from these ships and making them even more gray. The Vanguard seems to be choked of its color by doing the exact some thing of creating indented gray parts in the fins. The Protector especially has become a very colorless ship with the little color that was there being darkened compared to currently, and from the thumbnail I'm really not a fan of turning what were large blocks on the end of each spoke of the ship into fins. The only other thing I have an issue with is the rear fins on the Freighter. The four separate indentations in the rear fins look strange.

Otherwise though, looks pretty good. I'd be interested in seeing more feedback from others as there doesn't appear to have been as much chatter here compared to #5368.

**Comment by Zitchas** [comment]
The Wasp is a clear improvement as far as I'm concerned. The mouth is OK, but I'd also be OK without it. The increase in color, though, I definitely like.

The arrow is a good improvement on detailing, but the side windows got lost. Can we get those put back in?

I second Amazinite's comments about colors getting a bit drained for the Vanguard and the Protector. Perhaps some of the paneling that has been added in the detailing can be colored instead of grey? That would balance out the darkened color.

**Comment by Corraban2** [comment]
Overall some of the new images look really glossy, I'm not sure if that's good or bad. I dislike the indented fins, but otherwise the new details look good.

**Comment by beccabunny** [comment]
Honestly, these are the redesigns I am the the less sure of by far. There's a lot that could be improved in syndicate designs, just look at the Star Barge thumbnail; but all this PR does is add some random details here and there, without improving the overall shape at all and sometimes making it worse. For example, instead, in the the Southbound redesign structural changes were made to the Dread and Argosy (and the same to the modified argosy too) because they were needed, and in the Betelgeuse one the same was made to the Behemoth because of how weird it looked in 3d

**Pull request closed without merging**
