### PR TITLE
Small Change to Intro Wording

### PR DESCRIPTION
**Pull request by McloughlinGuy**
Quick correction to something in intro mission.

## Summary
In one of the intro missions, James comments on how he boarded a pirate ship and they had grenades that killed four of his crew members before he even knew what was happening. However, grenades are terrible defensive weapons, it even says so in the description of them. So I quickly modified the file so it said nerve gas rather than frag grenades, which have a defensive value that matches the laser rifle and works much better in the context of pirates. (I also think maybe the turns in the sentence could be changed to turned, but either works)

### CODE REVIEW

**Comment by Zitchas** [comment]
I'm not sure this is a problem: The situation James is describing sounds like the Pirates leapt right in with an offensive attack instead of defending.

**Comment by McloughlinGuy** [comment]
> I'm not sure this is a problem: The situation James is describing sounds like the Pirates leapt right in with an offensive attack instead of defending.

I disagree. It specifically says he sent his crew through the airlock and then four were dead before he knew what was going on. In order for that to happen he would have to be attacking, not defending.

**Comment by Amazinite** [comment]
Just because the player is attacking doesn't mean that the opponent is defending. The way that boarding actually works is that each side chooses whether to attack or defend. If both sides attack then both sides use their attacking values. If one side attacks and the other defends then it's attack values versus defense values. If both side defend then the boarding ends. So even though James attacked, the pirates could have also attacked, and therefore the the attack values of the grenades would be used.

In any case though, I don't think that the gameplay of how boarding works should have too much influence on how boarding is described in the story.

**Comment by TheMarksman-ES** [comment]
On a side note, "turns out" is correct in this capacity. However, the sentence itself sounds weirdly off, which is likely attributed to the "And it" at the front.

Would personally have gone with "Turns out, the pirates possessed grenades."

Side-side note: Gameplay doesn't always have to be equal to the story. James is old. He could've easily mixed up details, even if I agree with Derpy that Nerve Gas and Grenades wouldn't be an issue, or that Nerve Gas is an uncontrollable weapon and would've never really been used on a ship unless the people on board are that desperate.

**Pull request closed without merging**
