### PR TITLE
Show different Kestrels on the "for sale" mission

### PR DESCRIPTION
**Pull request by Anarchist2**
Not checking for a default Kestrel, since that shouldn't happen.

### CODE REVIEW

**Comment by Zitchas** [comment]
Seems like a good change. Haven't double checked the actual functioning yet, though.

**Review by Amazinite — CHANGES_REQUESTED** [review]
Doesn't work.
image

**Comment by Anarchist2** [comment]
Gotos under scene nodes are broken and don't work; adding in a line of (empty) text underneath the scene node makes them work properly.

**Comment by Amazinite** [comment]
> Gotos under scene nodes are broken and don't work

Because I'm pretty sure they were never intended to work.

**Pull request merged**
