### PR TITLE
[On Hold] Expanding the Quarg as a faction

### PR DESCRIPTION
**Pull request by Amazinite**
A rebalancing and expanding of the Quarg has been on people's minds for a while now. After the work done in #3536, we thought "why not do it ourselves?" In order to not step on Brick's toes, this PR doesn't include the outfit images for those outfits which are added by #3536, meaning that that PR must be merged if this one is to be.

The main intent of this PR is to give a base to work off of and establish the lower boundaries of T3, a lower boundary that leaves lots of room between T2 and T3 in some cases (e.g. the Quarg weapons are both efficient and powerful, leaving room for T3 weapons that may be powerful but not efficient or vice versa). It leaves open the possibility of many more Quarg ships or weapons of larger sizes, especially as some of the larger outfits in the PR are not in use by the three Quarg ships. (The Quarg can always be rebalanced again as well if necessary, this is just balancing them as a T3 template based off of current T2 and T2.5 tech that is established in game already.)
yasbjfqwqoes9c305-9bdq
(From top to bottom, the new Skylark image, the new Oriole light warship scout, and the new Wardragon image.)

New stuff:
* Added two new weapons
  * Skydagger: a smaller Skylance with a quicker turn rate
  * Ranseur: a long range laser sniper
* Added different sized Quarg power generators, shields, and engines
* Added Quarg hull repair (#1551)
* Added a new Quarg ship: the Oriole, a scout warship

Outfit quirks:
* Quarg engines have reverse thrust that is 50% the power of their forward thrust (#3252)
* All Quarg outfits (minus engines) have built in active cooling that is equal to 15 cooling per ton and cooling energy at 1 energy per 5 cooling
  * Explanation: the crystals used in Quarg outfits have strange thermodynamic properties, causing them to absorb heat surrounding them, but at the cost of the outfits becoming less efficient as more heat is absorbed (i.e. they suck up more energy).
* Quarg power generators provide the highest energy/ton of any generator and also have high (but not the highest) heat efficiencies, but they also have among the highest heat/ton of any generator, meaning that Quarg power still requires massive cooling to use. (Think Korath Plasma Cores, but with less heat compared to the energy provided.)

Changes:
* Buffed Quarg AM by increasing the AM value from 25 to 30 and increasing velocity from 500 to 750 in order to make it compete better with the powerful but short ranged Point Defense Turret. (#1800, but Quarg AM is still far less powerful than the Pug T3 AM)
* Nerfed the Skylance by cutting its damage in half (firing energy and heat changed accordingly) in order to put it more in line with tier progression.
  * Despite this seemingly massive nerf, all missions that feature Wardragons are still doable in a single ship of reasonable power for the mission.
* Doubled the defense value on Intrusion Countermeasures in order to keep the smaller ships difficult to cap
* Altered the stats of the Skylark and Wardragon in order to fit well with the new outfits and to fit more in line with tier progression.

Notes on warship balance (T2 heavies vs T3 lights):
* An Oriole will take down the shields of a Kar Ik Vot before losing
* A Wardragon will take down a Kar Ik Vot losing almost half of its shields before winning
* A Wardragon will take down a Punisher losing almost all of its shields before winning

To do list:

- [ ] Create a full array of ships for the Quarg to use
- - [ ] At least two medium warships
- - [ ] At least one heavy warship
- - [ ] At least one heavy freighter (For transporting large amounts of material to create ringworlds)
- - [ ] A superheavy warship (? The Quarg probably have something massive hidden up their sleeve for emergency situations)
- - [ ] A transport ship (? Seems like the Quarg would mainly use their teleportation system.)
- [ ] Create more weapons and unique weapons for the Quarg to use
- - [ ] Some form of secondary weapon system (perhaps two secondary weapons)
- - [ ] Small arms guns and turrets (replace Skydagger that's in this PR)
- - [ ] A Quarg "superweapon" (for the superheavy warship, if we do that)

<hr/>

Thanks to @Brick63 for creating the outfit sprites
Thanks to @1010Todd for creating the ship sprites
Assets can be found [here](https://drive.google.com/drive/folders/1qCnJMyfmY2Za6EFqBz2k4TqLFwHofdNS).

### CODE REVIEW

**Comment by Lineth** [comment]
Those ships.

oh god yes

**Comment by Lineth** [comment]
Just coming in to note: I personally think the Quarg should have weak/non-existent (probably not the latter, as shield piercing is fairly common in higher tech tiers) armor repair capabilities and rely on disproportionately strong shields for defense. IMO ity would make sense lore-wise as shields are more 'efficient' a means of defense compared to bulky, heavy armor; especially for a race as fancy and technologically advanced as the Quarg. To me high armor regen makes sense for the Korath (with their brutally straightforward, power-over-practicality approach), the Drak (their 'ships' are eldritch psychic bug monsters) and the Pug (whose ships are possibly alive and in general seem to regard the laws of physics as being polite suggestions). Remnant remain ambiguous until we get some more lore for them.

**Comment by endless-sky** [comment]
That made sense for the Quarg up until shield disruption and piercing became a thing. Quarg ships used to have very low hull values and no hull repair, and the result was that it was trivial for a ship with disruptors to disable them.

**Comment by KiLEdEnNis** [comment]
disruption and piercing resistance became a thing though, right? if so, why not use that

**Comment by Lineth** [comment]
In general I have to dislike the prevalence of shield nullifiers, as IMO it's klind of limiting on balance. If not a nerf for it (possibly in the form of 'reinforced shields' providing resistance as per @KiLEdEnNis 's suggestion), then I'd accept the Quarg ships having very high armor values (to represent spess majick supermetals) but no/token armor regen.

**Comment by Pointedstick** [comment]
What's the status of this PR? These art assets alone are super fantastic.

**Comment by jafdy** [comment]
Delayed indefinitely. In other words until MZ decides to accept it or do something different for himself or gets bored and closes without an explanation.

**Comment by Amazinite** [comment]
I've also waiting on Todd (or Brick) to create shipyard thumbnails for the Quarg ships.

**Comment by Zitchas** [comment]
The ship pictures look decent, but to me the Skylark looks like a warship. Specifically, it looks like a medium warship to the Wardragon's light warship.

**Comment by Amazinite** [comment]
I considered reserving "Wardragon" for a heavy warship and renaming what we know as the Wardragon to the "Nighthawk," but I decided not to. I will be revisiting this PR later on though and changing some things up before I consider it ready to merge, and a name change might be in order.

**Comment by Pointedstick** [comment]
I love the Skylark image, I love the new Oriole image, but I gotta admit, I do not love the new Wardragon image. If I had to try to put my finger on why, I might say that I think it feels too boxy, and I don't like the front wings/spikes. I think it would look a lot better without them.

**Comment by Amazinite** [comment]
All the ship images are going to get a look at once I get around to finalizing this. Right now there's already work being done to make the Skylark image look more "freighter-y" (see below), and there has been discussion on possibly changing how the Quarg ships represent their colors to be swizzled (changing it from the current neon lines of color that run down the middle of the ship).
ship

**Comment by Amazinite** [comment]
Added a to-do list to the OP of what I'd like to see done with the Quarg.

**Comment by Amazinite** [comment]
Closing this because otherwise it's just taking up space right now.

**Comment by Saugia** [comment]
I am currently leading the continuation of this PR. You can find work on that here: https://github.com/endless-sky/endless-sky/discussions/9016

Ship details, weapons, looks and other aspects have already been settled on. I am currently waiting on some models to be made. Please take any discussion there.

**Pull request closed without merging**
