### PR TITLE
bugfix: Fix AI timings and actually do what the documentation says

### PR DESCRIPTION
**Pull request by tibetiroka**
**Bugfix:** Fixes the `step` variable of AI.

## Fix Details
According to the documentation, AI.step is
> // The current step count for the AI, ranging from 0 to 30. Its value
> // helps limit how often certain actions occur (such as changing targets).

In reality, it reaches values as high as 31. Also, to clarify, with 60FPS, it should only reach 29, since 0-29 has 30 distinct integer values, so we go through each of them twice. This is what this documentation suggests:
> // Each ship only switches targets twice a second, so that it can
> // focus on damaging one particular ship.

Which was also incorrect, because the timings were off.

This is all fixed now. FindTarget is called twice per second, step stays in [0, 30[.
## Testing Done
~~AI doesn't seem to be any more broken then it already is.~~

### CODE REVIEW

**Comment by vitalchip** [comment]
Would we be as well testing for !step?

targetTurn is always going to be 1 at the point of checking it against step because it's initialised at zero every time Ai::Step is called then incremented by one just before we test against it, so we're really just testing step == 1 everytime and the rest is fluff. It was that way before, so I appreciate you've just added a new version of each increment.

**Comment by tibetiroka** [comment]
`targetLoop` is incremented inside a loop. This is so ships don't all update their targeting in the same frame; instead, only 1/30th of ships update per frame.

**Comment by vitalchip** [comment]
I must have chosen a poor place to sample, every ship I checked always had a value of 1 !   To be fair I don't normally run that code for target updating as I feel it's far too often so I had to do some reversions to test it.. probably put something in the wrong place.

**Comment by warp-core** [comment]
I think you should update the comments to indicate that `step` ranges from 0 to 31 and the target update happens `about` twice per second (once every 32 steps). There is no particularly need for it to happen *exactly* twice per second and 32 is an integer power of 2, which I assume is why modulo 32 was chosen (`x & 31` is equivalent to `x % 32`), or perhaps someone got the maths wrong and thought it would do `x % 30`.

**Comment by tibetiroka** [comment]
What's wrong with actually fixing it? Performance won't suffer, and this is easier to understand. _And_ this is more logical for regular human beings.

I just don't see what's so great about the `x & 31` approach.

**Comment by quyykk** [comment]
> I just don't see what's so great about the x & 31 approach.

it's branchless! :smile:

**Comment by tibetiroka** [comment]
Premature microoptimization at its best.

**Comment by quyykk** [comment]
> Premature microoptimization at its best. /s

I mean, kinda. But yeah I think this is not really necessary either sorry

**Pull request closed without merging**
