### PR TITLE
[Content] Creating additional Starts

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
This adds three starts:
- Alternate start (this is an identical to the normal start, just starts on Midgard instead.
- Easy start (this starts on Mainsail with 480k, but no loan and a credit score of 600)
- Hard start (this starts on Glaze with 450k, and a 0.6% interest rate loan)

## Lore
In order to maintain compatibility with the story and mission content later on, all of these starts are very close to identical. The main difference in the lore is the clarification that for the Easy start they were employed managing the logistics of a textile firm instead of in a textile mill proper. So in every case they are still associated with the textile industry, and thus the few mentions of textiles in various missions will continue to make sense. 

## Note:
Currently, the tutorial missions are hard-tied to New Boston, so none of these starts will see James. Should I adjust this? It might be good for at least the Easy and Alternate starts to get the tutorial, although I'm dubious about doing so for the Hard one.

As a side note, I wish the textbox for the start description was a bit bigger. It'd be nice to be able to fit a brief "This is the recommended start for new players" on the bottom of the default start, for instance. But that won't fit. Also, the list of starts and the start description box are comically tiny on a 1440p monitor. As in, they are maybe 1"x2" each on my screen. Tiny.

## Save File
This can only be tested by starting a *new* pilot

## PR Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by Arachi-Lover** [comment]
You'll also need to change the comment on the player's home region in Free Worlds Intro accordingly.
`Katya turns out to be a Dirt Belt native like yourself, from a planet named Hope` (line 913).

**Comment by Amazinite** [comment]
When adding new starts to the vanilla game, I'd rather go all out on it and have entirely separate backstories that we account for in any missions that mention them and potentially with different tutorial missions than basically just copy and paste the same introduction with differing starting finances, which if I was a new player would seem rather lazy to me.

I have a branch that started working toward some more complete alternate starts back before we even had the feature, and I published it once the syntax on choice starts was finalized: https://github.com/Amazinite/endless-sky/commit/c772f7bc8804d88be336ad76279a337eee8bc23e. This branch is very much unfinished at the moment, but what I have is I've kept the current start named Endless Sky, then I've added a Deep start that I have a description for but an unfinished intro conversation that's slightly easier than the default start, a Paradise Worlds start with a completed description and intro conversation that's much easier than the default start, and a Syndicate start with a completed description and intro conversation that's more difficult than the default start.

**Comment by Arachi-Lover** [comment]
There's also New Boston's description. Given the mention of the player being born there is just a short line, just removing it should be fine for other starts, or removing it entirely if that'd be easier to work with.

**Comment by Zitchas** [comment]
> When adding new starts to the vanilla game, I'd rather go all out on it and have entirely separate backstories that we account for in any missions that mention them and potentially with different tutorial missions than basically just copy and pasting the same introduction with differing starting finances, which if I was a new player would seem rather lazy to me.

I have one big problem with this, namely: content creator impact. If we actually have diverse backgrounds, that means anytime someone want to refer the the character's background, we'll need to make multi-split conversations. I don't like doing that, and I know for new content creators, it's even more of a struggle. On top of that, the more different they are, the less they have in common, which means that conversations that cover all these options will be more diverse, and thus harder to knit together cohesively. So the more diverse the backgrounds are, the less content creators are going to want to have anything to do with it.

This is why I picked "logistic manager for a textile firm," and I'm contemplating updating the hard one to be something farther down the chain, like forklift driver for a textile mill or something like that. We'll see what fits. In any case, it is something that retains the connection to textiles, but with a different feel to it.

**Comment by Amazinite** [comment]
> we'll need to make multi-split conversations.

Well #5440 will make such conversations MUCH easier to implement, whereas right now you need a mess of branches to handle more than two scenarios. But even if that weren't a thing, I'd still rather have to deal with branches when referring to the player's background than have all the starts be basically the exact same outside of the most minor of differences.

**Comment by Terin** [comment]
You've mentioned yourself about being interested in a Remnant start, right Zitchas? More flexible backgrounds would only help that, unless you were completely committed to the Remnant having a sleeper agent living very specifically on New Boston. Different starts being from different parts of the galaxy would be pretty effective at showing the inequality in the universe through narrative and gameplay mechanics right from the jump. I definitely lean a lot more towards that, when there are only a handful of references to you being from New Boston that we can work around. In fact, it'd give us more opportunities to make put some small hooks into in the Pirate Campaign, for instance.

**Comment by Zitchas** [comment]
I think before we get into making wildly different starts we need to have a bigger text box. What I've proposed here works with what we've got. To be honest, I mostly hear people wanting to start somewhere else - I don't hear anyone wanting a different James. 

I'm fine with getting completely different stories for each start - this is just the starting point where people get different to start in different places.

**Comment by Amazinite** [comment]
> I think before we get into making wildly different starts we need to have a bigger text box.

I don't see why we'd need a bigger text box. I've come up with four separate starts that all have descriptions that fit into the existing space.

**Comment by Zitchas** [comment]
Well, the ones you've got look good. Why don't we have them in-game already?

**Comment by Terin** [comment]
People like James, he's a good tutorial NPC. But like Barry from EVN, he's not really bound to any one world, he could show up at any of them.

> So that branch just needs to wrap up any of the conversations, it needs new thumbnails for the new starts, it needs new tutorial missions for the new starts, and we need to find out where we need to account for the player's backstory. in any existing missions. You're free to fork off of it and make any of those changes if you have the time, because I wasn't planning on getting to them any time soon. (And we don't need to PR all these starts at once, we could finish them each individually.)

From the comment above.

**Comment by Zitchas** [comment]
Alright, apparently I'm blind. Didn't see that comment.

**Comment by Amazinite** [comment]
I feel like there are a few more important things to get to than adding more vanilla starts, especially when there are still some features we could add to make handling multiple different backstories easier.

**Comment by Zitchas** [comment]
For full complex backstories, I agree. This PR was intended to be low-hanging fruit in giving people the starting point, namely, different locations. It's not as interesting as full different stories, but it does give people new starting points, albeit within the current story.

**Comment by Arachi-Lover** [comment]
On James, like I said I do think it'd be best to have him appear for alternative starts, save for specifically more difficult starts where one wouldn't get a tutorial friend as part of the added difficulty, but for more exotic starts where James being there wouldn't make the most sense, I think we should replace James with other NPCs instead of going the route of not having him at all.
Cases I can think of are the potential Pirate, Hai space, and Remnant starts.
For a Pirate start specifically it'd be very useful given how difficult it is to be a pirate in ES, I believe one plugin (Businessman if I'm not mistaken) did have a "Pirate James" sort of character that helped you out get started with the pirate jobs, so something like that for that start.
For the Hai and Remnant starts, just someone to provide some context as to how the player goes about exploring out of those pockets would be nice, instead of just dropping you after the loan conversation (which for each of these three could also be made much more different in regards to context and all that).

**Comment by Zitchas** [comment]
So, all or nothing, then? No possibility of allowing people alternate start types without radically changing their backstory and all the attendant ripple effects through the story?

**Comment by Amazinite** [comment]
> So, all or nothing, then? No possibility of allowing people alternate start types without radically changing their backstory and all the attendant ripple effects through the story?

I already said that if people want simple alternate starts then a plugin should suffice, but if we want new alternate starts in the base game then we shouldn't just make copy-pasted versions of the original start.

> I feel that this restriction is going to move alternate starts from "Easily implemented feature we could add now" to "hard to implement feature we potentially never get."

I've already linked my work on new starts that are unique from the original start. It really wouldn't take too much to go from what I've posted to a completed product. I will at some point finish them myself if someone else doesn't beat me to it, but we all know how much I have on my plate already. If there's interest I could look into finishing them after I wrap up the alien factions I'm working on.

> I can't speak for everyone, but patrolling the entire game for mentions of the character's backstory (and, in the future, having to police all mentions of the character's backstory to implement branches for all variations) is a very high workload for very poor returns.

I'm a sucker for games keeping track of less important things (and I do think that the player's backstory should be considered less important than the missions they've actually completed) and changing dialog to account for them, so I'd contest the idea that the return would be poor.

**Comment by Terin** [comment]
Finding those references is a light workload when spread out across the community. As from what I've been able to tell, there's been four:

1) Katya being from the Free Worlds "like yourself"
2) Mentioning your background to the scientist during Project Hawking
3) Finding out Barmy Edward is also from New Boston
4) Your reference to a Remnant that looks like a textile worker

Those are not so deeply ingrained in the game that \<first\> \<last\> needs to be set as a textile worker for all time. When we get a new start PR, then we can have more people scour the game files for any other references. They'd be easy to change, and then going forward, we can more clearly mark those points which reference the player's history, and change them accordingly. Especially for the Republic/Syndicate campaigns, having those reflect on where you came from vs. where you're going would be very flavorful.

**Comment by Zitchas** [comment]
The main point of this PR wasn't the different locations, but rather the different difficulties. Changing locations was basically just a way to make describing which start someone picked a little more interesting than just "hard, medium, easy."

In any case, I view this as two separate issues, warranting this PR to cover the first item, and a second (or multiple) PR's for the other part.

1. Different difficulties
2. Different backgrounds

Right now I'm interested in creating opportunities for people to have harder or easier starts, so that'd be number 1. Yes, I gave them slightly different backgrounds, but still close enough to not need any lore changes. These would be easy enough for someone to adapt when someone wants to implement a significant lore change for anyone one of these.

Beyond that, I have two observations:
A. I've seen a fair bit of interest in having different difficulties of starts.
B. I have seen some interest in having different starting locations.
C. I have seen *no* interest in having pilots with different trades or professions.

So, I put the effort where the interest is. Lots of people want the different difficulties, and this gives them that, and gives them different starting locations too. 

But the bigger question: Why block the many from having these difficulties available widely now? It makes adding content to meet the second half of stuff easier, and adds functionality that people want *now*?

And as to your last comment: Honestly, I love it when games respond to my decisions and reflect my character. That being said, which one of four professions my character happens to be prior to the beginning of the game has zero impact on the pilot's personality, skills, knowledge, or description. Ergo I place no value in it. 

Instead of adding baggage to any attempts at including the pilot's pre-story background in mission content, it would be *far* more interesting to add variation that reflects choices the character makes in-game. For instance, combat rating, who the character has made enemies with, what ship they fly, or what *kind* of ship they are flying?

As far as that goes, I'd much prefer that we could, say, track which type of ship the player favored flying the most and use that to change conversations (Hmmm, you've spent 10% of your career flying transports, 15% flying freighters, 10% flying light warships, and 65% flying Heavy Warships. We might be able to change a few NPCs perceptions based on that.) **This** is the sort of place we should be putting effort to shaping the story to match the player's pilot. Not wasting time on trying to drag extra meaning out of a detail that really translates to "Did you pick the hard, normal, easy, or alternate start".

(as a side note, the pre-pilot career is sufficiently meaningless I'd be just as happy purging every trace of it from the game. We don't need to add to it. Not unless  it becomes a pull down menu so that we can pick the difficult first, and then select any one of a dozen or two professions. Because the two really don't belong connected.)

**Comment by Terin** [comment]
>The main point of this PR wasn't the different locations, but rather the different difficulties. Changing locations was basically just a way to make describing which start someone picked a little more interesting than just "hard, medium, easy."

Most long-term difficulty will come via game rules and having presets through there. The different, normal, human starts can affect how a new player starts out, but once you pay off your initial loan, it's all practically the same. It's why I'd rather wait to use it for some small, but interesting background choices to provide different insights into how someone new to the stars might first see the universe, rather than rushing it in for a difficulty option that vanishes after an hour or two.

>As far as that goes, I'd much prefer that we could, say, track which type of ship the player favored flying the most and use that to change conversations (Hmmm, you've spent 10% of your career flying transports, 15% flying freighters, 10% flying light warships, and 65% flying Heavy Warships. We might be able to change a few NPCs perceptions based on that.) This is the sort of place we should be putting effort to shaping the story to match the player's pilot. Not wasting time on trying to drag extra meaning out of a detail that really translates to "Did you pick the hard, normal, easy, or alternate start".

Why not both? Any references to the player's background would be optional in dialogue, as easy as checking for the condition set by picking that intro. There's no need to expunge them, they'd be an easy change in dialog I could whip up in 20 minutes. I look at it as something similar to Mass Effect backgrounds. While those are roughly mechanically even, so are starting loans in the grand scheme of things.

**Comment by Zitchas** [comment]
> Most long-term difficulty will come via game rules and having presets through there. The different, normal, human starts can affect how a new player starts out, but once you pay off your initial loan, it's all practically the same. It's why I'd rather wait to use it for some small, but interesting background choices to provide different insights into how someone new to the stars might first see the universe, rather than rushing it in for a difficulty option that vanishes after an hour or two.

Again, there's no reason why we need to lump it all into one PR. I've got the intro-difficulties part here, with minor background changes that don't really ripple out, since I'm not really interested in the background side of it, just the starting conditions. The next person can just take one of those, and make the bigger background change that they're interested in making, and do the branches too. 

What I'm basically advocating for is an iterative approach where we take this part for what it is, and the next part builds on that. One piece builds ontop of the next piece. No need to make the whole thing wait for what I consider different things to be completed.

**Pull request closed without merging**
