### PR TITLE
Feature Request #240 - Comparing Outfits/Ships

### PR DESCRIPTION
**Pull request by GoldenDalek**
Press ‘c’ or Shift+ click to keep an outfit or ship’s info on the
screen. Press ‘c’ or Shift+ click on a different outfit to change the
extra info. Press ‘c’ or Shift+ click on the same space to close and
return to normal.

Some errors in the ship section for formatting, if you compare a ship with and without fighter bays

Edit: The right panel behaves normally.
I didn't add colour coding as in some values, a higher value is more desirable, and in others, a lower is more desirable, and to hardcode all of it would be very messy.

### CODE REVIEW

**Comment by GoldenDalek** [comment]
Note: Only displays, no comparing

**Comment by gchapyzh** [comment]
So this will allow you see two ships/outfits similtaniously in the map menu, correct?

**Comment by endless-sky** [comment]
Looks like a good change, but could you clean up the code a bit? In particular, your local changes to the XCode project should not be included in the commit. And, please use tabs instead of spaces for indentation, and try to follow the [style guide](http://endless-sky.github.io/styleguide/styleguide.xml)'s recommendations for where you put spaces, line breaks, etc.

**Comment by GoldenDalek** [comment]
How do you know if it's tabs or spaces in XCode?

**Comment by GoldenDalek** [comment]
And yes to gchapyzh

**Comment by endless-sky** [comment]
XCode has an option for inserting spaces vs tabs. Also, in the files you edited you should just be able to replace four spaces with tabs using the find / replace dialog.

You should be able to use git to revert the XCode project to the original version.

**Comment by GoldenDalek** [comment]
Done!

**Comment by GoldenDalek** [comment]
I think i changed back the XCode Project but i'm not sure...

**Comment by GoldenDalek** [comment]
I fixed the XCode Proj file as well.

**Comment by GoldenDalek** [comment]
With what?

**Comment by endless-sky** [comment]
I ended up adding my own implementation of this (c6b1d63):

compare

**Pull request closed without merging**
