### PR TITLE
Content: address wrong usage of Unfettered fleet (HR)

### PR DESCRIPTION
**Pull request by Hurleveur**
The Sea Scorpion was added to the Unfettered's ship but it's not seen in HR because it's using a copy of the `Large Unfettered` fleet.
In order to address that and any similar issue in the future I removed the copy, and replaced references of it by references to the actual `Large Unfettered` fleet.

It is not needed to define a copy of a fleet just to change the government, that can be done by the NPC definition. Since these fleets are only used in NPC definitions this will not cause any issues.

### CODE REVIEW

**Comment by EjoThims** [comment]
Does this not need to define that government change as well then?

**Comment by warp-core** [comment]
> Does this not need to define that government change as well then?

The npc's government overrides the governments of any fleets within that npc.

**Review by EjoThims — APPROVED** [review]
Seems like a good change all around. Even reduces line count

**Review by MasterOfGrey — APPROVED** [review]
Oh good, I always thought there was something jank about that fleet existing, but it was admittedly very far down my list of priorities to look into.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
