### PR TITLE
Create Independent Outfitters [content]

### PR DESCRIPTION
**Pull request by LocalGod79**
...removing (highly illegal) Nerve Gas for sale on Republic/FW planets.

also creates a convenient destination/origin for submitted outfit/story content.

### CODE REVIEW

**Comment by LocalGod79** [comment]
#1687 & #1664

**Comment by Pointedstick** [comment]
I like the idea of a place to put weird, uncommon, or highly illegal outfits. Gives you more of an incentive to explore the rougher parts of the galaxy.

**Comment by LocalGod79** [comment]
@Pointedstick i think that illegal outfits should be limited to `Pirate Outfits`, which still have a home on unconverted Pirate worlds.

otherwise, i believe that you generally approve of this pull (even though it may introduce conflicts for you to resolve in your p.r.)

**Comment by jafdy** [comment]
If this goes through the I can add my boosters to it.

**Comment by Bladewood** [comment]
Wait, what?

**Comment by LocalGod79** [comment]
i realized that the only place that `Independent Advanced` is used is on a non-FW/Republic world, and doesn't need to conform to their laws. (apologies @Pointedstick - i think this is what you were referring to)

`Independent Advanced` is now a duplicate of `Pirate Outfits` for the moment, providing a non-pirate outlet for community submitted outfits.

**Comment by retrue** [comment]
To Independent Advanced could go extra stuff that is not sold elsewhere, like the hyper boosters or small radiator.

**Comment by LocalGod79** [comment]
i'm working on adding a "Graviton Booster" outfit to this pull (a compromise to address #1706).

any opinions on whether this should this be an Independent Basics, or Advanced outfit?

**Comment by retrue** [comment]
All the new stuff to Smugler's Den that would be the only Independent Advanced.

**Comment by Admiral-Danforth** [comment]
Gatling gun turret

**Comment by Admiral-Danforth** [comment]
Flamethrower turret to as well as illegal licenses

**Comment by LocalGod79** [comment]
Flamethrower turret: no. just no. i'm not arguing - it's just not happening.

Gatling Gun Turret: a firm "maybe". (balancing this one will be challenging, and being groundbreaking (ammo'd turret), i'm _very_ hesitant)

what's an illegal license?

**Comment by BorkBorkGoesTheCode** [comment]
Illegal licenses could be stuff like getting permission from the local criminal underworld to use certain weapons.

**Comment by LocalGod79** [comment]
@BorkBorkGoesTheCode that sounds like a faction license - anyone willing to write some story? (please start a thread in the Google Group - i have a contact that has already prepared some balanced outfits that would be appropriate)

that said, i feel like the "Space Brakes" (to address #1706) i'm working on would fit better as `Independent Basics` outfits, rather than `Independent Advanced`, though part of #1664 and especially #1687 would probably fit better in the latter...

**Comment by Lineth** [comment]
I think the illegal licence might be referring to counterfeit versions of legal licences . Allows you to buy stuff you normally couldn't, and cheaper than the legal version, but with a chance of getting caught.

**Comment by Admiral-Danforth** [comment]
outfit "Turreted Flamethrower"
	category "Turrets"
	cost 190000
	thumbnail "outfit/flamethrower"
	"mass" 9
	"outfit space" -9
	"weapon capacity" -9
	"turret mounts" -1
	weapon
		sprite "effect/explosion/small"
			"frame rate" 60
			"no repeat"
		sound "flamethrower"
		icon "icon/flamethrower"
		"submunition" "Flamethrower Projectile"
		"inaccuracy" 12
		"velocity" 9
		"lifetime" 5
		"reload" 2
		"firing energy" .1
		"firing fuel" .25
		"firing heat" 4
	description "A crude but impressive-looking weapon, the Flamethrower ignites your hyperspace fuel and directs a stream of it towards your adversaries. The damage it does is relatively minor, but it can be useful for causing a target that is already operating near its thermal capacity to overheat, temporarily taking it out of the fight." The mechanics at Smugglers Den managed to mount it on a turret increasing its effectivity. 

It doesn't have a different sprite and has to be used separately from the other flamethrower, but it works (all you have to do is change gun/secondary weapon to turret).

**Comment by Admiral-Danforth** [comment]
Lineth hit the nail on the head for my definition of illegal license. Buy an illegal Navy License, run to Geminus with 100 interference plates and hope you don't get caught.

**Comment by Bladewood** [comment]
@Admiral-Danforth nonono, you're doing it wrong.
> outfit "Flamethrower Turret"
	category "Secondary Weapons"
	cost 640000
	thumbnail "outfit/flamethrower"
	"mass" 24
	"outfit space" -24
	"weapon capacity" -24
	"turret mounts" -1
	weapon
		sprite "effect/explosion/small"
			"frame rate" 60
			"no repeat"
		sound "flamethrower"
		icon "icon/flamethrower"
		"submunition" "Flamethrower Projectile" 2
		"inaccuracy" 12
		"velocity" 9
		"lifetime" 5
		"reload" 1
		"firing energy" .1
		"firing fuel" .25
		"firing heat" 2
	description "Being the amazing engineers that they are, the people at Smuggler's Den have managed to design the Flamethrower Turret, doubling the effectiveness of an ordinary Flamethrower."

**Comment by Amazinite** [comment]
@Admiral-Danforth #953

**Comment by Admiral-Danforth** [comment]
- [ ] `outfit "Turreted Flamethrower"
	category "Turrets"
	cost 190000
	thumbnail "outfit/flamethrower"
	"mass" 9
	"outfit space" -9
	"weapon capacity" -9
	"turret mounts" -1
	weapon
		sprite "effect/explosion/small"
			"frame rate" 60
			"no repeat"
		sound "flamethrower"
		icon "icon/flamethrower"
		"submunition" "Flamethrower Projectile"
		"inaccuracy" 12
		"velocity" 9
		"lifetime" 5
		"reload" 2
		"firing energy" .1
		"firing fuel" .25
		"firing heat" 4
	description "A crude but impressive-looking weapon, the Flamethrower ignites your hyperspace fuel and directs a stream of it towards your adversaries. The damage it does is relatively minor, but it can be useful for causing a target that is already operating near its thermal capacity to overheat, temporarily taking it out of the fight." The mechanics at Smugglers Den managed to mount it on a turret increasing its effectivity. 
`

**Comment by Admiral-Danforth** [comment]
> outfit "Turreted Flamethrower"
	category "Turrets"
	cost 190000
	thumbnail "outfit/flamethrower"
	"mass" 9
	"outfit space" -9
	"weapon capacity" -9
	"turret mounts" -1
	weapon
		sprite "effect/explosion/small"
			"frame rate" 60
			"no repeat"
		sound "flamethrower"
		icon "icon/flamethrower"
		"submunition" "Flamethrower Projectile"
		"inaccuracy" 12
		"velocity" 9
		"lifetime" 5
		"reload" 2
		"firing energy" .1
		"firing fuel" .25
		"firing heat" 4
	description "A crude but impressive-looking weapon, the Flamethrower ignites your hyperspace fuel and directs a stream of it towards your adversaries. The damage it does is relatively minor, but it can be useful for causing a target that is already operating near its thermal capacity to overheat, temporarily taking it out of the fight." The mechanics at Smugglers Den managed to mount it on a turret increasing its effectivity.

**Comment by DingusShingleton** [comment]
@Admiral-Danforth Protip: Above the text entry box is a tab called "Preview". Try it sometime.

**Comment by Admiral-Danforth** [comment]
I'm aware. Also when you highlight something and turn it to code does it really have to go into that inset mode. @Bladewood you will need third party tools for this

**Comment by LocalGod79** [comment]
@Admiral-Danforth i don't think you understand what @Amazinite and i are telling you:  M.Z. has already said that the Flamethrower is borderline over-powered - **a turreted version is _not_ going to make it into the base game**...

no Flamethrower Turret.

no means no.

ftr; i'm fully capable of creating balanced outfits of a wide variety, and have even had some implemented.  please don't waste my time with ill-considered and incomplete lists of specs...

i think a Navy License would be difficult to fake since it's recorded in Navy records (mostly as a salary) - not a card in your wallet.

**Comment by Bladewood** [comment]
ftr, I was just telling @Admiral-Danforth how to make a proper flamethrower turret, I was not suggesting the addition of the turret into the base game.

**Comment by Admiral-Danforth** [comment]
I was aware of what you were saying, but I was not replying to what you said.

**Comment by KiLEdEnNis** [comment]
the only way I ever managed to disable an Arfecta; Flamethrowers
if you can keep a ship disabled forever like this (similar w/ ion damage) it'd be OP

**Comment by Bladewood** [comment]
@KiLEdEnNis victory through 128 skylances.

**Comment by Johny-Cash** [comment]
1 modified shipyard

**Comment by KiLEdEnNis** [comment]
@Bladewood well, I did cheat w/ like 4 Antimatter Cannons so ye :P

**Comment by Admiral-Danforth** [comment]
I've used an all Archon fleet and they killed each other with the Antimatter Cannons.

Whoops

**Comment by LocalGod79** [comment]
this is not a Steam development thread - please take your anatomy measuring somewhere else.

**Comment by LocalGod79** [comment]
too bad i couldn't get any serious feedback from @endless-sky...

thanks; @Admiral-Danforth, @Bladewood, @KiLEdEnNis: time and place, kids - this isn't *ever* the place for tangential conversation (that M.Z. is going to have to sort through before he considers merging).  now you have to wait **_even longer_** for the intended new content.

ftr; the purpose of this pull request was to create an independent outfitter that could be added to **_in the future_**, and introduce an outfit (or two) that would sate a long standing request ("all-stop").

**Pull request closed without merging**
