### PR TITLE
New system at far south

### PR DESCRIPTION
**Pull request by Wyrdean**
Adds a single huge and intricately designed system, for the purpose of adding more fringe systems and to serve as an easter egg of sorts. Something interesting to find and explore, but also doesn't impact the game as a whole.

Cords are: -253 635
The system is located just in jump drive reach from Sadr, parked right on a bright star cluster.
However, should it be required, the system can quite easily be relocated within minutes.
I give permission for this system to be used in anyone's missions or new species should they like.
image
image

### CODE REVIEW

**Comment by Maddremor** [comment]
That's a lot of circular orbits like beaded bands that are clearly artificial (Whose name escapes me. Rose-something?). This is arguably a mega-structure in addition to being a star system. What is the explanation for this huge thing?

**Comment by Wyrdean** [comment]
> That's a lot of circular orbits like beaded bands that are clearly artificial (Whose name escapes me. Rose-something?). This is arguably a mega-structure in addition to being a star system. What is the explanation for this huge thing?

This system is made to look engineered, so I'm glad it looks that way to you. You're asking a lot of the same questions I'd like the player to ask when finding this mega-structure as you put it. I've left it open-ended, but it was clearly constructed by quite an advanced species, on level or higher than the quarg. Perhaps this was an early demonstration of power, the construction of this garden.

**Comment by unjown** [comment]
@Wyrdean suggestion for NPC..

pug afecta 
or
kahet ship (heavy )

**Comment by unjown** [comment]
how about just a pug system?

**Comment by Maddremor** [comment]
> 
> 
> > That's a lot of circular orbits like beaded bands that are clearly artificial (Whose name escapes me. Rose-something?). This is arguably a mega-structure in addition to being a star system. What is the explanation for this huge thing?
> 
> This system is made to look engineered, so I'm glad it looks that way to you. You're asking a lot of the same questions I'd like the player to ask when finding this mega-structure as you put it. I've left it open-ended, but it was clearly constructed by quite an advanced species, on level or higher than the quarg. Perhaps this was an early demonstration of power, the construction of this garden.

Yeah, but it's a very big thing with no explanation for how or why it exists. If it were a part of a story, it could be interesting in a similar way as a ringworld is, but like this it's just a dead end. What is the point of it from a narrative or game design perspective? An easter egg is generally something small and hidden acting as a reference to something or a joke from the developers to the inquisitive player.

**Comment by Amazinite** [comment]
I'm not really interested in merging content into the game with no explanation as to what it is then saying "oh, someone can make use of this later." If someone wants to develop a story that includes a system like this then that's reasonable (although I will say I don't really like the look of this system), but to add such a system first then create a reason for it later is a no-go from me.

**Comment by Wyrdean** [comment]
> > > That's a lot of circular orbits like beaded bands that are clearly artificial (Whose name escapes me. Rose-something?). This is arguably a mega-structure in addition to being a star system. What is the explanation for this huge thing?
> > 
> > 
> > This system is made to look engineered, so I'm glad it looks that way to you. You're asking a lot of the same questions I'd like the player to ask when finding this mega-structure as you put it. I've left it open-ended, but it was clearly constructed by quite an advanced species, on level or higher than the quarg. Perhaps this was an early demonstration of power, the construction of this garden.
> 
> Yeah, but it's a very big thing with no explanation for how or why it exists. If it were a part of a story, it could be interesting in a similar way as a ringworld is, but like this it's just a dead end. What is the point of it from a narrative or game design perspective? An easter egg is generally something small and hidden acting as a reference to something or a joke from the developers to the inquisitive player.

Part of why I submitted it as a pr was to get it out there so that it could be used for something and not for it to be immediately ready to merge, It's been recommended many times that it could be a pug system, perhaps a pug homeworld. I don't mind how it is used.
Its purpose from a game design perspective is much the same as the previously mentioned ringworlds, to show off how powerful a species is and what they are capable of.

**Comment by Amazinite** [comment]
> Part of why I submitted it as a pr was to get it out there so that it could be used for something and not for it to be immediately ready to merge

I'll say that that's not really the proper use of a pull request. If you have an idea, an issue or discussing it on Discord is more appropriate than opening an PR.

**Pull request closed without merging**
