### PR TITLE
chore: Code style fixes

### PR DESCRIPTION
**Pull request by tibetiroka**
Additional code style fixes that showed up after #7216, detected using #7147. 

### DO NOT MERGE THIS PR UNLESS #7147 IS ALSO GETTING MERGED.

I'm using the style checker script on the master branch to detect these issues, so separating the merge of these PRs would only result in me making a new PR when an issue shows up (which I'm getting tired of). Unfortunately, since so many code PRs don't sync with master and don't have the previous fixes yet, it is nearly impossible for me to check the PRs themselves.

I will keep updating this PR with fixes until these checks are automated (or the script PR is closed, which is not _that_ likely).

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
~~For my defense, this one was quuyykk's doing~~
This is a style only change and I dont see any problems with it, once the other PR is merged we can merge this.
Indeed we wouldnt want to merge it right away and have to open yet another PR afterwards.

**Comment by Hurleveur** [comment]
Btw if you mark this as a draft, it cannot be merged

**Comment by tibetiroka** [comment]
I didn't want to make this PR a draft since it is ready for merging, it is more of a personal preference to not have this merged too early. I made the _other_ style fix pr a draft because that gets new kind of fixes, while this one only follows master.

I don't know if this distinction makes sense, but whatever. Hopefully it will get merged before this becomes a problem.

**Comment by tibetiroka** [comment]
Closing this PR because the fixes are now tracked in the style checker PR.

**Pull request closed without merging**
