### PR TITLE
List required license alongside the cost.

### PR DESCRIPTION
**Pull request by alextd**
**Feature:** 

## Feature Details
A simple one: List the license requirement for an outfit or ship alongside the credit cost 

## UI Screenshots
image
image0
It does not show licenses for your ships:
image

(If something ever requires two licenses, it'll take two lines. Trying to cram multiple into one line would not work as soon as there's too many to fit.)

## Usage Examples
It's just a tiny UI improvement, I think. The requirement is only listed in the description right now. That's not quite visible enough for me.

## Testing Done
N/A Pretty simple

## Performance Impact
N/A

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
Nothing to say except great.

**Comment by quyykk** [comment]
I'm not sure it makes sense to have two places where the licenses are displayed. Ideally we should only have one, and honestly I prefer the description one but that's just my opinion.

**Comment by alextd** [comment]
It could go away once you have the license (though it does remain in the description)

It could also be boldened in red or something to show "you can't buy this yet!"

**Comment by tehhowch** [comment]
I'd be fine with including them when the player does not yet have them, AND either the description is minimized OR the license has a cost. That way the common case will see no changes.

**Comment by MasterOfGrey** [comment]
> I'd be fine with including them when the player does not yet have them, AND either the description is minimized OR the license has a cost. 

This conditional presentation makes the most sense to me.

**Comment by alextd** [comment]
Gee, the code for item info does not like adding conditionals much. I've thrown in code to handle this, but it's passing a boolean through a few places for this one purpose.

imageimage

After editing files so the Remnant license costs money:
image

And once I got the license:
image

---

The license I think should remain in the Map ship display. But code for that is **not written** because that's another bool to pass along the chain and that's getting bloated.

image

(Though the Map outfit display is unaffected, as it only shows attributes, not costs:)

image

**Comment by warp-core** [comment]
@alextd I've made some slight changes to make things a bit easier to read (hopefully) by not passing the depreciation objects separately to the player object in ShipInfoDisplay.
I'm not really a fan of passing the player object around to begin with, but it's already passed into OutfitInfoDisplay anyway, and we do need quite a few things from it.

**Pull request merged**
