### PR TITLE
Merged main thing to other thing...

### PR DESCRIPTION
**Pull request by toilethinges**

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
should we ignore this...?

**Comment by Amazinite** [comment]
Everyone must know that the main thing was merged to the other thing.

**Comment by toilethinges** [comment]
@KiLEdEnNis, yep, just me being a half noob to Github and pressing the wrong button...

**Comment by Lineth** [comment]
i think you went into too much detail here

can you simplify it for me

**Pull request closed without merging**
