### PR TITLE
new map region labels

### PR DESCRIPTION
**Pull request by Aurelite**
second half of #3684, labels only

screenshot from 2018-04-14 20-40-45

### CODE REVIEW

**Comment by jafdy** [comment]
I don't know, I like the cursive labels.

**Comment by Amazinite** [comment]
The new galaxy image was a clear improvement over the old one, but these new map labels just seem like a matter of preference to me.

**Comment by Zitchas** [comment]
The map itself looks good, but I was also partial to the cursive. I agree with Amazinite, though. Cursive vs block is just personal preference.

**Comment by KiLEdEnNis** [comment]
that and it's harder to see now, the current labels look like you have some space pirate treasure map, which looks cool, while this doesn't really fit

**Pull request closed without merging**
