### PR TITLE
Saturn

### PR DESCRIPTION
**Pull request by ravenshining**
**Content (Artwork)**

## Summary

Seems odd that we don't have a sprite for this, so I made one. I made a composite image from Cassini (for the high res and shadow placement on the rings) and Voyager (for the full disc) imagery, and then ES-ified it.

Then I added it to Sol, along with Uranus, Neptune, and what of their moon sprites we have already.

Outer planet distances have been set to a sort of average between linear and logaritmic distance.  Periods of all planets and moons have been set or corrected where divergent.

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/file/d/1qWuvbbZPyvZW4puoCaiUl9yAmCmjkIzh/view?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/181
 
-----------------------
**Feature:** This PR implements one of the features detailed and discussed in PR #5222 

## Feature Details

The aforementioned PR had a lot of new moon sprites and new versions of sprites, but no Saturn sprite, and apparently the shading was off?  Whereas all this adds is a Saturn sprite, with proper shading, and placement of it and existing assets.

## UI Screenshots

At max zoom:
Screenshot_20210526_004149

Saturn, Tethys, Rhea, & Titan:
Screenshot_20210526_004242

Saturn & Jupiter:
Screenshot_20210526_004452

Uranus, Miranda, & Oberon:
Screenshot_20210526_004552

Not pictured: Neptune, which has been placed in this PR but we have no moons for it.

Map of Sol:
Screenshot_20210526_004705

## Usage Examples
`sprite planet/saturn`

## Testing Done
Flying to Sol and looking at the planets.

## Performance Impact
N/A

### CODE REVIEW

**Comment by Zitchas** [comment]
Looks very pretty!

**Comment by ravenshining** [comment]
Thank you.  I'm a little concerned it's too bright, but not sure if that's just because Saturn is bright yellow.  I followed the shading directions exactly, and then darkened it some more, but it still looks brighter than other planets?

Fortunately I can easily and non-destructively make any adjustments people may desire such as darkening it if requested.

**Comment by ravenshining** [comment]
Looking at the image data, I realised I could add up to 18% transparency to the rings without changing its appearance against a black background... so I did.  After some fiddling I settled on 9% transparency.

While I was at it, I darkened the dark side, and downsampled from the ridiculous 32-bit float/channel working space and 16-bit/channel render to a more sane 16-bit integer/channel working space and 8-bit/channel render to reduce file size.

Top post has been updated with fresh screenshots, including moon orbits.

**Comment by Amazinite** [comment]
I will note that I'm not a fan of how tiny orbits of the inner planets get in the orbit map, making it potentially difficult to select the correct planet that you want from the map, but I already have plans to add a mechanic that would allow for the hiding of objects from the orbit map, so in the future we could hide the orbits of the planets further out in order to give a more reasonable look at the inner planets from the orbit map.

**Pull request merged**
