### PR TITLE
Heliarch shield generation and hull repair

### PR DESCRIPTION
**Pull request by Arachi-Lover**
this PR includes military-grade shield generators/hull repair outfits exclusive to the Heliarch.
most* variants also now utilize these new outfits by default.

*the Nimble variant of the Neutralizer could not fit both the Overcharged Shield Module and the Overclocked Repair Module, so instead it kept it's Large Repair Module, only replacing the Shields.

thanks @beccabunny for the images

### CODE REVIEW

**Comment by MCOfficer** [comment]
Are there any assets for this? @beccabunny

**Comment by Amazinite** [comment]
We also need a high DPI PR.

**Comment by MCOfficer** [comment]
> 
> 
> We also need a high DPI PR and a copyright update.

that, too? why was this merged, then?

**Pull request merged**
