### PR TITLE
hai carriers + gatling gun +rail gun

### PR DESCRIPTION
**Pull request by Wrzlprnft**
The idea behind it:
The unfettered want to increase their military, and like the idea the alphas introduced to them with the carrier. Though they develop their own incarnation.
Strong, but slow.
Preview images:
Edit: the fighter changed a bit.
shop
docked
deploy
Proposed placement:
with the unfettered invasion in their largest fleets (carrier +6 fighters as solo variant?)
@LocalGod79 did the balancing
@Amazinite helped, too.
Edit: I thought it's time for feedback since i consider the carrier to be finished (so far. suggestions are always welcome)
and yes, it ended up being kinda beasty, but that's locals fault ;)

### CODE REVIEW

**Comment by toilethinges** [comment]
> Unfettered Hai Carrier and Fighter (not finished)

> Edit: I thought it's time for feedback since i consider the carrier to be finished (so far. suggestions are always welcome)

Better change the title.

Looks awesome!

**Comment by LocalGod79** [comment]
> and yes, it ended up being kinda beasty, but that's locals fault ;)

the relatively low weapons capacity combined with numerous turret mounts and hard points actually makes this ship more awkward to outfit than you think...

and you pay for it: 41.211M credits for the carrier makes it the most expensive Tier 1 ship, replacing the Shield Beetle (32.093M).

i actually think that the base crew could stand to be bumped by a dozen or two, but i'll wait for some more community feedback before making that adjustment (and filling in the ship descriptions)

**Comment by mdsmestad** [comment]
Good concept, I like it better than the arachnid

**Comment by onnikyla** [comment]
Looking good! It would bring some much needed carrier variety. Maybe it
could have one or two drones?

**Comment by onnikyla** [comment]
The carriers shields are maybe a bit too strong

**Comment by LocalGod79** [comment]
@onnikyla i apologize if this sounds sharp, but:

maybe *you* could create some Drone and Drone Carrier sprites? prepare some balanced specs? play test the results? and make a pull request, too?

reality check: the biggest problem facing Hai drones is that the Hai don't have tiny power.  the Pebble Core and Basrem engines alone take up 62 tons of outfit space, and the human combat drone has only 58 outfit space.  further, the smallest weapon the Hai have is 13 tons, so you are looking at 77tons of outfit space minimum (after the supercapacitor, so the Pulse Cannon will actually fire).

since Korath Far Lek 14s only have 65 outfit space, i feel like this would be *really* incongruous.

so, in addition to creating a new drone model/sprite/spec, and altering the existing carrier model/sprite/spec, we would also need to create an additional power plant model/sprite/spec for this:
 
> Maybe it
> could have one or two drones?

it's a lot of work for a suggestion that balances in one direction, while your next critique (too much shields, 7 minutes later) balances in the other.

**Comment by onnikyla** [comment]
I didnt mean it that way, just thought it would bring a little bit of
variety. Sorry if I offended you somehow. And I didnt mean that the shields
were too big as critique.

30.6.2016 4.48 ip. "LocalGod79" <notifications@github.com> kirjoitti:

**Comment by onnikyla** [comment]
Ill start working on a drone and a drone carrier as you suggested.

**Comment by LocalGod79** [comment]
again, i apologize if my reply came off salty.

i just wanted to point out that the reality of adding that tiny bit of variety is about two weeks additional work (for a group of a few of us that are familiar with what's expected - more, if you've never contributed to E.S. before) - and for something that would be of questionable value, since the carrier and fighters aren't going to be available in shipyards without some kind of future unlock missions with the Unfettered.

another major hurdle is that the Hai Fighters ring in at 1.407M credits - three times what human fighters cost.  Drones will be even worse.

i did take your proposition seriously, establishing what needs to happen for that proposal to be realized.

imho, it's just more trouble than it's worth for the time being. perhaps if someone wrote more plot for the Hai, more ships and outfits might make more sense...

**Comment by onnikyla** [comment]
Im actually happy that you mentioned that I could make somesort of drone
carrier. Ive had a lot of time lately. I have been thinking how could I
contribute. Thx for the idea!

30.6.2016 6.44 ip. "LocalGod79" <notifications@github.com> kirjoitti:

**Comment by onnikyla** [comment]
And what is program commonly used to make sprites?

**Comment by LocalGod79** [comment]
that is a discussion for:
https://groups.google.com/forum/#!categories/endless-sky/content-creation

**Comment by onnikyla** [comment]
I know, Im using my phone right now, thought this would be easier.

**Comment by onnikyla** [comment]
Just noticed if this gets added to the main version of the game there might need to be a description update, Pebble core description says: A Pebble Core is a miniaturized nuclear reactor, small enough to be installed in **any ship larger than a fighter**. The Hai developed this model for their smaller ships.

Just making sure you guys notice.

**Comment by LocalGod79** [comment]
> Just noticed if this gets added to the main version of the game there might need to be a description update, Pebble core description says: A Pebble Core is a miniaturized nuclear reactor, small enough to be installed in any ship larger than a fighter. The Hai developed this model for their smaller ships.

technically, "any ship larger than a fighter" *can* carry the Pebble Core - not all fighters can necessarily carry it (e.g. Boxwing, or Barb is rendered otherwise useless if installed) - it's a logical distinction that needs to be made.

**Comment by LocalGod79** [comment]
@Alkallid it's the "tier 1.1" tradeoff for only having one gun port and 19 tons weapons capacity, and the outfit space was compensated for the built-in turret to maintain the fighter's tier 1 balance.

**Comment by LocalGod79** [comment]
@Amazinite, @Wrzlprnft and i had a discussion via Steam chat, and settled on some names, the rest followed quickly.

some reasoning for arachnid nomenclature departure from hai insect named ships;
to create distinction between Unfettered (ships) and normal Hai.
arachnids are always carnivorous, the ones chosen: predatory.
care was taken to choose names compatible with hai linguistics.

i believe @Wrzlprnft has a new sprite for the Violin Spider on the way (to reflect the permanent Bullfrog A/M)

**Comment by mdsmestad** [comment]
@LocalGod79 I like the sound of it, Violin Spider

**Comment by LocalGod79** [comment]
a.k.a. Brown Recluse - very small and highly venomous.

i didn't put it in the conversation, but the carrier is called "Solifuge" a.k.a. whip scorpion, another arachnid that falls somewhere between spiders and scorpions, and again - highly venomous.

**Comment by Alkallid** [comment]
Just go with arthopos then.

**Comment by LocalGod79** [comment]
it's still technically an arachnid, its genome just falls between the two largest groups of them.

**Comment by Alkallid** [comment]
No I meant any future names for Hai ships will go along the arthropod theme.

**Comment by jafdy** [comment]
You will need to have this introduced after the Giftbringer is destroyed. Putting the fleet changes and adding the ships to the shipyard could be part of the `wanderers: unfettered invasion starts` event. The ships could be part of a `unfettered carrier` shipyard.

**Comment by Wrzlprnft** [comment]
We thought about putting it into the ` wanderers: unfettered invasion starts` event, but that one is currently @endless-sky 's playground. I guess it's now up to him where we put it, where he can use it.

**Comment by LocalGod79** [comment]
ftr; these ships have not beed added to shipyards; only Large Unfettered, and Unfettered Raid fleets, though @jafdy is perhaps correct that they should not be deployed until after the main story?

**Comment by mdsmestad** [comment]
So lovely, I just want to admire it.

**Comment by endless-sky** [comment]
I just added support for fighter bays to have a direction (left, right, or back) and a display side (over or under) at the same time. This carrier might be a good use for that - the fighters could be drawn under it but face sideways.

In terms of where it would show up in the game, my plan is for the Wanderers to have to hold the Unfettered at bay for long enough for the Eye to open and all their people to be transported to Korath space. So, halfway through that process would probably be a good time for a new Unfettered ship to appear to make things more interesting. Just let me know when you think you're happy with the balancing and I'll merge this PR in.

**Comment by Wrzlprnft** [comment]
What's the exact syntax for the new positsitions? before or after over/under, seperated by one space?

**Comment by Wrzlprnft** [comment]
screenshot_20160702_180555
It would look like this. Maybe if we move the middle fighter more inwards to the center, but i do like the round shape provided by the fighters side slightly more. Opinions of others?

**Comment by LocalGod79** [comment]
@Wrzlprnft perhaps having the Violin Spiders facing towards the centre of of the Solifuge would preserve the lines you had originally intended better?  even leave the front ones facing forward?

there is a Drone carrier in the works that could employ the new dual-tag bays (my imagination fired up as soon as i read of their existence) - i'm not sure that adding them to *this* ship really adds anything (and may actually take away from the original appearance/function if employed).

**Comment by Wrzlprnft** [comment]
by facing inwards, the colored fins are visible, but that also doesn't really add anything, in my opinion, since they shadowed differently than the main ship, because of the rotation.

**Comment by LocalGod79** [comment]
i think this is going to be the biggest issue with sideways facing under/over bays (especially over) - incongruous ship spright lighting...

**Comment by LocalGod79** [comment]
@endless-sky the Hai light Medium Warship drone carrier containment response to this Unfettered threat is nearing completion: would you prefer it to be added to this p.r or a fresh one opened?

**Comment by LocalGod79** [comment]
@mdsmestad, @Amazinite: please confirm the copyright.

**Comment by Wrzlprnft** [comment]
aka community content pack managed by local god

**Comment by mdsmestad** [comment]
Seems to check out. Do I need to do something in particular?

**Comment by LocalGod79** [comment]
@mdsmestad ideally you will email the source .xcf and .blend files for the Rail Gun, Rail Slug and Flea to M.Z. (so that he can add them to the assets) and specify that you are publishing them (and their derived game-sprites) under CC-BY-SA 4.0.

i believe "seems to check out" will pass until he merges, and needs the @2x sprites+assets.

@Amazinite just saying here that the copyright file reflects your publishing license (for the files copyrighted to you, as well as the ones i attributed as derived from your works) will probably be sufficient.

**Comment by endless-sky** [comment]
If you all think this is ready (or at least good enough to be tested by a wider audience) I can go ahead and merge it. That's the nice thing about 0.9.3 being an "unstable" release - things don't yet need to be perfectly tuned.

**Comment by LocalGod79** [comment]
the Hai ships don't spawn anywhere, and the new ships/outfits are not in 'yards/'fitters until the events you deem should place them make it so.

otherwise, i believe all of this is ready to go (and @Wrzlprnft expressed his completion some 10 days ago)

**Comment by endless-sky** [comment]
Done. In the merge comment I credited @Amazinite, @LocalGod79, @mdsmestad, and @Wrzlprnft to make sure they'll all get mentioned when I update the changelog; let me know if I missed anyone.

**Comment by Amazinite** [comment]
@Sinsling worked on the railgun stats with @LocalGod79 doing some touching up on them, so I would think that @Sinsling would be credited as well.

**Pull request merged**
