### PR TITLE
feat: Allow more bay orientations / facing-angles

### PR DESCRIPTION
**Pull request by petervdmeer**
**Feature:** This PR implements a feature where bays can get a custom facing-angle, besides the current/previous facing-angles forward, left, right and back.

## Feature Details
Bay is now internally using an angle instead of a facing (index) variable.
Standard angles like 90 degrees and 180 degrees are still written out as right and back.
Non-standard angles are read and written using the angle child keyword.

Added comparison operator to Angle-class for ship/bay-savegame writing of standard angles.

## Testing Done
Tested with attached savegame:
- load and save
- checked angles both in save-file (after re-saving) and in flight

## Performance impact
None expected, the angles used after this PR are the same angles as for left, right, back angles.

## UI Screenshots
Here is a screenshot of the "Twister" ship (as also provided in attached savegame) that uses the new angle functionality for two of its bays.
six_directions

## Usage Examples
Here is an example of a bay with a current/previous angle and another bay with a custom facing angle:
```
fighter 47 -61 under
	angle 45
fighter -47 14 under left
```
Attached savegame can be used for testing this feature.
[six directions.txt](https://github.com/endless-sky/endless-sky/files/4083399/six.directions.txt)

### CODE REVIEW

**Comment by Zitchas** [comment]
I like the sounds of it. Probably not an urgent issue, but useful nontheless.

How does this interact with the other projects that interact with fighters? Thinking mainly of default launch location one.

**Comment by Amazinite** [comment]
Given that having engine sprites be able to come out at arbitrary angles is a part of #4539, I'd think that the syntax for bay angles and engine angles should be the same, or at least as similar as possible. The current syntax in #4539 is:
```
"engine" <x> <y> <zoom> <angle>
	[over | under]
```
Whereas the suggested syntax for bays is:
```
"fighter" <x> <y> [over | under] [left | right]
	"angle" <angle>
```
For reverse compatibility's sake, engines can't move their zoom and bays can't move their over/under and directional tags. The rationale behind having the over/under tags be a child of `"engine"` is so that you don't always need to specify the zoom and angle just to specify the over/under as well. Swapping the angle and the over/under to match the suggested syntax here (i.e.
```
"engine" <x> <y> <zoom> [over | under]
	"angle" <angle>
```
) would mean that specifying over/under for an engine still requires you to also specify the zoom, but it would closer match the suggestion here (and I don't think it'd be impossible to parse `"engine" <x> <y> [over | under]` without the zoom being listed).

**Comment by petervdmeer** [comment]
The most generic way to make those keywords similar is to change the syntaxes to:

```
"engine" <x> <y>
	"angle" <angle>
 	[over | under]
	"zoom" <zoom>

"fighter" <x> <y>
	"angle" <angle>
	[left | right]
	[over | under]
	"zoom" <zoom>
 ```

The "bay" keywords would need to support over, under and left/right on the same line as well for backwards compatibility, and the "engine" keywords would need to support the zoom on the same line as well for backwards compatibility. But this seems to be the most explicit way to make the keywords look similar. (And as a bonus you also get the format on how to have carried ships drawn at a zoom.)

**Comment by petervdmeer** [comment]
> How does this interact with the other projects that interact with fighters? Thinking mainly of default launch location one.

I don't see any negative interaction with #4700 (which I think is the feature request you are referring to). If the default emission point would specify angles, then it can just use the same keywords as discussed here, but I would expect the default emission point not to use angles at all (and only allow forward-facing bays from the default emission point).

**Comment by petervdmeer** [comment]
@Amazinite This PR now also contains an update to parse the generic format as discussed above.

**Comment by petervdmeer** [comment]
I processed all review comments and did a short re-test to verify that the angles still get saved and loaded.

**Pull request merged**
