### PR TITLE
feat(ui): enhance maps with parked/stored item lists, system colors

### PR DESCRIPTION
**Pull request by flowers9**
**Feature:**

## Feature Details
MapShipyardPanel now lists parked ships in the ship list, along with number, just as MapOutfitterPanel does with stored outfits.  You can now restrict the item display by either items for sale or items in storage/parked (there is a fourth item in the key list).  When restricting it by for sale on the outfitter panel, it no longer shows items in storage.

The map colors for systems will also show systems with the selected outfit/ship in storage, taking precedence over being for sale (i.e., if it's both for sale and stored/parked, it'll display the system using the storage color).

## UI Screenshots
Shipyard before:
Screenshot from 2023-07-19 21-45-28
Shipyard after:
Screenshot from 2023-07-19 21-44-36
Outfitter before:
Screenshot from 2023-07-19 21-46-03
Outfitter after:
Screenshot from 2023-07-19 21-44-03
Example of parked ships not for sale:
Screenshot from 2023-07-19 21-39-10

## Testing Done
Tested the new clickable zone (it toggles, as with the sales selection, and each disables the other).  Ships that cannot be bought (but that are parked) are displayed correctly.  The interface appears to work as should, just clicking around on various things and seeing what items are listed.

## Performance Impact
Minimally slower drawing the map, caused by extra searching when calculating SystemValue().  Might be relevant if player storage/ship parking is particularly high (but probably not).

## Notes
I'm not all that fond of the color I used (a light green), but I was fairly limited in my choices because it has to be provided by MapPanel::MapColor().  I went with the color generally shown in the other key on the right (the .5 system value).

It's possible I should make the two toggles (sales only, storage only) independent rather than cancelling each other.  I dunno.

(Edited to put correct shipyard before image in and to add performance notes.)

## Links
Assets: https://github.com/endless-sky/endless-sky-assets/pull/147
High DPI: https://github.com/endless-sky/endless-sky-high-dpi/pull/370

### CODE REVIEW

**Comment by Hurleveur** [comment]
Good idea, I for sure like the sound of this

**Comment by flowers9** [comment]
Bringing it into line with #9046.

**Comment by flowers9** [comment]
I'd also like to make a case for changing the "Has no" color to be dark blue (the -1 system value), as it doesn't stand out as much, which would be easy to bundle this the rest of this.

Screenshot from 2023-07-20 09-22-23

**Comment by Hurleveur** [comment]
That'd be more appropriate for another PR if we do it I think
Could you rename the title to smth more explicit plz?

**Comment by flowers9** [comment]
Well, I have seen a PR to add a single space to a content file, so I guess that's fair enough.

**Comment by Amazinite** [comment]
Do you have a 2x image and new asset files for this updated image for the [high DPI](https://github.com/endless-sky/endless-sky-high-dpi) and [asset](https://github.com/endless-sky/endless-sky-assets) repos?

**Comment by flowers9** [comment]
I do not.  I just messed with the existing png, and haven't even looked at the high dpi stuff.

**Review by Amazinite — COMMENTED** [review]
Looks good as is. My only request is if you could make the storage color apply to uninhabited systems. All stored outfits are going to be in outfitters, which will display as colored on the map regardless of whether you have something stored there, but ships can be parked on any planet that can be landed on, meaning you can have otherwise uninhabited systems that should probably not use the uninhabited color key.

I have a ship parked in Algieba and in Zosma, but only the Zosma system uses the "ship is parked here" color.
image

**Comment by flowers9** [comment]
Okay, I found an online png->svg converter, and did the other two by hand in gimp, and pushed the changes to both repositories.  Lemme know if I made any mistakes, as that's all new to me.

**Comment by Amazinite** [comment]
If all you did was alter the existing png then you don't need to create a new svg file. The svg is the original asset file that this UI element was created from. The svg was created in inkscape, exported as a png, and then had some extra detail added to it in GIMP, which is where the xcf asset file comes from. We want to keep the original assets used to create all of our image content, so if you didn't actually change the svg asset then you shouldn't be overwriting it.

Similarly, if you used a separate xcf file to create this modified asset, then that should be a separate xcf file in the assets repository instead of overwriting the original xcf file. But if you used the original xcf file to create this modification, then it's fine if it's the same file so long as the xcf file contains the layers to recreate the old image.

**Comment by flowers9** [comment]
I didn't use any xcf file - I just modified the png file directly.
So, I should rename the xcf file I created from my png so something
else, and upload just that?

**Comment by Amazinite** [comment]
Yeah.

**Comment by Amazinite** [comment]
(Ignore the text over spilling the UI. I'm running an exe from this PR with a different PR's data.)
Looks good now with ships parked in uninhabited systems.
image
But the color remains even when focusing on a different ship model.
image
I'd think when focusing on a different ship model from the one you have parked, the color displayed should be "Has no shipyard." (Not revert to uninhabited, because then that makes the system harder to spot that there actually is something there. Sure, we have the dot that fills the system ring, but also having the system color not be uninhabited helps as well.)

**Comment by flowers9** [comment]
Good point!  I didn't consider that.  However, it's not very useful as is, because you can't unselect the selection on the map sales panel.  So, I added that in, too.

**Comment by flowers9** [comment]
Honestly, it's always bugged me you can't unselect on that screen, so I'm happy to finally add it.

**Pull request merged**
