### PR TITLE
fix(documenation): Remove duplicate copyright entries

### LINKED ISSUE #7711: duplicate copyright entries
### Location

./copyright

### Describe the issue

Thanks for maintaining the copyright and licensing information in one place!

During the upgrade of the Debian package, where there is a very similar file part of the packaging metadata, automated checks discovered that some file patterns are present in more than one stanza with different copyright holders.

I think a similar issue is present in the high-dpi repository, but perhaps for different set of patterns. Will report that separately when I get to it.

Here's the list. I hope this is not very difficult to fix.

 * images/outfit/brig*
 * images/outfit/fuel?pod*
 * images/outfit/gat*
 * images/outfit/jump?drive?(broken)*
 * images/outfit/plasma?repeater*   (three times)
 * images/outfit/proton?turret*
 * images/outfit/scram?drive*
 * images/projectile/korath?digger*
 * images/ship/auxiliary*
 * images/ship/barb*
 * images/ship/vanguard*
 * images/thumbnail/auxiliary*

### Expected content

Can't really propose a fix.

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR partially fixes #7711 

## Fix Details
In https://github.com/endless-sky/endless-sky/issues/7711 a number of duplicate (and even triplicate) copyright entries were identified. While some need clarification, many of them are fairly simple "someone made art, then someone else improved on it and listed it in the copyright under their name derived from the original, but didn't delete the old entry" sort of thing.

## Full list of duplicate entries reported:

- [x] images/outfit/brig*
- [X] images/outfit/fuel?pod*
- [x] images/outfit/gat*
- [x] images/outfit/jump?drive?(broken)*
- [X] images/outfit/plasma?repeater* (three times)
- [X] images/outfit/proton?turret*
- [x] images/outfit/scram?drive*
- [x] images/projectile/korath?digger*
- [x] images/ship/auxiliary*
- [X] images/ship/barb*
- [X] images/ship/vanguard*
- [x] images/thumbnail/auxiliary*

## Testing Done
Checked to ensure that the items for whom the entries have been removed still are present elsewhere in the file.

## Save File
This change cannot be seen in-game. Only by looking at the copyright file.

### CODE REVIEW

**Comment by Amazinite** [comment]
What's the checklist for? Is that stuff that still needs fixed?

**Comment by Zitchas** [comment]
Yes, the checklist is the list of things that have duplicates/triplicates, and needs feedback in the main issues thread from various people to help identify what the correct situation is. Mainly @beccabunny and @GefullteTaubenbrust2

**Comment by beccabunny** [comment]
I think that mine are the gatling, scram and brig. The first one is actually a mistake on my part, and should say derived from wrzl's model, with that one removed; the brig just needs pointed's entry removed; and the scram i think also needs the gatling's treatment

**Review by quyykk — APPROVED** [review]
That's all of them I think

**Comment by Zitchas** [comment]
I think I  might still need to check on the digger, but otherwise, looks good.

**Comment by Zitchas** [comment]
There. All the duplicates have been dealt with.

**Pull request merged**
