### PR TITLE
Wormhole links on map and automatic pathing through known wormhole links

### PR DESCRIPTION
**Pull request by guillochon**
This PR adds visible wormhole paths to the map for wormholes that the player has traversed previously. To accomplish this, I've merged half the "visited-planets" PR I submitted previously, but without the visual indication in the visited-planets PR when all planets in a system have been visited. This PR does two major things:

* First, it adds a thin purple path onto the map between two systems linked by a wormhole if the player has traversed the wormhole in the past.

image

* If a wormhole path is discovered, *the player will automatically be routed through it*, including their escorts, if they set a path for which using the wormhole is faster. This means that ships will jump to the wormhole-hosting system, then automatically "land" on the wormhole in that system, then automatically continue to jump to the rest of the systems along their path.

image

There is only one outstanding issue that I'm aware of with this PR, and that is that escorts are aware of wormhole links even if the player is not. This is because the DistanceMap call for the escorts does not pass the player info to DistanceMap, so the escorts have no knowledge of which systems/planets the player has seen and/or visited (This actually appears to be an oversight for the pathing in general, the escorts will path through systems the player has never visited/seen even without this PR).

### CODE REVIEW

**Comment by egilburg** [comment]
Perhpas when you look at whole map, wormhole paths should only have a short arrow or purple symbol "W" next to the node. But if you click on either end of the path then the whole path becomes drawn for that wormhole. Likewise, if you are on a plotted course that includes travelling through a wormhole, then that wormhole path is fully drawn as part of the plotted course.

I'd prevernt UI clutter by wormhole paths being drawn over normal map, but still indicate there is a wormhole and fully show it when it's used.

**Comment by guillochon** [comment]
@egilburg Sure, something more subtle would be nice. I'd personally prefer to "fade" the wormhole line between the two systems, but it appears there's no easy way to do that. Open to suggestions.

**Comment by endless-sky** [comment]
It looks like this would require a "link" to be added in the map between ever pair of systems connected by wormholes. That should not be necessary, especially since links are always bidirectional but a wormhole link may be unidirectional (if it has more than two exit points).

There would also need to be some limit on how long the lines for the wormhole links can be, to avoid drawing the Pug wormhole line.

**Comment by guillochon** [comment]
@endless-sky Yes you need to add the "link" explicitly to those you'd like to show up on the map. I did this specifically because we don't want to show the Pug wormhole link, this gives us control over which ones appear and which ones do not.

How can a wormhole have more than two exit points? None like that exist in the game currently...

**Comment by guillochon** [comment]
Also here's a revised way of showing the wormhole path, is this better @egilburg?

image

**Comment by guillochon** [comment]
OK I'm satisfied with this one, what do you think guys?

image

**Comment by guillochon** [comment]
BTW @endless-sky, one can easily modify the logic to accommodate one-way wormholes, if any are added to the game.

**Comment by egilburg** [comment]
looks good :+1:

**Comment by endless-sky** [comment]
I've checked in a change that makes pathfinding include wormholes (3225ee5). Your implementation had quite a few issues with it - it would allow ships to hyperspace jump along the wormhole path, it would allow missions itineraries and map outfits to use the wormhole, and it would break quite a few sections of the code that rely on a system's "links" only being the hyperspace links. But if you merge your path drawing and visited planets changes on top of that, I can merge that in.

**Comment by Wrzlprnft** [comment]
Looks great, yes, and everybody will love you for the auto-routing through wormholes.

**Comment by guillochon** [comment]
Closing in favor of https://github.com/endless-sky/endless-sky/pull/404,

**Pull request closed without merging**
