### PR TITLE
New Human Stations sprites

### PR DESCRIPTION
**Pull request by beccabunny**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR, following https://github.com/endless-sky/endless-sky/pull/4644 , improves station2, 3 and 4 with new models, which (if anybody tries to) will be easier to animate. The original station5 and 6 were only slightly modified to have the lights made in Blender instead of gimp, following the pattern of making animating the stations easier. If these are added, I will probably try to make more stations sprites since the current ones are used many times
Screenshot (542)
Screenshot (544)

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: 
[stations.zip](https://github.com/endless-sky/endless-sky/files/3902530/stations.zip)
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/103

### CODE REVIEW

**Comment by jafdy** [comment]
The new station2 image required me to look for the forth solar panel as it was quite well camouflaged against the ring of the station.

**Comment by beccabunny** [comment]
Is that a problem? It's a space station, it's very likely some parts will be covered in shadows while others won't

**Comment by jafdy** [comment]
It was a comment. Nothing more.

**Comment by finite-galaxy** [comment]
> If these are added, I will probably try to make more stations sprites since the current ones are used many times

Sounds great! And yes, there are sixteen space stations in human space, but only eight sprites. For future reference:
```
station0: Lagrange
station1: Kraken, Phoenix, Wyvern
station2: Carbuncle, Charon
station3: Arachne, Fenrir, Muninn
station4: Hydra, Triton, Typhon
station5: Huginn, Oberon
station6: Charybdis, Leviathan, Smuggler's Den
station7: Alexandria
```

**Pull request merged**
