### PR TITLE
Coalition Pilgrimage dialogue: minor grammar fix

### PR DESCRIPTION
**Pull request by opusforlife2**
**Bugfix**

The sentence wasn't correct as per Coalition grammar. It was pretty easy to spot, since the rest of the dialogue is written so consistently with this grammar.

### CODE REVIEW

**Review by Zitchas — APPROVED** [review]
This looks like an appropriate typo fix. Especially since the sentence has duplicate "Wish".

**Comment by Zitchas** [comment]
Sure, its a typo too.

**Review by Arachi-Lover — APPROVED** [review]

**Comment by Saugia** [comment]
That spelling is intended.

**Comment by Zitchas** [comment]
It's a weapon of desperation, of sorts... I'm sure the Korath would like to go back to a Lagrange hyper heaver, with all that implies. They certainly have the *knowledge* for it. But their industrial capacity is still rebuilding. Until then, Langrange it is.

**Comment by Saugia** [comment]
We can't commit directly, at least we shouldn't be, do yes new pr. Also, preferably stop concersation on this one, or any merged pr in general.

**Pull request merged**
