### PR TITLE
Help balance the Mind battle

### PR DESCRIPTION
**Pull request by TheGiraffe3**
# **Balance**

This PR addresses the problem described in issue #7896. 

## Summary

In `Wanderers: Mind Escorts`, I added one Tempest.

In `Wanderers: Mind 6`, I took away from the hostile Mereti fleet one 128, one 64, and one 32. 

In `Wanderers: Mind 6`, I also added to the friendly fleet two 16s, but took away a 128. 

## Screenshots
None

## Usage examples
N/A

## Testing Done
None

## Save File
This save file can be used to test these changes:
[Melchior.Jack.txt](https://github.com/user-attachments/files/15845773/Melchior.Jack.txt). Courtesy of the issue. 

## Artwork Checklist
N/A

## Wiki Update
N/A

## Performance Impact
Fewer mines.

### CODE REVIEW

**Comment by Quantumshark** [comment]
I've never seen the Quarg have any difficulty with the Mereti in `Wanderers: Kor Efret 3`, so I'm not entirely sure that portion of this change is necessary. The Quarg are planned to be rebalance soon, so the mission will need adjusting then anyway.

As for the Mind, that mission probably does need changing, but I think you're overdoing it here.

**Comment by Hurleveur** [comment]
I totally agree the mind battle is too hard and relies too much on random spawns and luck in general. For the other missions I'm not sure, I remember a Quarg one where the reinforcements take a bit to come, and the ES isnt exactly agile enough to avoid combat, is it?

**Comment by Quantumshark** [comment]
With these changes, for the Mind battle, you have:
3 hurricanes, 4 derechos, and 5 tempests, plus 1 512, 2 256s, 3 128s, 4 64s, 7 32s, and 10 16s.
Against:
3 512s, 4 256s, 4 128s, 5 64s, 7 32s, and 10 16s.

That's 10 heavy warships, 12 medium warships and 17 light warships against 7 heavy warships, 9 medium warships and 17 light warships. That's a pretty major advantage even before you account for the presence of the player or the fact that the only spawns in the system during the mission are friendly.

**Comment by Quantumshark** [comment]
> What ship have you been flying?
Various single ships on various occasions. The ones I can remember being a Derecho, a Peregrine, and an Autumn Leaf.

> So here are the total on-paper stats for the Wanderers: Kor Efret 3 battle before my changes.

As far as I can see, you're not accounting for regen or ionisation, both of which I think favour the Quarg when included. Plus, if you're including the full theoretical DPS of the minelayers, that's probably also going to be misleading, as they struggle to achieve anything like that in practice. You also seem to be just summing shield and hull DPS, whereas in reality a weapon doesn't do both at once.

> If first last lands to recharge after losing shields, hull, and a few Efret allies, then all the surviving Mereti get completely recharged.

This may be your issue. I know this can be an advantageous strategy in some battles; it follows that it can be disadvantageous in others. I don't think I ever land as part of this battle, so maybe that's the cause of the issues you're experiencing.

**Comment by Hurleveur** [comment]
I don't think that's smth we should take into consideration much, looting korath ships in remnant space (or just doing wand missions/uhai tributes) can easily give you plenty of cash, and I dont think it should be expected to never have to farm a little bit of money.

**Comment by danaris** [comment]
> The real question is, are we assuming the player is flying a T1 Superheavy (Emerald Sword) or a T2 Heavy (Derecho)?

Should we be assuming _either_ of those things?

Those two ship types play quite differently, and unless we're going to be giving the player explicit in-game recommendations for their loadout before they're committed to this battle (ie, when they can still easily head back and buy/outfit a different ship), I think designing a major battle like this with specific assumptions about flagship capabilities, rather than broader assumptions about flagship power level, is likely to (continue to) lead to player frustration.

**Comment by Hurleveur** [comment]
Not just an SB, they should at least get a Derecho or maybe an ES if you know that you're doing, that should be the lowest point I think.
An SB would be useless in this battle that pierces shields

**Comment by Saugia** [comment]
Because this is an important balance concern and brought up, it would be greatly helpful if for the cases you are adjusting the fleets that you have save files we can use to playtest said changes. It's one thing to have changed the fleet definition by numerical or presumable data, but another to play through it love. (In general, when doing balance changes, a PR should have a save to test said change).

**Review by Quantumshark — APPROVED** [review]

**Pull request merged**
