### PR TITLE
fix(content): Shorten descriptions for brig & luxury jobs

### PR DESCRIPTION
**Pull request by bene-dictator**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR shortens the text of a couple of human jobs requiring brigs and luxury accommodations. Thanks to Hurleveur and Arachi for pointing it out.

I'll also take a look at other ones again to see if they need to be shortened in this PR. I've submitted it now because it's easier for me to test. 

## To-do
- [ ] Test it!

### CODE REVIEW

**Comment by Zitchas** [comment]
Doesn't this remove valuable information, namely what system this is going to? I think I prefer the original text that will specify both destination planet *and* system.

**Review by Zitchas — APPROVED** [review]
That looks good to me. Thank you for retaining the detail.

**Comment by bene-dictator** [comment]
Hahaha, I still wasn't able to test it because of the stuff with ESL2 yesterday. Well, if it's still too long, I'll make another PR.

**Comment by Pointedstick** [comment]
FWIW the original reason for including "to stand trial" in the description was to justify the mission being timed. Can't miss the court date!

**Comment by bene-dictator** [comment]
If I need to shorten these again I'll remember to add a bit to the dialog for the court date.

**Pull request merged**
