### PR TITLE
Ember Waste Raiding Economy Adjustments (aka changes to the cargo for Remnant and Korath Raiders, and adding missing ships to fleets)

### PR DESCRIPTION
**Pull request by Zitchas**
**Content**

## Summary
Some people have noticed that the Remnant and Korath fleets have a rather odd selection of cargos that don't seem to entirely fit the story. This PR adjusts this by limiting the Remnant and Korath Raider (Ember) fleets to carrying relevant cargoes. This represents the fact that the Korath are primarily interested in gaining Remnant resources; while the Remnant are most interested in gaining Korath outfits.

## Details:
Changes:
- Adds outfitter list for Ka'Het and Korath Exiles (these are not intended to be "for sale" outfitters, just lists of outfits common to their respective fleets)
- Adds the Ibis, Petrel, and Tern to Remnant fleets
- Specifies the cargo for Remnant fleets
- Specifies the cargo for the "Korath Ember Waste Raid"
- Adds a few more words to the vocabulary for Remnant fleet names

The cargo for the relevant fleets has been set to:
- commodities Food Metal Plastic "Heavy Metals"
- outfitters "Korath Basics" "Korath Exiles" (and for the Remnant, "Ka'het")

This covers several situations
- Cargo they are carrying as bait / trade resources
- Cargo they are carrying after having raided.
- Mix of cargo they are carrying for when they raid and get some, but also recover some of the resources they brought with them.

## Save File
Any pilot with access to the Ember Waste can see these changes via anything with a cargo scanner.

## PR Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by LorenzoBolla** [comment]
When you ask about the Ka'het to the Remnant, they say they haven't met a live one and simply found crashed shells on their planets. Is that going to be revised? Because, otherwise, it'd make little sense to have their outfits on cargo lists.

**Comment by Zitchas** [comment]
Technically, this falls into the territory of "Telling the truth but not necessarily how everyone else would see it." : Due the Ka'het being unstopping killing machines that attack without provocation, the Remnant have never met a live Ka'het itself. Mostly because the process for meeting one involves blasting the ship it is a part of to pieces, with invariably lethal results. So what they don't say in that statement is that they are the reason why some of those crashed shells are on the planets, and at least some of them are very fresh - only minutes, maybe hours since they fell out of the sky...

Which, if one thinks about it, should be fairly obvious: The Ka'het are very much present - it's hard to travel in the graveyard and *not* meet one. If you consider getting attacked by one to being meeting it, that is. But the Remnant are being quite truthful when they say that they have never face-to-face met one.

**Comment by WarlordMike** [comment]
Looks good and makes sense. I'm all for this.

**Review by WarlordMike — APPROVED** [review]
Looks great and makes sense. Would love to see this happen.

**Review by Pointedstick — APPROVED** [review]
Looks good to me.

**Pull request merged**
