### PR TITLE
[BUG FIX] Fix slow ships unable to jump.

### PR DESCRIPTION
**Pull request by 1010todd**
-----------------------
**Bugfix:** This PR addresses issue: #8693

## Fix Details
Due to a recent commit slower ships were sometimes unable to use hyperdrive/scram drive jumps because AI turning have lower precision making it stop turning before the game consider it aligned. Because the game check for jump alignment by ship's own turn rate and check if the ship will be perfectly aligned in the next frame low enough turn rate means AI will cut off before actually reaching the step-before-perfect.  

This fixed it by adding minimum value for TurnRate() at where jump alignment is being considered to "fake" a larger next turn step making the game think the ship will perfectly align in the next frame. From testing the imperfect alignment shouldn't be visually noticeable unless you really*3 look for it.

Gamerule is somewhat left over from testing but I decided to keep it in case someone want to play around with it or they somehow run into problem even with current minimum.

## Testing Done
Tested with extreme end of slow(2 in-game turn) and fast(240 in-game turn) ships. All works fine.

## Save File
This save file can be used to verify the bugfix. The bug will occur when using any commit after 725b1b2, and will not occur when using this branch's build.

[AAA Jumpbug test~~noplugin.txt](https://github.com/endless-sky/endless-sky/files/11330612/AAA.Jumpbug.test.noplugin.txt)

### CODE REVIEW

**Review by warp-core — COMMENTED** [review]
I don't think this should be a game rule. Even if I did, your description doesn't seem very good. It doesn't give any indication of what quantity the value corresponds to; it seems essentially impossible to even estimate what impact any change will have.

I think instead of what is done here, the logic of "within one turn step" should be included in `AI::TurnToward`, that is, either stop turning when *both* the dot product of the unit vectors is sufficiently close to 1 *and* the current direction is within one turn step of the target direction.

**Comment by Zireael07** [comment]
> I don't see much negative to it being a gamerule other than the game being a few bytes bigger'

Problem isn't bytes, problem is users/devs not knowing what the rule does

**Comment by mOctave** [comment]
So, when the Millennium Bridge was opened in London, they found out the hard way that with ~250 people on it it would start swaying, and so they had to close it and make exceptionally costly adjustments to reduce the swing.

This feels like the Millennium Bridge, but instead of making it sway less, we're banning more than 200 people from setting foot on the bridge at one time* – which will work very well, most of the time, and then probably eventually fail spectacularly.

This is definitely far better than nothing, but I feel like there should be a better solution here.

\* Although, of course, the actual number is left to players/content creators to decide, in this case

**Comment by petervdmeer** [comment]
Closing due to merge of [a parallel fix](https://github.com/endless-sky/endless-sky/pull/8701).

**Pull request closed without merging**
