### PR TITLE
Some Swizzle Masks

### PR DESCRIPTION
**Pull request by Ferociousfeind**
**Content (Artwork / Missions / Jobs)**

## Summary
The Kor Sestor warships seem to be covered in rust, alongside their actual red-orange-yellow colored fins/greebles. Currently, when the player captures one of these ships, or through some other method these ships end up with a swizzle, the reddish-brown and yellowish coloration of their tinted-neutral-color metal plating become different janky colors, vaguely following the red-orange-yellow color scheme (because that is how swizzling works).

With the addition of swizzle masks, these ships (plus the Scrapper, which also has significant rust) can have their rusty sections masked out, so that only the painted parts get painted.

## Save File
N/A, any save file which has ownership of Sestor ships should have the swizzle mask applied automatically, as it is attached to the reference of the original sprite, rather than called upon by some data in the save file. Or open up Omnis, the thumbnails as they appear in the shipyard have swizzle masks too.

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified (These images barely belong to me- I just painted over the ship images to highlight the swizzling reds, oranges, and yellows. It's fine to not credit me)
 - [ ] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/379

### CODE REVIEW

**Comment by EjoThims** [comment]
Before and after shots for the PR would be good.

**Comment by Ferociousfeind** [comment]
Oh, duhh. Here, korathy goodness (and bonus scrapper)

Merchant-swizzled ships, before PR:
image
image

after PR:
image
image

(The scrapper rust is either very subtle, or the mask isn't working...)

**Comment by Ferociousfeind** [comment]
Ugh, hold on, I suspect the scrapper might be named something differently, let me check...

**Comment by Ferociousfeind** [comment]
image

The mask is now working! The swizzling is more subtle than before, which I don't like, so I will have to fuss with the pixels a bit more...

**Comment by EjoThims** [comment]
Works really well for the Scrapper, not for the Sestor.

Just too little and too subtle, especially to still carry around the solid rust like sections.

**Comment by Ferociousfeind** [comment]
Those "too little and too subtle" parts are all the swizzled parts of the sestor ships... they _are_ mostly red with _rust_

kar ik vot 349

**Comment by EjoThims** [comment]
Which is exactly why only swizzling those bits instead of the whole rust pattern doesn't work.

Actually seeing it just really drives that home.

**Comment by MasterOfGrey** [comment]
It doesn't actually strike me as obvious that those sections are *rusty*, nor to me does it actually make a lot of sense.

It's not as if the Sestor ships are particularly old - their fight is old, but they're semi-autonomous war drones built to be thrown into battle until destroyed, and continuously replaced.
Which suggests to me that most Sestor ships are probably newer than your starting shuttle.
I'm also under the impression that they're manufactured in space, though I could be wrong about that, but that too makes me wonder if we should really be characterising them as "rusty"...

**Comment by bene-dictator** [comment]
I believe all of the Sestor drones are manufactured on Sestor Ikfar, and the Exiles disable the factories in the Wanderer campaign.

Nonetheless, I agree that it's not rust on the hulls of Sestor ships.

**Comment by Zireael07** [comment]
Huh, it definitely looks like rust... so what is it supposed to be?

**Comment by bene-dictator** [comment]
Some exotic Korath hull plating, maybe?

**Comment by EjoThims** [comment]
It definitely looks like rust, probably even using patterning made to be seen as rust, but I agree that it's probably meant (and appropriate, even if I'm wrong about initial intent) more as patterning within Korath color schemes than as directly representative of literal rust.

That's why I say "rust like" and "rust pattern" instead of "rust" ;)

**Comment by Zireael07** [comment]
I'd change the texture/patterning then to look less like rust. E.g. more yellow or orange than brown/red

**Comment by Ferociousfeind** [comment]
These korath warships are equipped with banishers, warders, and thermal repeater turrets, all of which have bases (a significant portion of the hardpoint sprite) which blend in with the unswizzled korath hull plating. hardpoint sprites... don't swizzle. So I suspect the rusty-brown and aged-yellow-pale colors are not meant to be part of the red-orange-yellow coloration of the ships.

**Review by Saugia — APPROVED** [review]
While I don't agree with the reasoning that the current colored parts of the ships are "rust" or similar (see Grey's comment), I do believe that the overall aesthetic looks better if we just swizzle smaller bits on the Automata ships. The color difference to help clarify government is still there, which is the more important part of a ship's color than whether or not it fits an indication of "rust" or not. Appearance-wise, this is more pleasing.

Scrapper looks fine.

Keep in mind though that this is more-so true for this specific example with the Automata, as I don't believe other factions would have the same result using this method. (Perhaps I'd like to do similar for the Gegno at some point, though.)

**Comment by Hecter94** [comment]
<details>
<summary>It definitely looks like Rust</summary>

image

image

image
</details>

<details>
<summary>Even the "non-rusty" bits of the hull have post-processing on them to make them look rusty:</summary>

image

image
</details>

So, is it rust? 
I think it is if we look at what's shown in-game.

We know that at least some Sestor drones are created planetside -
> The Kor Sestor prefer to develop planets rather than planting stations in space

> In the places where the Korath cities once were, the Kor Sestor have built massive factories with buildings sometimes close to a kilometer in height. In other places, the land remains undeveloped, but the factories are constantly expanding outward.`

We also know that they are repaired and refueled planetside -
> The Kor Sestor refineries are laid out in a grid pattern. Each square of the grid is a few kilometers on each side, and is laid out in exactly the same way: a central power station, surrounded by smelters and repair bays and factories and storehouses

> The caverns of the Kor Sestor are hidden deep under the mountains, but there are also a handful of refueling stations on the surface.

Since it seems like these drones are expected to, in some capacity, survive fights, be repaired, refueled, and sent back into the fight, it doesn't seem like the idea that they're simply built, thrown into the fight, killed, and replaced is entirely accurate.

It seems more likely that each drone is manufactured planetside, sent to patrol/fight, and returned to a repair bay once it is damaged, where it will be repaired, potentially even swapping out some of its armor plating for even older but still intact plating, refueled, and then sent back out to patrol/fight until it is damaged once again, repeating this process until it is either destroyed or so old/damaged that repair is no longer feasible. At this point, it will be replaced by a new drone.

If this is indeed the process, then the age of your average Sestor drone probably follows a bell curve, with brand-new drones being relatively rare, extremely old drones being relatively rare, and the majority being somewhere in the middle. 
Assuming that this is true and that your average drone is likely to be somewhat old and is likely to have been repaired a few times, there appears to have been ample opportunity for them to accumulate some degree of rust, either during the manufacturing process itself or while sitting planetside as they are being repaired or waiting to be repaired.

Since they visually appear to be rusty, and the lore surrounding these ships shows opportunities for them to become rusty, it makes sense to conclude that they are, in fact, rusty.

**Comment by bene-dictator** [comment]
Okay, that does look _like_ rust, but I can't believe the ships' hulls are made of rusty iron. I thought the texture was closer to the exile ships' textures.

**Comment by Ferociousfeind** [comment]
> Keep in mind though that this is more-so true for this specific example with the Automata, as I don't believe other factions would have the same result using this method. (Perhaps I'd like to do similar for the Gegno at some point, though.)

I didn't really look at many other ships, although ones worth scrutinizing are...
wanderer ships (with their weird colors)
remnant ships (there's nothing to swizzle)
other korath ships (they have a similar sort of color bias across the whole ship which probably shouldn't be swizzled)
and pug ships (which probably shouldn't swizzle at all)

**Comment by Saugia** [comment]
We talked about it and Wanderer and Remnant ships are fine as-is. Other Korath ships are fine too (especially because the civilian ones are specifically modeled for their swizzles). Pug ships, dunno. Maybe? But that's a discussion for another PR, since this one is for those above.

**Comment by Anarchist2** [comment]
The HDPI hasn't been updated with the correct Scrapper sprites.

**Review by ravenshining — CHANGES_REQUESTED** [review]
Masking out the whiter portions of the ship is good, but leave the darker bits to be swizzled.   Not swizzling brown is **inconsistent** with the 'olofez, which I specifically made this same brown as a reference to Sestor ships, and in order for it to be visually distinguishable when swizzled.  For **gameplay** reasons, it is helpful to recognise the overall colour of a ship at a glance, even when zoomed out.

Also, as these are new ships, these sections are **not rust**.  Given they are large sections, I would say this could be deliberate colouration.  The **Korath tend to be very expressive**, and the Sestor likely moreso than most.  Having Sestor ships have large sections of brown screams ostentatiously, "This ship is Sestor!"  Practically speaking, they'll have to use a cheaper brown paint rather than full on orange... and thus future owners may likewise be forced to thin their paints when applying over such a large surface, in order to fly into hostile-to-orange space with a big old orange ship.

And, on a personal level the lack of colour is just really disappointing.

**Comment by Saugia** [comment]
After some more discussion, we're pretty indifferent about the swizzle here with the Korath ships. Visual consistency is important when it comes to swizzling, so I have to agree with Raven's comment here. I don't think they need any more intricate swizzles either, the way they are is fine as-is in game, and as mentioned, consistent with most other ship swizzling, which is more important than what might look good to some compared to others.

The Scrapper, however, seems alright. For the sake of the situation (since most of the comments and such are about the Korath here), please open a new PR for the Scrapper swizzles.

**Pull request closed without merging**
