### PR TITLE
Increase background haze visibility

### PR DESCRIPTION
**Pull request by Pointedstick**
This PR slightly increases the visibility of the background haze effects, making it more prominent and prettier, especially when zoomed out. A picture's worth a thousand words, so I'll let some before-and-after screenshots do the talking:

Before:
Blue - zoomed in, before
Blue - zoomed out, before
Red - zoomed in, before
Red - zoomed out, before

After:
Blue - zoomed in, after
Blue - zoomed out, after
Red - zoomed in, after
Red - zoomed out, after

These haze files are only here in the main repo, not also in the high DPI repo, so no PR for it is necessary.

### CODE REVIEW

**Comment by ChamEV** [comment]
Looks good,  The only issue with haze that comes up in games is often it can be too bright and make the foreground hard to see.  The red is close, but I see no issue here.

**Comment by Pointedstick** [comment]
Yeah, I tried not to go overboard with it.

**Comment by Tadrix** [comment]
That's a nice addition, but I request that you don't close #4420 yet (I'd have to rename it), as it touched not only on haze sprites, but also system sprites (and lighting), like having dust (or asteroid) rings around systems using the same principle as nova, black hole, or WR sprites which would change the background near the star.

**Comment by Pointedstick** [comment]
Sure, no problem!

**Comment by Tadrix** [comment]
Thanks.

**Comment by Bladewood** [comment]
My impression was that background haze was meant to be a [very subtle effect](https://github.com/endless-sky/endless-sky/commit/ff5964b429bb95eac81d46117c9ffae7a486f53f). See also [this post](https://github.com/endless-sky/endless-sky/issues/1057#issuecomment-217769415).

These new hazes look very shrill in places where they used to smoothly fade into black.

**Comment by Pointedstick** [comment]
> My impression was that background haze was meant to be a [very subtle effect](https://github.com/endless-sky/endless-sky/commit/ff5964b429bb95eac81d46117c9ffae7a486f53f). See also [this post](https://github.com/endless-sky/endless-sky/issues/1057#issuecomment-217769415).

Let's discuss whether or not we even want to do this in https://github.com/endless-sky/endless-sky/issues/4420

**Comment by Pointedstick** [comment]
So, anyone up for this?

**Comment by beccabunny** [comment]
I'm still very interested in this feature request.

**Comment by Zitchas** [comment]
Would it be possible to add a opacity value to the haze? The haze itself is specified in the map.txt file. I would think it easy enough to have it look for a value to go with it that represents how bright and obtrusive it is. This would allow us to have a variety of haze without increasing the number of image files we need. 

Along the same lines, being able to stack the two haze on top of each other at varying levels would open up a lot of variety possibilities too.

**Comment by Pointedstick** [comment]
Those are good enhancements for a separate patch IMO. :)

**Comment by Amazinite** [comment]
@Zitchas Might be worth opening a PR on a haze opacity value.

**Comment by MCOfficer** [comment]
@Pointedstick Are there any assets for these? Ref #4571

**Comment by Pointedstick** [comment]
> @Pointedstick Are there any assets for these? Ref #4571

No, the assets are all here in the repo already. I just modified the files in GIMP.

**Comment by MCOfficer** [comment]
Since the originals didn't have xcf's either, i suppose that's ok.

**Pull request merged**
