### PR TITLE
Typo fix: s/year old/years old/

### PR DESCRIPTION
**Pull request by tstanke**
Pretty sure this is intended to be "years" :D I'm interested in contributing to the game, gotta start somewhere.

### CODE REVIEW

**Comment by LocalGod79** [comment]
conversational english is funny in that native speakers do not pluralize that word in that context (it's been my experience that this mistake is usually made by a second language speakers).

if anything, a hyphenation of 'year-old' or 'fourteen-year-old' would be appropriate.

**Comment by tstanke** [comment]
I think I see your point - you are framing "fourteen-year-old" as a noun (e.g., "he is a fourteen-year-old") but my intention was as an adjective (e.g., "he is fourteen years old"). Either seems valid but this is the one that occurs to me more naturally :D

**Comment by endless-sky** [comment]
@tsanke is right - in this context, that was a typo.

**Comment by LocalGod79** [comment]
oops - my apologies!

**Pull request merged**
