### PR TITLE
feat(content): Add another space creature to the Ember Wastes

### PR DESCRIPTION
**Pull request by Galaucus**
I accidentally broke #5585 while fixing problems with my base repository.

<hr/>

https://user-images.githubusercontent.com/68889791/103321740-e6048780-49ef-11eb-9d3a-b51fd8b1ae4f.mp4

## Summary
Void-dwelling creatures native to the Ember Wastes, the Embershade are ray-like entities which generate a natural cloaking field. Generally shy, they prefer to give intruding ships a wide berth and remain under cloak whenever possible. During the occasional ion storm that washes through the Wastes they become visible.

My intention with the Embershades is to add a ghostly presence to the otherwise-empty wastes; I want the player to know in the back of their mind that there's something there in the system with them, but they can't quite see it. The overall experience should be mildly disconcerting: a dark silhouette and scant luminescent patches should evoke the feeling of seeing a shadow moving in the sea, the creature's true form indeterminate. 

## Save File
[This plugin can be used to preview the new critters. For testing purposes they spawn in Segesta, Stercutus, Caeculus, and Peragenor.](https://cdn.discordapp.com/attachments/266345072554016768/793624413206609950/Embershades.7z)

## PR Checklist
 - [x] Initial mockup and testing complete
 - [x] Assets recreated in blender (blender work by @Ferociousfeind) , textured, and animated
 - [x] New personalities implemented by @InfiniteDonuts 's PR #5698  
 - [x] Fine-tuning of stats, spawn rate, and systems
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/drive/folders/1UvahLxZrVPUZ5OXumWGBWuN-NvWx-qE5?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/173

### CODE REVIEW

**Comment by Galaucus** [comment]
This is now ready for review. We'll need #5698 merged first, mind.

**Comment by Zitchas** [comment]
If you could refresh my memory, how are we making sure we don't end up with swarms of dozens of embershades in a single system?

**Comment by Galaucus** [comment]
> If you could refresh my memory, how are we making sure we don't end up with swarms of dozens of embershades in a single system?

The Roving personality has a check built in that forces ships to evacuate the system once enough are already present. I've combined this with fairly low spawn rate so that it's *likely* that there won't ever be enough in-system at once with their natural jump-out rate, but if it ever does hit that ceiling the AI will force a few of them to jump out to keep the number below a certain level.

**Comment by InfiniteDonuts** [comment]
To be precise: it's the same threshold as mining ships, so whenever there are more than nine of them in the system, one jumps away or lands. It's also designed so that the one that has been in the system the longest will leave (an unintended side effect, but a welcome one).

**Comment by Zitchas** [comment]
OK, thanks for the explanation. Is that a value that we can tweak or adjust? 9 is probably alright if they're staying really spread out (especially if they ignore the fence), or alternatively if they bunch together and move in a tight pack. But if they wander like most normal ships, I think the inner system will feel a bit too busy with that many. (admitedly we shouldn't see them most of the time).

**Comment by Galaucus** [comment]
I feel like the ideal solution here would be to have roving ships  have a, say, 1/6000 chance of deciding to leave per frame. This would ensure that the Embershade are roughly twice as likely to leave as they are to spawn, making any buildups rare.

**Comment by Zitchas** [comment]
That would be good. To avoid having it tied *just* to the Embershades, that might be something to look into as a personality.

**Comment by InfiniteDonuts** [comment]
The Embershades would be very spread out, since they will rove anywhere inside the fence.

**Comment by Galaucus** [comment]
> That would be good. To avoid having it tied _just_ to the Embershades, that might be something to look into as a personality.

 Defined value analogous to confusion, maybe?

**Comment by InfiniteDonuts** [comment]
I could simply build a 1/600 chance of leaving into the already-made Roving personality, or I could make a new one... which one would you guys prefer?

**Comment by Pointedstick** [comment]
I'll let you handle the review on this one, @Zitchas, as you're Mr. Ember Wastes these days. :)

**Comment by Zitchas** [comment]
@Pointedstick I'm pretty happy with everything I've seen of them. We've discussed them in Discord a few times, and while I haven't posted much on here, suffice to say that I really like both the intent and application of them so far. I'll be happy to see them merged into the Ember Waste, so long as they stay nice and rare. Ghostly things that people only occasionally see phasing into reality during ion storms. Spooky things, like going swimming and seeing the shadow of something big pass by in the depths beneath you.

**Comment by Pointedstick** [comment]
Cool @Galaucus, does this depend on and require https://github.com/endless-sky/endless-sky/pull/5698?

**Comment by Galaucus** [comment]
> Cool. @Galaucus, does this depend on and require #5698?

Yes.

**Comment by Zitchas** [comment]
In other words, not strictly necessary, but #5698 significantly improves them.

**Review by Zitchas — APPROVED** [review]
In regards to Anazinite's comment on discord, I just want to mention that I am good with these being merged without the new personalities. Those would be nice (likewise, having 3d models would be great), but the new personalities aren't strictly required.

**Comment by Amazinite** [comment]
We might have to break off `cloaking` from #5698, as I believe that's mandatory to get the "remains cloaked unless an ion storm hits" effect that I'd say would be a bear minimum to have these creatures be interesting.

**Comment by InfiniteDonuts** [comment]
> We might have to break off `cloaking` from #5698, as I believe that's mandatory to get the "remains cloaked unless an ion storm hits" effect that I'd say would be a bear minimum to have these creatures be interesting.

@Amazinite I'll look into it :)

Happy to see this getting merged!

**Comment by Galaucus** [comment]
Laptop with all the old assets is now dead and dusted, so they've been rebuilt from what I could scavenge. The good news is they're even better now!

**Comment by Galaucus** [comment]
Major credit goes to my friend Wowie for pretty much singlehandedly figuring out the texturing and glow animation, Ferociousfiend for the model and animation, and InfiniteDonuts for the AI.

**Comment by Anarchist2** [comment]
The ship definition is missing the frame rate of the animation. (You can also cut out some of the frames by making the animation reverse after reaching the end by using `rewind`.)

**Comment by Galaucus** [comment]
Lurked in Caeculus and they appear to be acting as expected.

**Comment by Zitchas** [comment]
Excellent. I'm looking forward to seeing comments about these from people who don't follow development. (also, not posting about it in the Ember Waste chat for that very reason.)

**Pull request merged**
