### PR TITLE
bug fix: ships you don't own will sometimes follow cloaked player flagship

### LINKED ISSUE #5739: Navy vessel follows cloaked Starling
**Describe the bug**
At entry point (ish) to F/W missions - when followed by the Navy warship from New Wales/Algorel in a Starling, the Navy vessel still follows even when the Starling is cloaked.

I realize it's pretty unlikely that many will tinker with the Remnant before the F/W missions are done, but hey.

To reproduce: Load the attached savefile, which starts on New Wales after overhearing the Navy officers chatting.
Chart a path back to Glaze.
Launch.
Observe the navy vessel launch.
Cloak.
Jump.
Navy vessel will follow. 
[Tinker Hammer~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/6016630/Tinker.Hammer.previous-1.txt)

### LINKED ISSUE #8303: NPCs can follow cloaked ships while scanning
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NPCs can follow ships - or at least the player's flagship - while it is cloaked, if the NPC is attempting to scan the player.

### Steps to Reproduce

Use the provided save file; it'll spawn in a remnant ship for you. Wait for it to begin scanning, then cloak and move away. When you uncloak, the NPC will be close to you, also uncloaking, and still scanning.

### Expected Behavior

Cloaked ships should be hidden.

### Screenshots

_No response_

### Link to save file

[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10614124/Test.Pilot.txt)

### Operating System

EndeavourOS (kernel: 6.1.9.zen1-1)

### Game Source

Built from source

### Game Version

latest contiuous

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Bugfix:** Fixes #8303 and fixes #5739

## Fix Details
Fixes:

1. #8303 - Bug: if an NPC can cloak, and is friendly to the player, it'll cloak and follow the player around when the player is cloaked. This is normally okay, unless the NPC is uninterested. I fixed that: ships only cloak with the player if they're the player's own ships, or if they have `escort` and not `uninterested`. In other words, only escorts cloak with the player.
2. #5739 - Bug: NPC that cannot cloak may end up in the `MoveEscort` behavior, following the cloaked player. I updated that logic so a ship can only follow its parent if they are the same government, unless it is an escort that isn't uninterested.

## Testing Done
Used the save from #8303 to ensure the ships de-target. Also tried getting scanned by gunships to ensure valid targets are *not* discarded. Tried #5739's test save, ensuring the gunboat had no idea where I went when I was cloaked, and then eventually caught up when I decloaked.

## Save File
This is copied from #8303. To test it, leave the planet, wait for the Remnant NPC escort to scan you, and then cloak:
[Test.Pilot.txt](https://github.com/endless-sky/endless-sky/files/10689392/Test.Pilot.txt)

This one is from #5739
https://github.com/endless-sky/endless-sky/files/6016630/Tinker.Hammer.previous-1.txt
There's a gunboat that follows you around.

Here are some illegal missions in human space.

This has a cloaking device and an illegal mission so you can test the feature in human space.
[Aimet Taepip~3029-04-19 Ranoerek Test.txt](https://github.com/endless-sky/endless-sky/files/10689207/Aimet.Taepip.3029-04-19.Ranoerek.Test.txt)

These are early-game designs that do *not* cloak, so things should work as normal. All have illegal missions.
[Aimet Taepip~3029-04-20 Sparrow Test.txt](https://github.com/endless-sky/endless-sky/files/10689208/Aimet.Taepip.3029-04-20.Sparrow.Test.txt)
[Aimet Taepip~3029-04-18 Heavy Shuttle Test.txt](https://github.com/endless-sky/endless-sky/files/10689209/Aimet.Taepip.3029-04-18.Heavy.Shuttle.Test.txt)
[Aimet Taepip~3029-04-18 Clipper Test.txt](https://github.com/endless-sky/endless-sky/files/10689210/Aimet.Taepip.3029-04-18.Clipper.Test.txt)
[Aimet Taepip~3029-04-18 Blackbird Test.txt](https://github.com/endless-sky/endless-sky/files/10689213/Aimet.Taepip.3029-04-18.Blackbird.Test.txt)

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
After further testing, I'm not 100% convinced the fix works, so I'm closing this PR until I can test further.

**Comment by UnorderedSigh** [comment]
Re-opened. Sorry about that. I missed the one spot where a cloaking NPC that is uninterested will follow its parent.

It fixes #8303 too now.

**Comment by tibetiroka** [comment]
This does fix the original issue brought up in #8303, but not the whole thing. Fighters created without carriers still get messed up when they lose their scanning target.

**Comment by UnorderedSigh** [comment]
> Fighters created without carriers still get messed up when they lose their scanning target.

Do you have a test case for this?

Also, I don't know what "messed up" means, but I guess I'll know when I see the test case in action?

**Comment by tibetiroka** [comment]
This was discussed in the issue; basically, some Remnant fleets allow fighters and drones to be created without carriers. If one of these ships is scanning the player when the player's ship cloaks, the fighter just stops, and doesn't do anything. (They are supposed to be flying around, going to planets and stuff.)

**Comment by tibetiroka** [comment]
For a test case, just use the same save and wait until you spawn in some Petrels or Smews.

**Comment by UnorderedSigh** [comment]
I'm seeing a lot more than just fighters get confused by that disabled Korath ship. All the Remnant ships eventually get stuck on top of it.

**Comment by tibetiroka** [comment]
Oh. That's another, independent bug, not the one I was referring to.

The fighter issue is still a scanning+cloaking bug; the difference is, that instead of following the player, the fighter just stops (not drifting, completely stationary).

**Comment by UnorderedSigh** [comment]
I tracked it down using printf, and it turns out that behavior is not a bug. The probes are behaving exactly as intended. When surveillance ships have nothing to scan, they come to a full stop. Navy gunboats do the same thing. The Navy surveillance drones do *not* do that because they also have atmospheric scanners, so they scan the StellarObjects, which is what gives them the appearance of patrolling.

```c++
                unsigned total = targetShips.size() + targetPlanets.size() + targetSystems.size();
                if(!total)
                {
                        // If there is nothing for this ship to scan, have it hold still                                                                                                       
                        // instead of drifting away from the system center.                                                                                                                    
                        Stop(ship, command);
                        return;
                }
```

**Comment by RisingLeaf** [comment]
I just want to say that the real issue is, I also pointed this out in #8303, npcs have the player as their flagship

**Comment by UnorderedSigh** [comment]
> I just want to say that the real issue is, I also pointed this out in https://github.com/endless-sky/endless-sky/issues/8303, npcs have the player as their flagship

No, that has nothing to do with any of these problems. Scanning is based on the target, not the parent.

**Comment by RisingLeaf** [comment]
> > I just want to say that the real issue is, I also pointed this out in #8303, npcs have the player as their flagship
> 
> No, that has nothing to do with any of these problems. Scanning is based on the target, not the parent.

No, if the parent cloaks, the child cloaks too, in cloaked state they will just follow the parent

**Comment by UnorderedSigh** [comment]
> No, if the parent cloaks, the child cloaks too, in cloaked state they will just follow the parent

That's firstly a user interface issue: you have no way to tell individual ships whether to cloak. The cloak button is an "all or nothing" feature.

**Comment by UnorderedSigh** [comment]
Checks are failing due to a network issue.

**Comment by UnorderedSigh** [comment]
This PR also fixes #5739, which had a similar problem to #8303.

**Comment by UnorderedSigh** [comment]
It would be advisable for @Zitchas to look at this, since it affects the Remnant more than other factions.

**Comment by RisingLeaf** [comment]
> > No, if the parent cloaks, the child cloaks too, in cloaked state they will just follow the parent
> 
> That's firstly a user interface issue: you have no way to tell individual ships whether to cloak. The cloak button is an "all or nothing" feature.

Uh, no, it is an engine issue with make all npc's childs to the players flagship

**Comment by UnorderedSigh** [comment]
> Uh, no, it is an engine issue with make all npc's childs to the players flagship

That doesn't matter because `DoCloak` only has the NPC ships cloak if they are owned by the player, or if they are `escort`s without the `uninterested` personality...

... because that is one of the fixes in this PR.

**Comment by tibetiroka** [comment]
> When surveillance ships have nothing to scan, they come to a full stop.

Yes, that does indeed seem to be intended.

> Navy gunboats do the same thing.

Gunboats have hyperdrives. Do they jump away after a while? As I see it, the Remnant fighters just stay at the planet if there aren't any targets, and I assume they would continue to accumulate over time. That is definitely not right. It's a matter for another PR, though.

**Comment by UnorderedSigh** [comment]
> Gunboats have hyperdrives. Do they jump away after a while?

Yes, eventually they get bored and leave.

> As I see it, the Remnant fighters just stay at the planet if there aren't any targets, and I assume they would continue to accumulate over time. That is definitely not right. It's a matter for another PR, though.

Yes, reverting to a patrol or swarm pattern makes the most sense. As you say though, that belongs in another PR.

**Comment by UnorderedSigh** [comment]
Last tested and confirmed to work at Sun, 19 Feb 2023 04:42:01 UTC.

**Comment by warp-core** [comment]
Have you considered excluding untargetable ships from being selected in `AI::FindTarget()` instead of discarding them in `AI::MoveIndependent()`?

**Comment by UnorderedSigh** [comment]
> Have you considered excluding untargetable ships from being selected in `AI::FindTarget()` instead of discarding them in `AI::MoveIndependent()`?

The target will have become untargetable since it was last selected, if the target cloaked since then. In that situation, FindTarget will have found a valid target (since the ship wasn't cloaked) but MoveIndependent will still follow it, even though the target is no longer valid.

Am I missing something?

**Comment by warp-core** [comment]
If the current target is untargetable, it should rerun FindTarget, even if it is not this ship's "target turn".

**Comment by UnorderedSigh** [comment]
> If the current target is untargetable, it should rerun FindTarget, even if it is not this ship's "target turn".

Ah, I understand now. Thank you.

There may be quite a delay if forty ships suddenly switch targets. The target selection algorithm is O(n), and quite complicated, which is why ships take turns.

**Comment by warp-core** [comment]
I'm having difficulty reproducing problem 3.

I have no particular issues with your changes to `DoCloak()` or `MoveEscort()`, however.

**Comment by UnorderedSigh** [comment]
> I'm having difficulty reproducing problem 3.

I'm not sure what circumstances are necessary to reproduce it without hitting the other bugs.

Should I remove that workaround? If we need it, we can add it in later.

**Comment by warp-core** [comment]
> > I'm having difficulty reproducing problem 3.
> 
> I'm not sure what circumstances are necessary to reproduce it without hitting the other bugs.
> 
> Should I remove that workaround? If we need it, we can add it in later.

Yes

**Comment by UnorderedSigh** [comment]
Okay, I'll work on that. I need to double-check that I'm not removing changes for fixes 1 and 2.

**Comment by UnorderedSigh** [comment]
@warp-core - the changes for the third fix are gone, and the remaining changes still fix the first two problems

**Review by warp-core — APPROVED** [review]

**Pull request merged**
