### PR TITLE
Adds hotkey instructions for hiring/firing crew

### PR DESCRIPTION
**Pull request by Morcleon**
A small QoL change for the Hire Crew panel. I don't think this was covered in any tutorial or intro material, so it took me a really long time to figure how to actually hire new crew members.

### CODE REVIEW

**Comment by Bladewood** [comment]
Should also explain that H can be used with shift, ctrl, alt, etc. to increase the crew multiplier.
I found clicking the hire button while piloting a Bactrian to be very annoying. (That's, what, 175 clicks?)

**Comment by KiLEdEnNis** [comment]
just Ctrl+Shift+Alt for x50000, 1 click & done

**Comment by Morcleon** [comment]
The Shift/Ctrl/Alt stuff is used for everything though, so I'll probably try to find a different place to put that in. Maybe have a popup the first time the player opens Trading, Outfitter, or Hire Crew? I'd probably want a different popup for Shipyard, since multiple buying works differently there (what with naming schemes and all).

**Comment by DingusShingleton** [comment]
You can also use space bar to hire crew which I recently discovered

**Comment by endless-sky** [comment]
Do you have a screen so small that the "Hire" and "Fire" buttons aren't showing up?

**Comment by Bladewood** [comment]
On the note of really small screens:
https://groups.google.com/d/msg/endless-sky/aAUJWWlbER8/Msr_du3hAQAJ
you asked for 1280x720 screenshots here, but if we use that resolution, the trading, banking, and crew hiring tabs have [related buttons] that go off of the screen. while they can still be clicked, it looks weird.

**Comment by Morcleon** [comment]
...I didn't even know there were buttons until know. Switching the screen to full screen has them just show up on the bottom of the screen. (That [Pay All] button would have been really really useful to have. xD)
This is what I have on my screen: https://i.gyazo.com/a63ee16fc8987c44a750dfdd5c5eb74c.png

**Comment by Bladewood** [comment]
...wow.
That's sad, really.

**Comment by Pointedstick** [comment]
A valiant effort, but it seems like the real fix is to make sure critical UI elements aren't cut off on smaller screens.

**Comment by TeoTwawki** [comment]
Smaller screens? is 1280x720 "small" now? I didn't even know how to hire, I never saw any buttons.

**Comment by KiLEdEnNis** [comment]
1600x900 & 1920x1080 are very common these days, so yes, 1280x720 is rather small

**Comment by TeoTwawki** [comment]
-_feels old_- 😞

**Comment by Bladewood** [comment]
1440x900 is my current computer's monitor's res.
Used to have a 1920x1080 all-in-one computer. Then it died.

**Comment by whismerhill** [comment]
I think
the game should warn ya if your display area is too small to fit UI elements, not sure how that can be done though (would need to handle windowed & fullscreen)

**Comment by KiLEdEnNis** [comment]
simply saying "minimum resolution: [size]" so players know that stuff may not be displayed correctly

**Comment by whismerhill** [comment]
@KiLEdEnNis 
minimum resolution is misleading, since game can be played in a window, player could think his resolution is enough, but if he plays windowed & not borderless, it's gonna not work properly
hence why I was talking about display area instead.

**Comment by KiLEdEnNis** [comment]
players would wonder why the screen would be cluttered if they don't have a maximized screen
if they window it and make it shrink it's logical (their "fault" in my opinion) it'd become cluttered, the players would think "oh, I need to maximize the window"

**Comment by whismerhill** [comment]
As long as it's not too difficult to pull off, it's best practice to make a mechanic the most robust to abuse, 
you never know what players might invent or do :p

**Pull request closed without merging**
