### PR TITLE
Mining and fleet AI updates

### PR DESCRIPTION
**Pull request by samrocketman**
Intent
------

A note from @samrocketman (Sam Gleske).

This change only introduces engine changes to enable plugins to implement the behavior initially.  However, eventually the game data files would also be updated to support the behavior.

All data file changes have been stripped from this code in order to limit how much gameplay is affected.  You can include the data file changes by installing the following plugin which includes behavior originally introduced with this engine change.

The idea is to polish this a bit and to match the code style with the rest of the project so that it may be merge-worthy.

Primary changelog
-----------------

* Adding Strafing & Circling AI support
  > Thanks to VitalChip for coding this.  They say they are going to redo
  > it better in a few weeks. But in the mean time, this is what I pulled
  > from their branch. Hopefully it works!

Fixes provided by contributors

* Removing the python script
* Removing duplicate arrival
* Missing }
* Fixing duplication of keys
* Fixing a bracket
* And a missing else
* Fixing another bracket

Sources of changes
------------------

* https://github.com/endless-sky/endless-sky/pull/5772
* https://github.com/Zitchas/endless-sky/pull/67
* https://discord.com/channels/251118043411775489/431496424992014347/953417198821580850

### CODE REVIEW

**Comment by samrocketman** [comment]
# WARNING

This change mixes tabs and spaces.  I need to push a followup commit which changes the spaces to tabs to match the rest of the file.

# Source

This is change was pulled from https://github.com/Zitchas/endless-sky/pull/67 with only conflicts resolved on master branch.

Data files changes were also removed to be added by a plugin.

**Comment by samrocketman** [comment]
# Don't recommend merging at this time

After play testing this appears to break the AI entirely.  Gather ship AI does not work and there's randomly disabled ships when I launch from a planet.

**Comment by samrocketman** [comment]
# Attempted data

Here's a short version of the data I used in a plugin but I could not get valid mining behavior.

```
ship "Korath Chaser"
	attributes
		rear 1
ship "Far Osk 27"
	attributes
		rear 1
ship "Black Diamond"
	attributes
		rear 1
ship "Barb"
	attributes
		rear 1
ship "Boxwing"
	attributes
		rear 1
ship "Dagger"
	attributes
		rear 1
ship "Dropship"
	attributes
		rear 1
ship "Finch"
	attributes
		rear 1
ship "Lance"
	attributes
		rear 1
ship "Heliarch Pursuer"
	attributes
		rear 1
ship "Heliarch Rover"
	attributes
		rear 1
ship "Heliarch Stalker"
	attributes
		rear 1
ship "Violin Spider"
	attributes
		rear 1
ship "Petrel"
	attributes
		rear 1
outfit "Asteroid Scanner"
	miner 1

```

**Comment by EjoThims** [comment]
So this is just a collection of loose code updates and attempting to resolve the conflicts between them?

Or is there a more specific tie in between the changes picked?

Either way, it really should be converted to a draft if it's explicitly not ready for current merging.

**Comment by Zitchas** [comment]
Thanks for taking up this project. VitalChip's AI changes demonstrated in Revamp how fighters and drones could really be differentiated into their own unique contribution to combat; and made to be truly frightening, with simple manoeuvrability changes and especially the AI to use them. 

Worth noting that the circling behavior, due to the restrictions of physics, does need considerably higher acceleration values than we typically have in game. (it takes a surprisingly high amount of thrust to fly in a circle around a moving target). Note that Revamp, where this AI was showcased to great effect, most fighters had, as a minimum, double their current vanilla thrust; and I believe may have been quadruple their normal thrust.

I think, overall, there is a decent amount of agreement (but by no means unanimous) in regards to speeding up fighters in general, but the means of doing this is still being discussed. (Note: There are exceptions, such as fighters that are actually serving in roles that basically amount to "detachable turret" rather than "chase down target" roles.

**Comment by samrocketman** [comment]
Closing since this will be revisited in other PRs.

**Comment by samrocketman** [comment]
See #6669 which is a spiritual successor

**Pull request closed without merging**
