### PR TITLE
Visual indication of whether all planets in a system have been visited

### PR DESCRIPTION
**Pull request by guillochon**
**Update**: Now that the visitedPlanets variable has been added to the master branch, this PR simply adds the visual indication that all planets in a system have been visited.

I've added a "visitedPlanets" variable to the PlayerInfo structure that keeps track of all the planets the player has visited. This data is also saved and loaded to the pilot file.

Systems for which all planets have been visited will appear as filled circles on the map, whereas those in which at least one planet has not been visited will be continue to be shown as open circles. Uninhabited systems with no landable objects will appear filled once they are visited.

I think this is very useful information to show to the player, especially if one is interested in exploring all corners of the galaxy (and remembering where one has actually seen all there is to see!). Here is what it looks like:

image

I've created a poll to vote on whether this PR should be merged, needs some more work, or should not be merged: http://poll.lab.io/ic7wCN0vdhmIwa-eyV6fbA

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm a bit worried about this being confusing for new players. (They already get confused enough by the color-coding of the systems!)

It might be better for the exploration status of each system to be an alternative color-coding option along with commodity prices and presence of shipyards or outfitters, rather than allowing systems to have different icons in addition to different colors. (For example, maybe the "Space Port" text for each planet in the ports map could instead display "Unexplored," "Refueling," or "No Refueling" depending on whether you have explored the planet and whether you can refuel there.)

**Comment by endless-sky** [comment]
But also, I'm not sure how many players will actually care about knowing whether they have landed on a given planet or not, unless the game is changed so that you do not know what services a planet offers until you land there (which would be rather annoying).

**Comment by guillochon** [comment]
In principle there will be ~600 systems when the game is finished, each with custom art and some with multiple planets. There are also missions that are offered on specific planets, which you may miss unless you visit every world. For completionists, I think it makes sense to help them out with a small visual hint rather than forcing people to write down where they have landed. This was something that always annoyed me about the original Escape Velocity.

I'm not sure that I agree that the different icons are particularly confusing, it's a very subtle visual cue. It also enables one to quickly see what's left to explore on the map, whereas burying it in the pilots subpanel forces one to click on each system one at a time.

**Comment by ItsNickBarry** [comment]
I think this is a valuable addition.  I found it annoying to think that I might have missed some planets, and their associated background information.

Any confusion that might result from this would be removed with the addition of a key to the map, which might be needed anyway.

**Comment by guillochon** [comment]
I agree that a key on the map would be very helpful anyway, what the colors correspond to is not obvious until you are familiar with the game.

**Comment by ItsNickBarry** [comment]
This would work as an alternative color-coding option as well.

**Comment by omagasohe** [comment]
I vote for endless-sky's Idea. The game is based around simplistic, uncluttered and intuitive approach. I agree that the color's aren't obvious right off the bat, but you get the hang of them quickly. filled and unfilled dots aren't going to be readily apparent and would require an effort to point out what a small percentage of players care about.

**Comment by guillochon** [comment]
I guess I don't understand the harm in adding a subtle visual queue to indicate planet visitation status. If a player doesn't understand the filled/open distinction, does that really harm their gameplay? Even if the fraction of players who appreciate it is small, doesn't it make sense to please them so long as it doesn't bother the rest?

What's more, the addition of visited planets to the saved data adds another story-telling option to the game. "You've you seen the waterfalls on Greenbloom?" an NPC might say.

**Comment by omagasohe** [comment]
I don't think anyone is against the idea, just method of implementation.  I do concede that knowing if I've dropped in on every world is useful. I also like the idea of missions knowing if you've visited a world, but that's easily done with a one shot mission. After thinking about it, Having the map fill in the dot is good, and documenting that in a map tutorial is good idea too. it's confusing as heck some days =P 


    On Friday, December 4, 2015 6:29 AM, guillochon <notifications@github.com> wrote:
 

 I guess I don't understand the harm in adding a subtle visual queue to indicate planet visitation status. If a player doesn't understand the filled/open distinction, does that really harm their gameplay? Even if the fraction of players who appreciate it is small, doesn't it make sense to please them so long as it doesn't bother the rest?What's more, the addition of visited planets to the saved data adds another story-telling option to the game. "You've you seen the waterfalls on Greenbloom?" an NPC might say.—

**Comment by brick96** [comment]
This would be a great thing to add. Something else to go along with this is coloring the inside green when a escort is there (mostly for quickly locating disabled or left behind escorts, as the map search is pretty subtle)

**Comment by guillochon** [comment]
Trying something here to get more feedback: I've added a poll to ask whether this PR should be merged or not, or whether it needs some more work, http://poll.lab.io/ic7wCN0vdhmIwa-eyV6fbA.

**Comment by guillochon** [comment]
This has been partially implemented in https://github.com/endless-sky/endless-sky/pull/404, but this PR still adds a visual indication that all planets in a system have been visited.

**Comment by frameworld** [comment]
* Needs more work.

1 players should get a clue that this feature exists and how they can extract information from it.

2 Some missions only appear with a combat rating of 8000+ do I really have explored Tarazed to it's fullest extend when visiting it with a combat rating of just 7000?

3 The circle may have multiple dots - one per planet.

4 Colour-coding has issues.

Planet and system colours should be separate. Somehow. They don't mean the same.

**Comment by johnca** [comment]
I like this a lot, and don't think it adds too much complexity to the map, which already desperately needs a tutorial anyway.

**Comment by endless-sky** [comment]
In commit 4f0b23a in the "ports" map, each planet's visited / not visited status is included in the planet information along with whether it has a spaceport, outfitter, and shipyard. I've also made it possible to color the systems based on whether some / all planets in each system have been visited.

**Comment by guillochon** [comment]
This is great but I have one very minor quibble: When displaying the coloring for visitation status, "uninhabited" systems still show as grey even if they have a vistable object. I think on that screen the grey should mean "nothing visitable", and uninhabited systems with visitable objects should use the visit coloring.

**Comment by sanjayatio** [comment]
@endless-sky:
just an aesthetics complaint: please enlarge the planet/space station window to accommodate the new line.
another (un)related complaint: select Sol (for example) and the legend would be occluded by the commodity window.

Place like Carbuncle Station prevents us from planting a tiny flag next to the planet's name.
It might cause brief confusion for existing players, but 
- drawing visited planet/station name in solid white
- just gray out the not-yet-visited ones
should be better for the merchant-oriented players.

**Comment by endless-sky** [comment]
Included in release 0.8.10.

**Pull request closed without merging**
