### PR TITLE
refactor(source): all shader classes are moved to source/shader

### PR DESCRIPTION
**Pull request by Statter**
Heading: **Refactoring**

## Summary
Currently /root/source folder contains a very long list of source files (.h, .cpp)
To simplify code a little bit:
* directory /root/source/shader is added
* shader classes (Batch, Fill, Fog, Line, Outline, Pointer, Ring, Base Shader, Sprite) moved to "shader" directory
* refactoring of includes is done

No changes were done except required for shaders to move to a new home

## Screenshots
image

## Usage examples
Usage is the same as before, but path to include a shader class is now "shader/{$shader_class}.h"

## Testing Done
Clean/Build is working. Unit tests are working too after a change

## Save File
Any save file is valid for testing

## Artwork Checklist
No artwork change is provided

## Wiki Update
No update

## Performance Impact
N/A

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by tibetiroka** [comment]
Is this a duplicate of #10385?

**Comment by TomGoodIdea** [comment]
> Is this a duplicate of #10385?

yes, it is

**Comment by Statter** [comment]
This is my bad. I had to check for duplicate pulls, but I did't

**Comment by tibetiroka** [comment]
Closing as duplicate.

**Pull request closed without merging**
