### PR TITLE
feat(testing): Add some rudamentary checks for indefinite articles to the content style checker

### PR DESCRIPTION
**Pull request by tibetiroka**
**Feature:** This PR adds two new regex-based checks to the content style checker that check whether 'a' and 'an' are used correctly. Some additional safeguards might be required in the future if a new alien race's language abuses these rules, or if there are some rare edge cases not listed. (Works with all current wanderer dialog.)

The checks only give a warning so it won't fail the CI for any new languages.

## Testing Done
Found typos. Didn't find anything else. The new checks work correctly with the --auto-correct option.

### CODE REVIEW

**Comment by quyykk** [comment]
> The checks only give a warning so it won't fail the CI for any new languages.

I only recently discovered that there are warnings, because nobody is looking at the logs and if the build passes, then all is good. I think we should either 1) upgrade every warning to error (at least in CI) or 2) if the false positive is too high, just remove the check. Thoughts?

(as an aside, looks like CI doesn't run the content style check if only the json is modified)

**Comment by tibetiroka** [comment]
I regularly check master for any warnings. I don't actually know about any false positives for any warnings, so upgrading them to errors would also work.

**Comment by tibetiroka** [comment]
> (as an aside, looks like CI doesn't run the content style check if only the json is modified)

That's likely an issue with quite a few workflows... I'll check that.

**Review by quyykk — APPROVED** [review]
I can't read regex but I'm assuming it's correct

**Pull request merged**
