### PR TITLE
feat(mechanics): `heat` attribute for stars

### PR DESCRIPTION
**Pull request by TomGoodIdea**
## Feature Details
* Added a new child attribute for stars, `heat`, which defines how much heat ships receive (similar to `power` and `wind`).
* As requested below, no star has this attribute in vanilla game.

## Testing Done
Seems to work.

## Performance Impact
Probably N/A

### CODE REVIEW

**Comment by Saugia** [comment]
Not really sure this is appropriate for a Game Rule. Game Rules were introduced in terms of balancing gameplay for different styles of play, based on what is seen as ideal for the game's default, for example, having limited fleet sizes. It was mentioned that we don't want to add a bunch of game rules for the sake of turning something on and off, especially arbitrary attributes like this. Universal Ramscoop is an exception for obvious reasons, but I don't see solar heat being something necessitating a game rule for it.

**Comment by Ferociousfeind** [comment]
I think the heat would impact ships more expectedly if it were proportional to ship mass (or more likely, ship cross-section, which we have no good measure of...)

**Review by quyykk — APPROVED** [review]
seems reasonable to me

**Comment by Amazinite** [comment]
I actually do think this should be a gamerule if we were to add it, but I would prefer for its default value to be 0. I don't think that increased heat when near stars is something we want players to have to worry about, especially with how heat more negatively impacts smaller ships.

**Comment by Amazinite** [comment]
I'd prefer that if instead of adding a gamerule that adds a constant solar heat to all stars if we instead added a "solar heat" attribute to the stars themselves. This way, any plugin or total-conversion that wanted this mechanic could add solar heat to the stars, and have different stars have different heat values.

Solar power should remain a multiplier to the solar heat attribute from a ship, while the solar heat attribute of the star would be a constant value similar to the original gamerule. By default though, all stars in vanilla should have a solar heat of 0.

**Comment by TomGoodIdea** [comment]
Is there a single preferred solution?

**Comment by Amazinite** [comment]
The solar heat on stars method, since it provides us more flexibility than a hardcoded mechanic or gamerule that applies to all stars the same.

**Comment by TomGoodIdea** [comment]
idk how to implement the relative heat thing, could you give an equation for that?

**Comment by Amazinite** [comment]
The relative heat * maximum heat bit is what you're looking for. 
https://github.com/endless-sky/endless-sky/blob/98af346977f96149d477180b9b4cf1a3c6441da2/source/DamageProfile.cpp#L171-L173

**Comment by TomGoodIdea** [comment]
Actually I've thought about it before and I like the idea of hazards scaled with distance, but I wanted to do this PR as an easy way to add heat emission to all stars at once. But since it lost this advantage now, it might be better to focus on more flexible hazards instead.

**Pull request closed without merging**
