### PR TITLE
Sparrow/Flivver Stat Tweaks to Better Match their Roles 

### PR DESCRIPTION
**Pull request by Hecter94**
## Summary
Currently, the stats of the Sparrow and the Flivver are in a bit of a weird place. With the Flivver being slightly more expensive than the Sparrow, it is a logical first upgrade for new players. However, the current stats distribution is opposite to the roles these ships are supposed to fulfill. 

If you're looking for a fast transport ship that's cheap and agile with a small number of bunks and cargo, you should pick the Sparrow since it has the same number of bunks, ten more cargo, and is slightly cheaper to buy

If you're looking for an early warship that's fast, cheap and agile, you should pick the Flivver since it has more HP, weapon space and engine space. 

This seems quite counter to the Sparrow's role as an interceptor and the Flivver's role as a transport. 
As such, I've put together a small selection of proposed tweaks to make each ship a better option for the role they're supposed to fulfill, detailed below:

**Sparrow**

1. Shields: 1200 ->1400; this brings the Sparrow just slightly above the Flivver and Star Barge in terms of combined HP while still being worse than a more dedicated interceptor, like the Wasp or Fury. 
2. Weapon Capacity: 20 -> 25; this brings the Sparrow just slightly below the Wasp and slightly above the Barb, allowing it to mount slightly heavier weapons, such as two javelin pods or a single plasma cannon, giving it a bit more early-game firepower.

**Flivver**

1. Cargo Space 5 -> 15, this brings the Flivver up above most interceptors, such as the Berseker or Wasp, while still being less than the Shuttle in cargo and bunks. It also brings it above the Arrow by 5t, but the Arrow comes with two bunks over the Flivver to compensate for that. 
2. Weapon Capacity 25->16, this brings the Flivver down below any dedicated combat ship while still being above Shuttle, meaning there's still a reason to pick the Flivver over Shuttle without the Flivver beating out other similarly sized combat vessels in terms of weapon space. This also necessitates removing its two meteor missile pods in favour of a single Ion Reverse thruster, further reinforcing its role as a ship designed to move fast, jump fast, and run away from combat rather than fight.

With these changes, the Flivver is now much more desirable as an early-game fast transport craft; with a small but acceptable amount of bunks and cargo, plenty of fuel and a fast speed, it's not quite as good as a dedicated transport like Shuttle. However, it has some benefits that still make it a viable choice. 
Additionally, the Sparrow is now a much more formidable warship, with the extra shields meaning it can survive more damage than the Flivver can and the extra weapon space opening up several new possibilities for early game firepower that veteran and new players alike can take advantage of. 

## Save File
This save file will place you on Follower with a Flivver and a Sparrow with their new stats and loadout so you can see the changes for yourself:
[Sparrow Tweaks.txt](https://github.com/endless-sky/endless-sky/files/9738695/Sparrow.Tweaks.txt)

### CODE REVIEW

**Comment by Zitchas** [comment]
I agree with this conceptually, but I'm not entirely sure of the changes. The reduction to the Sparrow 's cargo in particular: many people consider the Sparrow the mining start, rather than the combat start, and while it is decidedly better at combat with these changes, it has its potential income per day reduced by two thirds.

There is also the little detail that despite being a "combat" start, we basically reinforce the idea that noone should actually be fighting in a Sparrow, so we probably shouldn't be hindering their ability to do anything else too much.

**Comment by Zitchas** [comment]
Also, the fliivet is described as a luxury VIP transport and/or luxury toy, akin to a sportscar. I'd have to check its stats, but I would be inclined to not boost its cargo, but consider dropping its mass and drag a little. I don't think it should really be a "fits into the typical progression" ship, but rather a specialty niche runner.

Personally, I think the Fliiver's typical jobs/income should be doing ultra-rush individual jobs, probably ultra-rush luxury jobs. Granted, small ones. By ultra-rush I mean "must fly directly to the destination by the most optimum route with no stops" type jobs.

**Comment by Hecter94** [comment]
I totally get where you're coming from, just a few things to consider:
> I agree with this conceptually, but I'm not entirely sure of the changes. The reduction to the Sparrow 's cargo in particular: many people consider the Sparrow the mining start, rather than the combat start, and while it is decidedly better at combat with these changes, it has its potential income per day reduced by two thirds.

I think the reason why the Sparrow is considered the mining start is entirely due to the fact that it simply isn't good at combat. As such, players are more so forced into the role of mining rather than choosing mining since the "combat" ship they are provided with is better at mining than it is at combat. 
This isn't really a good player experience, you pick the "combat" ship only to find out it's actually not very good at combat and you should go mine instead.

I think making these changes moves it more decidedly into a "combat" start, with there being other ships in this same price range that can still function quite effectively as mining ships if a player wants to do that.
Such as the Flivver with these suggested changes! It works very well as a starter mining ship with the extra cargo capacity and its base high speed, also still has enough weapons cap to equip two beam lasers and is very easily purchasable after just doing the James missions.
It's also worth noting that the Sparrow absolutely still can be used as a mining ship, a couple of tweaks to its stock loadout allows it to fit a heavy laser and a cargo expansion which is still very much functional as a mining ship if a player wishes to do that.
 
> There is also the little detail that despite being a "combat" start, we basically reinforce the idea that noone should actually be fighting in a Sparrow, so we probably shouldn't be hindering their ability to do anything else too much.

Hopefully, with these changes to make it better at fighting, people can actually use it to fight with since they've specifically chosen to go with the "combat" start. It's now better equipped to take on Bounty jobs or planetary defence jobs than it was previously, which are quite lucrative sources of profit



> Also, the fliivet is described as a luxury VIP transport and/or luxury toy, akin to a sportscar. I'd have to check its stats, but I would be inclined to not boost its cargo, but consider dropping its mass and drag a little. I don't think it should really be a "fits into the typical progression" ship, but rather a specialty niche runner.

The main issue here is that reduced mass/drag would only be useful to the Flivver/Player insofar as it helps them avoid pirates while doing job runs, however with its already impressively high speed combined with the stock reverse thrusters and the increase to system arrival distance, it's already more than capable of evading any pirates it runs into.

Decreasing its mass and/or drag further would really only help it to function as a fast interceptor or a dedicated missile boat, which is exactly what we were trying to avoid. 

Boosting the cargo still leaves it with a very small amount overall, 15 cargo is less than what the Shuttle, the cheapest ship in the game starts with, so it is still a *very small* amount of cargo but allows it to function as a high-speed, high-agility, dedicated transport for small amounts of cargo or a few high-paying passengers

> Personally, I think the Fliiver's typical jobs/income should be doing ultra-rush individual jobs, probably ultra-rush luxury jobs. Granted, small ones. By ultra-rush I mean "must fly directly to the destination by the most optimum route with no stops" type jobs.

This is true, and if we wanted to focus the Flivver more on "ultra-rush" jobs, we would increase its fuel capacity since a ship's speed and agility have absolutely no bearing on how good it is at performing rush jobs. 
The only metrics that matter when it comes to "rush" jobs are fuel capacity (so you can get to your destination without needing to land and refuel) and capacity so you can earn more per run.
Fuel is untouched in this PR, but capacity is increased so it is actually making it directly better at doing rush jobs!

**Comment by Amazinite** [comment]
> I think the reason why the Sparrow is considered the mining start is entirely due to the fact that it simply isn't good at combat.

While these changes make the Sparrow better for combat, at the end of the day it's still just an interceptor. I don't think we should be hurting the Sparrow's mining capability, particularly when we don't have a "dedicated miner" like the Sunder in the game just yet.

**Comment by Hecter94** [comment]
Okay, I have reverted the nerf to the Sparrow's cargo capacity, leaving it with just the buff to its shields and weapons capacity. 
Perhaps we can revisit this once early game mining gameplay is a bit more fleshed out.

**Review by Zitchas — APPROVED** [review]
Alright, I think this looks good. I'm curious to see how this plays out. This feels like the sort of change that could be quite useful, but could also be insignificant depending on the shadow of the game around it. As Amazinite said, "it is still just an interceptor." So long as at least dinner interceptors and light sod carry enough munitions to make sizeable dents in capital warships, interceptors will remain deathtraps that are best to stick to mining.

Sadly, I have not had the chance to play test this, nor will I in the foreseeable future.

**Pull request merged**
