### PR TITLE
Move port description panel

### PR DESCRIPTION
**Pull request by nickshanks**
# UI & Artwork

No ticket raised

## Summary
UI change: Move the port decsription panel on the map screen to an edge with more space. Re-centered the system name pane.
Code/asset changes: Rotates the image by 180° and removes a variable that is no longer needed.

## Screenshots
Before:
Screenshot 2024-05-31 at 23 51 41

Rejected due to 'steampunk' effects getting cut off:
Screenshot 2024-05-31 at 23 32 07

After:
Screenshot 2024-05-31 at 23 45 04

## Testing Done
Playing with this PR for a while and this is the position I liked best.

## Save File
Any file with a port will do.

## Artwork Checklist
(If any artwork was added or changed by this PR, the following must be provided.)
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/169
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/409

## Performance Impact
N/A

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
On master it looks like this:
image
The "selected system" partially covers the description. How did you take your "before" screenshot? I mean, it's still a bug, I'm just curious.

**Review by RisingLeaf — APPROVED** [review]

**Comment by nickshanks** [comment]
> On master it looks like this: image The "selected system" partially covers the description. How did you take your "before" screenshot? I mean, it's still a bug, I'm just curious.

Your screen looks very small. How is the system name (which is centered) so far to the left?

Also, perhaps you have updated the code and not the images/ui/description.png file or that your game is pulling it from somewhere (or vice versa?).

**Comment by TomGoodIdea** [comment]
> Your screen looks very small. How is the system name (which is centered) so far to the left?

I manually (in preferences.txt) set the window size to 1024x768, but this image isn't the whole window, just a part to show what I was talking about. But still, on master the selected system name isn't centered if you have the planet description open.

> Also, perhaps you have updated the code and not the images/ui/description.png file or that your game is pulling it from somewhere (or vice versa?).

The version on which I made the screenshot was the latest master branch. The order of what is drawn after what doesn't depend on the sprites. It's defined in the code, and I'm pretty sure the selected system name comes after the description box ~~because I made it this way myself~~. Maybe you were on an outdated version when taking the "before" screenshot?

**Comment by nickshanks** [comment]
@TomGoodIdea Ahh you're refrring to the sprite layering; which is on top of which.
I think for my 'before' picture all I did was edit the cordinates back again and swap the image back, after committing the changes for the 'after' picture, instead of checking out the master branch. I may have changed the order of the rendering somehow. Not sure. I see what you posted if I put the master branch in windowed mode and shrink it down.

**Comment by nickshanks** [comment]
I just had a happy moment where an idea I had had, to stack the shipyard/outfitter/missions/ports buttons on smaller screen sizes is already implemented, exactly as I had imagined it! this means that there is less liklihood of the moved port panel from colliding with the buttons (and the buttons go on top when they do overlap)

**Comment by Amazinite** [comment]
I don't think that this is the best move to make. It makes sense to have the descriptions appear next to the orbits panel, because you're clicking on the planet that you want to read the description of right next to it. With this change, you're now selecting something at the top right of the screen and needing to avert your eyes down to the bottom left to see the change.

>  I'm pretty sure the selected system name comes after the description box because I made it this way myself.

We should probably reverse this so that the selected system UI is drawn below the planet description, since you'll probably want to be able to read the description that you just caused to appear.

**Comment by nickshanks** [comment]
I didn't know you could click on the orbit panel, I just thought it was a pretty picture. I have always selected the planet by clicking its name/graphic on the top left list.

I think avoiding overlapping UI is more important than making the user move their eyes around more, though that is just my opinion.

**Comment by nickshanks** [comment]
Do you think most players (especially new ones) are clicking on a 10px by 10px dot in preference to a 250x150 pixel rectangle?

**Comment by tibetiroka** [comment]
It definitely happens. It's really convenient when sending escort to another system, which I think can be done this way.

**Comment by nickshanks** [comment]
@tibetiroka 

> It definitely happens. It's really convenient when sending escort to another system, which I think can be done this way.

Sure, but that's not the use case of clicking on a planet other than the one you are on, in order just to read the description about it, as described above by @Amazinite.

**Comment by TomGoodIdea** [comment]
What's the status of this PR?

**Comment by TomGoodIdea** [comment]
Adding "waiting on dev" to either greenlight or close this.

**Comment by warp-core** [comment]
What if the description panel were just moved down a little when it would overlap with the selected system readout?
image

**Comment by TomGoodIdea** [comment]
IMO it can be moved there permanently. It looks nice when aligned with the orbits view.

**Comment by tibetiroka** [comment]
@nickshanks Can you fix the merge conflicts? I also see some unaddressed comments above, could you look at them at some point?

**Comment by tibetiroka** [comment]
Closing as orphaned. Feel free to reopen this PR once the conflicts are resolved and the comments are addressed.

**Comment by TheGiraffe3** [comment]
(by the way, people without write access can't reopen a PR once it's been closed by someone with write access)

**Comment by Zireael07** [comment]
@TheGiraffe3 Not even the original author?

**Comment by TheGiraffe3** [comment]
This has been happening to a lot of PRs. I just thought I'd point out the fact that, as the author of the PR, it's not possible to do what you're being instructed to do. This could make it difficult for some people.

**Comment by RisingLeaf** [comment]
> People without write access can't reopen a PR once it's been closed by someone with write access...

Not the case, I don't have write but can reopen

**Comment by TheGiraffe3** [comment]
Or without access.
That is to say, the original author can no longer reopen the PR once it has been closed by someone who is not them.

**Comment by tibetiroka** [comment]
Are you sure about that? I'm pretty sure I could close and reopen my own PRs before I was an organization member.

**Comment by tibetiroka** [comment]
Actually @TheGiraffe3, you reopened your closed PR in #10292, so it is definitely possible.

**Comment by TheGiraffe3** [comment]
Yes, but I was the one who closed it in the first place.
Pointedstick mentioned this somewhere, though I'm unable to find it.

**Comment by tibetiroka** [comment]
Ah, OK. This hasn't really been an issue before, so it might just be some permission thing configured somewhere. If someone does run into it, we can just reopen it when they are ready.

**Pull request closed without merging**
