### PR TITLE
feat(content): "Gegno Exporation Nudge" adjustment

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

This PR addresses the discussion in https://github.com/endless-sky/endless-sky/discussions/10769

## Summary
This PR edits the Gegno Exploration Nudge mission to be a "floating" mission in the log so that players know that there are other encounters in Gegno space they can find. This is to help avoid cases where the player might find some of these, but not enough to progress the next part of the story, and possibly leave the area.

In return, I've decided to remove the specific mentions of planet types in the area as I believe a present reminder to look throughout their space is enough to say, as long as that mission is present in the log, there is something to find.

## Testing
Soon.

## Save File
Soon.

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by Saugia** [comment]
Converting to draft to add an additional change.

**Comment by Saugia** [comment]
Looks like I'm having a hard time getting the mission to disappear when it should; I'm making it so it fails on offer of the missions that continue once the player has enough encounters, but it doesn't disappear until the next landing, which is a bit awkward.

**Comment by TheGiraffe3** [comment]
I don't think that's possible at the moment.
But aren't those two missions offered on planets, and takeoff would fail the main mission?

**Comment by Saugia** [comment]
If a mission is failed after takeoff, it will remain in the mission log until next landing. Or at least that's my experience.

**Comment by TheGiraffe3** [comment]
Would it have to fail after takeoff?
I suppose there's no "time to fail" attribute like there is with events though.

**Comment by Saugia** [comment]
Gonna close this for now. I still think that the device saying which planets to go to is explicit enough, but if we're ever able to have more functional "background" missions (aka this disappears properly), I'd still consider it.

**Pull request closed without merging**
