### PR TITLE
More ship names, particularly for pirates

### PR DESCRIPTION
**Pull request by Pointedstick**
Deathmonger! Bonesnake! Warspike!

### CODE REVIEW

**Comment by Amazinite** [comment]
"Laughing Children"

That is terrifying.

**Comment by gunqqer** [comment]
Better than something like "Laughing Clowns Right Outside Your Door", @Amazinite

**Comment by Admiral-Danforth** [comment]
Considering I have seen at least 20 Edward teach's I support this

**Comment by Bladewood** [comment]
Deathbringer?

**Comment by KiLEdEnNis** [comment]
> Deathbringer

*triggered*
Malice / Wind Demon
(no 1 gets that 1 but the names could fit)

**Pull request merged**
