### PR TITLE
New "flagship landed" autocondition

### PR DESCRIPTION
**Pull request by Hurleveur**
**Feature:**

## Feature Details
New autocondition to know if we are landed.

## UI Screenshots
n/a

## Usage Examples
This could be useful in the Quarg atrocity conversation for instance when we give them the capacity to scan, to make it happen differently depending on the situation.
It mostly is useful to make automated tests easier and cleaner.

## Testing Done
tests will do it for me (hopefully on the first try this time)

### Automated Tests Added
I modified the tests to make use of this so we'll know if it works if they run.

## Performance Impact
n/a

### CODE REVIEW

**Comment by EjoThims** [comment]
Oh hey, would this be a good place to also add auto condition for "in space"?

**Comment by Zireael07** [comment]
Isn't NOT landed = in space??

**Comment by warp-core** [comment]
> Isn't NOT landed = in space??

Strictly speaking, not landed could also mean there is no flagship (either because it has been destroyed or sold without appropriate replacement available, perhaps other possibilities, too). But, yes, in general I would suggest using that to determine if the flagship is in space (a lot of things, like mission offering, can't happen if there is no flagship anyway).

If it turns out that there are situations where not landed can't adequately provide the functionality of "in space", we can add that then, but it seems like unnecessary redundancy without any examples of where it'd actually be necessary.

**Comment by EjoThims** [comment]
The use I had in mind was tracking passenger jobs abandoned in space (in particular the strike breaker missions) to use as reference for missions about you having literally spaced them as a bonus recruitment in for one of the pirate factions.

But that probably works just as well just checking that the ship isn't landed, yea.

**Comment by Hurleveur** [comment]
Damn look at that line number go down

**Review by quyykk — APPROVED** [review]

**Pull request merged**
