### PR TITLE
fix(content): Prevent Remnant: Expanded Horizons Astral job from having the HR systems as waypoints

### PR DESCRIPTION
**Pull request by Quantumshark**
**Bugfix:** This PR addresses issue #7702 

## Fix Details
Added the "inaccessible" attribute to the deep space systems, devil run and devil hide. Remnant: Expanded Horizons Astral job is set to not use systems with this attribute as waypoints.
Whenever the portion of HR that uses these systems becomes available, we may want an event to remove this attribute.

## Testing Done
Arguably not actually testing, but I searched every file in the data folder for "inaccessible" to check that the attribute wasn't being used for anything else, and it isn't. So this shouldn't cause any issues.

## Save File
Not sure I can use a save file to prove that the mission _doesn't_ offer with these systems as waypoints, but this should work in theory.

### CODE REVIEW

**Comment by Zitchas** [comment]
This should work, yes.

That being said, I prefer simply making those systems accessible, as per https://github.com/endless-sky/endless-sky/pull/8537

After all, these systems have active traffic to and from them. Not much, but still some. They're not random uninhabited inactive places, so it makes sense that people would be able to find there before the story shoves it in their faces and says "Hey, you must go here now!" 

Merely having them blocked by requiring a JD is more than enough to keep them hidden. (It's enough for the Pug worlds, for example, which have far greater justification for being unvisitable)

**Comment by Quantumshark** [comment]
I agree that they shouldn't be hidden, definitely - that would be my preferred solution, 100%.
In the absence of that, however, we shouldn't have this awkward middle-point we currently have where they're inaccessible but can still be mission destinations. So either we should do this to stop missions going there, or we should make them not hidden.

**Comment by Zitchas** [comment]
Agreed. That being said, this should probably update the events that make these systems accessible to also remove these attributes.

**Comment by Saugia** [comment]
We're still not sure whether or not we are keeping those systems in the first place, so this PR is going to have to wait until we get to that point in HR, or we make a solid decision to keep or remove them.

**Comment by Zitchas** [comment]
Not to disagree with you, but a fix that makes these systems not cause problems doesn't interfere in the least with any decision to keep or remove them. Them having a single extra attribute doesn't make them any harder to delete or edit, nor would it have any impact on the associated events that open up this string. This isn't exactly "baking them in" to other storylines or anything; just resolving a problem.

**Comment by Saugia** [comment]
Fair enough.

**Pull request merged**
