### PR TITLE
Little fixes, bank pay all, info panel targeting

### PR DESCRIPTION
**Pull request by MarcelineVQ**
Details of the whys are in the commit messages, fixes include
* updating the loan qualification when the pay all button is used
* viewing a ship in your system from the info panel while in space will select that ship

They're separate commits in case you wanted to cherry pick items, if you prefer single commits let me know.

### CODE REVIEW

**Comment by endless-sky** [comment]
It's actually intentional that shipyards not show the variant name. That's what allows the Kestrel to just show up as "Kestrel," for example, regardless of which modification you recommend making to it.

Also, "spare" actually was the word I meant to use there, in the sense of "scanty; not abundant or plentiful; meager; thin."

**Comment by MarcelineVQ** [comment]
Oh, but that's what sparse means hehe.
Too bad about the variants though, it's really quite strange seeing barb next to barb. The first time I saw it I just thought I had messed up my data files somehow and didn't realize 'till later on down the road that it was actually another version.

**Comment by KiLEdEnNis** [comment]
renaming the turret barb to something like Barb v2 or Hook may help, because it does look weird

**Comment by endless-sky** [comment]
One other thing: ships.front() is not necessarily your flagship - in particular, it may be a ship that is absent, disabled, or pilotless. For example, suppose the first ship in the list is an automaton, and the second ship is your flagship. In that case if the automaton gets disabled, your code would magically "repair" it whenever the game is reloaded.

I think the latest version of the game has patched all the cases where your flagship could land on a planet after being disabled, or become disabled after landing (except for if the payer edits the saved game file). So, that change might not be worth making.

**Comment by MarcelineVQ** [comment]
Mislead by my assumptions I guess, PlayerInfo::Flagship()'s comments lead me to believe the first ship in PlayerInfo's ship list is always the flagship. I see that FlagshipPtr() does more checks than I did, specifically the ones you've just mentioned, so I see how it was incorrect.

**Comment by KiLEdEnNis** [comment]
repairing any ship that gets disabled while landing can be a thing though, and even when landing on an uninhabited planet, shields have time to recharge as well (and ramscoops can work but that may give issues)

**Comment by jafdy** [comment]
Ramscoops Don't work on planets. See #1201.

**Comment by KiLEdEnNis** [comment]
yes I know, it would be realistic if ramscoops would work on uninhabited planets, but suddenly filling the fuel bar 100% would be weird, so that'd be unlikely to be implemented

**Comment by jafdy** [comment]
It's more like: tectonicly inactive planets witch won't be all uninhabited planets so...maybe one in the whole game. Otherwise your evaluation is correct.

**Comment by KiLEdEnNis** [comment]
that's why I thought it was unlikely to happen
#1201 has shield regeneration, and possible hull repair, but if a ship doesn't have that it should at least have the base amount of hull to be operational (which is one of the "issues"  brought up here, it's a good one in my opinion)

**Pull request merged**
