### PR TITLE
Separate trade commodity profit and price level into two columns

### PR DESCRIPTION
**Pull request by hmglasgow**
**Feature:** This PR implements the feature request detailed and discussed in issue #8013.

## Feature Details
Only a selected row that has the commodity in the hold shows the profit; otherwise the trade level is displayed. This provides a way to see both values when deciding whether to sell.

## Testing Done
I have bought and sold commodities and checked that the profit and trade levels show as expected.

### Automated Tests Added
N/A

## Performance Impact
N/A

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
Code wise its so simple that I dont think it even needs a review
The biggest question is do we want this change or is there a better way to solve the presented issue?
I'm fine with this change.

**Comment by Hecter94** [comment]
> Code wise its so simple that I dont think it even needs a review

We've had some pretty simple code changes break the game.

**Comment by RisingLeaf** [comment]
Generally I like the idea, but how about just increasing the information density here?
I think some thing like:
(trade level, profit)
so in game:
(medium, +5)
or
(low, -25)

**Comment by Zitchas** [comment]
I would prefer we see both price level & profit, rather than just one or the other. I think we have space to do that.

**Comment by warp-core** [comment]
@hmglasgow @Zitchas @Zireael07 @RisingLeaf thoughts?
image

(Column positions can be adjusted. Currently, the `Profit` label is not present if its column is empty.)

**Comment by Zitchas** [comment]
Sure, that looks good. Shows the profit, while not concealing the actual price.

Q: Will it show the profit for all cargo in the hold? Ex. if you have food, metal, and medical, will it show a profit (or loss) entry next to each of them?

**Comment by warp-core** [comment]
> Sure, that looks good. Shows the profit, while not concealing the actual price.
> 
> Q: Will it show the profit for all cargo in the hold? Ex. if you have food, metal, and medical, will it show a profit (or loss) entry next to each of them?

Yes

image

**Pull request merged**
