### PR TITLE
Feat(art): Add a new sprite for a proto planetary disk

### PR DESCRIPTION
**Pull request by RisingLeaf**
**Content (Artwork)**

## Summary
While I like this game for various reasons, I still like it most for the exploration. I just have fun flying around, finding new things that I know about from astronomy class.
To expand this, in my opinion most enjoyable part of the game, I added a new sprite representing a proto planetary disk. For everybody who does not know what that is, a proto planetary disk is what comes before planets, it is just dust and other small things that surround the star, well in shape of a disk.

The sprite is created to fit most stars, but it looks better with g to m class stars, that are also not the smallest ones.

## Screenshot:
Screenshot 2022-12-31 at 2 22 22 PM
Screenshot 2022-12-31 at 2 22 34 PM

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR for the asset https://github.com/endless-sky/endless-sky-assets/pull/108
 - [x] I created a PR for the @2x version https://github.com/endless-sky/endless-sky-high-dpi/pull/330

### CODE REVIEW

**Comment by RisingLeaf** [comment]
everything is uploaded, ready to be reviewed

**Review by Saugia — CHANGES_REQUESTED** [review]
Concept-wise: Fun! New universal object formations are always good in space exploration games.

Execution: Needs work. The sprite looks a bit too perfect. shape-wise. While there is some variation in the tiny little "dust" smears, they're all around the same thickness though they do have varying lengths. They also seem a bit too defined in some places, while others you do have nicer opacity. Some references, mostly in-game:

neb

Planetary nebulae are a lot more gaseous. While that's more so than a planetary disc, take note of the gradients. Your small patches do have gradient colors, but the scale of the gradient is making each piece look less like a cloud of gas or dust and more like a piece of paper. They need to be slightly grittier and dust-ier. 

carb

Same with carbon stars. Much more gaseous. Again, a star and not planetary disc, but keep in mind the design.

proto

It's good to reference our now-used Protostar graphics. The dust/gas here is also much more defined and less flat-looking, and is relevant to the object you're trying to make.

blackhole

Another good reference would be SagA*. It has a huge accretion disc which does have similar more perfectionist rings. The rings themselves are fine both in this PR and SagA*, but imagine if you were to chop out little bits of SagA8's (don't just do this) - they wouldn't look as flat and flimsy as the bits in your sprite. They'd have more gradient, grit, depth, etc..

oo20180620-Dong-et-al-ENG

Finally, just something I searched up on google. Might be worth making the sprite more visually interesting by having one to three various-sized chunks that imply some sort of planetary formation.

**Comment by RisingLeaf** [comment]
Updated the sprite according to @Saugia  's review.
2x and asset also updated.

**Comment by Saugia** [comment]
Much more interesting and less messy. Let's see what other have to say.

**Comment by Hurleveur** [comment]
Does it really have to be this huge of an image? The game weighs 700 mb and this does 35 mb (5% !). It really feels like a high dpi version to me

**Comment by RisingLeaf** [comment]
> Does it really have to be this huge of an image? The game weighs ~~700~~ 500 mb and this does 35 mb (~~5~~ 8% !). It really feels like a *high* high dpi version to me
> 
> edit: the nova image takes only 1.2 mb there is definitely something you can do to drastically improve the size here. The whole galaxy image is only 7.2mb...

Hmmm you are right, size is too much, not sure how to get it lower though. Just turn compression up?

**Comment by RisingLeaf** [comment]
So, I got the size down to 9mb, I dont get it any lower without getting losses. At least with the method I am using.

**Comment by Hurleveur** [comment]
Good work!
Yeah never said we should lose quality, but its good to get it as low as can be without losing too much of it like you did.

**Review by beccabunny — CHANGES_REQUESTED** [review]
Imo, it's still somewhat too regular at high levels of zoom - next to the planets and everything it looks stunning, but if you looks too close it loses some of that look

Unrelated, but have you tried making it a jpg with black background? It should solve the size issues in my experience, but dunno

**Review by beccabunny — APPROVED** [review]
Send it

**Review by Saugia — APPROVED** [review]

**Comment by Zireael07** [comment]
Is the picture your own creation or based on something (Nasa?) Just wondering...

**Comment by RisingLeaf** [comment]
> Is the picture your own creation or based on something (Nasa?) Just wondering...

I created this in blender. If you look at the PR description you will see a link to the asset PR.

**Pull request merged**
