### PR TITLE
[content] Southern Carriers II (including "Boxwing": cargo fighter)

### PR DESCRIPTION
**Pull request by LocalGod79**
so, here's where we can discuss the actual specs of the "F6-C" (sixth human fighter, cargo type) as a continuation of #939.

i've altered the specs somewhat from what was discussed before (in a couple of threads).

i think i might bump the mass up a bit more - to handle like a bulk freighter, it should have a mass of 227, but that's unreasonable.

edit; final @2x
boxwing 2x

### CODE REVIEW

**Comment by pootthedestroyer** [comment]
If handling is an issue, lower engine capacity and make terrible engines. Alternatively you can just lower engine capacity to zero and directly integrate some low engine values into the hull, but I know that's frowned upon.

**Comment by LocalGod79** [comment]
as it's prepared right now, it's equipped with the smallest engines available (new ones for the Barb), and to fit bigger ones in the Boxwing, choices will be necessary (and/or alien outfits).

i'm just trying to find an appropriate precedent, since this is "fresh snow" - untrodden territory.

for the moment, i'm trying to balance capacity vs crew vs cost, and am realizing immediately that this is an "end game" solution, so making the new carriers (esp. the Skein) almost as good as the Bulk with the Boxwing is not game breaking (as long as i balance properly).

**Comment by pootthedestroyer** [comment]
I think I may have misunderstood you. I thought you were reluctant to increase the mass to reduce performance, because it was currently handling too well. My suggestion was to create even smaller, even worse engines to reduce its handling to something appropriate, and then reduce engine capacity so that the player wouldn't have options to make them nimble.

**Comment by LocalGod79** [comment]
i'm fooling around with the numbers, seeing how it plays in the game...

the sprite is a little large as well, so i've got a little scaling to do...(but the quad engines look pretty cool)

**Comment by Amazinite** [comment]
That sprite looks like a flying coffin. Not sure if that's intended, given the description.

**Comment by psychiclegume** [comment]
So this is the Boxwing, right?

**Comment by LocalGod79** [comment]
@pootthedestroyer the problem with reducing the outfit mass is that it also reduces the overall mass of the ship, so i'd have to tack some on to the hull anyway.  and add *another* outfit that isn't used anywhere else (in the vanilla game).  using the newly created X1050s is a good plan.

the extra weight is easily justified by the hull strength and really does make the Skein feel like an overburdened freighter when the fighters are in bay.

the question now is, do i also employ solar generators to replace the AA, and cut the outfit space again to make more room for cargo?

@Amazinite not consciously intended, but a happy coincidence nonetheless.  i'll add it to the description.

**Comment by Amazinite** [comment]
Extra space before the last sentence. Comma before jocks intended?

**Comment by LocalGod79** [comment]
@Amazinite indeed (intentional) - it's to abbreviate "Fighter jocks"

**Comment by Amazinite** [comment]
#868 please.

**Comment by LocalGod79** [comment]
hopefully your combat fighters are quicker to the target and start taking the hits first...

the Boxwings, having no guns, do not engage hostiles (and just try to follow their parent ship around)

**Comment by LocalGod79** [comment]
@endless-sky i think this ship is ready, as an addendum to #939 

price at the shipyard is 399k - enough to make the Skein into a "viable" replacement for the Bulk Freighter (at about half a mil less at the checkout), being slower, fewer turrets, and having the inability to reduce the minimum crew below seven (using androids) - final fleet cargo / (Skein + 6 Boxwings) = 660 tons

the drag figure is unprecedentedly low, but the engines one can fit are extremely limited.  without swapping parts out of korath fighters, 609 top speed (909 with).

the heat dissipation figure is also unprecedented, but can be explained by equipment that regulates the temperature of the cargo hold (one presumes those potatoes are being transported in near-ideal conditions).

this detail, combined with the hull integrity further explains the base ship mass.

are there any adjustments you would make?

**Comment by LocalGod79** [comment]
after careful consideration, 'automaton' is a strict no-no for this ship.

with this addition (coupled with the Southern Carriers), one could theoretically create a fairly efficient cargo fleet without triggering the normal "freighter raider" pirates that plague merchants.

while this is still possible without the Boxwing (by retrofitting heavy warships with cargo expansions), the Boxwing makes it far more likely (and without the raiders, there needs to be some tradeoff - in this case, a 100 credit/day overhead for 90-105 tons of cargo space (replace AA and D14 with a solar panel, a battery, and cargo expansion for the extra 15).

**Comment by LocalGod79** [comment]
@endless-sky this can still be merged for 0.9.0...

**Comment by LocalGod79** [comment]
so, in addition to updating the X1050 Ion Engine sprite, after some feedback, new carrier sprites.
for the Skein - "flags" or no "flags"
nestroostskeinskeinflag

**Comment by pootthedestroyer** [comment]
I like the extra detail. It's always nice to differentiate the ships a
little bit more from their structural cousins, and more clearly define them
by faction too.

**Comment by LocalGod79** [comment]
the old sprites were flagged fairly well, but when i was visiting the Hauler III sprite, i noticed a couple extra details, and it got me thinking: this ship, being restricted to the militia, would probably get some kind of decoration, if not from the shipyard, then the crew would add it.  i figured some tapestry-like canopy/flags would be suitable...

i believe the new sprite gives the Skein a little bit of a 'Chinese Dragon' feel, which maybe makes it a little more intimidating;
skein

**Comment by LocalGod79** [comment]
in game, carrying finches and a pair of boxwings, photoshopped a flying one in;
screen shot 2016-05-02 at 8 17 35 pm

**Comment by psychiclegume** [comment]
In Free Worlds color, it doesn't look that different from front to back. Maybe if you darkened to back part just a little, it would look a little more balanced.

**Comment by LocalGod79** [comment]
made the middle more "middle"
screen shot 2016-05-02 at 9 59 17 pm

**Comment by endless-sky** [comment]
I *still* think you need to spray-paint a bit of shadow on the edges, particularly to break up that large patch of color (which should maybe also be shrunk to about 2/3 its curent width). In particular, if nothing else you should darken the cockpits so they stand out better. Plus, shadows make it look grungier and less artificial:

raw shadowed

Without shadows:

unshadowed

With shadows:

shadowed

**Comment by LocalGod79** [comment]
added a hinge for the cargo door - thoughts?

hinged

**Comment by pootthedestroyer** [comment]
I think I've been out of the loop for awhile. The hinges and bolted plating
look good, and reinforce the theme of the ship. The flair.. not so much. It
makes perfect sense for the Free Worlds to slap a bit of flair onto
carriers, but a flying cargo box is a flying cargo box. While it's true
that the "wings" and whatnot have no real effect out in space as they might
in an atmosphere, they artistically connote aerodynamism and
maneuverability. That's just not a cargo box's bag.

Since it's vital to have some colorization to distinguish the factions, I'd
recommend going with some barely-decorative spray painted stripes.

**Comment by LocalGod79** [comment]
the "winglets" were originally intended to be congruous with all other ships - even the bulk freighter has little fins.

another option is to colourize the engine struts...
nowings

**Comment by LocalGod79** [comment]
okay, did a little more work on the model, to give it more Southbound flavour (elements that would have previously been covered by the winglets.

then a little more to do a nice "painted" post, and here's the result;
moresouthbound

**Comment by pootthedestroyer** [comment]
I definitely prefer this more bare-bones version. And you're right that the
bulk freighters have flair, but they are very large ships with hyperdrives
and everything. I think the Boxwing is the bottom of the barrel in terms of
simplicity and economy of design.

**Comment by LocalGod79** [comment]
@endless-sky the desaturation layer that gives the paint a flaked look is pretty malleable, and i believe can enhance the look of ships that are supposed to be "older".

here's a leviathan i've treated with the layer;
leviathan

**Comment by LocalGod79** [comment]
i'm working on making the GIMP assets appear more like the work i did in Photoshop - adjustment layers don't port, and the two apps handle saturation blending differently - it looks like GIMP screens, while PS multiplies...
GIMP vs. Photoshop
skeingskein

**Comment by LocalGod79** [comment]
new sprites at Zug's 'yard;
screen shot 2016-05-11 at 10 31 42 am

i think everything is in order and that i'm done with this, @endless-sky.

assets and @2x in .zip files are here;
https://drive.google.com/folderview?id=0B92_vuqiHabWZEdfYWJKTXNuMDA&usp=sharing
 (i'll leave them there until i see the files added to the E.S. assets)

**Comment by Wrzlprnft** [comment]
Good work. Just look that your work doesn't get much more darker/desaturated in future.

**Comment by LocalGod79** [comment]
no, i'm really done...if Kerry JS is going to redo all of them, then there's not much point in me working these over any more...

**Comment by Amazinite** [comment]
Rip.

**Comment by LocalGod79** [comment]
@Amazinite - the main purpose of this pull was to introduce a cargo solution for fighter bays (before 0.9.0 release).  the testing and balancing for that was done some time ago.

the sprites started to get addressed additionally when some found them too bright, "flat" and colour saturated.

since a professional is doing sprite replacement work and getting generally positive feedback, i expect that he'll probably redo all of the ships, which have mostly been "good enough" placeholders until now.  the sprites in this pull are now at that same level, and will hold the places until Kerry gets to them.

if there's anything to be done, it's to smooth the ship description - it doesn't flow as nicely as i'd like it to.

**Comment by LocalGod79** [comment]
@endless-sky is there anything else that would make you more comfortable with this pull request?

**Comment by endless-sky** [comment]
With the current stats, the Boxwings can weigh 235 T each. That's a bit excessive considering that the Dagger and Lance are 109 and 119 respectively. I'd recommend removing the shield generator, setting the base mass to about 20, and reducing the cargo capacity to 70 or 80. That way a fully loaded Boxwing will only be 130 or 140 T, in line with the other fighters.

The shields and hull also seem way too high. Maybe you could eliminate the shields but leave the hull at 1000?

**Comment by LocalGod79** [comment]
i had actually hoped to make the Boxwing customizable into a "meatshield" fighter (since without weapons mounts, this ship always "swarms" its parent ship).  as it stands, mass expansioned out, one can just squeeze a S-970 and supporting systems (bringing the final price tag to near 2.25M credits, each)

i fear that your proposed changes would completely nerf that possibility. (which, admittedly, may have been your intention.)

the base mass was intended to:
a) balance the shield/hull/cargo stats
b) make both the fighter and the carrier handle more like the frankenstein freighter they were becoming
c) balance the absence of raider pirates that normally accompany freighters.

**Comment by LocalGod79** [comment]
@endless-sky : made some changes - some outright concessions, others an attempt at middle ground.

thoughts?

**Comment by endless-sky** [comment]
Is it intentional that the Skein has "flags" but the other two don't?

Other than that, it looks close enough to being balanced that I could merge it in. I really doubt people will prefer a 2.25M credit "meat-shield" with no weapons over a 2.25M credit Quicksilver, though.

**Comment by LocalGod79** [comment]
when i looked at the Hauler III sprites again, i noticed that they had extra details that i had omitted while constructing the carriers.  also, i felt that being restricted to FW Militia, they deserved "more aggressive" looking sprites.

i made a minor shift, since all other ships have some "customization space" when purchased stock.  i hope it doesn't step too far...

**Comment by pootthedestroyer** [comment]
If you actually want the "meat shield" to be a valid option, you might
consider giving them robust anti missile capability. Unfortunately I have
no idea how you'd do that for just that one ship in one configuration - you
might need to create an entirely new fighter with a similar graphic that
has that capability hardwired in.

Otherwise, the "meat shield" approach may just remain a noob trap. Since
this is a cargo conversion solution, that might not be so bad.

**Comment by LocalGod79** [comment]
@pootthedestroyer actually, this is as simple as defining an anti missile turret in the hard point definitions, without adding it to the outfits (presto, un-removable turret).  unfortunately, at this point, that means sprite adjustment, as well as rebalancing.

another option for the player, going forward, is to equip missile jamming equipment in converted cargo space.

perhaps for 0.9.2 we can revisit this ship, and balance it out with an anti-missile system. (unless you'd like this all hashed out in the first merge, @endless-sky)

**Comment by endless-sky** [comment]
I've merged it in for now. 0.9.1 will probably be in about 2 weeks, so that still gives people who are building the game from source a little while to test it before the ravening hordes of Steam users get their hands on it.

**Pull request merged**
