### PR TITLE
docs(PR Template): Add title guidelines

### PR DESCRIPTION
**Pull request by Hecter94**
## Summary
This PR updates our PR template with several basic good practice guidelines for titling PRs, as discussed in issue #7504 
This provides contributors with a standardized template for naming PRs, allowing better and more accurate titles that better follow a standardized format. 

This allows reviewers and maintainers to more quickly and easily discern what a specific PR is changing without necessarily needing to view the PR itself. It also helps remove some of the ambiguity of a non-standardized naming scheme. 

Adopting this will also open up a couple of future enhancements, such as:

1. Automated testing to ensure PR titles conform to our guidelines
2. Automatic tagging of PRs based on the title
3. Automatic assignment of PRs based on the title
4. Better categorization of PRs
5. Better and more thorough labeling of PRs

As we get more individuals wishing to contribute and expand our developer and reviewer team, additional guidelines and automation of basic tasks will help minimize repetitive tasks and allow our maintainers to better focus their efforts on improving the project.

Suggestions for additional Types/Scopes/Factions or changes to the definitions of existing ones are welcome.

## Screenshots
image

image

### CODE REVIEW

**Review by roadrunner56 — APPROVED** [review]

**Comment by Hecter94** [comment]
Requesting a review from Code Patrol to look over the included types/scopes and make sure they're appropriate for code PRs

**Comment by RisingLeaf** [comment]
If we are doing scopes, why not go for AI, Mission, Mechanics and Action etc.?

**Comment by Hecter94** [comment]
> If we are doing scopes, why not go for AI, Mission, Mechanics and Action etc.?

We could do that if people think including those scopes would be helpful. What would you suggest adding?

**Comment by RisingLeaf** [comment]
> > If we are doing scopes, why not go for AI, Mission, Mechanics and Action etc.?
> 
> 
> 
> We could do that if people think including those scopes would be helpful. What would you suggest adding?

Hmm maybe instead of scope, where faction is for content.

These are the ones I have in mind:
- AI
- UI
- Mission 
- Ship
- Outfit 
- Engine 
- Gameplay

**Comment by Hecter94** [comment]
> > > If we are doing scopes, why not go for AI, Mission, Mechanics and Action etc.?
> > 
> > 
> > We could do that if people think including those scopes would be helpful. What would you suggest adding?
> 
> Hmm maybe instead of scope, where faction is for content.
> 
> These are the ones I have in mind:
> 
> * AI
> * UI
> * Mission
> * Ship
> * Outfit
> * Engine
> * Gameplay
> 
> I am open for more

Okay, I've added a couple of those to the template under `scope`
I think it's best to keep them all as part of scope for now, so they fit within the specified guidelines.

**Comment by petervdmeer** [comment]
Looks good, but do people that submit new PRs now also have to remove the new text that was added?

**Review by petervdmeer — APPROVED** [review]

**Comment by Hecter94** [comment]
> Looks good, but do people that submit new PRs now also have to remove the new text that was added?

Yes. It's part of the template, so they will have to remove it before opening the PR. 
I've made that section as small as possible so it's not too intrusive if they do forget to remove it.

**Comment by petervdmeer** [comment]
> Yes. It's part of the template, so they will have to remove it before opening the PR.
> I've made that section as small as possible so it's not too intrusive if they do forget to remove it.

For now I guess this is fine. For the future we could consider to use multiple PR templates (GitHub also seems to support that) and just pre-fill the various templates with the correct syntax and fields.

**Comment by Amazinite** [comment]
I will say that I'm not so sure about saying that PR names should be formatted like our commit names. It feels similar to me like a comment from tehhowch on #7467. That is, I don't really think that the category that a PR falls under is the poster's call to make. Just looking to those PRs that some people do format similarly to our commit names, it's not rare for me to disagree with the poster and label or commit the PR under a different category.

Can we not simply have a line at the top of the template that says "Please name your pull request descriptively," or something like that?

> Adopting this will also open up a couple of future enhancements, such as:
> 1. Automated testing to ensure PR titles conform to our guidelines
> 2. Automatic tagging of PRs based on the title
> 3. Automatic assignment of PRs based on the title
> 4. Better categorization of PRs
> 5. Better and more thorough labeling of PRs

What happens if a PR title fails the test? What do we do then?
Do we really need automatic tagging and assigning of PRs? Are we not capable of handling that manually? Do we have difficulty at the moment with labelling and assigning that automation would address?
What about automating this would make categorization/labeling better? If the automatic categorization/labeling is just the same as what we would do manually, how would that be better? If it'd be different, how?

> As we get more individuals wishing to contribute and expand our developer and reviewer team, additional guidelines and automation of basic tasks will help minimize repetitive tasks and allow our maintainers to better focus their efforts on improving the project.

Is labeling an intensive task that we need to automate away from people? What use is the triage role that we gave to a bunch of people if labeling becomes automated?

**Comment by Hecter94** [comment]
> Can we not simply have a line at the top of the template that says, "Please name your pull request descriptively," or something like that? Just a small reminder. 

The main issue with this is that everyone has a different idea of a descriptive name; what may be a perfectly legible and understandable name to one person may confuse another. 
Setting standardized guidelines for how names should be constructed helps contributors name their PR descriptively rather than simply telling them to do so.

> What happens if a PR title fails the test? What do we do then? 
We'd have a lot of options! It depends on how much we want to "enforce" our naming scheme and how many PRs we see get opened that don't follow the naming scheme. A couple of automated options would be:

1. Add a specified tag to the PR in question, "Bad Title," or something like that, prompting the contributor or maintainer to update the title or remove the tag if it's not applicable.
2. Post a comment on the PR stating that the title doesn't appear to match our format and to please update it, again prompting the contributor to update it.
3. Fail the test, similar to our style check

All of those options could be done automatically, and there are more options we could do as well; we would want to think about them once we get an idea of how many PRs are following the guidelines. 

> Do we need automatic tagging and assigning of PRs? Are we not capable of handling that manually? Do we have difficulty at the moment with labeling and assigning that automation would address?

Can we handle it manually? Sure, but why should we? If we can automate something, why wouldn't we? 
Let our triage team and maintainers focus on doing things that can't be automated rather than waste their time doing things that we could be automating. 
I want our team to do what they are best at reviewing and working with PRs, not categorizing and labeling them.

> What about automating this would make categorization/labeling better? If the automatic categorization/labeling is just the same as what we would do manually, how would that be better? If it'd be different, how?

Less ambiguity. With a team of people handling categorization/labeling, there will always be times when two people disagree as to how something should be labeled. With an automated solution that follows a strict set of rules, it's *less* likely that there will be ambiguity about how something should be labeled.
Not to say it will be removed entirely, but it will help.

> Is labeling an intensive task we need to automate away from people? What use is the triage role that we gave to a bunch of people if labeling becomes automated?

Members in the Triage role can still be requesting reviews, reviewing PRs, approving PRs, and changing the labels/assignments on PRs in cases where the automated label/assignment ends up being incorrect. 

To give a summary of my position here. We've picked our Triage members as people we trust to do good quality reviews, and whose approval on a PR carries some weight. 
Let's let them do what we recruited them for and not burden them with tasks we could automate, no matter how minor those tasks may seem.

**Comment by Amazinite** [comment]
We already label our PRs, so I feel like requiring that PR names contain some sort of label is redundant with what we already do. Now part of the stated reasoning behind the redundancy is for the potential of automatic labeling. But we already have a fair amount of back and forth on our existing labels. If we can't even get nailed down on which labels should be used where, then I don't think it's a good idea to require that PR names contain some sort of labeling, as that will just create another area for us to argue over the labeling of. And as I also mentioned previously, I think that commit names should be up to the dev that merges the PR, so requiring formatting PR names as if they were commit names feels a bit presumptive. Even barring all that, labeling isn't exactly a time intensive act. It already feels like more of an afterthought to me when it comes to looking at new PRs. So I'm not convinced that automatic labeling is something we should be striving to have.

With us already having discussions every so often on the existing labels we have, I think we'd be better off spending more energy on that rather than creating a separate front to argue on.

**Pull request closed without merging**
