### PR TITLE
Add remodel of the Dagger

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds remodelled sprites for the Dagger.

dagger1
dagger2

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/82
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/303

### CODE REVIEW

**Review by pilover100 — APPROVED** [review]
Another fine piece of work here Gefu, the dagger now looks more fleshed out and is easier on the eye in places such as around the cockpit. This looks like it can be merged into master as it stands.

**Comment by Anarchist2** [comment]
Keep in mind that Derpy wants to give the two-gun fighters an extra port in the future.

**Comment by EjoThims** [comment]
> Keep in mind that Derpy wants to give the two-gun fighters an extra port in the future.

I think Dagger and Lance here could easily do a central one as an addition with no other changes, but that might mean doing a Dropship update after all.

**Review by Saugia — APPROVED** [review]
Github is lying I approved this a day ago, good model. :)

**Pull request merged**
