### PR TITLE
WIP: Allow missions to specify random outfits & random outfit quantities

### PR DESCRIPTION
**Pull request by tehhowch**
Refs #3082 
This PR extends support for random outfit picking, and random outfit quantity picking, in missions / jobs, to replicate the available features for mission cargo.

Also added to support the above
 - Category restrictions for the randomly selected outfit:
   - "random outfit" (e.g. purchased or looted from a ship)
   - "random minable" (located within a minable asteroid)
   - Use of an Outfit category, e.g. Power: "random power outfit", "random power minable"
 - Missions involving delivery of outfits to a destination (whether or not the outfits are given to the player) compensates the player for the used cargo space, just as though the outfits were "mission cargo"
 - Text substitutions in the form of `<trigger: _____>` where trigger is any of `offer`, `complete`, `accept`, etc.
   - These substitutions allow the mission writer to relay the requested outfits, cargo size, etc to the player in the appropriate place, e.g. tell the player about a stopover transfer in the stopover dialog and mention only the gifts transferred during the stopover, or tell the player on accepting which outfits will be picked up at the stopover and which outfits will be removed at the destination, without requiring them to be the same outfits.

A usage example:
```
on complete
    outfit "random power outfit" -1 -5
    payment 16000 150
    dialog `The store manager pays you <payment> and thanks you for delivering <complete: gifts given> to address the equipment shortage.`
```

TODO
 - [ ] Implement an optional value-based payment (#3082 ) that has the player either pay or be paid for gifted outfits
 - [ ] Check over random weights to ensure they introduce sensible bias for randomly picked outfits/minables
 - [ ] Perhaps implement space-checks to prevent jobs that are too large for the player to complete from being offered (non-jobs should probably be offered even if too large)
       - Always offering is a possibility because the player can upgrade their fleet in order to accommodate the requested job size
 - [ ] Clean up implementation (removing unused added functions / includes / development commentary)
 - [ ] Address community issues & feedback

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm really confused about why this would be useful. Is this for missions that would require you to go out and acquire a random outfit and deliver it to a planet? That seems like a very limited use case.

**Comment by tehhowch** [comment]
Indeed that is the intended use. It would have the most use in supporting mining jobs of variable quantity. Delivery jobs of outfits would also be possible.
The minimum addition I'd be happy with would be the random quantity generation for a specific outfit. A goal would then be random minables payload selection, with everything else as a bonus. To me these extras are a logical extrapolation of what is done for cargo also being supported for outfits.

**Comment by endless-sky** [comment]
Except, for cargo there are never missions that say, "Go buy 10 tons of medical supplies and bring them here." So, they're really completely different: mission cargo can have random names, but it's always given to you by the mission itself.

**Comment by Amazinite** [comment]
Closing all PRs older than 2020 which don't have any active discussion. If we wish to revisit these PRs then they may be reopened.

**Pull request closed without merging**
