### PR TITLE
reorder Carrier's HAM turret

### PR DESCRIPTION
**Pull request by Nescio0**
Placed the Carrier's first Heavy Anti-Missile turret on the first mount, to cover a greater area and protect it from full frontal missiles.

### CODE REVIEW

**Comment by tehhowch** [comment]
But now it can only inflict damage on a smaller area.

In other words, this is a preference change - both the current ordering and your proposed ordering are equally valid.

**Comment by KiLEdEnNis** [comment]
either position still only covers a certain "aura" around it, i.e. you either cover all sides a bit, or 1 a lot and another not at all

comparing it to other ships which btw have several AMs doesn't validate this preference change, it's unnecessary

**Comment by Nescio0** [comment]
Until 80f9f5967092b6f3590579bda1af796f37533480 a few days ago, the Carrier had only one AM turret, on the third slot. But because it now has two, it makes sense to spread them out, as is done with other large ships that have multiple AM turrets.
Because the HAM has a range of 200, the Carrier's sprite is 270×400 (which includes some empty space) and the Carrier is widest at the back, I'd recommend putting the AM turrets on the second and fourth slot.

**Comment by Nescio0** [comment]
Sometimes it's helpful to visiualize things, therefore I've marked the Carrier's turret positions and drawn r=200 circles to show the area covert by a heavy anti-miisile turret:
carrierturrets

The Carrier used to have only one HAM, on the second slot (magenta), which provided imperfect although the best possible coverage. 80f9f5967092b6f3590579bda1af796f37533480 added a second HAM on the third slot (yellow). Initially I proposed to move that one to the fourth slot (cyan) and to preserve the other on the second (magenta). However, now I've made this image, I realize the Carrier's currently completely unprotected against full frontal missiles. Therefore the sensible thing to do is place its HAMs on the first (green) and third (yellow) slots.

**Comment by tehhowch** [comment]
I'm pretty sure the range is 2x that, as the game draws at half size.

**Comment by Pointedstick** [comment]
Cool, let's do it.

**Comment by tehhowch** [comment]
Here we see the carrier firing its heavy laser turrets:
image

Heavy laser turret range is 400, 2x that of the Heavy Anti-Missile:
https://github.com/endless-sky/endless-sky/blob/ba784996fcb43aa6f1ffd7f7ff49ec1faf933a0d/data/weapons.txt#L244-L245
https://github.com/endless-sky/endless-sky/blob/ba784996fcb43aa6f1ffd7f7ff49ec1faf933a0d/data/weapons.txt#L366-L367

So even a HAM on the 3rd turret protects the bow (and the 4th just barely):
image

**Comment by tehhowch** [comment]
Game draws sprites at half scale to maintain detail during affine transformations. So a 270x400 pixel image will be drawn in game at 135x200. This would have been apparent if you had launched the game and taken a screenshot at 100% Main (UI) zoom and 100% View zoom:
image
(145x206 there, and obviously could be cropped further)

This detail is mentioned in the wiki as well: https://github.com/endless-sky/endless-sky/wiki/CreatingShips#sprites

**Comment by Pointedstick** [comment]
Revert if you like; I really have no strong opinion on the matter. So much ado over the placement of one turret. :)

**Comment by Nescio0** [comment]
If the range is actually twice as large, then I don't really understand why the addition of the second heavy anti-missile turret was necessary.

**Comment by Pointedstick** [comment]
Because it doubled the weight of anti-missile fire, which is important on large capital ships now that missiles are more powerful and numerous. I settled on the rough standard of mounting two HAMTs as a factor distinguishing capital ships from other ones.

**Comment by Nescio0** [comment]
Yes, but more anti-missile turrets also means sacrificing ordinary firepower. Anyway, that's beyond the scope of this request.

**Pull request merged**
