### PR TITLE
Simplify Ssil Vida activation/deactivation events

### PR DESCRIPTION
**Pull request by warp-core**
**Bugfix:**

## Fix Details
The `wr1` image these events use for the Caeculus star was removed.
Station sprites were doubled in resolution and given a 0.5 scale when rendered in game, but these events weren't updated.

Otherwise, these events were entirely unnecessarily redefining the entire system.
Instead, they now make only the changed necessary.

## Testing Done
soon:tm:

## Save File
as above

### CODE REVIEW

**Comment by Zitchas** [comment]
One of the reasons that I defined the entire system instead of using "add" anywhere is the fact that this pair of events is, at minimum, going to be used at least 6-8 times each over the course of the campaign. Some players may end up invoking them dozens of times. While adding and/or removing saves some data space; I find it much clearer and simpler to be able to just see which event was triggered most recently and directly read *exactly* what is in the system. Having to go through the process of adding stuff then removing stuff then adding stuff and removing stuff potentially dozens of times is just building in unnecessary points of failure, unnecessary complexity, and makes both the game and me do that much more work keeping track of everything.

That being said, I'm running *hard* into the limitations of Endless Sky's engine, including the fact that the game *really* doesn't like having missions go to places that don't exist when the game data is initialized. So I'm hoping that at some point we get engine support for simply *moving* players in mission code so that the activation de-activation can simply move the player from Ssil Vida (de-activated) to Ssil Vida (activated) that is located in what basically amounts to a mini-map using a different galaxy somewhere else. It would solve a *lot* of problems.

**Comment by warp-core** [comment]
> Having to go through the process of adding stuff then removing stuff then adding stuff and removing stuff potentially dozens of times is just building in unnecessary points of failure, unnecessary complexity, and makes both the game and me do that much more work keeping track of everything.

Using `add` is actually the least work for the game. `remove`ing a single item is usually less work than clearing the whole collection and then re-adding everything but a few items. However, redefining *every* property of a system, even though a lot of them are unchanged, definitely adds more work for the game.

There is already a condition to indicate which state the systems are in, and these events just alternate between two states. Trying to find the most recent instance of either of these events in a save file in order to figure out the current state of the systems doesn't actually seem to me like it'd be that easy: if you really need to figure it out, keep a "template" copy of all the systems to indicate what they should look like under each condition, but don't shove that into the save files half a dozen times.

I have already removed almost 400 lines from these events, this is without using the new `remove` feature on `object`s, so those are still being fully redefined. Six times, that's almost 2.5k lines, that's not a small amount.

There's also the fact that redefining stuff that you aren't actually changing *adds* confusion: "This is being redefined but it doesn't look like anything has changed. Am I reading it wrong?" Do you need to actually know the state of the trade values, and would going to the map file be too much hassle if you did?

You already *don't* redefine Caeculus and Levana on deactivation, only adding the wormholes.
The only change in those systems is the addition and deletion of those wormhole (and the permanent removal of the Embershades fleet from Caeculus, but I suspect that's just because the fleet wasn't added until after these events were and no one though to ensure these events were updated, not that I can blame them: these events don't actually intend to change fleets so a person could be forgiven for not thinking to update them with the new fleet).
You also already use `remove` for the Void Sprite and Subsidurial fleets within some systems. This fails at your intention of not needing to check previous changes because it raises the question: are any fleets left?
Using `remove fleet` eliminates this question because it explicitly removes all fleets.

Redefining them also leads to issues like the star sprite these events put in Caeculus no longer existing. The base map file was updated to use a different one, but this event was not. And, even if it had been, anyone who had this event in their save file already would still not see a star there; they'd have to go activate and deactivate Ssil Vida to get the fixed version (once a fix is actually applied.)
Similarly, habitable distances and distances and periods of objects have been changed, but the person who changed them didn't update these events because, I assume, they couldn't tell what is going on. (See: https://github.com/endless-sky/endless-sky/commit/1797f560765d7259d2c265dbba93021005988442)

No objects are added to or removed from Diespitar or Vaticanus, but the periods and habitable are all different to the map file, and the belt is further away. I can't tell if these are intentional or as a result of the event not being updated alongside the map file.

I'm making this a draft for now because I think there are some other changes I'd like to make  before it's ready.

**Comment by Zitchas** [comment]
Fair. It is also worth noting that this is a minimal-functionality state. The cluster of systems here will be getting a lot more stuff in the future, including life forms, planets, mineables, etc. And virtually all of it will be present only while Ssil Vida is active. Which is why it's not already there: Those planets will be mission destinations, but last I checked, having missions go to planets that don't exist at data load leads to some odd behavior.

I guess this is a way of saying "don't invest too much time into this, because it is going to be changing in the future and I'm very partial to the idea of creating two separate sets of these systems and moving the player between them instead of actually changing the system."

**Comment by warp-core** [comment]
> Those planets will be mission destinations, but last I checked, having missions go to planets that don't exist at data load leads to some odd behavior.

Planets that don't exist or planets that aren't assigned to a system?
From what I can tell, the planet needs to be defined but doesn't need to appear in a system. And, I can think of no good reason for a planet to not be defined in the base data, even if it is only ever assigned to a system object by event.

**Comment by warp-core** [comment]
I think I've mostly got the activation and deactivation events to where they should be.
Next steps are to create patch events and missions to reset the state of the systems if the old versions of the events have already been applied before the new versions are ever used.
Will also need to decide about how jump range is limited since that might change.
@Amazinite may also want to look at the distances and periods of the wormholes created and removed by these events.

**Comment by Zitchas** [comment]
Please note that these systems aren't intended to follow "normal" periods or distances.

**Comment by warp-core** [comment]
> Please note that these systems aren't intended to follow "normal" periods or distances.

From what I can tell, they matched the definitions in the map file when they were first created. The map file definitions have since been changed. If those are supposed to be abnormal, that should probably be addressed.

**Comment by Saugia** [comment]
@Zitchas Any plans to look at this? You have your self assigned due to some concerns with how this PR works, however this is a desired changed that we'd like to look at sooner than later.

**Comment by tibetiroka** [comment]
@warp-core Can you fix the merge conflicts?

**Comment by tibetiroka** [comment]
Closing as orphaned. Feel free to reopen this PR once the conflicts are resolved.

**Pull request closed without merging**
