### PR TITLE
New tipe of Sestor and Mereti asteroids

### PR DESCRIPTION
**Pull request by beccabunny**
This PR introduces a two new tipe of asteroids, one for the Sestors and one for the Mereti. Since there has been a civil war for hundreds of years, i think it could make sense that there there are small parts of spaceship floating in the system closest to the border between the empires. They are minable and release some materials common in their empire's respective part of galaxy and that may have been used in their spaceships
This is my first PR, so don't esitate to tell me what i did wrong

### CODE REVIEW

**Comment by jafdy** [comment]
Why are there over 27,000 new lines? What are they all?

**Comment by IntegratedQuantum** [comment]
It seems like you accidently put map.txt and harvesting.txt into the main folder instead of the data folder.

**Comment by beccabunny** [comment]
How can i do it right?

**Comment by beccabunny** [comment]
Is it right now?

**Comment by IntegratedQuantum** [comment]
Yes

**Comment by beccabunny** [comment]
Any thoughts about it?

**Comment by IntegratedQuantum** [comment]
It's a good idea, but i think the images should contain some visible damages like holes from explosions or dents instead of looking like new.

**Pull request closed without merging**
