### PR TITLE
Fix starting the game with an active takeoff mission.

### LINKED ISSUE #6116: Launching into a save on a takeoff mission takes off on menu
**Describe the bug**
If you launch the game when your last save is a takeoff/launch/flee mission, the game will play the takeoff noise and change the planet to empty as soon as the game is fully loaded.

**To Reproduce**
1. Go a mission with takeoff/launch/flee (such as Remnant: Defense 1).
2. Trigger the takeoff, and quit the game.
3. Re-launch the game, and notice the takeoff noise and planet name disappearing once everything is loaded.

**Expected behavior**
No sound will play, and the planet name will remain until you enter the save proper.

**System:**
 - OS: Windows 10 Pro, version 21H1
 - Game Source: Self-compiled
 - Version: commit hash 3ccb7b4

### PR DESCRIPTION
**Pull request by quyykk**
**Bugfix:** This PR fixes #6116 

## Fix Details

Previously, the two StepAll calls were needed to avoid a flicker for save files with an active takeoff mission, but now panels added during their respective Step call are handled immediately (since #6279). This means that the second StepAll is redundant. Removing it also fixes the linked issue, since there is no second StepAll call that goes into PlanetPanel's Step function that does the takeoff.

## Testing Done

Loaded a save file with an active takeoff mission and verified that the takeoff sound is only generated when actually loading the game. 

## Save File

[1k Weapons.txt](https://github.com/endless-sky/endless-sky/files/8381675/1k.Weapons.txt) (don't mind the name).

### CODE REVIEW

**Comment by tehhowch** [comment]
I still think that change to call panel::step immediately for created panels feels off, which is my only reluctance to merge this.

If removing it also fixes this and doesn't introduce some other bug, I would prefer that. (I would also like to know what bug, if any, is surfaced by removing it.)

Regardless of the fix method, do we have enough capability in the integration test framework to add a test for this scenario?

**Comment by quyykk** [comment]
> If removing it also fixes this and doesn't introduce some other bug, I would prefer that. (I would also like to know what bug, if any, is surfaced by removing it.)

You're referring to the `StepAll` call right? It's needed to prevent the flicker. Previously we needed to call it twice, now only once.

> Regardless of the fix method, do we have enough capability in the integration test framework to add a test for this scenario?

Not really, since the only bug is the flicker that appears for takeoff missions.

**Comment by tehhowch** [comment]
> > If removing it also fixes this and doesn't introduce some other bug, I would prefer that. (I would also like to know what bug, if any, is surfaced by removing it.)
>  > You're referring to the `StepAll` call right? It's needed to prevent the flicker. Previously we needed to call it twice, now only once.

My "it" is referring to this bit of added code from #6279: https://github.com/endless-sky/endless-sky/blame/fbd55e4a75262bb339a673e98cf596c45f05ac26/source/UI.cpp#L102-L104

**Comment by tehhowch** [comment]
> Well without the added code from that PR we need to call StepAll twice to prevent the flicker, which is the cause for the bug. So that's not possible.
> 
> What I can do is try to find an alternative solution if you'd like that more.

Right, without that code we have to call stepall twice whenever we totally create the game panel stack (and only then). So if we remove that code I linked, it seems we wouldn't need the current changes in this PR (removing the 2nd stepall call). My question is: are there any other impacts if we remove that second `PushOrPop` call?

**Comment by quyykk** [comment]
@tehhowch Would you accept me making `PushOrPop` public and calling StepAll + PushOrPop instead of StepAll twice? That would fix the linked bug.

**Comment by quyykk** [comment]
@tehhowch is this approach acceptable? Panels that are about to be popped around drawn anymore. As far as I can tell this only affects the start of the game when the GameLoading panel is popped and the MenuPanel is pushed (because nothing would be drawn until the next frame), but since we're not clearing the screen this has no effect.

**Comment by tehhowch** [comment]
The test save appears to require mods, btw

**Comment by quyykk** [comment]
It shouldn't, does it really? The save file should be of an active takeoff mission, that doesn't work? Yeah the save file itself is a bit of a mess but only the takeoff mission is important.

**Comment by tehhowch** [comment]
It seems like the core of the issue is that we perform an implicit `Land()` and (because we're in a separate UI stack) the guards against `PlanetPanel::Step` launching the player are not active.

Thinking ahead (to my desire for the game to compose data definitions into "runtime" objects on a per-pilot basis upon pilot selection, which allows "native" per-pilot mod configs), I'd prefer if we solve this by removing the implicit `player.Land()`, invoking that method only when the player has confirmed that they want to enter the currently selected pilot.

So the startup flow should eventually be something like:
1) launch binary
2) GameLoadingPanel loads data from disk, credits scrolling somewhere, intro music playing, etc.
4) GLP is replaced in UI stack with a "Save File Selector" panel. The SFS is pretty much an improved `LoadPanel`, displaying the credits, list of saves w/their mod dependencies, and info about the selected save. Default save logic is same as now.
5) "enter ship" clicked
6) Game instantiates "runtime" objects from the current collection of template objects
7) MainPanel & PlanetPanel added to game UI stack (PlanetPanel added by MainPanel ctor or by SFS directly, not by MainPanel::Step)
8) `PlayerInfo::Land` explicitly invoked by SFS or MainPanel ctor
9) SFS removes itself and anything else in the menu UI stack

Opening the menu in game would probably open a more basic menu panel than the SFS since there is already a loaded pilot.


I'd like to solve this minor bug by stepping in that direction. Probably the easiest first step is to investigate using the MainPanel constructor to add the PlanetPanel to the game panel stack and explicitly invoking PlayerInfo land.

What do you think?

**Comment by Amazinite** [comment]
Going through PRs older than three months to find PRs that could be closed.

Marking this PR as orphaned as there hasn't been activity from OP in some time, but not closing because it's a bug fix that we should have. Either someone should open a new PR with these changes finalized, or one of the devs could finalized this PR themselves.

**Pull request closed without merging**
