### PR TITLE
Sestor: Scattered Remnant change

### PR DESCRIPTION
**Pull request by Amazinite**
http://steamcommunity.com/app/404410/discussions/0/135509024338822302/

There has been some confusion with this mission on Steam. I've changed the mission by making it more clear through Danforth's dialog that you most *completely destroy* the ships (I just copied from the mission that defers, because he makes it pretty clear there) as well as putting dialogs on all the fleets that pop up once you have wiped the system clean of Kor Sestor ships..

### CODE REVIEW

**Comment by Pointedstick** [comment]
It would also be nice to have a waypoint on the system with the Alpha base.

**Comment by Amazinite** [comment]
There?

**Comment by Pointedstick** [comment]
Yeah! The first time I played that mission I was super confused because I defeated all the drones in the waypointed systems, but Danforth kept saying there were more. I had to crack open the mission definition in the data file to find that I was also expected to defeat the fleet in Alnilam, which was in the conversation dialogue, but I missed it.

**Comment by Architect-Luke** [comment]
That's actually an error, because there is a separate mission to go destroy the drone remnant in Alnilam. It triggers after completing the scattered remnant mission (so it doesn't trigger, unless you falsify the completion of scattered remnant as I did). The qualification that you destroy the Alnilam remnant to complete this mission needs to be removed; otherwise the separate mission for the Alnilam remnant is wasted programming that will never be seen.

**Comment by endless-sky** [comment]
The missions are designed so that if you already dealt with the remnant in Alnilam (say, in the first mission that took you there) Danforth never bothers to offer you reinforcements to help with taking those out.

These changes look good, but I think it should say, "All the Kor Sestor drones in this system have been eliminated" instead of "You have eliminated..." to account for the fact that the player might just lurk in the system until the local Merchants or the Navy have destroyed the drones.

**Comment by Amazinite** [comment]
:+1:

**Pull request merged**
