### PR TITLE
Minor mass and cargo expansions

### PR DESCRIPTION
**Pull request by retrue**
I was outfitting the last ship I bought when I discovered that I needed a little more outfit space to install the thingie I wanted and I only had left 16 cargo space, so I decided to create this PR.
There is already a small bunk expansion, so small cargo and mass expansions shouldn't be weird.
At the moment, added to Special Outfits only. But I think they could go to Advanced Lovelace outfitters or ideally to that future Smugglers Den outfitter.
And yes, the sprites are not good because they are just edited and recolored versions, but I include here the double resolution versions too.
green screwdriver 2x orange screwdriver 2x

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
My goodness, it is a multipurpose screwdriver.

**Comment by Bladewood** [comment]
I feel like I've seen this in a mod before.
Needless to say, this is not a good idea, because balance issues and stuff.

**Comment by MessyMix** [comment]
The fact that there is no small mass expansion makes ship building interesting. What fun is there in customizing your ship when the jigsaw pieces are the size of water droplets? It's fun when you have to cram tons of things (literally) into a tiny space. You'll make it work, eventually, but it's all a puzzle. You have 16 cargo space left and not 20 because it's intentional. You just gotta make it work.

**Comment by Admiral-Danforth** [comment]
This is like the one outfit space item ideas it will either get abused or end up being pointless

**Comment by Amazinite** [comment]
>This PR tries to cover the necessity of some players (like myself) of using all the available space in their ships. I chose a cooling device because it is unobtrusive and won't change the game experience or balance.

Then goes on to create an outfit that would change balance.

**Comment by Wrzlprnft** [comment]
I'd like to see those in a sandboxmode, though.
When we get a hard mode, i hope there is a sandboxmode then too.

**Comment by retrue** [comment]
They could be added late in the game when human ships are obsolete.

**Comment by Admiral-Danforth** [comment]
Kestrel/Carrier +  Flamethrowers vs Korath = Too Easy

**Comment by retrue** [comment]
@Admiral-Danforth Flamethrowers are weapons. Mass expansions don't change weapons capacity in a ship. I don't understand your comment.

**Comment by KiLEdEnNis** [comment]
@retrue he means human ships aren't obsolete because a human flamethrower ship > Korath ships (since they run near full heat)

**Comment by retrue** [comment]
But they could be obsolete in the future. Anyway, this cargo expansion doesn't break balance, and this small mass expansion could break it, but depends on how it is made. I totally imagine Marauders ships with one of these things and they could be not for sale anywhere, or just late in the game, or in a mode sandbox, or already in the code for modders. Whatever.

**Comment by KiLEdEnNis** [comment]
tbh the expansions make outfit-puzzling fun, these shouldn't be added, makes it too easy

**Comment by Johny-Cash** [comment]
This was suggested by MZ:
There's no other outfit that works this way (installing one uninstalls another), so I think doing this would just add confusion for most people, rather than simplifying things. (Plus, in the future there may be other mass expansions of other sizes; there's no guarantee they will always be exactly paired off with opposite effects.)

**Pull request closed without merging**
