### PR TITLE
Buff the Star Queen

### PR DESCRIPTION
**Pull request by Anarchist2**
The Star Queen is not a great ship: at 5.5 million credits hull price, it is the same cost as the Protector, and costs at least 1 million more than every medium warship. Fitting out the Protector with 11 bunk rooms (leaving it with 370 outfit space, 10 more than the Star Queen's total) gives it 113 total bunks versus the Star Queen's 112, which translates into even more passenger space due to the Protector's lower crew requirement. When putting in as many bunks as possible, the Star Queen has 151 passenger space, compared to the Protector's 193 and the Bastion's 131. (Both warships also have a large HP advantage, and the Bastion's hull only costs 3.8 million.) This PR increases the bunk efficiency of the Star Queen, so that it is a more worthwhile choice.

Changes:
- Decreased the Star Queen's crew requirement from 41 to 33. This increases the stock Star Queen passenger capacity from 69 to 77.
- Decreased the Star Queen's hull price from 5.5 million to 4.2 million. This means that the ship is on the level of mid/high-end medium warships, rather than low-end heavy warships.

### CODE REVIEW

**Comment by Hurleveur** [comment]
Hum... Not sure about this.
The Star Queen is the meta capping ship, pretty sure we shouldn't be bringing the cost down, until we fix capping somewhat.
Now as for the crew requirement I can see that making sense for sure, to make it more easily fill its actual role.

**Comment by Anarchist2** [comment]
If you're buying ships, you're not doing the capping meta. You usually jump straight from a Bastion to something like a Falcon, without needing a Star Queen as a midstep. Keeping the Star Queen "bad" doesn't help fix boarding, and making it cheaper doesn't break capturing more than it already is broken.

**Comment by Hurleveur** [comment]
Maybe its just me then but I used the Star Queen to cap infinite Shield Beetles and whatnot, given its relative small cost.
Cap meta doesnt mean capping only

**Comment by starcatter** [comment]
When already in Hai space, it's better to just get the Centipede anyway. It only takes capping 5-6 Lightning Bugs to afford one, and that can be done in a beefed up shuttle.

**Review by Arachi-Lover — APPROVED** [review]

**Comment by warp-core** [comment]
> Maybe its just me then but I used the Star Queen to cap infinite Shield Beetles and whatnot, given its relative small cost.
> Cap meta doesnt mean capping only
> ref: https://www.youtube.com/watch?v=mOUQ-J5L_PU

You can capture infinite 349s in a Shuttle.
You can also use any other ship with enough bunks (either by default or with bunk rooms) to farm infinite shield beetles.
You can use a lot of cargo ships and trade your way to a huge number of credits, and chances are, you'll be acquiring enough credits to buy a shield beetle faster than you'll be able to capture them before too long.

This doesn't seem like a great reason not to buff the Star Queen to me.

> This probably means the Prot is a bit too cheap?

This consideration has more merit, I think.

**Pull request merged**
