### PR TITLE
(refactor) Decoupling the rendering of UI and main view graphics

### PR DESCRIPTION
**Pull request by DanielWeiner**
NOTICE: Delete the sections that do not apply to your PR, and fill out the section that does.
(You can open a PR to add or improve a section, if you find them lacking!)

-----------------------
**Feature:** This PR implements the feature request detailed and discussed in issue [this feature request](https://github.com/endless-sky/endless-sky/discussions/8071).

## Feature Details
Decoupling the rendering of UI elements and main view graphics. 

This is a refactor of the rendering logic that splits up shader rendering into two types: `ScaledScreenSpace`, whose coordinates are multiplied by the user's scaling factor, and `AbsoluteScreenSpace`, whose coordinates ignore the user's scaling factor. This allows the main space view to be zoomed in/out consistently with the same behavior across all scale factors, while preserving the ability for the user to change the scale of the UI.

Almost every shader has been split into two facades: `Shader::UISpace` and `Shader::ViewSpace`. They function exactly like the original `Shader` implementations, but the `::UISpace` and `::ViewSpace` counterparts render into UI (scaled) and view (absolute) screen spaces.

In addition to that bifurcation, there's also a couple of static helper methods on the `ScreenSpace` base class. 

`Point ScreenSpace::ConvertPoint<ScreenSpaceA, ScreenSpaceB>(point)` takes a point from `ScreenSpaceA`, and outputs an equivalent point for `ScreenSpaceB`. This is useful when rendering in one screen space relative to another screen space. For
example, the Planet Label text is rendered in UI space so that the lettering scales with the user setting. But its position is relative to a planet, which is rendered in view space. This function conveniently makes that conversion.

`double ScreenSpace::ConversionFactor<ScreenSpaceA, ScreenSpaceB>()` returns a number that will scale a value from `ScreenSpaceA` to `ScreenSpaceB`. This can then be multiplied to a scalar value or to a point (which is done internally in `ConvertPoint`).

Note:
This is the first time in many years since I've actually written C++, and I've never written C++ in any professional capacity. So _please_ let me know if I'm violating any conventions or if I could be accomplishing this better.

## UI Screenshots
before:
image

after:
image

## Testing Done
Lots of manual testing to verify that the display is visually consistent, with no scaling mismatch or inconsistencies between the refactored and unchanged game.

### Automated Tests Added
N/A

## Performance Impact
None that I can tell.

### CODE REVIEW

**Comment by DanielWeiner** [comment]
I didn't realize there was a style checker, whoops! I'll make the appropriate style changes.

**Comment by Hurleveur** [comment]
Looks like a lot of work went into this, that's nice to see.
However, two small things: please mark this as a draft so long as it is a work in progress (this probably could use some more work) it probably should stay as a draft until you manage to make the tests run. I see you've been using a recent version of C, I think we're stuck on C11, or smth near it.
Also could you take a look at other files to see the conventions? (3 lines between functions, for instance)

I'll be honest I don't know much about UI so I won't be able to help too much

**Comment by Zitchas** [comment]
Making progress. :)

**Comment by DanielWeiner** [comment]
> Making progress. :) Hopefully the checks are helpful for you.

Yep! Definitely helpful. I'm seeing some local linting errors for code that I didn't modify, so I'm keeping my fingers crossed that this latest change passes.

**Comment by DanielWeiner** [comment]
All right, I think this is good style-wise and functionality-wise, and I believe I fixed that compilation issue for GLES targets. So I'm marking this as ready for review.

**Pull request closed without merging**
