### PR TITLE
Resized Hai stations

### PR DESCRIPTION
**Pull request by Azure3141**
**Content (Artwork)**

## Summary
This fixes the weirdly large scale with the Hai stations, making them more reasonably sized compared to every other station in the game.

-----------------------

## Feature Details
I rescaled the Hai stations to be consistent with the rest of the stations in the game. Previously the stations were larger than most gas giants, which looked bad in game and was very confusing (I initially thought something was bugged with the High DPI plugin).

This still leaves the Hai stations as being bigger than most other stations in the game, but now they don't look completely out of place or as though their scaling is bugged.

## UI Screenshots
Before
image

After
image

## Performance Impact
N/A

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
As discussed on the discord - please present these with justification scaled with respect to *other stations*, not just planets.

**Comment by MasterOfGrey** [comment]
Leviathan Station in human space is 280 pixels across.
Omgur's Siphon is 320 pixels in one dimension and 240 in the other. It is a dedicated fuel mining station of comparable function to one of these without the historical living space considerations.
Station Cian is a military station with a small shipyard used as essentially a large outpost with some light mining equipment, and is 260 across.

The Hai stations should be bigger than all of these.

As I said, I don't mind them being re-sized, but if you're going to argue for some sort of scale then you need to at least keep it consistent within the same class.
If they're smaller than these stations, it's no good.

**Comment by MasterOfGrey** [comment]
> None of those stations appear larger than their parent planets, 

irrelevant

> and none of them are 400 pixels across the way the Hai stations are. 

not the point that was being made

> They also aren't standard stations that appear in every system

also irrelevant


If you want to make a scale argument, you have to keep to a scale that's consistent _within_ the same class of object at a minimum. 
Start by scaling with respect to other stations, or you're not even ascribing to your own claims of reasonability - making this conversation and this effort entirely pointless.

**Comment by MasterOfGrey** [comment]
You were the one who started this discussion with the basis that "they're so much bigger than other stations".

So if you're not scaling them with respect to other stations, then related points are indeed irrelevant.
You set the terms for this at the outset. 

You don't get to move the goalposts to a discussion about how you think they look subjectively in the systems that they're in and then expect that to be ok.

**Comment by MasterOfGrey** [comment]
> That's because they are. The biggest station in your example is still 100 pixels smaller than the standard Hai stations.

And I never said they couldn't be re-sized.

> The entire point is that they are not currently scaled with respect to other stations. I have not "set terms," this is a PR, not a treaty discussion. It seems as thought you've become completely focused on one of my arguments to the point that you're dismissing all others immediately.

Then scale them with respect to other stations - i.e. at least marginally bigger than those listed.

> Why am I not allowed to use the argument that their current scale makes systems look bad? When did that become a rule?

It's not relevant to your actual justification used. If it's actually just a scaling problem, then it's irrelevant. If *after* any scaling problems are sorted, they still look bad, then it's a system design problem - not a scaling problem. It's simply a matter of one thing at a time. Conflating them only makes your position weak and your justifications muddy.

**Review by beccabunny — APPROVED** [review]
As the person who made these stations, I agree that they look very odd the way they are now. LGTM

**Comment by Amazinite** [comment]
If you reduce the scale on the sprites in the map as opposed to shrinking the sprites then you don't need a high DPI PR for this, which you're currently missing if we're to shrink the sprites.

**Comment by Anarchist2** [comment]
We technically don't even need a HDPI PR; the game automatically scales the @2x to fit the dimensions of the original, without throwing an error. ~[This will obviously not lead to any problems whatsoever.](https://github.com/endless-sky/endless-sky-high-dpi/issues/217)~

**Comment by MasterOfGrey** [comment]
> Why do they need to be bigger than every other station in the game?

Because at present, lore-wise, they are - and if we're complaining about scaling then there should be applicable scaling.

Like I said before, I'm down with them being re-sized, as long as we're sensible about it and not *creating* additional inconsistencies just for the sake of it.
I'm happy to agree they're too big, but now in here they're also too small.

And yeah, editing the scaling in the map file would probably be easiest.

**Comment by MasterOfGrey** [comment]
Why has this gone from scale 0.5 to scale 0.3. Actually, I just looked in the map file, why did they have a scale to begin with?
I just checked and there wasn't a scale value when they were first merged, so where did that come from?

**Comment by MasterOfGrey** [comment]
> See #6964

Ahhhhhhhhh, I understand now. Would the scale change produce any fuzziness?

Also, would be good to see before and after shots again, at the same zoom level.

**Comment by Saugia** [comment]
@Azure3141 Can you show images of before and afters of the station sprites?

**Comment by Hecter94** [comment]
Talked with Grey about this PR.
The current scaling of .3 looks a bit too small; Grey would like to see .42 or .41, or possibly even .4, as long as it doesn't look fuzzy

**Comment by MasterOfGrey** [comment]
So the problem happening here is that when you said:
> The stations are at 60% of their previous size, _which still leaves them as the biggest stations in the game._

The maths reveals that was a lie.

The request was to scale them with respect to other stations - i.e. <smaller than now, but> at least marginally bigger than those listed.
To achieve that a scaling of .34 would be the *absolute floor* of possible options.
Based on the shape of the stations involved and the amount of negative space in the sprites for 2 of these, I would propose the above values that Hecter mentioned.
But again, under **_no_** circumstances will I accept a scaling below .34

**Review by MasterOfGrey — CHANGES_REQUESTED** [review]
So the problem happening here is that when you said:
> The stations are at 60% of their previous size, _which still leaves them as the biggest stations in the game._

The maths reveals that was a lie.

The request was to scale them with respect to other stations - i.e. <smaller than now, but> at least marginally bigger than those listed.
To achieve that a scaling of .34 would be the *absolute floor* of possible options.
Based on the shape of the stations involved and the amount of negative space in the sprites for 2 of these, I would propose the above values that Hecter mentioned.
But again, under **_no_** circumstances will I accept a scaling below .34

**Review by Saugia — APPROVED** [review]

**Pull request merged**
