### PR TITLE
enhancement: add or remove individual planet attributes

### PR DESCRIPTION
**Pull request by EndrosG**
With this PR, content creators can alter the attributes list of a planet by adding or removing a single attribute or even a set of attributes without caring about all other attributes of that planet.

_I wasn't first sure if I should remove the braces or not, because it is not a "single expression", but looking at some examples in PlayerInfo.cpp the braces are used in such cases in the ES code._

### CODE REVIEW

**Comment by tehhowch** [comment]
This also makes it unnecessary for new attribute developers to propose methods of "toggling" those attributes... which I was just about to do after you posted in 2543 :+1: 
This looks good on paper.

**Comment by EndrosG** [comment]
Thanks a lot at @tehhowch for just helping me to test / debug / prove that all data ingame was modified as intended.
We did test with a mini mod:
```
planet Earth
	"attributes add" testattribute
	"attributes remove" urban

planet Luna
	"attributes remove" zeroattribute
```

- urban was removed properly, testattribute was removed properly.
- zeroattribute could not be removed (Luna does not have such an attribute) but also no error occurs.

**Comment by tehhowch** [comment]
Attribute modification was verified using a debug block at the end of Planet::Load
```
	// Debug attributes trace
	cerr << "Listing attributes for: " << name << endl;
	for(const string &attribute : attributes)
	{
		cerr << attribute << endl;
	}
}
```

We have verified that it successfully 
1. Adds attributes
2. Removes attributes
3. Does not remove non-present attributes.
4. Throws no errors / warnings.

**Comment by endless-sky** [comment]
I've implemented this in a different way (c2b60cf, 9facdcd) because as I looked at it, it seemed to me that being able to add or remove specific items should work for other planet attributes too.

This lets you do stuff like:
```
remove attributes urban tourism
add attributes "desolate wasteland"
remove shipyard "Southbound Basics"
add description "The Navy has built a base here."
```

**Comment by Elyssaen** [comment]
I'm sure Endros would've been happy to save you time if you'd wanted, but this is a really cool piece of work.

**Pull request closed without merging**
