### PR TITLE
fix(content): Remnant: Cognizance 34 "is" should be "are"

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR addresses issue #{{insert number}}

## Fix Details
"is" to "are"

Thanks to auldr on Discord for spotting and reporting it.

### CODE REVIEW

**Review by roadrunner56 — APPROVED** [review]

**Comment by Hurleveur** [comment]
just wondering, why wasn't this added to https://github.com/endless-sky/endless-sky/pull/7097?
I assumed that one was merged already but it doesn't look like it

**Comment by Zitchas** [comment]
Mainly because that one's already had a bunch of people review the changes and approve them. Adding in another change after a bunch of people have approved it and it's just waiting to be merged seems either deceptive or likely to delay it longer.

While the change itself is tiny, I used the "long text" label because it's part of a rather big block of text.

**Review by warp-core — APPROVED** [review]
Unless you mean you think we should read the whole conversation while reviewing this, it's definitely short. That one line, while a fairly long line, is still well short if being 'long' for the purposes of the label.

**Comment by Zitchas** [comment]
Makes sense. I'll follow that logic in the future.

**Pull request merged**
