### PR TITLE
Grammar fix - Coalition Expedition mission

### PR DESCRIPTION
**Pull request by opusforlife2**
**Content (Artwork / Missions / Jobs)**

Multiple grammar fixes throughout the mission dialogue.

### CODE REVIEW

**Review by Arachi-Lover — APPROVED** [review]
I think this first went like "... that to cease your stubborn attempts, you **are**..." but the *to* remained there when changing to should.
Could alternatively make it be just that, and change the *should* for *are*, but that's just a matter of preference.

**Comment by Arachi-Lover** [comment]
> Yeah, that's what it looked like.
> 
> Depends on how much authority this character has over the Heliarch tribune. If they are a superior, the to-are makes more sense over that-should. But if they are merely a senior trying to give stern but well-meaning advice, then that-should is better.

Well he is of a higher rank, however they are also personal friends, so I think both ways can work in this case. Up to you.


For the other edits:
Use this one for the first `"Said that thought it over, they had, and willing to oblige, they were"`, other one is awkward,
`Edit: and one more:` is fine,
`Edit 2:` is fine,
`Edit 3:` is fine,
I don't think you need to do anything like suggested in `Edit 4:`, not really a way to make this yoda-speechy without also making it way more off than usual,
For `Edit 5:`, maybe "Waste not your life on this" ?
`Edit 6:` is fine.

**Comment by Arachi-Lover** [comment]
I think N7 disrupts the flow a bit, and I'm not too sure it's right.
For N8, the first one works, though I dunno if it's strictly necessary. The second one doesn't work as well in my view.

In general it's not every instance that must be yoda'd, like how when you first tell the Heliarchs of the Hai, `"A second Coalition you are forming!"` instead of "A second Coalition, forming you are!", so I'm not too keen on making the yoda speech affect more minute bits of conversation.

**Comment by Arachi-Lover** [comment]
I honestly don't really know the specifics on the sentence structure used for the Coalition, despite having done the most dialog for them. @W1zrad made sure to help keep it all consistent to what existed previously, so he'd be the best one to look to for the specifics on these changes. Though, as I understand it he's not very available presently.

**Comment by Arachi-Lover** [comment]
> Meanwhile, please confirm my edits.

Thumbs up emote to 9 and 10 was a "looks good" kind of reaction emote.

For 7 and 8, as I said I'm not that good at the strict ruling on this. To me the changes make it seem off, but I can't tell if it should really be done regardless due to grammar stuff, it's why I mentioned Wizrad.

**Review by Arachi-Lover — APPROVED** [review]
Good tweaks, looks good to me.

**Review by W1zrad — APPROVED** [review]
Sorry for the radio silence all. Unfortunately, I don't remember much of the specifics I used to evaluate grammatical correctness with the Yoda-speak, but everything here seems fine.

P.S. - Please continue to feel free to ping me/request reviews. Obviously I don't have as much free time as I used to (and my track record for getting to stuff I intended to isn't great), but I'm still happy to help where I can.

**Comment by W1zrad** [comment]
@opusforlife2 no prob!

I was more referring to the PR itself, not the conversation. Just read through it; frankly, it seems like you've out more thought into the sentence structure than I ever did. I tended to just go off of feel, but this might be a case where sticking to a consistent structure could actually make more sense canonically. The player is always listening through a translator, so the translator is probably going to always "output" identical sentence structure instead of it being varied.

Just my two cents. Up to Arachi on whether y'all want to try to go that route, but hopefully that's a complete enough response to the above conversation

**Comment by Arachi-Lover** [comment]
I do just write off of feel and dunno how well it'd go to learn this pattern and apply it everywhere from now on, so keep in mind would need to be picking up after me on the dialog ~~so nothing new really~~ if we do intend to do this identical output thing.

**Comment by Arachi-Lover** [comment]
I've got a jokey bit about the translation quirk on the Resistance Intro PR (Combat Training mission chain), but it's more to acknowledge it. I don't think we should actually remove/soften the Coalition's yoda-speech, as it's very much one of the charms of the region and faction as a whole.

**Comment by Arachi-Lover** [comment]
That too would be softening up the Coalition's speech pattern, and definetly would remove the charm form it all. Forcing the sentences to conform to a short, simple format would be too restrictive for ES's medium of storytelling (being text-based and all), and just wouldn't be very fun.
As for languages being more complex or not, keep in mind the Coalition has a minimum of 3 languages (Saryd, Kimek, Arach), whereas humanity has just "1 language" (human). The whole game's in English, so we don't take the variety of languages within a species or dialects into account, but for the record I feel it'd be fairer to say the Coalition has more languages than humanity, not necessarily more complex ones. There are probably Coalition dialects far more complex than the usual human one, and some much more simple as well.

I understand it might be irksome for someone better versed in grammar and sentence structuring to read Coalition speech, but it is a concession that must be made, I'm sorry.

**Pull request merged**
