### PR TITLE
fix(map): outline system names so that they are readable at bright spots

### PR DESCRIPTION
**Pull request by RisingLeaf**
## Fix Details
Adds an outline to system names on the galaxy map, cause they are really difficult to read if you get close to Sag A*.
Outlines are added to every name, but are only really visible in the center, checks out i guess.
Also increased brightness of font, because the contrast was better that way.

(yes it still looks a bit awkward, but better than before)

## Testing Done
Screenshots on all zoom levels:

Before:

## Save File
nah, just open the map, what do you want a save for?

### CODE REVIEW

**Comment by tibetiroka** [comment]
Can you add a "before" variant of the same pictures for comparison?

**Comment by RisingLeaf** [comment]
sure, did that

**Comment by tibetiroka** [comment]
Oh yeah this is a lot more readable.

**Comment by mOctave** [comment]
Honestly, I'm not a big fan of this as it currently is. For Sag A*, it works great, but it also makes the text look darker and bulkier overall. Since I know where Sag A* is, I'm personally okay with not being able to see the label on the map, and I don't love how the outlines look. As a setting, however, I would be 100% behind this (even if it defaulted to on).

**Comment by Saugia** [comment]
I feel like the outline is a bit hard to read still, just in another manner. It generally looks readable on the images above, but in-game it seems a bit hard to read, especially in contrast to hyperspace links, system rings and other places on the map. 

If we're going to attempt to make core systems more readable, maybe we could decrease the brightness on the map sprite as well. I think an outline could still be workable, but as this is, this still seems hard to read.

**Comment by RisingLeaf** [comment]
I tried reducing the brightness of the map sprite, I also reduced contrast by just a tad to keep the outer areas at the approximately same brightness

**Comment by Saugia** [comment]
These actually look pretty good, I'd suggest opening the change in a new PR. I think that will be a better alternative to giving the system name's outlines.

**Comment by TomGoodIdea** [comment]
TBH I think this solution is better than #9434 (or we could have both), because some plugin galaxies may still be too bright. The outlined names seem unreadable only in places where they're cluttered, and we can't do much to fix these cases. The new darkened image seems a bit dull, but that's my opinion.

**Comment by Saugia** [comment]
I don't believe necessitating another change to the UI, in which such change only further creates more inconsistent readability or an overall higher need of nuance, is a good alternative to simply adjusting the map sprite. 

As I've mentioned in the new post, if we give system names outlines, those stand out like a sore thumb compared to hyperspace lanes and system rings as well as several other map UI elements that require too much additional adjustments for the sake of something that can be done with simply changing brightness and contrast. The map image itself is more of a backdrop, indeed it becomes more dull, but the player does not look at the map for the sake of the image, it's mostly around system and galactic mechanical usage. 

Sacrificing a small portion of that is acceptable if it means A. More readability and B. Not needing to adjust the whole map look.

**Comment by RisingLeaf** [comment]
Like that?

**Pull request closed without merging**
