### PR TITLE
Add message if an escort is destroyed

### PR DESCRIPTION
**Pull request by SomeDer**
It can be hard to notice if an escort has been destroyed, but it is an important event which could make restarting the game the best option. Adding a message when an escort is destroyed could make it easier.

### CODE REVIEW

**Comment by Zitchas** [comment]
Just to clarify (since I don't have compiling set up), is this a message that will show up in the bottom left log/message area?

**Comment by SomeDer** [comment]
Yes, it appears in the bottom left area

**Comment by SomeDer** [comment]
> Just to clarify (since I don't have compiling set up), is this a message that will show up in the bottom left log/message area?

Yes

**Comment by hcatlin** [comment]
I'd love to have this feature... as it often throws me off. I kind of land in the next sector and see "okay, who made it?"

**Comment by jostephd** [comment]
Maybe the message should be shown upon landing? Something like "You have lost 5 escorts, as a result, 2 story missions were aborted: <list of names of those missions>". This would only count story missions, not job board missions. (Should I open a separate issue for that? I don't want to hijack this.)

**Comment by Nescio0** [comment]
At most three messages can be displayed simultaneously, right? So if more escorts are destroyed, you might miss the notification.

**Comment by Pointedstick** [comment]
+1 to the idea of showing a notification for this. It may not be _immediately_ actionable, but it's actionable within a short period of time. It lets you know you'll need to re-buy it, and helps you understand where an escort went if it's disappeared.

However I'm generally concerned with putting too many messages in the message area on the bottom of the screen. The UX isn't great right now because the messages are really easy to miss, and this becomes worse the more messages are added because older ones time out even faster. Also, the message area intermixes messages that are ignorable (hails and flavor text) with messages that are critically important (you just failed a mission).

I think we generally need to overhaul the notification UX before we add a bunch of new notifications.

**Comment by Amazinite** [comment]
Ref: #3361 in regards to the bottom left messages.

**Comment by endless-sky** [comment]
I think the real question is whether a message should be shown for *every* ship that is lost, or only when a ship is lost that causes a mission to fail (the current behavior). If a message is shown for every ship, that would make the failed mission messages disappear more quickly. And as others have pointed out, the fleet info dialog already gives you an easy way to check if any escort has been destroyed.

**Comment by SomeDer** [comment]
As mentioned by @jostephd, maybe important messages should be shown upon landing as well, so that they can be acted upon immediately if noticed, but can still be read even if missed. Also, maybe they should appear in red, to make them more noticeable.

>  that would make the failed mission messages disappear more quickly

I think the failed mission messages are harder to miss, because they are longer, so they are more noticeable. Also, the lost escort messages appear earlier than the failed mission messages, so the failed mission messages can only be pushed up by other escorts being destroyed. If so many escorts are destroyed, then the player will probably either want to restart anyway, or is so rich that wouldn't care about losing either ships or missions.

>  the fleet info dialog already gives you an easy way to check if any escort has been destroyed.

I didn't notice this. Maybe this should be somehow documented. Also, perhaps it makes this proposition obsolete, as it provides another way to notice if an escort is destroyed (though perhaps a slightly more difficult one).

**Comment by jostephd** [comment]
> I didn't notice this. Maybe this should be somehow documented. Also, perhaps it makes this proposition obsolete, as it provides another way to notice if an escort is destroyed (though perhaps a slightly more difficult one).

Don't forget that this only works before you land. After you land, the info screen gives no indication of whether an escort had been destroyed before landing. It does show escorts that had been disabled, but again, an on-landing dialog saying that would be appreciated.

**Comment by jafdy** [comment]
What about a on-landing dialog that tells you the ships you have lost since you last landed. Probably sorted by value giving name and hull (and possibly value).

**Comment by jostephd** [comment]
@jafdy How about making that change in 0.9.11 (the next unstable release) and seeing how it's received by the wider community?

**Comment by jafdy** [comment]
I don't make those decisions, I am simply offering a solution that may work.

**Comment by SomeDer** [comment]
I'll close this for now, as it doesn't seem to be getting anywhere. If you need to check whether an escort has been destroyed, use the fleet info dialog.

**Pull request closed without merging**
