### PR TITLE
Fix "militia 4 variation" typo

### PR DESCRIPTION
**Pull request by Ferociousfeind**
**Bugfix:** This PR addresses the issue. [The issue was identified by randomly scrolling through the text file generated for `phrase "Friendly Militia 4" from PR #8054]

## Fix Details
Typo

### CODE REVIEW

**Comment by bene-dictator** [comment]
This is being addressed in #8022 - that's the "bad wording" I was talking about!

**Comment by Ferociousfeind** [comment]
FUCK

**Comment by bene-dictator** [comment]
damn.

**Comment by Ferociousfeind** [comment]
your PR already does what mine does, but also other fixes too

**Pull request closed without merging**
