### PR TITLE
Increase Gun Count on Small Combat Ships

### PR DESCRIPTION
**Pull request by Anarchist2**
Adding more gun ports to interceptors was previously discussed in #3264 and #3350, where the change was eventually dropped due to the then-recent blaster and missile changes. The introduction of missile pods has renewed interest in increasing gun port count, however.

This PR uses Derpy's numbers from his artwork bounty:
* The twin gun fighters now have 3 ports.
* The Sparrow has 4 guns.
* The Wasp has 5 guns.
* The Fury has 6 guns. The MFury has 8.
* The Berserker, Hawk, Barb, Scrapper, Combat Drone and Marauder Arrow and Bounder are unchanged.
  * The gimmick of the Hawk and Barb is that they have low gun count in exchange for other qualities, like a turret or more health.
  * In Derpy's original PR, he justified not giving the Berserker more guns as being part of the lore that the ship is outdated and less versatile.
  * Both Marauder interceptors are more like Light Warships, and are also more than powerful enough without extra gun ports.
  * The Scrapper is meant to be a weak ship, so there isn't much use for it having more gun ports.
  * I don't think buffing the Combat Drone matters.

### Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/126
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/351

### CODE REVIEW

**Comment by bene-dictator** [comment]
I'm very happy about this change, it will be interesting to see the potential of Furies with... 6 Javelin Mini Pods, hot damn. And a 4-blaster version of the Sparrow, too.

The only problem is updating the fleets.txt for these new variants, again...

**Comment by Zitchas** [comment]
I'm liking the sounds of that. Now we just need our carriers to actually carry proper complements of fighters... And fighters to actually be more manoeuvrable than *all* the heavy warships...

**Comment by LorenzoBolla** [comment]
Awesome, much welcomed changes! And wise to keep the Hawk, who's gimmick includes also having good weapon space to fit larger weapons on it's 2 gun ports, and the Berserker, which is pretty balanced as of now, and also meant to be old, out of the adjustments. However, the Berserker's description should probably be changed to exclude "the Berserker's popularity is now waning in favor of more modern and versatile ships ~~like the Hawk~~", as now the Hawk is one of the least versatile of the Interceptors, having less available loadouts due to it's heavy weapons focus! 

If any help is needed on updating fleets and variants, i am available.

**Review by Saugia — COMMENTED** [review]
Play-tested each ship with the gun ports in-use. The default ports used also still make sense. 

I see that you updated the model of the Marauder Fury. In the past, we've avoided editing pers ship models. For example, any of the ships I've redesigned (Kestrel, Bactrian) I left the pers ships to use the original models out of respect for the persons. Since there technically aren't any other Marauder Furies in the game, perhaps this is okay?

While we're at it, do we want to add two more guns to the Pers Marauder Fury as well? I'd suggest contacting the pers the Marauder Fury is for and ask them their opinions.

**Comment by Ferociousfeind** [comment]
The Fury and Lance images seem to have lost some luster in updating their gun layouts... is that intentional?

**Comment by Anarchist2** [comment]
The lighting should look better now.

**Comment by bene-dictator** [comment]
> While we're at it, do we want to add two more guns to the Pers Marauder Fury as well? I'd suggest contacting the pers the Marauder Fury is for and ask them their opinions.

I'm not sure that's necessary given #4448, it seems like LocalGod78 was the one updating it from the start though.

**Comment by Saugia** [comment]
I see, he mentioned updating graphics. Works for me then! And good catch with the lighting, I notice it now.

**Review by Saugia — APPROVED** [review]

**Comment by CrackedEmerald** [comment]
i'm gonna say it here, in case it's not noticed on the discord, i don't think the Finch and Sparrow should be that detailed and busy on it's wings and cockpit. Imo, it looks like they got put trough an AI to "improve" those areas, but it did not at all. I think especially for standard non marauder designs like those, they should be simpler.

**Comment by Hecter94** [comment]
It doesn't look like this PR added any details to those images. 

image
 
 You probably want https://github.com/endless-sky/endless-sky/pull/5368

**Pull request merged**
