### PR TITLE
Move fertilizer from food...

### PR DESCRIPTION
**Pull request by toilethinges**
...to Industrial, to avoid any restaurants serving fertilizer.

### CODE REVIEW

**Comment by Amazinite** [comment]
But fertilizer is so tasty.

**Comment by Amazinite** [comment]
Maybe you should readd it into industrial, given that industrial include pesticides.

**Comment by toilethinges** [comment]
I was going to add Farming Supplies somewhere, but I couldn't find where I really should - that sounds good.

**Comment by Amazinite** [comment]
Lol. There are a lot of strange foods in there you wouldn't expect to be at a fancy restaurant. Maybe @Pointedstick should make a commodity for fancy foods just for that jobs?

**Comment by Pointedstick** [comment]
@Amazinite I realized the same thing when I was writing that mission, but thought those possibilities were just too funny to change. You never know what the latest culinary trends on the paradise planets will be...

**Comment by jafdy** [comment]
That just proves they need to be dragged into the real galaxy.

**Comment by toilethinges** [comment]
I want some "fine frozen pizzas".

**Comment by Amazinite** [comment]
"I would be interested in having the fast food *supplies*, please."

**Comment by KiLEdEnNis** [comment]
"Ýes, I'd like pumpkins, and give the lady a cake mix."
lolk

**Comment by endless-sky** [comment]
The commodity categories are supposed to cover all things that a planet generating a particular commodity type would generate. Fertilizer is an agricultural product, not an industrial one. (Especially if it's produced the old-fashioned way...)

**Pull request closed without merging**
