### PR TITLE
Add hidden preference to disable ship thumbnails.

### PR DESCRIPTION
**Pull request by jostephd**
This adds a preference that enables the player to opt out of #3682.

### CODE REVIEW

**Comment by jostephd** [comment]
I prefer seeing the overhead sprites in the shipyard because they are easier for me to recognize because they're used in-flight too.

I agree about not adding hidden preferences for everything. Would you prefer a normal (not hidden) preference? I implemented it as a hidden preference because I wanted to get your opinion before investing time in adding an entry to the preferences screen.

**Comment by jafdy** [comment]
Rather than having a preference this could be moded in (out) instead.

**Comment by Pointedstick** [comment]
No way, the new shipyard sprites are fantastic. They add a lot of visual distinctiveness to the game and to the ships themselves.

**Comment by DingusShingleton** [comment]
Completely agree, having just gotten back into the game after a long period of absence, those sprites are one of my favorite changes. They really make the world seem fuller and more real rather than just a 2 dimensional representation

**Comment by Pointedstick** [comment]
@DingusShingleton I agree 100%.

**Comment by jostephd** [comment]
@DingusShingleton @Pointedstick No one is proposing to force everyone to use 2d models in the shipyard. I am simply proposing to add a preference so each player can choose whether to have 2d or 3d models in the shipyard according to his or her personal taste.

**Comment by MCOfficer** [comment]
to be honest, i don't see what harm a hidden preference can do.

~~the steamies won't find it anyways~~

**Comment by endless-sky** [comment]
It's simply a question of whether adding hidden preferences to allow players to "opt out" of various design choices is worth the complexity that it adds. To me it seems like that would be a messy precedent - there could potentially be dozens of similar design features that one particular person wants to disable or change.

**Comment by jostephd** [comment]
@endless-sky I get that having many preferences is a bad thing. I wouldn't ask you to add a preference if I thought I was the only person wanting it. I think there are other players who would find the shipyard screen _easier to use_ (not just _prettier_) with this preference. And I don't see what complexity this PR adds? `Ship::Thumbnail` can return nullptr even in current master for plugin ships.

**Comment by Pointedstick** [comment]
This isn't something I think we're going to do. The new thumbnails are fantastic, and preferences to turn off things like this rarely make sense in any software context.

**Comment by Bladewood** [comment]
> The new thumbnails are fantastic

Mind you, I agree with your opinion, but I think this is 100% subjective, so taking this as a reason to close it is simply unfair.

**Comment by jostephd** [comment]
For anyone still following, I've patched my build to use the overhead view in the Shipyard listing and the 3D view in the shipyard details sidebar (#5233), like this:

2021-05-15-154631_794x529_scrot

The code I use is below. (It's not mergeable as is, but it wouldn't be hard to make it mergeable, if there's interest.)

<details>

<summary>
Use overhead view in listing and 3D view in the details sidebar
</summary>

```diff
diff --git a/source/Ship.cpp b/source/Ship.cpp
index 7c3aafc27..4564f4b8c 100644
--- a/source/Ship.cpp
+++ b/source/Ship.cpp
@@ -1022,10 +1022,18 @@ const string &Ship::Description() const
 
 
 
+#include "Preferences.h"
 // Get the shipyard thumbnail for this ship.
-const Sprite *Ship::Thumbnail() const
-{
-	return thumbnail;
+const Sprite *Ship::Thumbnail(bool bypass_josteph_disablement) const
+{
+	// Returns nullptr for ships that don't have a thumbnail.
+	// Callers catch this and use GetSprite() instead.
+	if (bypass_josteph_disablement)
+		return thumbnail;
+	else if (Preferences::Has("Disable ship thumbnails"))
+		return nullptr;
+	else
+		return thumbnail;
 }
 
 
diff --git a/source/Ship.h b/source/Ship.h
index 0d88849c1..07c70dbce 100644
--- a/source/Ship.h
+++ b/source/Ship.h
@@ -149,7 +149,7 @@ public:
 	// Get this ship's description.
 	const std::string &Description() const;
 	// Get the shipyard thumbnail for this ship.
-	const Sprite *Thumbnail() const;
+	const Sprite *Thumbnail(bool bypass_josteph_disablement = false) const;
 	// Get this ship's cost.
 	int64_t Cost() const;
 	int64_t ChassisCost() const;
diff --git a/source/ShipyardPanel.cpp b/source/ShipyardPanel.cpp
index cf6177171..afe4e2d63 100644
--- a/source/ShipyardPanel.cpp
+++ b/source/ShipyardPanel.cpp
@@ -159,7 +159,7 @@ int ShipyardPanel::DrawDetails(const Point &center)
 		selectedItem = selectedShip->ModelName();
 		
 		const Sprite *background = SpriteSet::Get("ui/shipyard selected");
-		const Sprite *shipSprite = selectedShip->GetSprite();
+		const Sprite *shipSprite = selectedShip->Thumbnail(true); // use thumbnails in the details sidebar
 		float spriteScale = shipSprite
 			? min(1.f, (INFOBAR_WIDTH  - 20.f) / max(shipSprite->Width(), shipSprite->Height()))
 			: 1.f;
```

</details>

**Pull request closed without merging**
