### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by Zitchas**
This change simply creates license.md to provide the automated license parsing & display by GitHub. For an example of this, look at [the Endless Sky Editor that displays the relevant license](https://github.com/endless-sky/endless-sky-editor/blob/master/LICENSE) Contents are verbatim that of license.txt

(Based on MCO's explanation, GitHub specifically for LICENSE or LICENSE.md, not license.txt)

Thanks to William on the Discord for bringing this up, and @MCOfficer for the explanation.

### CODE REVIEW

**Comment by MCOfficer** [comment]
there seems to be a misunderstanding - i took a wild guess and didn't make that clear enough. either way, i checked on my branch, this change ain't it.

[some research later](https://help.github.com/en/articles/licensing-a-repository#detecting-a-license): a license.txt file should also be detected.

i still don't know what exactly the difference is ([and i couldn't find out](https://github.com/MCOfficer/endless-sky/commits/master)), but i think it has something to do with ES's license not being 100% standard. here's a diff of the editor's license (which is properly detected) vs ES's license (left):

https://www.diffchecker.com/u19LK497

**Comment by Zitchas** [comment]
As evidenced by the commit log, I've done a bunch of the same tests of variations. I wonder if GitHub is checking back to the original ES source for a license, on the grounds that a fork should generally have the license of its source.

**Comment by Zitchas** [comment]
(General note: As of the most recent commit, this PR replaces the license file with the license file from Endless Sky Editor)

**Comment by Pointedstick** [comment]
So does this actually work? Or is it WIP?

**Pull request merged**
