### PR TITLE
Buff the Protector

### PR DESCRIPTION
**Pull request by Amazinite**
**Content (Artwork / Missions / Jobs)**

## Summary
The Protector has been considered the worst human warship for some time now (and I wouldn't be surprised if some would take a medium warship over the Protector). This PR seeks to buff the Protector a bit to give it more appeal.

The Protector is currently pretty statistically similar to the Vanguard, except the Protector has a turret focus instead of a gun focus. These changes seek to push the Protector further away from the Vanguard and closer to the Leviathan in terms of HP, outfit space, and weapon space, while also leaning more heavily into the Protector's turret focus appeal by giving it the most turret mounts in human space instead of being tied with other ships.

Stat changes:
* +2 turret mounts.
* +20 outfit space.
* +10 weapon space.
* +500 shields.
* +1300 hull.

Default fit changes:
* Sidewinders -> Meteors.
* +2 Quad Blaster Turrets.

image

The Protector's engine space is still worst in class, and the mass and drag have remained untouched with these changes since I'll be tackling the mass and drag of all ships when I start breaking pieces off of #5779.

I also intend to rebalance blasters in a later PR, making the default 6 Quad Blaster setup (or even a potential 8 Quad Blaster setup) more viable.

## Save File
N/A. Go buy a Protector.

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/17
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/224

### CODE REVIEW

**Comment by Zitchas** [comment]
Made a PR to your Branch with a single small change - namely adding an ionic reverse thruster. The stock Protector can fit it without any problems, and it really feels appropriate for it.

**Comment by WarlordMike** [comment]
This is something that's been desperately needed for a while. While part of me feels like the engines could be increased somewhat, I'd rather give it a try with these new stats first and see how the ship feels from there.

**Comment by Zitchas** [comment]
Here's the current protector, with the thruster and steering replace with equivalent atomics. And the addition of an atomic reverse thruster.

I don't think it *needs* to even be this fast. It isn't supposed to be chasing anything, just hanging out with heavily loaded freighters and hitting anything coming close. If it needs to, as this shows, it can equip atomics and go *more* than fast enough.

Atomic Protector

**Comment by Saugia** [comment]
protector


Here's an updated thumb with fixed lighting. Let me know if you want me to send it to you differently.

**Pull request merged**
