### PR TITLE
Hai Heat Sink, a bigger cooling system for Unfettered Hai.

### PR DESCRIPTION
**Pull request by retrue**
I noticed that Solifuges have 6 or 8 Williwaw Cooling Systems depending on their configuration.
It seems a bit inefficient, so I propose to add a bigger cooling system to be used by Unfettered Hai in their Solifuges or any other big Hai ship with heat problems.
This PR includes:
A sprite that could be changed for something better.
It adds a Hai Heat Sink to Hai Outfits. Its specifications are conservative, aimed to replace 3 Williwaws.
It replaces the Williwaws in Solifuges for this new Cooling System.
And it adds Hai Heat Sink to Special outfits in sales txt.
The idea is that the only way that the player can obtain it is capturing or boarding Solifuges. And in that case the player can replace them with Korath Heat Sinks that are a lot better, so it won't disturb balance of the game. So, the commit is mostly for lore, because it doesn't look right that Solifuges have so many small cooling systems.
I include too the double resolution sprite for the high dpi plugin.
hai heat sink 2x

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
Hai outfits look similar to human ships, not to Wanderer outfits
and if the Unfettered sell their new outfits (railguns & some stuff, I think, not sure) it should be added to those outfitters
at school so can't check & if I get home I'll forget

**Comment by retrue** [comment]
@KiLEdEnNis Well, I justify its name and similarity with Wanderer Heat Sink because Unfettered and Wanderer are in war and the story of the game says somewhere that Unfettered Hai stole technology from the shipyards and outfitters in the planets they captured it. So a design that imitates Wanderer but that performances at the same level than Hai or Human tech seems appropriate like it was a poor imitation.

**Comment by KiLEdEnNis** [comment]
I would expect them to make a design based on the Wanderer one, but a little different (not recolored, a small redesign)

**Comment by retrue** [comment]
If you look very very close you will notice a small redesign, seriously. 
My skills are not good enough for a bigger redesign.

**Comment by Amazinite** [comment]
One problem with that; the Hai we never in contact with a Wanderer Heat Sink. The Wanderer Heat Sink was developed and released after the Unfettered finished taking planets and the Eye opened, so none of the outfitters they captured would have Heat Sinks in them. 

And along with that, I don't really see the point in the outfit. Yes, the new ship created by the crippled Hai faction is not the most efficient. That makes sense. They aren't some large and technologically advanced faction, so for their new ships to be inefficient makes sense to me.

**Comment by retrue** [comment]
I have made a new version with a bigger helix.
4th hai heat sink 2x

**Comment by Bladewood** [comment]
The Wanderer heat sink was developed along with the Derechos. The Unfettered could have disabled their ships and plundered their heat sinks (we know they plunder outfits, how else could the Giftbringer have obtained a Wanderer ramscoop?).

Even then, however, I disagree with giving the Hai a new cooling outfit. We don't want to overload the Hai with new outfits.

**Comment by retrue** [comment]
6 or 8 Williwaws in one Solifuge doesn't seem right to me.

**Comment by Lineth** [comment]
I think the sprite could just be swapped out with one that looks like an upgraded human water/liquid nitrogen cooler and it would be fine. I do think the Hai could use a higher-tier cooler of some sort, even if it's exclusive to the Unfettered.

**Comment by Pointedstick** [comment]
How about a graphic that doesn't look like a recolor of an existing one? Zero chance this is gonna get approved without better art assets.

**Comment by retrue** [comment]
I don't know how to draw. Edit an image is a lot of effort to me. But I think the idea is good and that Unfettered Hai need a bigger cooler. So, if somebody could draw a better sprite for this...

**Comment by KiLEdEnNis** [comment]
to be honest, in some way I like how they have a lot of small coolings, but a bigger slightly more efficient cooling could work

**Comment by Admiral-Danforth** [comment]
Random Idea:
You land on an Unfettered planet they say something about captured human freighters having big cooling. They ask you to give them one so they can better cool their ships.

**Pull request closed without merging**
