### PR TITLE
Nerf Refueling Module

### PR DESCRIPTION
**Pull request by Arachi-Lover**
----------------------
**Content (Balance)**

## Summary
It was pointed out in the Discord that the recently added Refuelling Module is much too powerful.

This PR simply cuts the fuel production in half, and increases the energy consumption to not be negligible.

### CODE REVIEW

**Review by Quantumshark — APPROVED** [review]
With these changes, one Refuelling Module provides 3 fuel per second, which is roughly what a wanderer ramscoop produces around an 'average' star at 1250 distance, or directly on top of a very poor star. The Refuelling module uses the equivalent of roughly 15 outfit space, depending on how exactly you're powering it and how much you value fuel capacity.
There's also the fact ramscoop is square rooted, while fuel generation is not.
Four wanderer ramscoops will give twice as much fuel per second as one - so, ~6 fuel/sec (in "average" conditions) in 28 space. Two refuelling modules gives a broadly similar 6 fuel/sec, for 20 space, 200 fuel capacity and 13.2 energy/sec. Which total to a fairly similar amount of outfit space - the Fuel Module, the most space-efficient provider of fuel capacity, gives 100 fuel per 4.75 outfit space, so you're looking at (on paper) 9.5 outfit space to offset the loss of fuel capacity - bringing you up to 29.5, compared to 28 for the four ramscoops.
The ramscoops will still perform much better in ideal conditions - if you're deliberately scooping, you'll be gaining double that amount of fuel, while the refuelling module can't do the same.

So, I think this puts the refuelling module in a sensible place compared to high-end ramscoops.

**Review by Amazinite — COMMENTED** [review]
It should be Refueling with one L.

**Comment by Quantumshark** [comment]
If you're changing the name, you'll need to also change it in the lunarium basics outfitter, and any ship variants that use it.

**Comment by Amazinite** [comment]
Image name too.

**Comment by Arachi-Lover** [comment]
Oh, right.

**Pull request merged**
