### PR TITLE
additional icon sizes in sconstruct

### PR DESCRIPTION
**Pull request by comnom**
refs: #3913

### CODE REVIEW

**Comment by Pointedstick** [comment]
Does this fully fix https://github.com/endless-sky/endless-sky/issues/3913?

**Comment by tehhowch** [comment]
I don't have a High DPI screen to test with, so let's ping @grawlinson to find out :)

**Comment by grawlinson** [comment]
Sure does, thank you for fixing this!

**Comment by Pointedstick** [comment]
Thanks for testing!

**Comment by Pointedstick** [comment]
Thanks for testing!

**Pull request merged**
