### PR TITLE
Jump drive remodel

### PR DESCRIPTION
**Pull request by Scrinarii1337**
Artwork

Remodel of the jump drive and broken jump drive
image

### CODE REVIEW

**Comment by EjoThims** [comment]
I like this a lot. Looks suitably space magicky.

Also less silly than current one, imo, while still immediately making clear what it is and does.

Could you go ahead and throw the broken one in that first post too, though? Maybe even both the originals too.

**Comment by Zitchas** [comment]
I won't criticize the original. It was good, it conveyed being a mysterious ultra-high-tech device really well. But these new ones.... Yeah, very nice. From my perspective, manages to look more technological while also being more mysterious.

This PR is only missing one thing:
1. Adding the copyright info to the copyright file.

Normally the asset file would just be attached to the first post, but Scrinarii1337 sent the file to me, so I'll put it in my drive folder full of asset zips [(zip file stored on google drive here)](https://drive.google.com/file/d/1mDOt2SoXvV0qrVMxSFEdcJRxKkbyPHEb/view?usp=sharing) so that one of the maintainers can get it to put in the official asset folder.


[JumpdriveRemodel Assets.zip](https://github.com/endless-sky/endless-sky/files/8049079/JumpdriveRemodel.Assets.zip)

**Comment by Arachi-Lover** [comment]
Needs a PR of the high-DPI versions to https://github.com/endless-sky/endless-sky-high-dpi as well.

**Comment by Zitchas** [comment]
They are, hopefully, working on that, since I mentioned it to them before they did this PR. That being said, the asset file does have high-res versions... although I note that the high-dpi versions in the asset file are exactly 1 pixel bigger in each dimension than x2 the normal image. I'm not sure why this is, or if it matters.

**Review by Zitchas — APPROVED** [review]
The new jump drives in the outfitter:
New Jump Drives

My first impression was just hard to see, after being used to looking at the much brighter and solid Jump Drive images. After flying around and coming back to look at them a few times, though, they look good. I love the detail. The fact that they somehow make more sense and yet imply even stranger forces at work. 

The Broken Jump Drive suffers from being too dark a bit more than the regular jump drive, though. For me personally they are both in that spot of "they are acceptable, and better than the old images, but it'd be better if their lighting was just a bit brighter."

**Comment by Zireael07** [comment]
+1 to making the broken variant slightly brighter. I squinted at the pic for quite some time before realizing there was more than the vague green cloud...

**Comment by Zitchas** [comment]
Over in the high-dpi repository they made some slightly brighter ones (We went back and forth on DMs with a couple iterations). The main JD is just slightly brighter, and the broken JD is moderately brighter, and they both stand out much better and look really good with that slight adjustment. (They also did a rust cloud and a red cloud; but we both agreed the green looks much better)

**Review by Zitchas — APPROVED** [review]
These slightly-brightened versions have resolved my minor quibbles with the brightness/contrast against the outfitter background. Very nice!

**Pull request merged**
