### PR TITLE
Support certain OpenGL 2.1 setups

### PR DESCRIPTION
**Pull request by SolraBizna**
Endless Sky doesn't actually use any OpenGL 3.0 features that weren't available as extensions to OpenGL 2.1 and earlier. Some people (including me) have hardware that cannot expose 3.0 support because of missing features, yet supports every feature used by Endless Sky.

Desperate to get my space trucker fix, I tried bypassing the version check and trivially modifying the shaders to be compatible with GLSL 1.2, and was surprised to find that the game seemed to need no other changes to work on my setup. I spent a few hours today testing the game and experienced nothing out of the ordinary other than low framerates in very crowded sectors. (This is expected; my graphics hardware is anemic.)

This PR replaces the OpenGL 3.0 error with an OpenGL 3.0 warning, giving the option to proceed but stating in no uncertain terms that proceeding is dangerous. It also rewrites every shader in the game to be GLSL 1.2, since no shader actually used 1.3+ features, only 1.3+ syntax. (It also tags the shaders with `#version 120`, indicating the version of GLSL they were written against, instead of `#version` "whatever-the-user-happens-to-be-running", which prevents future drivers from being able to perform any necessary version-related translation...)

### CODE REVIEW

**Comment by endless-sky** [comment]
What operating systems and GPUs have you tested this on?

Getting those shaders to work on Mac OS X, Linux, and Windows, and on
different hardware configurations of each, was a bit complicated. So I
don't want to change them if there's any risk that it will break support
for someone else who is currently able to run the game.

**Comment by SolraBizna** [comment]
I tested it with Mesa 10 on Debian Linux. The GPU is a Radeon X1600. (Actually, some kind of FireGL with the same core... I don't know what the people who designed this thing were thinking.) I'm also planning to test it with Mesa 11 on a Radeon HD 7870, but I've been very ill lately and haven't done it yet.

The changes to the shaders were trivial. `texture` became `texture2D`, `in`/`out` became `varying`/`attribute` (depending on context), and `finalColor` was removed whether it appeared and replaced with `gl_FragColor`. The shaders were already written in a way that `gl_FragColor`'s special restrictions were met. None of the modifications changed the actual meaning of the shader code, so there shouldn't be _any_ breakage where it already works. As far as I know, these GLSL 1.2 shaders compile the same byte-for-byte as the originals. (This is something I can actually test using ARB_get_program_binary, on a wider variety of platforms than I can test Endless Sky, if you like.) And any OpenGL 3.0 implementation supports GLSL 1.2.

Things would get a little more hairy if Endless Sky were to specifically request a higher-versioned OpenGL core (as opposed to compatibility) profile, but it doesn't.

If the `#version 120` approach is deemed unacceptably risky, I can set up the shaders so that they literally postprocess to the current code on 1.3+ and automatically fall back to 1.2 constructs if 1.3+ isn't available.

**Comment by SolraBizna** [comment]
It would. Drat.

I can rail against Mac OS X not doing the right thing until the cows come home, but that won't make that stop being a problem.

I'll modify the shaders to mutate into GLSL 1.2 compatible forms only when GLSL 1.2 is the version in use, I guess...

**Comment by SolraBizna** [comment]
Now on GLSL 1.3+ the only difference in the shaders by the time they hit the compiler is that `out vec4 finalColor` is the first global and not the last. If this causes problems, the declaration in the "header" can be removed and the declarations in the individual shaders restored, provided that they are protected by `#if __VERSION__ >= 130`.

`varying`/`attribute` are still used because those keywords were deprecated and replaced entirely (and therefore can harmlessly be `#define`d), whereas keeping them as `in`/`out` and `#define`ing them in the other direction would prevent use of the `in`/`out` keywords for function parameters.

**Comment by LocalGod79** [comment]
it's unfortunate that we Mac OS X users have to jump through hoops to play this game in the first place (disabling Apple's "known software/publisher" checks) - it would suck to do that _and_ accept the warning, only to find out that the downgraded graphics protocol doesn't work.

with that said, veteran Mac users are used to disappointment when it comes to games (and the user base affected by this would be _excruciatingly_ small), so "unstably" opening up OpenGL 2.1 for Linux and Windows users might actually be worth the effort...

**Comment by Wrzlprnft** [comment]
I agree with local. It is something that ends up in the branch selection on steam (where people can select beta currently) and is there without guarantee of even working or being updated. Like the windows xp branch for age of empires 2 HD.

It would be still more to compile and uploa for every update that makes it's way to this branch.

**Comment by SolraBizna** [comment]
Ideally, it wouldn't have to be a separate binary at all. The way my branch is currently set up, there _should_ be nothing different as long as you're using OpenGL 3.0 or later. Unfortunately, I can't test it very well. I only have two machines I can test on. And while the only remaining difference is the order in which some variables are declared, past experience says that I can't rely on that not breaking anything without testing first.

Anyone with the ability to compile and test on Windows machines and Macintoshes that can currently run the game, and confirm that everything still works?

(For my own part, after disabling motion blur I get excellent performance everywhere, with no visual glitches I recognize. And it still runs without errors with llvmpipe, which is OpenGL 3.3, though performance is naturally terrible.)

**Comment by Amazinite** [comment]
I'll test it out when I get later home today and report my findings.

**Comment by warp-core** [comment]
I can text it out on a few different configurations, some of which can't currently run the game due to OpenGL limitations however, I cannot compile it, I think some of the libraries I have are out of date but code blocks hasn't been very co-operative lately either and I don't have the time to reinstall everything.
Would it be possible for you to send ke a compiled copy? It'd only need to be the executable, the libraries from the Steam install should work with it.

**Comment by SolraBizna** [comment]
The only platform I can easily build on is amd64 Linux. Is that the binary you want?

**Comment by warp-core** [comment]
I'd be testing it on 32 and 64 bit Windoes systems... However, I should be able to boot them into Linux thanks to live USB installations but at least 1 of the configurations going to be 32 bit and that'll be one that doesn't currently support the game.

**Comment by LocalGod79** [comment]
unfortunately, even my secondary Early 2009 (7.5 years old!) Mac Mini has a NVidia GeForce 9400M GPU that is capable of OpenGL 3.3, even if it suffers from the 256MB VRAM cap...(so i cannot assist you in testing the OpenGL 2.1 code changes).

Apple lists iMac/Mac Pros as far back as 2007 that are capable of OpenGL 3.3 (under Yosemite). https://support.apple.com/en-ca/HT202823

**Comment by SolraBizna** [comment]
Testing it on 3.0+ is still helpful, to help determine whether my changes to the shaders broke any currently-working setups.

**Comment by Nechochwen-D** [comment]
I would personally love to see 2.1 support as I was hoping to make a RaspberryPi console of this game.

**Comment by SolraBizna** [comment]
Feel free to test if my branch works on your R.pi; it works well enough on my Thinkpad T60p that I've now completed the storyline twice. (It also worked for a friend of mine, but he doesn't count because he's on the same hardware and OS as me.)

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/2/135509314047664230/

**Comment by SolraBizna** [comment]
Still works for me on Mesa 13 on both my FireGL (2.1) and my Radeon HD (4.3). The main obstacle for wider testing is the production of binaries. Can anyone provide Mac/Windows binaries?

**Comment by SolraBizna** [comment]
My branch still seems to be working fine. Performance even seems to have improved slightly on my setup, whether due to Mesa updates or upstream Endless Sky improvements I can't say.

For the record, here is all my branch currently does:

- Replaces the OpenGL-less-than-3 error with a very stern OpenGL-less-than-3 warning.
- Trivially edits each shader into a GLSL 1.2-ish style.
- Depending on the GLSL version, the GLSL preprocessor will:
    - GLSL ≥1.3: Completely\* reverse the trivial edit, making the shaders modern GLSL style again.
    - GLSL &lt;1.3: Mutate the shaders the rest of the way to GLSL 1.2 style.

\*Almost completely. `finalColor` is declared as the first global rather than the last, to simplify the individual shader sources. (The reversal can be made exact by putting the `finalColor` declarations back into each shader, protected by an `#if`... but my most recent experiences with modern GLSL compilers suggest that it's not necessary.)

At this point, it seems to me that the best way to check whether this branch breaks modern setups is to tentatively merge it. Nobody seems both able and willing to make test binaries on Windows and macOS. I'm about 90% confident there will be no breakage, and it does seem there's some demand for OpenGL 2.1 "support".

**Comment by endless-sky** [comment]
Nothing has changed in the concerns I raised before: getting the current game to work across so many different operating systems took a lot of trial and error, and there were a lot of things that were non-intuitive (for example, having to specify the OpenGL version as 3.0 on WIndows, even though 3.3 features are required, and having to *not* specify the OpenGL version on OS X). So there's a very high risk that making this change would break things on one OS or another - it's not soemthing I would consider merging in without testing it.

Also, in terms of future-proofing, switching the game back to an outdated GLSL syntax doesn't seem like a good idea, because sooner or later that syntax will end up deprecated.

**Comment by SolraBizna** [comment]
> getting the current game to work across so many different operating systems took a lot of trial and error, and there were a lot of things that were non-intuitive (for example, having to specify the OpenGL version as 3.0 on WIndows, even though 3.3 features are required, and having to not specify the OpenGL version on OS X).

My branch doesn't touch anything outside the shader sources, `Shader::Compile`, and the version check. It doesn't change the way the library is loaded, the way the context is created, or the way any of the GL3+ features are accessed. In fact, if an OpenGL 3 context is successfully created, it should have no net effect.

On a *real* OpenGL 2.1 implementation, as opposed to an OpenGL 3+ implementation that's dumbing down for the available hardware, it may error out because it accesses core-promoted features by their core entry points. I made no attempt to prevent this; if I had gone to the effort to track down all such calls and replace them with their extension entry points, that *would* have broken it on macOS at least, and would certainly have made the changes more extensive and intrusive.

> So there's a very high risk that making this change would break things on one OS or another - it's not soemthing I would consider merging in without testing it.

Well, it's looking like nobody will build it for macOS or Windows without it being merged, so it'll probably never be tested further than it has been. If there were a build for those platforms, it would be easy to test. I don't have either platform, or I would do it myself.

> Also, in terms of future-proofing, switching the game back to an outdated GLSL syntax doesn't seem like a good idea, because sooner or later that syntax will end up deprecated.

That syntax already was removed, all the way back in GLSL 1.3. That's why it wasn't used originally. For most keywords, my branch uses the preprocessor to replace modern keywords with the deprecated ones if (and only if) the modern keywords aren't available. In the `in`/`out` case, because the modern language has multiple meanings for those, that wasn't possible, so the shaders were changed to use the (unambiguous but deprecated) old keywords and the preprocessor replaces those keywords with the modern ones if (and only if) the modern meanings *are* available.

The key is the use of the preprocessor. If GLSL 1.3 is available, the GLSL compiler never sees old keywords. Running on any system Endless Sky mainline currently supports, no additional deprecated features or constructs are used.

(I remember when GLSL first came out, and I was told GLSL was perfectly future proofed so we would never have to have a hack like this. Obviously, that wasn't the case. Sigh.)

**Comment by SHADOWELITE7** [comment]
I would like to contribute to this PR also

I do like to play this game on my current computer but I am getting the same [opengl 3.0 issues]( https://github.com/endless-sky/endless-sky/issues/3685#issuecomment-379564092).

here are my screen shots of my system through windows 7 using the direct x diagnostics tool

image

image
here is my system

**Comment by SolraBizna** [comment]
Unfortunately, I don't have a means to build a Windows binary of Endless Sky for you to try. I've given up on getting this merged anyway; no matter how surgical and careful my changes were, there will never be enough testing to assuage the fear of incompatibility.

There are dozens of us! DOZENS!

I'm a bit annoyed that nobody with commit powers seems to have examined my final patch in detail—if they did, I think they would agree with me that, given my approach, *new* incompatibilites from my changes are unlikely—but at this point I've fought and lost the OpenGL 2.x battle on so many different projects that I have little cause for hope.

Ironically, I was once chewed out for introducing a change to a project that brought its minimum GL version *up* to 1.2, when supporting 1.1(!!!) was still a project requirement.

**Comment by SHADOWELITE7** [comment]
o ok

**Comment by flaviojs** [comment]
I checked out your changes and for me it looks like a source of future problems.

I suggest you leave the shader code alone (text strings) and instead make `Shader::Compile` morph the code only when it detects shader version 1.20 (OpenGL 2.1).

This way the current users remain unaffected and you will be able to play the game with OpenGL 2.1.

**Comment by SolraBizna** [comment]
> I suggest you leave the shader code alone (text strings) and instead make Shader::Compile morph the code only when it detects a shader version lower than 1.30 (OpenGL 3.0).

Morphing the code only when it detects a shader version lower than 1.30 is effectively what my patch already does, using the GLSL preprocessor instead of an external parser. Because of the `in` and `out` conflations and the un-hardcoding of `gl_FragColor`, it's not simple to transform an unmodified modern shader into the 1.20 dialect, with the preprocessor or otherwise.

> I tried making a quick code morpher in an old laptop that has GLSL version 1.20 and hit a wall with sampler2DArray. There is no replacement for this type, so it is no longer possible to run this game in OpenGL 2.1 unless it supports GLSL version 1.30 (introduced in OpenGL 3.0).

Use of `sampler2DArray` in 1.20 simply requires `#extension GL_EXT_texture_array : enable`. Use of it was added since my last update to this branch. Unfortunately, unlike the other promoted-in-3 extensions Endless Sky implicitly relies upon, this one is not supported on my laptop. So it seems that finally, anticlimactically, Endless Sky has stopped even theoretically supporting my laptop. The flaws of my "allow 2.1 and let the GL_INVALID_VALUE errors sort themselves out" approach have now expanded to cover me.

When my EOMA-68 A20 finally arrives, I've got plans to make a new "lite" branch with cleanly sectioned alternative graphics code. That may or may not end up including an ugly, purely-software-rendered fallback, depending on the progress of Mali reverse engineering at that time.

**Comment by flaviojs** [comment]
Didn't know about `GL_EXT_texture_array`, thanks.

Tried continuing and got "extension `GL_EXT_texture_array' unsupported in fragment shader", which is a death sentence for the morphing approach. One of the appeals of this game is the polished graphics, so it is expected that more OpenGL 3 features get used over time.

The only viable approach I see for OpenGL 2.1 is to have alternate shader code, but it's unlikely to be merged since it requires more maintenance and the game would need to look the same. Good luck on your "lite" branch.

Here is the final state of my quick morph attempt: [quickMorphAttempt.patch.txt](https://github.com/endless-sky/endless-sky/files/1907086/quickMorphAttempt.patch.txt)

**Pull request closed without merging**
