### PR TITLE
Re-name Sestor vessels to follow prime number naming scheme

### PR DESCRIPTION
**Pull request by Galaucus**
## Feature Details
Kor Sestor vessels, for the most part, follow a naming pattern of ship models being assigned a prime number. This brings outliers in line to follow that pattern.

Changed names are:
"Far Lek 14" -> "Far Lek 13"
"Far Osk 27" -> "Far Osk 29"
"Tek Far 78 - Osk" -> "Tek Far 79 - Osk"

Missions/events which would have added the old name to the player's world state now write in the new ones instead.

The ships under their old names have been added to the deprecated outfits .txt, so as not to screw up older saves. 

## Testing Done
I took an old pilot to Exile space. The deprecated ships spawn correctly and behave normally.
I took a new pilot to Mesuket. Sestor ships spawn as expected with the new names. 

All seems to be in working order.

## Performance Impact
N/A

### CODE REVIEW

**Comment by tehhowch** [comment]
But _why_? We don't need this change.

**Comment by Galaucus** [comment]
Worldbuilding consistency. Both automata factions use mathematical patterns to name their ships, though the Sestor did so imperfectly. This resolves that.

**Comment by Anarchist2** [comment]
That's making the assumption that there's a pattern in the first place, which would by extension mean:
a) MZ somehow made _three_ mistakes while naming the Sestor ships, two of which are even numbers.
b) MZ then failed to notice these errors and rectify them.
Not very likely, if you ask me.

**Comment by MCOfficer** [comment]
I can totally see the Mereti being pattern-based, but Sestor ships are mostly asymmetrical and just generally *weird*. If anything, i'd say it's deliberately incorrect.

**Comment by Zitchas** [comment]
My personal head-canon is that there used to be ships with prime numbers in those spots, but due to performance issues with those models, they either developed new versions (where the current number is higher than the nearest prime), or reverted to older and "more successful" models (where the current number is lower than the nearest prime).

**Comment by Amazinite** [comment]
Part of the distinction between the Sestor and Mereti isn't just a difference in ship aesthetics, but also a different in philosophy. There's a reason the Sestor and Mereti ships handle so differently in combat. (Sestor have trapping weapons like the Detainer that open ships up to being swarmed by their many fighters, Mereti mainly use the same two weapons that work well not only together but also in bulk.) Given that the Sestor and Mereti are (or I guess in this case *were* since we're referring to the Korath that actually built the ships) suppose to be at odds with on another, I'd expect such divides to also extend to naming conventions. The Mereti are clearly the mathematical ones in their naming scheme, having ship names follow powers of two. Why would the Sestor also choose a mathematical root for their naming conventions at the same time (i.e. numbering all ships by prime numbers)?

> Both automata factions use mathematical patterns to name their ships, though the Sestor did so imperfectly.

This very line is refuted by the fact that the Sestor *don't* actually use a mathematical naming pattern. Only the Mereti ships use a mathematical naming scheme, and you're trying to force a similar scheme onto the Sestor.

**Comment by Zitchas** [comment]
In continuance of Amazinite's point; it is worth noting that for Mereti ships, that's all they have: "Model ##". That's it. In contrast, the Sestor ships have names. Unfortunately for us, the only part of the name that we can actually make sense of is the number, which is why it stands out. But we have to recognize that they do actually have names, the numbers only forming one part thereof.

"Far Lek", "Far Osk", "Tek Far - Osk" are, after all, three unique names, albeit ones that look very similar to us. Likewise for the rest of the Sestor fleet - even with the numbers removed, they each have a unique name. Although that being said, there are three with similar names: Tek Far, Tek Far - Osk, and Tek Far - Lek. Which suggests that they are variants or part of a development tree or something.

**Comment by WarlordMike** [comment]
From what I can discern of the Korath Language, Lek most likely means "left" and "Osk" probably means "right." My reasoning being thus: 

In terms of the Drones/"Fighters" (the Far Osk 27s are _technically_ fighter craft), their guns are on the respective sides (left for the FL 14s, right for the FO 27s). For the Carriers, that's the side which is covered by plating.

Regardless, four out of the seven being prime numbers would be grounds enough for turning the other three into prime numbers, as well. As I stated on the Discord, it's possible that they could have been fat-fingered (even the 29, as being 2 keys off is still fairly reasonable).

**Comment by Arachi-Lover** [comment]
I don't remember what Lek is but MZ said Osk was "S", iirc. both are letters in our language, I'm pretty sure S was one of the letters, don't remember the other.

**Comment by Anarchist2** [comment]
Could MZ type in the incorrect numbers to the names of a few ships? Sure.
Could MZ somehow completely miss the fact that the numbers of three ships, two of which are _even_, aren't prime over **252** lines of defining fleets?
Even if it was intended for the Sestor to have a prime naming scheme, MZ probably dropped it.

**Pull request closed without merging**
