### PR TITLE
fixed a typo: FO27 vs. FS27 (Far Osk 27 fighter)

### PR DESCRIPTION
**Pull request by EndrosG**
I assume it should be FO27 fighter, not FS27 fighter. Changed that. I am aware that the O letter is similar to the 0 number. But the full name is Far Osk, not Far Sok or whatever.

### CODE REVIEW

**Comment by Tadrix** [comment]
Not a typo.

Kor Sestor ship model names are letter names spelled out.
You would call letter F _ef_, letter S _ess_, letter T _tee_. Korath call their letter F _far_, letter S _osk_, letter T _tek_. You wouldn't argue that _Ef_ or _Ess_ is written as E, for them _Osk_ is written as S.

**Comment by Amazinite** [comment]
This was brought up before and it's intentional. Let me see if I can find the issue.

**Comment by Amazinite** [comment]
#1657

**Comment by MessyMix** [comment]
#1657 i'm looking too ;)

**Comment by EndrosG** [comment]
My fault of not finding it. Closing this then. Thx @Tadrix for the detailed explanation.

**Pull request closed without merging**
