### PR TITLE
Change MMK's government to Content creator;

### PR DESCRIPTION
**Pull request by Wrzlprnft**
In order to keep things straight and pay proper respect to Michael Zahniser

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
That's up to MZ.

**Comment by Lineth** [comment]
Maybe rename Owner to Developer?

**Comment by Bladewood** [comment]
Let's put Michael's ship under the God faction.
-joke-

I think leaving them both as Authors is fine. They are both developing - *writing*, in the broadest sense - content for the game. They're just on completely different scales.

**Comment by Wrzlprnft** [comment]
Then maybe MMK should stay "Author" but MZ be changed to "The Author"?

**Comment by KiLEdEnNis** [comment]
either leave it as it is or make MZ's "Owner" or "Developer"
I'd prefer "Owner" as in "own" you with his OP Kestrel

**Comment by endless-sky** [comment]
Or, I could be "Supreme Dictator." :)

At the moment, this doesn't seem important enough to be worth adding an extra government.

**Comment by Wrzlprnft** [comment]
"A government is a rather lightweight object - they don't really do much aside from reflecting who's hostile toward whom. So, you should go ahead and create new governments if you want one with a different name."  
Quote @endless-sky on an issue about person governments

**Comment by endless-sky** [comment]
That was written before I discovered how typos in plugins could cause a saved game to be littered with lots of extra governments that then never go away. :)

**Comment by Bladewood** [comment]
...I found that out the hard way.

**Pull request closed without merging**
