### PR TITLE
feat(ui): Ship category code added for non-scrollable panels (ship info) + test for it

### PR DESCRIPTION
**Pull request by Statter**
Heading: **Feature**

Sorry, this is my very first pull request to Endless Sky master, so it maybe requires correction.

I was surprised that it is impossible to get a ship type on the Ship Info panel (and even on the Player Info panel in a list of ships)

## Summary
For Ship Info (and in general for all non-scrollable panels) now a ship name additionally reflects a category code as 2 first letters code, wrapped in parentesis, eg: Aerie -> Aerie (MW)

Category code pattern:
* For a 2 words category: Medium Warship -> MW
* For a single word category: Fighter -> Fi

The change preserves backward capability by adding a default arg to a function

Screenshot before change:
image

Sceenshot after change:
image

## Usage examples
No game data changed

## Testing Done
A corresponding unit-test is provided

## Save File
Any save file is valid for testing

## Artwork Checklist
No artwork change is provided

## Wiki Update
No update

## Performance Impact
N/A

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
I'm not sure about the two-letter codes, especially if a plugin adds custom categories.

And, for such UI changes, please post before/after screenshots.

**Comment by Statter** [comment]
Actually, it's strange that neither Player Info panel with all ships nor Ship Info panel can show you an actual ship category. In my mind, Ship Info panel should reflect all basic ship information, but strangly a ship category is missing. A player, especially a new one, may not know the exact ship category by a ship name. As for me, I find this information very usefull

But I agree that two-letter codes can be not an optimal solution. Alternatives are:
* to add a full category name after a ship name (this can be achieved simply by scrollingPanel = true in ShipInfoDisplay::Update call for a Ship Info panel);
* to add support for custom plugings for such a behaviour (where can I find plugin system code to check what can be done in that way?);

**Comment by TomGoodIdea** [comment]
I'd accept the short codes if 1) they would be defined manually in the category definition - something like this:
```
category "ship"
        "Medium Warship"
                "short name" "MW"
```
(see data/categories.txt and the CategoryList class), and maybe fall back to the automated version if no custom code is defined, and 2) they would have tooltips showing the full category name on mouse hover.

If you want to replace the codes with full category names, they would need to be put on a separate line, so make sure the heat/energy table at the bottom doesn't go off-bounds because of that.

That said, it's just my opinion, and to be sure what solution would be acceptable to merge, you should probably wait for someone with more authority than me to make the decision.

**Comment by Statter** [comment]
I switched the branch and I need to reopen it

**Comment by Statter** [comment]
Reopened the pull request

**Comment by Statter** [comment]
I cannot reopen it by myself :( New brach is Statter:br_ship_category. But reopen button is not active

**Comment by tibetiroka** [comment]
Yeah, it looks like you will have to open a new PR.

**Pull request closed without merging**
