### PR TITLE
feat(ui): Red Alert Visual Warning Is Radar Instead of Icon

### PR DESCRIPTION
**Pull request by Koranir**
## Feature Details
I changed the visual red alert indicator from a small, hard-to-notice icon in the coner to the radar flashing red.

## UI Screenshots

https://user-images.githubusercontent.com/101683475/209950203-3aeea3fb-1331-4494-9c36-b46a98037c03.mp4

### CODE REVIEW

**Comment by Hurleveur** [comment]
I like how this looks better than the radar icon, that said I definitely noticed said icon.

**Comment by Koranir** [comment]
> I like how this looks better than the radar icon, that said I definitely noticed said icon.

Well, I did say _hard_ to notice. Especially without sound, the icon (for me, at least) stops flashing before I get to notice it.

**Comment by Hurleveur** [comment]
How about a more progressive and less blinking version, that would represent the scanning of smth on the radar ~~and make the enemies bigger when it reaches them~~ (kidding that part isnt needed ofc)
To be clear, I'm just giving an idea not requesting a change, I have no authority to do that on the art side.
I think that in the other PR there was a discussion to not make the color different from the rest of the UI (which I disagree with, don't like that brighter red instead of old orange) which you may want to look at if you didnt already.

**Comment by Zitchas** [comment]
That looks decent, although I'd personally suggest that this be added as an option instead of just replacing the icon. The main point of the visual indicator is accessibility, and different options may suit different people.  For instance, I'd probably opt to have both the icon & this radar glow. 

As for the color... Well, I like the more red color, as it stands out better than the orange. But I really think the specific color is something that should probably be user-customizeable, perhaps in a gamerule once those are implemented.

Looking at it again, would it be possible to have it pulse instead of blink? As in fade in and out.

**Comment by Koranir** [comment]
I don't think that the UI system can support smooth fades without hardcoding this particular case. 

I am working on a separate shader system that would support generalized cases, but it would be best not to count on that being complete any time soon.

**Comment by Koranir** [comment]
> How about a more progressive and less blinking version, that would represent the scanning of smth on the radar

Aforementioned shader system would allow that, but no go for now.

**Comment by Hurleveur** [comment]
Can't we just make a scanning image and rotate only that whilst not moving the edges of the radar?

**Comment by warp-core** [comment]
I suspect the only good way to get customisable colouring for something that isn't already a single, solid colour would be to swizzle it. The swizzle number could be customisable, however, I think that would mean the sprite used would have to be hard oded, not something that you can change in the interface definition.

**Comment by Amazinite** [comment]
I wasn't sure how this'd look when we discussed this as an alternative to the icon, but I do think this looks much better. Notably in both cases though, the color used isn't easily customizable, whereas all the other color on the HUD here is controlled by color definitions in interfaces.txt. I'd prefer if we could in some way have this be a shader which we could give a color to as to allow anyone to tweak it as they see fit.

> As for the color... Well, I like the more red color, as it stands out better than the orange. But I really think the specific color is something that should probably be user-customizeable, perhaps in a gamerule once those are implemented.

Gamerules aren't a cure-all. Different customizable points in the game will still exist in different locations. In this case, UI colors should still exist within interfaces.txt. Gamerules is for tweaking mechanics, not UI.

**Comment by Zitchas** [comment]
I'm also concerned with how this impact the visibility of hostiles (or anything, really) in the border area. A lot of my combat (or at least, a lot of my threats) these days spend a fair bit of time on the edge there, and having this obscure them for even fractions of a second is not a good thing.

**Comment by Amazinite** [comment]
Heads up that you need a high DPI PR and assets PR linked in the OP for a change like this.

**Comment by RisingLeaf** [comment]
To be honest, as much as I like the visual, I agree with Zitchas on this. The icon is not blocking my view and imo is attracting my attention better than this.

**Comment by RisingLeaf** [comment]
Maybe if one could choose between them?

**Comment by Amazinite** [comment]
I'd rather not support both. The only difference right now is the image used and how the interface file is set up, with all the underlying code being the same. One could edit their own interface file to choose how they want this alert to appear; it doesn't even need to be one of these two or in these locations. Although I will grant that the interface isn't very moddable at the moment; I don't think a plugin that changed the alert icon would be super clean, as it'd need to redefine the entire HUD instead of just being able to swap out this one piece.

**Review by Saugia — CHANGES_REQUESTED** [review]
The thickness of the circle should be brought way down. I'd prefer if it was thinner with the edge, because right now it's blinding and hurts my eyes. At least half the thickness it is right now. Otherwise, it works.

**Comment by ravenshining** [comment]
It *looks* nice, but I think it's too annoying/distracting vs. the icon.

I realise this is a more complex idea, but If it's going to be in the radar, maybe it should be more informative.  I'd make a small flash around the blip corresponding to the ship that just made the mistake of targeting the player.

**Pull request closed without merging**
