### PR TITLE
Add <npcmodel> replacement variable for missions

### PR DESCRIPTION
**Pull request by kaol**
## Feature Details
Add `<model>` to replacement variables for its ship model if there's a mission NPC.

## UI Screenshots
N/A

## Usage Examples
Ship models are a bit hard to grep for, I replaced two places I knew of offhand. These cases had a fixed ship model known beforehand but it's still less maintenance burden to know that missions would need no changes if model names change again. This would allow using model name in mission name and description while still allowing it to be anything from some class of ships.

## Testing Done
I added the replacement to some missions and they were properly showing the ship model.

## Performance Impact
N/A

### CODE REVIEW

**Comment by Zitchas** [comment]
As a content creator for an area of space where ships are verging on being NPCs in and of themselves, being able to refer to the model of the ship in conversations and dialogs using a `<model>` tag would be very much appreciated.

**Comment by Zitchas** [comment]
Ah, yes, my own feature request from a while back. lol.

https://github.com/endless-sky/endless-sky/issues/6254

This wouldn't resolve the whole issue, but it could contribute to it.

It *would* resolve Amazinite's feature request here: https://github.com/endless-sky/endless-sky/issues/5366

**Comment by warp-core** [comment]
I don't think this does resolve Derpy's issue
 That is asking for a replacement to use the *player's* flagships model, similar to how `<name>` uses the player's flagships name.
This PR uses the mission NPCs model, like how `<npc>` uses the NPCs name.

**Comment by kaol** [comment]
Right, there's the player's ship and the npc's (target's) ship. How about using `<npcmodel>` then instead? There's no `<npcship>` since that's just `<npc>`.

**Comment by Zitchas** [comment]
Good eye, warp-core. Would it be hard to expand this to handle providing the model for both player and npc ship?

Also, which NPC? Missions can have multiple NPC ships. I'd expect it to be either the flagship of the first NPC (or fleet)

**Comment by kaol** [comment]
The same "which ship" ambiguity with multiple ships applies just as well to using the current `<npc>`. I checked how it goes, it's the last npc defined in the mission file, since that ends up being the first when it accesses it.
If there's a need to add some way to refer to nth npc in title and description then it'd need something that'd apply to both and I'd leave it for some other PR.

**Comment by kaol** [comment]
I'm not adding it to this PR either but now that I thought about it why are the disguised warship missions only saying the ship name? It sounds odd to me that the local government giving the mission to knows a ship's name but not its model. If anything they'd know only the model and not the name.

**Comment by tehhowch** [comment]
I don't think adding piecemeal replacements, like this PR does, is worthwhile. A consistent system for arbitrary lookup will resolve this, while also handling things like that NPC ship's name, government, and so on. And additionally not limited to just a single NPC.

(Ref comments in #3384)

**Review by RisingLeaf — APPROVED** [review]

**Review by Hurleveur — APPROVED** [review]

**Comment by Hurleveur** [comment]
> I don't think adding piecemeal replacements, like this PR does, is worthwhile. A consistent system for arbitrary lookup will resolve this, while also handling things like that NPC ship's name, government, and so on. And additionally not limited to just a single NPC.
> 
> (Ref comments in #3384)

I do think this is worthwile, even as a temporary solution before we get said complex system.
Once we added a few of these we can still refactor them all to fit said logic.
But in the meantime, content creators are not lacking tools as much.

**Review by warp-core — APPROVED** [review]
I'm going to merge this, but I do think any further auto-generated text replacements should be done via a system as described in https://github.com/endless-sky/endless-sky/pull/7176#issuecomment-1229232891 and the PR it links to.

**Pull request merged**
