### PR TITLE
Dialogue Improvement

### PR DESCRIPTION
**Pull request by tmbutterworth**
Modified dialogue to emphasize honor.

### CODE REVIEW

**Comment by jafdy** [comment]
You can change a previously opened PR as well, that does reduce the clutter some what.

**Comment by tmbutterworth** [comment]
> You can change a previously opened PR as well, that does reduce the clutter some what.

Thanks just figured out how to do that.

**Comment by endless-sky** [comment]
The current dialog is intentional; the Free Worlds planets have a higher prevalence of theistic religions than the rest of human space, and they're the ones deciding what the oath should be.

**Comment by KiLEdEnNis** [comment]
(perhaps the handful that refuses follow some other religion fiercely enough not to take the oath)

**Pull request closed without merging**
