### PR TITLE
Fix misspelling of deceleration

### PR DESCRIPTION
**Pull request by Janaszar**
Quick fix of a spelling error.  Mainly used as an example to figure out how to do Pull Request/Forks and the like for larger stuff.

### CODE REVIEW

**Comment by Janaszar** [comment]
Hmm... Was told it should be a PR from a branch on my fork, so going to redo...

**Comment by Janaszar** [comment]
And now people are saying it's ok if it's a single PR change... So, open again?

**Comment by Bladewood** [comment]
Erm... I think that was supposed to say "decelerating", not "deceleration"...

**Comment by KiLEdEnNis** [comment]
both fit though as far as I know

**Comment by Bladewood** [comment]
Yes, but it's usually better to preserve the original intent.

**Comment by endless-sky** [comment]
I feel like "start decelerating" is clearer that "start deceleration," because the choice the AI is making is, "Should I decelerate? Yes, I should start decelerating."

**Comment by Janaszar** [comment]
Technically it should be accelerating/acceleration since reducing your velocity is just applying acceleration counter to your existing velocity. (Something I still remember from my high-school physics with a slightly pedantic teacher)
As for the AI, it could also be thought of as "starting deceleration phase".

**Comment by KiLEdEnNis** [comment]
why not just change it to "decelerating", it's (also) correct & saves pointless discussions

**Comment by MessyMix** [comment]
@Janaszar and the term commonly used to describe that subset of acceleration—that is, acceleration in the opposite direction of your velocity—is deceleration.

**Comment by Amazinite** [comment]
It's a code comment.
Don't think too deeply about it.

**Comment by Janaszar** [comment]
Ok, so I know how to edit a PR now. (If I knew sooner, probably would have done it when I first noticed the difference.  But what an interesting conversation.)

Uses Decelerating instead of Deceleration.

**Pull request merged**
