### PR TITLE
Medium Warship tweaks

### PR DESCRIPTION
**Pull request by Pointedstick**
This pull request addresses issues https://github.com/endless-sky/endless-sky/issues/1598, https://github.com/endless-sky/endless-sky/issues/1626, and https://github.com/endless-sky/endless-sky/issues/1627.

I tweaked several Medium Warships to differentiate them and increase appeal as player-controlled ships. The changes are not major or radical, but should be sufficient to make them more desirable as player ships.

Extensive playtesting to ensure Free Worlds mission balance should not be necessary since none of these changes involve the ships' combat performance, except for the Firebird's shield and hull changes, but still there is no net durability increase (-600 shields + 600 hull).

With these changes, here is how the ships will appear to the player:

**Bastion:** Bulldozer: unwieldy but tough and deadly to anything in front of it
**Corvette:** High tech: fast, maneuverable, and powerful shields for its size
**Firebird:** Old reliable: inexpensive, durable hull, and good cargo space
**Mule:** Miniature capital ship: strong hull, four turret mounts, and a fighter bay
**Osprey:** Destroyer: surprisingly fast for its firepower
**Splinter:** Entry level: an inexpensive and flexible starter Medium Warship

### CODE REVIEW

**Comment by Bladewood** [comment]
"miniature capital ship"

**Comment by toilethinges** [comment]
Did you make sure the Corvette could fit that bigger shield gen?

**Comment by Pointedstick** [comment]
Yes.

**Comment by MessyMix** [comment]
I think the new Corvette is a little too good, and I would buff the Osprey's shield a little.

**Comment by Pointedstick** [comment]
I was trying to avoid changing the stock combat performance of any ship to avoid difficulties making sure missions strings are still balanced, but you may be right about the Corvette.

I don't actually expect MZ to merge this--it's the kind of change he usually prefers to make himself. My intention is mostly to offer an example, and to display community approval for the idea. If MZ agrees, I expect the actual changes made to be different, and probably more conservative.

**Pull request closed without merging**
