### PR TITLE
Hai specific jobs

### PR DESCRIPTION
**Pull request by Amazinite**
Changes:
* Moving Unfettered Tribute jobs from `hai missions.txt` to `hai jobs.txt`
* Giving Hai worlds a few attributes for jobs
* Removing tourist and colony jobs from Hai space
* New jobs specific to Hai space.
* Rare chance of finding human merchants with Hai outfits in large northern merchant fleets
* Created an extra set of human jobs (generic cargo and passengers) just for the Hai that are slightly bigger

The new jobs:
* Hai vacation (passenger). Bring Hai from their home worlds to some of the stranger worlds throughout Hai space. Plays off of the idea that Hai vacation on planets that are more chaotic and dangerous.
* Human vacation (passenger). The opposite of the Hai vacation missions, bring humans to the nicer of the Hai worlds.
* Hai festival (passenger + cargo). For one month out of the year (that month being march), the Hai have a huge festival to celebrate... something. I can't exactly fit a reason into the job description. Maybe someone could make a mission for it. :3 (My current idea is that they are celebrating the end of the war hundreds of years ago). Transport Hai and/or humans along with their party supplies to other planets to celebrate.
* Unfettered supplies (cargo). Similar to the Unfettered tribute jobs, only instead of starting on Unfettered worlds and picking up the cargo in Hai space, you start off in Hai space and deliver the cargo to Unfettered worlds.
* Special delivery to human space (cargo). A simple, small cargo job that involves the player having to transport cargo through the dangerous, uninhabited Far North. (Payments are always 80k credits due to wormholes not being taken into account for payment calculation).
* Escorts to human space (escort). Sizes small through extra large (excluding tiny given how annoying the constant refueling would be), escort human merchants to or from Hai space through the Far North. Payments are double that of normal human escort jobs because of the added risk of needing to refuel your escort and having almost no help from other factions.

### CODE REVIEW

**Comment by Amazinite** [comment]
Might need a look over. Especially the escort ones. This is my first time actually making jobs, so I wouldn't be surprised if I made some mistakes.

**Comment by KiLEdEnNis** [comment]
> My current idea is that they are celebrating the end of the war hundreds of years ago

March is when the Korath raids suddenly stopped?

**Comment by Amazinite** [comment]
Well we don't have any specific date so we might as well just set a random one.

**Comment by KiLEdEnNis** [comment]
which reminds me; a day is based on Earth spinning around, & years are Earth spinning around the sun
then why do aliens use it
(and yes it's too confusing not to use regular years ;-;)

**Comment by Elyssaen** [comment]
Nice work. But have you playtested the ones whose sources and destinations are filters either side of the wormhole? I thought the wormhole barrier affected not just payment calculation, but also the check the filter runs to see what matches. I'm going off memory but I wouldn't have expected those missions to work.

**Comment by Amazinite** [comment]
Yeah, it works. I think it only blocks routes through wormholes if there are other ways, but I forced it so that the only way was through the wormhole for those missions so it turned out well. 
Thanks for testing them out. :)

**Comment by Elyssaen** [comment]
Ah, I see it: when it comes up with a list of matches, it thankfully doesn't do the Distance calculation as long as you haven't given it a maximum distance. If it did it, it'd 'fail' because of wormholes, but it's not a problem here. Sorry for the false alarm. : )

**Comment by Amazinite** [comment]
Is the 12 day deadline enough for the longer escort missions? I'm thinking it might make sense to reduce the source distance from `0 2` to `0 1` and up the deadline for when you need to refuel.

**Comment by Amazinite** [comment]
15 days should be plenty of time, assuming you only take two stops and have the same or greater fuel than your escortee.

**Comment by Amazinite** [comment]
I think that's everything. The escort jobs seem to be working well and I couldn't find any other obvious typos.

**Comment by MessyMix** [comment]
If possible, I would make the cargo payments of 180k actually vary randomly, probably between 150k and 200k. I think this would add just a tad of flavor / variety to the missions ;)

**Comment by Lineth** [comment]
I don't think he can, for coding reasons. I might be misinterpreting your suggestion/reasoning, though.

**Comment by KiLEdEnNis** [comment]
he means having the payment vary between 2 values
if it's possibly, a bug could be that it could be any whole number, instead of rounded on (ten)thousands

**Comment by Amazinite** [comment]
Payment is either set or based off of distance traveled, and given that wormholes break the distance traveled method I can only do set payments for this jobs.

**Comment by Elyssaen** [comment]
@Amazinite, I'm still thinking of completing that Jumping mission PR. Would you like me to, as part of it or separately, look at a similar mission characteristic to tell a mission to use wormhole-routes?

If variable payment was a priority (not sure it is), you could set the Waypoint system as a waypoint, and at least pick up variable payment for the first leg of the journey.

**Comment by Amazinite** [comment]
I don't really see it as priority for these jobs, but I do think that it would be a welcomed change to be able to do it.

**Comment by Amazinite** [comment]
Tweaked passenger jobs to be 200 credits per jump instead of the 150 credits per jump from human space, and the festival one is 250 credits per jump given the special occasion. Delivery jobs reduced from 180k to 120k so that the escort jobs are worth equal or more.

**Comment by Amazinite** [comment]
I've mainly been focusing on the pirate jobs PR lately. Anyone think this needs work?

**Comment by KiLEdEnNis** [comment]
depends on the jobs, regular cargo/passenger transports are fine

**Comment by endless-sky** [comment]
The "job board" is meant to be a sort of public message board, so it wouldn't make sense for people in human space to be posting on there asking for escorts or cargo delivery to Hai space. Most humans who have discovered Hai space prefer to keep it a secret, and it's even possible that the Republic might take action to enforce that secrecy.

I'm not sure if it makes sense to me for the missions shipping "tribute" to show up on non-Unfettered worlds. At the very least, on the Hai side they should be described as "aid shipments," not as "tribute."

**Comment by KiLEdEnNis** [comment]
or charity

**Comment by Amazinite** [comment]
So would you say that human ships using Hai outfits in northern merchant fleets is a no?

**Comment by Amazinite** [comment]
Alright, removed the to Hai space jobs and changed the wording on the shipment jobs.

**Comment by Wrzlprnft** [comment]
you could move the 'to Hai space' jobs to rare spaceport missions in the north.

**Comment by Amazinite** [comment]
Now all Hai jobs are different from human jobs.

**Comment by toilethinges** [comment]
https://groups.google.com/forum/#!category-topic/endless-sky/_QH0kFGIQPg

**Comment by Amazinite** [comment]
[Who says they're using it for fuel?](http://witscience.org/five-uses-for-gasoline-you-never-knew-about/) :)

**Comment by Amazinite** [comment]
Lol, but apparently "jet fuel" is in the same category as gasoline, so that would pop up as well.

**Comment by MessyMix** [comment]
WOOOO

**Comment by Amazinite** [comment]
YES

**Pull request merged**
