### PR TITLE
feat(translations/text-overrides): Add Text class for formatting and translations

### PR DESCRIPTION
**Pull request by thewierdnut**
Along with some sample replacements to see what they will look like in the code.

-----------------------
**Feature:** This PR implements part of feature request detailed and discussed in issues #558 and #8572

## Feature Details
This implements a new `Text` class that can handle formatting and translations, along with a few examples of its use. For now, this is mostly a stub to evaluate if this is the design that we want to use. 

## Usage Examples
This adds a new `Text` class that can be used to handle string formatting
```cpp
	Text::Args args = {{"count", ships.size()}};
	Text txt = Text::FormatN("Deployed 1 carried ship.", "Deployed <count> carried ships.", args);
	Messages::Add(txt);
```

## Testing Done
I implemented the two messages shown in the PR, and verified that the messages look correct in-game

### Automated Tests Added
none

## Performance Impact
For now, there is no performance impact expected, although as we add support for PO files, this is likely to change.

### CODE REVIEW

**Review by petervdmeer — APPROVED** [review]
Nice! This can also be used to let plugins change default texts in the game (if we don't use it for translations).

**Review by warp-core — COMMENTED** [review]
Using `string` as the keyword for this within interface definitions seems like it'll be confused with the existing usage of `string` there, and it'll restrict any possible extensions of that.
It also seems to me like the example you've given for a string within an interface could just be done with a label anyway.

The pattern for `string` as a root node also seems extremely similar to tooltips and help messages. Perhaps it should be handled more similarly to those?
Though, the way it is used seems horrific.
```c++
			Messages::Add(GameData::GetString("recalled",
					{{"<count>", to_string(toRecall.size())}}
				), Messages::Importance::High);
```
This is not very readable, and seems like it just adds more difficulty if, for example, we wanted the pluralisation of the phrase to be more correct.

**Comment by thewierdnut** [comment]
> Using `string` as the keyword for this within interface definitions seems like it'll be confused with the existing usage of `string` there, and it'll restrict any possible extensions of that. It also seems to me like the example you've given for a string within an interface could just be done with a label anyway.

I apologize. I was unaware of the use of `string` to generate an `Interface::TextElement`. How about `text`? That doesn't seem to be used, although it could be confused for a TextElement by people familiar with the code. `label` is already taken. 

The Interface::TextElement object created by use of the `label` or `string` keyword does not look like it can handle arbitrary text substitution, just a simple string lookup. If you think the correct path forward is to extend that capability instead, I can do that, but it doesn't handle the use case where text is placed into `Messages::Add()`, and I wanted those two use cases to be similar.
 
> The pattern for `string` as a root node also seems extremely similar to tooltips and help messages. Perhaps it should be handled more similarly to those? Though, the way it is used seems horrific.

It is the same on the parsing side. I could make the conditional selection for "tip" and "help" more complicated and use the same parsing code, though I opted not to in this case. For rendering though, we can't use it the same way as tips and help text, as tips are not dynamic, and help text only substitutes keyboard commands. We need the ability to substitute numbers and labels. 

> This is not very readable, and seems like it just adds more difficulty if, for example, we wanted the pluralisation of the phrase to be more correct.

My current full implementation has a lot of logic like `GetString(number == 1 ? "message singular" : "message plural", {{"number": to_string(number)}})`, and it is sufficient for English, but other languages (such as [arabic](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-1493303624) or [polish](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-1493056457))  will need to know the exact number in order to handle the translations. 

Right now, I'm just re-using the Format::Replace() method, which does string-to-string replacements in the target text. Eventually, we will need more context about what we are printing (Is it a number? A date? A noun that needs to be modified to suit the surrounding words?), but I've deferred that to later on the TODO list in issue #8572. The PO file format and the translations tools designed to work with them are aware of those use cases, and we will eventually need to support them. 

I know the syntax is ugly, but what specifically don't you like about it? Some alternatives:

An overload or template method for single-argument substitutions:
```cpp
	Messages::Add(GameData::GetString("recalled", toRecall.size())), Messages::Importance::High);
```

Separate out the argument and message generation into separate steps:
```cpp
	map<string, string> args = {{"<count>", to_string(toRecall.size())}};
	string formattedMessage = GameData::GetString("recalled", args);			
	Messages::Add(formattedMessage, Messages::Importance::High);
```

Some sort of new formatting syntax:
```cpp
	string formattedMessage = GameData::GetString("Recalled %1 carried ships.", toRecall.size());
	Messages::Add(formattedMessage, Messages::Importance::High);
```

**Comment by warp-core** [comment]
> > Using `string` as the keyword for this within interface definitions seems like it'll be confused with the existing usage of `string` there, and it'll restrict any possible extensions of that. It also seems to me like the example you've given for a string within an interface could just be done with a label anyway.
> 
> I apologize. I was unaware of the use of `string` to generate an `Interface::TextElement`. How about `text`? That doesn't seem to be used, although it could be confused for a TextElement by people familiar with the code. `label` is already taken.

I think `text` would be better. I'm sure anyone familiar with the code can figure it out.

> The Interface::TextElement object created by use of the `label` or `string` keyword does not look like it can handle arbitrary text substitution, just a simple string lookup. If you think the correct path forward is to extend that capability instead, I can do that, but it doesn't handle the use case where text is placed into `Messages::Add()`, and I wanted those two use cases to be similar.

True, but I don't think it would be particularly difficult to add support for that. The substitutions could be passed into Interface::Draw via the Information object. Though, the example of the hail panel does not contain any substitutions, it is only text that is displayed based on the state of the panel. While Interface does not have direct access to that state, it is informed of hte state via the Information object, which is how the buttons are different depending on the state.

> > The pattern for `string` as a root node also seems extremely similar to tooltips and help messages. Perhaps it should be handled more similarly to those? Though, the way it is used seems horrific.
> 
> It is the same on the parsing side. I could make the conditional selection for "tip" and "help" more complicated and use the same parsing code, though I opted not to in this case. For rendering though, we can't use it the same way as tips and help text, as tips are not dynamic, and help text only substitutes keyboard commands. We need the ability to substitute numbers and labels.
> 
> > This is not very readable, and seems like it just adds more difficulty if, for example, we wanted the pluralisation of the phrase to be more correct.
> 
> My current full implementation has a lot of logic like `GetString(number == 1 ? "message singular" : "message plural", {{"number": to_string(number)}})`, and it is sufficient for English, but other languages (such as [arabic](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-1493303624) or [polish](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-1493056457)) will need to know the exact number in order to handle the translations.
> 
> Right now, I'm just re-using the Format::Replace() method, which does string-to-string replacements in the target text. Eventually, we will need more context about what we are printing (Is it a number? A date? A noun that needs to be modified to suit the surrounding words?), but I've deferred that to later on the TODO list in issue #8572. The PO file format and the translations tools designed to work with them are aware of those use cases, and we will eventually need to support them.
> 
> I know the syntax is ugly, but what specifically don't you like about it? Some alternatives:
> 
> An overload or template method for single-argument substitutions:
> 
> ```c++
> 	Messages::Add(GameData::GetString("recalled", toRecall.size())), Messages::Importance::High);
> ```

Just passing the substitute strings without needing to create a map in place is much more readable.
Perhaps the `string` definition could also define and order in which the substitutions are expected:

```html
string "my string"
    subs
        <count>
        <literally anything>
    "This is <literally anything>, and there are <count> of them."
```

```c++
int count = SomeNumber();
string literallyAnything = SomeThing();
GameData::GetString("my string", to_string(count), literallyAnything);
```

With `GameData::GetString()` having a signature something like:

```
string GetString(string name, string... subs);
```

The order listed in the definition would be the order that the subs will be parsed from the argument (so different versions of the string can use them in different orders.)

Though, a new class should probably be created and this stuff be moved into it, with GameData/UniverseObjects just holding a `Set` of strings.

> Separate out the argument and message generation into separate steps:
> 
> ```c++
> 	map<string, string> args = {{"<count>", to_string(toRecall.size())}};
> 	string formattedMessage = GameData::GetString("recalled", args);			
> 	Messages::Add(formattedMessage, Messages::Importance::High);
> ```

I like this more than what there is now, much easier to read, but it still has the issue of needing to construct these maps all over the place which I don't think is good for maintainability.

> Some sort of new formatting syntax:
> 
> ```c++
> 	string formattedMessage = GameData::GetString("Recalled %1 carried ships.", toRecall.size());
> 	Messages::Add(formattedMessage, Messages::Importance::High);
> ```

Not this one.

**Comment by thewierdnut** [comment]
> Just passing the substitute strings without needing to create a map in place is much more readable. Perhaps the `string` definition could also define and order in which the substitutions are expected:
> 
> ```
> string "my string"
>     subs
>         <count>
>         <literally anything>
>     "This is <literally anything>, and there are <count> of them."
> ```
> 
> ```c++
> int count = SomeNumber();
> string literallyAnything = SomeThing();
> GameData::GetString("my string", to_string(count), literallyAnything);
> ```

I'm a little worried that this will create a dependence between the code and the configuration that will be hard to visualize and keep in sync. For example, what if a plugin overwrites "my string", and then "my string" is later updated to have a third argument or something.

**Comment by thewierdnut** [comment]
> > Some sort of new formatting syntax:
> > ```c++
> > 	string formattedMessage = GameData::GetString("Recalled %1 carried ships.", toRecall.size());
> > 	Messages::Add(formattedMessage, Messages::Importance::High);
> > ```
> 
> Not this one.

Just curious... what is your objection to this solution? I thought it was the cleanest approach, and it is the one which translators working with po files are most likely to be comfortable with.

**Comment by warp-core** [comment]
> > > Some sort of new formatting syntax:
> > > ```c++
> > > 	string formattedMessage = GameData::GetString("Recalled %1 carried ships.", toRecall.size());
> > > 	Messages::Add(formattedMessage, Messages::Importance::High);
> > > ```
> > 
> > 
> > Not this one.
> 
> Just curious... what is your objection to this solution? I thought it was the cleanest approach, and it is the one which translators working with po files are most likely to be comfortable with.

Using that style to denote text to be substituted is inconsistent with the rest of the game.

Though, if you think that would be most compatible with translations via po files, that suggests that perhaps more should be done to consider and demonstrate how the different options for this could interact with different means of doing translations, instead of making assumptions about how we will eventually do translations that might not end up being true, which could then require this stuff to be totally redesigned.

**Comment by thewierdnut** [comment]
> Though, if you think that would be most compatible with translations via po files, that suggests that perhaps more should be done to consider and demonstrate how the different options for this could interact with different means of doing translations, instead of making assumptions about how we will eventually do translations that might not end up being true, which could then require this stuff to be totally redesigned.

Maybe I should start at the beginning then. 

There are a number of requirements I want to ultimately address through a series of self contained merge requests:
1. All text that gets displayed to the user needs to go through a lookup table for the user's preferred language, prior to formatting. 
2. The lookup table needs to either be in PO format, or needs to be able to have a PO template extracted from it for translators to use
3. The formatter that reads the default format string or the supplied format string from the PO file needs to be able to account for plurality, and various rules for article usage. 
4. The formatter needs to be able to handle locale-specific constructs for things like dates, times, decimal places, as well as comma-separated list construction.

My goal for this particular merge request was to address requirement 1. I was planning on working on the rest of the issues later. 

The PO file format is part of the full gettext solution, which is designed to work with the `printf()` family of functions. Normally you would use printf's positional syntax like this: `printf("%1$s %2$d", "string arg1", int_arg2)`, and the translator could switch the order or even omit arguments if needed. We do not need to use this syntax as we do not use printf, but we do need to come up with some sort of consistent formatting style that can be used for both interfaces and messages. 

While I don't think we should use the full gettext solution, my intention is to implement support for extracting POT files from the configs and/or the code, and then loading PO files generated by translators so that we can swap out text on the fly. Both files have a syntax that looks like this:

```
# comments and flags useful to the translator, but unnecessary for the program. Whatever
# tool we use to extract strings from the configs can fill in stuff here as needed.
msgid untranslated-string-singular
msgid_plural untranslated-string-plural
msgstr[0] translated-string-case-0
...
msgstr[N] translated-string-case-n
```

This syntax supports arbitrary plurality, but it does not support variation in article or noun usage, which we will have to add support for ourselves. 

My original intention was to support a syntax like this: 
"You have jettisoned <number> tons of <plunder>."

And then in the English PO file, you could say something like this
```
msgid "You have jettisoned <number> tons of <plunder>."
msgstr[0] "You have jettisoned 0 tons of <plunder>."
msgstr[1] "You have jettisoned 1 ton of <plunder>."
msgstr[N] "You have jettisoned <number> tons of <plunder>."
```

Other languages with more complex noun requirements, could specify extra strings as part of the plugin.
```
ship "Finch"
    ...
    stringtable
        form_1 "finch"
        form_2 "Finch"
        form_3 "FINCH"
``` 
And then could refer to those strings as part of the format:
```
msgid "You have boarded the <ship>."
msgstr "You have boarded the <ship.form_1>."
```

The main reason I chose a `map<string, string>` as the formatting argument is because we already have an in-house `Format::Replace` function. We will eventually either have to extend or replace that function though, so I'm open to other ideas. I don't mind using positional arguments, or named arguments, but I don't like the use of positional arguments in the code, and then tying the positional arguments to named arguments in the config, as that will be prone to breaking.

Eventually, we will need a set of template classes for the arguments though, to handle things like dates, lists, nouns, and possibly other things I haven't thought of yet, but that is for a future merge request.

**Comment by thewierdnut** [comment]
Per a discussion on discord, this MR has been updated to strictly demo a text formatting class that can be hooked to provide translations and formatting in the future.

**Comment by thewierdnut** [comment]
bump

**Comment by RisingLeaf** [comment]
I fail to see why we need a std::map for the args each time, we could just do something like
"<replace> and <replace>", {"two", "three"}
and then just go in order?

**Comment by thewierdnut** [comment]
> I fail to see why we need a std::map for the args each time, we could just do something like " and ", {"two", "three"} and then just go in order?

Because when we translate to other languages, the order of the arguments is not fixed. We either need named arguments, or the arguments need numbered (which is less context for the translators)

**Comment by RisingLeaf** [comment]
~I would be in favor of numbers though (I just hate std map)~

**Comment by thewierdnut** [comment]
I did propose a "%1 and %2" syntax, but that was shot down. 

I'm not thinking that the std::map will cause any performance problems, because I intend to cache the rendered results, so that they will only be run once.

**Comment by thewierdnut** [comment]
I'm gonna put this one on the shelf for now. I'll work from the other side first, and re-approach this once I know what the underlying api will look like.

**Pull request closed without merging**
