### PR TITLE
parse events for definitions while ref checking

### PR DESCRIPTION
**Pull request by comnom**
Both can be created entirely through events, so an undefined planet or system is acceptable.

### CODE REVIEW

**Comment by tehhowch** [comment]
While they can be, IMO they should not be. I consider the usefulness of detecting incorrect uses of a planet where a system was expected, or a system where a planet was expected, far more helpful to mission writers.

I believe MZ had a comment somewhere about using an event to finalize already-defined items, i.e. to set the position & links of a system, or assign a planet to a system, etc.

**Comment by MCOfficer** [comment]
Why not print out exactly that, that it **may** cause issues but can also have no consequences at all? that's what warnings are for.

**Comment by comnom** [comment]
>While they can be, IMO they should not be.

It's been supported for quite a while (https://github.com/endless-sky/endless-sky/issues/1605), and more than one plugin uses the feature. Akasha Chronicles and the ever popular Ursa Polaris to name a couple.

For new plugin authors, having warnings for supported behavior would be confusing.

**Comment by comnom** [comment]
>Why not print out exactly that, that it may cause issues but can also have no consequences at all?

However you word it, the it still amounts to: "Warning: what you are doing is ok." Things like that lead people to ignore other, perfectly valid warnings.

**Comment by tehhowch** [comment]
The warning will stay. However, what should happen instead, to address this use case, is to scan through `GameEvent` changes to check for additional definitions.

**Comment by comnom** [comment]
>However, what should happen instead, to address this use case, is to scan through GameEvent changes to check for additional definitions.

Fair enough. I'll revert the removal and add that shortly.

**Pull request merged**
