### PR TITLE
feat(UI): Purchase Destination & Amount Dropdowns + Generic Dropdown Code

### PR DESCRIPTION
**Pull request by Koranir**
**Feature:** This PR implements the feature request detailed and discussed in issue #8539 

## Feature Details
This PR adds a new UI panel/element: The Combo List. This element is a panel which takes a vector of string-function pairs and creates a combo list. I have used it to implement dropdowns for the amounts and destinations of purchased outfits and ships. 

## UI Screenshots

https://github.com/endless-sky/endless-sky/assets/101683475/fb8a773a-cfca-4a82-8f85-826ffd988161

https://github.com/endless-sky/endless-sky/assets/101683475/c2bcc36b-0a65-4085-bd44-91c280686eb6

## Usage Examples
ComboList can be used in a UI with:
```
GetUI()->Push(
    make_shared<ComboList>(
        Rectangle, // Button size
        Vec<pair<string, function<void()>>>, // Button list and callbacks
        Alignment, // Text alignment in the box
        bool, // Dim the background or not
        int, // Padding
        int // Index of initially selected element
    )
);
```

## Testing Done
not a lot :(

## Performance Impact
N/A

### CODE REVIEW

**Comment by Koranir** [comment]
I intend to use the combo list for multi-option preferences later.

**Comment by mOctave** [comment]
Just to confirm, the combo list doesn't break the combo keybinds, right?

**Comment by Koranir** [comment]
Probably shouldn't

**Comment by Koranir** [comment]
Gonna leave this for later, gonna do #8792 first

**Pull request closed without merging**
