### PR TITLE
Update Quicksilver sprites

### PR DESCRIPTION
**Pull request by Anarchist2**
image

## Summary
This PR updates the Quicksilver and derivative sprites to be of higher detail and quality. Also corrects an instance of a sprite being listed twice in the copyright file.
image
image

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/9
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/215

### CODE REVIEW

**Comment by 1010todd** [comment]
Not the best top-down preview image, 3/4 ships look blurry. Also might be good to compare to other ships from the same shipyard which I believe includes Splinter and Manta. The cockpit color looks a bit light compared to other ships and I'm not too sure about that weird design, can't tell what's the window and what's the frame or is it a single piece canopy with odd shape(for some reason).

**Comment by LepRyot** [comment]
Have to agree with most of the above. Good job with the detail and increased color for the base model is great. But the overall to me design lends it more like a space forklift than an agile warship. The frame is more boxy and everything's just less streamlined. It looks more modular if that's what you're going for but it doesn't seem to live to its Quicksilver name. Honest feedback, not wanting to put down your effort

**Review by Amazinite — CHANGES_REQUESTED** [review]
As mentioned, the cockpit looks off with being a fairly light color compared to other cockpits and having those grooves in it. Otherwise though this looks great.

**Comment by Amazinite** [comment]
The cockpit could stand to be a little darker still.

**Comment by Anarchist2** [comment]
Made the cockpit darker. Comparison of before and after:
quicksilver@2x

quicksilver@2x

**Comment by Amazinite** [comment]
Looks good, but looks like you accidentally grabbed one of the 2x images for this PR.

**Pull request merged**
