### PR TITLE
fix(content): Make certain blasters are sold on pirate planets, by adding them to pirate outfits sales

### PR DESCRIPTION
**Pull request by bene-dictator**
**Bug fix**
If you land on planets with only Pirate Basics sales (Bloodsea), you'll have the option to buy Modified Blaster Turrets but not Blaster Turrets. That seems a bit off, so I added Blaster Turrets to Pirate Basics (and Pirate Advanced.) Also added normal blasters for good measure.

### CODE REVIEW

**Comment by Amazinite** [comment]
I wouldn't consider this a bug. Does selling modified blasters necessarily mean that pirate worlds should also sell normal blasters? You can buy Modified Argosies on pirate worlds but not normal Argosies. Is this not the same situation?

**Comment by bene-dictator** [comment]
Presumably, pirates need Blaster Turrets before they modify them into Modified Blaster Turrets. Some pirates may simply plunder more Blaster Turrets than they need and are willing to sell them off. I'd consider the Argosy sales to be the same position, yes.

**Comment by bene-dictator** [comment]
> I think only selling the illegally modified blasters helps make Pirate outfitters more distinct and gives them some character, even if it isn't necessarily the most realistic.

I mean, blaster turrets are sold anywhere with basic outfits (something Bloodsea just doesn't appear to have) and modified blasters are sold at ports all over the South. (Whenever it's easier to make fleets I'll probably add civilian variants utilising modified blasters in the South).

Anyway, I might look into the Argosy thing as well.

**Comment by Amazinite** [comment]
When it comes to the Argosy, pirates don't even fly Argosies, only modified ones. There's perhaps more of an argument for selling both modified and unmodified blasters because pirates at least use normal blasters, but given how piracy works, I wouldn't expect that pirate systems would be selling every item that pirates use.

More generally, I don't think that selling a modified version of X necessarily means that the unmodified version of X should also be sold at the same location. This may not be much of an issue now when we're only talking about blasters and a single ship, but there have been discussions around adding more variety to what pirates sell to be outside of the norm that you find in lawful space. But since most of what the pirates would sell would likely be bootleg/modified versions of existing gear, having them sell both versions would turn them into one-stop shops for a lot of items. With that said, I'd prefer if the goal were give pirate systems a different selection from lawful space rather than an expanded selection.

**Comment by bene-dictator** [comment]
> When it comes to the Argosy, pirates don't even fly Argosies, only modified ones.

This is untrue: see line 1930 to 1938 of fleets.txt, and also my personal experience :smug:

> But since most of what the pirates would sell would likely be bootleg/modified versions of existing gear, having them sell both versions would turn them into one-stop shops for a lot of items. 

I get the first point somewhat, but these are _blasters_. The most basic of weapons.

Adding blaster turrets to a couple pirate planets isn't going to make them one-stop shops – especially if you can get them next door at Greenrock or Smugglers' Den. However, we could go the other way and remove blasters/blaster turrets entirely from poorer pirate outfitters if you want to see even more nuance for pirate outfitters. At the moment there are simply not enough outfits to give exclusively to pirates so nuance is... difficult.

**Comment by Amazinite** [comment]
> This is untrue: see line 1930 to 1938 of fleets.txt.

😳 

> I get the first point somewhat, but these are blasters. The most basic of weapons.

Like I said, I can see the argument for adding blasters given their already near-ubiquity. But I think that it's only their ubiquity that should justify adding them to pirate systems in this case, not that the pirates already sell a modified version of the blasters.

**Comment by bene-dictator** [comment]
> You can buy Modified Argosies on pirate worlds but not normal Argosies. Is this not the same situation?

I can't find this instance, every world that sells Modified Argosies through the "Advanced Southern Pirates" shipyard also sells normal Argosies through the "Southern Pirates" shipyard. (Modified Argosies are only sold in that one shipyard.)

**Pull request merged**
