### PR TITLE
Fix libPNG warning on thumbnail/smew.png and ship/smew.png 

### PR DESCRIPTION
**Pull request by leklachu**
**Bugfix (Artwork)**

## Summary

Fix the libPNG warning on the Smew images. Simply with `mogrify images/ship/smew.png` `mogrify images/thumbnail/smew.png`

As I understand it this should do nothing but fix the invalid iCCP chunk from the files

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#22747902

## Artwork Checklist
- I (obviously) claim absolutely no copyright on the 'altered' version of the images!

-----------------------
**Bugfix:** This PR addresses issue #7198

## Testing Done

Started the game - no warning. Also checked the images looked right.

### CODE REVIEW

**Comment by Amazinite** [comment]
Does the same need done with the high DPI repo?

**Comment by leklachu** [comment]
Yes. Here's fixed copies of those.
smew@2x
smew@2x-thumb

**Comment by leklachu** [comment]
in the 2x repository, `outfit/ember tear` has the same problem

**Comment by Amazinite** [comment]
Please open a PR to the high DPI repo to fix the problems there as well.

**Pull request merged**
