### PR TITLE
On waypoint mission action

### PR DESCRIPTION
**Pull request by Amazinite**
**Feature:** This PR implements the feature request detailed and discussed in issue #5411.

## Feature Details
Adds a new `on waypoint` mission action that behaves similar to `on stopover`, triggering on the last waypoint visited.

## UI Screenshots
N/A

## Usage Examples
See testing done.

## Testing Done
Tested the following two missions with expected results:
```
# Dialog appears when the waypoint is visited.
mission "on waypoint test single"
	job
	repeat
	waypoint
		distance 2 3
	on waypoint
		dialog `On waypoint testing complete.`

# Dialog appears after the third/last waypoint is visited.
mission "on waypoint test multiple"
	job
	repeat
	waypoint
		distance 2 3
	waypoint
		distance 2 3
	waypoint
		distance 2 3
	on waypoint
		dialog `On waypoint testing complete.`
```

## Performance Impact
N/A

### CODE REVIEW

**Comment by Zitchas** [comment]
Thank you!

**Comment by MasterOfGrey** [comment]
What are the odds we can get this to let you specify a particular waypoint with a system name, while having an unlabelled on waypoint refer only to the last one?

**Comment by Amazinite** [comment]
That behavior is redundant with `on enter <system name>`, so the odds are zero.

**Comment by MasterOfGrey** [comment]
Point taken, it's a behaviour I was also hoping to see for `on stopover` and I forgot about `on enter`.

**Comment by Amazinite** [comment]
The equivalent behavior for `on stopover` would be the `on land` action described in #4978.

**Pull request merged**
