### PR TITLE
Fix active cooling display

### PR DESCRIPTION
**Pull request by Ferociousfeind**
**Bugfix:** This PR addresses an issue with active cooling.

## Fix Details
When you install active cooling, the entire attribute is subtracted from your `idle heat` as displayed by the shipyard/outfitter, and all of the cooling energy is subtracted from your `idle energy` too, but in-flight, these attributes are first multiplied by your idle heat (as a percentage) before being applied to your ship, meaning the outfitter and the gameplay disagree if you install active cooling. This PR takes into account the behavior of active cooling to bridge the gap between outfitter and gameplay.

## Testing Done
Installing outfits with active cooling, and observing that the full attribute values do not act on the energy/heat table. Then, installing heat-generating outfits and observing that idle energy appears to drop- this is because the higher idle heat will demand more from your active coolers. Then, installing passive cooling, and observing that idle energy appears to increase- the lower idle heat takes the pressure off of the active coolers again.

## Save File
(Do I need a save file...? I suppose I can get to coalition space where there are active cooling modules abound...)
Using [this save file](https://github.com/endless-sky/endless-sky/files/9612300/Testing.Active.Cooling.txt), which is cleaner than save file(s) I've provided before, you can enter the outfitter and toy with the cooling modules (active cooling), korath heat shunts (passive cooling), and repair modules (heat generation without energy consumption/generation) to see how the energy/heat table behaves.

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
Huzzah, I always thought there was something weirdly funky about how that displayed.

**Comment by Zitchas** [comment]
I still find it amusing/odd that active and passive cooling are basically flipped around.

cooling that always manages to force X amount of heat out no matter how hot it is should be active cooling, and take energy. Passive cooling, which simply radiates heat out ambiently without using energy, is what should vary in effectiveness depending on amount of heat present (a hot surface will radiate more heat than something that is merely warm)

**Comment by EjoThims** [comment]
Yes, current behavior is to subtract the maximum values for both heat and energy.

What is the actual change in behavior here?

I'm not seeing that described anywhere.

**Comment by 1010todd** [comment]
> Yes, current behavior is to subtract the maximum values for both heat and energy.
> 
> What is the actual change in behavior here?
> 
> I'm not seeing that described anywhere.

It seems to display actual energy used and actual heat when idle instead?
Yeah the PR description isn't very clear.

**Comment by Zitchas** [comment]
> Yes, current behavior is to subtract the maximum values for both heat and energy.
> 
> What is the actual change in behavior here?
> 
> I'm not seeing that described anywhere.

The actual change, as described, is that for variable cooling / energy cost outfits (like our poorly named active coolers), they will display the *actual* current idle cooling and energy cost as things currently stand, instead of displaying the max values.

I'm generally of the opinion that showing the current values for the idle ship configuration might be a bit of an improvement over the current behavior of showing the max; but is still quite problematic and is almost certainly going to lead to confusion as well. We really need it to display a range that shows both the min (idle) values as well as the max values.

**Comment by warp-core** [comment]
How does a player determine the maximum performance stats of the ship as a whole without removing the active cooling outfits and adding their values to the displayed ship stats themselves?

**Comment by EjoThims** [comment]
I think ranges on it would be perfect for extended info window, however that is eventually implemented.

For base display changes, I'd prefer a better explanation of current behavior over changing to a different not always accurate display.

**Comment by Amazinite** [comment]
I don't see the benefit in changing the display of active cooling in this manner. If correctness is of concern, then this technically still misses the mark, since the application of active cooling reduces a ship's overall heat, therefore reducing the amount of active cooling that gets applied. It eventually reaches some equilibrium point, but that equilibrium point won't be what's displayed by this change. At least the existing behavior has the usefulness of giving you the worst case scenario for your energy usage and best case scenario for your heat, as Warp has highlighted.

> the outfitter and the gameplay disagree if you install active cooling. This PR takes into account the behavior of active cooling to bridge the gap between outfitter and gameplay.

Do they need to agree? When I look at my heat bar while in flight, all I have is a sense of how full it is with my concern being to not have it fill completely. When I look at my heat stats in the ship info my concern is keeping the base heat plus the heat from engines, weapons, and shields below the max heat. These are two different realms of concern and there's zero need to make them agree with one another, particularly when the concern in the outfitter would actually be harmed by this since. Imagine a scenario where one has low idle heat, only uses active cooling, and has engines, weapons, and shields that run hot. Currently the outfitter will probably display a negative heat value in this scenario since 100% of the active cooling is being taken into account, and when adding everything up, you'd get a heat value below the max, which is what you want in order to avoid overheating. But with this change, idle heat being low means that most of the active cooling won't display, which could give the impression that you're far more likely to overheat than you actually are.

**Comment by MasterOfGrey** [comment]
> but that equilibrium point won't be what's displayed by this change. At least the existing behavior has the usefulness of giving you the worst case scenario for your energy usage and best case scenario for your heat, as Warp has highlighted.

Will it not? I thought that's what this was doing?

If not, that sounds like it should be the goal.

**Comment by Ferociousfeind** [comment]
No, the idle heat used is the heat level your ship will idle at when not doing anything, taking into account active cooling too. I made sure. >:(

I thought we already went over how the active cooling outfits were falsely advertising because there were no situations where they actually ever operated at the advertised 100% power. Is this not being more honest with the player??

**Comment by Ferociousfeind** [comment]
What you want is multiple conflicting goals, that the current energy/heat table simply cannot display.

Yes, you'll usually just want to make sure that your heat levels added together do not exceed your max heat.

But at the same time, you will not always be sitting at 99.999% heat where you'll actually get that idle heat generation, you'll be sitting somewhere lower. Where you're sitting impacts how much energy goes into keeping your ship cool, which impacts how much energy is available across the energy half of the table, which is what this change prioritizes. I'm not actually stuck with only, say, 450 energy generation most of the time, usually it's much higher because the cooling modules are usually only operating at, say, 10% strength. Who knows how much energy the table isn't telling me about?

If you want to argue what needs prioritized, then what _needs_ to be prioritized is giving the player the ability to prioritize values themselves. What if I'm turning and firing weapons, and only my shields are damaged? How am I to know what heat equilibrium level I'll strike in this very common scenario? What if the enemy is using a korath repeater on me, putting heat on me artificially? There is no way to know how this affects your heat equilibrium. Ideally, and this is far beyond my ability, the energy/heat table should be replaced with an interactive graph (of energy/heat generation values with respect to heat level) with multiple buttons or switches to toggle certain behaviors and scenarios. This puts the prioritization in the player's hands, rather than dictating what some number of devs think is the priority.

**Comment by Zitchas** [comment]
I like the thought of having toggles and controls that let me prioritize the heat and energy usage I want to see.

**Comment by EjoThims** [comment]
>because there were no situations where they actually ever operated at the advertised 100% power.

This should have been resolved by not shutting down at 100% heat.

**Comment by Hurleveur** [comment]
Wait active cooling shuts down when you are overheated? No way, right?
I think this PR lacks examples of what was displayed before and after this change and why its better this way, to help everyone grasp whats going on.

**Pull request closed without merging**
