### PR TITLE
Better explosion sounds

### PR DESCRIPTION
**Pull request by Pointedstick**
Made the following changes:
* Replaced "explosion huge.wav" with a better sound
* Added "heavy rocket hit.wav" that sounds cooler, and tweaked the config files to make it play when a heavy rocket hits something
* Increased the volume of all the existing explosion sounds
* Decreased the volume of the heavy rocket launch sounds ("rocket.wav"), because it overpowered the heavy rocket explosion sound
* Attributed the new sounds appropriately

### CODE REVIEW

**Comment by Alkallid** [comment]
Why has been here with no merge or suggestion for improvement?

**Comment by lehgogh** [comment]
@Alkallid probably due to merge conflicts.

**Comment by Pointedstick** [comment]
Michael, would you merge this if I rebase it from head? If so, I will, but if not, I won't.

**Comment by endless-sky** [comment]
I can give them a try. The existing explosion sounds were intentionally rather muted so that they wouldn't get too loud and annoying when dozens of them are overlapping due to exploding ships, so I'm a bit worried about making them any louder.

**Comment by Pointedstick** [comment]
Cool, thanks.

https://github.com/endless-sky/endless-sky/pull/1526

**Pull request closed without merging**
