### PR TITLE
Nerf the flamethrower

### PR DESCRIPTION
**Pull request by Quantumshark**
**Content**

Reduced the flamethrower's heat damage by 25%, increased the firing heat by 100%, and added an additional dropoff from full effectiveness at 45 range (where it turns into the submunition) to half effectiveness at max range.

There has been considerable discussion of this in various places at various times, and it seems the general consensus is that the flamethrower should probably be weaker than it currently is. This PR aims to address that.

Related:
https://github.com/endless-sky/endless-sky/issues/5976

### CODE REVIEW

**Review by Arachi-Lover — APPROVED** [review]

**Comment by Hurleveur** [comment]
I'm just worried this could be overkill? This should overheat and decay over range but a heat nerf on top of that?
Mb make it damage shields a bit more? Idk

**Comment by Quantumshark** [comment]
The firing heat is changed from 120 to 240. 240 heat still isn't that much, that means you can offset the heat from three flamethrowers with one small heat shunt.
The damage dropoff forces you to get closer to get the full effect, but if you do that it's not a problem.
So I think the nerf to the raw heat output (which is only 25%) is still needed.

**Review by Hurleveur — APPROVED** [review]
This is definitely a change in the right direction, we can always adjust it some more later on

Do note however that overheat was nerfed recently and this weapon is pure heat damage (but we should un-nerf it a bit in the future so its fine)

**Comment by Quantumshark** [comment]
The overheating nerf broke the balance of the wanderer campaign and the flamethrower is still overpowered. The fact that the flamethrower deals 12,000 heat damage is a problem, and there's no way to adjust the heat mechanics to bapa

**Comment by Quantumshark** [comment]
(accidentally closed this while trying to comment because I was on mobile, please ignore that)

**Comment by Zitchas** [comment]
One concern I have with this is balancing in-campaign use Vs meta. So I well stay with the concession that in the Mets the flamethrower is comically effective and a nerf is needed. This is supposed to be a risky but highly effective weapon for use against generally more powerful Navy ships. How well does it fill that role with this adjustment?

To be clear, I'm not really concerned with how effective it is when filling every gun port on a weapons kestrel. What I am concerned with is how it useful it is when used as just part of the loadout for an interceptor, light warship, or maybe a medium warship as typically used by the average player at that point in the FW campaign.

**Comment by Quantumshark** [comment]
I'm only aware of the flamethrower appearing in the campaign in two places (three if you count the mission where you're testing it), which are the battle in Rastaban (where they're already kind of overshadowed by the fact that it's the first time you see the Dreadnought) and the mission where you're escorting freighters to Bloodsea, in which pirates use them against you.

**Comment by gunqqer** [comment]
> One concern I have with this is balancing in-campaign use Vs meta. So I will start with the concession that in the Mets the flamethrower is comically effective and a nerf is needed. The meta aside, this is supposed to be a risky but highly effective weapon for use against generally more powerful Navy ships. How well does it fill that role with this adjustment?
> 
> To be clear, I'm not really concerned with how effective it is when filling every gun port on a weapons kestrel. What I am concerned with is how it useful it is when used as just part of the loadout for an interceptor, light warship, or maybe a medium warship as typically used by the average player at that point in the FW campaign.

100% agree with this. we need to make sure we are not balancing for people min/maxing. Like yes I can put 8 flamethrowers on a shield beetle but the weapons should be balanced where they're supposed to be using: durring Free Worlds.

So it might be worth putting together graphs of how much time it takes 1-4 flamethrowers to disable certain ships already running at max power, and adjust based off where we want those graphs to be.

**Comment by Hecter94** [comment]
> 100% agree with this. we need to make sure we are not balancing for people min/maxing. Like yes I can put 8 flamethrowers on a shield beetle but the weapons should be balanced where they're supposed to be using: durring Free Worlds.

Flamethrowers specialize in disabling single targets and keeping them disabled; during FW is arguably when they are _least_ useful. 
Regardless, weapons should be balanced based on what they are being used for, and in this case, they are not used to beat FW; they are used for disabling high-tier ships that players otherwise would not be able to. 

As such, flamethrowers should absolutely be balanced around people who are min/maxing their builds, because that is what they are actually being used for.
If FW needs to be adjusted so the campaign is still at a reasonable level of difficulty even after these changes, we can do that.

**Comment by Quantumshark** [comment]
At the very least, if we did decide not to balance the flamethrower around meta use, we'd also need by the same logic to **not** try to balance other things around meta use of the flamethrower.
The choices are either 
1. balance the flamethrower
2. accept that the flamethrower is unbalanced, and ignore it when balancing other content

**Comment by Zitchas** [comment]
The problem with balancing around minn/max builds is that if we make something only moderately effective for a minn/Mac builds, that occurrence renders things non-effective for non-minn/maxed build. Or in other words, harder. I would rather have the game be easy for minmaxers than make it hard for everyone who doesn't do that. If we can manage both, though, that is great.

**Comment by Quantumshark** [comment]
I don't have any problem with the flamethrower being as powerful as it is currently. There are only two places where flamethrowers are used against the player, so provided neither of those is too difficult (and indeed, they are not) the flamethrower being too powerful doesn't cause me any problems.
What I do have a problem with, and what I am attempting to prevent by proposing this nerf to the flamethrower, is people breaking the balance of other existing content (the wanderer missions being an example) in the mistaken belief that the problem is some inherent property of heat damage and not simply the fact that the flamethrower is overpowered.

**Comment by Hurleveur** [comment]
Maybe modify a bit the place where it is introduced to add a "it is more effective at closer range because the fire is more concentrated?"

**Comment by Quantumshark** [comment]
I've added some extra lines in the dialogue referencing the damage dropoff, what do people think?

**Review by Hecter94 — APPROVED** [review]

**Pull request merged**
