### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by MessyMix**
> The use of “it’s” creates a pronoun reference grammatical error: is
“it” referring to the beam weapon or the hull armor? We all know that
“it” is referring to the hull, but the sentence is grammatically
incorrect. This change eliminates the ambiguity.

-my commit text

### CODE REVIEW

**Comment by MessyMix** [comment]
Okay. I'm kind of a noob at Github. Can someone teach me how to remove the "merge remote tracking" from this commit?

**Comment by KiLEdEnNis** [comment]
no idea
but it's not really a grammar fix, more just a different wording
but isn't the current way also right?

**Comment by jafdy** [comment]
I don't see it. As far as I can tell it makes perfect sense.

**Comment by MessyMix** [comment]
https://webapps.towson.edu/ows/proref.htm

> A pronoun should refer clearly to one, clear, unmistakable noun coming before the pronoun.  This noun is called the pronoun’s antecedent. Unfortunately, it is very easy to create a sentence that uses a pronoun WITHOUT a clear, unmistakable noun antecedent.
Example: Take the radio out of the car and fix it.
What is the _it_ referring to? The car or the radio? This is called a pronoun reference error, which is one of the major 7 grammatical errors (PR, AGR, DM, MM, PAR, FRAG, ROS, CASE).

In this case, the offending sentence is:
> This massive beam weapon is relatively ineffective against shields, but cuts through hull armor like it's made of paper.
Now, is the _it_ referring to the "shields", the "hull armor" or the "beam weapon"? Because the antecedent of "it" could equally be all of them:

> This massive beam weapon is relatively ineffective against shields, but cuts through hull armor like the weapon is made of paper

or

> This massive beam weapon is relatively ineffective against shields, but cuts through hull armor like the shields are made of paper

or

> This massive beam weapon is relatively ineffective against shields, but cuts through hull armor like the hull armor is made of paper

The game is trying to express the latter, but its not made clear. My suggestion resolves this error.

**Comment by Amazinite** [comment]
Welcome to the English language, where things can be understood differently.
>"The woman saw the man on the hill with the telescope."
Who has the telescope and who's on the hill in this situation? You can't tell at all, but that doesn't make the sentence grammatically improper.

That said, context clues, my dude. 
In this situation, the context is pointing toward the armor being made of paper.
Does it make sense to describe the laser beam as being made of paper? Well not at all, because paper can't cut through hull armor.
Does it make sense to describe the shields as being made of paper? Well no, because it said it's ineffective against shields.
Therefore, the context clues point toward the hull being what is described as being "made of paper."

**Comment by jafdy** [comment]
This massive beam weapon is relatively ineffective against shields. But cuts through hull armor like it's made of paper.

According to your webpage ~~that~~ my revision should be fine. As @Amazinite said it makes no sense any other way.
Also some of the examples on that page are very awkward.

**Comment by MessyMix** [comment]
Well @Amazinite, you're right that context clues. Context clues, but it doesn't stop it from being a grammatical error. Trust me or not, I implore that you trust Georgia State University (http://wac.gsu.edu/49577.html):

> A vague pronoun reference occurs when a pronoun could refer to more than one subject or the subject that the pronoun refers to is only implied.

The antecedent of "it" in this case, regardless of anything, is CLEARLY IMPLIED. That makes it a grammatical error.

And it makes me squirm inside whenever I read it. :(

**Comment by jafdy** [comment]
Can you at least find a less well known metaphor.

**Comment by MessyMix** [comment]
@jafdy I'm sorry, I don't quite understand what you're trying to say.

**Pull request closed without merging**
