### PR TITLE
feat(artwork): Material and Lighting edit for the Twin Blasters

### PR DESCRIPTION
**Pull request by Daeridanii1**
**Content (Artwork)**

## Summary
The current twin blaster sprites were some of the first I made for the game, and are more saturated and have softer lighting than their single counterparts. This PR gives them a material and lighting edit to bring them more in line with the rest of their family.

## Artwork Checklist
 - [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: [#114](https://github.com/endless-sky/endless-sky-assets/pull/114)
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: [#336](https://github.com/endless-sky/endless-sky-high-dpi/pull/336)

### CODE REVIEW

**Comment by Saugia** [comment]
From a gloss over, they look good. Care to show it in game next to the other blasters?

**Comment by Daeridanii1** [comment]
Here they are:
blasters

**Comment by Saugia** [comment]
Looks good! I'll grab the others' attention and we'll go forward from there.

**Comment by 1010todd** [comment]
I think the new one are too light and desaturated. Here are the old ones compared with single version:

twin blaster

blaster

twin mod blaster

mod blaster

**Review by GefullteTaubenbrust2 — CHANGES_REQUESTED** [review]
Gotta agree with Todd, I think the colors are too light and unsaturated.

**Review by GefullteTaubenbrust2 — APPROVED** [review]
Yeah, that‘s better. Not entirely sure why you changed the color management but whatever.

**Pull request merged**
