### PR TITLE
 Expand side panel in shops - Option

### PR DESCRIPTION
**Pull request by whismerhill**
A picture is worth a thousand words : 
This creates this : 
http://prntscr.com/hzbqst
http://prntscr.com/hzbq3n
http://prntscr.com/hzbpwq

That is : **the optional ability to get a second sidebar that is used for ship details only, freeing the other one for the fleet only**
why ? because scrolling woes begone !!!

note: currently this sidebar activates once you reach 16 ships in the fleet 
it also doesn't work on lower resolutions (< 1250 pixels wide, e.g. 1024x768) by design because those would have too much of their screen blocked off by those bars it would be awful.

note2: this was compiled and working on Visual Studio Community 2017 only.

note3: there's some weird white-space shenanigans going on in here
 you may add **?w=1** at the end of the url for the comparison to show the real diff
if someone knows how to correct those whitespace stuff, then be my guest.

Thank you for your attention.
Thanks https://github.com/jmhorjus for the code this work is based on and for allowing me to reuse parts of it.

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
you somehow reuploaded all the files so it shows as if you deleted everything & then added stuff, which is a no-go for reviewing
not sure how to work on desktop GitHub properly but find out how ya can just upload the changes ya made

**Comment by Amazinite** [comment]
Reference: #3326

**Comment by whismerhill** [comment]
@KiLEdEnNis 
try this view : https://github.com/endless-sky/endless-sky/pull/3533/files?w=1

**Comment by Amazinite** [comment]
You might want to just start over.
screen shot 2018-01-12 at 5 59 36 am

**Comment by Nescio0** [comment]
> try this view : https://github.com/endless-sky/endless-sky/pull/3533/files?w=1
it's a whitespace problem for some unknown reason

Please try again to solve that problem to allow it to be reviewed properly.

Furthermore, I'd prefer to have the “Buy | Sell | Leave” panel below the ship's details, where there is plenty of space, not below the fleet panel (which get filled up quickly once you have a few hundred ships).

Also, an option to shrink or enlarge the fleet's ship icons or change the number per row would also be nice; perhaps a future pull request?

**Comment by whismerhill** [comment]
then say how cause I have no idea what's this white-space problem, it has nothing to do with upload & everything to do with file formatting otherwise this link https://github.com/endless-sky/endless-sky/pull/3533/files?w=1 wouldn't work out.
see this for reference : https://github.com/blog/967-github-secrets
> Ever have someone push a commit that involves a lot of real changes mixed in with a bunch of less-meaningful whitespace? Add ?w=1 to the URL to see the diff with whitespace ignored.

in the meantime it can be reviewed just fine with this option of github
@Amazinite http://prntscr.com/hzfr03

**Comment by jafdy** [comment]
What about smaller screens?

**Comment by Amazinite** [comment]
>in the meantime it can be reviewed just fine with this option of github

It's not a matter of review, it's a matter of attribution. If this were to be merged, each of the entire files that you changed would be attributed to you by Github, instead of just the lines you actually changed.

**Comment by tehhowch** [comment]
Your changes were going fine until whatever you did differently with the "non Visual Studio" commit - at that point your changes are nuking the whole file. Check your line endings, and your repo's settings for how it handles those (you might be forcing it to be CRLF rather than native, etc).

Your editor is also trimming off whitespace, which you should disable for this project.

**Comment by whismerhill** [comment]
@jafdy as far as I'm concerned, I don't care about them, future PRs or other maintainers can edit whatever & however they see fit, they have been obsolete for a while now and you can't invent new pixels. The fact that screens below 1250 pixels wide (note that 1280x720 is ABOVE) is because it just takes too much of a % of the screen it's actually detrimental in my humble opinion.

@Amazinite alright that's valid, I'll retry if MZ is actually interested, **no way I spend more time on this if it's to be rebuked at the end of the road anyway.** 

@tehhowch Thanks for looking into it and this narrows it down to mean that's probably my sublime text custom settings I suppose. I'm unwilling to change those because I like them like that and also because I work on other projects with those settings just fine. That said, after some rest I have an idea or two of what I could try IF it has a chance to make it past the higher powers that rule this repository. Thank you again.

**Comment by tehhowch** [comment]
You should be able to set custom settings for a given project: https://forum.sublimetext.com/t/project-specific-settings-override/9103  (No idea how relevant that topic still is)

This won't get code reviewed *at all* in its current state - if the ?w=1 option is enabled, line review cannot be performed. At best you can hope for some commentary based on the images you present. I can offer that your code doesn't match that expressed in the style guide (inline comments, non-sentence comments, `if (things)` instead of `if(things)`, etc. Style guide is linked in the wiki.

**Comment by whismerhill** [comment]
ok, I will try to review the style over the week end & see about that http://editorconfig.org/ thanks a lot

**Comment by whismerhill** [comment]
https://github.com/endless-sky/endless-sky/compare/master...whismerhill:file-formatting-fix
it's gonna take a while

**Comment by whismerhill** [comment]
@endless-sky 
hi, sorry to bother you
could you ignore the commits & code changes for a minute, and answer this question : 
Does this has a chance ?
Could the content as shown by the pictures get integrated in the project ?

If yes I'll continue fixing the code & maybe patch this PR or open a new pull request when it's ready
if not then there is no point in me tidying up the code.
Thank you.

**Comment by endless-sky** [comment]
My generic answer to stuff like this is that the game is really designed around piloting a single ship or a small fleet, even though some accommodation is made for larger fleets.

I'm also not convinced that every player would see this as an improvement, because the interface ends up with a lot of "blank space" and leaves less room for the items in the shop.

**Comment by KiLEdEnNis** [comment]
to me that sounds like this particular solution is a no, even though another solution would be accepted

what if there is some checkbox in the outfitter menu:
- when one clicks it, it "locks" the ship's stats on the side menu (as if you scrolled down entirely), so basically when ya click it you'll always see the ship stats
- when it's not selected it behaves like usual, so smaller screens don't get hurt either way

would that be an acceptable change, @endless-sky ?

**Comment by Nescio0** [comment]
> I'm also not convinced that every player would see this as an improvement, because the interface ends up with a lot of "blank space" and leaves less room for the items in the shop.

The proposed feature is optional and can be toggled on and off in preferences, so those who do not want it don't have to use it.

**Comment by Bladewood** [comment]
> The proposed feature is optional and can be toggled on and off in preferences, so those who do not want it don't have to use it.

Sadly, this philosophy has been rejected many, many times before.

More or less, it's only really acceptable if more than 10% of the community would prefer it; anything less, we shouldn't have it.

**Comment by Nescio0** [comment]
>More or less, it's only really acceptable if more than 10% of the community would prefer it; anything less, we shouldn't have it.

Only 10%? This option is useful for everyone with about 30 ships or more.

**Comment by tehhowch** [comment]
The idea being, if it isn't good enough to default on, it probably shouldn't be added. Adding it means maintaining it through any other changes to the outfitter/shop panels too.

The ideal solution will smoothly handle going from 1 to N ships in the fleet, without significant loss of tile space for the ships or outfits being sold (as occurs for this PR at this moment). The current method in `master` never changes the space available to the sold items, and is only "bad" for giant fleets.

Perhaps instead of a scrolled single panel, the ships list is paginated, with the name of the most recently selected ship displayed, along with a count of the total selected in parentheses (or somehow otherwise displayed). The most recently selected ship's info display is docked to the smaller of its full height and some% of the window height, to minimize both pages needed and scrolling of the info up and down.
Or something.
(Basically, keep improving it so it works for any size fleet without huge amounts of unused space.)

**Comment by whismerhill** [comment]
Well I guess of course I'm gonna propose stuff like this, cause as a player this game is only fun to me because it gives me the liberty to do what I want and in particular, build a fucking fleet.

**Pull request closed without merging**
