### PR TITLE
fix(content): Added needed jump variants and put them in for HR

### PR DESCRIPTION
**Pull request by MasterOfGrey**
I'd overlooked making sure Danforth and the Auxiliary had jump drives. This should hopefully sort that out.

### CODE REVIEW

**Comment by HotaruSama** [comment]
Testing reveals they also need a keystone to go through the wormhole.

**Comment by HotaruSama** [comment]
Changes needed for the Dreadnought in this mission:
```
ship "Dreadnought" "Dreadnought (Jump Keystone)"
	outfits
		"Heavy Anti-Missile Turret" 3
		"Armageddon Core"
		"S-970 Regenerator"
		"Liquid Helium Cooler" 2
		"Jump Drive"
		"Volcano Afterburner"
		Supercapacitor
		"Outfits Expansion" 2
		"Plasma Cannon" 4
		"A520 Atomic Thruster"
		"A525 Atomic Steering"
		"Breeder Reactor"
		"Quad Blaster Turret" 2
		"Laser Rifle" 25
		"Water Coolant System"
		"S-270 Regenerator" 2
		"LP144a Battery Pack"
```
Added after the Jump variant in the human "variants.txt" file

And line 887 of hai reveal 5 philosophers.txt
from ship `"Dreadnought (Jump)" "F.S. Ironwood"`
to ship `"Dreadnought (Jump Keystone)" "F.S. Ironwood"`

**Comment by HotaruSama** [comment]
Okay, that was dumb of me. I made the variant and then forgot to add the Keystone, so line 1201 needs to have `"Quantum Keystone"`

**Comment by Zitchas** [comment]
Why do they need keystones?

**Comment by HotaruSama** [comment]
The mission chain in question creates a disconnected system between Polaris and Almach containing a red wormhole to a chain of empty systems just outside the galaxy.
Devil-Run
Devil wormhole

**Comment by MasterOfGrey** [comment]
> Why do they need keystones? Or perhaps more accurately, these ships are going through the Ember Waste?

FYI, this is a feature of the plot that may well change as it's legacy Nomadic.
I just didn't have the time/brainspace to consider a real alternative in doing the rest of the rework that needed to happen to this narratively.

**Comment by Hurleveur** [comment]
I think we need a PR for overhauling the variants of HR as they pretty much all suck (I havent looked at all in details but all I've seen are objectively bad and feel rushed)

**Pull request merged**
