### PR TITLE
Alphabetized Pug ships

### PR DESCRIPTION
**Pull request by Nescio0**
Cf. `coalition ships.txt`, `hai ships.txt`, `ships.txt`.

### CODE REVIEW

**Comment by tehhowch** [comment]
Previously they were in strength / tier order

**Comment by Tadrix** [comment]
No need to change this, IMO. "strength / tier order" is more helpful. Perhaps if we had so many Pug ships as humans have now…

**Comment by KiLEdEnNis** [comment]
for the humans it's a big mess, and alphabetized because it's from various shipyards
as for aliens, they're mostly from small to large, split in groups if needed (like Wanderer, Korath (grouped in base, Sestor & Mereti), Coalition (grouped per species, & Heliarch))
if anything, human ships should be grouped per shipyard, but even then ya have warships & civilian ships
for my own mod I do warships, freighters & transports from small to large & I split them up in those groups as well, which makes more sense to work with than alphabetized

the only upside for an alphabetized lay-out is so one can quickly find a ship, but ya have Ctrl + F for that too

**Comment by Nescio0** [comment]
So I've looked at the files again. I've seen no list sorted purely by size.
Humans, Marauders, Variants, Hai, Quarg, and Coalition ships are always sorted purely alphabetically.
Drak have just one ship.
Korath ships are sorted by faction. Korath by first encounter, then Sestor by decreasing strength, then Mereti alphabetically (i.e. increasing strength).
Pug ships are sorted by strength.
Remnant ships are unsorted.
Wanderer ships are sorted by introduction date.

I for one thinks this is internally inconsistent, so I'd prefer one way to sort ships. The alphabet works.

**Comment by Tadrix** [comment]
With humans there's too many things you could sort them by: Shipyards; Civilian (Transport, Freighter) and Warships; sizes (Interceptor, Light, Medium, Heavy, Fighter, Drone). Alphabetized order at least ensures you'd know where to find the ship you're interested in.

This problem is absent with aliens, because they have only one shipyard, so to speak, and their ships can be ordered in whatever order seems logical. Those who maintain those lists are used to such order, and this is not something ordinary player would see, so, unless situation changes, if it ain't broke, don't fix it.

**Comment by Nescio0** [comment]
This problem is absent with aliens, because they have only one shipyard, so to speak, and their ships can be ordered in whatever order seems logical. People who maintain ship lists ar most likely used to such an order (otherwise they would reorder them), and this is not something ordinary player would see, so, unless situation changes, if it ain't broke, don't fix it.

If only one person worked on a file and no new content was added, the order won't matter much. However, because the game is constantly being expanded, having one uniform standard is helpful. Have a look at the Hai. Originally they had four ships. Later someone else created four other ships. A third person has proposed another three: #3314 
Although it's not terribly important, I think it's wise to have a uniform sorting standard for all content files.

**Comment by endless-sky** [comment]
This just feels like "churn" to me - changing things for the sake of changing them. I'd much prefer that you focus your (and my) time and energy on making changes that either fix definite bugs, or will make the game more fun to play.

**Pull request closed without merging**
