### PR TITLE
Feat(balance): Lance load-out improvement

### PR DESCRIPTION
**Pull request by Zitchas**
**Balance:**

NOTE: This does not change anything about the actual hull of the Lance. Any build that one can currently do, one can still do, and saves are not affected. All this does is change out one stock component for another one.

## Summary
- Replace the "nGVF-AA Fuel Cell" with "KP-6 Photovoltaic Panel"
- Note: This PR is built on the https://github.com/endless-sky/endless-sky/pull/9165 , as the Lance is the ship that is the most affected by it.

## Reasoning
- The Lance when engaged in combat frequently doesn't live long enough to drain it's power anyway.
- Still retains a modicum of power generation to ensure it doesn't become stranded.
- We have fighter AI to cause fighters to return to the carrier to recharge.
- Most combat takes places towards the center of the system.
- Common complaint with fighter usage is how expensive they are to replace. The nGVF-AA fuel cell is single most expensive outfit on the Lance by a large margin (35k vs the next most expensive at 20k)
- An additional complaint is how slow they are compared to many other ships. The nGVF-AA fuel cell is the single heaviest outfit they carry.

## Impacts
- Now has an effective combat sortie duration limit, at least for active combat. It's still fairly long, but not infinite.
- It's effective loiter duration, however, remains infinite.
- acceleration +40 (from 256 up to 296)
- turning +15 (from 90 up to 105)
- cost decrease from  357900 to 299900 (16% reduction in shipyard purchase price. Note this includes the cost reduction from the supercapacitor price reduction PR, which is about half the cost reduction)

## Goals
- Small buff to ship performance, enabling them to change directions faster, respond to commands faster, and escape combat to return to their carrier faster.
- 16% reduced cost to purchase a replacement should make losing them more palatable. Still not great, but better.
- Makes the Lance (as purchased in the shipyard) more of a fighter, and less of an "interceptor that lacks an HD"

### CODE REVIEW

**Comment by Quantumshark** [comment]
If you've freed up all that space, why not replace the four supercapacitors with one LP036a? That would give it a lot more battery, and would also reduce the cost slightly.

**Comment by Zitchas** [comment]
From the perspective of "making the Lance more of a fighter and less of a warship that happens to need to be carried", which would entail building it more of a high mobility weapons platform that resupplies frequently; it is very much worth considering removing the missile rack and associated missiles. If it's dropped down to just the two missile pods with 8 missiles, its acceleration goes up to 316, and turning up to 112; and cost drops to 259200. It does, however, require that the carrier associated with it does in fact have missile racks and supplies to reload it.

> If you've freed up all that space, why not replace the four supercapacitors with one LP036a? That would give it a lot more battery, and would also reduce the cost slightly.

The associated PR that this is built on reduces the supercapacitor price from 9k down to 1.5k. That means that the lance here has the exact same cost in battery either way. In effect, this build here is trading a small amount of battery capacity (4k vs 3k) and a small amount of cost (13k and 11 mass for 4 supercaps+KP6 vs 6k and 10 mass for a LP036a). 

It's a reasonable suggestion, and worth considering. It basically comes down to how well the AI (and the player) can handle having fighters that are *exclusively* battery powered, rather than "primarily battery with a little safety factor; and which should be the default stock configuration?

**Comment by Zitchas** [comment]
I guess the question we should be asking is:

"Should the stock Lance be the 'specifically built for carrier operations' version, with the "more ammo" and "more energy" configurations be moved to variants for use in appropriate situations?"

**Comment by Amazinite** [comment]
#8842 buffed low end thrusters by about 25%, providing a bigger boost to speed than this reduction in mass. Speed wise, how do things look now? What is the new benefit that this reduction in mass provides?

**Comment by Ferociousfeind** [comment]
"299900" is kind of irritating me
is there any chance its hull could be price bumped up by 100 credits? call it spaceflation

**Comment by Zitchas** [comment]
I think I'm leaning towards removing the missile storage rack and thus having the stock lance one purchases be optimized as a cheap fighter to buy to fill bays without wasting anymore money than necessary. In which case the price is 252200 per Lance. I'm sure we could drop the hull price by 200 or something...

I'd rather not bump it up by 100, because I'd like to keep it below the psychological 300k mark. Same principle as why so many stores knock a single cent off the price of things (or rather, add 99 cents) to give customers the psychological feeling that they're paying less.

**Comment by TheMarksman-ES** [comment]
To me, Fighters in space may not be as great as advertised, but the current implications I have had of them in-game were that they were meant for planetary operations. If the carrier was meant to serve as a mobile base, then the fighters were meant to provide air support within the atmosphere, to provide the support that can't be given through flipping the bird and levelling the site from orbit.

Still, though, I like these changes. It would help in pushing players to pick them in game.

**Comment by Zitchas** [comment]
I have also have had people tell me that they usually ditch the shield regenerators, given that they are so small that they regen fairly insignificant amounts, that they are better off without them. Without them, they are both cheaper to replace, and move faster and thus have a better chance of returning to the carrier for mothership-based means of recovery.

For myself, I note that shield regen only seems to be particularly beneficial on fighters if the fighter has a combination of : 
a) high regen, and 
b) well crafted manouverability that results in them only be ocassionally targeted by their victim. For example, having fighters with very high max speed, but poor turning. Which forces them into strafing attack runs with long turn around periods well outside their victim's turret range that give their shield regen a chance to actually work
c) The fighter has sufficient allies that the fighter is never locked-onto for more than a few seconds at a time. This does require sufficient amount of b that they get far enough away that the victim swaps to a different target. A slow fighter often cannot get far enough away to shake it.

---

I haven't had many people chime in directly on the "Should the stock Lance be the 'specifically built for carrier operations" question, so I'm thinking of opting for that here. That being, I probably won't have time to do any actual modifications until the weekend, possibly next week.

**Comment by Hurleveur** [comment]
you could ditch a capacitator and add more sidewinders although I understand the idea of more manoeuvrable

**Comment by Zitchas** [comment]
Well, for one, given how most of our carriers move, having missile-fighters being more mobile enables them to more reliably dock with their carriers to get more ammo.

For another, it means they can more reliably stay away from their target.

**Comment by Amazinite** [comment]
As mentioned in #9234, I'm not a fan of this approach of trying to make fighters even lighter for the sake of increasing their acceleration. If fighters need higher acceleration, then we should give them that through other means, either through increased thrust or some method of directly improving their acceleration.

I also agree with Warp in that the specific changes made here are somewhat at odds with one another. We talk about how in order to make fighters effective, we give them missiles that keep them far from combat. But far from combat also means far from the system center, and so solar panels don't actually seem beneficial to use.

**Pull request closed without merging**
