### PR TITLE
Warn about minor or priority being mixed with landing for missions

### PR DESCRIPTION
**Pull request by Amazinite**
**Feature:** This PR implements a feature that should stop my dumb ass from making changes like https://github.com/endless-sky/endless-sky/commit/62f0226bd1483c0d6ec02b01c258ac9f2993c826 again.

## Feature Details
This PR adds a warning that gets written to the error file if a mission has either the minor or priority tag and also has the landing tag, as minor and priority don't effect landing missions.

## UI Screenshots
N/A

## Usage Examples
N/A

## Testing Done
Let's see what the test parses turn up.

## Performance Impact
N/A

### CODE REVIEW

**Comment by Amazinite** [comment]
Well well well. It would appear I'm not the only one who's made this mistake.

**Comment by Amazinite** [comment]
I'll note that the wiki mentions that `priority` is only used for the intro mission as a way to prevent any other missions from offering, but it's also a landing mission that appears in the special case situation of after you've just bought your first ship, so really it's the `landing` that's making it offer while `priority` has no effect. Given that MZ's expectation was clearly that mixing `priority` and `landing` would work, should we reassess #4752 and perhaps allow these tags to be mixed and have an effect? (Multiple landing missions where they're all minor = only one offers. Multiple landing missions where some are minor and some have no extra tag = only the non-minor missions offer. Multiple landing missions where some are minor, some have no tag, and one or more have priority = only the priority mission(s) offers).

**Review by tehhowch — APPROVED** [review]

**Comment by tehhowch** [comment]
I'm also fine with extending the behavior of minor and landing. It's fine to include this warning now, and update them to work as expected in a later release.

**Comment by Amazinite** [comment]
In that case I'll reopen that issue and we can merge this one now.

**Pull request merged**
