### PR TITLE
feat(sounds): Ember Tear Unique SFX

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Sounds)**

## Summary
The current Ember Tear sound is simply the Ion Cannon sound. While the Ember Tear (and Heron) are currently placeholders/future content examples, the loud, obnoxiousness of using an Ion Cannon sound on a Remnant weapon is extremely unfitting. This PR replaces that definition with a brand new sound effect for the Ember Tear.

Old Sound:

https://user-images.githubusercontent.com/93169396/208531277-c518f779-8053-43a1-8cac-05770862e1b0.mp4

New Sound:

https://user-images.githubusercontent.com/93169396/208531090-e0ae5e3e-f3e2-4ddd-943b-3cbc8331f2b3.mp4

The new sound is more eerie, more beam-like, and has a deep tone to it as most Remnant weapons do. It is obviously quieter, and I cannot increase the sound volume any more than I have in Audacity or else it will click hard. However, I don't find that a problem, and still somewhat fitting for the Remnant's quieter weapon sound pool, even for a superweapon like this. 

Aside from the deepr tone sound, there is a bit of a wave-like Scifi sound in the beam sound's loop. While I think it still sounds cool and works for a weapon like this, Z said he wasn't sure how he felt about it, but unfortunately I cannot simply cut that part out of the audio. Regardless, even if in the end it isn't desired, I feel it's entirely worth the rest of the sound and replacing the Ion Cannon one.

I've also added a hit effect sound to the Ember Tear's vortex hit effect. Somewhat zappy, still not very loud, but appropriate for the new sound (and having sound is better than none for a weapon impact of this magnitude).

## Save File
N/A

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified

### CODE REVIEW

**Comment by Zitchas** [comment]
Thanks for PRing this. Given time to reflect, I definitely like this new main beam sounds. Not to sure about the impact sounds, though. It seems a little too... High pitched? Staticy?

But there main sound is very good

**Comment by Saugia** [comment]
https://user-images.githubusercontent.com/93169396/208549428-b8a4ea0e-b0e4-4a21-837a-056140c041a5.mp4

@Zitchas Low-pitched. Very subtle. (Any louder and it clicks badly.) Again, some sound vs no sound.

**Comment by Zitchas** [comment]
That last iteration there sounds much better. I like it.

**Comment by 1010todd** [comment]
I think the firing sound a bit too much like electron beam.

**Comment by McloughlinGuy** [comment]
I like it, it sounds like it’s tearing the space around it apart, which is exactly what it should sound like.

**Comment by Saugia** [comment]
>I think the firing sound a bit too much like electron beam.

https://user-images.githubusercontent.com/93169396/208707450-d47c8b4d-b584-48ea-a09b-bddbeeeb1726.mp4

At least to me it doesn't. They sound like two completely different weapons.

**Comment by 1010todd** [comment]
There's still something that rings the same to me but side-by-side it seems to be different enough I guess. So if possible I kidan want to hear something more different but as is it's not a big deal, I won't mind it too much.

**Pull request merged**
