### PR TITLE
Replace Graviton Thruster and Steering with Graviton Engine

### PR DESCRIPTION
**Pull request by jmhorjus**
Data only change, tested and working. 
Each graviton engine is exactly 1/2 a graviton thruster and 1/2 a graviton steering with the exception of the added reverse thrust and new description.
Old outfits were left in for legacy support (don't break saves).

### CODE REVIEW

**Comment by Gkramme** [comment]
This is in the drak engines.

**Comment by jmhorjus** [comment]
@Gkramme What is, specifically? I haven't seen Drak ships or engines. What are their engines called?

**Comment by jmhorjus** [comment]
Wait, I see what you mean.  The Drak ship that's defined in the data now also has graviton thrusters/steering listed on it that need to be replaced.

**Comment by jmhorjus** [comment]
Crap...something bad in my merge randomly deleted a bunch of files.  This comes of trying to make branches that don't include everything from my own master (because it already has an outstanding pull request).  Closing, will make a new pull from a new branch.

**Pull request closed without merging**
