### PR TITLE
Skylance Images

### PR DESCRIPTION
**Pull request by BlueFireball**
I'm new to GitHub (so I may be doing something incredibly wrong here) but I made some Skylance models and I'd like to request them. (Edit)
quarg skylance
quarg skylance x2

### CODE REVIEW

**Comment by ksrb** [comment]
Congrats on making a PR and making your way through git and github in general.

Though there seems seems to be a lively PR on the skylance and other quarg outfits in general here:
https://github.com/endless-sky/endless-sky/pull/3536

**Comment by Brick63** [comment]
There's nothing wrong with having different proposals for the same thing, so feel free to continue to improve on this

**Comment by ksrb** [comment]
Also in general instead of 'request them' what you're actually doing is asking if your PR could be merged.

**Comment by BlueFireball** [comment]
Welp, thanks for the compliments, and their skylance looks better than mine >.<
Also, here's the image resizing
quarg skylance
quarg skylance x2

 :

**Comment by BlueFireball** [comment]
Well I'll try make a PR there then, and I'll delete the 2x images on this PR

**Comment by BlueFireball** [comment]
Alright, made the @x2 PR : https://github.com/endless-sky/endless-sky-high-dpi/pull/53

**Comment by BlueFireball** [comment]
Well at this rate this post is a giant necro and the images need to be improved so this shall be closed.

**Pull request closed without merging**
