### PR TITLE
More detailed ship stats list.

### PR DESCRIPTION
**Pull request by quyykk**
## Feature Details

This PR adds a way to see all stats of a ship in the outfitter (like builtin stats but also the total stats like total thrust for example). I'm not 100% sure about some things so feedback is much appreciated:

- The way this list is shown is where outfits stats are displayed (see screenshot). It is shown when you click on the ship sprite of the normal ship stats section (Not exactly discoverable but UX is hard - If anybody has better ideas feel free to comment).

- The "outfit thumbnail" shown is the ship's thumbnail but wireframed. Again see screenshot. You'll also find two other alternatives to consider. Feel free to comment which one of those 3 is better.

- Something else to discuss is whether to show stats that already appear on the normal stats section (like shields, cargo space, bunks, ...). I filter them out currently, but feel free to provide feedback.

Thanks!

## UI Screenshots

ship stats full

<details>
<summary> Alternative ship sprite.</summary>

advanced-statsv5

advanced-statsv3

</details>

## Testing Done

Played with this feature in the outfitter.

## Performance Impact

N/A.

### CODE REVIEW

**Comment by Amazinite** [comment]
Ref: #4215

**Comment by Amazinite** [comment]
Ref: #2433

**Comment by Zitchas** [comment]
Hmmm.... I can definitely see the utility in having this all listed in the outfitter panel like this.

I was initially going to say that I'd much rather we get a pop-out window with all the ship stats and space for a scene involving that ship. But then I thought about it, and realized that having a more utilitarian "here's all the stats, including less visible ones" that you have here would be quite useful to have in the outfitter like this. I still want/hope for a proper "more info" panel in the shipyard, but this PR looks like it provides some definite benefits.

**Comment by Hecter94** [comment]
I notice "illegal" also gets added up, for instance having 500 nerve gas, shows you'll get fined 500,000,000 if you get caught.
image

**Comment by NaitNait** [comment]
Personally would find this incredibly useful, especially when outfits have less intuitive additional effects like ion protection or disruption resistance. Something completely missing from the game is special ship stats like "spinal mounts" which is impossible to know without looking at ship files. 

Will the stats be able to display information when selecting multiple ships? A tooltip when hovering over the values, breaking down the components and other ship's values (when multiple are selected), would be impressive. Not sure if organizing the values into categories is worth the UI space and discontinuity in alphabetical order. 

In terms of information overload, having this information under another UI/hotkey is reasonable since it lets the player know this is extra. I personally prefer the list being a sort of master list and having all information there. I am not sure if having an image of the ship is worth the space since there is already on there, people who would look at these numbers are only interested in the numbers (though possibly actual ship size, hitbox, and weapon location).

**Comment by Hurleveur** [comment]
There is some potential here, especially for seeing ramscoop (but maybe it should show effective ramscoop instead?)
Definitely needs some ordering around though, maybe it should be in expandable sub categories? As in navigation, protection, utilities (scanning and everything that doesn't go in the other categories)

**Comment by Amazinite** [comment]
My original idea for #4215 involved not simply displaying the exact stats, but converting those stats to something more useful where possible. For example, instead of displaying the ramscoop value, display how much fuel per second one would be expected to gain given a distance multiplier of 1 and a solar wind of 1. Or instead of displaying the protection values for damage, display how much damage will actually be received (e.g. a hull protection of 10 would display as 90.9% hull damage received or something like that). We'd of course also only display stats when relevant; for example, if you don't have any scanners then we wouldn't display your scan time or range.

**Comment by Amazinite** [comment]
> It is shown when you click on the ship sprite of the normal ship stats section (Not exactly discoverable but UX is hard - If anybody has better ideas feel free to comment).

Perhaps keep this as the way to show the extra stats, but add something to indicate that the sprite can be clicked on.

image

**Comment by Zitchas** [comment]
Just tried it out, and it works. It's nice being able to see all the values in there. Definitely could see some use and value for those who like to carefully optimize their ship.

**Comment by Saugia** [comment]
I'm still not entirely sold on the outline thumb + grid design for the image- part of me thinks that if done this way that the grid itself isn't entirely necessary and the outline thumb could be by itself, but then that loses consistency with other ES interfaces. 

Idk, the way it is now it just seems like too much empty space for an image that is supposed to represent more details of a ship, at least coming from a design standpoint.

**Comment by Amazinite** [comment]
For me I see it as taking an "x-ray look" at the ship, hence the increased detail of attributes that are normally "under the hood."

**Comment by Zitchas** [comment]
It would be neat if we could extract some kind of imagery that looks x-ray-ish. Maybe a ghost image of the ship's thumbnail or something? That would fill up the space a bit, and perhaps give the illusion of showing some skeleton or something.

**Comment by quyykk** [comment]
this was more of an experiment, no need to keep this open. We can always reuse the work done here in the future (or not).

**Pull request closed without merging**
