### PR TITLE
Remove wandering nightmares

### PR DESCRIPTION
**Pull request by Quantumshark**
## Summary
Removes wandering nightmares.

### CODE REVIEW

**Comment by warp-core** [comment]
You should also remove the lines in the first contact missions that fail this mission once those are offered.

**Comment by warp-core** [comment]
And, consider removing the event that triggers this mission.

**Comment by UnorderedSigh** [comment]
@MasterOfGrey should review this.

**Review by UnorderedSigh — APPROVED** [review]
Tested and confirmed to work. This mission was originally needed because the Wanderers campaign was locked out by preventing the player from landing on any of their planets. There had to be an event and message informing you that you could visit them. Now the Wanderers campaign is locked out a different way, so this mission is no longer necessary. I think that drawing the character to the Wanderers forcefully like this is now unnecessary.

I used this save to test it.

[Friction Diction~3026-06-01 TRY12 before C05.txt](https://github.com/endless-sky/endless-sky/files/10613738/Friction.Diction.3026-06-01.TRY12.before.C05.txt)

**Comment by RisingLeaf** [comment]
> @MasterOfGrey should review this.

nah, we agreed on instant merge....

**Review by warp-core — APPROVED** [review]

**Comment by warp-core** [comment]
Actually, no, can you remove the mission and event that are mmarked by the TODO below the wandering nightmare event line?

**Comment by UnorderedSigh** [comment]
@warp-core - that should *not* be done in the same PR. You don't really know if it is safe to remove the main clean-up event. It would require retesting the campaign from the beginning.

Someone should open a new PR for that. It is too high risk to be done without testing.

**Comment by UnorderedSigh** [comment]
@warp-core are you talking about this?

```ruby
# TODO: delete this mission and event before next steam build - just to fix up saves running on continuous.
mission "Hai Reveal [C05C] Cleanup Check"
        landing
        invisible
        to offer
                has "Hai Reveal [C05] Cleanup: done"
                has "Hai Reveal [A11-A] Permanent Fleets: active"
        on offer
                fail "Hai Reveal [A11-A] Permanent Fleets"
                fail "Hai Reveal [B02-A] The Blockade Goes Up"
                event "stormhold unsuppressed"

event "stormhold unsuppressed"
        system "Alcyone"
                add fleet "Small Core Pirates" 400
                add fleet "Large Core Pirates" 600
                add fleet "Korath Large Raid" 50000
                remove fleet "Human Wormhole Guards"

```

**Comment by UnorderedSigh** [comment]
*Definitely* do not remove that without testing from the beginning of Hai Reveal.

**Comment by warp-core** [comment]
If it isn't safe to remove it, that comment is extraordinarily bad.
But, fair enough. I'll do it later.

**Comment by UnorderedSigh** [comment]
I have opened an issue on that comment/mission:

https://github.com/endless-sky/endless-sky/issues/8295

**Comment by UnorderedSigh** [comment]
You can safely delete `mission "Hai Reveal [C05C] Cleanup Check"` and `event "stormhold unsuppressed"`. I just replayed Hai Reveal 4-6 without those, to confirm it works.

**Review by Hurleveur — APPROVED** [review]
I have no say in content but I dont like this mission, I feel like it prevents exploring.
Giving the location is my main issue with it but I dont see the harm in removing it; it feels like plugin content to me.

**Pull request merged**
