### PR TITLE
Wrap messages when drawing them to prevent overflow

### PR DESCRIPTION
**Pull request by tehhowch**
Refs #1825 
For this screenshot I set the wrap width to be really short, in order to illustrate the wrapping.
image

### CODE REVIEW

**Comment by jafdy** [comment]
Is it  supposed to be right over to the side like that?

**Comment by KiLEdEnNis** [comment]
could ya also include a screenshot with the actual feature implemented? (no absurdly small width)

**Comment by tehhowch** [comment]
With wrap at the normal position (i.e. constraining messages to be within the box defined in the interfaces file) it looks like you expect because the normal hails are not so long that they wrap. Only really long hails / messages are going to wrap.
This PR adds support for longer hails/messages, and prevents bad UI for those who use a modified interface that might not allocate as much horizontal space for messages.
I'll try to get a message long enough to wrap

**Comment by tehhowch** [comment]
By tweaking those planet names, I can get it to wrap at the normal position (which indicates that the normal position is not quite correct, as well):
image

**Comment by tehhowch** [comment]
Adding a 20pt pad to the right edge of the messages box fixes that issue. This same pad could be achieved via adding margins in the WrappedText object, but changing the interface file means one less operation needs to be done to draw the text:
<details><summary> fixed box padding </summary>

image
</details>

**Pull request merged**
