### PR TITLE
A bunch of discontinuous typo fixes

### PR DESCRIPTION
**Pull request by Bladewood**
"Discontinuous" in the sense that most of them have little to do with each other.

### CODE REVIEW

**Comment by Bladewood** [comment]
ah what the hell is with this commit system

**Comment by Amazinite** [comment]
You using an old branch.

**Comment by Bladewood** [comment]
Please, advise.

**Comment by Amazinite** [comment]
Instead of creating a new branch from the main and editting that, you editted and PRed an old branch which has all this gobully-goock in it.

**Comment by Bladewood** [comment]
But... this is the master branch... ah, hell. time to go find a Git guide for dummies...

**Comment by Amazinite** [comment]
Exactly.
It's old.

**Comment by Bladewood** [comment]
ah, hell

**Pull request closed without merging**
