### PR TITLE
mission: "FW Northern 4.1A" fix

### PR DESCRIPTION
**Pull request by LocalGod79**
it was possible for the player to complete mission "FW Northern 4.1A",
proceed through the storyline to mission "FW Bloodsea 1.2A" where
their karma could be lowered enough to be offered "FW Northern 4.2A".

### CODE REVIEW

**Comment by endless-sky** [comment]
Fixed in b77e2cf. This doesn't quite work because you need to use either the ":offered" or ": done" condition. (Also, I think it makes sense to put the check in the "to offer" instead of a "to fail".)

**Comment by endless-sky** [comment]
But, thanks for tracking down the bug and pointing it out!

**Comment by LocalGod79** [comment]
just followed a pointer from steam...

i know about : offered or : done - it was late, i was tired...

**Comment by LocalGod79** [comment]
as an aside, it was only possible for the karma to be adjusted downward after that point, so i figured the alteration to 4.1A was superfluous - never hurts to be thorough, i suppose.

**Comment by endless-sky** [comment]
Yes, especially because further changes to the story might make it possible to gain karma, too.

**Pull request closed without merging**
