### PR TITLE
Added a new station image

### PR DESCRIPTION
**Pull request by Wrzlprnft**
Just a new station image. Doesn't have a purpose, yet, except just to add a wider variety of stations.

station8 2x

[Assets and 2x file.](https://drive.google.com/open?id=0ByRgAHNH4k7rdXViQm9welA0NWM)

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
Further, if anyone thinks he/she/confused found a fitting place, ill include it in the pull.

**Comment by Alkallid** [comment]
The hexagons and center don't contrast well; the hexagons are sort of blurred and flat-colored, while the center is _too_ detailed (and asaymetrical)

**Comment by Wrzlprnft** [comment]
It is asymmetrical, yes, because it is rotated, but yeah, the lack of detail on the hexagons doesn't create the shadow needed for it. But i was thinking of them as landing pads, so i wasn't sure if i should change much more. I can detail the hexagons more if this version won't get merged.

**Comment by Wrzlprnft** [comment]
station8 alt
I toyed around a little with the 3D-Model (since this was the original way this station was born), and came up with some variations. Since the post-processing takes quite a time, i would like to have more feedback before i swap the image out.

**Comment by Gkramme** [comment]
Looks cool, but blocky. Could be a drak station mabye?

**Comment by Wrzlprnft** [comment]
As i sized this one, i felt almost bad for scaling it down to the size of other stations. It looks way more impressive a little larger. The Drak could do something like that, but i am not sure if that's their style. Maybe if i place the "landing pads" in the manner of spider legs. let's see what @endless-sky says to this one.

**Comment by endless-sky** [comment]
For stations, the light has to come from below at a low angle so that the lighting will match the planets; see [this file](https://drive.google.com/open?id=0B9aK8dG39P29eWo5aHo3ZVNrbVU) for an example.

Also, your model has lots of tiny-scale detail (the texture) and a few large-scale details, but I think it needs more medium-scale detail too so it looks less like a collection of plain geometric shapes.

**Comment by Wrzlprnft** [comment]
Okidoki. Haven't planned that one, though.

**Pull request closed without merging**
