### PR TITLE
Add updated Republic Navy ships by Gefüllte Taubenbrust

### PR DESCRIPTION
**Pull request by dragonmaus**
## Summary
Adds Gefüllte's excellent new Navy ship designs.
new navy ships
new navy carrier
new auxiliaries
retextured gunboat
Latest as of 2021-12-07:
updated ships

## Save File
This save file can be used to view the updated models:
https://gist.github.com/dragonmaus/96d0e915145633792f6e5856cb355950

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/drive/folders/1DDq0Xe6rFC2KhcVKHvtUlSAsZQHavZic
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/189

### CODE REVIEW

**Review by WarlordMike — APPROVED** [review]

**Review by Plip-Plop — APPROVED** [review]

**Comment by Pointedstick** [comment]
Very nice! But where are the Carrier and Auxiliary?

**Comment by dragonmaus** [comment]
> Very nice! But where are the Carrier and Auxiliary?

Gefüllte doesn't want to start on those because university is starting next week ([link](https://discord.com/channels/251118043411775489/266345072554016768/893381252265152553)).

**Comment by Pointedstick** [comment]
I can understand that, but it would seem a but weird for most but not all Navy ships to get updated graphics. We'd have two Navy ships that look oddly different from the other ones using the new style. Do we have an ETA for when the Carrier and Auxiliary graphics can be completed?

**Comment by dragonmaus** [comment]
Gefüllte's response:
> i cant really tell rn
> next week i might have some time, ill see
> the two weeks after that im pretty busy i believe
> and november im gonna be at uni pretty much for the whole day
> then theres also the weekends so
> i wanna for now just get comfortable with the situation and then well see

([link](https://discord.com/channels/251118043411775489/266345072554016768/893959076512432198))

**Comment by Zitchas** [comment]
I'm not too concerned about Navy ships having different "looks" to them, for two reasons.

a) It's really unusual for a navy's entire fleet to be designed and manufactured at the same time in the same shipyard.

b) The potential change for the carrier & auxilliary I don't anticipate being too major.

Actually, I'd honestly kind of like to use the current cruiser for the cruiser in use at the start of the game, and then this new cruiser for the Mark II and any subsequent cruisers. Taking advantage of this to add in a slight graphic change with the mark II change would add some additional variety to the game, and be a good thing.

**Comment by Zitchas** [comment]
The new carrier looks great except for two things:
1) it is flatter.
2) the shape of the bays are more square.

Number 1 is mainly referring to the fact that the redesign's bay arms, and how they are all closer to being horizontal than the old ones. The front pair is particularly noticeable. From a design perspective, having one set of arms with a strong downward angle while the rear ones have a strong upward angle is helpful in keeping the approach/launch paths clear, which is a safety thing. From an aesthetic side, I think it just looks better to have the stronger slant, especially on the front.

For number 2, just the old bays had a more octagonal feel to them. I like the less-square feel to it, but that's a minor thing and not particularly important.

**Comment by MasterOfGrey** [comment]
Mentioned this to them on Discord too, but for the record the Cruiser still suffers from hangars bedded into the central column so that the structural spine of the ship runs through what is obviously open hangar space. (Or at least predominantly open space.)
The new one looks better, but I think it still has that problem.

**Comment by Zitchas** [comment]
Looks pretty good!

**Comment by Pointedstick** [comment]
Looks great to me. Don't see a reason to delay any further, let's merge!

**Comment by Amazinite** [comment]
I guess self assigning and self requesting reviews mean jack shit then.

**Comment by Pointedstick** [comment]
Delaying clearly mergeable PRs like this turns off contributors and ultimately kills a project under the weight of excessive bureaucracy. It encourages exhaustion among the maintainers and hostile forks.

I've made this point before but clearly it's not shared by ES's maintainers, and I don't have the spare time to argue about it anymore. Fighting with you makes contributing feels like a job, and I've already got one of those. I'm going to unsubscribe and leave Endless Sky for the time being, and let it be a game for me again.

If I'm wrong and your leadership style is good for the project (which is quite possible, I'm usually wrong more than I'm right), then I will be happy to see Endless Sky continue to grow and prosper. Bye bye for now.

**Comment by Amazinite** [comment]
@Pointedstick I understand the sentiment, and I haven't said anything about plenty of other PRs that you've merged, I just feel like it's rude to merge something when I've assigned it to myself or self requested a review and haven't gotten to it yet. And I must admit that I have some heavy stuff going on in my life right now so I'm sorry for taking some of my stress out on you here as I was rather harsh, but if you're still going to take a break from things then I won't stop you.

**Pull request merged**
