### PR TITLE
Merge 0.9.13

### PR DESCRIPTION
**Pull request by tehhowch**
To be merged after 0.9.12 is released to the non-beta Steam channel and there are no reports of critical issues that must be hotfixed.

### CODE REVIEW

**Comment by Zitchas** [comment]
Fun list of additions. :)

**Comment by Zitchas** [comment]
So, is there a timeline for this being merged? I'm starting on the Remnant Ship steering flares, and wondering when it'll be in master as opposed to this branch.

**Comment by Amazinite** [comment]
> To be merged after 0.9.12 is released to the non-beta Steam channel and there are no reports of critical issues that must be hotfixed.

**Comment by Zitchas** [comment]
Ah, right. I somehow missed the last half of that sentence.

**Comment by MasterOfGrey** [comment]
So uhhh, isn't this good to go? What're we still waiting for?

**Comment by MCOfficer** [comment]
Bump. 2 weeks since 0.9.12 is stable, and no critical reports yet. If we don't do it know, will we ever?

**Pull request merged**
