### PR TITLE
Added running lights to most human ships

### PR DESCRIPTION
**Pull request by jafdy**
Excluded are: Marauders ~~(no blend or gimp files)~~ (will be done with a separate PR)
~~Pointed's vanguard (no gimp file) Wrzl has handed me the file so I will add that soon.~~
and Surveillance drone (couldn't think of anything good)
and the shuttle as it was done already.

I have @2x images.

### CODE REVIEW

**Comment by tehhowch** [comment]
Looks like at least one sprite has an oddity in the outline
image
Not sure which others have this yet

**Comment by tehhowch** [comment]
Finches are not right either:
image

**Comment by jafdy** [comment]
I was meaning to mention that, for some reason all of local god's fighters do that strange white box thing. I don't have any idea why.

**Comment by Bladewood** [comment]
Why most of them?

**Comment by tehhowch** [comment]
No funky dreadnought outline, and no strange white boxes :+1: 

The only complaint I can voice now is that the current lighting method makes them and all your hard work difficult to see without zooming in. Unfortunately that's a symptom of a bigger issue and will happen to all lighting effects when the ship is "pre-lit".

>Why most of them?

I'm guessing it's a lot of work :1st_place_medal:

**Comment by jafdy** [comment]
@Bladewood I explained the most bit in the OP.
@tehhowch Bother.

**Comment by tehhowch** [comment]
I know it isn't easy, but i think many of these (especially the ones mounted near "bright" areas on the ships) could benefit from being brighter than they are, and also being a slightly bluish or reddish light rather than white. The ones mounted in already-bright areas are almost impossible for me to see, and only the ones mounted in dark areas can be easily noticed. E.g. the Raven's lights are great due to the extra bounce they get from the wing angle, and the natural darkness of the area they are positioned in.

**Comment by jafdy** [comment]
I have noticed it is much worse on the navy ships, I can only see about half the lights on them and I know where they are! Adding a redder tinge could work where the area they are located in is already white although blue can't work because of the swizzling system. (Blue Aerie look really good.)

I don't have any control over how the lights go on and off. Having a bit more input without needing to add extra frames to the file would be good. (To have the lights fade to off before fading the next set on would require an extra frame between every set of lights.)

**Comment by Bladewood** [comment]
My question was not about why this pull excludes a small selection of ships, but rather why it includes almost all of the human ships.

**Comment by Amazinite** [comment]
I think a better question would be "why not?"

**Comment by Bladewood** [comment]
Reasonable.

**Comment by Pointedstick** [comment]
Vanguard assets: [Vanguard heavy warship.zip](https://github.com/endless-sky/endless-sky/files/1140636/Vanguard.heavy.warship.zip)

Where do I stick this so that people always have access to it?

**Comment by Amazinite** [comment]
Just wait for @endless-sky to pick it up and put it in the [assets folder](https://drive.google.com/drive/folders/0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk).

**Comment by jafdy** [comment]
@Pointedstick I have the assets for the normal Vanguard, I don't have all the assets for the version that Wrzl made for your in-game person.

**Comment by KiLEdEnNis** [comment]
I kinda liked the whitebox Finches...

**Comment by Pointedstick** [comment]
@jafdy 
Oh, I don't have that one myself. Maybe contact @Wrzlprnft?

**Comment by jafdy** [comment]
He's taking a long break and I don't want to disturb him even though he dose have all the Marauder files as well.

**Comment by MessyMix** [comment]
@jafdy he's never coming back to discord or steam, or maybe even github. But I think he'd gladly provide the marauder files—I can try and get them for you, if you'd like.

**Comment by jafdy** [comment]
Really? That's a shame, if you could get them that would be great.

**Comment by MessyMix** [comment]
@jafdy https://www.dropbox.com/sh/w603cb3he0ilfl2/AABrIVaPW3YUtvE1AX_baguKa?dl=0

there are a lot of ships that aren't marauder variants in game as well in there, as I think that's all of wrzl's modified ships, so you might have to do some sorting, but it should be comprehensive :)

**Comment by jafdy** [comment]
Thanks, I'll get those worked into a separate PR once this one is done.

**Comment by endless-sky** [comment]
With the shuttle, I found that the only way the light effects were visible at all was if I gave them a high frame rate combined with a high delay, so that the lights are flashing rather than slowly fading in and out. I'd recommend keeping the "frame time" to around 3-6 steps and the "delay" longer than the total duration of the rest of the animation.

**Comment by jafdy** [comment]
Would it be hard to have them change from one frame to the next without the fading?

**Comment by jafdy** [comment]
After 4 days of trying different stuff I have a potential solution to the lights just not being visible.

**Comment by tehhowch** [comment]
I'm still not seeing much of a difference, if any, on the cruiser and carrier images.

**Comment by jafdy** [comment]
The lights on the well lit sections of the ships are now in red not white. For the cruiser it is the last image only that was changed and for the carrier it was the last 2 images i think.

**Comment by tehhowch** [comment]
Ah, the red lights are getting swizzled. Are you using the frame rate constructs mentioned above? I can see the carrier's lights if i order one to hold position, and then stop next to it, but any kind of relative motion and the lights are imperceptible.
greenlights

**Comment by jafdy** [comment]
I haven't shifted the frame rates yet, I want to get a better set of images ready first.

**Comment by tehhowch** [comment]
Lights are better with the new framerate (and not sync'd up :+1: ). I was looking with the game's default zoom. Still an issue with swizzled lights for player ships (light green and background white/grey are pretty hard to distinguish)
Quicksilver's forward side lights may be just a bit too similar to the local Quicksilver hull. May be more, as I didn't inspect them all.

**Comment by jafdy** [comment]
The only way to avoid the lights swizzling is to have them white, and on a white surface a white light won't show up. With out a complete lighting overhaul (another issue) I don't see a way round this.

**Comment by tehhowch** [comment]
Blue tints get swizzled too? I know red and orange definitely do

**Comment by KiLEdEnNis** [comment]
all non-grey tints get colored (the more black, grey or white the less you notice it)
some swizzles don't really touch a certain color but yes

**Comment by jafdy** [comment]
@endless-sky I think this is about as good as I can get without doing something drastic. All I can do now is change between white and red lights and fiddle some numbers. 
I have 2 (not exclusive) ways I could make this better.

1. Increase the power of the lights dramatically so they will light up large sections of the ship, this will fall apart a little at high zooms because the lights will have no visible source.
2. Switch to cycles render and have lit objects, they will be bigger and more obvious, but risk looking a bit tacky. 
3. A compromise between both other solutions, this should be able to avoid looking too odd if done right but will take quite a lot of time to do right.

@endless-sky I don't want to start the large amount of work required for any of these with out your opinion as all 3 of these solutions will be a noticeable change in ship graphics.

**Comment by jafdy** [comment]
v1
This is option 1.

**Comment by MessyMix** [comment]
Oops. If #3002 becomes a real thing (and not just a plugin), looks like you have more work on your hands if you want to make this a real thing 😕

**Comment by Pointedstick** [comment]
Yep. That said, the running lights would look even better if most ships were darker and more shadowed.

**Comment by tehhowch** [comment]
They'd be fantastic and not require multiple rendered frames if we support
a "lamp layer" and dynamic shadowing :)

**Comment by jafdy** [comment]
The new angle will help but I don't get any change in the file size and the lack of communication from MZ is starting to get on my nerves.

**Comment by endless-sky** [comment]
I don't think these images are actual premultiplied alpha. I'm seeing weird (subtle) sparkly effects along the edge of the sprite when rotating it, and the glows aren't extending out beyond the edge of the ships.

**Comment by jafdy** [comment]
They're not, my attempts to do that resulted in those white boxes. I also found that with more complex shapes the shadows cast from the render would look great on a single ship.
The sparkle probably comes from where I had to put the alpha back in by hand on some ships. I think it's safe to say I don't have a firm grip on GIMP yet.

**Comment by endless-sky** [comment]
Closing because this is outdated due to the new "dark ships" sprites, and because for running lights to really look good they'd have to use additive blending the way the shuttle lights do. (Note that for the shuttle, the model was also re-rendered with the area near each light illuminated, to further add to the realism.)

**Comment by jafdy** [comment]
The tool you made makes no sense to me and all that white boxing stuff was caused by trying to add lights in gimp (I have no idea why it wasn't masking it). It needs a command line I think, I'm not great with cmd. 
I agree that this doesn't work with the new ship sprites but I don't know if you want it redone or not.

**Pull request closed without merging**
