### PR TITLE
Higher precision CargoHold Free() and Used() reporting

### PR DESCRIPTION
**Pull request by warp-core**
**Bugfix:** This PR addresses issue #7951 

## Fix Details
`CargoHold` reports its various properties (size, used, free, commodities size, outfits size, and mission cargo size) as integers, but some of these quantities can take non-integer values, specifically outfits size, used, and free.

Round 2: this PR adds new methods corresponding to those quantities which can benefit from greater precision: `FreePrecise()`, `UsedPrecise()`, and `OutfitsSizePrecise()` which provide the values as doubles and makes use of `FreePrecise()` in place of `Free()` when determining if an outfit can be bought into cargo. Nothing else is changed.

~~This PR ensures these values are reported as `double`s instead of `int`s.~~

This should fix the linked issue because it means free cargo space values below 1 should no longer be truncated to 0.

~~Edit: it looks like the number of tonnes occupied by the outfits was deliberately being rounded up, I'm assuming this was just so it didn't get truncated and the CargoHold appear to have more free space than it actually does. Hopefully, changing this doesn't cause issues anywhere else.~~

~~Edit 2: Oh dear.~~

## Testing Done
None yet.

## Save File
This save file can be used to verify the bugfix. The bug will occur when using {{insert commit hash / version}}, and will not occur when using this branch's build.
[ProvidedByZitchasIn7951.txt](https://github.com/endless-sky/endless-sky/files/10310260/Rebbia.Rampart.3024-01-07.Loading.up.Keystones.txt)

### CODE REVIEW

**Comment by Zitchas** [comment]
Is it possible to split up the value displayed and the actual value the game uses to determine free space? The game displaying "0 space left" is fine, but it really should still know that it actually has 0.9 space left

**Comment by Hurleveur** [comment]
I think it's best to not ask reviews when a PR is in a draft state
If help is needed it can be found in the hub or by ppl looking at it

**Comment by quyykk** [comment]
This will introduce some floating point bugs :pensive: probably worth it?

**Comment by warp-core** [comment]
> This will introduce some floating point bugs 😔 probably worth it?

They can't be that bad, can they?

We could multiply the value by 1000 in OutfitsSizePrecise() before rounding it up and returning it, use correspondingly scaled up values for commodities and mission cargo in UsedPrecise(), multiply size by 1000 in FreePrecise() and then divide the value by 1000 before comparing in OutfitterPanel (or, multiply the mass of the outfit being bought by 1000)?

**Comment by Hecter94** [comment]
> I think it's best to not ask reviews when a PR is in a draft state If help is needed it can be found in the hub or by ppl looking at it

Agreed on this. Best to not ask for reviews until the PR has been marked as "ready to review", for reasons I hope are obvious.

**Pull request merged**
