### PR TITLE
Added Railgun!

### PR DESCRIPTION
**Pull request by Gkramme**
I addded a very powerful new weapon. However, I still need a firing sound, sprite, thumbnail, sound, and a hit sound. Please tell me if I need to balance this!

### CODE REVIEW

**Comment by Pointedstick** [comment]
In such a basic, unbalanced, underdeveloped form, this would probably be better as a work-in-progress plugin than an addition to the basic game. During that time, it can undergo revisions to be balanced, have art assets added, and get integrated with the storyline and game world. After that, a merge request would seem more appropriate.

**Comment by lehgogh** [comment]
This does seem a bit overpowered, though it would be a good mod for those that already have a lot of money. Also, don't make this into a turret.

**Comment by Gkramme** [comment]
@Pointedstick, if this is available or part of the navy during the storyline, it would be way to op. This is made to be a very rare weapon found occaisonly on a carrier or a cruiser.

**Comment by LocalGod79** [comment]
if this is supposed to be a rare outfit on a character ship, why will it be available at "Deep Sky Advanced" outfitters?  and where are the sprite, sound and hit effect?

**Comment by toilethinges** [comment]
Also, it says "enormous price tag," 550k isn't necessarily an enormous amount of money.

**Comment by endless-sky** [comment]
This doesn't look ready for merging yet. If you want to suggest new outfits, the best way is to probably share a plugin through the forums, until you've got something that's polished and well-tested.

Also, adding new outfits in human space is a pain because the existing human ships need new variants added that make use of that new outfit.

**Pull request closed without merging**
