### PR TITLE
Complete solar system

### PR DESCRIPTION
**Pull request by beccabunny**
**Content (Artwork / Missions / Jobs)**

## Summary
This PR heavily changes the system Sol, giving every planet and moon (except saturn, of which I could not make a good alternative) a new sprite made using NASA or ESA pictures, and adds all the missing planets, many moons and 2 dwarf planets I kept the new planets separate in order to not override the planets outside of Sol and increase variety at the same time. I expect the number of stuff added to be reduced before merging, but I preferred to PR the whole set before deciding. Here https://github.com/beccabunny/Realistic-Solar-System I have a plugin that does the same thing but also changes the size of the of the system and of all the objects in Sol to be more realistic and detailed.
Screenshot (52)
*Earth and its moon, Luna.*
Screenshot (53)
*Jupiter and one of its four moons.*
Screenshot (54)
*Four of the eight moons of Saturn.*
Screenshot (55)
*Pluto and its moon, Charon.*

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/file/d/1BUn4hTBzV8_MRA9A2KoGnlLBuNjqNiaY/view?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/134

### CODE REVIEW

**Comment by Zireael07** [comment]
Considering those sprites are under CC-BY, could I use them in my own space game? I have been long looking for sprites for Uranus and Neptune moons, for instance...

**Comment by beccabunny** [comment]
Of course, those have been edited from the NASA pictures made by Voyager 2

**Comment by W1zrad** [comment]
Are you maybe missing the file for "earth-new" in this PR? I couldn't locate it in Files Changed, and it doesn't display in-game. If it's just me, then I apologize.
Besides that, I play tested and everything looks just fine. While it's cool to see the planets at a distance from each other that is much closer to real life, the distance does feel sort of unusually far when compared to most other systems in-game. Just something to keep in mind.

**Comment by beccabunny** [comment]
> Are you maybe missing the file for "earth-new" in this PR? I couldn't locate it in Files Changed, and it doesn't display in-game. 
Whoops! I somehow forgot it, added both here and in high DPI, thank you.

**Comment by Zitchas** [comment]
I like the concept of this. Especially if we eventually actually create stations/spaceports on one or more of those planets.

**Comment by beccabunny** [comment]
Added the right period to all the objects in the solar systems, including moons and dwarf planets

**Comment by Pointedstick** [comment]
FWIW I prefer this shadow/lighting style over the existing one, which I find to be much too dark and obscures the beauty of the planet. I think we could benefit from moving towards this brighter style overall.

I suppose that's a thing we should figure out first. :)

**Comment by beccabunny** [comment]
I don't think I'll be able to fix this in the near future, closing it for now.

**Pull request closed without merging**
