### PR TITLE
feat(testing): Split source code into libraries with their own sub-directories

### PR DESCRIPTION
**Pull request by petervdmeer**
**Feature:** This PR implements the separate libraries as suggested in #7031

## Feature Details
This PR performs an initial split as suggested in #7031 and as described in the [README.md](https://github.com/petervdmeer/endless-sky/tree/split_sourcecode/source) file that is part of this PR.
We will need to still make a lot of code-changes to completely finalize the split (like the changes done in #6502); currently there are a lot of classes in runtime that should be split into templates and into runtime classes.

Splitting into separate libraries should help with future splitting efforts, to ensure that only dependencies exist in the direction where we allow them.

We might also need to split the platform layer, since the templates might still need some platform code as well. But I'm not sure exactly on what is best there. As with any other code-change; relevant thoughts and review comments are always very welcome. Pull-requests to make this PR more complete (e.g. fixes for compile-frameworks that I didn't fix yet) are also very welcome.

This PR looks big, but it only moves code around. Any non-trivial code-changes that helps the splitting and that can be done in a separate PR, should be done in a separate PR (and possibly merged ahead of this PR).

## UI Screenshots
N/A

## Usage Examples
Just write code as done before, but when creating new files, then do consider in which of the libraries the code should land.

## Testing Done
So far I only compiled this with SCons (and I didn't update the other compile-frameworks and unit-tests yet), so the CI-tests will fail on initial upload.
This PR only moves code around; so checking if this compiles on all platforms, and running the automated tests, should be all that is needed.

## Performance Impact
No performance impact is expected (LTO will likely still work as well).

### CODE REVIEW

**Comment by EjoThims** [comment]
I'll admit this comes from a place of pure ignorance, but would you mind spelling out what the benefits of this would be for me, please?

**Comment by petervdmeer** [comment]
> I'll admit this comes from a place of pure ignorance, but would you mind spelling out what the benefits of this would be for me, please?

Sure, no problem. Good remark!
The benefits of the "templates" library is re-use by external programs (world editors, parsers, testers, etc), as [suggested by tehhowch on PR 6240](https://github.com/endless-sky/endless-sky/pull/6204#pullrequestreview-735453664) and [on PR 6502](https://github.com/endless-sky/endless-sky/pull/6502#pullrequestreview-860248005).

Keeping the "templates" and the "runtime" in a separate library allows us to easily check if there are no illegal dependencies from "template" to "runtime", because such a dependency would just not build after this PR because the includes don't work in the direction from "template" to "runtime".

The benefits of the "platform" library is that after we move all platform-specific code to this library, then we should be able to easily mock (provide fake inputs/outputs) of the platform I/O (Input/Output) for the "runtime" library during unit-testing, which should make the "runtime" library more easy to (unit)test.
We should even be able to get the point where we don't need LTO (Link Time Optimization) for unit-testing, as [also worked on by Quyyk in in Issue 6238](https://github.com/endless-sky/endless-sky/pull/6238) and as [requested by me in Issue 7031](https://github.com/endless-sky/endless-sky/issues/7031)). Removing the need for LTO from unit-testing should allow debug-builds to also run unit-tests and should remove some unpredictability in what can be unit-tested and what not.

Having a "foundation" library helps to allow all those other libraries to know about some common data-structures shared throughout the game. The "foundation" library classes can be used on interfaces between the other libraries.

I hope this makes the purpose of this PR a little bit more clear.

**Comment by Amazinite** [comment]
I think this would be a good topic to discuss between you, tehhowch, and quyykk on how to best divvy up the source files into folders, and then simply make the change without having a PR like this sit for too long, as that just means that this PR will keep stacking up merge conflicts as we merge code changes elsewhere. So while I won't close this PR, I'd say it might be better off closed and then you can make the change later once you guys are in agreement. Either that or just keep this open and fix all the conflicts once an agreement is reached.

**Comment by petervdmeer** [comment]
Yes, tehhowch, quyykk and me should align on this topic, and agree on the steps (and PRs) to get there. I don't expect this single PR to immediately fix everything; some files will still need to be split and moved later, after this PR gets merged. We might not even use the 4 libraries on all platforms after this PR (some might just compile the 4 libraries into 1 single one for a while longer, as is done today).

The merge-conflicts look worse than they actually are; most are about files that are being moved; but with the files themselves not having any content changes. Performing a git-merge from master into the branch (on my laptop) automatically resolved all conflicts. This is also the major reason why I try to keep the file-moves and the file-changes in separate PRs.

I do agree with you that we should handle this PR swiftly. And my time is also a little bit limited at the moment, which conflicts with handling this PR swiftly.

**Comment by petervdmeer** [comment]
Closing this PR; I still feel that this change is a good change, but making a change like this is easier after we have migrated all platforms to a single CMake build.
Using CMake we might even be able to perform the initial split without needing to move any files around.

**Pull request closed without merging**
