### PR TITLE
Update map.txt

### PR DESCRIPTION
**Pull request by natangold**
As home to every world religion prior to 2080, added the "religious" attribute to Earth.

### CODE REVIEW

**Comment by Gkramme** [comment]
What does the "religous" attribute do?

**Comment by natangold** [comment]
AFAICT, nothing yet; it is applied to New Tibet and Harmony (the monk-y planets). In a separate pull request (because I still haven't figure out how GitHub works) I added a set of pilgrimage jobs (transporting people to and from these two/three planets) that make use of the religious attribute.

**Comment by Gkramme** [comment]
Ah, I see. Now I connect the two. But does that mean you cannot demand tribute from Earth?

**Comment by natangold** [comment]
Dammit, I guess it does. So I guess that's what the religious attribute does? Make it so that the monks on New Tibet are utterly fearless and you can never demand tribute from them? Poop. Closing both pulls for now.

**Comment by natangold** [comment]
Triple check proved "religious" doesn't affect tribute behavior. (First tested by demanding tribute from Harmony. They ignored it. Closed the pulled, then retested by making Trinket religious, because that's where my ship happened to be. Trinket fought.) The reason those bloody monks never give up is because they have no tribute and/or defense fleet programmed. A religious Earth will still fight.

**Comment by endless-sky** [comment]
The "religious" tag was really just meant to apply to planets where the primary colony is a religious one (currently, just Harmony and New Tibet).

For your "pilgrimage" missions it might make more sense just to hard-code a list of destinations, instead.

**Pull request closed without merging**
