### PR TITLE
Added velocity and range overrides

### PR DESCRIPTION
**Pull request by Amazinite**
Ref: #4478, #1894

`"range override"`: A manual range override. This will be what shows up in the outfitter for a weapon's range. **Effects when the AI fires the weapon versus how far the target is.** Also used to calculate a weapon's lifetime for the AI, estimating it with `range override / velocity` if range override is present. Otherwise the normal lifetime is used.
`"velocity override"`: A manual velocity override. This will help to change where the AI points the ship when firing. The main and only use of this that I could think of and tested was in using weapons with submunitions that had their own velocity, as currently the game does not take in to account any changes in velocity caused by submunitions. **The higher the velocity override, the straighter the aim.** I assume that this could also be used for weapons that have drag and acceleration that drastically alter the true velocity of a projectile after it is fired; if the projectile increases in speed, then give it a higher optimal velocity than the normal velocity. If the speed decreases, then do the opposite. **Note that AI.cpp adds half of the random velocity to a weapon's velocity when calculating where to aim.** Just keep that in mind if you're changing velocity override because of a random velocity.

Note: **This PR does not improve the accuracy of the existing range/velocity equations. It only provides manual overrides to produce different AI behavior.**

@Bladewood I'd like to see if this works for your weapons that needed these, as these few changes alone were all I needed to get my weapons to work that I mentioned all the way back in #1826.

### CODE REVIEW

**Comment by Amazinite** [comment]
Cases that I tested:

This energy shotgun. `"optimal range"` is used to make it so that the weapon will only fire once the target is close enough that most of the projectiles will hit, and `"optimal velocity"` is used because of how the submunition increases the velocity over the base projectile.
```
outfit "Energy Blaster"
	category "Guns"
	cost 16000
	thumbnail "outfit/blaster"
	"mass" 5
	"outfit space" -5
	"weapon capacity" -5
	"gun ports" -1
	weapon
		sprite "projectile/blaster"
		sound "blaster"
		"hit effect" "blaster impact"
		"inaccuracy" 1
		"reload" 12
		"optimal velocity" 10.625
		"optimal range" 250
		"firing energy" 9.6
		"firing heat" 30
		submunition "Energy Blast" 12
	description "Although not the most accurate or damaging of weapons, the Energy Blaster is popular because it is small enough to be installed on even the tiniest of ships. One blaster is not enough to do appreciable damage to anything larger than a fighter, but a ship equipped with several of them becomes a force to be reckoned with."

outfit "Energy Blast"
	weapon
		sprite "projectile/blaster"
		"hit effect" "blaster impact"
		"inaccuracy" 15
		"lifetime" 48
		"velocity" 10.625
		"shield damage" 9.6
		"hull damage" 6
```

I also tested an Electron Beam that I gave an optimal range of 100, firing alongside a Beam Laser with no changes. As expected, the Electron Beam would only auto fire when at 1/3rd the range of the Beam Laser.

**Comment by Zitchas** [comment]
As the `range override` was suggested to be used for the #4977 PR, is this something that is likely to get merged in the near future? I note that it used to have the 0.9.11 milestone, but currently doesn't have one.

I don't think it is crucial - we can adapt to other ways of limiting range for now. But if it is going to get merged in the next week or two then we might as well just wait for it.

**Comment by Amazinite** [comment]
@Zitchas Recently GitHub added the ability to turn PRs into drafts after they've already been open. I recently went through all my PRs and turned some of them into drafts if they still need worked on. Everything else is likely to merge shortly after v0.9.12 (this PR included).

**Comment by Zitchas** [comment]
OK, thanks for the insight. That will be helpful.

**Pull request merged**
