### PR TITLE
Standardize engine flare sprite location

### LINKED ISSUE #2478: Put Coalition and Remnant engine flares in their own folders
note: I can kind of understand the Coalition flares not having their own folder (too few sprites), but there are about as many Remnant flare sprites as there are atomic or ion flare sprites.

### PR DESCRIPTION
**Pull request by tehhowch**
All engine flares now reside in subfolders indicating the technology used to generate the flare, or the race responsible for the flare (e.g. the player doesn't know/understand the technology enough to characterize its origin).
Closes #2478

### CODE REVIEW

**Comment by Elyssaen** [comment]
If these are going in sub-folders, should their names be shortened as with the others? The files in the 'atomic flare' folder are just called tiny, small, medium, huge, rather than 'atomic tiny flare', etc.

**Comment by tehhowch** [comment]
Yes, that is a definite possibility, and a logical next step if subfolders are to be used as an organizational strategy

**Comment by jafdy** [comment]
If you shortened the names like that then the game would be unable to call the correct sprite unless a source code change was implemented, that would then require more knowledge of the pathing to be able to mod the game.

**Comment by Elyssaen** [comment]
Could you explain that a little further, @jafdy?

large+0.png is in effect/plasma flare, effect/korath flare, effect/ion flare, effect/atomic flare and effect/explosion. The game has no problem calling the correct sprite of these: how come it'd need a source code change to call effect/remnant flare/large+0.png?

**Comment by jafdy** [comment]
That was my argument earlier. I seem to have forgotten that it was changed already.

**Comment by tehhowch** [comment]
Addressed the long names, but left the quarg thruster alone as both graviton and medium may be desirable differentiating characteristics when the quarg are next updated. Thruster too, perhaps. :+1:

**Comment by Lineth** [comment]
Why close this? Anything that makes the data files more organized is a plus.

**Comment by tehhowch** [comment]
I have plenty of other pulls that I would rather have MZ spend time looking at and approving, and that do more for the game than shuffling some files into folders, but sure, ok.

**Comment by endless-sky** [comment]
The "quarg flare" should probably just be "effect/graviton flare/medium". (Or better yet, just leave that one unchanged, because there's only one sprite and it's really a placeholder until Quarg tech is fleshed out more.)

**Comment by tehhowch** [comment]
Addressed

**Pull request merged**
