### PR TITLE
Civilian Phrase: Bands

### PR DESCRIPTION
**Pull request by Wrzlprnft**
Original Title: Added a civilian phrase...
...referring to 'There Might Be Riots'.

Edit: It is nothing sophisticated, @endless-sky, you may expand or change it as you like.

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm a bit worried about 10% of civilian hails suddenly being comments about that particular band - it seems like they'd be a minor enough part of the galaxy that people wouldn't be talking about them that much.

Better might be if you invented a dozen different band names and had civilians talk about random ones of those, so it's not like this one band is absurdly popular. (I mean, they have a loyal following, but they're probably still on the fringe of the music scene.)

**Comment by Wrzlprnft** [comment]
I haven't thought of that. Is there a way to prevent bands and titles to be mixed up except putting the title-word and the band-name-word together into one word?

**Comment by LocalGod79** [comment]
you could create phrases for each band, so that the civilian phrase cascades through them appropriately...

**Comment by Wrzlprnft** [comment]
Now, that was hijacked. But anyway, i can always add the stuff i have. I was thinking about some other fictional bands, given the time that has passed.

**Comment by LocalGod79** [comment]
sorry - just wanted to put together a couple to make examples of how it could be done - it's all you...

**Comment by Wrzlprnft** [comment]
I don't mind cooperation. And thx for the examplestructure

**Comment by LocalGod79** [comment]
i considered while adding the extra songs/bands, that this might be an opportunity for the community to add a couple of their own favourite songs to the phrasing, and give our eventual music composer a cross-section of the styles our current players are listening to...

**Comment by Wrzlprnft** [comment]
I used @LocalGod79 's structure and added 4 fictional bands with 5 songs each, additional to 'There might be Riots". I think i can extend the amount if needed. Also, i suggest that @endless-sky adds 3 more songs of TMBR so every band has the same amount.

**Comment by endless-sky** [comment]
I'm trying to think how it could be made more obvious to the player that these are fictional bands in the Endless Sky world, the same as the "null-ball" teams. Maybe that could be done by including planet and place names, something like: Last month I heard | "There Might Be Riots" | at their concert | at the amphitheater on Skymoot | , and now their songs are stuck in my head.

It would also work with "I just watched the video of", "I'm listening to", "I just heard", etc. and with "playing a concert", "doing a show", "live", "at a benefit concert", etc. Of course the downside is that it wouldn't include song names, but I worry that a random invented song name plus a random invented band name will just be too confusing for some people.

**Comment by Wrzlprnft** [comment]
Ill think over it a bit, maybe even a way to include song names. Is there a way to address random planets in phrases?

**Comment by endless-sky** [comment]
That would work! `(<I just heard> (<band> (<venue>). <song>) <was awesome>)`

Venue could be something like this:
```
phrase "musical venue"
	word
		"playing a concert"
		"doing a show"
		"in concert"
		"at their concert"
		"playing a benefit concert"
		"live"
		"on tour"
		"at a live concert"
		"playing a gig"
		"live in concert"
	word
		"at Tarazed stadium"
		"at the amphitheater on Skymoot"
		"at a concert hall in New Sydney"
		"in a night club on Splashdown"
		"at the Syndicated Systems Velodrome"
		"at Betelgeuse Stadium"
		"on Hestia"
		"at Lionheart Arena"
		"at the Grange on Heartland"
		"at a resort on Vail"
		"at Canyonland Park"
```

**Comment by Wrzlprnft** [comment]
Thanks :) ill add more bands and songs later today.

**Comment by Wrzlprnft** [comment]
I filled up the dozen for the bands, each with 5 songs, except "There might be riots". Additionally i added '   ' around bandnames and songnames.
I tried to keep consistent style, as well in the structure as in the songnames for a certain band

**Comment by Wrzlprnft** [comment]
I vote for the above commit to stay that way.

**Comment by LocalGod79** [comment]
i think that it's great - it's possible that 'Steam' is a 31st century narcotic...

**Comment by endless-sky** [comment]
Merged, and fixed a few things (20ca9a9).

**Comment by Wrzlprnft** [comment]
I am not entirely sure where that mistake came in...
Anyway, thanks.

**Pull request merged**
