### PR TITLE
Hai optical jammers

### PR DESCRIPTION
**Pull request by beccabunny**
**Content (Artwork / Missions / Jobs)**

Artwork for two new outfits by @MasterOfGrey and @Hurleveur - a Hai optical jammer, using the new functionality implemented by a recently opened PR, and its overclocked version used by the Unfettered. This PR doesn't add the two outfits themselves, just their sprites; their definitions will be in a separate PR probably made by hurl

Screnshot below: (the AM is the basic one, the bullfrog is the overclocked version. I'm wayyyy too lazy to make new outfits just for a screenshot)
image

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/109
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/331

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
Thx for doing this PR and the artwork themselves, they look amazing to me, especially the Unfettered version, it looks stunning!

**Review by GefullteTaubenbrust2 — APPROVED** [review]
Very cool, I like the effect you made. Looks hai enough for me as well.

**Comment by Zitchas** [comment]
While the outfit image itself looks amazing, the normal vs overclocked ones look identical, just the normal one looks like the entire image was faded out somewhat, and I don't think that looks very good.

I can see the logic - it's an optical scanner, the overclocked one is putting out more light. But I think there needs to be a little something to show that they are actually different outfits, and we're not just giving the Unfettered the ability to dial it up to 11 while the player isn't allowed to. For instance, having some extra and obviously-tacked-on cabling or conduits. Maybe have a panel or two obviously pried open with a cable running into it, or something like that.

**Comment by beccabunny** [comment]
Some changes
image

**Review by Saugia — APPROVED** [review]
Neato. Just be sure to get the other updated Hai outfits in sooner than later so there isn't a huge discrepancy in detail between outfits.

**Comment by beccabunny** [comment]
> Neato. Just be sure to get the other updated Hai outfits in sooner than later so there isn't a huge discrepancy in detail between outfits.

yep, I'm planning to have them ready for 0.9.17/.10.0/whatever is now the next version

**Pull request merged**
