### PR TITLE
Antares/Tomek typo fix

### PR DESCRIPTION
**Pull request by toilethinges**
Sys -> says.

### CODE REVIEW

**Comment by toilethinges** [comment]
Uhhh, I'm kind of new to this pull request thing... how can I create another new branch so that it doesn't show my previous pull request?

**Comment by endless-sky** [comment]
For a small change like this, the easiest thing to do is to edit [the file](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20start.txt) in the github web interface, and just save your changes as a pull request. (Click the pencil icon, make your changes, then select "Create a new branch and start a pull request...")

Or, when creating a branch, you just have to make sure that what you're branching from is the master branch, not a branch from your previous pull request.

**Comment by toilethinges** [comment]
@endless-sky Oh, I see. I'm sorry about that, and should I make another one using only that, or will this still work?

**Comment by endless-sky** [comment]
You should probably make a new PR, unless you can figure out how to merge this one with the master branch so that only your one new change shows up in the "Files changed" tab.

**Pull request closed without merging**
