### PR TITLE
Mystery Pug planet calls repair robots "insectoid" as well as "spider"--but spiders aren't insects

### PR DESCRIPTION
**Pull request by Pointedstick**
not insects

Changed "insectoid" to "arachnoid", to be consistent with the later description that the robots are "spider robots".

### CODE REVIEW

**Comment by jafdy** [comment]
Is there and --oid version of arachnid? (arachnoid?)
Or you could have ant[-like] robots. ...slow-moving arachnid robots... doesn't have the same ring to it as ...slow-moving insectoid robots...

**Comment by Pointedstick** [comment]
Yeah, "arachnoid" is a word. I rather like the sound of that, actually.

**Comment by endless-sky** [comment]
The robots have seven legs and the player is having a hard time classifying them. :)

The real point of the description is that the robots sort of remind you of spiders or insects, not that they can be strictly classified into either category.

**Comment by Pointedstick** [comment]
That's cool too, but if so, the description should still be re-worked to make that more clear. Right now with both "insectoid" and "spider", it seems like a mistake.

**Comment by KiLEdEnNis** [comment]
changing spider robots to spider-like robots or something could help? (so change in a way that both insectoid and spider are used while it's clear they look like it, not that they are necessarily spiders

**Comment by Lineth** [comment]
"vaguely arachnoid"?

**Comment by KiLEdEnNis** [comment]
could do yes

**Comment by omagasohe** [comment]
Oh my goodness. The propensity for nit picking over grammar and word usage for this game is staggering. Slang, colloquialisms and vernacular are all very important points of communication. Spiders and other arachnids are usually grouped with other insects by the general public.

 Splitting hairs actually detracts from the over all quality of the game. It can make the experience feel artificial instead of natural. I personally don't see anything wrong with the above usage as long as thingy is added after the word robot.

"Spider robot thingy" is much more acceptable.

**Comment by KiLEdEnNis** [comment]
you want a game to be as good as possible, without people saying "hey, that's not right!", your point is just plain dumb

**Comment by Bladewood** [comment]
In a way, this game is kind of a novel. We should be a little formal here.

**Comment by KiLEdEnNis** [comment]
simply said; as if written by a professional that knows what (s)he is talking about, not an 8-year-old

**Pull request closed without merging**
