### PR TITLE
Hyperspace boosters

### PR DESCRIPTION
**Pull request by jafdy**
In effect this adds the "Hyperspace Boosters" mod to the main game.
I almost feel obliged after winning the contest.
~~The outfit sprites are different from Wrzl's original. With the @2x images Ill need to get in touch with @FallenCat for the purple one but I can PR the orange one quickly enough.~~

### CODE REVIEW

**Comment by Amazinite** [comment]
They could probably use different outfit images, since they just look like swizzled Sand Cells.

**Comment by jamespglaze** [comment]
I like it! As Amazinite said, they could use different outfit images, but I like the idea a lot!  Could see lots of use on cargo ships or when traveling through dangerous systems.

**Comment by jafdy** [comment]
They are swizzled sand cells. And yes they do need new sprites. I don't have any ideas at the moment, if someone comes up with something that would be great.

**Comment by jafdy** [comment]
@Wrzlprnft has just said he would make outfit sprites for this.

**Comment by retrue** [comment]
Do these boosters increase the comsuption of fuel like scram drives do?

**Comment by jafdy** [comment]
No, unless you put a scram booster with a hyperdrive (which I don't recommend).

**Comment by retrue** [comment]
Then, hyperdrive + booster will cost 80000 with a total weight of 28, not extra fuel needed versus scram drive that costs 90000 with a weight of 30.
So, what is the jump speed of hyperdrive + booster related with speed of scram drive?
Can you add more than one booster to a hyperdrive increasing jump speed?
Same questions about hyperdrive + scram booster and about scram drive + booster.
Brief, my doubt is, are these boosters well balanced in relation with hyperdrive and scram drive considering weight, jump speed, price and fuel comsuption?

**Comment by jafdy** [comment]
The hyperdrive + hyperdrive booster will allow you to jump with 50% more speed than normal. The scram drive allows any velocity along the jump vector but limited (same speed a hyperdrive) velocity along the perpendicular vector.

It is important remember that the hyperdrive booster is different from the scram drive booster. The hyperdrive + hyperdrive booster is simply a slightly faster hyperdrive. A hyperdrive + *scram* drive booster behaves like a scram drive with half the normal perpendicular movement and the 150 fuel cost.

You can theoretically add an infinite number of boosters but you will experience diminished returns.

In terms of cost each booster is just over half the price and just under half the mass of there respective drive, they can't replace a drive and are only useful on the matching drive. Used on mass they could allow a ship to jump at almost any speed but the numbers needed would be huge.

**Comment by LocalGod79** [comment]
i feel like this belongs as Smuggler's Den, rather than everywhere...

**Comment by jafdy** [comment]
My guess is it would be mostly used by merchants, they could trigger a jump at a higher speed making it easier to get away from pirates. It's a thing to think about.

**Comment by LocalGod79** [comment]
the Scram Enhancer probably belongs in the north/Syndicate (as the drives themselves are conspicuously absent in the south - even through shipyards)

lore-wise, Smuggler's Den needs some unique outfits/ships, and i feel like this is an area that M.Z. wanted the community to flesh out: the difference between Independent and Pirate Outfitter/Shipyards.

it's a bigger project than i had originally imagined (part of why i haven't already pulled it):
•a new pair of outfitters (Independent basics, Independent advanced - for the moment, perhaps the Pirate outfits minus Nerve Gas, add Hyperdrive Enhancer)
•adjustments to the events that convert Pirate worlds with Shipyards and Outfitters to use the new ones
•perhaps switching Trinket's to the Independent 'fitter...

there's more - that's just off the top of my head...

going forward, it would become a convenient destination for users to submit niche outfits...

**Comment by retrue** [comment]
@LocalGod79 I think that Smuggler's Den could sell the Marauder outfits (I mean the Ionic Afterburner and the small and large regenerators) later in the game, for example once the player has completed the Wanderer's campaign up to 0.92 or 0.93. At that point in the game the player can access better shield generators and getting the ionic afterburner plundering Marauder leviathan is more a chore than an incentive. These outfits could be for sale after some mission.

**Comment by LocalGod79** [comment]
Ionic Afterburners and S-X70 regenerators are unlocked through the checkmate arc and are owned by The Syndicate.

currently, the player has no incentive to choose diplomacy with the pirates over the Tomek's plan to attack Greenrock (other than perhaps a minor karma bonus).

Independent Outfitters and Shipyards would change that somewhat.

**Comment by jafdy** [comment]
The sprites are just place holders at the moment, @Wrzlprnft is working on better models (see above).

You could say that the experience in modifying stuff that was available at Smuggler's Den meant that the development went on there. I still want to be able to give them to merchants early on though.

**Comment by LocalGod79** [comment]
@jafdy missed that part (sprites), sorry.

with a little more thought, i figure:
• the Scram Buffers can probably be sold as a part of `Syndicate advanced` from the start
• the both Buffers could appear on some merchants (so belligerent players can still get a hold of them if they're willing to grind)
• Hyperdrive Buffer appears as a part of the "Independent outfitters project"

**Comment by Lineth** [comment]
Doesn't one of the Northern Pirate worlds have a similar description to Smuggler's Den? Something about selling customized ships? Thought it sounded like that world (and possibly Smuggler's Den) was supposed to sell Marauder ships.

**Comment by jafdy** [comment]
@LocalGod79 I like that plan, I'll get the outfiter part set up. Giving some merchants boosters will take a bit more work so I will start on it once I get the go-ahead from MZ.

**Comment by LocalGod79** [comment]
@Lineth Pirate worlds have a few ships and outfits that are not available anywhere else; the Gatling Gun, Nerve Gas, and the Modified Argosy to name a few.

Marauder ships were never intended to be sold at shipyards, rather to be available only through capture from the corresponding Bounty Hunting missions - the idea being that getting a `Marauder Leviathan (Engines)` (or any other desired variant) would be an accomplishment the player would feel proud about - not only because the ship was good, but because it took a lot of a different kind of effort to get (like the Kor automata, on a smaller/easier scale).

with that said, Haven and Buccaneer Bay have descriptions that imply ships other than the Modified Argosy can be purchased, and some of the lower tier Marauder ships may arrive in those 'yards eventually (ideally with some Pirate story)...

@jafdy i think perhaps an `Independent basics` and `Independent advanced` outfitters might be in order.

as mentioned (albeit briefly) earlier, it has always bothered me that Trinket, a respectable government controlled planet right from the beginning of the game, sells Nerve Gas (a highly illegal outfit)...also Bloodsea and Nunki, if the player pursues diplomatic options.

the `Independent basics` outfits would be a copy of the Pirate outfits, with the Nerve Gas removed, and would replace the Pirate outfitters on worlds converted to FW or Independent (not Neutral) in the events that change their government.

`Independent advanced` outfits would be available only at Smuggler's Den (after its government is Independent, rather than Neutral), and would contain community submitted niche-outfits (possibly also with the Government change.

**Comment by jafdy** [comment]
Sounds quite reasonable but I don't want to expand to far in a single pull. I would be fine with changing it to `Independent advanced` but I'm not going to change much else.

**Comment by LocalGod79** [comment]
or at least until @endless-sky weighs in...

**Comment by jafdy** [comment]
@Wrzlprnft has now finished the sprites. I'll put them in when I've got the size right.

**Comment by Wrzlprnft** [comment]
(i totally forgot about this)

**Comment by jafdy** [comment]
I am going to close this (and take the opportunity to re-fork my branch). I can re-PR this easily if it is wanted.

**Comment by Zitchas** [comment]
Why was this closed? Did it just stagnate and get abandoned?

**Pull request closed without merging**
