### PR TITLE
Make Nullifier a cluster firing weapon

### PR DESCRIPTION
**Pull request by 10010101001**
The Nullifier is used to disable a ship in one shot rather than doing damage. Making it cluster fire will make mounting multiple Nullifiers more useful against larger targets.

### CODE REVIEW

**Review by EjoThims — COMMENTED** [review]
I think is an appropriate change, but we should definitely get @beccabunny to weigh over as primary decider.

It may be best to also throw "parallel" in there as well.

**Review by beccabunny — APPROVED** [review]
Why not

**Comment by Zitchas** [comment]
When one gets right down to it, cluster vs stream firing munitions should be player-controlled, perhaps from the ship information screen. 

That being said, why should Ka'het want to shoot multiples simultaneously? They're already quite effective, and shooting a stream seems more controlled than a "fire all launchers at once, no matter how many" strategy. This change also means less control for the player, as it means that if they set up their ship for larger capacity to fire, they will always fire all of them when they might only need to fire one. It's a rather big loss of control.

I don't think giving up that control just so that someone can "one click fire" all their launchers at once is really a useful or beneficial change.

**Comment by vitalchip** [comment]
The only issue with giving players a choice is that many of them won't know how to choose.

Which is better, stream or cluster?

Well, if you have say two guns and fire them across several cycles the overall effect balances. That is to say the number of frames where the residual ionization is higher for streaming or clustering will be the same because the fire rate is doubled on stream but the instant hit power is doubled on cluster.

That's not the story though, cluster gives higher peaks and lower troughs of ionization, so depending on the actual energy generation, storage and consumption of any given ship.. which is better and how often do you know what you're about to shoot far enough in advance to really plan?

I think having a choice will allow people to make things look cooler, if they prefer two simultaneous bolts from either side of the ship to an alternating pattern but I doubt it would be a meaningful choice in respect of performance.

**Comment by Saugia** [comment]
Yes, I would prefer avoiding that stream vs cluster is made a "choice" because there are some concerns there regarding balance. Several weapons in-game intentionally use these tags to have variety to them and be different than other weapons, while other weapons use it as a means of balance. I don't think we should be adding "fire modes".

**Pull request merged**
