### PR TITLE
New Ionic turret prototype projectile

### PR DESCRIPTION
**Pull request by RisingLeaf**
**Content (Artwork)**

As requested by @Hurleveur 

>Just a small explanation: the idea is that the ionic turret prototype is more than a simple mounted turret version of the cannon. Therefore it's only fair it gets a bit of a special projectile to denote that.
The blaster prototype shoots purple bolts, with the idea of that color being associated to unstable and scrambling damage. In opposition to that, this weapon mostly does ion, so it is more "pure energy" in its look.

>I'm planning an eventual zapper police weapon, related to this in its appearance (this projectile here is between that weapon and the ion cannon) 

## Summary
Adds a unique projectile sprite for the ionic turret prototype.

## Screenshots
A comparison between ion cannon and ionic turret prototype. 

https://github.com/endless-sky/endless-sky/assets/85687254/7ee17dfe-1dfb-4e2f-980d-70a3fe31f330

## Testing Done
uh, yes?

## Save File
[t t.txt](https://github.com/endless-sky/endless-sky/files/13624131/t.t.txt)

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/154
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/388

### CODE REVIEW

**Review by Hurleveur — APPROVED** [review]
Thx for the good work!

Just a small explanation: the idea is that the ionic turret prototype is more than a simple mounted turret version of the cannon. Therefore it's only fair it gets a bit of a special projectile to denote that.
The blaster prototype shoots purple bolts, with the idea of that color being associated to unstable and scrambling damage. In opposition to that, this weapon mostly does ion, so it is more "pure energy" in its look.

I'm planning an eventual zapper police weapon, related to this in its appearance (this projectile here is between that weapon and the ion cannon)

**Comment by RisingLeaf** [comment]
added assets + 2x

**Review by Saugia — CHANGES_REQUESTED** [review]
image

Pulling it up in-game and playing with it, it definitely could be shrunk down a bit. A regular ion cannon weighs 46 tons, while this turret weighs 58 (so including the base). Since it's heavier overall, it makes sense to be a larger projectile than the regular ion one, but I think the size it currently is is too big and can be misleading to how strong it actually is in terms of its usage. I'd say to lower the size of it by at least 20%, maybe 30%.

Also - there's a render box around the projectile (see above). :)

**Comment by Hurleveur** [comment]
Actually it does fire 15% slower and after accounting for size it does roughly twice the ion damage (with no more scrambling) but it costs 2.5x the energy whilst losing dps (so its more 'incoherent' as the new sprite shows so well).
I don't disagree with it being a bit too big, but make no mistake this turret is much stronger than the ion cannon in terms of, well, ion.

I'm just curious, what do you mean by render box? Its probably something quite obvious for blender users, so sorry if its a bit of a stupid question - is it the residual blue in a rectangle around it? For some reason I cant click on the img to zoom in.

**Comment by Saugia** [comment]
You can see colors around the projectile itself showing the box around the sprite at what dimensions the projectile is at.

**Comment by RisingLeaf** [comment]
Resized to 70% because that were nice numbers again, I think I also fixed the render box, at least I was not able to see one

**Comment by Saugia** [comment]
Took another look at it. Size is good, but the box is still happening.
image

**Comment by RisingLeaf** [comment]
ok, just bear with me one more try.

I also added a hue shifted hit effect

**Review by Saugia — APPROVED** [review]

**Pull request merged**
