### PR TITLE
Remove Google Groups link

### PR DESCRIPTION
**Pull request by lumbar527**
**Content (Documentation)**

## Summary
This removes the Google Groups link in the feature-request template because it doesn't work, at least for newer people. Having the link there made me think it was another place to search, but it can't be accessed.

## Relevant Issues:
#5658, #6692, endless-sky/endless-sky.github.io#23

### CODE REVIEW

**Comment by quyykk** [comment]
This was some discussion on this previously here https://github.com/endless-sky/endless-sky/pull/8552#discussion_r1139106555

**Review by quyykk — APPROVED** [review]

**Review by TomGoodIdea — APPROVED** [review]
#8552 was a slightly different thing. Keeping the link there (with a comment about its status) had a reason, but here it can just cause additional confusion.

**Review by MasterOfGrey — APPROVED** [review]

**Comment by Zitchas** [comment]
While I strongly feel that the reference in the larger github documentation should be retained, I am ambivalent about the mention here. There is some value to reminding those who do have access to it that it does exist and is worth checking for things. It's a minor benefit countered by a minor negative, so in my view there isn't a strong case for or against having the mention here. Overall, probably slightly leaning toward being better to remove it here.

**Comment by lumbar527** [comment]
The alternative to removing it would be to add a note about how newer people usually can't access it.

**Comment by Zireael07** [comment]
If newer people can't access it, what's the point of having the link in the feature template?

**Comment by lumbar527** [comment]
[#8552 (comment)](https://github.com/endless-sky/endless-sky/pull/8552#discussion_r1139106555) This says some stuff about that, except it is more of a record in the README and not a place to search. It also seems that some people can access the Google Groups page, so maybe it should still be there, even though new people can't use it.

I do agree with @Zireael07, though.

**Pull request merged**
