### PR TITLE
Ka'het outfits refresh

### PR DESCRIPTION
**Pull request by beccabunny**
**Content (Artwork / Missions / Jobs)**

## Summary
A companion PR to... another thing, while creating the new outfits I've taken the opportunity of updating the relative ones which, while more recent than a lot other stuff, haven't aged very well compared to the other graphical updates. I've already updated the ka'het ships some time ago, so it was about time I did something to the worse outfits

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 ^ it's the same as before 😎
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/145
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/368

### CODE REVIEW

**Review by lumbar527 — APPROVED** [review]
They look a little bit cooler to me!

**Review by OcelotWalrus — APPROVED** [review]
The images look kind of better. I won't say it's necessary but it could be a good add-on to the game.

**Comment by Saugia** [comment]
@beccabunny Let me know when you push the other assets and I'll review it after.

**Review by OcelotWalrus — APPROVED** [review]
The new textures you recently added looks good and more detailed. I like that!

**Review by Saugia — COMMENTED** [review]
Looking at these, they all look pretty good. The extra detail helps bring them back into the realm of other outfits. Some small changes also look good, more notably the changes to the reserve accumulator from subdivided slits to an array of bars in the cylinders as well as the extra depth to the two horizontal rails on top.

image
One of my comments is on the addition of these "prongs" at the end of ravagers. I'm not so sure I dig them, they kind of come off as tips to antennae, or very small barrels. If the idea is the ravager is two guns stacked vertically, then I think they need to be larger in diameter, and if not, make them maybe a tad longer to give of the antennae/piping vibe. If neither, I don't think they help the design, more so causing confusion.

image
The other is the shield restorer. The design is quite a bit different, moving away from that more open area center to the elevated closed aperture. While I do like the new lined ramps up 4 corners, they seem to get blurry and lost in the image, so I'd recommend toning that down a bit/having less iterations there. I'm sort of missing that center hole and the raised surrounding structures outlining it on the original as well, but I suppose that's more a stylistic choice. Finally, each arm on it seems a lot thinner than the original, specifically the end plates. On the original, they scale upward towards the end, and on the new one, they do have a bit more detail but are more flat. I'd like to see those also accentuated a bit more again, as right now it's making the overall design look more flat and less unique.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
