### PR TITLE
Feature: Add support for conditional hiding of text or choices in conversations

### LINKED ISSUE #5439: Conditional conversation nodes
**Is your feature request related to a problem? Please describe.**

I'm working on a plugin with a very non-linear, highly interdependent mission tree, to the point that it's more like a mission web. Very often, I'll have a conversation node where I want to offer six or more choices to the player, except that many of the choices require and/or are exclusive with things that may or may not have happened in previous missions. The usual solution for conditional `choice` nodes in Endless Sky is ... inadequate at this level.

**Related Issue Links**

(A quick search didn't find anybody else requesting this.)

**Describe the solution you'd like**

Synthesizing a very silly example:

```sh
conversation
    `"Hello!" the man sitting next to you at the bar says. "You're Captain <last>, right?"`
    branch "don't recognize him"
        not "got told about the renegade deputy"
    `    You recognize his face from the wanted bulletin that Captain Snafu sent you. This is the deputy that let the criminals who stole the Boundless Frontiers source code escape.`
        to display
            not "learned the truth about Boundless Frontiers LLC"
    `    You recognize his face from the wanted bulletin that Captain Snafu sent you. This is the deputy that helped those Remnant scientists steal the Boundless Frontiers source code so they could work on a cure.`
        to display
            has "learned the truth about Boundless Frontiers LLC"
    label "don't recognize him"
    `    You have to be careful what you say. Potato Pete warned you that this bar has listening devices under the stools.`
        to display
            has "know about the listening device"
    choice
        `    "Uh... hello."`
            goto "hello" # (clearer than just falling through)
        `    (Ignore him.)`
            defer
        `    (Try miming to him that there are listening devices under the stools.)`
            to display
                has "know about the listening device"
            goto "get arrested for public miming"
        `    (Try answering him in Remnant sign language.)`
            to display
                has "event: remnant: sign studies complete"
                or
                    has "know about the listening device"
                    has "learned the truth about Boundless Frontiers LLC"
            goto "get away with helping the deputy"
        `    (Shoot him.)`
            to display
                has "got told about the renegade deputy"
            goto "maybe shoot the deputy" # ...but NOT the sheriff?
        `    "You're under arrest!"`
            to display
                has "got told about the renegade deputy"
            goto "deputy runs away"
        `    "Hey, keep your voice down. You're a wanted man."`
            to display
                has "got told about the renegade deputy"
            goto "get caught helping the deputy"
```

The new `to display` node can go as a child of either a normal text node or the child of a `choice` node. If the condition is not met, it is as if the node was erased. So, in the above example:

```sh
        `    (Try miming to him that there are listening devices under the stools.)`
            to display
                has "know about the listening device"
            goto "get arrested for public miming"
```

If the "know about the listening device" condition is not set, it is as though the "miming" choice wasn't present in the list.

**Describe alternatives you've considered**

In the above example, choosing between the two "you recognize his face" parts can be handled with an additional `branch`, and only be a little clunkier. But even with just three binary conditions ("know about the listening device", "know remnant sign language and have either of two reasons to try it here" and "saw the wanted poster") the branch solution would require me to manually create eight different `choice` nodes and make a three-level branch mess to choose the right one. And then, if I want to add another choice, or I realize a particular case I missed, I'm really up a creek. In the unusually egregious case of the real mission I was just working on, there were four (or five? not sure yet) conditions, which would require me to manually make sixteen (or thirty-two!) choice nodes.

**Additional context**

~~I made a very brief attempt to add support for this to `Conversation` myself, but my first pass over the code did not yield sufficient understanding to make the necessary changes. I'll make a more serious attempt later. If that fails, I'll take the truly disgusting path of making [yet](https://github.com/SolraBizna/hubris) [another](https://github.com/SolraBizna/elko) thin DSL for this.~~

~~(And, I'm fully aware of the logistical nightmare that I'm unleashing on myself, by creating so many different paths both through individual conversations and through the mission tree as a whole. I'm a NetHack veteran, so... believe me, I know.)~~

PR #5440 implements this. It hasn't merged yet because this is pretty core stuff and we want to be sure we get it right.

Edited 2022-11-17: linked PR, updated example syntax

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Feature:** This is *not* my work; it is from @SolraBizna's PR #5440 who did the work to fix #5439. All I did was merge master and get everything to work.

**Note:** This is 100% working and ready for review, except that:

1. I don't know the future of #5440 since it is two years old and moving slowly. Hopefully @SolraBizna will tell me I can take over.
2. I don't know how to add tests, nor whether they're needed for this feature.

## Feature Details
Copied straight from #5440:

This PR allows a `to display` child to be applied to text in `conversation` and `choice` nodes. If this child is present, it contains a set of condition test expressions, all of which must evaluate to true in order for the paragraph / choice to be displayed and/or selectable.

Not from #5440: A reviewer comment wanted Element to be moved to the top of a class, but Node was already in the middle of the class. I moved them both to the top.

## UI Screenshots
Copied straight from #5440:

(N/A) the user experience is exactly the same as before, except that behind the scenes there's another way to hide text or choices from the player

## Usage Examples
This is needed for Hai Reveal PRs #7570 and #7594

This is how it would be used in #7570
[test2.txt](https://github.com/endless-sky/endless-sky/files/10026827/test2.txt)

## Testing Done
[test2.txt](https://github.com/endless-sky/endless-sky/files/10026827/test2.txt)

### Automated Tests Added
None yet. Maybe should add some?

## Performance Impact
Perhaps a few microseconds when processing a conversation.

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
Pinging reviewers of the other PR: @warp-core @Amazinite @petervdmeer @RisingLeaf @Hurleveur @tehhowch

**Comment by Hecter94** [comment]
Did the original OP say it was okay for you to take over their PR? 
I do want to see this feature, but I just want to make sure you were given permission to re-PR their work.

**Comment by UnorderedSigh** [comment]
> Did the original OP say it was okay for you to take over their PR?
> I do want to see this feature, but I just want to make sure you were given permission to re-PR their work.

I'm waiting to hear back on that. It's one of the reasons this is a draft (as explained in the PR description).

**Comment by Amazinite** [comment]
The OP of #5440 commented on the PR just a couple hours before you opened this. If a PR owner is still around and working on their PR then you should open changes as a PR to their branch, not a duplicate PR to the main repo.

**Comment by UnorderedSigh** [comment]
> The OP of https://github.com/endless-sky/endless-sky/pull/5440 commented on the PR just a couple hours before you opened this. If a PR owner is still around and working on their PR then you should open changes as a PR to their branch, not a duplicate PR to the main repo.

Doing it now.

**Comment by SolraBizna** [comment]
For the record, my comments featured ominous rumblings of unavailability. :)

I would be fine with a "duplicate" PR, or continuing to merge pull requests, or just giving people commit rights on my fork so they can work more directly on it. Whatever norms and whims dictate.

**Pull request closed without merging**
