### PR TITLE
New Ship: Kraken (Medium Warship)

### PR DESCRIPTION
**Pull request by OmegaZanicus**
Kind of an oddball, its like Leviathan's little brother, but a little more extreme towards the tanking and slow. Trading out speed for Armor/Shields and more combat customization for the player. Probably its best use in the game is guarding trade fleets, due to its speed, probably not as good a flagship.

kraken space
kraken stats

### CODE REVIEW

**Comment by jafdy** [comment]
I don't know if another human ship is needed.

**Comment by Bladewood** [comment]
It resembles a leviathan too well.

**Comment by KiLEdEnNis** [comment]
@Bladewood agreed, more like a remodeled Leviathan

**Comment by OmegaZanicus** [comment]
Doesn't seem like peeps are too thrilled so I'll just close this then.

**Comment by jafdy** [comment]
That has got to be the shortest time a PR has been open.

**Comment by OmegaZanicus** [comment]
Wrzl asked if I was gonna make a pull request for this since I won the contest, but If people don't think its necessary, then It doesn't need to sit around in the open section.

**Comment by Alkallid** [comment]
rip

**Comment by Wrzlprnft** [comment]
For the record my question was more aimed if he plans to make one by himself.

Anyway, that was not a very convincing pull. New ships these days need a reason to exist...

**Comment by KiLEdEnNis** [comment]
new human ships aren't needed, but if they are added, they shouldn't be an edited version of a current ship (like this Kraken); it'd need to be a ship of it's own
(and the Manta is Syndicate ships, the name Kraken would fit with it, if it resembled it a little bit, just like the Raven and Wasp do)

**Comment by OmegaZanicus** [comment]
`Anyway, that was not a very convincing pull.`
im not good at convincing

**Comment by Wrzlprnft** [comment]
Don't worry, captain brewtus never made it in (not yet at least) so i know that.

Next time set up a little backstory, like, some pirates tried to copy the leviathan but did not have the resources and only make it available at that small pirate cluster between human and wanderer space, and maybe only add it after a certain point in the campaign (maybe that one where those 3 levis drop on the players head).

**Pull request closed without merging**
