### PR TITLE
Autosteering

### PR DESCRIPTION
**Pull request by dplepage**
This is a possible patch for #166 - it adds an auto-steering button that has the following behavior when you hold it down:
 * If you have a target ship in this system, this is the same as turning on auto-aiming
 * Otherwise, if you have a target planet, this turns you to face that planet
 * Otherwise, if you have a target system, this turns you to face that system

I had to move all the text on the key settings panel up a few pixels to avoid running off the bottom.

### CODE REVIEW

**Comment by gchapyzh** [comment]
Does it act as the R button, but more forceful?
I suggest you add a toggle option rather then hold-down.

**Comment by dplepage** [comment]
@gchapyzh No, it's unrelated to the 'R' button (assuming your config is still set so that 'R' changes your target to the nearest hostile ship) - this emulates the "Autopilot" button from EV, which turns your ship to face your target (no matter how far away it is).

This is very useful for e.g. quickly breezing through fights with a lot of targets - hold down Autopilot, forwards, and fire, and tap 'R' as soon as your target is destroyed, and you'll automatically turn and chase after the next target.

**Comment by gchapyzh** [comment]
@dplepage Perfect, this will come in handy. Can you add a toggle option as well, so I don't have to use up a whole finger while fighting?

**Comment by dplepage** [comment]
I rebased this on the latest master, and also created a toggling version (#547). Both have a broken `PreferencesPanel`, though, because since 7029878753e11b33006ce4346b3741566d9fdbf6 moved the Scan button there's no longer space for the command in the appropriate box. I'm not sure where it should go now.

**Comment by jmhorjus** [comment]
I like this a lot after pulling/testing with it myself. If feels great to use this in combat and it points to the planet if there's no ship selected. Nice job.

However, the preferences pane isn't quite right. I think you need to change its dimensions slightly or remove a few pixels of spacing elsewhere.    

clip

**Comment by Pointedstick** [comment]
Can we revisit this now that there's plenty of room in the prefs panel?

**Comment by KiLEdEnNis** [comment]
I agree although I'd never use it

**Comment by Logicaluser** [comment]
Any chance of this being added? 

As a longtime former EV player, I repeatedly find myself trying to hold A to point the nose towards a targeted ship, only to realize later that it's doing nothing. 

Seems like the only aspect of Escape Velocity's ship combat controls that is missing at this point.

**Comment by azerwyn** [comment]
Presuming this feature still has a champion, I also request revisiting this on the grounds that it enhances "accessibility" for otherwise enabled players (#define CULTURAL_SENSITIVITY 1).  While I might not use this feature, I support and advocate for friends that require assistive technologies.

An auto-facing (AUTOSTEER) feature would enhance accessibility for the otherwise enabled with very little investment.

While not specifically a GNOME app, substantial effort has gone into the [GNOME Accessibility Developers Guide](https://developer.gnome.org/accessibility-devel-guide/stable/index.html.en) and seems to be well regarded.  Within the guide, two [Keyboard Navigation](https://developer.gnome.org/accessibility-devel-guide/stable/idp5169872.html.en) suggestions seem sensible:

> - Provide more than one method to perform keyboard tasks where possible. Some users may find some keys and key combinations easier to use than others.
> - Don't require repetitive use of simultaneous keypresses. Some users are only able to press and hold one key at a time. Assistive technologies such as AccessX may allow users to press the keys sequentially rather than simultaneously, but this of course means the operation will take longer for them.

Additionally, in the Windows world, MSDN suggests in [Guidelines for Keyboard User Interface Design](https://msdn.microsoft.com/en-us/library/ms971323.aspx?f=255&MSPPError=-2147217396):

> - Avoid simultaneous multiple key input. Applications should not require users to press multiple keys simultaneously, except for the modifier keys SHIFT, CTRL, ALT ...

Additionally, to the feature itself --

`+const Command Command::AUTOSTEER(1uL << 25, "Face selected ship");`

Semantics and future-proofing:  Is "Face selected **ship**" entirely accurate or can the action description better reflect the action today and hedge against future targeting options?

e.g. "Face selected target" seems more accurate, intuitive for new players, and resilient should future targeting expand to include additional non-ship targets (anomalies, stations, repair docks, debris, etc.).

Finally, some may prefer no auto-facing feature (considering it an unnecessary or unskilled offset), some may prefer a hold-to-activate (being familiar or leveraging muscle memory), and some may prefer a toggle (for ergonomic or accessibility reasons).  Perhaps a configuration option that determines the nature of the switch (null or press-to-activate or toggle) would mitigate the style-of-play debate while also offering enhanced accessability.

Of course a hook and plug-in alternative is always an option (and perhaps even more extensible if one considers the potential for navigation override, programmable maneuvers, or formation movement).

**Pull request closed without merging**
