### PR TITLE
fix(content): Moved items into files and removed hidden

### LINKED ISSUE #7702: Remnant research expedition can choose Devil-Hide before it's revealed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Remnant research job asked me to scan Devil-Hide but the system hasn't been exposed on the map so there is not access. This pilot is currently pre-FW.

Screenshot_2022-11-24_19-30-21
Screenshot_2022-11-24_19-33-09

### Steps to Reproduce

These are selected at random so are difficult to reproduce. 

### Expected Behavior

Only systems accessible on the map should be selected for these jobs. This is a spoiler of sorts, though it gives no actual information other than the system name.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Linux EmberWastrel-8088i 6.0.8-1-MANJARO

### Game Source

ESLauncher2

### Game Version

Recent continuous

### Additional Information

_No response_

### LINKED ISSUE #8477: Remnant Expedition mission reveals the system that is not allowed to access right now
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Hai Reveal mission is not active right now, but despite of this the Remnant issue the expedition mission to check the system related with this quest line.

### Steps to Reproduce

1. Go to Remnant territory.
2. Check the Research Expedition mission and see if it issue the expedition mission that is not meant to access right now.

### Expected Behavior

The system needs to have some tag such as unreleased, and such systems are exempt for the target system for the Research Expedition mission target issued by Remnant.

### Screenshots

https://steamcommunity.com/sharedfiles/filedetails/?id=2938729931

### Link to save file

_No response_

### Operating System

Windows 10.

### Game Source

Steam

### Game Version

0.10.0

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
- Moved Al Hurr into map systems, and Aspiration into map planets.
- Removed "hidden" from Devil-Run and Al Hurr.

## Reasoning
- Moved because, well, those are the files for that data to be in. I do not see any particular reason for it to need to be kept separate (and it makes them hard to find)
- Removed the "hidden" attribute because there's not really a reason for these systems to be hidden. They're right there, nothing happens to them. The fact that they need a Jump Drive to access makes them significantly low probability for the player to go there, especially since all they're likely to find is a wormhole or a relatively unremarkable pirate planet. An attentive player might note that it seems really odd to have a pirate world so isolated, but that's more intriguing than anything else, so not a problem.
- This also makes them places that the player can find via exploration, which I think is a good thing. More area to explore is good!
- This will also fix the problem with people being asked to take observations by the Remnant that they can't access.

## Closes:
fixes #7702 
fixes #8477 

## Save File
This save file can be used to verify this section of Hai Reveal works properly:
[Rebbia Rampart~3031-03-25 Found Wanderers and Election Time.txt](https://github.com/endless-sky/endless-sky/files/10949221/Rebbia.Rampart.3031-03-25.Found.Wanderers.and.Election.Time.txt)

This save file has access to research missions:

[Rebbia Rampart~3035-02-10 Finished Dawn Scanning mission.txt](https://github.com/endless-sky/endless-sky/files/10949273/Rebbia.Rampart.3035-02-10.Finished.Dawn.Scanning.mission.txt)

## Artwork Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Comment by bene-dictator** [comment]
I'm not kept up with what's happening with Hai Revealed, but I think some of this PR goes against the plans going on with it. Especially because Devil-Hide seems to be on the line right now, and it doesn't make very much sense for Al Hurr to be isolated.

If you've made the PR with co-operation with Grey, Sigh, or Amazinite, no problem then.

**Comment by Zitchas** [comment]
I've talked with both GreyMasterofGrey and UnorderedSigh about this.

I certainly hope it's not getting chopped. I very much enjoyed playing through most of it, and the few spots that weren't highly enjoyable were quibbles that are a matter of polish and balance, nothing drastic.

**Comment by ziproot** [comment]
So devil-hide can be visited as soon as you get a jump drive? Won't that require changing parts of hai reveal?

**Comment by Amazinite** [comment]
#8185 also moves the planet and system to the proper file, and that PR is something that I plan to merge, so the main substance of this PR is in the removal of `hidden`. 

I don't think that `hidden` should be removed from these systems. As ziproot has noted, if you're going to make these systems visible from the start of the game, then it'd make sense for the story to react to you discovering them early. But insofar as the story does not currently react to this, it doesn't make sense to remove `hidden`. (Yes, the FW storyline should probably also react to you having visited Deneb early, but that's something I do want to get to during the FW rework, and is somewhat related to #989.)

> The fact that they need a Jump Drive to access makes them significantly low probability for the player to go there

There is a low chance for a *new* player to go there, but across all players and all save files, the probability of anyone visiting these systems before actually going through Hai Reveal is basically a certainty, and so a reaction from the story is basically required.

> This also makes them places that the player can find via exploration, which I think is a good thing. More area to explore is good!

I don't think "more systems for the sake of exploration" is a sound reason for removing hidden in this case. Why not remove hidden from Postverta, or from the Emerald Sword system, or from Patir? These systems have justifications for being hidden before the story makes use of them, whether that be in-universe justifications for why the system wasn't visible before, or out-of-universe justifications in that it makes the story easier to work with.

> This will also fix the problem with people being asked to take observations by the Remnant that they can't access.

This could also be fixed by using the "inaccessible" system attribute that we've made use of in the past for such situations where we don't want those Remnant jobs to go to certain systems, although I'd say that the issue is with those jobs themselves, not with systems not accounting for them. Given the number of times that this has popped up in the past, with the Remnant jobs sending you to impossible locations, it's clear that these jobs create an undue burden on the rest of the game to account for them. A proper fix would be resolving #5395, not continually having to make use of the "inaccessible" attribute or making things visitable for the sake of these jobs.

<hr/>

In bringing this PR up to Grey, he noted that we should have a more concrete convention explaining when we should and should not make use of the `hidden` attribute, and I believe I've already outlined when I think that `hidden` should be used: in order to justify making use of `hidden`, either there needs to be some in-universe explanation for why the system was not mappable before, or some out-of-universe justification that relates to ease of story writing.

While we should aim to have the story react to the player given their circumstances instead of always being the same story every time, there is a limit to just how much we can and should account for. In this case, discovering an isolated group of seemingly highly technologically advanced pirates should certainly throw up some red flags in the HR story as something the player should mention to other characters, even very early on. But if the player does discover these systems early and the story never reacts to it, then it can feel like the player character is playing dumb. Such a change to the HR storyline would be quite large, though, and we're already in the middle of dealing with what already exists, so I don't want to place a burden on ourselves to write that kind of story reaction to the player by removing `hidden` right now.

Another out-of-universe justification for why a system might be hidden could also relate to how finding the system beforehand could essentially destroy the story that already exists. Imagine if you found the Emerald Sword by accident before starting the Emerald Sword storyline. Finding systems by accident in this game is not a difficult feat; we only have a few hundred systems, and it's obvious which ones you haven't visited, so it wouldn't take long for someone who wants to have every system visited to visit every system. Should someone stumble upon the Emerald Sword system before the story, you'd then be essentially short-circuiting MASSIVE parts of the storyline. It would be a much flatter story if the game were to account for you having found the system early, and so for the sake of having a bolder story, it makes sense to keep the Emerald Sword system hidden.

**Comment by ziproot** [comment]
I would like to add that the emerald sword is mission dependent and does not show up if you visit that system early. I know because the Remnant research bug revealed that system early.

**Comment by Amazinite** [comment]
Given the impossibility of representing the BILLIONS of stars in the Milky Way, I think we can afford to state simply that systems are displayed or not displayed for the sake of gameplay. We don't need some convoluted explanation why only a few hundred systems are able to be visited.

**Pull request closed without merging**
