### PR TITLE
Added a person which reminds the player to have a pause while playing

### PR DESCRIPTION
**Pull request by Wrzlprnft**
I had the idea for something that would break up the players focus while he's playing and grinding in the game like a maniac. Pretty low frequency to make up for it's silly look.

Idea and sprite by wrzlprnft, developed with quite a few prayers and praises to a local god.
coffee cruiser 2x

Reminder: It is not to be meant to add real depth or content to the game, but make a gamer look on his clock at 2 am and realize the "just a half an hour" went up to two or three more. lot of games have that in a more or leass sophisticated way. Anno1404 uses notification or achievements(while i was playingit on a lan-party we all suddenly got a achievement for playing several hours without using the chat....), while black and white 2 checks the use directory of the computer if there is a name in it which matches some prerecorded creepy whispers, which then would start to whisper your name in your ear while playing.
#929

### CODE REVIEW

**Comment by LocalGod79** [comment]
actually, if you wouldn't mind - i just thought of a joke i'd like added to Uncle Brewster's phrasing - with "cola." "tea." "water.";
could you add "literuhcola."  it's a "Super Troopers" reference which will certainly trigger a smile on the face of anyone who's seen the movie...

**Comment by LocalGod79** [comment]
i'd say use a cup from here;
https://thenounproject.com/term/cappuccino/93975/

**Comment by Wrzlprnft** [comment]
Ill be reworked again, do not merge.

**Comment by Wrzlprnft** [comment]
will come up with it again, as soon as ther is a better possibility than a low frequency

**Pull request closed without merging**
