### PR TITLE
More stars, to scale, & Lead's star sprites

### PR DESCRIPTION
**Pull request by ravenshining**
**Content (Artwork)**

## Summary

- The main sequence of stars has been expanded and standardised
- There are now dwarves, giants, and supergiants for every colour
- Matteo M. AKA "The Lead" has produced new sprites for all stars except the Wolf-Rayet
- A new star type, the carbon star, has been added.  It replaces the Wolf-Rayets in Kor Ak'mari and Antevorta, provides lots of fuel and little power.
- An "old" nova variant has been added.  It replaces the nova in Saquergen.
- Gefüllte Taubenbrust's neutron star has been added.
- All main sequence and giant stars are now in logarithmic scale to each other (but not anything else of course)

For variety and ease of map creation, each spectral type of star now has the same set of variants:

(m, k, g, f, a, b, o)
(-dwarf, 8, 5, 3, 0, -giant, -supergiant) 

So any combination of a letter from the first set with an epithet from the second results in a valid star.

This scheme results in the depreciation of M4 and unclassed  "giant" stars - existing M4s have been changed to M3s and M5s, existing giants have been changed to spectrally classed giants.  M4 has been given a quick and dirty update to maintain compatibility with old saves that have already done the Scar's hideout mission, while giant assets are untouched, but both have been removed from the 2x repo.  Most new star types have similarly been sprinkled about the map in the place of similar stars for variety.

Possible To-dos:
- Add a neutron star and some more O-type stars to the map as most are unused as of this writing.
- ~~I was hoping to include a not-SagA* black hole in this PR, too, but never got around to it.~~ Can be worked around, see usage examples.
- ~~Reassign stars in human space to match RL types and add lore explaining why they're out of place~~ Should probably wait for another PR.

Not a screenshot - comparing old and new stars:

compare

Not a screenshot and compressed lossily - spritesheet showing all stars (except carbon, novae, wr, neutron, & black hole) laid out as a crude Hertzsprung-Russel diagram:

H-R d

## Save File
This save file can be used to play through the new mission content:

[star test.txt](https://github.com/endless-sky/endless-sky/files/6289028/star.test.txt)

This save gives you an explored galaxy (with pug and new remnant wormholes) and a Raider that's easy to explore it with

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - ~~I uploaded the necessary image, blend, and texture assets here: obtained,~~ No blends were used.  Lead says his source files are 3 GB psd's so I don't think we want those.
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: [https://github.com/endless-sky/endless-sky-high-dpi/pull/172](https://github.com/endless-sky/endless-sky-high-dpi/pull/172)
  
-----------------------
## UI Screenshots

New black hole sprite:

Screenshot_20210404_115039

Betelgeuse:

Screenshot_20210404_234958

Carbon star:

Screenshot_20210411_132348

New nova variant: (nova-old+)

Screenshot_20210405_000618

Neutron star (Not actually placed anywhere yet, pictured for demonstration purposes):

Screenshot_20210406_233046

Redone nova:

Screenshot_20210406_180215

Redone Wolf-Rayet:

Screenshot_20210411_132728

## Usage Examples

The carbon star and (as of this writing) novas require a "core" sprite laid on top, similar to the black hole, like so:
```
	object
		sprite star/carbon
		period 10
	object
		sprite star/carbon-core
		period 10
```

The neutron star has the opposite, a core beneath:
```
	object
		sprite star/neutron-core
		period 10
	object
		sprite star/neutron
		period 10
```

As an unexpected bonus, you can construct a smaller, different sort of black hole by placing the neutron star core atop the nova:
```
        object
                sprite "star/nova"
                period 1
        object
                sprite "star/neutron-core"
                period 1
```

## Testing Done

I have gone through all systems containing giants or subgants to ensure there is no sprite overlap, widening orbits when necessary, and generally flown around the galaxy making sure everything looks right.  Did a lot of zooming in and out on stars to ensure normal and 2x sprites are spot on.  Should be good now.

## Performance Impact

Adds 10 MB to the game assets

A number of stars are much larger than they were before, particularly giants, but this should not be an issue.

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
Huzzah! It begins.

**Comment by Zitchas** [comment]
Looks very nice! I'm definitely enjoying watching all these comes together - should make Endless Sky much more enjoyable to spend time watching *the sky*. 

Once you are ready to go, I'd appreciate a PR to https://github.com/Zitchas/endless-sky/tree/Z-Combat-Revamp-Slow_v1 (or just DM me to let me know and I can do it) so that I can merge these into Revamp.

Thanks for working on these!

**Comment by MCOfficer** [comment]
Sidenote for any viewer, in case you are using the github dark userstyle (i know i recommended it to some people): It introduces visual bugs with these images. the carbon star screenshot doesn't actually look like this.
image

**Comment by ravenshining** [comment]
Have you tried a different browser? I use dark mode, and it looks fine at least in Opera on Linux.

**Comment by MCOfficer** [comment]
> 
> 
> Have you tried a different browser? I use dark mode, and it looks fine at least in Opera on Linux.

No, it's the fault of the userstyle. Just disabling it does the trick. I didn't want to go offtopic any further.

**Comment by BaddestApple** [comment]
Would anyone be opposed to me adding indentations to the first paragraphs of planet and spaceport descriptions for better readability? I've already spent half an hour adding them to this PR for my own sanity in anticipation of the image release. (I also added indentations to all my local outfit, weapon, ship, and mission files and my eyes want to bleed lol)

I'm new to github however and haven't yet figured out how to do commits and all that. Apparently I don't have write access here, so if it would be acceptable how do I go about submitting the change?

**Comment by Anarchist2** [comment]
Don't fork the forks. If you're looking to merge something into the base game, best to do it straight to master, rather than bogging down an existing PR.

Also see #5768.

**Comment by BaddestApple** [comment]
#5768 is paragraph breaks, not indentation of first paragraphs. Guess I'll just wait till this is (hopefully) merged then and I have a better understanding of how this all works.

**Comment by McloughlinGuy** [comment]
I just want to take a moment to appreciate how amazing these sprites look.

**Comment by TheMageKing** [comment]
Question from non-ES contributor: Is there a unit test that checks if any sprites in the system are intersecting?  If not, would you be interested in including such tests?

**Comment by Amazinite** [comment]
1) No such test exists.
2) I'd be interested in such a test. Be aware though that certain sprites are intended to overlap. See the Heliarch ringworlds with solar panels on top of them, or the nova or carbon star in this very PR where the sprites are large and allow planets within the orbit of the sprite. So there should be some way to add exceptions to what are allowed to overlap. We basically only want to avoid overlapping planets/moons.

**Comment by TheMageKing** [comment]
Ok.  I'll pop into a separate issue to discuss this in more depth: the test framework as-is would seem to be limited for supporting these sorts of resource tests (as opposed to code tests)

**Comment by Amazinite** [comment]
I’d get in touch with @petervdmeer about messing with the test framework, as I believe he’s the one doing the most work on that front.

**Comment by beccabunny** [comment]
> We basically only want to avoid overlapping planets/moons.

Actually, i am pretty sure there are various gas giants that have moons inside their sprite, because of the ring

**Comment by ravenshining** [comment]
> 2.  We basically only want to avoid overlapping planets/moons.

In my opinion having any sprite intersecting a dwarf, main sequence, old, or giant (not supergiant) star looks really bad, so I've been hunting through the map manually looking for such occurrences this PR introduced and widening orbits to accomodate.  I'm pretty sure I've taken care of all the most likely offenders, however.

**Comment by ravenshining** [comment]
I've been discussing on the Discord, how since these stars are of a different style, it changes the look of the title screen.  For now, I've given the title screen a G5, as it's yellow and plain-looking like the current title.  Personally, I think an F3 or A5 would look better, though, and (while implementing this might be better discussed in a different PR or issue) it might be fun to have the game randomly choose from a selection.

Here's a sampling of how the menu screen would look with what I think is the best example of each spectral class:

allstars

If this PR is accepted and we don't go the random route, maybe it'd be worthwhile holding a poll?

**Comment by Zireael07** [comment]
Aesthetically, I like F3 the most. Logically, M0 (most stars in the galaxy are red dwarfs) :P

**Comment by Zitchas** [comment]
Just out of curiosity, do we have a 0B star, as mentioned in this [article](https://www.livescience.com/new-milky-way-spur-discovered.html)?

**Comment by ravenshining** [comment]
...If I'm reading things correctly, an OB star is just a main sequence O star, or B star above 9 solar masses?

If that's the case, yes, we have added b0 and the entire o series.  No O-type main sequence stars have been placed yet, but in the course of diversifying the map I did change the uninhabited Regulus system from b5 to b0:

Screenshot_20210409_145230

**Comment by Zitchas** [comment]
Cool! Looking forward to seeing them!

**Comment by ravenshining** [comment]
Okay, this PR is basically good to go.  Before I mark it as "open," as mentioned on Discord I'd like some feedback on Lead's new Wolf-Rayet and Nova sprites.  Here's a side-by-side comparison:

novas

wrs

Personally I am partial to the originals, though I could see using either WR in different parts of the galaxy as there are a number of them.  I don't see that happening for the nova though.  I'd just not include them here but I feel like that would be a breach of the trust Lead has placed in my handling the data, post-process and git side of this PR.  Perhaps a poll is in order?

**Comment by MasterOfGrey** [comment]
In my opinion, keep the originals where they are, but still add these in for use elsewhere.

**Comment by Zitchas** [comment]
In terms of testing this, could I just merge this into Revamp with the larger orbits? Or is there any scaling or anything else that should be done?

**Comment by ravenshining** [comment]
Sadly it's not that simple.  But, if we can get @Ferociousfeind  to apply the same procedural change to my map file as they did to the vanilla map file, then I could use the result as the basis for a PR of this branch to Revamp without a lot of tedious editing by hand.

**Review by arkhne — APPROVED** [review]
Tested on https://github.com/Zitchas/endless-sky/pull/92 . Looks great. I have no objections, and have not found any issues in-game, while every system I have checked has the new sprites.

**Comment by ravenshining** [comment]
Here's a flight plan with the locations of all the giants and supergiants, in case you want to specifically check those out:

map

**Comment by Zitchas** [comment]
Thanks, that is quite helpful for finding them.

**Comment by McloughlinGuy** [comment]
Someone should redo the haze and star backround
That would look amazing with this.

**Comment by ravenshining** [comment]
I *did* add more hazes to the game about a year back.  I'm not keen on the idea of making them any more detailed, however, I think we've gone too far down the "everywhere is space is a nebula" trope as it is.  Apart from some *very* special places like Saggitarius A*, anyway, I have been thinking of making a better haze for that as the current one is just my core one made bigger and brighter.

Being able adjust star density on a per-system basis is high on my feature wishlist though.

**Comment by Pointedstick** [comment]
Just wanna say this looks amazing and I hope it gets merged soon!

**Comment by ravenshining** [comment]
Thank you!

By popular demand, I've tweaked the Alpha Centauri system to look more like its RL counterpart, although I did not include Proxima Centauri as that is too far out to display and fly to sanely.  I used a bit of a trick to make it look right, placing Alpha Centaur A's orbit just inside the gas giant with exactly the same period so we don't have a star shining on the dark side of a planet.

Also, I've discovered that placing my neutron-core sprite atop Lead's nova sprite results in a passable non-rotating, smaller black hole (example screenshot, not actually implemented):

Screenshot_20210504_230420

After some discussion with Arachi and Mike about what to do with the ringworlds, and some testing of various types, I've given them all orange subgiants (g0-old).  Ideally I'd give them k-giants, as RL Enif is a k-supergiant, but that doesn't look good with the present size of the rings.

Two exceptions to this are Queri, which retains its red subgiant star, and World's End.  The ring at World's End was placed there, not constructed there; as far as we know doesn't need power or fuel, just a stable star to park it around; and the lore about it being "broken" just utterly fails to come across to me.  So, I thought rather than give it an orange subgiant I'd give it a nice, ultra-stable M8, which underlines the message that something is not right with this ringworld, and because it sits on a red star in the galaxy image.

Screenshot_20210504_211700

With that, and after a month of testing, I think this PR is ready to go.  My plans to correct the rest of the stars in human space, and place a neutron star and more type-o stars somewhere on the map can probably wait for another PR.

**Comment by MasterOfGrey** [comment]
`I've discovered that placing my neutron-core sprite atop Lead's nova sprite results in a passable non-rotating, smaller black hole` Oh I need to use this for a thing.

**Comment by montaropdf** [comment]
Can't wait to see this in a forthcoming release.

**Comment by Pointedstick** [comment]
Time to merge this incredibly beautiful addition. I've actually been applying it to my git checkout of the game for months. It's lovely.

**Comment by kestrel1110** [comment]
Beautiful. So glad it's finally merged :)

**Pull request merged**
