### PR TITLE
Luxury ships

### PR DESCRIPTION
**Pull request by ph2000bis**
This is basically the same pull request as #553 after I sorted all my branch problems, except without the modification tourist missions.
The "Luxury Bunks" outfit is invisible in the outfitter

### CODE REVIEW

**Comment by guillochon** [comment]
I really don't think a new account was necessary here, but if it helps you then I guess it's fine. I guess you still need to get a bit more familiar with version control!

**Comment by ph2000bis** [comment]
What I had done was merged onto my local endless-sky/master, so I think that's why I stopped being updated

**Comment by Pointedstick** [comment]
@guillochon To be fair, Git and its associated administrivia (e.g. Github) are ridiculously difficult for a non-programmer to learn. Heck as a programmer myself I'll admit that it took about a year before I was really comfortable with all this stuff.

**Comment by guillochon** [comment]
@Pointedstick It's true that it isn't easy, but creating a completely new account should never be the solution.

**Comment by ph2000bis** [comment]
It was the simplest for me

**Comment by endless-sky** [comment]
Adding a custom outfit just to represent luxury bunks seems like a risky idea, especially since if you fail or abort one of those missions, you'll permanently lose those bunks (unless you also restore them in "on fail"). And, they'll show up in the plunder list, which will be confusing.

**Comment by ph2000bis** [comment]
Does "on fail" also work for abortion ?
I'll try removing them the fleets.
Otherwise, this is a stopgap measure until I figure out how to make "Luxury ships" visible on shipyards (as for now when I put category: "Luxury Transport", they disappear from the shipyard list in map, probably also on planets).
If someone, or @endless-sky can make this support, I will change my pull request

**Comment by ph2000bis** [comment]
returned the luxury bunk spaces on fail, and removed an obsolete "to fail"

**Comment by Pointedstick** [comment]
@ph2000bis what I always do is pull from current master:
> git checkout master
> git pull --rebase parent master

…and then branch off of that. To make the prior command work, first do this once:
> git remote add parent https://github.com/endless-sky/endless-sky.git

That will allow you to easily merge the latest changes here into your own repo.

**Comment by endless-sky** [comment]
Obligatory [xkcd](https://xkcd.com/1597/):

git

**Comment by Pointedstick** [comment]
It's so, so true.

**Comment by ph2000bis** [comment]
Is there a way to make them unplunderable ?
I don't understand what you are telling me to do. Is there a simple way within GitHub?

**Comment by Pointedstick** [comment]
Instead of creating a "Luxury bunk" outfit, just conditionalize your missions on whether or not the player owns a "Luxury Transport." If that part isn't yet working, then it should be fixed, not worked around with a kludge.

**Comment by sanjayatio** [comment]
> Is there a way to make them unplunderable ?

ask @endless-sky to make a "self destruct" hand to hand outfit; the last defender would press that button to keep their thing private?
make this a staple outfit for a secret society (space yakuza?) or maybe to future (ore even an existing) aliens?
this might be able to tone down the plundering mindset "enforced" within the game.

**Comment by ph2000bis** [comment]
How do you modify the shipyard UI, I checked in data\interfaces text and I can't find it

**Comment by Pointedstick** [comment]
You have to add the new ship class to source/ShipyardPanel.cpp and source/MapShipyardPanel.cpp.

**Comment by ph2000bis** [comment]
i found it, just trying to test it, probably get it fixed tommorow

**Comment by Pointedstick** [comment]
At this point the pull request is not clean and mergeable; you may want to close it and create a new one with just the changes for the ship types. If that is approved, then perhaps you can do another pull request that adds some missions that require a luxury transport, and/or modify the "VIP transport" mission that I just got merged to require a Luxury Transport.

**Comment by ph2000bis** [comment]
The shipyards display the luxury ships as separate.

**Comment by ph2000bis** [comment]
what's wrong with the merge request?

**Pull request closed without merging**
