### PR TITLE
Update includes & forward declarations

### PR DESCRIPTION
**Pull request by tehhowch**
- Removed some legacy includes
 - added includes where list/vector holds the complete type and not just a pointer
 - Swapped includes to forward declarations for shared_ptr<Type> if possible

I was testing some changes to Planet.h and noticed some unexpected files needed to be recompiled. Traced that to an `#include "Planet.h"` in PlayerInfo.h, and then found some missing includes, and decided to go through everything.

### CODE REVIEW

**Comment by endless-sky** [comment]
A forward declaration in the header should be sufficient if a type is only used in a vector or a list. Both those classes are just a wrapper around dynamically allocated memory. The only time a forward declaration does *not* work in a header file is if the size of the class that is defined in that header depends on the size of the class that is being forward-declared.

To put it another way, a vector object is the same size regardless of what it's a vector of, and you don't need to know how big the things that the vector holds are until you actually make use of it (which happens in the .cpp file).

**Comment by tehhowch** [comment]
Fair point. I'll revisit with that in mind. I had read a bit about that, but wasn't sure if we could count on that behavior across compilers (looking mostly at being compatible with MSVC, as for some players compiling with MSVC seems to resolve a host of stability issues, e.g. #3516, that are otherwise present in the steam / packaged binary.)

**Comment by tehhowch** [comment]
I went through the repo again, and got a few more missing includes, and header includes that could be replaced with forward declarations. I had to basically fall back to compiling after every change, since my intuition for when `container<class B> b` influences the size of class `A` isn't up to snuff.

For example:
1. PlayerInfo holds `list<GameEvent>` and has `#include GameEvent.h` in its header. Changing to a forward declaration here results in allocator errors complaining about the incomplete `GameEvent` type when compiling `main.cpp` (which creates the PlayerInfo object).

2. Engine holds `vector<PlanetLabel>` and ha(d) `#include PlanetLabel.h` in its header. Changing to a forward declaration here does not result in allocator errors when compiling.


Given 1), I would have expected allocator errors to appear when compiling MainPanel, as it creates the Engine object and has no idea about the PlanetLabel class beyond the forward declaration, but no such issues occur.

That said, you're busy, so don't go out of your way to provide basic C++ knowledge :grin:

**Comment by flaviojs** [comment]
`list` probably has a root node variable (instead of a pointer) because it simplifies logic, which would require knowing the size of the type.

MainPanel.cpp receives PlanetLabel.h from Engine.h "for free".

**Comment by tehhowch** [comment]
With the PR, PlanetLabel's header is no longer in Engine's header, so only Engine.cpp knows about it - same as with GameEvent` and `main.cpp` if we use forward declares for all `list<GameEvent>` cases.

Mostly it'd be nice to be able to alter `MissionAction`, `Mission`, and `GameEvent` without recompiling everything that uses includes `PlayerInfo.h`.
Someday I might try setting up a managing class that holds a reference to PlayerInfo, and have it hold the lists of missions and mission-related logic

**Pull request merged**
