### PR TITLE
feat(refactor): Extract flat map functionality from Dictionary

### PR DESCRIPTION
**Pull request by tibetiroka**
**Feature**

This PR extracts the flat map functionality from Dictionary, making it usable with different types.

## Summary
Creates a new FlatMap class template, which Dictionary is a specialization of. There should be no performance hit in Dictionary from  these changes.

## Usage examples
Various uses of std::map could be sped up using the new flat maps.

## Testing Done
I tested that the new dictionary behaves the same way as the old one. (Well, it behaved the same way a couple months ago, I think...)

## Performance Impact
None, according to the built-in benchmark.

### CODE REVIEW

**Comment by RisingLeaf** [comment]
I would honestly prefer if we use an unordered map instead.
I think implementing our own data structures goes a bit too far for the size of this project.  If we are doing that, then we could also do it right (own allocator, watching memory, etc.) because the step from this PR to that is not really far. An unordered map has also a decent insertion speed (on average). And its lookup time is also good (on average).

**Comment by tibetiroka** [comment]
I haven't tested it recently, but unordered maps used to be a lot slower than flat maps for our small data sets.

**Comment by RisingLeaf** [comment]
> our small data sets.

That is my point though, data of that size does not provide a ground for actual testing of performance or the creation of own data structures.

**Comment by tibetiroka** [comment]
1. It does, because we can still measure the overall relative performance
2. It's not a new data structure, it's literally our existing Dictionary code, it's just getting generalized.
3. Our Dictionary used this flat map structure precisely because it was proven to be faster than a standard map.
4. Unordered maps of string can be less efficient than standard maps, because hashing requires the entire string, while comparison doesn't.

**Comment by RisingLeaf** [comment]
> 1. It does, because we can still measure the overall relative performance

Give me stats then. I want to see an improvement of at least 10%.

> 2. It's not a new data structure, it's literally our existing Dictionary code, it's just getting generalized.

Before it was a class that related to `std::vector<std::pair<const char*, double>>`, now it is a new class, that is defined as:
```c++
template < class Key, class Value, class ThreeWayComp = std::compare_three_way, class Alloc =
		std::allocator<std::pair<Key, Value>>>
class FlatMap : private std::vector<std::pair<Key, Value>, Alloc>
```
this is a lot of added complexity, you might know your way around template classes very well, but our average potential contributor might not or get confused by a structure like this

> 3. Our Dictionary used this flat map structure precisely because it was proven to be faster than a standard map.

Ye than thats fine, inside dictionary. Until you show me where you actually want to use it I do not see the point of extracting it and making the code more difficult to read.

> 4. Unordered maps of string can be less efficient than standard maps, because hashing requires the entire string, while comparison doesn't.

That strongly depends on the use case but ok.



My entire point is, that you have opened various PRs lately that introduce complex data structures (complex meaning more than a beginner to intermediate c++ programmer might understand), these _might_ make sense for the concurrency PR, that is why I did not argue about such actions there, but in this case I fail to see the benefit of doing something like this. And correct me if I am wrong but I thought the goal was to keep it easy for others to get into the code, this makes it more difficult, even for experienced coders. Why? Because if I see a std call inside es that I do not remember, I can just go onto the cpp reference to look it up, if it is a es custom class, I will have to open the class and read the code and then understand what it does, extra steps that cost time.

**Comment by tibetiroka** [comment]
> Give me stats then. I want to see an improvement of at least 10%.

Sure. I'm using latest master and the release preset on Linux with GCC and no native optimizations, and for simplicity I'm switching the Dictionary backend between a map, unordered map and flat map / vector. I also included map and unordered map results without interning, as those avoid an extra lookup (whereas our flat map search was designed to support it without that extra lookup when inserting (and also because hashing has to reconstruct the string from the char array in the unordered map).
<details>
<summary> Results</summary>

### Built-in benchmark results:
1. flat map:
```
84: benchmark name                       samples       iterations    est run time
84:                                      mean          low mean      high mean
84:                                      std dev       low std dev   high std dev
84: -------------------------------------------------------------------------------
84: Dictionary::Get()                              100             4     2.4552 ms 
84:                                         21.4163 us    20.5019 us    25.5292 us 
84:                                         8.45593 us    654.492 ns    20.0081 us 
```
2. map (`const char *` keys):
```
84: benchmark name                       samples       iterations    est run time
84:                                      mean          low mean      high mean
84:                                      std dev       low std dev   high std dev
84: -------------------------------------------------------------------------------
84: Dictionary::Get()                              100             3     2.6277 ms 
84:                                         42.8684 us    41.1982 us    47.1552 us 
84:                                         12.3271 us    2.70938 us      22.36 us 
```

3. map (`std::string` keys, so without interning):
```
84: benchmark name                       samples       iterations    est run time
84:                                      mean          low mean      high mean
84:                                      std dev       low std dev   high std dev
84: -------------------------------------------------------------------------------
84: Dictionary::Get()                              100             3     2.5368 ms 
84:                                         39.7182 us    38.9756 us    43.0577 us 
84:                                          6.8788 us    853.852 ns    16.2912 us
```

4. unordered map:
```
84: benchmark name                       samples       iterations    est run time
84:                                      mean          low mean      high mean
84:                                      std dev       low std dev   high std dev
84: -------------------------------------------------------------------------------
84: Dictionary::Get()                              100             2     3.3958 ms 
84:                                          158.68 us    156.993 us     164.09 us 
84:                                         13.5551 us    2.35441 us    29.6879 us
```

5. unordered map (`std::string` keys, so without interning):
```
84: benchmark name                       samples       iterations    est run time
84:                                      mean          low mean      high mean
84:                                      std dev       low std dev   high std dev
84: -------------------------------------------------------------------------------
84: Dictionary::Get()                              100             2     3.7252 ms 
84:                                         143.939 us     142.61 us    147.393 us 
84:                                         9.86198 us    1.85271 us    19.7698 us
```
</details>

> Before it was a class that related to std::vector<std::pair<const char*, double>>, now it is a new class, that is defined as:
> template < class Key, class Value, class ThreeWayComp = std::compare_three_way, class Alloc =
		std::allocator<std::pair<Key, Value>>>
class FlatMap : private std::vector<std::pair<Key, Value>, Alloc>

The normal `std::map` is defined as
```
template <typename _Key, typename _Tp, typename _Compare = std::less<_Key>,
	    typename _Alloc = std::allocator<std::pair<const _Key, _Tp> > >
    class map
     {
    public:
      typedef _Key					key_type;
      typedef _Tp					mapped_type;
      typedef std::pair<const _Key, _Tp>		value_type;
      typedef _Compare					key_compare;
      typedef _Alloc					allocator_type;
      [...]
     }
```
This is exactly the same thing, except it has readable names out of the box, and uses a three-way comparator instead of a two-way comparator. If people understand `std::map` they should understand `FlatMap`; in fact, just changing the type name should work out of the box unless a custom comparator type was defined.

Also, Dictionary being a vector is an implementation detail; in its function, it has always been a map. Having it extend a map-like structure might even make more sense.

> Until you show me where you actually want to use it I do not see the point of extracting it and making the code more difficult to read.

#5699 and #5748 both have some examples. We can also test other maps' performance and replace them as necessary. (Especially if we can populate them before usage, as the gains in lookup  times are much greater than in insertion.) For instance, nested attribute lookup with standard maps too around twice as long as it took with the string-based dictionaries previously, which is in line with the above benchmark.

**Comment by RisingLeaf** [comment]
> This is exactly the same thing, except it has readable names out of the box, and uses a three-way comparator instead of a two-way comparator. If people understand std::map they should understand FlatMap; in fact, just changing the type name should work out of the box unless a custom comparator type was defined.

Yes but one is inside the std and one is inside our code that we have to maintain.

When I said I want some stats I wanted to know what impact these changes would have on the game as a whole, I can not really decide if a change is worth it from looking at micro seconds a function call takes when I do not know how much that is of the entire games performance. It might be just micro optimization until then.

Also, what is your answer to this:

> My entire point is, that you have opened various PRs lately that introduce complex data structures (complex meaning more than a beginner to intermediate c++ programmer might understand), these might make sense for the concurrency PR, that is why I did not argue about such actions there, but in this case I fail to see the benefit of doing something like this. And correct me if I am wrong but I thought the goal was to keep it easy for others to get into the code, this makes it more difficult, even for experienced coders. Why? Because if I see a std call inside es that I do not remember, I can just go onto the cpp reference to look it up, if it is a es custom class, I will have to open the class and read the code and then understand what it does, extra steps that cost time.

Which is my central point here.

**Comment by yjhn** [comment]
Only tangentially related, but is there anything preventing us from using `enum class Something` instead of `const char *` as key types for the dict/map? Using enums should provide much better performance + typo safety than strings. AFAIK all the keys are known at compile time, so this should be an improvement on all fronts.

**Comment by tibetiroka** [comment]
I don't believe the keys are known. You could define any arbitrary string as an attribute, which would be stored in a Dictionary.

**Comment by yjhn** [comment]
Can the game use that custom property in a meaningful way?

**Comment by tibetiroka** [comment]
Yes. For instance, `spinal mount` is such an attribute; it enables adding the Dragonflame Cannon to ship, but has nothing to do with the engine code.

**Comment by petervdmeer** [comment]
> This PR extracts the flat map functionality from Dictionary, making it usable with different types.

RisingLeaf gave a lot of good arguments on the costs of this change, but the benefits are less clear to me. Do you have a concrete list of maps in the codebase where replacement by this "faster lookup at the costs of slower insert" map would be beneficial?

> Various uses of std::map could be sped up using the new flat maps.

Sure, but it will come at the costs of maintaining our own FlatMap, so I would like to estimate the concrete benefits to offset the concrete costs which RisingLeaf described already quite well.

We might even remove the Dictionary specific map in the future; because only part of the attributes are performance critical, and we could store the fixed-list of performance critical attributes in a faster data-structure, like a fixed-size array, and store the remaining attributes in a regular map.

**Comment by tibetiroka** [comment]
I don't really have the time to maintain this right now. I'll reopen this when I have more time, and if this actually proves useful in real use cases.

**Pull request closed without merging**
