### PR TITLE
Fix: A spelling mistake and contractions outside of conversations

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR addresses a spelling mistake reported by Lord Insane on Discord, as well as a bunch of contractions used outside of conversations.

## Fix Details
- On line 564 the Quarg says "but i must advise you to be careful..." which is corrected to "but I must advise you to be careful..."
- 17 lines changed that had one or more contraction, but were not used in a conversation (instances of: don't, you're, she's, you'd)

No wording was changed, only expanding contractions so they are, well, no longer contracted. No contraction inside a conversation was changed.

### CODE REVIEW

**Comment by Amazinite** [comment]
> 17 lines changed that had one or more contraction, but were not used in a conversation (instances of: don't, you're, she's, you'd)

Not sure where you got the idea that we avoid contractions outside of conversations. 

https://github.com/endless-sky/endless-sky/blob/b86d2e289a43d5ca34a768170976be235ea3bc77/data/human/free%20worlds%20reconciliation.txt#L56

https://github.com/endless-sky/endless-sky/blob/b86d2e289a43d5ca34a768170976be235ea3bc77/data/human/free%20worlds%20reconciliation.txt#L424

https://github.com/endless-sky/endless-sky/blob/b86d2e289a43d5ca34a768170976be235ea3bc77/data/human/free%20worlds%20reconciliation.txt#L1299

https://github.com/endless-sky/endless-sky/blob/b86d2e289a43d5ca34a768170976be235ea3bc77/data/human/free%20worlds%20reconciliation.txt#L1622

https://github.com/endless-sky/endless-sky/blob/b86d2e289a43d5ca34a768170976be235ea3bc77/data/human/free%20worlds%20reconciliation.txt#L37

I'm down with such changes for the log entries, because I feel like it fits the tone better, but the other changes are unnecessary.

**Comment by Zitchas** [comment]
I got the idea from the fact that I've had a *lot* of contractions fixed in my writing over the past  year or two. Enough so to feel like it was pretty much a rule that we don't use contractions in text - just in conversations.

**Comment by Amazinite** [comment]
Line 598, the quotation should end with a comma instead of a period.

**Comment by Zitchas** [comment]
OK. Well, it's easy enough to remove those changes, then.

**Comment by Amazinite** [comment]
> OK. Well, I suppose it comes down to desireability, then. Does removing contractions improve the writing? I think it does, usually.

If you want to avoid contractions outside of dialog in your own writing then go ahead, but I'm not making that a requirement, especially seeing as how it's so widespread in the game already. See also: https://github.com/endless-sky/endless-sky/pull/3881#issuecomment-410401067

**Pull request merged**
