### PR TITLE
refactor(content): Separate pug.txt into different files

### PR DESCRIPTION
**Pull request by tibetiroka**
Note: This is a re-PR of #8722, with a file layout matching more closely that of the Coalition, Korath and Quarg (without a separate fleet file). I didn't use the original PR, but it did give the idea.

The copyright headers are all the same as the original one in pug.txt.

@Zitchas brought up that there might not be enough content here to be worth splitting into multiple files; if that's the conclusion, feel free to close this PR. I just wanted to get some better discussion out of this than just 'OP fill out the template' and 'where OP'.

Also, I checked, and the pug file is bigger than the three drak files overall (not counting indigenous). It's still definitely one of the smaller files, though.

~~I might be planning on adding some spaceport news to some Pug planets. Not quite sure yet.~~

### CODE REVIEW

**Review by lumbar527 — APPROVED** [review]
The `pug.txt` file is definitely oversized, in my opinion. The mission file seems a little small, but if other things are breaking up then it should come out too.

**Comment by quyykk** [comment]
> @Zitchas brought up that there might not be enough content here to be worth splitting into multiple files

I'm inclined to agree.

**Comment by Saugia** [comment]
>I'm inclined to agree.

Same here. We decided once already that we didn't want to do it for those reasons. I don't think anything has changed since then.

**Review by roadrunner56 — APPROVED** [review]
Considering #8911, we should probably split up pug.txt so it doesn't get unwieldy. It also makes room for future Pug content in the future.

**Comment by Zitchas** [comment]
I don't see the addition of pug spaceport news as being sufficiently good justification for splitting up everything else.

**Comment by Zitchas** [comment]
In which case, pile it all into one.

**Comment by lumbar527** [comment]
If #8911 gets merged, and this is not, then the `pug.txt` file would be too long.

**Comment by lumbar527** [comment]
How would one file make it easier to find things?

**Review by Hurleveur — APPROVED** [review]
Not my area but I agree with this change for the sake of clarity and coherence with the rest

**Pull request merged**
