### PR TITLE
Fix weird size for Sheragi Archaeology: The Box 2

### PR DESCRIPTION
**Pull request by ziproot**
----------------------
**Bugfix:** This PR addresses issue #8188 

## Fix Details
The size of the box mentioned in "Sheragi Archaeology: The Box 2" is big, and it is unlikely that a box that big could fit in an "unscrupulous backpack." I made the box 1/4 as big in volume to make it easier to hide. (That means the side length is now 1/4 of a meter instead of 1/2 of a meter).

## Testing Done
Looked at the rim archaeology file to see if it made sense with the new size.

## Save File
Just read rim archaeology.

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
> The two of you put the cube in an inconspicuous backpack

Now it seems a bit strange that two people are needed to hold the cube, but I guess this isn't too much a problem since it's alien technology.

**Comment by ziproot** [comment]
Considering that almost every other message involves you carrying it in some way, I should probably correct that.

**Review by EjoThims — APPROVED** [review]
I always just figured it was one of those big single main pocket backpacks, but the change does make the later handling by the smaller Hai seem more reasonable as well, while still being BIG for a portable data unit (compared even to present day human tech).

**Comment by Zireael07** [comment]
> I always just figured it was one of those big single main pocket backpacks 

Me too, but the cube *was* still too big for those

**Pull request merged**
