### PR TITLE
fix: style checker doesn't group similar quotes when checking for leading …

### PR DESCRIPTION
**Pull request by flowers9**
…spaces

**Bugfix:**

## Bug Notes
When the style checker looks for leading spaces, it groups quote marks.  While likely intended to handle cases like `", it also groups "", which can lead to style errors when parsing empty strings (such as happened in #9032).

## Fix Details
Changed the leading quote regex to only match different quote types (so, \`" or "\`, but not "" or \`\`).

## Testing Done
Ran the style checker against both "" and " stuff".  The former was no longer found, while the latter was still found.

### CODE REVIEW

**Comment by tibetiroka** [comment]
Nice catch!

The fix isn't 100% correct, though. It doesn't seem to catch `"" " stuff"`.

**Comment by flowers9** [comment]
It's true, it'll miss that where the original would not (after a fashion - the original actually matches the wrong part of the line).  However, there's very likely  stuff that the original misses, too, simply because it is such a pain to write a nested quotation matcher in regex that finds some stuff and skips other stuff (since you need to match the good stuff to get it out of the way while looking for bad stuff).

**Comment by flowers9** [comment]
More precisely - the original was only intended to check for spaces after the first quote mark (or series of quote marks) - it could never find spaces after subsequent quote marks.  The fact that it matches `"" " stuff"` is an accident, and not intended.  It would not catch

\`After a long journey, " Look out!"\`

for example.

**Comment by tibetiroka** [comment]
I wonder if something like `^[^"]*(("[^"]*){2})*" .*$` could be used as the base of the regex. We would need a separate version for the other quote mark, but I think this should only match spaces that come after an odd number of quotation marks.

**Comment by tibetiroka** [comment]
Yeah, that does seem to work a lot better than the original one. I'll get you a suggestion with the fixes in a bit.

**Comment by tibetiroka** [comment]
If you bring your branch up to date with master, I'll make a PR to your branch and you can merge my changes into this PR from there.

**Comment by flowers9** [comment]
Sure, I guess that works.

**Comment by tibetiroka** [comment]
https://github.com/flowers9/endless-sky/pull/1

**Comment by tibetiroka** [comment]
I checked, the content fixes are actually valid fixes.

**Comment by flowers9** [comment]
Looks good!  I'm amused that it now catches stuff that you had to fix. ;)

**Pull request merged**
