### PR TITLE
Allow planets to define a government.

### PR DESCRIPTION
**Pull request by jmhorjus**
This will allow a planet to be independent of it's system, defining it's own government. 
Planets that do not define a government (i.e. still all of them) will continue to use the government of the system they are in (no change in behavior of existing content).
  
This will allow mods to do a few things they couldn't before, like have planets of different governments in the same system.  There are one or two planets in the main game that might make use of this as well, such as the Quarg outpost "Echo" which is in Tarazed, an otherwise "Republic" or "Neutral" star system.

NOTE: [I've now tested this on my Win32 build and it works like a charm! Echo remains "Quarg" government whether the system is Republic or Neutral and reacts to your actions properly - if you attack a Quarg Ship, Echo becomes hostile while the other planets in the system don't care.]

### CODE REVIEW

**Comment by jmhorjus** [comment]
I added "government Quarg" to the Echo outpost in Tarazed - this should mean you cannot land there if you have angered the Quarg, despite the system having a Neutral government.

**Comment by jmhorjus** [comment]
I got my Win32 build working last night, so this is now tested and confirmed to work!

**Comment by jmhorjus** [comment]
Can this be merged, or if not, how can it be improved? 
I can put the additions to .gitignore in a separate pull request if desired.
I can also remove the change to Echo's government so that it's just a new modding capability being added with no effect on the base game.  
I've tested this and been playing/testing other things on my win32 build that includes this for a while so my confidence in its safety/correctness is fairly high.

**Comment by endless-sky** [comment]
Thanks! Sorry for the delay in merging this - I just didn't have time to test it during the week.

**Pull request merged**
