### PR TITLE
Add reworked Quarg Ringworld sprites

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Makes some smaller tweaks to the normal Quarg Ringworlds (see for reference [#7183](https://github.com/endless-sky/endless-sky/pull/7183)) and adds entirely new sprites for the broken Ringworld in the 'World's End' system. This also includes some changes to the map's data file, although this has only aesthetic effects.

Regular Ringworld:
ringworld3

Broken Ringworld:
worlds end ringworld

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/78
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/300

### CODE REVIEW

**Review by Saugia — APPROVED** [review]
Twizzler

**Review by beccabunny — APPROVED** [review]

**Review by roadrunner56 — APPROVED** [review]
I like how the difference between a broken and incomplete ringworld is made more obvious here.

**Comment by ravenshining** [comment]
Loving the broken one :-)  Could be a sprite with just the floating debris, no structure, for use in Queri?  The ringworld there is supposed to be *gone*, yes, but I think it'd set the scene better to have a few bits in orbit.

The regular one looks unfinished though, what with the exposed girders facing away from the centre.

Also how are these matching up visually with the Coal extensions?

**Comment by GefullteTaubenbrust2** [comment]
I've changed some stuff up slightly. The girders are still mostly unchanged, as not all structures have to be heavily shielded - we had a brief discussion on the main discord about this.

As for the coal, here is the new ringworld:
ring of friendship

Mostly I just changed the solar panels' color to more closely match the coal solar panels, although this wouldn't have to be perfect imo since they are sort of just stuck on to give illusion of actual construction.

**Comment by ravenshining** [comment]
I'm not concerned that they're not shielded, it's that they look like an unfinished framework that's meant to have something built around them.  Why are they even there, unless the ring is planned to be expanded outward?

**Pull request merged**
