### PR TITLE
Created a new Pact Recon 0, for if the player is on Glaze

### PR DESCRIPTION
**Pull request by ph2000bis**
As the mission currently stands, you can be in Glaze and be asked to "report to our base in Glaze". Would be incoherent.

Also made it more likely that the mission starts on Glaze, as it IS their base.

Gave more opportinity to defer, as the playermay want to wait to have a better ship and then do the missions

### CODE REVIEW

**Comment by Amazinite** [comment]
Is a whole new mission really necessary for the sake of one word and a comma?

**Comment by Bladewood** [comment]
We made a similar mission for the Heliarch first contact mission :|

**Comment by Amazinite** [comment]
The thing about that is that whatever mission offers on the Ringworld first needs to include information from the on offer and on complete sections of the current first contact mission, so it'd be a different experience, but for here adding one word doesn't change the experience at all, so I see no need for it.

**Comment by ph2000bis** [comment]
I agree it's not elegant, but I couldn't get any other way to work.
Do you have any ideas?

**Comment by Tadrix** [comment]
Wasn't there something like know branching dialogue options?

**Comment by ph2000bis** [comment]
I tried, but I'm not sure if the game accepts condition `planet Glaze` as a valid condition. It didn't seem to work when I tried, but it might be down to human error.

**Comment by Tadrix** [comment]
Wouldn't it be `planet == Glaze`?
If everything else fails, you could try an invisible mission triggering on Glaze which activates Pact Recon 0 and gives condition, and change Pact Recon 0 so that it activates only when not on Glaze by itself.

However, this whole thing feels unnecessary to me. When she says "base on Glaze", it doesn't imply you aren't already on that planet. I'd instead take out "on <planet>" from "A different female militia officer approaches you when you land on <planet>", because to me it implies you started on a different planet and leave the rest as it is. But it could be me and my not so good English.

**Comment by jafdy** [comment]
Saying "on Glaze" seems fine to me. If you are already on Glaze then the "here" is implicit.

**Comment by ph2000bis** [comment]
As I was just replaying the game from scratch, the phrase struck me as odd. For me, "report to our base in Glaze" makes it more or less explicit that we are not on Glaze. That is just how I feel the text, but I understand that not everyone feels the same way.

**Comment by Tadrix** [comment]
> the phrase struck me as odd

I'll admit that same here, it struck me as such as well, but you're proposing to add an entire new mission to fix something which could be improved with just a better wording. English not being my native language I opted to leave as it is for now. If you have better ideas, you're welcome.

**Comment by endless-sky** [comment]
It seems to me that a much simpler solution would just be to not allow the mission to be offered on Glaze.

**Comment by Bladewood** [comment]
I strongly disagree with that.
If I were offered such a mission, my first instinct on my next playthrough would be to constantly land and take off from Glaze. If it is never offered there, I'd basically be stuck forever.

**Pull request closed without merging**
