### PR TITLE
Quarg react to being farmed

### PR DESCRIPTION
**Pull request by Disiuze**
This PR makes the Quarg react to being farmed.
Sprites done by @mdsmestad, Elderdragon description by Isaac Vaughn.

If you reach -100 rep with the Quarg, they will launch a single Elderdragon in each of their systems and they will also send bounty hunters after you (if you stay in human space).

@2x, .blend and .xcf can be found here: https://drive.google.com/folderview?id=0B3MEAzs3P2WxbjZfR29pcUkwR00&usp=drive_web

### CODE REVIEW

**Comment by Isaacssv552** [comment]
10k hp is far too low, I could probably defeat it with a single kor mereti ship. Also, I've added some stuff to the plugin, which you may want to include.

**Comment by mdsmestad** [comment]
@Isaacssv552 Hmm interesting. Your probably right about the HP too

**Comment by jmhorjus** [comment]
Looks like similar motivation to https://github.com/endless-sky/endless-sky/pull/919

**Comment by toilethinges** [comment]
@jmhorjus - Together, these would add massive depth to attacking the Quarg.

**Comment by mdsmestad** [comment]
@jmhorjus I agree, combing these two ideas might work very well

**Comment by Disiuze** [comment]
@toilethinges I thought the same thing

@Isaacssv552 has also added more content to the pull in the Google Groups and I'm planning on adding that as well so the Quarg not only react to farming but also have more variety to them.

**Comment by egilburg** [comment]
Given all these suggestions significantly impact the storyline, I wonder if @endless-sky can comment on the direction he sees this taking before more work is done?

**Comment by Isaacssv552** [comment]
I've posted a newer version fixing a number of bugs and improving some minor matters. I don't really think the changes significantly impact the storyline. They basically just give the Quarg a wider range of ships/outfits and have them react to the player's incessant attacks. I would be willing to work on a storyline for the Quarg, although I'm not sure I could do it alone, but I certainly don't have one yet.

**Comment by jmhorjus** [comment]
Yeah, these kinds of changes are mostly tangential to the story.  If there was a Quarg story-line, which there may be eventually, I'm guessing that negative reputation with them would disqualify you from it regardless of whether there's any other more interesting consequences for farming them.

**Comment by Isaacssv552** [comment]
I've posted another update with additional bug fixing, some engine tweaks, and additional outfit descriptions.

**Comment by Disiuze** [comment]
@Isaacssv552 If you can make a pull to the pull then that'd be great because I won't have access to my PC until next weekend.

**Comment by Isaacssv552** [comment]
I made another pull because I couldn't seem to fork your repository.

**Comment by Disiuze** [comment]
I think it's best I close this for now, at least, until the interest for it grows.

**Pull request closed without merging**
