### PR TITLE
Add per-ton summary of outfit stats to the tooltip shown for outfit mass

### PR DESCRIPTION
**Pull request by starcatter**
related issue: #4106

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
Wouldn't it be better to compare based on outfit space instead of mass?
Most of the time it's the same, but for example the Hai Tracker Pod has a mass of 8 and needs 19 outfit space.
This might lead players to think the hai tracker pod or generally most secondary weapons are more then twice as good as they really are.

**Comment by starcatter** [comment]
Good catch, I don't often use secondary weapons so I never noticed they work that way. 

It's an easy fix although I don't think either way this would be a particularly useful metric for launchers, using mass we get stats for the weapon alone (and its embedded ammo store), while using outfit space also considers the base ammo capacity. Both make about as much sense if we consider using additional ammo pods - one way, we get a seemingly efficient weapon which may take up a huge amount of space due to its ammo, the other we see weapons become less efficient as we add ammo pods.

Also, I spotted a bug where secondary weapons don't get all stats displayed, so I'll try to fix that while we figure out the best way of approaching this.  Maybe also extend the tooltip for outfit space?

2019-01-03 03_26_29-window

**Comment by IntegratedQuantum** [comment]
> Also, I spotted a bug where secondary weapons don't get all stats displayed.

You need to change your `tooltipStats` every time `attributeLabels` and `attributeValues` are changed.
You currently just use the weapon stats which are part of `VALUE_NAMES`.

**Comment by Amazinite** [comment]
>Both make about as much sense

What you have to realize though is that outfit space and by extension weapon space is a limiting factor while mass is not. Knowing stats over outfit space is more important than knowing their stats over their empty mass.

**Comment by endless-sky** [comment]
This feels to me like it would just overwhelm new players with unnecessary information. And even for experience players, a lot of those stats aren't going to make sense. (Like, why is firing energy per ton an important consideration?)

And on top of all that, per ton of mass isn't the right way to calculate it. The launchers are a good example of that: their mass is less than the space they take up because the ammo has mass, too.

**Comment by Amazinite** [comment]
Closing as this steps into the realm of providing too much information. Any efforts to show more stats like this should probably go into creating an advanced stats page. Ref: #4215.

**Pull request closed without merging**
