### PR TITLE
Changed the NPCs in Terraforming 11 from bounty hunters to pirates

### PR DESCRIPTION
**Pull request by Amazinite**
For the entire terraforming string of missions, this is the only point in which there is any combat. Given the fact that a player can very easily reach this point without a very powerful ship or even any combat skills. I've swapped the NPCs that you have to fight from bounty hunters to pirates, meaning that the player must no longer take on these NPCs solo and will be supported by nearby merchants and any Navy fleets that enter the system.

### CODE REVIEW

**Comment by tehhowch** [comment]
Do you happen to have those possible fleet tables already prepared? Base `map.txt` and also after any possible changes during the campaign?

**Comment by Amazinite** [comment]
You have the right PR?

**Comment by tehhowch** [comment]
You mentioned that the player could receive help, so I thought perhaps you had also quantified what help may be possibly received.

**Comment by Amazinite** [comment]
I’m simply referring to the random fleets that enter the system, in the same way that a player taking an escort job can travel to a populated system and have the merchant and law enforcement fleets destroy the pirates for them. If a player reaches this point in an interceptor, it doesn’t become game over if the government of the NPCs is something others will attack.

**Comment by tehhowch** [comment]
I too am referring to the random fleets that enter the system.
If the average credits per second of help is too high, then I think an alternate path is better: keep Bounty, lower the base enemy strength, and use a "reenforcements" mission if the player warrants it

**Comment by Amazinite** [comment]
/shrug
Aside from this one instance, this entire string of missions is entirely non-combative. I'd rather it be too easy than to hard.

**Comment by Fzzr** [comment]
Looking at Cebalrai in the data files, it has non-Pirate combat fleets ranging from "Small Militia" at the beginning of the game to "Large Republic" after the battle of Alioth.

**Pull request merged**
