### PR TITLE
enhancement: adds advanced leviathan and falcon variants

### PR DESCRIPTION
**Pull request by LocalGod79**
not for sale in shipyards, 3 slightly modified variants of underused heavy warships (with unique sprites, thanks to Wrzlprnft) currently only acquirable through capture (expect death benefits), spawning only through 3 rare bounty hunting jobs (which make the better variants even rarer), and one invisible mission
that spawns player hunters, 3% on landing.

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
As far as i got it, some of the engine and gun ports are not there where they should belong... yet. Do not merge.

**Comment by lehgogh** [comment]
Branch conflicts?

**Comment by LocalGod79** [comment]
#586

**Comment by LocalGod79** [comment]
i've looked more closely, and there does not actually appear to be a conflict - the other branch modifies the existing ships.

this branch adds six unique ships (not variants, per coding) that are significantly different enough to warrant new sprites, new ship type and alternative acquisition method.

indeed, some of the balance points in the other branch take elements of these ships in the opposite direction.

that said, it does appear that some of the engine flares and gun ports are misplaced (that's how different) - will repost when it's fixed.

**Comment by jmhorjus** [comment]
The conflicts are likely because your forked master branch is behind the real master branch by 28 commits (missing all the changes that were made since you forked it or last did a "pull endless-sky master"). 

To resolve the conflicts, you can try:
1.)"pull endless-sky master"
2.)There will likely be one or more files with conflicts in them, which you'll have to look through and resolve in your local directory. Google "resolving conflicts in git" if necessary.
3.)Once the conflicts are resolved, make sure everything is kosher before you commit the changes to your local repository (if you're on windows make sure no image files were randomly deleted during the merge). Then "git push" them up to your advanced-leviathan-falcon-missions branch.
4.) Come back to this page, and inspect the "files changed" page to make sure it looks the way you'd expect and (hopefully) now says it can be merged without conflicts.

**Comment by LocalGod79** [comment]
i'm running into complications i don't know how to resolve.

would it be possible for this request be nixed and i start over by inserting the relevant code into an up-to-date master?

**Comment by jmhorjus** [comment]
Yeah. Git can be tricky. You need to be on the master branch of your fork and just do "git pull endless-sky master", then "git push" (do you use a git primarily from a command line or through a graphical interface? what OS?).  

Once your "master" is synced with the main "master" then any "branch" you create _from_ your master should be up to date and conflict free.

**Comment by LocalGod79** [comment]
i am learning git as i go, so "primarily" is a stretch...lol

i'm using mac os x yosemite, and i've downloaded (and am learning to use) the git desktop client.

**Pull request closed without merging**
