### PR TITLE
Could it be this simple?

### PR DESCRIPTION
**Pull request by LocalGod79**
possible negative shield energy fix - negative attribute exception

apologies if it’s sloppy - been almost 20 years since i had a compiler
open…

### CODE REVIEW

**Comment by LocalGod79** [comment]
#896

**Comment by LocalGod79** [comment]
i'm sorry - really going to start testing these before pulling. (the dialog doesn't come up anymore, but you still can't buy it)

**Comment by endless-sky** [comment]
I've checked in a fix for the shield energy (33a1999). It requires all shield generators to specify how much energy they use, but it makes the math a whole lot simpler and cleaner than any other option I could think of.

**Comment by LocalGod79** [comment]
i think in the long run, this is probably better than you had hoped...

if the previous iteration had worked, it would have been possible to create a shield-generator-reactor, which actually only generated power while recharging shields - a neat concept, but broken in implementation - no longer possible...

**Pull request closed without merging**
