### PR TITLE
Moved M. Fury to persons

### PR DESCRIPTION
**Pull request by Nescio0**
<s>Although I understand the Marauder Fury's need to defend itself, I think having it equipped with three Quarg Intrusion Countermeasures is hard to explain, lore-wise. This proposal replaces them with ordinary human laser rifles. There is no space (0/240) for security stations.</s>

Because it's a unique person ship, this proposal moves the M. Fury from the `marauders.txt` file to the `persons.txt` file to avoid unnecessary confusion.

### CODE REVIEW

**Comment by Amazinite** [comment]
The Marauder Fury is a person ship, so I don't see the need to remove its intrusion countermeasures. This also makes the Marauder Fury considerably easier to capture, and it's intended to be a difficult capture.

**Comment by kikotheexile** [comment]
The mfury in general, much like MZ's Kestrel, is a special ship that can freely break a few of the rules of the lore.

**Comment by Nescio0** [comment]
It is the only Marauder which has Quarg technology. The M. Arrow (crew 2/5) has only laser rifles, the M. Raven has no hand-to-hand weapons at all.

**Comment by Amazinite** [comment]
It is also the only Marauder that is a person ship.

**Comment by Nescio0** [comment]
> It is also the only Marauder that is a person ship.

Why is it here and not in the `persons.txt` file then?

**Comment by Amazinite** [comment]
That's a question for Local or Wrzl, who were the ones who made the Marauder ships.

**Comment by Startome** [comment]
Truthfully being a person ship, I think it should be harder to capture or uncapturable. That said I don't think that idea will find much support

**Comment by tehhowch** [comment]
I would place the ship definition below the person for whom it is used, rather than at the end of the file.

**Comment by Wrzlprnft** [comment]
i think it's just a remnant of how local made that stuff: it was probably a normal marauder ship before he had the person idea.

**Comment by Startome** [comment]
Yeah I really haven't had any problem right now with it set up as is. Any raider or baccy can easily capp it, it isn't too hard. My shield beetle could even capp it.

Nice to see you wrzl hope you are well.

**Pull request merged**
