### PR TITLE
enhancement: introduce variantName to Ship class

### PR DESCRIPTION
**Pull request by EndrosG**
This PR is a first step towards making the game aware of the variantNames of ships.
Making the game aware of variants has been commented several times in different issues and has been brought up in the last half hour on Discord again in some debugging stuff.

### CODE REVIEW

**Comment by EndrosG** [comment]
@tehhowch tested the change in Line 347 - Ship::FinishLoading() - and now the warning about an unrecognized outfit tells the name of the variant and not just of the (base) model.

The testcase I gave to @tehhowch :
[mining_ships.txt](https://github.com/endless-sky/endless-sky/files/1023883/mining_ships.txt)

> Unrecognized outfit in Shuttle (mining) ""

which refers to the "Tiny Mining Laser"

**Comment by tehhowch** [comment]
Works great. Fleet writer tool gives this for all the game's fleets, after being made variant-aware:
[es_fleets.txt](https://github.com/endless-sky/endless-sky/files/1023894/es_fleets.txt)

**Comment by endless-sky** [comment]
The Ship class is already such a monster that copying one more string in every ship isn't a huge deal, but if this is only for reporting errors in FinishLoading I think a better approach would be for it to not be publicly accessible and for the string to be cleared after FinishLoading() is done.

Even better would be if instead of a variant name, the string contained the entire DataNode trace of the ship, i.e. what would be shown by PrintTrace().

**Comment by tehhowch** [comment]
If a ship knows what variant it is, the game can look up the correct description if the ship itself doesn't remember (e.g. the ship was loaded from a save file). Marauder ships are the biggest offender here.
In #3070, ship descriptions are made significantly more visible, so having them be the correct version is helpful.

**Comment by endless-sky** [comment]
I don't see enough of a use case for this for it to be worth adding.

**Pull request closed without merging**
