### PR TITLE
Added a small dragon pod to the image for Skymoot

### PR DESCRIPTION
**Pull request by DrBlight**
I decided to make the image for Skymoot a little more exciting in order to match the description. If everyone likes this change, I may be able to do more. I'm likely to get better at it as I go along, too. I've made a high DPI version as well, found here: https://github.com/endless-sky/endless-sky-high-dpi/pull/37

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
ya know how every image in the game is a .png? I see .jpg, and they lose quality a lot

**Comment by tehhowch** [comment]
@KiLEdEnNis landscapes are generally jpg format.

**Comment by jafdy** [comment]
It's quite good, but my first reaction upon seeing it was to laugh, not really what we want people to be doing. I think the problem is with the dragon, perhaps a group in the distance would be slightly better. Also the city doesn't look too good, I'm guessing it hasn't been post-processed. 
The jpg is fine for photos but really you need png for computer graphics (like the city).

**Comment by KiLEdEnNis** [comment]
@tehhowch my bad then, was on phone so couldn't check

**Comment by Amazinite** [comment]
I don't think the city is necessary, and the dragon probably shouldn't be that close in the foreground. Check out one of those gas giants that the Void Sprites are around; one of the landscape images has the Void Sprites in it, but they aren't exactly that easy to spot *at first glance.*

**Comment by KiLEdEnNis** [comment]
to me the city, and especially the dragon, don't look that real
removing the dragon and adding some in the far distance already fixes it a lot

**Comment by DrBlight** [comment]
Not to worry, I anticipated reactions like these. I'm an inexperienced painter and I'm probably not up for publishing matte paintings as of yet. I'll try a different approach like the ones suggested and we'll see how it looks.

**Comment by KiLEdEnNis** [comment]
are you using [GIMP](https://www.gimp.org/downloads/)? it's the "paint" program we use for stuff like post-processing ships and basically all "drawn visuals"

**Comment by DrBlight** [comment]
I use Krita, another open-source program. I'm pretty sure there are no proprietary hangups anywhere along the line, as the original photo is public domain and I define anything I paint over it as also being in the public domain.

**Comment by endless-sky** [comment]
I'm horrible at freehand drawing, but I'd suggest something more like a distance, subtle silhouette rather than a big cartoony dragon in the foreground:

sky2

**Comment by KiLEdEnNis** [comment]
> I'm horrible at freehand drawing

not at all

**Comment by Amazinite** [comment]
>>I'm horrible at freehand drawing

>not at all

Let the man feel horrible. It's a good motivator for practice (so we can get more good drawings 👌).

**Comment by DrBlight** [comment]
All good suggestions. I'll see what I can do and try it again!

**Comment by endless-sky** [comment]
I was just going for more of an Eastern-looking dragon instead of a purely Western-looking one (i.e. a long, flowy body) because it'd make a cooler silhouette. I suppose it should have legs, but like birds I imagine that dragons would tuck their legs up close to their bodies when flying.

**Comment by MCOfficer** [comment]
tactical dot .
for real, there has to be a "subscribe to this PR" button somewhere?

since i'm commenting anyways, i might as well compliment you for your dragon. think about letting the long, eastern silhouette dive into the clouds somewhere in the background.

**Comment by nylki** [comment]
@MCOfficer 
> tactical dot . for real, there has to be a "subscribe to this PR" button somewhere?

There is, on the right side of the PR.

subscribe_screenshot

**Comment by DrBlight** [comment]
Skymoot, now with 300% greater subtlety! Hopefully this is more acceptable.
sky2

**Comment by KiLEdEnNis** [comment]
still a little big & generic green but a good improvement, I'm fine w/ this pic so unless anyone else has any objection, merge?

**Comment by DrBlight** [comment]
> still a little big & generic green but a good improvement, I'm fine w/ this pic so unless anyone else has any objection, merge?

Yeah, I went with the green because the description says they look "exactly" like mythological dragons. I decided to take that literally, but I'm open to more tweaking in the future.

**Comment by Tadrix** [comment]
I like MZ's version better. Can we have it?

**Comment by KiLEdEnNis** [comment]
personally I'd prefer a darker green but the model ain't bad

**Comment by DrBlight** [comment]
Hmm. Does this look better?
smaller darker

**Comment by KiLEdEnNis** [comment]
looks great, well done
my only concern is the rest of the image looks generally empty, but adding more seems a bad idea in general
adding that the sky has more intense colors on the right, which at least prevents drawing all attention on 1 point, I think this image is good enough to merge

**Comment by Bladewood** [comment]
...
Wait, so should we have another version of sky2, dragon-free?

**Comment by Tadrix** [comment]
Yup

**Comment by endless-sky** [comment]
No, it's only used for this one planet.

**Comment by Amazinite** [comment]
@DrBlight We're currently attempting to track down old asset files to add to https://github.com/EndlessSkyCommunity/endless-sky-assets. Do you happen to still have the assets for this image (e.g. a .xcf file if this was made in GIMP)?

**Comment by DrBlight** [comment]
I'm sorry, I checked through my old backups but was still unable to find it. It's just been too long and I've changed computers twice in this time! I remember that in the end it was just a single paint layer (in Krita) over the original photo, which I hope is still publicly available. I declared the part that I painted to be public domain as well, so anybody can alter it if they want to.

**Comment by Amazinite** [comment]
Well after all this time I suspected as much. Thanks for the reply, though.

**Pull request merged**
