### PR TITLE
feat(content): Add `lingering` to Gegno Protolith Fleet

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Artwork / Missions / Jobs)**

## Summary
The intent of the Protolith is to appear as a very old Gegno Generation ship, lacking a hyperdrive, that spawns very rarely in Heutesl and flies between the planets. The AI under these circumstances either goes to land on the other inhabited planet in the system, or sometimes, it will take off and immediately land back on the planet it takes off from.

Adding the `lingering` personality makes this behavior appear less goofy as the ship will spend a small amount of time longer in space, even if is going to land on the same planet, rather than fly directly back to it.

### CODE REVIEW

**Review by EjoThims — APPROVED** [review]

**Comment by alexrovw** [comment]
This... doesn't appear to do anything based on my testing.

`lingering` seems to add an extra idle period equivalent to 1/4th of the minimum fleet period in that system. Unfortunately, this system has a `Gegno Basic` fleet with a period of 200, which results in a linger time of 50 frames (0.83 seconds). The resulting delay is essentially imperceptible. I'm not sure how you can improve on this behavior without modifying the code. :/

**Comment by Saugia** [comment]
Are you sure you were on the right branch? Did you play test it in-game? When creating this PR, I tested it before opening it, and as I said although small, the delay is noticeable and better than the current behavior, regardless of the small value. Not only that, but other behaviors resulting from this change.

On master, the ships fly directly back to the planet, if that is their choice of landing.

On this branch, if a ship does this behavior, it will almost always glide over the planet at a stall for a second, then again attempt to and successfully land on the planet. Not only this, but another behavior is introduced. Sometimes, while the ship is turning around to re-land at the takeoff planet, they will change their decision and start to fly to the other planet and land there instead. Neither of these behaviors are present on master, and I've tested both for up to thirty minutes by increasing the spawn rate.

I would show footage of the example, but it is too large for Github. Either way, I feel the behavior change to be significant enough that a single personality is worth adding to the fleet. AI and personality changes are out of scope of this PR, which is doing as I have described.

**Comment by Hurleveur** [comment]
https://github.com/endless-sky/endless-sky/pull/8794 this would allow finer control over it

**Comment by Saugia** [comment]
For sure. I mostly felt the change in this PR wouldn't hurt anything and does a bit more of the behavior I'm looking for.

**Review by alexrovw — APPROVED** [review]
Yeah, it doesn't hurt at least.

**Pull request merged**
