### PR TITLE
feat(ui): in-game sandbox for ship design

### PR DESCRIPTION
**Pull request by flowers9**
**Feature:**

## Feature Details
This change allows the player to enter a sandbox-ish Shipyard or Outfitter on any planet (it's accessed from the PlanetPanel).  They can "buy" any ship that would show up on the MapShipyardPanel (subject to license requirements) in the Design Shipyard, and then outfit it with any outfits that would show up on the MapOutfitterPanel (subject to license requirements) plus any other outfits they have installed or in cargo (limited by the number they have available).  Changes made on the Design panels go away when leaving the planet.

## UI Screenshots
It's exactly the same UI as the existing ShipyardPanel and OutfitterPanel, with only the ships or outfits being different, and without access to the player's actual fleet.  The PlanetPanel is slightly changed - when SHIFT is held down, the Shipyard and Outfitter zones (if any) are replaced by Design Shipyard and Design Outfitter.

## Testing Done
Mostly just played around with it and made sure it didn't affect the actual player information (or crash).  Since the design player is the one given to the Shipyard or Outfitter panel, no changes should occur to the player data.  The code to populate the panels is taken from MapShipyardPanel and MapOutfitterPanel, so should be reliable.

## Future Expansion
I'd like to allow the player to play around with ships that they have in their fleet but that aren't available for sale.

## Reason for Existence
Ever tried to spec out a ship in-game, when you want outfits only available in different systems?  This is an attempt to work around that annoyance, plus let people play around a bit without giving away information they don't already have access to.

### CODE REVIEW

**Comment by lumbar527** [comment]
I couldn't access other outfits (and I think this should be more of an add-on rather than an actual in-game thing)

**Comment by flowers9** [comment]
What do you mean by other outfits?  Ones not available in outfitters?

**Comment by lumbar527** [comment]
I only got the New Boston outfitter.

**Comment by MasterOfGrey** [comment]
On the basis that this only allows access to outfits your character already knows where to purchase and/or has in cargo; this is a feature I coulda killed for a few times in the past.

It would be very nice if you could, after designing a ship, get a summary info screen for the ship like you can for your actual ships in the playerinfo panel.
Maybe with different coloured text or something so it's clear that it's a design and not an actual ship.
I'm not sure how hard that would be, but that would be a nice way of being able to screenshot a record of what you want to do.

**Comment by flowers9** [comment]
> I only got the New Boston outfitter.

If you're testing with a new start, then that's correct - the only outfitter you know about is the one in New Boston, so you only get their outfits.  If you fly to a system with an outfitter that offers different outfits, the Design Outfitter panel will show the combined set (that one and New Boston's).

**Comment by flowers9** [comment]
> I'm not sure how hard that would be, but that would be a nice way of being able to screenshot a record of what you want to do.

You can kinda do that in the Design Outfitter by clicking off Show outfits for sale (and storage), although I guess it might show the not-for-sale ones, but the list will be much shorter, at least.

I know what you're saying, though, and the Shipyard/Outfitter panels don't have a good way of showing that, as you say.

**Comment by lumbar527** [comment]
> > I only got the New Boston outfitter.
> 
> If you're testing with a new start, then that's correct - the only outfitter you know about is the one in New Boston, so you only get their outfits. If you fly to a system with an outfitter that offers different outfits, the Design Outfitter panel will show the combined set (that one and New Boston's).

Ah, OK. That makes sense.

**Comment by Saugia** [comment]
I personally don't find this an appropriate addition to Endless Sky. 

I don't like the idea of the player being able to figure out a ship build remotely at any time without actually having to visit the place that sells those objects or obtaining them in the first place. Yes, this is a QoL sort of thing, but it narrows gameplay noticeably as it indirectly removes exploration and involvement with said location or area of obtaining the outfits, since all you're doing is focusing only on the specific locations after you put something together.

If you want to go for a more in-universe answer, to me it doesn't make sense you'd be able to confidently sit there at any given planet with an outfitter and 100% know how a given alien outfit, likely from another corner of the galaxy, is going to fit your build without actually having hands-on capability to work with it.

Ultimately I don't think we need every single bit of QoL in the game as it starts to detract from other sources such as plug-ins or extensively made documents. There are many plug-ins out there that are specifically for helping build your ship and testing builds, and there are many documents that record outfits in detail, possibly even ones that can help create builds. Also, the community itself loves to discuss and help with builds on the side.

Feel free to disagree with me, but in my opinion, this is a bit of feature creep and unnecessary. I understand the desire for it, but I don't agree with it.

**Comment by flowers9** [comment]
I appreciate the comment!  As a newcomer, I'm kinda uncertain about the culture here, so I wasn't sure if this was something that should be in the game (and I couldn't find any discussion of this sort of thing).  But it was easy to make by repurposing existing ui bits, so I figured I could put something here that people could actually play around with and see what they thought.  I'm fine with it not going into the actual code.

Myself, I've got a perl/c++ ship optimizer I use for my own builds (and I'm not gonna try and put that in the game ;).

**Comment by Saugia** [comment]
Well, welcome to Github! Bear in mind that I'm only one voice. It may turn out that there's an overwhelming desire for this feature, or it may turn out that the other devs agree with me. This is just simply my own opinion.

We don't really have a good display of what we feel is appropriate for the game or not, and one of the other devs is planning on working on a sort of guideline for this sort of thing to help newcomers and veterans alike.

**Comment by flowers9** [comment]
> There are many plug-ins out there that are specifically for helping build your ship and testing builds

Could you point me at one/some (honestly asking here, I don't know anything about plugins)?  I looked around for plugins, but I didn't find anything quite like this (a limited sandbox ship design).  "All Content" has obvious spoiler issues, from the sound of it.  https://github.com/Hecter94/EndlessSky-PluginArchive might well have some, but I'm not sure I want to wade through >400 plugins to find them ( did browse through some likely sounding categories, but no luck).

**Comment by Hecter94** [comment]
> Could you point me at one/some

The big ones that I'm aware of are:
https://github.com/EndlessSkyCommunity/world-forge
https://github.com/endless-sky/all-content-plugin
https://github.com/Adde-Endless-Sky-Mods/-Omnis

Though there are more as well. 

With that said, I personally disagree with Saugia's assessment here. 
Seems to me that all this does is remove some of the tedium of trekking all over the galaxy to places you've already been by taking information that the player already has access to via the map panel and makes it easier to work with without needing to alt-tab and manually plug the information into a spreadsheet or something. 

There's no functionality added by this PR that couldn't be achieved by manually calculating everything yourself; simply allowing the game to do the calculation for you is a nice QoL feature that doesn't detract from exploration or require giving the player access to any information more than what they already have.

**Comment by flowers9** [comment]
> On the basis that this only allows access to outfits your character already knows where to purchase and/or has in cargo; this is a feature I coulda killed for a few times in the past.

This is something I feel those other plugins don't offer, though.  They certainly do allow you to try lots of different ship designs, but they also tend to give away a lot of information (from the descriptions, anyway, I haven't tried them myself).

That said, I do feel my attempt isn't quite right - the way to access it (using SHIFT on the PlanetPanel) feels kludgey.  I just haven't come up with anything better. ;)

**Comment by Hecter94** [comment]
> > On the basis that this only allows access to outfits your character already knows where to purchase and/or has in cargo; this is a feature I coulda killed for a few times in the past.
> 
> This is something I feel those other plugins don't offer, though. They certainly do allow you to try lots of different ship designs, but they also tend to give away a lot of information (from the descriptions, anyway, I haven't tried them myself).

You are correct. I also don't feel the plugin argument holds much weight for the reason you've given and several others.

**Comment by Hurleveur** [comment]
Maybe we should only enable this in debug mode or make it a setting or smth?

**Comment by Hecter94** [comment]
This would be most useful for newer players, who may not yet understand what exactly the various outfits do and don't want to spoil themselves by using one of the all-content plugins. 
Locking it behind debug mode, therefore, runs counter to that purpose. 
If someone wanted to use debug mode for this feature, they'd install one of the all-content plugins, which would give similar functionality and additional functionality which is also likely to be useful for debugging.

**Comment by Hurleveur** [comment]
If its for newer players then we definitely need an icon to click or smth visible

**Comment by Zitchas** [comment]
This sounds interesting. Actually, this sounds like a vastly more interesting, usable, and useful variant on the "outfit" tab of the map. Just to avoid confusion I'd recommend having it available from somewhere that isn't already an outfitter, though. Perhaps from the player's info / ship panel, perhaps? Then it has the added benefit of allowing me to play with outfit combinations sometime when I may not have access to an outfitter at all, and thus inform my choice of what outfitter I travel to.

**Comment by flowers9** [comment]
I like that idea - it seems like a more natural place to put it.  I had been playing around with putting small "Design" buttons to the right side of the Shipyard/Outfitter buttons (and limiting access to planets with those).

**Comment by flowers9** [comment]
For the moment, I've moved the design buttons to beside the shipyard/outfitter buttons while I see about finding a better place.  I'm thinking perhaps another tab on the PlayInfo/ShipInfo panels, although that's probably going to be a bit of work on my part. ;) 

Screenshot from 2023-07-06 10-20-14

I've also modified it so that it copies over the existing player fleet (actual copies, so changes won't modify the real ships), and doesn't put installed outfits into the player cargo (since they can now be stripped from the copied fleet ships instead).  One trouble is updating design ships when the player ships get their outfits changed - don't want to do it automatically, as that might discard stuff the player wants.  I'm figuring putting a "Reset" button on the Design panel to re-copy the player fleet.  For now, it resets when the player leaves the planet.

**Comment by flowers9** [comment]
>It would be very nice if you could, after designing a ship, get a summary info screen for the ship like you can for your actual ships in the playerinfo panel.

I've got an approach for this in #9002, which would list the installed outfits in the rightmost panel for the currently selected ship, right under the Attributes info.  (As that was something I'd been feeling the lack of before even starting on this PR, I put it in its own PR.)

**Comment by flowers9** [comment]
Moving this to the PlayerInfo tab group is proving to be a major code change, as I have to support a new tab panel.  But that also means it's a lot more flexible of an interface than piggybacking off the Shipyard/Outfitter buttons.  This is current interface, although it needs to be cleaned up a little and there's plenty of functionality I haven't added yet:

Screenshot from 2023-07-07 13-59-01

I've done my best to preserve the style and look of the various UI bits I need to change (mainly the tabs at the top, but also the buttons at the bottom).  Whoever made those did a nice job, which makes it a pain to make changes to them. ;)

**Comment by Hurleveur** [comment]
The issue with putting it there and only (as in, without smth like a shortcut to go there) is it could be obscure for newer players, also I'm not sure its the best place for it and how it would work for adding new ships to test etc?
Dont get me wrong there for sure is a lot of potential but it also would take a lot of work

**Comment by warp-core** [comment]
I'm not sure this is something the vanilla game should have, or even needs.
A new player is probably just going to be confused by it. They're outfitting a ship but they don't actually have it? Or the outfits?
There's also the issue that just because a player has visited a planet that sells some ship or outfit doesn't actually mean they can practically get to it right now. A new player is probably not going to have a good time traversing the whole of Republic space to get to a Deep Sky or Lovelace Labs outfitter, or Lionheart or Betelgeuse shipyard. Similarly, just because an outfit isn't available for sale anywhere the player has visited doesn't mean they don't have access to one or can't get it. This sort of system would completely ignore outfits exclusive to Korath automata, for example.
I think plugins can do this sort of thing much better. Not only do you actually outfit a ship that you can then fly around and actually try out, the available ships and outfits can be customised much more easily. Several such plugins already exist and have been mentioned by others.

**Comment by flowers9** [comment]
Yeah, clueing in newer players is tricky, to be sure.  I'm not sure, either. ;)

To add new ships, you go to the Shipyard, of course!  (It's one of the bottom buttons.)  To make changes, the Outfitter (Another bottom button.)  Update would copy any player ships not in the design fleet; Reset would copy over the entire fleet, erasing any changes that might have been made to them.

And yes, it will be a fair bit of work, which is why I put a snapshot here, to see what people thought about this approach.  Perhaps I should put something in the a Discussions forum?

On the plus side (for you all), if I'm working on this, I'm not bugging you with other PRs. ;)

Although, that said, I noticed that the button layout on the PlayerInfoPanel and ShipInfoPanel aren't quite aligned with each other...

**Comment by flowers9** [comment]
Eh, fair enough.  It's been fun working on it, though.

**Comment by Hurleveur** [comment]
@flowers9 dont worry, you're not bugging anyone with PRs, creative energy is always good to have.
The thing is that for big PRs it's often a good idea to first open an issue discussing the problem and the suggested solution, letting it around for a bit and then opening a PR (or, well, straight up opening PRs that address already existing issues or reviewing PRs if you feel like it)
When opening one like this, you may lose some time because of it, like here (then again, coding is fun).

**Comment by Zireael07** [comment]
Pity it got closed, I think it would've been a good idea to show the players how many options are there... (and lessening the reliance on outside sources)

**Comment by flowers9** [comment]
Yeah, and my personal game of ES will have it, but I can read the writing on the wall - I just wasn't able to figure out a way to put it in the game that works.  It feels like there should be something, but both approaches I came up with are clunky.  (Which I suppose shows that I am not a game designer. ;)

Amusingly, the first approach (which is what I'm using personally) took very little code, as this turns out to be a natural outgrowth of the the existing shipyard and outfitter.  The second approach (the design tab) was quite a bit more bulky, code-wise.

Sadly, this kind of thing cannot be done as a plugin, as it requires processing player data (to limit which ships and outfits are available), which I hadn't realized - plugins turn out to be non-code, which is understandable.

Anecdotally, when my new start got enough money to afford atomic engines, it was very handy to have, since I ended up pairing one with a chipmunk, and those aren't sold that close to each other (rather than another atomic, as I couldn't find the power and cooling for that combo).  I would not have wanted to do that design process either by hand or in game without the designer.

**Comment by MasterOfGrey** [comment]
> A new player is probably just going to be confused by it. They're outfitting a ship but they don't actually have it? Or the outfits? 

I think you're probably being ungenerous to potential new players. Most sci-fi games I've encountered in recent years have had some kind of design feature, frequently as a necessary step prior to construction/fitting.

I would go so far as to suggest that we're on the verge of being the odd ones for *not* having a feature like this.

> There's also the issue that just because a player has visited a planet that sells some ship or outfit doesn't actually mean they can practically get to it right now. A new player is probably not going to have a good time traversing the whole of Republic space to get to a Deep Sky or Lovelace Labs outfitter, or Lionheart or Betelgeuse shipyard. 

That's a decision they can make for themselves though...

> Similarly, just because an outfit isn't available for sale anywhere the player has visited doesn't mean they don't have access to one or can't get it. This sort of system would completely ignore outfits exclusive to Korath automata, for example.

`plus any other outfits they have installed or in cargo (limited by the number they have available).`
If they have one in their inventory it shows up in this. If they don't have one, that's honestly on them to go get one for planning purposes.

> I think plugins [...].

Ultimately the benefits you're describing are distinctly different from the benefits this provides, and those plugins are not always desirable for specifically the extra features you describe.

**Comment by Hurleveur** [comment]
I do think this would ultimately be a much better option than a plugin, and it would have the advantage of not requiring an update with each new outfit/ship.

**Comment by flowers9** [comment]
While I very much appreciate the continued discussion here, would it be possible to move this discussion to #9014?  Just so people who don't get involved in the PR process could see what's going on and have a chance to comment.

Sorry about not mentioning that I'd taken @Hurleveur suggestion and started a thread on the topic.  I didn't expect people to keep commenting here after the PR was closed (I wasn't even sure that was possible, at first ;).  I do mention this PR in the thread, though.

And I came up with additional ideas, and will be mentioning them in the thread.

**Pull request closed without merging**
