### PR TITLE
Removes the Ubuntu CD run

### PR DESCRIPTION
**Pull request by quyykk**
This PR simply removes the basic Ubuntu CD job. That job isn't very useful because the binary created is only usable on a specific Ubuntu version. For Linux CD releases the AppImage CD is the one to use.

### CODE REVIEW

**Comment by Zitchas** [comment]
So the linux one will work generally across most Linux systems, whereas the Ubuntu specific one will only work on a specific version of Ubuntu?

**Comment by MCOfficer** [comment]
I get that it doesn't have much use (if any), but is there truly any downside to keeping it?

**Comment by Zitchas** [comment]
If it's truly redundant, I don't see a point in keeping it. That being said, why did we establish it in the first place?

**Comment by quyykk** [comment]
It was added right when we began to use GitHub as CD from what I can tell.

>  Is it a stabler build run or something than the regular linux run? I know we've had issues with certain builds randomly failing in the past.

Not at all, currently it is in fact the same as the AppImage job except for a script call at the end that the AppImage job has (which creates the AppImage).

**Comment by Zitchas** [comment]
That is sounding more and more like just duplication of effort with a different nametag. Cutting down on the number of checks that need to run might be a worthwhile benefit for removing such duplication.

**Review by MCOfficer — APPROVED** [review]
> I think that was my bad, I always talked about the AppImage no longer requiring FUSE, but that's not true. It's just that now it is statically linked to FUSE, so you don't need to install it locally anymore (which is what was causing issues). However, you can always extract the AppImage and run it by running the `AppRun` program, yes.

That's "universal" enough for me.

**Pull request merged**
