### PR TITLE
Add "no sound.wav" and fix Archon error

### PR DESCRIPTION
**Pull request by TheGiraffe3**
**Bug fix**

This PR addresses the bug/feature described in issue #10433. 

## Summary
Adds a new `no sound.wav` and makes the Archon throwing errors use it. Split off of #10484 at RisingLeaf's request.

## Testing Done
No more errors when playing without plugins.

## Save File
This save file can be used to test these changes:
N/A

### CODE REVIEW

**Comment by reticent-rem** [comment]
> dumb question, but what happens if you just remove "hyperdrive sound" from the drak ships?

Not at all -- looking at the PR that added them #5044, looks like the "game reverts to the default sounds and effect," which I think would be undesirable for the drak.

**Comment by thewierdnut** [comment]
Rather than adding a new binary file to the repo, and forcing the mixer to process it, what if we must modified Audio::CheckReferences() to look like this:
```cpp
void Audio::CheckReferences()
{
	if(!isInitialized)
	{
		Logger::LogError("Warning: audio could not be initialized. No audio will play.");
		return;
	}

	for(auto &&it : sounds)
		if(!it.first.empty() && it.second.Name().empty())
			Logger::LogError("Warning: sound \"" + it.first + "\" is referred to, but does not exist.");
}
```

Basically, making an empty sound reference an allowed use case, since it behaves as expected here.

**Comment by tibetiroka** [comment]
This was attempted in #10434, but warp has a more comprehensive solution.

**Comment by TheGiraffe3** [comment]
So, does that mean that this PR should be closed?

**Comment by TheGiraffe3** [comment]
Superseded by #10648, which is a better way of making this work.

**Pull request closed without merging**
