### PR TITLE
Xcode build made easy

### PR DESCRIPTION
**Pull request by aglv**
I spent way too much time getting EndlessSky to build on macOS. With this commit, I added the necessary binaries directly inside the project, so feel free to reject the pull request if you want to keep the repository light and free of OS-specific binaries. Notice that I switched the project from dynamic to static libraries.
I also renamed XCode to Xcode, and updated the project file to the latest version of Xcode.

### CODE REVIEW

**Comment by pcordes** [comment]
If Endless Sky did this, it would have to update to track security fixes for all the libraries you've included.  Plus, I definitely don't want a bunch of OS X *binaries* in the git tree.  That's just the wrong way to do it.

If you want to make it easy to install on OS X, write a shell script that checks for dependencies and downloads/installs anything that's missing.  That could be small enough (and independent of upstream changes) to include in the repo.

Or just put this bundle of stuff somewhere and include a link to it in the OS X build instructions.

**Comment by aglv** [comment]
What do you mean in your first sentence?
> it would have to update to track security fixes for all the libraries you've included

**Comment by pcordes** [comment]
If the ES repository includes a copy of a library, then the ES maintainers have to keep that library up to date with bugfixes and security fixes.  If ES just uses whatever the system has installed, the usual mechanisms for people getting security updates for their libraries happens without any effort from ES developers.

**Comment by aglv** [comment]
But for _people_, do you mean users (people that download the game binary release) or developers (people that check out the git repository and compile ES to eventually use the produced binary on their computer)?

I'm asking just to clarify: ES for macOS included _libpng_ and _libturbojpeg_ as part of the distributed bundle (macOS apps are actually directories containing executables, resources and libraries, presented to the user as a whole object). If libpng is updated on the user's computer (at /usr/lib or wherever), when they launch ES, the outdated libpng from /Applications/EndlessSky.app/Contents/Frameworks/ is still loaded when launching ES.

**Pull request closed without merging**
