### PR TITLE
Add remodels of the Remnant cells and Crystal Capacitor

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds a rework for the sprites of the Aeon Cell, Epoch Cell, Millennium Cell and Crystal Capacitor.

remnant power

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/69
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/283

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
While I’m not against this rework per se, I do have to ask the question; what actual gain is there from this?

I think these changes make the various cells *less* identifiable and less visually striking - the clear, bold details of the originals now muted into a clutter of indistinguishable tech parts. The crystal capacitor one is… fine, but doesn’t seem to add much.

**Comment by Zitchas** [comment]
To be honest, I'm kind of agreeing with MasterOfGrey here. They're good images, but they're more *different* rather than strictly *better.* I'd rather use these for "mark II" versions of these outfits rather than just swapping them in as replacements. 

For instance, the old boxes look kind of ramshackle stuff tacked on to make it work. Fits the Remnants early lore of reverse engineering stuff and caring more about results than aesthetics; not to mention showcasing the shift from human manufacturing to more alien processes. The new images look more rounded and smooth and fitting in with their new ships; as if they were the old design that has been revised and improved. 

I do like the new reflections on some of the crystals. Ironically, I think the Crystal Capacitor is the one image I think is best suited to being just a drop-in straight-up improvement for the graphics.

(for the record, I wasn't contemplating having improving Remnant power systems until after chapter 3. Maybe a weak improvement in late chapter 3, so it's not an imminent thing)

**Comment by Zitchas** [comment]
As for the Crystal Capacitor itself, I'm kind of curious as to what it'd look like with a purple coloration. It has always struck me as a little odd that it's purple or shades thereof everywhere (Keystone, ships, power generation, etc.), but then is quite strikingly Pug-shaded yellow/orange for the capacitor. 

I'd be quite interested in seeing it have a more matching color. I don't know if it'd be a good look, so I'm not saying I want the capacitor definitely changed to match; but I am curious to see what it looks like.

**Review by Saugia — COMMENTED** [review]
I have to agree with Grey here, the new cells look a bit more....industrialized. While I do love the look of them individually a lot because of the detail, I feel they don't entirely fit the Remnant design style (more like Korath or Human at this point). This is one of those cases I think extra details *aren't* necessary, in order to stay within the design style of the faction.

The capacitor does look a bit better, but the patchiness of the texture feels off especially on the left large on, and similarly to the cells, I'm not sure it needs the extra details like the wires coming off of it.

**Pull request closed without merging**
