### PR TITLE
Use TBB for threading instead of std::threads.

### PR DESCRIPTION
**Pull request by quyykk**
## Feature Details

This PR switches our use of threads with the [TBB library](https://github.com/oneapi-src/oneTBB). Doing so has several advantages, which I will list below. 

- <details><summary>Efficient use of CPU threads</summary>Currently we spawn a whole separate thread for everything we need to multithread. But we are currently creating more threads than the CPU even has (the image loading threads use up all of the available threads by themselves).

    TBB creates exactly as many threads as the CPU supports automatically. </details>

- <details><summary>Independent tasks are pooled together and distributed across all threads</summary>Currently if let's say the image loading threads have finished loading all the images but the audio loading threading is still working, then we have an inefficient use of resources: There is only one audio thread responsible for loading the audio files, all the other CPU threads in the mean time remain idle.

    TBB efficiently distributes those tasks so that every CPU thread always has work to do.</details>

- <details><summary>Useful abstractions for multithreading that make the code easier to understand (with less lines of code).</summary>TBB includes very useful abstractions (like concurrent containers) that simplify a lot of code. Condition variables are tricky to understand if you've never encountered them and it's easy to make a mistake while implementing them. This PR completely eliminates every use of condition variables and lots of locks which make the multithreading portions of the code easier to understand.

    Also you might have noticed that this PR results in a net *decrease* of the code.</details>

- <details><summary>Adding parallelism to other parts of the code is very easy.</summary>The engine (also AI, collision detection, ...) does a lot of work that can be easily parallelized. With the current threading model actually doing so is not at all straightforward. But with TBB it's as simple as a call to tbb::parallel_for so parallelize a loop (for example), using every available thread on the CPU to execute the work as fast as possible.</details>

This PR also includes a fix for #6475, since it became very easy to fix.

Just to be clear: This PR simply switches the current threading code with TBB. There is no additional parallelism introduced (those are for latter PRs).

The immediate (and possible deal-breaker) disadvantage is the fact that we add yet another dependency to the game, when building and when running. Additionally, this PR requires a newish version of TBB that isn't available in Ubuntu 18. For Windows we can just add the newest version to the win64.dev zip file. This PR is marked as draft cause the additional dependency will cause CI to fail.

Feedback appreciated!

## Testing Done

Played the game a bit. I also ran a thread sanitizer to verify that I haven't accidentally added a race condition. 

## Performance Impact

Speedup due to better use of system resources and increased parallelization.

### CODE REVIEW

**Comment by a-random-lemurian** [comment]
Minor question: are we going to just dump the entire TBB source code tree in our tree or do we expect people to go install it on their own?

**Comment by petervdmeer** [comment]
The oneTBB library looks very impressive. Having more parallelism in a safe way sounds very valuable for ES.

I also see a need for contributing developers to learn the "generic programming" that oneTBB relies upon for gaining the true benefits from introducing oneTBB. This should be fine if the learning curve is not too large, if the knowledge is also very valuable outside of ES and/or if less experienced developers can still contribute in the "non-realtime" parts of the code. Could you comment on this?

You seem to know quite a bit about multi-threading. Are there also competing libraries/technologies to oneTBB that we should consider (and how would they compare)?

Another important factor (which you already identified) is the support for oneTBB on all the platform on which ES currently runs. (I believe the Steam environment is older than Ubuntu 18, but maybe there is a backport?)

**Comment by quyykk** [comment]
> I also see a need for contributing developers to learn the "generic programming" that oneTBB relies upon for gaining the true benefits from introducing oneTBB. This should be fine if the learning curve is not too large, if the knowledge is also very valuable outside of ES and/or if less experienced developers can still contribute in the "non-realtime" parts of the code. Could you comment on this?

Yes to all three.

- TBB is definitely on the easier side of multithreading. Check out the new implementation of SpriteQueue.
- It's a popular library as well, so knowledge of TBB is definitely not something only useful while working on ES.
- The experience (currently) is exactly as it is right now when contributing to the non-realtime parts. If we decide to multithread other parts of the engine, then that is something we should address then.

> You seem to know quite a bit about multi-threading.

Not really.

> Are there also competing libraries/technologies to oneTBB that we should consider (and how would they compare)?

So I did find competing libs, but a lot of them either only support a subset of features (like taskflow, OpenMP) or require a lot of boilerplate code (like HPX). Another one that I found that is comparable is Microsoft's PPL, but that one is no longer under active development and is Windows only anyways.

> Another important factor (which you already identified) is the support for oneTBB on all the platform on which ES currently runs. (I believe the Steam environment is older than Ubuntu 18, but maybe there is a backport?)

Yeah. Unfortunately I'm using features that were introduced at the beginning of last year, so even the latest Ubuntu 21 needs to download the library separately. Not really sure how to handle this and/or how big of a deal-breaker this is.

**Comment by quyykk** [comment]
Not going to do this anytime soon.

**Pull request closed without merging**
