### PR TITLE
New "final explosion" sounds for ships to play when they blow up

### PR DESCRIPTION
**Pull request by Pointedstick**
One thing that's dissatisfied me with the soundscape of this game is the lack of big, boomy "final explosion" type of sound when a ship blows up. There's usually a big explosion sprite with no correspondingly impressive sound, and that's been jarring and weird. I've added three such sounds for small, medium, and large ships, and set ships to play them when they finally explode. I really like the difference that this makes. The new sounds are:

Small: http://freesound.org/people/manuts/sounds/319712/
Medium: http://freesound.org/people/ryansnook/sounds/110113/
Large: http://freesound.org/people/CGEffex/sounds/93835/ (with a bit trimmed off the beginning and end)

### CODE REVIEW

**Comment by ph2000bis** [comment]
Have you tested it in a plugin ? If yes, how did you get the source to understand what "final explosion" was to be played at the end of the death cycle and not, say, in the middle ?

**Comment by Pointedstick** [comment]
Take a look at the diff. I added `explode "final explosion {small,medium,large}" 1` at the end of the explosion list for every ship. It works in testing. No source changes necessary.

**Comment by endless-sky** [comment]
The way explosion effects work is that when a ship is dying, any time the game decides to add a new explosion it picks one based on the probability distribution given by the existing explosions. So, it might play this sound when the ship is in the middle of blowing up rather than (or in addition to) at the end.

**Comment by Pointedstick** [comment]
Hmm. It seems to generally do what I expected, but maybe I'm getting lucky. Either way, I think a big dedicated final explosion adds a lot.

**Comment by endless-sky** [comment]
Yes, I definitely like the idea, it's just a matter of making sure it works properly. Like, maybe ships should have a separate "final explosion" effect. Or, I could make the final explosion sound automatically play whenever a ship dies, and pick which sound based on the mass of the ship.

**Comment by Pointedstick** [comment]
Yeah, a separate "final explosion" sound that always plays at the end of a ship's death sequence was  definitely what I was *trying* to do.

**Comment by Pointedstick** [comment]
If you wanna implement this in your own way, let me know if I should just close out the merge request.

**Comment by endless-sky** [comment]
Yes, I'll think about it and come up with a way to make sure those sounds are played just when the ship finally explodes.

Also, note that the CC-BY-NC licenses are incompatible with [Debian](https://wiki.debian.org/DFSGLicenses). Since I want Endless Sky to be available in the official repositories of various Linux releases eventually, anything with a non-commercial CC license shouldn't be used to make sounds for the main game.

**Comment by Pointedstick** [comment]
Oh, good to know.

**Comment by endless-sky** [comment]
I've added support for a "final explode" effect that would make this work correctly.

**Comment by LocalGod79** [comment]
done?

**Comment by Pointedstick** [comment]
Didn't like the sounds?

**Comment by endless-sky** [comment]
I merged them in manually, because they needed to be specified as "final explode" rather than just "explode" (so, just merging this PR wouldn't have worked).

**Comment by Pointedstick** [comment]
Oh okay, great!

**Pull request closed without merging**
