### PR TITLE
Add remodel of the Crystal Capacitor outfit

### PR DESCRIPTION
**Pull request by GefullteTaubenbrust2**
## Summary
Adds reworked sprites for the Crystal Capacitor:
crystal capacitor

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/71
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/287

### CODE REVIEW

**Comment by Hurleveur** [comment]
So this means the crystal capacitators are the same kind of crystals as the ones in the aeon cell?
I was under the impression the two were different, somewhat?

**Comment by Saugia** [comment]
I'll wait to review this until the above is expanded upon as I feel it's important

**Comment by Hecter94** [comment]
> So this means the crystal capacitators are the same kind of crystals as the ones in the aeon cell? I was under the impression the two were different, somewhat?

I would say this recolor/retexture came about as a result of this comment on the original PR:
https://github.com/endless-sky/endless-sky/pull/7116#issuecomment-1214168871

So Zitchas is at least open to the idea of them being colored the same.

**Comment by kestrel1110** [comment]
I dunno, I don't really like this. I liked the old sprite better, and that's because it gets you to think. Now, I have almost zero knowledge on the lore of how remnant tech works, but what I would extrapolate from them being different colors is maybe that one type of crystal holds energy and one generates, or something like that.
Don't get me wrong, it's a very well made sprite, and props to you Gefullte, but i don't really agree with the idea. I'd like to keep it as the yellow one.

**Comment by GefullteTaubenbrust2** [comment]
Perfectly fair. Zitchas asked if I could make it purple, which I did. And tbh I pretty much agree. I think I‘ll just let these be, for now at least.

**Comment by Zitchas** [comment]
I'm of two minds of this. Right now, as things stand, I very much like the looks of the purple crystal capacitor.

1. I think it looks better. I like the sharper edges and other details.
2. I really dislike having a single crystal item being different from everything else.

Now, the caveat is that *if* the Remnant had a large number of crystal stuff, then having a large range of colors would be quite interesting. If crystals were a part of every outfit, with different colors for different sorts of outfits, that would be neat. But we don't have that currently, it's not something I'd put as a priority, either. (I suspect it'd be hard to get crystals into many of those outfits in a way that would look good). And even with that, I'd prefer to see a spectrum more along the lines of different shades of purples, blues, and related colors. Yellow makes me think of Pug, and that's just a *blech* gut reaction from me. Reds and greens would also be good. Given a choice on my part, everything *except* yellows and oranges.

**Review by Zitchas — APPROVED** [review]
I should have put that in here. lol.

Anyway, yes; I like this purple crystal capacitor.

**Comment by Zireael07** [comment]
Why close?

**Comment by Zitchas** [comment]
I don't know, but please don't delete your work. There is probably a place for it elsewhere. I do very much like the look of it.

**Comment by GefullteTaubenbrust2** [comment]
I did not and will not delete anything. I closed because it isn‘t in a state where I am satisfied with it. Might get back to it at a later date, but for now it‘s staying closed.

**Comment by Zitchas** [comment]
Sorry if that came across a bit strong. I didn't mean don't delete *this* branch. It's yours, you can do what you want. I was just expressing that if it doesn't get used for this specific use, the assets for this could be very useful for future content.

**Pull request closed without merging**
