### PR TITLE
edit human AM for better visibility

### PR DESCRIPTION
**Pull request by comnom**
refs: #2970

[assets.zip](https://github.com/endless-sky/endless-sky/files/3070915/assets.zip)

### CODE REVIEW

**Comment by Amazinite** [comment]
Personally not too keen on the change to the basic AM. How about pulling a page from the Bullfrog AM's book and add some sort of plating around the top rim?
image

**Comment by tehhowch** [comment]
Please either update the copyright file, or explicitly state that these works should remain copyright their existing holders.

**Comment by Pointedstick** [comment]
If the regular AM turret's transparent base is part of the problem, than this latest version of the sprite doesn't fix that.

**Comment by comnom** [comment]
>Please either update the copyright file, or explicitly state that these works should remain copyright their existing holders.

Copyright's fine as is.

>If the regular AM turret's transparent base is part of the problem, than this latest version of the sprite doesn't fix that.

The way I read it, not having a base was the problem. I don't think it needs to be solid. The base shows up poorly on a gray checkerboard anyhow. Here it is on white and black.

Old:
anti-missileOldonwhite

anti-missileOldonblack

New:
anti-missileNewonwhite

anti-missileNewonblack

**Comment by Amazinite** [comment]
I think the considerably increase in base thickness is enough to help fix the issue,

**Pull request merged**
