### PR TITLE
More flexible and modular civilian ship names

### PR DESCRIPTION
**Pull request by Pointedstick**
In addition to adding more words and names to various lists, I modularized most of the civilian word lists so that they can be combined in more ways, leading to greater variety.

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
Pointy, if i am allowed to call you that way, i am glad to see you back active!

**Comment by toilethinges** [comment]
Wealthy & Crimson.


...please, that is.

**Comment by Amazinite** [comment]
Awesome.

**Comment by Pointedstick** [comment]
Thanks guys! 🙂 Wealthy is a good idea, but I didn't want to add Crimson since that's already in the Pirate list.

**Comment by toilethinges** [comment]
I knew that it was already in pirate, I meant to type Maroon, actually, but...

**Comment by endless-sky** [comment]
Wow. I'm impressed.

"Bleeding " in the pirate names needs the space removed after it. Other than that, it all looks like it should work fine.

**Comment by Pointedstick** [comment]
Glad you like it! My wife and I worked on it all night. Fixed the bleeding problem.

**Comment by KiLEdEnNis** [comment]
@Pointedstick good luck next month :P

**Pull request merged**
