### PR TITLE
Minor changes to Arach and Heliarch ship descriptions

### PR DESCRIPTION
**Pull request by strollcata**
I've made some changes to Arach and Heliarch ship descriptions, mostly to cut a single sentence into multiple smaller ones. The Heliarch Neutralizer has had a brief description of their ion rain guns added to the description, which is more for the sake of expanding it than anything else.

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
these changes really seem unneeded to me, especially the Heliarch ships

**Comment by MessyMix** [comment]
I think that apart from the ion rain gun description, these are good changes that make the text clearer, i.e. in terms of the "one pair of repulsor and attractor beams" --> "one Heliarch Attractor and one Heliarch Repulsor". This line clarifies a lot.

By the way, Ion Rain Gun should be capitalized.

**Comment by SirStigII** [comment]
I'm inclined to agree with KiLEdEnNis, the only change that seems to be needed is this one:

> description `Anyone who incurs the wrath of the Heliarchs cannot count on making a fast getaway thanks to the Interdictors, which were primarily designed to carry a pair of attractor and repulsor beams that can hold a ship a safe distance away while pushing it around enough to prevent it from getting a hyperspace lock to jump out of the system.`

> designed to carry a pair of attractor and repulsor beams

 implies that there are two of each beam, simply changing it to

> designed to carry an attractor and repulsor beam

would clarify it without needing the added changes.

**Comment by strollcata** [comment]
The changes aren't really supposed to be necessary for the most part. However, if clarification is preferred over rewriting with different mannerisms, then I'm happy to just do that.

**Comment by MessyMix** [comment]
I actually like the other changes apart from the Ion Rain Gun addition, as I clearly mentioned above. I think they make the text a lot more readable, so I support all the other changes.

**Comment by strollcata** [comment]
I know you're fine with them, Messy, I'm just pointing out that they're not supposed to be necessary as a response to Stig and Dennis.

**Comment by endless-sky** [comment]
Given that none of these changes fix actual grammatical errors, I don't think they're necessary. Which version is better is purely a matter of opinion.

In general the game text does not capitalize the names of particular weapons. That's mainly just to avoid text with lots of unnecessary Capital Letters, which Bother me.

**Comment by MessyMix** [comment]
@endless-sky I do think that the pair of attractor / repulsor beams is something that needs to be clarified.

Also, your rule on capitalization is interesting. What I've gone by thus far is that the name of the outfit is capitalized, i.e. Ion Cannon, but when referring to a generic weapon type, it isn't capitalized (i.e. the Ion Rain Gun is a type of ion gun). Or, the Navy Carrier is a carrier, and the Skein is a carrier.

**Comment by strollcata** [comment]
In that case, I'll remove everything except the Interdictors change. The original description could easily be read as 'two attractors and two repulsors', which is more than they carry.

**Comment by strollcata** [comment]
Closing to open new pull with only the Attractor and Repulsor changes.

**Pull request closed without merging**
