### PR TITLE
add bayless ships variants

### PR DESCRIPTION
**Pull request by daggs1**
with the PR of the code support to remove bays, it is a time to make use of it.
this feature helps best ships with internal bays because they can be replaced with extra cargo space.

Testing:
1. buy the ship
2. verify no bays exists and that the cargo size is bigger than the base model.
3. try to instruct fighters to enter the bay.

### CODE REVIEW

**Comment by Amazinite** [comment]
If one wants to use their bays for cargo then they should buy Boxwings.

**Comment by daggs1** [comment]
I didn't found any ships by that name.
this is a variant of two other ships that allows it.

**Comment by daggs1** [comment]
found it, adding fighter for extra cargo seems weird....

**Comment by daggs1** [comment]
also, having the bays replaced on the ship by cargo space allows adding me outfits to the ship. that you cannot do with a boxwing

**Comment by Amazinite** [comment]
That is exactly what is intended by not allowing ships with bays to directly convert their bays into cargo for themselves.

**Comment by daggs1** [comment]
if I can load any outfit I want on a ship, why I cannot convert the bay to cargo in a standard way and instead do it in a twisted way of got another smaller ship to park in the bay and use it's cargo? its illogical.

**Comment by Amazinite** [comment]
Because game balance. If carriers could convert their bays into cargo and therefore into outfit space, they'd be much stronger than similarly sized ships without bays.

If you want to carry more cargo on a ship with bays, buy Boxwings. If you want more outfit space than you can already get from converting some of your cargo space, buy a different ship.

**Comment by daggs1** [comment]
boxwing are great idea for external bays. not internal. this PR changes the only **2** human ships that has internal bays. not any other ship.

it is a shame that you've closed the PR like that as it is a draft PR which depend on an active PR which has no purpose without this.

**Comment by warp-core** [comment]
The purpose would be to support plugin creators who might want to do something like this, or if a person wanted to create a bayless variant of a ship for some other reason, not to boost other stats in the base game in a way that is intentional unavailable.

**Pull request closed without merging**
