### PR TITLE
Cache some values instead of going through maps to get them

### PR DESCRIPTION
**Pull request by tiennou**
I've done a few run while running Instruments (the profiler) here, and it seems there are some low-hanging fruits w.r.t to performance. My test bench was tributing Earth with a heavily modified ship that could sustain the mess that ensues :wink:.

Some other hot-spots I can see are :
- [ ] `AsteroidField::Asteroid::Collide()`, ~20% because of `remainder`.
- [ ] `AI::AutoFire()` (~10%), the std::shared_ptr ctx/dtx takes ~4%.

### CODE REVIEW

**Comment by endless-sky** [comment]
Won't the cached values be out of date the moment any outfits are added or removed?

What I was thinking of doing, instead, was to cache a pointer to certain frequently used fields (like cost) so that they can be accessed quickly, while still ensuring that they get updated properly when outfits are added or removed.

For the record, this was how often the attributes get accessed based on my testing during a big fight, so you're correct that cost and mass are the low-hanging fruit:

```
33.4% cost
13.3% mass
 5.8% turn
 4.0% hull
 3.4% hyperdrive
 3.3% cloak
 3.2% shields
 2.5% automaton
 2.5% required crew
 2.1% thrust
 1.8% ramscoop
 1.8% energy capacity
 1.8% jump drive
 1.7% cooling
 1.7% heat generation
 1.7% energy generation
 1.7% shield generation
 1.7% afterburner thrust
 1.6% hull repair rate
 1.6% turning energy
 1.5% turning heat
 1.5% shield energy
 1.5% scram drive
 1.0% drag
 0.9% thrusting energy
 0.9% thrusting heat
 0.7% fuel capacity
 0.4% jump speed
 0.4% reverse thrust
 0.4% cargo scan
 0.4% outfit scan
 0.0% cargo space
 0.0% turret mounts
 0.0% heat dissipation
 0.0% bunks
```

**Comment by tiennou** [comment]
It seems that outfit addition/removal is handled by `CargoHold`. Here I'm just internalizing the (constant) ship's mass from the data file, the rest of the calculation is still done as it was. I just noticed that outfit's mass also go through the attribute map, but I stopped since it wasn't showing up in the profile.

**Comment by tiennou** [comment]
Note that it already makes a big performance difference. If you're interested, I could post one of my runs so you can get a better idea of what's going on ?

**Comment by endless-sky** [comment]
Outfit adding and removal is handled by Outfit::Add(const Outfit &other, int count).

I think the more important thing will be to optimize the AI's ally strength calculation, which is why those Cost() calls happen in the first place.

**Comment by tiennou** [comment]
Updated. What do you mean by "optimizing the AI strength calculation", the 3-level loop at the start of `AI:Step` ? I've been trying to cache some values from here so the rest of the `IsEnemy` don't go snooping around `Politics`.

**Pull request closed without merging**
