### PR TITLE
specific name capitalization in ship descriptions

### PR DESCRIPTION
**Pull request by Nescio0**
Currently the names of specific ships are typically capitalized in their descriptions; e.g. the Carrier, the Freighter, the Hawk. This proposal implements that for consistency to the exceptions that were probably overlooked earlier. Ought to be uncontroversial.

### CODE REVIEW

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/issues/2698 https://github.com/endless-sky/endless-sky/pull/2453#issuecomment-298035626 https://github.com/endless-sky/endless-sky/issues/2162

**Comment by Pointedstick** [comment]
These are examples of a ship's own name not being capitalized in its description. That seems like a much clearer example of an error rather than a subjective choice.

**Comment by endless-sky** [comment]
The Wasp change makes sense, because "Wasp" is clearly a name, but the others don't seem necessary to me. It's perfectly reasonable for "drone" or "gunboat" to be used in a generic sense, and Excessive Capitalization makes writing more difficult to read.

**Comment by Nescio0** [comment]
Bulk Freighter, Carrier, Corvette, Cruiser, Freighter, Hauler, Heavy Shuttle, Shuttle, and others are all capitalized in their specific descriptions. I don't see why the Navy Combat Drone, Gunboat, and Surveillance Drone should be treated differently. Consistency matters.

**Comment by Tadrix** [comment]
To be precise, Shuttle is called a *shuttlecraft* (uncapitalized) in its description (while the Scout is called *Lionheart Scoutship*). Rainmakers are also called just *missile boats*.

Consistency has nothing to do with this. IRL you'd also capitalize *Ford*, *Abrams* or *Apache*, but not *car*, *tank* or *helicopter*. The *Hauler* is clearly a proper model name, same for the *Corvette* (think *Chevy Corvette*). *Drone* and *gunboat* are just common descriptors. There are plenty of different carriers in ES, but there's only one Navy *Carrier* model. Etc. etc, As for the Syndicate, they are models, but their designers (or supervisors) clearly lack imagination, as evidenced not only by model names, but also by ship shapes.

**Comment by Nescio0** [comment]
Let's quote the current descriptions:
> 	description "Although Betelgeuse Shipyards produces other ship models as well, the majority of their profits come from sales of the **Shuttle**.
>	description "The Lionheart Scoutship was designed back in the days when the galaxy was more sparsely populated, and ships prospecting for habitable worlds or worlds rich in resources would often travel far away from any habitable ports where they would be able to refuel. Although the galaxy has now been much more thoroughly explored, the **Scout** remains a popular ship for long-distance travel."
>	description "The **Rainmaker** is a missile boat built in the Republic Navy Yard.

As you can see the proper names are capitalized here; descriptions are not. Now have a look at:

> 	description "The Navy *gunboat* is designed for engaging targets at short range

Gunboat is not a common description in this sentence, it's clearly a proper name, therefore it ought to be capitalized.

**Comment by Amazinite** [comment]
Seeing as how the change to the Wasp description is the only thing that we're in agreement with for this PR, I added that change myself with 810b50e but creditted @Nescio0. I wouldn't capitalize "drone" and I would capitalize "gunboat," but that conversation was had in #2698. There are a lot more places where "gunboat" is lowercase than just its description as well, so such a change would need its own PR to remain consistent throughout the game.

**Pull request closed without merging**
