### PR TITLE
Add a Remnant Hand to Hand weapon

### PR DESCRIPTION
**Pull request by Brick63**
Short and simple, title tells the gist of it

Assets:
[remnant rifle assets.zip](https://github.com/endless-sky/endless-sky/files/1868302/remnant.rifle.assets.zip)

### CODE REVIEW

**Comment by jschiav** [comment]
> "The Tuning Rifle uses soundwaves to destabilize the weaker internal tissue of many races and liquidizes them."

Holy crap. The description makes me cringe. Nice!

Two very minor comments. "Sound waves" is two words, and maybe use the word "liquefies" instead? I think that word is more common and sounds better than "liquidizes".

**Comment by Brick63** [comment]
Nothing wrong with your fix but i just like the word more

**Comment by jschiav** [comment]
Fair enough. :)

**Comment by tehhowch** [comment]
Easy enough to thwart... Use a vacuum layer to isolate oneself from the external environment 😎

(Neat idea and quite fitting for the Remnant culture)

**Comment by gunqqer** [comment]
That would work until you suffocate, teh :P (+1 for the idea, looks fine and balanced to me)

**Comment by SirStigII** [comment]
I think liquifiy is the correct term, liquidise  is more about assets and money than the physical state of something.

> Liquefy is a related term of liquidate. Liquidate is a related term of liquefy.
> As verbs the difference between liquidate and liquefy is that liquidate is to settle (a debt) by paying the outstanding amount while liquefy is (physics|chemistry) to make into a liquid, either by condensing a gas or by melting a solid.

**Comment by Brick63** [comment]
Huh well can't argue with that

**Comment by Tadrix** [comment]
Using sound waves… Stutter Rifle then?

**Comment by temtemy** [comment]
Liquidize is still a correct term, liquefy is just clearer since liquidize can also be used as a business term (liquidize can mean "to liquidate").

**Comment by Kriegstofu** [comment]
giving it a bit better damage than the frag grenades should still be increased to maybe 1.5 to 1.7? as it is rather expensive, and with the korath rifle there will be other legal high end weapons anyways

**Comment by Brick63** [comment]
The difference is the fact that you need to farm the rifles from the korath, this however could be bought.

**Comment by Brick63** [comment]
Closing this to fix issues

**Pull request closed without merging**
