### PR TITLE
fix(mechanics): Always allow `on fail` to trigger after failure

### PR DESCRIPTION
**Pull request by tibetiroka**
**Bug fix**

This PR addresses the bug reported by @Hurleveur.

## Summary
A mission's `on fail` can run several days after it's failed (because it doesn't trigger mid-flight), so we have to make sure it can actually show up for an already-failed mission.

## Testing Done
I tested that the `on fail` from this mission now shows up: 
[mission Hai Legacy 3.txt](https://github.com/user-attachments/files/16647680/mission.Hai.Legacy.3.txt)

### CODE REVIEW

**Comment by petervdmeer** [comment]
> A mission's `on fail` can run several days after it's failed (because it doesn't trigger mid-flight), so we have to make sure it can actually show up for an already-failed mission.

But it the solution for this bug to have the `on fail` action happen later? Or is the solution to make the `on fail` actually happen mid-flight?

**Comment by tibetiroka** [comment]
Yeah, I think that's a planned feature, but it might require some reworking in the code base. (I don't actually remember the reason why it only triggers on landing. Maybe there is a good reason for it.)

We would still need to maintain compatibility with missions that expect it to be triggered on landing, so we would probably need to add a flag that missions can set to enable triggering it mid-flight.

**Comment by Hurleveur** [comment]
Iirc from looking at the code it would not remove the missions instantly bc they might have ships connected to them and stuff, felt like a mechanical reason to me they wouldn't trigger in space. From a quick look at the files I didnt see any missions that assumed you landed, besides a remnant one we can change easily.

**Comment by petervdmeer** [comment]
> We would still need to maintain compatibility with missions that expect it to be triggered on landing, so we would probably need to add a flag that missions can set to enable triggering it mid-flight.

Then let's update the Wiki to make this official; `on fail` triggers when landed, or on the first landing after the mission failed (if the player is not landed).
(And if we want an "instant" on fail later, then we can add `on fail instantly` as a separate keyword.)

**Comment by petervdmeer** [comment]
> Iirc from looking at the code it would not remove the missions instantly bc they might have ships connected to them and stuff, felt like a mechanical reason to me they wouldn't trigger in space. From a quick look at the files I didnt see any missions that assumed you landed, besides a remnant one we can change easily.

Agreed, it makes sense to keep the (failed) mission alive until landing to let connected NPCs continue until landing.

**Pull request merged**
