### PR TITLE
Added map color key for commodities. Other keys will need to be bigge…

### PR DESCRIPTION
**Pull request by guillochon**
…r and probably require more art assets. Here's what it looks like:

image

### CODE REVIEW

**Comment by Pointedstick** [comment]
Ooh, nice.

**Comment by omagasohe** [comment]
You sir are awesome. This is needed badly.

**Comment by endless-sky** [comment]
When I get a chance, I'll try to create a dedicated UI graphic for you to use for this. (Squeezing five lines of text onto that one makes it look a bit crowded, given that everything else in the game uses a line spacing of 20 pixels.)

**Comment by frameworld** [comment]
It's all nice, but wouldn't it be superior to show price-difference/(jumps+1)?

**Comment by endless-sky** [comment]
I've expanded this idea to include the other ways the map can be colored (by government, reputation, or shipyard or outfitter size) and added it in b13ec27:

gov
outfits
system
trade

**Comment by frameworld** [comment]
There are barely enough colours to make everything that detailed with just a single colour.

If we had other shapes - ovals vertical, horizontal, diagonal or squares/triangles/hexas, ... Hostile, Restricted and Dominated don't have to look the same.

**Comment by guillochon** [comment]
Very nice, only thing that's a bit lacking is the list of governments, which is missing quite a few.

**Comment by guillochon** [comment]
Oh nevermind, I see they change depending on the viewpoint.

**Comment by Pointedstick** [comment]
Should this be closed?

**Comment by guillochon** [comment]
Closing this given all the recently added keys

**Pull request closed without merging**
