### PR TITLE
[Mechanic] Blindness / Fog of War Damage Effect

### PR DESCRIPTION
**Pull request by Azure3141**
**Feature:** This PR implements the feature request detailed and discussed in issue #noonewantedthis

## Feature Details
Thanks to @RisingLeaf for ~~doing probably 85% of the work on this~~ helping me code this!

This PR adds a new damage type, `fog damage`, which inhibits the viewing range of the player.

## UI Screenshots

2b50fc4d2f5482d908e17267536b6067

image

## Usage Examples

As it is a damage type, `fog damage` can be used in both weapons and hazards. The intended use is with hazards (for special environments), but a blindness weapon could also potentially be a cool addition in the future.

During my testing, I used the following hazard:

```
hazard "System Fog"
	"system-wide"
	"constant strength"
	weapon
		"fog damage" 1
```

## Testing Done
Testing still in progress. So far I've mostly been flying around and listing everything that isn't yet affected by the fog. More testing is probably needed in the realm of performance and with different levels of fog damage.

### Automated Tests Added
N/A

## Todo
- [x] Make fog affect planets/objects/ships
- [x] Make fog affect projectiles
- [x] Make fog affect asteroids
- [x] Make fog affect the starfield and haze, dimming the background stars instead of completely hiding them
- [x] Make fog affect the targeting UI and other miscellaneous features
- [ ] Make fog affect the AI, reducing aggro distance and making it likely to lose a target if it is outside the visible region
- [x] Make an attribute that hides a ship from the RADAR, to allow for more surprising jumpscares

## Performance Impact
I haven't noticed any performance impact, but someone with more shader knowledge would probably know more about whether this has one.

### CODE REVIEW

**Comment by Zitchas** [comment]
Looks neat. Can definitely see some goof uses for this. Cam one do different colors or textures? Fading into a nebula haze would look good, probably.

**Comment by ziproot** [comment]
Would this do anything if you use it on the AI?

**Comment by ziproot** [comment]
OK, that makes sense. Thank you.

**Comment by Quantumshark** [comment]
If background stars remain visible, star objects should definitely remain visible too - it seems odd still being able to see the background stars which are multiple light years away, but not being able to see a star that's right nearby.

`thrusting fog` and the similar attributes need to be added to OutfitInfoDisplay.cpp so that they show up as 60 times the code value, like other attributes which are done per frame. Likewise, the protection and resistance attributes need to be added to OutfitInfoDisplay.cpp in the same places as other protection and resistance attributes, so that they show up correctly.

**Comment by Koranir** [comment]
Whhy not just make this a post-processing effect?

**Comment by RisingLeaf** [comment]
> I'm not sure what that would entail honestly. Using a shader was what was suggested to me by @RisingLeaf (who ended up actually making the shader) so I went with that.

~~stop pinging me~~

a post processing effect would require render to image which is overkill and not needed imo

**Comment by Quantumshark** [comment]
image
Extremely high fog levels (this was done with `"thrusting fog" 255`) give sharp edges like this, not sure if that's the intended functionality or is a bug.

**Comment by quyykk** [comment]
This might be easier to do in a similar way to the FogShader instead of modifying every shader to account for fog.

**Comment by TheGiraffe3** [comment]
@Azure3141 will you continue working on this please?
It looks like a quite enjoyable feature and if it is a prerequisite for the Avgi, it should to be done soon.

**Comment by tibetiroka** [comment]
Closing as orphaned, since this PR has conflicts, fails the CI, and received no fixes for these since last October. Feel free to reopen the PR once you actually get back to it.

**Pull request closed without merging**
