### PR TITLE
Capital Letter Missing (typo fix)

### PR DESCRIPTION
**Pull request by MessyMix**
Changed “dreadnought” to “Dreadnought”

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
Dreadnought is their name, but it's also a ship category, so I'm not sure if it is actually a mistake

**Comment by jafdy** [comment]
In this context it's a name.

**Comment by KiLEdEnNis** [comment]
well, I am a perfectionist myself, so I can sleep well tonight knowing another typo is fixed

**Comment by jafdy** [comment]
You also have forgotten to put full stops on the end of your sentences and you often forget the Capital Letters at the starts.

**Comment by KiLEdEnNis** [comment]
"forgotten", more like an intentional casual chatting style

**Comment by Amazinite** [comment]
>casual

>perfectionist


Does not compute.

**Comment by KiLEdEnNis** [comment]
perfectionist doesn't mean full-time perfectionist
when creating my ship in blender I translated like 5 digits precisely, and did every small detail that doesn't even show
but at things I don't care about (the way I chat) I put 0 effort in (because why would I)
I'm a perfectionist, not dumb, and laziness always controlled my character

**Comment by MessyMix** [comment]
Okay, but "dreadnought" is _not_ used as a ship category in the game. You see it rolled out as a new model, and I don't see anyone in game referring to other warships as "dreadnoughts". As such, I think that it's meant to be the name, much like "Cruiser" is a name and not a ship class in ES. Since the rest of the game uses "Dreadnought" (capitalized), then I think this will help keep consistency.

**Comment by KiLEdEnNis** [comment]
they are indeed only referred at as an actual name, the fact that ship categories are actual ship names is just a little confusing every now and then

**Pull request merged**
