### PR TITLE
Slight Dialog change

### PR DESCRIPTION
**Pull request by Ajm219**
Changed because while playing threw that the line "The Syndicate hate my my guts right now" does not seem like something a Professional would say, especially in the year 3014. Personal opinion does accompany this, take it with a grain of salt.

### CODE REVIEW

**Comment by solardawning** [comment]
Why?
Seriously- reading the change, why? It changes the characterization of Ijs, in a way that doesn't seem to be necessary, or a good change.
The existing line reads as a witty, snarky comment- exactly what a self-described rogue nuclear inspector/activist would say. The proposed change loses that.

Downvoted.

**Comment by Rob59er** [comment]
Yeah there's no point to this.

**Comment by jafdy** [comment]
He is not strictly a professional . . .

**Comment by Please-Close-This-Issue** [comment]
Quickly

**Comment by MessyMix** [comment]
As I said in the Discord, this is how to make a PR, and the game is open source so if you feel like there is something you should add, do so. I did not specifically recommend this change, however. Just clarification.

**Pull request closed without merging**
