### PR TITLE
debt response for mission triggers

### PR DESCRIPTION
**Pull request by MarcelineVQ**
re: https://github.com/endless-sky/endless-sky/issues/1216

Allowed mission triggers to use more credits than you have but if they do they apply a mortgage instead of subtracting credits. Decided against subtracting any credit if you can't afford it all so you have money to complete the mission if you need supplies.

I've tested this a fair bit but I don't typically make missions so it'd be great if someone could try it out in a few circumstances.

### CODE REVIEW

**Comment by jafdy** [comment]
Try using

`mission test
_job
_repeat
_on accept
__payment -1000000`

replace _ with a TAB.

**Comment by MarcelineVQ** [comment]
I hadn't thought to check the job board so I'm glad you mentioned that, it seems to work the same luckily.

**Comment by LocalGod79** [comment]
my plugin [url=http://steamcommunity.com/sharedfiles/filedetails/?id=631160921]Ursa Polaris[/url] has quite a few negative payment missions after the main storyline (that total nearly 1B credits), and a -200k mission just a few into the string...

you could use it to test your branch with an existing player snapshot.

**Comment by MarcelineVQ** [comment]
@LocalGod79 Based on thoughts from https://github.com/endless-sky/endless-sky/issues/1216 I've dropped changes to the 'payment' response and added a 'debt' response which allows you to set a debt, interest rate, and term if you desire.
Specifying interest number is a little awkward, in that it's so tiny, but that's how it appears for a mortgage in a save file which makes it easier for people to find examples for.

`debt <principal> [<interest> [<term>]]`

example job (github uses spaces so copying this directly probably won't work):
```
mission testmission
	landing
	repeat
	on accept
		debt 12345 .00123 45
```

**Comment by LocalGod79** [comment]
can you specify the interest rate to be based on the player's credit rating, the way normal mortgages do?

**Comment by MarcelineVQ** [comment]
@LocalGod79 
What do you think would be the most intuitive format for that based on other mission syntax?
`debt <principal> [(rating|<interest>) [<term>]]` ?

**Comment by jafdy** [comment]
What would the `rating` do?

**Comment by MarcelineVQ** [comment]
@jafdy Uses the player's credit 'rating', I'm open to suggestions for a clearer word to use though. 'credit' didn't seem any better

**Comment by jafdy** [comment]
I don't understand any better. It will become a documentation issue when this is merged.

**Pull request closed without merging**
