### PR TITLE
Content(boarding missions): Unfettered threaten to blow up (is it a bluff?)

### PR DESCRIPTION
**Pull request by Hurleveur**
**Content (Missions)**

## Summary
When you board Unfettered ships they will have a chance to trigger this mission, depending on how much of a crew advantage you have over them.

You then have the choice to either:
-call the bluff (either they blow up, blow up with you or don't blow up and call reinforcements)
-get the hell out (the ship may blow up still or you may just head out, with or without reinforcements for them)
-challenge the leader to a duel for a price of 100 000 for the winner, and guarantee of no reinforcements or blowing up
This third option normally guarantees the ship will stay in the system disabled for 3 days, without the reinforcements it would usually have. The captain also wont kill you.

Smaller ships will mean a smaller reinforcing fleet, ranging from 2 small fleets to 2 small fleets and a large one, and these are not attacked by the Hai and rush you (whilst staying in the system). The Unfettered also are made un-bribable temporarily (didnt test these).
The mission should only trigger in systems next to Uhai systems (but mb that doesnt work for boarding missions idk)

This in addition to https://github.com/endless-sky/endless-sky/pull/7471 should completely fix any beetle farming.

## Save File
just fly in UHai space, will include one soon

## TODO(draft until done):
- [ ] additional reinforcements if you have a big fleet
- [ ] improve the quality of the text as much as I can (ur welcome to help me on this one)

### CODE REVIEW

**Comment by binaryspica** [comment]
What means explode? Does it means the command destroys the flagship outright?

**Comment by binaryspica** [comment]
> > What means explode? Does it means the command destroys the flagship outright?
> 
> The `explode` endpoint in a conversation does indeed destroy the player's flagship (killing them).

Thanks. Then I don't think that it should be. Simply kill the player by a random chance seems too unreasonable.

**Comment by EjoThims** [comment]
Gonna have to come back for grammar pass and make sure I'm parsing the structure correctly, but I like what I'm seeing, especially how this incentivizes would be farmers to have -just enough- crew to reliably capture only one each day.
 
 What are the minimum and maximum chances on the different iterations of the "explode" branch, though? I have no problem with it being included, myself, but do want to be sure it's a low enough chance. :)

**Comment by Hurleveur** [comment]
The maximum chance of explosion is: 50% for mission to offer, then 100% for it to not be a bluff if you have 100 crew more than they do, then 2% chance for them to blow themselves up.
You will never blow up if you dont choose to check if its a bluff the stupid way.

The minimum chance is 0%: this will not offer if you dont have more crew than they do, and caps at 50% chance of offering when you have way more crew. Then, if you try and call the bluff but do not have more than 25% more crew than they do they will never self destruct so 0% again.

**Review by UnorderedSigh — CHANGES_REQUESTED** [review]
A few things:

1. Having this happen very frequently doesn't feel very "Endless Sky" to me. It should be an infrequent annoyance, otherwise it will be repetitive and obnoxious.
2. The player's combat rating should affect their success in the duel (that happens in other personal combat missions).
3. It doesn't make sense for the Unfettered "fight or flight" instinct to result in suicide.
4. How do they know your crew compliment without a tactical scanner?

Over all, I think this is a bad change, because the sole purpose is to break the combat mechanics to prevent Shield Beetle captures in a way that is obnoxious and at odds with how the game works everywhere else. There are only two other examples of non-standard captures, and they're out of necessity: automata self-destruct to avoid a trivial 100% capture rate, and the smugglers self-destruct to prevent problems with the story. Why would Korath not do this? Or pirates? Or the navy?

The Unfettered should fight fairly like everyone else, with a high crew count and good weapons, not unfair game mechanics.

**Comment by Hurleveur** [comment]
I can tweak this to only make them summon reinforcements
Also its their disgust of the player that makes them do this desperate action

**Comment by UnorderedSigh** [comment]
Occasional (rare) missions like this would add some nice color to farming. No longer is it a game where you get ships non-stop. Instead, you have to deal with stories along the way. We already have some missions like that, such as the one where you rescue slave soldiers from a pirate ship instead of capturing it.

**Comment by UnorderedSigh** [comment]
> possibly only if they have a JD

The Unfettered obsessively defending their jump drives makes sense, for the same story reason that Smugglers don't want to get caught. Self-destructing or dueling wouldn't make sense, though, but a large rescue fleet showing up might, as long as it doesn't cause them to lose more Jump Drives. The AI for the rescue fleet has to be smart enough to repair the ship and jump away instead of wandering around getting killed. The Smuggler "rescue" fleets are there to kill all witnesses, so the existing AI works for them, but maybe not for the Unfettered rescue ships.

**Comment by UnorderedSigh** [comment]
This mission would be okay if it was something like a 50% chance one-off mission or 5% chance reoccurring mission. Though, if we add more like it, each one would need a lower chance.

**Comment by Hurleveur** [comment]
Yeah don't worry thats why this is a draft: to propose an idea. We can tweak it as much as wanted.

**Comment by Hurleveur** [comment]
I'll close this for now to focus on other content, and to think about it more. Feel free to comment on it further if you have suggestions though, I'll open it again once the rest will have advanced

**Comment by Zitchas** [comment]
I like the concept, would like it better if it could be triggered on initiating the combat instead of merely opening the boarding menu. Then they are blowing the ship in response to an attempt to capture, rather than in response to mere theft.

While boarding is I think a very useful mechanic, I would like it better with more missions like these popping up. Capturing, to in the other hand, is only a little bit better than dominating planets: has a place, but should be rare, not common.

Other ideas: be met at the airlock by the captain with a credit stick: "You have us at a disadvantage. We will offer you X credits (about 5-10% the value of the ship) to repair us and leave us alone."

**Comment by Hurleveur** [comment]
Mechanically I cant do either of those though

**Comment by Zitchas** [comment]
I know, but ideas of what a codet might be able to make happen...

The point is to give us options. This is a spsce game: like having missions trigger it complete on entering systems, being able to do more stuff in boarding gives us more opportunity to have interesting and diverse story action instead of having everything happen on planet.

As far as that goes, having mission NPCs be able to do friendly boarding would be nice too. EV, for instance, had jobs where NPCs would broadcast stuff like "I have this cargo for X but my for changed, could you take it?" And if accepted, it comes over and "boards" the player to transfer the cargo. (Or the player boards them). Much like fuel transfer.

**Comment by Hurleveur** [comment]
Yeah but thats partly why I closed this PR: the original idea is no longer what I'm going to go with.
I'll make a unique 1 time boarding mission or two and the reinforcements will be the generic version probably, either if you bring horror gas or if they have a JD (and so bring non JD ships to protect it at all cost)
Also will make a more extreme version for truly defenceless ships - it seems that smth did not pass well lore wise btw, no Uhai die from the explosion except in the (in the worst case) 2% odd chance they blow with you. Otherwise they just always escape pod out of there.
Unfettered do not care about ships but they care about Hai dying.

**Comment by UnorderedSigh** [comment]
"Guilt trip" missions would add a nice spice to it. "We know we're not going to get out of this alive, but we have critical medication that we pillaged which needs to reach `<planet>` or thousands of people will die. Please take it there!" or "Our ship is critically damaged, and about to explode. There are five children with us. Please take them to `<planet>`."

**Pull request closed without merging**
