### PR TITLE
Add empty "on abort" sections to Syndicate target practice.

### PR DESCRIPTION
**Pull request by petervdmeer**
**Content (Jobs)** Don't fine players for ships they didn't destroy in target practice.

## Summary
This PR uses the feature from #5426 to ensure that aborted Syndicate target practice jobs don't fine the player for destroying the dummy ship by providing an empty on abort section.

## Testing Done
I checked both the fail situation and the abort situation (using the compiled code from #5426). The abort situation doesn't give any output, the fail situation still gives the proper message.

## Save File
I can provide a save file if desired, but the change is quite trivial, so I'm not sure if this is needed.

### CODE REVIEW

**Comment by tehhowch** [comment]
Probably we will want an explicit comment added in the node, as is done in situations where an "empty block" is suspicious in some way:
```
on abort
    # No penalty
on fail
    ...
```

(As currently written, the changes could look like a switch case fallthrough to someone not well-versed in reading ES datafiles.)

**Comment by petervdmeer** [comment]
Agreed. Added comment as suggested.

**Comment by Amazinite** [comment]
While we’re changing missions, I believe the FW second chance escort mission from FW Intro should require an explicit objective failure of the associated missions, as right now aborting those missions gets you the second chance, which is written as if you failed the objective.

**Comment by Amazinite** [comment]
Any pirate job that was changed in #4287 also needs an empty `on abort`.

**Comment by petervdmeer** [comment]
> Any pirate job that was changed in #4287 also needs an empty `on abort`.
I used a non-empty `on abort` here since that looked more appropriate. Please review. If you prefer empty, then I will replace those by empty aborts.

**Comment by Amazinite** [comment]
Well if there was a reputation hit on abort then I would imagine there to be one on fail as well. The dialog wouldn't be a part of the on fail though since it's redundant with the scan message.

**Comment by petervdmeer** [comment]
> Well if there was a reputation hit on abort then I would imagine there to be one on fail as well.

The pirates might be more forgiving of somebody that gets caught (which is a risk they understand) than of somebody that just runs away from the mission silently (which looks cowardly).
But I'm okay with also adding the pirate reputation hit in the on fail if that is appropriate.

> The dialog wouldn't be a part of the on fail though since it's redundant with the scan message.

Yes, I noticed.

**Comment by petervdmeer** [comment]
> While we’re changing missions, I believe the FW second chance escort mission from FW Intro should require an explicit objective failure of the associated missions, as right now aborting those missions gets you the second chance, which is written as if you failed the objective.
> 
> FW Escort 1, 1B, 2, 2B, and 3 need empty `on abort`s.

I feel that empty `on abort`s are not really appropriate if you leave freighters to travel alone without defensive escorts through an area crowding with pirates. An abort dialog that says "you abandoned your mission and the freighters got captured without their defensive escorts." might work better to directly connect those missions to second chances.

Btw, those are main storyline content missions, I feel they require more testing than the changes in this PR. Does it make sense to keep those for a separate PR?

**Comment by Amazinite** [comment]
In the case of the Remnant missions, the on fail exists because the missions are treated as completed whether or not the Korath Raiders survive, just with different outcomes based on the player's actions. If the player aborts the mission though, they never fought the Raider, and therefore neither ending makes sense to continue from.
I know that at least in the case of Salvage 4, [I pointed this out to Zitchas](https://github.com/endless-sky/endless-sky/pull/3761#discussion_r245404419), but highlighted how there's nothing we could do about it at the time. Now is the time to fix that, though.

Salvage 5 needs `not "Remnant: Salvage 4: aborted"` and Cognizance 5 needs `not "Remnant: Cognizance 4: aborted"` in their to offers should we give the previous missions on aborts.

In the case of the FW missions, if the player is purposefully aborting the missions, then I think we should take that as them completely quitting instead of dragging them back into the second chance as if they had simply failed the objective.

**Comment by petervdmeer** [comment]
> In the case of the FW missions, if the player is purposefully aborting the missions, then I think we should take that as them completely quitting instead of dragging them back into the second chance as if they had simply failed the objective.

Yes, that makes a lot of sense. I added the empty 'on abort's for the FW missions to this PR.

**Comment by petervdmeer** [comment]
> Any pirate job that was changed in #4287 also needs an empty `on abort`.
> Remnant: Salvage 4 and Cognizance 4 as well.



> Salvage 5 needs `not "Remnant: Salvage 4: aborted"` and Cognizance 5 needs `not "Remnant: Cognizance 4: aborted"` in their to offers should we give the previous missions on aborts.

Yes, sounds plausible. Added this as well.

**Review by Amazinite — APPROVED** [review]
This now covers all the instances that I can recall needing updated for when abort and fail can be differentiated.

**Pull request merged**
