### PR TITLE
Bugfix: Do not overthrust when ship is pointing at mouse

### PR DESCRIPTION
**Pull request by samrocketman**
## Summary

Using mouse control causes over-thrusting without some kind of precision-lacking calculation.  The behavior the player experiences is the following with mouse control enabled (Alt shortcut by default).

* Ship turning thrusters are always on
* Ship turning thrust sound always plays

## Fix Details

Enables adding a lack of precision to TurnToward method.  This means if the nose of the ship is "close enough" to the mouse it will stop trying to turn.

The benefit of this approach is that as the mouse is closer to the ship the more precise it becomes.  This could be used to fix other precision-thrust issues such as landing on planets and boarding ships.

[line 1923](https://github.com/endless-sky/endless-sky/blob/b760ee7613f94274d9b0b6325a9e5c669b39c41a/source/AI.cpp#L1923)
```
    if(!isClose || (!isFacing && !shouldReverse))
        command.SetTurn(TurnToward(ship, dp, 0.9999));
```

In MoveTo method would fix landing and boarding which can be a separate pull request after this one is merged.

## Testing Done

Opened the game and replicated the problem.

With the fix:

*  the ship does not use constant thrust to turn toward mouse.
* I verified precision is higher with the mouse closer to the ship.
* With the mouse further from the ship it is less precise but not noticeable.

## Related issues

* #7703
* #6936

## Performance impact

None

### CODE REVIEW

**Comment by samrocketman** [comment]
@Zitchas in Fix details that fix would address they lampyrid constantly turn-thrusting when landing or ship boarding.

**Comment by samrocketman** [comment]
I found #7703 is related

**Review by RisingLeaf — APPROVED** [review]
looks good to me

**Review by Hurleveur — APPROVED** [review]

**Review by quyykk — COMMENTED** [review]
Is this something that would be useful to do everywhere, i.e. all the time?

**Review by quyykk — APPROVED** [review]

**Pull request merged**
