### PR TITLE
balance: Put some grab-strikes on the mining Rano'erek so it can defend itself

### PR DESCRIPTION
**Pull request by ravenshining**
It's been pointed out that Korath mining Rano'ereks appearing in human space are coming armed without any real weapons, just diggers, banishers, and warders, plus chasers that only have diggers, making them trivial to capture.

This replaces the 5-digger variant with the default 3-digger Rano'erek that has two Grab-strikes.  This is still a fairly weak build, so it won't be going too far in the difficult direction, and it still comes with diggers, so it's still clearly a mining vessel.

Since it's not used anywhere else, I'd delete the 5-digger variant definition but apparently we have to preserve those for plugins now and I don't want to move it back and forth not knowing whether I'll want to use it for something else in the future or not.

### CODE REVIEW

**Comment by Zitchas** [comment]
This change sounds good for human space; but maybe the 5 digger variant could be used somewhere in a safer system? It does make sense to have a really focused mining ship; just not in risky areas.

**Comment by ravenshining** [comment]
There is also the civilian as well, that is already used to mine in Korath home systems.

**Comment by 1010todd** [comment]
Another thing that made them easy target is they'll ignore the player once damaged enough and return to mining, not jump out. So after some point you can shoot it without it focusing on shooting you. This behaviour might also have to be changed (in another PR).

**Comment by ravenshining** [comment]
Hurlever did mention that, I just didn't bring it up here yet as I hadn't a solution for it.

None of the personalities except `coward` are supposed to affect when a ship actually flees, and that is only for non-fleet-flagships.  So it's probably not that it is not jumping out when it's supposed to, it just seems that way because a `timid` ship only attacks nearby hostiles.  Which... is desired, a weaker ship shouldn't go charging into battle, but, hm.  We need personalities that make ships actually flee :-P

I don't know what you're seeing though.  When you say *ignore*, do you mean it's not attacking even when the player is nearby and/or shooting it?  Because that would be bugged.

**Comment by Hurleveur** [comment]
What he means is that they will literally just act as if you weren't there once they get to the point where they are damaged enough to flee, they'll resume mining XD
Timid isnt whats triggering it I'm currently doing some tests.

**Comment by Hurleveur** [comment]
https://github.com/endless-sky/endless-sky/pull/7468 that PR should fix that issue, I'll check soon to make sure

**Comment by Hurleveur** [comment]
We may want to add coward whilst we're at it, just to make sure the miners flee faster when in trouble instead of sticking till the end to put a (small) dent in your hull?

**Comment by ravenshining** [comment]
Korath may not be as psychopathic as people assume :-P
'Tis a tough call.  I think, given the memory lore I've been writing, plus their whole thing about codes of honour, they'd be inclined not to leave someone behind.... but then again, neither is it prudent to risk 200 to save 4, and they can't afford not to be prudent.

It'd certainly be nice if they actually fled hostiles, flew towards their wayward charges and started to flee a bit earlier to allow the fighters to land -- things player would do, rather than just park and wait -- or if leaving the fighters, had them go into a super evasive mode, possibly escaping planetside if they have `atmosphere scan`.

**Comment by Hurleveur** [comment]
Fear the super evasive Rano'Erek! Faster than an asteroid, it'll run away from you in a few years.

**Comment by ravenshining** [comment]
I mean the 'olofezes.  Even the mining variants ought to have a decent chance of evading pursuit.

**Comment by Hurleveur** [comment]
Frankly the olofezes are fine, they are timid meaning they'll always wonder around their carrier when you're nearby and wont really pursue you much I had trouble disabling them tbh.

**Review by Zitchas — APPROVED** [review]
This is a simple change, but it fits our lore and is much more appropriate to have a better armed ship do dangerous mining like this.

**Comment by Zitchas** [comment]
As a note, the `evasive` personality from https://github.com/endless-sky/endless-sky/pull/5698 might be useful for telling these ships to stay out of weapon range of hostiles. Might help them be more, well, evasive.

**Comment by Hurleveur** [comment]
Good point, but now that I fixed them mining to death they shouldnt be too easy to get
Although now Korath ships dont get disabled as often by pirates, idk how inaccessible a JD should be

**Comment by Zitchas** [comment]
I don't think JD should be particularly accessible. Getting them from the Korath here is, in my view, more of an "Elite veteran bypass" allowing those in the know (or lucky) to escape human territory without going through Hai space. The less likely the game is to just hand someone a JD by disabling a Korath ship for them here, the better.

**Review by Saugia — APPROVED** [review]
It still might be beneficial to save those variants for something in the future, maybe some sort of special mining escort mission in the Korath campaign, etc.

**Pull request merged**
