### PR TITLE
feat(content): mark systems in the Electron Beam mission

### PR DESCRIPTION
**Pull request by TheGiraffe3**
**Use a Feature**

## Summary
Added `mark` to FW Southern Recon 1B, as an indicator of how Freya said Gunboats might be there.

## Testing Done
Works.

## Save File
This save file can be used to test these changes:
Thanks to TomGoodIdea. Go to Trinket and land.
[Jon.Brother.txt](https://github.com/user-attachments/files/17411761/Jon.Brother.txt)

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
she also mentioned Wei

**Comment by TheGiraffe3** [comment]
~~but the Gunboats are in Alnasl~~

**Comment by TomGoodIdea** [comment]
I've provided a save for this mission in #10062.

**Comment by TheGiraffe3** [comment]
Thanks!

**Review by tibetiroka — APPROVED** [review]

**Pull request merged**
