### PR TITLE
last instance of 'copy' removed from outfitter

### PR DESCRIPTION
**Pull request by thomasballinger**

### CODE REVIEW

**Comment by thomasballinger** [comment]
Or maybe

* "another one of these weapons"
* "another of this weapon"

**Comment by thomasballinger** [comment]
I *really* want to say "instance" but that's terrible.

**Comment by Gkramme** [comment]
Another one of these launchers sounds more natural.

**Comment by thomasballinger** [comment]
I agree "launchers" is more natural, but this message could be displayed for anything that takes ammo, not just launchers. Even though everything that uses ammo for now sort of launches things

    Thunderhead Launcher: ammo "Thunderhead Missile"
    Meteor Missile Launcher: ammo "Meteor Missile"
    Sidewinder Missile Launcher: ammo "Sidewinder Missile"
    Javelin Pod: ammo "Javelin"
    Hai Tracker Pod: ammo "Hai Tracker"
    Torpedo Launcher: ammo "Torpedo"
    Typhoon Launcher: ammo "Typhoon Torpedo"
    Heavy Rocket Launcher: ammo "Heavy Rocket"
    Nuclear Missile: ammo "Nuclear Missile"

even if it's not called a launcher, but there could be things that don't launch anything that use ammo in the future like mine-layers or nitro boosters or scrolls of summoning reinforcements or whatever. If @endless-sky is on board we could that, otherwise this should be as general as the old message.

**Comment by Gkramme** [comment]
I got it. Necular missles dont require a launcher.

**Pull request merged**
