### PR TITLE
fix(content): Separate Acheron Spacelife Government

### PR DESCRIPTION
**Pull request by Saugia**
**Content (Bugfix)**

## Summary
Currently, the Vyrmeid space life use the same Indigenous government the Voidsprites use, which happens to have an `attitude toward` of 1 towards the "Ember Waste" government, which is used by the Ember Waste Node in Remnant content. This means that attacking Vyrmeid life can cause the Ember Waste Node to be hostile.

This PR separates the Vyrmeid from the default Indigenous government so this does not occur.

Edit: Included the Iije as well. Thanks to @MidnightPlugins for notifying me of members with the issues.

## Save File
Not really necessary, but I could make one if so.

### CODE REVIEW

**Review by lumbar527 — APPROVED** [review]

**Review by Zitchas — APPROVED** [review]
Seems like a good thing. The Vyrmeid are not connected to the Ember Nodes, so this is a good change to make.

**Comment by MidnightPlugins** [comment]
This issue seems to be caused by the Vyrmeid not being automatons like the Subsidurials.

I foresee a similar issue with Ember Shades and Ember Sylphs also not being automatons.

**Review by Quantumshark — APPROVED** [review]

**Comment by Saugia** [comment]
This issue seems to be caused by the Vyrmeid not being automatons like the Subsidurials.

I foresee a similar issue with Ember Shades and Ember Sylphs also not being automatons.

If that is the case, I could change Vyrmeid to be automations, but the Ember Shades and Embersylphs are part of the Emberwaste so it makes sense that attacking them would also upset attacking the Node just as if you attacked Voidsprites, though I'll leave that for @Zitchas to decide.

**Comment by MidnightPlugins** [comment]
Attacking a non-crewed Indigenous Lifeforms will cause hostility with factions that have a positive attitude towards them until the player leaves the system.

Long term hostility persists if crew members were killed.

This is why "crew equivalent" was created for the Korath automatons and why capturing Shooting Star doesn't have lasting negative reputation with the Author government. Also alluded to in the segment of Free Worlds requiring the player to plunder a Surveillance Pod from a navy drone.

I bring up the Ember Shade and Ember Sylphs because the lore specifies that the Void Sprites have a "special" relationship with the Drak, a government that has the same attitude towards Indigenous Lifeforms as the Ember Waste government. So unless lasting hostility resulting from attacking these other life forms is intentional, they should also be automatons.

**Comment by Saugia** [comment]
If that's the case, there's also the Subsidurials that do not use `automaton` at the moment, so I would open this as an issue or for another PR. The Vyrmeid don't have any relations with other governments so it wouldn't be an issue, however Subsidurials are found in an EW mission, so it's worth bringing up.

**Comment by Quantumshark** [comment]
It would be better to use governments with the right penalties rather than make these things automata when it doesn't make sense for them to be. "Long-term hostility" means reputation changes, and these can be avoided with custom penalties. It would be better to sort out the government relations, rather than make spacelife into automata.

**Comment by Zitchas** [comment]
Yes, I create the Ember Waste government specifically so that the Node *would* care about what is done to the indigenous life in the Ember Waste.

**Comment by Hurleveur** [comment]
If we make these automatons they will still be hostile if you provoked the other space creatures (void sprites), idk if they should be

**Comment by Saugia** [comment]
Reverted `automaton` per the above comments, and added the Iije as well to the new government, which has been renamed to "Indigenous Lifeform (Acheron)".

**Pull request merged**
