### PR TITLE
Dynamic trade implementation

### PR DESCRIPTION
**Pull request by guillochon**
**Updated to the latest version, 12/2/2015:** I have implemented a system of dynamic trade into Endless Sky with this pull request. This system adds a finite reserve of commodities in each system, which is initially calculated using the price set for each commodity in each system. Here is what the updated trading tab looks like:

image

Features:
* While the exact numbers calculated for the initial commodity reserves on each system still likely needs balancing, the total amount of each commodity on each system starts anywhere from a few ten thousands tons to several hundred thousand tons. This limits the maximum amount of profit between two systems to be a few tens of millions.
* Systems produce, consume, and trade goods with neighboring systems (those connected via hyperjumps). The rate of production and consumption are currently set based on how the commodity price compares to the highest and lowest possible prices, whereas the amount of trade is set proportional to the price differential between neighboring systems. All three scale with the "habitability" value of each system (or the sum of the origin and destination habitabilities in the case of trade), which is used as a proxy for population. The total rate of change is displayed beneath the "(+/-)" in the image above.
* As resources deplete or accumulate in a given system, the price adjusts up or down dynamically. When a player buys/sells goods, the prices change in such a way that it is impossible to make a profit by buying/selling repeatedly in the same location.
* All planets in a system share the same pool of resources, this was done partially because the commodity values are defined system-wide, but it makes sense given how easily goods are transportable within a system.
* When first starting the game the player is completely incapable of affecting the economy, but with a convoy of 10+ heavy freighters, it is possible to drain a system of its resources, requiring constant strategizing to find the best routes.
* Because systems trade with one another via hyperjumps (and to a lesser extent jump drives), the economic landscape will react naturally to events in the game (such as when the Pug cut off the Syndicate worlds in the Free Worlds storyline). This adds I think a very nice flavor!
* The reserves of commodities on each world are saved and loaded along with the pilot information, so the dynamic economy is persistent throughout play sessions.

This is a large update and I tried to keep as closely to the coding style as possible (the new "Reserves" class that handles much of the functionality was based on the "Politics" class), and I also realize it's a big change to the game that not everyone may like. However, I've already found that this makes conducting trade a lot more fun! No longer can one run hundreds of times between two systems to wrack up billions of dollars, now there's constant pressure to always be looking for the best available trade deal.

### CODE REVIEW

**Comment by Pointedstick** [comment]
This is **completely** awesome.

**Comment by gchapyzh** [comment]
Absolutely awesome. Do outfits work the same?

**Comment by endless-sky** [comment]
This is a really cool idea. But, I gave it a try to see how the trade prices evolve over time, and for most commodities it tends to "flatten out" the prices - meaning that over time, good trades become harder and harder to find. For example, for plastic:

plastic initial
plastic final

For other commodities, it settles into a state with very sharp transitions (i.e. very lucrative trades) between areas within which the prices are almost identical. For example, for food:

food initial
food final

Another problem is that the planet descriptions tend to be based on what commodities are cheaply available there, but the dynamic prices can change so that a planet where a particular commodity is meant to be plentiful instead has a shortage. For example, it's an important plot point that the Core is one source of cheap fissionable material, but as the simulation evolves the Core actually ends up having a heavy metal shortage:

heavy final

**Comment by guillochon** [comment]
Fantastic plots! I was struggling to find a way to fast forward the clock easily, I only saw things evolve over a few hundred days (is there an easy way to do this that's already implemented?). Certainly the speed that things adjust can be modified easily by changing some constants. And the algorithm can be tweaked to avoid situations like what you show in the bottom plot. Places where the price is high should have shortages, places where the price is low should have surpluses.

**Comment by Pointedstick** [comment]
I hasten to point out that the entire net effect of trade is to equalize prices over time, so this effect is completely realistic! However, from a gameplay perspective, it definitely wouldn't do for the character of regions to be undermined by having commodity prices flatten. Perhaps this could be ameliorated by increasing the production and consumption constants. That way the core will keep on churning out heavy metals and other systems will be hungrier for them. So yeah, tweak the algorithm a bit.

**Comment by dplepage** [comment]
Is `habitable` actually a reliable proxy for population? One system could have several larger planets in a smaller habitable zone, while another has a much larger zone but only one small planet actually in it.

**Comment by guillochon** [comment]
@dplepage Probably not the best, but it was the simplest way to get started. Certainly open to whatever seems the most logical to people.

**Comment by dplepage** [comment]
It might be nice to give each system (or even each planet?) an actual `population` number. That would also allow it to be affected by events - e.g. the populations of Geminus and Martini could drop significantly after the "war begins" event.

**Comment by guillochon** [comment]
@dplepage I agree, although I didn't want to assign those values myself, as I thought it would be difficult to make sure they're consistent with the story.

**Comment by egilburg** [comment]
> This is to prevent abuse as a player could reap huge profits by buying out all the goods in a system (driving up the price), and then immediately reselling his/her cargo in the same system at the higher price. Currently, it takes several weeks of in-game time for the price to adjust to any dramatic player-induced changes in the amount of a given commodity.

I think a better way would be to actually calculate the marginal differences for each item when you buy N items.

In other words, if you buy 5 items one at a time, you should pay the same total price as if you bulk-bought the five.

This way, there would be no advantage trying to buy and immediately resell the same item.

**Comment by guillochon** [comment]
@egilburg Perhaps this wasn't clear, but so long as you don't leave the planet, buying/selling the same good nets no profit/loss (the price doesn't start to adjust until some time elapses). So it doesn't matter if one buys in 1s or 10,000s, the price per unit is the same.

**Comment by endless-sky** [comment]
@guillochon, all I did to make the plots was this:

```diff
diff --git a/source/PlayerInfo.cpp b/source/PlayerInfo.cpp
index f7ce6f4..36d02e8 100644
--- a/source/PlayerInfo.cpp
+++ b/source/PlayerInfo.cpp
@@ -461,7 +461,8 @@ void PlayerInfo::IncrementDate()
        if(!message.empty())
                Messages::Add(message);
        
-       GameData::GetReserves().EvolveDaily();
+       for(int i = 0; i < 10000; ++i)
+               GameData::GetReserves().EvolveDaily();
 }
 
 
@@ -1316,6 +1317,7 @@ const map<string, int> &PlayerInfo::Conditions() const
 // they have actually visited it).
 bool PlayerInfo::HasSeen(const System *system) const
 {
+       return true;
        return (seen.find(system) != seen.end() || KnowsName(system));
 }
 
@@ -1324,6 +1326,7 @@ bool PlayerInfo::HasSeen(const System *system) const
 // Check if the player has visited the given system.
 bool PlayerInfo::HasVisited(const System *system) const
 {
+       return true;
        return (visited.find(system) != visited.end());
 }
```

**Comment by guillochon** [comment]
Haha, well of course... :+1:

**Comment by endless-sky** [comment]
I think ideally, there are two ways to allow the player's actions or random events to alter the trade prices - one simple way, and one complicated way.

The complicated way is to model the flow of goods over time the way you have been doing, but at the outset calculate the rates of flow such that the hard-coded values in the game data are where the prices will converge if not perturbed by outside events. Basically for each commodity you have a giant matrix where each row and column represents a star system and each cell represents rate of trade between two systems. Advancing the model one day would just involve a matrix multiplication, which means that the long-term equilibrium state will be the eigenvalues of the matrix.

The simpler way is to allow random events to perturb commodity prices in a given system by a relatively small amount, say +-25%. Each day you could randomly dump a glut of commodities or a shortage of commodities on a handful of systems - say, each day each system has a 1% chance of an extreme shortage or surplus, and a 10% chance of a random shortage or surplus. The player buying or selling lots of goods would have the same effect. The shortages or surpluses would then propagate out as in your model, but they would always be applying a multiplier within a fixed range, rather than adjusting the absolute price. That means that the tendency to even out over time would cause the "ripples" from these price disturbances to level out to zero given enough time (meaning the system reverts to its default trade price).

I think the second option would be simpler to implement (and would avoid needing to link in a linear algebra library) and would also be more robust over time. In pseudocode, it would basically do this each day for each commodity:

```
for each system:
    multiply the current surplus / shortage by 99% to "dampen" oscillations
    add a random value to the shortage / surplus value
        (usually near zero, but with occasional large negative or positive outliers)
for each system:
    for each system it is connected to:
        move some portion of this system's shortage or surplus to that system
        (as in your model, the rate of transfer would depend on the difference)
```

Then, the budget or surplus in each system could be mapped to a % change in price, somehow - e.g. a simple s-curve mapping.

**Comment by guillochon** [comment]
I definitely like the idea of random events, and agree that a matrix inversion is overkill. I think what makes the game interesting are one-off events where equilibrium is suddenly broken.

I've tweaked things a bit in the algorithm, it now uses DistanceMap so that trade can be conducted within 3 jumps of each system (but with diminishing effect with distance). This way is a bit slower and 10,000 steps is actually quite computationally expensive, but it does avoid some of the islanding problems of before.

**Comment by pellinor0** [comment]
I have a slightly different model in mind, which also has nice stability properties: 

* planet economies are defined by their production rates (which can change by plot/random)
* goods propagate by diffusion over hyperspace links (so flux is proportional to difference in "concentration")
* prices depend on the amount of goods available in the system
* available goods decay exponentially (e.g. each turn 5% of all resources are consumed)

As a physical visualization, this model can describe a metal framework that is constantly heated at certain points. The heat diffuses between connected parts and is dissipated by radiation. 

- This should guarantee a stable equilibrium where the prices reflect the default production rates. 
- Too much player activity on a certain trade route will temporarily flatten out the prices. 
- Direct manipulation of the amounts can lead to large price jumps, which the system will correct over time (this is a nice lever for plot or random events). 
- The physical interpretation might make the model more intuitive to work with (e.g. predicting what a  plot event will do with the price landscape).

**Comment by guillochon** [comment]
@pellinor0 Actually the model presently functions very similar to way you suggest, the prices are set by the amount of goods available in a system, the production rates are tied to the price set in the data files (and can be modified by modifying those values, e.g. by events), and goods are spread via diffusion. Goods decay asymptotically, as the amount of goods goes down the price goes up and the consumption rate decreases. I've put limits on the prices such that they're never outside of the range defined in the commodities.txt file.

**Comment by egilburg** [comment]
Just like we have fixed production rates in supplier systems, we should also have fixed consumption rates in consumer systems.

For example, an Ore refinery has continuous increase in supply of Ore at a fixed price - buying up all the stock will drive the price up, but only temporarily as continuous production would quickly restock at the original price.

On the other hand,  a manufacturing facility would have a fixed consumption rate of any resources it needs below a certain cost. If there is an overstock, it would pay less, but if there is understock it would continue paying its fixed price until all the goods are gone.

That way, prices would spread out between producer<->consumer systems and stay rather constant in systems not on a path between consumer and producer, rather than spread out until they evenly saturate the universe as would be the case with only supplier outputs but no consumer sinks.

**Comment by guillochon** [comment]
@egilburg You are probably partially right on this, and I'd favor maintaining equilibrium over more complicated models that may not. Now both production and consumption are pegged to the initial value (although we still have the option of changing them dynamically via events).

About the only other thing that could be used to improve things is to calculate the equilibrium prices as @endless-sky suggested for the initial conditions, and then write those new equilibrium values to map.txt. This way the fluxes in all systems for all commodities would be +0, at least initially. Or we could just start things slightly out of equilibrium to mimic the fact that the market is never truly in equilibrium.

**Comment by pellinor0** [comment]
@guillochon I haven't really looked into the details, just from reading the description I had the impression that you needed a few extra patches to make the system robust (like "the prices have a built in memory to prevent abuse"). 

A thermodynamic diffusion model naturally comes with the property that you can harvest energy from existing gradients but not from moving things around in any other way. Of course this also assumes that prices are updated while you buy and sell things. 

Maybe we have a different idea of equilibrium, I am talking about a dynamic one. Like a burning candle, a galaxy in equilibrium would not have zero but constant flows. For example a farming planet constantly produces excess food, and the prices in the neighbourhood are such that the sum of the flows equals the excess production. A mining planet might produce no food at all and instead act as a (food-)sink with a higher price. 

I wouldn't spend too much development effort on calculating perfect initial conditions. If the system is as stable as it needs to be, you can just start with something arbitrary and evolve the system for enough steps to get a close-enough equilibrium. Doing this once at the start of a new game should not take too long.

**Comment by guillochon** [comment]
Actually, if each planet has its prices set based on its current stocks (as is the case now), then the fluxes will naturally equilibrate to zero. The interesting part is how the player affects that equilibrium with their actions, and how changes to the game world also affect the equilibrium. This is why the "disasters" aspect is interesting: Suddenly a world might lose half of a commodity, greatly affecting the local equilibrium temporarily. I just think this makes the trade game more interesting than "find the best fixed route and stick to it forever" as it currently is.

**Comment by pellinor0** [comment]
So we have a farming world and a mining world, and the food economy converges to equal prices and no flow between them? This looks like a fault in the system for me. 

We shouldn't need disasters to keep the system away from thermodynamic equilibrium. In my understanding production/consumption should already do this. I'll try some tweaks based on your code. Probably will take a few days.

**Comment by guillochon** [comment]
This is a misunderstanding, the flux of *reserves* on a system approaches zero when the system achieves equilibrium. There is always trade ongoing. Production + consumption + trade = 0, but trade ≠ 0, unless the price of a commodity in both systems is identical.

**Comment by guillochon** [comment]
And disasters aren't necessary, they just pull the system slightly out of equilibrium to add flavor.

**Comment by guillochon** [comment]
All: I think this is very functional now and doesn't break the game. It should maintain equilibrium about the prices set in map.txt with a small adjustment due to trade with neighboring systems. The "disasters" I put into place are really a placeholder; I think it makes sense to add recurrent events to the game that can affect commodity reserves and prices (basically adding a "repeat" and "duration" aspect to events). Interested to know if @endless-sky and others thinks that the current system works well enough for merging, or what sorts of changes are necessary to get it to that point.

**Comment by pellinor0** [comment]
I still have the impression that the system has a few more parameters and mechanics than it needs. 

A few heretic ideas/questions:
* The 'price memory' sounds like treating a symptom instead of its cause. It would be much more consistent to have the price vary while you buy and sell. Of course in a way such that the price for a pile of goods is independent of the chosen increment. So initially the display shows the price for one unit. When you hold a modifier key (say x100), it switches to the average price for buying the next 100 units. (I think this is how Patrician3 did it, I liked that interface). 
* Does it need both production and consumption? Why not one value that can be negative? 
* "Production is linked to commodity price": which one (the fixed parameter or the dynamic variable?). The second would be an explanation why the behavior of the system drifted off too far from the configured initial values. 
* "trade over 3 jumps": this also looks like patching a symptom. The root cause is probably that empty systems are ignored. I think it would be better to have defined prices in empty systems. When your main variable is resource amounts, just treat empty systems like inhabited ones (the capacity represents passing merchant fleets). Then things should work for any galaxy graph. 
* "flux": the name does not fit the variable well. I don't really see what the player should do with this value. 
* I'm still not sure if we need the available resource amounts at all. In my picture a planetary-scale economy always has enough stuff to fill a few spaceships. The limiting factor is not availability but price. Since a scarce good already has a prohibitive price tag, what does this column add to gameplay? 
* Even more heretic: if removing the amounts column, the whole system could be formulated in terms of prices. Making the formulas and variables simpler and closer to what we already have.

**Comment by guillochon** [comment]
Response to your bullets:

* One could do this, but then the problem is that the listed price will *not* be the price per unit. So I think that would add additional confusion, and make it difficult for players to estimate their cost before hitting "buy." But it could be done, not sure what is favored.
* It doesn't need both, but the idea was that one or the other could be affected independently. This could probably be removed.
* The fixed parameter, the "drift" above is from an earlier version. The prices only mildly adjust from the initial conditions now due to trade.
* I'm not sure why this is better, it's far less realistic. I feel what I have is lot closer to reality, goods are less likely to come from 2 jumps than 1 jump, given the danger of pirates.
* Open to suggestions for a better name. It's good for the player to see this because they get a sense of how the prices will adjust in a given system in the future.
* I disagree here. I think this adds an interesting game dynamic, and it's perfectly reasonable for the supply to be limited.
* This is true, but it would get rid of what I think is an interesting addition (see above).

**Comment by pellinor0** [comment]
A name for flux: maybe something like "diff" or "+/-". Hard to find good names that are short enough. Probably a minor issue anyway because the numbers are pretty self explanatory. 

And to your readiness question: maybe the first point (about the listed price) should be decided before merging. Other than that, it looks fine to me and will make a good addition to the game.

**Comment by guillochon** [comment]
OK, I think I have addressed most of your issues @pellinor0. We now calculate the average buying/selling price per commodity when the modifier keys are held down and update the price display on the fly. Because buying in bulk will result in a price that is more expensive per unit than buying one unit, and vice-versa for selling one unit, when the mouse hovers over the [buy] or [sell] buttons, the price changes between the "buying price" and the "selling price."

The price memory is no longer necessary as we correctly calculate how much the goods will cost by performing a mathematical sum assuming that they are purchased one at a time.

I did leave production and consumption as separate functions, but it really doesn't make a difference, it's just whether we add the two within the same function or not.

**Comment by Pointedstick** [comment]
I'd really like to see this merged, in some capacity.

**Comment by endless-sky** [comment]
When this version is run for a long enough time, the long-term steady state is to invert the commodity prices: each commodity becomes cheap on the worlds where it started out pricy, and vice versa. It also still has the problem for some commodities of creating large swaths of space with no price variation at all, making that commodity useless as a trade good within those regions. I'm open to adding a dynamic economy, but not if it causes those problems.

**Comment by guillochon** [comment]
Let me test this some more, I didn't notice this after running a few hundred steps, but it's possible the "disasters" are causing the issue. The behavior should be to approach an equilibrium close to the original equilibrium without the disasters.

**Comment by guillochon** [comment]
Also: Let me know what you think about the "disasters," I think it would make a lot more sense to have them rolled into the event system, but wasn't quite sure how to best implement. Currently the "events" are quite limited, they don't have durations for instance, nor the ability to set random targets or numbers.

**Comment by guillochon** [comment]
OK, should be much closer to balance now. Initial conditions for food prices:

image

After 1000 steps:
image

After 2000 steps:
image

After 3000 steps:
image

**Comment by guillochon** [comment]
OK, I've tested this for a few hours, I think it's in good shape now. Prices remain fairly close to the original prices, although there is slight adjustment due to trade over several thousand steps. Others please feel free to test.

**Comment by dplepage** [comment]
Out of curiosity, how does this react to non-disaster changes in the systems? E.g. if a mission event involves a mining colony being shut down, it might specify that the system now consumes much less food and produces much less metal - will that change propagate much to the surrounding systems?

**Comment by guillochon** [comment]
@dplepage Yes, it should propagate to the neighbors. Although at the moment the propagation is quite slow, part of the balancing will be to determine over what speed the systems should equilibrate. And the maximum number of goods available, etc.

**Comment by guillochon** [comment]
Fixed a few more bugs, spruced up the formatting, reduced starting reserves slightly.

**Comment by endless-sky** [comment]
It looks like your changes to DistanceMap are not needed, because you ended up setting "hasJump" to false in Reserves.cpp, meaning that it will behave exactly the same as the existing DistanceMap code.

I also don't think that the reserves, "flux," etc. should be displayed in the trading panel. Consider how confusing all those columns of numbers would be to 90% of the people playing the game. And, it doesn't really make sense that the player would have intimate knowledge of the inner workings of every planet's economy.

Similarly, I'd prefer if the "blessings and disasters" are not something that gets displayed in the messages every day. There could be some other mechanism where you learn about those events - say, merchant ships might occasionally comment on them.

I also think this should be simplified to only use immediate hyperspace routes, rather than jump routes. That's what all the trade prices do at present, and it seems to work well enough. And, hard-coding the names of certain alien species will mean the engine can't handle new aliens added by plugins or total conversion mods.

**Comment by Pointedstick** [comment]
EV had a way for you to watch the news in the spaceport bar, and that would often inform you of commodity price changes. Such a thing might be nice here too. I kind of miss the news thingy because it was another way for you to read flavor text about the world itself, kind of like how other ships comment on random things that immerses you in the world. That stuff is awesome. We need more of it!

**Comment by guillochon** [comment]
@endless-sky, I like most of these suggestions. Some comments:

> It looks like your changes to DistanceMap are not needed, because you ended up setting "hasJump" to false in Reserves.cpp, meaning that it will behave exactly the same as the existing DistanceMap code.

Duly noted.

> I also don't think that the reserves, "flux," etc. should be displayed in the trading panel. Consider how confusing all those columns of numbers would be to 90% of the people playing the game. And, it doesn't really make sense that the player would have intimate knowledge of the inner workings of every planet's economy.

So if we hide the reserves, should we allow a commodity to "sell out"? One option is to just have the reserves drop below 0, but still permit the player to buy goods, dropping below 0 would just mean that the price in the system would be fixed to "very high" until the reserves recover. Would that be reasonable?

> Similarly, I'd prefer if the "blessings and disasters" are not something that gets displayed in the messages every day. There could be some other mechanism where you learn about those events - say, merchant ships might occasionally comment on them.

Definitely like this because it gives you a reason to hail merchant ships. Perhaps every time an event happens we add it to a list, and then merchants randomly draw from that list. Events fall off the list after a few weeks of in-game time.

> I also think this should be simplified to only use immediate hyperspace routes, rather than jump routes. That's what all the trade prices do at present, and it seems to work well enough. And, hard-coding the names of certain alien species will mean the engine can't handle new aliens added by plugins or total conversion mods.

So I do think there should be trade permitted with systems that are only accessible via jump drives, the Korath do travel to their neighbors occasionally. What about flagging individual systems in map.txt with a "jump tech" or "jump trade" attribute if they possess jump technology? That way we can get rid of the hard-coding solution.

I also think trade should be permitted over wormholes, which I didn't implement, but should be easier now given the recent wormhole improvements. Thoughts?

**Comment by frameworld** [comment]
A few variables nobody thought of yet:
* Food expires.
* Planets with disasters (also economically, especially food) have people(-quests) leaving.
* When a commodity is constantly high/low, usually new companies establish and the supply/drain gets altered (unless there is a reason for it not to happen such as an unpleasant atmosphere on a mining planet).

I like the idea of prices adjusting when players abuse the trade system too much and think that should be implemented as a stable version before shuffling code to get a good supply/demand system.

* It doesn't matter how big the difference is. As long as somebody wants food, somebody is gonna pay for it.

But not all peoples have equal wealth.

* The more luxury goods are available, the fewer is the demand on a specific one and prices on that leverage.
* Opposing that, rich peoples may purchase more luxury the more they already have / are used to buy.

Comparing with food, _difference_ is not the only variable here.

* Luxury goods may also attract more pirates than just simple clothes/food.

Some traders may choose not to trade the best available trade resource (also because of investment).

* There is a cost to each route.

Salaries, Mortgage (not only you!) and a variable that could represent loss to piracy / amount traders.

* The cost for a route may alter based on available ramscopes or security (navy, militia).

**Comment by guillochon** [comment]
OK @endless-sky, I think I've addressed all your new concerns.

* We no longer display the reserves/flux, and reserves can go "negative" in a system. This is invisible to the player and has the effect that stocks of a commodity will very quickly replenish back to their equilibrium level, but the price will remain high until the reserves become positive.

* Commodity blessings/disasters are now shared with the player via ship hails (30% chance per hail, random news item shared per hail). News items have a lifetime of 2 weeks in-game time, and are saved to the pilot file to preserve them between saves/loads. This also opens up the possibility of adding *other* kinds of news via events!

* Trade will now be conducted over jump routes with systems whose government has discovered jump technology, which is specified in governments.txt via the "jump drive fraction" attribute. This removes the need to hard-code who has jump drives, and gives some flexibility (perhaps 1% of independent ships should have jump drives, for instance?)

Let me know if you think we need any other adjustments.

**Comment by sanjayatio** [comment]
@guillochon: Skimmed through that #330 -- wow!

But, if we really want to have a complicated trade system, 
one facility should be added: warehouse.
Make the price steep, for balance, but make it happen.
This will allow greedy-stingy merchant to stockpile if he/she made the wrong investment.
Typical looters can also use it as storage - rather than parking ships just for the outfit capacity. 

What about ships/weapons/outfitting?
Weapon price should rise in time of war.
Ships - especially something like bactrian should be a limited commodity.

Local reputation should play a role on how an outfitter behaves.
One shop may offer discount if you're considered as a local hero
while others may overcharge or even flatly refuse to serve.

An example:
During cease fire periods, we can traverse through republic space;
but it shouldn't mean that we can buy whatever we want.

**Comment by ph2000** [comment]
How do you dowload this ? (I'm new to Github)

**Comment by asl97** [comment]
@ph2000 you down his fork ether using git (and remember to switch branch) or through the github interface https://github.com/guillochon/endless-sky/tree/dynamic-trade

and compile it yourself.

**Comment by bananarer** [comment]
Having problems compiling. Is there some way we can get a compiled version?

**Comment by luiges90** [comment]
@endless-sky Why it is closed? :confused:

**Comment by endless-sky** [comment]
@luiges90, because a different (simpler) dynamic trade implementation has been added, one that I ran through a [simulator](https://github.com/endless-sky/endless-sky-tools/blob/master/dynamic-economy.cpp) to make sure it works. The various versions of this implementation tended to drift into an odd state after several years had passed - e.g. big regions of the galaxy all at the same very high or very low price.

**Comment by guillochon** [comment]
No hard feelings on this closure, the dynamic trade now in the game is fine with me. Just glad we got some more realistic economics now!

**Pull request closed without merging**
