### PR TITLE
Add a sprite for the "Mug" outfit

### PR DESCRIPTION
**Pull request by lumbar527**
**Content (Artwork)**

## Summary
Adds an image for the "Mug" outfit:
Screen Shot 2023-05-26 at 7 31 18 PM

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: endless-sky/endless-sky-assets#138
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: endless-sky/endless-sky-high-dpi#365
 - [ ] Get an approved image.
-  - [x] Centered
-  - [x] Smooth
-  - [ ] Scene improvements (suggestions welcome)
-  - [ ] Update high-dpi and asset PRs

### CODE REVIEW

**Comment by DarcyManoel** [comment]
I'm not a fan of the sprite, it could be improved.

**Comment by bene-dictator** [comment]
Yeah since it comes from a convo in the Deep, maybe there could be something to reflect that on the model.

**Comment by lumbar527** [comment]
Any improvement suggestions?

**Comment by Luuiscool4567** [comment]
Maybe make it "sharper" it seems very rounded to me but not sure anymore.

**Comment by lumbar527** [comment]
Do you mean the resolution?

**Comment by 1010todd** [comment]
The image overall is very dark and flat, since you're probably using newer Blender(2.8+) first you should increase sun brightness to 2.5~3 for closer match to existing sprite. The material also looks wrong, just google Blender tutorials for ceramic material or something. The lip of the mug also looks sharp like you either used a torus scaled up on Z axis or low subdivision, it probably should be rounder. Handle also looks a bit too small for any hand to properly fit in.

I highly suggest getting pictures of actual mug and try to recreate that for starter.

**Comment by lumbar527** [comment]
Thanks! (Also this is totally a torus)

**Comment by lumbar527** [comment]
is this any better?

Is this better? Should I change the color? Does it still not look ceramic?

**Comment by 1010todd** [comment]
Still doesn't look like glazed ceramic to me. Though, mugs don't have to be ceramic I guess but you still have to make it look like whatever material you want it to be(if it's metal it should look like metal, if it's glass it should look like one, etc.). Yeah the color should probably be changed, maybe white or something or maybe some other light color (light blue maybe?). The rim looks better now but the handle shape is still a little odd(iirc typically at least the top part of the handle should be relatively flat), also its too thick.

Also as Bene-dictator suggested maybe it could have some design hinting its origin, maybe check the City-Ship License for idea? Or maybe just make it Bactrian/Mule hodgepodge shaped mug would be fun.

**Comment by lumbar527** [comment]
Mug III:
Screen Shot 2023-05-28 at 11 29 25 AM

Does that look better? I'm not sure what to put in it.

Maybe I should get a different glaze/ceramic formula?

**Comment by lumbar527** [comment]
If anyone wants to help, I'm temporarily putting my .blend file here.

**Comment by mOctave** [comment]
Alright, here's my take on the mug. It could certainly look better, but it's slightly less messy now.
mug
[mug.blend (zipped)](https://github.com/endless-sky/endless-sky/files/11586068/mug.blend.zip)

**Comment by lumbar527** [comment]
I think I just need to get the reflections working, and then make a scene to reflect. Your mug looks great to me, and I think I'll try to add the scene to it.

**Comment by DarcyManoel** [comment]
I couldn't imagine using the handle on that thing, perhaps refer closely to the way mugs are made realistically for inspiration.

**Comment by lumbar527** [comment]
I tried too, but I can make the handle bigger.

**Comment by 1010todd** [comment]
The world color is still too light, it should be black(or at very least far darker color) and maybe the sun could still be brighter. For the reflection did you try ramping up the Specular and decrease Roughness? Then maybe also Increase Clearcoat? For the handle I checked the files and it seems like you're using nurbs curve for handle so just select the end and press E to extrude then you should have more length to work with.

Also the text shouldn't be wrapping around to face the camera, it should be perpendicular to handle or wherever else it should be facing and if the text is not visible then just rotate the mug.

**Comment by lumbar527** [comment]
I've updated mug.blend with my latest things. I'm not sure about what direction the mug should face, and I'm not sure about how to make the text work better. (I'm using my blend, not mOctave's)

**Comment by Saugia** [comment]
Make sure you're using the outfit template/copying the light setup of another outfit. Right now it looks lit poorly and doesn't have much contrast. If you compare it to other outfits, the side facing us is much darker (so having some important insignia may not be the best for the design).

**Comment by bene-dictator** [comment]
> As you wander the spaceport with a snack, waiting for your ship to be refueled, you pass a local souvenir shop and poke your head in to kill a little time. You see a decent looking mug with the text "<origin>" printed underneath an attractive, stylized representation of the spaceport you are presently standing in and pick it up to see how it feels. The handle is solid, not too small for your fingers, and the lip of it looks like it would be comfortable to drink out of.

Keep this in mind. Maybe the conversation might need to be changed.

**Comment by lumbar527** [comment]
If someone makes a major contribution to the blend file, you can make a PR to my fork and show up on the commit if this gets merged.

Also, @mOctave, do you think you could help with the text again? I made a scene but don't know how to do what you did to make it wrap around well.

**Comment by mOctave** [comment]
What I did was do the text as flat, with depth so that the text intersects the mug everywhere. Then I used the boolean modifier to reduce the text to only what was inside the mug, and the displace modifier to offset it a very small distance along its local axis so that it wouldn't z-fight with the mug or be visible on the inside.

**Comment by lumbar527** [comment]
Thanks! Here's my newest sprite:
regular mug

And high dpi:
high-dpi mug

Are they getting closer to something people want?

**Comment by lumbar527** [comment]
Also, @mOctave, do you want me to mention your explanation on how to do things in the copyright?

**Comment by mOctave** [comment]
No, I don't need that.

And it's starting to look quite good, although it could probably be shaded smooth and the scene could use a little more work.

**Comment by lumbar527** [comment]
Sorry, what does "shaded smooth" mean (Is it like make the faces blend into each other better?)

And what would you suggest for the screen?

**Comment by bene-dictator** [comment]
> Is it like make the faces blend into each other better?

Sort of – you lose the edges from the smooth shaded areas, creating a smooth surface from a bunch of edges without needing too many verts.

**Comment by lumbar527** [comment]
I've been trying the `Remesh` modifier, is that going to help?

**Comment by lumbar527** [comment]
Thanks! (I probably need to learn more Blender)

mug-shade smooth

**Review by lumbar527 — COMMENTED** [review]
If there is going to be a mug sprite, the mission text needs to be changed.

`As you wander the spaceport with a snack, waiting for your ship to be refueled, you pass a local souvenir shop and poke your head in to kill a little time. You see a decent looking mug with the text "<origin>" printed underneath an attractive, stylized representation of the spaceport you are presently standing in and pick it up to see how it feels. The handle is solid, not too small for your fingers, and the lip of it looks like it would be comfortable to drink out of.`
What should it be?

**Comment by lumbar527** [comment]
Anyone have ideas for the scene on the mug?

**Comment by Saugia** [comment]
@Anarchist2 Weren't you working on a Mug as well?

**Comment by Saugia** [comment]
I have to agree with the others that the lighting and materials doesn't really blend well together with the rest of our outfit sprites. I'd recommend opening another outfit's blend file/copying the light setup/copying your model into the file. If you're using Blender 2.79, you'll have to make sure it's an older outfit. If you're using Blender 2.8+, make sure it's newer, and I strongly recommend using the Cycles render engine as we do for most outfits done in that version (Eevee gets messy with shading if you're not sure how to go about it).

As for textures, there are two ways you can go about it. One is simply making a brown material and exporting the render to GIMP to touch it up there (what I usually do). The other is to do texture mapping/nodes within blender (2.8+), but if you're at a beginner level, this might be daunting and it'd be easier to do it the other way.

Aside from the above, I'm...not really sure what's going on with this PR. It looks like there was a second attempt in the comments (still has the same lighting issues), but the files show the first iteration still. It seems like you have some checkmarks unchecked still and have things to do. The branch keeps getting updated, but nothing seems to be updating in the files. So for now, I'm reverting the PR back to draft form.

**Comment by lumbar527** [comment]
OK, I'll work on that soon.

Yes, I'm kind of a Blender beginner.

**Pull request closed without merging**
