### PR TITLE
Unfettered Hai story: Terraform Warfeed

### PR DESCRIPTION
**Pull request by NomadicVolcano**
## Summary

The Unfettered Hai food situation grows desperate as the environment on Warfeed nears a catastrophic collapse. The Hai refuse to help terraform Warfeed in fear it would make the Unfettered too strong, and the Wanderer war effort is too slow to feed the masses. Tired of insulting food donations from the Hai, the Unfettered turn to Captain `<last>` to arrange a large-scale smuggling operation to terraform Warfeed.

This story drags you into the night side of Endless Sky, to Marauders, a Hai mafia, a "Syndicate off-shoot," crooked bounty hunters, pirate scientists, and a deeply disturbed six-year-old. As you emerge, you're not sure you've done more good than harm. The entire story is playable if you've turned Pirate; all missions grant clearance because everyone is asking you to do something illegal.

There is also a secret super-boss fight, while being taunted by a six-year-old.

The main quest reward is a unique outfit designed for early-game piracy and smuggling. There is a short, follow-on, Drak/Quarg, side-story to upgrade that outfit late in the game.

This pull request adds 51 missions, so I'm providing a little guide to simplify testing.

## PR Checklist
 - [X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [X] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/open?id=1Z3sC9BqMEMzwMq7lAgI8oHG-X6ghr_3Z
 - [X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/117

## Bugs that Aren't

You'll see conflicting information from different characters, things that don't quite make sense, information that contradicts cannon, or get the feeling that something is missing. If a teenager claims to have single-handedly advanced armor technology by centuries, something isn't right. It reaches the point where you don't know what is real and what isn't. That's because everyone is lying to you or manipulating you. Welcome to the night side of Endless Sky.

~~Affinities towards the `"Hai"` and `" Hai "` governments must be the same. That is fixed in pull request #4902 which is incorporated into this pull request.~~ (That PR has been merged.)

There are three places the game breaks due to bug #1938 which is fixed by pull request #4764: missions will stay on the job board one landing after they're finished, Snuggles will not taunt you until two landings after you hire her, and she'll taunt you one landing after her ship is destroyed. These bugs are fixed by that pull request. NOTE: *The story is written so it still makes sense with the bugs present.*

## Guide and Saves

I'll give you two players to test this: 

1. For testing the balance of the mission, Megas Archon.  Megas has ships ranging from medium warship to low-tech capital ships (Shield Beetles). Only Hai and Human tech, and no jump drives.

2. To power through the missions and just test if they work, Omega Turtle. ("There are turtles all the way down, but I'm the biggest.") Omega has a Bactrian and a vast fleet of capital ships. Omega Turtle has met all requirements for the Drak/Quarg follow-on story other than finishing this story.

### Starting point

There are two possible starting points for this story: North Pirate space or Hai space. Both Freedom and Makerplace give you a 100% chance of seeing the mission. 

- Balance testing: Hai start with Megas Archon: 
[Megas Archon~1401 START.txt](https://github.com/endless-sky/endless-sky/files/4310129/Megas.Archon.1401.START.txt)

- Only technical testing: Hai start with Omega Turtle: 
[Omega Turtle~3026 warfeed start.txt](https://github.com/endless-sky/endless-sky/files/4310033/Omega.Turtle.3026.warfeed.start.txt)

- Only technical testing: North Pirate start with Omega Turtle: 
[Omega Turtle~3027 warfeed pirate start.txt](https://github.com/endless-sky/endless-sky/files/4310016/Omega.Turtle.3027.warfeed.pirate.start.txt)

Megas Archon has several options for flagships. "Six Ion Beetle 1" can handle all missions, including the super-boss. The "Six Tracker Manta" or "Particle Corvette" are closer to what I expect players to have. "Fast Ship" lives up to its name; use it for smuggling. The "Scram Cargo" ships are more accessible smuggling ships for early players. I parked a few captured pirate ships that I haven't outfitted yet (Ospray, Leviathan, etc.) if you want to try tweaking them.

### Guide: Terraform Warfeed

At the spaceport, you should see one of these:

- Freedom: "As you walk from a bar to salon, a cloaked man approaches you..."
- Makerplace: "As you peruse the spaceport establishments, a Hai beckons you from a dark stairwell..."

After the mission on Shroud, you'll be hunted by "Syndicate?" government ships. If you're in a fast ship, you may not notice them. Kill them before you fight the bounty hunter or it'll be a harder fight when they catch up.

You'll be asked to hire a bounty hunter to kill you. There are four, but only three will be listed. To get the fourth hunter, the super-boss fight, you need to "come back later" seven times. Details on that in a later section.

When you're asked to dodge "White River's Spy," the "Six Ion Beetle 1" won't be able to since the two ships are evenly matched. The easiest way for that ship to deal with the spy is to fly to Durax and wait for the spy's ship to be disabled. Then leave and finish the mission. The "Fast Ship" can out-run anything, so it won't have trouble with this mission.

After you reach Darkcloak, you need to visit the spaceport to get a 72 ton smuggling mission. If you don't have space, you should be able to leave the planet and come back. Talk to the planet and the authorities will scold you and let you land. (The later 133 ton mission from Greenrock has the same feature.)

For the 72 ton smuggling mission from Unfettered space to the South, Megas Archon (the balance testing player) has no perfect option. The "Fast Ship" will need to stop to ramscoop, but it is hard to catch. The "Six Ion Beetle 1" can refuel through pillaging, but it is easier to catch.

### Guide: Koor'alei Skin

This is the quest reward and the subject of the follow-on story. 

#### Get the Reward Outfit

First, you need to finish the prior story and get the outfit. After you set up the smuggling route, and visit Follower and Snowfeather one last time, you'll need to wait seven days to get the next stage of the mission. Then land on any of these planets for a 100% chance of the mission: Follower, Furnace, Greenrock, Kraken Station, Makerplace, or Snowfeather. (It can happen anywhere in Human or Hai space with a 10% chance.) 

You'll receive a confusing message from Lilith who wants to give you a present at Buccaneer Bay. The present is the quest reward outfit: some flakes of skin from an ancient creature that was nearly invincible and invisible.

The outfit's main ability are its big boost to radar jamming and scan interference, and it slowly repairs your hull and refuels you. This is the perfect early-game pirate outfit. There's a constant energy drain which necessitates either a large ship or a nuclear generator though. The outfit is rendered useless early when cloaking replaces jamming and interference. The follow-on story fixes that by upgrading the hull repair.

#### Upgrade the Reward Outfit

That quest begins when Lilith asks you to find a way to destroy the skin. This save file begins just after you receive the skin:

[Omega Turtle~3030 have armor.txt](https://github.com/endless-sky/endless-sky/files/4310177/Omega.Turtle.3030.have.armor.txt)

You'll be sent to Quarg scientists and then a Drak Archon. The Drak will promise to "reawaken" the skin once you've proven yourself to be a peacemaker. Do this by finishing Wanderers Start, the main story, and returning the void sprite eggs. After that, you have to wait 30 days. Or use this save file instead:

[Omega Turtle~3031 before upgrade.txt](https://github.com/endless-sky/endless-sky/files/4310237/Omega.Turtle.3031.before.upgrade.txt)

Depart, and land on Korati Efreti (or anywhere other than Kuwaru Efreti). You'll receive a telepathic message. Then head to Kuwaru Efreti in the same system to finish the story and upgrade the outfit.

### Guide: Sparkle Snuggles

This is the secret bounty hunter. Choose "come back later" seven times at Foundry, and she'll be the first option. She'll contact you eventually and accept the contract to kill you. After that, land twice and you'll start receiving "threatening" messages from her, every time you land. In battle, she'll taunt you. It comes off more "cute" than "threatening" because she's six and hasn't learned to intimidate anything more dangerous than a sandwich. Once her ship is disabled, if you talk to it, she'll tell you she's in an escape pod and begs you to destroy the ship.

Later, from analyzing information, you can deduce a bit more about her. She's a kidnapped six-year-old girl named Rosa from New Boston, who is the mascot of a group of bounty hunters. From the ship (Model 256), its outfits (Sestor and Metri), and their association with a "Syndicate off-shoot," it seems likely they're connected to the Alphas that have Kor Sestor technology. That means she is probably being groomed for future use as a willing host for Alpha fetuses. Nice fate for a six-year-old, right? It's good that Captain `<last>` is there to rescue her.

#### Taunting

Snuggle Sparkles (AKA Rosa) will taunt you when you land. You'll start seeing these two landings after she accepts the contract. (Two, due to issue #1938.) Examples:

- `You receive a threatening message from Sparkle Snuggles, "I can see you. Come out, so I can love you with my bombs!"`
- `You receive a threatening message from Sparkle Snuggles, "'Captain <first> dummy <last> the ker-splat!' That's gonna be on your grave."`
- `You receive an intimidating present from Sparkle Snuggles. It's a batch of cookies with words written in icing. Most of them say, "ded," "burn," or "soon." Your scanners say there are no poisons or toxins in the cookies, so you try a few. The cookies are delicious.`
- `You receive a threatening video from Sparkle Snuggles. It opens with her grinning psychotically at the camera. She's hugging her bear in one hand and pointing at the camera with the other. She doesn't blink or move for about 30 seconds and then rolls on the floor laughing.`

## Lessons to Learn

Don't judge a race by the first person you meet. Not every Quarg is a super-scientist omni-sage. Some of them are poetry teachers. Not every Unfettered Hai is a bird-smashing baby-eater who thinks the Drak are demons. Not all Fettered Hai are peaceful and law-abiding. Some marauders are upbeat, pleasant, intelligent, spy-scientists. 

Six-year-old girls are dangerous when they have a Model 256 with twin Korath Detainers.

There are secrets in the universe much older than the Drak. For how many races do they mourn?

### CODE REVIEW

**Comment by Zitchas** [comment]
Haven't looked at the actual text yet, but the synopsis sounds good. 

I also like the "ph34r t3h cu73 on35." I sincerely hope she has that as a hail when the player sees her in space.

**Comment by NomadicVolcano** [comment]
> Haven't looked at the actual text yet, but the synopsis sounds good.
> 
> I also like the "ph34r t3h cu73 on35." I sincerely hope she has that as a hail when the player sees her in space. (although I also hope she's not named Piroko. Referencing copyrighted works is something we've leaned away from in other instances. If that is her name, changing it to Pirok0 or something is probably sufficient. (Although this isn't an endgames or megatokyo -like universe, so the character obviously isn't the same character, so probably shouldn't be any problems anyway.)

I didn't include that phrase in the game for the very reason you describe: copyright restrictions. Plus, that phrase, and its numbers within, are core to the story of Megatokyo. They're almost a perfect description of the environment of the comic.

Sparkle Snuggles (Rosa) talks like a normal six-year-old. Her words are those of an annoying little sister pestering you for not playing with her, or for being a bad pilot. In the end, like the annoying little sister that she is, she expects you to save her from trouble.

**Comment by Zitchas** [comment]
OK, if there's no characters with any names from Megatokyo involved, I think you are perfectly clear to include that as a hail. While Megatokyo may have popularized it, I don't think it is exclusive to it.

**Comment by NomadicVolcano** [comment]
> OK, if there's no characters with any names from Megatokyo involved, I think you are perfectly clear to include that as a hail. While Megatokyo may have popularized it, I don't think it is exclusive to it.

I'm trying to keep her as a normal six-year-old, not someone that speaks l33t. I'll give a few examples of planet landing messages. 

The farthest she goes from normal english words is embedded emojis:

- `You receive a threatening message from Sparkle Snuggles, "(=.=) Just give up! (x.x)"`
- `You receive a threatening message from Sparkle Snuggles, "(^o^) I know where you are! (^o^)"`

The rest of her stuff is regular english:

- `You receive a threatening message from Sparkle Snuggles, "Your ship looks so cute and tiny! I want to make it, 'splat!' like a bug!"`
- `You receive an intimidating present from Sparkle Snuggles. It's a "happy birthday" card where "birth" has been replaced with "deth," written in crayon. Below that, you see the word "sune." Inside the card, you can see the words, "gona getcha" repeated over and over.`
- `You receive a threatening video from Sparkle Snuggles. She is dressed in a giant lizard suit in a cramped room filled with paper buildings and paper people. She's stomping violently through the room, smashing everything. Occasionally, she stops to rip the head off of a paper person. The people all have your name on them.`

**Comment by tmoftdead** [comment]
I love this story line, but I think the dialogue in Wanderers Hai Assistance 2 to cut off aid becomes obsolete after this, as unfetttered do have food after this.
Also, the hai tribute missions become obsolete as well because they have food.
(I think unfettered food prices should go down as well, but I never saw a mission which affected trade prices)
Those missions can easily be fixed with small dialogue changes,(I would like to make them but sadly I don't know how to do it and I don't want to break something.)

**Comment by NomadicVolcano** [comment]
> I love this story line, but I think the dialogue in Wanderers Hai Assistance 2 to cut off aid becomes obsolete after this, as unfetttered do have food after this.
> Also, the hai tribute missions become obsolete as well because they have food.
> (I think unfettered food prices should go down as well, but I never saw a mission which affected trade prices)
> Those missions can easily be fixed with small dialogue changes,(I would like to make them but sadly I don't know how to do it and I don't want to break something.)

No, they don't have much food. A thousand tons of food from the wanderers will not feed billions of people for very long. Nominally, you need 600,000 tons per day for a billion people, and the Unfettered Hai probably have several billion. It is also very small compared to the amount of food they received daily from the Fettered Hai. That's why they're still desperate to take over Wanderer territory, and why the food prices are still high. It is also the main motivation of the war. It turns "we want to fight" into "we have no choice but to fight." Terraforming Warfeed will fix that problem, but it will take a few years to boost crop production after terraforming is complete.

A few years after they have all Wanderer territory, and have started farming all of those planets, they will have an enormous excess of food. That will be quite a while after Wanderers Act 3.

**Comment by NomadicVolcano** [comment]
> Looks good to me on my first pass.
> My only gripe with this is the Ancient Skin. It seems odd that the skin remained on Stormhold for so long, without some high-tier race recovering it, such as the Quarg, Pug, Drak or similar.

No, it is implausible that any of those races would have found a stealth artifact buried several miles under the ground in a planet far from all of their territories. The Quarg were amazed to find some dragons they dearly missed. That archaeological site was vast and buried only a few hundred meters. This is a stealth outfit buried several kilometers. The Pug wouldn't have cared, and may have even left it to be found. The Drak were too busy killing each other to notice anything until recently (on the Drak scale of years), and more recently they've stayed away from everything. Also, the Drak are not all-knowing.

So, no. It is completely expected for them to miss this.

**Comment by Zitchas** [comment]
Drak killing each other? What?

**Comment by NomadicVolcano** [comment]
> Drak killing each other? What?

`Not that the Drak are strangers to war. Planets and moons and even stars were consumed in their wars and are no more. But then they learned wisdom,...`

**Comment by ira210** [comment]
It isn't working for me, i have tried it as a pugin and put the unfetteded misssions file into the hai data file and i get the fist mission but nothing happens when i land on snowfeather. I have tried all 3 saves and am running 0.9.12

**Comment by NomadicVolcano** [comment]
Closing all pull requests related to this account.

**Comment by W1zrad** [comment]
Just so it's mentioned on this PR, I'm planning on taking this content, addressing its issues, and re-PRing it (while still giving credit to NomadicVolcano, of course). Feel free to send me your thoughts, suggestions, or comments about the PR.

**Comment by UnorderedSigh** [comment]
@W1zrad @MasterOfGrey Do you still have interest in resurrecting this? It is one of my favorite stories, and I was the basis of the six-year-old. Right now I'm busy testing the Hai Reveal and some of @Hurleveur's stuff, but I can probably get to this in a few weeks.

Btw, I can probably charm/coerce NV into logging in long enough to give permission for people to use her content. Do you need that?

**Comment by UnorderedSigh** [comment]
Ah, there seems to be some confusion in the comments. There are no plot holes or cannon violations. In my interpretation of the story, everything is disinformation and half-truths, until the follow-up where you talk to the Quarg. Even the premise of the story is an apparent fabrication: Warfeed's environment never changes, regardless of what you do.

Absence of terraforming is more true to the spirit of the story, because it raises more questions than it answers. Is the terraforming taking longer than expected? Or did the Unfettered lie about why they needed the supplies? Maybe it's for more sinister purposes? Bioweapons, perhaps? Such foreboding loose ends make for a better story.

Actually, after I fix all the bugs, I want to add two missions:

1. Try to visit Whispering Rose a few months after the story ends, only to find the store is gone. Nearby residents deny the building even existed.
2. Visit Warfeed a year later and find that nothing has changed. Ask the planet authorities about it, and get an evasive answer about how useful you were.

It also needs connections to the Hai Reveal for you to report illegal actions instead of completing the missions.

**Comment by MasterOfGrey** [comment]
Definitely still interested in it being resurrected.
But point of note: Warfeed would have already been terraformed in the past. It would actually be looking at dealing with a fairly recent degradation of its state, presumably due to conflict and subsequent mismanagement. So it's more a *restoration* of a previously terraformed state that would be theoretically the goal.

Of course, this can still be a lie, but is potentially important to how it's presented.

**Comment by UnorderedSigh** [comment]
Yes, many details are wrong. The story is presented awkwardly because it wasn't originally supposed to be a story on its own. NV was going to use these missions as the first chapter of her Night Sky campaign, to setup the atmosphere. Once she realized the campaign would take another 400 hours to implement if she worked alone, she gave up on that. Then she put in last-minute changes to make it a self-contained story. In other words, it isn't a finished product.

I know how to tweak it to be a better stand-alone story, and I've planned a twist ending in another follow-on mission sequence.

**Pull request closed without merging**
