### PR TITLE
Removing obsolete fourth-wall dialog text

### PR DESCRIPTION
**Pull request by alextd**
It seems to me that the dialog option"I want to explore the rest of the galaxy, but apparently that part of the game hasn't been implemented yet" is probably obsolete dialog, since I am doing that in my game.

(I didn't check when this was added, don't know if there are huge plans for more exploring, didn't verify it works, but I'm pretty sure the format is still okay)

### CODE REVIEW

**Comment by Amazinite** [comment]
Well there *is* still a lot of galaxy missing.
image

And the intention of that choice seems to largely be about the fact that the game is open source and that you can contribute, and nothing has changed about that, even if new systems have been added to the game since that choice was added.

**Comment by ZBok** [comment]
I think this breaking of the 4th wall is ok and a cool way of letting the player know they can get involved without ruining any storyline vibe as it's already over by then.

I do think the Player dialogue ("I want to explore but that part of the game hasn't been implemented yet") could possibly be worded a little differently, like maybe "I want to explore but it seems that vast areas of the galaxy cannot be reached", while removing Ijs comment and have just Katya break the fourth wall with her response, but that's just my opinion.

**Comment by petervdmeer** [comment]
> I think this breaking of the 4th wall is ok and a cool way of letting the player know they can get involved without ruining any storyline vibe as it's already over by then.

When I encountered this 4th wall dialog, then it did actually break the story-line vibe for me.
You are immersed in the story and you expect some in-game story-line closure, not references to outside the game by in-game characters.

A good thing about the 4th wall dialog is that it encourages players to contribute to the game. The dialog suggested that contributions from players are very welcome and it is one of the things that convinced me to send in some PRs.

**Comment by Pointedstick** [comment]
I think this is something we want to keep. It could be worded with a bit more subtlety, maybe. But overall this should stay in. A little levity and fourth-wall-breaking can be used strategically, and as has been mentioned, it's a good invitation to contribute.

**Pull request closed without merging**
