### PR TITLE
Allow projectiles to not collide with ships or asteroids

### PR DESCRIPTION
**Pull request by Amazinite**
**Feature**

This PR is an idea I came up with a awhile ago. It'll be useful when combined with some other features I have planned.

## Summary
Adds new weapon attributes with no value (like "cluster" or "safe").
* `"no ship collisions"`: This weapon's projectiles won't run collision detection against ships (unless it is a phasing projectile and has a target). Weapons with a trigger radius will still explode when within range of an enemy even if they can't directly collide with one.
* `"no asteroid collisions"`: This weapon's projectiles won't run collision detection against tiled asteroids.
* `"no minable collisions"`: This weapon's projectiles won't run collision detection against minables.

## Usage examples
The following weapon would only explode when it is within 100 units of an enemy. It would phase through all asteroids along the way.
```
weapon
	"no asteroid collisions"
	"no minable collisions"
	"trigger radius" 100
	"blast radius" 200
```

## Testing Done
Tested the Gridfire to ensure that it still behaved the same way: no asteroid or minable collisions, can collide with any ship when not targeting, can only collide with the target ship when targeting.

Tested a weapon with each of the "no collision" attributes individually and observed that they weren't able to hit objects that they had no collisions against, but could hit the other two object types.

### CODE REVIEW

**Comment by tibetiroka** [comment]
Would it make sense to give this values to make it immune to only ship or asteroid collisions?

`"no collisions" ship`

`"no collisions" asteroid`

The default one would be immune to both.

**Comment by Amazinite** [comment]
Phasing will actually behave like a normal projectile if it has no target.

**Comment by Amazinite** [comment]
I've split the attribute into three so that we can individually control which object types a weapon can hit.

**Review by Hurleveur — APPROVED** [review]
Looks good to me code wise

**Pull request merged**
