### PR TITLE
spartan-Spartan

### PR DESCRIPTION
**Pull request by Gkramme**
Had to look it up, but Spartan has a capital s.

### CODE REVIEW

**Comment by Gkramme** [comment]
@Alkallid Where?

**Comment by endless-sky** [comment]
[Google Ngrams](https://books.google.com/ngrams/graph?content=Spartan%2Cspartan&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CSpartan%3B%2Cc0%3B.t1%3B%2Cspartan%3B%2Cc0) says it's about an 80-20 split, but with the lower-case form gaining ground. And, [Merriam-Webster](http://www.merriam-webster.com/dictionary/Spartan) says "often not capitalized" when used as an adjective. So, I think the usage is divided enough that there's no clear right answer.

**Comment by Alkallid** [comment]
An example usage by Google.

**Comment by LocalGod79** [comment]
what M.Z. basically said is "Spartan" - someone from Sparta - is capitalized, while "spartan" - used as a description of 'bare, or basic' - is quite acceptable according to Merriam-Webster.

**Comment by Gkramme** [comment]
Dunno what I did here, closing this

**Pull request closed without merging**
