### PR TITLE
Feat: operating costs on old ships and slower depreciation

### PR DESCRIPTION
**Pull request by Hurleveur**
**Feature:** as discussed here https://github.com/endless-sky/endless-sky/issues/7826, this improves depreciation mechanic to better achieve what it planned to do

## Feature Details
Once you get too many ships the game gets too easy.
Once you capture too many ships the game gets too easy.
Late game you don't know how to spend your money, and finally there is too much pressure to sell your ships right away.

All of those issues are at least partially solved by this elegant solution:
A ship will have an operating cost that you will pay daily, which will become higher as it's depreciation increases.
To compensate, depreciation will increase much slower. (going from 0.997 to 0.999)

A sparrow with 99% of it's value will cost 2.2 additional credits to maintain (since its worth 440000, it's 0.000005 of it), and an additional 2.2 per % of depreciation, which will of course cap at 25% depreciation, costing you 75 * 2.2 = 165. A palavret would cost 21k per day. Keep in mind it already has a crew cost of at least 15k, so it's not too far off from that.
The flagship does not have any maintenance costs to not have too much of an effect on newer players, and encourage smaller fleets play even more.
This additional cost will only be in effect when the ship is not parked, and will be displayed in the UI right next to the cost (won't go overboard ^^) this also takes into account how much the ship costs and gives per day, finally showing that into the UI.
I expect it will discourage huge fleet playtroughs and make the mid game less trivial, without giving any hard blockers.

As soon as gamerules are out I will add one for this. 
There are not many changes here but I also moved the code for calculating the ship costs and income to the ship itself instead of being in player info for some reason, since I need to be able to use it elsewhere (in the shipinfodisplay).

## UI Screenshots
Doesn't go out of the screen because I added it to where the cost is displayed.

## Usage Examples
n/a

## Testing Done
Tested manually with a new and old pilots and it worked as expected.

### Automated Tests Added
n/a

## Performance Impact
n/a

### CODE REVIEW

**Comment by Hurleveur** [comment]
42k is the cap, it's how much it costs after 1386 days if you normally buy it. Capturing it is supposed to be discouraged.
The exact amount can always be tweaked though, but since it already costs 15k from crew it doesn't seem that big, maybe cut it in 2 once again? As I said this would be a gamerule players could play with as they want, eventually.

**Comment by rovermicrover** [comment]
Could there be a refurbish feature added to the shipyard where you reset the counter by paying the appreciation?

Also sorry if I missed this but is depreciation based on days active or just general days?

**Comment by Hurleveur** [comment]
Just general days or we'd have to write the amount of days a ship has been active in the savefiles.

Also that feature makes sense, but may as well keep it for another PR maybe? Idk

**Comment by Amazinite** [comment]
#2219, #3659, #7333.

**Comment by SimulatedKnave** [comment]
Damn, that was fast. 

I may be the only person who WOULD like maintenance on the flagship. lol

Love variable maintenace by ship class. 

Suspect one could slow depreciation down even more without much loss. 

Looking forward to trying this.

**Comment by Hurleveur** [comment]
> #2219, #3659, #7333.

I see the first two have been rejected, do you mean I should try and do the third instead of this?
Also this one isnt on outfits its on the entire ship.

**Comment by Hurleveur** [comment]
Would adding a way to repair your ship be good enough (if they sell the same model in the shipyard then allow to repair it?) I dont see anyone being against this idea
Maybe only base it on the hull and ignore outfits?

**Comment by Amazinite** [comment]
I don't think the player should be punished just because the stuff they have is older. Depreciation is in some sense already its own punishment for having old stuff, but you only feel that punishment when selling what you have. If you keep what you have, then you never actually lose any value. This on the other hand actively increases a player's expenses just because their stuff is old, which I don't think is how we should go about things. Even if the values are low, it's still a punishment that shouldn't exist.

More generally, I don't think we should be actively gunning for large fleet players. I feel like fleet size should largely be a gameplay style decision and that we shouldn't be trying to force/influence players to have smaller fleets.

**Comment by SimulatedKnave** [comment]
If there is no actual reason for depreciation (i.e. increased maintenance), then people are refusing to pay full price for your alien superweapons because the paint is scuffed. Which is silly. You want to talk punishments that shouldn't exist, there's one. 

If there is no benefit to things not depreciating other than their resale value, the smart move for the player is to just pirate stuff willy-nilly rather than ever buying new. This gives a reason to buy equipment new, and even to replace equipment sometimes if you want. 

It also means there's an actual reason for depreciation, as opposed to it just being a tax on the player existing.

**Comment by Hurleveur** [comment]
As I said before gamerules would be great for this.
I guess that when that PR's in I'll make this a default off toggle, then?

**Comment by SimulatedKnave** [comment]
I'd love it as a plugin or something in the interim. I very much want to use it.

**Comment by bene-dictator** [comment]
> I'd love it as a plugin or something in the interim. I very much want to use it.

You can build it yourself or download it with ESLauncher2.

**Comment by quyykk** [comment]
As this has been unlikely-ed I'll close it at this point.

**Comment by Hurleveur** [comment]
I'll just reopen it when we get gamerules

**Pull request closed without merging**
