### PR TITLE
fix(ui): Make RenderBuffer respect DPI scaling

### PR DESCRIPTION
**Pull request by implicitfield**
**Bug fix**

## Summary
This PR makes `RenderBuffer` respect DPI scaling (currently, this affects plugin descriptions and dialog boxes, as those are the only things that utilize `RenderBuffer`.) In the screenshot below, the old rendering of a plugin description can be seen on the left, and the output of this PR on the right.

## Screenshots
Combined

## Testing Done
The above screenshots were rendered on a highdpi screen (with a scale factor of 2.) Also tested disabling highdpi support, and in that case the rendering correctly appears the same with and without this PR.

## Performance Impact
N/A

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
@implicitfield Could you post your screen resolution and OS on which you've tested this?

**Comment by warp-core** [comment]
Can you share some of your other display settings? Is display scaling active?

**Review by Koranir — APPROVED** [review]

**Comment by warp-core** [comment]
I've tested this on a Mac and seen that it works.
I'm concerned that the same behaviour doesn't seem to happen on Windows, and also that this wasn't a problem prior to the use of RenderBuffer here.
It seems like there is something different about how the "Screen" class reads the resolution depending on OS, which isn't itself surprising, but it seems that the result is also OS specific behaviour on our side of the "Screen", not just where "Screen" interfaces with the OS. This isn't great. I wouldn't expect a need for OS specific handling of values reported by "Screen".

**Comment by warp-core** [comment]
I'm going to merge this, but I still want to know what RenderBuffer does differently that requires this because it doesn't appear to have been necessary when PreferencesPanel was handling the sprite and text drawing itself, or in anything else that doesn't use RenderBuffer.

**Pull request merged**
