### PR TITLE
Switch File I/O to SDL_RWops

### PR DESCRIPTION
**Pull request by thewierdnut**
This will support reading files from android-assets, as well as normal
I/O for PCs.

-----------------------
**Feature:** This is the beginning of a series of merges to implement #1502

## Feature Details
Specifically, this switches over to the SDL_RWops api for file I/O. This allows an android port to read from the apk assets as well as from the file system. 

## Testing Done
Tested on android and desktop builds, made sure that files could still be read and written

## Performance Impact
N/A

### CODE REVIEW

**Comment by quyykk** [comment]
Interesting. The only problem I see is that this introduces a dependency on SDL for file handling, which is why the tests fail to compile: They are built without SDL.

I'm not quite sure if an Android port make sense in the first place, that's yet another platform we need to support and the changes required to the game to make it work without a keyboard would be substantial.

**Comment by thewierdnut** [comment]
I would love to know the reason the tests are built without SDL. It seems like they build fine with SDL. 

I have had to make some changes to the interface and to the commands (coming in a future merge request) to get the game to be playable, but I've been working through the storyline for two weeks now, and I think it works out fine. 

I agree that there will be additional maintenance costs going forward to having another platform, and I will admit that my availability will be sporadic. I would like to keep the costs on the main code base minimal, and it would be great to get some opinions on how to do that if we want to go forward with this.

**Comment by tehhowch** [comment]
Hi, thanks for your interest in the project! To echo Nick though, I'm not certain of the value in this change for this particular repo at this time. That said:

1) Don't link SDL into the unit tests. I'd much rather you use a test mock instead. Unfortunately you'll get to be the one who implements that, too, as this is a volunteer project where that hasn't been necessary yet. (Note that our unit tests need to be runnable via `scons test` on Windows & Linux, and also through the Code::Blocks IDE & its CPB files.)
2) Since you are sharing your branch with us, please don't force-push to it. Push new commits that clearly show what you changed and whose message indicates why you changed it that way.
This project squash-merges contributions; we keep a linear base branch history while gaining the educational information associated with an iterative arrival at a solution.

**Comment by thewierdnut** [comment]
The unit tests link with Files as well, which has a dependency on SDL already. I think the only reason for the successful compilation is the link time optimization, which isn't a reliable way to handle dependencies. 

What is the reason that you don't want SDL linking with the unit tests? They way you guys use it, its less of a media library, and more of an operating system abstraction layer anyways.

**Comment by thewierdnut** [comment]
I think I have addressed everybody's immediate concerns, so at this point, we are left with the bigger issue... Should endless sky support android platforms?

Let me stoke your fears by explaining what I have done so far to get the game to be playable. 
1. An abstraction layer needs to be added to be able to read game assets. That is the purpose of this merge request, since SDL_RWops contains most of the abstraction we need already. SDL doesn't have the ability to parse directories however, which means we need more code added to Files.cpp to be able to handle the android use case. I currently have code (not part of this merge request) that directly accesses the android asset classes via the JNI to be able to accomplish this, which is conditionally compiled via the `__ANDROID__` preprocessor macro. 
2. A separate code path needs to be added to Panel.h to handle touchscreen events. Without keyboard controls, new mechanisms need to be added that allow the player to navigate and trigger actions. I currently have support for triggering the map, zooming, scanning, navigating, and jumping. If a touch event is not handled by one of these actions, then it calls the normal click events, which handle things like landing and boarding, plus all the UI buttons, but I picture these code paths diverging over time as we refine the touch controls. Note that other platforms besides android support touchscreens, and because we can discriminate between mouse events and touchscreen events in the event handler, there is no need to conditionally compile or create a preference to toggle this behavior. 
3. We will need an alternate layout to be able to handle some of the panels. A small screen size means the text is too small to read, and many of the clickable elements are hard to touch accurately. The main issue I had was with the planet panel. When I zoomed the UI enough to be able to read it, most of the buttons along the bottom were cut off from the screen. I solved this by removing the top half of the planet dialog and rendering the landscape image behind the text. I think the result looks pretty good, although it could benefit from adjustments by somebody better at graphics than me. 

Well, this sounds like a lot of changes, both now, and to maintain going forward. So why should we consider it? Because its *fun*. I spent six hours hunting pirates yesterday on my phone while I was at an event where I didn't have access to my computer. I consider the time I spent adding android support well worth it just for my own ability to play the game on my phone, even if my changes end up getting rejected. 

If you don't like the SDL_RWops changes in this merge request, but are still interested in adding android support, I can find a different solution (Probably involving the jni interface I mentioned in part 1 above). Just let me know.

**Comment by MCOfficer** [comment]
No offense, but it being fun was never in question, and isn't really a good argument when pitted against maintenance effort. And if we were to reject it, that wouldn't rule out the possibility of an uptodate android fork that doesn't place the burden of maintenance on us - see f.e. https://github.com/thomasballinger/endless-web.

**Comment by thewierdnut** [comment]
Ok. I'll see what I can do. Thanks for the advice.

**Comment by Zitchas** [comment]
Definitely an interesting project, and perhaps relevant as touch screen things become more and more common. I can't see myself playing ES on my phone, but there's some tablets out there that are more than big enough, not to mention the flipping screens on notebooks and laptops.

The arguments against maintaining a 4th OS to support are significant, though, which makes this a good candidate for a parallel but separate project, such as the ES-on-the-web thing. I'm sure there would be plenty of people interested in playing it on their mobile device too.

**Comment by thewierdnut** [comment]
For anybody who cares, a new fork is at https://github.com/thewierdnut/endless-mobile

**Pull request closed without merging**
