### PR TITLE
Save a ship's base mass.

### PR DESCRIPTION
**Pull request by Hacklin**
Fix issue #3480

### CODE REVIEW

**Comment by Hacklin** [comment]
The OutfitInfoDisplay is a separate issue.
Not fixing it in this pull request.

**Comment by endless-sky** [comment]
Given that the bug was only present for a day, I'll probably leave a week or two for people to use this code to mend any issues with their saved games, then revert the changes that were only work-arounds for the bug.

**Comment by Hacklin** [comment]
Fine.
You should revert all changes to 'source/Outfit.cpp' and
the ship's chassis mass check in 'source/Ship.cpp' lines 373-387.

However, I'm not sure about the ships with a base class in 'source/Ship.cpp' lines 106-107.
These 2 lines shouldn't be needed (and can be reverted),
as a ship with any base attributes should also have a base/chassis mass.

Just leave the 'Save a ship's base mass.' commit.

Note:
I changed the `Outfit::Add()` and `Outfit::Reset()` methods,
but in hindsight I should just have added an `Outfit::ResetMass()` method.

**Comment by Hacklin** [comment]
@endless-sky: What do you prefer, separate git branches for fixes and workarounds or separate commits for fixes and workarounds in the same git branch?

**Comment by endless-sky** [comment]
In this case it made sense to put them together, for the sake of anyone who needed to patch a corrupted game.

**Pull request merged**
