### PR TITLE
Neutralise directional baked lighting to omni

### PR DESCRIPTION
**Pull request by SamKeightley**
Baked lighting on top down vehicles that can rotate 360 degrees looks strange. This commit neutralises this so that this effect is negated. These are the result of a scrip that I wrote in Photoshop. Asymmetric vehicles will require being updated by hand or replaced with symmetric variants at a later stage have been included as well but would be happy to revert them in this pull request if desired. 

Comparisons to old graphics are showcased by viewing the commit itself: https://github.com/endless-sky/endless-sky/pull/2206/commits/e73280a518f6094afd225cf2232938843f59a044

### CODE REVIEW

**Comment by Bladewood** [comment]
I must point out that some of the sprites are offset by a few pixels, and are [rougher, less smooth] on the edges.

**Comment by SamKeightley** [comment]
I did notice the slight offset on some of the sprites. This is the result of them being vertically centered to the center of the canvas in the script. If this is a problem I can re-run the script if you require.

As for the edges, I'm not sure what you mean.

**Comment by Amazinite** [comment]
This ruins asymetrical ships (e.g. Bactrian, Barb), and I don't see thing getting merged. The point of the shadowing was to give a more 3D look, and removing them make some ships look really flat and bland.

**Comment by Amazinite** [comment]
Relevant: #595
This is a FAR better solution, but even this got shot down.

**Comment by MessyMix** [comment]
What is with the mirroring of sprites? It is an inelegant and unaesthetic solution.

Honestly, I think the current system is fine, imo.

**Comment by SamKeightley** [comment]
I love it when people fail to read haha. 

"Flat" and "Bland" are easily fixed, and in fact I had done just that as well. The reason I kept them stock is because I didn't want people saying they preferred "Flat" and "Bland" sprites lol. You can't please anyone, the point is that they can be fixed to how the devs would prefer it. 

> What is with the mirroring of sprites? It is an inelegant and unaesthetic solution.
> 
> Honestly, I think the current system is fine, imo.

What drivel.

**Comment by MessyMix** [comment]
Excuse me, that was very rude of you. I reserve my right to my own opinion.

**Comment by SamKeightley** [comment]
It was, Then I realised that and then elaborated upon it before your reply. No need to have an ineligant sense of entitlement though, were all here because we allwant to improve this awesome game, and I think we should be able to all work together to do so.

**Comment by MessyMix** [comment]
@SamKeightley Of course we are here to improve this awesome game, and I did not intend to come across as overly critical. In fact, I think removing unidirectional shadows is a great idea. However, I think #595 may be a better solution, although we are not seeing your finished work, right? Perhaps your talents would be better directed at reworking and developing that one.

**Comment by SamKeightley** [comment]
Yup, these are not finished yet. 

I'm really impressed with #595 but think the main concern there was performance. That point would also extend the work being done here so would be happy to investigate that later as a next step.

**Comment by Wrzlprnft** [comment]
would this mean every content creator would need photoshop and get the script running or rely on someone to do that? i'd really dislike that.
i'd rather change the blender files and the template to achieve the same effect.
i am, unlike with #595, not convinced that this is a step forward. removing directional lighting is a good idea, but removing almost all the shadows takes far to much away from the pseudo-3D-ness.

though, i think, that is debatable personal opinion.
but since MZ made the directional lighting in the blend files on purpose, i doubt this is going to be merged.

you can work on it, though. try to get rid of anything in the progress one would need to pay for, and try to achieve a more 3D effect, and i'm in.

**Comment by whismerhill** [comment]
sorry but these look bad to me, until it's improved I don't like it.

**Comment by SamKeightley** [comment]
Nope, I just used a script to go over the 150 or so sprites instead of doing it manually. Any imaging program can be used to create the same effect. 

They do look bad at the moment, but saw more value in showing the default versions instead of showing edited versions and have people disliking them outright. I'm improving them all now go a level I think will satisfy all the current feedback/observations.

**Comment by jafdy** [comment]
The ships all look cartoony and some (Barb, Bactrian) look out right daft. 
First off you should do all the a-symmetric ships before opening the pull.
Second, this is a step back. #595 is the better way of fixing this.

**Comment by KiLEdEnNis** [comment]
@jafdy wasn't it closed because it'd be too intense for the game engine in large battles?

**Comment by Pointedstick** [comment]
We should really lobby for re-investigating https://github.com/endless-sky/endless-sky/issues/595 instead.

**Comment by jafdy** [comment]
Files that don't have a normal map use what ever the base image is. 
Setting that turns off the normal mapping and just generates a single image when the sprite is loaded up.

That would give no change needed to plugins and an option to come back to the point we are already at.

**Comment by Amazinite** [comment]
@KiLEdEnNis There was never any actual reason given from MZ.

**Comment by SamKeightley** [comment]
> The ships all look cartoony and some (Barb, Bactrian) look out right daft.
> First off you should do all the a-symmetric ships before opening the pull.
> Second, this is a step back. #595 is the better way of fixing this.

Just relax dude, you are being too pedantic. Wait for me to make some fixes and contribute properly. 

If you read my earlier posts you will notice that I said I would be investigating #595 further with newer sprites...

**Comment by SamKeightley** [comment]
I'll close this PR and make another one when the art has been completed.

**Pull request closed without merging**
