### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by warp-core**
Changed Varu K'est description from 'Varu K'est is a spare, ancient planet...' to 'Varu K'est is a sparse, ancient planet...'

### CODE REVIEW

**Comment by endless-sky** [comment]
This already got discussed in #1421 - that's a valid meaning of the word "spare," and in fact it's closer to the meaning I intended than "sparse" would be. That is, the original meaning of the adjective "spare" is "meager, not plentiful."

**Comment by KevinKorzekwa** [comment]
Spare in this context feels unnatural, which is why it would feel like a typo to most playing.  If you want the meaning to be 'not plentiful' you may want to change it to another word.  Possibly "uninhabited/vacant/deserted" if you want it to specifically refer to population, or "paltry/miserable" if you want planet to seem negative in terms of aesthetics or conditions.

Spare just seems as if you're saying it's an extra planet or something.  That it doesn't matter.  This doesn't match the rest of the description, so to keep 'spare' in there you would probably want to change the rest of the description.  But you are, ultimately, correct. Spare in its adjective form can meager, inadequate.

**Comment by KiLEdEnNis** [comment]
in my opinion, if something is spelled right, but everyone thinks it isn't, it should be changed, but if that happens everywhere the game only uses basic English words, making reading boring (because new words keep it interesting)

@KevinKorzekwa never doubt the almighty MZ >:(

**Comment by Zireael07** [comment]
English major here, it would never occur to me to think 'not plentiful' upon seeing 'spare', especially in a computer game,

**Pull request closed without merging**
