### PR TITLE
Fix one problem with scanning

### PR DESCRIPTION
**Pull request by warp-core**
**Bugfix:**

## Fix Details
It has been noted in various places that some ships, such as Smews, are unable to complete scans with scan speeds below some threshold. (https://github.com/endless-sky/endless-sky/pull/7229#issuecomment-1255644369, #8395, as examples.)

The reason seems to be an oversight in the related to `AI::FindTarget()` where it may return a nullpointer which results in the ships target being changed (its target pointer was previously not null) so it resets the scan progressw.
If the scan speed is sufficiently high that the ship can complete its scan before it attempts to look for a new target, there is no issue, which is where the apparent threshold behaviour came from.

This PR prevents this by ensuring that `AI::FindTarget()` looks for targets to scan if no other option is available before returning a nullpointer, and it will prioritise a ship it is already in the process of scanning.

## Testing Done
Hang out in Remnant space for a little bit and notice that Smews and such are able to scan me, without this, they are not.

### CODE REVIEW

**Comment by Zitchas** [comment]
Does this explain why fighers can't complete a scan but non-carriable ships (Starlings, for instance) can complete them?

**Comment by warp-core** [comment]
> Does this explain why fighers can't complete a scan but non-carriable ships (Starlings, for instance) can complete them?

Yes

**Review by quyykk — COMMENTED** [review]
Do you know where exactly it loses its target?

I haven't looked at this in detail, so I might be wrong, but it would seem to be cleaner for the code in FindTarget that searches for a ship to scan to consider its previous target as well so that it doesn't switch targets if it overshoots and finds a closer candidate, if that makes sense.

**Comment by samrocketman** [comment]
I've seen the targeting issue with 1 ship.

**Comment by warp-core** [comment]
> Do you know where exactly it loses its target?
> 
> I haven't looked at this in detail, so I might be wrong, but it would seem to be cleaner for the code in FindTarget that searches for a ship to scan to consider its previous target as well so that it doesn't switch targets if it overshoots and finds a closer candidate, if that makes sense.

A stock Smew gets to line 1192 which returns a null pointer. This is then passed to `Ship::SetTargetShip()`, and since this doesn't point to the same object as its existing target pointer, it resets the scan progress.
Later, in `AI::DoSurveillance()`, it reacquires the same target (me, there is no other ship in this system) and continues to try scanning me, but its progress was reset so it never finishes (a scan speed high enough that it completes the scan faster than the retarget interval overcomes this, which is what I saw when I was testing 7229 in September, though I didn't narrow it down to this at that point.)

**Comment by Amazinite** [comment]
Can confirm that Smews can successfully scan ships now, but once they're finished scanning they're sitting around doing nothing. Sometimes a carrier with spare bays comes in and they try to dock, but the carrier isn't waiting for them, so it leaves the system and the Smews go back to doing nothing.
image

And although it's technically optimal, I find it a little odd that the Smews will fly *directly* on top of me, getting as close as possible.

And I know that we have a check to have ships not try to scan a ship that a friendly already scanned, but I'm pretty sure this isn't working. If I idle in a Remnant system, Smews build up as more successfully scan me.
https://github.com/endless-sky/endless-sky/blob/eface8816033d8e0eefdbf1a3770d1bb469d0e35/source/AI.cpp#L1335-L1337

I think that insofar as this PR resolves the bug that it sought to, it's fine to merge, but the above notes are something to look into for future PRs.

**Comment by warp-core** [comment]
> Can confirm that Smews can successfully scan ships now, but once they're finished scanning they're sitting around doing nothing. Sometimes a carrier with spare bays comes in and they try to dock, but the carrier isn't waiting for them, so it leaves the system and the Smews go back to doing nothing. image

That's just what surveillance ships do when they have nothing to scan or fight. @tibetiroka has a PR that makes them "patrol" the system instead.

It is perhaps a bit strange that so much effort is put into demonstrating scanning by the Remnant when they'll actually only ever scan the player's ships, or the occasional solo-flight Korath chaser.

> And I know that we have a check to have ships not try to scan a ship that a friendly already scanned, but I'm pretty sure this isn't working. If I idle in a Remnant system, Smews build up as more successfully scan me.

Yes

**Comment by samrocketman** [comment]
> That's just what surveillance ships do when they have nothing to scan or fight.

I agree.  Sitting still is part of the surveillance AI behavior when it has nothing to surveil.  A ship stop command is issued.

**Pull request merged**
