### PR TITLE
More variety in many of the word lists

### PR DESCRIPTION
**Pull request by Pointedstick**
This makes repeats much less likely, as well as decreases the previously-inappropriately-high frequency of ships with titles and human names.

Also, how was "cutlass" not already in the pirate word list!? 😁

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
Hey, you could spice up the bandnames as well. I failed in creating sophisticated references and ended up just doing some random stuff.

**Comment by Pointedstick** [comment]
Yeah, I can work on that at some point.

**Comment by Bladewood** [comment]
let me throw in the ship names I've used in the past.
because I was bored.

- vindicator
- nemesis
- horizon's edge
- god's fury
- shattered void
- thunderbolt
- punisher

**Comment by Pointedstick** [comment]
Those sound like some good pirate ship names. 🙂

**Comment by BorkBorkGoesTheCode** [comment]
Add O'Reilley's Daughter.

**Comment by Bladewood** [comment]
http://www.dictionary.com/browse/vindicate?s=t

**Comment by endless-sky** [comment]
I usually call my Star Barge "Mr. Bungles."

**Pull request merged**
