### PR TITLE
(bugfix) Don't display the "you have missions that require landing on [planet]" notice for bounty hunter missions

### PR DESCRIPTION
**Pull request by OcelotWalrus**
# Bug fix

This PR addresses the bug/feature described in issue #9992

Related?: #8779

## Summary
To fix the bug described in #9992, this PR disables the "you have missions that require landing on [planet]" notice for every failed missions.

## Usage examples
This is useful for missions that don't end on a planet, but still have a destination, like bounty jobs.

## Testing Done
I've ran a bounty hunter mission to see if the notice showed up, and it didn't

## Performance Impact
N/A

## Alternatives

An alternative would be to make missions able to be completed outside of planets.

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
Instead of introducing a new attribute, we can just check if the mission is failed (until #10015 gets merged, use `HasFailed(player)`). The message doesn't make sense for failed missions IMO, and because of the "fail to complete" hack used in bounties, finished bounties are considered failed, too.

**Comment by TomGoodIdea** [comment]
Also, the whitespace changes seem unrelated.

**Comment by OcelotWalrus** [comment]
> Instead of introducing a new attribute, we can just check if the mission is failed (until #10015 gets merged, use `HasFailed(player)`). The message doesn't make sense for failed missions IMO, and because of the "fail to complete" hack used in bounties, finished bounties are considered failed, too.

Indeed, that's a much better way to do this; I'm getting to it.

> Also, the whitespace changes seem unrelated.

I just noticed them while coding.

**Comment by warp-core** [comment]
The editorconfig file specifically leaves indentations like these in:
https://github.com/endless-sky/endless-sky/blob/acde3d27531c24dca4496811dc11a8058662a95f/.editorconfig#L9-L12
If we do want to change indentation on empty lines, it shouldn't be done in a PR that makes an entirely unrelated change to an entirely different part of the game code.

**Comment by OcelotWalrus** [comment]
> The editorconfig file specifically leaves indentations like these in:
> 
> https://github.com/endless-sky/endless-sky/blob/acde3d27531c24dca4496811dc11a8058662a95f/.editorconfig#L9-L12
> 
> If we do want to change indentation on empty lines, it shouldn't be done in a PR that makes an entirely unrelated change to an entirely different part of the game code.

Right on. I'm reverting these changes right now

**Pull request merged**
