### PR TITLE
Make coward and appeasing trigger earlier

### PR DESCRIPTION
**Pull request by Hurleveur**
~~The wiki description says cowards run at 0% shield but they do not, I updated it to match that.~~

The wiki's description needs to be updated to say that this happens to a ship when he reaches critical health, it works almost in the exact same way appeasing does except this one just gets out of there (generally it does match 0 shield but it actually is 35% of total health, meaning hull left before being disabled + shield / full available hull before disabled + full shields)

~~On top of that I discovered that coward wasn't working properly, because the current target was not removed so the ship would just exit the fleet and keep on fighting it's current target instead of getting the heck out of there.
So this makes cowards actually behave as you would expect, instead of stubbornly keeping on attacking the old target.~~

This was my initial theory but further testing revealed it wasn't the case, coward just needed a bit of a boost to when it toggles in order for coward fleet to feel coward and not try leaving when its already too late. As suggested by Amazinite I raised the treshold to 50%. This does affect appeasing ships, but they usually drop their cargo way too late anyway.
The code for making the ship actually flee was also changed to take that treshold into consideration, as suggested.

### CODE REVIEW

**Comment by quyykk** [comment]
I think that was the intended behavior when it was introduced in #3369. So, the wiki should be changed imo.

**Comment by Hurleveur** [comment]
really ? well I will have to add a new personality then ? crap
I want my unfettered ships to run when shields are down caus otherwise you just farm them so easily on the Hai border that it should be illegal x)

**Comment by quyykk** [comment]
Well, your ships will just run sooner (instead of running at 0 shields they run at 35% shields). Which is good if you want them to be harder to disable.

**Comment by Hurleveur** [comment]
they don't run at 35% shield, they run at 35% hull

**Comment by quyykk** [comment]
Oh oops, you're right. I misunderstood.

**Comment by Zitchas** [comment]
Just a thought: What happens when cowards face a ship with a lot of piercing? I'd say that a ship with the "coward" personality that still has lots of shields left (maybe even full shields) should still run away if it's hull gets below a certain threshold. Given the way the personality is described, maybe it should simply run away the instant it takes *any* hull damage, no matter how insignificant. It is described as being cowardly, after all.

Either that, or we have two separate personalities. One for fleeing when shields drop, and another that flees when hull gets below a eertain amount.

That being said, I think that *all* ships should flee combat when they've sustained heavy hull damage. That's not being cowardly, that's being smart.

**Comment by Hurleveur** [comment]
yeah I agree that hull points should be way more significant that shield in the equation calculating health
and we found the problem I think, cowards just don't get the order to leave the system after being split from the fleet ^^'

**Comment by Hurleveur** [comment]
I tested it as much as I could and cowards do now behave like actual cowards, running as soon as shields go down, as opposed to before, I just changed that their target is reset caus otherwise they keep attacking even when they are getting killed

**Review by Amazinite — COMMENTED** [review]
I'm not noticing any different behavior with this. I created a coward pirate fleet with a Bastion flagship and Quicksilver escort. Attacking the Quicksilver with and without these changes, it flees after its shields are nearly depleted, while without coward it just continues to fight.

**Comment by Amazinite** [comment]
Could it be that the threshold is just too low to get coward's effect to actually show up? If I wanted to I could kill the Quicksilver I was testing with before it could actually escape the system, and that was with only using two heavy laser turrets. Perhaps we should raise the threshold to at least 50%, or have coward ships measure their current health against the strength of the enemies in the system somehow (although that would be a more involve change than just raising the threshold).

**Comment by Hurleveur** [comment]
> I think just raising the threshold should be enough, as ships normally try to flee combat at 25% health anyway, and having coward do the same thing at 35% health isn't much of a difference.

I tried it, it works perfectly indeed, there was not a problem of target as I assumed earlier, only of how quickly it would trigger, and 50% seems to work perfectly well.
About looking at all the ships in the system, it could be done but I feel like even if you are massively outnumbering the opponent individual fights can still happen and the point is that if that one goes badly the coward will leave. (as opposed to the whole big fight going badly, that would apply to a smart general)

**Comment by Hurleveur** [comment]
I think I just saw what I wanted to see, earlier and now
Leaving the fleet is simply no guarantee of leaving the system, which I think a coward should do at the same time?

**Comment by Amazinite** [comment]
Try changing `ship.Health() < RETREAT_HEALTH` to `ship.Health() < (RETREAT_HEALTH + 0.25 * person.IsCoward())`
https://github.com/endless-sky/endless-sky/blob/a00776497199a388c0dcc416d006c939063efa66/source/AI.cpp#L1244-L1249

**Comment by Hurleveur** [comment]
It seems to be required that you have no target for that bit of code to trigger? (which is why I initially was resetting the target)
I will test different things to be sure.

**Comment by Amazinite** [comment]
Well if a coward ship doesn't reset its target when its personality gets triggered, it'll reach this point and reset its target anyway within half a second.

**Comment by Hurleveur** [comment]
You're right, I hadn't noticed the changing target every half second part.

**Pull request merged**
