### PR TITLE
Escort mission improvements

### PR DESCRIPTION
**Pull request by Pointedstick**
This Pull Request implements https://github.com/endless-sky/endless-sky/issues/1773 as well as a few other minor changes to the escort missions. Here is a summary of the changes:
- Split each of the Northern and Core escort jobs into two, one of which is offered only at dangerous origins (frontier, north, core) but wants to go to safe destinations ("near earth", paradise, deep), and the other of which is offered at safe origins and wants to go to dangerous destinations.
- Changed the pirate fleet locations so that the dangerous origin jobs don't have pirates waiting at the destination, and the dangerous destination jobs don't have pirates waiting at the origin. In both cases, the removed pirate fleets instead spawn at a random nearby location (close to the origin for the dangerous origin jobs, and close to the destination for the dangerous destination jobs) and follow you, adding an element of randomness which should spice up the jobs a bit.
- Added an additional randomly-spawning small pirate fleet to the dangerous origin and dangerous destination jobs, to decrease the chance of you missing one of the pirate fleets entirely (if desired, I can do the same for the Southern escort missions too).
- Changed the job description texts to reflect the nature of each escort job (out of, into, or through dangerous space).
- Increased the maximum distance of the core-dangerous-origin jobs to 5 so that no matter where you are in Syndicate space, there is always the possibility of taking an escort job to another region of space.
- Fixed some problems with the Tiny escort jobs I added a while back:
  - Referred to the captains who hire you using gender-neutral language.
  - Added "on visit" tokens.
  - Made the escorted ship random (was fixed before).
  - Made the spawned pirate ships random (was fixed before) and added a chance that they'll be slightly tougher (Berserker vs Sparrow or Wasp).
  - Added an additional pirate ship with a random spawn point to increase the difficulty after hearing reports that these missions are not challenging and a source of easy credits in the early game.
  - Increased the maximum distance by one jump.

### CODE REVIEW

**Comment by Bladewood** [comment]
...um... berserker*?

**Comment by Pointedstick** [comment]
Oops, good catch!

**Comment by endless-sky** [comment]
I think the "Large, Southern, Dangerous Origin or Destination" job ought to have a minimum and maximum distance specified, like all the other escort jobs.

The "Tiny" missions should check `has "ships: Interceptor"` rather than checking that your cargo space is less than 20, so that they'll be offered even if you have a sparrow with a cargo pod, and won't be offered if you have a shuttle with a mass expansion.

**Comment by Pointedstick** [comment]
Done!

**Comment by endless-sky** [comment]
Looks good, thanks!

**Pull request merged**
