### PR TITLE
Add raid to Hai space

### PR DESCRIPTION
**Pull request by mOctave**
Not exactly a bugfix, but close enough...

**Bugfix:** This PR addresses issue #7237

## Fix Details
Added one line to the governments.txt file under Hai:
> "raid" "Unfettered Raid"

## Testing Done
I didn't test it really beyond making sure it works: adding one line to a data file shouldn't cause other issues.

## Save File
This save file can be used to verify the bugfix. The bug will occur when using 0.9.14, and will not occur when using this branch's build. Plugins are installed but are not required.
[Atlantian Cruise.txt](https://github.com/endless-sky/endless-sky/files/9590794/Atlantian.Cruise.txt)

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Is this going to make the entirety of Hai space as busy and violent as the northern systems?

**Comment by Hurleveur** [comment]
I was wanting to do this since quite some time, I just intended to do so after reworking the raid mechanics, but that's not at all a requirement. Indeed it makes sense the UHai would have some "spies" amongst the Hai.
I approve this idea, however I'm not sure if that "Unfettered Raid" fleet is the right one, we should probably add some more spice to it (its just a bunch of shield beetles).
By that I mean it needs to be more random, sometimes bringing one shield beetle, sometimes 2 (but very unlikely), and often a few lightning bugs and such smaller ships. I recommend taking a look at line 2342 of fleets.txt; the pirate raids fleet.

**Comment by mOctave** [comment]
> Is this going to make the entirety of Hai space as busy and violent as the northern systems?

It will add a raid that will only happen if the player has too much cargo space and not enough weapon space. It won't affect which fleets spawn naturally in Hai space.

>  I approve this idea, however I'm not sure if that "Unfettered Raid" fleet is the right one, we should probably add some more spice to it (its just a bunch of shield beetles).

I'll write up a new fleet for it, then, and also distinguish between the raid in Wanderer space and the raid in Hai space.

**Comment by mOctave** [comment]
I've added the new fleet, although I haven't had a chance to test it yet.

And the style-check fails, without any useful debug information. Anyone have any ideas as to why? As far as I can tell, the styling is all correct...

**Comment by Hurleveur** [comment]
It wants a final newline in hai fleets.
When it doesnt show the error just close the "error" that's shown and open it again.

About the fleets its looking good we're just lacking the spawnrates of the pirate raids, what I mean by that is that everything has a likelihood (variant) of 1, we could have smaller, more common fleets, and rare fleets of this size.

**Comment by MasterOfGrey** [comment]
Ah now that I've seen the discussion and understand what's going on here. I have some thoughts:

1. Hai space is intentionally "safe", that's a chunk of the lore, and the Unfettered are explicitly contained - with the only way around that containment being jump drives that they're hiding so as not to show their hand. As such, unfettered ships are definitely not appropriate for use in a raid in Hai space. Period.
2. Canonically there are occasional issues with _human_ pirates, and also human smugglers. These would be the appropriate sources of possible raids.
3. Human pirates that can actually make it that far are exclusively marauders.

So, if you want to add raids to Hai space that trigger when you have too much cargo then they should be either:
- A deep strike marauder fleet with at least one amped up cargo ship in the fleet to carry off loot.
- A "merchant" fleet that is actually smugglers in disguise taking an opportunistic moment to make bank off someone vulnerable.

Hai ships should not be involved with the marauder fleet, but could be involved with the smuggler fleet (ala the "Hai Merchant (Human)" government).

In either case, you'd probably want to consider building some ship variants for this that utilise combinations of Hai and Human tech and are explicitly geared to either avoid or defend from Hai Surveillance and Large Hai fleets.

**Comment by ThrawnCA** [comment]
> So, if you want to add raids to Hai space that trigger when you have too much cargo then they should be either:
> 
> * A deep strike marauder fleet with at least one amped up cargo ship in the fleet to carry off loot.
> * A "merchant" fleet that is actually smugglers in disguise taking an opportunistic moment to make bank off someone vulnerable.

This sounds promising.

**Comment by Amazinite** [comment]
I'd prefer if Hai space just didn't have raid fleets, as it does now. Hai space may allow for easy trading, but so to does Wanderer space or Coalition space. Coalition space particularly I feel is even better than Hai space for racking up loads of credits trading and doing jobs. There may be a difference in that those locations require a jump drive to get to, but that doesn't change much when it comes to players who know what they're doing.

**Comment by ThrawnCA** [comment]
Well, I'm not an experienced player, and wouldn't know offhand how to go about obtaining a jump drive, but I found my way to Hai space easily enough. My 11-year-old installed a fuel pod on his starter and did the same. It's available basically immediately and without any combat, except running from random pirates on the way in.

**Comment by Amazinite** [comment]
A price for the exploratory.

**Comment by Quantumshark** [comment]
If trading in Hai space is too strong of a source of money, I would argue that a better solution would be to reduce the variance in commodity prices in Hai space. I'm not convinced it makes sense for that small region of space to have the same full range of commodity prices that you get across the whole of human space, especially given that the Hai society is supposedly more stable and organised than human space.

**Comment by ThrawnCA** [comment]
> If trading in Hai space is too strong of a source of money, I would argue that a better solution would be to reduce the variance in commodity prices in Hai space.

That would make less difference than you might think, since you can just pile up missions until you're full.

But I'm happy to discuss alternate solutions on #7237. I had an idea about limiting how many ships can land at a spaceport...

**Comment by Amazinite** [comment]
Note that in human space, pirate raids don't prevent freighter snowballing, they only slow it down by requiring that you also protect your freighters. So in Hai space, where one doesn't need to worry about raids, it makes sense that the method of slowing down snowballing would not be increasing expenses via needing defensive ships but reducing revenue via smaller margins.

**Comment by mOctave** [comment]
I'll close this PR then. I would definitely support reducing commodity price variation as an alternative, though.

**Pull request closed without merging**
