### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by Wrzlprnft**
#405

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
89fd173

**Comment by endless-sky** [comment]
Thanks!

**Comment by anonybosch** [comment]
Thanks from me too, Wrzl, since I'm still having a great deal of trouble just getting from page to page around here, not to mention actually getting anything accomplished.

**Comment by Wrzlprnft** [comment]
No problem, in future just post issues, there will be somebody around to fix them.
I personally don't know what to do with the knowledge i have, sometimes, so i am glad guys like you find things i can do :)

**Pull request merged**
