### PR TITLE
Use Mk2 variants in Navy Surveillance fleets

### PR DESCRIPTION
**Pull request by tehhowch**

### CODE REVIEW

**Comment by Bladewood** [comment]
Uh, then the Gunboats are useless for actual surveillance missions...

**Comment by KiLEdEnNis** [comment]
I'm speaking from experience: FW borders get SPAMMED with Navy Surveillance, at least until the point where the 1st 3 worlds are joining the FW (which is where I am in my 1st playthrough after half a year+), so sitting back waiting for the tech isn't really an option
although that fix would be reducing the frequency a lot, which would make the weapon farming even easier like Bladewood said

still, I think that even the surveillance fleets should be updated to use the new tech, considering they're going into enemy territory, plundering Electron tech won't be that much easier and ya unlock it at the end of the story anyway

**Comment by tehhowch** [comment]
>Uh, then the Gunboats are useless for actual surveillance missions....

Care to explain?

**Comment by KiLEdEnNis** [comment]
Mark II Gunboats have no scanners

**Comment by tehhowch** [comment]
Yep, just saw that.

**Pull request closed without merging**
