### PR TITLE
Add a Person which reminds the player to make a pause while playing.

### PR DESCRIPTION
**Pull request by Wrzlprnft**
Other games have a more (black&white2) or less (anno 1404) sophisticated way to remember the player to make a break from time to time. Since there is no simple way to track the playtime **in one session**, i just lowered the frequency to ensure this person doesn't pop in too often.
I thought it is a neat idea, and consulted local god, which resulted in this pull. Name is open for discussion.
2x image:
coffee machine 2x

### CODE REVIEW

**Comment by LocalGod79** [comment]
mapped turrets on the knobs;
	turret 35.5 -27.5 "Heavy Anti-Missile Turret"
	turret -35.5 -27.5 "Heavy Anti-Missile Turret"
	turret 35.5 -42.5 "Plasma Turret"
	turret -35.5 -42.5 "Plasma Turret"
	turret 35.5 -59.5 "Plasma Turret"
	turret -35.5 -59.5 "Plasma Turret"

**Comment by LocalGod79** [comment]
engines
	engine -51 117.5
	engine 0 117.5
	engine 51 117.5

**Comment by Wrzlprnft** [comment]
i thought i mapped the turrets to the... oh wait... i messed the versions up where i made the pull request from.

**Comment by LocalGod79** [comment]
Also I like "Coffee Cruiser" as the ship class, and "The Grind" as the ship name...

**Comment by LocalGod79** [comment]
also, some phrasing i had done up when we were first talking about this;
		phrase
			word
				"Look at you go!  "
				"Well on your way to Galactic fame, I see.  "
			word
				"Perhaps it's time to "
				"Do you think you should "
				"Can you believe studies have shown that you should periodically "
			word
				"get up and walk around for 30 seconds to a minute "
				"take a break "
				"take a washroom break "
				"step outside for a breath of fresh air "
				"have a coffee "
			word
				"so you can "
			word
				"improve your focus?"
				"maintain your focus?"
				"improve your health?"
				"maintain your health?"
				"improve your reaction time?"
				"improve your mental acuity?"
				"improve flexibility?"
				"improve circulation?"

**Comment by LocalGod79** [comment]
i "americanized" some of your phrasing, added my own.

did defining the ship that way work as a plugin?

**Comment by endless-sky** [comment]
Isn't the Java logo copyrighted?

I've got mixed feelings about the ship sprite - a flying coffee machine seems just a little bit *too* silly. I mean, Cap'n Pester is silly too, but at least flies an ordinary ship.

**Comment by LocalGod79** [comment]
come on - after playing for several hours straight, a flying coffee machine is par for the course - it might actually make people stop and stand for a minute...

besides, is it really any different than;
https://github.com/endless-sky/endless-sky/blob/master/images/ship/hallucination-0.png

**Comment by Wrzlprnft** [comment]
I looked up oracles guidelines for the java logo. Since spaceships in a game which is not programmed in java will be hardly count as "oracle approved artwork", because it is not closely tied to java (e.g. a java application loading screen) nor un-modified.
Ill replace it and prepare a new branch in my fork, which i may or may not make a pull request from depending if it has any chance to get merged.
I have to agree to local god, in flight it looks less silly than one might think, and don't forget, the original idea was to only enable it after quite a lot of playtime, so it will be rare enough. As far ad i got it the frequency will do the job for now.
Additionally, imagine a player gets sucked i to the game and plays it for 3 hours straight, wouldn't do this ship a pretty good job to get the players attention?
I tried to add a spaceship touch, like those "thruster" feet.

**Comment by Wrzlprnft** [comment]
During the modeling of this ship, i was thinking about placing the star queens huge glass bridge/window thingy instead of the two cups/glasses, shall i work those oit completely as alternative option? It looked way more like a spaceship and less "silly"

**Comment by LocalGod79** [comment]
perhaps instead of the java logo?

i really like the coffee...

**Comment by jmhorjus** [comment]
Yeah, the java logo is copyrighted, so I don't think we can use that logo exactly as part of the ship. :(
I do like the idea in general though. The frequency is *very* low, so the silly factor is muted by that.

**Comment by Wrzlprnft** [comment]
I need a name for it and then it is good to go.

**Pull request closed without merging**
