### PR TITLE
Turning the Bactrian into actual City Ship

### PR DESCRIPTION
**Pull request by Zitchas**
This PR is not intended for near-term merging, but is a proposal for shifting the stats of the Bactrian to more closely reflect the way it is described. I'm expecting a fair bit of discussion, and I suspect these stats aren't final. I'm basing this on the assumption that the description is cannon, and the stats are subject to debate.

> "The Lionheart Bactrian is the last of the great city-ships, a design hearkening back to the early days of space colonization when a long-distance vessel needed to be a self-contained world, able to survive for weeks at a time without encountering an inhabited planet. It is not only a freighter, but a carrier, and a capable warship either at short range or at a distance."

> Naturally, this versatility also makes it extremely expensive, and the Bactrian is normally only for sale to citizens who have been vetted by the local government of the Deep."

So, based on this description, it is a ship built for long haul traveling that is capable of defending itself and being self-supporting, as well as all-round versatility.

Breaking it down: 
1) "City ship from the early days of colonization" sounds like a transport to me.
2) Long distance travel. This implies the need to cover distances, not agility.
3) Both a freighter and a carrier. Good cargo capacity and fighter bays.
4) Capable warship. Not awesome warship, capable. 

This leads me to the following changes:
1) Changed the type from Heavy Warship to Transport.
~~2) Replaced the Steering with an X4200 to be in balance with the thrusters, which is more in line with a ship built to cover long distances instead of for agility.~~
3) The Bactrian is already a great hauler and can carry 3 fighters, so seems good as is for this.
4) IIt has more turrets than any other human ship except for the Protector. This fits, since turrets are quite appropriate for large non-agile things like cities and space stations. However, it *also* has 4 gun ports, which doesn't fit. Guns require agility and precision to aim, and that is something a city generally lacks. My first inclination is to remove all the gun ports entirely, but in ES missiles require gun ports, and having a pair of missile launchers for anti-fighter defense is reasonable. So, the torpedoes are removed, and the number of gun ports is decreased to 2.

As a result, they are still a very capable warship, but it reduces its clear combat superiority a touch so that dedicated warships like the Falcon and Leviathan at least outclass it in terms of guns, even if they can't surpass it in anything else. It also means that Dreadnoughts are a bit more significant, since the Bactrians still outclass them by a turret, so giving the dreadnought a 2 cannon advantage I think is important in setting the Dreadnought apart as a meaningful upgrade in the combat sense.

~~Being a city-ship implies thousands of people, but ES doesn't run with that sort of scale: Even the world-ships carrying the last segments of Korath population cap out at 1'500. So here I've settled for increasing the crew by 10 and the bunks by 30. This expands its ability to hold people, but at the cost of outfit space, which decreases by 110.~~

~~The decrease in outfit space is reflects the additional life support required for those bunks, as well as a reduction in available space for extraneous things. Recalling that this ship is a self-contained world, living space isn't just standard life-support and bunks; it includes things like hydroponic food production, medical facilities, and all the other things that would be necessary to support long expeditions and colonization efforts.~~

On a more meta level, this reduction is also intended to push the player into making choices. By default, the ship is pretty good at everything, but not great. If they want to go faster (the engine capacity can clearly fit better engines) they will need to sacrifice either weapons or cargo. Likewise, if they opt for heavier weapons than the standard, they are going to need to cut into something else. 

One of the key problems with the Bactrian metagame is that it is a very good ship that can be great at anything while still remaining very good at most or all of the other areas. With these changes it continues to be a very good all-round ship, but now in order to be great in any particular area it has to sacrifice a bit more and won't be as good in the other areas. This gives other ships (primarily the Heavy Warships) a bit more room to shine in their own right instead of being generally outclassed in almost every way.

I particularly find it problematic that people looking for a warship often focus directly on the Bactrian. The fact that an antique city-ship design from six centuries ago is the go-to choice instead of modern combat ships such as the Dreadnought, Falcon, Carrier, or Cruiser, or even Kestrel seems problematic to me; especially since nowhere in the Bactrian's description does it describe being a great warship, or the best one. It clearly has a valuable role, and will continue to be an excellent flagship and boarding vessel. But it should be an excellent combat freighter, not a warship. 

Changed:
- Heavy Warship to Transport
- ~~Mass increased from 940 to 1040~~
- ~~Outfit decreased from 740 to 630~~
- ~~Increase required crew to 80~~
- ~~Increased bunks to 275~~
- Removed torpedoes
- Removed two gun ports
- ~~Replaced X5200 steering with X4200 steering~~

List of relevant PRs and discussions:
- https://github.com/endless-sky/endless-sky/pull/2248
- https://github.com/endless-sky/endless-sky/pull/2076

Edit: I really like the idea of making a Marauder Bactrian with the stats of the current Bactrian, and making this "Transport Bactrian" the actual in-game Bactrian. That being said, what I'm proposing here is a lot more minor than what Amazinite was proposing, and I rather like his take on it. But that never got merged, so I'm bringing this more minor transformation up.

Edit2: In order to simplify the PR, removing the changes to mass, minimum crew, and  bunks.

Edit3: For reference, the PR's for the ships that might be able to provide some competition with the Bactrian are:
- The Navy Auxilliary and Dropship in #4004 .
- The Wanderer Riptide in #4102 .

Edit4: Just to clarify the current changes, added a bunch of strikethroughs to clarify what this PR is actually changing right now. Which is *only* the ship type, 2 gun ports, and the torpedoes.

### CODE REVIEW

**Comment by Amazinite** [comment]
Are we really going at this again?
image

**Comment by Zitchas** [comment]
Well, if you'd like to revive your PR, that'd work even better. :)

**Comment by SirStigII** [comment]
I personally agree with all of these changes. It's just too good at everything.

**Comment by jafdy** [comment]
The reasoning behind it being a heavy warship is the same as with the mule, it can be a really good warship so it gets classed as such. That said the change may help with the mentality people get into with it. 
I also like the weapons change as torpedoes feel like heavy weaponry. 
Otherwise I have no strong feelings either way on the matter.

**Comment by Zitchas** [comment]
*nods* That's what I was going for. Honestly, the changes I'm proposing are pretty minor. I was aiming to change *just* enough that it feels like a transport/heavy freighter that happens to be very capable of combat, as opposed to outright being a heavy warship.

**Comment by Amazinite** [comment]
>pretty minor

Stripping it of 110 outfit space is minor?

**Comment by shitwolfymakes** [comment]
I think it still has too much pure cargo space. While the lost outfit space makes sense for having stuff like resource production and fabrication, A city ship would also have last resort storage of food and other necessary supplies, so I would cut the total scargo down to 500. 

Additionally, any city ship lumbering through space would have to be able to travel for indefinite periods of time between ports, so I would give it 800 fuel and 3 ramscoops.

I would also give it another 2 fighters, because any city ship would have a dedicate fighter wing and 3 fighters is not enough, especially give how little of an effect they have

**Comment by Amazinite** [comment]
Given the various changes that have happened to mechanics of the game (e.g. fleet cargo, not number of freighters triggers raids now, replacement of mass expansions with outfits expansions), I wouldn't necessarily say that the Bactrian needs changed anymore, at least not in this regard.

<hr />

You mention comparing the Bactrian to the Falcon and Leviathan, but I don't find that comparison apt, at least not anymore. The Bactrian now requires a license to buy, while the Falcon and Leviathan do not. With that in mind, it's hard for me to really compare the two civilian warships to a license locked warship. The fact that the Bactrian has the power of a license locked warship but was not itself license locked, despite the description of the ship implying so, is part of why I wrote the Deep missions. Now that that's done though, comparisons between non-license locked and license locked ships are a little difficult.

Comparing the Bactrian with other license/story locked human ships, it's obviously bottom of the barrel in terms of combat. While the Bactrian sits at 300 weapon space, the Cruiser is at 320, Carrier at 370, Dreadnought at 360, Kestrel at a whopping 390 or 430. It has the least gun ports among those ships, tied with the Dreadnought, while having the most turret mounts. Given the increased effectiveness of gun ports though, I don't think that having more turrets over gun ports is necessarily more beneficial now. The HP of the Bactrian is comparable to these ships, with their HPs ranging from 23.6k (Kestrel) to 29.7k (Carrier) with the Bactrian in between (26.1k), but it is the slowest among them, slower than even the Carrier, which is the only ship heavier than it. Looking at outfit space, it is actually also at the bottom there, having 20 less than the Cruiser at the closest and 80 less than the Carrier at the furthest. 

If was only when mass expansions were a thing that the Bactrian was a better ship in terms of combat, and that was simply because of the fact that the ungodly outfit space allowed it to easily install weapons and shields that the other ships couldn't, which easily offset the increased mass and therefore reduced speed. Now that the cargo space of a warship doesn't so easily equate to better combat prowess, at least beyond a certain point, the Bactrian is now properly the worst of the licensed human combat ships.

With that said, I don't see the reduction in gun ports or outfit space necessary, and the claim that the Bactrian is great at every role no longer stands.

<hr/>

If you want to make any change to the Bactrian, you need to get at the core of why people use it. The Bactrian isn't useful for T1/human combat anymore, or at least isn't the smartest choice. The reason the Bactrian is so often talked about and used is because of its combination of massive bunk space and cargo space. 

I've mentioned in various places that I think that this is more of the core issue with the Bactrian's balance.

>[If I were to make a version that was locked behind a license, I would remove the health changes that I did here and set the cargo space to something like 260-320 instead of the original 530 and the 240 I have here, then keep all other changes that this PR proposes.](https://github.com/endless-sky/endless-sky/pull/2076#issuecomment-275953091)

>[If the answer to 1 [What type of ship is the Bactrian?] is civilian and 2 [Will it be license locked?] is yes, then I'll revert the hit point changes and slightly buff the cargo from here.
>...
>If the answer to 1 is military and 2 is yes, then only slight changes need done compared to what I've done here, likely just a slight cargo nerf as to make it less viable in T2 territory.](https://github.com/endless-sky/endless-sky/pull/2076#issuecomment-276075250)

>[The boarding ability [high cargo and high bunks] is exactly what I want to nerf and have always wanted to nerf.
>...
>This is essentially a list of the best boarders in terms of both capturing and looting. Now look at the requirements to get each ship.](https://github.com/endless-sky/endless-sky/pull/3120#issuecomment-339173410)
> 1. Bactrian: available at the beginning of the game
> 2. World-Ship: must be captured
> 3. Quarg Skylark: must be captured
> 4. Korath Raider: must be captured
> 5. Saryd Sojourner: must discover the Coalition and unlock their civilian tech
> 6. Solifuge: must complete the FW campaign and part of the Wanderer campaign, then capture
> 7. Shield Beetle: must discover the Hai
> 8. Kestrel: must reach a combat rating of about 9.
> 9. Carrier: must be captured
> 10. Dreadnought: must play through the FW campaign

So leaving the cargo space be and *buffing* the bunk space isn't the way to go. You reference my attempt at this same thing in #2248, but you need to realize that that came before mass expansions were replaced with outfits expansions, at which point it the Bactrian *was* a master of all trades and #2248 was a compromise of killing the Bactrian's combat capabilities at the cost of having it retain its number one spot as a boarder. This PR right now is basically trying to solve the issue in the same way as #2248 even though #2248 is no longer a viable solution.

**Comment by Zitchas** [comment]
I agree that the recent changes have helped diminish it a bit, but it is still far too militaristic for a civilian transport ship. 

Likewise, even if all the rest of the changes are removed, I think it should still get the changed designation to "transport" and loosing two gun ports. Even if it isn't as strong as it used to be, it still is a very strong ship, far better than merely a "capable warship." Part of that may be simply how it is perceived, but not all. Changing its classification and removing the two guns would weaken the combat aspect slightly, and reinforce that it is not intended to be a serious contender for "best warship."

**Comment by Amazinite** [comment]
>it is still far too militaristic for a civilian transport ship.
>...
>Changing its classification and removing the two guns would weaken the combat aspect slightly, and reinforce that it is not intended to be a serious contender for "best warship."

That's the thing though, it isn't just some civilian transport ship--I'm sure that at the time of its creation it was only used by a select few, and although advanced for its time, it has been surpassed as a warship by plenty of ships now. And I wouldn't exactly call something that is license locked a civilian ship--and it is already not a serious contender for best warship, at least when we're referring to warship as a ship used for combat. It isn't the combat aspects of the ship that need weakened because it isn't the combat aspects that are unbalanced. These changes make it even better at the job that people already use it for while just making it need to rely on escorts more than before.

**Comment by Zitchas** [comment]
Actually, I don't see any problem with something being both a civilian ship and license locked. While we don't have any in ES currently, EVN had a few fairly good ships that were locked behind the Sigma corporation. Completely civilian ships, but good enough that the corporation that made them kept them to itself. 

As far as that goes, the Coalition ships and early Wanderer ships are probably good examples of ships that are clearly civilian or at least "only just barely refurbished into warship" type ships, but are license locked. 

The only thing that a license lock means is that in the lore the people who have control over its distribution consider it too valuable to let just anyone buy them. Most factions are far too military focused, so that restriction tends to focus on military capability of the ships, but there's no reason it has to be.

The Deep, the Remnant, and the Korath are all factions that either did or do value the lives of their people far more than pure military power; so I would consider it reasonable for all three to put stiffer restrictions on ships that carry more people than they do on their military ships.

That being said, my larger changes actually do hit the Bactrian in its core strength. Despite gaining 30 bunks, the 110 of outfit space will mean a net loss of capturing power for those who min/max, even if it expands the capturing power of those who don't invest in extra bunks. So better capturing ship for the generalists, while being a worse capturing ship for the min/maxers.

**Comment by Amazinite** [comment]
>As far as that goes, the Coalition ships and early Wanderer ships are probably good examples of ships that are clearly civilian or at least "only just barely refurbished into warship" type ships, but are license locked.

We're talking about human ships here. Don't go off into the weeds of alien ships.

>That being said, my larger changes actually do hit the Bactrian in its core strength. Despite gaining 30 bunks, the 110 of outfit space will mean a net loss of capturing power for those who min/max

110 outfit space fits 5 bunks. 5 bunks is worth 20 crew. So you're hurting it by 20 crew but adding 30.

**Comment by Zitchas** [comment]
Huh. I failed my math, then. You're right.

**Comment by Zitchas** [comment]
As far as the weeds of alien ships, goes, if we had the Navy Transport, Riptide, and other high-end transports for the other races, we'd see a lot less focus on the Bactrian. Those two in particular should be bumped up to have at least equal if not more bunks than the Bactrian.

**Comment by SirStigII** [comment]
Remind me what those pull#s are?

**Comment by Zitchas** [comment]
The Navy Auxilliary and Dropship is #4004 .
The Wanderer Riptide is #4102 .

**Comment by Zitchas** [comment]
In order to simplify the impacts of the PR, reverted three of the changes. So now the proposed change list stands at:
Changed:
- Heavy Warship to Transport
- Outfit decreased from 740 to 630
- Removed torpedoes
- Removed two gun ports
- Replaced X5200 steering with X4200 steering

**Comment by comnom** [comment]
A Bactrian nerf isn't needed. It's no longer absurd, and alot of people like it how it is. I don't see what the big deal is if people want to trivialize capturing and plundering by running a mediocre (or worse when min/maxers do it) combat ship. That's a tradeoff, not an "I win" strategy.



>There's already a lot of hype about the Bactrian in the forums and whatnot, admittedly some of it dating back to several updates ago and no longer accurate. But its current stats are good enough that it still looks like a solid contender for best human warship.

The community's perception of balance should be secondary to actual balance. That is to say, we should concern ourselves with the "meta" game only if it highlights an existing large imbalance, which simply isn't the case here. 

The Bactrian is at the bottom of combat performance amongst locked human ships, and has been for a long time. 

If the online community hasn't caught on to that, oh well. Active forum posters represent only a subset of players, and any kind of metagaming is fairly irrelevant to a single player game anyway.

**Comment by Zitchas** [comment]
It is indicative of perceptions, though. People are going to judge it based on first impressions, and those are currently dictated by its label as a special locked heavy warship. As a standard rule, locked heavy warships are usually the better warships at being, well, warships. 

This is why the single most important part of this PR - even if every other change is removed - is relabeling it a Transport. Just like the Argosy is a capable warship version of a light freighter, the Bactrian is a capable warship version of a transport. 

The Bactrian's entire purpose, its reason for being, is to be a Transport. It should be labeled thus. If not, then its description needs to change to reflect the fact that it no longer is one.

That being said, its combat capabilities still far exceed its description as a "capable warship," and I feel the removal of two gun ports would bring it down to where it should be.

**Comment by Amazinite** [comment]
>My reason for not doing so directly is that I feel this PR is likely to hit it indirectly

Why hit it indirectly though when you have the option to hit it directly with far less consequences and a far more effective result?

>As far as Bactrian use and value goes, I think putting it behind a license actually makes the situation worse: There's already a lot of hype about the Bactrian in the forums and whatnot, admittedly some of it dating back to several updates ago and no longer accurate. But its current stats are good enough that it still looks like a solid contender for best human warship. And now that it is locked behind a license, well, that means it must be as good as the Carrier and Cruiser, right?

So do we remove the license now? And how far does that logic extend? Just because the Bactrian is the least combat capable license locked ship doesn't mean we should remove the license on it, or else something else will become the least combat capable, so that logic doesn't hold. Or another conclusion from that logic would state that all license locked ships must be of similar capabilities, which just means you're making all the license locked ships bland. Important to note too is the fact that what it does take to unlock the Bactrian and what it takes to unlock the Dreadnought or will take to unlock the Cruiser and Carrier are two totally different beasts. The Dread and Navy ships are or will be made available toward the latter end of large campaigns, whereas the Bactrian is only obtained after a dozen or so missions. 
And as I have noted numerous times now, it isn't the combat capabilities of the Bactrian that make it good, so nerfing them isn't going to change anything with respect to the supposed hype around the Bactrian.

**Comment by Zitchas** [comment]
Why do it indirectly? Because being good at hauling cargo better suits the description and original design of a ship designed for long haul transport/merchant work, so that's where the space should be allocated by default. 

I'm not arguing that all licensed warships should be the same, but I think that it is reasonable to assume that licenses that take a lot of work to get probably have ships of equal value/effectiveness in wherever their area of expertise is. I think it is also a fair assumption that If someone sees that a Heavy Warship's area of expertise is going to be being a warship. It's right there in the label. 

Dreadnoughts, Carriers, Cruisers, Albatrosses, Hurricanes, Derechoes... They're all license locked Heavy Warships that are clearly very powerful warships in their own ways. And by and large, in different ways. But they are all very effective at being warships. 

The Bactrian is the odd-ship out that it is the only license locked heavy warship whose specialty is in NOT being a great warship. But it *is* a great transport. It is the best purchasable transport in the game. So why not actually be honest with ourselves and actually label it a transport?

**Comment by Zitchas** [comment]
Update on what this PR changes:

Changed:
- Heavy Warship to Transport
- Removed torpedoes
- Removed two gun ports

So, with all the discussion, the change list gets pared down to this. The essentials to pull the Bactrian a little bit farther away from being a warship, and giving the Bactrian the distinction worthy of its history: The only license-locked transport in human space (currently), and given future plans, the only one that will be accessible without completing a large part of a major plot line. 

I think the Bactrian deserves to be labeled what it is, and show everyone that the transport category isn't just a category to minimize and forget about.

That being said, in view of discussions about fighter usefulness, I think that boosting the carrier up to six or even eight fighters, and giving the Bactrian another one or two fighters would be good. There aren't nearly enough civilian ships with fighter bays, but the fact that the dedicated carrier has so few makes it hard to not overshadow it. But that's for a fighter balance PR, not this one.

**Comment by Pointedstick** [comment]
> Update on what this PR changes:
> 
> Changed:
> 
>     * Heavy Warship to Transport
> 
>     * Removed torpedoes
> 
>     * Removed two gun ports
> 
> 
> So, with all the discussion, the change list gets pared down to this. The essentials to pull the Bactrian a little bit farther away from being a warship, and giving the Bactrian the distinction worthy of its history: The only license-locked transport in human space (currently), and given future plans, the only one that will be accessible without completing a large part of a major plot line.

+1

> That being said, in view of discussions about fighter usefulness, I think that boosting the carrier up to six or even eight fighters, and giving the Bactrian another one or two fighters would be good. There aren't nearly enough civilian ships with fighter bays, but the fact that the dedicated carrier has so few makes it hard to not overshadow it. But that's for a fighter balance PR, not this one.

+1

**Comment by Amazinite** [comment]
I think at this point we're getting into a question of "What defines a ships category?" Is a Bactrian a transport because its description says that's what its main purpose was? Or is it a heavy warship because its armament is so far from other transport ships and so close to that of heavy warships? Looking at the description of the Mule, it's clear that there's a distinction between a ship's purpose and how it's ultimately categorized due to other factors. The Mule's description is even worded in such a way that suggests that Republic laws are what categorize a ship; "The Lionheart ship designers combined a good deal of cargo space with a decent amount of weaponry and even a fighter bay, and ended up with a ship that is mostly used as a freighter *but **must** be classified as a warship because of its heavy armament and shields.*" With that said, I don't think that the ship's category should be changed when paired with what have become such small changes to the ship's stats.

To that extent, what does this change add to the game? Stepping back into arguments I've made in the various other issues and PRs pertaining to the Bactrian's balance, this change doesn't help us to make room for anything new, because as I've said, the Bactrian's combat prowess isn't the core of the issue. There are already human ships above and below the Bactrian in terms of combat ability, and this change only unnecessarily pulls it further from the top rungs.

**Comment by Zitchas** [comment]
For the game as a whole, I think we would be better off changing one line of the mule's description and having the Mule and the Bactrian be continuations of the Argosy theme of combat-capable non-warships, rather than lumping them in with the rest of the warships. The Behemoth is a good example of how this is possible. (it has more shields, more hull, and more weapon space than the mule, but it exists quite appropriately as a heavy freighter)

What does this add to the game: Quite simply, player choice. This change gives players a combat-capable ship that isn't a warship. Unsurprisingly, ES is a very combat-focused game, and that is unlikely to change. Nor do I particularly want it to change. Despite that, however, I feel that increasing the breadth of non-warship classified ships in the upper echelons of the combat-capability scale is an opportunity to give players who prefer the idea of being a "simple merchant captain who happens to be good at combat" more opportunities to play as that. It is a little incongruous to pretend to be "just a simple merchant captain," after all, when one is flying something that is clearly labeled a Heavy Warship, even if one can justify it via the bunks or cargo capacity.

In the same breath, simply changing the label of an "almost top-end" warship that of a transport is also incongruous, hence the -2 gun port change. I think that small change is sufficient to justify the Bactrian being labeled as a highly combat-capable transport instead of a warship, and thus give players interested in playing such a role a viable option amidst the cloud of warships.

**Comment by Wrzlprnft** [comment]
How about splitting the Bactrian in name and purpose. make a city ship named bactrian, and a new ship that fits the bactrians current intended role?

**Comment by Zitchas** [comment]
I'd be up for that, but I'm not sure what the two roles should be. There's the transport-focused city-ship role that I've been focused on, but what is the other role?

**Comment by Wrzlprnft** [comment]
uh, sorry, i meant splitting the flavor from the current functionality. make a city ship, that is a city ship, and call it bactrian, and make a new ship, that fills the role the current bactrian fulfills. basically, split the stats from the flavor. that would allow the flavor to go it's own way, and the stats to go their own way, and both come to rest in a better place. because, obvioulsy, the two seem not to go that well together (somewhat nimble boarding flagship versus city ship which isn't supposed to be a nimble boarding thing).

**Comment by Zitchas** [comment]
Ah, that makes sense. Yes, I would be up for that.

**Comment by ghoulavenger** [comment]
Back when I used to post here regularly I've always hated how people picked on the Bactrians warship capability when it was already a subpar warship. The only thing that kept it relevant was mass expansions, and those were changed specifically to nerf the Bactrian. I agree 100% with Amazinite that the only reason I've ever used the Bactrian over even the Leviathan (and I have run Leviathan heavy fleets) is because it is a boarder. You want to take the Bactrian out of the picture? Make boarders less important or give more boarder variety.

How do you make boarders less important? Well, let every ship in your fleet be capable of boarding. That means you could potentially capture heavy warships with any reasonably well armed fleet. You wouldn't need to be driving the bactrian anymore. But nobody wants to do this because it opens up a whole new can of worms. And yes, my last playthrough I did it almost completely without boarding ships, it was an interesting experience, where I didn't really like the bactrian much at all.

So that opens up giving boarders more variety. In human space regrettably, the Bactrian is the easiest option and probably the best. Nobody wants to go around capturing ships with a Star Queen after all.

As far as the role-play aspect of a Merchant Captain goes, I'd say being armed to the teeth is the right idea, unless you're in peaceful alien space. Space pirates are a real problem, especially as your cargo fleet gets larger.

**Comment by jafdy** [comment]
I think the problem is perception, people still perceive the Bactrian as the "best ship" so what we should really be doing is finding ways to change that perception.

**Comment by Zitchas** [comment]
I'm not arguing about how "armed to the teeth is bad," I'm arguing that 4 gun ports on a city is excessive and doesn't fit the lore. They are guns. On a mobile space station. Things that are noted for being glacial to turn shouldn't be incorporating large numbers of hardpoints for weapons that require agile turning to aim.

Note that I'm not changing the number of turrets or fighter bays (I'm actually even making the case that in a fighter rebalance the Bactrian should get *more* fighter bays. The thing would still have more turrets than almost every other human ship, and those are the weapons that actually fit with the "City-ship" description. 

As far as that goes, I'd be all for a more radical change that boosts the Bactrian at the same time: More bunks? Sure. More cargo? Yeah, I could agree to that. Fighter bays? Definitely. Sacrifice some turning speed for more thrust? That also would fit the lore quite nicely.

**Comment by Zitchas** [comment]
Just re-reading the description for it, I'd like to repost the first part of the description here:

> The Lionheart Bactrian is the last of the great city-ships, a design hearkening back to the early days of space colonization when a long-distance vessel needed to be a self-contained world, able to survive for weeks at a time without encountering an inhabited planet. 

This ship was designed in, and is a relic of, the early days of space colonization. The heavily militarized piracy we face today didn't exist back then. It couldn't have. Pirates by definition need someone to pirate. If these ships (designed to be colony ships) are the first ships going into an area, there is *Nothing* there for pirates to loot, and thus, there should be no pirates. 

Virtually every aspect of the ship as it currently stands makes a lot of sense for this colonization role, with the exception of the armaments. Hull & Shields? Useful for protecting people from unknown space hazards, and a ship like this would be running into those almost as much as scouts would be. Cargo? Well, it takes a lot of equipment to setup a colony. Not to mention hydroponics and indefinite life-support takes up a lot of space. Large number of bunks? Pretty much goes without saying. The only question is "why so few?" Setting up a colony is the work of many hundreds of people, preferably thousands. Fighter bays? Sure, whether they are providing covering fire or being used to scout out landing locations to establish a colony, having built-in bays makes sense. 

If such a ship is going to have armaments, turrets make sense, as it allows the ship to defend itself while it continues to flee. And a colony ship has no business pursuing anyone. 

Guns, though? Only useful if the ship is pointed at its enemies. And that means it is focused on moving towards threats, not away from them. A colony ship should be focused on disengaging and fleeing, not charging the enemy.

**Comment by Zitchas** [comment]
Alright, since most of the veterans who post on here seem to be of the opinion that the Bactrian is already a transport masquerading as a sub-par warship without needing any changes, I've proposed an alternate PR that straight up makes that change without touching any stats whatsoever. 

Basically, if this is what the veterans already think of the Bactrian; and, as Jafdy put it, the problem is one of perception, not statistics, then let's change the perceptions. Since most people judge things by their cover/label, let's change the label so that it tells players what the Bactrian is. Which is to say, a Transport.

(also, it'd help balance out ship categories. We have 26 Heavy Warships and 14 Transports. Or, if you limit it to ships that may be purchasable at some point in the near future, it is 16 heavy warships and 14 transports.)

Along the same lines as the perception: The Bactrian is the most expensive Heavy Warship available in human space. As a general rule in computer games, balance dictates that the "most expensive" stuff is typically the "best". Stuff that doesn't follow this rule (like the Osprey) typically have some kind of description or aesthetic appearance that indicates its value is due to being fancy, a special skin, or the like. Given that the Bactrian obviously doesn't look like a special easter egg ship like the Kestrel, nor does it look extra fancy/expensive like the Osprey, should we be surprised when people assume it must be the best human warship because it is the most expensive one?

**Comment by Lineth** [comment]
Just as a belated note r.e. balance. The forward mounts on the Bactrian are not for guns. They're for missiles, which imo fit the colony ship description perfectly as a long-range defensive weapon.

**Comment by SirStigII** [comment]
Hmm, this is where the missiles using gun ports makes is trickier to balance something. If missiles used their own ports, or no ports at all then you could make it not use forward firing weapons.

**Comment by Zitchas** [comment]
Yeah. I'm firmly in the camp of "gun ports are for guns. Missiles are why we have limits on Weapon Capacity." A ship like the Bactrian that really shouldn't have guns should have low to no guns. 

I agree, though, missiles make a lot of sense for long-range defense. Hence why a Bactrian has lots of weapon capacity. But we'll need a larger discussion on the merits of missiles and gun ports globally for that change.

**Comment by Amazinite** [comment]
Still a no from me.

**Comment by Zitchas** [comment]
I continue to think that the Bactrian need some kind of nerf - if only a slight one or a re-adjustment. 

That being said, given the number of changes that have been introduced to the game, I am happy to close this issue for now, and leave it until, say, after 0.9.12 has been released and we have all had more of a chance to see how well it fits into the game and whether or not it still has such an overpowering position at that point in time.

**Pull request closed without merging**
