### PR TITLE
Fix there being two archons during void sprites missions if you've angered the drak

### PR DESCRIPTION
**Pull request by ziproot**
**Bugfix:** This PR addresses issue #9245 

## Fix Details
When some of the void sprites missions are active, if you've angered the Drak you can face two Drak, which isn't what the mission says. I renamed the Drak so that they have the same name with the hidden one, then fail that mission and set it to not offer while a void sprites mission is active. 

## Testing Done
- [ ] No issues with two NPCs having the same name.
- [ ] No issues with renamed NPCs (i.e. broken saves)
- [ ] Only one Drak in void sprites when Drak are angered and void sprites are left alone
- [ ] Only one Drak in void sprites when Drak are peaceful and void sprites are left alone
- [ ] Outside void sprites missions, Drak shows if and only if you attack void sprites
NEW (as per comments by developers)
- [ ] Exactly two Drak in void sprites when Drak are angered and void sprites are subsequently attacked
- [ ] Exactly two Drak in void sprites when Drak are peaceful and void sprites are subsequently attacked

EDIT: Fix checkboxes

## Save File
This save file can be used to verify the bugfix. The bug will occur when using current continuous, and will not occur when using this branch's build.
[Shigeshige Tokugawa.txt](https://github.com/endless-sky/endless-sky/files/13182718/Shigeshige.Tokugawa.txt)
From issue report.
[Shigeshige Tokugawa~sample return.txt](https://github.com/endless-sky/endless-sky/files/13183953/Shigeshige.Tokugawa.sample.return.txt)
[Shigeshige Tokugawa~void sprites.txt](https://github.com/endless-sky/endless-sky/files/13183954/Shigeshige.Tokugawa.void.sprites.txt)
New save files to do the other missions. I think you need to depart and land several times to get the missions, after aborting the cognizance one if it's still there. However, this will cause all the missions to work as normal. The return the samples mission involves the archon still attacking you of course, but the text says so.
EDIT: You also need to visit the spaceport and have only a 50% chance for return the samples. Also, the original issue with cognizance 1 won't work at first anymore as my code is dependent on it offering, so I would need to modify the save again. Once the game builds I will do so.

### CODE REVIEW

**Comment by danaris** [comment]
Why rename the Archon that you normally encounter there—the Lifted Lorax—to Sleeping Dragon? Why not instead rename the one that would only be encountered by a much smaller subset of players to match the one that's usually visible?

**Comment by Amazinite** [comment]
I'd likely be much cleaner to instead use `to despawn` on the NPC from the void sprite mission for when your rep is negative.

**Comment by ziproot** [comment]
... I misread your comment. Oops.

**Comment by ziproot** [comment]
I just tested the provided save file from the original issue and can't reproduce. I only see the sleeping dragon on continuous. With my fix it's renamed to "lifted lorax." I was able to complete that mission without any losses.

**Comment by ziproot** [comment]
For some reason my PR isn't working on "return the samples."

**Comment by ziproot** [comment]
Reverting as this caused the archon to despawn permanently upon triggering a void sprite mission. This may not be "clean" but it's the only way to actually solve the problem as far as I know. @Amazinite, if you have a better way that ensures the constraints in "testing done" are all true, please let me know.

**Comment by Amazinite** [comment]
Not `to despawn` on the permanent Archon, `to despawn` on the temporary archons if Drak reputation is negative.

**Comment by ziproot** [comment]
Well, I'm going to mark this as a draft until I get to testing.

**Comment by Amazinite** [comment]
> Otherwise, attacking a void sprite will cause you to fight two archons, then killing it would have one of them disappear.

This feels like a non-issue to me. The point of these missions is to dodge the Archon. If you're going out of your way to attack the Archon, then it doesn't seem far-fetched to me to have a second one pop up. And if you actually have the firepower to kill an Archon, having the temporary one disappear if it was the permanent one you killed doesn't seem all that bad to me. Perhaps in-universe, it simply fled. The permanent one will respawn anyway.

**Comment by ziproot** [comment]
Then that still creates an inconsistency where attacking void sprites before the mission only leads to one archon but attacking void sprites during the mission leads to two, and the second one still despawns after you finish the mission.

**Comment by EjoThims** [comment]
> Then that still creates an inconsistency where attacking void sprites before the mission only leads to one archon but attacking void sprites during the mission leads to two

Actually, I think that's consistent logic with giving us the chance at working past the Archon aggression by returning the eggs.

Regardless of your previous hostility, in making this attempt you only have one obstacle to dodge while doing your good deed, but if you instead take the chance to cause more damage, you get roflstomped.

> and the second one still despawns after you finish the mission.

That also still seems consistent to me as behavior after following through with the good deed.

**Comment by ziproot** [comment]
That resolves most of my concerns. The only one left is that if you attack the void sprites before hand, attacking them again does not cause the second ship to attack, while not attacking the void sprites before hand does cause the second ship to attack.

**Comment by Zitchas** [comment]
It isn't meant to be easy to earn the trust of the Archons. If you have angered them, it seems reasonable that you might have to face two of them when if you haven't, you just need to deal with a single less trusting Archon. There's a reason why the normally peaceful archon and the angry one have different names, and that is because there are two different archons with different personalities and opinions active here, under different situations.

**Comment by Arachi-Lover** [comment]
It's pretty deliberate to have 2 Archons there (Lifted Lorax appearing during the missions in question only, but nonetheless *there*), as it is known that the Archons value the Void Sprites greatly.

Likewise, it is tremendously difficult to kill an Archon, it isn't something a player would just accidentally do and then get caught off-guard in these missions. I find it'd be a tremendous outlier at all if someone has managed to get to the point in the game of being *capable* of beating an Archon without being aware of the Sleeping Dragon/Lifted Lorax situation and missions in general.
And, if done by attacking the Void Sprites, again that'd be pretty deliberate from the player, and not without a warning as Sleeping Dragon would immediately aggro and its presence would be made known.

Outright "deleting" one of the Archons there with a name change (be it Sleeping Dragon or Lifted Lorax) isn't desireable as there being two of them there is clearly deliberate (as stated by Zitchas, both have different names).
The `to despawn` conditions suggestions seems fine, but honestly given what you have to do to even be in the scenario where both are uncloaked and hostile I'm not really sure it's necessary.

**Comment by ziproot** [comment]
It appears like the main problem was that this happened for neither of the two expected actions, and this was fixed in 0.10.4. As the issue was not closed as completed then, I thought that there was still an issue, and opened this pull request. As it looks like the issue actually is solved, I will close this pull request with the expectation that the linked issue will be closed as completed.

**Comment by EjoThims** [comment]
I honestly was thinking this was meant to be a patch fix for anyone else still stuck in the situation from the linked issue who just hasn't realized it yet, otherwise I'd have pointed that out myself :3

**Pull request closed without merging**
