### PR TITLE
fix(content): qualify Tomek's alleged tactical genius

### PR DESCRIPTION
**Pull request by Pointedstick**
Tomek is described as a tactical genius right after he's let his emotions get the better of him and lost a major battle as a result. These are not the actions of a tactical genius, so the description seems odd, to say the least.

To reduce this jarring contrast, let's have Freya qualify the statement a bit.

### CODE REVIEW

**Comment by Amazinite** [comment]
This entire scenario is already rewritten in #7000.

**Review by Zitchas — APPROVED** [review]
This is a very simple change that in no-way blocks the larger FW rewrite that is expected to be included in... I think 0.9.17, maybe?

In the meantime, this change improves the story in a couple ways:
a) Shows that the FW council is, in fact, aware of Tomek's flaws. (This makes their usage of Tomek seem more like a calculated risk rather than being blind to his flaws)
b) Provides the player with a little context so that they can share in this knowledge.

If this was a heavy rewrite of all the Tomek stuff that conflicted significantly with Amazinite's FW reworking, and would be a major block for imminent content, then merging this wouldn't be appropriate.

However, this is a small tweak that doesn't block it in the least, and in fact is probably quite complimentary to it. The one-line conflict should be quite easy to handle, too; and in the meantime, this is a solid tweak to the story that significantly improves the portrayal of Tomek.

**Comment by Pointedstick** [comment]
> This entire scenario is already rewritten in #7000.

But that's not merged yet. In software dev terms, this is a bugfix for an existing feature, while your PR is a replacement with a new feature. They aren't in conflict, and it's generally considered good practice to continue to bugfix what's already there in advance of the new thing being merged.

**Comment by Pointedstick** [comment]
Merging since it's approved by a core contributor.

**Pull request merged**
