### PR TITLE
feat(content): cleanup carbon systems & Ildaria, resolve/improve WR images

### PR DESCRIPTION
**Pull request by ravenshining**
**Content (stars/map)**

## Summary

This PR:
 - Reverts the splitting of the WR image done in #6378
 - Reverts the change to planet sprites in Kor Ak'Mari done in #7086
 - Selectively darkens the new WR sprite to reduce eyestrain and increase detail
 - Renames the old WR image to a more fitting `nova-small`
 - Copies the old WR image to the high-dpi repo where it had no sprite, and shrinks its image here
 - Adds a 0.5 scale f-giant to Ildaria to better match the Sad Archie image 
 - Adds a companion `k-dwarf` to Kor Ak`Mari to rationalise the spiral pattern
 - Reshuffles the planets in all three systems with carbon stars for aesthetic and astrophysical reasons

By restoring an image to `star/wr`, merging this PR before the next release may prevent potential problems with plugins and other PRs.

## Rationale

Wolf-Rayet stars are the brightest and hottest of all stars, with most WRs being even brighter and hotter than most blue supergiants.  Also, they emit primarily in the ultraviolet.  Accordingly, the new image in #5828 was made intensely bright and purple.  These stars are probably too energetic to expect life-sustaining planets around, and are not depicted to scale with other stars.

While the old image might be a reasonable way to depict both a WR and a surrounding nebula, I don't think it fits with the scale of systems used in ES, and it looks especially bad with orbiting planets.

Carbon Stars, meanwhile, the intended replacement for stars that previously were a WR but that we want to keep orange for one reason or another -- such as matching the Sad Archie image -- are a sort of decaying red giant, and these I think are a more appropriate fit for a system that formerly held intelligent life than a WR.

## Background

#5828 split systems that previously used a Wolf-Rayet star to either use an updated Wolf-Rayet, or the new Carbon star, which has a vaguely similar appearance to the old WR sprite.  Unfortunately, no regard was given for their planetary systems, and Ildaria escaped my notice.

Compounding this, #6378 did not continue this pattern, instead bringing back the old, false-colour or nebula-sized WR image for Ildaria, and renamed the two WRs into wr0 and wr1, raising concerns for compatibility and leaving us with a star that depicts either too cool or too far away a Wolf-Rayet, that has no high-dpi image.

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/281

### CODE REVIEW

**Comment by Zitchas** [comment]
While the changes do sound good, the image being deleted *does* look really neat. Maybe don't delete it, and just rename it something else so it can be used in empty systems?

**Comment by ravenshining** [comment]
Hm.  Well I thought it was inferior, which is part of why I replaced it it #5828 .   Also, there's no high DPI version.

It might be suitable for a a smaller nova?  I don't know anywhere on the map off the top of my head where we would want a small nova, but then, we haven't used the neutron star yet, either.

**Comment by Amazinite** [comment]
If there's a concern with plugins then we can just rename `wr0` to `wr`. PRs should be expected to deal with conflicts.

A carbon star still doesn't really match the scene image from Sad Arachie. Even if we changed Ildaria to a carbon star, it doesn't look like the distances would need tweaked, as other carbon star systems have planets within the cloud of the star.
image

I also don't see part of the rationale behind changing the Ildaria star from a WR to a carbon star; it's never stated that the Sheragi inhabited Ildaria, so I see no issue with Ildaria having a WR star. And if WR stars are said to be too bright and hot for anything to inhabit the area around them, the habitable range should be extremely high, not extremely low.

The newer WR star still hurts my eyes btw.

**Comment by ravenshining** [comment]
I think a carbon star matches the Sad Archie scene *better* than the old WR.  It's got that banding thing going on, that the old WR doesn't have so much.

I moved the planets out on Ildaria, because it was a very small distance they had to be moved, and because it's in human space, where things are supposed to look more boring.

It may or may not be stated the Sheragi lived there, but I think it's implied.  Enough so for me to think it was.  And it seems odd the Drak who talks about them would be hanging around a star where they didn't.

I put the habitable range at 100 because that's what I thought you wanted as a placeholder for uninhabitable stars.  But, seeing your comment, I searched through the map file real quick and found B-supergiants with habitables of about 45000, so I put the WR at 50000 for now.

I assume you're being hyperbolic when you say it hurts your eyes, but regardless a WR probably should do that.  Granted IRL they tend not to be very bright because most of their emissions are in the ultraviolet, so I could adjust the image if you like.

**Comment by Amazinite** [comment]
>I assume you're being hyperbolic when you say it hurts your eyes 

No, I'm serious. It hurts for me to look at. This isn't something I'm pulling out my ass, it's something I've talked about repeatedly whenever the new WR image comes up, and was one reason I mentioned in #6378 for why I brought back the older image. The only reason I ended up keeping both is because when asked, people wanted both.

**Comment by ravenshining** [comment]
Alright.  Of course I've never been privy to any of those conversations, today is the first I've heard that anyone had a problem.

While The Lead did most of the work on the stars, I did a lot of the post-processing to dial in hue and brightness and such, and can certainly do so for the WR as well.

I've re-added the old image as a small nova in an earlier commit.

**Comment by ravenshining** [comment]
There, that should be a little easier on the eyes.  Upon closer examination, it appears large portions of the sprite were overexposed.  So I multiplied the saturation into the value over bright, coloured areas of the image, and then adjusted the gamma as dark as I could while maintaining smooth cloud edges.

**Comment by Amazinite** [comment]
MUCH better. Thank you.

**Comment by MasterOfGrey** [comment]
> as other carbon star systems have planets within the cloud of the star.

They shouldn't though - in order to *be* a non-binary carbon star it necessarily must have at least wiped out it's inner system, and gas giants would have had their atmospheres stripped from them. If any, it should be limited to large rocky masses in wide orbits (near, at, or beyond the edges of the graphic).

If we're going to mess around with changing the system it would be nice to clean it up properly.

**Comment by Zitchas** [comment]
> > as other carbon star systems have planets within the cloud of the star.
> 
> They shouldn't though - in order to _be_ a non-binary carbon star it necessarily must have at least wiped out it's inner system, and gas giants would have had their atmospheres stripped from them. If any, it should be limited to large rocky masses in wide orbits (near, at, or beyond the edges of the graphic).
> 
> If we're going to mess around with changing the system it would be nice to clean it up properly.

Is this in reference to the changes in Caeculus, or the other system? If it is in regards to Caeculus, I would request that that we not try to "fix" the system. The system itself is not the result of a naturally occurring formation processes (at least, not in its current state), and doesn't need to conform to any such rules of system formation.

**Comment by MasterOfGrey** [comment]
> Is this in reference to the changes in Caeculus, or the other system? 

Caeculus is still a Wolf-Rayet, not a carbon star. The carbon star is in Ildaria.

**Comment by ravenshining** [comment]
> > They shouldn't though - in order to _be_ a non-binary carbon star it necessarily must have at least wiped out it's inner system, > 
> Is this in reference to the changes in Caeculus, or the other system? If it is in regards to Caeculus, I would request that that we not try to "fix" the system. The system itself is not the result of a naturally occurring formation processes (at least, not in its current state), and doesn't need to conform to any such rules of system formation.

Antevorta is the example Derpy gave - and I agree, when systems are in the Ember Wastes, we can pull all kinds of crazy stuff to emphasize that something went terribly, terribly wrong there.

Kor Ak'Mari, on the other hand, also features a carbon star, and there are planets within its cloud there.  So that system needs one or more of:
 - its planets moved out beyond the sprite radius,
 - another star
 - a lore reason for the system to be a bit screwy

**Comment by MasterOfGrey** [comment]
> Antevorta is the example Derpy gave - and I agree, when systems are in the Ember Wastes, we can pull all kinds of crazy stuff to emphasize that something went terribly, terribly wrong there.
> 
> Kor Ak'Mari, [...] needs one or more of:
> * a lore reason for the system to be a bit screwy

It should be noted: that (if I'm not mistaken) for either of the above they require *recent* lore reasons - between ~ 600 and 2100 years into the past.
Older than that and I believe it's either not possible or likely to go complete nova within a reasonable in-game time period. Younger than that and I believe it's still in the process of wreaking destructive havoc (and wouldn't technically match the sprite just yet - too many rings for a fresh one).

So the one in the Ember Waste actually doesn't strike me as something that fits given my understanding that the crazy stuff mostly happened a long while ago.

**Comment by ravenshining** [comment]
Okay, I've been reading up on this and I see what you mean to some extent.

R. Sculptoris, the star which we modelled the sprite after, has this weird, multilayered, spiral pattern to it *because* it's a binary system; it has a hidden companion star.  I take it this must be hidden by the brilliant gas in... I'm guessing at the outermost tip of the spiral pattern?  Could barren planets be orbiting a hidden star here?

From what I understand... this is a star that has been expanding and contracting as it dies, leaving behind shells of material that get blown away by its wind.  Would it be reasonable to assume that the star is currently between these expansive pulses, and the innermost, most coherent and in this sprite oddly squarish ring, is leftover from its last expansion/pulse, and that the two outer, spiralling, more diffuse rings, are the result of this material getting swept out by the wind and pulled by the gravity of its companion?  Could some lava planet be in the area of the intermediate ring, outside the expanded radius of the primary, inside the orbit of the companion?

Fun facts.  Apparently while the star is undergoing a thermal pulse, it may look to us, from afar, like a Wolf-Rayet.  Also, technetium stars are often carbon stars.  A good point to keep in mind for any future descriptions of landable objects, maybe the Korath are harvesting technetium for some purpose.

**Comment by Zitchas** [comment]
> > Antevorta is the example Derpy gave - and I agree, when systems are in the Ember Wastes, we can pull all kinds of crazy stuff to emphasize that something went terribly, terribly wrong there.
> > Kor Ak'Mari, [...] needs one or more of:
> > 
> > * a lore reason for the system to be a bit screwy
> 
> It should be noted: that (if I'm not mistaken) for either of the above they require _recent_ lore reasons - between ~ 600 and 2100 years into the past. Older than that and I believe it's either not possible or likely to go complete nova within a reasonable in-game time period. Younger than that and I believe it's still in the process of wreaking destructive havoc (and wouldn't technically match the sprite just yet - too many rings for a fresh one).
> 
> So the one in the Ember Waste actually doesn't strike me as something that fits given my understanding that the crazy stuff mostly happened a long while ago.

As the heat and storms are (supposed) to foreshadow (especially in conjunction with Dawn's commentary on them), there is still a *lot* of energy being poured into the Ember Waste from unknown sources. Stuff is very much still happening there. Conditions are appropriate for everything from "happened this morning" to "happened sometime long enough ago to be measurable in cosmological scales." Particularly since we don't actually have a date for the Ember Waste. All we really know is that several thousand years ago it was a much higher energy environment (radiating in the purple/UV spectrum primarily instead of in the reds/IR)

**Comment by ravenshining** [comment]
One of the neat things about the way The Lead did things like the carbon star, is it opens up possibilities for different layering combinations, as I demonstrated on the PR for creating alternate black hole images.  We can do something similar here, for example, swapping out the default `carbon-core` for an `f-giant`, to represent the star during its expansion/pulsing phase in a way that matches with the scene:

Screenshot_20220804_062640

**Comment by ravenshining** [comment]
Top post has been rewritten to be more comprehensive and... well, polite.  Sorry about that.  I had the flu and was in some panic at the time.

Went through the three carbon star systems and adjusted orbits based on the research above, and for aesthetics.  Results:

Ildaria:
Screenshot_20220804_083808

Kor Ak'Mari:
Screenshot_20220804_083554
Screenshot_20220804_083428

Antevorta:
Screenshot_20220804_083642

**Comment by MasterOfGrey** [comment]
> Would it be reasonable to assume that the star is currently between these expansive pulses, and the innermost, most coherent and in this sprite oddly squarish ring, is leftover from its last expansion/pulse.

Yes

> Could some lava planet be in the area of the intermediate ring, outside the expanded radius of the primary, inside the orbit of the companion?

If indeed it is a binary system, then any planets would've had to be close to one or the other star, or far out orbiting the whole system. Anything close enough would have gotten hot enough to boil the rock away into gas.

> I've read these pulses happen anywhere from between 1000 years to 100,000 years apart. Were the Wastes created less than 100,000 years ago, could planets have been hurled in then?

My understanding is that while these pulses can be slow - once they're specifically _carbon_ stars in this process, they're pretty close to the end (where my original times came from). I can be corrected on that, but there still shouldn't be anything close to the star.

My understanding is that the wastes were created >1 million years ago, though Zitchas point about them being in an ongoing state of change seems fair. There was also potentially some additional and significant disruption with the Builders and the Quarg/Pug disagreement in the last comparatively short while.

> Went through the three carbon star systems and adjusted orbits based on the research above, and for aesthetics. Results:

Following on from above; The inner most objects for Kor Ak'Mari and Antevorta still don't feel like it should be possible for them to exist - but things in the outer rings are somewhat ok I suppose as long as they're not like ice-planet sprites, and we don't talk about the possibility of there being a secondary star in there somewhere.

**Comment by ravenshining** [comment]
> Following on from above; The inner most objects for Kor Ak'Mari and Antevorta still don't feel like it should be possible for them to exist - but things in the outer rings are somewhat ok I suppose as long as they're not like ice-planet sprites, and we don't talk about the possibility of there being a secondary star in there somewhere.

Hm, well, the Wastes are Zitchas's wheelhouse, and so if they say planets are still being thrown about from time to time and it's fine to have planets that close, I don't want to change Antevorta any further.  One is a lava planet, the innermost is a dessicated rock, and the outermost is a sand planet.  I did not add a k-dwarf to Antevorta because it is supposed to be strange.

The planet on the sprite and the one moving in and out of it as it orbits k-dwarf in Kor Ak'Mari are both lava planets, and I don't mind moving the inner one outside if you think that's what needs to happen.

**Comment by Zireael07** [comment]
As someone who has spent quite a bit of time researching for my own space game, planet migration (especially from outwards to inwards) *is* a thing. So the carbon star might've destroyed the original inner planets, and thousands or millions of years later a previously outer planet got drawn in. (That's roughly how so many so called 'hot Jupiters' came to be, sans the carbon star bit :P )

**Comment by ravenshining** [comment]
Ooohhh, that gives me some ideas about things to write up for Korath Stage III! Thanks!

In fixing the merge conflict with master, this PR now *also* reverts the change in #7086 to the planet sprites in Kor Ak'Mari since that change upsets future plans for the system.

**Review by Zitchas — DISMISSED** [review]
These changes look good to me; and Ravenshining knows astronomy quite a bit better than I, so I'll trust them on the science part.

Anyway, I will note that a few uninhabited systems have significantly increased habitable ranges; but the arrival distances don't change. I don't think this is a problem as the arrival distances were already unmatched, so I'm of the opinion that leaving them as such is good. We can adjust them in a stand-alone PR if needs be; but in any case arrival distances is not the purpose of this PR.

**Review by Amazinite — CHANGES_REQUESTED** [review]
I'd still prefer that Ildaria use the same sprite that it does now. I also don't find it appropriate to shrink that image and put the old 1x image in the high DPI repo. Just leave it the size it is and where it is, please.

**Comment by ravenshining** [comment]
There.  Illdaria is now a `nova-small`.  I left the mini f-giant in there as I think that still helps it match the scene better.  I also moved the orbits back in, but I left the ice planets further out.

The original sprite is back at 1x, and I ran a DCCI upscale on it for the high DPI.  Ideally this sprite should be remade, but that is a task for someone more talented than I.

**Comment by Zitchas** [comment]
@Anarchist2 Just out of curiosity, why was my review dismissed? While there have been some changes since I left that approval, I don't think they are sufficiently major to invalidate it.

**Review by Zitchas — APPROVED** [review]
It appears that Anarchist2 was not to blame for the dismissed reviews, but rather a Github rule that dismissed reviews after stuff was pushed. Sort of a "there's new stuff now, so everything needs to be reviewed fresh" sort of thing. That's been disabled now. Re-approving this as per my previous approval.

**Comment by Amazinite** [comment]
> I left the mini f-giant in there

I just want it untouched. 🥲

**Comment by ravenshining** [comment]
> > I left the mini f-giant in there
> 
> I just want it untouched. smiling_face_with_tear

Okay, that's back to just the one, old sprite again.  Is that all, or did you want the ice planet back on the innermost orbit as well?

**Review by Amazinite — APPROVED** [review]

**Pull request merged**
