### PR TITLE
New Species: The Sleepers

### PR DESCRIPTION
**Pull request by AnxiousArchon**
**Summary**
Adds three new systems and a new species called the Sleepers (roughly tier 2.5ish) to the east of Korath Automata space with a couple of ships and a set of outfits. A spaceport encounter on Maker triggers an event which places the systems in their final position, and gives a mission to explore them. The encounter is locked behind the main storyline and Act 2 of the Wanderer storyline. I have written a short series of missions which establish communications with the species and explains their backstory a bit. As it stands now, if the quality is brought up to the point where it would be feasible to implement into the game, I think there is enough content to justify doing so. That being said, there is certainly room to add more in future PRs. Hopefully there is enough flavor here for other contributors to run with and create/build more content around.

**Background**
The Sleepers are driven by a desire for efficiency to such a degree that they want to hibernate past the interesting parts of the cosmological future to when all the stars have burnt out, and the universe is cold and dead. Humans call this distant but inevitable future the heat death of the universe. Because space will be so cold and empty, reactors will work just a bit more efficiently than they do currently; this is why the Sleepers are waiting for the heat death. To speed up their wait, they have built and inhabited a single large space station in orbit above a black hole. Like all very dense objects, the black hole that the Sleepers live around curves space-time such that the Sleepers experience the passage of time differently. Twenty four hours for the Sleepers might translate to months or years for an observer far away from the station. Humans call this effect gravitational time dilation. Because the temporal experience of the Sleepers is so divorced from the rest of the universe, they built a faction of autonomous robots, called the Custodians. The Custodians' primary function is to gather fuel and materials for the Sleepers so that they can use it when the heat death finally comes and they can leave their station.

**Note**
I am fairly new to GitHub and this is my first endeavour into ship/outfit/mission creation in ES. As such, the quality of many of the components of this PR are lacking. I more wanted to lay the groundwork for this new species so that more experienced contributors could see the gist of it and make improvements. I am opening up an issue linked to this PR which highlights the areas that need particular attention, and for discussion of how the problems in these areas should be addressed. If the species and their potential as an addition to the game isn't particularly interesting to anyone, I won't take it personally and I can remove the PR :-). I'd be thankful for any suggestions and feedback! Finally, please let me know if I've gone about making this PR wrong in any way.

**Save File**
This save file can be used to play through the new mission content. See the 'Test Testerson.txt' file in
[https://github.com/AnxiousArchon/ES_sleeper_blend](https://github.com/AnxiousArchon/ES_sleeper_blend)
Jump to Delta Capricorni and enter the spaceport on Maker to unlock the new region of space.

### CODE REVIEW

**Comment by Zitchas** [comment]
Thanks for the contribution. A couple suggestions for you to help improve how things go:

Firstly, having some more detail in the PR intro post would be welcome. I'd include two sections
    A) For the first one, think in terms of marketing: What makes the Sleepers interesting? Why would players care to visit them? What are they like? This first part would be basically a teaser just to get people interested. Including a screenshot of the new map showing where the systems are would also be helpful.
   B) The second section is more for content-creators and developers, and should dig more into the details of what this species offers. What stories would be set with them? How do they fit into the general scheme of the game? How powerful are their ships and outfits compared to other factions? Do they have something that they specialize in?

Secondly, if this is a work in development where you are hoping to build up the species, outfits, etc; I might recommend building it as a plug-in instead. As a plug-in, it would have the key advantage that anyone can download it and drop it into their plug-in folder and try it out. This could lead to more people playing it, and more interest. (While the ESlauncher has made trying out PRs much easier than in the past, there is still a comparatively tiny slice of the ES community that tests PRs, whereas lots of people play with plug-ins.) As far as being merged into the game in the future is concerned, being a plug-in is no disadvantage. Content from plug-ins does sometimes get merged, and is in fact the recommended way to work on large scale additions to the game.

**Comment by Arachi-Lover** [comment]
For whatever reason there are a lot of completely unrelated changes in the map file, which make it really annoying to find what's actually relevant.

the warship is definetly higher than 2.5, closer to 2.75 or 2.8, it's got about 10k less hull than the Interdictor while having 40k more shields (and given the size of the Interdictor compared to this, I'm inclined to believe a Medium Warship like this built on the same scale as the Interdictor would be uncomfortably close to what a Quarg MW would be). complete shield piercing seems a tad too much, the low range would only matter if they were fighting missile-boats or a player coordinating their range while using something like the Particle cannon to keep the ships at bay, since the AI will always charge into 'melee' range.
`The Sleeper's willingness to play fast and loose with such causal paradoxes greatly concerns the Quarg while simultaneously amusing the Pug.` why would either of those two care about it like that?
the shield generator is absurd at a whopping ~20 shield gen/space efficiency, almost no energy and heat, and a fuel cost that doesn't matter when you have `ramscoop 80`, or when you can just use the space that would otherwise be used for cooling down or powering up a shield this powerful with many ramscoops or fuel processors. if you compare it with the Quarg's shield generator, 120 tons means you can use 6 of these, which would give a ship 2400 shield generation per second. that's excessive even if it was for a Tier 3 species.

the graphics are pretty rough, the ships especially.

I'll say I don't like most of the conversations. I'm not a fan of involving Rek like this when we don't know what would change when Wanderers Act 3 is added, and her, an incredibly talented linguist, saying she can't help you with figuring out "synthetic language" is something I just don't buy; side-note, the thing about human history archives being used again is ehhh, even if you don't have to make the trip to Alexandria again.
you could theoretically attack and cap or just talk with the crewed Medium Warship, but you can only meet the robot, and not the creators? seems like there should be something where you can talk to one directly.

I just have to say, *another* one of these? how many species in ES will we get that are "X sentient created Y group of independent/automated ships/beings?" one of said Y still fight each other at the start of the game, another attacked the creators (twice, because the same mistake was done by said creators twice I guess), then what's new about this one is... they aren't killing everyone? will the entire galactic east be populated by species that each created their own AI/Symbiotic/Organic Spacefarings/Whatever Have You ? vary only by what the created group ends up doing?

**Comment by AnxiousArchon** [comment]
@Zitchas Thanks for the advice. Since I'm new I was unaware that the norm was to only post things that are essentially complete. If I get the time to work on this little addition more, I'll redo it as a plugin, and discuss how it should be implemented on the Discord.
@Arachi-Lover Sorry about the map file. I honestly don't know what happened there. As for the balancing, graphics, and the conversations: Yes, these could all use quite a bit of attention, and I'm not married to any of the ship/outfit values or graphics (see the linked issue). I was just unaware that GitHub was not the place to post code so it could be worked on collaboratively. As for the flavour this species adds to the game: this was the main thing I was gunning for. If this addition is really indistinguishable from the automata then it's pretty useless, I agree. However, I think the interesting thing is the psychology/motivation of the species (I've added a little bit in the summary section at Zitchas' suggestion so one doesn't have to read the files to get the idea) and this sufficiently differentiates them from the Exiles/automata. The point is, if one doesn't make the delineation between Custodians/automata or Custodians/Ka'het, then it also makes sense to make an equivalency between Humans/Hai, Humans/Remnant, especially Republic/FW, etc.

Given that this addition needs work and the story is perhaps not what other folks are looking for, I am going to close this PR and (if I get time) work on it some more with the input of the community.

**Comment by Zitchas** [comment]
Just to clarify: GitHub itself is a great place to collaboratively work on a project. However, it works better when you work collaboratively on your own project (then all the issues, PRs, etc are all relevant to your project), and then you can release plug-ins and stuff from there. Or PR it to the main repository, depending on how things go. People on Discord are pretty comfortable with following links to your own project. Most of the major projects and plug-ins have their own GitHub projects to help keep things focused. 

You can check out the Endless Sky Community repository for a list of guides and things to help:
https://github.com/EndlessSkyCommunity/awesome-endless-sky

Of note is the links to the plug-in lists. Many of those can provide you with an example of how you can set things up to work on your plug-in on GitHub.

**Pull request closed without merging**
