### PR TITLE
Combine the two Barbs into a single ship.

### PR DESCRIPTION
**Pull request by Quantumshark**
**Balance:**

## Summary
Removes the modified attributes, lost turret mount and alternate sprite from the Barb (Proton), making it only an outfitting variant, and moves it to variants.txt. Adds the +4 weapon space formerly on the Barb (Proton) to the base Barb, bringing it up from 24 to 28. The alternate sprite is retained to avoid breaking saves.

## Reasoning
As requested by Amazinite:
image

Objectively, this is a buff to the Barb - and I think it's fair to say that it could do with one. With this, the Barb becomes marginally more versatile. It can now run a single quad blaster turret and a meteor pod, for example.

### CODE REVIEW

**Comment by Zitchas** [comment]
Why? What's the justification for this? The whole point of the Barb is that it's the strictest barebones implementation with zero extra mass wasted on stuff like hardpoints that aren't being used. 

I mean, I don't think it'd break the game or anything to do this combination, but neither do I think we're actually gaining anything useful. And it is a neat (albeit very minor) bit of detail/lore to have such a stripped down ship.

**Comment by Quantumshark** [comment]
The description explicitly mentions flexibility as the Barb's primary asset, and it doesn't really have much else going for it. This adds to the Barb's flexibility, so it helps emphasize the Barb's strength.

In the more general scope of human fighter balance, the Finch is currently top of the pack in almost every category - mobility, armament, and toughness. With this, the Barb is nudged to the top of fighter armaments (adding a clear upside to balance out its worst-in-category mobility and toughness).
I'd also like to look at giving the dagger more mobility - my main idea was to give it +5 engine space and give it an atomic thruster, to better fit its description which (erroneously) proclaims it to be "considerably faster than other fighters".

**Comment by Zitchas** [comment]
That's fair.

That being said, I honestly rather like having a fighter that includes baked into its description "We had to tear out the additional hardpoint to get enough space to fit this bigger gun on it." That's just a fun bit of lore/description/character as far as I'm concerned.

Standard:
> Though the Syndicate doesn't build fighter carriers, it is testing the waters with the Barb, a cheap and flexible carrier-launched craft featuring newly-developed miniaturized ion engines. The design philosophy of the Barb seems to have been "uglier than the Protector," and as you look at the cockpit nestled between the massive gun port and turret mount, you wonder where the power systems are supposed to go. Though an awkward-looking ship, it seems flexible enough to become a dangerous addition to any fleet with carriers.

Proton:
> The Barb's commercial success spurred demand for a variant equipped with a Proton Gun. Syndicated Systems had to remove the turret mounting hardware to fit the powerful cannon, but the result is a level of short-range firepower that is unheard-of for a craft its size.

**Comment by Zitchas** [comment]
> We could add the weapon space and take the turret away and even still change description in the variant, right?

Yes, we can do that. There's really not much difference between having two barbs, and having a barb and a variant barb; aside from the fact that missions will recognize both regular and variant as being one of the same kinds of ships. So arguably it's probably better to have barb+variant than to have two barbs.

**Comment by Amazinite** [comment]
I think the two Barb variants should be combined into one because I don't feel like having two Barb variants really brings anything to the table. Looking at the Barb generally, what makes it stand out from the other human fighters is enough weapon space to fit a Proton Gun (for the proton variant) and a turret mount (for the turreted variant), but the only thing that divides the two variants is 4 weapon space and a single hardpoint. Balance-wise, what reason do we actually have to split these variants? A Barb that has a Proton Gun equipped has 0 remaining weapon space, so having the turret mount on the same fighter that can fit the Proton Gun isn't a balancing issue as it adds nothing to the combat capabilities of the fighter to have an empty turret mount. And adding 4 extra weapon space to the Barb that has a turret only allows it to install one new (human) turret that it wouldn't have been able to before, that being the quad blaster turret, but good luck effectively powering a quad blaster turret on such a small ship. So the way I see it, there's little reason to have the variants be split.

Keep in mind too that the Barb is the slowest of the human fighters (excluding the Boxwing), as it has the lowest engine space. Its total HP is also rather poor; the Finch and Dagger have total HPs of 1300, with the Lance at 1200, while the Barb only has a total HP of 1000. So we have a fighter that can equip heavier weaponry at the cost of being not only slower but also squishier. So even if combining the variants allowed for some massively powerful combination that we're not seeing right now, that's coming at a cost. (And frankly, if we want to lean into the Barb as being humanity's "heavy fighter," it deserves an HP boost, but I think that's a topic for another PR.)

To the concern of the loss Proton Gun Barb's lore, we could easily change the description of the combined Barb to include something similar. How does this sound?
```
description `Though the Syndicate doesn't build fighter carriers, it is testing the waters with the Barb, a cheap and flexible carrier-launched craft featuring newly-developed miniaturized ion engines. The design philosophy of the Barb seems to have been "uglier than the Protector," and as you look at the cockpit nestled between the massive gun port and turret mount, you wonder where the power systems are supposed to go. Though an awkward-looking ship, it seems flexible enough to become a dangerous addition to any fleet with carriers.`
description `	In order to be capable of fitting a Proton Gun while still maintaining a turret mount, Syndicated Systems had to remove various life support systems, requiring that the pilot wear a pressurized suit rather than having the cabin be fully pressurized. Although it makes piloting a Barb an uncomfortable experience, the result is a level of short-range firepower that is unheard-of for a craft its size.`
```

**Comment by Zitchas** [comment]
That's a good argument; and I like the revised description. Pilots stuck in their spacesuits for the duration of travel. And our pilots thought that being stuck in the boxwing was bad... At least they can change their clothes...

With the revised description, I'm good with it.

**Pull request merged**
