### PR TITLE
Added Quarg descriptions

### PR DESCRIPTION
**Pull request by Gkramme**
This PR gives all the Quarg outfits descriptions. The descriptions are up for change, so any ideas are welcome!

### CODE REVIEW

**Comment by Gkramme** [comment]
What's wrong with this?

**Comment by jafdy** [comment]
conflicts hear too.

**Comment by Gkramme** [comment]
How to fix them?

**Comment by Wrzlprnft** [comment]
Maybe because the hails?

**Comment by Gkramme** [comment]
Which hails?

**Comment by Gkramme** [comment]
Can this be merged if you make a few changes?

**Comment by Wrzlprnft** [comment]
The actual procedure would be: you do fetch the endless sky master and merge it into this branch. it will show some 
>>>>>>>head

>>>>>>>endless sky master

<<<<< end conflict

you select one version and delete all the rest. then the merge conflicts should be solved

**Comment by Gkramme** [comment]
How do you merge though? Lots of people have told me but I can't make heads or tails of it.

**Comment by Wrzlprnft** [comment]
Ill edit some useful information in this comment later.

**Pull request closed without merging**
