### PR TITLE
fix(content) [Coalition] Prevent Coalition Games jobs from offering with deadlines after July

### PR DESCRIPTION
**Pull request by Arachi-Lover**
----------------------
**~~Copied Homework~~ Bugfix**

## Fix Details
This PR pretty much does what #7992 did for the Earth Day jobs, but for the Coalition Games jobs instead.
The Games take place in July, so I just applied the same logic warp-core did for Earth Day, adjusting the date.

### CODE REVIEW

**Comment by Saugia** [comment]
Copy his homework, you say?

**Comment by warp-core** [comment]
This deadline seems to be for the end of July? Is that the goal?

**Comment by Arachi-Lover** [comment]
> This deadline seems to be for the end of July? Is that the goal?

Yeah. Like how Earth Day's jobs offer during April and before the 22nd, Coalition Games jobs offer during July.

**Review by warp-core — APPROVED** [review]
Should work as well as the Earth Day change.

**Comment by Saugia** [comment]
>warp-core: 

>"Should work as well as the Earth Day change."

**Pull request merged**
