### PR TITLE
Multiple outlines in mask.

### PR DESCRIPTION
**Pull request by flaviojs**
This was created while experimenting with alternate ways of showing outlines and is being split off to this PR because it fixes sparks in transparent areas.

Main change:
 * Generate multiple outlines in `Mask`, adding support for holes and independent shapes.
Thanks to that, sparks no longer appear in holes: (image by @tehhowch) 
outline_hole

Other changes:
* More accurate image traces by interpolating the position with the directions and the alpha value.
* Smoother simplified outlines (closer to original image) by using squared area instead of squared distance to decide when to stop simplifying.

### CODE REVIEW

**Comment by tehhowch** [comment]
<details><summary>For reference, the current behavior:</summary>

image
</details>

**Comment by KiLEdEnNis** [comment]
does this also mean a ship could now consist of multiple shapes that aren't connected to each other?

**Comment by flaviojs** [comment]
Yes, it allows ships with multiple independent shapes (not connected to each other).

**Comment by flaviojs** [comment]
Reminder: the wiki page [CollisionDetection](https://github.com/endless-sky/endless-sky/wiki/CollisionDetection) will need updating.

**Comment by Amazinite** [comment]
I believe that the ship builder would need updating to express the changes to collision masks as well.

**Review by tehhowch — APPROVED** [review]
@beccabunny @Ferociousfeind: your signoffs are requested

**Review by beccabunny — APPROVED** [review]

**Pull request merged**
