### PR TITLE
Hide trading panel when system is known and uninhabited

### PR DESCRIPTION
**Pull request by Rakete1111**
This implements #1497.

Nothing else to say :)

### CODE REVIEW

**Comment by toilethinges** [comment]
Does this hide it when there isn't a spaceport, or when there are no trade prices? Just for clarification.

**Comment by Amazinite** [comment]
Ruin is uninhabited, so I would think yes.

**Comment by Rakete1111** [comment]
@toilethinges It hides it when there isn't a spaceport on any planet in the system.
Ruin is an interesting case, but I actually don't know if it would show it or not. 

If it has a spaceport, the panel should show up, as per the code. The data in pug.txt shows that it has the attribute uninhabited, but I don't know what this changes, I'll have to investigate.

**Comment by endless-sky** [comment]
I'm not sure if it makes sense to do this, because the trade panel serves two purposes. It shows the trade prices for the current system, but it also lets you click on commodities to change what the map is colored by. I would find it annoying if whenever I bring up my map in an unoccupied system, the only way I can view commodity prices is by first clicking on an occupied system.

**Comment by Bladewood** [comment]
I find something (else, and probably completely unrelated) annoying: I cannot set my map's system colors to [reputation] if I am in a system with no objects I can land on.

**Comment by Morcleon** [comment]
@endless-sky I agree, since that's also a (slightly) easier way to check if there's a spaceport at all. I'd make the suggestion to remove the Trade button on the actual planet screen if there's no trader there (similar to how the Shipyard and Outfitter buttons disappear if they don't exist).

**Comment by Rakete1111** [comment]
I could change it: always display it in for the current system, ignoring every other condition.
But I don't know if that would confuse players or not.

Yeah, being able to change the colors of the systems by trade in any system selected might be even better than hiding the system completely.

@Morcleon Isn't it already hidden?

**Comment by Morcleon** [comment]
I could have sworn there was one planet where the Trade button gave a blank box with no prices, but I can't seem to find it.

**Comment by Bladewood** [comment]
That happened to me when I visited Far'en Lai, but I think that would have been fixed by now.

**Comment by Morcleon** [comment]
Well, looks like it was fixed, but now you can buy and sell commodities (and hire crew) from the non-existent Korath on the surface. xD

**Pull request closed without merging**
