### PR TITLE
fix(content): Quick bugfix to the backup smuggler chain for HR

### PR DESCRIPTION
**Pull request by MasterOfGrey**
Offer conditions are borked, this should fix them.

### CODE REVIEW

**Comment by HotaruSama** [comment]
Okay, this is my first submission, but I talked with Grey about it on the discord, and tested it. The mission now depends on the prior boarding mission being finished and does start once you land on Stormhold. I think I attached the file correctly, please tell me if I screwed it up.
[hai reveal 5 philosophers.txt](https://github.com/endless-sky/endless-sky/files/9847888/hai.reveal.5.philosophers.txt)

**Comment by RisingLeaf** [comment]
> Okay, this is my first submission, but I talked with Grey about it on the discord, and tested it. The mission now depends on the prior boarding mission being finished and does start once you land on Stormhold. I think I attached the file correctly, please tell me if I screwed it up. [hai reveal 5 philosophers.txt](https://github.com/endless-sky/endless-sky/files/9847888/hai.reveal.5.philosophers.txt)

please just show what you changed, nobody wants to search through a file of this size

**Comment by HotaruSama** [comment]
Okay. Line 590.
Change `has "Hai Reveal [B06-long] Tarazed Analysis: done"`
to `has "Hai Reveal [B06-long] Boarded Smuggler: done"`

**Comment by MasterOfGrey** [comment]
Gonna add a cleanup, don't merge yet

**Pull request merged**
