### PR TITLE
feat(balance): Hawk and Berserker tweaks

### PR DESCRIPTION
**Pull request by Zitchas**
**Content (Artwork / Missions / Jobs)**

## Summary
- Hawk reduce required crew from 2 to 1
- Hawk reduce hull mass from 150 to 110
- Berserker reduced hull mass from 110 to 90

## Explanation
Crew count:
The Hawk is quite a small ship: It's got only 2 guns, and can't mount turrets at all. On the other side, it's got 20 cargo and 2 (now 3) spare bunks. There's really not a lot of stuff to manage here, nor very much in terms of economic opportunity, either. 

In terms of outfit space, it has 200 outfit. This is the same as the Berserker (which has 1 crew), and less outfit space than the Bounder, which is a transport in the same size range, but also has 16 free bunks and double the cargo at 40 and manages that all with only 1 crew. 

20 cargo is peanuts for commodity hauling and jobs, poor for jobs, and not even great for mining. One obvious method of income for combat ships is looting, but that 20 cargo kind of impedes this. Cargo expansions are a possibility to improve this, but that's likely to cut into the capacity to actually fight, which is fairly important for both mining and salvaging.

On the flip side, by reducing the max crew by 1, this expands the available bunks by 1, which increases it from 2 to 3. This gives the Hawk a slight bit of flexibility in mission running and carrying passengers. The difference is slight, but it can be significant at this point in the game.

Between all these lore and limitation aspects, the  Hawk just doesn't feel like a ship that needs another crew member. As an interceptor, it's also one of the last ships (in human space, at least), that makes sense to be a solo ship. As in, one that we're flying by ourselves. This also means that the player isn't subject to ongoing crew costs and a constant drain on their finances while they are flying a ship that - while fun - isn't really a great ship for making money.

Mass: 
Two parts to this:
a) What else has a hull mass of 150? Corvette, Clipper, Gunboat. What are some things lighter than this? Aerie, Raven, bunch of Marauder ships, bunch of light warships... So, two medium warships, a bunch of light warships, light freighters, and assorted other ships. The fact that it's got more hull mass than two medium warships and a bunch of light warships is rather problematic. At the very basic level, the Aerie has 7600hp, vs the Hawk's 3000hp. The fact that it has 28 bunks and 50 cargo (and 390 outfit) make it extremely odd that the Hawk has more hull mass. Corvette also has 7600hp, 32 bunks, 40 cargo, and 420 outfit space. Yet somehow requires the same amount of structure to hold together as the Hawk. These two are the big outliers, but others are similarly oddly matched.
b) Performance. The Hawk is supposed to be a Tarazed ship, probably the most advanced interceptor in human space, and is explicitly described as being able to chase down most smaller ships. Given it's role as a freighter escort and part of planetary defense militias, this probably means hunting down fighters, interceptors, and the odd smuggler transport ship. Given how fast some of these latter get, this implies it should have pretty good performance. 
c) From a meta perspective, the fact that it's basically the best interceptor that one can get in human space, it's probably the last interceptor the player is ever likely to fly. By the time they get access to one of the other interceptors (of which there aren't many), they will likely be in an actual warship, and not likely to want to downgrade.

edit: Amazinite suggested bringing the Hawk down slightly further to 110 (I had it at 115), and include dropping the Berserker to 90. I think this is reasonable, so I have included it. The Berserker really can use some love too, honestly.

In this case, I dropped the hull mass by 40 down to 110, while dropping the Berserker down to 90. So it is still 20 bigger than the next biggest human purchasable human interceptor, but moves it to be smaller than the other human light and medium warship. This means it has a little bit better acceleration and turning, as befits what amounts to a fighter-hunter. Definitely more fun to fly, perhaps fun enough to put off upgrading for a bit longer. 

In the larger scope of things, the whole mass system needs to be redone. But in the meantime, this tweak moves the Hawk into at least the proper sequence relevant to the surrounding ships, which will make future work easier in that regards, and given that the mass rebalance is, based on the current stream, a very long ways off, this will allow the Hawk a little bit more playability and longevity.

## Save File
This save file can be used to play through the new mission content:
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}

## Artwork Checklist
 - ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
 - ~~[X] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
 - ~~[X] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}~~

### CODE REVIEW

**Review by Hecter94 — APPROVED** [review]
This seems like a very appropriate change to me. 
The Hawk was always the only non-marauder interceptor with more than one required crew and never seemed to have anything to justify it being the exception in that regard. 

Bringing it's Mass down also seems perfectly reasonable. It having the same mass as the Gunboat, while having a third of the bunks, less than half the cargo space and 30% less outfit space is frankly silly. 

Altogether, I approve of this change.

The only other thing I feel worth mentioning is that while I do approve of the change to the required crew, the Hawk *visually* very clearly appears to have a two-seater cockpit compared to something like the Fury or the Berserker:

image

image

image

So we may want to consider tweaking the visual design at a later date if we do change it's required crew.

**Comment by Amazinite** [comment]
Here's the existing hull masses of the human interceptors.

Ship | Hull mass
---|---
Sparrow | 50
Wasp | 60
Fury | 70
Berserker | 110
Hawk | 150

Could probably bring the Berserker down to. Maybe 110 -> 90 for the Berserker and 150 -> 110 for the Hawk.

**Comment by Zitchas** [comment]
Sure, I'd be happy to do that. Do you want that in a separate change, or should this become a general "tweak the interceptors a bit" PR?

**Comment by Amazinite** [comment]
It's fine to do it here.

**Review by EjoThims — APPROVED** [review]
This feels like a very appropriate adjustment to their current placement as a readying step towards larger across the board adjustments.

From a theming perspective, I feel like all baseline human interceptors still being single crew requirement gives a lot more room to help differentiate other places. A theoretical (justified) 4-5 or even 20 crew alien interceptor gets a lot more impactful now, imo, even if most people will only use them as escorts by the time they see them.

**Review by Hurleveur — APPROVED** [review]
we noticed this weirdness of mass together and I approve of it being fixed
I never use those ships because they just dont have a selling point, them being better in combat will help with that

**Comment by Zitchas** [comment]
To be honest, my recent playthrough (which was the first one where I've pushed myself to not only start with the interceptor, but stick with interceptors as long as possible) led me to feel that it's not a super great experience. They are without doubt the most "fun" to fly; and dodging stuff in combat is quite fun when I can manage to do it. But it doesn't really make up for the fact that there's precious few opportunities in this game for an interceptor to have much role as a solo ship in combat. We can ignore that small ships have no place as a flagship in combat for transports and freighters because, well, they're transports and freighters, not combat ships. They have other things they are supposed to be doing. But an interceptor? Combat is its thing. If it can't make a living doing that, then it's basically a bait-and-switch thing. 

"Look at the shiny combat ship, it's fun to fly... Oh, wait, you actually want to fly one? You actually want to fight stuff? lol. Go mine asteroids. Maybe take a job or two hunting tiny fighter pirates, or cheesing escort missions (because you almost certainly can't fight most of the pirates that will target those freighters...) The fact that there are so few weapons that one can use to kite just makes it even worse, since kiting is one of the few ways a highly agile but relatively lightweight ship can really take on a bigger warship.

**Comment by Hurleveur** [comment]
> But given how fast the shield recharge rates are on basically everything

I don't think that's the case in human space, in fact all generators are completely useless except for the biggest one (and the synd ones obv) if you ask me

**Comment by Zitchas** [comment]
I find them a double edged sword: Too slow to feel useful *on* my ship, and too fast for my ship to be effective against when I fly an interceptor against them, unless I cross the magical threshold where my DPS is good enough to just overwhelm it and I've got sufficient advantage to just make it a slugging brawl.

**Comment by Hurleveur** [comment]
I think human shield gen should not work when under fire but when not give more regeneration, that way they'd be more useful; at least for the smallest ones.

**Comment by vitalchip** [comment]
I think either change the interceptor start to a mining ship start or if sticking with the interceptor then take the player by the hand for a bit.

Tell them they won't get much work around here because it's too safe, direct them to a predetermined system where the threats are minimal and controlled. Have some freighter Captain offer them a chance as a rookie escort because one of their usual guys has engine trouble etc. Make sure it's a ship which already has several intercaptor escorts and give the player the role of staying with the ship as a guard while the other escorts take on any threats.

Once they've done that do the return trip undder the same conditions and after that gradually give them a more prominent role but still always one of many. 

There are many things in game which really disadvantage small ships and this isn't the place but until many of those are addressed it's always going to be a tough way to make money.

**Comment by Zitchas** [comment]
Agreed, this isn't really the place for this discussion. (probably, ideally, belongs over in one of the many dead horse threads about fighter balance...) But thanks for the ideas! Perhaps we can discuss them (or test them) elsewhere sometime.

**Comment by Zitchas** [comment]
> The only other thing I feel worth mentioning is that while I do approve of the change to the required crew, the Hawk _visually_ very clearly appears to have a two-seater cockpit compared to something like the Fury or the Berserker:

I don't actually find that a problem. After all, we *can* have as many as 4 crew and humanity currently has a *lot* of vehicles (aircraft in particular) that only *require* one person to operate, but have windows (and often controls) to allow 2 or more people to see out.

As far as that goes, it's entirely possible and perhaps even likely that in such a small ship, one or more of the seats passengers are expected to be in during flight *is* right there next to the pilot/captain. Nothing says that the cockpit/main window must be sized such to explicitly prevent anyone other than required crew from seeing out.

**Pull request merged**
