### PR TITLE
feat(content): Reduce payment of "Deal Change 2"

### PR DESCRIPTION
**Pull request by Anarchist2**
Halves the mission's payment, so you can't pay off your entire mortgage in a single mission.

### CODE REVIEW

**Comment by Hurleveur** [comment]
Wouldnt it be more interesting if we added some more risk instead?

**Comment by Amazinite** [comment]
What risk could we add that wouldn't just be adding pirates that you could bribe, which would only dampen your reward slightly, especially if this mission is being received early game when your bribe costs are low? Unbribable pirates in Lesath and Shaula?

**Comment by Hurleveur** [comment]
I was thinking of the ones who asked you to get this package to the right place hiring bounty hunters to see what happened to the cargo
They could cost a lot to bribe of be unbribable

**Comment by ziproot** [comment]
Bounty hunters already cost 4x more to bribe than pirates (bribe 0.2 instead of bribe 0.05). I don't think that's enough but at least it's better. I think having both the bounty hunters **and** halving the reward is the best option, as combined it should only be a little more than following the orders now if you bribe them.

**Comment by Hurleveur** [comment]
Yeah and idea would be that one of the pirates on that world tips the ones who asked you to deliver the cargo, and you get a bounty hunter on you for like 14 days? You'd have to bribe them a lot if you dont want to fight

**Comment by Amazinite** [comment]
I don't think it makes sense to have the bounty hunters follow you. You're able to choose to go to either destination, but if the bounty hunters are from the original mission providers to prevent you from bringing the cargo elsewhere, it doesn't make sense for the bounty hunters to attack you when you could be going to the original destination, and speaking from outside of the story, bounty hunters following you just makes both destinations more difficult instead of only the higher paying destination.

**Comment by Hurleveur** [comment]
I meant for the bounty hunter to attack you after you betray them
Yeah we can add hostiles but thats easier

**Comment by Amazinite** [comment]
> I meant for the bounty hunter to attack you after you betray them

That wouldn't be increasing the risk of going for the higher paying option, that'd be providing a punishment for doing so. It's not quite the same thing.

**Pull request merged**
