### PR TITLE
New indigenous lifeform in the Ember Wastes: the Embershade

### PR DESCRIPTION
**Pull request by Galaucus**
https://user-images.githubusercontent.com/68889791/103321740-e6048780-49ef-11eb-9d3a-b51fd8b1ae4f.mp4

## Summary
Void-dwelling creatures native to the Ember Wastes, the Embershade are ray-like entities which generate a natural cloaking field. Generally shy, they prefer to give intruding ships a wide berth and remain under cloak whenever possible. During the occasional ion storm that washes through the Wastes they become visible.

My intention with the Embershades is to add a ghostly presence to the otherwise-empty wastes; I want the player to know in the back of their mind that there's something there in the system with them, but they can't quite see it. The overall experience should be mildly disconcerting: a dark silhouette and scant luminescent patches should evoke the feeling of seeing a shadow moving in the sea, the creature's true form indeterminate. 

## Save File
[This plugin can be used to preview the new critters. For testing purposes they spawn in Segesta, Stercutus, Caeculus, and Peragenor.](https://cdn.discordapp.com/attachments/266345072554016768/793624413206609950/Embershades.7z)

## PR Checklist
 - [x] Initial mockup and testing complete
 - [x] Assets recreated in blender (blender work by @Ferociousfeind) , textured, and animated
 - [ ] New personalities implemented by @InfiniteDonuts 's PR #5698  
 - [x] Fine-tuning of stats, spawn rate, and systems
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: https://drive.google.com/drive/folders/1UvahLxZrVPUZ5OXumWGBWuN-NvWx-qE5?usp=sharing
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/173

### CODE REVIEW

**Comment by Zitchas** [comment]
Alright. I saw this back when it was posted, but I'll post this just for the record:

Very cool idea. I really like the effect of having a permacloaked creature that fades partially into view during storms. I like the idea of having these being found sparsely throughout one cluster of systems. 

I think the cluster at Segesta, Stercutus, Caeculus, and Peragenor would probably be a good place for them.

**Comment by Galaucus** [comment]
> I think the cluster at Segesta, Stercutus, Caeculus, and Peragenor would probably be a good place for them.

I'll double check or tweak their government assignment to ensure they won't "land" on Ember wormholes.

**Comment by Galaucus** [comment]
Ready for review - just waiting on InfiniteDonuts' AI, and this will be ready for merge. I'll still be making small graphical tweaks to get the Embershade just right, but as-is it's good to go. Eventually I hope to come back and do a properly, fully animated version with majestic space-flaps, but until then this is better than nothing.

**Comment by Galaucus** [comment]
Animated embershade

**Comment by Zitchas** [comment]
Once the AI are ready for merging, I'll merge both them and this into Revamp to make it easier to test.

**Comment by Galaucus** [comment]
I accidentally broke the PR. Replacement is up #5933.

**Comment by tehhowch** [comment]
It doesn't look broken...

**Comment by Galaucus** [comment]
> It doesn't look broken...

unknown-3

**Comment by InfiniteDonuts** [comment]
oh dear

**Pull request closed without merging**
