### PR TITLE
No nerve gas on Trinket

### PR DESCRIPTION
**Pull request by Pointedstick**
Removed pirate outfits from Trinket so that you can't buy nerve gas et al. on what's presented as a tourist planet.

### CODE REVIEW

**Comment by Amazinite** [comment]
#1466

**Comment by Pointedstick** [comment]
I know about that one. But there's no explanation whatsoever for why this tourist planet sells something so illegal that the only other place in the galaxy where you can buy it is the pirate planets.

**Comment by Amazinite** [comment]
>Many of the starships parked here have scorch marks and dents on their hulls, a sure sign of recent battle. It is likely that some of the people walking through the port are in fact pirates, posing as civilians in order to sell stolen cargo or to take a vacation incognito.

**Comment by Pointedstick** [comment]
Oh, lol.

Still, the outfitters would be _selling_ highly illegal outfits just because pirates vacation there?

**Comment by Amazinite** [comment]
That goes back to what MZ said in #1466. XD

**Comment by Pointedstick** [comment]
I dunno, that seems like a cop-out. With that logic, virtually anything should be available anywhere. Am I really being led to believe that nobody on a whole lot of entire *planets* sell things like batteries, laser rifles, scanners, and starmaps? Really? I can't find those things _anywhere at any seller on the entire planet??_ I can find the terrestrial equivalent of all that stuff within a 15-minute walk of my house, for Pete's sake.

**Comment by DingusShingleton** [comment]
I guess the question becomes, are the outfits and items available for purchase everything that *can* be purchased? Or are we assuming that there are many other things that simply can't be represented realistically in the game world, IE that we don't need the likely dozens or hundreds of small twin-gun interceptors made by every company under the sun, because the sparrow can simply represent all of them?

If it's the latter, then we have to accept that what we are buying at the outfitter isn't a note for note representation of what's available... that there is a layer of abstraction between what we buy and what would actually theoretically exist on these worlds, and therefore, we can't hew too closely to the idea that everything has to "make sense" in that regard.

Honestly I'm not sure where I'm going with this, or what point I'm even trying to make. Just throwing some vaguely philosophical meandering into the mix and hoping something sticks...

**Comment by Pointedstick** [comment]
I could understand the notion that when I buy a Plasma Cannon, my character might really be buying a plasma-cannon-like gun cobbled together from what was locally available that's represented by a Plasma Cannon in-game.

What I can't understand is why the local equivalent of _nerve gas grenades_ should be for sale on a tourist planet simply because some of the tourists are incognito pirates.

**Pull request closed without merging**
