### PR TITLE
Update free worlds checkmate.txt

### PR DESCRIPTION
**Pull request by Alkallid**

### CODE REVIEW

**Comment by psychiclegume** [comment]
On line 540, where you change Speaker to speaker, It should be capitalized, as Speaker is shortened from Speaker of the House or Senate or whatever it is that they have. It is a title like Senator. If MZ was saying "the speaker said..." then it would be speaker.

**Comment by Alkallid** [comment]
I did wonder about that... I can't change it now, unfortunately. A but later

**Comment by psychiclegume** [comment]
Can't you just go into the files changed tab and edit it with the pencil in the top left corner?

**Comment by Alkallid** [comment]
I need a computer for that...

**Comment by Alkallid** [comment]
Closed unless you want it.

**Pull request closed without merging**
