### PR TITLE
Split the map file into multiple files

### PR DESCRIPTION
**Pull request by Amazinite**
## Summary
So guys. We did it. We reached one megabyte of information in the map file. A file so big, GitHub now refuses to render it using the normal view.
image

The potential of splitting up the map file has been discussed a number of times in the past. Even before this point, it's been a very large file for a very long time, and has proven difficult to deal with in the GitHub browser when it comes to reviewing pull requests. But with the file now this big, we basically have no choice but to split the file up unless we're willing to not do anything in the browser when it comes to the map.

This PR splits the file into two parts, one part containing all the galaxies and systems and the other part containing all the planets and wormholes. While by line count the planets and wormholes don't take up that much space, by storage count this nearly cuts the file into two halves because of the planet and spaceport descriptions being so much longer than your average system definition line.
image
This was done instead of splitting the map file into regions, as has sometimes been suggested, because I would like to keep the number of splits we have to make to the map at a bear minimum to reduce any potential overhead that would come with dealing with multiple map files.

I am opening this PR as a draft to display our intentions to split up the map file. Before this is merged, we must first determine if we have the tools to continue development of the map file in this split state without requiring us to stitch the file back together then pull it back apart again every time we want to use an editor of some sort. This mainly just means making sure @quyykk's editor can handle editing a split map, because that's basically all anyone uses now with the official system editor being so broken and decrepit.

### CODE REVIEW

**Comment by Saugia** [comment]
:ohno:

**Comment by RisingLeaf** [comment]
If we split by object type planet <-> system
why not make a separate file for galaxies(labels)?

**Comment by Hecter94** [comment]
Seems like a good initiative to me. Especially with more new factions coming.

**Comment by Amazinite** [comment]
> If we split by object type planet <-> system
> why not make a separate file for galaxies(labels)?

Galaxies/labels make up such a small number of lines in the file to begin with, and their positions are in the same plane as the system positions, so it doesn't make much sense to me to move them into their own file.

**Comment by RisingLeaf** [comment]
> > If we split by object type planet <-> system
> > why not make a separate file for galaxies(labels)?
> 
> Galaxies/labels make up such a small number of lines in the file to begin with, and their positions are in the same plane as the system positions, so it doesn't make much sense to me to move them into their own file.

good point, I accept that

**Review by Hecter94 — APPROVED** [review]
This change seems appropriate to me, and would resolve the issue with GitHub and allow us to view the map file again. 
As such, I'd like to see this merged sooner rather than later so we can get that issue resolved.

**Review by warp-core — APPROVED** [review]

**Review by Zitchas — DISMISSED** [review]
This PR adds to the clutter in the root level of the data folder. While it is technically required to use GitHub's diff in conjunction with the map file, I'd like to see it done in a way that doesn't make the clutter of the data folder worse.

**Comment by Amazinite** [comment]
1) The root folder isn't exactly what I would describe as cluttered.
2) One extra file doesn't suddenly make it cluttered.
3) This PR is about the size of the map file becoming a difficulty to deal with, not the organization of the root folder.

**Comment by Zitchas** [comment]
This was inappropriately merged, and my comment was inappropriately cleared.

Also "map_planet + map_system" is a very poor organization choice compared to using a folder. We already went through this once with faction naming. Now we're just repeating it with map stuff.

**Pull request merged**
