### PR TITLE
Switch libpng reference to latest version.

### PR DESCRIPTION
**Pull request by Isaacssv552**
Updated the XCode project to work with the latest version of libpng. Without this change a system with the latest libpng installed compiles a bugged game that hangs at launch.

### CODE REVIEW

**Comment by Elyssaen** [comment]
Since I ran your multi-jump code okay, I take it this is backward compatible for those with an old version of libpng?

**Comment by Isaacssv552** [comment]
I wouldn't expect it to be, you need libpng16.16.dylib for it to compile. All it does is change the reference from libpng14.14.dylib to libpng16.16.dylib because compiling with libpng14.14.dylib causes the game to hang on launch.

**Comment by Pointedstick** [comment]
This is basically a duplicate of https://github.com/endless-sky/endless-sky/pull/202

**Comment by endless-sky** [comment]
I'll upgrade libpng eventually, but I'm in no hurry to do so because the old one works fine, so switching could only break things. (Note that your change made it so that the library isn't copied into the app, which would cause it to fail to launch on systems where the library is not installed.)

**Pull request closed without merging**
