### PR TITLE
Animated Stars

### PR DESCRIPTION
**Pull request by Amazinite**
I created this and got some good feedback from a couple of people who tried it out, so I thought I might as well just PR it to try.

As stated, it animates all the stars, giving them the look of their upper layers moving around. As to keep with MZ's wishes in #1517, the frame rates are low so that the animations aren't too drastic/visually distracting.

@2x images at the ready.

### CODE REVIEW

**Comment by toilethinges** [comment]
I'm going to actually try it now, because I think I'm one of the people included in "a couple of people who tried it out."

**Comment by Amazinite** [comment]
I might try and dim down the small, red stars because they seem a little brighter and more distracting than the rest.

**Comment by Amazinite** [comment]
[The Steam thread link](http://steamcommunity.com/app/404410/tradingforum/350540973999405802/?tscn=1473119611), for the sake of seeing the responses there.

**Comment by davidwhitman** [comment]
Just tried it out as well. I like it, I guarantee people would mention it in their Steam reviews. "Played for 10 hours before I realized the stars were animated. This game is awesome!"

The Regulus star animation was nice, but uneven. It seemed like it would ease from state A to state B, then ease back to A. As opposed to constantly changing state, albeit in a loop. 

So, seemed like 
ABCCBA
instead of
ABCDEA

perhaps there are a certain number of frames and it's going through the set, then reversing; I didn't look at the code.

**Comment by Amazinite** [comment]
Every single star is set to loop through 7 frames at 1 frame every 2 seconds, so it might be that some of the frames are too similar. I'll take closer look at it and see if it's the same for me.

**Comment by Amazinite** [comment]
Yeah, once per 5 seconds looks better to me.

**Comment by davidwhitman** [comment]
Yeah, I like it. Very subtle now. Could be said to be too subtle, but better this way than too obvious. Nice work!

**Comment by Amazinite** [comment]
Thanks. :)

**Comment by toilethinges** [comment]
Between this and mining, the map editor really needs to be updated. Otherwise, newer creators will end up having systems with no stars and no mineables.

**Comment by Amazinite** [comment]
Well their systems would still have stars; they'd just need to set the frame rate.

**Comment by Pointedstick** [comment]
I LOVE this!

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky-tools

**Comment by endless-sky** [comment]
Sorry, but I really like the existing stars better. These are way too saturated. When you look at the sun in real life, you see a white disk, not a bright yellow one. These end up looking cartoony - to my eyes it wasn't even clear at first that that yellow circle on the title screen was supposed to be a star.

I think graphics like these might work for red giants or other dim stars, but in that case you'd want to include [limb darkening](https://en.wikipedia.org/wiki/Limb_darkening) rather than having the whole disk of the star a similar color.

**Comment by Amazinite** [comment]
_Casualy tosses onto back burner_

**Pull request closed without merging**
