### PR TITLE
Upload all the Steam depots when creating a release

### PR DESCRIPTION
**Pull request by quyykk**
## Feature Details

Creates all the Steam depot zips as part of the release workflow. Those zips can then be uploaded to Steam as-is.

## Testing Done

Not yet, but it should work (because I copy pasted 95% of it from a previous branch where I tested it)

### CODE REVIEW

**Comment by quyykk** [comment]
In the future we can comment them out to automatically push the zips to Steam

**Comment by MCOfficer** [comment]
Can you test this with a dummy release on your branch, please? Not too keen on this failing while we are releasing.

**Comment by quyykk** [comment]
https://github.com/quyykk/endless-sky/releases/tag/vSteam2

**Comment by quyykk** [comment]
I checked all the depots, and they're all correct :smile:

**Review by MCOfficer — APPROVED** [review]

**Pull request merged**
