### PR TITLE
Change the escort ships in FW Prisoner Parole, FW Prisoner Parole 2 and FW Southern Prisoners - Release so the escort ships are a new Prisoner Transport variant

### PR DESCRIPTION
**Pull request by AlbertNewton**
----------------------
**Content (Artwork / Missions / Jobs)**

## Summary
I scanned one of the ships that accompany you transporting prisoners in FW Prisoner Parole and found that none of them have a Brig - presumably this is because the missions were created before the Brig was added to the game. This was a bit confusing to me, so I created new Prisoner Transport variants of the Falcon and Blackbird and changed the ships in FW Prisoner Parole and FW Prisoner Parole 2 to these variants.

Now I have also made the same change to the Blackbirds in FW Southern Prisoners - Release, because this is also a prisoner transport mission.

## Save File
This save file can be used to play through the new mission content:
[Alfred Wells.txt](https://github.com/endless-sky/endless-sky/files/8578062/Alfred.Wells.txt)

## Testing Done
I reverted to Liberate Kornephoros, played through to the start of FW Prisoner Parole and scanned the escort ships. Then I played to the start of FW Prisoner Parole 2 and scanned those escort ships.

### CODE REVIEW

**Review by Zitchas — APPROVED** [review]
This looks like a good change, and it incorporates the Brig into the actual storyline instead of just being a random outfit that exists.

**Review by Zitchas — APPROVED** [review]
Still looks reasonable.

**Review by petervdmeer — APPROVED** [review]

**Comment by petervdmeer** [comment]
I'm not sure why GitHub shows 12 commits for this PR, while only 3 commits seem to be relevant.

**Comment by petervdmeer** [comment]
@Amazinite confirmed that if the diff looks good, then the squash-commit should also be fine.

**Pull request merged**
