### PR TITLE
Added a hotkey to clear the current ship target selection

### PR DESCRIPTION
**Pull request by guillochon**
I added a new command to the game that will clear the currently selected ship target, the hotkey preference has been added to the preference pane and a default value for the hotkey (the "backspace" key) has been set in keys.txt. I think this is a very useful keyboard shortcut to include.

Note: Originally there were some other unrelated changes in this pull request, I've closed the original request and submitted this replacement one.

### CODE REVIEW

**Comment by guillochon** [comment]
This one is now merge-ready I think, fixed some of the code formatting.

**Comment by endless-sky** [comment]
Pressing the "Select next ship" key already clears your target selection if your currently selected target has left the system, so basically the only situation where this would be useful is to avoid firing on a friendly ship. But, if there are any hostile ships in the system at all, you can just press "Select nearest hostile ship" instead, and if no hostile ships are present there is no reason you would be firing weapons. So, this really does not seem like a useful enough feature to merit its own key command.

**Comment by guillochon** [comment]
Actually it does not clear the target selection if a ship has left the system, it simply targets another ship (I just tested it).

**Comment by brendanjones** [comment]
Endless, where I think it's useful is if you're whipping through ship selections and go past the ship you want, clearing the selection and running through the list again can be faster than selecting next ship all the way through and then beginning again until you select the ship you wanted. Another implementation could be a 'back' button, to go 'back' through the ship selections, rather than 'forwards'.

**Comment by frameworld** [comment]
Shit+target alt+target...
Target&Backspace

When I select something with the mouse and press next target the next target is empty.

It is just difficult sometimes to select a planet without hotkeys or not accidentally click a friendly target and fire weapons by a key accidentally hit.
IRL weapons have a safety-switch.

**Comment by Pointedstick** [comment]
Here is a highly applicable and consequential situation in which a "clear target" key would be useful:

You're in the middle of a pitched battle above a planet that won't let you land, like a pirate world. You start to lose, and want to quickly bribe your way onto the planet. But in order to hail the planet, your target must be empty! And there are three dozen ships fighting! You die before you can cycle through ships quick enough to clear the target and hail the planet.

This just happened to me.

**Comment by jafdy** [comment]
@Pointedstick umm... you do know you can press SHIFT+T to talk to the planet don't you?

**Comment by Pointedstick** [comment]
Apparently I did not!

**Comment by BuildBruh** [comment]
What's the default bind for t? I have all my shortcuts set around wasd so
none of them are default.

**Comment by KiLEdEnNis** [comment]
@BuildBruh hailing to target ship/planet

**Comment by BuildBruh** [comment]
Ah, thank you.

**Comment by Bladewood** [comment]
I personally want this, because I am a, uh, rather trigger-happy player.

**Comment by KiLEdEnNis** [comment]
I use N & Shift+N to clear it (a little practise taught me)

**Pull request closed without merging**
