### PR TITLE
Update Tear of Skade outfit sprite

### PR DESCRIPTION
**Pull request by Anarchist2**
Self-explanatory.
image

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/28
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/239

### CODE REVIEW

**Comment by Zitchas** [comment]
Looks pretty. My one quibble would be that the shadows inside the box look a little dark.

**Comment by W1zrad** [comment]
@SpearDane thoughts?

**Comment by SpearDane** [comment]
> @SpearDane thoughts?

I am 100% happy with it.

**Comment by W1zrad** [comment]
Sounds good! @Anarchist2 - just need conflicts resolved, then merging time.

**Review by W1zrad — APPROVED** [review]

**Pull request merged**
