### PR TITLE
**Very** Scuffed Solution to Game Slowdown at Low Display Refresh Rates

### PR DESCRIPTION
**Pull request by Koranir**
## Fix Details
This PR makes it so that the game calculates a gamestep twice occasionally with monitors that have <60 frames per second (i.e. it will calculate the gamestep twice every frame at 30fps). This should stop the game from slowing down, at the cost of a pretty nasty stutter.

It's a very scuffed fix, and I just put this out as a option for people that really need it.

It does not apply to monitors with refresh rates at or above 60, and monitors with an fps that is a factor of 60 will also be smooth.

### CODE REVIEW

**Comment by Koranir** [comment]
Is this even needed? lol.

**Comment by quyykk** [comment]
> This should stop the game from slowing down, at the cost of a pretty nasty stutter.

I think slowing down is better than high stutter tbh.

**Comment by Koranir** [comment]
I'm pretty sure there is no stutter at 30fps, but I haven't been able to test that.

**Comment by quyykk** [comment]
I think we definitely want to try it out on an actual 30Hz display. I tried to limit my fps to 30 and it worked like a charm, except for fast forward which freezed the game (because it stopped drawing completely).

**Comment by Koranir** [comment]
I looked back through some pull requests and found #6316, which seems to do this but better.

**Pull request closed without merging**
