### PR TITLE
Content: add tribute fleets for the unfettered

### PR DESCRIPTION
**Pull request by Hurleveur**
Adds a tribute fleet for each of the 3 default Unfettered planets.
They would not accept tribute on the new ones; they don't even let you land there, and most importantly there isn't anything to tribute from there (yet), the Unfettered understand tribute as food, and money. In order to be considered serious you need to have a significant battle reputation.

I tried to not make the fleets too strong, they are all below remnant level of power.
Darkcloak is well defended being the shipyard and the point from where all ships go, to Wah Ki or to Wanderer space.
Warfeed is their only source of food, they will fight to the last to defend it. That fleet is there to defend the world against potential Korath raids.
Firelode does not matter much. It produces heavy metals but it being cut won't destroy the Unfettered. Furthermore, they do not expect an attack there, and even if there is one its not like there is much to defend, Unfettered are there to go raid (the food does not come from the world itself)

The tributes are not disabled during the war with the wanderers, although I could change that; the idea is that a lot of ships stay behind because of a lack of Jump Drives, and to keep the Hai at bay should they try something. The Unfettered never have to commit too many ships in the attacks on the Wanderers as of yet, and the smaller ships are more likely to stay behind.
I'm open to changes regarding the strength of the fleet and the amount of the tribute itself.

### CODE REVIEW

**Comment by Hurleveur** [comment]
Also just to answer a few questions one might have: why the Unfettered Hai and not all of the Hai? Why so much money (I'm thinking of increasing it honestly):
The Unfettered are a military oriented culture that respects strength, and is shown to do tributes on both the Hai and the Wanderers, so they full well know what it's about and approve of it.

**Comment by Zitchas** [comment]
As far as that goes, I'm good with pretty much everything having a tribute fleet, to be honest. They are already considered non-cannon, if it makes people happy to conquer stuff, well, good for them. 

As for the wanderer worlds, I'd say those should be tributable too; just they should have a rather low payout. Perhaps even pathetically so. They're a prime example of "highly valued, but not much of value yet."

That being said, tributable just means the player has the chance to beat up enough ships to get them to pay a token amount to the player to leave them alone, they're not actually being conquered. (otherwise the player could just loot the outfitter and shipyard, for instance)

**Comment by MasterOfGrey** [comment]
The issue I have with giving tribute fleets to the Unfettered, is that I can't see how that wouldn't put the Hai on a war footing with you.

I know it's "non-canon", but my understanding was that the aliens don't generally allow tribute because their governments are more centralised and have more integrated responses to external threats (compared to the human worlds that are largely quite autonomous).

This would seem to break from that general status quo.

**Comment by Zitchas** [comment]
Well, I don't think the Hai are any more centralized than, say, the Deep. And given our lore, the same logic would make Paradise worlds untouchable because tributing one of them should get the entire Republic up in arms, given how the Paradise world's influence over the Navy is kind of central element of the story.

**Comment by warp-core** [comment]
> Well, I don't think the Hai are any more centralized than, say, the Deep. And given our lore, the same logic would make Paradise worlds untouchable because tributing one of them should get the entire Republic up in arms, given how the Paradise world's influence over the Navy is kind of central element of the story.

Demanding Tribute from a Paradise world, or any Republic world ffor that matter, does make the "Republic" government (the Navy) hostile to you.

**Comment by Zitchas** [comment]
Yep, but I think what MasterofGrey is talking abouta *co-ordinated* effort. Like the Hai mounting a proper warfleet and centralized organization to specifically track down the player. Which, I'm arguing, the Navy is just as likely to do for the Paradise Worlds; or the Deep/Syndicate for themselves.

**Comment by MasterOfGrey** [comment]
> Yep, but I think what MasterofGrey is talking abouta _co-ordinated_ effort. Like the Hai mounting a proper warfleet and centralized organization to specifically track down the player. 

Indeed

> Which, I'm arguing, the Navy is just as likely to do for the Paradise Worlds; or the Deep/Syndicate for themselves.

Maybe they should lol.

**Comment by Hurleveur** [comment]
The Unfettered would not want the Hai to get involved in it at all. All it is is a little money given to the player as a token of respect, and a teat of their strength.
For the new worlds they're limited on ships and busy fighting a war so actually makes more sense if they ignore you.

**Comment by Hurleveur** [comment]
If you were to seriously consider bombarding those new worlds it'd be war.
Not the same kind of "well I guess we'll send these ships we have here" that happens with the "old worlds", where they have plenty of ships anyway, and are anxious to be put to action but the "lets let them think they have the tribute, regroup and crush them with the entire military because we can't afford to lose any ships here" kind of response.
The Hai should war you as well at that moment, heck even the wanderers should hate you for it. The Unfettered don't let you land on those new worlds, whatever you may do, they don't give you the time of day there.

But since tribute is non-canon nonsense kind of thing I can't really make that kind of response happen, so let's wait for a decision being reached on tribute having consequences or not before making the new world tribute-able.

**Comment by Amazinite** [comment]
While tribute is an underutilized system, I think it's rightfully so. Having unfettered (no pun intended) access to land on any planet that you're able to tribute doesn't lend itself well to storylines where it's expected that you don't have landing access. There's also issues like #7663 which make even less sense if you've conquered planets but you're still getting job offers from them. Now perhaps in such cases we should tweak the conditions on the missions as to not have them offer or to force relinquish tribute (#5448) and prevent future tribute from being gathered, but that just becomes a big headache to have to deal with something that normally we don't have to worry about. That's why we sometimes say that tribute is "non-canon" because of how it absolutely breaks the story and causes nothing to really make sense. I've thought of expanding tribute to other factions in the past, but because of these issues, I feel like we're better off just keeping tribute where it is and then maybe in the future revisiting the concept entirely. (Future mechanics like what's been mentioned in #7684 would help with this.)

**Comment by Zitchas** [comment]
> On the flip side we could just go down the route of giving everything tribute and saying making it clear, "If the game gets weird being this point, it's on you."
👍

Tributing is right up there with:
- If you show up with a alien heavy warship when the game expects you to probably still be flying a human interceptor/light warship, it might not make as much sense.  
- If you show up with 200 shield beetles, the story *might* not make as much sense. For that matter, if you have a fleet of hundreds of ships, regardless of what they are, the story might have some flaws.
- The game stops making a whole lot of sense economically when the player has a bank account measured in exponents because it overflowed past however many billions that takes.
- Likewise for the economy, when one has a hundred+ deep rivers in a giant fleet, it raises some lore concerns with how a lot of planets can even handle *landing* that many simultaneously, let alone servicing them all.

**Comment by SimulatedKnave** [comment]
The only things I ever tribute are pirate planets, because the outlandish bribes they request while constantly attacking me are ridiculous. 

I think it makes some sense as you demanding landing rights, them going "nah," and you showing that no, you can land where you please. 

Being able to land on pirate planets without constantly being a pirate or having a specific mission to go there needs to be an option, IMO. So whatever is done (if anything), it shouldn't remove that. And I WOULD lump the Unfettered in with pirates on this point to at least some extent.

**Comment by Hurleveur** [comment]
I wanted to make this canon, but I didnt here, no missions are linked to it.
Also the Unfettered are hostile to you if you land by tributing or by paying a bribe and most jobs would always offer regardless (and selling a JD forgives the tribute, as it should) hence I dont see that as an issue.

Here tribute does not matter much, it's just a token of respect from the Unfettered, if anything yes the rest of the game's tribute makes little sense but this one does and no missions will need to be changed because of it.
All aliens should not be getting tributable just because the Unfettered are, they are special: they respect strength and use tributes a lot.

**Comment by SimulatedKnave** [comment]
Indeed, the Wanderer fluff notes several times how once you manage to land on the Unfettered planets, hospitality rules mean they will leave you alone. Suggesting that it is possible to do so. 

It makes more sense that you can intimidate them into letting you land then that they can constantly extort you for money to do so.

**Pull request merged**
