### PR TITLE
Jump Cruisers now have Catalytic Ramscoops.

### PR DESCRIPTION
**Pull request by Lineth**
Makes long-range travel (like for the "Hunt the Alpha Base" mission)
less annoying.

### CODE REVIEW

**Comment by Bladewood** [comment]
What about jump dreadnoughts and jump carriers?

**Comment by toilethinges** [comment]
And, have you made sure the Jump Cruiser has enough outfit space for it?

**Comment by Lineth** [comment]
This was primarily just for the Alpha Base mission, as Danforth's ship is not specified, just that it's a 'jump' version of the Navy Cruiser.

**Comment by Bladewood** [comment]
...wait.
Jump cruisers DO have ramscoops!?

**Comment by Lineth** [comment]
Only the crappy normal ones, so when you get to this point and are using Catalyst or Wanderer scoops (or even Quarg Antimatter Cores if you have the Quarg Military Retaliation plugin) they might as well not be there its so slow.

**Comment by Lineth** [comment]
I guess this isn't being pulled, then?

**Pull request closed without merging**
