### PR TITLE
Corrected spelling errors within data folder

### PR DESCRIPTION
**Pull request by guillochon**
Attempting my first pull request with endless-sky. Went through all of the .txt files in the data folder and corrected a number of spelling errors. Also corrected small error in SDL install instructions.

### CODE REVIEW

**Comment by naehc** [comment]
Benefitted and whisky are not misspellings as such, see e.g. http://www.thefreedictionary.com/benefitting / http://www.thefreedictionary.com/whisky. Which is preferable is partly a matter of region, e.g. whisky is the more common variant in British English, and vice versa in American English.

**Comment by guillochon** [comment]
Should the game conform to British or American English? I think it should be one or the other, and if so, American would be preferable just because the vast majority of the text uses American spellings. Both "benefiting" and "whiskey" are the more common American spellings.

**Comment by naehc** [comment]
Agreed, applying one standard consistently is the better option, and yeah, the game is probably 99.9% American English already. 'Whisk[e]y' is not as simple a case as e.g. colour / color though, as in a given case it depends more on the region of the product than on the region of the language. That is, any Scotch whisky is never whiskey, and any Irish whiskey is never whisky etc... so, the correct spelling would depend on the particular tastes that the writer intended for the character[s]? ;) Benefitting is easier, albeit still a bit odd, since it's American English which considers it acceptable, while British English doesn't (at least, Merriam Webster does, and Cambridge doesn't).

**Comment by guillochon** [comment]
FYI I've divorced this pull request into its own branch and created a new pull request using the new branch, https://github.com/endless-sky/endless-sky/pull/305

**Pull request closed without merging**
