### PR TITLE
updated ship name from "world-ship" to "echo-galleon"

### PR DESCRIPTION
**Pull request by drewbowering**
**Content (Missions)**

## Summary
I noticed that the name of the ship in this mission hadn't been updated from "world-ship" with the new name, so I've changed it.

### CODE REVIEW

**Comment by Saugia** [comment]
If we do end up changing this, make sure to capitalize it as "Echo-Galleon".

**Comment by EjoThims** [comment]
Agree with @Saugia above, if others do think this is confusing enough to go ahead and change.

But I don't think this actually should be, and I'm pretty sure it was in fact left this way deliberately. Even though they all have proper names now, Echo-Galleons are still "world-ships."

The same way Airbuses are still "planes" and Abrams are "tanks."

**Comment by ravenshining** [comment]
That was indeed the intention; the idea being that the wanderers get an incomplete translation and wind up just generally referring to large Korath ships as (lowercase) "world-ships."  Same idea with the raider, also left deliberately lowercase; basically anyone unfamiliar with the Korath refers to a ship smaller that the world-ships as "raiders."

**Comment by drewbowering** [comment]
This makes sense, thanks for clarifying!

**Pull request closed without merging**
