### PR TITLE
Changed some words

### PR DESCRIPTION
**Pull request by warp-core**
Changed `You bring your ship to a gingerly landing...` to `You gingerly bring your ship in for a landing...`

### CODE REVIEW

**Comment by Bladewood** [comment]
To note, "gingerly" is apparently usable as both an adjective and an adverb. https://www.merriam-webster.com/dictionary/gingerly

**Comment by warp-core** [comment]
Hmm. I've not encountered it as an adjective before. Based on that usage, there's nothing wrong with how it is now beyond opinion on what sounds better or is easier to read.

**Comment by Zireael07** [comment]
I've never seen it used as adjective either. I believe the changed wording is much more understandable, especially to non-native English speakers.

**Comment by jafdy** [comment]
The new version reads awkwardly to me, perhaps `You gingerly bring your ship in for landing...` or `You gingerly bring your ship in to landing...

**Comment by endless-sky** [comment]
This has been discussed before (#1653). It's perfectly valid usage as it is (e.g. the [four examples](https://en.wiktionary.org/wiki/gingerly) of adjectival usage on Wiktionary).

**Pull request closed without merging**
