### PR TITLE
Remove accidental white supremacy from White Sun

### PR DESCRIPTION
**Pull request by Galaucus**
Turns out that the energy generation on this is 1488, which paired with "white sun" is fairly sketch. This is a very minor tweak that makes the reactor not-Hitlery.

This changes the regen/sec from 1488 to 1485.

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
Can we buff it instead to 1502?

**Comment by Galaucus** [comment]
> 
> 
> Can we buff it instead to 1502?

That would be 25.033 repeating, which is kinda' awkward.

**Comment by MasterOfGrey** [comment]
> > Can we buff it instead to 1502?
> 
> That would be 25.033 repeating, which is kinda' awkward.

1501? I think better to buff slightly and get clear away from it than tweak a nerf.

**Review by petervdmeer — APPROVED** [review]

**Review by Zitchas — APPROVED** [review]
The current modified value of 24.85 results in 1491. Unlike the previous 1488 number, 1491 has no hits when searched for in conjunction with "white supremacy," and instead turns up mainly historical info related to events of 1941 and a book on the subject. 

It also turns up a native american sketch comedy troop "Their comedy sketches depict contemporary Native American life in the United States, using humor and satire to explore issues such as stereotypes and racism (internal and external), tribal politics, and the conflict between tradition and modernity." (copied from wikipedia).

In terms of breaking up the triple set of white supremacist references, I think this should be adequate (and kind of appropriate too).

**Pull request merged**
