### PR TITLE
refactor(balance,content): Reduce size of  X1700 & X1100 by 1

### PR DESCRIPTION
**Pull request by Zitchas**
**Bugfix:** This PR addresses issue #6624 

## Fix Details
This reduces the size of the X1700 and X1100 (the smallest ion thruster and the ion reverse engines) by 1.

This changes the thrust per ton from 1350 up to 1440. This boosts it up from slightly below the Fusion engine to just above the Fusion engine.

## Expansion

Since the point of this was to make it possible to have Heavy Shuttles with reverse engines, I went ahead and added a "Reverse" variant of the Heavy Shuttle. It is, quite simply, the stock Heavy Shuttle with a X1100 reverse engine. No other change. This variant was then added to the Small Southern Merchants and Small Core Merchants fleets; so now it will appear now and then out in the wild.

## Thoughts
While increasing the Heavy Shuttle's weapon capacity up by 1 would be open up a variety of combat options for the Heavy Shuttle (which I don't think would be a good thing), instead reducing the size of the smallest ion thruster and its equivalent ion reverse thruster also enables it to use reverse thrusters, which I think is a good thing. This doesn't increase the performance ratio of this engine enough to be meaningful, but the very slight decrease in size increase the possibility that these (especially the reverse thrusters) could be useful in a few more places.

These are, after all the absolute weakest thrusters in the game, in terms of both absolute thrust and thrust per ton. I don't think it negatively impacts game balance to make them slightly smaller, and thus faintly more useful.

If the fact that it now becomes slightly more thrust per space efficient than the Fusion Drive is a problem, the later can be reduced by 10 (from 480 down to 480), which brings its thrust per space from 1425 to 1455, which re-establishes it in its current 5th worst place overall standings for thrust-per space (it, along with the worst, second worst, and third worst are all engines with both thrust and steering).

## Testing Done
Played around with a few test configurations.

## Save File
No special conditions required - see any outfitter that has the X1700 and X1100.

### CODE REVIEW

**Review by EjoThims — APPROVED** [review]
I know there are a lot of ships specifically designed around being just a bit too small for certain engine combos, but don't think Heavy Shuttle is one of them, and I agree that making the matching pair one smaller is better than giving it one more space.

I'm not sure this is really a -needed- change, but I emphatically think it is a positive one, especially considering it's low overall impact to balance while still providing a nice early variety factor in otherwise easy to overlook starting ships, both to use and as background world.

I don't think the Fusion Drive adjustment would be out of line either, but it should be a separate PR, imo.

**Comment by tehhowch** [comment]
Why is the engine being made universally better when the stated purpose is to make it fit in ship X?

If _making it fit_ is the purpose, then reduce the stats as well.

(Note that the engines are not "broken" or "misbehaving" just because they don't fit in ship X, so the PR does not _fix_ anything. It is a change for some other purpose)

**Comment by 3519421** [comment]
This is a very nice tweak for anyone wanting to mess around with low-end Human ships and outfits. Outside of combat, merchant vessels can be made to run on shockingly low energy levels if a reverse thruster is included (much less burn time on main thrusters and steering), and this change makes the difference between "do I remove one solar panel and risk running out of power, or give up this cargo/bunk/fuel/brig" for a whole range of small freighters and transports. It allows for a lot more variety in the non-combat side of things.

**Comment by Amazinite** [comment]
Doing a balancing pass on engines is my plan for the first piece to break out of #5779, so I'd say it'd be better to just close this and keep this idea and #6624 in mind when going over all engines.

**Comment by Zitchas** [comment]
If merging engine changes in is something happening in the near future, then sounds great. If it is going to continue in the "something on your list for the indeterminate future", then I would prefer to have a discussion here about the merits of this slight change to the balance; with the view of merging this without waiting for the engine pass.

**Comment by Hurleveur** [comment]
I personally can't stand engines that don't fit and just change the stats in frustration.
But I think maybe it would do best to do as tehhowch suggests and not change the actual thrust by unit of this one engine piece without real context, as Amazinite said. So maybe we could just accept that it stays the same ratio and leave the true balancing for later, with all other engines?

**Comment by Zitchas** [comment]
We could, yes. My argument, however, is that this thruster is so inconsequential to the game that there *is* no balance consequences. As pointed out, the change isn't enough for it to even come close to the next best thruster. And as is, we're talking about the absolute worst two thrusters in the game, no matter which metrics you use to compare them. I don't foresee any problems arising because of this. No-one is using these to make OP ship configurations, after all.

**Comment by 3519421** [comment]
"No-one is using these to make OP ship configurations, after all."

In fact, I've been using them to make horrendously-underpowered but still spaceworthy merchies. The only reason they don't get shot out of the skies constantly is that they spend so very little time in normal-space in any system other than take-off and landing. We're talking "one or two solar panels and a capacitor, no shield generator, no weapons, maybe a radar jammer if it fits". I skip out on the standard thrusters, so my flagships literally ride the residual velocity from hyperspace to make a landing. Autopilot chokes on that setup, so if it misses the target or I get shot at, it's time for some fiddly maneuvering. Here's my favorite early-game clown car WITHOUT the scaled-down engines:

S1647718366

Aside from making a reverse engine fit into an unarmed Heavy Shuttle, this mainly gives the option of fitting in a Small Radar Jammer, Brig, or Chasm Battery without yanking out one of the KP-6 Panels in other tiny low-tech, low-performance ships.

**Comment by Zitchas** [comment]
This is exactly the sort of thing I think this favors, and is worth including on its own without forcibly waiting for it to be possibly considered as part of a larger thruster review in the future. While keeping optimization hard for the "maximum OP" end of the thruster power spectrum, I think it serves a valuable purpose to make life a bit easier for the "radically un-optimal" end of the spectrum. After all, it promotes greater variety of configurations.

**Comment by Amazinite** [comment]
Like I said, I'll tackle engines as a whole.

**Comment by Zitchas** [comment]
Could you provide a timeline? If your engine rework is getting PR'd tomorrow (or even sometime in the next week), then great. If, on the other hand, it's just something that's hoped to be PR'd sometime in the next few months or indefinite future, then no, this can be discussed and possibly merged here in the present on its own merits, and then changed accordingly by the engine rework whenever that happens.

A holistic fix-everything big balance rework of the whole ecosystem would be great, but I see no reason why we can't piecemeal the balance into slightly better shape in the mean time.

**Pull request closed without merging**
