### PR TITLE
Shore leave button

### PR DESCRIPTION
**Pull request by Pallington**
Proposed idea for a button to skip 1 day and refresh missions, etc. without departing and returning.
I don't know how to do all the other coding behind it though. Just an idea.

### CODE REVIEW

**Comment by Bladewood** [comment]
> Flagship avatar

**Comment by Pallington** [comment]
Flagship avatar indeed. Well spotted.

**Comment by jafdy** [comment]
Taking off and landing immediately will skip one day.

**Comment by MessyMix** [comment]
>without departing and returning

@jafdy I think he gets it, but he either wants a) no crew salaries (a "shore day" is like a break, I would assume) or b) the convenience of not needing to go through such a hassle.

Which, I think, is a good idea provided that it doesn't clutter the interface.

**Comment by Pallington** [comment]
Quality of life change. I'll try to do the rest of the coding.

**Comment by gunqqer** [comment]
So you could just do with with your FW moniez and get rich by doing nothing?

**Comment by EndrosG** [comment]
Spaceport authorities should charge something (extra) for blocking a landing pad.

**Comment by Nechochwen-D** [comment]
As it is crew are automatically paid whenever the day increments so they would still be paid. I can however see adding o feature to "load more" missions without incrementing the day.

**Comment by MessyMix** [comment]
@EndrosG no, you're parking the ships. You don't pay upkeep for parking ships on planets. That shouldn't be the case here.

@Nechochwen-D again, when you park your ship, you don't pay your crew. I think it works as-is, imo.

I support this feature, so long as it doesn't interfere with the minimalist UI.

**Comment by tehhowch** [comment]
One's entire daily salary income could be spent on "lodging"... After all, "shore leave" means you aren't sleeping in your cramped crew quarters for a night 👍 
Example ticker message:  
`You receive <exact_monies> in salary and tribute payments, and spend it all on your <adjective> <noun>.`
\<adjective\> and \<noun\> would be chosen such that they match the planet you are staying on (e.g. "lavish hotel room" if in a paradise world). Some planets could define no-shore-leave, e.g. military outposts, uninhabited, hostile government....

**Comment by EndrosG** [comment]
@MessyMix that was meant as a joke ;-)

**Comment by MessyMix** [comment]
@EndrosG flew right over my head.

@tehhowch could work, although players might start demanding the ability to not spend their money on lavish hotels. :P

**Comment by Pallington** [comment]
Never thought this idea would get this far. Now, we are parking in a spaceport so perhaps do charge some amount of money?
Also, what do you mean by FW money?

**Comment by MessyMix** [comment]
@Pallington it hasn't gotten far, we're just brainstorming here.

By FW money we mean salary and/or tribute.

**Comment by Pallington** [comment]
It's gotten farther than I thought it would.

Besides that, still no idea how to make the button pass a day but here goes!

**Comment by endless-sky** [comment]
This seems really unnecessary. It would clutter up the UI with an out-of-place button that many players wouldn't use, and it would encourage a game-play style where there is a lot less variety and random chance involved in what missions you take on.

**Comment by Elyssaen** [comment]
Definitely agree about the UI if it creates a fifth row on either column. Two alternatives that would be a little easier on the eyes are:

1. A "Wait" or "Shore Leave" button in the centre top of the planet pane, above the image.
2. Add buttons inside the Spaceport Bar, that appear in the central box above or below the description. This would have to go with a larger expansion of Spaceport Bar, perhaps adding a few other activities either at the same time or later.

Personally, I don't think there's anything wrong with the impact on gameplay style. Player who want to refresh the mission list are going to take off and land anyway. I don't think there should be any change to how your finances are handled as the day advances this way, though: no break on crew payment, no free for storing an unparked ship. That seems like extra work that doesn't add to what you're trying to achieve.

**Comment by KiLEdEnNis** [comment]
if anything, a hidden hotkey, if it's even worth it

**Comment by Bladewood** [comment]
No, a hidden hotkey would not work with this. A player who would accidentally hit that key would be so very confused by the silent timeskip.

**Comment by Pallington** [comment]
Expanding the spaceport bar to have a button for this does currently seem like the best idea. Or, you could have it fitted to have pressing the spaceport button two or three times trigger a pop-up.

**Comment by endless-sky** [comment]
I don't really like the idea of intentionally adding a feature with the sole purpose of encouraging the player to scum for good missions.

**Comment by Pallington** [comment]
Although, if the player really wants the most lucrative missions those would be timed ones, AKA ones that you can't afford to scum much on, and otherwise he wants to scum as little as possible since you could be making more money instead of wasting days for missions.

**Comment by endless-sky** [comment]
Yes, so this basically encourages a behavior that's not even beneficial in the first place.

**Comment by Pallington** [comment]
but it doesn't necessarily encourage the behavior either - button that's hidden away means that you don't want to spam nearly as much, but can still do it if you need to.
Besides, it's a tradeoff, as if the planet has literally no missions that are anywhere near where you want to go, it's beneficial, but it can't be overused.
Also, if it didn't skip only one day would be nice (slider/enter number of days to skip)

**Comment by Elyssaen** [comment]
I think part of the reason I kind of _like_ this is that I like some other feature ideas that would need this. For instance, I'm really not sold on the 'free' escort travel, and would support each escort only being able to go one jump one day. For that to work, you'd need to be able to land and wait a number of days.

But on reflection, with things as they are, I guess MZ is right. All this really does for now is refresh the mission list. @Pallington, you mention a slider for number of days... when would you ever actually do that in-game? To fast forward through the Free Worlds campaign break? To zip forward through 100M credits of salary?

**Comment by Pallington** [comment]
@Elyssaen FW salary is easy to nerf
For now, perhaps the slider isn't useful - it's futureproofing, and as is obvious, if you're never gonna add on to it there's no point in futureproofing.
Also, free escort travel _does_ seem sketchy.

say, what if we added something to do during shore leaves?
I suggested nothing kappa

**Comment by EndrosG** [comment]
I dont see good points for many days at once.
You wont have a super-long mission list with e.g. the mission offers of 14 days combined into one list.
Thus, this will not help you acquiring lots of missions towards a specific destination or region.

Also, that entire shore leave would really have to be handled internally like a complete takeoff() + landing(), because each day an event can happen which alters the planet you are landed on. Examples:
- the shipyard on Geminus gets destroyed, later it gets rebuild
- the spaceport on that one Wanderer planet gets destroyed by the Alpha driven Kor Sestor fleet (well, you wont be there when this happens, but anyways)
- plugins can always add shipyards or outfitters to planets which did not have any before, or remove all of them.
- technology introduces new outfits


Personally, I would prefer to launch, mine some asteroids, harvest the floatsam, and then land again = make some profit - if I were in a situation where I would want to skip a day.

**Comment by Pallington** [comment]
Not everyone wants to mine
Plenty aren't in a good situation to mine, aka might be in a poor system for mining, don't have enough cargo space or weapon slots, or just aren't cut out for it. And/or they want to skip a day quickly because they don't have the time to screw around with flying inertially or taking off and landing with a slow cargo ship.

Which is where the button comes in.

**Pull request closed without merging**
