### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by Wrzlprnft**
Typo fixes
http://steamcommunity.com/app/404410/discussions/1/458607699619757456/#p1

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
Additionally, the modified argosy variant (Laser) has no lasers, but blasters on it.

**Comment by jmhorjus** [comment]
All good finds. :)  I read all these missions without catching these.

**Comment by Wrzlprnft** [comment]
I do not catch them myself, i got a "supplier" in the steam forum :)
Next time i try to get all these into one single commit. Once i fix my computer problems.

**Comment by Alkallid** [comment]
But were the Modified Argosy variants (Laser and Heavy) fixed?

**Comment by Wrzlprnft** [comment]
yes, see commit c19f299b0d9b71aca14f2deb8f2055bc7050472d

**Pull request merged**
