### PR TITLE
Correcting the Mule as a Heavy Freighter

### PR DESCRIPTION
**Pull request by Zitchas**
This update corrects the Mule:
- Changed classification to Heavy Freighter
- Changed description to indicate that the Republic officials were tempted to classify it as a warship instead of actually *being* classified as a warship.

Just to be clear, NO STATS ARE CHANGED, only the label and a slight wording change in the description

These changes bring the mule in line with the Behemoth (which has more hull, more shields, and more weapon space than the mule) and the Bulk Freighter (which also has significantly more hull and somewhat less shields (but still more combined health) and as much weapon capacity as some medium warships and more than most.). To a lesser extent, this also brings it in line with the Argosy, which has more hull, shields, and weapon space than many light warships.

One of the reasons for this change is to increase the number of options for players who wish to play as merchants who happen to be good at combat. It is hard to pretend to be a merchant when one is flying a heavy warship, no matter the justifications. Thus this change reclassifies the mule as a heavy freighter, and modifies the description to give it some ambiguity: It is more interesting to look at the mule and see how regulators might have classified it as a warship; rather than to look at it and see a subpar warship that only barely made it into the category.

Also, while what the regulators term a warship may have been relevant back when licenses for warships were a thing, now that they are not, keeping the mule as a warship simply muddies the waters and hides a ship that merchant players may wish to fly in a section where they might not look when comparing freighter capacity.

### CODE REVIEW

**Comment by Zitchas** [comment]
This change also facilitates #4347 .

**Comment by Nescio0** [comment]
Why not a transport? Both its number of free bunks (43-6=37) and the bunks to crew ratio (43/6) are superior to several other transports.

**Comment by Zitchas** [comment]
Primarily because its description revolves around being used as a freighter. Nowhere does it mention that it was designed for or intended to be a transport. It just so happens to be decent at being one.

In terms of "what ships are classified as" I am concerned primarily with the lore of the game and what they are intended to be.

**Comment by Nescio0** [comment]
To clarify, I'm not opposed to the change per se, I'm merely wondering as to why.
You state it's because of lore, however, the lore (description) makes it immediately clear the ship is classed as a warship, because of its shields and weapon capacity.
Classes are arbitrary, but to me this patch seems to change something slightly problematic into something else slightly problematic, i.e. no real improvement, so why change?

**Comment by Zitchas** [comment]
The main reason is that the original intent behind the classification was so that a ship with a certain amount of combat capability would be locked behind a license that had to be purchased, like EVN and EVO did. Just to be clear, in EVN/EVO these were purchased licenses that basically amounted to "you can't buy a warship until you pay the license people 150k for a warship permit" (I don't know what it was actually like in ES, though.)

Subsequently, licenses were deemed too annoying, and were removed. Now that there is no reason to restrict ships based on combat capability within "warship" licenses, I feel that it would be more appropriate to sort ships based on their intended purpose, thus allowing the various warship categories to actually be just those ships that were specifically designed to be warships, and not clutter it up with ships that aren't really warships but are classified that way because they have a bit too much shield/hull/guns/whatever. 

This change also makes it easier for new players to understand the ships, as they can peruse ships based on what they are looking for (say, a freighter), and can then note that this ship, which is primarily intended to be a freighter, also happens to have very good transport and combat capabilities. I feel this is more intuitive than forcing players to focus on the warships and try to pick out which one makes the best freighter.

After all, ES is largely a space-combat game. Combat capabilities are relevant for *every* ship. As such, we should sort the main categories based on their intended purpose, realizing that every category is going to have at least a few and possibly many ships that have some degree of combat capabilities.

**Comment by Pointedstick** [comment]
Frankly I would also support reducing the Mule's combat potential a bit, like halving the number of gun ports or making it a bit less maneuverable. That would make the classification change a bit more sensible.

Of course that's a larger more controversial change. :)

**Comment by petervdmeer** [comment]
> Of course that's a larger more controversial change. :)

Small steps, one at a time; let's just first merge the current change here. It is just sufficiently non-controversial to have a chance to get merged somewhat quickly.

**Comment by finite-galaxy** [comment]
In my version I removed one gun port from the Bactrian (from 4 to 3) and Mule (from 2 to 1).

(Also, because freighter/transport/warship (and what about carriers?) is rather arbitrary, I replaced ship categories and based them solely on total mall (hull mass + outfit size + cargo space). I'm not implying you should do the same, though.)

**Comment by finite-galaxy** [comment]
In my version I removed one gun port from the Bactrian (from 4 to 3) and Mule (from 2 to 1).

(Also, because freighter/transport/warship (and what about carriers?) is rather arbitrary, I replaced ship categories and based them solely on total ship mass (hull mass + outfit size + cargo space). I'm not implying you should do the same, though.)

**Comment by Tadrix** [comment]
The Mule is the best medium warship (installable firepower and durability-wise), yet faster than heavy freighters and with a small crew; its cargo space also isn't that big. It shouldn't be classed as a heavy. If anything, the Bastion's closer to that.

**Comment by Zitchas** [comment]
I'm happy with the content of the discussion, and I continue to think it is a good change.

I personally like the idea of reducing both the Mule's and Bactrian's combat potential slightly, but that's for another merge & discussion. For now, I'm good.

**Comment by Tadrix** [comment]
I'd say hold off this change till there's a need for Medium Freighters, and then class the Mule as them. It doesn't have enough of cargo capacity to be a heavy.

(For the purposes of Pointed being merge-happy, consider it a hard objection.)

**Comment by Amazinite** [comment]
The Bastion also has the same justification in its description for why it's classed as a warship instead of a freighter. Given that both the Mule and Bastion mention this, it's clear that this is part of the lore of how ships are categorized, at least in human space, and I don't agree with retconning that just because. 

I can't really get behind the reasoning for this change.
Re: The Behemoth being bigger than the Mule. The Behemoth has less HP than the Vanguard, which is the weakest heavy warship. This harkens back to the idea of making the Mod Argosy a medium warship; if you make the change, then it just moves from becoming the biggest heavy freighter to the smallest heavy warship, just as moving the Mod Argosy would change it from the biggest light warship to the smallest medium. Ignoring the Bactrian, the Behemoth has nearly 5x more cargo than any human heavy warship, which fits with the current idea of ability over purpose in categorization.
Re: Number of options for merchant players. Your loss if you aren't checking the other categories for potential ships to use. I don't see the use of the Mule as immersion breaking in this regard given that its description even highlights this oddity about it. If I was someone who only wanted to play with freighters but bought myself a Mule, I'd realize that I was teetering on the edge of what it means to be in a freighter. Same goes with the Bactrian. A freighter wants lots of cargo but also wants to be well armed to defend itself, and the Mule and Bactrian get into the realm of "how well armed can a freighter be before it's no longer a freighter?" 
Re: Category licenses aren't a thing anymore so it should be changed. While category licenses were removed for gameplay purposes, it's important to note that they are still mentioned in game as a reason for the FW leaving the Republic, so they still have some bearing on the lore. But even if the reason that the Bastion, Mule, and Bactrian were originally classed as warships was to keep them behind more expensive licenses, we still run into the purpose versus ability argument as to if we should change the categories around. In terms of ability, the Bactrian, Mule, and Bastion are closer to the warships that they are categorized as, even if their purposes lean more toward being freighters/transports/what-have-you.

**Comment by Zitchas** [comment]
Given the feelings and support that this issue has, I would like to propose that we (I) close this issue and at some point in the near future we have a broader discussion on how exactly ships should be classified, and then to a full pass through the whole set of ships. Humanity in particular, but there's a few oddities among the aliens too.

**Pull request closed without merging**
