### PR TITLE
Add remodel of the Splinter

### PR DESCRIPTION
**Pull request by JanErikAhrens**
## Summary
Remodelled the Splinter and its marauders and changed the image files and hardpoints accordingly.

splinter6

splinter7

splinter11

splinters

(These images are from the first commit and thus no longer up to date.)

## Save File
This save file can be used to see the new ships in-game:
[Aaron Zuhl~Splinter.txt](https://github.com/endless-sky/endless-sky/files/8049928/Aaron.Zuhl.Splinter.txt)

## PR Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I uploaded the necessary image, blend, and texture assets here: [Google Drive](https://drive.google.com/drive/folders/1CsWiTjYyRmCTvwIWVlG-zqFz8y1A0cEq?usp=sharing)
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/208

### CODE REVIEW

**Comment by Saugia** [comment]
You should get some Syndicate color images for us too! It'd be awesome to see them in their own environment.

**Comment by Hurleveur** [comment]
Maybe show comparison with the old one? To show the improvements you made (I really like how it looks!)

**Comment by MasterOfGrey** [comment]
Oh yay! Now it actually looks like a ship instead of a conical fractal. Nice. :)

**Review by Amazinite — CHANGES_REQUESTED** [review]
Not a fan of the cockpit. It has the same issue as the Navy remodels where you're shrinking the details of it. From the thumbnail perspective it looks fine, but from the top-down perspective you've gone from having this very recognizable section of the ship that is the cockpit to having this small sliver of windows.

That doesn't mean we can't get a bit fancy with the cockpits on these remodels, as the cockpit on the Raven remodel you did is different from the norm, but with that remodel the cockpit is at least still easily recognizable from the top down perspective.

Similarly to the cockpit, the guns don't feel as pronounced. They're definitely thicker on the old model. The up-armoring on the new Marauders also isn't as significant as the old ones. Maybe the old ones went overboard on the greebles, but I feel like the new Marauder models could definitely use some more work around the front to make them look more up-armored. (And in hindsight, maybe the new Marauder Ravens could use a bit more work too. Again, not nearly as far as the old models, but could definitely reach some middle-ground between the two.)

I also feel like the thumbnail angle might be a little off as the ships are looking a little smaller, but that might just be a matter of the new model itself.

Aside from all that, looking pretty good. I'd say the Splinter is definitely my least used human ship, but I might have to give it a spin after this.

**Pull request merged**
