### PR TITLE
Make campaign missions offer more consistently

### PR DESCRIPTION
**Pull request by Anarchist2**
## Summary
Right now, at 0 CR, it takes ~4 times rolling the spaceport to find the first FW mission. This doesn't seem that bad on the surface, but when considering the smaller size of FW space, the relative difficulty in reaching it and how newer players check the spaceport less often, most players will often leave FW space before getting offered any FW mission.

In order to help hook players onto FW, this PR increases offer rates for the FW intro missions across the board. Also affected are Mystery Cube jobs, which have been made more likely (and now have a no-threat, no-CR version) in order to make it easier to get enough cubes to start the Bactrian quest, as it is somewhat likely to have no cube jobs be offered.

An alternative to upping every offer chance is to make one of the missions (probably FW Recon) always offer, and use that mission as a way to inform people about the campaign, but that method can still end up forcing players to keep relanding for a while to force one of the missions to offer.

### CODE REVIEW

**Comment by Zitchas** [comment]
Another idea: it might be good to leave the random chance as is - but have somewhere ( the capital or HQ for the relevant faction) have a guaranteed offer chance.

**Comment by MasterOfGrey** [comment]
> Another idea: it might be good to leave the random chance as is - but have somewhere ( the capital or HQ for the relevant faction) have a guaranteed offer chance.

I would back this approach. 
One of the things I found particularly appealing about the early game was that the campaign didn't shove itself down your throat while I was exploring and learning my preferred playstyle.

**Comment by Hecter94** [comment]
I'm not sure how strictly necessary this is given that the current difficulty in accessing FW is simply because only one of the three main campaigns is finished, and not any issue with the FW campaign itself. 
I feel as though changing FW to fix an issue that's unrelated to FW isn't entirely appropriate. 

Once those campaigns are added, this change will be out of line with the other campaigns or will be far too much if all of the campaigns are this common and easy to trigger. 

Is the intention here to use this as a temporary solution until the other campaigns and stories are added? If so, is this such a pressing issue we really need to add a stopgap solution?

**Comment by 1010todd** [comment]
I feel like things will get even worse for the FW when other campaign are implemented, when I was a new player I already avoided the south like plague, even James recommend you to stay within the Paradise Planets to be safe. I think it could benefit from slightly higher offer chance to catch the player during their few visit if there's some well paying jobs heading there. (Or we could even have missions pointing/taking player into the FW area.)

I also agree with Zitchas that there could be a planet with guaranteed chance. This will also make it easier for experienced to get the mission right away without wasting time rolling for the mission only to find out after some hours that the mission was blocked by something else not their luck.

**Comment by Zitchas** [comment]
> I feel like things will get even worse for the FW when other campaign are implemented, when I was a new player I already avoided the south like plague, even James recommend you to stay within the Paradise Planets to be safe. I think it could benefit from slightly higher offer chance to catch the player during their few visit if there's some well paying jobs heading there. (Or we could even have missions pointing/taking player into the FW area.)

One thing I implemented in my alternate starts that I find really helps with this is shifting the start date. Typically, I find that I've barely gotten started, and only explored a tiny segment of human space before the bombing and the war starting. Which means that chances are I'm still in an early ship (often just my first step up from the starter ship), haven't gone into the South, and don't actually know where anything is. As such, the descriptions of the bombings are usually very much a "Huh, so somewhere I've never heard of and never seen got bombed. And somewhere else I've never heard of is suspected of doing it. OK, whatever." Even just moving the start date up by a single year, though, and suddenly when the bombings happen, I've usually been there at least once. I have often ventured into the South, at least a little bit. So this simple change suddenly makes the bombings and the war *massively* more impactful, and I probably even see some of the changes on the map. There's also better odds that I've done some of the prelude FW militia missions and actually experience some of the problems they talk about.

It's amazing what a single year can do, especially for new and non-rushing players.

**Comment by Hurleveur** [comment]
I do agree FW triggers before you are ready, often, but now you can just come to it 10 years after the bombings and start the story - which I guess newbies may not do? Idk

**Comment by Zireael07** [comment]
@Hurleveur That begs the question WHY would the player care 10 years after the bombings, though.

**Comment by Hurleveur** [comment]
No idea, but the navy and FW sure waited for them

**Comment by Zitchas** [comment]
> No idea, but the navy and FW sure waited for them

Are we *sure* that First last isn't a mythical chosen one? *everyone* really seems set on waiting around until First Last can work for them in order to get stuff done, even things like prosecuting a war that really shouldn't wait for one soldier...

**Comment by Anarchist2** [comment]
Leave the discourse on start dates/player agency for another PR/issue.

**Comment by Zitchas** [comment]
No, I think it *is* relevant here. In my view, one of the main reasons the difficulty in triggering the campaign is important is because it really feels like the campaign is already started and the player is just struggling to figure out how to get involved. Having an earlier start date so the player is likely both slightly more experienced with the galaxy and in a slightly better ship both lead to the player being more comfortable ranging farther afield, and thus likely to be getting more into the South to trigger said campaign; especially since it raises the chances that they do the prelude missions.

As such, changing the start date is a quite serious alternate method for rectifying the specific problem being described  here.

**Pull request merged**
