### PR TITLE
Convert GB spelling into American.

### PR DESCRIPTION
**Pull request by quyykk**
This PR simply converts every instance of GB spelling into American.

~~The only one I'm not too sure about is "Mitre -> Miter`.~~ update: not a typo

### CODE REVIEW

**Comment by Amazinite** [comment]
It looks like back in #3476 we settled on grey, but I'm fine with switching everything over to gray. Something I did mention in that issue is probably worth bringing back up again:

> Unless we consider it canon that at some point between now and 3013, all instances of English being used have been standardized to modern American English, **I see no problem in both gray and grey being used in ship names,** but outside of that it should be standardized.

So there are a number of instances of "Grey" being used as a name that I'd revert. Everything else looks good, though.

**Review by Zitchas — COMMENTED** [review]
Amazinite beat me to the punch on this, but I'll just add in my two cents here: Both "gray" and "grey" are acceptable spellings in English. Both are used throughout the English speaking world, and even in the USA. Especially in the names, I actually *prefer* to see a variety of spellings. Humanity hasn't managed to standardize on one so far, I really doubt that we'll standardize in the coming years either. If anything, I suspect that we'll get more variety, not less.

After all, people can name things whatever they like. We could just as easily have someone name their ship "Grae Goose," for that matter.

So, I'd prefer to see all the gray/grey stuff, but otherwise it looks good.

**Comment by quyykk** [comment]
> So, I'd prefer to see all the gray/grey stuff, but otherwise it looks good.

Just to be clear, are there still any changes that you want to see reverted? Or did I already address them all?

**Comment by Amazinite** [comment]
Looks good.

**Comment by Zitchas** [comment]
I think we should perhaps *not* put a lot of work into standardizing the language? If a spelling is out-and-out wrong in American English, than by all means let's fix it. But if a spelling is merely the "more popular" spelling in American English, then I think we should be fine having both used in-game.

For instance, catalogue vs catalog. Looking it up, it seems fairly clear that in present days American spelling, neither one is wrong, but the later is the more common spelling. Some might even call it preferred, but the former is by no one wrong.

**Pull request merged**
