### PR TITLE
code cleanup: removing std:: from cpp files

### PR DESCRIPTION
**Pull request by flowers9**
## Fix Details
Removed std:: prefixes (and added using namespace std, as needed) to various cpp files to bring them in line with the c++ style guide.  Had to rename a couple of unfortunately chosen variables (list<> list and thread thread).

## Testing Done
It compiled fine.  Played with it a bit to make sure nothing weird happened.

### CODE REVIEW

**Comment by flowers9** [comment]
Any suggestions on how to debug that error?  I don't have access to a windows machine, unfortunately.

**Comment by RisingLeaf** [comment]
> Any suggestions on how to debug that error? I don't have access to a windows machine, unfortunately.

https://github.com/build2/build2/issues/259

add an std again

**Comment by flowers9** [comment]
No, the linked article made it pretty clear (and thanks for it).  I was unhappy at all the changes I'd have to make. ;)

**Review by Hurleveur — APPROVED** [review]
Consistency is good indeed
Name collusion is why using namespace std is not done usually but honestly those variables may as well be renamed from such generic things as threat and list, to be more explicit.

**Comment by flowers9** [comment]
Personally, I never use "using namespace std" because I like to see where stuff comes from (my code or libraries or whatever).  But, well, if that's the way we're doing it, we should be consistent, I reckon.

**Review by RisingLeaf — APPROVED** [review]

**Comment by Amazinite** [comment]
So just to be clear, our current exceptions are std::move and std::forward? Is that all?

**Comment by tehhowch** [comment]
Please ensure you understand [why something is present](https://github.com/endless-sky/endless-sky/pull/3630#issuecomment-364614030) before removing it.

Using `git blame` is a great way to discover the history of particular lines.

**Comment by flowers9** [comment]
You can just say it's a poorly conceived PR,  Save us all a bit of time, I think.

Apparently, the trouble is that removing the std:: from some things is problematic.  It's one more reason for why I don't use using namespace std, I guess (my usual reason is I like to know where stuff comes from).  And there's just no good way to tell what will work and what won't.

Perhaps the wiki should reflect the issue?  Or should people just find out the issue for themselves when things break on machines they can't test on?  Or at least for things that have had issues, like move, forward, and isnan (and any others people know of)?

**Pull request closed without merging**
