### PR TITLE
Additional goods for the commodities

### PR DESCRIPTION
**Pull request by Pointedstick**
I added a bunch more specific goods to the master commodities list for extra flavor and to reduce the repetitiveness of the goods for people who do a lot of trading.

### CODE REVIEW

**Comment by gchapyzh** [comment]
Could you please add 'tanks'? I just want a mission "Could you transport 50 tons of **tanks** to... for 200,000?"

However this gave me an idea of what to add to the list myself, perhaps I will submit my own pull later.

**Comment by endless-sky** [comment]
Looks good! But, I wonder if maybe you should take out "tampons" and "prophylactics" - I'm sure some people would either take offense at that or be too young to know what those are.

Also, maybe "disposable" instead of "disponible"? They mean the same thing, basically, but the first is a much more common word.

**Comment by Pointedstick** [comment]
Oops "disposable" is French! Submitted another merge request for that.

**Comment by Pointedstick** [comment]
Hmm, it looks like this merge somehow didn't work. I don't see that data/commodities on master has the changes, and my second merge request to fix "disposable" is in conflict as a result.

**Comment by ItsNickBarry** [comment]
Until today, I was too young to know what "cupronickel" is, and I'm definitely offended by the concept.

**Comment by ItsNickBarry** [comment]
The wanton mixing of metals is an abomination!

**Comment by Tufton** [comment]
"unplasticized PVC"
god help us if we are still using PVC pipe in the year 3000

**Comment by ItsNickBarry** [comment]
What would you propose?  Some sort of alloy?  Please, keep that to yourself - there could be children present.

**Pull request merged**
