### PR TITLE
feat(UI): Dropdowns for Multi-Setting Preferences

### PR DESCRIPTION
**Pull request by Koranir**
## Feature Details
Related: #8790 
This PR uses the same code a #8790 to implement dropdowns for multi-setting preferences.

Also standardises preferences a bit

## UI Screenshots

https://github.com/endless-sky/endless-sky/assets/101683475/32f624ca-8504-42de-84a3-ea93b1716761

### CODE REVIEW

**Comment by lumbar527** [comment]
Looks like it fits Endless Sky well enough.

**Comment by mOctave** [comment]
I'm not sure I like the drop-up style here, honestly. Dropdown would be less confusing and more visually appealing, in my opinion.

**Comment by TomGoodIdea** [comment]
IMO the best option would be to position the menu relatively to what value the setting is currently set.

**Comment by Saugia** [comment]
@Koranir Any plans for continuing work on this PR soon?

**Comment by Koranir** [comment]
> @Koranir Any plans for continuing work on this PR soon?

Not really, feel free to orphan it. @Saugia

**Pull request closed without merging**
