### PR TITLE
Content: two use cases for custom penalties to fix unwanted behavior

### PR DESCRIPTION
**Pull request by Hurleveur**
Quarg no longer mind you provoking Gegno civilians as much as before; you need to provoke 1001 civilians for a Quarg war (that said, disabling one ship ought to do it too)
They still mind the rest like before and dont care about you assisting Gegno.

Remnants no longer mind you scanning void sprites (they literally ask you to do it)

### CODE REVIEW

**Comment by Hurleveur** [comment]
I seems that this crashes the game on loading... @warp-core ?
Anyhow still wouldnt mind an opinion on if this change should be made but we need to fix this first.

**Comment by warp-core** [comment]
Oh dear

**Comment by Hurleveur** [comment]
Should now work without any issues.
I see other use cases for custom penalties but I wouldnt call them bug fixes so I'll keep this PR as is.

**Review by Zitchas — APPROVED** [review]
I can't speak to the Gegno and if that fits with the intent for the civilians; but the custom penalty for the Remnant in regards to the Indigenous Lifeform looks good.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
