### PR TITLE
refactor(content): Relocate "famous warrior" warning to events.txt

### PR DESCRIPTION
**Pull request by MasterOfGrey**
As mentioned in #8944 the warning given when your combat rating gets high enough is hard to find because it exists in a silly file. I have relocated this to events.txt (because it is something which happens to you) in the hope that this is more accessible.

This is now it's own PR per @warp-core's request

### CODE REVIEW

**Review by lumbar527 — APPROVED** [review]

**Review by EjoThims — APPROVED** [review]

**Comment by Quantumshark** [comment]
I'd say `human missions.txt` would be a better place for this than events, but I definitely agree it shouldn't be in the jobs file.

**Comment by MasterOfGrey** [comment]
If there was an equivalent `events.txt` file for the Hai I'd put the similar Hai one there too, but I'm not creating a whole file for that.

Because it's a fixed reference point warning to the player, it's more of an event than a mission, and it'd be hard to find in the missions file.
It only kinda works in the Hai file because they have a first contact and stuff which it can logically go next to as one of the 'introductory' type deals.

**Comment by Amazinite** [comment]
Events.txt is really aimed toward campaign events, so maybe we change the name of the file to campaign events.txt to make that more clear. On top of that, this isn't even an event, it's a pair of missions, I'm in agreement with Quantum that I think that human missions is a more appropriate location for this.

**Comment by Amazinite** [comment]
We should probably move the raid warning too, which is also in jobs.txt.

**Pull request merged**
