### PR TITLE
Shop panel hierarchy improved (display options and greyed-out items)

### PR DESCRIPTION
**Pull request by stechio**
This PR was motivated by the noticeable usability flaws of the **outfitter panel**:
* **awkward, inconsistent display options**: if the user checks `Show outfits for sale`, all the available outfits are (correctly) listed BUT, if the user checks `Show outfits in cargo`, the cargo items are NOT shown by themselves until the `Show outfits for sale` is unchecked (so ugly!). Furthermore, if the user wants just to see the outfits installed in the selected ship, she has to switch off all the checkboxes, one by one (kinda convoluted pain!). 
* **inability to show just the actually purchasable/installable outfits**: it's pointless to show ALL the outfits on sale when the selected ship cannot install most of them or there isn't enough cargo room to store them!

EDIT: because of participants' feedback, the _PR implementation has changed to support **greyed-out items** instead of hiding them_ -- see [Amendment 1](https://github.com/endless-sky/endless-sky/pull/4516#issuecomment-529223269).
EDIT: the same enhancements applied to the oufitter panel have been later extended to the **shipyard panel** -- see [Amendment 2](https://github.com/endless-sky/endless-sky/pull/4516#issuecomment-529426994).

&nbsp;
&nbsp;
DEPRECATED:
This PR addresses such issues redefining the display options as _neat, symmetrical, mutually-exclusive views on the same set of outfits_:
1. `Show outfits available`: shows _all the outfits available_ for purchase/sale as cargo (in case no ship is selected) or for installation/sale as equipment (in case any ship is selected)
&nbsp;
endless-sky_outfit_ALL

2. `Show outfits purchasable`: shows _the outfits actually available_ for purchase as cargo (conditions like lack of storage room or credits exclude unsuitable outfits from this view)
&nbsp;
endless-sky_outfit_PURCHASABLE

3. `Show outfits in cargo`: shows the outfits available in cargo for sale
&nbsp;
endless-sky_outfit_CARGO

4. `Show outfits installed`: shows the outfits installed in the selected ship
&nbsp;
endless-sky_outfit_INSTALLED

5. `Show outfits installable`: shows _the outfits actually available_ for installation as equipment (either from cargo or purchase) into the selected ship (conditions like lack of equipment space or credits exclude unsuitable outfits from this view)
&nbsp;
endless-sky_outfit_INSTALLABLE

Summary of the display options:
<table>
<tr><td></td><td>Cargo</td><td>Ship equipment</td></tr>
<tr><td>1. ...available</td><td align="center">*</td><td align="center">*</td></tr>
<tr><td>2. ...purchasable</td><td align="center">* (filtered)</td><td></td></tr>
<tr><td>3. ...in cargo</td><td align="center">*</td><td></td></tr>
<tr><td>4. ...installed</td><td></td><td align="center">*</td></tr>
<tr><td>5. ...installable</td><td></td><td align="center">* (filtered)</td></tr>
</table>

Option 1 is common both to cargo and ship equipment; options 2 and 3 are cargo-specific; options 4 and 5 are equipment-specific. If the user selects a ship while a cargo-specific view is active, the panel automatically switches to its homologous equipment-specific view, that is:
* if current view is `Show outfits purchasable`, it automatically switches to `Show outfits installable`;
* if current view is `Show outfits in cargo`, it automatically switches to `Show outfits installed`.

### CODE REVIEW

**Comment by jafdy** [comment]
For both 3 and 4, I feel that the existing "installed" and "in cargo" labels do just fine. And for 2 and 5 I feel that greying the other outfits out would be a better option, along this line those options could be condensed into a single option that works outside the other options.
Also, mutually exclusive checkboxes. You would need a new graphic for that to communicate the exclusivity of them (and presumably the requirement to have at least one).
Throughout this you must consider the real reason those boxes are there at all, to make it easier for people to buy into cargo (deselecting ships wasn't obvious enough).

**Comment by stechio** [comment]
> Also, mutually exclusive checkboxes. You would need a new graphic for that to communicate the exclusivity of them (and presumably the requirement to have at least one).

Sure, radio buttons.

> For both 3 and 4, I feel that the existing "installed" and "in cargo" labels do just fine. And for 2 and 5 I feel that greying the other outfits out would be a better option, along this line those options could be condensed into a single option that works outside the other options.

_Greying the unsuitable outfits could be an effective solution_ -- this way the outfit store would keep the same layout for both cargo and ship equipment purchases, while the options would collapse into just four (2 options for both cargo and ship equipment, orthogonally):
1. `purchasable` (for _cargo addition_ -- ship selection deactivated): shows all the outfits available in store for purchase, with unsuitable items greyed according to cargo-related conditions (e.g. lack of cargo space or credits);
2. `in cargo` (for _cargo removal_ -- ship selection deactivated): shows the outfits available in cargo for sale;
3. `installable` (for _ship equipment addition_ -- ship selection activated): shows all the outfits available for (possibly) purchase and installation, with unsuitable items greyed according to selected-ship-related conditions (e.g. lack of equipment space or credits);
4. `installed` (for _ship equipment removal_ -- ship selection activated): shows the outfits installed in the selected ship.

Summary of the revised display options (orthogonal representation):
<table>
<tr><td></td><th>Addition</th><th>Inspection/Removal</th></tr>
<tr><th align="left">Cargo</th><td align="center"><code>purchasable</code></td><td align="center"><code>in cargo</code></td></tr>
<tr><th align="left">Ship equipment</th><td align="center"><code>installable</code></td><td align="center"><code>installed</code></td></tr>
</table>
&nbsp;

> Throughout this you must consider the real reason those boxes are there at all, to make it easier for people to buy into cargo (deselecting ships wasn't obvious enough).

It's _precisely_ because the existing solution feels so convoluted (thus failing its purpose) that _listing all the display options in a flat, clear and obvious manner_ (without special buttons to activate filters on current view, which are prone to distraction and confusion) _is the best way to expose the outfits_. Use cases:
- the user wants to buy goods for her cargo: let her click `purchasable` (or whatever label would convey that meaning);
- the user wants to sell goods from her cargo: let her click `in cargo` (or whatever label would convey that meaning);
- the user wants to inspect/change the configuration of her ships: let her click `installed` (or whatever label would convey that meaning);
- the user wants to improve the configuration of her ships: let her click `installable` (or whatever label would convey that meaning).

To me this new interface is much more clear and dead-simple (contrary to the existing solution): the orthogonality of the options boosts their consistency, it's self-explanatory.

**Comment by tehhowch** [comment]
To me it makes little sense to have a view that would only show outfits you can install, claim that the purpose of said view is to improve the functioning of the ship, and then hide all outfits that could be removed to make room for a desired outfit. Most commonly one does not have an empty ship to outfit; one has installed outfits and installable outfits (from cargo or store) with which to compare and contrast. Yes, sometimes the new outfit can fit in without tweaking existing installed outfits, but I feel it is much more common to need to both uninstall and install.

(Please consider opening issues or adding to the conversation of existing issues when considering large or UX-based changes from existing behavior, rather than a PR that then invites discussion. This is so that, if the PR is closed for some reason, the related issue is still open and the discussion can continue easily.)

**Comment by stechio** [comment]
> To me it makes little sense to have a view that would only show outfits you can install, claim that the purpose of said view is to improve the functioning of the ship, and then hide all outfits that could be removed to make room for a desired outfit. Most commonly one does not have an empty ship to outfit; one has installed outfits and installable outfits (from cargo or store) with which to compare and contrast. Yes, sometimes the new outfit can fit in without tweaking existing installed outfits, but I feel it is much more common to need to both uninstall and install.

I understand (and accept) your point -- that's the reason why @jafdy suggested to grey the unsuitable outfits instead of hiding them: [my latest comment](https://github.com/endless-sky/endless-sky/pull/4516#issuecomment-529105482) elaborated on that feedback.

> (Please consider opening issues or adding to the conversation of existing issues when considering large or UX-based changes from existing behavior, rather than a PR that then invites discussion. This is so that, if the PR is closed for some reason, the related issue is still open and the discussion can continue easily.)

You are right -- next contributions will follow that workflow.

**Comment by jafdy** [comment]
I still don't understand the requirement for having both `in cargo` and `installed` as those have existing labels. The use case for `in cargo` is to sell off some of you in cargo outfits while keeping others (outside of missiles this is not a common use case), for `installed` I can only think of people taking screen shots of the equipment. Once we are down to the last two options it then becomes a button that deselects all ships.
I'm not telling you that the old way is better, I just think you have overshot on the usability front.

**Comment by stechio** [comment]
> I still don't understand the requirement for having both `in cargo` and `installed` as those have existing labels.

_Those views are already in the existing implementation_, they are just unevenly exposed:

-  `in cargo` view has a dedicated option (which takes effect only if the other `for sale` option is unchecked, ouch!)
&nbsp;
endless-sky_outfit_old_incargo

- `installed` view is buried under the all-options-disabled state (ouch!)
&nbsp;
endless-sky_outfit_old_installed

> The use case for `in cargo` is to sell off some of you in cargo outfits while keeping others (outside of missiles this is not a common use case), for `installed` I can only think of people taking screen shots of the equipment.

Since both `in cargo` and `installed` views are _already_ in the existing implementation, _I'm just sorting them in a better (evenly exposed) manner_.

> Once we are down to the last two options it then becomes a button that deselects all ships.

Since both `in cargo` and `installed` views are _already_ in the existing implementation, we are NOT down to the last two option -- they are all still there! ;-)

**Comment by jafdy** [comment]
I don't like the current boxes, they solved the problem but not in a way that made an ounce of sense to me, so I don't care what exactly is there now. You can say three times that they already exist and I will continue to wonder why they need to. Just because they were added doesn't mean that there aren't better options available that don't include them. Assuming that you can only add things will often result in feature bloat so sometimes things do need to be removed. (In case you hadn't guessed, my preferred solution is a button that deselects all the ships.) 

As a side note, your second and third responses missed the point (It was a statement nothing more!) or failed to consider my full argument. If I start with "Now we are . . ." or "Once we are . . ." then you need to consider my argument on the basis of my assumption, if you have attempted to invalidate an earlier part of my argument then there is no need to state it again.

Right now we need a clear picture of the current proposal. So lets see how I can do. (Provisional names throughout.)

We have 4 options on radio buttons
1 `buy to cargo` Force deselects all ships when clicked, forced if all ships are deselected while option 2 is active. Shows all outfits in cargo or for sale. Outfits are greyed out if they are not in cargo and can't be bought (for any reason).

2 `install to ship` Forced if a ship is selected while option 1 is active. Shows all outfits installed on the selected ship/s, for sale or in cargo. Outfits are greyed out if they are not installed and can't be installed (for any reason) on (one/all of) selected ship/s.

3 `in cargo` Shows only outfits in cargo at the time.

4 `installed` Shows only outfits installed in that ship/s.


This does leave some questions like how do we handle multiple ships (and what is the default option, and how do we give that option to the player).

**Comment by stechio** [comment]
> I don't like the current boxes, they solved the problem but not in a way that made an ounce of sense to me, so I don't care what exactly is there now. You can say three times that they already exist and I will continue to wonder why they need to. Just because they were added doesn't mean that there aren't better options available that don't include them. Assuming that you can only add things will often result in feature bloat so sometimes things do need to be removed. (In case you hadn't guessed, my preferred solution is a button that deselects all the ships.)

My (conservative) objective was just to rationalize the existing functionality improving the way it's delivered to the user. To me, allowing the user to have a clean and easily-accessible view of cargo and ship equipment status is a bonus which doesn't impair/bloat anything (it's just 2 items in a well-thought handful of options) -- quite the other way around :-) (someone else may actually consider it useful)!

> As a side note, your second and third responses missed the point (It was a statement nothing more!) or failed to consider my full argument. If I start with "Now we are . . ." or "Once we are . . ." then you need to consider my argument on the basis of my assumption, if you have attempted to invalidate an earlier part of my argument then there is no need to state it again.

Please don't care about it, I stressed my point solely because I felt misunderstood and needed to focus on that crucial premise :-) (aside from your legitimate opinion).

> Right now we need a clear picture of the current proposal. So lets see how I can do. (Provisional names throughout.)
> 
> We have 4 options on radio buttons
> 1 `buy to cargo` Force deselects all ships when clicked, forced if all ships are deselected while option 2 is active. Shows all outfits in cargo or for sale. Outfits are greyed out if they are not in cargo and can't be bought (for any reason).
> 
> 2 `install to ship` Forced if a ship is selected while option 1 is active. Shows all outfits installed on the selected ship/s, for sale or in cargo. Outfits are greyed out if they are not installed and can't be installed (for any reason) on (one/all of) selected ship/s.
> 
> 3 `in cargo` Shows only outfits in cargo at the time.
> 
> 4 `installed` Shows only outfits installed in that ship/s.

Yes, your recap is perfect.

> This does leave some questions like how do we handle multiple ships (and what is the default option, and how do we give that option to the player).

Do you see any issue about multiple-ship handling in comparison with the existing implementation?

About the default option, since in a trading space game exchanging goods is the ordinary activity whilst changing ship configuration is an ancillary activity, I think the default view should be `buy to cargo`.

**Comment by jafdy** [comment]
You can't profit off buying and selling outfits and if you are plundering then there is a sell all outfits in cargo button, so I would argue for `install to ship` (also the default currently and the effective from before).

The main question with multi ship handling is in the last part of option 2, " on (one/all of) selected ship/s." The problem is, should an outfit be greyed out if any of the selected ships can't install it or only if all of the selected ships can't install it.

**Comment by stechio** [comment]
> You can't profit off buying and selling outfits and if you are plundering then there is a sell all outfits in cargo button, so I would argue for `install to ship` (also the default currently and the effective from before).

You are right (sorry, my misinterpretation).

> The main question with multi ship handling is in the last part of option 2, " on (one/all of) selected ship/s." The problem is, should an outfit be greyed out if any of the selected ships can't install it or only if all of the selected ships can't install it.

What happens now when multiple ships are selected and any of them can't install an outfit? Is the "Buy" command enabled anyway? If yes, then I would go for the normal (non-greyed) rendering, wouldn't you?

**Comment by jafdy** [comment]
That is the kind of detail that is required for a full feature request, exhaustive (and exhausting).

**Comment by stechio** [comment]
Here we are, [Amendment 1](https://github.com/endless-sky/endless-sky/pull/4516/commits/93b7a48d6f8696886974b2532575a6db42a46df4) introduces the **greyed-out items** and redefines the options (view modes) according to the latest evolution.

I test-drove it and seems quite effective (way cooler then the existing implementation) -- I'm pretty satisfied (please, don't mind the option labels, the checkboxes-to-be-radio-buttons, the option box background etc. -- they are minor details we'll fix later):

1. `install to ship`
&nbsp;
endless-sky_outfit_v2_installable

2. `buy to cargo`
&nbsp;
endless-sky_outfit_v2_purchasable

3. `installed`
&nbsp;
endless-sky_outfit_v2_installed

4. `in cargo`
endless-sky_outfit_v2_cargo

**Comment by stechio** [comment]
The latest commits ([1](https://github.com/endless-sky/endless-sky/pull/4516/commits/ec7add7c573290686708e98ea0c232267eb68fe9) and [2](https://github.com/endless-sky/endless-sky/pull/4516/commits/81b2446db99d11373f690696fa4db5927982cb6c)) fix the option group style.
&nbsp;
endless-sky_outfit_v2_outfitter-key

**Comment by beccabunny** [comment]
If with this PR I select a greyed out item, does it stay greyed or does it turn normal? I think it would be nice to have the latter, as a player may want to see the image of the outfit better(to make an example, triple system cores, which are very big and can be acquired relatively early) without having to remove other outfit just to look at it.

**Comment by stechio** [comment]
> If with this PR I select a greyed out item, does it stay greyed or does it turn normal? I think it would be nice to have the latter, as a player may want to see the image of the outfit better(to make an example, triple system cores, which are very big and can be acquired relatively early) without having to remove other outfit just to look at it.

Since the purpose of the grey shade is to deliver the _unavailability_ of the outfit, reversing to normal just because it's selected (_yet still unavailable!_) would be a bit logically disruptive... nevertheless, _we could certainly apply an intermediate grey level to the selected outfit_: this way, it could stand out without interfering with the available outfits.

**Comment by jafdy** [comment]
It's a special case, lots of games do it just because people like looking at the pictures.

**Comment by stechio** [comment]
ok, it make sense: I committed this behavior.

**Comment by stechio** [comment]
[Amendment 2](https://github.com/endless-sky/endless-sky/pull/4516/commits/45b931ce4a0476b71f38c24cda27c7bdce95b689) brings the same enhancements of OutfitterPanel to ShipyardPanel:

- greyed-out ships when unavailable (not enough credits)
&nbsp;
endless-sky_ship_selected_enabled

- highlighting of greyed-out ships when selected
&nbsp;
endless-sky_ship_selected_disabled

**Comment by stechio** [comment]
[Buy/Sell key bindings have been extended](https://github.com/endless-sky/endless-sky/pull/4516/commits/24f6049a908263318f90a4c3b4ce451f96a2468e) to support also, respectively, the more intuitive "+" and "-" keys.

**Comment by stechio** [comment]
[Command buttons have been improved and fixed](https://github.com/endless-sky/endless-sky/pull/4516/commits/15ad8e611c98d67dca61d8049a6f8489455ba363):

- **ship-related views** consistently label commands as Install/Uninstall. Furthermore, the original behavior of "Sell" has been fixed: in case the selected outfit had both installed AND in-cargo instances, the "Sell" command (wrongly) removed instances from cargo instead of (as expected) from installation.
&nbsp;
endless-sky_outfit_buttons_install

- **cargo-related views** consistently label commands as Buy/Sell.
&nbsp;
endless-sky_outfit_buttons_cargo

**Comment by stechio** [comment]
In `install to ship` view, [already-installed outfits which cannot be further installed now are highlighted](https://github.com/endless-sky/endless-sky/pull/4516/commits/0403ba39d673c1854499f93cc1cba1f3dfc3fed7):

- normal state (semi-bright)
&nbsp;
endless-sky_outfit_v3_installed_normal

- selected state (fully bright)
&nbsp;
endless-sky_outfit_v3_installed_selected

**Comment by stechio** [comment]
The [highlighting behavior of `install to ship` view](https://github.com/endless-sky/endless-sky/pull/4516#issuecomment-529572952) has been [ported to `buy to cargo`](https://github.com/endless-sky/endless-sky/pull/4516/commits/166fd13e3d473c87d533ce522e7f8db5170da446) (this way, in-cargo outfits which cannot be further bought are semi-bright).

**Comment by jafdy** [comment]
>  Buy/Sell key bindings have been extended to support also, respectively, the more intuitive "+" and "-" keys.

Um, no, don't do that. It should be a separate PR. Complicating a PR just makes it hard to merge, unless it is a requirement for the rest of the PR each change should be its own thing.

For the sake of ease of use there should only be two brightness levels, full colour and greyed out. The more levels you add the harder it is to distinguish. In general you want as few levels as you can get away with.

**Comment by tehhowch** [comment]
- Install was only shown when you didn't need to spend money; why change that?
 - Sell always preferred cargo over installed because there was previously no way to select just cargo simply; to sell cargo outfits with your behavior would require selling all of the installed outfits first, then selling cargo'd outfits, then reinstalling the desired number. Hence why there is a Remove / Uninstall key now, for when one *does* want to uninstall and not sell from cargo.

It's very easy to completely change how things work, but please consider that doing that in a single PR is unlikely to make progress. UX changes should probably go through an issue and research component before being PR'd, and especially before being tacked on to an existing PR.

**Comment by stechio** [comment]
ok, I suppressed the changes unrelated to this PR.

**Comment by Pointedstick** [comment]
Coupla UI comments:
- Radio buttons are typically round, not square. Consider adjusting the appearance accordingly.
- The radio buttons' text should use sentence-style capitalization (i.e. "Install to ship").
- I'm not sure how much I like reducing the opacity of non-installed items in the "Install to ship" and "Buy to cargo" View. The visual cue seems to imply that there's something unavailable or uninstallable about those items, which isn't the case. If anything, this is what you would want to do for the "Installed" view.

**Comment by Amazinite** [comment]
Closing this PR as it is rather out of date at the moment and isn't a feature which we seem particularly interested in.

**Pull request closed without merging**
