### PR TITLE
Add some inaccuracy at the moment of firing

### PR DESCRIPTION
**Pull request by EndrosG**
Using the existing inaccuracy flag of weapons, I added another way of inaccuracy by adding some error to the rendezvous time estimation.

### CODE REVIEW

**Comment by endless-sky** [comment]
I'm really not sure what the purpose of this is.

**Comment by jafdy** [comment]
Won't that do the same thing as normal inaccuracy?

**Comment by EndrosG** [comment]
The purpose of this can may be best explained with the following picture.

endless_sky_v0_9_6__20170409__inaccurate_rendezvous_time

Green: the ship which will fire.
Yellow, Orange, Red: enemies at different distances and different moving paths but same moving speed.
Think of relative movement paths on that image, may be the green ship is holding position. Easier for the brain to think of :-)

The white X: the real rendezvous point.
The question marks: potential rendezvous points if you make a wrong guess either upon rendezvous time (i.e. number of steps in terms of code, my approach) or upon relative speed.

For the red enemy, it will not change anything with respect to the firing angle. For the other two enemies it will matter. That error depends on the relative movement vector. - Normal inaccuracy has a "fixed" variation of the firing angle.
Example if you had an energy blaster or gatling with a blast radius of about 20 and a trigger radius of 10, may be representing some sort of "flak cannon", it would still hit if the guess was semi accurate.

Remember: using Random::Normal() should make the effect not too big. You can, of course, use any other Random distribution, but it should have a mean of zero.
Sadly, for beam lasers with their still very low inaccuracy, I dont even notice the effect in my local build. For Energy Blasters I think I notice the effect.

**Comment by Elyssaen** [comment]
Ah, so whereas existing inaccuracy is a physical inaccuracy of the beam/munitions out of the gun, this is an inaccuracy in the rendezvous calculation. It's computer error, rather than mechanical error.

While I like this, I don't think it should be connected in any way to the weapon, either as the existing weapon `inaccuracy `or a new attribute.

I prefer this as a different implementation to Confusion, or potentially as an additional 'status effect' that can be applied to a ship as some kind of scanner interference.

**Pull request closed without merging**
