### PR TITLE
Feat(content): Add departure distances to ringworlds

### PR DESCRIPTION
**Pull request by RisingLeaf**
**Content (Artwork / Missions / Jobs)**

## Summary
It seems strange to jump out of a system while being inside the range of a ringworld. That is why I thought, it would make sense to have a departure distance for every system with a ringworld.

I only talked about this with a few people so far, so I am open for changes or arguments against this.

The departure distance is chosen a bit away from the ringworld to avoid ships jumping right from the border.

In the future we might consider having a departure distance for every star because of gravitation, but for now I just want to add this for ringworlds

## Save File
Just go to a system with a ringworld and hit jump while being inside its radius.

### CODE REVIEW

**Comment by Hecter94** [comment]
Seems like an interesting idea, and a good first use for Departure Distance.

**Review by a-random-lemurian — APPROVED** [review]
looks good to me

**Review by Arachi-Lover — APPROVED** [review]
Makes sense.
Is there any tooltip or pop-up to warn players who aren't aware of this about needing to be far away enough? Or would this need to be something they figure out themselves?

**Review by Zitchas — APPROVED** [review]
Definitely an appropriate use for this, and a visually-sensible place to test out how well it works.

**Comment by Saugia** [comment]
@RisingLeaf Can you resolve the conflicts on this PR?

**Comment by RisingLeaf** [comment]
done

**Pull request merged**
