### PR TITLE
Copy editing: mostly TMBR 3B grammar + typo

### PR DESCRIPTION
**Pull request by pcordes**
I found a couple grammar problems in the TMBR mission where you take them up to Hai space, and a typo.

I earlier _thought_ I'd found a typo in the planet Quicksilver's landing message, but it turns out it was just unusual sentence structure.  I changed it anyway; I think it reads better this way.

See the commit messages for more details.

### CODE REVIEW

**Comment by endless-sky** [comment]
The only one of these that's actually a mistake is patch - path. The other changes are purely opinion, since the current text works fine grammatically.

**Comment by pcordes** [comment]
Some of the changes are opinion, which is why I titled this "copy editing" to include changes that IMO improve readability even when the original might not be breaking any rules.  Feel free to amend this commit however you like, and just consider my changes a suggestion / bug report.

According to the source I quoted in the commit message, starting a sentence with "But comma" *is* an error.  It definitely looked wrong to me, so I googled it.  I didn't look at other hits to see if there were conflicting opinions on it; looking wrong to me and finding confirmation from anyone else was sufficient to change it.

I'm also certain that "bring your ship to a gingerly landing" sounds wrong, and pretty certain that it's not even correct.  Valid options include:

* "bring your ship to a ginger landing" (doesn't sound ideal)
* "bring your ship to a landing, gingerly"
* "bring your ship gingerly to a landing" (still sounds clumsy, but I think it's legal grammar)
* "gingerly bring your ship to a landing" (More of a change to the writing style, but definitely reads more easily to my eye.)

**Comment by endless-sky** [comment]
"Gingerly" can be used as either an adjective or an adverb. The example [Merriam Webster](http://www.merriam-webster.com/dictionary/gingerly) gives is "gave the cork on the bottle of champagne a gingerly twist," which is rather similar to how I was using it.

**Comment by pcordes** [comment]
Ok, I stand corrected on "gingerly".  That usage is apparently technically correct (and my suggestion of "ginger landing" as a viable alternative was probably wrong).

I don't remember ever encountering that usage before, though, and it still feels wrong to me.  (I'm from the east coast of Canada, in Halifax, NS).  I'd only ever seen gingerly as an adverb, which led me to believe that it was the adverb form of "ginger".  I suspect I'm not the only person with this mistaken impression who will find that sentence odd, so you might consider changing it just for that reason.

As far as the rest of the sentence, I still think splitting it into two separate sentences is an improvement.  They don't sound related enough to be joined by an "and".  The rest of the paragraph is also short sentences, so stylistically it seems to fit better.

**Comment by pcordes** [comment]
I think the comma I inserted into "When it spoke I felt ..." was also a significant improvement.  It's a separate clause, right?

BTW, I'm curious: do you think any of my changes actually make the text worse to read for some readers?  Or do you just think both ways are fine and don't want to change it for no reason?  If the latter, please consider merging this because I think it will make the text look better for some readers (including myself) without causing any harm to others.

**Comment by MessyMix** [comment]
@endless-sky I think this guy is looking for a response?

**Pull request closed without merging**
