### PR TITLE
New pug galaxy image

### PR DESCRIPTION
**Pull request by beccabunny**
This PR adds some colors to the pug rainbow galaxy. Doesn't require a copyright change since it is very minor, and the high DPI is impossible since MZ's pug galaxy image which this is based on isn't there

### CODE REVIEW

**Comment by MCOfficer** [comment]
While you're at it, you might want to add this image to the copyright file. It is public domain so it's fine the way it is, but it seems weird to have a section for all other public domain files from NASA (including galaxy.jpg) and not include the pleiades.

https://github.com/endless-sky/endless-sky/blob/c7c979497e84e5edcae54f90b80ee9fb1a30d1d0/copyright#L172-L194

**Comment by beccabunny** [comment]
Alright, done

**Comment by comnom** [comment]
I'm not sure I agree with the coloring here. If this is actually the [pleiades](https://en.wikipedia.org/wiki/Pleiades), then blue should dominate, and even if it isn't, the lack of individual colors of the various stars makes the dust cloud/nebulae that image was taken through over dominate.

The worst part of the current image isn't really the lack of color, but the lack of contrast that washes it out. I'd recommend starting from the original,

<details>

Pleiades

</details>

ramping up the contrast until you get a full black background, then dropping the saturation of the blue/cyan to a more realistic level (the original looks a bit color enhanced).

After that you can give a go at adding more colors than blue, but I'd do it at a bit of a smaller scale. (ie, add some color to various stars rather than just large swathes over the nebulae)

Also, you've saved the image as a .png. We use .jpg for large images that don't need transparency.

**Comment by beccabunny** [comment]
@comnom now?

**Comment by tehhowch** [comment]
For changes to map background images, it is a very good idea to provide before & after screenshots as seen in the Endless Sky map view, so all can double-check that it and the systems remain properly positioned.

**Comment by beccabunny** [comment]
Sure thing. Tomorrow, when I will have corrected some other stuff, I'll add them

**Comment by beccabunny** [comment]
Screenshot (455)
Screenshot (456)
Alright, updated. These are the screenshot that you asked @tehhowch 
This is the updated xcf
[Pleiades.zip](https://github.com/endless-sky/endless-sky/files/3090523/Pleiades.zip)

**Comment by MCOfficer** [comment]
i like the colors a lot more now, but it's still way to bright and intense. compared with the milky way backdrop:


Clipboard01

**Comment by beccabunny** [comment]
The one in the left isn't the current one, but I get what you mean

**Comment by MCOfficer** [comment]
It is? https://raw.githubusercontent.com/endless-sky/endless-sky/master/images/ui/galaxy.jpg

**Comment by beccabunny** [comment]
Oh sorry I meant the  right one

**Comment by beccabunny** [comment]
Screenshot (458)
@MCOfficer is this better?

**Comment by beccabunny** [comment]
Screenshot (459)
@comnom and @tehhowch i updated the galaxy again, with some help and corrections from MCO. This is the current version
New file:
[Pleiades.zip](https://github.com/endless-sky/endless-sky/files/3093971/Pleiades.zip)

**Comment by Amazinite** [comment]
@comnom Does this look good to you now?

**Comment by comnom** [comment]
<details>

Capture

</details>

I've got no major complaints. Some of the small background stars have had their color overridden by the larger star's coloring still, but it's not really noticable at scale unless you're looking for it.

**Comment by MCOfficer** [comment]
is [this](https://github.com/endless-sky/endless-sky/pull/4256#issuecomment-484446455) the final asset link?

**Comment by Pointedstick** [comment]
I love it! Sorry for the absence. Work got insane and I had to cut out hobbies for a while.

**Pull request merged**
