### PR TITLE
afterburner alignment quick fix

### PR DESCRIPTION
**Pull request by djlad**
quick fix for issue #4260

### CODE REVIEW

**Comment by Zitchas** [comment]
I can't read the code well enough to know if this is a fix, but hopefully this works. We just had someone post on the discord with a video of them showing the glitch even worse while flying a flivvr.

**Comment by Fzzr** [comment]
Is it possible this is caused by display scaling or whether or not you're using the high-DPI mod?

**Comment by Zitchas** [comment]
I'm running on "straight off the GitHub Nightly" without any plugins (although admittedly I'm alternating between a number of different branches writing stuff. All are up to date with the Nightly.)

**Comment by Fzzr** [comment]
For what it's worth, there is no afterburner effect in the high-DPI mod. I can't test right now though.

**Comment by Janaszar** [comment]
I've been looking at the history of `ship.cpp`, and it seems it broke with this commit: https://github.com/endless-sky/endless-sky/commit/547e43277528bbf391c1053c761bd579a7a2cf09

I can't find any "prior commit" to that that changes that line by adding a 0.5 multiplier.  Going all the way back to when the afterburner was originally added ( https://github.com/endless-sky/endless-sky/commit/d88e716f88a2ea7c43f02a834e25783c297341b7 ), there was always a 0.5 multiplier in the position function just above what is being suggested here.

**Comment by Zitchas** [comment]
Anyone know why that modifier was removed?

**Comment by djlad** [comment]
I think commit [d88e716](https://github.com/endless-sky/endless-sky/commit/d88e716f88a2ea7c43f02a834e25783c297341b7) addresses a different issue. It is adding `.5 * zoom`, but this issue is solved by adding `.5 * velocity`.

I found out what was changing the afterburner `Visual` position. It was this [line](https://github.com/endless-sky/endless-sky/blob/938f68dec84d8e9f0f9bbb97299ed7c0e2c3cba4/source/BatchDrawList.cpp#L58) in the draw function for visuals:

image

Here is where the additional `.5 * velocity` was coming from. It didn't affect game state, which is why I didn't see it before. It's just drawing the effect `.5 * body.Velocity()` away from where the visual actually is.

Removing this `.5 * body.Velocity()` term fixes the issue, but it would affect other projectiles and `Visual` effects.  I really don't think this term is supposed to be here though.

**Pull request closed without merging**
