### PR TITLE
refactor: split korath ships.txt into ships and variants files

### PR DESCRIPTION
**Pull request by ravenshining**
**Refactor(Data)**

## Summary

This is the first five commits that belong to #6891 , plus an update to accommodate conflicts created by #6870 , to be merged prior to #6891 in order to avoid losing the history attached to one copy of a file.

These commits use a little git trickery to split `data/korath/korath ships.txt` into two files, `korath ships.txt` and `korath variants.txt`, in the following manner:
  - in two diverging commits, `korath ships.txt` is renamed to `korath variants.txt` and `copy`
  - the two commits are merged back together, creating two copies of the file both with the new names
  - the `copy` copy is renamed back to `korath ships.txt`
  - the redundant lines are stripped out from each file, so `korath ships.txt` contains only base ship definitions, and `korath variants.txt` contains only ship variants

They do not change any content, it is strictly a refactor, moving lines from one file to another.

Unfortunately, **a squash merge of these commits would destroy the history and blame of** `data/korath/korath variants.txt`, treating it as a new file with no history, authored entirely by the squash merge commit, rather than the rename that it really is, authored by many commits from various authors over the years.

Therefore, to preserve this history in `data/korath/korath variants.txt` and not only in `data/korath/korath ships.txt`, these commits must be merged via fast-forward (if done through the CLI) or via a merge commit (if done through GitHub's GUI).

History and blame that one would see if these commits, in #6891, are **squash merged**:
https://github.com/ravenshining/endless-sky/commits/mergetest/data/korath/korath%20variants.txt
https://github.com/ravenshining/endless-sky/blame/mergetest/data/korath/korath%20variants.txt

History and blame that one would see if this PR is merged via a **merge commit**:
https://github.com/ravenshining/endless-sky/commits/mergetest-2/data/korath/korath%20variants.txt
https://github.com/ravenshining/endless-sky/blame/mergetest-2/data/korath/korath%20variants.txt

## Do not squash merge this PR.

Either:
 - we accept these six or seven commits, or
 - we close this PR and erase the history of `data/korath/korath variants.txt` when #6891 is squash merged.

In either case, `data/korath/korath ships.txt` will remain unaffected.

### CODE REVIEW

**Comment by Amazinite** [comment]
I don't think we should be worrying ourselves and jumping through extra hoops to maintain blames and histories on lines whenever we split files. It's not something we've ever done before, and it sounds to me like it'd be a hassle to have it be something we start doing and start expecting of content creators to do.

Not doing this doesn't completely destroy the blame and history of the content; whenever I'm going through a file's blame or history, if at any point the file was split and I'm looking at the new file that was made and therefore doesn't have the "proper" blame and history, I just go to the parent commit of the commit that created the file, then keep searching from there. That is a comparatively small hurdle to overcome for people who are searching the blame and history of files as compared to asking content creators to copy and strip files as you've done, then asking maintainers to commit merge instead of squash merge, which is what we always do and leads to a cleaner commit history on the master branch.

**Comment by ravenshining** [comment]
Alright.  I was just making sure I had all my is dotted and ts crossed :-)

Just to be sure, aside from "don't expect others to do this," which is totally understandable, the takeaway I'm getting is, "preserving this isn't worth the extra commits, and I should close this?"

**Comment by Amazinite** [comment]
Yup.

**Comment by MasterOfGrey** [comment]
> That is a comparatively small hurdle to overcome for people who are searching the blame and history of files as compared to asking content creators to copy and strip files as you've done.

While I get this, can I just clarify; even though it's obviously a bar that we don't *expect* content creators to leap, are we now explicitly saying that there is no value to doing so?

**Comment by Amazinite** [comment]
Not that there is no value in it, but I see minimal value in doing so, since as I said one can just go to the parent commit of the commit that split the files to continue searching the blame and file history from there, which is just a few extra clicks.

**Comment by MasterOfGrey** [comment]
I get that, my point is:
Since it is already done, and in this case done cleanly in a minimal number of commits - if we close this we are explicitly stating that there is no value to doing so for us.

I just wanted to check that that was indeed the position the project was taking on the matter.

**Comment by ravenshining** [comment]
Perhaps for larger, more important files, it might be worthwhile.  `data/map.txt`, for example.

**Comment by MasterOfGrey** [comment]
image
Happy to explain on Discord if you want.

**Pull request closed without merging**
