### PR TITLE
small typo fix

### PR DESCRIPTION
**Pull request by KiLEdEnNis**
or is it "it would be likely"?

### CODE REVIEW

**Comment by gunqqer** [comment]
I think "it would be likely" is correct. The current "it's" doesn't sound right

**Comment by Amazinite** [comment]
Correct as is.

**Comment by KiLEdEnNis** [comment]
how is "Alondo thought it likely that some pirates" correct?
I can change it to the would be likely thing that @gunqqer also thinks is better, but I doubt the base game version is right

**Comment by MessyMix** [comment]
Correct as is.

If it aint broke, don't fix it!

/close

**Comment by KiLEdEnNis** [comment]
if both of you say so, then sure
but care to drop a link or whatever? since I really have no idea why it's right

**Comment by MessyMix** [comment]
Okay. @KiLEdEnNis just for you xD

You say, "I find your paper interesting". You don't say, "I find your paper is interesting". The same would hold for past tense. "I found your paper interesting. You don't say, "I found your paper is interesting".

Now, take a look at what the text says. "Alondo thought it likely [...]" versus "Alondo thought it is likely [...]". Same deal here. The former is correct.

**Comment by KiLEdEnNis** [comment]
would "Alondo thinks it likely" be correct too then?

**Comment by MessyMix** [comment]
@KiLEdEnNis, yes, but MZ uses past tense.

**Pull request closed without merging**
