### PR TITLE
Pirate jobs

### PR DESCRIPTION
**Pull request by Amazinite**
This is a continuation of #1935. I've split the previous pirate jobs PR up because it was too big and had some pretty wild changes in it (e.g. selling passengers into slavery) which I will introduce in seperate PRs. This PR contains only the generic pirate jobs from #1935, excluding any of the selling your passengers into slavery job and the fake ID job that allowed you to reset your reputation with certain governments.

<hr/>
Jobs available on pirate planets. Most of which are in some way illegal, either through the cargo you carry or through requiring you to attack merchants and law enforcement, and they are only offered to you if you have a high enough reputation with pirates or if you have proven yourself to them through having a high combat rating.

Instead of increasing job payments by increasing sizes, Pirate jobs are worth more per ton/passenger than other jobs. This is to give them some sort of appeal given how low-profit they would otherwise be from fines or how dangerous they can be from being hostile toward most of human space. These jobs pay anywhere from 33.3% to 150% more for cargo related missions and 100% to 166.6% more for passenger missions (and 566.6% more for the rare highly wanted passenger missions, which is transporting a single passenger with NPCs deployed to either scan you or take you down). Escort missions pay twice as much as their legal counterparts of the same size due to how every merchant becomes an enemy to your escort.

Contains:
* 65 total jobs that can be offered on pirate planets.
* 3 space port planetary defense missions.
* 2 invisible missions that trigger bounty hunters to come after you if you are hated by law enforcement.
* Some new pirate hails that relate to the jobs.

The new jobs: 
* Cargo Smuggling (0 through 3): Smuggle illegal cargo from pirate worlds into law enforced space. 
* Drug Running (0 through 3): Smuggle illegal drugs from pirate worlds into law enforced space. Fines and pay are bigger than transporting cargo.
* Bulk versions of the previous two jobs (0 through 2): Bigger cargo, bigger fines, and more distance to travel.
* Stealth versions of the previous job types (2 per region: north, south, and core): If scanned during the job, the job is failed and a hefty fine is placed on the player. Spawns law enforcement with scanners to track down the player (also adds Quicksilver and Bastion scanner variants for this mission).
* Wanted Passengers (0 through 3): transport wanted criminals across law enforced space. Being scanned results in a failure. These missions do not spawn NPCs with scanners. 
* Highly Wanted Passenger (3 regional jobs): transport a passenger who is wanted across the galaxy, namely for stealing stuff from the government. Spawns NPCs with scanners to track down the player and their cargo.
* Slave Transport (0 through 2) and bulk versions (0 and 1): transport slaves across the galaxy from pirate planet to pirate planet. Slavery is highly illegal throughout the galaxy, and thus getting caught is considered an atrocity.
* Mercenary Jobs: The pirate version of escort jobs. Comes in 2 flavors: normal escorting and escorting stolen ships. There are two normal escorting jobs per region (entitled `Protection to <planet>` and `Protect cargo to <planet>`) and one stolen ship escort per region (entitled `Protect ship to <planet>`) which involves the player escorting a large warship and their stolen freighter or transport ship.
  * These jobs do not spawn many NPCs to fight given that most fleets that you come across will already be hostile to your escorts.
* Eliminating Targets: The pirate version of bounty missions. 5 different jobs per region. There are 3 types: competition (which comes in small and large), law enforcement (also comes in small and large), and merchant raids. 
* Regional Pirate Defense: the flipside of the pirate attack missions, where instead you are the pirate defending against regional law enforcement. 
* Cargo Theft: A local warlord is interested in some cargo being transported by a merchant convoy nearby. Attack the convoy and board the target ship, stealing its secret cargo before blowing it out of the stars and returning to the pirate world.

Other Changes:
* Adds a bunch of illegal cargo and drug commodities.
* Changes the drug names mentioned in a friendly pirate hail to match the new drugs and adds a new hail with pirates giving drugs a bad review.
* If your reputation with any law enforcement is too low, there is a chance that they will send bounty hunters after you on landing. There is a smaller version of a few interceptors when you hit -10 and a larger version of a heavy warship and either one medium warship or two light warships after you hit -200. This does not occur during the war.

I got a little bit of help from ~~@OmegaLokkes~~ @Kryes-Omega for a few of the jobs at first, and @Bladewood, @Wrzlprnft, @Disiuze, @Pointedstick, @kaylara, and @comnom all contributed commodity names.

### CODE REVIEW

**Comment by Amazinite** [comment]
Keep or trash?: The ransom jobs. I don't really like how they play out (I imagine them being confusing to some players), and in the end it doesn't really make sense for the law enforcement to attack the player if they really are carrying someone who is suppose to be given over for ransom. Should I just trash the dangerous half of the jobs and keep the safe half, making it a rare job that pays well?

**Comment by Forlarren** [comment]
Ransom should have a chance to go bad at the exchange. Getting away should be the challenge, since you no longer have your insurance aboard.

And maybe a very rare chance that you anger a family member "with a particular set of skills" and a "bounty hunter" harries the player every step of the way. Something like a 1% chance. If they board the players ship it should be bad, really bad.

**Comment by Forlarren** [comment]
I'm going to make a separate post here and it's going in my personal notes, I'm maybe half way to getting how to do these mods. Actually I'm procrastinating learning git... anyway...

A model for a crime and punishment system.

Win or lose if a player "gets caught" (mission dependent), there should be some consequence based on the crime, either a fine they can pay or try to escape.

Republic worlds might use a system much like the modern US. They announce via a quest trigger something like "Capitan so and so of the vessel such and such, hereby serving you a warrant for (whatever they did), stand down and prepare to be boarded...

If it's just a fine you pay it then and there. If it's a death warrant you better fight though, giving up is losing.

I'm thinking about taking an idea from THX 1138 here, warrants should run out according to cost. Blow up enough retrievers and they give up. As long as you only blow up retrievers it shouldn't hurt your reputation. Reputation is more for politics than simple crime. Governments shouldn't care politically about a little crime as long as it doesn't affect military operations.

The idea is there is a pot of money, a "budget" for every police action. Ships keep getting bought from the budget until it runs out and the contract is canceled. Bigger the budget bigger the problem.

The actual quest logic wouldn't bother but that's the explanation. The real quest logic would be two to four ambushes they have to wipe out before being clear based on their combat rating. Just don't tell them that. Bureaucratic court systems are obtuse and capricious no explanation necessary.

The Syndicate just change the flavor to corporate gangsters. If you break the "law" somewhere there is someone that considered whatever you took **his** property and you personally insulted him/her/whatever. Same concept you can pay off your debt and all is forgiven, or you get enforcers.

Maybe the first one's AI is to disable and board, where the player gets a "meet here and bring the money" timed quest.

Miss the deadline they send a contract killer.

Contract killer fails, depending on the size of the insult (fine size) whoever's problem you are comes after you personally. Disable and board that guy's ship to earn your rep back, or blow him up, costs reputation but the quest missions stop coming after you.

Bigger the "insult" the more escalating layers. Also the cost to pay off the "insult" doubles each time you don't have the money or you kill a collector/enforcer.

Rim and Dirt Belt should have a loose Federal Martial system. Basically those "Wanted: Dead or Alive" with a reward for retrieval. Well the dead part was only for the really bad guys.

Martials can swing all sorts of ways is the interesting part.

Some wear a white hat and will announce themselves, demand you stand down and escort them to the world you broke the law (timed, no dilly dallying), pay the fine and you are on your way. Since the governments are looser knit and less staffed "good guys" try to make things easiest on everyone. Shiny white knights.

Or you could roll a black hat. Shoots first, shoots more later, then maybe asks questions. Tries to board you and demand double to make him go away. Trick to this mission is you have to kill the Martial but do not kill the deputy. Race back to where you owe the court and pay it (timed), and you can even get a reputation bonus (everyone likes the honorable rapscallion).

Or get away and "lay low" long enough. Maybe give that one planet no landing clearance until the fine is payed or time runs out for small crimes and hostile unless fine is payed for big crimes.

All missions should have a statute of limitations, but like a half life system, after a week if you can just avoid scans (I don't know if that's possible, will look into it) in their territory (or shorter or longer for game play) and another week consequences just go away so main quests don't break. The universe is a busy place and as a starship captain and a member of the ultra rich class, there are rules for thee and rules for me (aka it has to be fun).

Just a concept. Feel free to ignore. Posted here just in case someone wants to get to it before I take a swing. I still have to actually play the plot.

**Comment by Pointedstick** [comment]
@Forlarren Those are interesting ideas, but it's considered a bit rude to hijack someone's issue or pull request with your own voluminous semi-related thoughts like that. This isn't a forum. I'd like to see some of those ideas implemented, but this PR isn't the right place to talk about them. The right approach is to try your hand at implementing your ideas, and if you wind bugs or missing features that are getting in your way, then open specific issues or PRs to fix them in a narrow, targeted manner.

**Comment by Amazinite** [comment]
Removing the ransom jobs. Here's my reasoning:
1) a person's weight in credits when a single chip can be worth billions doesn't make sense. That could be rewritten but then there's the complaint that you still have the passenger space taken up on the return trip.
2) they force otherwise peaceful players into fighting law enforcement
3) they aren't dynamic

**Comment by Amazinite** [comment]
I feel that this is pretty polished as is for now. 

I've reduced the payment on a lot of the jobs so they aren't so outrageously better than non-pirate jobs. Cargo and passenger jobs are now generally anywhere from 33.3% to 150% better in terms of payment than their legal counterparts. The bigger the pay, the bigger the fine, and even a single fine will take out most if not all of your profit on shorter jobs, and leave you with a lot less on longer jobs (or with nothing if the job fails on scan). Slave transfer jobs, which can leave you dead when scanned, are 166.6% better than normal passenger jobs, and highly wanted passenger jobs (transporting 1 passenger) are 666.6% better than normal jobs (of the same size), but with massive fines to go with them.

**Comment by endless-sky** [comment]
I'm wondering if there's a better way to do the `"Target <government>"` ships. Having them show up as a different government seems messy, and if you're a pirate it's likely that at least some of those governments are hostile to you so you're going to have to sort through all ships in system to find your true targets anyway.

**Comment by endless-sky** [comment]
I've added a "target" personality that lets you mark a mission target so it will stand out on the radar (flashing white) and be labeled as a "mission target" in the target info. (ee91ad9) I think that's a better approach than having a separate government for the target ships.

**Comment by Amazinite** [comment]
Thanks.

**Comment by Amazinite** [comment]
🎆

**Comment by jafdy** [comment]
Nice going @Amazinite this should be an interesting addition.

**Comment by Amazinite** [comment]
@endless-sky Just so I can know if I should go ahead with polishing and PRing the rest of what was in #1935, would you want those fake ID and/or selling passengers into slavery jobs? I'm just going to list some of the stuff I had written down for how I needed to polish the selling passengers missions:
* Have the first time you land on a pirate planet with passengers require the player to choose to walk up to a pirate slaver. From there on out, pirate slavers would approach the player.
* By extension, the chances of finding a slaver in the spaceport increases with the number of slaves the player has sold.
* Create a job where the player can release slaves without having sold slaves before, as the current releasing slaves jobs requires the player to have sold slaves in the past.
* Rewrite the `on offer` conversations to have no repetition between different missions. Possibly include branches that change the conversation based on how many times you've sold slaves.

My only concerns with the selling passenger jobs right now are that 1) #1938 is an issue, and 2) the missions have to have a static payment that I'm basing off of the average number of passengers that a certain passenger job will give you instead of scaling with the number of passengers you have, meaning that sometimes you get overpaid and sometimes you get unerpaid per passenger sold.

**Pull request merged**
