### PR TITLE
enhancement: New planet attributes to control Jobs/Trade/Crew/Bank availability

### LINKED ISSUE #666: Can visit shipyard, hire crew, trade with wanderers before being able to communicate?
It seems to me that all of these features should be disabled upon landing on the first Wanderer world, currently they are all available.

### PR DESCRIPTION
**Pull request by tehhowch**
This is a touchup of #951 by @jmhorjus to bring it up to speed with the current repo and resolve the merge conflicts. 

Closes #951 
Closes #666
Allows #1722 to be addressed fully.

Addition of these attributes allows significantly more flexibility to content creators.
 - "no " + (trading / jobs / banking / crew)
The "no ____" attributes let the content creator prevent the player from accessing a planets Trading, Crew, Bank, Jobs even while the player has access to the planet.
    - "no crew" will only prevent the player from hiring additional crew for boarding purposes (undermanned ships are replenished as desired).
 - language _____
Use of the "language _____" tag allows creators to condition services on some event that teaches the local language. If `language _____` is specified in the planet description, it supersedes the value inherited from the local government (may be useful for systems that swap governments due to hostile takeovers, as the planet likely still speaks the original language, at least for some amount of time).

### CODE REVIEW

**Comment by EndrosG** [comment]
Just for clarification: this implementation mostly uses the planet attributes list, correct?
So, while for other planet stuff we can write events like
```
event "nerf the earf!"
	planet Earth
		spaceport clear
		shipyard clear
		outfitter clear
		language "quarg backwards"
```
We will need to specify a complete new list of attributes of that planet if we want to change any particular access condition.
Personally, I find it already "difficult" from the point of view of a content creator to keep track of planet conditions when these get changed by multiple events.
Not having any string operations available as content creator (like "existing attributes" + "no jobs" , or "existing attributes" - "tourism") to perform some delta operations feels getting more and more complex with more and more functional attributes. Som attributes, like "uninhabited" have codewise functions, while others only feature certain content like "urban" or "tourism" (--> allowing for certain jobs).

I think I will come up with a solution for that with a separate PR.

**Comment by EndrosG** [comment]
My PR #2548 is up. :-)

**Comment by tehhowch** [comment]
I've reconciled the conflicts caused by the recent attributes interface update, and also decided to remove the `language` feature as it
1) did not match the new interface style (key/valueindex)
2) could/should probably support the add/remove functionality as with other planet 'attributes'
3) Was not continued to be used by MZ for Coalition as it was for Wanderers
4) because of 3), all planets of governments with a declared language in governments.txt but no "language: X" in the player's save would not offer "complex" services such as banking, hiring crew, or jobs.

Having removed that separate functionality, all planets offer the correct services as expected based on map.txt and the additions from each players cumulative event tree.


To demonstrate the use of the new attributes, I have a test missions file which usees the new interface and applies the attributes to a Coalition world (Mystery).
[pr2543_testmissions.txt](https://github.com/endless-sky/endless-sky/files/1034946/pr2543_testmissions.txt)

**Comment by endless-sky** [comment]
In my opinion, the gameplay advantage of allowing the player to count on all the basic services being available on any inhabited world outweigh the realism advantage of allowing certain worlds to not offer those services. (Note in particular that if you wanted to make this change in a consistent way, you would have to block auto-rehiring of crew on worlds with no hiring option.)

**Comment by Zitchas** [comment]
I didn't know this PR was a thing until today, but that being said, I really like the looks of it. Realism aside, I think having the various "No trading/jobs/banking/etc" really opens up the potential diversity of planets and plotlines.

For example, Esquiline (in the Remnant storyline) starts as an uninhabited gas giant and it's only option is to jump to fully functional station with all services. While that might be the end goal, I'd much rather have it go through a few intermediary steps where the station gains jobs, then trading, then everything. 

Actually, I'd love to have an intermediary step to that: Where the trading will buy everything but not sell anything. For small colonies and stations in particular they might love to buy everything the player brings them, but doesn't have any exports for the player to buy.

**Pull request closed without merging**
