### PR TITLE
Buff Heliarch ships' Ion and Scramble protection values

### PR DESCRIPTION
**Pull request by Arachi-Lover**
----------------------
**Balance*

## Summary
Times 5 for the existing values, and also adds .2 protection for the Fighters.

### CODE REVIEW

**Comment by Saugia** [comment]
Is there a reasoning that you're buffing these protection values by 5x? Preferably in the PR description, explain why you're buffing something and related content following it.

**Review by Zitchas — CHANGES_REQUESTED** [review]
These values are excessive and unjustified in both lore and gameplay, and are this unsuitable.

**Comment by EjoThims** [comment]
This scale of jump would be extraordinary even in resistance, but in protection seems especially ludicrous.

"a total value of 1 will cut incoming damage in half"

I agree this needs steep justification for both lore and gameplay perspectives, especially in regards to why, across the galaxy, any new and different developments from any species or factions on those fronts will just always be half as effective (or even -less-) against these Heliarch ships.

And even if those justifications hold up, if the entirety of them is actually Quarg specific, the resulting changes should instead be in resistance values paired to whatever desired % of these Quarg damage values instead of through buffing the upfront negation provided by protection.

**Comment by Arachi-Lover** [comment]
Given the Quarg rebalance project's still ongoing, I'll have this closed and maybe revisit the idea depending on what their stats are once finalized, and how they match up against Heliarch warships.

**Pull request closed without merging**
