### PR TITLE
Fixed display of floatsam tons and name case

### PR DESCRIPTION
**Pull request by Rakete1111**
This fixes the issues addressed in #1450 

- Amount of floatsam instead of tons is printed
- Name is lowercased, which maybe isn't ideal for some collectibles?

If there is anything wrong, please comment :)

### CODE REVIEW

**Comment by Amazinite** [comment]
This only works properly if you pick up >1 items of a non-1 mass.
d022d1bd54764d8db249c894d66303d9
I only picked up duplicates of two things; the tiny batteries and the Ramscoop, and both are 7.5 tons of mass, and those were also the only two that had the proper mass shown (aside from the 1 ton scrap metal pieces).
1088871f4a474b3090c479afce2581d7

**Comment by Rakete1111** [comment]
@Amazinite Oops, how did I miss that :) I fixed it, and reverted the name case change.

**Comment by Amazinite** [comment]
It doesn't work with decimal values (not sure how important that would be) but otherwise it works great. :)

**Comment by Rakete1111** [comment]
@Amazinite Decimal values? Can you really have half a ton of something? Or did you mean something else?

**Comment by Amazinite** [comment]
Yes, decimal masses are possible. A vanilla example would be ammunition.

**Comment by Rakete1111** [comment]
I messed up, I'll open it again.

**Pull request closed without merging**
