### PR TITLE
Documentation issue requires checking for duplicates 

### LINKED ISSUE #9479: Suggestion: Add request to check for duplicates to documentation issue templates
### Location

documentation/feature request issue template

### Describe the issue

I noticed after another duplicate was posted that the template for feature requests and documentation issues doesn't ask to check for duplicates. This is unlike the bug report template, which does ask to check for duplicates. As a result, newcomers to bug reporting may not know to check for duplicates, leading to potentially many feature requests and/or documentation issues that are duplicates of each other.

(I checked for duplicates of this issue myself)

EDIT: It looks like the feature request template does ask to check for duplicates. It doesn't make this a checkbox which means people (like me apparently) may skip over it. At the same time, I have seen people post duplicates anyways even with a checkbox in other repos, so this may not be necessary. The documentation issue template should still be updated, though.

### Expected content

I think that the templates for ~~feature request and~~ documentation issues should ask to check for duplicates, just like the bug report ones.

EDIT: I noticed that the CONTRIBUTING.md file asks to check for duplicates for issues. However, the readme file that  everyone would see seems to imply that this is for developers, and people may not think that posting a feature request or documentation issue makes them a developer. Otherwise, this file is hidden in the "docs" folder and its name also doesn't suggest that it should be read by those posting feature requests/documentation issues. An alternative approach is to therefore update the readme file to suggest that people posting to issues should also read the CONTRIBUTING.md file.

### PR DESCRIPTION
**Pull request by TheGiraffe3**
**Issue Template Fix**

Fixes #9479.

## Summary
In the documentation issue template you are now required to check the box that says "I have searched the existing issues".

## Screenshots
None

## Usage examples
N/A

## Testing Done
Changed the default branch of my repository to `patch-1` and confirmed that the checkbox was shown.

## Save File
This save file can be used to test these changes:
N/A

## Artwork Checklist
N/A

## Wiki Update
I doubt it.

## Performance Impact
N/A

### CODE REVIEW

**Comment by TomGoodIdea** [comment]
Shouldn't we redirect to the wiki repo for documentation issues?

**Comment by warp-core** [comment]
> Shouldn't we redirect to the wiki repo for documentation issues?

This repository does have some of own documentation such as the readme, build instructions, even code comments are a form of documentation, and probably some other stuff. And, unless I forgot, the instructions when opening an issue should already be directing people with wiki issues to the wiki repository.

**Comment by TheGiraffe3** [comment]
So shall I change this to delete that template?

**Comment by TheGiraffe3** [comment]
They do.

**Review by ziproot — APPROVED** [review]

**Review by tibetiroka — APPROVED** [review]

**Pull request merged**
