### PR TITLE
added Gatling gun

### PR DESCRIPTION
**Pull request by LocalGod79**
this tiny ammo weapon was conceived, discussed and developed on Steam. it aims to add more available Missile tactics to Fighters and Drones and their Carriers.

forum moderator collaboration;
@Wrzlprnft, @Amazinite 

@endless-sky i’m not totally sure about the copyright for the bullets/hit effect.

follow-up to #1295

one commit.

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
The copyright might create merge issues with the hai carrier pull at merging.

**Comment by endless-sky** [comment]
Why so many animation frames for the bullet? After the first one, they all look identical. So, you could just use a "no repeat" animation and only supply the first two frames.

Also, could you clean up extra modifications to the variants.txt file (deleting whitespace)?

Do you have @2x sprites?

**Comment by LocalGod79** [comment]
we have @2x sprites; in the usual spot:
https://drive.google.com/folderview?id=0B92_vuqiHabWYVlTaU5FRkR3M1k&usp=sharing

this weapon has been in development in public on the Steam discussion for almost a week and a half.

normally "tracers" are fired every fifth round, but i found this effect to be less satisfactory.  with the current number of frames, ~1 in 7 bullets is a tracer, and and all bullets are remain unchanged so for their entire lifetime.

i spent quite a bit of time optimizing the combat appearance/behaviour of this weapon - from using a submunition to render a better "firing effect", the ideal number of non-tracer projectiles, "random velocity" and "random lifetime" number - and whether to have an active frame rate (we tried a few) so that tracers would randomly ignite and extinguish, or the current "full lifetime frame".

i believe you'll also be happy with all of it, including the hit effect.

is there a better way to specify a different sprite for every ~7th projectile, so that we could use only two sprites?

**Comment by LocalGod79** [comment]
@Wrzlprnft it may, but i think Solifuge/Violin Scorpion might be easier to resolve than this one - believe me when i say keeping this one all straight was a challenge the first time around (especially since the icon was rendered almost a week ago).

**Comment by LocalGod79** [comment]
to further elaborate on this weapon:
the mass of bullets in a stream is theoretically enough to fool an unmanned a.m.s. into firing on it (so bullets were given `"missile strength" 1`).  the bullets themselves vaporize on being struck, but there are so many of them (and in a nice spray), and presumably more fighters/small ships than the a.m.s. can cope with.  this will both sap energy and cooling resources of the target, as well as expose them to incoming heavier ordinance (controlled by the player).

balance tradeoffs for this fairly powerful package include:
• moral: the radioactive ammo is made by slave children!  will nobody think of the children?!
• availability: more often than not, reloading will involve bribing your way onto, or dominating a pirate world.
• cooldown: for every 3 seconds spent firing, one must cool down for 6.
• heat: comparatively high firing heat for this size/type of weapon.

**Comment by endless-sky** [comment]
The animation could use the new "delay" keyword: `delay 5` to have the first frame last 5 extra frames.

**Comment by LocalGod79** [comment]
@endless-sky i'm confused whether you're proposing using `"delay" 25`(their maximum possible lifetime) instead of `"frame rate" 1`, or proposing that tracers "burn out" after 5 frames (or another lifetime shorter than their max).

**Comment by endless-sky** [comment]
The "delay" attribute is the number of extra frames to wait in between cycles of the animation. So, to have 1/7 bullets use the bright frame you could supply two frames: the normal one as frame 0, and the bright one as frame 1. Then you could do this:

```
sprite "projectile/bullet"
    "delay" 5
    "frame rate" 0
    "randomize"
```

**Comment by LocalGod79** [comment]
i just tried this.  as expected, half of all bullets fired were tracers.

without randomize, an interesting fade in and out happened in the spray, but still: 50%.

no matter how we play with the frame rate, the engine has to work with the number of available animation frames, which determine the likelihood of a given sprite (the tracer, in this instance) will be chosen.

if there are only two sprites, the chances are 50% that the tracer sprite will be chosen.  when there are seven sprites, the effect is much more visually pleasing (as ~14% of bullets are tracers).

these sprites are super tiny, the collection of which are 1/4 of images/projectile/rainbow~0.png in VRAM - is this really an issue?

**Comment by endless-sky** [comment]
Sorry, it's actually "random start frame", not "randomize". And, the frame rate at the moment is required to be nonzero (although, I should change that). So:

```
		sprite "projectile/bullet"
			delay 5
			"frame rate" 0.01
			"random start frame"
```

But, at least on my monitor the non-tracer bullets are nearly impossible to see, which makes it look like the gun is only firing sporadically.

**Comment by LocalGod79** [comment]
i tried "randomize", and figured you meant "random start frame" when the error popped up.

i've tried every way i know of to use only two sprites to achieve the desired effect. this one needs all of the sprites.

the non tracer bullets appear as visibly as the background stars on my medium to low quality l.e.d. monitor, but these things have crazy contrast ratios and response times since my last monitor purchase.

if you fire "over" friendly ships or bright planetary objects, the non-tracer rounds are far more visible.  plus, the hit effect rain

i wish it were possible to specify every 7th bullet precisely, but i've explained the situation away in the ammunition description.

would a slightly lighter non-tracer projectile make you feel more comfortable with this weapon?  the intention was for the bullets to be difficult to see, rather than impossible.

**Comment by endless-sky** [comment]
Are you using the latest code? I tested the code I posted above with only two frames of the sprite installed (with frame 1 being the bright one) and it worked for me.

**Comment by LocalGod79** [comment]
code is up to date.

i only get 50% with two sprites, no matter what i do...

**Comment by LocalGod79** [comment]
perhaps a more viable solution would be to have just the one sprite for the bullets, and a live effect that drops the single tracer sprite?

i'm not really familiar with effects in general, and live effects seem especially mysterious to me.

**Comment by LocalGod79** [comment]
sorry - finally got it to work - will update this pull shortly.

excuse: Hai Drone carrier is nearing completion (Hai need more power with less personnel to contain Unfettered Solifuge/Violin Spider threat); included is another entirely different tiny ammo weapon ("Rail Gun"), drone (Flea or Fairyfly - opinion?), medium warship drone carrier ("Pond Strider"), hai fuel cell (Sand Cell), and unified atomic engines similar to the X1050s ("Baellie").

co-ordinating a group of almost half a dozen individuals doing different components of that project is proving to be a more stressful challenge than expected, but i'm hoping that the educational value of the exercise will pay off with more balanced content from the modding community.

**Comment by mdsmestad** [comment]
I really hope this gets merged, I'm looking forward to seeing fighters armed with Gatling guns

**Comment by LocalGod79** [comment]
merged into #1284

**Pull request closed without merging**
