### PR TITLE
Feat(balance): Engine rebalance: flatter thruster scaling

### PR DESCRIPTION
**Pull request by Quantumshark**
**Content (Balance)**

Provides a solution, or at least an initial step towards one, for #5271, #4034 and a small step in the right direction on #8124.

## Summary
This PR makes smaller thrusters more powerful and makes the largest thrusters slightly less powerful.
The second largest thrusters in each full set, or the equivalent in incomplete sets (Type 4 radiant, Smelter-class etc.) are unchanged.
The other thrusters had their thrust tweaked so that the difference in thrust/ton between them and the second largest thrusters is halved, making the scaling flatter. There is still scaling, so big ships are still better off with big engines than with small ones, but that scaling is flatter, so small ships are now faster.
Ships themselves are unchanged, which means this change is compatible with old save files.

If you have your own engine sets, in a plugin or aimed for vanilla, and want help making this same adjustment to them, you can ask me and I'll do it.

For engines without any equivalent size thruster, such as the Coalition ones, the thrust was adjusted based on the changes to similarly-sized engines, keeping comparisons to different engine types intact.
Combined engines were compared to the combination of thruster and steering of the same group, with the exception of Ka'het engines, which were compared using the Telis engines as the baseline.

Steerings, afterburners, and the Vareti engine block are unchanged.
Steering is unchanged because the range of turning stats within which a ship is enjoyable to play is much narrower than the equivalent ranges for top speed and acceleration. Therefore, the extent to which turning varies with ship size should be much smaller than the extent to which top speed and acceleration do, and thus I think the current system of turning being largely invariant with ship size is OK.
I would be open to slightly buffing the smallest steering engines if the consensus is that that would be a good change, but I certainly don't think steering engines should be changed as much as thrusters.

Afterburners were unchanged because I don't think they would benefit from the same changes, and because they were rebalanced fairly recently, so are still arguably in a state of flux.
In the case of the Korath afterburners, the Asteroid-class is already an extremely useful outfit and amazingly good for its size, bordering on overpowered, while at the other end of the scale the sheer impracticality of the Stellar-class balances out its higher theoretical strength.
There's nothing else that the Bellows-class can be compared to, so there's really no way to go about calculating what the change to it would be. In any case, I think most would agree that it's not in need of a buff.
That just leaves the human afterburners, which I think are in a good state already.
If the general consensus is that I'm wrong about these things, I would be open to making similar changes to afterburners.

The Vareti engine block was unchanged because it's already weaker (in thrust/ton) than the Telis engines, which means it would have been buffed if I had applied the same method to it. The goal of this PR is not to make heavy warships faster, so that change has not been made.

## Save File
Any save file will work, as long as you're not using engines from a plugin.

### CODE REVIEW

**Comment by lumbar527** [comment]
Sounds great; I think we need to do something like this. Have you tested? I think I'll try this out.

**Comment by lumbar527** [comment]
> I would be open to slightly buffing the smallest steering engines if the consensus is that that would be a good change, but I certainly don't think steering engines should be changed as much as thrusters.

I think they should be changed some; you can get quick turn in your interceptor-Leviathan.

**Comment by Quantumshark** [comment]
> I think they should be changed some; you can get quick turn in your interceptor-Leviathan.

This PR isn't intended to make big ships slower on the whole. Most heavy warships don't actually use the largest size of thrusters, so it's only things like the Engines Marauder Falcon and Leviathan and some of the bigger Korath ships that are made slower in this PR, and even then only slightly. The changes here are instead primarily aimed at making small ships faster, hence why I took the second-largest size of engines as the standard to compare to.
Small ships don't need a significant buff to their turning - high turning gets quite unpleasant to control, and low turning is quite unpleasant too, so turning shouldn't vary that much with size.
Fighters could be an exception to this, because the expectation is that players won't use them - so they can get away with high mobility that most players would find awkward to control. So the smallest steerings could potentially be buffed, but I don't think making changes to steering that are the same as the changes made to thrusters here would be a good idea.

**Comment by lumbar527** [comment]
Yeah, I guess.

**Comment by Zitchas** [comment]
As an amusing aside: Low turning (as should be the norm on heavy ships) is a much more tolerable experience when they have a small amount of lateral and reverse thrust. It doesn't take much - just enough to handle stationkeeping - to negate the vast majority of the need for fast turning that most ships have.

**Comment by Quantumshark** [comment]
> As an amusing aside: Low turning (as should be the norm on heavy ships) is a much more tolerable experience when they have a small amount of lateral and reverse thrust. It doesn't take much - just enough to handle stationkeeping - to negate the vast majority of the need for fast turning that most ships have.

That can be made to work on some ships, yes - the Emerald Sword, for example, doesn't feel nearly as sluggish as its 55 turning would suggest, and part of that is the reverse thrust. Another part of that is the fact that the sprite is so big that it _looks_ like it's turning pretty quickly even so, because the geometry means that the edges of the sprite are actually moving pretty quickly - the exact same handling stats _feel_ slower on a Leviathan, because you don't have that optical illusion making it look like it's turning more quickly than it is. The Emerald Sword is pretty close to the limit though - the reverse thrust certainly doesn't make the stock Bulk Freighter an enjoyable ship to pilot, for example.

**Comment by Hurleveur** [comment]
I think you missed a few big engines like the gegno and bunrodea ones? Or do they already obey to these new rules?

**Comment by Quantumshark** [comment]
> I think you missed a few big engines like the gegno and bunrodea ones? Or do they already obey to these new rules?

The largest Bunrodea thrusters are 55 tons, which puts them in the "large" rather than "huge" size category - similar to the planetary class, or the A5 human atomics. Like those engines, the Bunrodea ones are unchanged.
Likewise, the Gegno do not have "huge" thrusters, they only go up to "large".

**Review by Hurleveur — APPROVED** [review]
Balance is not my area but this seems to me like an elegant solution that indirectly improves small ships that really need it. I often find my small ships lack the speed to manoeuver around larger ships and choose where to engage.
The small nerf of the huge engines is more debatable but its not big enough to be a problem anyway.

**Comment by Quantumshark** [comment]
#6686 primarily changes the balance between different sets of engines. That balance is unchanged here - rather, the only thing that is touched is the scaling within each set.
#8080 (and the relevant changes in #6686) is the main thing I was referencing when I said that "Afterburners... were rebalanced fairly recently, so are still arguably in a state of flux."

#5779 is I think rather more relevant here, as one of its goals is a similar end result to the goal of this PR. I do think this PR is a better approach than the one taken in #5779, for a few reasons:
1. This PR is specifically tackling this one specific goal, rather than trying to do several different things at once. The cross-set balance changes in #5779 were addressed in #6686, which was merged, while #5779 was closed. I think breaking down these things into smaller functional units makes them much easier to test, easier to review, and easier to decide on whether or not they are a good idea.
2. This PR specifically changes outfit stats, not ship stats, and thus is fully compatible with old saves. #5779 mostly adjusted relative mobility between ship categories by editing ship stats, rather than outfit stats, and thus the changes would not have applied to old saves.

**Comment by Amazinite** [comment]
No changes to the reverse thrust of the Remnant thrusters to match the change to the forward thrust?

**Comment by Amazinite** [comment]
Red is Korath automata. Orange is Efreti. Circles are the old values, X's are the new values. X-axis is tonnage and Y-axis is thurst/ton.
The intention was for the Efreti engines to fill the gaps between the automata engines in terms of thrust/ton, but now the Efreti engine are at a similar thrust/ton compared to the automata engines in the same size category.
image

**Comment by Quantumshark** [comment]
> No changes to the reverse thrust of the Remnant thrusters to match the change to the forward thrust?

Good catch. I evidently missed that.

> Large: unchanged, except for Coalition being +16.8%

The Coalition large thrust module may be called large, but in terms of its size it fits much better among small engines. Likewise, the small thrust module is better described as "tiny" than "small" when comparing to other engines

> Red is Korath automata. Orange is Efreti. Circles are the old values, X's are the new values. X-axis is tonnage and Y-axis is thrust/ton. The intention was for the Efreti engines to fill the gaps between the automata engines in terms of thrust/ton, but now the Efreti engine are at a similar thrust/ton compared to the automata engines in the same size category for the first three sizes.

I think I can see how this happened, and by extension how to fix it. Essentially, taking the biggest Efreti engine as the base for that set has pushed up the smaller ones more than was done for the other Korath engines, because it's in effect half a size up from the Planetary.

**Comment by Amazinite** [comment]
> Combined engines were compared to the combination of thruster and steering of the same group

What exactly is meant by this? I'd expect the hybrid engines to get similar buffs to their thrust as the tiny engine of the same set. Instead, their bumps are closer to what small or medium thrusters received. except for with the Hai hybrid engine. (Ignoring the Ka'het engines, since those are fairly special case, and just focusing on the tiny hybrid engines.)
* X1050 Ion Engine: +14.6%
* Fission Engine: +12.5%
* Anvil-Class Engine: No change?
* Baellie Atomic Engine: +34.25% (biggest buff in this PR)
* Meteor Engine: +6.7%

**Comment by Quantumshark** [comment]
Ah. There's a mistake in the part of the spreadsheet I used to calculate those, which explains some of the oddness of the numbers.

It's worth noting that currently the meteor engines are slightly more powerful than a set of asteroid-class ones, and last I checked the Anvil is much stronger than the crucible and even than the forge (I also mistakenly thought it was stronger than the smelter, but that was due to the aforementioned spreadsheet mistake). Thus, applying this method would give those smaller buffs, particularly in the case of the Anvil.

**Comment by Quantumshark** [comment]
That should fix the combined engines. The Baellie seems to have already been correct, and seems to have received a similar proportional increase to the X1050, so I think that was right. As mentioned, the Anvil and Meteor ended up receiving smaller buffs, because they're not as weak compared to larger engines as other similarly-sized engines are.

**Comment by Amazinite** [comment]
Let's see how this works out for a bit. Steeper mass scaling is likely still something we want, but this should be a decent improvement for now.

**Comment by Quantumshark** [comment]
Just realised I missed the deprecated Korath thrusters.

**Comment by Hurleveur** [comment]
I dont think we have to modify any depreciated things

**Pull request merged**
