### PR TITLE
Renamed Scrapper and Mammoth sprite

### PR DESCRIPTION
**Pull request by 1010todd**
----------------------
**Content (Artwork / Missions / Jobs)**

## Summary
Renamed Scrapper and Mammoth sprite from `scrapper` => `pirate scrapper` and `mammoth` => `pirate mammoth` for better organization in `images` folder.

Might break some savefile but faster this is accepted less saves will be broken.

## Save File
This save file can be used to play through the new mission content:
N/A

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - ~~I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets:~~
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/339

### CODE REVIEW

**Comment by Hurleveur** [comment]
Not smth that should be done here necessarily but this gets me wondering if we should fix it for all factions

**Review by EjoThims — APPROVED** [review]
Better now than later.

**Review by Hurleveur — APPROVED** [review]

**Comment by Saugia** [comment]
Don't forget to update the copyright in the DPI PR too.

**Comment by Amazinite** [comment]
> Not smth that should be done here necessarily but this gets me wondering if we should fix it for all factions

Can't do that without giving people invisible ships.

**Comment by RisingLeaf** [comment]
> 

We need some mechanic that allows us to rename things without breaking stuff.
I propose:
```
rename
   oldname newname
```
and then add a check in datanode.Token()

Idk, but I think it would be nice to be able to do such things

**Review by Saugia — APPROVED** [review]

**Pull request merged**
