### PR TITLE
More Portraits

### PR DESCRIPTION
**Pull request by MCOfficer**
This PR adds 40 new portraits, including pictures of Arachs and Hai. All humans (except human106) have been added to news.txt.

This PR is somewhat of a WIP since i'm not 100% sure all of these are appropriate for the game - the perfect example being hai02, which is a bit over the top. Also, i don't know if the arach portraits line up with how you imagine them to look like.

All images are public domain. I plan to edit the copyright file once this is merge ready, so i don't have to amend it every time i remove an image.

Edit: in case anyone needs them, here are the [source files](http://endlesssky.mcofficer.me/portraits.zip).

### CODE REVIEW

**Comment by jafdy** [comment]
I think people will expect the Hai to look less like your garden variety squirrel. Maybe you need to add a hat or something or change the proportions a little.

**Comment by Amazinite** [comment]
Pretty much all of these have black pixelly edges around the people in them and some even have random black pixels out in the transparent space.
screen shot 2018-04-08 at 11 48 36 am

**Comment by MCOfficer** [comment]
turns out the image conversion i used (irfan view batch processing) caused some artifacts, my source files are a-ok.
totally not my fault.

**Comment by Amazinite** [comment]
MUCH better.

**Comment by MCOfficer** [comment]
somewhat of a bump - do you need 2x versions for the hdpi plugin? if yes, i'll make (second) a PR for that.

**Comment by endless-sky** [comment]
I think I'd like to see how people react to the spaceport "news" system in the 0.9.9 release before adding more portraits. Currently it's just an "experimental" feature, and I suspect that a lot of people will dislike it.

**Comment by KiLEdEnNis** [comment]
2/3rd of the people that voted in the Discord voted against it (52 for 104 against), so yeah a lot of people will indeed dislike it

**Comment by Pointedstick** [comment]
Personally I'd vote to keep the feature itself, but remove the portraits.

**Comment by Amazinite** [comment]
Definitely. The feature itself is amazing, it's just the current portraits I'm iffy about. An alternative to completely removing the idea of showing an image would be to replace the current system with #3742.

**Comment by Pointedstick** [comment]
I strongly support #3742 too. :)

**Comment by MCOfficer** [comment]
yes, I was skeptical about the hai (especially that one), but hai00 is already a thing:
grafik

as for human104, unfortunately the original image is cropped like this. unless this is about his head being cut off, i don't see a problem - you'll never have a direct comparison anyways.

**Comment by Pointedstick** [comment]
I personally think human104 is okay, but I know @endless-sky wanted to keep a rough head size equivalency between all the portraits. So if the original can't be fixed, maybe remove it or replace it with another.

**Comment by Pointedstick** [comment]
Let me get real specific about what I'd like to see that would turn my Changes Requested status into Accepted:
- Remove the Hai with a hat or replace it with a Hai-without-a-hat image
- Change human104 to a new one with a smaller head that generally matches the other ones better.

I'll grudgingly accept the ~moose~ spider and squirrel images for now, but I still think that in order to make this work at all, we need an artist to make us some alien faces.

**Comment by MCOfficer** [comment]
i'm with you on the aliens, but so far that's all we have to work with. for now though, this PR is on hold, at least until the 0.9.9 feedback comes in and the future of the news system has been decided.

**Comment by Pointedstick** [comment]
I think it makes more sense to add them now. The news system is going to be released with 0.9.9 regardless, so we might as well have the maximum number of portraits for the launch. No need to hold back IMHO, especially for a feature that benefits so strongly from additional content.

**Comment by Pointedstick** [comment]
To be even clearer: if you make the requested changes, I'll merge this PR. :) More content for the news system can only help it make a better first impression.

**Comment by MCOfficer** [comment]
easy, cowboy, i didn't even start with the hdpi PR. will take a while

**Comment by endless-sky** [comment]
The current alien "portraits" were never meant to actually be displayed in-game. They were just meant to be a hint of what those species should look like (face structure, skin texture, etc.) in case we ever find an artist who wants to sketch some alien portraits.

**Comment by MCOfficer** [comment]
I just happened to stumble over this paper from nvidia: https://arxiv.org/pdf/1812.04948.pdf

If you don't want to dig through that (and get a major headache doing so), here's a TL;DR: They trained an AI to generate human portraits, and the results are impressive:
grafik

Leaving aside that this is pretty scary once you think about the implications, it might be possible to use this to generate portraits, or even to generate portraits on the fly. There have already been projects that generate portraits based on attributes (hat, brown hair, etc.), even though their results are still rather crude.

**Comment by Pointedstick** [comment]
Agreed!

**Pull request merged**
