### PR TITLE
Fix coalition campaign conditions

### PR DESCRIPTION
**Pull request by quyykk**
## Fix Details

Some conditions in the coalition campaign and related jobs were typo-ed.

### CODE REVIEW

**Review by Arachi-Lover — APPROVED** [review]

**Comment by quyykk** [comment]
@Arachi-Lover Another one but idk which one it's supposed to be https://github.com/endless-sky/endless-sky/blob/master/data/quarg/quarg%20missions.txt#L236

**Comment by Arachi-Lover** [comment]
That one's to offer should be just the first 2 `has` lines, then `not` for both having joined the Heliarchs and the Lunarium.

**Comment by quyykk** [comment]
like this?

**Comment by Arachi-Lover** [comment]
Yes, I *think* that should be good now.

**Comment by Saugia** [comment]
Anything else? Rest looks good.

**Comment by quyykk** [comment]
nope nothing left

**Review by Arachi-Lover — APPROVED** [review]

**Pull request merged**
