### PR TITLE
Moved the Strong Wind to the Wanderer licence

### PR DESCRIPTION
**Pull request by williaji**
## Summary
The Wanderers are an open handed trust culture. They provide food for the Unfettered to raid, they reach out the the Efreti, they provide a terraforming mind to the Mereti, and they disastrously invite the Exiles to assist with dealing with the Sestor. Regarding the Exiles,  "No," says Rek, "the leaders are right, we must offer them our trust until they prove utterly unworthy of it."

Yet, when it comes to the player, they restrict access to their repurposed exploration ship even though the player has fought beside them and assisted with their diplomacy for no direct financial compensation.

Additionally, the only thing actually restricted is the hull. The weapons systems and reactors needed to power them are available it the outfitter. At this point in the game, the player has access to several equivalent ships that can field those weapons systems and have turret mounts as well, so it's hard to see this being a problem with technology transfer.

Finally, there is a long lag time between license changes. And when the military license comes along it's simultaneous with the Tempest and followed in short order by the Derecho and the Hurricane. That means there is a long period when you might buy a Strong Wind, but can't, followed by a period where you can, but won't because there are better ships on offer.

## Save File
This save file can be used to play through the new mission content:
[Fred Flintstone.txt](https://github.com/endless-sky/endless-sky/files/8444300/Fred.Flintstone.txt)

## Testing Done
I played through with the attached save file. Screenshots below.

## UI Screenshots
Strong Wind license 2022-04-07_13-07-03
Stron Wind Outfitter_2022-04-07_13-09-30

### CODE REVIEW

**Comment by Amazinite** [comment]
Strong Wind FW playthrough here I come.

**Comment by Amazinite** [comment]
So the military Wanderer license is given by "Wanderers Solifuge Recon 2". This is two missions after "Wanderers Hai Assistance 3", which is when Tempests become purchasable. There are no outfits that require a military license, only the Tempest, Derecho, and Hurricane ships, meaning that, aside from the Strong Wind, the existence of this license only prevents you from purchasing anything for a meer two missions. I feel like with such a short time between when the first thing that even requires a military license becomes available and when you're given the military license, it almost might as well not even exist. So instead of switching the Strong Wind over to the normal Wanderer license, we should either do that plus extend the time between the Tempest being mass produced and the providing of the military license, OR we should provide the military license before the Tempest is available. Both such changes would require more story work than this, though.

**Comment by williaji** [comment]
@Amazinite There is actually a fair game time gap between the getting the Wanderer license and the start of the path the the Military license. This is the point where the Wanderer story line blocks on the free world. In addition, there is a 40 (day?) truce timer that runs. In my own experience, it's rare for me to stay in Wanderer space and run out that timer. I generally leave and come back later, which can be a long time if you pick up another faction thread.

While I agree that the military license is unnecessary, at least at this point in the game, (I could see future missions where the Efreti buy Wanderer ships since they have no domestic capacity as things stand). I didn't want to delve too deeply into re-working the story line. I also agree that there needs to be a gap on the ships coming on line. One of my early frustrations playing the Wanderers was that I'd just bought my Tempests when the Derecho came out and I was out of cash. The simplest way to do this would be to extend the truce timer. That requires no existing dialogue or story changes.

**Comment by Amazinite** [comment]
Well the Wanderer campaign isn't done and I think that what exists could be improved, so I'm not against making this change for now and improving the military license interaction later.

**Comment by Zitchas** [comment]
I'd say that this sounds like a good change, too. It'd be nice to have access to the Strong Wind longer. I've never been really fond of the Wanderer ship progression: It's really fast, and I always feel like I need to upgrade as soon as it is available. Having the Strong Wind available a little earlier would help quite a bit with this.

**Pull request merged**
