### PR TITLE
Center Pointedstick's Vanguard

### PR DESCRIPTION
**Pull request by czartrak**
This PR fixes the offset for Pointedstick's Vanguard

Thanks to @KiLEdEnNis for fixing the sprite

I will also add a PR to the High DPI mod to fix that one too

### CODE REVIEW

**Comment by KiLEdEnNis** [comment]
image
no idea what this is doing

**Comment by czartrak** [comment]
I don't either. The high DPI pr was fine

**Comment by MCOfficer** [comment]
your master hasn't been updated since 3 days before d65d0fb97e1c2b6b6001d88beabbcaf319c11f85, which changed this very image, that's why you get a merge conflict.

for future PRs, don't PR from master and update your branch before making changes.

**Comment by czartrak** [comment]
I'll close this while I resolve my out-of-date fork

**Pull request closed without merging**
