### PR TITLE
Dreadnought mk2

### PR DESCRIPTION
**Pull request by jafdy**
#1742

### CODE REVIEW

**Comment by Bladewood** [comment]
...no, wait, you still need to actually implement the new variant.

**Comment by jafdy** [comment]
That is . . . a good idea.

**Comment by jafdy** [comment]
It's possible to complete the campaign without making the stack core available.

**Comment by Bladewood** [comment]
oooh... I did not realize that...

**Comment by jafdy** [comment]
Not worth keeping up to date.

**Pull request closed without merging**
