### PR TITLE
feat: Also build CD on PRs

### PR DESCRIPTION
**Pull request by MCOfficer**
**Feature:** This PR implements enables CD builds on Pull Requests, so people can download and playtest PRs without having to compile.

## Feature Details
With this change, the CD workflow will run,
1. when a new commit is pushed to the master branch
2. when a PR is opened
3. when new commit are added to a PR

In the case of 1), artifacts will be published to the `continuous` release. For PRs, artifacts can be downloaded from the "Checks" tab:
https://gfycat.com/annualtintedcopepod

The download is still only available for logged-in users: https://github.com/actions/upload-artifact/issues/51

## Testing Done
Tested on a multitude of PRs. As far as i can tell, this change needs to be in the head branch, so this will not work for old PRs until they merge master.

## Follow-up features:
Post a comment on the PR with links to the assets. Unfortunately, Github's Actions API is still somewhat immature, so this would require querying and parsing the Github API. There is a nice action for "Sticky" comments, though: https://github.com/marocchino/sticky-pull-request-comment

### CODE REVIEW

**Comment by MCOfficer** [comment]
Here's some more incentive: (If a PR includes this change,) everyone can playtest it with minimal effort.

 
I already implemented this into the [ESLauncher2](https://github.com/EndlessSkyCommunity/ESLauncher2) prototype. It uses a [workaround](https://endlesssky.mcofficer.me/artifacts.html) to download artifacts despite not having a Github account:
ESLauncher2-PR-Demo

**Comment by tehhowch** [comment]
Sounds reasonable. Since we'll be doing more on each commit there are some things we should also do:
1. shared prefix (e.g. `cd` or `pkg`) for CD jobs
2. indicate compatibility (e.g. MacOS 10.15) where needed.
3. Cancel pending / running workflows whenever a new commit is added to a PR, to avoid redundant work. I think this will require using the REST API: https://developer.github.com/v3/actions

**Comment by MCOfficer** [comment]
I don't get 1). The workflow is named "CD", and all jobs reference their workflow.
image

2) i agree with, but i'm not sure where to put in a PR. It's easy once actions can post to the PR, but as i said, actions/upload-artifact#51. We can at least mark it on the releases page, but that has little to do with this PR (rather #5013).

3) Is reasonable.

**Comment by tehhowch** [comment]
I suggested 1 due to the mobile page view: 
<details><summary>screen cap</summary>


Screenshot_20200427-140010
</details>

For 2 I was thinking to just name the output accordingly.

**Comment by tehhowch** [comment]
We can add run cancelling as a follow-up.

**Pull request merged**
