### PR TITLE
As the commit details this fixes a divide by zero error

### PR DESCRIPTION
**Pull request by zwparchman**

### CODE REVIEW

**Comment by zwparchman** [comment]
Your style fix has been applied. 

I just found it after enabling floating point exceptions while working on #1969. I wasn't chasing it, and it is unrelated to what I was working on.

**Comment by Elyssaen** [comment]
Good find, anyway! I was just saying I glanced at the code only briefly, and don't know what it's actually doing. I'll leave that to somebody else. :  )

By the way, I don't know how much it bothers others to have the merge commit clutter, but if you don't know, git rebase is pretty helpful to keep the commit history tidy. I got some advice on it [here](http://stackoverflow.com/questions/41433318/switching-git-workflow-from-merge-to-rebase-how-to-clean-up-a-merge-commit-hist) just today to clean up my own branches.

**Comment by Elyssaen** [comment]
Particularly, I wasn't sure why it was set to Point(0,1), and I hadn't looked at the lines around it. Looking at it a little more, this is clearly the code that creates a unit vector. 

Would you mind explaining why we need a null vector to have a unit vector of (0,1)? Depending on how it's used elsewhere I could see that it might be safer to make sure the unit vector _does_ have unit length, even if it's in an arbitrary direction. Is that why?

**Comment by zwparchman** [comment]
You guessed it. The function currently will return (Nan,Nan) when the 0 vector is passed in. I'd be surprised if (0,1) breaks anything since Nan is infectious and it would be breaking math everywhere.

**Comment by Elyssaen** [comment]
What I mean is more, why not return Point(0,0) as the unit vector of (0,0)? The unit vector of a null vector isn't really defined, but is it better to set it to an arbitrary unit vector like (0,1) than to set it back to the null vector?

I quickly tried to find an example of this Unit() function being used so we could talk about what a unit vector of (0,1) for a base vector of (0,0) would do in practice, but haven't yet found an example that is possible: the uses I've looked at so far don't let (0,0) go into the function anyway. Is there any time in the code that Unit() can divide by zero in practice?

**Comment by zwparchman** [comment]
In the git commit I mention the function. Thee following is a copy paste from there.

Specifically AI::KeepStation managed to subtract 2 non zero vectors of
equal magnitude, but opposite direction.

**Comment by zwparchman** [comment]
If you want to reproduce it it took 5-10 minutes of fighting in 1 system with the code modified to allow floating point exceptions.

**Comment by endless-sky** [comment]
This would only affect non-vectorized builds. I've checked in an alternative (9b79494) that alters the vectorized code as well.

**Pull request closed without merging**
