### PR TITLE
Add reworked models of the Republic Navy ships

### PR DESCRIPTION
**Pull request by JanErikAhrens**
## Summary
Reworked the models and images of the Carrier, Cruiser, Frigate, Gunboat, Lance and Rainmaker. For the Rainmaker in particular, this also envolves slight changes to the hardpoints.

## Save File
This save file can be used to view the reworked models:
[Aaron Zuhl~Navy tests.txt](https://github.com/endless-sky/endless-sky/files/8239836/Aaron.Zuhl.Navy.tests.txt)

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/EndlessSkyCommunity/endless-sky-assets/pull/10
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/216

### CODE REVIEW

**Review by EjoThims — APPROVED** [review]
Really did love the first set of changes, but these refinements are superb!

**Comment by Saugia** [comment]
The Rainmaker looks MUCH better. The head details for the Carrier does as well, and the new cockpits for it and the Cruiser, Frigate, and honestly especially the Lance are MUCH better as well. I know the block-y cockpit style of is is a bit odd, but before it was quite literally objects where now they look like both objects AND cockpit areas. 

The only remaining gripe I have is the *color/brightness* of the Carrier head still seems to stand out a bit, unlike the Cruiser where a good portion of the body is also that color/brightness. I'm not sure how that would be appropriately solved, though, but it's a fleeting design point amongst all the other good things happening here. Awesome stuff!

**Comment by Amazinite** [comment]
I'll get to this some time this week.

**Review by Amazinite — CHANGES_REQUESTED** [review]
Going to be comparing all these to the originals as opposed to the previous versions.

## Rainmaker

image

As I've mentioned before, the Rainmaker is definitely my favorite out of all the redesigns here, making it look like an actually formidable ship compared to the dinky light warship that it was before. My only suggested change for the image now is to cut down on the outer wings a bit; in enlargening the missile pods, you didn't shrink the wings and instead just pushed them out, making the ship not look a little stout. Perhaps change it so that you have more of a straight line along the edge of the ship here (ignoring the missile pod) as I have on the left side, or slope the wing a little more as I have on the right side.

I'm fine with the racing stripe on this one, and the colors are fine.

image

## Lance

image

I'd just remove the racing stripes around the cockpit. Other than that, I think this looks great.

image

## Combat Drone

image

I see that the combat drone isn't redone here, but I'll comment on it anyway. As has been the case elsewhere, you've shrunk the gun. I'd slightly increase the gun size so that it better matches the diameter of the old one. And going along with the idea of avoiding making the details too small, I'd change the segmented blocks of color around the edge of the drone into a single solid piece as was done on the original.

Color wise, the drone is now a lot more orange as opposed to the distinct red and yellow on the original. I'd say we could make the rear wings a more prominent solid yellow as was the case with the original, as right now the wings are gray with orange sections on the side that you can barely see from above, and the edge sections could perhaps be made more red. I'd also say ditch the colored sections on the gun.

I'm 50/50 on the racing stripes here. Up to you to keep or ditch them.

## Gunboat

image

My feedback on the Gunboat is basically the same as my feedback elsewhere: avoid the segmented colored sections and stick with more solid pieces, try and have more of a range of colors instead of just a general orange, ditch the racing stripes, and ditch the color on the guns.  The only thing specific to the Gunboat that I have is that I'm not really a fan of these inset wing seconds near the front. And the cockpit feels a little wonky to me, but I'd say we're fine to leave it.

image

## Frigate

image

Aside from the colors being mostly orange-ish, I don't really have much on the Frigate. This is getting to the size where the segmented sections aren't as much of an issue to have, and even the stripe around the cockpit area doesn't look too bad to me (although it may end up changing anyway to better match the removal of the stripes from other ships).

My only comment is that it looks like you might have gone a little overboard with the spray paint tool on the top wings during post processing since the gray areas around them are tinted orange (especially noticeable on the middle one).

image

## Cruiser

image

As with the Frigate, I don't really have much to say here; looks great, and I don't even feel like the colored rings on the guns are off. Although, also as with the Frigate, for the sake of consistency that may also need to change, along with the stripe around the cockpit. And in terms of lost features from the original, I was actually a fan of the antennae sticking out the front of the ship.

## Carrier

And as the ship sizes grow, my lazy background is revealed as me just opening these images with the file explorer behind them.
image

Hey, no more racing stripes anymore, but the segmented sections around the cockpit also seem weird to me. I don't really have any particular feedback on how to change them, though, and the rest of the segmented sections on the ship seem fine.

## Auxiliaries

image

Looks like these also aren't done here, but these need the same cockpit treatment that the rest of them got, and I'd also ditch the racing stripes on this one. You could perhaps also reintroduce the color to that rear middle fin; this has the same issue as the combat drone where the color is painted onto the side of the fins, making the color almost if not entirely invisible to see from top down.

**Comment by JanErikAhrens** [comment]
I'm gonna get to it as soon as possible, but just a few comments. The reason I didn't rework the Aux and Drone is because I'm actually not sure they really needed a rework to begin with. For the Aux I might still just add some more "polishing touches" to the original like beveling the wings, but for the Drone I actually went through some of the changes you suggested and the whole design basically started breaking down to the degree where I have to redesign half the thing anyway. As for this comment:
> My only comment is that it looks like you might have gone a little overboard with the spray paint tool on the top wings during post processing since the gray areas around them are tinted orange

That isn't the spray paint tool, it's actually bounce light from the fin. I might just try adjusting the material a bit but having such a huge brightly colored surface will always cause something like this.
Anyway, thank you so much for the lengthy response and I'll get to work very very soon.

**Comment by Anarchist2** [comment]
> having such a huge brightly colored surface will always cause something like this.

You could always just reduce light bounce count to zero.

**Comment by JanErikAhrens** [comment]
But the photorealism! No but fair enough, I can give that a shot.

**Review by Amazinite — CHANGES_REQUESTED** [review]
Looks like the high DPI PR only updated the thumbnails from the recent changes. I'd still also like to see changes to the combat drone and Auxiliary.

**Review by Amazinite — APPROVED** [review]

**Pull request merged**
