### PR TITLE
feat(balance): Give the Fetri'sei appropriate outfit, weapon and engine space for an interceptor

### PR DESCRIPTION
**Pull request by Quantumshark**
**Balance**

## Summary
Currently, the Fetri'sei, despite being an interceptor and clearly much smaller than the Maeri'het, has the same outfit, weapon and engine space as the Maeri'het, of which it actually uses very little.
This doesn't really matter at the moment, as there's no way to obtain a Fetri'sei in the base game or even to see its stats, but the current stats don't make sense, and this avoids any future issues if story or mechanics changes ever allow players to see these stats.

## Screenshots
Before:
image

After:
image

Size comparison with the Maeri:
image

## Testing Done
As part of getting the 'after' screenshot for the section above, loaded up the game with these changes and confirmed the outfit space didn't go negative.

## Save File
No vanilla save file can be used to test these changes, get an all content plugin.

### CODE REVIEW

**Review by beccabunny — APPROVED** [review]
Definitely makes a lot more sense than the current values. I think I had just copied the Maeri'het health at the time?

**Comment by Quantumshark** [comment]
> I think I had just copied the Maeri'het health at the time?

HP looks right, 2400/7200 shield/hull compared to the Maeri's 17600/23100

**Comment by beccabunny** [comment]
Oh, better then

**Comment by warp-core** [comment]
Should the energy capacity, generation, and heat generation not also be reduced? They look like they are also the same as what the Maeri'het has.

**Pull request merged**
