### PR TITLE
Bugfix selling jump drives to the unfettered

### PR DESCRIPTION
**Pull request by NPN26**
**Bug fix**

This PR addresses the bug described in issue #9902 

## Summary
Duplicated the story line to check if players has a hyperdrive installed already to prevent them from getting another hyperdrive. I haven't been able to test since I don't have a save file to check it.

## Performance Impact
N/A

### CODE REVIEW

**Comment by Hurleveur** [comment]
Thanks for getting to it but actually it isnt required to duplicate it, we can just have a branch that leads to 2 different action nodes

**Comment by warp-core** [comment]
I don't think making a second copy of these missions for this is a great approach.
You can probably use branches and actions within the conversation to only give the hyperdrive if one isn't already installed.
Regardless of how it is done, if a hyperdrive is not provided, the payment should have the fully depreciated price off a hyperdrive in addition to the base million credits.

Alternatively, the "outfit" node in GameAction could be expanded to support children that might specify where to try to put the outfit. Or to only install it if the player has fewer than a certain number of it.

**Comment by TomGoodIdea** [comment]
@NPN26 This PR has been waiting on you for 3 months. Do you want to update it or should we close it?

**Comment by TomGoodIdea** [comment]
unorphaning because of #10247

**Pull request closed without merging**
