### PR TITLE
Make void sprites drop void sprite parts

### PR DESCRIPTION
**Pull request by Quantumshark**
**Content**

This uses the flotsam chance attribute from #7942 

## Summary
Adds void sprite parts to the void sprites (also reduces the mass of the void sprite itself to match, so their handling is unaffected).
~~I think this should cause void sprites to sometimes drop void sprite parts when killed, though I may be wrong about that.~~
Now uses flotsam chance from #7942, so they will drop correctly once #7942 is merged.
I'd be open to any suggestions on what the exact numbers should be. Currently, average drops are 10 from an adult void sprite and 5 from an infant.

I figured the inside of a void sprite seems like a sensible place for void sprite parts to be.

## Testing Done
Checked that the new flotsam sprite was working properly by taking off with void sprite parts in cargo and dumping them.
image
Shot some void sprites, confirmed that they are correctly dropping void sprite parts.

See comments below for updated sprites (not using the Mouthparts sprite).

## Artwork Checklist
 - [x] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
 - [x] I created a PR to the [endless-sky-assets repo](https://github.com/endless-sky/endless-sky-assets) with the necessary image, blend, and texture assets: https://github.com/endless-sky/endless-sky-assets/pull/115
 - [x] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: https://github.com/endless-sky/endless-sky-high-dpi/pull/338

### CODE REVIEW

**Comment by warp-core** [comment]
I have not checked, but I think the items a "ship" may drop as flotsam on destruction are actually basd on what it had in its cargo, not what outfits were installed.

So, in order to achieve the desired effect, you would want to add the void sprite parts outfitter to the Void Sprite fleet definition (as is done for some Korath fleets in the Remnant Cognizance missions), this would, however, reduce their capacity to hold mined materials. And, I don't think a ship that doesn't have much cargo space left will actually mine, which is perhaps undesirable in this case.

**Comment by Quantumshark** [comment]
I've frequently picked up ammunition after ships were destroyed, I don't know if that's a specific exception or if the ships in question had ammunition in their cargo.

**Comment by warp-core** [comment]
Outfits in the "Ammunition" category are indeed an exception.
https://github.com/endless-sky/endless-sky/blob/a5de9eb8ab8d0f1c48bea668fe06da0f81dd2fca/source/Ship.cpp#L1576-L1588

**Comment by Quantumshark** [comment]
Perhaps we should implement an attribute that allows designation of other outfits to survive after a ship is destroyed, so you could have something like "flotsam chance" 0.15 or similar.

**Comment by Zitchas** [comment]
I like the idea of this happening, but I'm not sure the mechanics of it work. Void Sprite Parts as ammunition also seems... Odd.

**Comment by Quantumshark** [comment]
Another solution would be to have outfits have a chance to drop in flotsam if they're below a particular size (say, mass <= 5, but either disallow it for outfits with 0 mass or add an attribute which prevents an outfit from dropping in flotsam since otherwise mouthparts would drop) instead of handling it by category.
Alternatively, have outfits have a chance to drop if their mass is below 5, and resize the mouthparts so that instead of having 0 mass they have a mass of >5.

**Comment by warp-core** [comment]
We should probably have an issue for discussing changes to the way flotsam is generated upon a ship's destruction.

**Comment by warp-core** [comment]
It might be possible to define `cargo` in the ship definition and put the Void Sprite Parts there, which should achieve the desired result.

**Review by warp-core — APPROVED** [review]
This won't currently actually do anything, but once #7942 is done and merged, it should work as intended. ~~Unless the attribute name is changes.~~

The only question is what the expected number of parts per Sprite should be. As is, this will be 5 for the infants and 10 for the big ones.
Are these something we want to drop so frequently?
Should it be something most Sprites drop a few of, but some won't?
Should it be something that is rarely dropped?

I have no strong opinions on this matter; I'm not planning on going around murdering Void Sprites to see what they drop, so I only expect to encounter this myself when I'm near a Korath ship that happens to kill a Void Sprite, either on purpose or as collateral damage. My experience generally doesn't involve actually seeing Korath killing Void Sprites too often (it's usually happening on the other side of the system, or I've killed the Korath already) so a relatively high drop rate seems reasonable in that regard.

~~Unless someone feels differently about the drop rate, can we merge this to get the PR count down?~~

**Comment by Quantumshark** [comment]
Currently the void sprite parts will (with #7942) drop in the boxes that other dropped outfits are in, which would look wrong. I would like to give them a proper flotsam sprite before this is merged.
As far as changing the average number dropped, ideally I'd like to hear from Zitchas before this is merged, as this is directly connected to the Remnant campaign - depending on the drop rates for void sprite parts, the implied number of Void Sprites the Korath are harvesting would be different.

**Comment by Quantumshark** [comment]
Added a flotsam sprite for the void sprite parts. Currently, it is just a resize of the Mouthparts image (which is also used as the outfit image for the void sprite parts) from 100x100 to 30x30

**Review by Zitchas — APPROVED** [review]
These quantities look good. Thanks!

**Comment by Quantumshark** [comment]
As it has been expressed that the flotsam sprite here is unsuitable, I am going to close this PR. I don't expect to have a better flotsam sprite to use in the forseeable future, so this PR is just taking up space unnecessarily.

If anyone else does have a better flotsam sprite, they can either send it to me (in which case I will reopen this PR with the new sprite) or make their own PR and implement it themself, reusing the content of this PR if they want to.

**Comment by Saugia** [comment]
Because this is an overall desired and welcomed PR, I'm reopening it. There's no reason to close it and reopen it later as that's not really solving a space issue. 

I suggest talking to @beccabunny or @GefullteTaubenbrust2 for making a simple flotsam sprite. I think one of them has even already previously made one too (though I still feel a flotsam sprite for this should be a bit more abstract).

**Comment by Saugia** [comment]
I'll try to make one myself.

**Comment by Saugia** [comment]
I'm going to PR to your branch later today with a flotsam sprite as well as an outfit sprite. I'll open 2x and Asset PR's when I do so.

**Comment by Saugia** [comment]
https://github.com/Quantumshark/endless-sky/pull/1 @Quantumshark Here's the PR to your branch. You just have to run the tests first, wait for everything to go green, then Squash Merge.

**Review by Zitchas — APPROVED** [review]
The new artwork looks... like the blob it is supposed to be?

**Comment by Saugia** [comment]
@Quantumshark Can you remove the mouthpart sprite labeled "Void Sprite Parts"?

**Review by beccabunny — APPROVED** [review]
Nicely done

**Pull request merged**
