### PR TITLE
feat(balance): Reduce the turn rate and burn DPS of the Inferno and Blaze-pike

### PR DESCRIPTION
**Pull request by Quantumshark**
**Balance:**

## Summary
Both turrets' traverse is reduced by .7 deg/frame, equivalent to 42 deg/sec. This represents a 25% reduction for the Blaze-pike, and a 35% reduction for the Inferno.
The Blaze-Pike loses .05 burn damage per frame, equivalent to 300 heat/sec, a reduction of 11% to its burn damage, or about 8% to its total heat application. The Inferno loses .15 burn damage per frame, equivalent to 900 heat/sec, a reduction of about 17% to its burn damage, or 12.5% to its total heat application.

## Reasoning
This is arguably two distinct changes with distinct reasonings, so I'm open to separating it into two PRs if that's desired.

The first issue is that the two weapons have been noted to have very high effective heat DPS, causing balance issues in a not dissimilar issue to the Flamethrower. As has been noted in various places, including #9470, attempts to resolve this by tweaking the mechanics of heat (#8968 and #7042) have had unintended balance side effects elsewhere, and tweaking overperforming weapons (as was done in #7606) is a better approach.
The idea of constructive interference with the multiple fire-lances is maintained - the burn damage per frame is now .15 per fire-lance for the single fire-lance, .2 per fire lance for the twin fire-lances of the Blaze-Pike, and .25 per fire-lance for the triple fire-lances of the Inferno. There was more room to nerf the burn damage than the heat damage while retaining that aspect, which is why I opted to do so.

The second issue is that both weapons have very high traverse rates for their size, particularly the Inferno. Hence, they are reduced here.

## Save File
Don't have a suitable one currently, but could probably put one together if desired.

### CODE REVIEW

**Comment by EjoThims** [comment]
This may well be a valid nerf, but especially without even further reduction of the flamethrower, all it's really doing is making them an even worse alternative.

7200 pre-nerf to 6300 post-nerf combined heat and burn DPS for 77 tons for the Inferno versus 9000 direct heat DPS for 9 tons.

And while flamethrower does use fuel, it's also a much lower tech level.

I'm starting to think the flamethrower's usage in balancing FW fleet battles is hindering the balance of both other heat focused weapon -and- our entire heat system.

**Comment by Hecter94** [comment]
The flamethrower's usage as a balancing metric in the FW campaign is not a consideration for balancing the flamethrower as a weapon and certainly not the basis of all other heat weapons and the entire heat system. 
Suppose the flamethrower needs to be nerfed to half-effectiveness to balance heat weapons in general, and that ends up unbalancing the FW campaign. In that case, adding a couple more flamethrower-equipped ships to balance it out specifically for that campaign is a very easy and simple fix.

**Comment by AvianGeneticist** [comment]
> This may well be a valid nerf, but especially without even further reduction of the flamethrower, all it's really doing is making them an even worse alternative.
> 
> 7200 pre-nerf to 6300 post-nerf combined heat and burn DPS for 77 tons for the Inferno versus 9000 direct heat DPS for 9 tons.
> 
> And while flamethrower does use fuel, it's also a much lower tech level.
> 
> I'm starting to think the flamethrower's usage in balancing FW fleet battles is hindering the balance of both other heat focused weapon -and- our entire heat system, but how exactly to address that should also almost certainly be a separate PR.

It's worth noting that the flamethrower has received a far more impactful nerf in the form of Damage Dropoff. Its effectiveness starts to fall *as soon as* it splits, reducing the weapon's DPS to half as it approaches ~200 (198) units travelled, meaning it only does 4500 heat DPS at ranges shorter than any other offensive weapon in the game (except the Guile). In contrast, the Firelance and its derivatives retain full damage out to their maximum ranges (390, 450, and 550) while also not costing fuel. Though it can be argued the size is an appropriate detriment, there's still very little to argue that the Firelance family of weapons isn't a good challenger to the Flamethrower's throne.

**Comment by EjoThims** [comment]
The overlap between ships both fast and agile enough to maximize flamethrower damage and with the gun port focus to take advantage of stacking them is generally high, though, so the damage dropoff doesn't interview as much in practice with the flamethrowers place on the heat damage throne as it seems to on paper.

And that spot just really should be held by the much larger and more advanced weapon, even if that weapon -also- is currently overturned against the rest of the weaponized heat line.

**Comment by EjoThims** [comment]
>Suppose the flamethrower needs to be nerfed to half-effectiveness to balance heat weapons in general, and that ends up unbalancing the FW campaign. In that case, adding a couple more flamethrower-equipped ships to balance it out specifically for that campaign is a very easy and simple fix.

Precisely, but so far, the response has been instead to be overly conservative in changes to the flamethrower, making it less overpowered but still not proper balanced against other heat weapons.

Changes to fleet compositions instead is exactly the kind of thing I would like to see instead of continuing to keep flamethrowers unbalanced enough to  have they impact they do without changing those compositions.

**Review by Hurleveur — APPROVED** [review]
Just hoping in to say I'm personally for this change, but I am no balance reviewer
Unlike the flamethrowers these weapons do a bunch of damage and take less slots. Also consider that the flamethrower is a story unlock - what mostly bothered me with these weapons however is notably how trivial they make the future uhai duels, and just how easily you get overheated. Since rebalancing heat weapons and adding cooling seems to be the course of action to deal with the overheating imbalance, looking at each of these weapons invidually makes sense. I also think that most turrets have too much turning and beams are too meta so thats a change in the good direction, too.
About the flamthrower I think we should make it cost more fuel but thats a subject for another PR I'd say

**Comment by Quantumshark** [comment]
I can have a look at PRing another nerf for the Flamethrower if it's still agreed to be too strong.

**Review by EjoThims — APPROVED** [review]
Alongside the flamethrower changes, I think this is probably a good direction to take the top end of the current heat damage ecosystem, whether or not it still needs later adjustment as we figure out a more effective overall system.

**Review by Saugia — APPROVED** [review]

**Pull request merged**
