### PR TITLE
Fix awkward use of "world" in Navy hail

### PR DESCRIPTION
**Pull request by Amazinite**
I feel like this would be a good fix to replace the use of the word "world" in one of the Navy hails.

I changed "need" to "want" as well because that was the original saying:
https://www.loc.gov/exhibits/treasures/images/tlc0090.jpg

### CODE REVIEW

**Comment by Amazinite** [comment]
My thought process begin leaving out the far north is that it's made up to be a pretty lawless and pirate ridden area with those three pirate planets, so I don't really think it would make sense for the Navy to advertise "Touring the Far North!"

**Comment by Gkramme** [comment]
#1135

**Comment by Amazinite** [comment]
I know, I just thought it would be better to do it this way.

**Comment by Amazinite** [comment]
If you want, I could merge this into your branch instead of you having to remove your change to it.

**Comment by endless-sky** [comment]
This seems like a good approach for the Navy - eliminating some of the awkward combinations in the original, which the other PR would still allow - so I'm merging it in.

**Pull request merged**
