### PR TITLE
[content] adding External + Pressurized Fuel Pods

### PR DESCRIPTION
**Pull request by Taejang**
**Feature:** This PR implements the feature request detailed and discussed in [issue #6388](https://github.com/endless-sky/endless-sky/issues/6388)

## Feature Details
Two new fuel pods added, one in Wanderer space and one in human space. Both need new thumbnails and are using the original fuel pod thumbnail as a placeholder.

Ideally, the external fuel pod could be jettisoned after use to remove the drag and negative hull values, at the cost of the outfit itself. This would need new code to accomplish.

The external fuel pod stats should be reviewed. I'm unsure if my use of "drag" and "hull" are correct here.

### CODE REVIEW

**Comment by Taejang** [comment]
The external fuel pod contains these:
"drag" +.1
"hull" -200

Does this syntax work? Do these properties work when attached to an outfit?

I also came across "fuel protection" on the Coalition fuel pod, and am curious what it does. It is _not_ included in the outfits for this PR.

**Comment by Ferociousfeind** [comment]
Generally, for small questions and idle chatter, try the Discord. For the record here:
Outfits function (currently) by adding or removing amounts in attributes from a ship's pile. In the code, these are all under attributes.Get("attribute names"). We also have access to the ship's bare attributes, the ones on the ship if it had no outfits on, under baseAttributes.Get("attribute names").

To add an attribute, you'd use something like `"hull" 50`, while to remove an attribute you'd use `"hull" -50`. Your use of `"hull" -200` works, but your `"drag" +.1` does not. Think of it more like adding by default, and you can use `-` to negate the value. 

Attributes that haven't been defined are by default 0. No setting via outfits, no need to explicitly call that you're adding rather than setting, there is only adding.

**Comment by Zitchas** [comment]
And as for `"fuel protection"`, that is detailed in the "Creating Outfits" page of the wiki:
https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits

That being said, the general consensus is, I think, that we don't want human space to have too much in terms of special damages, and thus also not the corresponding protections. There are several reasons for this, but the two predominant ones are:
1. We want to keep human space relatively simple and avoid overwhelming people with options.
2. We want to have more opportunities to have races like the Hai in the galaxy who have different combat strengths and damage types, which allows them to be only somewhat more powerful than humanity, but have significantly different weapons that aren't just "blasters or lasers with a different graphic/sound/description."

**Comment by Pointedstick** [comment]
Agreed. Also this isn't merge-ready without sprites. It's probably best to wait until you've got those before opening a PR. Better luck next time!

**Pull request closed without merging**
