### PR TITLE
feat(mechanics): Save ship explosion effects in alphabetic order to savegame.

### PR DESCRIPTION
**Pull request by petervdmeer**
**Feature:** This PR implements part of the feature request detailed and discussed in issue #5171

## Feature Details
This PR adds a temporary map in the function that saves the ship-explosion-effects to a save-game file to ensure that the explosion-effectss are saved in alphabetical order.

## UI Screenshots
N/A

## Usage Examples
N/A, the game automatically applies the ordering when saving.

## Testing Done
I started the game with an existing save-game, pressed depart and then closed the game. The explosion effects in the save-game before and after starting where the same (but the effects after starting were sorted in alphabetical order).

## Performance Impact
The function that saves the game will take a little bit more time and temporary uses a little bit more memory (since it needs to build up the temporary maps). But ships have small lists of explosion effects, so the impact should be very minimal.
Saving the game is not performance critical code.

### CODE REVIEW

**Review by tehhowch — CHANGES_REQUESTED** [review]
Per discussion on discord, please implement a template method that will write the items of a given container in sorted order, and replace these calls with calls to that template method. You should then apply this method to the previous PR for sorting outfits, and any other items that should be written in sorted manner, to resolve #5171 for ships

**Comment by petervdmeer** [comment]
Converted to draft; conversion to template method needs a bit more work.

**Comment by petervdmeer** [comment]
> Per discussion on discord, please implement a template method that will write the items of a given container in sorted order, and replace these calls with calls to that template method.

Done. the outfits, explosions and final explosions now all use the template method. Those are all the items in ships that I know need to be sorted.

**Comment by petervdmeer** [comment]
Closing as duplicate of #5333

**Pull request closed without merging**
