### PR TITLE
Created Weapons for the Monads, a new species

### PR DESCRIPTION
**Pull request by InfiniteDonuts**
Created some weapons for the Monads, a robotic species I plan to add over the course of my next few pulls.

Added these weapons:
- Energy Lance
- Energy Lance Turret
- Energy Minelayer
- Energy Shadow Generator
- Energy Shadow Turret
- Energy Lens System

### CODE REVIEW

**Comment by InfiniteDonuts** [comment]
Note: For some reason some of the checks failed, saying I had not specified a "turret turn" attribute, even after I fixed it.

**Comment by MasterOfGrey** [comment]
I can scarcely begin to enumerate my concerns with this, but I will start with these:

- If you want to add a species to the main game, communication and collaboration with the other content creators on the discord is pretty much essential.
- You don't start by submitting the outfits, start with the map and the concepts and the world design.
- Your pet species does not need a superweapon.
- Your random species weapons need to not be added to some other in-game species outfitters.
- Outfits come in the context of ships, ships come in the context of balance and world-building.
- Anything that ties in the Drak is going to require direct approval from Amazinite, likely *before* you write it.
- Who, What, When, Where, Why, How... robots?

**Comment by Ferociousfeind** [comment]
I think you'll want to join the ES discord. We have a bunch of brilliant minds willing to provide some outside perspectives which will help you change your in-development aliens more quickly and for the better. I think everyone would be less uneasy if everyone was in contact with everyone else and we all developed the ideas fully before trying to implement them into the game.

Communication is key.

**Comment by Ferociousfeind** [comment]
(yeah what masterofgrey said)

**Comment by W1zrad** [comment]
I thought a general outline of how new species and other major content changes are often added might be helpful for you:
1. Have an idea, come up with a basic premise for what you want to do.
2. Workshop the idea over on the [Discord server](https://discord.gg/ZeuASSx) until you get to a point where a reasonable amount of people like the idea and don't have serious concerns about what content you'd be introducing.
3. Pull everything together (map, pictures for ships and outfits, missions, etc.) and create a plugin so others can try out the content in-game.
4. Get feedback on the plugin and renovate it accordingly.
5. Eventually get to the point where everything's polished enough to create a PR here.

I've never done this myself, but based on what I've heard this is the general process. Usually, the content PRed here are things that have been reasonably tested, workshopped, and changed - late stages of development, not the very beginning. It seems like you've sort of jumped from the first step to the last step here. Hope this helps!

**Comment by InfiniteDonuts** [comment]
I have answers to all your concerns:

- Yes, I added the Monad outfits to the Hai outfitters for testing reasons, so I could have easy access to the weapons. Thank you for pointing that out.
- The Energy Lens System is just for concepts, I plan to make it *much* less powerful, perhaps on par with the Pug Gridfire Turret or the Quarg Skylance.
- I will talk to Amazinite about including something about the Drak once I have polished up the idea.
- I did not know Endless Sky had a discord server! (I have never done Discord before!).
- The Monads are supposed to be a robotic species, a runaway experiment by a race long gone. The single purpose of their existence, or so they say, is to perfect engineering in every way.

**Comment by Amazinite** [comment]
For you (and for anyone looking to add new faction), take a look at #4716 for an example of what is necessary to adding a new faction. We need systems, ships, outfits, images for everything, names for everything, some idea of the story of the faction that is in some way unique when compared to other factions in game already while also being exciting, and at least a first contact in terms of missions. 

> The Monads are supposed to be a robotic species, a runaway experiment by a race long gone.

So similar to the Kor Sestor or Mereti (robotic faction), the Ka'het (runaway experiment of a long gone race), or the Sleepers (both #5266) that someone tried to add recently? Might want to go back to the drawing board on that one.

**Comment by InfiniteDonuts** [comment]
Thanks, @Amazinite. My idea was to test the weapons, see how they worked, and then add new sprites, new effects, and planets.

Sorry for trying to cram a pull request in without being prepared, that's just me.

Also, I had an idea to put the Monads in the second galaxy (the one that you can visit via the wormhole in the Deneb system) and have the Pug try to subjugate them. But I'll create a plugin first and then get some ideas from the Discord.

Additionally, this is my first time contributing to a big project (I like programming but I'm a Git newbie)

**Comment by Zitchas** [comment]
We like seeing new content - and having new people join brings fresh perspectives of ideas and problems to the table. W1zrad's five-point process is a really good summary of how to develop a new race to fit into Endless-Sky.

That being said, I'd like to emphasize the "make a plug-in" part. Endless-Sky was built to be added to. Plug-ins aren't "just" an after thought, but rather a concrete way to let people make stuff for themselves and share it with the community. While plug-ins definitely can be merged into the game at a later point, they are also ways to let creators with their own vision that might differ from the Devs create content for ES that is equally valid. Stuff that goes into vanilla has to be put through the wringer in terms of story, balance and quality. There's a lot of stuff that would make perfectly good and enjoyable plug-ins that will get blocked from becoming vanilla. 

Build all your stuff into a plug-in, upload it somewhere (your own repository on GitHub would be ideal), and then send us a link to it on discord. There are a few plug-in repositories that store links to the various plug-ins, and it can be included on those.

Also, just a note on power levels. Endless Sky uses a "Tier" system to describe the relative power level of the the factions. These are *not* canonical or hard-and-fast rules, just aproximations for how to think of the different factions. Factions have areas of strength and weakness where they can be significantly stronger or weaker than their number might indicate.

Humans - tier 1 
Hai - roughly 1.25 
Coalition - tier 1.5 
Ka'het - tier 2
Korath automata - tier 2 
Korath Exiles - tier 2 (historically may have been as high as tier 2.5, but have degraded due to war, exile, and lack of resources)
Wanderers - tier 2.25
Heliarchs - tier 2.5 (with tier 1.5 civilian outfits) 
Quarg - tier 3 (nominally) 
Drak - tier 4 (nominally) 
Pug - tier 4 (nominally) They field ships aimed at being somewhat superior to whoever they are facing, but only a bit. So we currently have Tier 1 pug and Tier 3 pug, but despite using weaker ships, they are at least tier 3 and some claims point to them being tier 4.
Remnant - inconsistent due to reverse engineered tech

Note: "Nominally" means they are subject to being balanced once stories involving them in a significant capacity and/or other groups that can deal with. Currently, tier 3 basically is defined as "More powerful than everything currently involved in stories" and tier 4 basically translates to "even more powerful than those."

In terms of development it is generally considered that the main place where we need more ships is around the Tier 1.5 to 2 range. While there are lots of options in human space, the range for player options as they leave human space drops drastically. At this point in the story, we don't need factions that can challenge the Quarg, Pug, or Drak, as these three factions are basically just story telling elements that will be adjusted upwards in strength as needed and the story progresses. As such, it is recommended to balance things against stable factions. Humanity and the Hai are the two most stable factions, currently (Stable, as in "least likely to change dramatically as the game is improved upon"), but Wanderers and Coalition are fairly stable at this point.

**Pull request closed without merging**
